### ISSUE TITLE
Build for raspberry Pi tips

### ISSUE THREAD

**Issue by liabixiaoxin** [Tencent/ncnn#1000]
Hi,

I think current ```CMakeLists.txt``` only applies for raspberry pi **32bit** OS, such as the official **raspbian**.  However, when compiling in a **64bit** OS, such flags are enabled by default and will cause errors during the compilation step.

```bash
add_definitions(-mfpu=neon)
add_definitions(-mfloat-abi=hard)
```

Probably a ```CMAKE_SYSTEM_PROCESSOR``` can be set as a flag to determine the OS mode.

P.S. I'm using **Manjaro with LXQT desktop** btw.

Thanks,
Eddie

**Comment by nihui** [comment]
we handle the compiler flags in cmake toolchain file now
Thanks
