### ISSUE TITLE
register them as no-op的这段代码应该放在哪？

### ISSUE THREAD

**Issue by zys1994** [Tencent/ncnn#1002]
```
class Noop : public ncnn::Layer {};
DEFINE_LAYER_CREATOR(Noop)

net.register_custom_layer("LinearRegressionOutput", Noop_layer_creator);
net.register_custom_layer("MAERegressionOutput", Noop_layer_creator);
```
如果我需要不理会LinearRegressionOutput这个层，关于register them as no-op的这段代码应该放在哪？

**Comment by nihui** [comment]
参考这的用法
https://github.com/Tencent/ncnn/blob/37e150162ad8bc083019b9801d9f0edfc74e4560/examples/mobilenetv2ssdlite.cpp#L45

**Comment by zys1994** [comment]
十分感谢, 看的很明白。  二群的密码现在改成什么啦？我用【卷卷卷卷卷】申请提示错误
