### ISSUE TITLE
可以编译出Linux x86的so库吗

### ISSUE THREAD

**Issue by YuGongCharley** [Tencent/ncnn#1003]
在安卓上用ncnn写了c++的底层和jni部分，突然说要上服务器，再重新开发可能来不及，想问一下可不可以编译一个so库可以在x86 linux的pc上运行，运行速度暂时不用考虑。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux-x86
参考这个编译静态库使用
