### ISSUE TITLE
显卡预测结果与CPU不一致

### ISSUE THREAD

**Issue by veepersgit** [Tencent/ncnn#1004]
在多个显卡上测试过，其中较老的显卡（如：1070，TITAN X）预测结果与CPU一致，但较新的显卡如（1080,1080TI）需要关掉16fp存储以及int8存储才会与CPU预测一致。现在比较关心嵌入式设备，在TX2上，关掉只能缩减与CPU预测之间的误差，但误差还会有，请问有没有更好的解决方案呢？

**Comment by nihui** [comment]
1 升级最新的驱动
2 ncnn git 代码时常会修些 bug，也可以更新看看
3 通常 fp16 storage 不会引起很大误差，fp16 arithmetic 没有测试过，可能会有问题
4 发现结果不对，extract 前面几层的 blob 检查，找出是哪个 layer 导致的

**Comment by nihui** [comment]
```
ncnn::Net net;
net.opt.use_fp16_packed = false;
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
net.opt.use_int8_storage = false;
net.opt.use_int8_arithmetic = false;
```
