### ISSUE TITLE
量化后损失严重，准确率太低。

### ISSUE THREAD

**Issue by dancingpipi** [Tencent/ncnn#1005]
一个mobilenetv2，1000类，使用了2000张训练图片进行量化，每一个类别两张图片。
使用1000张图片作为测试集，以FP32跑出来的结果作为ground truth，在PC上测试INT8的准确率：
准确率为 76.7%，这个是不是太低了，问下是什么原因啊？还能怎么做来提高INT8的准确率

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
20210507版本大幅优化int8推理速度，建议更新
