### ISSUE TITLE
ncnn 是否有类似caffe::caffe_cpu_dot 的计算？

### ISSUE THREAD

**Issue by zys1994** [Tencent/ncnn#1007]
```
float dot_12 = caffe::caffe_cpu_dot(faceFeat1->featSize, faceFeat1->pFeat, faceFeat2->pFeat);
```
ncnn 是否有类似caffe::caffe_cpu_dot 的计算

**Comment by nihui** [comment]
elementwise prod
binaryop mul

**Comment by hgzry2015** [comment]
> elementwise prod
> binaryop mul
    a = torch.rand(1, 1, 3, 4)
    c1 = 1 - a
    c2 = torch.sub(1, a)
类似这种相减，转换后网络也是错误的，
