### ISSUE TITLE
Elementwisesum not supported yet 

### ISSUE THREAD

**Issue by HaoLiuHust** [Tencent/ncnn#1008]
when I use mxnet2ncnn tool to convert my model to ncnn, this error occur

**Comment by HaoLiuHust** [comment]
have plan to support it?

**Comment by nihui** [comment]
请提供下 json 文件中 Elementwisesum 相关的内容行

**Comment by HaoLiuHust** [comment]
{
      "op": "ElementWiseSum", 
      "name": "res_5_block1_conv_proj_conv2d-oct-sum-l", 
      "attrs": {"num_args": "2"}, 
      "inputs": [[1664, 0, 0], [1666, 0, 0]]
    },

**Comment by HaoLiuHust** [comment]
@nihui will be supported?

**Comment by nihui** [comment]
see https://github.com/Tencent/ncnn/commit/af950819cd08a5a5e081f0a4e1afa5aba6cbe9bd

**Comment by HaoLiuHust** [comment]
Thank you very much
