### ISSUE TITLE
example build error, tools build error

### ISSUE THREAD

**Issue by linxueya** [Tencent/ncnn#1009]
example：
/home/user/ncnn-master/examples/fasterrcnn.cpp: In function ‘int detect_fasterrcnn(const cv::Mat&, std::vector<Object>&)’:
/home/user/ncnn-master/examples/fasterrcnn.cpp:119:55: error: invalid conversion from ‘const char*’ to ‘const unsigned char*’ [-fpermissive]
     fasterrcnn.load_param("ZF_faster_rcnn_final.proto");
                                                       ^
In file included from /home/user/ncnn-master/examples/fasterrcnn.cpp:10:0:
/home/user/ncnn-master/examples/../src/net.h:70:9: note:   initializing argument 1 of ‘int ncnn::Net::load_param(const unsigned char*)’
     int load_param(const unsigned char* mem);

tools：
/home/user/ncnn-master/tools/ncnnoptimize.cpp: In member function ‘int NetOptimize::fuse_batchnorm_scale()’:
/home/user/ncnn-master/tools/ncnnoptimize.cpp:115:24: error: ‘class ncnn::Layer’ has no member named ‘type’
         if (layers[i]->type != "BatchNorm")

**Comment by nihui** [comment]
try upgrading cmake > 3.10
drop build directory entirely, re-run cmake
https://github.com/Tencent/ncnn/wiki/how-to-build

**Comment by linxueya** [comment]
my cmake version is 3.14.4. I have completed the "build" for ncnn, I'm trying to compiling a demo in the "example", but the compilation keeps going wrong.

**Comment by nihui** [comment]
open your platform.h in build directory
make sure the macro NCNN_STDIO and NCNN_STRING defined to 1

**Comment by nihui** [comment]
feel free to reopen this issue if it is still not resolved
