### ISSUE TITLE
文档应该更完善一些

### ISSUE THREAD

**Issue by look-recognize** [Tencent/ncnn#1013]
一点建议：文档应该更完善一些，方便使用者理解。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet

大部分文档在wiki上 https://github.com/Tencent/ncnn/wiki
