### ISSUE TITLE
Convolution results not right in some cases

### ISSUE THREAD

**Issue by rocketbear** [Tencent/ncnn#1014]
Currently I am running ncnn on x86 platform, without vulkan.
For a convolution layer with kernel=3, padding=1, stride=2, it seems that the result is wrong when the output size (w * h) is not multiple of 4.

Following is content of the param file I tested with:
7767517
2 2
Input            data                             0 1 data
Convolution      conv2_fwd                        1 1 data conv2_fwd 0=4 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 5=1 6=108

The test results are as follows:
Input h=16, w=16, output h=8, w=8: Correct.
Input h=17, w=16, output h=9, w=8: Correct.
Input h=18, w=16, output h=9, w=8: Correct.
Input h=18, w=17, output h=9, w=9: Wrong.
Input h=18, w=18, output h=9, w=9: Wrong.
Input h=18, w=19, output h=9, w=10: Wrong.
Input h=18, w=20, output h=9, w=10: Wrong.
Input h=18, w=22, output h=9, w=11: Wrong.
Input h=18, w=24, output h=9, w=12: Correct.
Input h=20, w=20, output h=10, w=10: Correct.
Input h=22, w=20, output h=11, w=10: Wrong.
Input h=21, w=24, output h=11, w=12: Correct.
Input h=22, w=24, output h=11, w=12: Correct.
Input h=23, w=24, output h=12, w=12: Correct.

I have not verify if the same problem happens for arm version yet.

**Comment by nihui** [comment]
mat data may not be continuous.
Use Mat::channel to access
