### ISSUE TITLE
MobileNetV3

### ISSUE THREAD

**Issue by excllent123** [Tencent/ncnn#1015]
Has  anyone  port  MobileNetV3 to ncnn  ?

**Comment by soham24** [comment]
@excllent123 mobilenet3 pytorch-->onnx-->ncnn 
is handy option

**Comment by excllent123** [comment]
@soham24 Can you share how to do it ?   
I implement MobileNetV3  based on  https://github.com/xiaolai-sqlai/mobilenetv3
MobileNetV2  is  right,but V3  is wrong

**Comment by soham24** [comment]
What errors you are getting @excllent123 
is this solved?

**Comment by excllent123** [comment]
It seems that  hswitch/hsigmod is not supported @soham24

**Comment by soham24** [comment]
@excllent123 
 you are getting error here
 pytorch-->onnx 
or
onnx-->ncnn

**Comment by excllent123** [comment]
onnx-->ncnn @soham24

**Comment by soham24** [comment]
@excllent123  have you tried https://github.com/daquexian/onnx-simplifier 
and then to nccn

**Comment by excllent123** [comment]
Yes,After using onnx-simplifier,  there  still two error

**Comment by soham24** [comment]
Ohh :( I hope ncnn guys will fix this asap

**Comment by excllent123** [comment]
https://blog.csdn.net/hmzjwhmzjw/article/details/94027816

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
