### ISSUE TITLE
ncnn windows Debug版本进行nmake的时候出现问题(VS2013和VS2019都已测试)

### ISSUE THREAD

**Issue by Ason93** [Tencent/ncnn#1016]
ncnn windows Debug版本进行nmake的时候出现问题。
安装的指令如下：
cd <protobuf-root-dir>
mkdir build-vs2013-debug
cd build-vs2013-debug
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%cd%/install -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF ../cmake
nmake
nmake install

cd <ncnn-root-dir>
mkdir -p build-vs2013-debug
cd build-vs2013-debug
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%cd%/install -DProtobuf_INCLUDE_DIR=C:/artosyn/libncnn/protobuf-3.4.0/build-vs2013-debug/install/include -DProtobuf_LIBRARIES=C:/artosyn/libncnn/protobuf-3.4.0/build-vs2013-debug/install/lib/libprotobuf.lib -DProtobuf_PROTOC_EXECUTABLE=C:/artosyn/libncnn/protobuf-3.4.0/build-vs2013-debug/install/bin/protoc.exe -DNCNN_VULKAN=OFF ..
nmake
nmake install

报错如下:
......................
[ 91%] Building CXX object tools/caffe/CMakeFiles/caffe2ncnn.dir/caffe2ncnn.cpp.
obj
caffe2ncnn.cpp
C:\artosyn\libncnn\protobuf-3.4.0\build-vs2013-debug\install\include\google/prot
obuf/io/coded_stream.h(870) : warning C4800: “google::protobuf::internal::Atomi
cWord”: 将值强制为布尔值“true”或“false”(性能警告)
C:\artosyn\libncnn\protobuf-3.4.0\build-vs2013-debug\install\include\google/prot
obuf/io/coded_stream.h(874) : warning C4800: “google::protobuf::internal::Atomi
c64”: 将值强制为布尔值“true”或“false”(性能警告)
C:\artosyn\libncnn\protobuf-3.4.0\build-vs2013-debug\install\include\google/prot
obuf/generated_message_util.h(160) : warning C4800: “const google::protobuf::ui
nt32”: 将值强制为布尔值“true”或“false”(性能警告)
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(106) : warning C4244: “=”:
从“double”转换到“float”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(107) : warning C4244: “=”:
从“double”转换到“float”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(114) : warning C4244: “retur
n”: 从“float”转换到“signed char”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(218) : warning C4267: “初始
化”: 从“size_t”转换到“int”，可能丢失数据
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\algorithm(4141) :
 warning C4244: “参数”: 从“int”转换到“const float”，可能丢失数据
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\INCLUDE\algorithm(4141) :
 warning C4244: “参数”: 从“size_t”转换到“const float”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(268) : warning C4244: “=”:
从“const float”转换到“size_t”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(277) : warning C4244: “参数
”: 从“int”转换到“const float”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(277) : warning C4244: “参数
”: 从“size_t”转换到“const float”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(277) : warning C4244: “=”:
从“const float”转换到“size_t”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(278) : warning C4267: “参数
”: 从“size_t”转换到“const unsigned char”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(764) : warning C4267: “初始
化”: 从“size_t”转换到“int”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(994) : warning C4267: “初始
化”: 从“size_t”转换到“int”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(1106) : warning C4267: “初始
化”: 从“size_t”转换到“int”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(1219) : warning C4267: “初始
化”: 从“size_t”转换到“int”，可能丢失数据
C:\artosyn\libncnn\ncnn\tools\caffe\caffe2ncnn.cpp(1475) : warning C4305: “初始
化”: 从“double”到“float”截断
[ 92%] Building CXX object tools/caffe/CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.obj

caffe.pb.cc
C:\artosyn\libncnn\protobuf-3.4.0\build-vs2013-debug\install\include\google/prot
obuf/io/coded_stream.h(870) : warning C4800: “google::protobuf::internal::Atomi
cWord”: 将值强制为布尔值“true”或“false”(性能警告)
C:\artosyn\libncnn\protobuf-3.4.0\build-vs2013-debug\install\include\google/prot
obuf/io/coded_stream.h(874) : warning C4800: “google::protobuf::internal::Atomi
c64”: 将值强制为布尔值“true”或“false”(性能警告)
C:\artosyn\libncnn\protobuf-3.4.0\build-vs2013-debug\install\include\google/prot
obuf/generated_message_util.h(160) : warning C4800: “const google::protobuf::ui
nt32”: 将值强制为布尔值“true”或“false”(性能警告)
NMAKE : fatal error U1073: 不知道如何生成“C:\artosyn\libncnn\protobuf-3.4.0\bui
ld-vs2013-debug\install\lib\libprotobuf.lib”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 12.
0\VC\BIN\amd64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 12.
0\VC\BIN\amd64\nmake.exe"”: 返回代码“0x2”
Stop.

**Comment by YuPeize** [comment]
求问如何解决的呢？

**Comment by GHLab** [comment]
I had same issue and resolved it. I think @Ason93 found same reason.
First protobuf must be built by debug type and change the 'libprotobuf.lib' path to 'libprotobufd.lib'.

-DProtobuf_LIBRARIES=C:/artosyn/libncnn/protobuf-3.4.0/build-vs2013-debug/install/lib/libprotobuf.lib
to
-DProtobuf_LIBRARIES=C:/artosyn/libncnn/protobuf-3.4.0/build-vs2013-debug/install/lib/libprotobufd.lib
