### ISSUE TITLE
arm端int8量化后速度慢了

### ISSUE THREAD

**Issue by ivoxx** [Tencent/ncnn#1018]
ARM Cortex-A53，build armv7 library
对mtcnn进行量化

模型 | 模型大小 | ARM端前向耗时ms | 其他
-- | -- | -- | --
P 输入400*300 | 27KB | mean:18.01 |  
R 输入24*24 | 401KB | mean:1.71 |  
O 输入48*48 | 1.6MB | mean:5.67 |  
P-int8 输入400*300 | 7KB | mean:23.28 | 
R-int8 输入24*24 | 105KB | mean:2.43 | 
O-int8 输入48*48 | 398KB | mean:7.42|

这个速度是否正常？

**Comment by stupidchenchen** [comment]
A53 为啥要用 armv7 library

**Comment by ivoxx** [comment]
> A53 为啥要用 armv7 library

路径依赖😄

**Comment by linxueya** [comment]
你好，请问量化时image这一项需要多少图片，我用的是一张，量化后的模型好像不能检测

**Comment by ivoxx** [comment]
> 你好，请问量化时image这一项需要多少图片，我用的是一张，量化后的模型好像不能检测

我用了几万张，能检测，效果不好。

**Comment by linxueya** [comment]
你训练好的caffe模型可以分享一下吗，我用A53跑的mobilenetssd（chuanqi305的模型）检测一张图结果要700ms

**Comment by ivoxx** [comment]
> 你训练好的caffe模型可以分享一下吗，我用A53跑的mobilenetssd（chuanqi305的模型）检测一张图结果要700ms
链接:https://pan.baidu.com/s/1x0vyzF1PN8Bx1HK1Q8hyCg  密码:j25w

**Comment by linxueya** [comment]
> > 你训练好的caffe模型可以分享一下吗，我用A53跑的mobilenetssd（chuanqi305的模型）检测一张图结果要700ms
> > 链接:https://pan.baidu.com/s/1x0vyzF1PN8Bx1HK1Q8hyCg  密码:j25w


@ivoxx 请教一下我量化的过程中为什么一直出现couldn‘t find any detctions.
我这次用了5000张图片

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
20210507版本大幅优化int8推理速度，建议更新
