### ISSUE TITLE
卷积的参数，不支持kernel_h != kernel_w （在caffe模型转换ncnn模型时，出错）

### ISSUE THREAD

**Issue by hexujun** [Tencent/ncnn#102]
在做caffe模型转换ncnn模型时，出错。
不支持：
kernel_h != kernel_w   
pad_h != pad_w 
stride_h != stride_w

请问后续什么时候支持？

**Comment by aliushn** [comment]
同问，或者有什么替代方案么？

**Comment by nihui** [comment]
不支持长方形的

**Comment by nihui** [comment]
支持转换，待优化
 https://github.com/Tencent/ncnn/commit/abfd3ea6c8fb9f8521ce0f2b2c60c940f721b969
