### ISSUE TITLE
Run benchncnn error in Hi3516CV500 platform

### ISSUE THREAD

**Issue by AaronFan1992** [Tencent/ncnn#1020]
I compiled the source code using "toolchains/himix200.toolchain.cmake",  it's successful, but except error when running './benchncnn' on my board:

### ./benchncnn: error while loading shared libraries: libc.so: cannot open shared object file: No such file or directory

I created a symbolic link "libc.so" in the system lib folder, still except:

**Comment by 92ypli** [comment]
请问是你怎么解决的？

**Comment by yumaofan** [comment]
@92ypli 没有解决，项目停了
