### ISSUE TITLE
ncnn如何获取某一层的维度？

### ISSUE THREAD

**Issue by zys1994** [Tencent/ncnn#1022]
ncnn如何获取某一层的维度
如人脸识别我想获取fc5这个层的维度，该用什么？

**Comment by lancemao** [comment]
我理解某一层没有一个固定的维度，应该分为输入（在ncnn里面是bottom）和输出（top）。另外，可以有多个输入和输出的blob（就是一个ncnn的mat）
如果你的问题是想拿到fc5输出的维度，方便后续存储，其实可以简单的传入一个mat作为output，然后output.w就是输出的维度。下面是我在做人脸识别获取feature的代码
```
ncnn::Extractor ex = m_net.create_extractor();
ex.input("data", image);
ncnn::Mat out;
ex.extract("fc1", out);
// out.w就是输出的维度。out.h等于1。这里out当作一个vec
```

**Comment by nihui** [comment]
正如楼上所示，输出的维度是运行时才可获知的
