### ISSUE TITLE
libncnn.a里面的xxx.cpp.o报错

### ISSUE THREAD

**Issue by Armyer** [Tencent/ncnn#1026]
我用ncnn生成的libncnn.a 放入 Android，并且在CMakeLists.txt加入了
FIND_PACKAGE(OpenMP)
if(OPENMP_FOUND)
    message("OPENMP FOUND")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()
并且在build.gradle中也加入了
 cmake {
                cppFlags "-frtti -fexceptions"
                arguments "-DANDROID_TOOLCHAIN=clang"
            }
为什么编译还是出现下面这些错误？求解答！感激不尽！
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(cpu.cpp.o):/home/nihui/osd/ncnn/src/cpu.cpp:function ncnn::set_cpu_powersave(int): error: undefined reference to 'omp_set_num_t
hreads'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(cpu.cpp.o):/home/nihui/osd/ncnn/src/cpu.cpp:function ncnn::set_cpu_powersave(int): error: undefined reference to '__kmpc_fork_c
all'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(cpu.cpp.o):/home/nihui/osd/ncnn/src/cpu.cpp:function .omp_outlined.: error: undefined reference to '__kmpc_for_static_init_4'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(cpu.cpp.o):/home/nihui/osd/ncnn/src/cpu.cpp:function .omp_outlined.: error: undefined reference to '__kmpc_for_static_fini'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(cpu.cpp.o)(.text._ZN4ncnn19get_omp_num_threadsEv+0x0): error: undefined reference to 'omp_get_num_threads'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(cpu.cpp.o)(.text._ZN4ncnn19set_omp_num_threadsEi+0x0): error: undefined reference to 'omp_set_num_threads'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(cpu.cpp.o)(.text._ZN4ncnn15get_omp_dynamicEv+0x0): error: undefined reference to 'omp_get_dynamic'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(cpu.cpp.o)(.text._ZN4ncnn15set_omp_dynamicEi+0x0): error: undefined reference to 'omp_set_dynamic'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function ncnn::Mat::substract_mean_normalize(float const*, float const*): error: un
defined reference to '__kmpc_fork_call'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function .omp_outlined.: error: undefined reference to '__kmpc_for_static_init_4'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function .omp_outlined.: error: undefined reference to '__kmpc_for_static_fini'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function .omp_outlined..1: error: undefined reference to '__kmpc_for_static_init_4'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function .omp_outlined..1: error: undefined reference to '__kmpc_for_static_fini'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function .omp_outlined..2: error: undefined reference to '__kmpc_for_static_init_4'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function .omp_outlined..2: error: undefined reference to '__kmpc_for_static_fini'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function ncnn::copy_make_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int, i
nt, float): error: undefined reference to '__kmpc_fork_call'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(mat.cpp.o):/home/nihui/osd/ncnn/src/mat.cpp:function ncnn::copy_cut_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int): e
rror: undefined reference to '__kmpc_fork_call'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(int, ncnn::Mat&): error: undefined reference to '
omp_get_dynamic'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(int, ncnn::Mat&): error: undefined reference to '
omp_get_num_threads'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(int, ncnn::Mat&): error: undefined reference to '
omp_set_dynamic'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(int, ncnn::Mat&): error: undefined reference to '
omp_set_num_threads'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(int, ncnn::Mat&): error: undefined reference to '
omp_set_dynamic'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(int, ncnn::Mat&): error: undefined reference to '
omp_set_num_threads'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(char const*, ncnn::Mat&): error: undefined refere
nce to 'omp_get_dynamic'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(char const*, ncnn::Mat&): error: undefined refere
nce to 'omp_get_num_threads'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(net.cpp.o):/home/nihui/osd/ncnn/src/net.cpp:function ncnn::Extractor::extract(char const*, ncnn::Mat&): error: undefined refere
nce to 'omp_set_dynamic'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(convolutiondepthwise.cpp.o):/home/nihui/osd/ncnn/src/layer/convolutiondepthwise.cpp:function .omp_outlined..1: error: undefined
 reference to '__kmpc_for_static_init_8'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(convolutiondepthwise_arm.cpp.o):/home/nihui/osd/ncnn/src/layer/arm/convolutiondepthwise_arm.cpp:function ncnn::ConvolutionDepth
Wise_arm::forward(ncnn::Mat const&, ncnn::Mat&) const: error: undefined reference to 'omp_get_nested'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(convolutiondepthwise_arm.cpp.o):/home/nihui/osd/ncnn/src/layer/arm/convolutiondepthwise_arm.cpp:function ncnn::ConvolutionDepth
Wise_arm::forward(ncnn::Mat const&, ncnn::Mat&) const: error: undefined reference to 'omp_set_nested'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(convolutiondepthwise_arm.cpp.o):/home/nihui/osd/ncnn/src/layer/arm/convolutiondepthwise_arm.cpp:function ncnn::ConvolutionDepth
Wise_arm::forward(ncnn::Mat const&, ncnn::Mat&) const: error: undefined reference to 'omp_set_nested'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(deconvolutiondepthwise_arm.cpp.o):/home/nihui/osd/ncnn/src/layer/arm/deconvolutiondepthwise_arm.cpp:function ncnn::Deconvolutio
nDepthWise_arm::forward(ncnn::Mat const&, ncnn::Mat&) const: error: undefined reference to 'omp_get_nested'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(deconvolutiondepthwise_arm.cpp.o):/home/nihui/osd/ncnn/src/layer/arm/deconvolutiondepthwise_arm.cpp:function ncnn::Deconvolutio
nDepthWise_arm::forward(ncnn::Mat const&, ncnn::Mat&) const: error: undefined reference to 'omp_set_nested'
C:/Users/Administrator/Desktop/CNNCache/ncnn-android-lib/armeabi-v7a/libncnn.a(deconvolutiondepthwise_arm.cpp.o):/home/nihui/osd/ncnn/src/layer/arm/deconvolutiondepthwise_arm.cpp:function ncnn::Deconvolutio
nDepthWise_arm::forward(ncnn::Mat const&, ncnn::Mat&) const: error: undefined reference to 'omp_set_nested'

**Comment by lancemao** [comment]
openmp在android上默认就是支持的
你只需要调用ncnn的设置thread num函数，传入当前机器cpu数量就可以了

**Comment by nihui** [comment]
需要加 link -fopenmp
