### ISSUE TITLE
NCNN支持 有多个输入的caffe 模型吗？

### ISSUE THREAD

**Issue by zxDeepDiver** [Tencent/ncnn#1027]
大神您好，

现在想用NCNN部署一个网络模型，需要拆分两部分来部署。第二部分网络结构自然变成了有多个输入（大概10个左右）的一个caffe的prototxt文件。我的方式是：
ex2.input(detect2_param_id::LAYER_predict_layer_1, predict_layer_1);
ex2.input(detect2_param_id::LAYER_predict_layer_2, predict_layer_2);
。。。连续执行十次 input函数，然后extract一个输入结果。

但是extract会导致程序闪退。

请问是什么原因，应该怎么排查bug呢？

非常感谢大神。

**Comment by corleonechensiyu** [comment]
不支持N维度大于1的
