### ISSUE TITLE
编译caffe2ncnn时报错，protobuf未定义的引用

### ISSUE THREAD

**Issue by wuzuyu365** [Tencent/ncnn#103]
我装的protobuf是2.6.1版的，但报错：
CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o:(.data.rel.ro._ZTVN5caffe14PReLUParameterE[_ZTVN5caffe14PReLUParameterE]+0x40)：对‘google::protobuf::Message::InitializationErrorString[abi:cxx11]() const’未定义的引用

**Comment by nihui** [comment]
重装下 protobuf，建议使用系统的 protobuf
sudo apt-get install libprotobuf-dev protobuf-compiler
