### ISSUE TITLE
fasterrcnn.cpp有人测试成功过么

### ISSUE THREAD

**Issue by xcaizewu** [Tencent/ncnn#1032]
我看fasterrcnn.cpp里面的代码，没有像vgg，ZF这样的网络架构，也没有fast rcnn的是被部分，而是直接调了函数，我想请问这些函数是ncnn已经封装好了么

**Comment by nihui** [comment]
网络结构是模型定义的，fasterrcnn.cpp 用的示例模型是 ZFNet

**Comment by weilanShi** [comment]
> 网络结构是模型定义的，fasterrcnn.cpp 用的示例模型是 ZFNet
也就是说如果要在ncnn测试其他网络（vgg16）这份fasterrcnn.cpp是需要更改的，是吗？大概需要改哪些地方呢？

**Comment by weilanShi** [comment]
> 网络结构是模型定义的，fasterrcnn.cpp 用的示例模型是 ZFNet
您好，非常感谢您的贡献，为后者带来诸多方便。我在pc端测试fasterrcnn时，用的vgg16网络的模型，也用onnx转为了ncnn所需格式，然而，我在测试时,出现了这样一个错误：find_blob_index_by_name im_info failed 段错误 (核心已转储)，在fasterrcnn.cpp里根据自己的训练类别数改了class，.param 和.bin也是onnx生成的，出现这个错误是否是在转.param 和.bin时protox修改得不对呢？

这是修改后的protox输入部分：
name: "VGG_ILSVRC_16_layers"

layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param {shape {dim: 1 dim: 3 dim: 224 dim: 224  } } }

layer {
  name: "im_info"
  type: "Input"
  top: "data"
  input_param {shape { dim: 1 dim: 3 } } }

希望得到解答，万分感谢！
