### ISSUE TITLE
Time inference

### ISSUE THREAD

**Issue by YaYaB** [Tencent/ncnn#1037]
Hi,

I have been toying a bit with ncnn and I have remarked some interesting things. It's a light deep learning framework to release deep models in mobiles (mainly arm cpus).

However I wanted to try it on classical cpus to see if it gives better performances on those.
Here is the benchmark I did, note that all of these were launched on the following CPU **i7-5820K CPU @ 3.30GHz**  with a **batch size 1**. I've compared ncnn and caffe's inferences time.

```
SSD 512x512 2 classes
- 5s/it caffe
- 54s/it ncnn

squezzenet_sdd 300x300 2 classes
- 0,52 s/it caffe
- 0,23 s/it ncnn

ssd 300x300, 21 classes
- 2,13 s/it caffe
- 3,12 s/it ncnn

gnet 224*224, 21k classes
- 1 s/it caffe
- 0.369 s/it ncnn

vgg 300*300, 101 classes
- 0.729927 s/it caffe
- 0.7633 s/it ncnn (edited)
```

As you can see, for light models as squeezenet and gnet, ncnn performs way better. However for models a bit bigger (vgg, ssd) ncnn is slower than caffe.

Do you have any idea why it is like this?

Best,
YaYaB.

**Comment by nihui** [comment]
ncnn is optimized for the mobile platform, not for the desktop
so, slow inference speed is expected
