### ISSUE TITLE
About Float 16

### ISSUE THREAD

**Issue by DickyQi** [Tencent/ncnn#1038]
[0 Adreno (TM) 630]  queueC=0[3]  queueT=0[3]  memU=2  memDL=2  memHV=2
[0 Adreno (TM) 630]  fp16p=1  fp16s=0  fp16a=0  int8s=0  int8a=0
means not support fp16 storage?

**Comment by nihui** [comment]
yeah, it means fp16 storage is not supported by hardware
however, fp16p is supported on all vulkan-capable devices, somewhat slower than the hardware fp16 storage but lots faster than vanilla fp32 storage.

**Comment by Eleanor456** [comment]
> yeah, it means fp16 storage is not supported by hardware
> however, fp16p is supported on all vulkan-capable devices, somewhat slower than the hardware fp16 storage but lots faster than vanilla fp32 storage.

请问怎么解决这个问题呢，我加载了fp16的模型之后，提示ncnn cannot create up with use_fp16 storage if not support fp16 storage。当直接设置net.ope.use_fp16 storage=false后，模型在extract时报segmentation fault。麻烦请问一下这个要怎么解决呢
