### ISSUE TITLE
modelbin read index_array failed

### ISSUE THREAD

**Issue by sunbinbin1991** [Tencent/ncnn#1039]
I use the latest version of ncnn, here is a problem, when I use tools  convert my model, nothing wrong happend,however, I load my model,here is wrong message:
**`Modelbin read index_array failed 0`**
**` layer`load_model 755 failed`**
also，it seems crash at forward in **deconvolution：：forward**

**Comment by HaoLiuHust** [comment]
@nihui what does this mean?

**Comment by nihui** [comment]
the error occurs when the weight_data_size is not corresponding to the layer parameters.
for example, inch=4, outch=4, kernel_size=3, but weight_data_size=36, which is too small

**Comment by HaoLiuHust** [comment]
@nihui how to solve this? we use mxnet2ncnn tool to convert a trained model to ncnn, should we check the convert tool?

**Comment by HaoLiuHust** [comment]
I have debug it for a few time, seems the flag_struct is wrong, int mxnet2ncnn, the flag is 0, but when read the model, it changes to 671 @nihui

**Comment by xiejiezhang** [comment]
has we solved the problem?
