### ISSUE TITLE
ncnn适合量化和稀疏的方式有哪些

### ISSUE THREAD

**Issue by hanyajun0040** [Tencent/ncnn#1040]
我想问一下，ncnn适合量化和稀疏的方式有哪些

**Comment by hanyajun0040** [comment]
@nihui

**Comment by nihui** [comment]
量化方法参考 https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
ncnn 不支持稀疏

**Comment by hanyajun0040** [comment]
我想问一下，我用caffe-int8工具转换了squeenet_v1.1之后,为什么速度比之前不量化的时候变慢了，慢了大概1ms.  分类模型量化后慢了大概8ms，具体是什么原因？

**Comment by hanyajun0040** [comment]
@nihui
