### ISSUE TITLE
benchmark vgg16,resnet50

### ISSUE THREAD

**Issue by lyuchuny3** [Tencent/ncnn#1041]
Hi, 

这个issue主要是关于ncnn的benchmark的vgg16和resnet50的性能疑问：

* VGG16 (224x224) 的理论计算量约为 30.7 G 个乘累加
* Resnet50 (224x224)的理论计算量约为7.7G个乘累加
  统计计算量工具可以用：https://dgschwend.github.io/netscope/#/editor， prototxt链接: [vgg16](https://github.com/davidgengenbach/vgg-caffe), [resnet50](https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt)

这两个网络的**理论计算量大概是 4倍**的关系，ncnn的benchmark, 以3399为例：
* vgg16: 875ms
* resnet50: 650ms
这个耗时比和理论计算量之比差距较大，所以抛出疑问

Thanks

**Comment by nihui** [comment]
conv 3x3 使用了 winograd f63 减少了运算量，并且 ncnn 优化较好
resnet50 有比较多的 conv1x1 和开头的 conv7x7，不适用 winograd
