### ISSUE TITLE
如何分析ncnn model结构，有类似netscope的东西来分析吗

### ISSUE THREAD

**Issue by helloearth012** [Tencent/ncnn#1044]

**Comment by nihui** [comment]
没有类似的工具，建议用原始的 caffe mxnet onnx 模型看
ncnn model 结构定义可以参考以下文档
https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure
https://github.com/Tencent/ncnn/wiki/operation-param-weight-table

**Comment by nihui** [comment]
netron 支持查看 ncnn 模型
