### ISSUE TITLE
反卷积针对kernel_size=8 性能很差，请问什么时候可以支持这个kernel_size加速？

### ISSUE THREAD

**Issue by hexujun** [Tencent/ncnn#105]
反卷积针对kernel_size=8 性能很差，请问什么时候可以支持这个kernel_size加速

**Comment by cscyangj** [comment]
@hexujun 这个应该你自己添加代码实现。使用neon并行下就行了。如果支持了太多的kernel, 工作量就太大了。

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/issues/1048
