### ISSUE TITLE
Android端和ubuntu端人脸相似度不同

### ISSUE THREAD

**Issue by YuGongCharley** [Tencent/ncnn#1050]
使用的是mobilefacenet的模型，我用同样两张不同人脸的图片在安卓端比对的相似度是30%左右，可是将代码和模型移植到x86的Ubuntu上运行，相似度就升到的90%多，比对部分的代码没有变，想请教一下是为什么？

**Comment by nihui** [comment]
建议用 bmp 格式图片测试

**Comment by YuGongCharley** [comment]
@nihui ok，看来是io的问题了，谢谢大佬

**Comment by aa12356jm** [comment]
你好，这个问题解决了吗? 可以分享一下是什么原因吗？谢谢

**Comment by YuGongCharley** [comment]
@aa12356jm 解决了，图像转换的问题，通道数不对应导致的，jni里做ncnn::Mat::from_pixels_resize之前判断一下通道数，然后对应相应通道做ncnn::Mat::PIXEL_xxxxxxx
