### ISSUE TITLE
float浮点型数据输入问题

### ISSUE THREAD

**Issue by shenchao8607** [Tencent/ncnn#1052]
我现在的输入数据是一个非图像类型的float数组，我的model是从caffe转ncnn的。
caffe 里面输入的方法是：
data = np.reshape(input_features, (1, 1, 15, 100))
net.blobs['data'].data[...] = data
然后我在ncnn输入用以下方法：
float * data; 
Mat in(w,h,c, data)

但是现在无论data怎么变，输出都不变。但是caffe里面是工作正常
希望大佬@nihui 解答！！

**Comment by 2Moonsbird** [comment]
> 我现在的输入数据是一个非图像类型的float数组，我的model是从caffe转ncnn的。
> caffe 里面输入的方法是：
> data = np.reshape(input_features, (1, 1, 15, 100))
> net.blobs['data'].data[...] = data
> 然后我在ncnn输入用以下方法：
> float * data;
> Mat in(w,h,c, data)
> 
> 但是现在无论data怎么变，输出都不变。但是caffe里面是工作正常
> 希望大佬@nihui 解答！！

请问你的问题解决了吗？
我使用的模型是keras训练出来，转caffe再转到ncnn，同样是数组而非图片。确认ncnn::Mat in的数据变动，但是out中输出一直不变

**Comment by shenchao8607** [comment]
> > 我现在的输入数据是一个非图像类型的float数组，我的model是从caffe转ncnn的。
> > caffe 里面输入的方法是：
> > data = np.reshape(input_features, (1, 1, 15, 100))
> > net.blobs['data'].data[...] = data
> > 然后我在ncnn输入用以下方法：
> > float * data;
> > Mat in(w,h,c, data)
> > 但是现在无论data怎么变，输出都不变。但是caffe里面是工作正常
> > 希望大佬@nihui 解答！！
> 
> 请问你的问题解决了吗？
> 我使用的模型是keras训练出来，转caffe再转到ncnn，同样是数组而非图片。确认ncnn::Mat in的数据变动，但是out中输出一直不变

create new Extractor for each image
The ncnn::Extractor object is stateful, if you reuse for different input, you will always get exact the same result cached inside.

Always create new Extractor to process images in loop unless you do know how the stateful Extractor works.

for (int i=0; i<count; i++)
{
    // always create Extractor
    // it's cheap and almost instantly !
    ncnn::Extractor ex = net.create_extractor();

    // use
    ex.input(your_data[i]);
}
