### ISSUE TITLE
feature map size is  subtracted by 2 after Deconvolution layer in ncnn. How to avoid this?

### ISSUE THREAD

**Issue by lidehuihxjz** [Tencent/ncnn#1053]
When I convert pytorch model to ncnn, the featrue map was subtracted by 2. That is because the deconvolution layer of pytorch have the parameter _output_padding_ to maintain feature maps' original size. Dose ncnn have  any way to keep the original size when do the deconvolution?

**Comment by wincle** [comment]
Meeting the same problem.
