### ISSUE TITLE
from_pixels_resize 在安卓平台 armv7a架构出现内存泄漏

### ISSUE THREAD

**Issue by Wengjpv** [Tencent/ncnn#1056]
ncnn::Mat ncnn_img = ncnn::Mat::from_pixels_resize(input_image.image_data, ncnn::Mat::PIXEL_BGR, input_image.width, input_image.height, input_image.width / scale, input_image.height / scale);
使用这一接口会导致在android armv7 架构下内存会不断增长

**Comment by Wengjpv** [comment]
测试了在windows x86架构没有出现该问题

**Comment by Wengjpv** [comment]
ncnn::resize_bilinear_c3(u_src, src_w, src_h, u_dst, w, h); 应该是这个函数内部的问题

**Comment by crz1336768325** [comment]
@Wengjpv ，解决了吗

**Comment by aa12356jm** [comment]
同问

**Comment by Wengjpv** [comment]
没有 暂时用opencv实现resize

**Comment by nihui** [comment]
从代码上看，resize_bilinear_c3 并没有内存泄漏的地方...

**Comment by Wengjpv** [comment]
安卓平台测试确实内存不断增长 换成opencv做resize之后解决了 windows没有这个问题@nihui

**Comment by zxDeepDiver** [comment]
我也观察到了这个现象

**Comment by ujsyehao** [comment]
@Wengjpv 这个问题，还有吗

**Comment by nihui** [comment]
做了新的实现 https://github.com/Tencent/ncnn/pull/5200
用最新版本试试
代码上看没有内存泄漏，但是会做 new delete，可能是释放内存后，glibc保留了下来，导致系统看到在增长
