### ISSUE TITLE
自定义层在ubuntu的ncnn框架下运行没问题，但是编译成安卓库之后在移动端调用却结果不一致？

### ISSUE THREAD

**Issue by 503216199** [Tencent/ncnn#1057]
自定义层在ubuntu的ncnn框架下运行没问题，但是编译成安卓库之后在移动端调用却结果不一致？

**Comment by nihui** [comment]
用 bmp 图片格式测试

**Comment by nihui** [comment]
建议更新ncnn最新版
另外可以注意下模型加载接口是否正确
https://github.com/Tencent/ncnn/wiki/ncnn-load-model
如果还有问题，可以reopen issue继续讨论
