### ISSUE TITLE
如何将OpenCV的Mat通过 jni传给ncnn作正确转换

### ISSUE THREAD

**Issue by YuGongCharley** [Tencent/ncnn#1058]
我在ubuntu上用java写的应用层，在读图时使用的是imread读成Mat，然后转成byte[]数组后通过jni传给ncnn::Mat::from_pixels_resize，可是这样会出现因为图像格式的问题导致识别返回的结果都是90%多的问题，java也没有安卓上的Bitmap类型，想请问一下我这里应该怎么做？

谢谢

**Comment by YuGongCharley** [comment]
自己解决了。。close了。。。

**Comment by tanghaoran666** [comment]
大佬，你好。我也在做使用ncnn的人脸识别项目，请问人脸特征那块，如何从ncnn::Mat转换成cv::Mat,或者直接遍历其中浮点数

**Comment by YuGongCharley** [comment]
@tanghaoran666 
你可以试试这个方法：
cv::Mat cv_img = cv::Mat::zeros(rows,cols,opencv_typ);
ncnn_img.to_pixels(cv_img.data,ncnn::Mat::PIXEL_RGB);

请一定要注意通道数和像素排列（RGBA、RGB这种），我之前就是因为没注意到这个才出现上面的错
