### ISSUE TITLE
使能vulkan启用AMDGPU为何还占用那么多的CPU

### ISSUE THREAD

**Issue by ggkingdom** [Tencent/ncnn#1060]

**Comment by ggkingdom** [comment]
问题描述：
关闭vulkan, cpu4652, 占用90%，gpu显存占用为0
打开vulkan, cpu3614, 占用70%，gpu显存占用很少
启用方式：
ncnn::create_gpu_instance(); 
net.opt.use_vulkan_compute = true;
net.opt.use_fp16_packed = false;
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
net.opt.use_int8_storage = false;
net.opt.use_int8_arithmetic = false;
请问哪位大牛知道什么原因啊，望不吝赐教，谢谢：）

**Comment by ggkingdom** [comment]
原因是ncnn::Mat::substract_mean_normalize调用了Bias层，该层vulkan不支持。深度网络模型有bias偏置参数，vulkan不支持只能回退到cpu侧执行了

**Comment by nihui** [comment]
预处理和后处理是cpu函数，后面会考虑给 vkmat 也实现 substract_mean_normalize

**Comment by ggkingdom** [comment]
嗯嗯，期待：）
