### ISSUE TITLE
Can ncnn accepts cv::Mat as input without ncnn::Mat conversion? 

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#1065]
I am converting cv::Mat to ncnn::Mat and passing it to model. Can I pass cv::Mat into model directly?

**Comment by soham24** [comment]
Tflite accepts cv::mat.data directly. 
This saves time of cv mat to ncnn mat conversion

**Comment by soham24** [comment]
@nihui

**Comment by nihui** [comment]
That is what the Mat::from_pixels_resize() for
Because the internal data layout is different, conversion cannot be avoided anyway.
