### ISSUE TITLE
floating point exception ./benchncnn

### ISSUE THREAD

**Issue by imistyrain** [Tencent/ncnn#1068]
Mac 下编译了带vulkan的库，运行./ncnnbench时出现floating point exception  ./benchncnn

```
benchmark git:(master) ✗ ./benchncnn 1 1 0 0
[0 Intel(R) Iris(TM) Plus Graphics 640]  queueC=0[1]  queueT=0[1]  memU=2  memDL=2  memHV=2
[0 Intel(R) Iris(TM) Plus Graphics 640]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
loop_count = 1
num_threads = 1
powersave = 0
gpu_device = 0
          squeezenet  min =    9.70  max =    9.70  avg =    9.70
[1]    17762 floating point exception  ./benchncnn 1 1 0 0
```
而之前不带vulkan编译的时候可以正常运行，vulkan版本为1.1.108

**Comment by nihui** [comment]
mac gpu 我这里没环境，确保系统，moltenvk，ncnn代码，param文件都更新了
打开vulkan validation layer跑下看有什么输出
https://github.com/Tencent/ncnn/wiki/vulkan-notes#debugging-tips
以及调试贴下堆栈信息

**Comment by nihui** [comment]
如果没有解决，请提供更多信息重新打开issue

**Comment by billmguo** [comment]
I also met this issue with latest 3/4 release , I turn on #define ENABLE_VALIDATION_LAYER 1  but also display  Floating point exception only.
