### ISSUE TITLE
ncnn::Net net; net.load_model("ldmk_det_vgg.bin"); 执行这句话总是出现Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zf829** [Tencent/ncnn#1070]
在一个toybrick的板子上用ncnn转模型，执行 net.load_model("ldmk_det_vgg.bin");这句话总是出现Segmentation fault (core dumped)，大神们有啥指点吗

**Comment by nihui** [comment]
可能是内存不足？

**Comment by nihui** [comment]
请提供更多信息后reopen吧
