### ISSUE TITLE
NEON intrinsics not available with the soft-float ABI

### ISSUE THREAD

**Issue by grapefruitL** [Tencent/ncnn#1071]
i use arm-himix100-linux-g++ to compile
so i edit the file ./toolchain/himix100.toolchain.cmake like this:

SET ( CMAKE_C_COMPILER "/opt/arm-himix100-linux/bin/arm-himix100-linux-gcc" )
SET ( CMAKE_CXX_COMPILER "/opt/arm-himix100-linux/bin/arm-himix100-linux-g++" )
SET ( CMAKE_FIND_ROOT_PATH "/opt/arm-himix100-linux/bin/" )

and use "cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/himix100.toolchain.cmake .. " command.
when i make, i got errs:
```
In file included from /home/kevin/ncnn-master/src/mat.h:22:0,
                 from /home/kevin/ncnn-master/src/layer.h:23,
                 from /home/kevin/ncnn-master/src/layer.cpp:15:
/opt/arm-himix100-linux/lib/gcc/arm-linux-uclibceabi/6.3.0/include/arm_neon.h:31:2: error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softp or -mfloat-abi=hard"
 #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softp or -mfloat-abi=hard"
  ^~~~~
In file included from /home/kevin/ncnn-master/src/layer.h:23:0,
                 from /home/kevin/ncnn-master/src/layer.cpp:15:
/home/kevin/ncnn-master/src/mat.h: In member function 'void ncnn::Mat::fill(float)':
/home/kevin/ncnn-master/src/mat.h:504:5: error: 'float32x4_t' was not declared in this scope
     float32x4_t _c = vdupq_n_f32(_v);
     ^~~~~~~~~~~
/home/kevin/ncnn-master/src/mat.h:533:15: error: '_c' was not declared in this scope
           "w"(_c)       // %4
               ^~
/home/kevin/ncnn-master/src/mat.h: In member function 'void ncnn::Mat::fill(int)':
/home/kevin/ncnn-master/src/mat.h:558:5: error: 'int32x4_t' was not declared in this scope
     int32x4_t _c = vdupq_n_s32(_v);
     ^~~~~~~~~
/home/kevin/ncnn-master/src/mat.h:587:15: error: '_c' was not declared in this scope
           "w"(_c)       // %4
               ^~
make[2]: *** [src/CMakeFiles/ncnn.dir/layer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
make: *** [all] Error 2
```
i tried to do as the suggestion:"Please use -mfloat-abi=softp or -mfloat-abi=hard"
and it doesn't work.
how to fix this?

**Comment by ysh329** [comment]
Hi, I wanna ask what's the difference between soft float and hard float?

**Comment by nihui** [comment]
do as the suggestion, use -mfloat-abi=softp or -mfloat-abi=hard
the difference is about the ABI for passing floating point arguments, the inference speed should be very near

**Comment by grapefruitL** [comment]
sorry fo late reply 
i build successfully by turning off the neon(Comment "add_definitions(-D__ARM_NEON)" in himix100.toolchain.cmake)
my env is huawei liteos ,it doesn't seem to support neon, so the compiler didn't define __ARM_FP, then my arm_neon.h got errs:
```
#ifndef __ARM_FP
#error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softp or -mfloat-abi=hard"
#else
```
