### ISSUE TITLE
自己编译出的lib和下载的lib大小不一致，问题在哪里呀

### ISSUE THREAD

**Issue by ysh329** [Tencent/ncnn#1074]
大家好，我最近在使用ncnn的过程中，尝试自己编译NCNN的android-armv8的lib，以及下载编译好的android-armv8的lib，但是发现大小不一样。

都是来自release页面，6月11日的代码或lib包：

- release代码编译出来的`build-android-aarch64/lib/libncnn.a`有15MB；
- 下载release的android-armv8的`libncnn.a`只有2MB。

究竟是哪里出了问题，功能上有差异嘛，二者？

感谢您们的回答~ 🙇

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android
看下 optional 这段
