### ISSUE TITLE
参数 有行存储与列存储的区别吗？

### ISSUE THREAD

**Issue by adeagle** [Tencent/ncnn#108]

**Comment by nihui** [comment]
对...
所以matlab caffe的模型转换有这个问题

**Comment by adeagle** [comment]
如果是python caffe 不会有这个问题吧，可以直接转换？
我现在用 darknet2caffe.py 把 yolo 转成caffe ,可以正常工作，但转到NCNN后，输出的结果不对
NCNN输出的结果跟CAFFE输出的，内存布局是一样的吗？

**Comment by linVdcd** [comment]
@adeagle 你yolo转ncnn成功了吗

**Comment by adeagle** [comment]
成功了，主要是我的DEMO写的有问题，导致取出的数据不对

**Comment by linVdcd** [comment]
我也是写的有问题，后来好了
