### ISSUE TITLE
in platform.h.in you can use std::mutex

### ISSUE THREAD

**Issue by graph** [Tencent/ncnn#1082]
current implementation uses pthread on linux/mac and windows locking on windows. If you allow c++11 and above you should use std::mutex.

```
#include <mutex>

// std::mutex has lock & unlock like ncnn::Mutex so just a typedef is enough.
typedef std::mutex Mutex;
// similar for MutexLockGuard and unique_lock.
typedef std::unique_lock<Mutex> MutexLockGuard;
```

Thread and ConditionVariable will require more work but very straightforward to switch. I prefer  c++ standard functions to be used over the platform specific ones.

**Comment by graph** [comment]
Here is adapted starter code. only ConditionVariable is not backwards compatible. Or your team can replace all usages with c++11 features. I think the replacing with c++11 outside of platform is better but definitely more work.
```
#ifndef NCNN_PLATFORM_H
#define NCNN_PLATFORM_H

#cmakedefine01 NCNN_STDIO
#cmakedefine01 NCNN_STRING
#cmakedefine01 NCNN_OPENCV
#cmakedefine01 NCNN_BENCHMARK
#cmakedefine01 NCNN_PIXEL
#cmakedefine01 NCNN_PIXEL_ROTATE
#cmakedefine01 NCNN_VULKAN
#cmakedefine01 NCNN_REQUANT
#cmakedefine01 NCNN_AVX2

#include <thread>
#include <mutex>
#include <condition_variable>

namespace ncnn {

typedef std::mutex Mutex;
typedef std::unique_lock<Mutex> MutexLockGuard;

// ConditionVariable wait function is not backwards compatible. It forces you
// to use MutexLockGuard. Which should be fine overall.
class ConditionVariable : std::condition_variable;
{
public:
    void broadcast() { notify_all(); }
    void signal() { notify_one(); }
private:
};

class Thread
{
public:
    Thread(void* (*start)(void*), void* args = 0) {
        thread = std::thread([args)() {
            start(args);
        }
    };
    // it will crash if you exit without the thread being completed.
    ~Thread() { thread.join();}
    void join() { thread.join(); }
private:
    std::thread thread;
};


} // namespace ncnn

#endif // NCNN_PLATFORM_H
```

**Comment by nihui** [comment]
Thanks !
I love these c++11 features too, but some embedded platforms have really old toolchains, so they are implemented for the best portability at the moment.

Thus, I think we can make c++11 optional, checking compiler features and enable it.

```
#if NCNN_CPP11
// use std::mutex ...
#else
// use pthread ...
#endif
```

**Comment by graph** [comment]
This issue got closed. But was there an official decision that was made? I like the idea of NCNN_CPP11 too, atleast the windows build can use standard c++11 as that will mean I won't have to worry about special windows switches when compiling the library.
