### ISSUE TITLE
How to using fp16 with Vulkan

### ISSUE THREAD

**Issue by DickyQi** [Tencent/ncnn#1084]
How to using fp16 with vulkan support? is it need to convert widget to float16 format, or it will run-time converting? any thing I need be careful with different hardware, such as mobile GPU and desktop GPU?

**Comment by nihui** [comment]
fp16 is automatically detected and used at runtime. Either fp32 or fp16 storage model binary is fine.
you can control them per network instance
https://github.com/Tencent/ncnn/wiki/vulkan-notes#control-storage-and-arithmetic-precision

Use the latest ncnn git master code, with continous bugfix and optimization pulled in.
Optimize your model with ncnnoptimize tool for significant faster gpu inference speed
https://github.com/Tencent/ncnn/wiki/model-optimize

**Comment by DickyQi** [comment]
I tried FP16 on PC(Ubuntu18.04 with 2 GTX970, lunarg-vulkan-1.1.108, Nvidia Driver 430.34), it working fine as CPU result, and has ~25% performance improvement. But it isn't work with my Android device(OnePlus 6T with Adreno™ 630, vulkan 1.1.6). I think this platform also has bug as Mali GPU. BTW FP32 working fine.

**Comment by gigadeplex** [comment]
> 
> 
> I tried FP16 on PC(Ubuntu18.04 with 2 GTX970, lunarg-vulkan-1.1.108, Nvidia Driver 430.34), it working fine as CPU result, and has ~25% performance improvement. But it isn't work with my Android device(OnePlus 6T with Adreno™ 630, vulkan 1.1.6). I think this platform also has bug as Mali GPU. BTW FP32 working fine.

Hi I too have a problem on Mali GPU with fp16, however, with fp32 output is fine.
