### ISSUE TITLE
xcode链接ncnn-vulkan.framework错误

### ISSUE THREAD

**Issue by yonkong** [Tencent/ncnn#1086]
xcode工程。

下载最新的ncnn-vulkan.framework（android ios 预编译库 20190611 bade132），引入到工程，并指定ncnn-vulkan和MoltenVK路径后，出现下面的错误

<img width="916" alt="屏幕快照 2019-07-08 下午5 44 21" src="https://user-images.githubusercontent.com/32286565/60800564-03181b80-a1a8-11e9-91f9-77db06d1277d.png">

**Comment by nihui** [comment]
还需要下载 openmp.framework 一起用

**Comment by yonkong** [comment]
> 还需要下载 openmp.framework 一起用

done
