### ISSUE TITLE
替换ncnn版本后结果不正确

### ISSUE THREAD

**Issue by yonkong** [Tencent/ncnn#1087]
如题，同一个项目，升级ncnn版本后，结果不正确。

旧版本使用的ncnn版本时间为：去年6月份左右
新版本：今天6月份vulkan版本的ncnn
代码说明：修改点只有引入新ncnn和openmp外。原项目代码没有设置过option。

新版本或vulkan版本，是不是还要专门要设置什么参数才能兼容低版本？

**Comment by nihui** [comment]
先在pc上开发，比较两个版本结果是不是一样
如果不一样，把中间 blob extract 出来比较下
如果是开了 gpu，可以先把 gpu 关掉，或者用纯 fp32 运算观察结果对不对
https://github.com/Tencent/ncnn/wiki/vulkan-notes#control-storage-and-arithmetic-precision

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#blob-may-have-channel-gap

如果还有问题请提供更多信息，比如模型输出shape等

**Comment by JIANGYP42** [comment]
你好，请问问题解决了吗

**Comment by qinb** [comment]
请问问题解决了吗？我这边跑mnasnet，一个ncnn tag是20191113和另一个不知道版本的unkown，unkown的结果正常，而tag是20191113的结果不对

**Comment by qinb** [comment]
自己编写的加速op是基于tag 2019113写的，和ncnn tag 20191113结果一直，但是就是不正确。unkown版本2019年11月21日下载的master

**Comment by nihui** [comment]
可以试下今天刚发的新release
你自己写的加速op不依赖特定版本吧...

**Comment by qinb** [comment]
多谢，已经搞定啦

**Comment by nihui** [comment]
真好
