### ISSUE TITLE
编译IOS静态库包体积偏大

### ISSUE THREAD

**Issue by ChisenZhang** [Tencent/ncnn#1088]
我按说明用（https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-ios-on-macosx-with-xcode）加了-G “Xcode” 生成了Xcode的工程编译IOS的静态库，支持了arm7 arm7s arm64, 但是包的体积明显要比官方的framework要大很多，有15M；一些编译优化都加上了，缩包的选项也加了。 但是没什么作用，怎么才能把包的体积缩小呢？

**Comment by nihui** [comment]
打开了 llvm bitcode ？

**Comment by ChisenZhang** [comment]
> 打开了 llvm bitcode ？

关了也一样，没什么变化  debug的选项都关了  strip也打开了， CMake里面的-g也注释了；还有什么没有考虑到的地方吗？

**Comment by ChisenZhang** [comment]
额   关了 Xcode中的bitcode选项没有用， 要把编译选项里面的 -fembed-bitcode 去掉才行   又一个坑
