### ISSUE TITLE
[BUG] Elu.cpp load param

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/ncnn#109]
int ELU::load_param(FILE* paramfp)
{
    int nscan = fscanf(paramfp, "%f", &alpha);
    if (nscan != 1)
    {
        fprintf(stderr, "ELU load_param failed %d\n", nscan);
        return -1;
    }

    return 0;
}

这边有读取alpha的值，但在caffe2ncnn 中没有处理这个 alpha 的值

**Comment by nihui** [comment]
caffe2ncnn 没转换 ELU 参数 ...
