### ISSUE TITLE
Unsupported operator ReduceMean

### ISSUE THREAD

**Issue by kaustubh-pandey** [Tencent/ncnn#1092]
I would like to report an unsupported operator.
I was trying to use pytorch implementation of mobilenet v2 from this repo [link](https://github.com/marvis/pytorch-mobilenet) . I was able to export it to onnx and then used onnx simplifier. But still one operator **ReduceMean** remained and it isn't supported by ncnn. You can find the onnx model after using onnx simplifier here : [mobilenet_v2_onnx](https://github.com/kaustubh-pandey/mobilenet_v2_pytorch)

**Comment by nihui** [comment]
转换出来是这样的，倒数第二个 global avg pooling
```
Clip             463                      1 1 462 463 0=0.000000 1=6.000000
ReduceMean       464                      1 1 463 464
ReduceMean       465                      1 1 464 465
InnerProduct     output                   1 1 465 output 0=1000 1=1 2=1280000
```

手工修改下就好了
```
Clip             463                      1 1 462 463 0=0.000000 1=6.000000
Pooling          465                      1 1 463 465 0=1 4=1
InnerProduct     output                   1 1 465 output 0=1000 1=1 2=1280000
```

还有就是最开头的 layer count 和 blob count 两个数字要各减1

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
