### ISSUE TITLE
CENTOS X86 CPU Permute没有生效，麻烦请帮忙看看么？谢谢了~

### ISSUE THREAD

**Issue by yangchengtest** [Tencent/ncnn#1096]
void transpose(const ncnn::Mat& in, ncnn::Mat& out)
{
    ncnn::Layer* op = ncnn::create_layer("Permute");
    // set param
    ncnn::ParamDict pd;
    pd.set(1, 5);// order_type
    op->load_param(pd);
    // forward
    op->forward(in, out);
    delete op;
}
执行如下的代码，NHWC并没有转成NCHW。
请问Permute层有平台限制么？主代码没看到有平台宏限制啊，能帮忙解释一下么？谢谢！~

**Comment by nihui** [comment]
```
pd.set(0, 5);// order_type
```

**Comment by yangchengtest** [comment]
PD方法理解错了。
可以了，多谢。
