### ISSUE TITLE
看到之前的版本里面有tensorflow转ncnn的工具，但是现在的版本这个工具没了，ncnn是对tensorflow不支持了吗？以后有支持的计划吗？

### ISSUE THREAD

**Issue by Ason93** [Tencent/ncnn#1098]

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#why-i-get-so-many-xyz-unsupported-yet-errors-when-converting-tensorflow-model
