### ISSUE TITLE
ncnn+vulkan编译出错，请问这是什么问题，怎么解决

### ISSUE THREAD

**Issue by emailxuchen** [Tencent/ncnn#1104]
ncnn+vulkan编译时，在CMakeLists.txt中注释掉add_subdirectory(benchmark)，可以正常编译通过。但是加上add_subdirectory(benchmark)，则会出现如下问题，请问怎么解决？

[100%] Linking CXX static library libncnn.a
[100%] Built target ncnn
Scanning dependencies of target benchncnn
[100%] Building CXX object benchmark/CMakeFiles/benchncnn.dir/benchncnn.cpp.o
[100%] Linking CXX executable benchncnn
../src/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::~VulkanDevice()':
gpu.cpp:(.text+0xfc): undefined reference to `vkDestroyShaderModule'
gpu.cpp:(.text+0x120): undefined reference to `vkDestroyDevice'
../src/libncnn.a(gpu.cpp.o): In function `ncnn::destroy_gpu_instance()':
gpu.cpp:(.text+0x1f4): undefined reference to `vkDestroyInstance'
../src/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::compile_shader_module(unsigned int const*, unsigned long) const':
gpu.cpp:(.text+0x2d4): undefined reference to `vkCreateShaderModule'
../src/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::destroy_shader_module()':
gpu.cpp:(.text+0x834): undefined reference to `vkDestroyShaderModule'
../src/libncnn.a(gpu.cpp.o): In function `ncnn::VulkanDevice::init_device_extension()':
gpu.cpp:(.text+0x8a0): undefined reference to `vkGetDeviceProcAddr'
gpu.cpp:(.text+0x8c4): undefined reference to `vkGetDeviceProcAddr'
gpu.cpp:(.text+0x8d8): undefined reference to `vkGetDeviceProcAddr'
gpu.cpp:(.text+0x8ec): undefined reference to `vkGetDeviceProcAddr'
gpu.cpp:(.text+0x90c): undefined reference to `vkGetDeviceProcAddr'
../src/libncnn.a(gpu.cpp.o):gpu.cpp:(.text+0x920): more undefined references to `vkGetDeviceProcAddr' follow
../src/libncnn.a(gpu.cpp.o): In function `ncnn::create_gpu_instance()':
gpu.cpp:(.text+0x9b0): undefined reference to `vkEnumerateInstanceExtensionProperties'
gpu.cpp:(.text+0xa14): undefined reference to `vkEnumerateInstanceExtensionProperties'
gpu.cpp:(.text+0xb20): undefined reference to `vkCreateInstance'
gpu.cpp:(.text+0xbbc): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text+0xbd0): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text+0xbe4): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text+0xbf8): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text+0xc0c): undefined reference to `vkGetInstanceProcAddr'
../src/libncnn.a(gpu.cpp.o):gpu.cpp:(.text+0xc20): more undefined references to `vkGetInstanceProcAddr' follow
../src/libncnn.a(gpu.cpp.o): In function `ncnn::create_gpu_instance()':
gpu.cpp:(.text+0xc58): undefined reference to `vkEnumeratePhysicalDevices'
gpu.cpp:(.text+0xca4): undefined reference to `vkEnumeratePhysicalDevices'
gpu.cpp:(.text+0xcf0): undefined reference to `vkGetPhysicalDeviceProperties'
gpu.cpp:(.text+0xde0): undefined reference to `vkGetPhysicalDeviceQueueFamilyProperties'
gpu.cpp:(.text+0xe7c): undefined reference to `vkGetPhysicalDeviceQueueFamilyProperties'

**Comment by nihui** [comment]
参考编译步骤 https://github.com/Tencent/ncnn/wiki/how-to-build

**Comment by emailxuchen** [comment]
@nihui  我们在TX2平台上按照https://github.com/Tencent/ncnn/wiki/how-to-build这个链接里的步骤编译的，就会出现上面的错误。请问要怎么解决呢

**Comment by emailxuchen** [comment]
是不是因为Vulkan_loader_demos_1.1.100.tar.gz里面的Vulkan库版本与现在最新的ncnn版本不兼容导致的问题呢？

**Comment by emailxuchen** [comment]
以下是CMakeLists.txt文件
if(CMAKE_TOOLCHAIN_FILE)
set(LIBRARY_OUTPUT_PATH_ROOT ${CMAKE_BINARY_DIR} CACHE PATH "root for library output, set this to change where android libs are compiled to")
# get absolute path, but get_filename_component ABSOLUTE only refer with source dir, so find_file here :(
get_filename_component(CMAKE_TOOLCHAIN_FILE_NAME ${CMAKE_TOOLCHAIN_FILE} NAME)
find_file(CMAKE_TOOLCHAIN_FILE ${CMAKE_TOOLCHAIN_FILE_NAME} PATHS ${CMAKE_SOURCE_DIR} NO_DEFAULT_PATH)
message(STATUS "CMAKE_TOOLCHAIN_FILE = ${CMAKE_TOOLCHAIN_FILE}")
endif()

if(NOT DEFINED CMAKE_INSTALL_PREFIX)
set(CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install" CACHE PATH "Installation Directory")
endif()
message(STATUS "CMAKE_INSTALL_PREFIX = ${CMAKE_INSTALL_PREFIX}")

cmake_minimum_required(VERSION 3.0)

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE release CACHE STRING "Choose the type of build" FORCE)
endif()

project(ncnn)

set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)

option(NCNN_OPENMP "openmp support" ON)
option(NCNN_STDIO "load model from external file" ON)
option(NCNN_STRING "plain and verbose string" ON)
option(NCNN_INSTALL_SDK "Install ncnn library and headers" ON)
option(NCNN_OPENCV "minimal opencv structure emulation" OFF)
option(NCNN_BENCHMARK "print benchmark information for every layer" OFF)
option(NCNN_PIXEL "convert and resize from/to image pixel" ON)
option(NCNN_PIXEL_ROTATE "rotate image pixel orientation" OFF)
option(NCNN_CMAKE_VERBOSE "print verbose cmake messages" OFF)
option(NCNN_VULKAN "vulkan compute support" OFF)
option(NCNN_REQUANT "auto merge int8 quant and dequant" OFF)
option(NCNN_AVX2 "optimize x86 platform with avx2" OFF)
if(NCNN_OPENMP)
    find_package(OpenMP)
    if(NOT TARGET OpenMP::OpenMP_CXX AND (OpenMP_CXX_FOUND OR OPENMP_FOUND))
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
    endif()
endif()

if(NCNN_VULKAN)
    find_package(Vulkan REQUIRED)
    include_directories(${Vulkan_INCLUDE_DIR})
    #link_directories(${Vulkan_LIBRARY})
endif()

if(WIN32)
    add_definitions(-D_SCL_SECURE_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE)
    add_definitions(-DNOMINMAX)
else()
    add_definitions(-Wall -Wextra -Wno-unused-function)

    add_definitions(-fPIC)
    if(CMAKE_BUILD_TYPE MATCHES "(Release|RELEASE|release)")
        if(NOT CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
            add_definitions(-Ofast)
        endif()

        add_definitions(-ffast-math)
    endif()

    if(PI3)
        add_definitions(-march=native)
        add_definitions(-mfpu=neon)
        add_definitions(-mfloat-abi=hard)
        add_definitions(-D__ARM_NEON)
        add_definitions(-D__ANDROID__)

endif()
    # add_definitions(-march=native)
    # add_definitions(-flto)
    add_definitions(-fvisibility=hidden -fvisibility-inlines-hidden)
endif()

if(ANDROID)
    # disable shared library on android
    set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions")
elseif(IOS)
    # disable shared library on xcode ios
    set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions")
elseif(NCNN_AVX2)
    #set up according to your own system environment
    #Windows
    if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /arch:AVX2 /DAVX2")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /arch:AVX2 /DAVX2")
    #Linux
    else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mfma")
    endif()
endif()

##############################################

# add_subdirectory(examples)
add_subdirectory(benchmark)
add_subdirectory(src)
if(NOT ANDROID AND NOT IOS)
add_subdirectory(tools)
endif()

**Comment by nihui** [comment]
应该是兼容的，需要链接 libvulkan.so

**Comment by emailxuchen** [comment]
nihui 链接libvulkan.so还是出现同样的错误啊，能帮忙分析下原因吗，谢谢

**Comment by yzhu20** [comment]
你這個使用TX2編譯的時候報錯的吧，我也遇到同樣的問題了，請問解決了嗎？ @emailxuchen

**Comment by zZTaccount** [comment]
请问问题解决了吗？是怎么弄的呢？遇到了同样的问题。。

**Comment by emailxuchen** [comment]
现在github上版本更新了，编译了没问题




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            emailxuchen
                            
                            
                                
                                    邮箱：emailxuchen@mail.tsinghua.edu.cn
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2019年08月30日 13:47，zZTaccount 写道： 请问问题解决了吗？是怎么弄的呢？遇到了同样的问题。。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Tencent/ncnn/issues/1104?email_source=notifications\u0026email_token=AKHKZNRGGBVX6JCYL7BMRATQHCX7HA5CNFSM4ICLHUU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5QTVBA#issuecomment-526465668",
"url": "https://github.com/Tencent/ncnn/issues/1104?email_source=notifications\u0026email_token=AKHKZNRGGBVX6JCYL7BMRATQHCX7HA5CNFSM4ICLHUU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5QTVBA#issuecomment-526465668",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by emailxuchen** [comment]
现在github上版本更新了，编译了没问题




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            emailxuchen
                            
                            
                                
                                    邮箱：emailxuchen@mail.tsinghua.edu.cn
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2019年08月30日 14:04，emailxuchen 写道： 
现在github上版本更新了，编译了没问题




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            emailxuchen
                            
                            
                                
                                    邮箱：emailxuchen@mail.tsinghua.edu.cn
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


在2019年08月30日 13:47，zZTaccount 写道： 请问问题解决了吗？是怎么弄的呢？遇到了同样的问题。。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Tencent/ncnn/issues/1104?email_source=notifications\u0026email_token=AKHKZNRGGBVX6JCYL7BMRATQHCX7HA5CNFSM4ICLHUU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5QTVBA#issuecomment-526465668",
"url": "https://github.com/Tencent/ncnn/issues/1104?email_source=notifications\u0026email_token=AKHKZNRGGBVX6JCYL7BMRATQHCX7HA5CNFSM4ICLHUU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5QTVBA#issuecomment-526465668",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zZTaccount** [comment]
我在编译时没有遇到问题，成功的编译了，并且跑了benchmark也是能够调用GPU的，但是在编译自己的代码时就会报错，
error: ‘get_gpu_device’ is not a member of ‘ncnn’，
请问是我链接出了问题吗，这是cmakelist，您能帮我分析一下是怎么回事么？感谢谢谢

------------------ 原始邮件 ------------------
发件人: "emailxuchen"<notifications@github.com>;
发送时间: 2019年8月30日(星期五) 下午2:05
收件人: "Tencent/ncnn"<ncnn@noreply.github.com>;
抄送: "邹芷桐"<429834658@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Tencent/ncnn] ncnn+vulkan编译出错，请问这是什么问题，怎么解决 (#1104)




 现在github上版本更新了，编译了没问题
 
 
 
 
     
 
 
 
     
     
     
 
 
 
     
         
             
                 
                     
                         
                     
                     
                         
                             emailxuchen
                             
                             
                                 
                                     邮箱：emailxuchen@mail.tsinghua.edu.cn
                                 
                         
                     
                 
             
         
     
 
 
 Signature is customized by Netease Mail Master
 
 
 在2019年08月30日 13:47，zZTaccount 写道： 请问问题解决了吗？是怎么弄的呢？遇到了同样的问题。。
 
 —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
 [
 {
 "@context": "http://schema.org",
 "@type": "EmailMessage",
 "potentialAction": {
 "@type": "ViewAction",
 "target": "https://github.com/Tencent/ncnn/issues/1104?email_source=notifications\u0026email_token=AKHKZNRGGBVX6JCYL7BMRATQHCX7HA5CNFSM4ICLHUU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5QTVBA#issuecomment-526465668",
 "url": "https://github.com/Tencent/ncnn/issues/1104?email_source=notifications\u0026email_token=AKHKZNRGGBVX6JCYL7BMRATQHCX7HA5CNFSM4ICLHUU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5QTVBA#issuecomment-526465668",
 "name": "View Issue"
 },
 "description": "View this Issue on GitHub",
 "publisher": {
 "@type": "Organization",
 "name": "GitHub",
 "url": "https://github.com"
 }
 }
 ] 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nihui** [comment]
> 我在编译时没有遇到问题，成功的编译了，并且跑了benchmark也是能够调用GPU的，但是在编译自己的代码时就会报错， error: ‘get_gpu_device’ is not a member of ‘ncnn’， 请问是我链接出了问题吗，这是cmakelist，您能帮我分析一下是怎么回事么？感谢谢谢
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "emailxuchen"<notifications@github.com>; 发送时间: 2019年8月30日(星期五) 下午2:05 收件人: "Tencent/ncnn"<ncnn@noreply.github.com>; 抄送: "邹芷桐"<429834658@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Tencent/ncnn] ncnn+vulkan编译出错，请问这是什么问题，怎么解决 (#1104) 现在github上版本更新了，编译了没问题 emailxuchen 邮箱：emailxuchen@mail.tsinghua.edu.cn Signature is customized by Netease Mail Master 在2019年08月30日 13:47，zZTaccount 写道： 请问问题解决了吗？是怎么弄的呢？遇到了同样的问题。。 —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#1104?email_source=notifications\u0026email_token=AKHKZNRGGBVX6JCYL7BMRATQHCX7HA5CNFSM4ICLHUU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5QTVBA#issuecomment-526465668", "url": "#1104?email_source=notifications\u0026email_token=AKHKZNRGGBVX6JCYL7BMRATQHCX7HA5CNFSM4ICLHUU2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5QTVBA#issuecomment-526465668", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ] — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

更新ncnn代码，注意 platform.h NCNN_VULKAN 宏是开启的
