### ISSUE TITLE
Run different parts of model on cpu and gpu?

### ISSUE THREAD

**Issue by ItchyHiker** [Tencent/ncnn#1106]
Is there any way to run the first part of my model on cpu, then take out the output of intermediate node, and run the second part of my model on GPU?
I am new to Vulkan. This is what I tried and my program terminate when inference the second part on gpu.
```
ncnn::Extractor ex_cpu = net.create_extractor();
ncnn::Extractor ex_gpu = net.create_extractor();
ex_gpu.set_vulkan_compute(false);
ex_gpu.set_vulkan_compute(true);
ex_cpu.set_light_mode(true);
ex_gpu.set_light_mode(true);
ex_cpu.input("input", inMat);
ex_cpu.extract("middle", middleMat);

ex_gpu.input("middle", middleMat);
ex_gpu.extract("out", outMat);
```
I ask this problem because when I ran my model completely on gpu, the program was terminated for using too much memory. Although run on cpu took **less** memory, the speed is too slow.

Any helpful information or instructions?

**Comment by nihui** [comment]
your code snippet seems fine
try debug your program and retrieve the stack backtrace info

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan
You shall also call create_gpu_instance() and destroy_gpu_instance()
And enable vulkan compute via net.opt.use_vulkan_compute = 1;

Feel free to reopen issue if the problem still occurs.
