### ISSUE TITLE
Reduction.cpp bug

### ISSUE THREAD

**Issue by lvle0222** [Tencent/ncnn#1107]
`mins_ptr[j] = op(mins_ptr[j], ptr[i]);`
165行，这里好像应该是下面这样
`mins_ptr[j] = op(mins_ptr[j], ptr[j]);`

**Comment by lvle0222** [comment]
`const float* ptr1 = b;
 float* outptr = c;`
在binaryop.cpp里，310、311、328、329行应该都有问题，b、c为Mat类型，不能直接给指针赋值，channel返回的是子mat，应该用row函数，另外310、311行计算逻辑我有一些疑问，是b的每行加a产出c吗，如果是这样，a的取数逻辑可能也有问题，
`const float a0 = a[y];
for (int x=0; x<w1; x++)
{
    outptr[x] = op(a0, ptr1[x]);
}
`
应该改成
`const float* a0 = a.row(0);
for (int x=0; x<w1; x++)
{
    outptr[x] = op(a0[x], ptr1[x]);
}
`

**Comment by lvle0222** [comment]
net.cpp中，2084行的extract函数，使用新输入，重复调用的时候，feat并没有重新计算，forward在if范围内，重复调用不会执行if内的代码
`int Extractor::extract(int blob_index, Mat& feat)`

**Comment by nihui** [comment]
> `const float* ptr1 = b; float* outptr = c;`
> 在binaryop.cpp里，310、311、328、329行应该都有问题，b、c为Mat类型，不能直接给指针赋值，channel返回的是子mat，应该用row函数，另外310、311行计算逻辑我有一些疑问，是b的每行加a产出c吗，如果是这样，a的取数逻辑可能也有问题，
> `const float a0 = a[y]; for (int x=0; x<w1; x++) { outptr[x] = op(a0, ptr1[x]); } `
> 应该改成
> `const float* a0 = a.row(0); for (int x=0; x<w1; x++) { outptr[x] = op(a0[x], ptr1[x]); } `

没有问题 float* p = Mat 可以的

a = vector
b = tensor
for each channel i in b
    c.channel(i) = b.channel(i) + a[i]

**Comment by nihui** [comment]
> net.cpp中，2084行的extract函数，使用新输入，重复调用的时候，feat并没有重新计算，forward在if范围内，重复调用不会执行if内的代码
> `int Extractor::extract(int blob_index, Mat& feat)`

使用新输入，重复调用，需要创建新的 Extractor
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#create-new-extractor-for-each-image
