### ISSUE TITLE
[BUG]  reshape.cpp 中的 int Reshape::load_param(FILE* paramfp)

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/ncnn#111]
int Reshape::load_param(FILE* paramfp)
{
    int nscan = fscanf(paramfp, "%d %d %d %d",
                       &w, &h, &c, &permute);

这里应该是
int nscan = fscanf(paramfp, "%d %d %d %d",
                       &c, &w, &h, &permute);

才对吧？

**Comment by onlyygo** [comment]
你是使用的caffe转ncnn模型后遇到的问题吧？我是直接将转换好的ncnn的模型定义文件reshape层的后面三个参数手动调换位置。

**Comment by onlyygo** [comment]
还有，就是这个读取的4个数，但是txt里面只有三个额，奇怪的是ubuntu和android下运行没问题。不过放到win（uwp开发）下到这一步就出错，不知道为什么

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/195193f919e12c669a826ef3e0092223a91a0ee6

手头没有 reshape 的模型可以测试，尚不清楚有没有修复 =_=
最后一个数字代表是否要进行 CHW -> HWC 的转换，只实现了 reshape 成一维的情况，适用在 tensorflow ...

**Comment by Serissa** [comment]
> 你是使用的caffe转ncnn模型后遇到的问题吧？我是直接将转换好的ncnn的模型定义文件reshape层的后面三个参数手动调换位置。

我遇到这个问题了，请问改后的顺序是什么样的？
