### ISSUE TITLE
如何压缩安卓库体积到300K？

### ISSUE THREAD

**Issue by wincle** [Tencent/ncnn#1113]
简介里提到：整体库体积小于 700K，并可轻松精简到小于 300K。
请问采用哪些手段才能将安卓库体积压缩到这个体积呢？目前我只能使安卓库体积达到1.8M。
谢谢

**Comment by nihui** [comment]
这个大小是实际编译为 so 并打包 apk 后的实际大小，单个架构

可以裁剪不需要的 layer，以及禁用 NCNN_STDIO NCNN_STRING

**Comment by wincle** [comment]
好的，谢谢。

**Comment by Channingss** [comment]
@nihui 指的是armv7吧？armv8我刚刚编的master分支，so也有2.2m
