### ISSUE TITLE
Siamese network inference

### ISSUE THREAD

**Issue by arnaudbrejeon** [Tencent/ncnn#1116]
Hi,

let's assume I have a siamese network with 2 inputs, the first input is a query image and the second one is a template image.
If I have N templates, I'd like to precompute the templates part of the network in advance (e.g after loading) and cache the results, so that I save some time each time I receive a new query image.
Is there a way to do this with Extractor?

**Comment by arnaudbrejeon** [comment]
I've looked at the code and what is needed is a way to freeze some blobs to prevent from cleaning them during & after inference.
If other people are interested, I could try to make a pull request.

**Comment by nihui** [comment]
```
Mat input, output;
Mat cached_blob;

ex.input("input", input);

if (cached_blob.empty())
{
    // cache intermediate blob on first run
    ex.extract("blob_to_cache", cached_blob);
}
else
{
    // reuse the cached blob
    ex.input("blob_to_cache", cached_blob);
}

ex.extract("output", output);

```

**Comment by arnaudbrejeon** [comment]
Oh yeah, your solution works best.
Thank you
