### ISSUE TITLE
[BUG] slice forward crash

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/ncnn#112]
slice.cpp forward 函数中
我的proto中的参数如下
Slice            slice2           1 3 to_use1 not_use2 to_use2 not_use22 3 2 8 -233
如下函数：

for (size_t i=0; i<top_blobs.size(); i++)
    {
        int slice = slices_ptr[i];
        if (slice == -233)
        {
            slice = (channels - q) / (top_blobs.size() - i);
        }

当输入的bottom 的  w = 11, h = 11, c =8,  top_blobs.size() = 3
当 i = 2时， q=10
 slice = (channels - q) / (top_blobs.size() - i); 
 slice = -2 ，这个明显不对
下面的 top_blob.create(w, h, slice);   crash

**Comment by nihui** [comment]
slice 的参数是 num_slice 后面接着 num_slice 个数字表示输出的各个 c，最后几个可以 -233 代表平均切分
bottom c=8，slice 的三个输出 c 为 2 + 8 + x，已经超出输入c大小了，所以会 crash

**Comment by cutejerry** [comment]
slice层应该可以根据axis选择从N x C x H x W这0~3个维度中的某一个进行切分吧？目前ncnn好像只支持了按照Channel进行切分，可以加上其它维度吗？

**Comment by huanyingjun** [comment]
是我搞错了，我的caffe模型中axis=2，是对H 进行切分，而ncnn 默认只支持对channel进行切分，所以才会crash。
