### ISSUE TITLE
最新版本ncnn耗时问题

### ISSUE THREAD

**Issue by qiudi0127** [Tencent/ncnn#1121]
升级完最新版本ncnn后，相比于比较老版本，mtcnn的耗时增加了几倍，请问一下是什么原因？

**Comment by nihui** [comment]
你用 benchncnn 跑下看看，是不是多线程设置的不一样

**Comment by qiudi0127** [comment]
@nihui 感谢回复，刚刚发现通过ex.set_num_threads设置多线程后速度明显变快，但是不设置线程时速度又降下来，想请教一下为什么？

**Comment by qiudi0127** [comment]
@nihui 是在android手机端测试，如果不设置mtcnn各网络的线程数，速度会下降很多。

**Comment by nihui** [comment]
之前有个 ncnn::set_default_option 的方法废弃了，改成了直接对 ncnn::Net opt 成员设置

**Comment by qiudi0127** [comment]
@nihui 了解了，多谢。
