### ISSUE TITLE
Onnxruntime_EP

### ISSUE THREAD

**Issue by monishramadoss** [Tencent/ncnn#1124]
Has there been a discussion to make this into an onnxruntime execution provider??? I think it would a useful addition as not many currently supported EPs support mobile devices.

**Comment by nihui** [comment]
no, ncnn will always be a standalone project and do not depend any third-party library or runtime.
you may interest in the DNNLibaray as an onnxruntime option on mobile devices https://github.com/JDAI-CV/DNNLibrary
