### ISSUE TITLE
hi, 最新的Android SDK的tools里已经没有 ant了，所以 ant debug编译不了。。。

### ISSUE THREAD

**Issue by yeRuiHuan** [Tencent/ncnn#1132]
hi, 最新的Android SDK的tools里已经没有 ant了，所以 ant debug编译不了。。。
lybvinci的方法直到 ndk-build都是没有问题的， libs 文件夹会被编译到 ncnn/examples/squeezencnn 下，但是运行 Android Studio project会报错

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tencent.squeezencnn-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.squeezencnn-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libsqueezencnn.so"
```

把
```
sourceSets.main {
jniLibs.srcDirs = ["src/main/libs"]
jni.srcDirs=[]
}
```
改成
```
sourceSets.main {
jniLibs.srcDirs = ["libs"]
jni.srcDirs=[]
}
```
libsqueezencnn.so 还是找不到，不知道如何解决这个lib引用不到的问题。。。。

_Originally posted by @telefire in https://github.com/Tencent/ncnn/issues/9#issuecomment-317815132_

**Comment by yeRuiHuan** [comment]
不知是so库创建过程出错了还是其他的什么原因

**Comment by nihui** [comment]
可以参考我的新example工程
https://github.com/nihui/ncnn-android-squeezenet
