### ISSUE TITLE
编译源码报错:无效的预处理指示 #cmakedefine01,求解

### ISSUE THREAD

**Issue by Roger8** [Tencent/ncnn#1134]
ncnn/src/platform.h:18:2: 错误：无效的预处理指示 #cmakedefine01
 #cmakedefine01 NCNN_STDIO

**Comment by nihui** [comment]
按照wiki指南的方法编译 https://github.com/Tencent/ncnn/wiki/how-to-build
platform.h 是 cmake 生成的

**Comment by Roger8** [comment]
已解。3q

**Comment by hitzhang** [comment]
怎么解的？我就是按照wiki编译的
