### ISSUE TITLE
android平台benchmark测试

### ISSUE THREAD

**Issue by qiudi0127** [Tencent/ncnn#1135]
想问下，在PC端跑benchncnn没问题，但在android端跑就会报错。
![861cbd6c-1908-422c-a379-3880197d8ab0](https://user-images.githubusercontent.com/26405062/61629528-c5db7f80-acb7-11e9-9d3c-7c7f0f752833.png)

**Comment by nihui** [comment]
看起来是你的 shell 坏掉了，重新刷rom，或者换个手机试试看

**Comment by YgRen** [comment]
我在mac上用华为手机P30 Pro 和红米手机都出现此错误。。。

**Comment by nihui** [comment]
也有可能是文件传输问题
你试试看其他程序是不是也是这个情况，比如android ndk自带的gdbserver
