### ISSUE TITLE
difference between vulkan and no_vulkan on WIndows10x64

### ISSUE THREAD

**Issue by laohur** [Tencent/ncnn#1137]
they share one source code.
_`D:\code\ncnn\ncnn-master\no_vulkan\examples\Release>.\squeezenet.exe cat.jpg
 NCNN_VULKAN:  OFF!
283 = 0.308698
332 = 0.281439
281 = [0.114481`]_
_`PS D:\code\ncnn\ncnn-master\vulkan\examples\Release> .\squeezenet.exe cat.jpg
[0 Intel(R) UHD Graphics 630]  queueC=0[1]  queueT=0[1]  memU=0  memDL=0  memHV=0
[0 Intel(R) UHD Graphics 630]  fp16p=1  fp16s=1  fp16a=0  int8s=0  int8a=0
 NCNN_VULKAN:  gpu count 1, using 0
451 = 0.012115
907 = 0.011925
903 = 0.011925`_

1.vulkan result is right,on Nvidia GPU?
2.why result scores are so diffrerent?

__

**Comment by nihui** [comment]
upgrade your graphics driver

intel https://downloadcenter.intel.com/product/80939/Graphics-Drivers

amd https://www.amd.com/en/support

nvidia https://www.nvidia.com/Download/index.aspx
