### ISSUE TITLE
vkEnumerateInstanceExtensionProperties  failed  -3

### ISSUE THREAD

**Issue by yizhaoyanbo** [Tencent/ncnn#1138]
windows10编译ncnn+vulkan的静态库，编译环境VS2015 + cmake3.14 + vulkan1.1.101，显卡型号GTX750TI，编译成功，在本机上运行（CPU或者vulkan）都没问题。

然后我换了台机器测试，运行环境：windows10 + VS2017 + cmake3.15 + vulkan1.1.101, 显卡型号GTX1060，只跑CPU结果没有问题，但是开启vulkan加速后，在load_param()这里崩溃，错误码如下：

vkEnumerateInstanceExtensionProperties  failed  -3

两台机器显卡驱动都更新到了最新，求教， 感谢。

**Comment by liuxy-up** [comment]
我也遇到类似的问题：windows7 64位系统，显卡GTX1080，vs2015+cmake3.13+vulkan1.1.92.1，编译成功，不开启vulkan运行成功，开启vulkan后网络前向可以运行，但从第一层卷积开始输出均为全0，像是load网络参数出错，并且app退出时报访问冲突错误。换另外一台机器win10系统，软件版本一样，出现同样的问题。

**Comment by nihui** [comment]
vkEnumerateInstanceExtensionProperties 错误表示，显卡驱动更新失败了，重装下驱动
我自己用的是 win10 gtx1070 正常
