### ISSUE TITLE
mxnet deconvolution转行后不能运行

### ISSUE THREAD

**Issue by HaoLiuHust** [Tencent/ncnn#1139]
mxnet的deconvolution层能够转换，但是去运行的时候就会报错

**Comment by nihui** [comment]
尝试转换了 gluoncv simple pose 模型，含有 deconvolution，没有发现问题

**Comment by HaoLiuHust** [comment]
@nihui 可以把模型发给你试试么

**Comment by nihui** [comment]
可以提供下参考的 github

**Comment by HaoLiuHust** [comment]
https://pan.baidu.com/s/1O-iv7ZGT8lSDFaPDeRcE9w @nihui 相关的文件我放在云盘了，多谢

**Comment by HaoLiuHust** [comment]
Any update?

**Comment by HaoLiuHust** [comment]
seems there is a elementwise sum has only on bottom blob, its my mistake
