### ISSUE TITLE
Operators doc

### ISSUE THREAD

**Issue by hellocsi** [Tencent/ncnn#1141]
[Wiki](https://github.com/Tencent/ncnn/wiki/operation-param-weight-table) gives operation param weight table used in NCNN.
@nihui Do you have any plan to add a doc to explain these operations like [ONNX Operators.md](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Squeeze) ?
I think this may be helpful for and friendly to new developers.

**Comment by nihui** [comment]
Sorry, I don't have much time to add these details.
In fact, most operation semantics are the same as onnx ones.
The most important difference is that there is no "N" dimension in ncnn, I think.

**Comment by hellocsi** [comment]
@nihui Thank you anyway!

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx


operator doc
https://github.com/Tencent/ncnn/wiki/operators
