### ISSUE TITLE
Build for Linux X86 without OpenMP?

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#1147]
Is it possible to build ncnn for linux X86_64 without the use of OpenMP. 
My use case requires me to only use a single thread during operation. Right now, I have been doing this by setting the environment variable in my shell `export OMP_NUM_THREADS=1` and this does the trick. However, for my use case, I will not have access to the shell. When I try exporting the environment variable using my C++ code (which I may do for my use case), it still seems to use multiple threads: 
```
    char ompEnv[]="OMP_NUM_THREADS=1";
    putenv( ompEnv );
```

Is there some options or flags I can use while compiling ncnn which will build it in single thread mode (and thus not use OpenMP or permanently set `OMP_NUM_THREADS` to 1)?

**Comment by cyrusbehr** [comment]
I managed to solve it by using the following code:
```
omp_set_num_threads(1);
char ompEnv[]="OMP_NUM_THREADS=1";
putenv( ompEnv );
```

**Comment by cyrusbehr** [comment]
However, is there a way to permanently build it without OpenMP / in single thread mode

**Comment by nihui** [comment]
```
cmake -DNCNN_OPENMP=OFF ..
```
