### ISSUE TITLE
编译不通过啊

### ISSUE THREAD

**Issue by HduSy** [Tencent/ncnn#1148]
error LNK2001: 无法解析的外部符号
error LNK2001: 无法解析的外部符号
error LNK2001: 无法解析的外部符号
error LNK2001: 无法解析的外部符号
error LNK2001: 无法解析的外部符号
fatal error LNK1120: 9 个无法解析的外部命令

**Comment by kalcohol** [comment]
i found that your location was Shanghai, so u can go to  @nihui 's office and ask he face to face.

**Comment by tpoisonooo** [comment]
BTW, prepare five SCI as a gift, respectively.

**Comment by ghgggg** [comment]
additionally you'd better bring some gift for nihui's office Security personnel，:) you know usually you can't access

**Comment by kalcohol** [comment]
> additionally you'd better bring some gift for nihui's office Security personnel，:) you know usually you can't access

i do not agree. Date/seeing some one may need some skills.

**Comment by nihui** [comment]
feel free to reopen this issue when you are able to provide more information  :|
