### ISSUE TITLE
CENTOS X86基于MOBILENETV3的模型推理时出现Segmentation fault，使用的是当前的MASTER分支版本。

### ISSUE THREAD

**Issue by yangchengtest** [Tencent/ncnn#1149]
ONNX和转化后的NCNN模型在：
https://github.com/yangchengtest/NCNN_CRASH

**Comment by nihui** [comment]
最新代码已实现 mobilenetv3 模型转换

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
