### ISSUE TITLE
example/squeezencnn运行错误：init返回-1;Fatal signal 11 (SIGSEGV)闪退

### ISSUE THREAD

**Issue by yeRuiHuan** [Tencent/ncnn#1150]
@nihui  你好，我在使用最新的example/squeezencnn + releases/20190611 + ndk r20时，ndk-build出了两个指定ABI下的libsqueezencnn.so库，运行时load_param 和 load_model的ret都返回 -1 ，然后就报了错误：Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)并闪退。我正在试着把AS上的ndk回退到ndk r19，以符合releases/20190611要求的ndk版本。
  我发现我的问题和[issues#177](https://github.com/Tencent/ncnn/issues/117)相似，但似乎并没有看到解决办法？
  另外我注意到github上并没有build.gradle文件，以下是我的build.gradle文件，不知道有没有什么问题？
`apply plugin: 'com.android.application'
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.1"

    defaultConfig {
        applicationId "com.tencent.squeezencnn"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            moduleName "ncnn"
            abiFilters 'armeabi-v7a'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    sourceSets.main {
        jniLibs.srcDirs = ["src/main/libs"]
        jni.srcDirs=[]
    }
} `

**Comment by yeRuiHuan** [comment]
上面的问题解决了，原因是AS报警告的时候没看清，注释掉了一行需要执行的代码，最后导致初始化失败然后崩溃。是MainActivity/initSqueezeNcnn()中的一行代码：
`int byteCode = assetsInputStream.read(param);`
跑通后，load_param和load_model都不再是-1或者0了（是个大于0的数字）,但无论什么图片，结果都是“et_words.txt = 0.001”，这个问题似乎没有人遇到过？

**Comment by yeRuiHuan** [comment]
使用GPU是“et_words.txt = 0.001”，不使用GPU是“et_words.txt = 0.000”

**Comment by yeRuiHuan** [comment]
搞定了，是我自己的错误。在推倒重来之后发现assets文件中的bin和txt文件需要更换（example/squeezencnn/assets里的两个文件内容指示者最终文件的路径，而不是内容）

**Comment by nihui** [comment]
nice！
