### ISSUE TITLE
通过darknet2ncc方式转模型，在编译过程中出现错误！

### ISSUE THREAD

**Issue by rockygao123** [Tencent/ncnn#1151]
在利用darknet2ncnn编译自己的动态库，但是在编译动态库时发生了错误，`CMakeFiles/darknet2ncnn_jni.dir/src/main/cpp/layer/darknet_activation.cpp.o:darknet_activation.cpp:typeinfo for ncnn::DarknetActivation: error: undefined reference to 'typeinfo for ncnn::Layer'

CMakeFiles/darknet2ncnn_jni.dir/src/main/cpp/layer/darknet_shortcut.cpp.o:darknet_shortcut.cpp:typeinfo for ncnn::DarknetShortcut: error: undefined reference to 'typeinfo for ncnn::Layer'

CMakeFiles/darknet2ncnn_jni.dir/src/main/cpp/layer/yolov1_detection.cpp.o:yolov1_detection.cpp:typeinfo for ncnn::Yolov1Detection: error: undefined reference to 'typeinfo for ncnn::Layer'

CMakeFiles/darknet2ncnn_jni.dir/src/main/cpp/layer/yolov3_detection.cpp.o:yolov3_detection.cpp:typeinfo for ncnn::Yolov3Detection: error: undefined reference to 'typeinfo for ncnn::Layer'

clang++: error: linker command failed with exit code 1 (use -v to see invocation)
`

libncnn.a我是link的，

**Comment by nihui** [comment]
因为 android/ios libncnn.a 没有开启 rtti exceptions，所以编译 so 时也要这些编译参数
```
-fno-rtti -fno-exceptions
```
