### ISSUE TITLE
Pooling type  为max时，pad_value为 -FLT_MAX

### ISSUE THREAD

**Issue by zhewang95** [Tencent/ncnn#1152]
见这一行：　https://github.com/Tencent/ncnn/blob/77c1f361b7c90fc87ce2c54f78b186e26e78068b/src/layer/pooling.cpp#L107
设置为-FLT_MAX合理吗？
pytorch中这种情况pad_value为0

**Comment by nihui** [comment]
使用 -FLT_MAX 可以确保 pad_value 的值不会影响 max
如果 pad_value 为 0，那么附近的负数会被影响，导致 max 结果为 0

**Comment by YunyiGUANG** [comment]
这种是不是设成-infinity更合理？
