### ISSUE TITLE
on rk3399

### ISSUE THREAD

**Issue by bjthemost** [Tencent/ncnn#1153]
请问，如何能在rk3399上 linux环境下（不是android）让ncnn最新版本能用上gpu呢？
#28的37行 貌似已经不是原来开关的位置了。
谢谢

**Comment by kalcohol** [comment]
UNLESS ROCKCHIP RELEASE VULKAN DRIVER FOR IT'S GPU, ncnn will not able to run on gpu of RK.
RK said: vulkan, Who cares?

**Comment by bjthemost** [comment]
hahaha......
thank you


发自我的 iPhone

> 在 2019年7月28日，23:01，kalcohol <notifications@github.com> 写道：
> 
> RK said: vulkan, Who cares?

**Comment by nihui** [comment]
The latest ncnn now support rk3399 gpu inference on android 9.0
with the vulkan driver here https://github.com/rockchip-toybrick/vendor-rockchip-common-9.0/tree/master-9.0/gpu

**Comment by bjthemost** [comment]
thank you 
多谢

发自我的iP6+1

**Comment by zhaokewei** [comment]
rk3399用gpu的话速度会快一些吗？
