### ISSUE TITLE
1D max Pooling

### ISSUE THREAD

**Issue by arnaudbrejeon** [Tencent/ncnn#1154]
Hi,

I use a 1D maxpooling and the ONNX declaration is:
kernel_shape = 4
strides = 4
pads=0,0

from that the conversion to nccn leads to:
Pooling          81                       1 1 80 81 0=0 1=4 2=4 3=0 13=0 5=1

and the code will think that the kernel and stride are (4,4) and (4,4) because:
    kernel_h = pd.get(11, kernel_w);
and
    stride_h = pd.get(12, stride_w);

Shouldn't the conversion give the following in this case?
Pooling          81                       1 1 80 81 0=0 1=4 2=4 3=0 **11=1 12=1** 13=0 5=1

Arnaud

**Comment by nihui** [comment]
pooling1d is now supported, convert your model using pnnx, it will work out of the box

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
