### ISSUE TITLE
Targeted OS version does not support use of thread local variables in _get_unique_idv for architecture x86_64

### ISSUE THREAD

**Issue by JerryMR** [Tencent/ncnn#1155]
android ios 预编译库 20190611 bade132中的ncnn.framework.zip 是 ios 的静态库(armv7 + arm64 + i386 + x86_64)

在Deployment Target8.0的模拟器中编译失败，Targeted OS version does not support use of thread local variables in _get_unique_idv for architecture x86_64 #1155

**Comment by nihui** [comment]
所以请用新版的模拟器吧...
ios 10 应该ok
