### ISSUE TITLE
example ex.extract(squeezenet_v1_1_param_id::BLOB_prob, out);出现崩溃

### ISSUE THREAD

**Issue by jabinwang** [Tencent/ncnn#1156]
SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x31004)) 运行到 ex.extract时候回出现这种错误，模型用的是squeezenet_v1

**Comment by nihui** [comment]
同样的问题？
https://github.com/Tencent/ncnn/issues/1150

**Comment by yeRuiHuan** [comment]
可以说的具体一些吗，比如给出一些关键文件

**Comment by nihui** [comment]
可以参考这个工程
https://github.com/nihui/ncnn-android-squeezenet
