### ISSUE TITLE
使用load_param加载.param文件之后，ex.input("data", in); ex.extract("prob", out)，结果是load_param和load_model返回0，result一直是tench,Tinca tinca=0

### ISSUE THREAD

**Issue by yeRuiHuan** [Tencent/ncnn#1157]
使用自己的模型得到两个文件：my.param和my.bin，用load_param(FILE *fp)的方式读这两个文件，然后在[使用指北](https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet)上看到要用ex.input("data", in); ex.extract("prob", out)分别取代之前的ex.input(yolov3_mobilenetv2_coco::BLOB_data, in)和ex.extract(yolov3_mobilenetv2_coco::BLOB_prob, out)，但这样运行后发现load_param和load_model都返回0，并且运行的时间异常减少了许多，结果也一直是tench,Tinca tinca=0。
冒昧问一句，有谁可以提供现成的ncnn2mem可执行文件吗？我自己搞了半天没编译出来。

**Comment by yeRuiHuan** [comment]
上面的结果是我把.param和.bin放到手机公共目录下的app私有目录，并在c中用fopen()的方式读取的。今天我试着直接在MainActivity.java中initSqueezeNcnn函数中把.param.bin和.bin文件替换掉读入，发现load_param和load_model返回-1，更惨。
请问有谁知道该怎么读取.param和.bin文件吗？

**Comment by yeRuiHuan** [comment]
搞定了，上面第一个方法是对的，只是我的模型输出的内容跟SqueezeNcnn的不一样罢了，Init是对的

**Comment by twmht** [comment]
@yeRuiHuan 

你有試過用 int load_param(const unsigned char* mem) ?

https://github.com/Tencent/ncnn/issues/1208

**Comment by yeRuiHuan** [comment]
@twmht 有的，后来就是用load_param（const unsigned char * mem）函数成功初始化了

**Comment by wtxfrancise** [comment]
@yeRuiHuan  load_param（const unsigned char * mem） 这个返回结果为0 ，是正确的吗？

**Comment by yeRuiHuan** [comment]
返回0是失败的
