### ISSUE TITLE
convolution and pooling layers crashed with kernel < stride

### ISSUE THREAD

**Issue by Corea** [Tencent/ncnn#116]
Sometimes we need to build convolution or pooling layer with kernel=1, stride=2 and  padding=-233(SAME). But now ncnn is crashed with this settings, it should be fixed. 

I guessed checking arguments of `copy_make_border` would fix this issue, but size is not appropriate after then.

**Comment by nihui** [comment]
can not reproduce this crash with the following sample on both pc and android platform
using the latest code on git
```
int main(int argc, char *argv[])
{
    using namespace ncnn;

    int inw = 210;
    int inh = 133;
    int inc = 3;
    int outc = 8;

    int ksize = 1;
    int stride = 2;
    int pad = -233;

#if __ARM_NEON
    Convolution_arm conv;
#else
    Convolution conv;
#endif
    conv.num_output = outc;
    conv.kernel_size = ksize;
    conv.dilation = 1;
    conv.stride = stride;
    conv.pad = pad;
    conv.bias_term = 0;
    conv.weight_data_size = outc*inc*ksize*ksize;

    Mat bottom(inw, inh, inc);
    Mat kernel(conv.weight_data_size);

    conv.weight_data = kernel;

    Mat top;
    conv.forward(bottom, top);

    int outw = top.w;
    int outh = top.h;
    printf("outw is %d, outh is %d\n", outw, outh);
}
```

**Comment by Corea** [comment]
Because this problem is related to memory violation, so you can check this problem with Valgrind. Precisely, the crash will be raised in function `copy_make_border_image` due to `src.w > dst.w` or `src.h > dst.h`.

**Comment by nihui** [comment]
please provide the shape( w h c ) of the bottom blob which raises this problem

**Comment by Corea** [comment]
My settings were w=160, h=160 and c=20. I'm not sure about convolution layer now, but you can check on pooling layer with option `-fsanitize=address` for gcc. I can reproduce the crash with this code. 

```cpp
#include "mat.h"
#include "layer/pooling.h"

int main(int argc, char *argv[])
{
    using namespace ncnn;

    int inw = 160;
    int inh = 160;
    int inc = 40;
    int outc = 40;

    int ksize = 1;
    int stride = 2;
    int pad = -233;

    Pooling pool;
    pool.pooling_type = 0;
    pool.kernel_size = ksize;
    pool.global_pooling = 0;
    pool.stride = stride;
    pool.pad = pad;

    Mat bottom(inw, inh, inc);

    Mat top;
    pool.forward(bottom, top);

    int outw = top.w;
    int outh = top.h;
    printf("outw is %d, outh is %d\n", outw, outh);

    return 0;
}
```
