### ISSUE TITLE
Vulkan compile error

### ISSUE THREAD

**Issue by wincle** [Tencent/ncnn#1161]
error: unknown type name 'VkMat'

When compile android sdk with Vulkan, occur many errors like this.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android
perhaps you missed the "-DNCNN_VULKAN=ON" arguments in your cmake command

**Comment by wincle** [comment]
I'm sure I have added it to my Cmake command, here is my cmd line:
cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..

**Comment by wincle** [comment]
> https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android
> perhaps you missed the "-DNCNN_VULKAN=ON" arguments in your cmake command

I'm sure I have added it to my Cmake command, here is my cmd line:
cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..

**Comment by wincle** [comment]
> Scanning dependencies of target ncnn
> [ 76%] Building CXX object src/CMakeFiles/ncnn.dir/command.cpp.o
> [ 76%] Building CXX object src/CMakeFiles/ncnn.dir/allocator.cpp.o
> [ 76%] Building CXX object src/CMakeFiles/ncnn.dir/blob.cpp.o
> [ 76%] Building CXX object src/CMakeFiles/ncnn.dir/cpu.cpp.o
> [ 76%] Building CXX object src/CMakeFiles/ncnn.dir/gpu.cpp.o
> [ 77%] Building CXX object src/CMakeFiles/ncnn.dir/layer.cpp.o
> [ 77%] Building CXX object src/CMakeFiles/ncnn.dir/mat.cpp.o
> [ 77%] Building CXX object src/CMakeFiles/ncnn.dir/mat_pixel.cpp.o
> In file included from /Users/wangchao67/Github/ncnn/src/layer.cpp:27:
> In file included from /Users/wangchao67/Github/ncnn/build-android-armv7/src/layer_declaration.h:7:
> /Users/wangchao67/Github/ncnn/src/layer/vulkan/absval_vulkan.h:30:33: error: unknown type name 'VkMat'
>     virtual int forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& opt) const;
>                                 ^
> /Users/wangchao67/Github/ncnn/src/layer/vulkan/absval_vulkan.h:30:57: error: unknown type name 'VkCompute'
>     virtual int forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& opt) const;
>                                                         ^
> /Users/wangchao67/Github/ncnn/src/layer/vulkan/absval_vulkan.h:33:5: error: unknown type name 'Pipeline'
>     Pipeline* pipeline_absval;

Here is the part of my compile output.

**Comment by nihui** [comment]
try building in a clean build workspace folder
besides, make sure the "NCNN_VULKAN" macro is defined as 1 in your build/src/platform.h header generated by cmake

**Comment by wincle** [comment]
> try building in a clean build workspace folder
> besides, make sure the "NCNN_VULKAN" macro is defined as 1 in your build/src/platform.h header generated by cmake

Building in a clean build folder and the "NCNN_VULKAN" is defined as 1 in build/src/platform.h, but still got the error.

**Comment by nihui** [comment]
it's quite strange
perhaps another platform.h file exists or system environment depended
you may need a clean operating system and then retry building

**Comment by wincle** [comment]
> it's quite strange
> perhaps another platform.h file exists or system environment depended
> you may need a clean operating system and then retry building

You are right ! I have add ncnn sdk to my system library and include path, it cause when building use another platform.h file, you are so smart!
