### ISSUE TITLE
find_blob_index_by_name data failed and find_blob_index_by_name detection_out failed in onnx2ncnn converted model.

### ISSUE THREAD

**Issue by rahulsharma11** [Tencent/ncnn#1164]
Hi, I am using my onnx-ssd-detector model with one of the example. It throws error-
find_blob_index_by_name data failed 
find_blob_index_by_name detection_out failed .

However this error is resolved in caffe-models by using "upgrade_net_proto_text/binary". 
But here i have used onnxsimplifier still it throws error as above.
Any suggestion?
Thanks.

**Comment by nihui** [comment]
usually, the blob names in onnx model are formatted as a number string, such as "201" "322" etc
you can figure out them in your param file

**Comment by rahulsharma11** [comment]
Thanks.

**Comment by snehabhapkar10** [comment]
@rahulsharma11 , How did you solve this issue ?

**Comment by rahulsharma11** [comment]
@snehabhapkar10 , There is string in code like "input_layer"/"output_layer" which correspond to input and output node of NN model. Replace that with the input/ouput numeric values in your onnx model.

**Comment by snehabhapkar10** [comment]
@rahulsharma11 ,How to replace input and output values(as onnx model is in binary form) can you please me how I am new to this.

**Comment by jianbaba** [comment]
@rahulsharma11 hello，would you tell me where is the "input_layer"/"output_layer" ？I don't know where it is?

**Comment by rahulsharma11** [comment]
As an example in "https://github.com/Tencent/ncnn/blob/master/examples/mobilenetssd.cpp"
There is a section in code-
    ex.input("data", in);
    ncnn::Mat out;
    ex.extract("detection_out",out);

You need to change these strings("data", "detection_out") according to the digit in your onnx-model (input-digit and output-digit) in param file.

**Comment by jianbaba** [comment]
thanks very much！I met the error when i convert model to int8 ，https://github.com/Tencent/ncnn/tree/master/tools/quantize，do you know why？ @rahulsharma11

**Comment by jianbaba** [comment]
下载了最近的ncnn版本，现在解决了谢谢

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
