### ISSUE TITLE
语义分割模型转化为ncnn后在pc和arm上都很慢

### ISSUE THREAD

**Issue by mengdong824** [Tencent/ncnn#1166]
语义分割模型icnet转为ncnn后，和caffe用cpu推理时间作比较，在pc上慢了一倍多，嵌入式arm平台上慢了好几倍。

**Comment by nihui** [comment]
可能是用了比较多的 deconvolution？建议改为 upsampling + conv

**Comment by mengdong824** [comment]
> 可能是用了比较多的 deconvolution？建议改为 upsampling + conv

没有使用deconvolution层，用的时interp层

**Comment by nihui** [comment]
编译时没有开启 neon 吗？
观察下编译过程中，是不是 src/layer/arm/xxxx_arm.cpp

**Comment by mengdong824** [comment]
没有使用deconvolution层，用的是interp层


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: nihui <notifications@github.com>
发送时间: 2019年8月2日 15:53
收件人: Tencent/ncnn <ncnn@noreply.github.com>
抄送: mengdong824 <312573315@qq.com>, Author <author@noreply.github.com>
主题: 回复：[Tencent/ncnn] 语义分割模型转化为ncnn后在pc和arm上都很慢 (#1166)




可能是用了比较多的 deconvolution？建议改为 upsampling + conv

**Comment by ABlueLight** [comment]
原模型的耗时时长多少，在cpu下还是gpu下什么框架跑得呢

**Comment by mengdong824** [comment]
> 原模型的耗时时长多少，在cpu下还是gpu下什么框架跑得呢

在cpu下跑，arm下，转ncnn速度慢到1500ms，后面尝试mnn速度120ms

**Comment by Hoogck** [comment]
> 编译时没有开启 neon 吗？
> 观察下编译过程中，是不是 src/layer/arm/xxxx_arm.cpp

我的编译是加载了 layer/arm/XXX_arm.cpp：
[ 13%] Building CXX object src/CMakeFiles/ncnn.dir/layer/arm/batchnorm_arm.cpp.o
[ 19%] Building CXX object src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o

 85%] Building CXX object src/CMakeFiles/ncnn.dir/layer/arm/hardsigmoid_arm.cpp.o
[ 89%] Building CXX object src/CMakeFiles/ncnn.dir/layer/arm/hardswish_arm.cpp.o

但是移植后速度也还是很慢，800*800的单张要1.5s，227*227大概500ms内。

**Comment by nihui** [comment]
ncnn最新版本已经优化了很多，可以更新试试，如有问题，可 reopen issue 继续交流

**Comment by cillayue** [comment]
> Author
我的deeplabv3++,输入wh:816*612; cpu环境，NCNN 推理2500ms。。。MNN 推理 3000ms，这速度感觉不正常啊

**Comment by nihui** [comment]
> > Author
> > 我的deeplabv3++,输入wh:816*612; cpu环境，NCNN 推理2500ms。。。MNN 推理 3000ms，这速度感觉不正常啊

可以算一下模型的 FLOPS，结合硬件能力评估
