### ISSUE TITLE
Failed to build iOS on MacOSX using xcode

### ISSUE THREAD

**Issue by JerryMR** [Tencent/ncnn#1167]
执行 cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -
---------
出现下面的错误
DIOS_PLATFORM=OS ..
-- CMAKE_TOOLCHAIN_FILE = /Users/jinyongfeng/Desktop/ncnn/toolchains/ios.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /Users/jinyongfeng/Desktop/ncnn/build-ios/install
-- Building with Xcode version: 
-- Configuring iOS build for platform: OS, architecture(s): armv7;armv7s;arm64
CMake Error at toolchains/ios.toolchain.cmake:211 (message):
  Please make sure that Xcode is installed and that the toolchainis pointing
  to the correct path.  Please run:sudo xcode-select -s
  /Applications/Xcode.app/Contents/Developerand see if that fixes the problem
  for you.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.15/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:20 (project)

CMake Error at toolchains/ios.toolchain.cmake:215 (message):
  Invalid CMAKE_OSX_SYSROOT: does not exist.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.15/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:20 (project)

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by nihui** [comment]
```
Please make sure that Xcode is installed and that the toolchainis pointing
to the correct path. Please run:sudo xcode-select -s
/Applications/Xcode.app/Contents/Developerand see if that fixes the problem
for you.
```

if you installed a very recent version of xcode
try update the toolchain file with https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake
