### ISSUE TITLE
ONNX２ＮＣＮＮ

### ISSUE THREAD

**Issue by lxb324** [Tencent/ncnn#1168]
转换ＯＮＮＸ模型到ＮＣＮＮ出现如下：
＂ReduceMean not supported yet!
  # keepdims=0＂
然后在ＮＣＮＮ中重写ＲｅｄｕｃｅＭｅａｎＬａｙｅｒ，但是在onnx2ncnn.cpp中不知道怎么加入该层的解析信息．
麻烦能更新一下ＲｅｄｕｃｅＭｅａｎＬａｙｅｒ（reductionlayer的一种)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/issues/1092
和这里同样的模型？

**Comment by lxb324** [comment]
不是，我自己设计的模型，torch.mean函数转为onnx为ReduceMean，然后不能转换为ＮＣＮＮ

**Comment by nihui** [comment]
ReduceMean added in https://github.com/Tencent/ncnn/commit/04b4b023249865ae01befe4170a873d5f2ec33f8

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
