### ISSUE TITLE
top, bottom, right, left padding in covoluition

### ISSUE THREAD

**Issue by andreistirb** [Tencent/ncnn#1169]
Hello, 

Will there be taken into consideration a convolution implementation in which all directions (top, bottom, left, right) of the padding can be set?

Currently I suspect that ncnn does not work with inputs that are not square. If I am wrong please tell me how can I set different padding for left, right, top, bottom. I saw that with pooling it is possible, so I guess it can be made with convolution, too.

Thank you,
Andrei

**Comment by nihui** [comment]
asymmetric padding implemented in
https://github.com/Tencent/ncnn/commit/9a6ee37eefa753fd5a45ee83de3dea8619e3b682

and onnx converter in
https://github.com/Tencent/ncnn/commit/18833c92861300a731047619fbffef4cd8ac47c2

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
