### ISSUE TITLE
How to run benchmarks on iOS?

### ISSUE THREAD

**Issue by MingSun-Tse** [Tencent/ncnn#1171]
I have got through the compilation. Everything goes fine and in the `benchmark` dir, there is `benchncnn`. How should I do benchmarks on an iOS phone? Thanks in advance :D

**Comment by nihui** [comment]
I use a jailbreaked ios device, and run benchncnn in shell

**Comment by laohur** [comment]
> I use a jailbreaked ios device, and run benchncnn in shell

How？
