### ISSUE TITLE
facenet在最新版的ncnn中可以正常运行，在2018年4月的ncnn版本中结果是错误的。是out的提取方式改变了吗？

### ISSUE THREAD

**Issue by JIANGYP42** [Tencent/ncnn#1172]

**Comment by JIANGYP42** [comment]
最新版ncnn中结果正确，其中out.w=128,out.h=1,out.c=1：
    ex.input("data", img_);
    ncnn::Mat out;
    ex.extract("fc1", out);
    feature_out.resize(128);
    for (int j = 0; j < 128; j++)
    {
        feature_out[j] = out[j];
    }
但是在2018版中，如果依然使用上述代码，结果是错误的，并且out.w=1,out.h=1,out.c=128。
如果把代码改成：
    ex.input("data", img_);
    ncnn::Mat out;
    ex.extract("fc1", out);
    feature_out.resize(128);
    for (int j = 0; j < 128; j++)
    {
        const float* feat = out.data + out.cstep * j;
        feature_out[j] = feat[0];
    }
结果依然不对。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#blob-may-have-channel-gap
参考下这个

**Comment by JIANGYP42** [comment]
我在新版本ncnn中正常运行了，是不是说明我的模型kernel weight/ RGB顺序 /图片预处理以及 blob name等都是正确的？换到旧版本以后，为什么就不对了呢？

**Comment by nihui** [comment]
既然新版本能解决问题，就用新版本吧 w
