### ISSUE TITLE
int8量化后耗时变多

### ISSUE THREAD

**Issue by SophieChang66** [Tencent/ncnn#1173]
在arm cortex_a53上，一个分类的模型量化后，耗时反而增加一点，是aarch64上的int8 优化还不完善吗？希望答疑一下，谢谢~提供的量化后的googlenet耗时是减少了，eye, yawn和phone都是简单的二分类模型，下面是耗时：
loop_count = 10
num_threads = 1
powersave = 0
gpu_device = -1
                 eye  min =   10.20  max =   11.54  avg =   10.69
            eye_int8  min =   12.52  max =   13.02  avg =   12.67
                yawn  min =    3.11  max =    3.46  avg =    3.24
           yawn_int8  min =    2.84  max =    3.03  avg =    2.93
               phone  min =    9.46  max =    9.92  avg =    9.67
          phone_int8  min =    9.38  max =    9.92  avg =    9.67
          squeezenet  min =  370.12  max =  376.07  avg =  372.74
     squeezenet_int8  min =  251.49  max =  254.62  avg =  252.69
           mobilenet  min =  468.59  max =  472.60  avg =  470.80
      mobilenet_int8  min =  407.66  max =  411.77  avg =  408.82
           googlenet  min = 1093.59  max = 1099.22  avg = 1095.61
      googlenet_int8  min =  809.53  max =  816.34  avg =  812.59
        my_googlenet  min = 1097.45  max = 1102.68  avg = 1099.94
   my_googlenet_int8  min =  806.59  max =  812.14  avg =  809.77
            resnet18  min =  887.87  max =  891.38  avg =  889.78
       resnet18_int8  min =  756.76  max =  764.57  avg =  760.18

**Comment by BUG1989** [comment]
@chengtingting 你能说下模型的backbone吗？建议如下：

- 合并BN
- 开启requant

**Comment by chengtingting** [comment]
谢谢回复！很简单的模型，融合了BN，融合后耗时就会下降一点，融合后再量化，耗时下降了20%左右

**Comment by chengtingting** [comment]
> @chengtingting 你能说下模型的backbone吗？建议如下：
> 
> * 合并BN
> * 开启requant

谢谢回复！很简单的模型，融合了BN，融合后耗时就会下降一点，融合后再量化，耗时下降了20%左右

**Comment by nihui** [comment]
感谢支持w

**Comment by twmht** [comment]
@nihui 

是不是要提供一個量化的 squeezenet 的 model，還有量化的過程，我這裡量化完後的 int8 速度並沒有提升 https://github.com/Tencent/ncnn/tree/master/tools/quantize

**Comment by BUG1989** [comment]
@twmht 请问你用的什么arm平台呀

**Comment by twmht** [comment]
@BUG1989 

我是用跑在手機上的，CPU 是 https://www.qualcomm.com/products/snapdragon-820-mobile-platform

Qualcomm Snapdragon 820
--




Qualcomm Snapdragon 820
--



Qualcomm Snapdragon 820
--




Qualcomm Snapdragon 820
--

**Comment by twmht** [comment]
@BUG1989 

我這裡測是是用 mobilenetV2，用 fp32 跟 int8 跑起來速度沒什麼差異

**Comment by Rainy000** [comment]
@twmht  请问你找到原因了吗，我也是量化成int8后在A53 上跑没速度提升，甚至有轻微增加。。
