### ISSUE TITLE
ncnn on rockpro64(rk3399) with vulkan support.

### ISSUE THREAD

**Issue by rahulsharma11** [Tencent/ncnn#1175]
Hi, I am able to run mobilenetessd and other examples successfully on rockpro64 board. (OS-ubuntu18.04).

I want to use integrated GPU (MALI T-860) now to get some more decent results.
I followed following steps for the same-
1) installation of vulkan (sudo apt-get install libvulkan-dev)
2) glslang installation (git clone --depth=1 https://github.com/KhronosGroup/glslang.git).
code compiled successfully with NCNN_VULKAN=1.
But while running the squeezenet example, it throws "Segmentation fault".
**vkEnumeratePhysicalDevices failed -3
Segmentation fault**

Note- i also built all things on my laptop (nvidia GPU) OS- Ubuntu18.04. 
and followed- ("https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux-x86").
Compiled done but again while running the squeezenet example-"Segmentation Fault".
**[0 GeForce 930M]  queueC=0[16]  queueT=1[1]  memU=4294967295  memDL=7  memHV=9
[0 GeForce 930M]  fp16p=1  fp16s=1  fp16a=0  int8s=0  int8a=0
[1 Intel(R) HD Graphics 5500 (Broadwell GT2)]  queueC=0[1]  queueT=0[1]  memU=0  memDL=0  memHV=0
[1 Intel(R) HD Graphics 5500 (Broadwell GT2)]  fp16p=1  fp16s=0  fp16a=0  int8s=0  int8a=0
Segmentation fault (core dumped)**

I have checked few posts regarding this but not able to find solution.
Any other requirements need to be done for both the above points?

Thanks.

**Comment by nihui** [comment]
Unless Rockchip release a new RK3399 graphics driver which supports vulkan api, the rk3399 platform is not a vulkan capable device.

PC platform should work fine, try upgrading your graphics driver

**Comment by rahulsharma11** [comment]
Thanks.

**Comment by sebastianfelipe** [comment]
Could NanoPi Neo4 run Vulkan instead? I think it has preinstalled a vulkan and can compiled everything. But I have the same problem with vkEnumeratePhysicalDevices.

**Comment by nihui** [comment]
The latest ncnn now support rk3399 gpu inference on android 9.0
with the vulkan driver here github.com/rockchip-toybrick/vendor-rockchip-common-9.0/tree/master-9.0/gpu

**Comment by sebastianfelipe** [comment]
Is there vulkan driver for linux?
