### ISSUE TITLE
转NCNN之后，softmax得出的结果为负数，查看了最后的size也不对，求教可能是什么问题。

### ISSUE THREAD

**Issue by zsmj610** [Tencent/ncnn#1178]
使用预训练好的caffemodel来做inference没问题，但是转ncnn之后，使用C++获取到的预测prob为负数，是怎么回事呢，求解。

**Comment by zsmj610** [comment]
查看了最后输出的size，我本身是而分类，所以size也应该是2 。 但结果size却变成好几千了

**Comment by Teragump** [comment]
你的版本是最新版吗，如果是比较旧的版本，softmax层的实现对于axis参数的实现中h轴和w轴的处理是写反了的，尝试直接改下生成的param文件中softmax层axis参数跑跑看，参考https://github.com/Tencent/ncnn/commit/d85775fbcd92f46acd5a64c9edeba7d83d49ecac

**Comment by zsmj610** [comment]
问题解决了，谢谢回复

**Comment by zhixianGuo** [comment]
@zsmj610 你好，你这个是什么原因，怎么解决的？

**Comment by zsmj610** [comment]
> @zsmj610 你好，你这个是什么原因，怎么解决的？

我当时由于系统原因，根据id取的层取错了，没有取到softmax层，所以得出来的结果是错的
