### ISSUE TITLE
How about replacing float with half in neon ?

### ISSUE THREAD

**Issue by peyer** [Tencent/ncnn#1180]
@nihui Recently, I am considering that use half data type in neon(__fp16) to speed up inference.
Would you have plan to support neon with half data type?
ps: To support neon with half data type for small organization is so arduous for me!

**Comment by nihui** [comment]
fp16 neon inference is only supported on the latest armv8.2 chips, however I don't own one at the moment.
the fp16 neon optimization won't be ready soon in the near several months
