### ISSUE TITLE
ncnn 有类似下面这个函数没？ warpAffine

### ISSUE THREAD

**Issue by bjthemost** [Tencent/ncnn#1181]
void warpAffine(InputArray src, OutputArray dst, InputArray M, Size dsize, int flags=INTER_LINEAR, intborderMode=BORDER_CONSTANT, const Scalar& borderValue=Scalar()) 
-------------------
另外多线程 有没有 纯C++的code 。
谢谢
z

**Comment by BUG1989** [comment]
1、仿射变换暂时没有
2、src/layer路径下的就是纯c++的code

**Comment by bjthemost** [comment]
thank you 
close


发自我的 iPhone

**Comment by nihui** [comment]
好像 bug1989 写过一个精简的 warpaffine.cpp

**Comment by BUG1989** [comment]
基于网上一个精简版本opencv修改的，速度也就提升x1.5-x2.0，如果有需要，后面我放出来

**Comment by bjthemost** [comment]
哦？我嗅嗅去
谢
z

发自我的 iPhone

**Comment by bjthemost** [comment]
@BUG1989  速度不是很重要，只要能替换他就可以 谢谢

**Comment by jianbaba** [comment]
@BUG1989 您好，请问针对于ncnn版本的warpAffine函数有开源出来么？我现在做的移动端不能使用opencv，所以需要ncnn版本的warpAffine函数进行对齐。

**Comment by bjthemost** [comment]
还没有看到 我已经放弃了


发自我的 iPhone

**Comment by nihui** [comment]
warpaffine 函数最新代码已经实现啦~

**Comment by xzou999** [comment]
最新版本代码里函数get_affine_transform得到的仿射变换矩阵似乎不太准确，我试着用该函数以及实时获取的5个人脸关键点得到仿射变换矩阵，用该矩阵的数据创建一个新的基于opencv的Mat类型对象，然后再带入opencv的warpAffine函数去对人脸图片做仿射变换，最后送入人脸识别网络后识别率比较低。而同样的实时获取的5个关键点，用opencv的estimateAffine2D函数去获取仿射变换矩阵后，再带入opencv的warpAffine函数去对人脸图片做仿射变换，最后送入识别网络后识别率就比较高。

**Comment by nihui** [comment]
> 最新版本代码里函数get_affine_transform得到的仿射变换矩阵似乎不太准确，我试着用该函数以及实时获取的5个人脸关键点得到仿射变换矩阵，用该矩阵的数据创建一个新的基于opencv的Mat类型对象，然后再带入opencv的warpAffine函数去对人脸图片做仿射变换，最后送入人脸识别网络后识别率比较低。而同样的实时获取的5个关键点，用opencv的estimateAffine2D函数去获取仿射变换矩阵后，再带入opencv的warpAffine函数去对人脸图片做仿射变换，最后送入识别网络后识别率就比较高。

src和dst反了？
ncnn的warpaffine默认是inverse的

**Comment by bjthemost** [comment]
thank you  @nihui

**Comment by ShiquanYu** [comment]
@nihui @BUG1989 测试了一下warpafine_c3比opencv慢了一倍，跪求一个neon版本orz

**Comment by nihui** [comment]
> @nihui @BUG1989 测试了一下warpafine_c3比opencv慢了一倍，跪求一个neon版本orz

对的，还没有优化呢， qwq

**Comment by ShiquanYu** [comment]
> > @nihui @BUG1989 测试了一下warpafine_c3比opencv慢了一倍，跪求一个neon版本orz
> 
> 
> 
> 对的，还没有优化呢， qwq

up回复好快，up加油*⸜( •ᴗ• )⸝*

**Comment by nihui** [comment]
> > > @nihui @BUG1989 测试了一下warpafine_c3比opencv慢了一倍，跪求一个neon版本orz
> > 
> > 
> > 对的，还没有优化呢， qwq
> 
> up回复好快，up加油*⸜( •ᴗ• )⸝*

你要不要来试试看写个优化呀

**Comment by ShiquanYu** [comment]
> > > > @nihui @BUG1989 测试了一下warpafine_c3比opencv慢了一倍，跪求一个neon版本orz
> 
> > > 
> 
> > > 
> 
> > > 对的，还没有优化呢， qwq
> 
> > 
> 
> > up回复好快，up加油*⸜( •ᴗ• )⸝*
> 
> 
> 
> 你要不要来试试看写个优化呀

我想，，但是我的理智告诉我我不会QAQ，up啥时候直播下指导neon和vulkan
| ᴥ•́ )✧

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/2604

**Comment by nihui** [comment]
最新的release已对warpaffine做了arm优化
