### ISSUE TITLE
OpenCV float 型 单通道 Mat如何输入ncnn

### ISSUE THREAD

**Issue by ghuiii** [Tencent/ncnn#1182]
我这里需要将opencv的一个单通道（y) float型数据输入nccn：处理过程如下：

1. 将bitmap -> cv:Mat rgba_mat
2. rgba_mat -> yCrCb_mat
3. 从ycrcb_mat中提取y通道mat y_mat
4. 将y_mat做缩放 y_mat.convertTo(y_float_mat, CV_32FC1, 1/255.f);

以上过程都是通过opencv来处理的，而且确定没问题(已在另一个深度学习框架上验证无问题)

现在的问题是如何将这个opencv格式的y_float_mat转为ncnn的mat输入

我在issue中找到的方法是可以使用 ``ncnn::Mat::from_pixels``将opencv的mat转为ncnn的mat 但这个方法接受的type都是rgb格式的类型。我这里是单通道的y类型，而且做了float缩放。

**Comment by nihui** [comment]
```
cv::Mat y_mat;
ncnn::Mat in = ncnn::Mat::from_pixels(y_mat.data, ncnn::Mat::PIXEL_GRAY, w, h);

const float norm_vals[1] = {1/255.f};
in.substract_mean_normalize(0, norm_vals);
```

**Comment by ghuiii** [comment]
@nihui 谢谢大佬, 解决了

**Comment by soham24** [comment]
#1415 can yuou help me @sethcreate

**Comment by soham24** [comment]
@nihui my op will be also an ncnn mat
how I should convert it into cv mat? 
I will need to denormalize it right?

I tried this
but did not work

   //created new cv mat
    cv :: Mat cv_img = cv :: Mat :: zeros (224*2, 224*2, CV_32FC1);

  //added nccn data to it
    out.to_pixels (cv_img.data, ncnn :: Mat :: PIXEL_GRAY);

//
    cv_img.convertTo(cv_img, CV_8UC1, 255.0);
    imwrite("/storage/emulated/0/singlechannel.jpg", cv_img);

**Comment by soham24** [comment]
for input I need to normalise by this:
const float norm_vals[1] = {1/255.f};
in.substract_mean_normalize(0, norm_vals);

what should I do to de-normalise o/p?

**Comment by mei123hao** [comment]
如果是三通道呢？
