### ISSUE TITLE
关于海思平台的加速

### ISSUE THREAD

**Issue by dongfangduoshou123** [Tencent/ncnn#1183]
Hisilicon platform的实现是否用到了海思的nnie加速模块了吗？
还是实现的cpu版？

**Comment by nihui** [comment]
海思的nnie加速模块属于商用硬件，没有公开接口，无法利用，所以ncnn是用cpu运行的

**Comment by BUG1989** [comment]
我猜楼主是想问：ncnn能否将nnie的API封装进去？
