### ISSUE TITLE
Mac上编译aarch64失败

### ISSUE THREAD

**Issue by windmaple** [Tencent/ncnn#1184]
最后linker一步失败，linux上没问题，只是在Mac上

[ 99%] Building CXX object src/CMakeFiles/ncnn.dir/layer/selu.cpp.o
In file included from /Users/weiwe/Desktop/project-src/ncnn/src/layer/vulkan/hardsigmoid_vulkan.cpp:15:
/Users/weiwe/Desktop/project-src/ncnn/src/layer/vulkan/hardsigmoid_vulkan.h:30:17: warning:
      'ncnn::HardSigmoid_vulkan::forward_inplace' hides overloaded virtual function [-Woverloaded-virtual]
    virtual int forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& opt) const;
                ^
/Users/weiwe/Desktop/project-src/ncnn/src/layer/hardsigmoid.h:29:17: note: hidden overloaded virtual function
      'ncnn::HardSigmoid::forward_inplace' declared here: different number of parameters (2 vs 3)
    virtual int forward_inplace(Mat& bottom_top_blob, const Option& opt) const;
                ^
/Users/weiwe/Desktop/project-src/ncnn/src/layer/vulkan/hardsigmoid_vulkan.cpp:52:56: warning: unused parameter 'opt'
      [-Wunused-parameter]
int HardSigmoid_vulkan::destroy_pipeline(const Option& opt)
                                                       ^
/Users/weiwe/Desktop/project-src/ncnn/src/layer/vulkan/hardsigmoid_vulkan.cpp:63:95: warning: unused parameter 'opt'
      [-Wunused-parameter]
int HardSigmoid_vulkan::forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& opt) const
                                                                                              ^
2 warnings generated.
[ 99%] Building CXX object src/CMakeFiles/ncnn.dir/layer/arm/selu_arm.cpp.o
3 warnings generated.
[100%] Linking CXX static library libncnn.a
[100%] Built target ncnn
[100%] Building CXX object benchmark/CMakeFiles/benchncnn.dir/benchncnn.cpp.o
[100%] Linking CXX executable benchncnn
../src/libncnn.a: error adding symbols: Archive has no index; run ranlib to add one
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [benchmark/benchncnn] Error 1
make[1]: *** [benchmark/CMakeFiles/benchncnn.dir/all] Error 2
make: *** [all] Error 2

**Comment by nihui** [comment]
Mac上编译aarch64是什么？android aarch64？

确保用新的cmake，以及build目录删除重新编译

**Comment by nihui** [comment]
如还有问题，可以reopen issue
