### ISSUE TITLE
ModelBin read quantization_value failed 0 layer load_model 54 failed

### ISSUE THREAD

**Issue by chengtingting** [Tencent/ncnn#1190]
您好，我遇到了以下问题，望答疑，谢谢~
已经使用了最新的caffe-int8-convert-tools和最新的ncnn，在模型量化成功后，出现加载量化后的.bin失败的问题。单独使用benchncnn测试量化后的模型（只加载量化后的.param文件）可以使用，但是一旦load_model(*.bin)就报错ModelBin read quantization_value failed 0 layer。

**Comment by chengtingting** [comment]
output_num和group不相等时，int8量化导致后面的层weight中出现nan，去掉这样的层量化就可以了，但没有细看转化代码，所有不知道为什么。

**Comment by chenyangMl** [comment]
> output_num和group不相等时，int8量化导致后面的层weight中出现nan，去掉这样的层量化就可以了，但没有细看转化代码，所有不知道为什么。

您好，我也遇到和您相同的问题，ncnn2int后load_model(),load_parm()失败，量化后用netron可视化也失败了，你说的去掉为nan的量化层怎么操作的？
