### ISSUE TITLE
Accuracy of the Models on Imagenet

### ISSUE THREAD

**Issue by imirzadeh** [Tencent/ncnn#1192]
Hi,

Do you also have the accuracy of the implemented models on Imagnet?

**Comment by BUG1989** [comment]
@imirzadeh 
[Accuracy and Performance](https://github.com/BUG1989/caffe-int8-convert-tools#accuracy-and-performance)

**Comment by nihui** [comment]
Accuracy of the ncnn model should be the same as the original model converted from
