### ISSUE TITLE
ncnn2table 交叉熵计算疑问？

### ISSUE THREAD

**Issue by zjd1988** [Tencent/ncnn#1193]
在结合Ｎvidia的ppt，阅读threshold_distribution代码时，发现有一处地方貌似跟ppt不一致，如下图
![kl-compute](https://user-images.githubusercontent.com/7134030/63156098-89950800-c046-11e9-9eec-e4bdb437f119.png)

Ｑ分布的计算在源码中没有做归一化操作吧

![kl_code](https://user-images.githubusercontent.com/7134030/63156232-d547b180-c046-11e9-8797-663d9aa3daef.png)

**Comment by BUG1989** [comment]
@zjd1988 
https://github.com/Tencent/ncnn/blob/3e3189736c20441e604d294bed8afbaa516c13db/tools/quantize/ncnn2table.cpp#L477

**Comment by zjd1988** [comment]
@BUG1989  谢谢解答，我再看看代码．＾＿＾
