### ISSUE TITLE
出现“undefined reference to”错误，请问怎么解决呢

### ISSUE THREAD

**Issue by 1343464520** [Tencent/ncnn#1196]
![errorlog](https://user-images.githubusercontent.com/24668916/63251172-c3ad1680-c29f-11e9-9d4f-0c27b074a16f.png)

**Comment by 1343464520** [comment]
@nihui @arnaudbrejeon @cook @tamworth 请问怎么解决呢，谢谢！

**Comment by 1343464520** [comment]
请问有人遇到过吗？怎么解决呢？

**Comment by arnaudbrejeon** [comment]
you probably forgot to link with the ncnn library.

**Comment by 1343464520** [comment]
thank you, arnaudbrejeon. i have solved it.

**Comment by sebastianfelipe** [comment]
Hi! I have the same issue. Have compiled everything using a Makefile written by me and I linked the ncnnn library but it still having this issue. What are the correct flags to compile it? Maybe something lacks in what I'm doing. I'd really appreciate your support. Thanks.
