### ISSUE TITLE
ncnn支持batchsize > 1的inference吗？

### ISSUE THREAD

**Issue by chengtingting** [Tencent/ncnn#1197]
@nihui 你好，请问ncnn支持batchsize > 1的前向推理吗？如果支持，在arm上平均速度会提升吗？

**Comment by nihui** [comment]
arm cpu 不支持 batchsize > 1，因为即使支持也不会变快，可以外部循环
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#create-new-extractor-for-each-image
gpu参考
https://github.com/Tencent/ncnn/wiki/vulkan-notes#batch-inference

**Comment by fzyzcjy** [comment]
@nihui 你好，请问为什么`即使支持也不会变快`？对于小模型的一些小的layer，我的理解是。

同时，ncnn似乎内部已经使用了多线程，那第二个链接的

```
#pragma omp parallel for num_threads(max_batch_size)
for (int i=0; i<1000; i++)
{
    ncnn::Extractor ex = net1.create_extractor();
    ex.input("data", inputs[i]);
    ex.extract("prob", outputs[i]);
}
```

在外部用openmp并行，是否会真的加速？

谢谢

**Comment by chenglimin** [comment]
riscv上支持batch size大于1吗？

**Comment by nihui** [comment]
The ncnn batch infrastructure feature, which relies on the pnnx tool, is implemented at https://github.com/Tencent/ncnn/commit/127b4146148844ccf67a5bdcb0385e925aa13fbb
