### ISSUE TITLE
How to compile the example?

### ISSUE THREAD

**Issue by lijian8454088** [Tencent/ncnn#12]
怎么编译code里面的example，我需要将生成的lib导入进去吗？

**Comment by lijian8454088** [comment]
修改了一些配置就可以了
![Uploading image.png…]()

**Comment by guozhongluo** [comment]
![image](https://user-images.githubusercontent.com/20280270/28560801-932580d2-714e-11e7-98d5-bf67a8ec09e8.png)
我用vs2015，将example以及src代码，放到一个新建的工程里面，可以运行。性能：cpu i7 3.4GHZ,  picture 492*344大小，耗时 1.376秒
