### ISSUE TITLE
to_pixels_resize()函数好像是错的

### ISSUE THREAD

**Issue by soccergame** [Tencent/ncnn#1201]
函数内部实现，以灰度图为例：
else if (type_to == PIXEL_GRAY)
    {
        Mat src(target_width, target_height, (size_t)1u, 1);

        to_pixels(src, type);

        resize_bilinear_c1(src, w, h, pixels, target_width, target_height);
    }
src开辟的空间大小是target_width * target_height。可是在to_pixels的实现里面，src则是用*this指针进行赋值操作，也就是说src的大小应该是与*this对应的Mat矩阵的大小一致，也就是w*h。

**Comment by nihui** [comment]
恩，确实有问题，欢迎 pull request !
