### ISSUE TITLE
arm cortex a53上，利用benchncnn测试f16和f32耗时一样

### ISSUE THREAD

**Issue by SophieChang66** [Tencent/ncnn#1203]
arm cortex a53上，利用benchncnn测试f16和f32耗时一样，net的option设置如下：
g_default_option.use_winograd_convolution = true;
g_default_option.use_sgemm_convolution = true;
g_default_option.use_int8_inference = true;
g_default_option.use_vulkan_compute = use_vulkan_compute;
g_default_option.use_fp16_packed = true;
g_default_option.use_fp16_storage = true;
g_default_option.use_fp16_arithmetic = true;
g_default_option.use_int8_storage = true;
g_default_option.use_int8_arithmetic = true;
耗时没有差异，请问是a53没有f16计算单元吗？我是硬件菜鸟。。。

**Comment by chengtingting** [comment]
arm cortex a53上，利用benchncnn测试f16和f32耗时一样，net的option设置如下：
 g_default_option.use_winograd_convolution = true;
    g_default_option.use_sgemm_convolution = true;
    g_default_option.use_int8_inference = true;
    g_default_option.use_vulkan_compute = use_vulkan_compute;
    g_default_option.use_fp16_packed = true;
    g_default_option.use_fp16_storage = true;
    g_default_option.use_fp16_arithmetic = true;
    g_default_option.use_int8_storage = true;
    g_default_option.use_int8_arithmetic = true;
耗时没有差异，请问是a53没有f16计算单元吗？我是硬件菜鸟。。。

**Comment by BUG1989** [comment]
- A53没有fp16的硬件计算单元
- ncnn目前不支持fp16计算（即使有fp16计算单元的硬件，例如Cortex-A75/A76/A55）

**Comment by nihui** [comment]
楼上正解
fp16 cpu上面主要用来压缩模型大小的
另外，ncnn gpu 是支持 fp16 计算的

**Comment by SophieChang66** [comment]
@nihui @BUG1989 ,谢谢回复

**Comment by zengjie617789** [comment]
那为什么int8感觉也没变化呢
