### ISSUE TITLE
./ncnn2table not working

### ISSUE THREAD

**Issue by bocharm** [Tencent/ncnn#1205]
First, I am really thankful for your awesome project and releasing to the public.

I am trying post quantization following your wiki docs
https://github.com/Tencent/ncnn/tree/master/tools/quantize
but at step2, it doesn't work with some tricky error message

```====> Quantize the parameters.
====> Quantize the activation.
    ====> step 1 : find the max value.
find_blob_index_by_name data failed
[1]    12761 segmentation fault  ./tools/quantize/ncnn2table --param squeezenet-nobn.param --bin  --images
```

how can I figure out this error?
Thank you

**Comment by bocharm** [comment]
I figured out this problem 
thx

**Comment by Zrufy** [comment]
how you resolve this problem?

**Comment by sheng8006** [comment]
请问您是如何解决这个问题的呢？

**Comment by bocharm** [comment]
I can't remember exactly, but open your [name].param file and check the name of "blob_index" and change the source files with "data" to the name of your "blob_index"
