### ISSUE TITLE
Performance results affected by enabling NCNN_BENCHMARK flag

### ISSUE THREAD

**Issue by delemelo-mobica** [Tencent/ncnn#1206]
I am trying to analyse the layer times obtained from a benchmark performance test run. I have enabled the flag (NCNN_BENCHMARK) in order to display the layer times. However, the performance results obtained by doing this is slower. It seems that the performance result is worse than the actual performance i.e running without the use of the flag (NCNN_BENCHMARK).

Please are there any plans to resolve this?

**Comment by nihui** [comment]
That's why it is a compile-time option.
You should only enable it for debug or profile purpose, and always disable it for deployment.
