### ISSUE TITLE
使用 ncnn2mem， softmax 出來的 output 很大

### ISSUE THREAD

**Issue by twmht** [Tencent/ncnn#1208]
用最新 master branch 上的 ncnn + ndk-r17C 轉 squeezenet_v1.1

先用編譯好的 tool，ncnn2caffe -> ncnn2mem 生成  `squeezenet_v1.1.id.h` 、`squeezenet_v1.1.mem.h` 跟 `squeezenet_v1.1.param.bin`

修改 https://github.com/Tencent/ncnn/blob/master/examples/squeezencnn/jni/squeezencnn_jni.cpp

加上

`
#include <squeezenet_v1.1.mem.h>
`

用 ndk-build 生成 libsqueezenet.so

將生成的 bin file 跟 so 放到 https://github.com/dangbo/ncnn-mobile/tree/master/squeezencnn-AS

最後一層出來的 softmax prob 值非常大，遠遠超過 1

用原本的 ncnn-mobile 上的 so 跟 bin 檔就沒有這個問題

奇怪的是範例 https://github.com/Tencent/ncnn/blob/master/examples/squeezencnn/jni/squeezencnn_jni.cpp 並沒有加上 `#include <squeezenet_v1.1.mem.h>`

請問這是 bug 嗎？

**Comment by twmht** [comment]
我看 `load_param` 跟 `load_model` 回傳的值是 3792 跟 4942088

後來把  `squeezenet_v1.1.mem.h` 拿掉後還是可以跑，我們真的需要 `squeezenet_v1.1.mem.h`?

**Comment by twmht** [comment]
model 本身是沒問題的，在 pc 端可以跑

**Comment by twmht** [comment]
原先的 `ncnn-mobile`  的 load_param 速度非常快，但是上面的 bin 跟 param.bin 的大小跟我是一樣的，是後來的 ncnn 的 load_param 有再修改嗎？

**Comment by nihui** [comment]
https://github.com/dangbo/ncnn-mobile 版本过于陈旧，不兼容现在的模型格式，不要参考使用
参考 https://github.com/Tencent/ncnn/tree/master/examples/squeezencnn 实现
内存加载是 const unsigned char* 的接口，没有问题

**Comment by twmht** [comment]
@nihui 

我就是用 ncnn 最新的版本下去編譯 squeezenet.so 阿

然後直接取代替換掉 ncnn-mobile 的 squeezenet.so

理論上我用到的只有 ncnn-mobile 的 java code，它那邊的 java code 跟最新版的 ncnn 的 java code 是一致的，所以不會有 ncnn-mobile 舊不舊的問題

**Comment by twmht** [comment]
換成 ndk-r18b，一樣會有這個問題...
![Screenshot_20190825-105114](https://user-images.githubusercontent.com/1567200/63644930-8ffe4080-c726-11e9-9cf7-455a24dfeb47.png)

**Comment by twmht** [comment]
ok..

看起來把 build.gradle裡面的

```
         ndk {
             moduleName "ncnn"
            abiFilters 'armeabi-v7a'
         }
```

直接註解掉就把這問題解決掉了

不過到底需不需要去 include `squeezenet_v1.1.mem.h`?

**Comment by nihui** [comment]
I created a sample project with android studio here, you may refer this repo
https://github.com/nihui/ncnn-android-squeezenet

**Comment by twmht** [comment]
@nihui 

所以看起來不用特別去 include  `squeezenet_v1.1.mem.h`？

**Comment by nihui** [comment]
模型从 bin 资源加载，不需要 mem.h
