### ISSUE TITLE
does mxnet to ncnn tool fully support mxnet?

### ISSUE THREAD

**Issue by helloearth012** [Tencent/ncnn#1209]
I can see there is this tool, just wondering do you fully support the mxnet conversion?
I ever used the tensorflow to ncnn tool, and encountered some problems, so just confirm that whether MXnet is good here.

**Comment by nihui** [comment]
Most operators involving depth dimension such as LSTM or 3d convolution is not supported
But for most computer vision tasks, the mxnet2ncnn tool should do a good job
and I personally use mxnet/gluon at work :P
