### ISSUE TITLE
同一个硬件，不同版本ncnn，速度存在差异

### ISSUE THREAD

**Issue by SophieChang66** [Tencent/ncnn#1213]
1.都在A53上，单线程跑10个不同网络，3月的ncnn版本比7月31的快，使用相对应版本里的caffe2ncnn转换的模型；
2.使用7月的ncnn里的ncnnoptimize针对A53硬件选择最快的卷积方式生成.param和.bin后，有些模型耗时减少明细，有些差不多，有些增加一点点；
3.没有对不分析过这两个版本里的差异，请问是因为走了不同的优化分支造成的吗？

**Comment by nihui** [comment]
确实存在这种可能性，因为每次优化的时候，是在我的几个旧手机上测试的，主要是nexus6p，无法覆盖到全部的硬件，但尽量保证大部分手机是变快的
