### ISSUE TITLE
why quantization tool does not decrease model size by 75%? 

### ISSUE THREAD

**Issue by MoMentum99** [Tencent/ncnn#1214]
First, thank you so much for awesome project and releasing to the public

I am trying model quantization following your quantization guidelines
https://github.com/Tencent/ncnn/tree/master/tools/quantize

but after finishing all steps without any single lines of error, model size doesn't decrease at all. Checking ncnn::Mat::elemsize, model file changed from float64 to int8 which means quantization works to some degree.

What's the problem with it? Am I did something wrong?

**Comment by lexuszhi1990** [comment]
我也碰到了同样的问题。 

![image](https://user-images.githubusercontent.com/548467/63840319-6dcd2280-c9b3-11e9-9bd5-efe61e483fa4.png)

`example.param`  和 `example.bin 是得到的初始ncnn模型。

```
./ncnnoptimize example.param example.bin example-nobn-fp32.param example-nobn-fp32.bin 
./ncnn2table --param example-nobn-fp32.param --bin example-nobn-fp32.bin --images images/ --output example-nobn.table --mean 104,117,123 --norm 0.017,0.017,0.017 --size 224,224 --thread 2
./ncnn2int8 example-nobn-fp32.param example-nobn-fp32.bin example-int8.param mobilenet-int8.bin 
```
ncnnoptimize 优化之后，模型大小将为 883k，然后ncnn2int8定点化之后，模型大小又变成了1.8M

**Comment by lexuszhi1990** [comment]
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
根据这里的描述，可能现在这种方法采用的是 “the runtime way, no model binary reduction”，所以模型大小并没有下降

**Comment by MambaWong** [comment]
> 我也碰到了同样的问题。
> 
> ![image](https://user-images.githubusercontent.com/548467/63840319-6dcd2280-c9b3-11e9-9bd5-efe61e483fa4.png)
> 
> `example.param` 和 `example.bin 是得到的初始ncnn模型。
> 
> ```
> ./ncnnoptimize example.param example.bin example-nobn-fp32.param example-nobn-fp32.bin 85535
> ./ncnn2table --param example-nobn-fp32.param --bin example-nobn-fp32.bin --images images/ --output example-nobn.table --mean 104,117,123 --norm 0.017,0.017,0.017 --size 224,224 --thread 2
> ./ncnn2int8 example-nobn-fp32.param example-nobn-fp32.bin example-int8.param mobilenet-int8.bin 
> ```
> 
> ncnnoptimize 优化之后，模型大小将为 883k，然后ncnn2int8定点化之后，模型大小又变成了1.8M

并没有看到你在 `./ncnn2int8 example-nobn-fp32.param example-nobn-fp32.bin example-int8.param mobilenet-int8.bin ` 这里面指定 table 文件，所以应该没有存成 8bit 吧。过程中有看到 “quantize_convolution layer_name ” 类似的打印么。

**Comment by BUG1989** [comment]
@lexuszhi1990 
这位同学的解释是正确的@MambaWong

**Comment by bocharm** [comment]
@MambaWong 
could you please check my case?
I used torchvision model and convert it to .bin, .param file using onnx
(https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx)

![image](https://user-images.githubusercontent.com/47184034/64936099-3b666500-d88f-11e9-973e-34417f2c264e.png)

```
./ncnnoptimize squeezenet.param squeezenet.bin squeezenet-nobn.param squeezenet-nobn.bin 0
./ncnn2table --param squeezenet-nobn.param --bin squeezenet-nobn.bin --images ../../samples/ --output squeezenet.table --mean 123,117,104 --norm 0.017,0.017,0.017 --size 224,224 --thread 2
./ncnn2int8 squeezenet-nobn.param squeezenet-nobn.bin squeezenet-quant.param squeezenet-quant.bin squeezenet.table
```

**Comment by cheng-wen-long** [comment]
hello, have you solved your problems, I also meet this problem. @bocharm

**Comment by nihui** [comment]
请更新ncnn量化和转换工具
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
