### ISSUE TITLE
fatal error: platform.h: No such file or directory

### ISSUE THREAD

**Issue by 958099161** [Tencent/ncnn#1215]
...
[ 50%] Building CXX object CMakeFiles/squeezenet.dir/squeezenet.cpp.o
/home/luzhongshan/soft/ncnn/examples/squeezenet.cpp:21:22: fatal error: platform.h: No such file or directory
compilation terminated.

**Comment by 958099161** [comment]
为什么找不到这个头文件?

**Comment by nihui** [comment]
platform.h is generated by cmake
you can find this header in build/src directory
