### ISSUE TITLE
mxnet to ncnn error

### ISSUE THREAD

**Issue by czqhubu** [Tencent/ncnn#1216]
./mxnet2ncnn models/mobilefacenet3/model-y1-softmax-symbol.json models/mobilefacenet3/model-y1-softmax-0217.params 
BlockGrad not supported yet!

BlockGrad is not supported ?

**Comment by czqhubu** [comment]
ncnn is new

**Comment by nihui** [comment]
BlockGrad is a operator used in training phase, so it is fine to drop it totally or replace it with noop

https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#layer-xyz-not-exists-or-registered

**Comment by ramonsf29** [comment]
Hi, I am having the same problem and I can not fix it by registering the layers, there is any other way to remove the layers and save the model to convert to ncnn?

Best regards
