### ISSUE TITLE
新工具ncnn2int8支持部分量化吗

### ISSUE THREAD

**Issue by SophieChang66** [Tencent/ncnn#1217]
@nihui @BUG1989 我之前使用caffe2ncnn可以使用部分量化的，但现在用ncnn2int8进行部分量化，结果没有量化，返回的是原模型。请问为什么不支持部分量化了，个人感觉部分量化听有必要的，因为根据逐层打印耗时来看，有些层量化后耗时反而增加，这样的层可以选择不量化。

**Comment by SophieChang66** [comment]
解决了，是因为7月31号clone的代码里，作者一个手误iter_data == blob_int8scale_table.end()，看最新的代码里，已经修正了这个bug

**Comment by nihui** [comment]
感谢w
