### ISSUE TITLE
squeezenet例子的问题

### ISSUE THREAD

**Issue by yqbyqbyqb** [Tencent/ncnn#1218]
我照着 Build for Linux x86 说明
运行squeezenet，如下：
$ cd build/examples
$ ./squeezenet yourimage.jpg 

output top-3 class-id and score
you may refer examples/synset_words.txt to find the class name
404 = 0.990290
908 = 0.004464
405 = 0.003941

请问结果怎么跟synset_words.txt对应起来？synset_words.txt里的格式如下：
n01440764 tench, Tinca tinca
n01443537 goldfish, Carassius auratus
n01484850 great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias
n01491361 tiger shark, Galeocerdo cuvieri
n01494475 hammerhead, hammerhead shark
n01496331 electric ray, crampfish, numbfish, torpedo

谢谢，望指点，不胜感激。

**Comment by nihui** [comment]
404 = 0.990290
这里的 404 代表 synset_words.txt 的第 405 行
如果是 0 = 0.990290，就是 synset_words.txt 第 1 行 tench, Tinca tinca

**Comment by yqbyqbyqb** [comment]
谢谢

> 404 = 0.990290
> 这里的 404 代表 synset_words.txt 的第 405 行
> 如果是 0 = 0.990290，就是 synset_words.txt 第 1 行 tench, Tinca tinca

谢谢.....一万个:-)
