### ISSUE TITLE
如何使用ndk-r13b编译

### ISSUE THREAD

**Issue by chenyibo89** [Tencent/ncnn#1219]
有什么办法可以使用ndk-r13b来进行编译？目前的项目只能用这个ndk版本。
20180427版本的ncnn，用ndk-r13b编译会报如下错误，ndk-r15就没事。
build-android-armv7 chenyibo02$ cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake     -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON     -DANDROID_PLATFORM=android-14 ..
-- CMAKE_TOOLCHAIN_FILE = /Users/chenyibo02/android-sdk-macosx/android-ndk-r13b/build/cmake/android.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /Users/chenyibo02/workspace/snowboy-vision-sdk/Cpp/ncnn/build-android-armv7/install
-- Android: Targeting API '14' with architecture 'arm', ABI 'armeabi-v7a', and processor 'armv7-a'
-- Android: Selected GCC toolchain 'arm-linux-androideabi-4.9'
-- Check for working C compiler: /Users/chenyibo02/android-sdk-macosx/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc
-- Check for working C compiler: /Users/chenyibo02/android-sdk-macosx/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc -- broken
CMake Error at /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/Users/chenyibo02/android-sdk-macosx/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/chenyibo02/workspace/snowboy-vision-sdk/Cpp/ncnn/build-android-armv7/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_d9207/fast"
    /Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_d9207.dir/build.make CMakeFiles/cmTC_d9207.dir/build
    Building C object CMakeFiles/cmTC_d9207.dir/testCCompiler.c.o
    /Users/chenyibo02/android-sdk-macosx/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc -target armv7-none-linux-androideabi --sysroot=/Users/chenyibo02/android-sdk-macosx/android-ndk-r13b/platforms/android-14/arch-arm  -isystem /Users/chenyibo02/android-sdk-macosx/android-ndk-r13b/platforms/android-14/arch-arm/usr/include  -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security   -O0 -fno-limit-debug-info    -o CMakeFiles/cmTC_d9207.dir/testCCompiler.c.o   -c /Users/chenyibo02/workspace/snowboy-vision-sdk/Cpp/ncnn/build-android-armv7/CMakeFiles/CMakeTmp/testCCompiler.c
    arm-linux-androideabi-gcc: error: armv7-none-linux-androideabi: No such file or directory
    arm-linux-androideabi-gcc: error: unrecognized command line option '-target'
    arm-linux-androideabi-gcc: error: unrecognized command line option '-fno-integrated-as'
    arm-linux-androideabi-gcc: error: unrecognized command line option '-fno-integrated-as'
    arm-linux-androideabi-gcc: error: unrecognized command line option '-fno-limit-debug-info'
    make[1]: *** [CMakeFiles/cmTC_d9207.dir/testCCompiler.c.o] Error 1
    make: *** [cmTC_d9207/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:15 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/chenyibo02/workspace/snowboy-vision-sdk/Cpp/ncnn/build-android-armv7/CMakeFiles/CMakeOutput.log".
See also "/Users/chenyibo02/workspace/snowboy-vision-sdk/Cpp/ncnn/build-android-armv7/CMakeFiles/CMakeError.log".

**Comment by nihui** [comment]
因为 r13b bug 太多了。。。比如 openmp 就是不正常的
推荐至少 r15c，只要 target platform 一样，应该是兼容的
