### ISSUE TITLE
生成int8量化的table文件的过程太慢了，多线程速度还是慢

### ISSUE THREAD

**Issue by xiaozhao00** [Tencent/ncnn#1223]
请教一下，是什么原因，谢谢

**Comment by SophieChang66** [comment]
多线程没有设置进去，在post_training_quantize函数的QuantNet net定义后，增加一句net.opt = g_default_option;

**Comment by xiaozhao00** [comment]
> net.opt = g_default_option;

非常感谢

**Comment by nihui** [comment]
opt 加上了
