### ISSUE TITLE
用squeezenet例程识别图片，显示的数字是什么意思？

### ISSUE THREAD

**Issue by ljy-2019** [Tencent/ncnn#1224]
![ncnn图片识别后的结果](https://user-images.githubusercontent.com/54355262/63929001-3b8af600-ca83-11e9-9ee2-9cb55e6d5583.png)
怎么才能让它显示有用的信息啊？比如，姓名，性别，年龄等

**Comment by nihui** [comment]
duplicate of https://github.com/Tencent/ncnn/issues/1218
