### ISSUE TITLE
Ubuntu下（Tegra X2集显）编译ncnn+vulkan失败，如何解决？

### ISSUE THREAD

**Issue by CnybTseng** [Tencent/ncnn#1225]
我按照如下步骤编译ncnn+vulkan：
cd ncnn/build/
export VULKAN_SDK=/home/dji/project/1.1.92.1/x86_64/
cmake -DNCNN_VULKAN=ON ..
make -j4

然后出现如下错误：
[  0%] Running cpp protocol buffer compiler on onnx.proto
Scanning dependencies of target generate-spirv
[  0%] Building SPIR-V module absval.spv
[  0%] Building SPIR-V module absval_fp16p.spv
[  1%] Building SPIR-V module absval_fp16s.spv
/home/dji/project/1.1.92.1/x86_64/bin/glslangValidator: 1: /home/dji/project/1.1.92.1/x86_64/bin/glslangValidator: Syntax error: "(" unexpected
src/CMakeFiles/generate-spirv.dir/build.make:507: recipe for target 'src/absval.spv.hex.h' failed
make[2]: *** [src/absval.spv.hex.h] Error 2
make[2]: *** Waiting for unfinished jobs....
Scanning dependencies of target onnx2ncnn
/home/dji/project/1.1.92.1/x86_64/bin/glslangValidator: 1: /home/dji/project/1.1.92.1/x86_64/bin/glslangValidator: Syntax error: "(" unexpected
/home/dji/project/1.1.92.1/x86_64/bin/glslangValidator: 1: /home/dji/project/1.1.92.1/x86_64/bin/glslangValidator: Syntax error: "(" unexpected
src/CMakeFiles/generate-spirv.dir/build.make:511: recipe for target 'src/absval_fp16p.spv.hex.h' failed
make[2]: *** [src/absval_fp16p.spv.hex.h] Error 2
src/CMakeFiles/generate-spirv.dir/build.make:515: recipe for target 'src/absval_fp16s.spv.hex.h' failed
make[2]: *** [src/absval_fp16s.spv.hex.h] Error 2
CMakeFiles/Makefile2:481: recipe for target 'src/CMakeFiles/generate-spirv.dir/all' failed
make[1]: *** [src/CMakeFiles/generate-spirv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Building CXX object tools/onnx/CMakeFiles/onnx2ncnn.dir/onnx.pb.cc.o
[  1%] Building CXX object tools/onnx/CMakeFiles/onnx2ncnn.dir/onnx2ncnn.cpp.o
[  1%] Linking CXX executable onnx2ncnn
[  1%] Built target onnx2ncnn
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

请问：该如何解决？

**Comment by nihui** [comment]
tx2 不应该用 x86 的 vulkan sdk，可以参考 wiki 关于 jetson nano 的编译方法
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-nvidia-jetson

**Comment by CnybTseng** [comment]
> tx2 不应该用 x86 的 vulkan sdk，可以参考 wiki 关于 jetson nano 的编译方法
> https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-nvidia-jetson

谢谢你^-^
我从https://developer.nvidia.com/user下载了预编译的vulkan sdk，然后下载安装glslang：
dji@manifold2:~/project/glslang/build$ sudo cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$(pwd)/install" ..
dji@manifold2:~/project/glslang/build$ sudo make -j6 install
。。。
[100%] Built target spirv-reduce
Install the project...
-- Install configuration: "Release"
。。。
这些都OK
然后编译ncnn+vulkan，我先修改ncnn/src/CMakeLists.txt
if(NCNN_VULKAN)
    #find_program(GLSLANGVALIDATOR_EXECUTABLE NAMES glslangValidator PATHS $ENV{VULKAN_SDK}/bin NO_CMAKE_FIND_ROOT_PATH)
    find_program(GLSLANGVALIDATOR_EXECUTABLE NAMES glslangValidator PATHS /home/dji/project/glslang/build/install/bin NO_CMAKE_FIND_ROOT_PATH)
    message(STATUS "Found glslangValidator: ${GLSLANGVALIDATOR_EXECUTABLE}")
endif()
然后编译：
dji@manifold2:~/project/ncnn/build$ cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake -DNCNN_VULKAN=ON -DCMAKE_BUILD_TYPE=Release ..
dji@manifold2:~/project/ncnn/build$ make -j4
就出现了如下错误：
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16p.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16s.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16a.spv
[ 28%] Building SPIR-V module lrn_square_pad_within_channel_pack4.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16p.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16s.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16a.spv
[ 29%] Building SPIR-V module pooling.spv
[ 29%] Building SPIR-V module pooling_fp16p.spv
[ 29%] Building SPIR-V module pooling_fp16s.spv
[ 30%] Building SPIR-V module pooling_fp16a.spv
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1211: recipe for target 'src/pooling.spv.hex.h' failed
make[2]: *** [src/pooling.spv.hex.h] Error 2
make[2]: *** Waiting for unfinished jobs....
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1215: recipe for target 'src/pooling_fp16p.spv.hex.h' failed
make[2]: *** [src/pooling_fp16p.spv.hex.h] Error 2
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1223: recipe for target 'src/pooling_fp16a.spv.hex.h' failed
make[2]: *** [src/pooling_fp16a.spv.hex.h] Error 2
CMakeFiles/Makefile2:478: recipe for target 'src/CMakeFiles/generate-spirv.dir/all' failed
make[1]: *** [src/CMakeFiles/generate-spirv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CnybTseng** [comment]
谢谢你^-^
我从https://developer.nvidia.com/user下载了预编译的vulkan sdk，然后下载安装glslang：

~/project/glslang/build$ sudo cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$(pwd)/install" ..
~/project/glslang/build$ sudo make -j6 install
。。。
[100%] Built target spirv-reduce
Install the project...
-- Install configuration: "Release"
。。。
这些都OK
然后编译ncnn+vulkan，我先修改ncnn/src/CMakeLists.txt
if(NCNN_VULKAN)
#find_program(GLSLANGVALIDATOR_EXECUTABLE NAMES glslangValidator PATHS $ENV{VULKAN_SDK}/bin NO_CMAKE_FIND_ROOT_PATH)
find_program(GLSLANGVALIDATOR_EXECUTABLE NAMES glslangValidator PATHS /home/dji/project/glslang/build/install/bin NO_CMAKE_FIND_ROOT_PATH)
message(STATUS "Found glslangValidator: ${GLSLANGVALIDATOR_EXECUTABLE}")
endif()
然后编译：
~/project/ncnn/build$ cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake -DNCNN_VULKAN=ON -DCMAKE_BUILD_TYPE=Release ..
~/project/ncnn/build$ make -j4
就出现了如下错误：
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16p.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16s.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16a.spv
[ 28%] Building SPIR-V module lrn_square_pad_within_channel_pack4.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16p.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16s.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16a.spv
[ 29%] Building SPIR-V module pooling.spv
[ 29%] Building SPIR-V module pooling_fp16p.spv
[ 29%] Building SPIR-V module pooling_fp16s.spv
[ 30%] Building SPIR-V module pooling_fp16a.spv
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1211: recipe for target 'src/pooling.spv.hex.h' failed
make[2]: *** [src/pooling.spv.hex.h] Error 2
make[2]: *** Waiting for unfinished jobs....
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1215: recipe for target 'src/pooling_fp16p.spv.hex.h' failed
make[2]: *** [src/pooling_fp16p.spv.hex.h] Error 2
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1223: recipe for target 'src/pooling_fp16a.spv.hex.h' failed
make[2]: *** [src/pooling_fp16a.spv.hex.h] Error 2
CMakeFiles/Makefile2:478: recipe for target 'src/CMakeFiles/generate-spirv.dir/all' failed
make[1]: *** [src/CMakeFiles/generate-spirv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2





------------------ 原始邮件 ------------------
发件人: "nihui"<notifications@github.com>;
发送时间: 2019年8月30日(星期五) 上午10:31
收件人: "Tencent/ncnn"<ncnn@noreply.github.com>;
抄送: "Spock"<984943763@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tencent/ncnn] Ubuntu下（Tegra X2集显）编译ncnn+vulkan失败，如何解决？ (#1225)




tx2 不应该用 x86 的 vulkan sdk，可以参考 wiki 关于 jetson nano 的编译方法
 https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-nvidia-jetson
