### ISSUE TITLE
Installed cmake files don't find the ncnn library

### ISSUE THREAD

**Issue by yurivict** [Tencent/ncnn#1226]
```
$ echo 'find_package(ncnn REQUIRED)' >CMakeLists.txt
$ cmake -Wno-dev .
[...]
CMake Error at /usr/local/lib/cmake/ncnn/ncnn.cmake:79 (message):
  The imported target "ncnn" references the file

     "/usr/local/lib/lib/libncnn.a"
```

See the complete error message in the downstream bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240187

**Comment by akemimadoka** [comment]
The library is placed at wrong path, this should be the pkg author's missing, please contact with the author for helping.
You can install ncnn manually with CMake, using "install" target.

**Comment by yurivict** [comment]
I only install it with cmake's install target, and then this problem occurs.

**Comment by akemimadoka** [comment]
Can you provide your build command, install log and if possible, the path structure of installed target?

**Comment by nihui** [comment]
this issue has been solved on downstream
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240187#c2
