### ISSUE TITLE
在大疆manifold2-g平台上编译ncnn+vulkan失败，如何解决

### ISSUE THREAD

**Issue by CnybTseng** [Tencent/ncnn#1227]
我从https://developer.nvidia.com/user下载了预编译的vulkan sdk，然后下载安装glslang：

~/project/glslang/build$ sudo cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$(pwd)/install" ..
~/project/glslang/build$ sudo make -j6 install
。。。
[100%] Built target spirv-reduce
Install the project...
-- Install configuration: "Release"
。。。
这些都OK
然后编译ncnn+vulkan，我先修改ncnn/src/CMakeLists.txt
if(NCNN_VULKAN)
#find_program(GLSLANGVALIDATOR_EXECUTABLE NAMES glslangValidator PATHS $ENV{VULKAN_SDK}/bin NO_CMAKE_FIND_ROOT_PATH)
find_program(GLSLANGVALIDATOR_EXECUTABLE NAMES glslangValidator PATHS /home/dji/project/glslang/build/install/bin NO_CMAKE_FIND_ROOT_PATH)
message(STATUS "Found glslangValidator: ${GLSLANGVALIDATOR_EXECUTABLE}")
endif()
然后编译：
~/project/ncnn/build$ cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake -DNCNN_VULKAN=ON -DCMAKE_BUILD_TYPE=Release ..
~/project/ncnn/build$ make -j4
就出现了如下错误：
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16p.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16s.spv
[ 28%] Building SPIR-V module lrn_square_pad_across_channel_pack4_fp16a.spv
[ 28%] Building SPIR-V module lrn_square_pad_within_channel_pack4.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16p.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16s.spv
[ 29%] Building SPIR-V module lrn_square_pad_within_channel_pack4_fp16a.spv
[ 29%] Building SPIR-V module pooling.spv
[ 29%] Building SPIR-V module pooling_fp16p.spv
[ 29%] Building SPIR-V module pooling_fp16s.spv
[ 30%] Building SPIR-V module pooling_fp16a.spv
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1211: recipe for target 'src/pooling.spv.hex.h' failed
make[2]: *** [src/pooling.spv.hex.h] Error 2
make[2]: *** Waiting for unfinished jobs....
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1215: recipe for target 'src/pooling_fp16p.spv.hex.h' failed
make[2]: *** [src/pooling_fp16p.spv.hex.h] Error 2
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1223: recipe for target 'src/pooling_fp16a.spv.hex.h' failed
make[2]: *** [src/pooling_fp16a.spv.hex.h] Error 2
CMakeFiles/Makefile2:478: recipe for target 'src/CMakeFiles/generate-spirv.dir/all' failed
make[1]: *** [src/CMakeFiles/generate-spirv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/blob/af646b65774184aa9b6dda5b4459c543d8899eca/src/CMakeLists.txt#L100
https://github.com/Tencent/ncnn/blob/af646b65774184aa9b6dda5b4459c543d8899eca/src/CMakeLists.txt#L119
https://github.com/Tencent/ncnn/blob/af646b65774184aa9b6dda5b4459c543d8899eca/src/CMakeLists.txt#L138
https://github.com/Tencent/ncnn/blob/af646b65774184aa9b6dda5b4459c543d8899eca/src/CMakeLists.txt#L157

这几行中把 -s 参数去掉，编译下，可以看到 glslangvalidator 错误信息

**Comment by CnybTseng** [comment]
谢谢你！我按照你的指示改了ncnn/src/CMakeLists.txt，然后编译，报错信息如下：
[ 29%] Building SPIR-V module pooling.spv
/home/dji/project/ncnn/src/layer/vulkan/shader/lrn_square_pad_within_channel_pack4.comp
/home/dji/project/ncnn/src/layer/vulkan/shader/lrn_square_pad_within_channel_pack4.comp
[ 29%] Building SPIR-V module pooling_fp16p.spv
[ 29%] Building SPIR-V module pooling_fp16s.spv
/home/dji/project/ncnn/src/layer/vulkan/shader/lrn_square_pad_within_channel_pack4.comp
[ 30%] Building SPIR-V module pooling_fp16a.spv
/home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: 'readonly' : argument cannot drop memory qualifier when passed to formal parameter
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1211: recipe for target 'src/pooling.spv.hex.h' failed
make[2]: *** [src/pooling.spv.hex.h] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: 'readonly' : argument cannot drop memory qualifier when passed to formal parameter
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1215: recipe for target 'src/pooling_fp16p.spv.hex.h' failed
make[2]: *** [src/pooling_fp16p.spv.hex.h] Error 2
/home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp
/home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: 'readonly' : argument cannot drop memory qualifier when passed to formal parameter
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1223: recipe for target 'src/pooling_fp16a.spv.hex.h' failed
make[2]: *** [src/pooling_fp16a.spv.hex.h] Error 2
CMakeFiles/Makefile2:478: recipe for target 'src/CMakeFiles/generate-spirv.dir/all' failed
make[1]: *** [src/CMakeFiles/generate-spirv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
再次麻烦你啦，^_^

**Comment by CnybTseng** [comment]
谢谢你！我按照你的指示改了ncnn/src/CMakeLists.txt，然后编译，报错信息如下：
[ 29%] Building SPIR-V module pooling.spv
/home/dji/project/ncnn/src/layer/vulkan/shader/lrn_square_pad_within_channel_pack4.comp
/home/dji/project/ncnn/src/layer/vulkan/shader/lrn_square_pad_within_channel_pack4.comp
[ 29%] Building SPIR-V module pooling_fp16p.spv
[ 29%] Building SPIR-V module pooling_fp16s.spv
/home/dji/project/ncnn/src/layer/vulkan/shader/lrn_square_pad_within_channel_pack4.comp
[ 30%] Building SPIR-V module pooling_fp16a.spv
/home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: 'readonly' : argument cannot drop memory qualifier when passed to formal parameter
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: '' : compilation terminated
ERROR: 2 compilation errors. No code generated.

SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1211: recipe for target 'src/pooling.spv.hex.h' failed
make[2]: *** [src/pooling.spv.hex.h] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: 'readonly' : argument cannot drop memory qualifier when passed to formal parameter
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: '' : compilation terminated
ERROR: 2 compilation errors. No code generated.

SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1215: recipe for target 'src/pooling_fp16p.spv.hex.h' failed
make[2]: *** [src/pooling_fp16p.spv.hex.h] Error 2
/home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp
/home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: 'readonly' : argument cannot drop memory qualifier when passed to formal parameter
ERROR: /home/dji/project/ncnn/src/layer/vulkan/shader/pooling.comp:84: '' : compilation terminated
ERROR: 2 compilation errors. No code generated.

SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1223: recipe for target 'src/pooling_fp16a.spv.hex.h' failed
make[2]: *** [src/pooling_fp16a.spv.hex.h] Error 2
CMakeFiles/Makefile2:478: recipe for target 'src/CMakeFiles/generate-spirv.dir/all' failed
make[1]: *** [src/CMakeFiles/generate-spirv.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
再次麻烦你啦，^_^





------------------ 原始邮件 ------------------
发件人: "nihui"<notifications@github.com>; 
发送时间: 2019年8月30日(星期五) 下午2:09
收件人: "Tencent/ncnn"<ncnn@noreply.github.com>; 
抄送: "Spock"<984943763@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Tencent/ncnn] 在大疆manifold2-g平台上编译ncnn+vulkan失败，如何解决 (#1227)




https://github.com/Tencent/ncnn/blob/af646b65774184aa9b6dda5b4459c543d8899eca/src/CMakeLists.txt#L100
 https://github.com/Tencent/ncnn/blob/af646b65774184aa9b6dda5b4459c543d8899eca/src/CMakeLists.txt#L119
 https://github.com/Tencent/ncnn/blob/af646b65774184aa9b6dda5b4459c543d8899eca/src/CMakeLists.txt#L138
 https://github.com/Tencent/ncnn/blob/af646b65774184aa9b6dda5b4459c543d8899eca/src/CMakeLists.txt#L157
 
这几行中把 -s 参数去掉，编译下，可以看到 glslangvalidator 错误信息

**Comment by nihui** [comment]
https://github.com/KhronosGroup/GLSL/issues/83

尝试回退这个更改
https://github.com/KhronosGroup/glslang/pull/1874

或者遇到 res = max(res, sfp2afp(bottom_blob_data[v_offset + x])); 这类的地方
参数先声明出来
比如
afp v = sfp2afp(bottom_blob_data[v_offset + x]);
res = max(res, v);

**Comment by CnybTseng** [comment]
非常感谢你的帮助，采用你的第二种建议，修改了如下几个文件：
pooling.comp
pooling_global.comp
pooling_global_pack4.comp
pooling_pack4.comp
priorbox_mxnet.comp
softmax_reduce_max.comp
softmax_reduce_max_pack4.comp
成功编译ncnn+vulkan，在NVIDIA Tegra X2上实际测试我的模型得到的结果正确无误！
再次感谢你的宝贵帮助！^_^ ^_^ ^_^

**Comment by nihui** [comment]
> 非常感谢你的帮助，采用你的第二种建议，修改了如下几个文件：
> pooling.comp
> pooling_global.comp
> pooling_global_pack4.comp
> pooling_pack4.comp
> priorbox_mxnet.comp
> softmax_reduce_max.comp
> softmax_reduce_max_pack4.comp
> 成功编译ncnn+vulkan，在NVIDIA Tegra X2上实际测试我的模型得到的结果正确无误！
> 再次感谢你的宝贵帮助！^_^ ^_^ ^_^

于是可以把你的修改发个 pull request 吗

**Comment by CnybTseng** [comment]
呵呵，没问题




------------------ 原始邮件 ------------------
发件人: "nihui"<notifications@github.com>; 
发送时间: 2019年8月30日(星期五) 下午4:42
收件人: "Tencent/ncnn"<ncnn@noreply.github.com>; 
抄送: "Spock"<984943763@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Tencent/ncnn] 在大疆manifold2-g平台上编译ncnn+vulkan失败，如何解决 (#1227)



 
非常感谢你的帮助，采用你的第二种建议，修改了如下几个文件：
 pooling.comp
 pooling_global.comp
 pooling_global_pack4.comp
 pooling_pack4.comp
 priorbox_mxnet.comp
 softmax_reduce_max.comp
 softmax_reduce_max_pack4.comp
 成功编译ncnn+vulkan，在NVIDIA Tegra X2上实际测试我的模型得到的结果正确无误！
 再次感谢你的宝贵帮助！^^ ^^ ^_^
  
于是可以把你的修改发个 pull request 吗

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/d11c4c1d42571d118f19a57317908762f5ee779f
