### ISSUE TITLE
vs2010 编译  error C3861: '_InterLockedCompareExchang‘

### ISSUE THREAD

**Issue by XueDx** [Tencent/ncnn#123]
我用cmake构建vs2010工程，编译时遇到error C3861: '_InterLockedCompareExchange问题。
另外git上以下 vs2013 vs2015 工程，编译通过，修改为vs2010也会遇到同样的C3861问题。
请问 NCNN 能用vs2010编译运行吗？

vs2015 https://github.com/guozhongluo/ncnn-vs2015-examples-demo
vs2013 https://github.com/liyemei/ncnn-windows-vs2013

编译器输出：
> Output
1> mat_pixle.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\memory(1047): error C3861: '_InterLockedCompareExchange': identifier not found
1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\memory(1054): error C3861: '_InterLockedIncrement': identifier not found
1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\memory(1059): error C3861: '_InterLockedIncrement': identifier not found
1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\memory(1064): error C3861: '_InterLockedDecrement': identifier not found
1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\memory(1073): error C3861: '_InterLockedDecrement': identifier not found

_InterLockedIncrement 指向 Microsoft Visual Studio 10.0\VC\include\intrin.h line 181，编译器却无法识别。

**Comment by cuixing158** [comment]
请问解决了吗，VS2013，ncnn2018012版本遇到同样问题

**Comment by guozhongluo** [comment]
用vs2015编译

**Comment by ran130683** [comment]
用vs2015编译，遇到同样的错误 +1

**Comment by GarrickLin** [comment]
https://github.com/Tencent/ncnn/issues/283

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/3977d32eb9de01a427e24e4ba0f99a53a32979c1
