### ISSUE TITLE
能否在TEE下运行，比如高通的QSEE？

### ISSUE THREAD

**Issue by szWingLee** [Tencent/ncnn#1235]
涉及安全问题，需要在TEE下运行。试了一下，似乎是因为有STL而不能运行。海思的麒麟系列也不行。编译可以通过，但运行直接退出；不加载ncnn功能可以运行。编译配置是这个：Build for ARM Cortex-A family with cross-compiling，aarch64.

**Comment by nihui** [comment]
没有试过，如果可以调试的话，贴下堆栈信息，或者 printf 检查是哪里的代码问题
也可以自己写个程序测试STL兼容性

**Comment by JoeyZhaoForWork** [comment]
我也考虑过这事。我猜测应该用指定的编译器，QSEE的版本不同，它指定的LLVM版本也不一样，指定的LLVM是和官网上不一样的，有修改。这样链接可能都有问题，即使链接过了，一切都OK，还有堆栈大小的限制，一般TEE就十几M的堆空间，越界就挂。

**Comment by szWingLee** [comment]
> 没有试过，如果可以调试的话，贴下堆栈信息，或者 printf 检查是哪里的代码问题
> 也可以自己写个程序测试STL兼容性

在可以在TEE运行的代码上加过STL测试，TA直接挂了，没有任何log输出，连调用STL之前的log都没有。编译和链接没有任何问题，堆空间也没有问题。OP-TEE之类倒是明确不支持STL的。我用的是linaro gcc 7.3.1，用这个编译器编译的不含C++的代码是可以在TEE跑的。
可以用STL声明，比如：
std::vector<int> a; //在TEE可以跑通
但调用会直接挂掉，比如：
a.push_back(1);//加入这句TEE直接失效，不能启动。

**Comment by nihui** [comment]
也许你可以自己实现下，ncnn我记得只用了string和vector

**Comment by szWingLee** [comment]
嗯嗯，我也有此想法，感谢。
