### ISSUE TITLE
将ncnn编译静态库改为动态库时，benchmark链接出错

### ISSUE THREAD

**Issue by liupengkd** [Tencent/ncnn#1240]
将src cmake文件里的add_library(ncnn STATIC ${ncnn_SRCS})改为add_library(ncnn SHARED ${ncnn_SRCS})，install(TARGETS ncnn EXPORT ncnn ARCHIVE  DESTINATION lib)改为install(TARGETS ncnn EXPORT ncnn LIBRARY DESTINATION lib)，能够得到libncnn.so,但是benchmark里的benchncnn会链接报错，显示各种未定义错误，如
[100%] Linking CXX shared library libncnn.so
[100%] Built target ncnn
Scanning dependencies of target benchncnn
[100%] Building CXX object benchmark/CMakeFiles/benchncnn.dir/benchncnn.cpp.o
[100%] Linking CXX executable benchncnn
CMakeFiles/benchncnn.dir/benchncnn.cpp.o: In function `benchmark(char const*, ncnn::Mat const&)':
benchncnn.cpp:(.text+0x3a): undefined reference to `ncnn::Net::Net()'
benchncnn.cpp:(.text+0xca): undefined reference to `ncnn::Net::set_vulkan_device(ncnn::VulkanDevice const*)'
benchncnn.cpp:(.text+0xfd): undefined reference to `ncnn::Net::load_param(char const*)'
benchncnn.cpp:(.text+0x1b4): undefined reference to `ncnn::Net::upload_model()'
benchncnn.cpp:(.text+0x1bc): undefined reference to `ncnn::Net::create_pipeline()'
如果是编译ncnn的静态库就不会有错

**Comment by nihui** [comment]
因为ABI不稳定，所以目前禁止动态库编译，建议自己外面封装下做成动态库

**Comment by nihui** [comment]
最新的release已提供动态库
