### ISSUE TITLE
Does this support RNN？

### ISSUE THREAD

**Issue by ccckj** [Tencent/ncnn#1245]
识别任务会用到RNN， 这个可以直接转吗？

**Comment by nihui** [comment]
现在支持 onnx LSTM 转换了，可以参考 https://github.com/ouyanghuiyu/chineseocr_lite

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
