### ISSUE TITLE
Split not supported yet!，ReduceMean not supported yet!

### ISSUE THREAD

**Issue by aa12356jm** [Tencent/ncnn#1246]
使用pytorch中shufflenet转换到ncnn中，出现Split not supported yet!，ReduceMean not supported yet!

**Comment by showwaychen** [comment]
@aa12356jm   我也碰到这个问题了，不知道你解决了没

**Comment by showwaychen** [comment]
@aa12356jm   我也碰到这个问题了，不知道你解决了没

**Comment by nihui** [comment]
Split implemented in https://github.com/Tencent/ncnn/commit/53d54115a8a35e8541994ba934fc0127ff8e5ee2
ReduceMean implemented in https://github.com/Tencent/ncnn/commit/04b4b023249865ae01befe4170a873d5f2ec33f8

**Comment by showwaychen** [comment]
@nihui   谢谢大佬。
