### ISSUE TITLE
param is too old, please regenerate network graph not ready

### ISSUE THREAD

**Issue by C-SJK** [Tencent/ncnn#1249]
在使用c++调用生成的ncnn.param.bin时
-----------------------------------------------------
	net.load_param_bin("ncnn.param.bin");
	net.load_model("ncnn.bin");
	ex.input(ncnn_param_id::BLOB_0, in);
	ex.extract(ncnn_param_id::BLOB_29, out);
-----------------------------------------------------
出现下面的错误
param is too old, please regenerate
network graph not ready
-----------------------------------------------------
请问是什么原因，如何解决呢？

**Comment by nihui** [comment]
update your caffe2ncnn/mxnet2ncnn/onnx2ncnn tool
generate ncnn model with the updated conversion tool
