### ISSUE TITLE
层名为“335” 类似的时候， ncnn2int8.cpp里解析table文件有bug

### ISSUE THREAD

**Issue by SophieChang66** [Tencent/ncnn#1251]
某个table文件如下
...
512_param_0 851.168762 609.982239 935.410034 673.293945 836.306213 671.169739
334 114.038055
...
按照ncnn2int8.cpp里read_int8scale_table()函数的解析方式，层名334以及后面的scale 114.038055都将被解析为weight的scale，而”334”层不存在了。
原始解析代码如下：
int nscan = sscanf(key, "%f", &scale);
            if (nscan == 1)
            {
                scales.push_back(scale);
                continue;
            }

建议将这个函数改为如下：
//add by Sophie in 2019-09-11
static bool read_int8scale_table_cplusplus(const char* filepath, std::map<std::string, std::vector<float> >& blob_int8scale_table, std::map<std::string, std::vector<float> >& weight_int8scale_table){
    blob_int8scale_table.clear();
    weight_int8scale_table.clear();
    std::string table_file = filepath;
    std::ifstream input(table_file);
    if(!input.is_open()){
        std::cout << "open " << filepath << " failed" << std::endl;
        return false;
    }
    while(!input.eof()){
        std::string keystr;
        std::vector<float> scales;
        keystr.clear();
        scales.clear();
        std::string line;
        std::getline(input, line);
        std::vector<std::string> content;
        content.clear();
        if(!line.empty()){
            std::stringstream ss(line);
            std::string sub_line;
            while(ss >> sub_line){
                content.emplace_back(sub_line);
            }
            if(content.size() > 1){
                keystr = content[0];
                for(int i = 1; i < content.size(); i++){
                    scales.emplace_back(std::atof(content[i].data()));
                }
                if (strstr(keystr.c_str(), "_param_"))
                {
                    weight_int8scale_table[ keystr ] = scales;
                }
                else
                {
                    blob_int8scale_table[ keystr ] = scales;
                }
            }
        }

    }
    return true;
}
看过ncnn2table.cpp文件，每层写结束都有换行符的。

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/pull/1341
