### ISSUE TITLE
Onnx conversion - shape, gather, unsqueeze, cast not supported - segmentation fault

### ISSUE THREAD

**Issue by pfeatherstone** [Tencent/ncnn#1254]
When using the onnx converter, i get the following errors:

Shape not supported yet!
Gather not supported yet!
  # axis=0
Shape not supported yet!
Gather not supported yet!
  # axis=0
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Squeeze not supported yet!
  # axes 7
Squeeze not supported yet!
  # axes 7
Squeeze not supported yet!
  # axes 7
Squeeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Cast not supported yet!
  # to=1
Shape not supported yet!
Gather not supported yet!
  # axis=0
Cast not supported yet!
  # to=1
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Cast not supported yet!
  # to=1
Shape not supported yet!
Cast not supported yet!
  # to=1
Segmentation fault (core dumped)

**Comment by nihui** [comment]
please post this issue to onnx-simplifier project

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
