### ISSUE TITLE
mxnet2ncnn MAERegressionOutput not supported yet!

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#1257]
Trying to convert a mxnet model to NCNN. The last layer of the model is a MAERegressionOutput.
When I run the mxnet2ncnn executable, I get the following error: `MAERegressionOutput not supported yet!` 
Are there any work arounds or fixes?

**Comment by nihui** [comment]
simply delete the MAERegressionOutput line, adjust the layer count / blob count

or register a noop for it
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#layer-xyz-not-exists-or-registered

**Comment by nihui** [comment]
implemented in https://github.com/Tencent/ncnn/commit/d67d2531ae5c630757d0144359a31701af8de9f6
