### ISSUE TITLE
android lib除了 armeabi-v7a和arm64-v8a，ncnn还支持armeabi ，x86和x86_64 吗？

### ISSUE THREAD

**Issue by awarmisland** [Tencent/ncnn#1259]
下载了android build demo 发现里面只有 armeabi-v7a 和arm64-v8a 的库，看文档编译说明，也是只有这两个类型的，请问ncnn 支持armeabi，x86，x86_64吗？

**Comment by nihui** [comment]
可以只编译这两个架构的版本

https://github.com/nihui/ncnn-android-squeezenet/blob/a04eb835898aa6dc42e43ecd3816cac130e98612/app/build.gradle#L12

**Comment by kkeyong** [comment]
那其他平台（armeabi，x86，x86_64）可以直接用吗？还是只能在armeabi-v7a 和arm64-v8a这两个平台编译。 @nihui

**Comment by nihui** [comment]
armeabi，x86，x86_64 这三个平台因为市场太小了，没必要编译进来

**Comment by kingaza** [comment]
但是x86的模拟器快很多啊。。。
