### ISSUE TITLE
onnx2ncnn does not support Slice axes

### ISSUE THREAD

**Issue by arnaudbrejeon** [Tencent/ncnn#1261]
ONNX Slice operation has axes attribute and it is not supported by onnx2ncnn. This leads to memory exceptions during inference because the conversion is not correct

**Comment by arnaudbrejeon** [comment]
I made a pull request that fixes the issue: https://github.com/Tencent/ncnn/pull/1262

**Comment by nihui** [comment]
I added the starts, ends, axes attributes to crop, please test
https://github.com/Tencent/ncnn/commit/a6c60068e69c1458f1ad3c707a74239e2ccbdeff

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
