### ISSUE TITLE
Crop across w axis not supported?

### ISSUE THREAD

**Issue by wwwanghao** [Tencent/ncnn#1264]
Crop parameters:
     woffset : 0    hoffset : -233        coffset :     -233      
     outw: 2        outh: -233             outc:-233

input dimension: 
     c:1 h:3000 w:4
output dimension
      c:1 h:2 w:4

normally, the output dimension should be   c:1   h:3000    w:2.
If there is misunderstanding, please give me some suggestion, Thank you!

**Comment by arnaudbrejeon** [comment]
Can you try to set offset and coffset to 0? I had a similar issue and it may have fixed it.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/a6c60068e69c1458f1ad3c707a74239e2ccbdeff
