### ISSUE TITLE
使用ndk同时编译openCV4.1和ncnn的动态库时出错

### ISSUE THREAD

**Issue by CodingMice** [Tencent/ncnn#1265]
同时加载ncnn和openCV静态库时，ncnn里面include里面的opencv.h是否会和OpenCV里面的opencv.hpp冲突？

**Comment by nihui** [comment]
不冲突，ncnn里的opencv.h不include就行

**Comment by xiakj** [comment]
@nihui ncnn编译的时候opencv支持的版本是3还是4啊？
