### ISSUE TITLE
group convolution 输出结果与caffe下结果不对应

### ISSUE THREAD

**Issue by xskxushaokai** [Tencent/ncnn#1268]
模型从caffe转到ncnn，convolution层， group为3，inchannel和outchannel数大于group，转到ncnn后type自动转为ConvolutionDepthWise，看了以下转了以后的参数都是对的，but depthwise层inference的结果与caffe下的结果不一致，用相同的输入图片和常量矩阵都试过，都不一致。
还有另一个问题，extractor的light_mode设置成true输出的结果跟设置为false输出的结果也不一致。并且当light_mode设置为false时，3x3的kernel，stride=1，group=3的DepthwiseConv层输出恒为0。

**Comment by nihui** [comment]
没有重现这个问题
请提供 caffe prototxt 和 caffemodel

**Comment by nihui** [comment]
如果有更新，可以reopen issue
