### ISSUE TITLE
 ncnn/src/layer/arm/softmax_arm.cpp  has error

### ISSUE THREAD

**Issue by hdmjdp** [Tencent/ncnn#1269]
https://github.com/Tencent/ncnn/blob/50f69f1755400445a832b83c3d6d69a5d7175608/src/layer/arm/softmax_arm.cpp#L187

这里算的是每个寄存器里对应元素的最大值，不是每行的最大值。后面求sum也是。最后输出的结果，应该是一行 每隔4个的softmax。并不是在一行上面进行归一化吧

**Comment by nihui** [comment]
这里是每行的最大值，注意这里是 elempack = 4
_max 最后得到的四个值是第0/1/2/3行的max
_sum 最后得到的四个值是第0/1/2/3行的sum
