### ISSUE TITLE
安卓上，指定2核，但是adb shell中 top显示有8核在运行。

### ISSUE THREAD

**Issue by zxDeepDiver** [Tencent/ncnn#1270]
如下图所示：
通过
`		ncnn::set_cpu_powersave(2);
		ncnn::set_omp_dynamic(0);
    	        ncnn::set_omp_num_threads(2);`
设置了在两个大核运行，但是adb shell中top查看资源占用，发现有8个核被利用。请问这个是哪里设置错了吗？

![image](https://user-images.githubusercontent.com/7352077/65494206-f1146200-dee6-11e9-9a33-e0ee81e11929.png)

**Comment by zxDeepDiver** [comment]
上面com.ex...是我的安卓程序。手机型号是麒麟950.

**Comment by nihui** [comment]
这是因为 substract_mean_normalize 曾经没有遵循 openmp 设置，新版本应该不会有问题了，如果有问题请 reopen issue
