### ISSUE TITLE
ncnn fp32 VS tensorflow_lite

### ISSUE THREAD

**Issue by SophieChang66** [Tencent/ncnn#1274]
@nihui, 你好，你就某一个模型，对比过ncnn和tf-lite的耗时吗？fp32计算方式的~

**Comment by BUG1989** [comment]
ncnn快！

**Comment by SophieChang66** [comment]
我对比的也是这个结论，有一个模型我在ncnn上跑11毫秒，在tf-lite上居然有18毫秒（如果我没有犯什么错误的话）。同一个平台，都是单线程~还记得，ncnn会比tf-lite大约快多少比例吗？

**Comment by SophieChang66** [comment]
> ncnn快！
我对比的也是这个结论，有一个模型我在ncnn上跑11毫秒，在tf-lite上居然有18毫秒（如果我没有犯什么错误的话）。同一个平台，都是单线程~还记得，ncnn会比tf-lite大约快多少比例吗？

**Comment by SophieChang66** [comment]
> ncnn快！

**Comment by SophieChang66** [comment]
@BUG1989 不小心close 了issue，我有一个模型，同一个平台，单线程，f32计算，ncnn耗时11ms， tf-lite耗时18ms，请问这正常吗？你测试的时候，一般慢多少比例啊

**Comment by SophieChang66** [comment]
@BUG1989 ，看大神的头像是int8, ncnn和Tengine，那这两个对比过吗？

**Comment by lyyiangang** [comment]
@SophieChang66 比较过ncnn版本的mobilenet和tflite 版本的mobilenet， tflite 的int8模型速度接近于ncnn的float32模型，如果你模型不quant， 还是ncnn更快。

**Comment by SophieChang66** [comment]
@nihui @lyyiangang 我的测试对比是：tflite的f32比ncnn的f32慢挺多，有些成倍的慢，因此即使tflite量化后能成倍提升，还是和ncnn的f32相当，和你的结论一致。既然这样，那tflite相比ncnn，那不是一点优势都没有吗？

**Comment by brucechou1983** [comment]
兩個引擎都經過多次改版了，有朋友有做最新的比較嗎？

**Comment by lyyiangang** [comment]
> @nihui @lyyiangang 我的测试对比是：tflite的f32比ncnn的f32慢挺多，有些成倍的慢，因此即使tflite量化后能成倍提升，还是和ncnn的f32相当，和你的结论一致。既然这样，那tflite相比ncnn，那不是一点优势都没有吗？

感觉tflite是没啥优势。。。

**Comment by fzyzcjy** [comment]
2021年有朋友做过比较吗，两个库又都变化很多了

**Comment by yinghuang** [comment]
2022年有朋友做过比较吗

**Comment by csukuangfj** [comment]
ncnn 这么香，不用选其他的了。
