### ISSUE TITLE
yolov3-tiny在hisiv300上加载模型的时候崩溃

### ISSUE THREAD

**Issue by cyf518** [Tencent/ncnn#1275]
在windows上可以正确加载并运行
在3559a上也可以正确加载并运行
但在3516a （hisiv300）上，一加载模型就segment fault

**Comment by cyf518** [comment]
问题找到了，是因为yolo-tiny模型在加载的时候消耗过多内存引起的

**Comment by nihui** [comment]
对于硬件内存不足，可以关掉 net.opt.use_sgemm_convolution net.opt.use_winograd_convolution 开关，减少内存使用，但是速度会变慢
