### ISSUE TITLE
output float with -1.#QNAN000

### ISSUE THREAD

**Issue by billtiger** [Tencent/ncnn#1277]
@nihui 您好，我的ncnn模型是由MXNet模型转换得到的，转换时没出现错误。
但是前向输出特征是输出的值都是-1.#QNAN。
我测试了其他模型不会出现这种错误，我这个模型用了全局平均池化和全局最大池化，是否和这两个操作有关系？
希望得到您的答复，谢谢！

**Comment by billtiger** [comment]
解决了，我的模型中有minus_scalar操作，数值为1.0，但是转换成ncnn后的参数文件中为2=1，需要将2=1改成2=1.0才能输出正确结果。
所以ncnn用%g替换%f输出参数，是否会存在一些bug？ @nihui

**Comment by nihui** [comment]
感谢反馈，最新的代码已经改成 %e 了
