### ISSUE TITLE
keyError:'frobenius_norm'

### ISSUE THREAD

**Issue by mapleyuan** [Tencent/ncnn#1280]
Hi guys, I want to transfer .pt to .onnx, but i got a error. 
![image](https://user-images.githubusercontent.com/6057711/65828523-58a72480-e2ce-11e9-867f-f8a8282ea486.png)

**Comment by mapleyuan** [comment]
![image](https://user-images.githubusercontent.com/6057711/65828538-783e4d00-e2ce-11e9-8aa3-09a70abe24b7.png)

**Comment by nihui** [comment]
There may be unsupported operator or a compatibility issue of pytorch onnx.
You would better posting your issue to onnx or pytorch project.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
