### ISSUE TITLE
Im2col implementation of 3x3 stride 2 convolution produces incorrect result

### ISSUE THREAD

**Issue by Timen** [Tencent/ncnn#1283]
I found that the im2col implementation of the 3x3 conv with stride 2 called here:
https://github.com/Tencent/ncnn/blob/6703286831359c098b97b68311844f5aae5193a1/src/layer/arm/convolution_arm.cpp#L1236

Produces 1 incorrect pixel (at index 40) in every output channel when being run on a 14x14x20 input with SAME padding and producing a 7x7x42 output. A quick work around is disabling the im2col and always using conv3x3s2_packed_neon which produces the correct results.

**Comment by tpoisonooo** [comment]
I suggest that add result check in auto pack model.
Now that convolution could be implemented with multiple approach, we can compare different methods' result.

**Comment by nihui** [comment]
fixed
Thanks for your report !
