### ISSUE TITLE
Ubuntu16.0.4 compile error: [error: ‘numeric_limits’ is not a member of ‘std’]

### ISSUE THREAD

**Issue by kame-lqm** [Tencent/ncnn#1287]
Need to add head file "#include <limits>" to "ncnn2table.cpp" to fixed this compile bug.

**Comment by kame-lqm** [comment]
Need to add head file  #include <limits> to "ncnn2table.cpp"

**Comment by kame-lqm** [comment]
add head file #include \<limits\>

**Comment by cyrusbehr** [comment]
why not make a pull request if it's a simple solve?

**Comment by kame-lqm** [comment]
Sorry, it's my fault.
