### ISSUE TITLE
libgomp: Thread creation failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by luyahan** [Tencent/ncnn#1290]
我在hi3519 soc上运行ncnn 会出现libgomp: Thread creation failed: Resource temporarily unavailable ，请问如何关闭openmp?
我已经在cmake里 把openmp设置为 option(NCNN_OPENMP "openmp support" OFF)

**Comment by Bananajia** [comment]
在你的toolchain的cmakefile的openmp 选项也去掉 也就是去掉-fopenmp

**Comment by swithmn1** [comment]
@Bananajia  没找到你说的cmakefile文件呢？
