### ISSUE TITLE
any RNN model could be used in cellphone ?

### ISSUE THREAD

**Issue by ucasiggcas** [Tencent/ncnn#1293]
hi,
glad to see the project, I just want to use the RNN model trained by tensorflow in phone,
and the RNN model is easy, as follows

`def multi_layer_dynamic_gru(input_x,n_steps,n_hidden):
    stacked_rnn = []
    for i in range(3):
        stacked_rnn.append(tf.nn.rnn_cell.GRUCell(num_units=n_hidden))
    mcell = tf.contrib.rnn.MultiRNNCell(cells=stacked_rnn)
    hiddens,states = tf.nn.dynamic_rnn(cell=mcell,inputs=input_x,dtype=tf.float32)
    hiddens = tf.transpose(hiddens,[1,0,2])
    return hiddens,states`

and this is the [link](https://github.com/HankPeng03/DeepLearning-Demo/blob/3e629bad925b275349ae5bd4bbf78e6ea6a09b6b/RNN/multi_layer_rnn.py)

any helpful idea ?
thx

**Comment by nihui** [comment]
RNN model is not supported
You may try tensorflow-lite, which is the edge framework suitable for deploying tensorflow models
