### ISSUE TITLE
vulkan interpreter use huge memory and not faster on iphone6 plus 

### ISSUE THREAD

**Issue by laohur** [Tencent/ncnn#1294]
squeezenetv1
from https://github.com/chrisYooh/ncnnSrcDemo:  480m
myapp framwork20190909   :
 cpu  40m 9ms 
 gpu 480m 10ms

**Comment by nihui** [comment]
The speed is in line with expections.
The soc Apple A8, equipped with iphone6 plus, is slow for computing workload.
You'd better always using cpu for small models.
That's why the ios coreml api never works on Apple A7/A8 gpu

**Comment by laohur** [comment]
> 
> 
> The speed is in line with expections.
> The soc Apple A8, equipped with iphone6 plus, is slow for computing workload.
> You'd better always using cpu for small models.
> That's why the ios coreml api never works on Apple A7/A8 gpu
same as on iphone xs. 
even mobilenet2 get menory error when extract  on vulkan
