### ISSUE TITLE
How to build for Android with Vulkan support

### ISSUE THREAD

**Issue by jfindley8** [Tencent/ncnn#1300]
Hi there,

First of all, great library! It's exactly what I was looking for, thank you for sharing it!

I got an ONNX model to run in Android using the 20190908 91ef4ee release. It works correctly on CPU, but when I try to run on GPU it simply returns zero.

I'd like to debug this issue, and to that end I've been trying to rebuild the library with debugging info. I did that successfully for the CPU version, but when trying to build a version with Vulkan support I'm struggling with getting a Vulkan SDK for android.

In your wiki (https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android) you suggest to download and install vulkan-sdk from https://vulkan.lunarg.com/sdk/home:

```
$ wget https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-x86_64-1.1.92.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.1.92.1.tar.gz
$ tar -xf vulkansdk-linux-x86_64-1.1.92.1.tar.gz

# setup env
$ export VULKAN_SDK=`pwd`/1.1.92.1/x86_64
```

But that's a SDK for linux x86, not for Android.

So my question is: how did you build the Android release with Vulkan support?
Where did you get the SDK? My understanding is that it comes with Android Studio, but I could not find a path in there that works with `VULKAN_SDK`, as Android Studio organizes files differently.

Any suggestions/pointers will be appreciated.

**Comment by nihui** [comment]
do follow the wiki how-to-build
yes, the vulkan-sdk is for linux x86, it is the compiler, not the runtime
the android-ndk is also for linux x86, isn't it ?

**Comment by jfindley8** [comment]
Just to be clear, I'm on a mac, trying to compile for armv7 and aarch64.

I thought `vulkansdk-linux-x86_64-1.1.92.1.tar.gz` had both compiler and target as x86, no?

And the android SDK would have compiler for linux or mac (depending on the version of Android Studio you download), but targeting armv7 and aarch64?

I tried `https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/latest/mac/vulkan-sdk.tar.gz` (as I'm on a mac), but here's what I get:

```
$ echo $ANDROID_NDK
/Users/username/Library/Android/sdk/ndk-bundle

$ echo $ANDROID_SDK
/Users/username/Library/Android/sdk

$ echo $VULKAN_SDK
/Users/username/ncnn/vulkansdk-macos-1.1.121.1/macOS/

$ cmake -DNCNN_VULKAN=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-14 ..
-- CMAKE_TOOLCHAIN_FILE = /Users/username/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /Users/username/ncnn/build-android-armv7-debug/install
-- android-14 is unsupported. Using minimum supported version 16.
-- Found glslangValidator: /Users/username/ncnn/vulkansdk-macos-1.1.121.1/macOS/bin/glslangValidator
CMake Error at /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.15.4/share/cmake/Modules/FindVulkan.cmake:71 (find_package_handle_standard_args)
  src/CMakeLists.txt:298 (find_package)
```

**Comment by jfindley8** [comment]
To further clarify what I mean: if you look at the target libvulkan.so in the vulkan linux sdk (as suggested in the wiki), you can see it is for x86_64:

```
$ file 1.1.92.1/x86_64/lib/libvulkan.so.1.1.92
1.1.92.1/x86_64/lib/libvulkan.so.1.1.92: ELF 64-bit LSB pie executable x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=f035d79faa9d636f41492f5fef1919e5868bdb34, not stripped
```

**Comment by nihui** [comment]
update ncnn source
the latest ncnn does not rely on vulkan sdk for compiling vulkan support
