### ISSUE TITLE
Grouped convolution quantisation issue

### ISSUE THREAD

**Issue by ShuangLiu1992** [Tencent/ncnn#1304]
Current implmentation of the quantize tool produces wrong result when it's not depthwise (i.e. groups = in_channel = out_channel). I'm investigating the bug myself now but haven't been able to fix the problem, would the author have any tips or hints towards this?
@nihui @BUG1989

**Comment by nihui** [comment]
It may be a known issue, move to https://github.com/Tencent/ncnn/issues/1234
