### ISSUE TITLE
ncnn::Mat 访问元素和赋值

### ISSUE THREAD

**Issue by BingranHu** [Tencent/ncnn#1309]
请问如果不通过转换成cv::Mat的方法（to_pixels），能否直接对ncnn::Mat 元素进行遍历访问和赋值操作？谢谢！

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki#print-mat-content

**Comment by BingranHu** [comment]
> https://github.com/Tencent/ncnn/wiki#print-mat-content
感谢回复！
