### ISSUE TITLE
lighten cnn 转换模型问题

### ISSUE THREAD

**Issue by xiaomage11** [Tencent/ncnn#131]
@nihui，@eeric，lighten cnn  caffe C模型转换成功，逐层对比数据在pool4层之前与caffe的数据都是相同的，但在etlwise_fc1提取的256维特征与caffe版的特征值有差别，在fc1层操作后就出现差异了。看到有人提过这个问题，请大神帮忙解释一下，出现过这个问题的朋友你是否解决了这个问题，如何解决的请赐教。

**Comment by xiaomage11** [comment]
@nihui，不知这个问题您是否知道如何解决，或是目前没有办法解决，或是我在操作时出现什么问题。

**Comment by zhenglaizhang** [comment]
@xiaomage11 您好，我也在尝试，遇到同样的问题，你这边有解决了么？

**Comment by sunbinbin1991** [comment]
我也有模型转换的问题，我的是mxnet 最后一个层的类别数是不对的

**Comment by nihui** [comment]
请使用最新代码验证下，是否还存在问题...
近期修复了 maxpooling 2x2 stride=2 的 bug

**Comment by nihui** [comment]
lightencnn C 模型与caffe输出结果，已验证没有问题，请更新最新的代码
