### ISSUE TITLE
Ubuntu18.04 ncnn+vulkan ‘VkTransfer’ has not been declared

### ISSUE THREAD

**Issue by wangergou135** [Tencent/ncnn#1311]
参考步骤https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux-x86

运行cmake -DNCNN_VULKAN=ON ..   &&  make -j8时报错

batchnorm_vulkan.h:30:30: error: ‘VkTransfer’ has not been declared
batchnorm_vulkan.h:33:33: error: ‘VkMat’ has not been declared

详细：
[ 80%] Building CXX object src/CMakeFiles/ncnn.dir/layer/vulkan/absval_vulkan.cpp.o
[ 80%] Building CXX object src/CMakeFiles/ncnn.dir/layer/batchnorm.cpp.o
[ 80%] Building CXX object src/CMakeFiles/ncnn.dir/layer/vulkan/batchnorm_vulkan.cpp.o
In file included from /home/ysh/face_ssd/ncnn/src/layer/vulkan/absval_vulkan.cpp:15:0:
/home/ysh/face_ssd/ncnn/src/layer/vulkan/absval_vulkan.h:31:33: error: ‘VkMat’ has not been declared
     virtual int forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& opt) const;
                                 ^~~~~
/home/ysh/face_ssd/ncnn/src/layer/vulkan/absval_vulkan.h:31:57: error: ‘VkCompute’ has not been declared
     virtual int forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& opt) const;
                                                         ^~~~~~~~~
/home/ysh/face_ssd/ncnn/src/layer/vulkan/absval_vulkan.h:34:5: error: ‘Pipeline’ does not name a type; did you mean ‘timezone’?
     Pipeline* pipeline_absval;
     ^~~~~~~~
     timezone

**Comment by nihui** [comment]
查看 build/src/platform.h 文件中，NCNN_VULKAN 宏是否为1
如果不是1，删除build目录，重新执行cmake -DNCNN_VULKAN=ON .. 生成看看

**Comment by wangergou135** [comment]
@nihui 看了下，NCNN_VULKAN=1

**Comment by nihui** [comment]
你找找系统里是否存在 platform.h，比如 /usr/include /usr/local/include 这些地方，可能有同名头文件，然后里头 NCNN_VULKAN=0

**Comment by wangergou135** [comment]
@nihui 感谢，找到问题了，
在./build/src/platform.h里NCNN_VULKAN=1，
在./src/platform.h里有定义NCNN_VULKAN=0， 把./src/platform.h里的改为1即通过编译
