### ISSUE TITLE
core dumped while running retinaface

### ISSUE THREAD

**Issue by wangergou135** [Tencent/ncnn#1312]
steps:
1.make ncnn with vulkan support
2.download mnet.25*.json and mnet.25*.param from https://github.com/deepinsight/insightface/issues/669
3.run command ./mxnet2ncnn mnet.25*.json and mnet.25*.param in build/tools/mxnet
4.run ./retinaface a.png

只要extract mobilenet0_relu10_fwd_splitncnn_0 mobilenet0_relu10_fwd_splitncnn_1后面的blob都会显示core dumped，extract之前的blob都没有问题

好像是Split layer导致的问题，retinaface 跑不起来。

**Comment by nihui** [comment]
更新下最新的代码试试看，我这里 cpu gpu 都是正常的

**Comment by wangergou135** [comment]
下了最新的代码，重新试了下，这个问题就没了，
谢谢，打扰了。。
