### ISSUE TITLE
vulkan计算结果是nan

### ISSUE THREAD

**Issue by veepersgit** [Tencent/ncnn#1313]
从caffe转过来的模型，用CPU计算正常，用vulkan就是nan。

**Comment by veepersgit** [comment]
感谢大佬，问题解决！

**Comment by sunjunlishi** [comment]
我也是，开启 GPU计算，错误。
ncnn::create_gpu_instance();
	const char *model = "E:/tools/project_other/chineseocr_lite-master/ncnn_project/models/psenet_lite_mbv2.bin";
	const char *model_param = "E:/tools/project_other/chineseocr_lite-master/ncnn_project/models/psenet_lite_mbv2.param";
	psenet.opt.use_vulkan_compute = 1;
	psenet.opt.use_fp16_packed = false;
	psenet.opt.use_fp16_storage = false;
	psenet.opt.use_fp16_arithmetic = false;
	psenet.opt.use_int8_storage = false;
	psenet.opt.use_int8_arithmetic = false;
	doInit(model, model_param, psenet);

**Comment by sunjunlishi** [comment]
我显卡的原因或者驱动我的太老了，mx130
