### ISSUE TITLE
Can't include libraries (Makefile without CMake)

### ISSUE THREAD

**Issue by sebastianfelipe** [Tencent/ncnn#1314]
Hi everybody,

I'm trying to compile an example code without CMake. I have these flags added to the compilation process:
```
CFLAGS = -std=c++11 -fPIE -fopenmp -DLINUX
IFLAGS = -I $(GTISDKPATH)/Include/ \
        `pkg-config opencv --cflags` \
        -I /usr/local/lib/ncnn/build/src -isystem /usr/local/lib/opencv \
        -I /usr/local/lib/ncnn/build/install/include/ncnn 

LFLAGS = -L -pthread -ldl -lpthread \
        `pkg-config opencv --libs` \
        -Wl,-rpath,/usr/local/lib \
        -L /usr/local/lib \
        -L /usr/local/lib/ncnn/build/install/lib/libncnn.a \
        -L /usr/local/lib/libopencv_highgui.so.3.3.0 \
        -L /usr/lib/gcc/x86_64-linux-gnu/5/libgomp.so \
        -L /usr/local/lib/libopencv_imgcodecs.so.3.3.0 \
        -L /usr/local/lib/libopencv_imgproc.so.3.3.0 \
        -L /usr/local/lib/libopencv_core.so.3.3.0 \
        -Wl,-rpath-link,/usr/local/lib
```

Everything works well with OpenCV itself, but whatever about ncnn, I have errors like this:

```
<location of my example> undefined reference to `ncnn::Net::Net()'
```

So it seems like it is not recognising the libs or I'm doing something wrong. Can you help to compile an example but outside the ncnn context and manually doing a Makefile?

I'd really appreciate your help.

Thanks,
Sebastián.

**Comment by nihui** [comment]
add -lncnn to your LFLAGS

**Comment by sebastianfelipe** [comment]
Thanks for answering. It says:
````
/usr/bin/ld: cannot find -lncnn
````
How can I compile with lncnn flag then?

**Comment by sebastianfelipe** [comment]
I already made it! Put -lncnn flag just after ```-L /usr/local/lib/ncnn/build/install/lib````

Thanks! I hope this solution works for someone else too.

**Comment by docongminh** [comment]
@nihui hi, could you help me ? How to download -lncnn because i also got stuck into this problem. 
Thanks !
![Screenshot from 2020-11-06 11-21-18](https://user-images.githubusercontent.com/34453681/98340315-c3816e00-203f-11eb-918a-8c46e20f8a2e.png)
