### ISSUE TITLE
add more broadcasting type in binaryop

### ISSUE THREAD

**Issue by bindog** [Tencent/ncnn#1317]
As we introduce keepdims in reduction op, there exist some cases which are not supported by binaryop. For example: A [7, 7, 1024] B[7, 7, 1] and so on...what do you think about it? @nihui

We can make some discussion here. I'd like to work on it~

**Comment by nihui** [comment]
yeah, do whatever you want.
you're awesome.
and add new broadcasting type in
https://github.com/Tencent/ncnn/blob/master/docs/developer-guide/binaryop-broadcasting.md

**Comment by nihui** [comment]
implemented in https://github.com/Tencent/ncnn/commit/ab4cfbf5b05550f38f6aa562c1e583fa92d73da3
