### ISSUE TITLE
Unable to run in single thread mode

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#1318]
I am running the benchmark executable to test the number of threads. 
When I run the exe with the following commands, it works as expected:
`./benchncnn 1 2 0 -1`
Running `cat /proc/<PID>/status | grep Threads` outputs `Threads:	2` which is expected.

However, when I try to set the number of threads to 1, it looks like it is using the default number of threads on the machine. 
`./benchncnn 1 1 0 -1`
Running `cat /proc/<PID>/status | grep Threads` outputs 'Threads:	20'

For reference, I am using a fresh install digital ocean machine, 20VCPUs, running Ubuntu 18.04.3 LTS

**Comment by hellocsi** [comment]
Did you check the PID number every time?
