### ISSUE TITLE
onnx2ncnn not supported yet

### ISSUE THREAD

**Issue by onexuan** [Tencent/ncnn#1322]
Shape not supported yet!
Gather not supported yet!
Cast not supported yet!
  # to=1
Cast not supported yet!
  # to=6
Unsupported reduction axes !
Unsqueeze not supported yet!
  # axes 7
Cast not supported yet!
  # to=7

**Comment by nihui** [comment]
see
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#simplify-onnx-model

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by zengjie617789** [comment]
pnnx 使用pip安装，那么怎么用呢？ 使用哪的 ".pnnx"； 如果从source build, 会显示需要安装cuda
