### ISSUE TITLE
How to PR mobilenetv3-ssd detection model?

### ISSUE THREAD

**Issue by ujsyehao** [Tencent/ncnn#1323]

**Comment by nihui** [comment]
you can refer this PR
https://github.com/Tencent/ncnn/pull/929

**Comment by ujsyehao** [comment]
This is my model repository: https://github.com/ujsyehao/mobilenetv3-ssd

**Comment by ivankk2003** [comment]
> This is my model repository: https://github.com/ujsyehao/mobilenetv3-ssd

Dear Sir,
this link is overdue...
could you kindly release it once again.
Thanks!
