### ISSUE TITLE
ONNX2NCNN MemoryData dims problem

### ISSUE THREAD

**Issue by GuoxiaWang** [Tencent/ncnn#1330]
[onnx2ncnn.cpp#L929-L940](https://github.com/Tencent/ncnn/blob/master/tools/onnx/onnx2ncnn.cpp#L929)

I think the dims do not remove batch dimension. Please review. If need, I can request PR to fix this bug.

**Comment by nihui** [comment]
hi, please create a PR for it
I appreciate your contribution :D

**Comment by nihui** [comment]
merged https://github.com/Tencent/ncnn/pull/1331
