### ISSUE TITLE
ncnn::Mat dims = 3  mat.c = １, mat.h = mat.w = -1 

### ISSUE THREAD

**Issue by zhanhe18** [Tencent/ncnn#1337]
@nihui 你好，请问extract 后　dims为３，mat.c = 1 但是mat.h 与mat.w 均为-1 ，请问为什么，谢谢．

**Comment by nihui** [comment]
是什么模型？

**Comment by zhanhe18** [comment]
是faster-rcnn的模型，可能是我的输入不对，我使用cv::Mat存储图片，然后把cv::Mat从NHWC转成NCHW格式，这样使用ncnn::Mat的constructor构造，拿出来一个层的中间结果就是这样的．没有使用from_pixel请问这样可以吗？谢谢．

**Comment by nihui** [comment]
faster-rcnn可以参考这个
https://github.com/Tencent/ncnn/blob/master/examples/fasterrcnn.cpp

**Comment by magicse** [comment]
> 是faster-rcnn的模型，可能是我的输入不对，我使用cv::Mat存储图片，然后把cv::Mat从NHWC转成NCHW格式，这样使用ncnn::Mat的constructor构造，拿出来一个层的中间结果就是这样的
I have the same problem.
Hi could you help me. How did you convert NHWc to NCHW ?
