### ISSUE TITLE
在树莓派2上（ubuntu的系统）上编译运行比caffe慢2倍？

### ISSUE THREAD

**Issue by Weyne168** [Tencent/ncnn#134]
你好，我们在树莓派2（cortex-A7架构）的开发板上编译运行了squeezenet demo，但结果是caffe的时间大概是300ms左右，而ncnn则超过600ms，请问是否正常，或者可能是有些编译选项没设置？（我们已经加了armeabi-v7a O3）

**Comment by nihui** [comment]
参考 #28

**Comment by Lebron8997** [comment]
你好,我这里也是树莓派2,从测试看squeezenet demo ,caffe+openblas 时间大概是300ms左右, 编译不用 Neon是 1100ms, 用 Neon 是 600 ms (参考 #28), 感觉比 caffe 慢得多啊? 还请多多指教
[CMakeCache.txt](https://github.com/Tencent/ncnn/files/1301783/CMakeCache.txt)

**Comment by wl3b10s** [comment]
我在 8xA53下跑squeezenet是80ms左右。 你看看你运行时是不是没打开多线程并行？

**Comment by nihui** [comment]
wiki how to build 更新了树莓派3和arm-linux交叉编译方法，可参考
