### ISSUE TITLE
Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 

### ISSUE THREAD

**Issue by wanzghen0123** [Tencent/ncnn#1342]
cmake的时候显示如下：
-----------------------------------------------
-- CMAKE_INSTALL_PREFIX = /home/wangzhen/Tensorflow/darknet2ncnn/ncnn/build/install
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
CMake Warning at tools/caffe/CMakeLists.txt:12 (message):
  Protobuf not found, caffe model convert tool won't be built

-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
CMake Warning at tools/onnx/CMakeLists.txt:12 (message):
  Protobuf not found, onnx model convert tool won't be built

-- Configuring done
-- Generating done
---------------------------------------------
请问是什么问题？？

**Comment by nihui** [comment]
apt-get install libprotobuf-dev protobuf-compiler

**Comment by yjiangling** [comment]
> apt-get install libprotobuf-dev protobuf-compiler

But if I'm not root and I have successfully installed protobuf by hand. How can I solve this problem?

**Comment by zeakey** [comment]
I installed protobuf compiler through `conda install `.

In my case, adding `-DProtobuf_INCLUDE_DIR=/data/home/kaiserzhao/anaconda3/envs/py36/include/google/protobuf`
to the cmake command in `build.sh` solved the problem.

**Comment by AlphaNext** [comment]
Solution here:
1. install protobuf , ref: [this link](https://www.jianshu.com/p/00be93ed230c)
2. set CMakeLists.txt, ref: [this link](https://www.jianshu.com/p/ae5c56845896)
      ```  
      set(Protobuf_PREFIX_PATH
          "/home/xx/soft/protobuf-3.8.0/include"            
          "/home/xx/soft/protobuf-3.8.0/lib"             
          "/home/xx/soft/protobuf-3.8.0/bin" )
      list(APPEND CMAKE_PREFIX_PATH "${Protobuf_PREFIX_PATH}")
      find_package(Protobuf REQUIRED)
      ```

hope this could help you!

**Comment by nfhe** [comment]
> I installed protobuf compiler through `conda install `.
> 
> In my case, adding `-DProtobuf_INCLUDE_DIR=/data/home/kaiserzhao/anaconda3/envs/py36/include/google/protobuf` to the cmake command in `build.sh` solved the problem.

hi ,man

I have the same question. Can you give me a detailed step and tutorial? Thank you very much.

**Comment by charlesMrH** [comment]
uninstall and then reinstall with source code like this  https://github.com/protocolbuffers/protobuf/blob/master/src/README.md. 
I solved this problem by so.

**Comment by xifen523** [comment]
> 

yeah  thank you ！！my cmake is work
