### ISSUE TITLE
caffe2ncnn： ncnn 中的 slice 层是否支持 w, h 维度的切分？

### ISSUE THREAD

**Issue by popper0912** [Tencent/ncnn#1349]
我的caffe网络对图像做了 w, h 维度的切分，转化为 ncnn 后，取得slice层数据为空。如何是好？请大佬相助。谢谢

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/c9a9128db7480745700c1abd17926c64ca832f03

**Comment by popper0912** [comment]
> fixed in [c9a9128](https://github.com/Tencent/ncnn/commit/c9a9128db7480745700c1abd17926c64ca832f03)

谢谢您！
