### ISSUE TITLE
如何设置int8运行requantize逻辑

### ISSUE THREAD

**Issue by duzeyan** [Tencent/ncnn#1351]
**现在的操作方法:**
X86下修改convolution类中构造函数设置use_int8_requantize=true
**结果:**
运行时因src/layer/x86/convolution_sgemm_int8.h文件中的
conv_im2col_sgemm_int8_requant_sse函数的scale_requant为空数组而崩溃。

请问如何正确设置使x86成功运行requantize逻辑。

**Comment by BUG1989** [comment]
cmake -DNCNN_REQUANT=ON ..

**Comment by duzeyan** [comment]
thx
