### ISSUE TITLE
After update to f11b772, the android version must link libandroid.so

### ISSUE THREAD

**Issue by Niinor** [Tencent/ncnn#1353]
I found there are some functions of AAsseet_XXXX, and must depend on libandroid.so, but after Android 8.0, there has a limiting of vendor service. The vendor process can not access system libraries.

**Comment by nihui** [comment]
They are part of ndk api
https://developer.android.com/ndk/guides/stable_apis

link with libandroid.so should be fine in any android system, just like libc.so or liblog.so

**Comment by Niinor** [comment]
Hi nihui,
    If you are use it by JNI for APK, it's fine, but if you want to use it in vendor namespace, it's invalid. The vendor can not access this type system libraries.
    I think I can find a way to walk around, but this is a new limiting of the original NCNN.

**Comment by nihui** [comment]
> Hi nihui,
> If you are use it by JNI for APK, it's fine, but if you want to use it in vendor namespace, it's invalid. The vendor can not access this type system libraries.
> I think I can find a way to walk around, but this is a new limiting of the original NCNN.

We can add another cmake option to disable all the platform-specific goodies.
Please create a PR if you are willing to.

**Comment by Niinor** [comment]
> > Hi nihui,
> > If you are use it by JNI for APK, it's fine, but if you want to use it in vendor namespace, it's invalid. The vendor can not access this type system libraries.
> > I think I can find a way to walk around, but this is a new limiting of the original NCNN.
> 
> We can add another cmake option to disable all the platform-specific goodies.
> Please create a PR if you are willing to.

I found maybe it's my device environment problem. **libandroid.so should be in public list**.
