### ISSUE TITLE
pytorch模型有maxpool3d层，并且ceil_mode=False，请问ncnn能支持吗？

### ISSUE THREAD

**Issue by yutian11308023** [Tencent/ncnn#1358]
pytorch模型转onnx转ncnn的时候，有maxpool3d层，并且ceil_mode=False，这样还能够支持吗？

**Comment by nihui** [comment]
ncnn不支持3D的算子

**Comment by yutian11308023** [comment]
请问是否建议自己在ncnn中添加这一层？我准备这么做，不知道会遇到什么问题，您可以提示一下吗？

**Comment by nihui** [comment]
主要问题在于，ncnn Mat 数据结构只有3维，3d算子是需要处理4维数据的
当初没有设计支持3d算子，是考虑到3d算子的速度非常慢，不适合在手机上跑...

**Comment by yutian11308023** [comment]
嗯，还有一个问题想要确认一下。
就是用pytorch转onnx再转ncnn的方式，是不是就对pooling层的ceil_mode没有要求一定为True才行？
因为我用这种方式转换的时候，我的ceil_mode=false，也是能够转换成功并结果是一致的。

**Comment by nihui** [comment]
ncnn 对两种 ceil_mode 都是支持的

**Comment by yutian11308023** [comment]
谢谢，麻烦可以问一下这个支持的部分是在哪里体现的？？因为我在pooling层没有看到用floor()还是ceil()的地方。
只看到默认的向下取整：
 int outw = (w - kernel_w) / stride_w + 1;
int outh = (h - kernel_h) / stride_h + 1;

**Comment by nihui** [comment]
pad_mode full 是 ceil_mode = true
pad_mode valid 是 ceil_mode = false

**Comment by yutian11308023** [comment]
可是，为什么我的模型无论ceil_mode为true或false的时候，转换到ncnn的Pooling层的参数pad_mode也就是5都是1呢？pad_mode==1，不是vaild 吗？

**Comment by yutian11308023** [comment]
首先我的pytorch模型的池化层padding==0，即vaild，所以我在想是不是pad_mode对应的是padding的取值，那么ceil_mode的影响在哪，我还是没有找到。
感谢你耐心解答~~谢谢

**Comment by nihui** [comment]
看了下 onnx2ncnn 的代码，发现并没有处理 ceil_mode，只处理的 auto_pad 的情况，ceil_mode 相当于只能处理 false 的情况...

**Comment by nihui** [comment]
于是把 ceil_mode 转换加上了
https://github.com/Tencent/ncnn/commit/6ce5da28a0ad9eb5716feb23f18425b2de901c43

**Comment by yutian11308023** [comment]
我刚刚用你新加的这个去转换我的ceil_mode=true模型，然后出来的池化层5号参数仍然是1。
我想问一下，是不是你这样改过之后，无论5号参数是0或者1，pad_mode都会是0；
还是你修改的那部分就是修改的5号参数的赋值，如果是这样，我就来看看是不是我这边的问题。

**Comment by yutian11308023** [comment]
hi, 我发现无论我的pytorch模型的ceil_mode是true还是false，转换成onnx后，再去用onnx2ncnn工具转换的时候，我把ceil_mode打印出来发现都是0，所以这个地方可能还是有些问题需要再弄清楚下再改

**Comment by yutian11308023** [comment]
还有一个是，当我pytorch的ceil_mode为true时，onnx输出来的pads会有加几个数和我原本pytorch设置的不一样。但如果为false的话，onnx数出来的pads就全部是0

**Comment by yutian11308023** [comment]
这些pytorch模型中，我的padding都是设为0的

**Comment by yutian11308023** [comment]
而且ceil_mode为true的模型转换过来都不能够load了，，，不知道是怎么回事

**Comment by yutian11308023** [comment]
不好意思，前面说的太乱了，总结一下我的目前的测试结果：
（1）pytorch转onnx的时候，onnx模型似乎本身会对ceil_mode做判断，并且当ceil_mode为true时，onnx会改变pads[]的值；反之，则不改变。
（2）然后输出的onnx模型的ceil_mode值总是为0，在默认pad_mode=1的情况下根据onnx传递过来的修改后的四个pads[]操作就可以得到正确的out的shape（我在纸上根据逻辑演算推理得到的），所以ncnn应该不需要在这里做判断。应该是我误导了你的修改。
（3）现在这些逻辑问题都理清了，但我不知道为什么ceil_mode=True的pytorch模型，能够转成功onnx和ncnn，但没有办法load，您能帮我看看这个问题原因吗？
[pent_id.h.txt](https://github.com/Tencent/ncnn/files/3830324/pent_id.h.txt)
[pent_model.h.txt](https://github.com/Tencent/ncnn/files/3830325/pent_model.h.txt)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by nihui** [comment]
pool3d 最新版本ncnn已经支持了
