### ISSUE TITLE
希望安卓预编译库的补充架构X86

### ISSUE THREAD

**Issue by starlightjy** [Tencent/ncnn#1359]
能否默认编译出x86 x86_64架构的libncnn.a放到release的预编译库中

**Comment by nihui** [comment]
android 版本？

**Comment by starlightjy** [comment]
> android 版本？

对,不仅电脑上模拟器, 现在部分真的平板的安卓系统也是X86的架构了,所以想一起兼容一下

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/releases/tag/20191113 已加

**Comment by starlightjy** [comment]
> https://github.com/Tencent/ncnn/releases/tag/20191113 已加

非常感谢~~~
