### ISSUE TITLE
pytorch如何转int8

### ISSUE THREAD

**Issue by jianbaba** [Tencent/ncnn#1362]
目前pytorch转ncnn已经成功，但是没有在wiki上看到如何转int8，请问目前支持pytorch转int8么？

**Comment by duzeyan** [comment]
You can watch  README.MD under `tools/quantize`

**Comment by jianbaba** [comment]
谢谢，我找到了！但是又遇到两个问题：
1.read.me中：/ncnnoptimize mobilenet-fp32.param mobilenet-fp32.bin mobilenet-nobn-fp32.param mobilenet-nobn-fp32.bin  [flag] 缺少flag标志
2.生成table文件时：./ncnn2table ***产生如下错误：
--- ncnn post training quantization tool --- 10:08:11 Sep  9 2019
param = 'torch_model.param'
bin = 'torch_model.bin'
images = '/nfs/project/lijian_i/onnx-simplifier-master/imgs/'
output = 'torch_model.table'
mean = '127.5,127.5,127.5'
norm = '0.0078125,0.0078125,0.0078125'
size = '120,96'
thread = '2'
====> Quantize the parameters.
====> Quantize the activation.
    ====> step 1 : find the max value.
find_blob_index_by_name data failed
[1]    17891 segmentation fault (core dumped)  /home/luban/ncnn1/ncnn/build/tools/quantize/ncnn2table --param  --bin

请问如何解决呢？

**Comment by jianbaba** [comment]
下载了最近的ncnn版本，现在解决了

**Comment by chuck0518** [comment]
> 下载了最近的ncnn版本，现在解决了

怎么解决的？

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
