### ISSUE TITLE
pytorch转ncnn再转int8后，再跑程序报错！ModelBin read index_array failed 0 layer load_model 7 failed [1]    30452 segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jianbaba** [Tencent/ncnn#1364]
操作步骤如下：
pytorch转ncnn：（https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx）
        
       ./onnx2ncnn   sim.onnx   torch_model.param   torch_model.bin  

pytorch转ncnn转int8:（https://github.com/Tencent/ncnn/tree/master/tools/quantize）

        ./ncnnoptimize  torch_model.param  torch_model.bin  torch_model_nobn.param  torch_model_nobn.bin  1

	./ncnn2table  --param torch_model_nobn.param --bin torch_model_nobn.bin --images /nfs/project/lijian_i/onnx-simplifier-master/imgs/  --output torch_model.table --mean 127.5,127.5,127.5 --norm 0.0078125,0.0078125,0.0078125 --size 120,96 --thread 2

	./ncnn2int8  torch_model_nobn.param  torch_model_nobn.bin   torch_model_nobn_int8.param   torch_model_nobn_int8.bin   torch_model.table

请问您知道是哪里的问题么？

**Comment by jianbaba** [comment]
@nihui @duzeyan您好，请问您知道问题出现的可能原因吗？我调试了好几天都没有找到问题！谢谢了

**Comment by zxb-caffe** [comment]
您好：
    请问您的问题解决了吗？我也遇到同样的问题。

**Comment by jianbaba** [comment]
> 您好：
> 请问您的问题解决了吗？我也遇到同样的问题。
还没，好惨一男的

**Comment by zxb-caffe** [comment]
你是怎么建立的工程？是用源码还是库？我是在VS2015下用源码建立的工程，我的问题解决了，从debug模式变成release模式就可以了。

**Comment by jianbaba** [comment]
> 你是怎么建立的工程？是用源码还是库？我是在VS2015下用源码建立的工程，我的问题解决了，从debug模式变成release模式就可以了。

我就是按照我粘贴的链接傻瓜式的操作，linux下编译的啊

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
