### ISSUE TITLE
need support for mat rotate 

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#1368]
while working in android, images that come from the front camera usually rotated.
it needs to be corrected before passing it into ncnn. 
converting image from bytebuffer-->cv:mat->rotate->ncnn:mat takes lot of time and operational cost.
It will be great if ncnn:mat get rotation option 
#suggestion 

tf has it:
https://www.tensorflow.org/api_docs/python/tf/image/rot90

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/issues/435

In fact, the optimized code for rotating is in my local branch, but I don't think I will push them soon before another new release.

**Comment by soham24** [comment]
@nihui that is great to know
Can I expect next release within a month

**Comment by soham24** [comment]
@nihui 
I see a latest release .. awesome
does this release has rotate functionality ?

**Comment by soham24** [comment]
@nihui I see the latest release .. awesome
does this release has rotate functionality?

**Comment by soham24** [comment]
@nihui Please let us know if there is such timeline, so we can plan our development accordingly
