### ISSUE TITLE
param is too old, please regenerate network graph not ready

### ISSUE THREAD

**Issue by Rcity** [Tencent/ncnn#1369]
您好，我想请问一下，在使用load_param_bin()函数载入网络结构时，提示如题所示的错误；产生此错误的原因，有没有可能是使用了包含label和loss的训练网络结构.param.bin？ @nihui 而.param文件可以正常运行

**Comment by Rcity** [comment]
对了，.param文件可以正常运行

**Comment by nihui** [comment]
试试看重新转换下模型
如果还是不行，可以把 param 和 param.bin 传上来
