### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by guker** [Tencent/ncnn#137]
inline void Mat::release()
{
    if (refcount && NCNN_XADD(refcount, -1) == 1)
        fastFree(data);

    dims = 0;
    data = 0;

    w = 0;
    h = 0;
    c = 0;

    cstep = 0;

    refcount = 0;
}

假设Mat的refcount ！= 1，则不会执行fastFree，而此时data=0，则内存泄漏

**Comment by nihui** [comment]
refcount > 1 有其他 Mat 共享这个 data，所以不能 fastFree ...

**Comment by kobebry80** [comment]
为什么判断是NCNN_XADD(refcount, -1) == 1，而不是NCNN_XADD(refcount, -1) == 0？ 不是引用计数为0的时候释放内存么？

**Comment by nihui** [comment]
NCNN_XADD 返回的是 XADD 之前的值
