### ISSUE TITLE
ncnn2table: Segmentation fault (core dumped)?

### ISSUE THREAD

**Issue by chenyangMl** [Tencent/ncnn#1372]
Using quantitation tool: ./ncnn2table --param mobilenet-nobn-fp32.param --bin mobilenet-nobn-fp32.bin --images images/ --output mobilenet-nobn.table --mean 104,117,123 --norm 0.017,0.017,0.017 --size 224,224 --thread 2
发生段错误

发现这个函数好像漏了一个返回值.
tools/quantize/ncnn2table.cpp     QuantNet::get_input_names

**Comment by nihui** [comment]
欢迎发PR修正

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/fda1c8c5309a9cb0378214ae2827fa7cb407df0a
