### ISSUE TITLE
请问通道转换怎么转，比如ncwh转成nchw？

### ISSUE THREAD

**Issue by kingLCH** [Tencent/ncnn#1374]
请问有类似下面caffe中的通道转换吗
    对输入图像：
        transformer = caffe.io.Transformer({'data': net.blobs['blob'].data.shape})
        # change h*w*c to c*h*w
        transformer.set_transpose('data', (2, 0, 1))
        # change rgb to bgr
        transformer.set_channel_swap('data', (2, 1, 0))

    输出结果：
        #change out (batch,c,h,w)-->(batch,h,w,c)

**Comment by nihui** [comment]
将 nhwc RGB 图像转换为 nchw BGR
ncnn::Mat in = ncnn::Mat::from_pixels_resize(rgb_data, ncnn::Mat::PIXEL_RGB2BGR, w, h);

**Comment by kingLCH** [comment]
> 将 nhwc RGB 图像转换为 nchw BGR

再进一步请问一下，关于图像存储，如果是nhwc的方式，则三个通道的排列顺序是RGBRGBRGB...
如果是nchw的方式，则三个通道的排列顺序是RRRR...GGG...BBB...
关于这个有相关的转换形式吗，类似caffe中的transformer.set_transpose('data', (2, 0, 1))

因为从caffe的网络结构文件来看基本是NCWH的形式，也就是说三个通道的排列顺序是RRRR...GGG...BBB... ，但是用opencv读取的图像都是RGBRGBRGB...

**Comment by kingLCH** [comment]
> 将 nhwc RGB 图像转换为 nchw BGR
> ncnn::Mat in = ncnn::Mat::from_pixels_resize(rgb_data, ncnn::Mat::PIXEL_RGB2BGR, w, h);


明白了，通道转换后会NWHC也会转成NCWH的形式。那么
如果想将NWHC转成NCHW怎么转呢？
  我的做法是
  先将读取进来的图像的mat进行转置，然后再如下面
  ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgrdata, ncnn::Mat::PIXEL_BGR, h, w, w , h);
但是似乎还是有点问题，还望不吝赐教， 非常感谢

**Comment by nihui** [comment]
from_pixels_resize 后面的 w h 不要搞反了呀

**Comment by nihui** [comment]
另外，关于 opencv 和 ncnn 转换可以参考
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-opencv

**Comment by Suncheng2022** [comment]
> 将 nhwc RGB 图像转换为 nchw BGR ncnn::Mat in = ncnn::Mat::from_pixels_resize(rgb_data, ncnn::Mat::PIXEL_RGB2BGR, w, h);

我终于找到这个函数的作用，一直怀疑它也能转换维度！ncnn有api之类的文档吗，C++或python的
