### ISSUE TITLE
undefined reference to `typeinfo for ncnn::Layer' when cross compiling for ARM

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#1376]
I am trying to cross compile for ARM. 
I am using the following command to build the library:
```
cmake -D NCNN_VULKAN=OFF -D CMAKE_BUILD_TYPE=Release -D CMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabihf.toolchain.cmake CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions" ..
```
The library builds ok, but when I try to link against it with an exe compiled using the arm toolchain, I get the following error:
```
mylib.a(main.cpp.o):(.data.rel.ro._ZTI4Noop[_ZTI4Noop]+0x8): undefined reference to `typeinfo for ncnn::Layer'
collect2: error: ld returned 1 exit status
```

[this thread](https://github.com/Tencent/ncnn/issues/1151) mentions adding ` -fno-rtti -fno-exceptions` which I have done in my CMAKE_CXX_FLAGS, but did not seem to help

If I compile ncnn on my raspberry pi 4 device using `cmake -D NCNN_VULKAN=OFF -D CMAKE_BUILD_TYPE=Release ..` then copy the library back to my x86 device and link against that, it works correctly. However, I need to cross compile the ncnn library on my x86 device.

**Comment by nihui** [comment]
you may interest in the NCNN_DISABLE_RTTI cmake option

**Comment by cyrusbehr** [comment]
Having the same issue with:
```
  cmake -D NCNN_VULKAN=OFF -D CMAKE_BUILD_TYPE=Release -D NCNN_DISABLE_RTTI=ON -D CMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabihf.toolchain.cmake CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions" ..
```

Any other ideas?

**Comment by cyrusbehr** [comment]
setting `NCNN_DISABLE_RTTI=OFF` worked, thank you!
