### ISSUE TITLE
考虑mkl-dnn的backend支持？

### ISSUE THREAD

**Issue by tcye** [Tencent/ncnn#1381]
目前ncnn在x86 cpu的表现较差，主要是op没有优化，是否考虑加入mkl-dnn的op作为backend，这样仅仅是一层简单封装，就可以达到x86 cpu上近乎最优的速度。

**Comment by BUG1989** [comment]
如果使用mkl-dnn会引入第三方库的依赖了，ncnn的设计初衷只是针对arm平台。目前已有的x86代码只是做了简单的sse、avx2优化，目的只是为了快速验证部分实验功能(winograd,int8....)

**Comment by BUG1989** [comment]
非常感谢您的建议，如果您对x86平台的优化感兴趣，可以尝试进行优化。另外mkl-dnn不一定是最优的哟~

**Comment by nihui** [comment]
最新版本的 ncnn 已经加入 sse2 和 avx2 的优化啦
