### ISSUE TITLE
How to solve the expansion not supported yet!

### ISSUE THREAD

**Issue by LvNianZu** [Tencent/ncnn#1382]
expansion not supported yet!

**Comment by nihui** [comment]
please provide more info about your model
what is your training framework that produces your model ?
what is the network architecture and CNN task type, such as mobilenet and image classification ?

**Comment by LvNianZu** [comment]
Thank you very much. I've solved the problem.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nihui"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 下午3:50
收件人: "Tencent/ncnn"<ncnn@noreply.github.com&gt;; 
抄送: "img-why"<1797664658@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/ncnn] How to solve the expansion not supported yet! (#1382)




please provide more info about your model
 what is your training framework that produces your model ?
 what is the network architecture and CNN task type, such as mobilenet and image classification ?

**Comment by nihui** [comment]
ok, that's good
