### ISSUE TITLE
CPU占用不稳定，速度不稳定

### ISSUE THREAD

**Issue by SophieChang66** [Tencent/ncnn#1383]
@nihui，同一套测试程序，新版本的ncnn CPU占用率不稳定，导致耗时不稳定，怎样编译能让CPU占用率稳定~

**Comment by nihui** [comment]
尝试绑定大核心
ncnn::set_cpu_powersave(2)
尝试不要用太多线程数

**Comment by SophieChang66** [comment]
设置了这个参数的，我跑的是单线程，我的板子没有大小核，是一样的

**Comment by SophieChang66** [comment]
@nihui,终于稳定了，我的模型都是比较小的，所有我设置的是单线程，最外层的cmakelist.txt里openmp开关也关了，但是toolchain下的-fopenmp没有去掉，导致编译的库里有openmp，应该是ncnn内部调用了多核，导致cpu不稳定，本身模型小，切换耗时反而降低了性能。把-fopenmp关掉后愉快的解决了问题。多谢@bananjia  #1290
