### ISSUE TITLE
Elempack enabled produces incorrect results

### ISSUE THREAD

**Issue by Timen** [Tencent/ncnn#1384]
When running with elempack enabled the 1x1 pack 4 convolution produces incorrect results when applied to a featuremap with size 14x14x64.

Something similar happens for depthwise 3x3 on a 16x16x64 featuremap with no padding. 

Is this inherent to the elempack 4 optimized convolutions or is this a bug?

**Comment by nihui** [comment]
how do you use the pack4 optimized convolution, via enabling the net.opt.use_packing_layout or the low-level op api?
For the later case, you have to convert the element packing yourself since the operator would support blobs with packing layout only.

**Comment by Timen** [comment]
I'm enabling the net.opt.use_packing_layout before I load the network. All the earlier layers produce correct results but once the featuremap size gets below 16x16 it produces incorrect results.

**Comment by nihui** [comment]
hi, thanks for your report
please try to find the layer that starts to produce wrong result
the layer type, parameters and your input blob shape

It is kind of you if you could provide a minimal model that could reproduce this issue

**Comment by nihui** [comment]
please try the latest code
feel free to reopen this issue if you still get the wrong result
