### ISSUE TITLE
Raspberry Pi 4 + SSD

### ISSUE THREAD

**Issue by Qengineering** [Tencent/ncnn#1386]
I'm having problems with the SSD networks like MobileNet.
The MobileNet-SSD models downloaded from the given location (https://drive.google.com/open?id=0ByaKLD9QaPtucWk0Y0dha1VVY0U) in the example work very good on a Raspberry Pi (3 or 4), but only with an old ncnn version found at https://github.com/zlingkang/pedestrian_detection_and_tracking

The lastest ncnn version says the model must be regenerated and gives a segmentation error. However, when doing so with the tools found at the caffe-WeiLui89 fork, the network gives no errors any more, but on output either. Installation on the Raspberry according to the instructions. Networks like squeezenet, yolov3 works right away.

**Comment by nihui** [comment]
hi, you can retrieve the orignal caffemodel from https://github.com/chuanqi305/MobileNet-SSD
then convert it to ncnn model with the latest caffe2ncnn tool. That should resolve your problem

**Comment by nihui** [comment]
I have uploaded ncnn models to github.com/nihui/ncnn-assets/tree/master/models
