### ISSUE TITLE
ncnnoptimize工具arm上出现段错误， PC上可以通过

### ISSUE THREAD

**Issue by SophieChang66** [Tencent/ncnn#1389]
@nihui 
增加
#define __aarch64__ //add by Sophie Chang
#define LINUX
编译ncnnoptimize.cpp，同一个模型，在PC上可以通过，在arm上融合失败，在某一层出现如下错误：
Input  [w h nc]: 1 1 64
Kernel [w h nc]: 3 3 320
Output [w h nc]: 1 1 5
winograd cost 0.079ms 
Segmentation fault

是在support_fp32_conv_type（，，2）返回1时，表示支持pointwise类型的卷积，然后就报错。arm上不知道怎么debug。。。

**Comment by sebastianfelipe** [comment]
Same issue here

**Comment by nihui** [comment]
最新版本已废弃 aarch64 的特化代码
The aarch64 specific optimization code path is now deprecated and removed in the latest ncnn code.
