### ISSUE TITLE
Configuring incomplete, errors occurred

### ISSUE THREAD

**Issue by duan348733684** [Tencent/ncnn#139]
duanchao@dc:~/ncnn/build$ cmake ..
-- CMAKE_INSTALL_PREFIX = /home/duanchao/ncnn/install
-- OpenCV ARCH: 
-- OpenCV RUNTIME: 
-- OpenCV STATIC: OFF
CMake Warning at /home/duanchao/opencv-2.4.13/cmake/OpenCVConfig.cmake:163 (message):
  Found OpenCV Windows Pack but it has not binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  examples/CMakeLists.txt:2 (find_package)

CMake Error at examples/CMakeLists.txt:2 (find_package):
  Found package configuration file:

    /home/duanchao/opencv-2.4.13/cmake/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

-- Configuring incomplete, errors occurred!
See also "/home/duanchao/ncnn/CMakeFiles/CMakeOutput.log".

请问下这是怎么回事　怎么解决　搞了几天了　　泪奔

**Comment by nihui** [comment]
下载 opencv linux 源码编译，或者按照发行版自己的 opencv

**Comment by nihui** [comment]
比如 ubuntu

sudo apt-get install libprotobuf-dev libopencv-dev protobuf-compiler

**Comment by Rainy000** [comment]
@nihui  I meet the same error before I change the "OpenCV_DIR", but when I change it from "/home/yuang/opencv-2.4.13/cmake” into  "/home/yuang/opencv-2.4.13/release", then cmake show an error:

CMake Error at /home/yuang/opencv-2.4.13/release/OpenCVConfig.cmake:71 (include):

  include could not find load file:

    /home/yuang/opencv-2.4.13/release/OpenCVModules_armeabi_v7a.cmake
Call Stack (most recent call first):
  examples/CMakeLists.txt:13 (find_package)


CMake Error at /home/yuang/opencv-2.4.13/release/OpenCVConfig.cmake:71 (include):
  include could not find load file:

    /home/yuang/opencv-2.4.13/release/OpenCVModules_armeabi_v7a.cmake
Call Stack (most recent call first):
  examples/ssd/CMakeLists.txt:1 (find_package)


CMake Error at /home/yuang/opencv-2.4.13/release/OpenCVConfig.cmake:71 (include):
  include could not find load file:

    /home/yuang/opencv-2.4.13/release/OpenCVModules_armeabi_v7a.cmake
Call Stack (most recent call first):
  mtcnn/CMakeLists.txt:2 (find_package)

The version of ncnn I used is :https://github.com/ElegantGod/ncnn
Can you give me some advice?

**Comment by XiaYuanxiang** [comment]
@Rainy000 
do you solved the second problem？include could not find load file:
/home/yuang/opencv-2.4.13/release/OpenCVModules_armeabi_v7a.cmake
I meet the same problem

**Comment by Rainy000** [comment]
@XiaYuanxiang  Yes, maybe just replace the opencv library. Sorry, It's too long I can not remeber..

**Comment by XiaYuanxiang** [comment]
@Rainy000  It's OK，I solved the problem。I had build the ncnn before，so I just re-git clone and rebuild，it workes
