### ISSUE TITLE
关于vulkan版安卓库编译时报错的问题

### ISSUE THREAD

**Issue by kingLCH** [Tencent/ncnn#1390]
用非vulkan版则无报错，用vulkan版一编译就报错，提示找不到相关函数
gpu.cpp:(.text._ZN4ncnn19create_gpu_instanceEv+0x3c): undefined reference to `vkEnumerateInstanceExtensionProperties'
gpu.cpp:(.text._ZN4ncnn19create_gpu_instanceEv+0x84): undefined reference to `vkEnumerateInstanceExtensionProperties'
gpu.cpp:(.text._ZN4ncnn19create_gpu_instanceEv+0x1bc): undefined reference to `vkCreateInstance'
gpu.cpp:(.text._ZN4ncnn19create_gpu_instanceEv+0x1e0): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text._ZN4ncnn19create_gpu_instanceEv+0x1fc): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text._ZN4ncnn19create_gpu_instanceEv+0x218): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text._ZN4ncnn19create_gpu_instanceEv+0x234): undefined reference to `vkGetInstanceProcAddr'
gpu.cpp:(.text._ZN4ncnn19create_gpu_instanceEv+0x250): undefined reference to `vkGetInstanceProcAddr'

**Comment by nihui** [comment]
link libandroid.so

**Comment by kingLCH** [comment]
> link libvulkan.so

请问这个so库在哪里可以下载到或者需要自己编译

**Comment by nihui** [comment]
在 android ndk 里面，android-24
链接方法和 libandroid liblog 这些一样
