### ISSUE TITLE
手机运行benchncnn报错

### ISSUE THREAD

**Issue by qinb** [Tencent/ncnn#1392]
利用华为手机【型号：MT7-TL00，处理器：Hisilicon Kirin 925】进行时间测试；
运行 ./benchncnn 8 2 0时，报错如下：
CANNOT LINK EXECUTABLE: empty/missing DT_HASH in "./benchncnn" (built with --hash-style=gnu?)

请问怎么解决呢？ 多谢

**Comment by nihui** [comment]
你是如何编译的呢？
android-ndk 默认是 hash-style=sysv，不应该会出现这个问题

**Comment by nihui** [comment]
https://stackoverflow.com/questions/26199983/cannot-link-executable-empty-missing-dt-hash-error

> In my case, I transferred the binary to my device via FTP (FileZilla) and had transfer type set to Auto. This corrupted the binary resulting in the error. When I transferred with Binary transfer type, the binary executed fine on my device.

**Comment by qinb** [comment]
> 你是如何编译的呢？
> android-ndk 默认是 hash-style=sysv，不应该会出现这个问题

感谢你的回答，我这边编译是通过ncnn提供的编译方式：https://github.com/Tencent/ncnn/wiki/how-to-build  其中build for android。

**Comment by qinb** [comment]
> https://stackoverflow.com/questions/26199983/cannot-link-executable-empty-missing-dt-hash-error
> 
> > In my case, I transferred the binary to my device via FTP (FileZilla) and had transfer type set to Auto. This corrupted the binary resulting in the error. When I transferred with Binary transfer type, the binary executed fine on my device.

这个链接我看到过，首先，我使用的是scp拷贝的；再者，我把benchncnn二进制文件打包后，再进行的scp，仍旧不行。我这边下载一个filezila看一下吧，一会反馈； 再次感谢

**Comment by qinb** [comment]
> > https://stackoverflow.com/questions/26199983/cannot-link-executable-empty-missing-dt-hash-error
> > > In my case, I transferred the binary to my device via FTP (FileZilla) and had transfer type set to Auto. This corrupted the binary resulting in the error. When I transferred with Binary transfer type, the binary executed fine on my device.
> 
> 这个链接我看到过，首先，我使用的是scp拷贝的；再者，我把benchncnn二进制文件打包后，再进行的scp，仍旧不行。我这边下载一个filezila看一下吧，一会反馈； 再次感谢

反馈：
      我测试了你提到的方法，放到手机上运行还是报相同的错误，麻烦帮忙排查一下？🙏
      我再写一下测试机器的型号：  HUAWEI MT7-TL00，处理器：Hisilicon Kirin 925, Android: 4.4.2

**Comment by nihui** [comment]
android 4.4.2 你可能要用老版本的 android ndk 编译，比如 r16b

**Comment by qinb** [comment]
👍， 问题已经解决了！

![image](https://user-images.githubusercontent.com/13461049/69425158-5fe62e00-0d65-11ea-97ef-c1792d456d08.png)
这个量化int8怎么比量化前速度还慢呢？
