### ISSUE TITLE
Question about the running time of the quantized model

### ISSUE THREAD

**Issue by zxb-caffe** [Tencent/ncnn#1393]
I found that the int8 model and the float32 model run almost the same time. 
Why is this?

**Comment by BUG1989** [comment]
Because the people who do int8 optimization are limited, you can try to optimize

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
20210507版本大幅优化int8推理速度，建议更新
massive int8 inference speedup in the 20210507 release !
