### ISSUE TITLE
测试修改后的网络结构时间

### ISSUE THREAD

**Issue by qinb** [Tencent/ncnn#1395]
自己修改了一个模型结构，想测试一下手机上inference时间，具体过程如下：

**step1:**   pytorch model转成onnx，ncnn转onnx成.param和.bin两个文件；
**step2:**  修改benchmark/benchncnn.cpp文件，并编译通过，如下：
             添加自己的结构：             
![image](https://user-images.githubusercontent.com/13461049/69426435-3b3f8580-0d68-11ea-80ae-2c7d30410b42.png)
**step3:**  benchncnn以及.param拷入手机；
**step4:**  出错，截图如下：
![image](https://user-images.githubusercontent.com/13461049/69426658-ad17cf00-0d68-11ea-882e-482f33709228.png)

我这边对比了一下官网给的shufflenet.param和自己生成的param:
shufflenet.param
![image](https://user-images.githubusercontent.com/13461049/69426722-d89ab980-0d68-11ea-9d88-e6dd3ff06b2c.png)

my.param
![image](https://user-images.githubusercontent.com/13461049/69426741-e5b7a880-0d68-11ea-988f-6b686d0ddcdb.png)

所以问题有两个：
1.  如果测试自己的网络在手机端的速度呢？这种方式可以吗？
2.  my.param 怎么样才能生成像shufflenet.param这样的结构呢？

不胜打扰，还望海涵!

**Comment by nihui** [comment]
你需要手工把param文件里的输入和输出blob改成 data和output

**Comment by nihui** [comment]
另外建议先用ncnnoptimize工具优化下模型

**Comment by luoduo21** [comment]
你pytorch shufflenetv1 shufflenetv2模型转过来inference时间跟提供的比差距大吗?我转过来的shufflenetv2 1.5x速度特别慢,比mobilenetv2,mobilenetv3都慢不少,

**Comment by qinb** [comment]
> 你需要手工把param文件里的输入和输出blob改成 data和output

🙏

Q1: 我需要先修改输入输出blob，再ncnnoptimize优化？
我没有修改直接ncnnoptimze的话报错：
`parse magic failed`
`network graph not ready`

Q2: 手动修改输入输出blob，随便给个名字？

**Comment by qinb** [comment]
> 你pytorch shufflenetv1 shufflenetv2模型转过来inference时间跟提供的比差距大吗?我转过来的shufflenetv2 1.5x速度特别慢,比mobilenetv2,mobilenetv3都慢不少,

没有注意，我的关注点没在那上面 😄

**Comment by qinb** [comment]
已解决，多谢
