### ISSUE TITLE
小白不会安装

### ISSUE THREAD

**Issue by Pratyeka** [Tencent/ncnn#14]
请问，有没有详细一点的安装文档或者教程？

**Comment by BiranLi** [comment]
See #25

**Comment by ruyiweicas** [comment]
http://blog.csdn.net/best_coder/article/details/76201275
这个是写的感觉比较详细的安装教程，可以参照的看看

**Comment by ruyiweicas** [comment]
@Pratyeka http://blog.csdn.net/best_coder/article/details/76201275
这个是写的感觉比较详细的安装教程，可以参照的看看
