### ISSUE TITLE
HSwish conversion from onnx

### ISSUE THREAD

**Issue by ShuangLiu1992** [Tencent/ncnn#1402]
At least with my version of onnx and pytorch, `x * F.relu6(x + 3., inplace=self.inplace) / 6.` gets converted to 
```
  %167 : Float() = onnx::Constant[value={3}]()
  %168 : Float(1, 8, 51, 51) = onnx::Add(%166, %167)
  %169 : Float(1, 8, 51, 51) = onnx::Clip[max=6, min=0](%168), scope: QUANTNET/f_block/Hswish[A] # /home/sliu/projects/mesh_tools/py_face/scripts/venv/lib/python3.6/site-packages/torch/nn/functional.py:958:0
  %170 : Float(1, 8, 51, 51) = onnx::Mul(%166, %169), scope: QUANTNET/f_block/Hswish[A] # /home/sliu/projects/mesh_tools/py_face/scripts/landmark/quant.py:13:0
  %171 : Float() = onnx::Constant[value={6}]()
  %172 : Float(1, 8, 51, 51) = onnx::Div(%170, %171)
```

at line 420 of the conversion tool, 
`if (node2->op_type() != "Clip" || node3->op_type() != "Mul" || node4->op_type() != "Div")`
evaluates to false because node4 is value 6 not Div, is this a bug just for my version of pytorch and onnx or....? (latest stable release pytorch 1.3)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
