### ISSUE TITLE
ncnn2table.cpp(19): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory

### ISSUE THREAD

**Issue by wuxiang20111** [Tencent/ncnn#1403]
您好 ，我这边编译ncnn2table报错，ncnn2table.cpp(19): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory

**Comment by wuxiang20111** [comment]
ncnn2table.cpp(19): fatal error C1083: 无法打开包括文件: “unistd.h”: No such file or directory

**Comment by nihui** [comment]
ncnn2table暂时只能在linux上面编译
