### ISSUE TITLE
mtcnn使用20191113版本速度变慢

### ISSUE THREAD

**Issue by yue-sunyata** [Tencent/ncnn#1404]
代码：https://github.com/moli232777144/mtcnn_ncnn
使用代码自带的ncnn库(更新时间是20180516)，NDK版本使用android-ndk-r16b，对代码自带的科比图像循环检测100次，线程数为2，平均耗时是45ms。
更新ncnn库到20191113版本，NDK版本更新为android-ndk-r19c，对科比图像循环检测100次，线程数为2，平均耗时是106ms。
注：测试手机是vivo NEX A，骁龙710，代码下载下来之后未作变动，只是更新了gradle版本。对比前后只是更新了ncnn库和sdk版本（sdk版本不变的话，20191113版本检测时间还会更长一点），其余未作变动。
这个耗时相差还是比较大的，请问一下可能是什么原因呢？非常感谢！

更新：对历史版本挨个测试之后发现，20190611版本的2线程循环1000次平均耗时仍然为44ms，到了20190908版本就变成了107ms。

**Comment by onexuan** [comment]
我已反馈好多次了，T_T

**Comment by yue-sunyata** [comment]
> 我已反馈好多次了，T_T

请问有大佬说原因么？

**Comment by nihui** [comment]
net.opt.num_threads = 2 ？

**Comment by yue-sunyata** [comment]
> net.opt.num_threads = 2 ？

感谢大佬回复！代码没有变动，界面上可以设置线程数，为了对比都是设置为2。

**Comment by onexuan** [comment]
> > 我已反馈好多次了，T_T
> 
> 请问有大佬说原因么？

知道部分原因，不过得作者去对比版本变化了，从加了量化开始的，开始变慢了

**Comment by yue-sunyata** [comment]
> > > 我已反馈好多次了，T_T
> > 
> > 
> > 请问有大佬说原因么？
> 
> 知道部分原因，不过得作者去对比版本变化了，从加了量化开始的，开始变慢了

感谢答复！

**Comment by onexuan** [comment]
> > > > 我已反馈好多次了，T_T
> > > 
> > > 
> > > 请问有大佬说原因么？
> > 
> > 
> > 知道部分原因，不过得作者去对比版本变化了，从加了量化开始的，开始变慢了
> 
> 感谢答复！
我用旧版本MTCNN只有30ms左右（当然自己做一些优化），而只更换新版本libncnn.a +include 代码没动，新版本要200~400ms，而且跳得厉害

**Comment by yue-sunyata** [comment]
> > > > > 我已反馈好多次了，T_T
> > > > 
> > > > 
> > > > 请问有大佬说原因么？
> > > 
> > > 
> > > 知道部分原因，不过得作者去对比版本变化了，从加了量化开始的，开始变慢了
> > 
> > 
> > 感谢答复！
> 
> 我用旧版本MTCNN只要30ms左右（当然自己做了一些优化），而只更换新版本libncnn.a +include 代码没动，新版本要200~400ms，而且跳得厉害

嗯，差别还是蛮大的，希望有解决方案吧

**Comment by nihui** [comment]
pnet输入200x200
rnet输入24x24
onet输入48x48


20190611
```
OnePlus7T:/data/local/tmp $ ./benchncnn 100 1 0 -1                                                                                                                                                                                          
loop_count = 100
num_threads = 1
powersave = 0
gpu_device = -1
          squeezenet  min =   23.61  max =   27.85  avg =   23.87
          mtcnn_pnet  min =    6.18  max =    6.75  avg =    6.27
          mtcnn_rnet  min =    0.19  max =    0.26  avg =    0.19
          mtcnn_onet  min =    0.97  max =    1.10  avg =    0.99

OnePlus7T:/data/local/tmp $ ./benchncnn 100 2 0 -1                                                                                                                                                                                          
loop_count = 100
num_threads = 2
powersave = 0
gpu_device = -1
          squeezenet  min =   15.47  max =   31.12  avg =   15.97
          mtcnn_pnet  min =    4.14  max =    4.64  avg =    4.24
          mtcnn_rnet  min =    0.14  max =    0.23  avg =    0.14
          mtcnn_onet  min =    0.67  max =    0.80  avg =    0.69
```

20191128(master)
```
OnePlus7T:/data/local/tmp $ ./benchncnn 100 1 0 -1                                                                                                                                                                                      
loop_count = 100
num_threads = 1
powersave = 0
gpu_device = -1
          squeezenet  min =   17.30  max =   17.57  avg =   17.42
          mtcnn_pnet  min =    4.45  max =    4.64  avg =    4.52
          mtcnn_rnet  min =    0.12  max =    0.17  avg =    0.13
          mtcnn_onet  min =    0.64  max =    0.74  avg =    0.66

OnePlus7T:/data/local/tmp $ ./benchncnn 100 2 0 -1                                                                                                                                                                                          
loop_count = 100
num_threads = 2
powersave = 0
gpu_device = -1
          squeezenet  min =   11.60  max =   11.82  avg =   11.68
          mtcnn_pnet  min =    2.93  max =    3.09  avg =    2.98
          mtcnn_rnet  min =    0.10  max =    0.15  avg =    0.11
          mtcnn_onet  min =    0.45  max =    0.56  avg =    0.47

```

**Comment by yue-sunyata** [comment]
@nihui 感谢您的回复。
我这边试了一下benchncnn测试，最新版本确实比20190611版本快，但是rnet仍然慢了近一倍。
但是同样的手机跑这个工程https://github.com/moli232777144/mtcnn_ncnn，最新版本也确实比20190611慢很多。
我曾尝试将其他更新的android工程的编译选项移植过来，并未改善最新版本的耗时。

20190611
-----------------------------------------------------
PD1806:/data/local/tmp $ ./benchncnn 100 2 0 -1                                
loop_count = 100
num_threads = 2
powersave = 0
gpu_device = -1
          squeezenet  min =   35.47  max =   41.89  avg =   36.17
          mtcnn_pnet  min =    7.65  max =   14.04  avg =    7.95
          mtcnn_rnet  min =    0.21  max =    0.40  avg =    0.22
          mtcnn_onet  min =    1.43  max =    1.73  avg =    1.49
-----------------------------------------------------
20191129
-----------------------------------------------------
PD1806:/data/local/tmp $ ./benchncnn 100 2 0 -1                                
loop_count = 100
num_threads = 2
powersave = 0
gpu_device = -1
          squeezenet  min =   31.24  max =   36.96  avg =   31.84
          mtcnn_pnet  min =    6.54  max =    7.22  avg =    6.86
          mtcnn_rnet  min =    0.25  max =    1.21  avg =    0.46
          mtcnn_onet  min =    1.11  max =    4.01  avg =    1.45
-----------------------------------------------------

**Comment by nihui** [comment]
benchncnn 里设置了 net.opt.use_packing_layout = true

**Comment by onexuan** [comment]
请问use_packing_layout的作用是什么？@nihui

**Comment by yue-sunyata** [comment]
我把benchncnn里的全部设置项(包括net.opt.use_packing_layout = true)以及ncnn根目录里的CMakeList.txt里的编译选项都用到了mtcnn_ncnn工程里面，仍然未降低最新版本的耗时。
从打印log看，APK跟benchncnn相比，20190611版本：RNet高出约20%，ONet保持一致。20191129版本：RNet高出约50%，ONet高出约100%。
另一方面，在APK上mtcnn完整执行一次(使用科比图像)，PNet执行9次，RNet执行42次，ONet执行3次。

**Comment by onexuan** [comment]
> 我把benchncnn里的全部设置项(包括net.opt.use_packing_layout = true)以及ncnn根目录里的CMakeList.txt里的编译选项都用到了mtcnn_ncnn工程里面，仍然未降低最新版本的耗时。
> 从打印log看，APK跟benchncnn相比，20190611版本：RNet高出约20%，ONet保持一致。20191129版本：RNet高出约50%，ONet高出约100%。
> 另一方面，在APK上mtcnn完整执行一次(使用科比图像)，PNet执行9次，RNet执行42次，ONet执行3次。
你可以试试 20180830 ef36d79 版本，是个分水岭版本，这个版本开始慢

**Comment by jeremycheong** [comment]
> benchncnn 里设置了 net.opt.use_packing_layout = true

同样发现这个版本的mtcnn速度变慢了，设备是RK3399，我设置了opt.use_packing_layout = true后不仅耗时更多，而且检测不到人脸了。不过这个版本使用benchmark测试的mobilefacenet的速度将近快了一倍。

**Comment by hanjw123** [comment]
请问你们用新版本的ncnn测试mtcnn时，在top里面看cpu的占用率高吗？

**Comment by nihui** [comment]
最新版本应该修复 packing_layout 计算问题了

**Comment by yue-sunyata** [comment]
> 最新版本应该修复 packing_layout 计算问题了

感谢您的答复！

**Comment by liushuan** [comment]
rk3399 最新版本 使用 taskset -c 4,5 ./detect  mtcnn 速度很快30ms  ， 但是在 detect.cpp 程序里面通过程序绑定大核 速度却还是很慢300ms左右。
 cpu_set_t mask;
 CPU_ZERO(&mask);
CPU_SET(4, &mask);
CPU_SET(5, & mask);
sched_setaffinity(0, sizeof(cpu_set_t), &mask);

这是怎么回事？？？？

**Comment by liushuan** [comment]
目前关闭OpenMp 速度会变快，考虑应该是 ncnn在使用openmp的时候没有考虑大小核，所以导致很多时间阻塞在小核心上面。
