### ISSUE TITLE
use_packing_layout设置为true之后，输出结果不一致

### ISSUE THREAD

**Issue by yangfei963158659** [Tencent/ncnn#1406]
hi，我把use_packing_layout设置为true之后，和没有设置为true时的最后一层的输出结果不一致，麻烦你们帮忙排查一下，看看是不是有bug

**Comment by nihui** [comment]
请提供下模型的 param 文件

**Comment by yangfei963158659** [comment]
https://pan.baidu.com/s/1c_S_A5wszU5r7-xS7ykOTg。这是模型的链接，没有密码

**Comment by nihui** [comment]
测试这个param发现，use_packing_layout true/false 结果是一样的

**Comment by yangfei963158659** [comment]
const float mean_vals[3] = {104.f, 117.f, 123.f};
    const float norm_vals[3] = {1.0/255,1.0/255,1.0/255};
  
    // in.substract_mean_normalize(mean_vals, 0);
     in.substract_mean_normalize(0, norm_vals);
 
    ncnn::Extractor ex = squeezenet.create_extractor();
    ex.set_light_mode(1);

    ex.input("img", in);
 
   ncnn::Mat out;
 
   ex.extract("feature2", out);
  
    int stride = out.total()/20;
          for(int j=0;j<out.total();j+=stride){
              printf("%.3f ",out[j]);
          }

**Comment by grainw** [comment]
@nihui 遇到了同样的问题，把use_packing_layout设置为true之后 ，结果不正确了。@yangfei963158659  有解决吗？

**Comment by haibozhang123** [comment]
同样遇到这个问题
