### ISSUE TITLE
ncnn2int8  量化后检测不出来

### ISSUE THREAD

**Issue by wuxiang20111** [Tencent/ncnn#1408]
作者您好，我用ncnn2int8 量化后 调用model 形式是否和之前没量化调用model 一样，前向测试时阈值需要做哪些更改啊

**Comment by BUG1989** [comment]
你是使用的什么网络模型呢？分类任务还是检测任务，校准图片用的多少？

**Comment by wuxiang20111** [comment]
主网络用的是mobilenet0.25  做目标检测任务，校准图片我使用的是12000张(这个也是训练样本)。
没转int8 之前model 能够正常检测到

**Comment by BUG1989** [comment]
1. 你试试标准的mobilenet-ssd模型，看能量化成功，输出正确吗？这个模型是我们测试过的。若行，则说明你对ncnn2int8的使用方法是正确的；
2. 尝试将校准图片较少到5000张左右；
3. 通过修改生成的calibration.table，手动删除第一次和最后一层的数据，实现混合精度量化；
4. 若还是不行……再聊吧。

**Comment by wuxiang20111** [comment]
作者 你好，我ncnn2int8后model 在安卓板子上测和ncnnoptimize 后 model检测时间一样，按道理int8 量化后速度应该变快啊

**Comment by BUG1989** [comment]
@wuxiang20111 因为我当初学艺不精，没优化好.....

**Comment by 8600862** [comment]
我也是结果不对，请问量化后取结果的blob里面data输出是不是从float32变成int32还是byte了呢？
