### ISSUE TITLE
ncnn2table不支持单通道灰度图？

### ISSUE THREAD

**Issue by yyyreal** [Tencent/ncnn#1409]
看了一下源代码，好像ncnn不支持灰度图生成table。
我的模型是单通道的灰度图，请问一下需要修改什么地方呢？

**Comment by SophieChang66** [comment]
1.imread改成读灰度图 cv::imread(img_name, CV_LOAD_IMAGE_GRAYSCALE)
2.mean_val和norm_val变成一维

**Comment by yyyreal** [comment]
按照3channnel的方式居然完成的量化。。。。我还得测一测效果是不是对的。另外又确实按照上述的说法，又改了一版本。

**Comment by BUG1989** [comment]
嗯，没有测试过单通道的灰度，如果您实现了，麻烦更新下，造福大家~

**Comment by hshunghsu** [comment]
目前使用mobilenet-ssd也遇到了一样的问题, 针对单通道的模型最后输出的结果不正确, 我修改了两个地方的代码, 把原先的三通道改成了单通道,

![WeChat 圖片_20191129154805](https://user-images.githubusercontent.com/32537690/69852603-aab0fa00-12bf-11ea-9305-5cb092d2aff3.png)
![WeChat 圖片_20191129154811](https://user-images.githubusercontent.com/32537690/69852604-aab0fa00-12bf-11ea-806f-cb92c631886d.png)

**Comment by chuck0518** [comment]
> 目前使用mobilenet-ssd也遇到了一样的问题, 针对单通道的模型最后输出的结果不正确, 我修改了两个地方的代码, 把原先的三通道改成了单通道,

您好，请问这样修改最后的结果是对的吗？

**Comment by lishang06** [comment]
目前也遇到了一个问题，按照楼上的方法修改读图格式和三维变一维，然后把ncnn的resize接口参数也调整了
![image](https://user-images.githubusercontent.com/59634114/88749305-980bff00-d185-11ea-8707-d5463f47e060.png)
量化模型是出来了，但在反复加载模型和clear的过程中内存会泄漏很快，一会儿就killed了，使用20190611之前的版本都是这样，换了20190908才正常，不知道问题在哪里啊？

**Comment by yicm** [comment]
> 嗯，没有测试过单通道的灰度，如果您实现了，麻烦更新下，造福大家~

我测试过，使用3通道的方式，即mean和norm的值还是使用三个值去用`ncnn2table` ，在程序中用数组大小为1是可以使用量化模型的，且精度只有小数点后两位后的精度损失。

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
20210507版本大幅优化int8推理速度，建议更新

量化工具现已支持灰度图输入
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
