### ISSUE TITLE
Mac 编译android库，squeezeNet在rk3288运行时间1000ms以上？

### ISSUE THREAD

**Issue by lxy890123** [Tencent/ncnn#141]
在Mac上编译的android静态库，armeabi-v7a，程序里设置线程数为4，为什么会这么慢？可能在哪个地方出问题了？
编译设置：-DCMAKE_TOOLCHAIN_FILE=../android.toolchain.cmake _DANDROID_ABI="armeabi-v7a with NEON" -DANDROID_STL_FORCE_FEATURES=OFF

**Comment by lxy890123** [comment]
sorry，测试的平台是rk3229，性能比较低

**Comment by BUG1989** [comment]
In the RK3288 platform,my benchmark of squeezeNet is 318 ms.
