### ISSUE TITLE
使用ncnn2table生成的量化表有大量的 inf 数据

### ISSUE THREAD

**Issue by ldd91** [Tencent/ncnn#1412]
我在使用 ncnn2table 生成量化表的时候，发现量化表里面有好多的 inf 的数据，这种类型的数据会影响后面的模型量化吧，有没相应的解决方法

**Comment by ldd91** [comment]
没有进行 optimizer 直接生成量化表的话不会有这个问题

**Comment by BUG1989** [comment]
@ldd91 

- 请问是 conv_op_param 的数据inf，还是conv_op 的数据inf;
- 如果进行 optimizer 后，使用fp32做推理的数据正常吗。

**Comment by ldd91** [comment]
你好，感谢回复：
1.是 conv_op_param
2.正常
还有一个问题我发现，不使用 optimizer 生成的量化表里面的 conv_op_param 会有 e+25类型的这种值，有些值非常大，使用该表量化完的模型基本不可用

**Comment by ldd91** [comment]
还有一个现象就是我实验混合精度，前80层卷积全部不做量化，只做了后十几层的量化，出来的效果也是跟全部量化一样，

**Comment by BUG1989** [comment]
@ldd91 
conv_op_param的值异常，说明在统计weight权重中，出现某一通道weight值全为零或绝对值非常非常小，而 conv_op_param(scale_weight) = 127.0 / weight_outch_max，所以异常了。建议在以下地方进行修改
file  : ncnn2table.cpp
line : 173, 194, 215
例如将这段代码
```
for (int i = 0; i < weight_data_size_output; i++)
    max_value = std::max(max_value, std::fabs(data_n[i]));

if (quant_6bit)
    scales.push_back(31 / max_value);
else
    scales.push_back(127 / max_value);
```
修改为
```
for (int i = 0; i < weight_data_size_output; i++)
    max_value = std::max(max_value, std::fabs(data_n[i]));

if (max_value < 0.000001)
{
    scales.push_back(0);
}
else
{
    if (quant_6bit)
        scales.push_back(31 / max_value);
    else
        scales.push_back(127 / max_value);
}
```
若您方便，请分享修改后的效果，谢谢~

**Comment by ldd91** [comment]
好的 我这就试下

**Comment by ldd91** [comment]
你好经过测试，生成的量化表看起来比较正常了，以前的 inf 现在变成0 了，但是出来的结果还是跟之前的一样精度差很多，我这个是识别的模型，我直接对经过 float32 与 int8 模型的图像提取特征对比，发现有些特质值会差 0.05-0.06 以上，只有个别的特征值对的上

**Comment by BUG1989** [comment]
假设你的网络模型最后输出维度是256维的数据。

- “特征值相差0.05-0.06以上”是这256个数据中的某一个数据，还是对这两组matrix求的矩阵距离（例如余弦相识度）？
- 请问你的网络模型中有convolution3x3s1这样的layer吗？

- int8模型跑完测试集掉点多少呢？

**Comment by ldd91** [comment]
感谢回复：
1.模型的输出刚好就是256，差值指的是 256 个数据的某一个数据
2.没有
3.你好点是上升了，就是2个完全不一样的人提取的特质打分也会有将近0.5（总分1）

**Comment by ldd91** [comment]
结合之前我测试混合精度，感觉问题应该还是出在生成量化表这一步，量化表不正确导致我实验只剩下量化模型其中的几个卷积，出来效果也是很差

**Comment by BUG1989** [comment]
- 同一个图，量化前后相似度是多少呢？
- far == 0.0000001时候的tar，用整个数据集跑测？

**Comment by ldd91** [comment]
1.同一个图量化前后相似度打分都是1
2.用的是整个验证集 800多张图片

**Comment by ldd91** [comment]
hi @BUG1989  刚刚我测了下对于同一个人的2张不同的图片提取出来的特征向量做内积，未量化的模型的结果是：0.833116   量化完的模型的内积是：0.872984

**Comment by ldd91** [comment]
hi @BUG1989  我今天又测试了下，只做第一层卷积量化然后提取图片的特征向量与未做量化的进行对比，结果现象还是跟之前的一样，有些位对的上，有些差距还是比较大。感觉从第一层卷积量化就出问题了
