### ISSUE TITLE
int8 量化速度问题

### ISSUE THREAD

**Issue by wuxiang20111** [Tencent/ncnn#1413]
作者 你好，我int8 量化后在板子上跑速度比没量化的要慢，请问有可能是哪种原因阿

**Comment by hsnuonly** [comment]
請問你的運行環境是?

**Comment by BUG1989** [comment]
@wuxiang20111 因为没有优化好

**Comment by tpoisonooo** [comment]
@wuxiang20111   

速度主导的话。

1. int8 测试需要打开 REQUANT 编译选项；
2. fp32 需要在源码里打开 layout 选项（改 1 行就行）；
3. 目前在 armv7/arm64 上优化较多，不适用 x86/mips 芯片。

**Comment by JCYAO-gz** [comment]
我这边也是，mtcnn模型量化之后，耗时更长了。发现Pnet产生的预测框由19变成了69个。

**Comment by IvyGongoogle** [comment]
@BUG1989 @tpoisonooo @JCYAO-gz  I meet the same problem. For my case, Using int8 is four times slower than using fp32.  Do you solve this? 

Thanks.

**Comment by ywangwxd** [comment]
> @wuxiang20111
> 
> 速度主导的话。
> 
> 1. int8 测试需要打开 REQUANT 编译选项；
> 2. fp32 需要在源码里打开 layout 选项（改 1 行就行）；
> 3. 目前在 armv7/arm64 上优化较多，不适用 x86/mips 芯片。

那个打开layout选项说的是 opt.use_packing_layout = true; 吗？我也在尝试int8量化前后的效果对比。用benchnn程序，发现在单线程的情况下，int8量化稍微加速一点，多线程还变慢了。

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新

**Comment by hykn2193** [comment]
hello, 我的scrfd_2.5g模型在20210507版本上使用int8推理速度和fp16推理速度基本差不多，请问是什么原因，处理器是3399

**Comment by BraveLii** [comment]
> 

我也遇到了同样的问题
