### ISSUE TITLE
Crash when load_param called.

### ISSUE THREAD

**Issue by GHLab** [Tencent/ncnn#1414]
Hi, I have some problem.
I converted tensorflow pb file to ncnn by tensorflow2ncnn then called load_param function but the crash occurred with "layer TFReshape not exists or registered".
How can I resolve this problem?

Attaching first four lines.

7767517
67 67
Input            input                            0 1 input 0=0 1=0 2=0
TFReshape        Reshape                          1 1 input Reshape 0=224 1=224 2=1 3=0

**Comment by GHLab** [comment]
I resolved it by changing 'TFReshape' to 'Reshape' but I don't know it's correct a way.

**Comment by nihui** [comment]
I suppose that you are using the community-maintained tensorflow2ncnn tool
you shall probably follow the instructions of how to add tensorflow specific layers in ncnn

https://github.com/hanzy88/tensorflow2ncnn#second-convert-from-tensorflow-to-ncnn
