### ISSUE TITLE
why significant is shifted one more position in half2float?

### ISSUE THREAD

**Issue by hpsoar** [Tencent/ncnn#142]
https://github.com/Tencent/ncnn/blob/0edd2b78c544205b8121d579776483126487fde9/src/mat.cpp#L235

I can't understand this, can any one help?

is there any reference for this case, when exponent == 0 & significant != 0?

**Comment by nannanmath** [comment]
I also feel this is incorrect.

**Comment by nihui** [comment]
For normalized fp32 value, the significand precision is 24 bits but only 23 explicitly stored, the leading bit is implicitly stored.
For denormal value, all bits are stored.
Thus the significant is shifted one more position during denormal fp16 to normalized fp32.

https://en.wikipedia.org/wiki/Single-precision_floating-point_format
