### ISSUE TITLE
int8 requant 修改建议

### ISSUE THREAD

**Issue by tpoisonooo** [Tencent/ncnn#1420]
【目前情况】
目前 int32 计算结束后转回 int8，现在的做法是：
out = float2int8(in * scales + bias)
其中，
in:  int32_t
scales:  float32
bias:  float32
out: int8

【现有问题】
一堆 int32=> fp32， fp32=>int8 的指令在里面。

【预期改法】
假设没有 bias，把 scales 看作 M。
在有限的计算机可表达的数值范围内，M == y/(2>>x)， 其中 x > 0，  0.5 <= y < 1。
再用一个 int32_t 类型的 M0 代替 y，整个计算只有 smla 和 shift。

例如：
scales = 0.13332 =  0.53328 /  (1<<2)
用 34949 代替 0.53328（就是 (1<<16) * 0.53328），

34949 * in / (1<<16) / (1<<2) 和最终结果接近。

【优点】
少了 `fmul`，没了 `scvtf`。世界清净了。REQUANT 操作基本没开销。

【参照】
参考 https://arxiv.org/abs/1712.05877 2.2 节，里面有个关于 M 的叙述。

【行动】
先把这个 PR 合了，下个 PR...

**Comment by BUG1989** [comment]
SQRDMULH

**Comment by tpoisonooo** [comment]
这个quant是纯推理做，还是模型量化脚本做。我总感觉脚本做更合适。

**Comment by nihui** [comment]
api和模型要保持向后兼容

**Comment by BUG1989** [comment]
create_pipeline()中修改呀

**Comment by tpoisonooo** [comment]
⭕

**Comment by tpoisonooo** [comment]
> api和模型要保持向后兼容

好想要这个 "member" 的标记，感觉酷酷的。

**Comment by xieydd** [comment]
目前这个 requant 有什么进展吗？ @tpoisonooo  @BUG1989

**Comment by tpoisonooo** [comment]
有个大佬正在 pr，卡在代码 format 上  =_=

**Comment by xieydd** [comment]
@tpoisonooo I have implement the shift scale in x86, but now i meet a problem, use fixed position in every layer will cause a big error in last few layers in mobilenetv2 model. Is there a method, i come up a way finetune position in every layer, how to keep Scale in special op like (split concat)  is consistent is a problem i meet.

**Comment by tpoisonooo** [comment]
https://github.com/tpoisonooo/ncnn/tree/int8-pack8 在写。
