### ISSUE TITLE
有什么方法可以将ncnn的模型转成像是caffe或者是tensorflow的模型？

### ISSUE THREAD

**Issue by HollrayChan** [Tencent/ncnn#1421]
好像没有什么开源的工具来进行来进行反向的模型转换，都是各种框架的模型向ncnn转的，希望得到些意见····

**Comment by tpoisonooo** [comment]
写一个，并不难。

**Comment by tpoisonooo** [comment]
目前的确没听说有反向转换工具，这个工具的应用场景大约只有破解未加密的 ncnn.param/ncnn.bin。需求比较小众。

实现起来并不复杂，不如写一个然后 PR 出来。

**Comment by nihui** [comment]
模型转换可以尝试下 onnx
ncnn 模型可以用netron打开看
具体结构可以参考 https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure

**Comment by HollrayChan** [comment]
好的，谢谢，我尝试去做下，有结果的话就share出来



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nihui"<notifications@github.com&gt;; 
发送时间: 2019年12月13日(星期五) 上午10:45
收件人: "Tencent/ncnn"<ncnn@noreply.github.com&gt;; 
抄送: "Hollray Chan"<1723314028@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/ncnn] 有什么方法可以将ncnn的模型转成像是caffe或者是tensorflow的模型？ (#1421)




模型转换可以尝试下 onnx
 ncnn 模型可以用netron打开看
 具体结构可以参考 https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure
