### ISSUE TITLE
cmake .. 后提示Protobuf compiler version doesn't match library version 2.5.0 Call Stack (most recent call first):   tools/onnx/CMakeLists.txt:2 (find_package)

### ISSUE THREAD

**Issue by Note-Liu** [Tencent/ncnn#1423]

**Comment by hellocsi** [comment]
截图看一下控制台信息

**Comment by Note-Liu** [comment]
> 截图看一下控制台信息

@server:~/ncnn/ncnn/build$ make -j
[ 97%] Built target generate-spirv
[ 97%] Running C++ protocol buffer compiler on onnx.proto
onnx.proto:451:5: Expected "required", "optional", or "repeated".
onnx.proto:451:17: Missing field number.
onnx.proto:479:3: Expected "required", "optional", or "repeated".
onnx.proto:479:15: Missing field number.
make[2]: *** [tools/onnx/onnx.pb.cc] 错误 1
make[1]: *** [tools/onnx/CMakeFiles/onnx2ncnn.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 97%] Built target mxnet2ncnn
[ 97%] Built target caffe2ncnn
[ 97%] Built target ncnn
make: *** [all] 错误 2

**Comment by nihui** [comment]
升级下 protobuf >= 2.6.1

**Comment by Note-Liu** [comment]
> 升级下 protobuf >= 2.6.1
> 或者 cmake -DNCNN_BUILD_TOOLS=OFF .. 跳过模型转换工具编译

@server:~/ncnn/ncnn/build$ ls
benchmark  CMakeCache.txt  CMakeFiles  cmake_install.cmake  install  install_manifest.txt  Makefile  src  tools
@server:~/ncnn/ncnn/build$ cd tools
@server:~/ncnn/ncnn/build/tools$ ls
caffe  CMakeFiles  cmake_install.cmake  Makefile  mxnet  ncnn2mem  ncnnoptimize  onnx
编译没有报错，但是ncnn/build/tools 目录下，只生成了 ncnn2mem这个可执行文件，没有caffe2ncnn ，那怎么把caffe转成ncnn?

**Comment by nihui** [comment]
如果要编译模型转换工具，你需要先升级 protobuf 到 2.6.1 以上

**Comment by quocnhat** [comment]
Newest protobuf version on CentOS 7 is 2.5 .0-10. what should I do? assume that I can not upgrade to centOS 8. thank you.

**Comment by nihui** [comment]
> Newest protobuf version on CentOS 7 is 2.5 .0-10. what should I do? assume that I can not upgrade to centOS 8. thank you.

You can skip the tools building via cmake -DNCNN_BUILD_TOOLS=OFF ..

**Comment by quocnhat** [comment]
> > Newest protobuf version on CentOS 7 is 2.5 .0-10. what should I do? assume that I can not upgrade to centOS 8. thank you.
> 
> You can skip building tools via cmake -DNCNN_BUILD_TOOLS=OFF ..

skip building tools mean We can not use tools for porting model ( onnx,...) or something like that. is it correct?

**Comment by nihui** [comment]
You can build these tools on other systems with newer protobuf, or upgrade protobuf manually
The model files produced by conversion tools are interchangeable among different platforms and systems

**Comment by quocnhat** [comment]
great news I got today. Thank you very much for your kindly helps.
