### ISSUE TITLE
onnx转ncnn问题

### ISSUE THREAD

**Issue by sunnymoon155** [Tencent/ncnn#1433]
@nihui 请问大佬，我使用的https://github.com/megvii-model/ShuffleNet-Series 这个pytorch的shufflenetv2，转换onnx后无法转ncnn，simplifier也用过了还是不行。。
Gather not supported yet!
  # axis=0

**Comment by nihui** [comment]
推荐使用 pytorch 官方模型
https://pytorch.org/hub/pytorch_vision_shufflenet_v2/

**Comment by GYxiaOH** [comment]
我同样遇到这个问题了，你知道问题出在哪里了吗

**Comment by nihui** [comment]
最新的 onnx2ncnn 支持了 megvii shufflenet 的 channel shuffle 和 split channel

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
