### ISSUE TITLE
int result = ex.extract("output", out);

### ISSUE THREAD

**Issue by LvNianZu** [Tencent/ncnn#1436]
请问int result = ex.extract("output", out);  返回值为-100，out输出为空，一般是上面原因呢？我在onnxruntime上测试了我的onnx模型，结果没有问题，在转换为bin和param文件的过程中，也没有报错

**Comment by ddcat1991** [comment]
遇到了同样的问题, 平台x86-linux上。
请问你现在解决了吗？

我用的一个ssd网络, 输出两个结果(scores, boxes)，也是用的onnx->onnx simplifier ->转换 bin和param。 然后onnx在onnxtuntime上是正常的。转换为bin和param后，只能拿到scores的结果,  另一个 int r = ex.extract("boxes", m_boxes); 返回-100.

**Comment by northeastsquare** [comment]
我也遇到类似问题。把example里面的rentinanet在ubuntu上一切正常，跑到手机上，就是crop层输出-100，crop0前面层没问题， 不知道怎么回事

**Comment by northeastsquare** [comment]
弄好了，原来是ncnn arm_crop.cpp里面有bug, nihui大佬已经修复
https://github.com/Tencent/ncnn/issues/1546

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
