### ISSUE TITLE
ncnn::Mat 类型  支持频繁读写操作吗，遍历切片时出现（核心已转储问题）？

### ISSUE THREAD

**Issue by JuZiSYJ** [Tencent/ncnn#1437]
1.Ubuntu 下 对图片 划分为 3 * 3个区域，每个区域切片 32 * 32图片，没有问题。

2.ubuntu下，对图片继续逐元素操作，类似 tmp = ptr[x] *2 +1；遍历 1w-30w次不等，会出现（核心已转储问题）

3.Android 下  对图片 划分为 3 * 3个区域，每个区域切片 32*32图片，出现  A / libc ：Fatal signal 11 （SIGSEGV） ,code 1 （SEGV_MAPEPR）， fault addr 0xcef8bf79 in tid 1660( thread-4),pid 2540

**Comment by nihui** [comment]
shall be fixed since https://github.com/Tencent/ncnn/commit/0f7e7bca0223bfa3600c08c808d2ded0a1cb3b04

如果问题依旧，可以开新issue或者reopen
