### ISSUE TITLE
a problem in layer/reduction

### ISSUE THREAD

**Issue by Wilbur529** [Tencent/ncnn#1440]
https://github.com/Tencent/ncnn/blob/9c3011ece09b724f372bb41661031eba5e556c8d/src/layer/reduction.cpp#L334

I think there is a mistake since it will create a mat with shape[w * c * h]?

**Comment by nihui** [comment]
b will be [w * c]

**Comment by Wilbur529** [comment]
Because the keepdim is set to 0? So the mat'b' is regarded as a [w * c ] mat,  even though the attribute of b is: b.h == channels?

**Comment by nihui** [comment]
yeah, ncnn always squeeze the rank to w*h for 2-dimension, and w for 1-dimension. This is the shape notation convention.
