### ISSUE TITLE
How to set flag for ncnnoptimize

### ISSUE THREAD

**Issue by WIll-Xu35** [Tencent/ncnn#1441]
Hi,

After  reading the document of how to use ncnnoptimize, I'm still confused about the last 'flag' parameter.

The example in readme set flag to 65536 for a mobilenet. I optimized my own classification mobilenet (only 2 classes) with flag set to 1, the optimized output is exactly the same before optimize, which is good. But when optimizing a model with some res-blocks, which generates 512 outputs, the inference fails and says "find_blob_index_by_name xxx failed". I'm wondering if I set the wrong value for the 'flag' parameter.

So what exactly does this flag mean?

Many thanks.

**Comment by nihui** [comment]
currently the flag is the storage type
If it is 65535, that means use fp16 storage type for model weight, or fp32 otherwise

you can open the param file in netron visualizer and find what the blob name is for your model

**Comment by WIll-Xu35** [comment]
@nihui Thanks you so much!

Just one more question. As for the ARM linux platform part of [https://github.com/Tencent/ncnn/blob/25979c1bdb73d58d0a463abb7742a46c44e30f47/docs/how-to-use-and-FAQ/use-ncnnoptimize-to-optimize-model.md](https://github.com/Tencent/ncnn/blob/25979c1bdb73d58d0a463abb7742a46c44e30f47/docs/how-to-use-and-FAQ/use-ncnnoptimize-to-optimize-model.md)

Does this mean if I build ncnn for arm, I'll use this to optimize my model? And what does the input weight 227 mean in the table? Is it just a typo, which should be input width 224 or this it mean something else?

**Comment by nihui** [comment]
The ARM linux platform part is optional. You can optimize the model on PC.
In fact, the optional part is considered deprecated.
For faster inference on ARM, it is more convenient to enable packing layout option.
