### ISSUE TITLE
pytorch怎么转成onnx?

### ISSUE THREAD

**Issue by Note-Liu** [Tencent/ncnn#1443]

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx

**Comment by Note-Liu** [comment]
> https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx
我刚接触，不是特别明白。想问问caffe转ncnn还需要预的模型caffemodel，pytorch转成onnx怎么没看到在哪用到预训练的模型?
谢谢。

**Comment by Note-Liu** [comment]
# An example input you would normally provide to your model's forward() method
x = torch.rand(1, 3, 224, 224)
# Export the model
torch_out = torch.onnx._export(model, x, "resnet18.onnx", export_params=True)
此处的“model"就是预训练的pytorch模型吧

**Comment by Note-Liu** [comment]
> https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx

thanks

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
