### ISSUE TITLE
生成ncnn的.param和.bin文件之后，怎么看模型参数量和速度？

### ISSUE THREAD

**Issue by Note-Liu** [Tencent/ncnn#1444]

**Comment by tpoisonooo** [comment]
等这个 [PR](https://github.com/Tencent/ncnn/pull/1445) 合并后，用 ncnnoptimize 就行了。顺带还能测 Bug 换积分（大雾）。

目前训出模型应该就直接知道参数量，这些都是可以手工算出来的（也可以用一些魔改的 caffe editory 工具直接计算参数量和 MACC）。速度的话仿照 example 目录下面写个单测程序。

**Comment by Note-Liu** [comment]
> 等这个 PR 合并后，用 ncnnoptimize 就行了。顺带还能测 Bug 换积分（大雾）。
> 目前训出模型应该就直接知道参数量，这些都是可以手工算出来的（也可以用一些魔改的 caffe editor 工具直接计算参数量和 MACC）。速度的话仿照 example 目录下面写个单测程序。

thanks

**Comment by zengxiangfu1985** [comment]
从原来的模型配置文件应该可以算出参数量,另外通过MATLAB打开.bin文件能直接查看其中的各个参数,命令为:xxx = memmapfile('xxx.bin', 'Format', 'single').Data

**Comment by nihui** [comment]
设置 Input 层的 shape 信息，ncnnoptimize 结束时会进行推理测试，并输出乘法次数和内存足迹
另外，也可以参考 benchncnn 进行实际的速度测试。
