### ISSUE TITLE
關於squeezenet int8模型與fp32模型在PC上的推理結果不一致

### ISSUE THREAD

**Issue by wenych** [Tencent/ncnn#1446]
大神您好，首先感謝您的分享。我用example裏面的squeezenet_v1.1.param和squeezenet_v1.1.bin測試squeezenet的TOP3分類結果正確；可是測試int8的模型top3結果錯誤，以下是我的操作步驟，請您看看是否有錯誤的地方：
1. ncnn2table生成了校準文件，校準數據集規模我準備了1000張圖片
2. ncnn2int8生成int8模型， squeezenet-int8_1.param和squeezenet-int8_1.bin
3. 修改squeezenet.cpp中模型加載的代碼，加載int8模型
4. make
5. ./squeezenet test.jpeg 推理測試

以上是我的操作步驟，結果FP32和INT8的推理結果不一致，請問我做錯哪一步了嗎？謝謝！
debug了下源代碼， int Convolution_x86::forward（）裏面有use_int8_inference這個參數無論加載fp32模型還是int8模型，值始終爲false,請問這個有影響嗎？謝謝

**Comment by tpoisonooo** [comment]
pull 新版试一下，前几天在这个 [PR](https://github.com/Tencent/ncnn/pull/1480) 修了，基本是我的锅...
 
如果还不行跟我说一下...继续修。

**Comment by nihui** [comment]
最新代码已修复
