### ISSUE TITLE
expand层维度拓展问题

### ISSUE THREAD

**Issue by Tiaaaaaaa** [Tencent/ncnn#1447]
expand层可以按指定的张量大小拓展维度吗？如(n,n,w), n为指定长度？目前代码里似乎只支持拓展为（1, 1, w）的

**Comment by nihui** [comment]
expand不能扩充数据

**Comment by Tiaaaaaaa** [comment]
那如何处理SE模块？



------------------ 原始邮件 ------------------
发件人: nihui <notifications@github.com&gt;
发送时间: 2019年12月19日 19:21
收件人: Tencent/ncnn <ncnn@noreply.github.com&gt;
抄送: Tiaaaaaaa <824732093@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/ncnn] expand层维度拓展问题 (#1447)




Closed #1447.

**Comment by nihui** [comment]
SE 模块不需要expand，直接 mul 就可以，自动 broadcast

**Comment by Tiaaaaaaa** [comment]
mul操作调用的是eltwise层吗？出来的结果不对





------------------ 原始邮件 ------------------
发件人: nihui <notifications@github.com&gt;
发送时间: 2019年12月19日 19:34
收件人: Tencent/ncnn <ncnn@noreply.github.com&gt;
抄送: Tiaaaaaaa <824732093@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/ncnn] expand层维度拓展问题 (#1447)

**Comment by nihui** [comment]
BinaryOp
具体可以参考 benchncnn mobilenet_v3.param

**Comment by Tiaaaaaaa** [comment]
VkMat结构数据，直接通过mapped_ptr()取值会崩溃。此外，想把VkMat转化为Mat，是否可通过VkMat的成员download函数来实现？实际验证，通过该方法转化也是崩溃。问题：如想把VkMat转化为Mat该如何操作才能正确的拷贝数据，且不会崩溃？



------------------ 原始邮件 ------------------
发件人: nihui <notifications@github.com&gt;
发送时间: 2019年12月19日 21:07
收件人: Tencent/ncnn <ncnn@noreply.github.com&gt;
抄送: Tiaaaaaaa <824732093@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/ncnn] expand层维度拓展问题 (#1447)




BinaryOp
 具体可以参考 benchncnn mobilenet_v3.param

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/vulkan-notes#zero-copy-on-unified-memory-device
https://github.com/Tencent/ncnn/wiki/low-level-operation-api#cpu---gpu---forward---gpu---cpu

**Comment by Tiaaaaaaa** [comment]
好的非常感谢！





------------------ 原始邮件 ------------------
发件人: nihui <notifications@github.com&gt;
发送时间: 2019年12月20日 12:41
收件人: Tencent/ncnn <ncnn@noreply.github.com&gt;
抄送: Tiaaaaaaa <824732093@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/ncnn] expand层维度拓展问题 (#1447)




https://github.com/Tencent/ncnn/wiki/vulkan-notes#zero-copy-on-unified-memory-device
 https://github.com/Tencent/ncnn/wiki/low-level-operation-api#cpu---gpu---forward---gpu---cpu

**Comment by John1231983** [comment]
@Tiaaaaaaa have you fixed it? I am using mobilenetv3 and convert to ncnn also has the issue.

@nihui : could you suggest solution to convert mobilenetv3 mxnet to ncnn in english? Thanks
