### ISSUE TITLE
使用use_packing_layout = true x86上结果是正确的，在arm 上结果不正确

### ISSUE THREAD

**Issue by grainw** [Tencent/ncnn#1452]
在X86 上速度没有提升反而下降了，在rk399 arm上从第一层卷积结果就不对了，全部是0

**Comment by grainw** [comment]
数据输入是1*3*360*640 第一层卷积kernel 为 3，步长为2 numout为 13 ，第一层卷积后shape为1*13*180*320 ，但是值全部为0

**Comment by grainw** [comment]
ncnn::Net model;
model.opt.use_packing_layout = true;
    model.load_param(param_path.c_str());
    model.load_model(enet_path.c_str());

ncnn::Mat inputMat;
    inputMat = ncnn::Mat::from_pixels_resize(img.data, ncnn::Mat::PIXEL_BGR, img.cols, img.rows, resizeWidth, resizeHeight);
    
    ncnn::Extractor extractor = model.create_extractor();
    extractor.set_num_threads(2);
    extractor.input("data", inputMat);

    ncnn::Mat outputMat;
    extractor.extract("conv0_1", outputMat);
    pretty_print(outputMat);

    std::cout << outputMat.w << outputMat.h << outputMat.c << std::endl;

**Comment by grainw** [comment]
pretty_print(const ncnn::Mat& m)
{
    for (int q=0; q<1; q++)
    {
        const float* ptr = m.channel(q);
        for (int y=0; y<1; y++)
        {
            for (int x=0; x<100; x++)
            {
                printf("%f ", ptr[x]);
            }
            ptr += m.w;
            printf("\n");
        }
        printf("------------------------\n");
    }
}

**Comment by grainw** [comment]
打印的第一channel 第一行的前100个数，设定model.opt.use_packing_layout = true; 与不设定，不设定的结果正确，设定的结果全是0

**Comment by nihui** [comment]
我这里测试没有发现计算错误
请贴下 param 文件中的前几行

**Comment by grainw** [comment]
7767517
238 268
Input            data             0 1 data 0=640 1=360 2=3
Split            splitncnn_0      1 2 data data_splitncnn_0 data_splitncnn_1
Convolution      conv0_1          1 1 data_splitncnn_1 conv0_1 0=26 1=3 2=1 3=2 4=1 5=1 6=702
Pooling          pool0_1          1 1 data_splitncnn_0 pool0_1 0=0 1=2 2=2 3=0 4=0
Concat           concat0_1        2 1 conv0_1 pool0_1 concat0_1 0=0
Scale            bn0_1            1 1 concat0_1 bn0_1 0=29 1=1
PReLU            prelu0_1         1 1 bn0_1 prelu0_1 0=29
Split            splitncnn_1      1 2 prelu0_1 prelu0_1_splitncnn_0 prelu0_1_splitncnn_1

**Comment by grainw** [comment]
@nihui  在conv0_1 结果就不对了

**Comment by jiyinghui39** [comment]
该问题有没有解决啊，我这里有一个检测模型打开model.opt.use_packing_layout = true后，在arm上检测就不正确了。另外几个模型检测是正确的。

**Comment by nihui** [comment]
shall be fixed since https://github.com/Tencent/ncnn/commit/0f7e7bca0223bfa3600c08c808d2ded0a1cb3b04

**Comment by nihui** [comment]
如果测试发现还有问题，可以开新issue或者reopen

**Comment by wqvbjhc** [comment]
@nihui 20200616版本这问题还存在。

**Comment by nihui** [comment]
> 
> 
> @nihui 20200616版本这问题还存在。

https://github.com/Tencent/ncnn/releases/tag/20200727
试试看新版本，如果还有问题，需要你提供下模型的param

**Comment by wqvbjhc** [comment]
> > @nihui 20200616版本这问题还存在。
> 
> https://github.com/Tencent/ncnn/releases/tag/20200727
> 试试看新版本，如果还有问题，需要你提供下模型的param

20200727版本解决了这个问题。
