### ISSUE TITLE
set VULKAN=ON,  build ncnn failed(on ubuntu 14.04 LTS) !

### ISSUE THREAD

**Issue by dangxusheng** [Tencent/ncnn#1455]
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/vulkan/absval_vulkan.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] 错误2
make: *** [all] 错误 2

**Comment by nihui** [comment]
please post more messages with
```
make VERBOSE=1
```

**Comment by dangxusheng** [comment]
error messages as follows:
---------------------------------------------------------------------------------------------------
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/permute_vulkan.cpp:166:31: error: request for member ‘cstep’ in ‘top_blob’, which is of non-class type ‘int’
     constants[9].i = top_blob.cstep;
                               ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/permute_vulkan.cpp:170:13: error: request for member ‘record_pipeline’ in ‘cmd’, which is of non-class type ‘int’
         cmd.record_pipeline(pipeline_permute, bindings, constants, top_blob);
             ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/permute_vulkan.cpp:170:29: error: ‘pipeline_permute’ was not declared in this scope
         cmd.record_pipeline(pipeline_permute, bindings, constants, top_blob);
                             ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/permute_vulkan.cpp:175:13: error: request for member ‘record_pipeline’ in ‘cmd’, which is of non-class type ‘int’
         cmd.record_pipeline(pipeline_permute_pack4to1, bindings, constants, bottom_blob);
             ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/permute_vulkan.cpp:175:29: error: ‘pipeline_permute_pack4to1’ was not declared in this scope
         cmd.record_pipeline(pipeline_permute_pack4to1, bindings, constants, bottom_blob);
                             ^
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/vulkan/permute_vulkan.cpp.o] 错误 1
make[2]:正在离开目录 `/home/lpadas1/share/HDD/jory.d/build/ncnn-master/build_vulkan'
make[1]: *** [src/CMakeFiles/ncnn.dir/all] 错误 2
make[1]:正在离开目录 `/home/lpadas1/share/HDD/jory.d/build/ncnn-master/build_vulkan'
make: *** [all] 错误 2
lpadas1@lpadas1:~/share/HDD/jory.d/build/ncnn-master/build_vulkan$

**Comment by nihui** [comment]
It seems that there is another platform.h header file in your system path or local path

**Comment by dangxusheng** [comment]
It is ok when setting NCNN_VULKAN =OFF, But I want to  compile with NCNN_VULKAN=ON, this is latest error messages:
-----------------------------------------------------------------
 In file included from /home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:15:0:
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.h:31:33: error: ‘VkMat’ has not been declared
     virtual int forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& opt) const;
                                 ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.h:31:57: error: ‘VkCompute’ has not been declared
     virtual int forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& opt) const;
                                                         ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.h:34:5: error: ‘Pipeline’ does not name a type
     Pipeline* pipeline_absval;
     ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.h:35:5: error: ‘Pipeline’ does not name a type
     Pipeline* pipeline_absval_pack4;
     ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp: In constructor ‘ncnn::AbsVal_vulkan::AbsVal_vulkan()’:
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:25:5: error: ‘pipeline_absval’ was not declared in this scope
     pipeline_absval = 0;
     ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:26:5: error: ‘pipeline_absval_pack4’ was not declared in this scope
     pipeline_absval_pack4 = 0;
     ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp: In member function ‘virtual int ncnn::AbsVal_vulkan::create_pipeline(const ncnn::Option&)’:
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:31:17: error: ‘vk_specialization_type’ was not declared in this scope
     std::vector<vk_specialization_type> specializations;
                 ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:31:39: error: template argument 1 is invalid
     std::vector<vk_specialization_type> specializations;
                                       ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:31:39: error: template argument 2 is invalid
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:31:56: error: invalid type in declaration before ‘;’ token
     std::vector<vk_specialization_type> specializations;
                                                        ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:35:9: error: ‘pipeline_absval’ was not declared in this scope
         pipeline_absval = new Pipeline(vkdev);
         ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:35:31: error: expected type-specifier before ‘Pipeline’
         pipeline_absval = new Pipeline(vkdev);
                               ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:35:31: error: expected ‘;’ before ‘Pipeline’
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:42:9: error: ‘pipeline_absval_pack4’ was not declared in this scope
         pipeline_absval_pack4 = new Pipeline(vkdev);
         ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:42:37: error: expected type-specifier before ‘Pipeline’
         pipeline_absval_pack4 = new Pipeline(vkdev);
                                     ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:42:37: error: expected ‘;’ before ‘Pipeline’
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp: In member function ‘virtual int ncnn::AbsVal_vulkan::destroy_pipeline(const ncnn::Option&)’:
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:52:12: error: ‘pipeline_absval’ was not declared in this scope
     delete pipeline_absval;
            ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:55:12: error: ‘pipeline_absval_pack4’ was not declared in this scope
     delete pipeline_absval_pack4;
            ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp: At global scope:
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:61:36: error: ‘int ncnn::AbsVal_vulkan::forward_inplace’ is not a static member of ‘class ncnn::AbsVal_vulkan’
 int AbsVal_vulkan::forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& /*opt*/) const
                                    ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:61:36: error: ‘VkMat’ was not declared in this scope
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:61:43: error: ‘bottom_top_blob’ was not declared in this scope
 int AbsVal_vulkan::forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& /*opt*/) const
                                           ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:61:60: error: ‘VkCompute’ was not declared in this scope
 int AbsVal_vulkan::forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& /*opt*/) const
                                                            ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:61:71: error: ‘cmd’ was not declared in this scope
 int AbsVal_vulkan::forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& /*opt*/) const
                                                                       ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:61:76: error: expected primary-expression before ‘const’
 int AbsVal_vulkan::forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& /*opt*/) const
                                                                            ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:61:97: error: expression list treated as compound expression in initializer [-fpermissive]
 int AbsVal_vulkan::forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& /*opt*/) const
                                                                                                 ^
/home/lpadas1/share/HDD/jory.d/build/ncnn-master/src/layer/vulkan/absval_vulkan.cpp:61:99: error: expected ‘,’ or ‘;’ before ‘const’
 int AbsVal_vulkan::forward_inplace(VkMat& bottom_top_blob, VkCompute& cmd, const Option& /*opt*/) const
                                                                                                   ^
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/vulkan/absval_vulkan.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] 错误 2
make: *** [all] 错误 2
lpadas1@lpadas1:~/share/HDD/jory.d/build/ncnn-master/build_vulkan$

**Comment by dangxusheng** [comment]
@nihui, please help me to solve this problem, thank you ~

**Comment by sebastianfelipe** [comment]
Can you run vulkaninfo?

**Comment by nihui** [comment]
The latest master branch supports compiling gpu functions without installing vulkan-sdk. You can give it a try.
If it doesn’t work, feel free to reopen the issue and post your findings.
