### ISSUE TITLE
使用DNCNN_VULKAN编译后int8推断报错

### ISSUE THREAD

**Issue by sunnymoon155** [Tencent/ncnn#1457]
make没问题，执行推断时结果也没问题，但是提示vkCreateInstance failed -9
新旧版本的VULKAN都试过了还是不行，不用VULKAN的话推断速度太慢了，系统是Centos7

**Comment by nihui** [comment]
需要升级显卡驱动

**Comment by dangxusheng** [comment]
我使用VULKAN后make过不去， 报错了，你遇到过吗？
-------------------------------------------------------------------------
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/vulkan/absval_vulkan.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] 错误 2
make: *** [all] 错误 2
lpadas1@lpadas1:~/share/HDD/jory.d/build/ncnn-master/build_vulkan$

**Comment by sunnymoon155** [comment]
> ## 我使用VULKAN后make过不去， 报错了，你遇到过吗？
> make[2]: *** [src/CMakeFiles/ncnn.dir/layer/vulkan/absval_vulkan.cpp.o] 错误 1
> make[1]: *** [src/CMakeFiles/ncnn.dir/all] 错误 2
> make: *** [all] 错误 2
> lpadas1@lpadas1:~/share/HDD/jory.d/build/ncnn-master/build_vulkan$

没有诶，我的make没有问题，就是用不了

**Comment by nihui** [comment]
安装 nvidia 显卡驱动的时候，需要将 opengl 的组件也安装才能使用 vulkan。如有问题可 reopen issue 继续交流。
