### ISSUE TITLE
benchmark上与examples下测试模型的速度不一致

### ISSUE THREAD

**Issue by hajungong007** [Tencent/ncnn#1463]
我有一个语义分割的模型，是在x86上测试，修改了benchmark下的代码单独测试网络的性能，速度是9.1ms。然而我把整个工程放在examples目录下，由于依赖opencv4，在cmakelist中添加了set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")，测试我的网络推理部分的速度是12.55ms。请问我是哪里弄错了配置啊？另外一个问题，我在firefly rk3399　linux下参考交叉编译的文档编译ncnn，测试benchmark上的模型的速度跟您们提供的参考评测是一致的，但是我的模型在benchmark上速度比我单独分离出来的工程的快一倍，是哪些因素影响导致的呢？

**Comment by nihui** [comment]
benchmark 使用了内存池 （allocator）
example 为了简便没有使用
