### ISSUE TITLE
output shows nulls on Reshape

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#1465]
these are last layers of my model.
I was getting null op. so I checked all layers from last.
I found that I am getting right output till Convo 84 layer.
but after it , Reshape layers gives me 0 /null mat.
am I doing something wrong.
I have correctly exported model from pytorch.

Convolution      84                       1 1 83 84 0=4 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=2304
Reshape          86                       1 1 84 86
Permute          87                       1 1 86 87
Reshape          89                       1 1 87 89 0=448 1=448 2=1
BinaryOp         90                       2 1 53 89 90 0=0

**Comment by nihui** [comment]
This Reshape-Permute-Reshape block seems to be a pytorch PixelShuffle operation.
Try updating to the latest ncnn code, which implements PixelShuffle layer and related onnx conversion.
Feel free to reopen this issue if you still encounter this problem.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
