### ISSUE TITLE
onnx2ncnn转换的模型 Segmentation fault

### ISSUE THREAD

**Issue by yippeesoft** [Tencent/ncnn#1469]
MXNET MODEL使用 https://github.com/deepinsight/insightface/wiki/Model-Zoo    MobileFaceNet,ArcFace@ms1m-refine-v1
https://pan.baidu.com/s/1If28BkHde4fiuweJrbicVA 

直接用mxnet2ncnn转换的ncnn model运行正常。

先转换成onnx格式，mxnet使用onnx model也正常。
input_shape=(1,3,112,112)
onnx_file='./model-y1.onnx'
converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)
再用onnx2ncnn转成ncnn mode，ex.extract会导致 Segmentation fault

**Comment by nihui** [comment]
mxnet模型用mxnet2ncnn直接转换
onnx主要是用来转pytorch模型的

**Comment by yippeesoft** [comment]
好的。谢谢。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
