### ISSUE TITLE
caffe2ncnn 转换InceptionV3模型段错误

### ISSUE THREAD

**Issue by SunAriesCN** [Tencent/ncnn#147]
InceptionV3有些模块长下面的样子：
‘’‘
layer {
  name: "conv2d_36"
  type: "Convolution"
  bottom: "conv2d_35"
  top: "conv2d_36"
  convolution_param {
    num_output: 128
    bias_term: false
    stride: 1
    pad_h: 3
    pad_w: 0
    kernel_h: 7
    kernel_w: 1
  }
}
‘’‘’
貌似会出段错误，gdb是下面这句出的错，估计是没有kernel_size报了caffe内部错误。
‘’‘
convolution_param.kernel_size(0);
‘’‘’
倪神能不考虑下支持InceptionV3这种妖孽卷积核？

**Comment by nihui** [comment]
#102
