### ISSUE TITLE
retinaface 'parse magic failed'

### ISSUE THREAD

**Issue by sanrahul** [Tencent/ncnn#1471]
Platform:: Linux

When I build ncnn with 'examples'(by setting it in CMake), the retinaface executable works fine.

However when I build retinaface separately,  the executable is not throwing following exception on execution::
parsemagicfailed
network graph not ready
find_blob_index_by_name data failed
find_blob_index_by_name face_rpn_cls_prob_reshape_stride32 failed
find_blob_index_by_name face_rpn_bbox_pred_stride32 failed
find_blob_index_by_name face_rpn_landmark_pred_stride32 failed
Floating point exception (core dumped)

CMake File::

project(FaceDetector)

add_definitions(-std=c++11)
add_definitions("-Wall")

set(OpenCV_DIR "/usr/local/opencv/")
set(NCNN_DIR <your compiled ncnn>)
if(True)
    find_package(OpenMP)
    if(NOT TARGET OpenMP::OpenMP_CXX AND (OpenMP_CXX_FOUND OR OPENMP_FOUND))
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
    endif()
endif()

include_directories(${OpenCV_DIR}/include
                    ${NCNN_DIR}/include
                    )

link_directories(${OpenCV_DIR}/lib/
                 ${NCNN_DIR}
                  )

set(OpenCV_LIBS opencv_core 
                opencv_highgui 
                opencv_imgproc 
                opencv_imgcodecs 
                opencv_videoio)

set(SRC
	retinaface.cpp
        )

add_executable(FaceDetector ${SRC})
target_link_libraries(FaceDetector ncnn ${OpenCV_LIBS})
if(OpenMP_CXX_FOUND)
    if(NCNN_CMAKE_VERBOSE)
        message("Building with OpenMP")
    endif()
    target_link_libraries(FaceDetector PUBLIC OpenMP::OpenMP_CXX)
endif()

**Comment by sanrahul** [comment]
However when I build squeezenet.cpp separately.. it's executable works fine

**Comment by sanrahul** [comment]
Found the issue:: model issue
Reconverted again to ncnn from mxnet using the same converter tool. 
Works fine now.

**Comment by quocnhat** [comment]
Hi @sanrahul 
I fall into the same problem.
what do you mean with the same converter tool?
I've tried to rebuild the model but did not solve it. thanks

**Comment by JavisPeng** [comment]
@quocnhat 
I just resovle this issue by converting the original mxnet weight file 
[](https://github.com/Tencent/ncnn/issues/2218)
