### ISSUE TITLE
`SliceChannel` op can not get the correct result 

### ISSUE THREAD

**Issue by IvyGongoogle** [Tencent/ncnn#1473]
Hello, I use `mxnet` to define a model, in which I use a op `output = mx.sym.SliceChannel(input, num_outputs=40,  axis =2)` where `input` is tensor of `7 x 40 x 96(h x w x c)`, so `output` should have 40 tensors where everyone is `7x96`.  But I use `mxnet2ncnn` to convert my model and then use ncnn C++ inference api to infer the converted model. When I check the output, I find it's w, h, c  is `40 x 7 x 2` rather than `40 x 7 x  96`.  
So what causes this incorrect result ?   Can you give some advises?

**Comment by nihui** [comment]
There's something wrong with your description itself.
output = mx.sym.SliceChannel(input, num_outputs=40, axis =2)
input is 7 x 40 x 96(h x w x c)
the output cannot be 10 tensors where everyone is 8x32

by the way, we don't usually use NHWC shape notation in mxnet model

**Comment by IvyGongoogle** [comment]
@nihui  Thanks for your reply. Sorry, I wrote it wrongly and I have corrected it.   Now I add the params `1=1` at `Slice` layer and it works.
