### ISSUE TITLE
前向运行Segmentation fault

### ISSUE THREAD

**Issue by sherlockgjh** [Tencent/ncnn#1478]
您好，我这边模型是由onnx转为ncnn的，在android端测试，模型运行正常，但是在linux上，模型前向运行总会出现Segmentation fault，显示信息为：
![image](https://user-images.githubusercontent.com/48944589/71948145-00a38680-320a-11ea-8fea-53dc1e91fa8c.png)
请问，您这边知道这是什么原因导致吗？

**Comment by nihui** [comment]
更新ncnn库，重新转换下模型

**Comment by sherlockgjh** [comment]
您好，我已经更新到最新的ncnn库，且模型在此ncnn库下重新转换，但仍是出现Segmentation fault：
![image](https://user-images.githubusercontent.com/48944589/71957220-1cb62080-3228-11ea-8a8b-f3b3006f1d32.png)
ncnn库信息：
![image](https://user-images.githubusercontent.com/48944589/71957248-38212b80-3228-11ea-9146-de973bf889b7.png)

**Comment by nihui** [comment]
经过检查，发现是接口调用错了...

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
