### ISSUE TITLE
int8量化后模型执行时间减少，cpu占用飙升

### ISSUE THREAD

**Issue by jiyinghui39** [Tencent/ncnn#1479]
模型使用https://github.com/Tencent/ncnn/tree/master/tools/quantize量化完成后，实际测试，每次检测的时间由量化前的120ms左右，减少到量化后的60ms左右。但是实际测试cpu资源占用，发现CPU资源占用由量化前的6%，飙升到40%。通过观察发现，系统同时有4个线程再运行了（量化时指定了--thread=1 1个线程）。量化前系统只有1个线程同时运行。
另外还有一个模型，通过量化后执行正常。
运行的平台为anroid 8.1, armv7。是否有人遇到过类似问题。求解答。

**Comment by jiyinghui39** [comment]
补充说明下，使用的模型为MobileFaceNet

**Comment by SophieChang66** [comment]
@你好，请问arm上 int8耗时对比过吗？

**Comment by jiyinghui39** [comment]
问题找到了。代码中使用的一个函数resize_bilinear(const Mat& src, Mat& dst, int w, int h)函数; 新的ncnn库变更为resize_bilinear(const Mat& src, Mat& dst, int w, int h, const Option& opt)了。继续使用以前的定义，编译可以通过，但是执行会异常。添加上opt的参数，就正常了。感谢支持。
