### ISSUE TITLE
@wuxiang20111

### ISSUE THREAD

**Issue by silencervan** [Tencent/ncnn#1481]
@wuxiang20111   

速度主导的话。

1. int8 测试需要打开 REQUANT 编译选项；
2. fp32 需要在源码里打开 layout 选项（改 1 行就行）；
3. 目前在 armv7/arm64 上优化较多，不适用 x86/mips 芯片。

_Originally posted by @tpoisonooo in https://github.com/Tencent/ncnn/issues/1413#issuecomment-564423355_

**Comment by wuxiang20111** [comment]
你好，fp32 需要在源码里打开 layout 选项（改 1 行就行）具体怎么改啊

**Comment by nihui** [comment]
在 load_param 前
net.opt.use_packing_layout = true;

**Comment by wuxiang20111** [comment]
你好，请问添加net.opt.use_packing_layout = true;这个是在前向测试时候添加这个语句，还是在源码添加之后从新编译ncnn

**Comment by nihui** [comment]
这个开关在最新版本中已自动开启，无需修改源码
