### ISSUE TITLE
Loading Model Incorrect

### ISSUE THREAD

**Issue by joeson996** [Tencent/ncnn#1482]
When I try to load "squeezenet_v1.1.param.bin" and "squeezenet_v1.1.bin" (get from ncnn-android-squeezenet) in Linux platform(Ubuntu 16.04) with source code

`
    ncnn::Net net;
    net.load_param("squeezenet_v1.1.param.bin");
    net.load_model("squeezenet_v1.1.bin");
`
But there's some error message : 

parse magic failed
network graph not ready

**Comment by nihui** [comment]
you should use load_param_bin to load binary param.bin file

**Comment by joeson996** [comment]
> you should use load_param_bin to load binary param.bin file

Thanks, the issue is fixed. But the outcome is still incorrect. 

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include "net.h"
#include "squeezenet.id.h"
#include <iostream>
using namespace std;

int main()
{
	cv::Mat img = cv::imread("IMG_20191224_181353.jpg", 1);
	int width = img.cols;
	int height = img.rows;

	ncnn::Net squeezenet;
	squeezenet.load_param_bin("/home/liuwenjie/Project/ncnn/squeezenet.param.bin");
	squeezenet.load_model("/home/liuwenjie/Project/ncnn/squeezenet.bin");

	// subtract 128, norm to -1 ~ 1
	ncnn::Mat in = ncnn::Mat::from_pixels(img.data, ncnn::Mat::PIXEL_BGR, width, height);

	// squeezenet
	std::vector<float> cls_scores;
	const float mean_vals[3] = {104.f, 117.f, 123.f};
	in.substract_mean_normalize(mean_vals, 0);
	ncnn::Extractor ex = squeezenet.create_extractor();
	ex.set_light_mode(true);
	ex.set_num_threads(4);

	int inSucess = ex.input(squeezenet_param_id::BLOB_data, in);

	ncnn::Mat out;
	ex.extract(squeezenet_param_id::BLOB_prob, out);

	cls_scores.resize(out.c);
	for (int j=0; j<out.c; j++)
	{
		const float* prob = out.channel(j);
		cls_scores[j] = prob[0];

		cout << cls_scores[j] << endl;      // results only print out value 1.92253e-05
	}

	return 0;
}

squeezenet.param.bin and squeezenet.bin are transformed from Caffe. Here is the following step:
1. download official Caffe model and graph ---- squeezenet_v1.1.caffemodel&&deploy.prototxt 
2. use caffe2ncnn --- transform squeezenet_v1.1.caffemodel&&deploy.prototxt     to  squeezenet.bin  &&squeezenet.param
3. use ncnn2mem --- transform squeezenet.bin&&squeezenet.param     to    squeezenet.mem.h&&  squeezenet.param.bin&&squeezenet.id.h&&squeezenet.param.bin
4. use squeezenet.param.bin&&squeezenet.id.h&&squeezenet.param.bin(3 files) with above code to generate a detection process.

**Comment by nihui** [comment]
you can refer how the output blob is handled in example code
https://github.com/Tencent/ncnn/blob/591b13ed05e80fd4fbff46f38a0c14732586563f/examples/squeezenet.cpp#L54

**Comment by joeson996** [comment]
> you can refer how the output blob is handled in example code
> https://github.com/Tencent/ncnn/blob/591b13ed05e80fd4fbff46f38a0c14732586563f/examples/squeezenet.cpp#L54

same error result

**Comment by joeson996** [comment]
![IMG_20191224_181353](https://user-images.githubusercontent.com/49138243/72250060-ba00c280-3635-11ea-8922-d4f15f0009c2.jpg)
This is the test image.

**Comment by nihui** [comment]
```
./squeezenet 72250060-ba00c280-3635-11ea-8922-d4f15f0009c2.jpg 
508 = 0.712668
810 = 0.133960
878 = 0.082166
```

n03085013 computer keyboard, keypad

**Comment by joeson996** [comment]
> ```
> ./squeezenet 72250060-ba00c280-3635-11ea-8922-d4f15f0009c2.jpg 
> 508 = 0.712668
> 810 = 0.133960
> 878 = 0.082166
> ```
> 
> n03085013 computer keyboard, keypad

Could you please send a sample code with squeezenet model files, I'm really not sure whether it is the problem with the code or the transformed model file?

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/tree/master/examples
