### ISSUE TITLE
How to convert ncnn mat type?

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#1491]
I am sounding like a noob but how to convert ncnn mat to dirrerent type.

Here I get mat from source in RGB format.

ncnn_rgb = ncnn::Mat::from_pixels(faceImageChar, ncnn::Mat::PIXEL_BGR2RGB,
                                          imageWidth, imageHeight);

now I want to convert this rgb mat to gray mat to pass in dirrerent model.

**Comment by nihui** [comment]
```
ncnn_gray = ncnn::Mat::from_pixels(faceImageChar, ncnn::Mat::PIXEL_BGR2GRAY,
imageWidth, imageHeight);
```

**Comment by soham24** [comment]
ncnn::Mat::from_pixels does this method work on nccn::Mat also?
will this work?

ncnn_gray = ncnn::Mat::from_pixels(ncnn_gray, ncnn::Mat::PIXEL_RGB2GRAY,
imageWidth, imageHeight);

**Comment by nihui** [comment]
no
As you can always get a grayscale mat at the beginning, the usecase of mat color conversion is rare

**Comment by soham24** [comment]
thanks just wanted to make sure
