### ISSUE TITLE
Android Sample

### ISSUE THREAD

**Issue by philp123** [Tencent/ncnn#1492]
When I check out the Android example "https://github.com/nihui/ncnn-android-squeezenet/", I find out that this sample code is using pre-compiled dynamic library "libsqueezenet.so" rather than compiled library from jni file. But when I try to reconstruct from jni cpp file, error is always there. I've commented  in relevant issues "https://github.com/nihui/ncnn-android-squeezenet/issues/5" but nobody replied. Would someone please give feedbacks about this issue, that would be very kind of you. Thanks!

**Comment by nihui** [comment]
This sample project is the very basic one, it should work as long as you follow the instructions in README.
