### ISSUE TITLE
vulkan split layer output issue

### ISSUE THREAD

**Issue by Chanbluky** [Tencent/ncnn#1494]
it seems that the vulkan split layer is not correct. when I enable vulkan to inference, the output from split is always incorrect, but once disable vulkan, the output become correct. attached is the param and bin files I used.

[ERFNet_model.zip](https://github.com/Tencent/ncnn/files/4058403/ERFNet_model.zip)

**Comment by Chanbluky** [comment]
environment: Window10 VS2015, ncnn20200106, vulkan 1.121.2

**Comment by nihui** [comment]
confirmed and reproduced

**Comment by nihui** [comment]
fix non-symmetric dilation convolution on x86 
https://github.com/Tencent/ncnn/commit/71b11d3457ba4fcd5a56a63710ea52250b4f8b20

**Comment by nihui** [comment]
feel free to reopen this if you still suffer from it.
