### ISSUE TITLE
reclaim_blob_allocator/reclaim_staging_allocator get wild allocator

### ISSUE THREAD

**Issue by Chanbluky** [Tencent/ncnn#1495]
I always get the following two FATAL ERRORs when i use vulkan to inference:
FATAL ERROR! reclaim_blob_allocator get wild allocator  00000xxxxxxxxxxx
FATAL ERROR! reclaim_staging_allocator get wild allocator  00000xxxxxxxxxxx

my Environment: vs2015, vulkan1.121.2 ncnn20200106
code:
ncnn::create_gpu_instance();
ncnn::Mat input_data = ncnn::Mat::from_pixels_resize(img_crop.data, ncnn::Mat::PIXEL_BGR, w, h, target_w, target_h);
const float mean_value[] = { 103.939, 116.779, 123.68 };
const float std_value[] = { 1.0,1.0,1.0 };
input_data.substract_mean_normalize(mean_value, std_value);

ncnn::Net net;
net.opt.use_vulkan_compute = 1;
	
net.opt.use_fp16_packed = false;
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
net.opt.use_int8_storage = false;
net.opt.use_int8_arithmetic = false;

net.load_param("ERFNet_model-op.param");
net.load_model("ERFNet_model-op.bin");

ncnn::Extractor ex = net.create_extractor();
ex.set_vulkan_compute(true);

ncnn::Mat out1;
ex.extract("358", out1);

ncnn::Mat out;
ex.extract("out", out);

ncnn::destroy_gpu_instance();
[ERFNet_model.zip](https://github.com/Tencent/ncnn/files/4062846/ERFNet_model.zip)

**Comment by nihui** [comment]
you have to ensure ncnn::destroy_gpu_instance(); is called after ncnn::Net instance destruction
```
ncnn::create_gpu_instance();

{
ncnn::Net net;
}

ncnn::destroy_gpu_instance();
```
