### ISSUE TITLE
load_param_bin 导入模型的时候，可能会卡死在layers.resize() blobs.resze()

### ISSUE THREAD

**Issue by lubinBoooos** [Tencent/ncnn#150]
当使用者偶然出现load_param_bin导入了错误的模型文件或者把模型的权值文件作为输入，这个函数中的layer_count/blob_count可能会出现负数，从而导致程序卡在layers.resize() blobs.resze()处，建议在这之前对读入的文件做一个判断，防止误操作

**Comment by nihui** [comment]
new param load api 检查开头特殊的 magic number
