### ISSUE TITLE
lstm arm

### ISSUE THREAD

**Issue by hset911** [Tencent/ncnn#1501]
lstm的arm版本有计划更新吗？

**Comment by tpoisonooo** [comment]
why not ?!

**Comment by beniz** [comment]
FTR, we are maintaining an updated ARM version of the LSTM layer, here: https://github.com/jolibrain/ncnn/blob/master/src/layer/lstm.cpp
It's tested in production on OCR systems.

**Comment by tpoisonooo** [comment]
> FTR, we are maintaining an updated ARM version of the LSTM layer, here: https://github.com/jolibrain/ncnn/blob/master/src/layer/lstm.cpp
> It's tested in production on OCR systems.

How did you convert LSTM model to ncnn.para/ncnn.bin, would you please give an example ?

**Comment by beniz** [comment]
You may want to look at https://github.com/jolibrain/ncnn/blob/master/tools/caffe/caffe2ncnn.cpp#L1195

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/1613

**Comment by hset911** [comment]
> #1613

up主最近在推进ocr_lite，不如顺手把lstm的速度问题解决了吧，也好大家好好学(白)习(嫖)

**Comment by nihui** [comment]
We now have arm neon optimization for RNN LSTM and GRU in the latest ncnn version !
