### ISSUE TITLE
用了 onnxsimple之后 依旧Gather not supported yet

### ISSUE THREAD

**Issue by GYxiaOH** [Tencent/ncnn#1502]
Simplifying...
Ok!
Gather not supported yet!
  # axis=0
Gather not supported yet!
  # axis=0
Gather not supported yet!
  # axis=0
Gather not supported yet!
  # axis=0
Gather not supported yet!
  # axis=0
Gather not supported yet!
  # axis=0
Gather not supported yet!

但是文件正常生成了，不知道什么情况

**Comment by GYxiaOH** [comment]
不知道我该用什么思路去debug这个问题

**Comment by nihui** [comment]
如果还是无法去除，只能手工修改param了
https://zhuanlan.zhihu.com/p/93017149

btw shufflenetv2建议使用 pytorch 官方的实现

**Comment by nihui** [comment]
最新的 onnx2ncnn 支持了 megvii shufflenet 的 channel shuffle 和 split channel

**Comment by shineway14** [comment]
用的是官方实现，还是 有这个问题

**Comment by Printeger** [comment]
> 用的是官方实现，还是 有这个问题

 请问您解决了吗？我也遇到了这个问题，onnxsim 不能完全简化。
