### ISSUE TITLE
为什么有的reshape（view）操作之后，输出就是空了？

### ISSUE THREAD

**Issue by GYxiaOH** [Tencent/ncnn#1507]
pytorch-onnx-ncnn，发现channel—shuffle的reshape之后就没有输出了，是不是维度太高就不行，我大概转成了6维的形状。。因为发现split不支持第一个维度的split。。。
因为用的shufflenetplus，没法用官方模型
by the way:
我把shufflenet-series里的channel shuffle换成了官方的channelshuffle 跑是能跑了，就是输出都是0.。。。。。
越深层0越多，最后全是0了....

**Comment by nihui** [comment]
请提供下 onnx 文件

**Comment by nihui** [comment]
最新的 onnx2ncnn 支持了 megvii shufflenet 的 channel shuffle 和 split channel

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
