### ISSUE TITLE
ncnn2table format for grayscale image model

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#1509]
in normal flow of (fp32), I normalize images with  norm value {0.00392156862} which is (1/255)
and passing mean as 0.

how can I execute ncnn2table for  this ? 

./ncnn2table --param example-nobn-fp32.param --bin example-nobn-fp32.bin --images images/ --output example-nobn.table --mean 0 --norm 0.00392156862 --size 224,224 --thread 2

is this the right approach?

also, the example I am working on is of object detector.
It detects for object in 224/224 frame.
so while training I normalized bouding box by x/224, y/224 and so on. so it fits in range of 0 to 1.
normal ncnn (fp32) gives me op in same range . then I multiply it by 224 and get desired values.
what changes I need to perform when using in8 interface.

ps. thank you so much for optimise and int8 tool. this is world class work. 
 to @nihui  and all developers working on this.

**Comment by soham24** [comment]
@kalcohol @nihui

**Comment by soham24** [comment]
@nihui @kalcohol do I need to pass my gray input as 3 channel?

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507 release brings massive int8 inference speedup, and ncnn2table tool is completely rewritten.
The new tool now supports grayscale model input
