### ISSUE TITLE
当输入的ncnn::Mat的size和input layer的h w不匹配的时候 net是怎么处理的

### ISSUE THREAD

**Issue by ygyin-ivy** [Tencent/ncnn#151]
你好，我想问一下
我input layer的h w 是12 12
但是ncnn::Mat的size 是64 48
请问此时net的forward_layer是怎么处理的？

**Comment by nihui** [comment]
会依照输入的实际 Mat size 处理
input layer 的 w h c 实际并不会看

**Comment by ygyin-ivy** [comment]
谢谢



yinyongguang@ivymobile.com
 
发件人： nihui
发送时间： 2017-09-27 19:07
收件人： Tencent/ncnn
抄送： ygyin-ivy; Author
主题： Re: [Tencent/ncnn] 当输入的ncnn::Mat的size和input layer的h w不匹配的时候 net是怎么处理的 (#151)
会依照输入的实际 Mat size 处理
input layer 的 w h c 实际并不会看

**Comment by ygyin-ivy** [comment]
谢谢

**Comment by ygyin-ivy** [comment]
谢谢，不过如果接下来是全连接层就会出错吧？毕竟model的参数数目不会变化

**Comment by nihui** [comment]
对的，全卷积网络会这么做，有全连接层会出错
