### ISSUE TITLE
performance vs opencv dnn module

### ISSUE THREAD

**Issue by pfeatherstone** [Tencent/ncnn#1512]
this isn't an issue, rather an observation
opencv dnn module, in CPU mode, is about 6x faster than ncnn using same number of threads and AVX2 enabled

**Comment by zchrissirhcz** [comment]
@pfeatherstone ncnn aims mobile (Android) first thus PC CPU is not that fast.

**Comment by nihui** [comment]
ncnn is mainly optimized for mobile platform
If you deploy your model on android phone with ncnn, it will run much faster than opencv dnn module

**Comment by pfeatherstone** [comment]
Could there be a "-march=native" option in CMake ?

**Comment by nihui** [comment]
I don't think march=native would make much runtime speed difference.
If you need faster inference on your PC, the ncnn vulkan support is there and runs fast on almost any platforms, including intel amd nvidia etc.

**Comment by PrashantDandriyal** [comment]
What about Beaglebone devices ? @nihui Do you mean NCNN will perform better on these devices too ? 

Also, I guess will it be better than FeatherCNN ?
