### ISSUE TITLE
Segmentation fault when using Vulkan

### ISSUE THREAD

**Issue by sebastianfelipe** [Tencent/ncnn#1513]
Hi! I realize that when I use Vulkan I cannot run models without a segmentation fault. Some commits before it weren't a problem at all. Please try to run the mnet.25-opt (retinaface example) and see what happens.

Thanks,
Sebastián.

**Comment by sebastianfelipe** [comment]
@nihui I think this is important.

**Comment by sebastianfelipe** [comment]
Solved: It is necessary to load the model after set use_vulkan_compute=true, because if it is set before, there is a segmentation fault coming.

**Comment by dianxin556** [comment]
@sebastianfelipe ,where to set use_vulkan_comput=true? I have the same problem :
fopen mnet.25-opt.param failed
fopen mnet.25-opt.bin failed
find_blob_index_by_name data failed
find_blob_index_by_name face_rpn_cls_prob_reshape_stride32 failed
find_blob_index_by_name face_rpn_bbox_pred_stride32 failed
find_blob_index_by_name face_rpn_landmark_pred_stride32 failed
Floating point exception (core dumped)
