### ISSUE TITLE
Why not use Eigen3 for convolutions?

### ISSUE THREAD

**Issue by pfeatherstone** [Tencent/ncnn#1514]
Why not use Eigen3 for fast convolutions? It's a header-only library that is proven to be fast, works everywhere and is used by major frameworks (Tensorflow)

**Comment by BUG1989** [comment]
Because the Eigen3 is slower than the implement of ncnn.



---Original---

**Comment by pfeatherstone** [comment]
Is this for - loop faster than eigen3 or a gemm function:

#pragma omp parallel for num_threads(opt.num_threads)
    for (int p=0; p<num_output; p++)
    {
        float* outptr = top_blob.channel(p);

        for (int i = 0; i < outh; i++)
        {
            for (int j = 0; j < outw; j++)
            {
                float sum = 0.f;

                if (bias_term)
                    sum = bias_data[p];

                const float* kptr = (const float*)weight_data + maxk * channels * p;

                // channels
                for (int q=0; q<channels; q++)
                {
                    const Mat m = bottom_blob_bordered.channel(q);
                    const float* sptr = m.row(i*stride_h) + j*stride_w;

                    for (int k = 0; k < maxk; k++) // 29.23
                    {
                        float val = sptr[ space_ofs[k] ]; // 20.72
                        float w = kptr[k];
                        sum += val * w; // 41.45
                    }

                    kptr += maxk;
                }

                if (activation_type == 1)
                {
                    sum = std::max(sum, 0.f);
                }
                else if (activation_type == 2)
                {
                    float slope = activation_params[0];
                    sum = sum > 0.f ? sum : sum * slope;
                }
                else if (activation_type == 3)
                {
                    float min = activation_params[0];
                    float max = activation_params[1];
                    if (sum < min)
                        sum = min;
                    if (sum > max)
                        sum = max;
                }
                else if (activation_type == 4)
                {
                    sum = static_cast<float>(1.f / (1.f + exp(-sum)));
                }

                outptr[j] = sum;
            }

            outptr += outw;
        }
    }

**Comment by BUG1989** [comment]
This is naive implement of convolution.
On x86/arm platform, please see x86/convolution_x86.cpp or arm/convolution_arm.cpp



---Original---

**Comment by pfeatherstone** [comment]
Thanks. I see now.

**Comment by nihui** [comment]
By the way
Tensorflow use eigen3 for convolution, and that's why tensorflow runs much slower than ncnn on mobile I think.
