### ISSUE TITLE
shape hint in param

### ISSUE THREAD

**Issue by nihui** [Tencent/ncnn#1515]
As we do not know the input blob shape during the loading time, relu vulkan implementation has to create all the element packing pipeline variants. It is not only wasting lots of time for creating many unused pipelines, but also may waste memory for winograd or sgemm convolution weight relayout allocations.

resolve blob shapes
write optional output blob shapes for each layer
load blob shapes into paramdict
layer load_param may optionally ask for specific blob shape hint

**Comment by nihui** [comment]
```
// fixed id -23330 used for storing multiple shape hints
// thus maintaining backward and forward compatibility

Input    data    0 1 data -23330=4,3,227,227,3
```

```
class Shape
{
public:
    // 0 = empty
    int dims;

    // -233 = variable
    int w;
    int h;
    int c;
};

// new Layer member
class Layer
{
public:
    // shape hint
    std::vector<Shape> bottom_shapes;
    std::vector<Shape> top_shapes;
};

// bottom_shapes and top_shapes
// should be ready for use in load_param / load_model / create_pipeline ...
```

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/6cefaad9578ef76ec9641dd932841920458e01d7
https://github.com/Tencent/ncnn/commit/e2bd4eae6e1a0aeecd3c76be92f9cd0785401efc

**Comment by lq0104** [comment]
Up主，关于这个有一个问题，这样设置之后是不是传给网络的输入图像分辨率就固定下来了？我做了一个测试，我往input wid=256, hei=256的模型放了一个512,512分辨率大小的图像，结果输出的结果就是些很奇怪的框，但是放入256,256分辨率大小的图像，输出结果就正确。我想问的是，如果在识别工作中我的输入给模型图像分辨率不能确定下来，可能会发生变化，这个时候应该怎么处理啊 @nihui

**Comment by nihui** [comment]
> Up主，关于这个有一个问题，这样设置之后是不是传给网络的输入图像分辨率就固定下来了？我做了一个测试，我往input wid=256, hei=256的模型放了一个512,512分辨率大小的图像，结果输出的结果就是些很奇怪的框，但是放入256,256分辨率大小的图像，输出结果就正确。我想问的是，如果在识别工作中我的输入给模型图像分辨率不能确定下来，可能会发生变化，这个时候应该怎么处理啊 @nihui

ncnnoptimize 的时候，Input 层不填shape信息即可，就像```Input  input 0 1 data```

**Comment by lq0104** [comment]
> ncnnoptimize 的时候，Input 层不填shape信息即可，就像Input input 0 1 data
我试了一下，这样的话在ncnnoptimize之后生成的param中就没有23330的信息，不过测试不同输入的分辨率结果还是有问题，后来我定位了问题的原因，发现问题出在Crop层，例如：
Crop                   4_59                 1 1 3_51_bn_leaky_split_0 4_59 2=12 3=128 4=128 5=12
这里面属性3和4：3=128 4=128与输入分辨率是强相关的，所以输入分辨率一旦改了，这块就出问题了。我想一种解决方法就是针对自己的模型改成自适应的输出Crop层的分辨率的方式，因为我的Crop层的输出分辨率和输入分辨率是一样的。
不过先想问一下Up主ncnn目前有没有更合适的方式来解决这个问题？ @nihui

**Comment by nihui** [comment]
Crop 接受第二个 blob 输入作为 target shape 来对第一个 blob crop
```
Crop  crop 2 1 blob_to_crop shape_ref_crop dst
```

**Comment by lq0104** [comment]
好的，我的理解是如果input的分辨率是可变的，那么shape_ref_crop实际上也必须要求是可变的，但如果我的模型dst和blob_to_crop一致的话，那么shape_ref_crop也把它写成blob_to_crop就行？就想这样：
Crop  crop 2 1 blob_to_crop **blob_to_crop** dst
那如果dst和blob_to_crop的whc不一致的话，那我还需要在代码中考虑如何给shape_ref_crop的宽高自适应赋值的问题？

**Comment by nihui** [comment]
比如输入 input_blob 是可变size
Crop crop 2 1 blob_to_crop input_blob dst

**Comment by lq0104** [comment]
好的，谢谢Up主
