### ISSUE TITLE
build latest release version in RPi4 - error 

### ISSUE THREAD

**Issue by ghimiredhikura** [Tencent/ncnn#1521]
## build command
```
mkdir -p build
cd build    
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/pi3.toolchain.cmake ..
 make -j4
```
## error 
```
.../ncnn-20200106/src/layer/arm/convolution_arm.cpp:976:31: error: ‘activation_ss’ was not declared in this scope
                         sum = activation_ss(sum, activation_type, activation_params);
```
![image](https://user-images.githubusercontent.com/24696403/73637523-a377e500-4690-11ea-8bdd-769fa4922d31.png)

**Comment by nihui** [comment]
It seems that your are trying to compile the arm code without NEON enabled
You may try adding "-mfpu=neon" flag

**Comment by nihui** [comment]
If there are still problems, feel free to reopen issue
