### ISSUE TITLE
running realtime with camera feed takes more memory

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#1522]
when I run face detector of mtcnn realtime.. the time it takes increases as time passes exponentially. like it goes from 17ms to 300ms 
is there any ideal pipeline mechanism to run ncnn realtime /live.

**Comment by nihui** [comment]
the mtcnn face detection speed is not stable in theory, depending on how many faces there are in one frame.

btw, here is a fast and more 'speed-stable' face detector, you may interest in it.
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB

**Comment by soham24** [comment]
thanks @nihui
