### ISSUE TITLE
centos7系统下安装ncnn报错

### ISSUE THREAD

**Issue by joshua23333** [Tencent/ncnn#1526]
在g++4.8.5，libprotoc 3.11.3， cmake `3.12.0-rc1的版本下安装ncnn报错，
报错信息：
/usr/local/lib64/libopencv_videoio.so.3.4.6: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21

提示信息是：make[2]: *** [examples/simplepose] Error 1
make[1]: *** [examples/CMakeFiles/simplepose.dir/all] Error 2
make[2]: *** [examples/retinaface] Error 1
make[1]: *** [examples/CMakeFiles/retinaface.dir/all] Error 2
make: *** [all] Error 2

请问是什么原因？是我配置的不对吗

**Comment by nihui** [comment]
这个错误信息似乎是因为 opencv 安装有问题，你试试看重新编译安装 opencv

**Comment by joshua23333** [comment]
可是我没在服务器上装过opencv呀，安装ncnn也没说要opencv呀

**Comment by nihui** [comment]
ncnn的example需要用opencv读图片
有这个文件 /usr/local/lib64/libopencv_videoio.so.3.4.6 说明是有opencv的，但是没装好
/usr/local/ 下面找下 opencv 的文件
要么删掉，这样再编译ncnn的时候就不会编译example
要么重新编译安装下，这样就能编译出example

**Comment by joshua23333** [comment]
您好，我重新编译了opencv后，虽然make通过了，100%后也没有报错，但是build的文件夹下没有编译好的install文件夹，您看只有这几个文件
![image](https://user-images.githubusercontent.com/30322543/73904293-8b91a280-48d6-11ea-89d4-12b7374b3b3c.png)

**Comment by nihui** [comment]
`make install`

**Comment by joshua23333** [comment]
谢谢您，另外我想问问ncnn官方测量前向传播时间的源码是在哪个文件夹下的，我看到有个warmup的过程但是我没找到那部分代码

**Comment by joshua23333** [comment]
在benchmark文件夹下我找到了，谢谢您
