### ISSUE TITLE
自己转的分类模型无法输出结果

### ISSUE THREAD

**Issue by CheungBH** [Tencent/ncnn#1528]
你好。我用了squeezenet分类的demo，能够非常顺利地转换并且输出结果。
然后我用了自己训练的pth的mobilenet网络，通过pytorch-->onnx-->ncnn路线转换成功，然而输出图片的时候出现了问题：
find_blob_index_by_name data failed
find_blob_index_by_name prob failed
Segmentation fault (core dumped)
就退出了。

我看回了C++代码，是这几句出了问题（都是从squeezenet.cpp里面复制过来的）
    ncnn::Extractor ex = squeezenet.create_extractor();

    ex.input("data", in);

    ncnn::Mat out;
    ex.extract("prob", out);

我想问一下，这个"data"和“prob”是不是已经在squeezenet里面定义好的，mobilenet里面的这个名字是变了的？如果是这样的，我该怎么知道我自己的网络的这些名字是什么，该输入啥呢？
谢谢

**Comment by mengfu188** [comment]
这个我会，输入id对应param文件中的[Input](https://github.com/Tencent/ncnn/blob/01853010eae3fbd367a51eeed0f5540958cb8fe7/examples/squeezenet_v1.1.param#L3)，输出id对应[最后一行](https://github.com/Tencent/ncnn/blob/01853010eae3fbd367a51eeed0f5540958cb8fe7/examples/squeezenet_v1.1.param#L77)，看一下你生成的param文件就好了

**Comment by CheungBH** [comment]
> 这个我会，输入id对应param文件中的[Input](https://github.com/Tencent/ncnn/blob/01853010eae3fbd367a51eeed0f5540958cb8fe7/examples/squeezenet_v1.1.param#L3)，输出id对应[最后一行](https://github.com/Tencent/ncnn/blob/01853010eae3fbd367a51eeed0f5540958cb8fe7/examples/squeezenet_v1.1.param#L77)，看一下你生成的param文件就好了

感谢！可以用了~

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
