### ISSUE TITLE
Training ncnn model

### ISSUE THREAD

**Issue by CheungBH** [Tencent/ncnn#1529]
I wonder whether we can train the ncnn models after conversion? If so, are there any demos?

**Comment by nihui** [comment]
No, ncnn is an inference framework only.
For training models, I recommend pytorch

**Comment by pfeatherstone** [comment]
There is a problem though, most ONNX models, which is the standard format for exporting pytorch models, aren't convertible to ncnn. There is almost always an error. There are countless issues related to ```GATHER not supported``` for example. Which is the training framework of choice which minimises these errors?

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
