### ISSUE TITLE
模型部署到安卓端后输出为空

### ISSUE THREAD

**Issue by CheungBH** [Tencent/ncnn#1531]
你好
我把examples中的姿态检测跑了一遍在PC端测试。pose.bin和pose.param下载了下来之后，在PC端运行没有问题。
但我仿照mobilenetssd的demo的样子把它放到安卓上的时候，输出就有问题了。
![安卓](https://user-images.githubusercontent.com/39186017/74253589-3c120300-4d2a-11ea-8da8-4cb152ec0959.jpg)
右边的终端和文档是PC端的运行，左边的是安卓端的。

检查了加载模型的返回值和字节数。字节数是对得上的，加载模型返回值是True。
![loadmodel](https://user-images.githubusercontent.com/39186017/74259231-8c8d5e80-4d32-11ea-85aa-06aa7367ad7d.jpg)

但是在前向传播的时候，即是运行ex.extract()这个函数时，在PC端的返回值是0，在安卓端的返回值是-1。
很迷惑，一样的代码一样大小的输入，一样的模型没有经过丝毫变动，为啥安卓端前向传播会出现-1

**Comment by CheungBH** [comment]
然后还看了一下，第一层开始就已经返回-1了。
![-1](https://user-images.githubusercontent.com/39186017/74296849-fb44d900-4d7f-11ea-82ea-c280d28ca775.jpg)

我之前那个demo是对加密模型文件进行读取的（“param.bin”文件），我在想模型文件的加载会不会有什么不同？

**Comment by nihui** [comment]
param 和 param.bin 加载接口是不一样的，具体可以看
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-alexnet.zh#%E5%8A%A0%E8%BD%BD%E6%A8%A1%E5%9E%8B

**Comment by CheungBH** [comment]
嗯嗯，我检查的一下接口，用的接口确实是对的，应该是其他的问题吧..

**Comment by nihui** [comment]
另外，如果是 asset 加载模型，建议参考 https://github.com/nihui/ncnn-android-squeezenet

**Comment by CheungBH** [comment]
唔，其实不是找不到参考demo的问题。事实上，我就是参考你们的demo的：https://github.com/chehongshu/ncnnforandroid_objectiondetection_Mobilenetssd。
那里确实是用asset加载的demo，我也我能够成功复现它。与此同时，我也能够在PC端复现你们的simplepose的demo。
问题是我按照你们那个mobilenetssd的安卓demo来复现simplepose的PC端demo的时候，我保持模型一样，输入维度一样，就直接输出为空了。

**Comment by nihui** [comment]
我看了你的代码，接口用的不对，推荐用 https://github.com/nihui/ncnn-android-squeezenet 的写法
```
AAssetManager* mgr = AAssetManager_fromJava(env, assetManager);
ncnn_net.load_param(mgr, "pose.param");
ncnn_net.load_model(mgr, "pose.bin");
```

如果你一定要用内存数据加载明文param，应该用 ncnn_net.load_param_mem()

**Comment by yuanlisha** [comment]
@CheungBH 您好，请问您的这个问题解决了吗，我也遇到和您同样的问题了

**Comment by yuanlisha** [comment]
> 我看了你的代码，接口用的不对，推荐用 https://github.com/nihui/ncnn-android-squeezenet 的写法
> 
> ```
> AAssetManager* mgr = AAssetManager_fromJava(env, assetManager);
> ncnn_net.load_param(mgr, "pose.param");
> ncnn_net.load_model(mgr, "pose.bin");
> ```
按照您推荐的方法导入模型，ncnn_net.load_param总是出现函数不匹配问题，请问怎么解决了

**Comment by yuanlisha** [comment]
> 我看了你的代码，接口用的不对，推荐用 https://github.com/nihui/ncnn-android-squeezenet 的写法
> 
> ```
> AAssetManager* mgr = AAssetManager_fromJava(env, assetManager);
> ncnn_net.load_param(mgr, "pose.param");
> ncnn_net.load_model(mgr, "pose.bin");
> ```
@nihui 按照您说的方法导入模型，ncnn_net.load_param和ncnn_net.load_model总是出现函数不匹配问题，请问怎么解决了
