### ISSUE TITLE
Same commits, same inputs, different archs -> different results

### ISSUE THREAD

**Issue by sebastianfelipe** [Tencent/ncnn#1532]
Hi!

I'm facing a real problem here. I have a NanoPi Neo4 and already compiled everything. Right now I realised that it produces different outputs for same inputs. For example, mobilenetv2_yolov3, it behaves different on my iMac and on NanoPi it generates a lot of false positives, using 352 (original) scale.

I know that there is a possibility that the processors have different operations internally, but, there's a lot of differences, too much.

Thanks!
Sebastián.

**Comment by nihui** [comment]
please provide your param file

**Comment by sebastianfelipe** [comment]
[mobilenetv2_yolov3.param.zip](https://github.com/Tencent/ncnn/files/4208613/mobilenetv2_yolov3.param.zip)

This one, is the same you provide in your examples. No modification added.

**Comment by sebastianfelipe** [comment]
Original
![subject-0](https://user-images.githubusercontent.com/6192023/74590466-6f37e900-4fed-11ea-8633-ede091bc184d.jpg)

But then in NanoPi Neo4 (aarch64) it detects
![2020-02-15 12 20 27](https://user-images.githubusercontent.com/6192023/74590479-942c5c00-4fed-11ea-87b3-5f9eb4cdd6ae.jpg)

And in OSX or Linux, it is empty as it should. I tried it with 352, the original param configuration.

Thanks.

**Comment by nihui** [comment]
hello, I just tested the yolov3 example with your input image and some other images on my pc and android phone, and I didn't find any major difference in the output.

https://github.com/Tencent/ncnn/blob/master/examples/yolov3.cpp
https://github.com/nihui/ncnn-assets/tree/master/models

Try updating to the latest ncnn code and check if the image decoding on Nanopi makes difference RGB.

**Comment by sebastianfelipe** [comment]
Well, is the same code tho, how can I check whether the Nanopi is making some RGB difference? For now, gonna try using the latest commit and gonna get the result. Thanks.

**Comment by sebastianfelipe** [comment]
With the latests commits cannot compile ncnn well. It throws this new error when I compile with examples included.

![Screenshot 2020-02-17 15 44 35](https://user-images.githubusercontent.com/6192023/74679396-7d783780-519c-11ea-983a-e41cd7212144.png)

**Comment by sebastianfelipe** [comment]
I already tested with the last commit. Here is the result:
15 = 0.30509 at 344.37 197.29 93.29 x 133.58

![output](https://user-images.githubusercontent.com/6192023/74685056-2d08d600-51ac-11ea-9453-71fe6d526ba0.png)

Issue is alive.

**Comment by nihui** [comment]
Thanks for your report and testing.
There may be some bug in old code...
A new version release will be issued soon.
