### ISSUE TITLE
如何在ncnn中添加padding

### ISSUE THREAD

**Issue by philp123** [Tencent/ncnn#1533]
在用caffe模型到ncnn转换过程中，出现了如下问题：

caffe中的网络结构
layer {
  name: "input"
  type: "Input"
  top: "data"
  input_param {
    shape {
      dim: 1
      dim: 3
      dim: 112
      dim: 96
    }
  }
}
layer {
  name: "conv1_1"
  type: "Convolution"
  bottom: "data"
  top: "conv1_1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    stride: 2
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0
    }
  }
}

对应生成的ncnn网络结构：
const int LAYER_input = 0;
const int BLOB_data = 0;
const int LAYER_conv1_1 = 1;
const int BLOB_conv1_1 = 1;

输入都是batch=1,channel=3,height=112,width=96，caffe经过一层卷积变成batch=1,channel=64,height=56,width=48，但是ncnn输出的结果channel=64,height=55,width=47，也就是特征图长宽相比于caffe各少了一个像素，这应该是由于没有padding导致的吧，请问一下该如何操作才能使得caffe与ncnn卷积后的特征图一致?

**Comment by nihui** [comment]
请提供下你转换出来的 param 文件
pad参数应该是自动padding的，可能是别的地方有问题

**Comment by philp123** [comment]
[sphereface.tar.gz](https://github.com/Tencent/ncnn/files/4211373/sphereface.tar.gz)

**Comment by philp123** [comment]
还有一个问题，在caffe里面用resnet之后，两个分支通道数不变，而ncnn里面的split_ncnn却变成了原来的一半
caffe输出的通道数
![1](https://user-images.githubusercontent.com/49138243/74617202-f8bef680-5166-11ea-9e88-e227ad2063a1.jpg)
![2](https://user-images.githubusercontent.com/49138243/74617215-ffe60480-5166-11ea-960f-2c950f758f19.jpg)
![3](https://user-images.githubusercontent.com/49138243/74617218-01afc800-5167-11ea-8b98-7968bd922916.jpg)

而在android里面
const int BLOB_conv1_1_relu1_1_splitncnn_0 = 3;
const int BLOB_conv1_1_relu1_1_splitncnn_1 = 4;
显示的特征图长宽为23和27，如果添加padding正好是BLOB_conv1_1_relu1_1的一般。

相当于是说caffe经过relu1_1的resnet后，两支特征图长宽不变，但是ncnn长宽各变成relu1_1的1/2，是因为实现的不同么，如果要变成和caffe模型完全一致，该如何操作呢

**Comment by philp123** [comment]
> 请提供下你转换出来的 param 文件
> pad参数应该是自动padding的，可能是别的地方有问题

[sphereface.tar.gz](https://github.com/Tencent/ncnn/files/4211524/sphereface.tar.gz)

**Comment by philp123** [comment]
> 还有一个问题，在caffe里面用resnet之后，两个分支通道数不变，而ncnn里面的split_ncnn却变成了原来的一半
> caffe输出的通道数
> ![1](https://user-images.githubusercontent.com/49138243/74617202-f8bef680-5166-11ea-9e88-e227ad2063a1.jpg)
> ![2](https://user-images.githubusercontent.com/49138243/74617215-ffe60480-5166-11ea-960f-2c950f758f19.jpg)
> ![3](https://user-images.githubusercontent.com/49138243/74617218-01afc800-5167-11ea-8b98-7968bd922916.jpg)
> 
> 而在android里面
> const int BLOB_conv1_1_relu1_1_splitncnn_0 = 3;
> const int BLOB_conv1_1_relu1_1_splitncnn_1 = 4;
> 显示的特征图长宽为23和27，如果添加padding正好是BLOB_conv1_1_relu1_1的一般。
> 
> 相当于是说caffe经过relu1_1的resnet后，两支特征图长宽不变，但是ncnn长宽各变成relu1_1的1/2，是因为实现的不同么，如果要变成和caffe模型完全一致，该如何操作呢

还有一个问题，在caffe里面用resnet之后，两个分支通道数不变，而ncnn里面的split_ncnn却变成了原来的一半
caffe输出的通道数
![1](https://user-images.githubusercontent.com/49138243/74617202-f8bef680-5166-11ea-9e88-e227ad2063a1.jpg)
![2](https://user-images.githubusercontent.com/49138243/74617215-ffe60480-5166-11ea-960f-2c950f758f19.jpg)
![3](https://user-images.githubusercontent.com/49138243/74617218-01afc800-5167-11ea-8b98-7968bd922916.jpg)

而在android里面
const int BLOB_conv1_1_relu1_1_splitncnn_0 = 3;
const int BLOB_conv1_1_relu1_1_splitncnn_1 = 4;
显示的特征图长宽为23和27，如果添加padding正好是BLOB_conv1_1_relu1_1的一般。

相当于是说caffe经过relu1_1的resnet后，两支特征图长宽不变，但是ncnn长宽各变成relu1_1的1/2，是因为实现的不同么，如果要变成和caffe模型完全一致，该如何操作呢

**Comment by nihui** [comment]
试了这个param，输出的shape没有问题啊
out = 48 56 64

另外，splitncnn 也不改变通道数

```
int main()
{
    ncnn::Net net;

    net.load_param("sphereface.param");

    DataReaderFromEmpty dr;
    net.load_model(dr);

    ncnn::Extractor ex = net.create_extractor();

    ncnn::Mat in(96, 112, 3);
    ex.input("data", in);

    ncnn::Mat out;
    ex.extract("conv1_1", out);

    fprintf(stderr, "out = %d %d %d\n", out.w, out.h, out.c);

    return 0;
}
```

**Comment by philp123** [comment]
> 试了这个param，输出的shape没有问题啊
> out = 48 56 64
> 
> 另外，splitncnn 也不改变通道数
> 
> ```
> 
> class DataReaderFromEmpty : public ncnn::DataReader
> {
> public:
>     virtual int scan(const char* format, void* p) const { return 0; }
>     virtual size_t read(void* buf, size_t size) const { memset(buf, 0, size); return size; }
> };
> 
> int main()
> {
>     ncnn::Net net;
> 
>     net.load_param("sphereface.param");
> 
>     DataReaderFromEmpty dr;
>     net.load_model(dr);
> 
>     ncnn::Extractor ex = net.create_extractor();
> 
>     ncnn::Mat in(96, 112, 3);
>     ex.input("data", in);
> 
>     ncnn::Mat out;
>     ex.extract("conv1_1", out);
> 
>     fprintf(stderr, "out = %d %d %d\n", out.w, out.h, out.c);
> 
>     return 0;
> }
> ```

您用的是linux平台吧，我在Android Studio上运行，结果就不对。
![Screenshot from 2020-02-18 09-08-43](https://user-images.githubusercontent.com/49138243/74695313-874a7b00-522e-11ea-9964-d114ee3dfe5d.png)
下面是我从sphereface.param转化后的id.h文件
[sphereface.tar.gz](https://github.com/Tencent/ncnn/files/4216894/sphereface.tar.gz)

**Comment by nihui** [comment]
我是在 linux 上测试的，你也可以先在pc上试试看
另外，从你的截图看，很可能是新的模型文件没有同步到手机上面，extract 的 blob 到后面去了，试试看先卸载app，确保模型和 id.h 配套并更新，重新编译安装下

**Comment by philp123** [comment]
> 我是在 linux 上测试的，你也可以先在pc上试试看
> 另外，从你的截图看，很可能是新的模型文件没有同步到手机上面，extract 的 blob 到后面去了，试试看先卸载app，确保模型和 id.h 配套并更新，重新编译安装下

在pc上测的结果与caffe一致，包括relu1_1，res1_3，最终输出的特征向量维度也与caffe一致，所以说明转换结果正确。但是在android studio上编译，结果还是不对，您说的新模型文件没有同步到手机，该怎么操作呢，我已经把之前app删除，然后重新安装的，还是不对

![Screenshot_2020-02-18_16-02-55](https://user-images.githubusercontent.com/49138243/74715889-6dc62500-5268-11ea-9d36-6e411ce6be40.png)
还是说因为在assets调用的导致不对？但是ncnn-squeezenet例子里面也是同样的调用方法

**Comment by philp123** [comment]
> 我是在 linux 上测试的，你也可以先在pc上试试看
> 另外，从你的截图看，很可能是新的模型文件没有同步到手机上面，extract 的 blob 到后面去了，试试看先卸载app，确保模型和 id.h 配套并更新，重新编译安装下

**Comment by philp123** [comment]
> 我是在 linux 上测试的，你也可以先在pc上试试看
> 另外，从你的截图看，很可能是新的模型文件没有同步到手机上面，extract 的 blob 到后面去了，试试看先卸载app，确保模型和 id.h 配套并更新，重新编译安装下

也实验过不同版本的NDK，包括21,20,19,18,17，也都是同样的结果，说明与NDK版本无关，其他的那只可能是ncnn调用pc内部实现函数与android内部实现函数有差异，所以不知道哪里可能出现此问题

**Comment by nihui** [comment]
看你项目里没有把 squeezenet 去掉
从你blob shape看，你把squeezenet错当做sphereface用了，因为这三个blob shape正好对应squeezenet的输出

建议重新建个新项目做下

**Comment by nihui** [comment]
如果还有问题，可以 reopen issue 继续讨论
