### ISSUE TITLE
安卓上跑不了PC端能跑的网络

### ISSUE THREAD

**Issue by CheungBH** [Tencent/ncnn#1534]
您好，我按example上的例子把simplepose跑通了，并且按https://github.com/chehongshu/ncnnforandroid_objectiondetection_Mobilenetssd
上面的方法把.param和.bin文件部署到安卓上，并且加载模型成功了。

但是安卓端extract函数的返回值是-1，请问这是为什么

**Comment by nihui** [comment]
duplicate of https://github.com/Tencent/ncnn/issues/1531
