### ISSUE TITLE
android studio 工程使用ncnn 静态库，编译出现问题

### ISSUE THREAD

**Issue by zsliaoming** [Tencent/ncnn#1535]
使用android studio 添加 ncnn lib 时，出现
error: undefined reference to '__kmpc_for_static_init_8'
在cmakelist 编译中添加了：
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  -fopenmp")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
编译出来得app 会闪退，怎么解决

**Comment by nihui** [comment]
https://github.com/nihui/ncnn-android-squeezenet
这是个模板工程，可以试试看能不能用，参考下

**Comment by qinb** [comment]
https://stackoverflow.com/questions/59794824/android-app-crash-after-ndk-upgraded-from-20-1-to-21-0 
你看看这个能不能帮到你，我今天也遇到这个问题！
我在Android.mk中修改了这两行，就正常啦。

LOCAL_CFLAGS += -fopenmp -static-openmp
LOCAL_CPPFLAGS += -fopenmp -static-openmp
LOCAL_LDFLAGS += -fopenmp -static-openmp

**Comment by PigletOS** [comment]
感谢大佬！！困扰了我一星期终于找到答案了。。

**Comment by jingth** [comment]
> 使用android studio 添加 ncnn lib 时，出现 error: undefined reference to '__kmpc_for_static_init_8' 在cmakelist 编译中添加了： set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp") set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp") 编译出来得app 会闪退，怎么解决

我也遇到同样的问题，请问您解决了吗？

**Comment by jingth** [comment]
> https://stackoverflow.com/questions/59794824/android-app-crash-after-ndk-upgraded-from-20-1-to-21-0 你看看这个能不能帮到你，我今天也遇到这个问题！ 我在Android.mk中修改了这两行，就正常啦。
> 
> LOCAL_CFLAGS += -fopenmp -static-openmp LOCAL_CPPFLAGS += -fopenmp -static-openmp LOCAL_LDFLAGS += -fopenmp -static-openmp

谢谢，用了您说的方法，解决了闪退的问题。

**Comment by zsliaoming** [comment]
太久了，做的项目，记得在评论有人给我建议，解决了，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月26日(周六) 凌晨0:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/ncnn] android studio 工程使用ncnn 静态库，编译出现问题 (#1535)




  
https://stackoverflow.com/questions/59794824/android-app-crash-after-ndk-upgraded-from-20-1-to-21-0 你看看这个能不能帮到你，我今天也遇到这个问题！ 我在Android.mk中修改了这两行，就正常啦。
 
LOCAL_CFLAGS += -fopenmp -static-openmp LOCAL_CPPFLAGS += -fopenmp -static-openmp LOCAL_LDFLAGS += -fopenmp -static-openmp
  
谢谢，用了您说的方法，解决了闪退的问题。

**Comment by wapping** [comment]
> 使用android studio 添加 ncnn lib 时，出现 error: undefined reference to '__kmpc_for_static_init_8' 在cmakelist 编译中添加了： set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp") set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp") 编译出来得app 会闪退，怎么解决

我把你这两行改成
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp -static-openmp")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp -static-openmp")
```
就可以了。
