### ISSUE TITLE
android studio 采用release版本的静态库，int8结果不正确

### ISSUE THREAD

**Issue by liangkaihuan** [Tencent/ncnn#1536]
大神，你好。我在android studio中用了20200106版本的ncnn静态库，加载了一个目标检测的模型。fp32的模型没有出现问题，换成int8模型之后输出结果不正确，导致后处理出错，app出现闪退。我在ubuntu下面测试过，int8模型跟fp32模型的准确率相差不大，请问这是预编译库的问题吗，要如何调试？

**Comment by nihui** [comment]
下周发个新版本修复它

**Comment by nihui** [comment]
暂时可以用 https://github.com/Tencent/ncnn/releases/tag/20191113 这个版本

**Comment by liangkaihuan** [comment]
我用了20191113版本之后，cpu版本的int8没有问题，但是gpu结果不对。是因为gpu还不支持int8吗？

**Comment by nihui** [comment]
是的，gpu 还不支持 int8

**Comment by liangkaihuan** [comment]
好的，非常感谢up主^_^
