### ISSUE TITLE
Ncnn部署安卓端运行模型的时候出现问题

### ISSUE THREAD

**Issue by heizhuguizu** [Tencent/ncnn#1540]
在android手机上部署最新版本的ncnn运行模型的时候使用cpu可以正确识别，但使用gpu的时候识别错误。部署先前版本（tag20200106）的ncnn运行cpu和gpu都可以正确识别。运行的模型采用https://github.com/nihui/ncnn-assets/tree/master/models的mobilenet_ssd_voc_ncnn。

**Comment by nihui** [comment]
confirmed
