### ISSUE TITLE
ubuntu 编译 android-armv7  vulkan

### ISSUE THREAD

**Issue by lyhehong** [Tencent/ncnn#1541]
执行步骤
$ wget https://sdk.lunarg.com/sdk/download/1.1.92.1/linux/vulkansdk-linux-x86_64-1.1.92.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.1.92.1.tar.gz
$ tar -xf vulkansdk-linux-x86_64-1.1.92.1.tar.gz

# setup env
$ export VULKAN_SDK=`pwd`/1.1.92.1/x86_64

$ mkdir -p build-android-armv7
$ cd build-android-armv7

$ cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON \
    -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..

-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found glslangValidator: /root/1.1.92.1/x86_64/bin/glslangValidator
-- Found OpenMP_C: -fopenmp=libomp (found version "3.1")
-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1")
-- Found OpenMP: TRUE (found version "3.1")
-- Found Vulkan: /root/soft/android-ndk-r18b/platforms/android-24/arch-arm/usr/lib/libvulkan.so
-- Configuring done
-- Generating done
$ make -j4

Scanning dependencies of target generate-spirv
[  0%] Building SPIR-V module absval_fp16p.spv
[  0%] Building SPIR-V module absval_fp16s.spv
[  0%] Building SPIR-V module absval_fp16a.spv
[  0%] Building SPIR-V module absval.spv
SPIR-V is not generated for failed compile or link
src/CMakeFiles/generate-spirv.dir/build.make:1326: recipe for target 'src/absval_fp16a.spv.hex.h' failed
make[2]: *** [src/absval_fp16a.spv.hex.h] Error 2
make[2]: *** Waiting for unfinished jobs....
[  0%] Building SPIR-V module absval_pack4.spv
[  0%] Building SPIR-V module absval_pack4_fp16p.spv
CMakeFiles/Makefile2:128: recipe for target 'src/CMakeFiles/generate-spirv.dir/all' failed
make[1]: *** [src/CMakeFiles/generate-spirv.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nihui** [comment]
You need to upgrade vulkan sdk

**Comment by lyhehong** [comment]
use vulkan_skd version 1.2.131.2  ndk18 compiled ok
ndk16 compile error 
/src/layer/arm/gemm_symm_int8.h:1012:19: error: use of undeclared identifier 'nullptr'
    if (scales == nullptr) {
/src/layer/arm/gemm_symm_int8.h:2697:33: error: use of undeclared identifier 'nullptr'
                bias = (bias == nullptr)? nullptr: bias + 2;

**Comment by nihui** [comment]
feel free to reopen if you encounter other problems
