### ISSUE TITLE
把retinaface迁移到android运行有错

### ISSUE THREAD

**Issue by northeastsquare** [Tencent/ncnn#1546]
ncnn example里面retinaface, 编译到ubuntu16.04运行正常。
编译到android, 通过打印发现，stride32运行正常，但是stride16,stride8两处都会出错，返回-100.
通过ex.extract,对应blob发现crop0的输入，是可以得到的，但是extract输出blob，就会返回-100， 为什么会这样呢？

**Comment by nihui** [comment]
试了下把 example retinaface 直接编译了 android 版本放在手机上跑
gpu能出结果，cpu坏掉了，mnet.25 的模型，我看看

**Comment by nihui** [comment]
修好了，更新代码吧～

**Comment by northeastsquare** [comment]
辛苦您了，能跑了

**Comment by dianxin556** [comment]
请问ncnn下运行retinaface gpu和cpu速度分别如何？谢谢

**Comment by charlie6004** [comment]
retinaface 迁移到android上执行到`ex.extract("output0", out);` 会报`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 7711 (obilenetssdncnn), pid 7711 (obilenetssdncnn)`的错误。然后app会闪退（cpu 和gpu都会如此）。retinaface使用的mnet.25，ncnn-android-vulkan-lib 20200727。是什么原因呢？

**Comment by CharlieXie** [comment]
tombstone如下图
![QQ20200728-0](https://user-images.githubusercontent.com/20149037/88656307-ac5ae800-d102-11ea-806b-0a01fae9cd69.png)
使用addr2line debug获取的信息如下
![QQ20200728-2](https://user-images.githubusercontent.com/20149037/88656444-e3c99480-d102-11ea-937d-a88df1916336.png)

**Comment by charlie6004** [comment]
android studio tombstone 如图
![QQ20200728-0](https://user-images.githubusercontent.com/8241802/88656756-62263680-d103-11ea-994d-3ad3623119fc.png)
使用addr2line debug获得的信息如图
![QQ20200728-2](https://user-images.githubusercontent.com/8241802/88656844-84b84f80-d103-11ea-9b3f-3e252db5dfa0.png)

**Comment by hande6688** [comment]
我参考的是这个demo：https://javis486.blog.csdn.net/article/details/109099941也是retinaface的编译运行在ipad上直接闪退，能帮忙看看是怎么回事吗，下载源码出现找不到ndk，但是添加了ndk还时报错找不到ndk
