### ISSUE TITLE
the latest version is very very slow for mnas model on Intel(R) Xeon(R) CPU E5-2630

### ISSUE THREAD

**Issue by IvyGongoogle** [Tencent/ncnn#1547]
Hello, I got a  problem. When I use the version after 2020, I find the inference speed is very very slow for `mnas` model.  This situation will not happen for the version of 2019 on my same machine.

My cpu: 
`40  Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz`

Can you give some advises?
Thanks.

**Comment by nihui** [comment]
Did you ever enable the NCNN_AVX2 make option in your previous build ?

**Comment by IvyGongoogle** [comment]
@nihui  thanks for your reply. `#define NCNN_AVX2 0` in `platform.h` in previous build

**Comment by nihui** [comment]
Check the num_thread parameter setting and check if multithreading was enabled before
It is recommended to use the latest code and enable NCNN_AVX2 option for your CPU

**Comment by nihui** [comment]
Hi, quite a lot of sse2 and avx2 optimization has been brought into the latest ncnn code.
Try upgrading your ncnn library.
If your problem is still not resolved, then feel free to reopen issue and tell us  :)
