### ISSUE TITLE
ncnn_vulkan版本 vkCreateInstance failed -9

### ISSUE THREAD

**Issue by zys1994** [Tencent/ncnn#1548]
OS:ubuntu16.04
cpu:i3-7100
集显:Intel® HD Graphics 620 (Kaby Lake GT2) 

目前的问题是：
成功安装vulkan-sdk1.2.131，成功编译ncnn_vulkan.  运行benchmark时报错vkCreateInstance failed -9。这个要怎么去解决呢。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan

升级下显卡驱动

**Comment by RaySue** [comment]
OS: Ubuntu 18.04
gpu: TITAN XP
vulkan-sdk-1.2.131.1
同样遇到问题 vkCreateInstance failed -9

**Comment by RaySue** [comment]
> https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan
> 
> 升级下显卡驱动

我看了文档里的问题，和我遇到的不一样
