### ISSUE TITLE
mobilenetv2ssdlite.cpp does not detect on gpu

### ISSUE THREAD

**Issue by takuya-takeuchi** [Tencent/ncnn#1553]
I tried https://github.com/Tencent/ncnn/blob/master/examples/mobilenetv2ssdlite.cpp on linux and windows.
But both windows and linux does not work on gpu.
On cpu, it works fine.

![image](https://user-images.githubusercontent.com/6241854/75146199-ea13a900-573d-11ea-9387-a36025918fe7.png)

I used tag 20200106.
What is wrong?

**Comment by takuya-takeuchi** [comment]
Test image is https://github.com/takuya-takeuchi/NcnnDotNet/raw/master/examples/MobileNetV2SSDLite/dog.jpg

**Comment by nihui** [comment]
Hello, can you try updating to the latest ncnn code and see if this problem is still there.
I wasn't able to reproduce this issue at the moment.

**Comment by takuya-takeuchi** [comment]
@nihui 
Thank you for your quick response.
You are right. Latest commit works fine!!
This issue was my stupid issue. I'm very sorry.
