### ISSUE TITLE
raspberry pi ZeroW Illegal instruction

### ISSUE THREAD

**Issue by jesszgc** [Tencent/ncnn#1554]
build on raspberry pi zeroW successfully. but get bad result while running benchncnn, Can anybody helpe me ,thanks
and make test all failed

**Comment by nihui** [comment]
raspberry pi zero does not support neon instructions
You have to remove the "-mfpu=neon" flags

https://github.com/Tencent/ncnn/blob/7c971425248f8fbe9839ecae268be221149aaede/src/CMakeLists.txt#L290
