### ISSUE TITLE
how to do different kind of rotations 

### ISSUE THREAD

**Issue by philp123** [Tencent/ncnn#1555]
Would you please give an example of how to do different kinds of rotations

![20170401110627973](https://user-images.githubusercontent.com/49138243/75241032-535bf080-5800-11ea-828c-ab6a15436fe1.png)
x rotation 

![20170401110637928](https://user-images.githubusercontent.com/49138243/75241136-869e7f80-5800-11ea-97e1-253ed85b25d5.png)
y rotation

and any other kind of rotations. I've seen in the code, there are some specifications about rotations

#if NCNN_PIXEL_ROTATE
// type is the from type, 6 means rotating from 6 to 1
//
//     1        2       3      4         5            6           7          8
//
//   888888  888888      88  88      8888888888  88                  88  8888888888
//   88          88      88  88      88  88      88  88          88  88      88  88
//   8888      8888    8888  8888    88          8888888888  8888888888          88
//   88          88      88  88
//   88          88  888888  888888
//
// ref http://sylvana.net/jpegcrop/exif_orientation.html
// image pixel kanna rotate
void kanna_rotate_c1(const unsigned char* src, int srcw, int srch, unsigned char* dst, int w, int h, int type);
void kanna_rotate_c2(const unsigned char* src, int srcw, int srch, unsigned char* dst, int w, int h, int type);
void kanna_rotate_c3(const unsigned char* src, int srcw, int srch, unsigned char* dst, int w, int h, int type);
void kanna_rotate_c4(const unsigned char* src, int srcw, int srch, unsigned char* dst, int w, int h, int type);
// image pixel kanna rotate with stride(bytes-per-row) parameter
void kanna_rotate_c1(const unsigned char* src, int srcw, int srch, int srcstride, unsigned char* dst, int w, int h, int stride, int type);
void kanna_rotate_c2(const unsigned char* src, int srcw, int srch, int srcstride, unsigned char* dst, int w, int h, int stride, int type);
void kanna_rotate_c3(const unsigned char* src, int srcw, int srch, int srcstride, unsigned char* dst, int w, int h, int stride, int type);
void kanna_rotate_c4(const unsigned char* src, int srcw, int srch, int srcstride, unsigned char* dst, int w, int h, int stride, int type);
// image pixel kanna rotate, convenient wrapper for yuv420sp(nv21)
void kanna_rotate_yuv420sp(const unsigned char* src, int srcw, int srch, unsigned char* dst, int w, int h, int type);
#endif // NCNN_PIXEL_ROTATE

But I could not use this method(ncnn-android-vulkan-lib was used) in Android Studio jni, do I need to recompile from source code?

Thanks for your reply.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/issues/1506

**Comment by philp123** [comment]
> #1506
> 
> documentation is lacking, sorry

Thanks for your reply, but the sample is in gray format, how to do that in color format. I know it could be possible to split 3 channels and kanna_rotate_c1 separately. But is there any faster or cleaner way to do that(e.g. using one line code)?

Also, would you please give an example in Android(Mat extracted from bitmap), 
ncnn::Mat in = ncnn::Mat::from_android_bitmap(env, bitmap, ncnn::Mat::PIXEL_BGR);

That would be very kind, Best Regards.

**Comment by nihui** [comment]
```
cv::Mat a = cv::imread("a.jpg", CV_LOAD_IMAGE_COLOR);
int w = a.cols;
int h = a.rows;

// rotate from 7 to 1
int outw = h;
int outh = w;
cv::Mat b(outh, outw, CV_8UC3);

kanna_rotate_c3(a.data, w, h, b.data, outw, outh, 7);

cv::imwrite("b.jpg", b);
```

**Comment by philp123** [comment]
> ```
> cv::Mat a = cv::imread("a.jpg", CV_LOAD_IMAGE_COLOR);
> int w = a.cols;
> int h = a.rows;
> 
> // rotate from 7 to 1
> int outw = h;
> int outh = w;
> cv::Mat b(outh, outw, CV_8UC3);
> 
> ncnn::kanna_rotate_c3(a.data, w, h, b.data, outw, outh, 7);
> 
> cv::imwrite("b.jpg", b);
> ```

Indeed, when converting  opencv mat with ncnn::kanna_rotate_c3, everything is fine. But when converting ncnn::Mat with ncnn::kanna_rotate_c3, everything crashes accidentally. Here is the implementation code.  

	cv::Mat img = cv::imread("mmexport1581500289347.jpg", CV_LOAD_IMAGE_COLOR);
	int width = img.cols;
	int height = img.rows;
	ncnn::Mat in = ncnn::Mat::from_pixels(img.data, ncnn::Mat::PIXEL_BGR, width, height);

	//pretty_print(in);   //print with float, value is correct. 

        ncnn::Mat in_flip(in.h, in.w);
        ncnn::kanna_rotate_c3((const unsigned char *)in.data, in.w, in.h, (unsigned char *)in_flip.data, in_flip.w, in_flip.h, 2);

	pretty_print(in_flip);  //incorrect

	cv::Mat cv_img = cv::Mat::zeros(in_flip.h,in_flip.w,CV_8UC3);
	in_flip.to_pixels(cv_img.data,ncnn::Mat::PIXEL_RGB);
	cv::imwrite("/home/liuwenjie/Project/ncnn_flip/mmexport1581500289347_flip.jpg", cv_img);

ncnn::kanna_rotate_c3 requires const unsigned char* but ncnn::Mat is float, maybe this is the problem. 

Output value for in_flip
![Screenshot_2020-02-26_18-00-24](https://user-images.githubusercontent.com/49138243/75334015-19532300-58c2-11ea-9c23-f10de4280243.png)

**Comment by nihui** [comment]
kannarotate famliy only accepts uchar data

If you want to rotate a Mat, rotate the original image first, and then construct the Mat object from the rotated image

It is possible to implement a rotate function for Mat (use the kannarotate c4 version on each channel in Mat), but for maximum speed, it is recommended to apply rotation on the original image, because it is much faster to process the uchar data than the float data in Mat.

**Comment by YIFanH** [comment]
@nihui hi, crash happend with **rotate_4_c4 fuction，which is not necessary and input data is aligned, thanks for your replay

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/6233
