### ISSUE TITLE
onnx2ncnn Segmentation fault,gdb 调试无法看到文件和行号

### ISSUE THREAD

**Issue by lawo123** [Tencent/ncnn#1556]
![image](https://user-images.githubusercontent.com/44777088/75312155-0cb7d600-5894-11ea-9bf7-f584b9750ddf.png)

**Comment by lawo123** [comment]
@nihui

**Comment by nihui** [comment]
please provide your onnx file

**Comment by lawo123** [comment]
> please provide your onnx file

这是我的onnx文件和sim onnxfile。
[onnx_file.zip](https://github.com/Tencent/ncnn/files/4254128/onnx_file.zip)

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
修好了

**Comment by lawo123** [comment]
成功了，多谢

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
