### ISSUE TITLE
mxnet转到ncnn不需要transpose吗

### ISSUE THREAD

**Issue by northeastsquare** [Tencent/ncnn#1560]
在mxnet程序里面，inference时候要
`data = data.transpose((2,0,1)).expand_dims(axis=0)`

可是转换到ncnn模型后，如下操作，没有tranpose，就可以得到正确结果，奇怪的事情，mxnet里面tranpose、归一化以后，输出，和ncnn如下操作后，vscode调试看网络输入图片，竟然是一样的。为什么呢？难道from_pixels_resize，里面做了transpose?
`    

    ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_BGR2RGB, bgr.cols, bgr.rows, 128, 128);
    ncnn::Mat in2;
    const float mean_vals[3] = {0.485f*255.f, 0.456f*255.f, 0.406f*255.f};
    const float norm_vals[3] = {1/0.229f/255.f, 1/0.224f/255.f, 1/0.225f/255.f};
    in.substract_mean_normalize(mean_vals, norm_vals);
    //transpose(in, in2);
    ncnn::Extractor ex = mnet.create_extractor();
    ex.input("data", in);`

**Comment by nihui** [comment]
指定 ncnn::Mat::PIXEL_BGR2RGB 参数会自动转换 RGB/BGR

**Comment by northeastsquare** [comment]
载入的图片是hwc的，ncnn::Mat::PIXEL_BGR2RGB自动转成chw了吗？

**Comment by nihui** [comment]
是的，RGBRGB 自动转为 RRR GGG BBB
