### ISSUE TITLE
ncnn with vulkan --> nvdc: nvdcEventThread select failed: Bad file descriptor

### ISSUE THREAD

**Issue by ghimiredhikura** [Tencent/ncnn#1561]
NCNN with Vulkan: I got this message while trying to execute example with vulcan in NVIDIA Jetson Nano. I followed this instruction in order to build ncnn with vulkan: https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-nvidia-jetson

Test example with output: detection result is fine but with error message regarding nvdcEventThread. I am wondering is my device using GPU or not? 

```
ghimire@ghimire:~/ncnn/build/examples$ ./retinaface faces.jpg
[0 NVIDIA Tegra X1 (nvgpu)]  queueC=0[16]  queueG=0[16]  queueT=0[16]  buglssc=0
[0 NVIDIA Tegra X1 (nvgpu)]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
nvdc: start nvdcEventThread
nvdc: nvdcEventThread select failed: Bad file descriptor
1.00000 at 305.84 766.30 244.91 x 316.35
0.99805 at 1268.22 403.23 137.21 x 174.13
0.99805 at 994.96 178.39 134.77 x 180.02
0.99707 at 1050.96 366.47 127.96 x 157.73
0.99707 at 740.11 764.73 252.11 x 305.27
0.99512 at 717.05 32.50 121.27 x 143.45
```
![ncnn_vulkan_result](https://user-images.githubusercontent.com/24696403/75517736-87652a80-5a27-11ea-9ebe-5e5887192c95.png)

**Comment by nihui** [comment]
Run benchncnn with very large loopcount
At the same time, run nvidia-smi and check if benchncnn is in the list

**Comment by ghimiredhikura** [comment]
@nihui 

Thanks for quick reply. Its Jetson Nano so nvidia-smi is not available. However running benchncnn I got following output: 
```
ghimire@ghimire:~/ncnn_vulkan/build/benchmark$ ./benchncnn 10 4 0
[0 NVIDIA Tegra X1 (nvgpu)]  queueC=0[16]  queueG=0[16]  queueT=0[16]  buglssc=0
[0 NVIDIA Tegra X1 (nvgpu)]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
loop_count = 10
num_threads = 4
powersave = 0
gpu_device = -1
          squeezenet  min =   30.78  max =   31.48  avg =   31.06
     squeezenet_int8  min =   37.79  max =  132.16  avg =   47.52
           mobilenet  min =   40.72  max =   50.53  avg =   42.00
```

**Comment by nihui** [comment]
That indicates the gpu is actually used
You see that it runs even faster than 4-cpu cores.

**Comment by ghimiredhikura** [comment]
Yes, it looks great. 
However, I am still wondering why this message is there while testing retinaface example. 
```
nvdc: nvdcEventThread select failed: Bad file descriptor
```

**Comment by nihui** [comment]
I have no idea about this error message, it may be an internal issue of the vulkan driver

A rough search gives me a gfx-rs issue
https://github.com/gfx-rs/gfx/issues/3116

It may be related on how the vulkan instance is created because it did not appear in your benchncnn output.

Is it only occurs in retinaface example ? How about the other ncnn examples ?

**Comment by nihui** [comment]
just ignore warning message atm  :D
