### ISSUE TITLE
量化性能变差接近一倍

### ISSUE THREAD

**Issue by houjuan890410** [Tencent/ncnn#1562]
android手机跑mobilenet_v1模型，fp32的性能比量化的性能好1倍。
难道是姿势不对？ 
mnn测试也发现int8模型性能恶化.

求大神解答

**Comment by nihui** [comment]
那是因为fp32跑得太快了 ...

**Comment by nihui** [comment]
只有 tflite 这种 fp32 跑得慢的框架，才能很好的体现出 int8 量化的加速效果（
