### ISSUE TITLE
请问ncnn在linux、android、ios系统的推理时间和精度有差别吗？我在做测试的时候是否只验证其中一个平台的推理时间和精度就可以了呢？

### ISSUE THREAD

**Issue by lawo123** [Tencent/ncnn#1565]
@nihui

**Comment by nihui** [comment]
不同平台的时间肯定是不同的，要分别测试
不同平台精度上会有运算误差，但非常小可以不管，如果结果完全不一致就是bug

**Comment by lawo123** [comment]
> 不同平台的时间肯定是不同的，要分别测试
> 不同平台精度上会有运算误差，但非常小可以不管，如果结果完全不一致就是bug

好的。多谢
