### ISSUE TITLE
pytorch2ncnn后分割结果差很多怎么回事？

### ISSUE THREAD

**Issue by lawo123** [Tencent/ncnn#1567]
![pytorch](https://user-images.githubusercontent.com/44777088/75608211-81ab3a00-5b38-11ea-980c-fadd5950b01c.JPG)
![ncnn](https://user-images.githubusercontent.com/44777088/75608212-8243d080-5b38-11ea-914a-be49b21aa680.png)
这是pytorch分割的结果和ncnn分割的结果，检查了预处理和后处理都没问题，为什么结果差这么多？请问还应该怎么定位呢？
`// Tencent is pleased to support the open source community by making ncnn available.
//
// Copyright (C) 2017 THL A29 Limited, a Tencent company. All rights reserved.
//
// Licensed under the BSD 3-Clause License (the "License"); you may not use this file except
// in compliance with the License. You may obtain a copy of the License at
//
// https://opensource.org/licenses/BSD-3-Clause
//
// Unless required by applicable law or agreed to in writing, software distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

#include <stdio.h>
#include <algorithm>
#include <vector>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/opencv.hpp>

#include "platform.h"
#include "net.h"
#if NCNN_VULKAN
#include "gpu.h"
#endif // NCNN_VULKAN

#define INPUT_WIDTH     512
#define INPUT_HEIGHT    512

static int detect_squeezenet(const cv::Mat& bgr, std::vector<float>& cls_scores)
{
    ncnn::Net espnet;

#if NCNN_VULKAN
    espnet.opt.use_vulkan_compute = true;
#endif // NCNN_VULKAN

    espnet.load_param("espnetv2.param");
    espnet.load_model("espnetv2.bin");
    cv::Mat tmp;
    cv::Mat tmp1;
    cv::resize(bgr, tmp, cv::Size(INPUT_WIDTH, INPUT_HEIGHT));
    cvtColor(tmp,tmp1,CV_BGR2RGB);
    ncnn::Mat in = ncnn::Mat::from_pixels(tmp1.data,ncnn::Mat::PIXEL_RGB, tmp1.cols, tmp1.rows);
//    ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_BGR2RGB, bgr.cols, bgr.rows, 512, 512);
    const float mean_vals[3] = {0.485*255.f, 0.456*255.f, 0.406*255.f};
    const float mean_stds[3] = {1/0.229f/255.f, 1/0.224f/255.f, 1/0.225f/255.f};

    in.substract_mean_normalize(mean_vals, mean_stds);

    ncnn::Extractor ex = espnet.create_extractor();

    ex.input("input.1", in);

    ncnn::Mat out;
    ex.extract("1294", out);
    fprintf(stderr, "%d = %d\n", out.c, out.w);

    cv::Mat cv_img = cv::Mat::zeros(out.w,out.h,CV_8UC1);
    float *srcdata = (float*)out.data;
    unsigned char *data = cv_img.data;

    for (int i = 0; i < out.h; i++)
       for (int j = 0; j < out.w; j++)
       {
         float tmp = srcdata[0*out.w*out.h+i*out.w+j];
         int maxk = 0;
         for (int k = 0; k < out.c; k++)
         {
           if (tmp < srcdata[k*out.w*out.h+i*out.w+j])
           {
                tmp = srcdata[k*out.w*out.h+i*out.w+j];
                maxk = k;
           }
//            fprintf(stderr, "%f\n", srcdata[k*out.w*out.h+i*out.w+j]);

         }
         data[i*out.w + j] = maxk;
       }

    cv_img *= 255;
    cv::imshow("test", cv_img);
    cv::waitKey();

    return 0;
}

static int print_topk(const std::vector<float>& cls_scores, int topk)
{
    // partial sort topk with index
    int size = cls_scores.size();
    std::vector< std::pair<float, int> > vec;
    vec.resize(size);
    for (int i=0; i<size; i++)
    {
        vec[i] = std::make_pair(cls_scores[i], i);
    }

    std::partial_sort(vec.begin(), vec.begin() + topk, vec.end(),
                      std::greater< std::pair<float, int> >());

    // print topk and score
    for (int i=0; i<topk; i++)
    {
        float score = vec[i].first;
        int index = vec[i].second;
        fprintf(stderr, "%d = %f\n", index, score);
    }

    return 0;
}

int main(int argc, char** argv)
{
    if (argc != 2)
    {
        fprintf(stderr, "Usage: %s [imagepath]\n", argv[0]);
        return -1;
    }

    const char* imagepath = argv[1];

    cv::Mat m = cv::imread(imagepath, 1);
    if (m.empty())
    {
        fprintf(stderr, "cv::imread %s failed\n", imagepath);
        return -1;
    }

#if NCNN_VULKAN
    ncnn::create_gpu_instance();
#endif // NCNN_VULKAN

    std::vector<float> cls_scores;
    detect_squeezenet(m, cls_scores);

#if NCNN_VULKAN
    ncnn::destroy_gpu_instance();
#endif // NCNN_VULKAN

//    print_topk(cls_scores, 3);

    return 0;
}
`

**Comment by lawo123** [comment]
@nihui

**Comment by nihui** [comment]
有这些问题
1. cv::Mat 构造不是 w h，应该是 h w
2. 遍历 out 应该用 out.channel(k).row(i)[j] 访问，直接读 data 可能会有 channel gap 的问题
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#blob-may-have-channel-gap
3. 乘255应该在 out 上做，而不是在 8UC1 cv_img 上做

输出图的转换可以参考 https://github.com/Tencent/ncnn/wiki/use-ncnn-with-opencv

**Comment by lawo123** [comment]
感谢回复，我对您指出的问题进行了一些修改，但是结果还是一样的。
`ncnn::Net espnet;

#if NCNN_VULKAN
    espnet.opt.use_vulkan_compute = true;
#endif // NCNN_VULKAN

    espnet.load_param("espnetv2.param");
    espnet.load_model("espnetv2.bin");

    ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_BGR2RGB, bgr.cols, bgr.rows, 512, 512);
    const float mean_vals[3] = {0.485*255.f, 0.456*255.f, 0.406*255.f};
    const float mean_stds[3] = {1/0.229f/255.f, 1/0.224f/255.f, 1/0.225f/255.f};

    in.substract_mean_normalize(mean_vals, mean_stds);

    ncnn::Extractor ex = espnet.create_extractor();

    ex.input("input.1", in);

    ncnn::Mat out;
    ex.extract("1294", out);
    fprintf(stderr, "%d = %d\n", out.c, out.w);

    cv::Mat cv_img = cv::Mat::zeros(out.h,out.w,CV_8UC1);
    unsigned char *data = cv_img.data;

    for (int i = 0; i < out.h; i++)
       for (int j = 0; j < out.w; j++)
       {
         float tmp = out.channel(0).row(i)[j];
         int maxk = 0;
         for (int k = 0; k < out.c; k++)
         {
           if (tmp < out.channel(k).row(i)[j])
           {
                tmp = out.channel(k).row(i)[j];
                maxk = k *255;
           }
         }
         data[i*out.w + j] = maxk;
       }

    cv::imshow("test", cv_img);
    cv::waitKey();`

**Comment by caishanli** [comment]
可以试一下ncnn的python接口，这样可以在保持原来python pytorch的前处理和后处理不变的情况排查问题

**Comment by lawo123** [comment]
> 可以试一下ncnn的python接口，这样可以在保持原来python pytorch的前处理和后处理不变的情况排查问题

感谢您的回复，请问ncnn的python接口是在哪呢？我没有看到python接口啊

**Comment by caishanli** [comment]
> > 可以试一下ncnn的python接口，这样可以在保持原来python pytorch的前处理和后处理不变的情况排查问题
> 
> 感谢您的回复，请问ncnn的python接口是在哪呢？我没有看到python接口啊

https://github.com/caishanli/pyncnn

**Comment by lawo123** [comment]
> > > 可以试一下ncnn的python接口，这样可以在保持原来python pytorch的前处理和后处理不变的情况排查问题
> > 
> > 
> > 感谢您的回复，请问ncnn的python接口是在哪呢？我没有看到python接口啊
> 
> https://github.com/caishanli/pyncnn

多谢
