### ISSUE TITLE
INT8 model performance on Android slower than fp32 

### ISSUE THREAD

**Issue by DeleOgunjumelo** [Tencent/ncnn#1574]
Please, could you confirm if INT8 inference times are expected to be slower than that of FP32? I have recently ran a recent version of TencentNCNN performance tests on an Android device and i got the following results:- 

adb shell cd /data/local/tmp/tencent && ./benchncnn 10 4 0 -1
loop_count = 10
num_threads = 4
powersave = 0
gpu_device = -1
          squeezenet           min =   28.90  max =   29.96  avg =   29.27
          squeezenet_int8   min =   42.09  max =   48.68  avg =   43.67
          mobilenet              min =   42.47  max =   48.91  avg =   44.25
          mobilenet_int8      min =  110.76  max =  120.27  avg =  113.62
          resnet18                min =   87.20  max =   95.31  avg =   90.08
          resnet18_int8        min =  133.98  max =  140.59  avg =  135.91
          vgg16                    min =  471.45  max =  505.06  avg =  489.83
          vgg16_int8            min =  819.01  max =  945.47  avg =  838.20
          resnet50                min =  215.05  max =  223.05  avg =  217.78
          resnet50_int8        min =  319.33  max =  330.32  avg =  322.33

Is there a build flag or such for optimizing INT8 performance?

Environment -
 - Tencent NCNN Version: v20200226
-   OS : Andriod 9. 0 /   arm64-v8a

**Comment by nihui** [comment]
Because I often optimize the speed of fp32 inference, the int8 part lacks deeper optimization.
You can try enabling the NCNN_REQUANT cmake option, it will bring some benefits. Do not give it to much expectation.

**Comment by tpoisonooo** [comment]
INT8 inference is mostly contributed by part-time contributors whose life full-filled with realistic factor ... the most important thing is ... nihui is single and being single is productive ... maybe.

**Comment by DeleOgunjumelo** [comment]
Thanks for the explanation and suggestion about using NCNN_REQUANT.
