### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by xieydd** [Tencent/ncnn#1575]
I  notice convolution class  have not `use_int8_inference` member, in https://github.com/Tencent/ncnn/blob/master/src/net.cpp#L766， is that a bug? 
When i compile with `cmake -DNCNN_REQUANTIZE=ON ..`, it will be wrong.

@nihui

**Comment by nihui** [comment]
shall be fixed since https://github.com/Tencent/ncnn/commit/52ce59e6727e5be4b57d0c6ccf5e0b92b9f5561b

**Comment by xieydd** [comment]
👌
