### ISSUE TITLE
How to descale int8 weight to fp32?

### ISSUE THREAD

**Issue by IvyGongoogle** [Tencent/ncnn#1577]
I meet a problem...
First, as the size of my fp32 model `modelA_fp32` is big, so I  use ncnn quantize tools  to quatize it to int8 model `modelA_int8`, but I find the in8 inference speed is four times slows than fp32 using android armv7 and armv8. So I want to descale my `modelA_int8` to `modelA_fp32` after loading model, and then use fp32 infernce. How to do this?  

Thanks.

**Comment by nihui** [comment]
I don't think your usecase is supported currently.
If you only need to compress your model binary, it will be more suitable to use fp16 storage, while maintaining high accuracy.
That could be achieved via "ncnnoptimize xyz.param xyz.bin xyz-opt.param xyz-opt.bin 65536"

**Comment by IvyGongoogle** [comment]
@nihui sorry, in many cases fp16 storage is still large.  Now, I directly use int8 weight_data to divide corresponding float `scales`, but meet some problem. I find some float `scales` value is 0, or very large like `-1142198143503311241119761862492160.00000000`.

**Comment by IvyGongoogle** [comment]
finally, this method can work, but with some prob loss
