### ISSUE TITLE
不能正确解析onnx: conv2d 为 conv_dw

### ISSUE THREAD

**Issue by cvwoker** [Tencent/ncnn#1579]
如图，这种情况怎么改

![onnx_ncnn](https://user-images.githubusercontent.com/30815640/75864552-28475180-5e3d-11ea-9892-b1e741a45fc0.png)

**Comment by nihui** [comment]
请上传有问题的onnx以便分析

**Comment by cvwoker** [comment]
[erfnet_sim.zip](https://github.com/Tencent/ncnn/files/4290523/erfnet_sim.zip)

**Comment by nihui** [comment]
这个似乎是 netron 显示的问题，netron 没有正确读取非正方形的 kernel shape
但是 ncnn 的 parma bin 内容是正常的

**Comment by cvwoker** [comment]
谢谢

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
