### ISSUE TITLE
So问题请教

### ISSUE THREAD

**Issue by enduringstack** [Tencent/ncnn#158]
使用下面的命令编译出了32位的libncnn.a静态库：
cmake -DCMAKE_TOOLCHAIN_FILE=../android.toolchain.cmake 
           -DANDROID_ABI="armeabi-v7a with NEON" 
           -DANDROID_NATIVE_API_LEVEL=android-21
           -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9     
           -DANDROID_STL_FORCE_FEATURES=OFF ..

那么使用这个32位的libncnn.a静态库可以编译生成64位的ncnn.so库吗？

**Comment by nihui** [comment]
不能，需要再编译一个，参考 ncnn/build.sh
