### ISSUE TITLE
what is the input layout of func "conv_im2col_sgemm_transform_kernel_sse" and "conv_im2col_sgemm_sse"

### ISSUE THREAD

**Issue by xu78guo6** [Tencent/ncnn#1580]
Hello, I'm trying to understand the method in this two function "conv_im2col_sgemm_transform_kernel_sse" and "conv_im2col_sgemm_sse", feeling a little confused about layout of input data, does it accept OIHW layout in "conv_im2col_sgemm_transform_kernel_sse" and NCHW in "conv_im2col_sgemm_sse"?

**Comment by nihui** [comment]
yep, We have re-implemented this part of the code in the latest version
