### ISSUE TITLE
当分组卷积，不是depthwise时，这一层输出的结果完全不对，

### ISSUE THREAD

**Issue by dangxusheng** [Tencent/ncnn#1581]
我 做过实验，
实验1： pytorch到ncnn， 只要涉及到分组卷积，但不是depthwise，这层卷积输出结果就不对了，但如果是depthwise时就没问题

实验2： caffemodel到ncnn，也是一样的现象。

只要中间一旦不对，其结果就完全不对，我测试的是简单分类。

我自己大概看了下convolutiondepthwise.cpp， 没发现哪里不对。
希望官方检查下src代码。
我用前两天最新的版本build后测试也是一样

**Comment by nihui** [comment]
请提供有问题的 onnx 或 caffemodel

alexnet shufflenet 都是有分组卷积的，没发现有什么问题
https://github.com/pytorch/vision/blob/master/torchvision/models/shufflenetv2.py

**Comment by dangxusheng** [comment]
[mnist_classifer.zip](https://github.com/Tencent/ncnn/files/4287990/mnist_classifer.zip)

这里是pytorch 的model， onnx，  和 ncnn，  在group conv之前的层输出在pytorch和ncnn两端都是基本一样的，过了group conv之后就不一样了.
 
请验证。

**Comment by dangxusheng** [comment]
如果是depthwise 是没问题的， 但这里只是普通的group conv,  在pytorch和ncnn的输出就不一致了，

**Comment by nihui** [comment]
reproduced

**Comment by dangxusheng** [comment]
你们验证了吗，这个问题确实存在吗？

**Comment by nihui** [comment]
修好了，请测试下

**Comment by CasonTsai** [comment]
我也遇到这样的问题额，请问怎么解决，是下载新版本的ncnn么

**Comment by dangxusheng** [comment]
对，在我提出这个问题后，作者很快进行了修改并提交了，但我并没有测试，你在github上找下那个时间节点，后面的就都应该没问题了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CasonTsai"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 上午10:27
收件人:&nbsp;"Tencent/ncnn"<ncnn@noreply.github.com&gt;;
抄送:&nbsp;"Jory.d"<707564875@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/ncnn] 当分组卷积，不是depthwise时，这一层输出的结果完全不对， (#1581)





 
我也遇到这样的问题额，请问怎么解决，是下载新版本的ncnn么

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
