### ISSUE TITLE
NCNN是否支持Mat提取矩形区域

### ISSUE THREAD

**Issue by zengqi0730** [Tencent/ncnn#1582]
作者你好，在opencv里，可以对图片进行矩形区域的提取。不知NCNN是否支持呢，没找到相关文档和案例指导。
我是有两个模型，第一个模型进行人脸检测，第二个模型需要抠出检测到的人脸，进行其他任务的识别。我想在得到人脸坐标后，直接对 ncnn::Mat 进行提取送入下一个模型。这个应该怎么做？

**Comment by nihui** [comment]
copy_cut_border 可以对 Mat 取中间的ROI
不过更加推荐在原图RGB上直接ROI转换到Mat
https://github.com/Tencent/ncnn/wiki/efficient-roi-resize-rotate
