### ISSUE TITLE
关于推理时间的疑问

### ISSUE THREAD

**Issue by lawo123** [Tencent/ncnn#1583]
你好，我测试了我的模型在
服务器GPU下推理时间为15ms，miou为93.4
在ncnn android系统vulcan推理时间为70ms，miou为85.56
在ncnn android系统无vulcan推理时间为1200ms,miou为85.56
请问转化为ncnn后miou差了8个点，推理时间差5倍，且无valcan时推理时间这么长是否正常？

**Comment by nihui** [comment]
精度差距，参考 https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result 检查下

服务器GPU比手机强大很多，比服务器慢是正常的
模型比较大的情况下，建议使用vulkan推理

**Comment by lawo123** [comment]
我是使用pyncnn来测试的精度，请问和直接用c++是否有精度上偏差呢？
`  img = cv2.imread(imagepath)
   h,w = img.shape[:2]    
    mat_in = ncnn.Mat.from_pixels_resize(img, ncnn.Mat.PixelType.PIXEL_BGR2RGB,w,h,512,512)

    mean_vals = [0.485255, 0.456255, 0.406*255];
    mean_stds = [1/0.229/255, 1/0.224/255, 1/0.225/255];
    mat_in.substract_mean_normalize(mean_vals, mean_stds)
    ex = net.create_extractor()
    ex.input("input.1", mat_in)
    mat_out = ncnn.Mat()
    ex.extract("1294", mat_out)
    out = np.array(mat_out)
    img_out = np.argmax(out,axis=0)

    target = Image.open(targetpath)
    target = target.resize((512,512), Image.BILINEAR)
    target_out = np.array(target)

    num_classes = 2
    miou_class = MIOU(num_classes=num_classes)
    outputs = torch.from_numpy(out).unsqueeze(0)
    targets = copy.deepcopy(torch.from_numpy(target_out).unsqueeze(0))
    inter, union = miou_class.get_iou(outputs, targets)
    iou = sum(inter) / sum(union)+ 1e-10
    print(iou)
’
@nihui

**Comment by lawo123** [comment]
我又重新检查了下代码，发现在数据归一化部分有点问题，修改后的miou与原始代码几乎相同，感谢大佬的开源

**Comment by nihui** [comment]
恭喜你啦！
