### ISSUE TITLE
按照how to build的说明试图在Mac OS X上build失败

### ISSUE THREAD

**Issue by ruiann** [Tencent/ncnn#1584]
最后install/lib里面没有生成可用的动态链接库文件

make -j 4的输出有：
`
[ 59%] Linking CXX static library libncnn.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(command.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(gpu.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(opencv.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(pipeline.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(command.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(gpu.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(opencv.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(pipeline.cpp.o) has no symbols
`

我本地opencv是源码build出来的4.0版本，按照workflow里面的脚本，卸载然后brew install opencv3再试也是一样的结果。再卸载了opencv结果也是一样。

最后的build/install里面include是有的，lib里面是空的。

**Comment by nihui** [comment]
XXXX has no symbols 这个不是致命错误，看看是否还有其他的错误
