### ISSUE TITLE
int8优化后速度估计

### ISSUE THREAD

**Issue by qinb** [Tencent/ncnn#1586]
你好，我训练的模型，利用ncnn，int8的速度要比fp32慢一倍。
想请问：
 Q1: 有什么办法缓解这个问题吗？
 Q2: 如果ncnn优化完int8 op，您认为和ncnn的fp32 op相比，速度方面上大概会快/慢多少？
期待回答，感谢！

**Comment by qinb** [comment]
@nihui 这个也回答一下呗，多谢

**Comment by tpoisonooo** [comment]
Q1:
开发 int8 的 pack8

Q2：
A72 int8 极限情况下可以比 fp32 快 50% 
因为`fmla`只能做 4 个， `smla` 可以处理8个 int8，但由于有溢出问题需要额外的进位。
直观的感受可以看 https://github.com/tpoisonooo/chgemm 里面的图。

**Comment by BUG1989** [comment]
如果有预算的话，建议了解下Tengine，商用版的arm int8，速度靠谱。

**Comment by qiudi0127** [comment]
@BUG1989 您好，请问下int8人脸检测模型在pc测试输出正常，移植到安卓端无法检测到人脸的原因是libncnn.a的问题么

**Comment by BUG1989** [comment]
@qiudi0127 建议每一层打印出来对比

**Comment by qiudi0127** [comment]
@BUG1989 好的 我试试 感谢

**Comment by qiudi0127** [comment]
<img width="436" alt="image" src="https://user-images.githubusercontent.com/26405062/76301867-f846f500-62f9-11ea-966d-654c8d942aac.png">
@BUG1989  您好 这样加载模型然后ndk编译成so是否能成功加载

**Comment by tpoisonooo** [comment]
android 的权限貌似不是这么设计的，先看这个目录有么有读写权限。

**Comment by tpoisonooo** [comment]
最简单的验证方法是 android 编译器交叉编译个可执行程序，adb push 进 /data/local/tmp 跑一跑。 小测试程序没问题基本可以排除 ncnn 本身的问题，着重看 android 开发。

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新
