### ISSUE TITLE
softmax layer 部分输出 nan

### ISSUE THREAD

**Issue by ItchyHiker** [Tencent/ncnn#1588]
使用 softmax 输出分割类别，最后的结果部分像素是nan. 
通过每个操作排查，发现是UnaryOp中部分出现inf.

**Comment by ItchyHiker** [comment]
系统是 OSX (x86_64)
使用的是自己编译的 20200226 的 release

**Comment by ItchyHiker** [comment]
好像是当通道值超过90的时候，该通道softmax就会nan

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/issues/1284
试试看debug编译也许就好了...

**Comment by ItchyHiker** [comment]
好的，我试试

**Comment by ItchyHiker** [comment]
debug编译有同样的问题
不过我想办法绕开这个问题了
