### ISSUE TITLE
返回值问题

### ISSUE THREAD

**Issue by enduringstack** [Tencent/ncnn#159]
如下，通过内存去加载模型，
// init param
    {
        int len = env->GetArrayLength(param);
        alexnet_param.resize(len);
        env->GetByteArrayRegion(param, 0, len, (jbyte*)alexnet_param.data());
        int ret = alexnet.load_param(alexnet_param.data());
        __android_log_print(ANDROID_LOG_DEBUG, "txncnn", "load_param %d %d", ret, len);
    }

    // init bin
    {
        int len = env->GetArrayLength(bin);
        alexnet_bin.resize(len);
        env->GetByteArrayRegion(bin, 0, len, (jbyte*)alexnet_bin.data());
        int ret = alexnet.load_model(alexnet_bin.data());
        __android_log_print(ANDROID_LOG_DEBUG, "txncnn", "load_model %d %d", ret, len);
    }
 
这个状态码0  应该是成功，状态码是8代码什么含义呢？

 D/txncnn: load_param 8 804
 D/txncnn: load_model 0 243860928

**Comment by nihui** [comment]
内存加载的返回值代表读取的数据量，并不是0

看下.h里的注释

**Comment by enduringstack** [comment]
@nihui  那这里内存加载大概哪里出错了呢？

**Comment by nihui** [comment]
内存加载要用 param.bin 的内容，参考 
https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet
