### ISSUE TITLE
benchmark speed on android

### ISSUE THREAD

**Issue by lawo123** [Tencent/ncnn#1594]
你好，我用benchmark测试linux cpu 1458ms,linux gpu 1447ms,android的速度cpu版4078ms gpu版4196ms，自己写代码测试android cpu版400ms，gpu版2000ms,pytorch gpu 20ms。

问题一：为什么benchmark的linux gpu版好和 pytorch的gpu版速度不一样呢？
问题二：为什么benchmark的 gpu版反而比cpu版慢一点呢？
问题三：为什么benchmark测试的速度和我自己在android上跑的速度差很多呢？
benchmark linux cpu:
lydia@lydia:~/disk/project/ncnn/build/benchmark$ ./benchncnn 4 2 0 -1
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = -1
cooling_down = 1
        espnetv2-opt  min = 1444.80  max = 1468.16  avg = 1458.76

benchmark linux gpu :
lydia@lydia:~/disk/project/ncnn/build/benchmark$ ./benchncnn 4 2 0 0
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = 0
cooling_down = 1
        espnetv2-opt  min = 1444.61  max = 1452.32  avg = 1447.69

benchmark android cpu:
130|HWEML:/data/local/tmp $ ./benchncnn 4 2 0 -1                                                           
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = -1
cooling_down = 1
        espnetv2-opt  min = 3944.03  max = 4221.74  avg = 4078.30

benchmark android gpu:
HWEML:/data/local/tmp $ ./benchncnn 4 2 0 0                                                                
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = 0
cooling_down = 1
        espnetv2-opt  min = 4187.23  max = 4205.94  avg = 4196.50
 @nihui

**Comment by nihui** [comment]
看你的输出信息，gpu没编译上？
正常来说，跑gpu会输出显卡的信息，就像 https://github.com/Tencent/ncnn/blob/master/benchmark/README.md

编译步骤参考下 https://github.com/Tencent/ncnn/wiki/how-to-build

**Comment by lawo123** [comment]
多谢，检查了一下确实是gpu没编译上，修改后的linux gpu 39ms，cpu 1447ms，   android gpu 391ms ，android cpu 4170ms。请问android gpu和cpu的速度差那么多正常吗？现在还能再提速吗，想android gpu 至少能到70ms左右。

**Comment by lawo123** [comment]
爲了加速，嘗試量化，但是量化後的速度反而增加了。
linux gpu:
lydia@lydia:~/disk/project/ncnn/build/benchmark$ ./benchncnn 4 2 0 0
[0 GeForce GTX 1080 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 GeForce GTX 1080 Ti]  buglssc=0  bugihfa=0
[0 GeForce GTX 1080 Ti]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = 0
cooling_down = 1
        espnetv2-opt  min =   43.05  max =   55.90  avg =   51.14
linux cpu:
lydia@lydia:~/disk/project/ncnn/build/benchmark$ ./benchncnn 4 2 0 -1
[0 GeForce GTX 1080 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 GeForce GTX 1080 Ti]  buglssc=0  bugihfa=0
[0 GeForce GTX 1080 Ti]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = -1
cooling_down = 1
        espnetv2-opt  min = 1603.01  max = 1606.14  avg = 1604.59

android gpu:
HWEML:/data/local/tmp $ ./benchncnn 4 2 0 0                                                                
[0 Mali-G72]  queueC=0[2]  queueG=0[2]  queueT=0[2]
[0 Mali-G72]  buglssc=0  bugihfa=0
[0 Mali-G72]  fp16p=1  fp16s=0  fp16a=0  int8s=0  int8a=0
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = 0
cooling_down = 1
        espnetv2-opt  min =  389.71  max =  420.83  avg =  408.70
android cpu:
130|HWEML:/data/local/tmp $ ./benchncnn 4 2 0 -1                                                           
[0 Mali-G72]  queueC=0[2]  queueG=0[2]  queueT=0[2]
[0 Mali-G72]  buglssc=0  bugihfa=0
[0 Mali-G72]  fp16p=1  fp16s=0  fp16a=0  int8s=0  int8a=0
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = -1
cooling_down = 1
        espnetv2-opt  min = 4170.18  max = 4415.36  avg = 4292.82

**Comment by nihui** [comment]
除了消减模型，可能没什么好办法

然后可以试试看把这个设为true ...
https://github.com/Tencent/ncnn/blob/5be84ef76db4d00b67571351289eefc02f443bc2/src/gpu.cpp#L524

**Comment by lawo123** [comment]
修改爲true後是比現在快了一點42ms，但是還是沒有量化前速度快（量化前35ms），我以爲量化不是應該能提速很多嗎？爲什麼速度還慢了？是和我的模型有關係嗎？我的模型裏有膨脹卷積 dilate>1

**Comment by nihui** [comment]
> 修改爲true後是比現在快了一點42ms，但是還是沒有量化前速度快（量化前35ms），我以爲量化不是應該能提速很多嗎？爲什麼速度還慢了？是和我的模型有關係嗎？我的模型裏有膨脹卷積 dilate>1

改成true，你在手机gpu上跑跑看
量化提速很多是因为tensorflowlite的fp32跑得太慢。ncnn的fp32足够快，所以并不会提速

**Comment by lawo123** [comment]
我试了一下android gpu版报错，cpu版可以，但是时间很长
HWEML:/data/local/tmp $ ./benchncnn 4 2 0 0                                                                
[0 Mali-G72]  queueC=0[2]  queueG=0[2]  queueT=0[2]
[0 Mali-G72]  buglssc=0  bugihfa=1
[0 Mali-G72]  fp16p=1  fp16s=0  fp16a=1  int8s=0  int8a=0
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = 0
cooling_down = 1
Segmentation fault 
139|HWEML:/data/local/tmp $ ./benchncnn 4 2 0 -1                                                           
[0 Mali-G72]  queueC=0[2]  queueG=0[2]  queueT=0[2]
[0 Mali-G72]  buglssc=0  bugihfa=1
[0 Mali-G72]  fp16p=1  fp16s=0  fp16a=1  int8s=0  int8a=0
loop_count = 4
num_threads = 2
powersave = 0
gpu_device = -1
cooling_down = 1
        espnetv2-opt  min = 5630.06  max = 5838.73  avg = 5760.39
[espnetv2-opt.zip](https://github.com/Tencent/ncnn/files/4304911/espnetv2-opt.zip)

**Comment by nihui** [comment]
你得改模型，精简下
pytorch gpu 20ms 的模型，无论如何优化，手机gpu必然跑不到70ms，不能违反物理原则

**Comment by lawo123** [comment]
pytorch gpu 和ncnn android的速度大概差几倍呢？我如果pytorch gpu精简到7ms左右，android ncnn 70ms左右

**Comment by nihui** [comment]
这个得看你的电脑gpu和手机gpu具体硬件能力了，建议多裁剪几个模型，分别实际测试下看看

**Comment by lawo123** [comment]
好的，多谢
