### ISSUE TITLE
Mac 编译ios版本报错

### ISSUE THREAD

**Issue by clq1983** [Tencent/ncnn#1599]
大佬帮看看，
XCode版本是： 11.1
cmake刚安装的版本是：3.17
在执行cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/iosxc.toolchain.cmake ..，时报如下错误:

-- CMAKE_TOOLCHAIN_FILE = /Users/clq/Desktop/DeepLearning/ncnn-master/toolchains/iosxc.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /Users/clq/Desktop/DeepLearning/ncnn-master/build-ios/install
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:165 (message):
  Failed to resolve SDK path for
  '/home/nihui/osd/cctools-port/usage_examples/ios_toolchain/target/SDK/iPhoneOS10.2.sdk'
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:213 (_apple_resolve_multi_arch_sysroots)
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:20 (project)

CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:165 (message):
  Failed to resolve SDK path for
  '/home/nihui/simulatord/cctools-port/usage_examples/isimulator_toolchain/target/SDK/iPhoneOS10.2.sdk'
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:213 (_apple_resolve_multi_arch_sysroots)
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:20 (project)

CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:204 (message):
  No SDK found for architecture 'armv7'
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:213 (_apple_resolve_multi_arch_sysroots)
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:20 (project)

CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:204 (message):
  No SDK found for architecture 'arm64'
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:213 (_apple_resolve_multi_arch_sysroots)
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:20 (project)

CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/Platform/Darwin-Initialize.cmake:221 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /home/nihui/osd/cctools-port/usage_examples/ios_toolchain/target/SDK/iPhoneOS10.2.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:20 (project)

-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:20 (project):
  The CMAKE_C_COMPILER:

    arm-apple-darwin11-clang

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:20 (project):
  The CMAKE_CXX_COMPILER:

    arm-apple-darwin11-clang++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/Users/clq/Desktop/DeepLearning/ncnn-master/build-ios/CMakeFiles/CMakeOutput.log".
See also "/Users/clq/Desktop/DeepLearning/ncnn-master/build-ios/CMakeFiles/CMakeError.log".

**Comment by donghejun** [comment]
应该是下面这个路径导致的错误，因为下的路径并不是我的：

**Comment by nihui** [comment]
You used the wrong toolchain file
please refer https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-ios-on-macosx-with-xcode
