### ISSUE TITLE
iOS版本问题

### ISSUE THREAD

**Issue by donghejun** [Tencent/ncnn#1602]
1.【Because the compiler bundled with xcode do not support openmp feature, you cannot enable the multithreading inference feature of ncnn library, if you build with xcode.】是否意味着直接把NCNN库的源代码集成到工程中运行是不支持多线程推理功能？必须是要在linux下编译的ios NCNN库才支持多线程推理功能？
2.是否可以提供已经编译好的支持openmp的且支持bitcode的ios版本NCNN库？

**Comment by nihui** [comment]
1 如果xcode可以自己指定第三方支持openmp的编译器，技术上是可以的，但是我没有试过
2 下个版本会尝试提供 -fembed-bitcode 编译库

**Comment by donghejun** [comment]
@nihui 谢谢，期待支持bitcode的编译库。
