### ISSUE TITLE
int8量化模型android移植问题

### ISSUE THREAD

**Issue by qiudi0127** [Tencent/ncnn#1603]
人脸检测模型量化后pc端测试输出正常，移植到安卓端通过ndk编译成so后检测不到人脸，请问是什么问题，以及如下加载模型到方式移植后是否有效？
![image](https://user-images.githubusercontent.com/26405062/76326976-5c7eae80-6324-11ea-9418-60a768fccaac.png)

**Comment by tpoisonooo** [comment]
check **https://github.com/Tencent/ncnn/issues/1586**

**Comment by qiudi0127** [comment]
@tpoisonooo 感谢回复，问题已经解决，android侧不可以如上加载模型，在android侧读取模型送入so的方法是可以。
