### ISSUE TITLE
model.load_model()函数报Program terminated with signal SIGKILL, Killed错误

### ISSUE THREAD

**Issue by CnybTseng** [Tencent/ncnn#1604]
平台：海思hi3559av100
交叉编译：
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/himix100.toolchain.cmake \
    -DNCNN_BUILD_EXAMPLES=OFF ..
make -j12 && make install

在板子上加载模型：
ncnn::Net yolov3;
yolov3.load_param("./model/deploy.param");   // load_param_bin("./model/deploy.param.bin"); 一样
yolov3.load_model("./model/deploy.bin");

gdb跟到load_model()，报错：
Program terminated with signal SIGKILL, Killed

deploy.param和deploy.bin在centos上测试运行正常(用官方的yolov3.cpp稍加改动测试)

怎么解决？

**Comment by nihui** [comment]
内存不足 ？

**Comment by CnybTseng** [comment]
板载4GB DDR4内存

**Comment by CnybTseng** [comment]
> 内存不足 ？

板载4GB DDR4内存
我在ncnn/src/CMakeLists.txt的PRIVATE -Wall -Wextra -Wno-unused-function后面加了-g
gdb跟踪到int Net::load_model(const DataReader& dr)第二个for循环里面某个阶段发生了这个Program terminated with signal SIGKILL, Killed

**Comment by nihui** [comment]
SIGKILL 基本上都是因为内存不足，模型太大无法加载，建议换小一点的模型
