### ISSUE TITLE
absval_arm中的for循环步长问题

### ISSUE THREAD

**Issue by jnulzl** [Tencent/ncnn#1605]
冒昧的问下，为什么absval_arm.cpp中57行的ptr步长为4. 而51行for循环中的i步长为1，如下所示，不是应该都为4吗？
https://github.com/Tencent/ncnn/blob/7d1eec3d5d58a1d13c9a103a688ed5819f6e2e76/src/layer/arm/absval_arm.cpp#L51

https://github.com/Tencent/ncnn/blob/7d1eec3d5d58a1d13c9a103a688ed5819f6e2e76/src/layer/arm/absval_arm.cpp#L57

**Comment by nihui** [comment]
pack4 内存布局中，一个元素是4个float
https://github.com/Tencent/ncnn/wiki/element-packing

**Comment by jnulzl** [comment]
哦，好的，多谢啦！
