### ISSUE TITLE
ndk编译问题

### ISSUE THREAD

**Issue by lebronjdw** [Tencent/ncnn#1607]
在ndk编译后，有如下报错
error: unknown type name 'PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR'
error: unknown type name 'PFN_vkGetBufferMemoryRequirements2KHR'; did you mean 'PFN_vkGetBufferMemoryRequirements'

等都是类似错误，有何解决办法不

**Comment by nihui** [comment]
ndk版本是多少？

**Comment by nihui** [comment]
出现这个错误的主要原因是编译 ncnn 和 app 用的 android api 版本不一样。尝试提高 app 的 android platform api

**Comment by nihui** [comment]
如果还有问题，可以 reopen issue 继续讨论

**Comment by Eleanor456** [comment]
你好，请问我编译vulkan版本的ncnn时，总是提示/data1/gepei/stock_ocr/ncnn/src/gpu.h:45:8: error: unknown type name 'PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR'
extern PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR vkGetPhysicalDeviceExternalBufferPropertiesKHR;

**Comment by Eleanor456** [comment]
你好，我在用ndk r14b编译ncnn时，总是出现下面这个错误 xxxx/ncnn/src/gpu.h:45:8: error: unknown type name 'PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR'
extern PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR vkGetPhysicalDeviceExternalBufferPropertiesKHR;
编译命令为：cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake"     -DANDROID_ABI="arm64-v8a"     -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..


当我换了ndk 18b时，则会出现找不到vulkan库，当我指定了vulkan库的位置时，会出现新的错误：android-ndk-r18b/sources/cxx-stl/llvm-libc++/include/support/android/locale_bionic.h:30:10: fatal error: 
      'android/ndk-version.h' file not found
#include <android/ndk-version.h>
编译命令为：cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake"     -DANDROID_ABI="arm64-v8a"     -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..

请问这个问题要怎么解决呢，谢谢

**Comment by nihui** [comment]
> 你好，我在用ndk r14b编译ncnn时，总是出现下面这个错误 xxxx/ncnn/src/gpu.h:45:8: error: unknown type name 'PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR'
> extern PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR vkGetPhysicalDeviceExternalBufferPropertiesKHR;
> 编译命令为：cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
> 
> 当我换了ndk 18b时，则会出现找不到vulkan库，当我指定了vulkan库的位置时，会出现新的错误：android-ndk-r18b/sources/cxx-stl/llvm-libc++/include/support/android/locale_bionic.h:30:10: fatal error:
> 'android/ndk-version.h' file not found
> #include <android/ndk-version.h>
> 编译命令为：cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
> 
> 请问这个问题要怎么解决呢，谢谢

cmake 版本更新下

**Comment by Eleanor456** [comment]
> > 你好，我在用ndk r14b编译ncnn时，总是出现下面这个错误 xxxx/ncnn/src/gpu.h:45:8: error: unknown type name 'PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR'
> > extern PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR vkGetPhysicalDeviceExternalBufferPropertiesKHR;
> > 编译命令为：cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
> > 当我换了ndk 18b时，则会出现找不到vulkan库，当我指定了vulkan库的位置时，会出现新的错误：android-ndk-r18b/sources/cxx-stl/llvm-libc++/include/support/android/locale_bionic.h:30:10: fatal error:
> > 'android/ndk-version.h' file not found
> > #include <android/ndk-version.h>
> > 编译命令为：cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
> > 请问这个问题要怎么解决呢，谢谢
> 
> cmake 版本更新下

你好，更新cmake到3.14.1依旧是这两个错误
