### ISSUE TITLE
relu6转换错误

### ISSUE THREAD

**Issue by ruiann** [Tencent/ncnn#1609]
pytorch->onnx->onnx-sim->ncnn的转换流程中，relu6最终转换成了
`
Clip             409                      1 1 405 409 0=-3.402823e+38 1=3.402823e+38
`
需要手动修改。

**Comment by nihui** [comment]
请提供 onnx 文件以便复现问题

**Comment by ruiann** [comment]
[model-sim.onnx.zip](https://github.com/Tencent/ncnn/files/4327839/model-sim.onnx.zip)
这是onnxsim之后的文件

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
修好了~

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
