### ISSUE TITLE
对回归任务结果误差比较大，数值上的相对误差超过10%

### ISSUE THREAD

**Issue by ruiann** [Tencent/ncnn#1610]
输入采用全黑图像，避免了rgb通道or杂七杂八的问题，相对于pytorch版本输出的数值，误差最大超过了10%，对于数值非常敏感的回归任务来说，10%的额外误差也很难接受。
历史issue里面查看了一些对误差的讨论，有说是因为使用fp16的原因，但我在pytorch中对全部参数to(torch.float16)之后再计算比较，误差依然非常大。

想问一下误差是什么原因导致的，如何解决这个误差问题。

**Comment by nihui** [comment]
你是用cpu跑的吗？应该是不会有这么大误差的
首先可以按照faq检查
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result

如果结果还是不对，可以 ex.extract 中间的 blob 和 pytorch 对比，检查是哪个层开始导致的问题

**Comment by ruiann** [comment]
您好，我仔细检查过，代码应该没有问题。
从blob对比来看，误差是一直存在并开始累积的。我的网络是mobilenetv2的主干接多尺度特征融合，然后max pooling回归数值。
比如在主干的第四层上的输出的最后一个channel的最后一行上，pytorch的输出为：
`
[-3.1513, -1.2132, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471,
        -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471,
        -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471,
        -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471,
        -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471,
        -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471,
        -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471,
        -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1471, -1.1951, -2.3341]
`
而ncnn的输出是：
`
-3.14972 -1.21383 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.14665 -1.19476 -2.33155 
`
累积到后面的层误差就逐步增大，到主干跑完的时候，部分数值就已经产生了大约10%的误差了。

因此我主要想知道误差是怎么产生的，有没有一些方法来规避。

**Comment by nihui** [comment]
检查输入blob有没有误差，图片用 bmp 试试看，也许是解码不一样

**Comment by ruiann** [comment]
没有，输入是全黑图片，mean也是0，bmp也测试过。

**Comment by nihui** [comment]
这就很奇怪了呀，你是用gpu跑的吗？
gpu默认是fp16 packed/storage，可以设置用fp32运行
https://github.com/Tencent/ncnn/wiki/vulkan-notes#control-storage-and-arithmetic-precision

**Comment by ruiann** [comment]
我是在mac平台上使用cpu跑的，目前还处于开发阶段，还没有植入设备中。
是否需要我提供pytorch的model文件和模型？

**Comment by ruiann** [comment]
更精确的定位了一下
`
7767517
136 150
Input            input.1                  0 1 input.1
Convolution      363                      1 1 input.1 363 0=32 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=864
Clip             367                      1 1 363 367 0=0.000000e+00 1=6.000000e+00
ConvolutionDepthWise 368                      1 1 367 368 0=32 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=288 7=32
Clip             372                      1 1 368 372 0=0.000000e+00 1=6.000000e+00
`
从367这个输出就已经出现了误差，这一层在一张正常的图像上的输出的一部分是
`
0.724806 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.514281 0.392789 0.395919 0.397397 0.402691 0.410009 0.403347 0.394591 0.395046 0.401269 0.397984 0.393460 0.395291 0.400336 0.389034 0.201697 0.347220 0.242356 0.294011 0.371292 0.375421 0.371310 0.391924 0.396678 0.391971 0.377660 0.381765 0.379662 0.394828 0.396251 0.403410 0.410610 0.413475 0.424675 0.423462 0.424484 0.426062 0.429110 0.432785 0.434546 0.438057 0.438942 0.442538 0.445000 0.445396 0.445091 0.443957 0.439189 0.440131 0.439549 0.440073 0.439406 0.447782 0.444167 0.448276 0.448966 0.445859 0.438860 0.438223 0.435776 0.438075 0.431505 0.428939 0.427653 0.420297 0.410583 0.401521 0.340452 0.158815 0.167469 0.240189 0.269031 0.341179 0.397357 0.394148 0.394716 0.390163 0.390254 0.348371 0.030346 0.121451 0.134611 0.151947 0.133961 0.135221 0.119922 0.114637 0.130784 0.162246 0.170877 0.172070 0.164050 0.139993 0.127647 0.121611 0.132670 0.153924 0.177358 0.183003 0.171549 0.141190 0.085174 0.083888 0.128461 0.137439 0.117957 0.119654 0.116902 0.116743 
`

对应这一层的pytorch的输出（显示8位）：
`
[0.72480553, 0.51428121, 0.51428121, 0.51428121, 0.51428121, 0.51428121,
        0.51428121, 0.51428121, 0.51428121, 0.51428121, 0.51428121, 0.51428121,
        0.51428121, 0.51428121, 0.51428121, 0.51428121, 0.51200706, 0.51516050,
        0.51330793, 0.51278615, 0.39568391, 0.39460033, 0.39772823, 0.40015125,
        0.40653092, 0.40724188, 0.38943180, 0.39532527, 0.39939201, 0.39766073,
        0.38973162, 0.39274019, 0.39516479, 0.38929504, 0.19675185, 0.34600824,
        0.24494931, 0.29857108, 0.36431617, 0.37102205, 0.36745203, 0.39202067,
        0.39906386, 0.38372174, 0.38051271, 0.38166928, 0.37723610, 0.39277458,
        0.39595982, 0.40328562, 0.41241533, 0.41480729, 0.42432889, 0.42434335,
        0.42354110, 0.42283028, 0.42559507, 0.43482378, 0.43393448, 0.44051182,
        0.44285515, 0.44078377, 0.44498304, 0.44441783, 0.44793355, 0.44151130,
        0.43956831, 0.43824613, 0.43954432, 0.44685081, 0.43055859, 0.44665349,
        0.44161049, 0.44812596, 0.44879678, 0.44517002, 0.43885732, 0.43598196,
        0.43772250, 0.43771321, 0.43366009, 0.42177933, 0.43513152, 0.41500577,
        0.41538393, 0.39435437, 0.34669495, 0.16069831, 0.15955949, 0.23947361,
        0.27195394, 0.34291127, 0.39637971, 0.39757627, 0.39373207, 0.38845015,
        0.38900152, 0.34982476, 0.02842101, 0.12327246, 0.13503547, 0.14797752,
        0.13547781, 0.13605346, 0.11716397, 0.11273131, 0.13305040, 0.16383223,
        0.16904850, 0.17142422, 0.16652954, 0.13457933, 0.12429003, 0.12027256,
        0.13532619, 0.15555780, 0.17322503, 0.18192443, 0.17271249, 0.14182574,
        0.08830351, 0.08023153, 0.12951413, 0.13688028, 0.12034318, 0.11506389,
        0.11704288, 0.11582574]
`
这一层的结构非常简单，就是conv2d+bn2d+relu6

看起来似乎是ncnn的执行中间存储使用的是fp16，只保存到7位有效数字，导致精度下降了？
`
detect_model.opt.use_fp16_packed = false;
detect_model.opt.use_fp16_storage = false;
detect_model.opt.use_fp16_arithmetic = false;
 detect_model.opt.use_int8_storage = false;
detect_model.opt.use_int8_arithmetic = false;
`
这几个我都设置过，没什么作用。

**Comment by nihui** [comment]
cpu运行是fp32

从你的输出结果看，依旧怀疑是输入数据有不一样
input.1
363
367

前三个blob都输出看看，如果367不对，363应该必然也不对，那么 input.1 很可能也不一样

ncnn的卷积实现本身出bug的概率感觉不大，毕竟用了那么久了 ....

**Comment by ruiann** [comment]
我对比了一下前面三个blob，input.1和pytorch的输入是一样的，363的输出就已经不对了。
363只有6-7位有效数字，而pytorch的输出有效数字则很长，数据类型是torch.float32。

**Comment by ruiann** [comment]
设置显示更多位有效数字后我发现确实产生了误差，但误差非常小，设置显示8位后，从主干出来的输出中，误差只有0.01%的水平。
于是我继续往后看，发现问题出现在插值上。以在主干输出特征的某一通道的某一行为例。
pytorch输入：
`
[0.58389425, 0.05054252, 0.48553699, 0.93665701, 1.29889274, 1.28866768, 0.00000000, 1.43809557]
`
运算：
`
y = F.interpolate(x, scale_factor=2, mode='bilinear', align_corners=True)
`
输出：
`
tensor([0.58389425, 0.33499676, 0.08609930, 0.22454031, 0.42753771, 0.63591027,
        0.84643298, 1.03325319, 1.20229661, 1.29684782, 1.29207611, 1.11684549,
        0.51546717, 0.09587295, 0.76698428, 1.43809557],
       grad_fn=<SelectBackward>)
`

ncnn输入：
`
0.58388895 0.05053828 0.48554060 0.93666089 1.29889429 1.28866649 0.00000000 1.43809354
`
输入跟pytorch的输入差不多，误差规模非常小
运算：
`
Interp           609                      1 1 581 609 0=2 1=1.000000e+00 2=1.000000e+00 3=16 4=16
`
输出：
`
0.58388895 0.45055127 0.18387595 0.15928885 0.37679002 0.59832066 0.82388085 1.02721930 1.20833588 1.29633737 1.29122341 0.96649987 0.32216662 0.35952339 1.07857013 1.43809354
`

可以认定问题出现在这个位置，请问有什么好的解决办法？

**Comment by nihui** [comment]
ncnn 的插值只实现了 align_corners=False 的情况

**Comment by ruiann** [comment]
感谢，测试了一下发现一致了
