### ISSUE TITLE
ncnn有能支持NDK R14的库吗

### ISSUE THREAD

**Issue by ht1066608644** [Tencent/ncnn#1614]

**Comment by nihui** [comment]
是什么原因要用那么老的ndk呢？

**Comment by ht1066608644** [comment]
我的项目使用的OpenCV只能在NDK R14上面运行起来，更新到NDK 其他的版本都编译不了，看网上说是OpenCV cmake配置问题，一直没太搞明白具体原因是什么，不知道你那边有openCV和ncnn一起使用的么,所以我想问问ncnn有能在NDK r14上面编译的库么，我看git上编译的也跳过了R14,不知道原因是什么，谢谢你的回答

**Comment by ht1066608644** [comment]
我的项目使用的OpenCV只能在NDK R14上面运行起来，更新到NDK 其他的版本都编译不了，看网上说是OpenCV cmake配置问题，一直没太搞明白具体原因是什么，不知道你那边有openCV和ncnn一起使用的么,所以我想问问ncnn有能在NDK r14上面编译的库么，我看git上编译的也跳过了R14,不知道原因是什么，谢谢你的回答

**Comment by nihui** [comment]
opencv 用新的 ndk 是肯定可以编译的，也可以去opencv官网下载编译好的android库使用
ncnn历史上最早只支持到ndk r15c，再早的ndk有很多bug，容易导致崩溃

**Comment by ht1066608644** [comment]
好的，我在看看
