### ISSUE TITLE
undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int)'

### ISSUE THREAD

**Issue by AIGirl10** [Tencent/ncnn#1615]
I was trying to run program linking NCNN library and create a binary. It gave me correct output on pre-built libncnn.a(1.1MB) (which source code I don't have) , but giving this error
```
undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int)'
```
when tried to make binary with latest NCNN (size : 2.4MB)

Can anyone please help me.
--------------------------------

我试图运行链接NCNN库的程序并创建一个二进制文件。它在预构建的libncnn.a（1.1MB）（我没有的源代码）上给了我正确的输出，但是给出了这个错误
```
undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int)'
```
尝试使用最新的NCNN制作二进制文件时（大小：2.4MB）

谁能帮帮我吗。

**Comment by AIGirl10** [comment]
Sorry, my stupidity. The reason was I didn't used new header files (used old ones)

**Comment by AIGirl10** [comment]
Sorry, my stupidity. The reason was I didn't used new header files (used old ones)

**Comment by suntaiwu** [comment]
头文件没错也报这个错，ios的，orz
