### ISSUE TITLE
win7 cmake ncnn error

### ISSUE THREAD

**Issue by 1109449054** [Tencent/ncnn#1616]
执行cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DProtobuf_INCLUDE_DIR=D:\Protobuf\protobuf-3.4.0/build-vs2017/install/include -DProtobuf_LIBRARIES=D:\Protobuf\protobuf-3.4.0/build-vs2017/install/lib/libprotobuf.lib -DProtobuf_PROTOC_EXECUTABLE=D:\Protobuf\protobuf-3.4.0/build-vs2017/install/bin/protoc.exe
后显示No source or binary directory provided,检查了命令中的文件都有

**Comment by nihui** [comment]
最后缺少 ..
