### ISSUE TITLE
Compile error running glslangValidator

### ISSUE THREAD

**Issue by teamaltumview** [Tencent/ncnn#1618]
I was trying to compile NCNN with Vulkan GPU support and encountered the following error.
It seems that glslangValidator does not support the "GL_EXT_shader_explicit_arithmetic_types_float16" extension.
I was compiling under Linux. My Vulkan loader and glslangValidator come from sdk-1.1.73.0
Is this a known issue?
Thanks
D

[  0%] Building SPIR-V module absval_fp16pa.spv
/home/shunya/s1/ncnn/src/layer/vulkan/shader/absval.comp
ERROR: /home/shunya/s1/ncnn/src/layer/vulkan/shader/absval.comp:21: '#extension' : extension not supported: GL_EXT_shader_explicit_arithmetic_types_float16
ERROR: /home/shunya/s1/ncnn/src/layer/vulkan/shader/absval.comp:21: '#extension' : extra tokens -- expected newline
ERROR: /home/shunya/s1/ncnn/src/layer/vulkan/shader/absval.comp:21: '' : missing #endif
ERROR: /home/shunya/s1/ncnn/src/layer/vulkan/shader/absval.comp:21: '' : compilation terminated
ERROR: 4 compilation errors.  No code generated.

**Comment by nihui** [comment]
upgrade your vulkan sdk
