### ISSUE TITLE
重做系统后，ncnn加载不了模型和网络了

### ISSUE THREAD

**Issue by HandsomeHans** [Tencent/ncnn#162]
编译都能通过，
就是在运行例子的时候提示错误。

`
hans@hans-desktop:~/ncnn/build/examples$ ./squeezenet /home/hans/asd.jpg 

fopen squeezenet_v1.1.param failed

fopen squeezenet_v1.1.bin failed

find_blob_index_by_name data failed

find_blob_index_by_name prob failed

Segmentation fault (core dumped)
`

**Comment by HandsomeHans** [comment]
傻了，param和bin文件搞错位置了

**Comment by mathpopo** [comment]
> 傻了，param和bin文件搞错位置了

????请问怎么操作？

**Comment by mathpopo** [comment]
./squeezenet_v1.1.bin
./squeezenet
./squeezenet_v1.1.param

**Comment by HandsomeHans** [comment]
> > 傻了，param和bin文件搞错位置了
> 
> ????请问怎么操作？

三年前的工啦，都忘记差不多了。应该就是文件路径的问题，你仔细检查看看。

**Comment by mathpopo** [comment]
就是修改代码，直接写个活的路径，后期再写在bin后面就行了

在 2020年6月2日星期二，Hans Ren <notifications@github.com> 写道：
