### ISSUE TITLE
我的项目使用的OpenCV只能在NDK R14上面运行起来，更新到NDK 其他的版本都编译不了，看网上说是OpenCV cmake配置问题，一直没太搞明白具体原因是什么，不知道你那边有openCV和ncnn一起使用的么,所以我想问问ncnn有能在NDK r14上面编译的库么，我看git上编译的也跳过了R14,不知道原因是什么，谢谢你的回答

### ISSUE THREAD

**Issue by ht1066608644** [Tencent/ncnn#1620]
我的项目使用的OpenCV只能在NDK R14上面运行起来，更新到NDK 其他的版本都编译不了，看网上说是OpenCV cmake配置问题，一直没太搞明白具体原因是什么，不知道你那边有openCV和ncnn一起使用的么,所以我想问问ncnn有能在NDK r14上面编译的库么，我看git上编译的也跳过了R14,不知道原因是什么，谢谢你的回答

**Comment by nihui** [comment]
duplicate of https://github.com/Tencent/ncnn/issues/1614
不要重复发issue
