### ISSUE TITLE
slice后面接conv层进行量化报错

### ISSUE THREAD

**Issue by onesnow123q** [Tencent/ncnn#1626]
转换ghostnet报错，用pytorch转为onnx没有报错，onnx转为ncnn时也没有报错，但是在转为int8时,使用ncnn2table时报错
====> Quantize the parameters.
====> Quantize the activation.
    ====> step 1 : find the max value.
Segmentation fault (core dumped)
经过定位，发现slice(ncnn转换为crop)后接conv，对该conv进行操作时报错：
![image](https://user-images.githubusercontent.com/30360420/76942609-f6ec7c80-6938-11ea-8548-665b17cca2e6.png)
望解答，谢谢！！

**Comment by onesnow123q** [comment]
刚刚跑了下float32的，发现从crop开始就已经没有输出了

**Comment by nihui** [comment]
更新下onnx2ncnn.cpp重新转换下模型看看
修复了一个crop的转换问题

**Comment by onesnow123q** [comment]
是的是的，slice这里的attr都是input输入的~~多谢大佬 @nihui

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
