### ISSUE TITLE
set_vulkan_device

### ISSUE THREAD

**Issue by FB-wh** [Tencent/ncnn#1628]
net.set_vulkan_device(0); // use device-0
net.set_vulkan_device(1); // use device-1
这样设定后，一直会分配到gpu1上面，gpu0上面不会分配任务。是不是还有其他设定才可以在多个gpu上一起运行

**Comment by nihui** [comment]
开启两个线程，创建两个 net 实例，各设置一个gpu

**Comment by FB-wh** [comment]
好的，感谢
