### ISSUE TITLE
编译报错error: ‘INT_MAX’ 

### ISSUE THREAD

**Issue by iotsharer** [Tencent/ncnn#1631]
前一个版本可以正常编译，最新版本编译后报错
![image](https://user-images.githubusercontent.com/29347606/77037113-89e5ef00-69eb-11ea-99dc-6fc417dafc3a.png)

**Comment by iotsharer** [comment]
补充一下，我是在树莓派4b上编译，目前问题已经解决，之前编译使用的是
`cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/pi3.toolchain.cmake -DPI3=ON ..`
Cmake Error是cannot find -lpthreads
后来直接使用的`cmake ..`编译成功，具体原因不明

**Comment by nihui** [comment]
修好了~
