### ISSUE TITLE
希望官方能支持pytorch转ncnn

### ISSUE THREAD

**Issue by xinheblue** [Tencent/ncnn#1632]
做训练目前最好用的是pytorch，简单方便源码很多
做推理，在很多场合，最好用的是ncnn，支持各种硬件，方便，快，32位都支持
这两个搭配，感觉做深度学习就爽的不得了
但是，目前从pytorch转ncnn，各种不爽，稍微复杂点的模型都转不了，转onnx后，onnx转ncnn也各种不支持，直接转的是第三方工程，pytorch还停留在0.2
官方能否出一个从pytorch模型直接转ncnn的，那就太方便了

**Comment by nihui** [comment]
转onnx的时候注意尽量不要引入自定义op和后处理op，还是很好转的

**Comment by xinheblue** [comment]
> 转onnx的时候注意尽量不要引入自定义op和后处理op，还是很好转的

从pytorch转到onnx，很多时候能转成功，用onnx测试也是可以的，但是再转到ncnn，就会很容易出问题，目前碰到的，大部分的情况，github上面一些start很高的项目，都会有问题。比如会碰到Shape, Gather, Cast, Unsupported unsqueeze axes,之类的，很多很多的问题

**Comment by xinheblue** [comment]
而且onnx，用https://github.com/daquexian/onnx-simplifier  处理，也很多处理不了的

举个例子
https://github.com/biubug6/Face-Detector-1MB-with-landmark

这个代码里面，提供了一个onnx，用最新的ncnn版本/pytorch版本，不管是windows还是linux，都转换失败。我还在尝试直接用作者编译的onnx2ncnn试一下，遇到库兼容的问题还在解决。

这种出现的特别多，能不报错从onnx转到ncnn的，在碰到的开源代码里面，感觉是少数情况。

**Comment by nihui** [comment]
pytorch onnx不同版本的模型，细节上会有区别，所以之前能转换的模型新版本不能转换也是有可能的。
毕竟是不同的开源项目，相互间的接口升级和兼容步调不一致，只能发现问题解决问题

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
