### ISSUE TITLE
量化之后，推理速度变慢

### ISSUE THREAD

**Issue by liupengkd** [Tencent/ncnn#1642]
平台：rk3399
网络：mobile
量化之后，推理速度反而变慢了，开的线程越多，慢得越明显
同时，在跑ncnn源码中的benchmark也出现了这个问题，非量化模型的测试效果和官网benchmark结果类似，但是int延迟与未量化的对应模型相比较，延迟增加

**Comment by CrD1997** [comment]
> 平台：rk3399
> 网络：mobile
> 量化之后，推理速度反而变慢了，开的线程越多，慢得越明显
> 同时，在跑ncnn源码中的benchmark也出现了这个问题，非量化模型的测试效果和官网benchmark结果类似，但是int延迟与未量化的对应模型相比较，延迟增加

我也遇到了相同的问题，请问您解决了吗

**Comment by liushuan** [comment]
之前的版本会不用自己设置绑核，新版本 主动绑定 大核心运行就快了。

**Comment by liushuan** [comment]
例如 运行 ./test 程序 邦核（rk3399的大核心是4，5）运行   taskset -c 4 ./detect  速度杠杠的，也可以在程序里面动态设置。

**Comment by liupengkd** [comment]
@liushuan 试过，还是一样的，我当时猜想可能是我网络结构较小，量化与反量化增加得时间开销大于了节省开销，所以速度反而变慢了，因为我在大的检测模型上量化是要快一些的。除此之外感觉性能测试波动挺大的，比如不同时段及重启前后测试性能（可能是因为嵌入式本身资源有限，其他程序对系统整体状态影响较大）。而且当时看得ncnn设置大小核设置接口实现得源代码，内部只支持Android和ios的设置。可能现在版本又有所变化吧，我有时间换现在的最新版本试一下。还是非常感谢，thx

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新
