### ISSUE TITLE
onnx转ncnn后，不能正常推理

### ISSUE THREAD

**Issue by yonkong** [Tencent/ncnn#1647]
1、先将pytorch模型export为onnx，然后再使用onnx2ncnn得到ncnn模型
2、ncnn推理异常，即返回结果为-100.  跟踪后发现是 Crop操作返回-100.

怀疑点：
而ncnn模型文件对应层定义为
`
Crop             369                      1 1 364 369 -23309=0 -23310=0
`

推理流程走了
`int Crop::forward(const std::vector<Mat>& bottom_blobs, std::vector<Mat>& top_blobs, const Option& opt) const {
    const Mat& bottom_blob = bottom_blobs[0];
// error, reference_blob is null.
    const Mat& reference_blob = bottom_blobs[1]; `

问题：由于推理出错 ，不确定是转onnx的问题，还是转ncnn的问题？如何解决？

[100.onnx.zip](https://github.com/Tencent/ncnn/files/4374266/100.onnx.zip)

**Comment by nihui** [comment]
confirmed

**Comment by yonkong** [comment]
补充：pytorch export到onnx时，选择opset 11有问题，选择opset 9没有问题

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/253e5057653f0ed9def6332003d51e6b9aa01df3

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
