### ISSUE TITLE
1 如果xcode可以自己指定第三方支持openmp的编译器，技术上是可以的，但是我没有试过

### ISSUE THREAD

**Issue by clq1983** [Tencent/ncnn#1648]
【1 如果xcode可以自己指定第三方支持openmp的编译器，技术上是可以的，但是我没有试过
2 下个版本会尝试提供 -fembed-bitcode 编译库】
@nihui,您好，我这边有个app使用了ncnn库，效果很好，但因为app必须需要支持bitcode的ncnn framework，我尝试在linux下编译支持openmp的ncnn，但linux下ios工具链的编译有点麻烦，我担心赶不上app版本发布，你们支持bitcode的新版本计划大概是什么时候会发布，是否有可能在3月底可以提供一个支持bitcode的io版本库，非常感谢！

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/tree/89ef1f0d66c4d7e3851858a46b2a17352be5ff29
用这个版本编译了一套你试试看

[ncnn-vulkan.framework.zip](https://github.com/Tencent/ncnn/files/4379398/ncnn-vulkan.framework.zip)
[ncnn.framework.zip](https://github.com/Tencent/ncnn/files/4379399/ncnn.framework.zip)
[openmp.framework.zip](https://github.com/Tencent/ncnn/files/4379400/openmp.framework.zip)

**Comment by clq1983** [comment]
好的，谢谢@nihui

**Comment by clq1983** [comment]
@nihui ，你好：
我使用上面支持bitcode版本的ncnn库集成到工程里(整个工程也设置为支持bitcode)，真机(iphone7plus)调试没有问题，但要发布打包(release提交app store )时编译报错，当我在工程里去掉ncnn库再发布打包就可以，想问下是什么原因，有没有可能是ncnn库依赖的某些库不支持bitcode(-fembed-bitcode)
报错如下：
could not reparse object file in bitcode bundle: 'Unknown attribute kind (60) (Producer: 'LLVM9.0.1' Reader: 'LLVM APPLE_1_1100.0.33.8_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.8)' for architecture arm64
【Ld /Users/clq/Library/Developer/Xcode/DerivedData/ZAHKIDCard-bqkxllpvowiasagiupzhptchdezn/Build/Intermediates.noindex/ArchiveIntermediates/DSLHKIDCardSH/IntermediateBuildFilesPath/DSLHKIDCard.build/Release-iphoneos/DSLHKIDCard.build/Objects-normal/arm64/DSLHKIDCard normal arm64
    cd /Users/clq/Desktop/DSL_IDCard_NCNNFramework/DSLHKIDCard
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios8.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk -L/Users/clq/Library/Developer/Xcode/DerivedData/ZAHKIDCard-bqkxllpvowiasagiupzhptchdezn/Build/Intermediates.noindex/ArchiveIntermediates/DSLHKIDCardSH/BuildProductsPath/Release-iphoneos -F/Users/clq/Library/Developer/Xcode/DerivedData/ZAHKIDCard-bqkxllpvowiasagiupzhptchdezn/Build/Intermediates.noindex/ArchiveIntermediates/DSLHKIDCardSH/BuildProductsPath/Release-iphoneos -F/Users/clq/Desktop/DSL_IDCard_NCNNFramework/DSLHKIDCard/DSLHKIDCard -filelist /Users/clq/Library/Developer/Xcode/DerivedData/ZAHKIDCard-bqkxllpvowiasagiupzhptchdezn/Build/Intermediates.noindex/ArchiveIntermediates/DSLHKIDCardSH/IntermediateBuildFilesPath/DSLHKIDCard.build/Release-iphoneos/DSLHKIDCard.build/Objects-normal/arm64/DSLHKIDCard.LinkFileList -install_name @rpath/DSLHKIDCard.framework/DSLHKIDCard -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/clq/Library/Developer/Xcode/DerivedData/ZAHKIDCard-bqkxllpvowiasagiupzhptchdezn/Build/Intermediates.noindex/ArchiveIntermediates/DSLHKIDCardSH/IntermediateBuildFilesPath/DSLHKIDCard.build/Release-iphoneos/DSLHKIDCard.build/Objects-normal/arm64/DSLHKIDCard_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/clq/Library/Developer/Xcode/DerivedData/ZAHKIDCard-bqkxllpvowiasagiupzhptchdezn/Build/Intermediates.noindex/ArchiveIntermediates/DSLHKIDCardSH/BuildProductsPath/Release-iphoneos -fobjc-arc -fobjc-link-runtime -stdlib=libc++ -fembed-bitcode -framework openmp -framework opencv2 -framework ncnn -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/clq/Library/Developer/Xcode/DerivedData/ZAHKIDCard-bqkxllpvowiasagiupzhptchdezn/Build/Intermediates.noindex/ArchiveIntermediates/DSLHKIDCardSH/IntermediateBuildFilesPath/DSLHKIDCard.build/Release-iphoneos/DSLHKIDCard.build/Objects-normal/arm64/DSLHKIDCard_dependency_info.dat -o /Users/clq/Library/Developer/Xcode/DerivedData/ZAHKIDCard-bqkxllpvowiasagiupzhptchdezn/Build/Intermediates.noindex/ArchiveIntermediates/DSLHKIDCardSH/IntermediateBuildFilesPath/DSLHKIDCard.build/Release-iphoneos/DSLHKIDCard.build/Objects-normal/arm64/DSLHKIDCard
】

**Comment by clq1983** [comment]
我使用的开发工具是xcode11.1,对应的LLVM版本是：11.0.0

**Comment by nihui** [comment]
高版本llvm输出的bitcode，低版本llvm不认识
正在想办法……

**Comment by clq1983** [comment]
好的，先谢谢@nihui了

**Comment by nihui** [comment]
我的编译器是 clang 9.0.1，我编译个 clang 7.0.1 然后再编译看看

**Comment by clq1983** [comment]
好的，谢谢，辛苦辛苦

**Comment by nihui** [comment]
clang 7.0.1 无法生成asm的bitcode，尝试用 clang 8.0.0 ....

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/tree/163e2c065505b697418390fc9d5a11cab02c60ec

clang-8.0.0 编译的包，试试看，有问题或没问题都请回复下

[openmp.framework.zip](https://github.com/Tencent/ncnn/files/4443234/openmp.framework.zip)
[ncnn-vulkan.framework.zip](https://github.com/Tencent/ncnn/files/4443236/ncnn-vulkan.framework.zip)
[ncnn.framework.zip](https://github.com/Tencent/ncnn/files/4443239/ncnn.framework.zip)

**Comment by clq1983** [comment]
@nihui，目前使用上面最新支持bitcode版本，我在xcode11.1上打包生产版本是可以了，非常感谢。

**Comment by nihui** [comment]
> 
> 
> @nihui，目前使用上面最新支持bitcode版本，我在xcode11.1上打包生产版本是可以了，非常感谢。

太棒了！那么以后发release就这么打包了
