### ISSUE TITLE
hardsigmoid转换失败

### ISSUE THREAD

**Issue by sosopop** [Tencent/ncnn#1650]
github上搜索下 pytorch mobilenetv3
hardsigmoid hardswish 在转换时会自动识别的

_Originally posted by @nihui in https://github.com/Tencent/ncnn/issues/1646#issuecomment-603621839_

找了两个模型，我发现onnx转换的时候到这里判断失败
if (node2->op_type() != "Clip" || node3->op_type() != **"Div")
经查看实际节点类型是Clip, Constant, Div, Mul
是不是对torch版本有什么要求

**Comment by nihui** [comment]
请提供下onnx文件

**Comment by sosopop** [comment]
[models.zip](https://github.com/Tencent/ncnn/files/4380113/models.zip)

**Comment by nihui** [comment]
修好了~

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
