### ISSUE TITLE
Android使用vulkan时，应用崩溃了，报signal 11的错误。

### ISSUE THREAD

**Issue by mmjj2014** [Tencent/ncnn#1660]
Squeezenet的demo使用vulkan能正常运行。我的应用未使用vulkan时，也是能正常运行的，使用vulkan后，应用崩溃了，报signal 11的错误。vulkan的使用会跟模型有关吗？以下是错误日志。
 signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x28
 x0   0000000000000000  x1   000000769017fc20  x2   0000007661a00000  x3   0000000000000012
 x4   00000000000001d3  x5   0000000000000004  x6   000000767ed30b80  x7   000000767ed2dc80
 x8   000000765d029e90  x9   0000000000000003  x10  00000000000001d3  x11  0000000000000000
 x12  00000076615c1660  x13  0000007661bd3860  x14  0000000000000000  x15  0000000000000003
 x16  00000076911b65b0  x17  000000769115d95c  x18  0000000000001000  x19  000000766b5f7570
 x20  0000000000000000  x21  000000766b5fd018  x22  000000766b5f7380  x23  000000766b5f7320
 x24  000000766b5ff4e8  x25  0000000000000120  x26  0000000000000003  x27  0000000000000000
 x28  000000765e392940  x29  000000766b5f7160  x30  000000765d029e90
 sp   000000766b5f70f0  pc   000000765d029ec0  pstate 0000000060000000
 backtrace:
 #00 pc 00000000001aaec0  /data/app/com.wonxing.wonsege-1/lib/arm64/libncnnsege.so
 #01 pc 00000000000d3398  /data/app/com.wonxing.wonsege-1/lib/arm64/libncnnsege.so

**Comment by nihui** [comment]
请提供下param文件

**Comment by mmjj2014** [comment]
[potnet_128_sim.param.zip](https://github.com/Tencent/ncnn/files/4392954/potnet_128_sim.param.zip)
谢谢您的及时回复，param文件在zip包中，解压即可。

**Comment by nihui** [comment]
看了下是4通道输入的，pc和手机上都试了试，没发现有崩溃...
如果你输入3通道是会崩溃的
```
    ncnn::Extractor ex = net.create_extractor();

    ncnn::Mat in(128, 128, 4);
    ex.input("input.1", in);

    ncnn::Mat out;
    ex.extract("701", out);
```

**Comment by mmjj2014** [comment]
你真的很厉害一下子就定位到了。我再想请教一下，我使用的是input data是BGR排序，bitmap转mat代码如下：
inMat = ncnn::Mat::from_android_bitmap(env, bitmap, ncnn::Mat::PIXEL_RGBA2BGR);
现在我要怎么给inMat多添加一个通道，变为四通道？from_android_bitmap方法中，我找不到相应的type_to参数，BGR排序的似乎只有三通道，没有类似的BGRA。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/4d6cf47db818caadb604e19d7c9317475e5cf9f3

我把 BGRA 加上了

**Comment by mmjj2014** [comment]
好的，谢谢。
