### ISSUE TITLE
vulkan报段错误

### ISSUE THREAD

**Issue by lxb324** [Tencent/ncnn#1661]
[detector1.zip](https://github.com/Tencent/ncnn/files/4396796/detector1.zip)

cpu模式下没问题，ｖlukan包段错误代码如下：
#if NCNN_VULKAN
    ncnn::create_gpu_instance();
    detector.opt.use_vulkan_compute = true;
    detector.opt.lightmode=false;
    detector.set_vulkan_device(0);
#endif

    ncnn::Mat in;
    ncnn::Mat location;
    ncnn::Mat confidence;
    ncnn::Mat out;

    ncnn::resize_bilinear(img,in,det_w,det_h);
    const float mean_vals[3] = {127.5,127.5,127.5};
    in.substract_mean_normalize(mean_vals,0);
    ncnn::Extractor ex = detector.create_extractor();
    //ex.set_num_threads(num_threads);
    ex.input("data", in);
    ex.extract("output0", confidence);//出错的地方    
#if NCNN_VULKAN
    ncnn::destroy_gpu_instance();
#endif

**Comment by nihui** [comment]
请提供下param文件

**Comment by lxb324** [comment]
[detector1.zip](https://github.com/Tencent/ncnn/files/4400276/detector1.zip)

**Comment by nihui** [comment]
> [detector1.zip](https://github.com/Tencent/ncnn/files/4400276/detector1.zip)

这个没法下载，重新传下param

**Comment by lxb324** [comment]
[detector1.param.zip](https://github.com/Tencent/ncnn/files/4406235/detector1.param.zip)

**Comment by nihui** [comment]
写了个测试代码，没发现有错误，更新下ncnn试试看

```
#include <stdio.h>
#include <vector>

#include "net.h"
#include "datareader.h"
#include "gpu.h"

class DataReaderFromEmpty : public ncnn::DataReader
{
public:
    virtual int scan(const char* format, void* p) const { return 0; }
    virtual size_t read(void* buf, size_t size) const
    {
        memset(buf, 0, size);
        return size;
    }
};

static int detect_teststnet()
{
    ncnn::Net testnet;

    testnet.opt.use_vulkan_compute = true;

    testnet.load_param("detector1.param");

    DataReaderFromEmpty dr;
    testnet.load_model(dr);

    ncnn::Mat in(640, 640, 3);

    ncnn::Extractor ex = testnet.create_extractor();

    ex.input("data", in);

    ncnn::Mat output0;
    ncnn::Mat output1;

    ex.extract("output0", output0);
    ex.extract("output1", output1);

    fprintf(stderr, "output0 = %d %d %d\n", output0.w, output0.h, output0.c);
    fprintf(stderr, "output1 = %d %d %d\n", output1.w, output1.h, output1.c);

    return 0;
}

int main(int argc, char** argv)
{
    ncnn::create_gpu_instance();

    detect_teststnet();

    ncnn::destroy_gpu_instance();

    return 0;
}
```

**Comment by nihui** [comment]
如果还有问题，可以 reopen issue 继续讨论
