### ISSUE TITLE
新版本 Cilp Op 异常

### ISSUE THREAD

**Issue by Xyzhao1999** [Tencent/ncnn#1666]
你好！在上次修复 #1640 后，最终图像结果异常，最后发现似乎是Clip Op有异常。

左边为旧版本的结果，右边为新版转换的结果。

![image](https://user-images.githubusercontent.com/23482405/77985629-93eee280-7347-11ea-86da-c615b23be427.png)

![image](https://user-images.githubusercontent.com/23482405/77985598-7c175e80-7347-11ea-957d-7a0c9766d6be.png)

**Comment by nihui** [comment]
看图，右边才是正常的 Clip
