### ISSUE TITLE
win10_64位系统用VS2013编译20200226：不知道如何生成“\openmp

### ISSUE THREAD

**Issue by pengfeidip** [Tencent/ncnn#1669]
仿照2017的教程，之前的步骤执行正常，但是：

在ncnn里面执行 `nmake`命令 的时候，出现错误  `NMAKE : fatal error U1073: 不知道如何生成“\openmp` .

**Comment by pengfeidip** [comment]
我在CMakeLists.txt里面把openmp给关了，不用这个就可以正常编译。请问：
1. openmp在这里面的作用是什么？
2. 该如何解决这个问题呢?

**Comment by pengfeidip** [comment]
之前用的 20200226版本的代码有问题，用的最新的代码就没有问题了

**Comment by suzj-hash** [comment]
@pengfeidip 请问不关闭openmp这个问题是如何解决的？
