### ISSUE TITLE
pytorch mobile-v2-ssd-lite.onnx 转 ncnn后，某个crop layer无法正确返回结果，显示shape : 0,0,0。

### ISSUE THREAD

**Issue by handoku** [Tencent/ncnn#1670]
转模型过程：pytorh -> mobile-v2-ssdlite.onnx -> onnxsim -> onnx -> ncnn.

转换之后进行测试，extract scores 和 boxes，发现有输出scores，但boxes的shape是（0,0,0）。
![image](https://user-images.githubusercontent.com/16758743/78110815-38e3eb00-742e-11ea-8120-9439860036a4.png)

二分手动extract 某些blob，最终定位到两个crop layer没有正确输出。

extract 852：
![image](https://user-images.githubusercontent.com/16758743/78111200-e3f4a480-742e-11ea-8c8a-f390b0ad841c.png)
这里extract blob 852还会导致 extract boxes出错。

extract 857：
![image](https://user-images.githubusercontent.com/16758743/78111597-7d23bb00-742f-11ea-90ad-e56ec794f7a6.png)

对应param信息如下
![image](https://user-images.githubusercontent.com/16758743/78111752-b5c39480-742f-11ea-8eae-be13688c4c78.png)

转换前onnx的neutron可视化：
![image](https://user-images.githubusercontent.com/16758743/78111983-1d79df80-7430-11ea-80e3-7e1a53a00427.png)

转换后param的可视化：
![image](https://user-images.githubusercontent.com/16758743/78112107-4e5a1480-7430-11ea-9379-5ea4daac79d7.png)

我比较奇怪，同样位置的slice -> crop过后的blob 851和856的结果是正常的。花了些时间看crop.cpp里的些东西。不过还是不太理解param里key对应value的含义。

请教大神，这里的问题是出在哪儿，是原模型的代码有些问题，还是转换时导出的key-value参数有误。指点一下，感激不尽~

**Comment by handoku** [comment]
又看了看别的blob，问题其实不止这两个。scores虽然有输出，但也是有问题，每次同样的图片输出都不同，结果是随机的。不知道应该如何修正。寻求帮助。

我用的pytorch模型，来自https://github.com/qfgaohao/pytorch-ssd，可以通过 
`wget  https://storage.googleapis.com/models-hao/mb2-ssd-lite-mp-0_686.pth `
下载
onnxsim转化后的onnx：
`https://drive.google.com/open?id=14gmZENrr8jgRGk_FDsLg_CNDzaJNDxP9`

**Comment by handoku** [comment]
ok，经过反复的extract layer，我终于找到了问题的原因，原因并不在我上图的层中，实际出现在更早的crop layer。

crop layer实现了numpy style的切片功能，但存在一个小bug。我的代码里是二维的情况，
所以举一个简单的例子: 

有一个shape为(2, 4)的 num
```
[[1, 2, 3, 4],
[1, 2, 3, 4]]
``` 

那么num[, 2:] =
```
[[3, 4]，
[3,4]] 
```
shape = (2, 2).

然而，我在crop.cpp里发现了这样的代码：

```
// when dims == 2
_woffset = start >= 0 ? start : w + start;
_outw = std::min(w, end > 0 ? end : w + end) - _woffset;
```
_outw 是用来保存切片后的长度的，即切片结果中w这一维度的长度，例子里_outw应该等于2。
经过onnx2ncnn工具转化后，这里的start = 2， end = -1 (对应numpy 的 [2:-1])
问题就出现了:
```
_outw = w+ end - start
= 4 + (-1) - 2
= 1
```
显然，这是错误的。

因此我将代码改为
```
// when dims == 2
_woffset = start >= 0 ? start : w + start;
_outw = std::min(w, end > 0 ? end : w + end + 1) - _woffset;
```

重新编译，解决了我的模型问题。

如果有遇到同样crop layer问题的朋友可以参考看看。

这个bug应该可以通过简单+1解决，但我不清楚其他style转模型后的参数是否也是这种情况
请大佬看看，@nihui。有时间还麻烦修正qaq 。

**Comment by nihui** [comment]
太强了 qaq

**Comment by handoku** [comment]
大佬，crop_arm的实现似乎还有别的bug。单单改了resolve_crop_roi函数，在arm平台上run还是有问题的。
我用的模型可以从这下载 https://drive.google.com/open?id=14gmZENrr8jgRGk_FDsLg_CNDzaJNDxP9
烦请大佬看看。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
