### ISSUE TITLE
基于VULKAN编译后没有example和tool

### ISSUE THREAD

**Issue by iotsharer** [Tencent/ncnn#1671]
##  操作1 有VULKAN：

> git clone https://github.com/Tencent/ncnn.git
cd ncnn && mkdir -p build && cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake -DNCNN_VULKAN=ON -DCMAKE_BUILD_TYPE=Release ..
make -j`nproc`
sudo make install
## 结果：
![image](https://user-images.githubusercontent.com/29347606/78140059-ffc26f80-745b-11ea-8982-b1eeb12ebaac.png)
## 操作2 无VULKAN：
`cmake..
make -j4`
## 结果：
![image](https://user-images.githubusercontent.com/29347606/78140562-ca6a5180-745c-11ea-8724-428a49909cf3.png)
在这种情况下运行example无法使用VULKAN
## 目的
想请教使用VULKAN编译后如何运行example，以及其他tool

**Comment by pengfeidip** [comment]
我也遇到VULKAN的问题：
windows10_64bit 带有VULKAN编译失败（已经安装了VULKAN）, 停在了cmake时候的find_package（VULKAN）
