### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Tencent/ncnn#1673]
Stream is opened
https://github.com/Tencent/ncnn/blob/07170542c97b6ef616a53ce945eef3fada92d560/tools/ncnn2mem.cpp#L79
Opened file never closed
https://github.com/Tencent/ncnn/blob/07170542c97b6ef616a53ce945eef3fada92d560/tools/ncnn2mem.cpp#L103

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/issues/4690
