### ISSUE TITLE
abiFilters只留arm64-v8a，项目能运行，abiFilters "armeabi-v7a", "arm64-v8a"项目就编译出错了

### ISSUE THREAD

**Issue by 7hundeR** [Tencent/ncnn#1676]
错误日志在下：
···
Build command failed.
Error while executing process D:\Android\SDK\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C D:\itst\android\Cotton\app\.cxx\cmake\debug\armeabi-v7a cotton}
ninja: Entering directory `D:\itst\android\Cotton\app\.cxx\cmake\debug\armeabi-v7a'
[1/2] Building CXX object CMakeFiles/cotton.dir/cotton_jni.cpp.o
[2/2] Linking CXX shared library D:\itst\android\Cotton\app\build\intermediates\cmake\debug\obj\armeabi-v7a\libcotton.so
FAILED: D:/itst/android/Cotton/app/build/intermediates/cmake/debug/obj/armeabi-v7a/libcotton.so 
cmd.exe /C "cd . && D:\Android\NDK\android-ndk-r19c\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi24 --gcc-toolchain=D:/Android/NDK/android-ndk-r19c/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/Android/NDK/android-ndk-r19c/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -fno-addrsig -march=armv7-a -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++  -fopenmp -fomit-frame-pointer -fstrict-aliasing -ffast-math -fvisibility=hidden -fvisibility-inlines-hidden -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now  -fopenmp -shared -Wl,-soname,libcotton.so -o D:\itst\android\Cotton\app\build\intermediates\cmake\debug\obj\armeabi-v7a\libcotton.so CMakeFiles/cotton.dir/cotton_jni.cpp.o  D:/itst/android/Cotton/app/src/main/jni/ncnn-android-vulkan-lib/armeabi-v7a/libncnn.a -landroid -lz -llog -ljnigraphics -lvulkan D:/itst/android/Cotton/app/src/main/jni/../jniLibs/armeabi-v7a/libopencv_java3.so -latomic -lm && cd ."
D:/Android/NDK/android-ndk-r19c/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: D:/itst/android/Cotton/app/src/main/jni/ncnn-android-vulkan-lib/armeabi-v7a/libncnn.a(allocator.cpp.o): incompatible target
D:/Android/NDK/android-ndk-r19c/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: D:/itst/android/Cotton/app/src/main/jni/ncnn-android-vulkan-lib/armeabi-v7a/libncnn.a(gpu.cpp.o): incompatible target
D:/Android/NDK/android-ndk-r19c/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: D:/itst/android/Cotton/app/src/main/jni/ncnn-android-vulkan-lib/armeabi-v7a/libncnn.a(net.cpp.o): incompatible target
D:/Android/NDK/android-ndk-r19c/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: D:/itst/android/Cotton/app/src/main/jni/ncnn-android-vulkan-lib/armeabi-v7a/libncnn.a(option.cpp.o): incompatible target
D:/Android/NDK/android-ndk-r19c/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: D:/itst/android/Cotton/app/src/main/jni/ncnn-android-vulkan-lib/armeabi-v7a/libncnn.a(benchmark.cpp.o): incompatible target
D:/Android/NDK/android-ndk-r19c/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: D:/itst/android/Cotton/app/src/main/jni/ncnn-android-vulkan-lib/armeabi-v7a/libncnn.a(mat_pixel_android.cpp.o): incompatible target
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:371: error: undefined reference to 'ncnn::create_gpu_instance()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:379: error: undefined reference to 'ncnn::destroy_gpu_instance()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:386: error: undefined reference to 'ncnn::Option::Option()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:399: error: undefined reference to 'ncnn::get_gpu_count()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:408: error: undefined reference to 'ncnn::Net::load_param_bin(AAssetManager*, char const*)'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:417: error: undefined reference to 'ncnn::Net::load_model(AAssetManager*, char const*)'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:429: error: undefined reference to 'ncnn::get_gpu_count()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:434: error: undefined reference to 'ncnn::get_current_time()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:447: error: undefined reference to 'ncnn::Mat::from_android_bitmap_resize(_JNIEnv*, _jobject*, int, int, int, ncnn::Allocator*)'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:460: error: undefined reference to 'ncnn::Net::create_extractor() const'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:461: error: undefined reference to 'ncnn::Extractor::set_vulkan_compute(bool)'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:462: error: undefined reference to 'ncnn::Extractor::input(int, ncnn::Mat const&)'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:464: error: undefined reference to 'ncnn::Extractor::extract(int, ncnn::Mat&)'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:465: error: undefined reference to 'ncnn::Extractor::~Extractor()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:521: error: undefined reference to 'ncnn::get_current_time()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:465: error: undefined reference to 'ncnn::Extractor::~Extractor()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:534: error: undefined reference to 'ncnn::get_current_time()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:568: error: undefined reference to 'ncnn::get_current_time()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:21: error: undefined reference to 'ncnn::UnlockedPoolAllocator::UnlockedPoolAllocator()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:0: error: undefined reference to 'ncnn::UnlockedPoolAllocator::~UnlockedPoolAllocator()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:22: error: undefined reference to 'ncnn::PoolAllocator::PoolAllocator()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:0: error: undefined reference to 'ncnn::PoolAllocator::~PoolAllocator()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:24: error: undefined reference to 'ncnn::Net::Net()'
D:/itst/android/Cotton/app/src/main/jni/cotton_jni.cpp:0: error: undefined reference to 'ncnn::Net::~Net()'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
···

**Comment by nihui** [comment]
需要 armv7 的 libncnn.a
可以参考这个工程
https://github.com/nihui/ncnn-android-squeezenet

**Comment by 7hundeR** [comment]
更改了minSdkVersion为22  ,后报错：
```
error: cannot find -lvulkan
```

**Comment by nihui** [comment]
vulkan 需要 24或以上

**Comment by 7hundeR** [comment]
明白了，之前导入的是“ncnn-android-vulkan-lib.zip”，改成“ncnn-android-lib.zip”这个包就好了
