### ISSUE TITLE
ndk-r16编译的android-22的ncnn库，在3399上运行运行结果和3288不一致？

### ISSUE THREAD

**Issue by DevelopJoy** [Tencent/ncnn#1677]
和pc上的ncnn-x86测试结果（特征的数值范围在-3-3）做的对比:
3399上的结果和pc上的运行结果误差平均<0.05；
3288上的运行结果和pc上的运行结果误差平均在0.5左右。
大佬们知道啥原因导致的吗？

**Comment by nihui** [comment]
更新最新的ncnn代码编译看看，我没有发现这种问题
另外，可以把有问题的模型 param 上传下，方便复现

**Comment by DevelopJoy** [comment]
更新了最新的代码，这个问题还是存在。模型好像用的是以前版本的ncnn转换的，我再试试全部更新成最新的。
[test1.zip](https://github.com/Tencent/ncnn/files/4441753/test1.zip)

**Comment by DevelopJoy** [comment]
您好，重新测试了一下，还是存在差别。
下面是部分输出值。输出值的越大，3288上的误差会增大
3288:-1.41393 1.24892 1.19096 -0.634688 1.20161 -1.18296 1.80551 0.645798 0.694023 
3399:-1.57381 1.41171 1.33017 -0.706755 1.25774 -1.30246 1.89132 0.833672 0.832454 
pc:     -1.54528 1.37137 1.29672 -0.684835 1.239    -1.30575 1.88679 0.795904 0.812572

**Comment by nihui** [comment]
close 是表示问题解决了？

**Comment by DevelopJoy** [comment]
传入数据的差别，opencv340和331导致图像处理上数据有偏差，单独生成数据验证建模，结果差别不大。现在新的验证结果和之前发的不同，避免误导其他人，所以就关掉了。
