### ISSUE TITLE
ncnn的目标检测模型怎么测map?

### ISSUE THREAD

**Issue by luoduo21** [Tencent/ncnn#1678]
如voc数据集上的模型，请问有测试代码吗？还是需要自己实现

**Comment by nihui** [comment]
ncnn只是推理计算库，不提供这个功能，测模型精度可以用 pytorch caffe 的相关算法实现代码，通常都会有 python 脚本做这个事情

**Comment by kadebudongtan** [comment]
> 如voc数据集上的模型，请问有测试代码吗？还是需要自己实现

你解决了吗？有测试代码吗？
