### ISSUE TITLE
inference in chaos state and log "out of compute queue" when using in multi-thread with vulkan GPU compute

### ISSUE THREAD

**Issue by leoluopy** [Tencent/ncnn#1682]
in my product case , i use multi-thread inference with multi vulkan instance and this problem occurs , how can i solve it ? wait for some tips online...

**Comment by nihui** [comment]
You can query the max gpu thread count via vkdev->info.compute_queue_count;
integrated gpu usually has small threading capability
If you spawn too many threads, some workloads have to wait others to finish before they can be submitted.

https://github.com/Tencent/ncnn/wiki/vulkan-notes#batch-inference

**Comment by nihui** [comment]
addressed in https://github.com/Tencent/ncnn/commit/1469bc8b19b83d44206f36abfa3dc7377feeef69

This error shall be rear now
