### ISSUE TITLE
ncnn-android-vulkan-lib.zip下载太慢，有没有网盘资源？

### ISSUE THREAD

**Issue by xiakj** [Tencent/ncnn#1683]
https://github.com/Tencent/ncnn/releases/tag/20200226
这里面的ncnn-android-vulkan-lib.zip在浏览器下载太慢，能否提供一个更容易下载的资源，网盘或者单独申请？

**Comment by nihui** [comment]
你可以用各个网盘的离线下载功能
或者加qq群问问呢

**Comment by xiakj** [comment]
@nihui 网盘、迅雷都下载不动这个。您能传给我一份吗，xiakejiang@126.com，谢谢

**Comment by nihui** [comment]
qq群号码在github主页readme底下有，加一下
