### ISSUE TITLE
最新的ncnn版本在树莓派4b上benchmark报错

### ISSUE THREAD

**Issue by hyaihjq** [Tencent/ncnn#1684]
release20191113 和20190908测试都是可以benchmark成功的，20200106编译不通过，20200206benchmark mobilenet时段错误

**Comment by shaoxiang** [comment]
类似，release 20200413在Jetson nano上测benchmark时段错误，但是20200206测试都是可以的

**Comment by Sanbao1052** [comment]
请问，在树莓派4B上是用的Ubuntu吗，在4B上测试目标检测网络有可以达到实时的吗，每秒能跑多少帧

**Comment by hyaihjq** [comment]
> 请问，在树莓派4B上是用的Ubuntu吗，在4B上测试目标检测网络有可以达到实时的吗，每秒能跑多少帧

不能实时，两帧左右

**Comment by shaoxiang** [comment]
> > 请问，在树莓派4B上是用的Ubuntu吗，在4B上测试目标检测网络有可以达到实时的吗，每秒能跑多少帧
> 
> 不能实时，两帧左右
>
所以Jetson平台还是用tensorrt吗？还有更快的吗？

**Comment by shaoxiang** [comment]
> > 请问，在树莓派4B上是用的Ubuntu吗，在4B上测试目标检测网络有可以达到实时的吗，每秒能跑多少帧
> 
> 不能实时，两帧左右
>
所以Jetson平台还是用tensorrt吗？还有更快的吗？

**Comment by hyaihjq** [comment]
> > > 请问，在树莓派4B上是用的Ubuntu吗，在4B上测试目标检测网络有可以达到实时的吗，每秒能跑多少帧
> > 
> > 
> > 不能实时，两帧左右
> 
> 所以Jetson平台还是用tensorrt吗？还有更快的吗？

tensorrt吧，其他感觉速度都一般

**Comment by 2684160504** [comment]
> > 请问，在树莓派4B上是用的Ubuntu吗，在4B上测试目标检测网络有可以达到实时的吗，每秒能跑多少帧
> 
> 不能实时，两帧左右
请问树莓派上哪种网络的检测速度是最好的？

**Comment by hyaihjq** [comment]
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB

> > > 请问，在树莓派4B上是用的Ubuntu吗，在4B上测试目标检测网络有可以达到实时的吗，每秒能跑多少帧
> > 
> > 
> > 不能实时，两帧左右
> > 请问树莓派上哪种网络的检测速度是最好的？

https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB，魔改的SSD
