### ISSUE TITLE
How is GPU automatically used ?

### ISSUE THREAD

**Issue by PrashantDandriyal** [Tencent/ncnn#1687]
Hi, I have been planning to use the NCNN library on a Raspberry Pi or a BeagleBone device. In the _benchmark_ section, I see that the tests have been performed with and without using the GPU (on-device). 

I can't understand how the library automatically looks for any available GPUs and distributes work among them and the CPUs...
Also, if I use it on some random GPU-supported device (not mentioned in the benchmark devices), how can I be sure that the GPUs **WILL** indeed be used ?

Any help is welcomed :)

**Comment by nihui** [comment]
If your device supports the vulkan api, could be checked via vulkaninfo tool or https://vulkan.gpuinfo.org, then the gpu CAN be used by ncnn library.

ncnn provides api to get the available gpu info and a switch to turn on/off the gpu inference part at runtime. You can control whether the gpu could be used or not.

reference https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan

**Comment by PrashantDandriyal** [comment]
Oh thanks @nihui The FAQ was useful. I plan to use your library with BeagleBone Boards. Unfortunately, they don't have good GPUs; instead they possess other co-processors like DSPs, PRUs and EVEs. 

Regarding
>The current vulkan inference implementation is far from the preferred state. Many handful optimization techniques are planned, such as winograd convolution, operator fusion, fp16 storage and arithmetic etc.

Are these optimizations completed and added to the library ?

**Comment by nihui** [comment]
It will be in a good state in the next coming release
