### ISSUE TITLE
使用ncnn-android-vulkan-lib 编译出错

### ISSUE THREAD

**Issue by zsliaoming** [Tencent/ncnn#1690]
./native/libs/ncnn-android-lib/armeabi-v7a/libncnn.a(pipeline.cpp.o):pipeline.cpp:function ncnn::Pipeline::create_descriptorset_layout(int): error: undefined reference to 'vkCreateDescriptorSetLayout'

**Comment by nihui** [comment]
You can refer this sample project https://github.com/nihui/ncnn-android-squeezenet

The vulkan support needs android api version >= 24
