### ISSUE TITLE
only texture read utilize L1 cache on qcom adreno

### ISSUE THREAD

**Issue by nihui** [Tencent/ncnn#1694]
- [ ] bug for storage buffer without L1 cache
- [x] resolve image binding count from spirv
- [x] create pipeline with proper image binding descriptor
- [x] create pipeline with proper sampler
- [x] mutable image layout member in VkImageMemory
- [x] better VkImageMat allocator
- [x] optional copy to VkImageMat in upload_model
- [x] VkCompute record copy VkMat to VkImageMat
- [x] VkCompute record copy VkImageMat to VkMat~~
- [x] VkCompute record pipeline with image bindings
- [x] convolution pack4 image shader
- [x] deconvolution pack4 image shader
- [x] innerproduct pack4 image shader
- [x] convolution vulkan record image pipeline
- [x] deconvolution vulkan record image pipeline
- [x] innerproduct vulkan record image pipeline

**Comment by gaozp1123** [comment]
好多工作，up加油

**Comment by nihui** [comment]
https://github.com/nihui/ncnn/tree/adreno

**Comment by nihui** [comment]
merged in https://github.com/Tencent/ncnn/commit/62da1228e1999a1dd7bc7d1fccd0eff9ef422e69
