### ISSUE TITLE
gpu count

### ISSUE THREAD

**Issue by fxj8911** [Tencent/ncnn#1696]
为什么get_gpu_count总是0

**Comment by nihui** [comment]
What is your graphics card and your system platform ?

The vulkan api is supported from android 7.0

try upgrading the graphics driver if you are using pc
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan

**Comment by fxj8911** [comment]
i ran offical sequeeze demo found gpu count is one，but when i use my jni so could not found gpu account.by the
 way i use vulkan ncnn static library

**Comment by nihui** [comment]
There is something wrong in your project
You can refer the gradle configuration in https://github.com/nihui/ncnn-android-squeezenet

**Comment by fxj8911** [comment]
i mean darknet2ncnn project can not use gpu on android

**Comment by liulai** [comment]
> What is your graphics card and your system platform ?
> 
> The vulkan api is supported from android 7.0
> 
> try upgrading the graphics driver if you are using pc
> https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan

i upgraded my driver(26.20.100.7323), but get_gpu_count always is 0,
Inter(R) HD Graphics 620(win10)

**Comment by nihui** [comment]
Use the new darknet2ncnn tool here https://github.com/Tencent/ncnn/tree/master/tools/darknet
feel free to reopen issue if the problem still occurs
