### ISSUE TITLE
vulkan版ncnn模型加载耗时长

### ISSUE THREAD

**Issue by sherlockgjh** [Tencent/ncnn#1708]
您好，我这边尝试在android端掉用vulkan版的ncnn，但模型加载耗时就占用了5-6s，而使用cpu模式，模型加载仅需要100ms左右。请问，这个是正常的吗？

**Comment by Bloodhoofwow** [comment]
主要是load_model耗时
例如：int ret = squeezenet.load_model(mgr, "squeezenet_v1.1.bin");一般耗时要3s以上

**Comment by nihui** [comment]
已实现 online pipeline cache，现在应该会快很多了

**Comment by yg1031** [comment]
> 

您好，现在使用的是ncnn-20221128，在rk3568上使用vulkan加速时，模型加载还是需要5s左右，而使用cpu推理模型加载时间则不到200ms，请问需要改什么地方？

**Comment by yg1031** [comment]
> 已实现 online pipeline cache，现在应该会快很多了

您好，现在使用的是ncnn-20221128，在rk3568上使用vulkan加速时，模型加载还是需要5s左右，而使用cpu推理模型加载时间则不到200ms，请问需要改什么地方？

**Comment by yg1031** [comment]
> 已实现 online pipeline cache，现在应该会快很多了
您好，现在使用的是ncnn-20221128，模型基于yolov5n训练，大小3MB左右，在安卓rk3568上使用vulkan推理，模型加载还是需要5s左右，而使用cpu推理，模型加载时间则不到200ms，请问可以缩短vulkan下的模型加载时间吗？
