### ISSUE TITLE
arm convolution_8bit的代码是否有bug

### ISSUE THREAD

**Issue by cszhj1990** [Tencent/ncnn#1715]
src/layer/arm/convolution_sgemm_int8.h文件的1967到1970中使用的 v4.h，是不是应该是从0-3，而不是现在的0，0,1,1

**Comment by tpoisonooo** [comment]
1. 1967-1970 看着的确不太对， @BUG1989  确认一下；
2. `convolution_sgemm_int8.h` 目前生效的代码只有前 87 行，建议用个 IDE 看代码，好的工具省时省力。

**Comment by tpoisonooo** [comment]
FYI: 目前用的 vscode 感觉还不错，支持 linux，再加个 C++/Remote 插件基本够用。已抛弃 vim。

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新
