### ISSUE TITLE
use_packing_layout=1 cause quantized model error output in arm

### ISSUE THREAD

**Issue by lsdustc** [Tencent/ncnn#1719]
更正一下 之前问题没有定位清楚
我们在测试量化好的int8模型时发现在arm平台上的结果输出完全错误，浮点模型在arm上工作量化，而别的平台却没有这种问题。
经过反复调试我们发现在每个layer执行完，由于默认的opt配置了use_packing_layout=1,会对一个计算好的blob_mat进行一次convert_packing，见net.cpp 1245 行，在这个op之后我们发现在x86上bottom_blobs数据类型大小为4u（float），每一层的输出shape和python下也是一致的，但是在arm上却有问题，表现为数据类型大小为16u，扩大了4倍 shape缩减未原来的1/4，在下一层的运算中直接导致只计算其中前1/4的网络连接，最终结果完全错误，目前我们在声明 Net时关闭了use_packing_layout 暂时解决了问题

**Comment by nihui** [comment]
int8 目前不支持 packing layout，所以必须关闭才能用
