### ISSUE TITLE
Extractor default number of threads?

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#1720]
I see most tutorials setting the number of threads for an extractor using the following:
```
ncnn::Net net;
ncnn::Extractor ex = net.create_extractor();
ex.set_num_threads(4);
```

My question is regarding the default behavior if we do not specify the number of threads using `set_num_threads`.

The comments above the function deceleration state that the "default count is system dependent". 

Can you elaborate more on what the default behavior is. Does it use all available threads by default? Does it use as many threads as there are cores?

Will we get the best performance on our system if we just use the default? Or is it best practice to set it ourselves using `set_num_threads`?

**Comment by nihui** [comment]
The default value is what the ncnn::get_cpu_count() returns
In most opemmp enabled build, it is the cpu core count

It depends on your cpu and your model.
4 threads setting is usually a sweetpot as mobile cpus usually have 4 big + 4 small cores. Worker threads will probably spill on small cores in 8 threads setting, that results slower speed than 4 threads.

In addition, large model is more suitable with high thread count setting. If the model is very tiny, one thread may be the best, as thread scheduling overhead can be high.

**Comment by cyrusbehr** [comment]
Thank you!

**Comment by zengjie617789** [comment]
what about kirin chips which has 1 big + 3 midium + 4 small cores?
