### ISSUE TITLE
最新版本在x86平台下的cpu利用率问题

### ISSUE THREAD

**Issue by fidmail** [Tencent/ncnn#1721]
最新版本因为默认打开了use_packing_layout，最近在x86下测试发现CPU利用率会很高，即使只设置1线程计算，CPU利用率也在500%以上（i7@4核8线程），后来定位到与use_packing_layout有关，关闭use_packing_layout就正常。
而arm下没这个问题。

**Comment by nihui** [comment]
旧版本ncnn的 packing 层没有遵循线程数设置，最新版本已修复，推荐更新。
如有问题，请 reopen issue 继续交流

**Comment by fidmail** [comment]
收到，感谢nihui！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/ncnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 下午4:31
收件人:&nbsp;"Tencent/ncnn"<ncnn@noreply.github.com&gt;;
抄送:&nbsp;"909501376"<fidmail@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/ncnn] 最新版本在x86平台下的cpu利用率问题 (#1721)





 
Closed #1721.
