### ISSUE TITLE
关于关闭int8的推理问题

### ISSUE THREAD

**Issue by onesnow123q** [Tencent/ncnn#1722]
![image](https://user-images.githubusercontent.com/30360420/80295284-462d9480-87a4-11ea-984b-523b03034dfe.png)
请教一下，图片中的the runtime model only是什么意思呢？？
看wiki这里加载的是fp32的模型，将use_int8_inference 设置为0，就是不使用int8推理，使用fp32的推理，有个疑惑，就是本身这里加载的就是fp32模型，为什么还要设置这个参数呢？ 
是否可以加载int8的模型然后设置该参数使其使用fp32的推理？？
望各位明白的人解答一下~~

**Comment by onesnow123q** [comment]
啊，理解错误，这里是加载了int8的模型，不好意思
但是利用自己的模型（pytorch-->onnx-->onnx-sim -->ncnn）转成int8后，设置use_int8_inference=0， 获得的结果是nan，但是int8跑出来的结果是有的，这个是什么原因呢？？使用的是tag 20200413

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
