### ISSUE TITLE
convert model from pytorch -> onnx -> onnxsim -> ncnn, but lose the accuracy

### ISSUE THREAD

**Issue by niezhongliang** [Tencent/ncnn#1725]
@nihui Hi, thanks for your great job at first. I follow the tutorial step by step. But the ncnn model's output is different from my onnx-sim model. Is there any suggestions about it.

some details about my model. 
1. torchvision official implementation of mobilenet v2 (torchivision 0.3) 
2. use the correct pre-process of the image, follow the wiki.

[Desktop.zip](https://github.com/Tencent/ncnn/files/4535219/Desktop.zip)

**Comment by niezhongliang** [comment]
has

**Comment by SatMa34** [comment]
i have met the same problem, have you solved this? 
the input of pytorch and ncnn is exactly the same, but the outputs are different from the first decimal point.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
