### ISSUE TITLE
关于maxpool3d的疑问

### ISSUE THREAD

**Issue by cvwoker** [Tencent/ncnn#1726]
看lprnet，发现设计了maxpool3d。导致无法在ncnn中使用；

从分离卷积的角度看：
完全可以增加一个 2个向量的maxpool1d函数，这个实现很简单。
maxpool3d =   先通道间的maxpool1d ，再常规的通道内的maxpool2d
这样操作也很适合移动端。

不知道有没有这个计划。
往后的发展，这种3D算子应该会越来越多，不跟进有点限制了ncnn应用范围

**Comment by nihui** [comment]
maxpool3d 已实现
