### ISSUE TITLE
请问一下ncnn支持不规则的卷积核吗？1*N，N*1这种

### ISSUE THREAD

**Issue by Wong-Charles** [Tencent/ncnn#1727]
大神你好，我参照指南，生成了param和bin文件，然后部署到设备上发现结果不一致，排查之后发现第一层卷积输出的结果就不一致，
在pytorch中我的输入size是1x20x394x1（NCHW），卷积核size是512x20x5x1，无padding步长1，输出size是1x512x390x1
在ncnn中我的输入是394x1x20，第一层卷积输出size是390x1x512。

我仔细对比了一下两个输出结果，发现不一致，我怀疑是生成的bin文件有问题，下面是我用python生成bin文件的代码：
```python
def save_conv2d(layer, fid):
    # write flag to bin
    flag = 0
    flag = struct.pack('I', flag)
    fid.write(flag)

    # write weight to bin
    weight = layer.weight.data.detach().numpy()
    weight = weight.flatten().astype(np.float32)
    # print(weight[:20])
    weight.tofile(fid)
    
    #write bias to bin
    bias = layer.bias.data.detach().numpy().reshape(-1).astype(np.float32)
    bias.tofile(fid)
```
奇怪的是，我同学用了相似的代码生成bin文件，得到的ncnn的结果和pytorch的结果一致，他用的是相同大小的卷积核5x5。

**Comment by un-knight** [comment]
netron 可视化的结果会有点奇怪，不过我看过 param 里边的 conv 操作的后面的 layer parameter 是正确的，而且我测试的计算结果也一致的

**Comment by Wong-Charles** [comment]
> 我看过 param 里边的 conv 操作的后面的 layer parameter 是正确的，而且我测试的计算结果也一致的

感谢回复，我验证了一下，ncnn是支持1*N的卷积的。

**Comment by un-knight** [comment]
> > 我看过 param 里边的 conv 操作的后面的 layer parameter 是正确的，而且我测试的计算结果也一致的
> 
> 感谢回复，我验证了一下，ncnn是支持1*N的卷积的。

不过这种特殊的卷积，效率应该也比较一般

**Comment by Wong-Charles** [comment]
> 不过这种特殊的卷积，效率应该也比较一般

嗯，效率确实一般。我之前对不齐的原因是这个：https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#blob-may-have-channel-gap，希望看到的人能避免这个坑。

**Comment by nihui** [comment]
net.opt.use_packing_layout = true 会稍微优化一下下....
