### ISSUE TITLE
ReLU6转换出错的问题

### ISSUE THREAD

**Issue by yuanyangxue** [Tencent/ncnn#1728]
我的MobileNet 模型使用了relu6，用caffe训练，通过ncnn转换成.bin和.param 文件，在.param文件中的relu6 已经被自动转成了clip操作，但运行网络 inference  的时候程序直接崩溃了（显示Segmentation fault），能帮忙解答一下吗

**Comment by Sejudyblues** [comment]
目前我用pytorch训练出来的mobilenetV2转到ncnn做推理，没有遇到做推理的时候程序崩溃。

**Comment by BUG1989** [comment]
应该不会崩溃，clip layer很简单的

**Comment by nihui** [comment]
建议使用 pytorch 配合 pnnx 转换工具
