### ISSUE TITLE
Get segmentation fault when using onnx2ncnn

### ISSUE THREAD

**Issue by un-knight** [Tencent/ncnn#1729]
The code causing segmentation fault is `torch.bmm` op. So does ncnn support `torch.bmm` or  `torch.mm` which is `GEMM` or `MatMul` in ONNX?

Here is the target onnx file:
[mm.zip](https://github.com/Tencent/ncnn/files/4545622/mm.zip)

Then I debug onnx2ncnn with gdb, and get the following information:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555a3fca in onnx::TensorProto::_internal_dims (this=0x55555587fc30, index=-1)
    at /home/xxx/Codes/ncnn/debug/tools/onnx/onnx.pb.h:6244
6244      return dims_.Get(index);
```

**Comment by aoru45** [comment]
Yes I have the same problem. Have you solved it?

**Comment by nihui** [comment]
The latest onnx2ncnn greatly improved the compatibility of MatMul and GEMM conversion
Try updating ncnn

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
