### ISSUE TITLE
你好，大神，NCNN的crop层不太懂

### ISSUE THREAD

**Issue by EdwardVincentMa** [Tencent/ncnn#1736]
感谢大神解答，我看了Crop层NCNN源码，没看明白这个参数。例如.param文件里crop层如下：

Crop  slice_axis13   1 1 softmax1 slice_axis13 -23309=1,0 -23310=1,1 -23311=1,1

这里的23309=1,0 -23310=1,1 -23311=1,1 分别代表什么，为什么09 10 11前面要加-233？
当然我知道09是starts，10是ends，11是axis。那么为什么前面加-233？

在caffe的prototxt里面应该如何对应？
caffe 的 Crop 层参数只有axis 和 offset，并没有starts 和 ends，不太懂在caffe里面应该怎么写这一层的prototxt文件。也就是问 NCNN Crop 层里面的 starts ends 分别对应caffe Crop层的哪个参数？

**Comment by nihui** [comment]
-233 前缀表示是数组

https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure

crop的starts ends axis是onnx中 slice 的参数
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Slice

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
