### ISSUE TITLE
Compile at Mac OSX with vulkansdk-macos-1.2.135.0

### ISSUE THREAD

**Issue by DickyQi** [Tencent/ncnn#1738]
compile with vulkansdk-macos-1.2.135.0, runtime error such as
program_source:176:1972: error: cannot reserve 'sampler' resource location at index 0
program_source:176:1720: error: cannot reserve 'texture' resource location at index 1
program_source:185:148: error: cannot reserve 'buffer' resource location at index 0
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
vkCreateComputePipelines failed -1000012000

**Comment by nihui** [comment]
please use 20200413 tag 
https://github.com/Tencent/ncnn/tree/20200413

It shall be a compatibility issue in shader code in master branch
