### ISSUE TITLE
VS2015编译vulkan版本出错

### ISSUE THREAD

**Issue by loveandhope** [Tencent/ncnn#1739]
已经安装了vulkan SDK 1.1.114.0，使用VS2015编译vulkan版本时，提示如下错误信息：
2>  Building SPIR-V module convolution_pack4_3x3s1d1_lds_8_8_2.spv
2>  SPIR-V is not generated for failed compile or link
2>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 2.

3>d:\workspace\sdk\misc\ncnn\vs2015_vulkan\src\convolution_pack4_3x3s1d1_lds_8_8_2.spv.h(2): fatal error C1083: Cannot open include file: 'convolution_pack4_3x3s1d1_lds_8_8_2.spv.hex.h': No such file or directory

**Comment by nihui** [comment]
删除cmake缓存，重新 cmake

**Comment by loveandhope** [comment]
删除cmake缓存后，还是一样的现象，没有解决问题。然后，又仔细比对了源码，终于找到问题，是因为我升级ncnn库时，是在原来ncnn目录基础上比对替换升级的，这样，只是保证代码都是最新的，但有一些以前存在的comp文件没有删除，故出现了上述错误。删除之前版本残留的多余的comp文件后，编译正常了。
