### ISSUE TITLE
mobilenet_ssd_voc_ncnn.param    is too old?

### ISSUE THREAD

**Issue by zyg1982527** [Tencent/ncnn#174]
根据ssdmobilenet.cpp 中给的链接下载了mobilenet_ssd_voc_ncnn.bin和 mobilenet_ssd_voc_ncnn.param，运行时报错 
 param is too old, please regenerate
net load -1 0

以下两个链接里的文件，你们是不是要更新一下。
/*
     * model is  converted from https://github.com/chuanqi305/MobileNet-SSD
     * and can be downloaded from https://drive.google.com/open?id=0ByaKLD9QaPtucWk0Y0dha1VVY0U
     */

**Comment by zyg1982527** [comment]
补充一下，是iOS

**Comment by nihui** [comment]
对，需要更新  @lzx1413  帮忙更新下。。

**Comment by lzx1413** [comment]
ok

**Comment by jjjjohnson** [comment]
大神@lzx1413，
 我也在ios上遇到报错：param is too old, please regenerate 请问怎么更新？ 我用了最新版本 caffe2ncnn 还是不行。。。

**Comment by jjjjohnson** [comment]
模型地址： https://github.com/ElegantGod/ncnn/tree/master/mtcnn

**Comment by nihui** [comment]
> 
> 
> 根据ssdmobilenet.cpp 中给的链接下载了mobilenet_ssd_voc_ncnn.bin和 mobilenet_ssd_voc_ncnn.param，运行时报错
> param is too old, please regenerate!
> layer load_param failed
> Segmentation fault (core dumped)
> /*
> 
>     * model is converted from https://github.com/chuanqi305/MobileNet-SSD
> 
>     * and can be downloaded from https://drive.google.com/open?id=0ByaKLD9QaPtucWk0Y0dha1VVY0U
>       */

更新代码，包括 caffe2ncnn 工具，重新转换下
