### ISSUE TITLE
Onnx layer gru not supported

### ISSUE THREAD

**Issue by Zrufy** [Tencent/ncnn#1745]
GRU not supported yet!
  # direction=bidirectional
  # hidden_size=256
  # linear_before_reset=1
GRU not supported yet!
  # direction=bidirectional
  # hidden_size=256
  # linear_before_reset=1

**Comment by HaoYang0123** [comment]
Yes, I have same problem. 
My version is:
Python=3.7
pytorch=1.4.0
onnx=1.7.0
onnx_tf=1.5.0/1.6.0
tensorflow=2.2.0
============================
I want to convert my pytorch model to tensorflow model by onnx. In my pytorch model, there is a GRU.
The error is :
RuntimeError: GRU with linear_before_reset is not supported in Tensorflow.
However, if I change GRU to LSTM, it can be OK. So why doesn't support GRU but support LSTM? I was so confused!

**Comment by nihui** [comment]
RNN LSTM and GRU are now supported in the latest ncnn version.
Upgrade your ncnn library and enjoy :)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
