### ISSUE TITLE
ncnnoptimizeflag设为1也无法优化出fp16的模型

### ISSUE THREAD

**Issue by Sejudyblues** [Tencent/ncnn#1748]
当我尝试使用flag为0 和 1的时候，两个出来的模型大小一模一样是一模一样，应该设置flag为1的时候fp16出来应该只有fp32的一半大小啊。

**Comment by nihui** [comment]
flag 65536

**Comment by Sejudyblues** [comment]
> flag 65536

- -好吧 我看博客上是flag 0 和 1 原来是65536
