### ISSUE TITLE
你好，关于，caffe2ncnn

### ISSUE THREAD

**Issue by ylc2580** [Tencent/ncnn#1750]
你好，我这边按照步骤编译完ncnn之后，没有在build/tools/caffe/ 中发现caffe2ncnn，可能的问题是什么，求大神告知

**Comment by mychina75** [comment]
可以看看编译条件满足不，makefile里面有判断，不满足条件就不会编译。

**Comment by zhxingye** [comment]
这可能是因为你之前没有正确安装protobuf，自己重新安装后再手动编译caffe2ncnn即可

**Comment by nihui** [comment]
看看这里的文档
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-protobuf-problem.zh
