### ISSUE TITLE
Merge code of CPU, ARM NEON and SSE

### ISSUE THREAD

**Issue by maxint** [Tencent/ncnn#1754]
因为指令级SIMD代码只能优化128bit/256bit的数据，剩下的数据还是得通过CPU代码计算，不如合并这些代码到一个实现，如以 [src/layer/arm](../tree/master/src/layer/arm) 为模板，删除 [src](../tree/master/src) 下的版本，再合并 [src/layer/mips](../tree/master/src/layer/mips) 和 [src/layer/x86](../tree/master/src/layer/x86) 的代码。这样可以减少重复代码，Layer 实现更集中，提高代码可维护性。不过分离实现有个好处是，可以在单元测试中直接比较不同实现的结果。

![image](https://user-images.githubusercontent.com/85147/81693377-604cbf80-9492-11ea-809b-131f9a21a7b9.png)

**Comment by nihui** [comment]
# src/layer/absval.cpp
- naive实现，没有任何加速技巧，确保正确性为主，同时作为单元测试的reference
- 实现该op可支持的全部参数组合
- 当x86/arm等加速版未实现某参数组合，以便fallback

# src/layer/x86/absval_x86.cpp src/layer/arm/absval_arm.cpp
- 特定架构优化的代码，可以依赖指令特点各种骚操作
- 可以只实现某种参数下的加速版

合并之后，单个 absval.cpp 变大了，虽然总体行数会比多个文件少，但是 x86 arm mips 代码混杂在一起，反而不利于维护

按架构区分，是很多底层优化项目的 best practice，参考 linux ffmpeg glibc 等等

**Comment by maxint** [comment]
是的，这样代码更清楚些，代价是有重复代码。

> 当x86/arm等加速版未实现某参数组合，以便fallback

有个问题请教下，代码里如何自动判断加速版本是没实现某参数组合的？

**Comment by nihui** [comment]
比如 shufflechannel_arm.cpp 没有实现 group > 4 的情况，这时候 ShuffleChannel::forward

**Comment by maxint** [comment]
明白了，加速版本的实现也是完整的，只是在没有优化版本是fallback到CPU版本
