### ISSUE TITLE
LSTM在vulkan和cpu上的运行结果不一致

### ISSUE THREAD

**Issue by TreeDiagram-1** [Tencent/ncnn#1756]
lstm的代码如下，当opt.use_vulkan_compute = false时，程序的结果与onnx运行结果一直，设成true的时候，结果不对，请问是什么原因？
对比了中间层的数据，lstm出来的结果是一致的，是后面的fc层导致的gpu和cpu计算结果不一致

    ncnn::Net lstm;
    #if NCNN_VULKAN
    lstm.opt.use_vulkan_compute = false;
    #endif // NCNN_VULKA
    lstm.load_param("lstmv1.param");
    lstm.load_model("lstmv1.bin");

    ncnn::Extractor ex = lstm.create_extractor();
    ex.set_num_threads(1);
    ex.input("x", data);
    ex.extract("74", out);

    ncnn::Mat scores = out.reshape(out.w * out.h * out.c);
    for (int j = 0; j<out.w; j++)
        {

            printf("scores[%d] is %f \n",j,scores[j]);
        }

网络结构如下
Input            x                        0 1 x
Input            h                  0 1 h
Input            c                  0 1 c
ExpandDims       Unsqueeze_0              1 1 x 9 -23303=1,0
ExpandDims       Unsqueeze_1              1 1 h 10 -23303=1,0
ExpandDims       Unsqueeze_2              1 1 c 11 -23303=1,0
LSTM             LSTM_3                   1 1 9 69 0=512 1=409600 2=0
Squeeze          Squeeze_5                1 1 69 73 -23303=2,0,1
InnerProduct     Gemm_6                   1 1 73 74 0=40 1=1 2=20480

opt.use_vulkan_compute = false时的结果（cpu上运行，结果正确）
scores[0] is 2.535745 
scores[1] is -0.830365 
scores[2] is 3.766143 
scores[3] is 1.569435 
scores[4] is -1.733376 
scores[5] is -1.063240 
scores[6] is 1.336062 
scores[7] is 1.093385 
scores[8] is 0.135495 
scores[9] is 1.101650 
scores[10] is -1.484522 
scores[11] is -0.862298 
scores[12] is 0.056632 
scores[13] is -0.460387 
scores[14] is -2.626549 
scores[15] is -0.775600 
scores[16] is 0.089214 
scores[17] is -1.608107 
scores[18] is 0.744300 
scores[19] is -2.004079 
scores[20] is -1.103879 
scores[21] is -0.662038 
scores[22] is 1.154631 
scores[23] is 2.769236 
scores[24] is 1.392973 
scores[25] is -2.608238 
scores[26] is -1.800971 
scores[27] is 2.676787 
scores[28] is -0.865460 
scores[29] is 0.442421 
scores[30] is -0.537280 
scores[31] is -0.129252 
scores[32] is 0.238351 
scores[33] is -2.560330 
scores[34] is -0.130769 
scores[35] is -0.143469 
scores[36] is 0.039386 
scores[37] is 0.609815 
scores[38] is -1.691653 
scores[39] is 1.453406 

opt.use_vulkan_compute = true时的结果
scores[0] is 0.000000 
scores[1] is 0.000000 
scores[2] is -0.000000 
scores[3] is -0.000000 
scores[4] is -2.026575 
scores[5] is 52832660.000000 
scores[6] is 6743256.500000 
scores[7] is -0.000000 
scores[8] is -0.000000 
scores[9] is 0.000000 
scores[10] is -2658293573836677503915547355462500352.000000 
scores[11] is -54005134213824714492474294272.000000 
scores[12] is 0.000000 
scores[13] is 0.000000 
scores[14] is 0.000000 
scores[15] is -0.000000 
scores[16] is 0.000000 
scores[17] is 0.000000 
scores[18] is 0.000000 
scores[19] is 0.000000 
scores[20] is -0.000000 
scores[21] is -0.000000 
scores[22] is -47205609898765363370000065769766912.000000 
scores[23] is -0.000013 
scores[24] is 0.000002 
scores[25] is 0.000000 
scores[26] is 0.000000 
scores[27] is 31960279040.000000 
scores[28] is 0.162753 
scores[29] is 0.000000 
scores[30] is 0.000000 
scores[31] is 0.000000 
scores[32] is -0.000000 
scores[33] is -0.000000 
scores[34] is -0.000000 
scores[35] is -0.000000 
scores[36] is -0.000000 
scores[37] is -0.000000 
scores[38] is -0.000000 
scores[39] is -0.000000

**Comment by yanghedada** [comment]
@nihui   大佬，我遇到同样的问题。在Android中，最后一层无活层， 使用 cpu计算，输出结果大概在0-1之间，而gpu计算结果全为0或者结果大于1.

**Comment by yanghedada** [comment]
> @nihui 大佬，我遇到同样的问题。在Android中，最后一层无活层，使用cpu计算，输出结果大概在0-1之间，而gpu计算结果全为0或者结果大于1。
或者先使用cpu，再用gpu结果会正常。

**Comment by nihui** [comment]
推荐更新 ncnn 库，最新版本已针对 LSTM 做了优化，onnx2ncnn 转换器也大幅改善了 LSTM 的兼容性

**Comment by nihui** [comment]
如还有问题，可发新issue交流

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
