### ISSUE TITLE
can i use ncnn vulkan to handle gpu like Mail Serials ( eg. mali T860 GPU )

### ISSUE THREAD

**Issue by leoluopy** [Tencent/ncnn#1757]
i have compiled ncnn on my arm linux board with a GPU of mali T860 GPU and opencl 1.2. Before compiling ncnn i have compiled Vulkan-Loader and glslang , you can see this procedure is much similar to compile ncnn at NVIDIA Jetson . After that every thing went ok . the libncnn.a the libvulkan.so and the glslang is successfully built . Finally there's somethine wrong while i am runing my detector at my arm board . Here's the run time Error:

vkCreateInstance failed -9 (VK_ERROR_INCOMPATIBLE_DRIVER = -9,)

so my question is : can we use ncnn in opencl based GPU in arm linux board environment ?

**Comment by nihui** [comment]
The vulkan api is supported in the latest android system (>8.1) for RK3399 mali T860
RK3399 arm linux is known lacking vulkan support at the moment.

**Comment by leoluopy** [comment]
> The vulkan api is supported in the latest android system (>8.1) for RK3399 mali T860
> RK3399 arm linux is known lacking vulkan support at the moment.

thanks for reponse , you mean if i install android system (>8.1) in my RK3399 board , then i can use ncnn with gpu support which will make full use of mali T860 GPU.

**Comment by nihui** [comment]
probably, with the latest android system image

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/6876
