### ISSUE TITLE
ncnn 在安卓设备上的精度误差问题

### ISSUE THREAD

**Issue by liguiyuan** [Tencent/ncnn#1764]
请问一下，我在两台安卓设备上跑mtcnn人脸检测，对一些难检测人脸的图片，为什么一台安卓设备可以检测到人脸，另外一台就检测不到了呢？这也是浮点运算误差吗？（跑的是同一个app，这两台机子cpu型号不同，安卓版本也不同）

**Comment by nihui** [comment]
建议使用bmp图片测试，jpg在不同系统或硬件上解码出来数据是不一样的

**Comment by liguiyuan** [comment]
感谢niuhui，我刚才试了一下，确实是这个问题造成的
