### ISSUE TITLE
windows上from_pixels崩溃

### ISSUE THREAD

**Issue by loveandhope** [Tencent/ncnn#1770]
测试一个模型，不停调用了from_pixels输入图片，然后extract，有的图片可能比较大，进行到第几千次时，有一个图片会在from_pixels的_aligned_malloc里崩溃，我看了下这个图片，分辨率是3569x3541，大小985KB。但单独跑这一个图片测试时，又是正常的。请问会是什么问题？

**Comment by nihui** [comment]
3569x3541 from_pixels，输出 Mat 需要大约 144.6M 连续内存
检查下你的程序是否有内存泄漏，导致内存不够了

**Comment by loveandhope** [comment]
同样的图片集，用retinaface会出，用mtcnn正常，堆栈和内存占用如下图：
![QQ截图20200518151900](https://user-images.githubusercontent.com/53557328/82185060-345e8d80-991b-11ea-8e4d-97c4d3d4a580.jpg)
![QQ截图20200518151935](https://user-images.githubusercontent.com/53557328/82185061-358fba80-991b-11ea-93bf-5abc03cb9d8b.jpg)

**Comment by nihui** [comment]
试试看按这个 issue 的方式，修改下 retinaface 的部分代码

https://github.com/Tencent/ncnn/issues/1475

**Comment by loveandhope** [comment]
我没有启用openmp。

**Comment by loveandhope** [comment]
请教下，用cv::imread读取出的cv::Mat，如果长宽不是4的倍速，需要对齐后，再将frame.cols, frame.rows, frame.data传入from_pixels吗？我看ncnn代码里，ncnn::mat里图像stride直接用的宽度*3，是不是和我没有对齐有关系？

**Comment by nihui** [comment]
从现象看，就是内存不足的问题
如果你确信没有内存泄漏，可以换个内存大些的电脑跑跑看

**Comment by loveandhope** [comment]
同样的代码，如果不使用vulkan，则不会崩溃；使用vulkan后，除了存在上面的问题，有时图片宽高大于4000以上时，也会崩溃，提示类似vulkan alloc memory failed的错误提示。我这边有上万张图片，不停测试，有的图片分辨率小，有的图片分辨率很大，大部分图片的分辨率可能都不同。无vulkan版本内存偶尔会增长到几百MB，但很快会降下来到几十MB，但vulkan版刚开始占用内存200MB左右，到几千张图片时，逐渐上升到900多MB，并且不会降低，然后就崩溃了。 所以，猜测应当是在上述使用场景下，ncnn vulkan版本的内存使用有问题。

**Comment by nihui** [comment]
图片太大的时候，显存不够，所以崩溃
建议在推理前，判断下图片大小，尺寸太大先缩小
