### ISSUE TITLE
cl: 命令行 error D8021 :无效的数值参数“/Wextra”

### ISSUE THREAD

**Issue by chenjun2hao** [Tencent/ncnn#1774]
用vs2015编译的时候报错：`cl: 命令行 error D8021 :无效的数值参数“/Wextra”`，用vs2017好像也没有`-Wextra`参数呀。

**Comment by nihui** [comment]
更新下 cmake 新版本看看

**Comment by chenjun2hao** [comment]
尝试一下，感谢回复。
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nihui"<notifications@github.com&gt;; 
发送时间: 2020年5月19日(星期二) 晚上7:01
收件人: "Tencent/ncnn"<ncnn@noreply.github.com&gt;; 
抄送: "陈军"<778961303@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/ncnn] cl: 命令行 error D8021 :无效的数值参数“/Wextra” (#1774)





 
更新下 cmake 新版本看看

**Comment by chenjun2hao** [comment]
win10，vs2015，cmake更新到3.17.2.依然会有这个问题。只能去掉-Wextra。

**Comment by Atlas-88** [comment]
> win10，vs2015，cmake更新到3.17.2.依然会有这个问题。只能去掉-Wextra。

怎么去掉 -Wextra

**Comment by wxk0125** [comment]
> win10，vs2015，cmake更新到3.17.2.依然会有这个问题。只能去掉-Wextra。

您好请问您是怎么去掉的呢？
