### ISSUE TITLE
MacOS上编译的android arm64库总是比预编译版本慢

### ISSUE THREAD

**Issue by xu78guo6** [Tencent/ncnn#1780]
编译参数如下：
cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI="arm64-v8a" \
    -DANDROID_PLATFORM=android-21 ..

执行的网络是我自行定义的，预编译版约15ms 我编译的约45ms

**Comment by xu78guo6** [comment]
NDK版本是r21b

**Comment by nihui** [comment]
可能你用的是 debug 编译的？

**Comment by nihui** [comment]
总之，建议使用 release 预编译版本 :P
