### ISSUE TITLE
ncnn 在移动端 支持输入数据shape不确定对模型吗？

### ISSUE THREAD

**Issue by baiyu8534** [Tencent/ncnn#1783]
我的tensorflow模型输入的数据必须是不定长的数据，因为要输入文件，对文件处理后，生成对应对文件。
因为文件类型，用户输入对文件肯定是不一样对
而且要根据源文件经过模型处理后生成文件

tflite模型只支持确定shape对数据输入

请问ncnn可以转换输入数据shape不确定对tensorflow模型吗？

或者ncnn可以在移动端实现支持不确定shape对数据输入对模型？

望解答！谢谢！！🙏🙏🙏🙏🙏

**Comment by nihui** [comment]
ncnn 支持不确定shape输入
然而 tensorflow 模型转换很困难 ...

**Comment by baiyu8534** [comment]
@nihui 谢谢！
我先试试直接转化，有冻结模型，和ckpt模型，看能不能转化
如果不行，那我尝试用ncnn还原我的模型
