### ISSUE TITLE
带lstm的crnn模型是不支持int8量化吗

### ISSUE THREAD

**Issue by zqnnn** [Tencent/ncnn#1784]

**Comment by UPmao** [comment]
我也遇到同样的问题了，crnn int8 量化后，终端上推理的结果完全不对，请问大佬解决了吗？

**Comment by zuowanbushiwo** [comment]
这个目前支持了吗？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5435

**Comment by nihui** [comment]
implemented in https://github.com/Tencent/ncnn/commit/08b7d99a75ad70fdc5c1d9e5debc675fce5e83a9
