### ISSUE TITLE
请问如何定位 ncnn inference 时候的实际执行算子

### ISSUE THREAD

**Issue by un-knight** [Tencent/ncnn#1796]
比如说 `innerproduct` 算子有纯 c++ 实现也有 arm 汇编实现，要如何能够确定自己在实际运行的时候是调用了纯 c++ 的 `innerproduct` 还是 arm 汇编版本的 `innerproduct`？

**Comment by nihui** [comment]
你可以在 innerproduct_arm.cpp 加些 log ....

**Comment by un-knight** [comment]
> 你可以在 innerproduct_arm.cpp 加些 log ....

多谢！看来目前只能这种手动log了
