### ISSUE TITLE
vs2015+vulkan1.2.135.0   测试example/squeezenet.cpp，运行结果和cpu跑的不同

### ISSUE THREAD

**Issue by DevelopJoy** [Tencent/ncnn#1797]
vulkan的运行结果：
[0 Intel(R) UHD Graphics 620]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics 620]  buglssc=0  bugsbn1=0  bugihfa=0
[0 Intel(R) UHD Graphics 620]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
308 = 2658455991569831745807614120560689152.000000
831 = 765260092932096.000000
863 = 507974372032512.000000
不用vulkan的运行结果：
231 = 0.686512
230 = 0.225083
232 = 0.019268
请问大佬是什么原因呢？

**Comment by DevelopJoy** [comment]
https://github.com/Tencent/ncnn/wiki/vulkan-notes#control-storage-and-arithmetic-precision
disable all lower-precision optimzations, get full fp32 precision。设置32位，结果好像一致了。

**Comment by xiakj** [comment]
相同的配置环境，使用vulkan后CPU占用率是降了一些，但是没有看到GPU占用率提升，也没有感受到速度有多大提升。这一般是什么情况？
