### ISSUE TITLE
ncnn 数据输入通道数

### ISSUE THREAD

**Issue by qinb** [Tencent/ncnn#1798]
输入格式是 [batch, h, w, c]，如果c=15：
Q1:  如何构造满足ncnn输入的数据？
Q2:  假设数据组织完成，使用什么方法input到ncnn中?

期待大佬的回答！

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-opencv
参考 std::vector < cv::Mat > + CV_32FC1 -> ncnn::Mat multiple channels 这部分

也可以直接构造 Mat 后，把数据填入

**Comment by qinb** [comment]
多谢，我试一下

**Comment by qinb** [comment]
多谢，由于无法使用cv库，只能定义ncnn::Mat变量。 那么是否直接有函数 支持初始化操作？

**Comment by qinb** [comment]
多谢，ncnn需要特定版本支持吗？目前使用的是ncnn20200226.
```
ncnn::Mat in_ = ncnn::Mat(64,64,15)
ncnn::Extractor ex = net->create_extractor()
ex.input("data", in_);
ex.extract("prob", output);
```
output报错，为空

**Comment by qinb** [comment]
> 多谢，ncnn需要特定版本支持吗？目前使用的是ncnn20200226.
> 
> ```
> ncnn::Mat in_ = ncnn::Mat(64,64,15)
> ncnn::Extractor ex = net->create_extractor()
> ex.input("data", in_);
> ex.extract("prob", output);
> ```
> 
> output报错，为空

使用了ncnn20200413，仍报错。
直接把ncnn::Mat(64,64,15)改成(64,64,3)居然能跑通，期待回答！

**Comment by qinb** [comment]
> 多谢，ncnn需要特定版本支持吗？目前使用的是ncnn20200226.
> 
> ```
> ncnn::Mat in_ = ncnn::Mat(64,64,15)
> ncnn::Extractor ex = net->create_extractor()
> ex.input("data", in_);
> ex.extract("prob", output);
> ```
> 
> output报错，为空

使用了ncnn20200413，仍报错。
1、使用15channel模型
     ncnn::Mat(64,64,15)报上述错误，直接改成(64,64,3)居然能跑通！

下图是15channel param和3channel param对比
![image](https://user-images.githubusercontent.com/13461049/83506264-84337c00-a4f9-11ea-9889-d3993c5e6511.png)
![image](https://user-images.githubusercontent.com/13461049/83506349-a88f5880-a4f9-11ea-909f-d2326e3c7e23.png)

期待回答，多谢！
