### ISSUE TITLE
Compilation for 32bit x86 windows

### ISSUE THREAD

**Issue by itayalfia** [Tencent/ncnn#1801]
Hi,
I can't seem to find documentation about compilation for x86 windows (32 bit), 

Is it currently possible? If not, do you think it would be possible to compile for 32bit with some minor changes?
Do you employ optimizations for old SSE2 CPUs?

I would be very glad if you can help!
Its very hard to find inference engines supporting old architectures...

**Comment by nihui** [comment]
compilation for x86 32bit should be fine, but the speed will probably not be fast since ncnn is mainly optimized for mobile platforms.
