### ISSUE TITLE
自定义扩展算子的效率问题

### ISSUE THREAD

**Issue by un-knight** [Tencent/ncnn#1803]
使用 [add custom layer](https://github.com/Tencent/ncnn/wiki/add-custom-layer.zh) method1 中的方法实现 LSTM 自定义扩展，但是发现效率远低于 ncnn 的内置算子。

## 详情
我将 ncnn `src/layer/lstm.cpp` 中的 LSTM 代码主体拷贝出来重命名，以 method1 的方式实现为自定义扩展，但是发现自定义扩展的 lstm 计算效率远低于 ncnn 内置的 lstm。

> 测试硬件：x3288, A17, 单线程
> 编译：打开 O3 优化

| 操作实现  | 延迟(s) |
| -- | -- |
|ncnn 内置 lstm |  0.169  |
| 自定义扩展 lstm | 0.97  |

通过 GDB 跟踪过两种 LSTM 的计算，是完全一致的，都是如下函数

https://github.com/Tencent/ncnn/blob/054ec09195503095d3c057f3e3cda74ae7e814e2/src/layer/lstm.cpp#L59

鉴于两者 LSTM 代码完全一样，但是计算效率却存在如此大的区别，实在是非常奇怪，不知道这是否和 ncnn 的某些执行机制有关系，希望有大佬能够回答一下，谢谢！

**Comment by nihui** [comment]
执行机制上，内置的op和自定义注册的op是完全平等的，如果代码完全一样，不会有效率差别
检查下编译参数是否一致，输入shape是否一致

**Comment by un-knight** [comment]
> 执行机制上，内置的op和自定义注册的op是完全平等的，如果代码完全一样，不会有效率差别
> 检查下编译参数是否一致，输入shape是否一致

好的了解了，多谢:)
