### ISSUE TITLE
最新的ncnn在集显上用vulkan输出结果不正确

### ISSUE THREAD

**Issue by xiuyangleiasp** [Tencent/ncnn#1805]
模型：resnet50
测试环境：win10
集显型号：intel iris 655
vulkan：1.1.114.0
现象：相同的模型在旧版ncnn（4月中旬的版本），使用vulkan可正常运行，但今日pull了最新的ncnn编译后，输出结果完全不正确（top5的输出概率全部为0，对应的class_id亦完全不一致）；另外，奇怪的是，在1080ti上两个版本的输出结果概率值虽存在明显差异，但top5对应的class_id一致。

[resnet50.txt](https://github.com/Tencent/ncnn/files/4714472/resnet50.txt)

**Comment by nihui** [comment]
confirmed
