### ISSUE TITLE
发现vulkan相关小bug

### ISSUE THREAD

**Issue by colorwavelet** [Tencent/ncnn#1808]
在包含GPU的库版本，只用CPU运行的时候，报错signal 11 (SIGSEGV)

原因是net.cpp第530行的地方，因为没有判断是不是用vulkan，就去调vkdev对应配置，导致用CPU时候调到空指针
参考net.cpp第343行，应该还需要加入if (opt.use_vulkan_compute)等判断避免调到空指针。
另外if (vkdev->info.bug_layout_binding_id_alias) opt.use_image_storage = false;已经在355行做过了，这里的出现再做的意思应该要把opt改成opt1

建议作者对这部分代码做修改

#if NCNN_VULKAN
        if (!layer->support_image_storage)
        {
            opt1.use_image_storage = false;
        }
        if (opt.use_vulkan_compute) //加入判断
        {
            if (vkdev->info.bug_layout_binding_id_alias) opt1.use_image_storage = false;    //此处功能是否要将opt改成opt1？
        }
#endif // NCNN_VULKAN

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/64985809a3e3989b651e25ca2f532d0b3d043662

已经修好了
