### ISSUE TITLE
在iOS上ncnn比Tensorflow慢2倍以上

### ISSUE THREAD

**Issue by ddlxstudio** [Tencent/ncnn#181]
在iPhone6s 上使用AlexNet网络测试

使用ncnn耗时 200ms
而使用tensorflow才80ms

差别很大。
ncnn我使用的是从release目录下载的20171017日预先编译好的库。

有遇到同类问题的么？

**Comment by nihui** [comment]
模型是一样大小的吗...

**Comment by ddlxstudio** [comment]
相同的模型

**Comment by nihui** [comment]
请提供下模型链接...

**Comment by ddlxstudio** [comment]
模型下载地址 https://share.weiyun.com/f30c5d5caf52adae20bac79593aab5f9

**Comment by aitaoquanyi** [comment]
@ddlxstudio 请教一下tensorflow安卓或者ios开多核以及使用openblas的方法，谢谢，我QQ270525694。

**Comment by keyongyu** [comment]
Of course, CPU optimization can't beat the apple's Accelerate Framework.

**Comment by nihui** [comment]
The latest code is much faster :)
