### ISSUE TITLE
模型量化後比量化前速度還要慢

### ISSUE THREAD

**Issue by Hank0223** [Tencent/ncnn#1813]
請問模型量化完後，程式碼內還需要添加什麼開關啟用int8模型嗎？
還是說只要加載量化後的模型就會自行跑int8的程式?
我比較量化前後的模型網絡時間，模型量化後比量化前速度還要慢
請求高手指點 
謝謝 !!

**Comment by ItchyHiker** [comment]
> 請問模型量化完後，程式碼內還需要添加什麼開關啟用int8模型嗎？
> 還是說只要加載量化後的模型就會自行跑int8的程式?
> 我比較量化前後的模型網絡時間，模型量化後比量化前速度還要慢
> 請求高手指點
> 謝謝 !!

同样的问题

**Comment by qinb** [comment]
是不是有5x5dw？ 在ncnn20200226版本里面，5x5dw貌似没优化，很慢。

**Comment by Hank0223** [comment]
![2B72E335-13BE-4557-ACCE-A3E5104D2094](https://user-images.githubusercontent.com/58155722/83845780-217df280-a73c-11ea-8136-6bf732d1a1e1.jpeg)
這是我原始的架構，我在轉換中並沒有出現5x5switch

**Comment by Hank0223** [comment]
> 是不是有5x5dw？ 在ncnn20200226版本里面，5x5dw貌似没优化，很慢。

我在原始的架構中沒有5x5dw
![A1E096F4-DBD6-4B78-B3F4-270E59FD2750](https://user-images.githubusercontent.com/58155722/83846107-a79a3900-a73c-11ea-931f-d4b46f1122ac.jpeg)

**Comment by yileld** [comment]
在特定的平台上才会加速，因为原理上模型是伪量化，计算完后会转回浮点数的，所以理论上对于通用平台加速没有效果

**Comment by JensenHJS** [comment]
量化加速只能在手机端或者海思等平台上才能体现吗，在英伟达jetson嵌入式GPU上是否能加速？jetson平台是arm cpu+nvidia gpu

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新

**Comment by zc850134557** [comment]
> https://zhuanlan.zhihu.com/p/370689914
> https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
> 20210507版本大幅优化int8推理速度并重写了量化工具，建议更新

@nihui   求教下呀，我使用int8(MobifaceNet)量化后的模型在RK 系列的andorid平台，在inference过程中没有实现加速，求教下是什么问题呀？（已使用20210507版本）
