### ISSUE TITLE
预编译的库ncnn-vulkan.framework有问题，直接ld: Framework not found ncnn-vulkan

### ISSUE THREAD

**Issue by chenminghong** [Tencent/ncnn#1814]
我使用github上面预编译好的ncnn-vulkan.framework库，按照常规使用方式在Build phases里添加进项目，run之后直接error了，提示ld: Framework not found [ncnn-vulkan，我使用其他的framework库都没有任何问题，我网上下载了别人编译好的ncnn-vulkan.framework库，按同样的方式集成进项目里，也没有报错，目前就是使用了github上预编译好的ncnn-vulkan.framework出现了这个问题，麻烦尽快处理一下，谢谢！

**Comment by nihui** [comment]
20200413版本的framework开启了bitcode编译，ios工程也要打开bitcode
后面新版本会提供native和bitcode两种framework

**Comment by chenminghong** [comment]
我说的这种volkan的framework，找不到库的问题，是怎么回事？我已经打开bitcode了，还是不行，麻烦看看是我本地问题还是预编译库的问题？如果是预编译的库的问题，方便更新一下ncnn-volkan.framework库文件吗？麻烦了！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nihui <notifications@github.com&gt;
发送时间: 2020年6月4日 21:50
收件人: Tencent/ncnn <ncnn@noreply.github.com&gt;
抄送: chenminghong <1044854645@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/ncnn] 预编译的库ncnn-vulkan.framework有问题，直接ld: Framework not found ncnn-vulkan (#1814)





 
20200413版本的framework开启了bitcode编译，ios工程也要打开bitcode
 后面新版本会提供native和bitcode两种framework

**Comment by chenminghong** [comment]
目前我导入了这三个库，遇到了两个问题，我是做sdk开发，一个就是framework not found ncnn-vulkan，另一个就是ncnn-vulkan.framework里，很多文件导入#include <vulkan/vulkan.h&gt;的，都会报这个vulkan.h头文件找不到的问题，我目前已经尝试了三天，各种方式导入，都无法解决，不知道是什么问题，MoltenVK.framework里，确实没有vulkan.h这个头文件，我去官网下载，以及我自己使用源码编译vulkan，MoltenVK.framework里都没有vulkan.h头文件，想问一下是什么情况导致的这个问题？我目前在导入framework方面操作应该都是正确的，是我Xcode本地环境需要配置什么吗？麻烦协助解决一下这个问题，项目比较急！

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nihui <notifications@github.com&gt;
发送时间: 2020年6月4日 23:48
收件人: Tencent/ncnn <ncnn@noreply.github.com&gt;
抄送: chenminghong <1044854645@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/ncnn] 预编译的库ncnn-vulkan.framework有问题，直接ld: Framework not found ncnn-vulkan (#1814)





 
ncnn-vulkan.framework 还需要配合 openmp.framework 和 moltenvk
 
moltenvk的framework可以这里下载 https://vulkan.lunarg.com

**Comment by nihui** [comment]
把 ncnn-vulkan.framework 重命名为 ncnn.framework 就正常了...

**Comment by nihui** [comment]
最新的release已修复文件夹名称问题

**Comment by chenminghong** [comment]
好的，谢谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: nihui <notifications@github.com&gt;
发送时间: 2020年6月19日 14:26
收件人: Tencent/ncnn <ncnn@noreply.github.com&gt;
抄送: chenminghong <1044854645@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Tencent/ncnn] 预编译的库ncnn-vulkan.framework有问题，直接ld: Framework not found ncnn-vulkan (#1814)





 
最新的release已修复文件夹名称问题

**Comment by farawei** [comment]
您好，我也遇到到了相同的问题，ios引入 ncnn-20210124-ios-vulkan 库，会报错误：'vulkan/vulkan.h' file not found；想问下 valkan.framework 这个库是必须的吗？因为 https://vulkan.lunarg.com 官网还不支持 ios，所以想确定下 如果不使用 vulkan.framework，是不是不支持GPU

**Comment by chenminghong** [comment]
> 您好，我也遇到到了相同的问题，ios引入 ncnn-20210124-ios-vulkan 库，会报错误：'vulkan/vulkan.h' file not found；想问下 valkan.framework 这个库是必须的吗？因为 https://vulkan.lunarg.com 官网还不支持 ios，所以想确定下 如果不使用 vulkan.framework，是不是不支持GPU

valkan.framework不是必须的，好像是使用GPU就得使用valkan.framework，看你项目需求，我感觉CPU就挺好的。头文件找不到是因为你没有手动去引入这个库的头文件。建议你参考一下这个文章 https://www.jianshu.com/p/ce3a6f60b61d 在Search Path Setting中的Framework Search Path 添加一下相关头文件。

**Comment by farawei** [comment]
我也找过了这个链接查看，发现里面也是没有使用vulkan.framework 框架，只引用了MoltenVK.framework；因为当前我想使用支持GPU的，现在的问题是valkan.framework不支持ios。卡主了，当前就是想玩一玩支持GPU的，想对比一下CPU的，看看效果

**Comment by chenminghong** [comment]
> 我也找过了这个链接查看，发现里面也是没有使用vulkan.framework 框架，只引用了MoltenVK.framework；因为当前我想使用支持GPU的，现在的问题是valkan.framework不支持ios。卡主了，当前就是想玩一玩支持GPU的，想对比一下CPU的，看看效果

MoltenVK跟valkan有区别？MoltenVK中的VK你怎么理解的？难道不是valkan的简写？

**Comment by farawei** [comment]
我编译时发现一个提示：
<img width="994" alt="出错提示" src="https://user-images.githubusercontent.com/5398348/110079742-71214580-7dc4-11eb-8985-a8dc0178f7ca.png">

看到ncnn.framework 特意要求引入vulkan.framework，所以才有了以上的问题

**Comment by farawei** [comment]
发现MoltenVK也有对vulkan的include。我一开始是直接把ncnn的宏NCNN_VULKAK修改为0，编译通过通过后，查看GPU的使用情况，发现与不使用vulkan的库使用GPU的时间相差不多，所以考虑vulkan不能不引入。
我看到note说是支持iOS GPU的，不知道我是哪一步出错了，谢谢答复~

**Comment by chenminghong** [comment]
> 我编译时发现一个提示：
> <img alt="出错提示" width="994" src="https://user-images.githubusercontent.com/5398348/110079742-71214580-7dc4-11eb-8985-a8dc0178f7ca.png">
> 
> 看到ncnn.framework 特意要求引入vulkan.framework，所以才有了以上的问题

有不带vulkan的framework啊，你要是非要用vulkan，我上面不是说过了？引入头文件啊，你的vulkanSDK里面不是有MoltenVK？里面的头文件手动引入一下。。

**Comment by farawei** [comment]
终于可以了，原来只需要引入头文件，一直在想怎么引入vulkan库：
<img width="297" alt="截屏2021-03-05 下午5 06 44" src="https://user-images.githubusercontent.com/5398348/110092984-2eb43480-7dd5-11eb-954b-dd9c3330a7a1.png">

跑了一下，相比可以节省100ms左右的时间，CPU与GPU基本各占一半，谢谢指导，非常感谢。

**Comment by chenminghong** [comment]
不用谢，估计你跟我开始一样，没有仔细阅读简书上的那个文章，只需要按照文章里那个方式引入报错提示的头文件即可



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: farawei ***@***.***&gt;
发送时间: 2021年3月5日 17:08
收件人: Tencent/ncnn ***@***.***&gt;
抄送: chenminghong ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[Tencent/ncnn] 预编译的库ncnn-vulkan.framework有问题，直接ld: Framework not found ncnn-vulkan (#1814)





 
终于可以了，原来只需要引入头文件，一直在想怎么引入vulkan库：
 
 
跑了一下，相比可以节省100ms左右的时间，CPU与GPU基本各占一半，谢谢指导，非常感谢。

**Comment by stoneForRock** [comment]
我也遇到这个问题了，'vulkan/vulkan.h' file not found 确实是因为头文件没有引用导致的编译问题.看了上面大佬的讨论，还是没能解决  原来是我导头文件导错位置了，如图所示，需要把include 文件夹 拖到HeaderSearchPath这里，我之前是添加到FrameworkSearchPaths里面了。还有就是 如果你拖的是 include里面的vulkan文件夹，那就要把代码里面的导入改成include <vulkan.h> 所以直接导入include文件夹就可以
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/16237800/187825087-de356899-56f4-4e95-9842-6badda9f5343.png">
