### ISSUE TITLE
使用ncnnoptimize量化yolov3和tiny-yolov3报layer DarknetActivation not exists or registered，Segmentation fault，是什么问题呢，参考https://blog.csdn.net/liuwei36120516/article/details/105675956，为什么人家就一步对，我感觉我有毒

### ISSUE THREAD

**Issue by 2017ZYS** [Tencent/ncnn#1815]

**Comment by nihui** [comment]
可以试试最近更新的 darknet2ncnn 工具
https://github.com/Tencent/ncnn/tree/master/tools/darknet

**Comment by xiakj** [comment]
> 可以试试最近更新的 darknet2ncnn 工具
> [`master`/tools/darknet](https://github.com/Tencent/ncnn/tree/master/tools/darknet?rgh-link-date=2020-07-01T14%3A04%3A11Z)

yolov4-tiny训练了一个手检测模型，到ncnn上运行性能下降好多啊

**Comment by kjcx100** [comment]
同问，我看yolov3的param文件里面有DarknetActivation层，是目前不支持这个layer还是要转换？

**Comment by nihui** [comment]
ncnn是对arm优化的性能，可以在手机上测试
darknet 模型用这里的工具转换 https://github.com/Tencent/ncnn/tree/master/tools/darknet
