### ISSUE TITLE
未经过x86的优化代码无法准确的预测出结果

### ISSUE THREAD

**Issue by Hank0223** [Tencent/ncnn#1819]
请问@nihui 如果我不使用x86的优化代码去跑int8量化后的程序, param是否有需要更改什么吗?
我尝试分別跑了有x86的優化代碼和沒有使用x86的優化代碼, 但兩者的結果不一樣
未经过x86的优化代码，无法准确的预测出结果，而经过x86的优化代码会正常的预测结果
以下是我的param的档案
谢谢

@nihui  If I do not use x86 optimized code to run the int8 quantization program, do I need to change the parameters?
I tried using x86 to run optimized code, and not x86 to run optimized code, but the results of the two are different.
Without x86 optimized code, it is impossible to accurately predict the results, and x86 optimized code can usually predict the results correctly.
The following is my param file.
Thank you

[int8.txt](https://github.com/Tencent/ncnn/files/4740548/int8.txt)

经过x86的优化代码
![12098858187976](https://user-images.githubusercontent.com/58155722/83948843-c7238580-a852-11ea-83d0-7ab7ba31f34b.png)

未经过x86的优化代码
![12098852741103](https://user-images.githubusercontent.com/58155722/83948849-d0145700-a852-11ea-9a4e-31169bf9f952.png)

**Comment by nihui** [comment]
QQ群有较多人反馈，标记为 bug

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新
