### ISSUE TITLE
Vulkan convolution wrong output with shape hint

### ISSUE THREAD

**Issue by zhiliu6** [Tencent/ncnn#1828]
The shape hint introduced by ncnnoptimize will cause wrong output when using vulkan.

The attachment file [yolov4-opt.zip](https://github.com/Tencent/ncnn/files/4751683/yolov4-opt.zip) is an optimized yolov4 network, the wrong output begins at layer "62_452", blob "62_452_bn_mish".

Removing shape hint of layer "60_439", blob "60_439_bn_mish" will produce correct output on "62_452_bn_mish".

The shape hint does not affect cpu inferencing.

The weight file can be downloaded at:
https://drive.google.com/file/d/1RLEdUqUJIEnR2_ZOYkmKK05FfsjfBr13/view?usp=sharing

**Comment by nihui** [comment]
identical crop pack4 fp16s produce wrong result
https://github.com/Tencent/ncnn/commit/f72b3945885945e2ae5f4d4b31aa8027e7dcdf36 is a potential workaround
