### ISSUE TITLE
rk3288 上相同计算量的shufflenet跑的比mobilenet快，有办法优化mobilenet或者加速rk3288上面跑的速度吗？比如优化指令啥的？

### ISSUE THREAD

**Issue by xulingling516** [Tencent/ncnn#1830]
rk3288 上相同计算量的shufflenet跑的比mobilenet快，有办法优化mobilenet或者加速rk3288上面跑的速度吗？比如优化指令啥的？

**Comment by nihui** [comment]
benchmark 中的 shufflenet 是 g3-0.5x

**Comment by xulingling516** [comment]
不是benchmark里面的模型，是我们自己的模型，计算了模型参数和计算量，shufflenet和mobilenet大体一致，但是mobilenet大概慢16%。

**Comment by nihui** [comment]
shufflenet 的内存访问比较友好，这也是 shufflenet 的主要贡献点
