### ISSUE TITLE
rk3288上面绑定不了大核

### ISSUE THREAD

**Issue by xulingling516** [Tencent/ncnn#1832]
rk3288上面使用set_cpu_powersave=2，还是随机运行两个核，绑定不了两个大核怎么回事？不管set_cpu_powersave=0还是set_cpu_powersave=1效果都是一样。

**Comment by nihui** [comment]
cpu.cpp 里面
#define __ANDROID__
试试看

powersave 那些目前只在 android 上开启了，arm linux 没有效果

**Comment by xulingling516** [comment]
现在我们的rk3288上面装的就是安卓的系统，类似手机使用方式，ncnn使用的github上面编译好的安卓版本20200413。这个也要重新编译吗？还有如果想使用gpu跑模型，但是又要显示图像，有办法同时支持吗？

**Comment by nihui** [comment]
rk3288 是不区分大小核的吧，我看四个cpu core是一样的

gpu跑模型需要比较新的 android 系统，才会有 vulkan 驱动

**Comment by xulingling516** [comment]
安卓5.1.1可以吗？现在用gpu
跑模型会影响图像显示，有办法可以解决吗？




徐玲玲
tel: 15195993599
                                
在2020年06月10日 12:35，nihui 写道：

rk3288 是不区分大小核的吧，我看四个cpu core是一样的

gpu跑模型需要比较新的 android 系统，才会有 vulkan 驱动

**Comment by nihui** [comment]
android 5.1.1 用不了gpu
