### ISSUE TITLE
自己的模型生成了param和bin，但是无法跑benchmark

### ISSUE THREAD

**Issue by Qingyang-Liu** [Tencent/ncnn#1834]
因为想要比较各个引擎的速度，所以用了统一的模型转换后跑benchmark。利用NCNN的转换工具成功生成了param和bin，但是跑benchmark的时候报错。我直接在benchncnn.cpp文件里面加入了如下内容
benchmark("C_Mobilenet..."， ncnn::Mat(224, 224, 3), opt)；
![image](https://user-images.githubusercontent.com/32212639/84249259-1d3b4600-ab3d-11ea-98c0-6dc7a341f01e.png)

报错内容为find_blob_index_by_name output failed。
![image](https://user-images.githubusercontent.com/32212639/84249657-a2265f80-ab3d-11ea-9a44-c8e537fc7c9a.png)

请问有人可以指导一下是怎么回事吗？

**Comment by nihui** [comment]
需要把 benchmark 的 param 中的输入输出blob名字改为 data 和 output

**Comment by Qingyang-Liu** [comment]
> 需要把 benchmark 的 param 中的输入输出blob名字改为 data 和 output

是的，改了之后有效！太感谢了！
