### ISSUE TITLE
对于Resnet-18，与caffe相比，获取fc1000的值不一样

### ISSUE THREAD

**Issue by WuYuChun** [Tencent/ncnn#184]
Hi，我在caffe中使用Resnet-18网络结构，获取fc1000层的结果与在ncnn中获取fc1000层的结果不一样，差异很大。都是相同的输入。

请问一下：1）这是由于什么原因造成的呢？2）若是想要结果相同，是需要修改哪里呢？

**Comment by zhly0** [comment]
有时候会出现结果不一致的原因,这个我也碰到了,暂时无解

**Comment by nihui** [comment]
检查下预处理是否一致

**Comment by WuYuChun** [comment]
@nihui 预处理是一致的，已检查在送入网络之前的数据是一致的。

**Comment by WuYuChun** [comment]
@nihui hi，请教一下，BatchNorm是否有问题，因为我初步验证这数据进过BatchNorm后，数据就不一样了。谢谢。

**Comment by jackcc** [comment]
@WuYuChun res-18中BN的滑框机制不一样，NCNN还没有考虑这个

**Comment by zhly0** [comment]
现在这个问题已经不存在了吗?

**Comment by Orangels** [comment]
有同样的问题, 设置一样的均值和方差, 输出结果差0.12左右
