### ISSUE TITLE
 error: invalid types 'int32x4_t {aka __vector(4) __builtin_neon_si}[int]' for array subscript

### ISSUE THREAD

**Issue by zhaokai5** [Tencent/ncnn#1844]
我使用的是qnx6.6的交叉编译工具，编译ncnn时出现如下错误，有啥解决方案不
![webwxgetmsgimg](https://user-images.githubusercontent.com/24264343/84746522-a5f82d00-afe8-11ea-88d9-e9485df1a7db.jpg)

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新

**Comment by nihui** [comment]
最新版本代码已经重写，去除了下标操作
