### ISSUE TITLE
请问怎么在安卓端导入模型？

### ISSUE THREAD

**Issue by Huhaowen0130** [Tencent/ncnn#1847]
不能在java中调用cpp，像这样导入模型吗？
ncnn::Net net;
    net.load_param("D:\\AndroidStudioProjects\\new_opencv_ncnn_proj\\app\\src\\main\\cpp\\MyModel.param");
    net.load_model("D:\\AndroidStudioProjects\\new_opencv_ncnn_proj\\app\\src\\main\\cpp\\MyModel.bin");

**Comment by nihui** [comment]
https://github.com/nihui/ncnn-android-squeezenet
https://github.com/nihui/ncnn-android-mobilenetssd

参考下sample project

**Comment by Huhaowen0130** [comment]
> https://github.com/nihui/ncnn-android-squeezenet
> https://github.com/nihui/ncnn-android-mobilenetssd
> 
> 参考下sample project

你好，我的图像原始尺寸是640 * 480，怎么样才能在用BitmapFactory.decodeResource()读图的时候不改变图像的尺寸呢
