### ISSUE TITLE
ncnn针对图像旋转有加速函数吗

### ISSUE THREAD

**Issue by lbwang2006** [Tencent/ncnn#185]

**Comment by nihui** [comment]
没有。。。
也许将来会有。。。用不了多久
也许要很久。。。

**Comment by nihui** [comment]
旋转api
https://github.com/Tencent/ncnn/commit/1009b539aad42a0c0ac62143af61ae21fb8b1ee1

**Comment by nihui** [comment]
warpaffine 旋转api也已经实现了～

**Comment by nihui** [comment]
最新的release已对warpaffine做了arm优化
