### ISSUE TITLE
Filed to convert onnx model with FPN structure

### ISSUE THREAD

**Issue by MarsTechHAN** [Tencent/ncnn#1850]
ncnn version: a91a18b901d917b905f5bdc6c77deed100e97d6b

Log from onnx2ncnn:
```
$ ./onnx2ncnn ../../../../models/retina_evogrid.onnx 
Gather not supported yet!
  # axis=0
Gather not supported yet!
  # axis=0
Shape not supported yet!
Gather not supported yet!
  # axis=0
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Shape not supported yet!
[1]    2470 segmentation fault (core dumped)  ./onnx2ncnn ../../../../models/retina_evogrid.onnx
```

Failed to converted onnx modell:
[retina_evogrid.zip](https://github.com/Tencent/ncnn/files/4793140/retina_evogrid.zip)

**Comment by nihui** [comment]
fixed in the latest code

Thanks for your report !

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
