### ISSUE TITLE
有支持keras 转 ncnn的工具么？

### ISSUE THREAD

**Issue by RandomWalkEagle** [Tencent/ncnn#186]
如题

**Comment by nihui** [comment]
没有，推荐用 caffe 转 ncnn ...

**Comment by yanghanxy** [comment]
Hi，我想实现一个Keras2NCNN的工具，但是我不大清楚NCNN需要的模型格式是什么样的。
请问有没有文档能介绍一下PARAM和BIN的格式？

**Comment by nihui** [comment]
@yanghanxy  粗略地写了两篇... 具体实现细节可以看其他转换器代码和 paramdict.cpp modelbin.cpp
https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure
https://github.com/Tencent/ncnn/wiki/operation-param-weight-table

**Comment by yanghanxy** [comment]
@onexuan [https://github.com/yanghanxy/Keras2NCNN/tree/master](https://github.com/yanghanxy/Keras2NCNN/tree/master)
一个小脚本，比较杂乱，你看着参考下吧~
