### ISSUE TITLE
set_num_threads设置为多线程，主线程退出时，会导致崩溃

### ISSUE THREAD

**Issue by zxy464430447** [Tencent/ncnn#1870]
背景：win10系统，预测部分做成dll库，主进程加载dll调用接口进行预测，预测结果返回后，卸载dll
问题：当设置set_num_threads为大于1的数时，卸载dll时会导致崩溃，如果set_num_threads设置为1，则正常。另外，如果预测结束后sleep 200ms左右也正常。感觉像是多线程预测时，结果返回后，其它子线程的资源未完全释放导致的。

**Comment by nihui** [comment]
https://stackoverflow.com/questions/34439956/vc-crash-when-freeing-a-dll-built-with-openmp
是这里的问题？

**Comment by zxy464430447** [comment]
程序中没有使用OpenMP

**Comment by zxy464430447** [comment]
调试模式下，崩溃时提示：0x7895BB90（vcomp140d.dll）处（位于Test.exe中）引发的异常：0xC0000005: 执行位置0x7895BB90时发生访问冲突。

**Comment by nihui** [comment]
ncnn内部使用 openmp 了，建议尝试 stackoverflow 的方法

**Comment by zxy464430447** [comment]
问题解决了，非常感谢！
