### ISSUE TITLE
latest release [20200616] in jetson nano --> Could NOT find CUDA 

### ISSUE THREAD

**Issue by ghimiredhikura** [Tencent/ncnn#1873]
hi, 

I am building latest release ([20200616](https://github.com/Tencent/ncnn/tree/20200616)) in nvidia jetson nano, but I keep getting cuda can;t find error. 

```ruby
root@ghimire:/home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/build# cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake -DNCNN_BUILD_TOOLS=ON -DCMAKE_BUILD_TYPE=Release ..
-- CMAKE_TOOLCHAIN_FILE = /home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/toolchains/jetson.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/build/install
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.5.1")
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE
  CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is exact version "10.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.15/Modules/FindCUDA.cmake:1092 (find_package_handle_standard_args)
  /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:86 (find_package)
  /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:108 (find_host_package)
  tools/quantize/CMakeLists.txt:1 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/build/CMakeFiles/CMakeOutput.log".
See also "/home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/build/CMakeFiles/CMakeError.log".
```
[CMakeError.log](https://github.com/Tencent/ncnn/files/4820204/CMakeError.log)
[CMakeOutput.log](https://github.com/Tencent/ncnn/files/4820205/CMakeOutput.log)

Thanks in advance.

**Comment by nihui** [comment]
ncnn doesn't depend cuda but it seems that your opencv4 does

**Comment by ghimiredhikura** [comment]
thanks. 
yeah, sorry it was from opencv. solved. closing. :)

**Comment by leondgarse** [comment]
For any other who encounter this. In my case, I have compiled and installed `opencv` from source, that leads to this issue... We can specify `cuda` path by:
```sh
cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.0 ..
```
But my `opencv` asks for `cuda 10.2`, so removing that `cmake` from system path solves my problem:
```sh
sudo rm /usr/local/lib/cmake/opencv4/ -r
```

**Comment by 15760951164** [comment]
> hi,
> 
> I am building latest release ([20200616](https://github.com/Tencent/ncnn/tree/20200616)) in nvidia jetson nano, but I keep getting cuda can;t find error.
> 
> ```ruby
> root@ghimire:/home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/build# cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake -DNCNN_BUILD_TOOLS=ON -DCMAKE_BUILD_TYPE=Release ..
> -- CMAKE_TOOLCHAIN_FILE = /home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/toolchains/jetson.toolchain.cmake
> -- CMAKE_INSTALL_PREFIX = /home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/build/install
> -- The C compiler identification is GNU 7.5.0
> -- The CXX compiler identification is GNU 7.5.0
> -- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc
> -- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++
> -- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found OpenMP_C: -fopenmp (found version "4.5")
> -- Found OpenMP_CXX: -fopenmp (found version "4.5")
> -- Found OpenMP: TRUE (found version "4.5")
> -- Found Protobuf: /usr/local/lib/libprotobuf.so;-lpthread (found version "3.5.1")
> CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
>   Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE
>   CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is exact version "10.0")
> Call Stack (most recent call first):
>   /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/share/cmake-3.15/Modules/FindCUDA.cmake:1092 (find_package_handle_standard_args)
>   /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:86 (find_package)
>   /usr/local/lib/cmake/opencv4/OpenCVConfig.cmake:108 (find_host_package)
>   tools/quantize/CMakeLists.txt:1 (find_package)
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/build/CMakeFiles/CMakeOutput.log".
> See also "/home/ghimire/Desktop/devplatform-rasberrypi3/benchmark/frameworks/ncnn/ncnn-20200616/build/CMakeFiles/CMakeError.log".
> ```
> 
> [CMakeError.log](https://github.com/Tencent/ncnn/files/4820204/CMakeError.log) [CMakeOutput.log](https://github.com/Tencent/ncnn/files/4820205/CMakeOutput.log)
> 
> Thanks in advance.

I have the same problem, how did you solve it
