### ISSUE TITLE
Android 系统中使用 ncnn-vulkan load shufflent v2 人脸关键点检测模型失败

### ISSUE THREAD

**Issue by luckynote** [Tencent/ncnn#1874]
GPU - IMG GE 8300
加载两个模型--人脸检测和人脸关键点检测
人脸检测模型：ssd，param 10kb，model 509kb，cpu load param 需要1.7ms，load model 需要 19ms;
但是，使用vulkan load param 需要 32s，load model需要55s，一个初始化需要将近2min;

人脸关键点检测模型：shufflenet v2，param 40kb, model 2.5Mb, cpu load param 需要 5ms，load model 需要 10ms;
但是，使用vulkan load param 时，mem 中native 狂飙，直接被杀死，导致初始化失败。

**Comment by luckynote** [comment]
```
VulkanDevice* get_gpu_device(int device_index)
{
    try_create_gpu_instance();

    if (device_index < 0 || device_index >= g_gpu_count)
        return 0;

    MutexLockGuard lock(g_default_vkdev_lock);

    if (!g_default_vkdev[device_index])
        g_default_vkdev[device_index] = new VulkanDevice(device_index);

    return g_default_vkdev[device_index];
}
```
经过debug，终于到gpu.cpp了，发现
**g_default_vkdev[device_index] = new VulkanDevice(device_index);**
这个过程被阻塞了，但不知道为啥，希望有大佬可以指点一下迷经。

**Comment by luckynote** [comment]
经过排查发现，执行pooling_vulkan create_pipeline，在第二次执行的时候，卡在

VkResult ret = vkCreateComputePipelines(vkdev->vkdevice(), 0, 1, &computePipelineCreateInfo, 0, &pipeline);

内存开始疯狂增长，然后被系统杀死了

整个主干网络采用shufflenet v2，中间使用了MaxPooling，在网络concat层之后，进行三次pooling平均池化，结果第一个pooling就出现内存溢出了

**Comment by nihui** [comment]
QQ群交流后，发现是 pooling kernel=20 stride=20 参数过大导致

**Comment by luckynote** [comment]
**问题补充：**
主干采用shufflenet v2，最后三层为reduce，**由于vulkan不支持reduce**，因此用如下方法代替
`Pooling    pool1    1 1 ShuffleNetV2/Stage2/concat_splitncnn_0 pool1 0=1 1=20 11=20 2=20 12=20 5=1`
但是在vulkan ncnn load model 执行到 pipeline.cpp 540行
`ret = vkdev->vkCreateDescriptorUpdateTemplateKHR(vkdev->vkdevice(), escriptorUpdateTemplateCreateInfo, 0, &descriptor_update_template);`
**内存崩掉了，然后被系统强杀。**

**原因分析：**
0=1 表示average pool，1和11表示kernal的h和w，2和12表示pad的h和w，以此来代替reduce操作，该方法在ncnn arm cpu 上能够得到正确的结果，但是在vulkan gpu上内存会出现上述问题。

**替换方案：**
`Pooling    pool1    1 1 ShuffleNetV2/Stage2/concat_splitncnn_0 pool1 0=1 4=1`
可以在确保正确forward的同时，提升上述推算的速度。

**Comment by luckynote** [comment]
简单的将遇到的问题做了一下总结，详细参见以下两篇blog
[【Android-NCNN-Vulkan】记录一次ncnn-vulkan在低性能开发板上出现的native内存溢出的问题](https://blog.csdn.net/lgh0824/article/details/107074604)
[【Android-NCNN-Vulkan】ncnn-vulkan load param & model 速度慢](https://blog.csdn.net/lgh0824/article/details/107103936)

**Comment by nihui** [comment]
关于 gpu load 速度慢的问题，正在做 pipeline cache ...
在做了，在做了

**Comment by nihui** [comment]
online pipeline cache 已经合并到 master 了，gpu 加载模型应该会快很多

**Comment by luckynote** [comment]
> online pipeline cache 已经合并到 master 了，gpu 加载模型应该会快很多

厉害了，同比之前 load param 降低 8s，load model降低50-80s，pipeline cache效果很明显
