### ISSUE TITLE
ncnn load_param报0xC0000005: 读取位置 0xFFFFFFFFFFFFFFF7 时发生访问冲突

### ISSUE THREAD

**Issue by steelOneself** [Tencent/ncnn#1888]
### param和bin文件
[test.zip](https://github.com/Tencent/ncnn/files/4844390/test.zip)

### 测试代码如下
```
ncnn::Net test_net;

//load model
std::string param_files = "test.param";
std::string bin_files = "test.bin";
test_net.load_param(param_files.c_str());
test_net.load_model(bin_files.c_str());
```
### 测试环境
操作系统：win10
开发软件：visual studio2019

### 错误信息
![image](https://user-images.githubusercontent.com/20657139/85986322-a0eea100-ba1e-11ea-89ea-be1fe490095a.png)

0x00007FF6451114DE 处(位于 ncnn_developy.exe 中)引发的异常: 0xC0000005: 读取位置 0xFFFFFFFFFFFFFFF7 时发生访问冲突。 出现了 
![image](https://user-images.githubusercontent.com/20657139/85986427-cd0a2200-ba1e-11ea-979c-95c6514e9a93.png)

通过调试定位错误发现报错位置是：**load_param**方法

通过ncnn加载其它的网络没有问题，不知道是什么原因导致这个问题，模型我是用mxnet训练的，网络是自己设计的，在使用mxnet2ncnn转换的时候，没有任何的错误信息。

**Comment by nihui** [comment]
param 文件中，存在多个同名的 layer 和 blob，比如 pool0_fwd，这会导致加载出错

可以 mxnet gluon symbol 名字增加前缀后缀，防止重名

**Comment by steelOneself** [comment]
谢谢nihui大神！

**Comment by nihui** [comment]
> 
> 
> 谢谢nihui大神！

不客气！不客气！
