### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Ryuk17** [Tencent/ncnn#1906]
Linux平台 opencv版本2.4.9.1

tools/quantize/CMakeFiles/ncnn2table.dir/build.make:62: recipe for target 'tools/quantize/CMakeFiles/ncnn2table.dir/ncnn2table.cpp.o' failed
make[2]: *** [tools/quantize/CMakeFiles/ncnn2table.dir/ncnn2table.cpp.o] Error 1
CMakeFiles/Makefile2:1051: recipe for target 'tools/quantize/CMakeFiles/ncnn2table.dir/all' failed
make[1]: *** [tools/quantize/CMakeFiles/ncnn2table.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

如果我把CMakelist中127行的
add_subdirectory(tools)
注释掉则可以编译通过

**Comment by nihui** [comment]
你把 tools/CMakeLists.txt 的 add_subdirectory(quantize) 就可以不编译 ncnn2table，不用整个tools注释掉

**Comment by Ryuk17** [comment]
我把 add_subdirectory(quantize)注释掉了后面的ncnn2int8不也不编译，那不就不能做量化了

**Comment by Ryuk17** [comment]
使用了新版本的opencv, 问题已解决，谢谢up

**Comment by zhepherd** [comment]
> 使用了新版本的opencv, 问题已解决，谢谢up
你的是什么版本的opencv，我的是3.4也报错

**Comment by Ryuk17** [comment]
> > 使用了新版本的opencv, 问题已解决，谢谢up
> > 你的是什么版本的opencv，我的是3.4也报错

我的版本是opencv-3.4.3
