### ISSUE TITLE
Vulkan API

### ISSUE THREAD

**Issue by vinorth05** [Tencent/ncnn#1907]
Hello, 

I saw Vulkan drivers can have great performance on a embedded machines such as RaspberryPi:
https://www.tomshardware.com/news/nvidia-engineer-vulkan-driver-raspberry-pi-quake-iii-100-fps

So, is it possible to have the same with NCNN vulkan for Deep learning models such as YOLO or SSD on raspberry pi?

Thank you in advance,
Best regards

**Comment by nihui** [comment]
As long as the driver supports compute shader, it is definitely possible.
