### ISSUE TITLE
build examples failed, 'platform.h' file not found & ld: library not found for -lncnn

### ISSUE THREAD

**Issue by DRosemei** [Tencent/ncnn#1910]
cd <ncnn-root-dir>
cd examples
mkdir build
cd build
cmake ..
make -j4
然后出现错误，'platform.h' file not found
我找到'platform.h'在编译的ncnn路径 <ncnn-root-dir>/build/install/include/install/include 里面，在CMakeLists.txt更改路径后，再次make，出现下面的错误
(base) rose@RosedeMacBook-Pro build % make -j4
Scanning dependencies of target mobilenetssd
Scanning dependencies of target mobilenetv2ssdlite
Scanning dependencies of target simplepose
Scanning dependencies of target retinaface
[  7%] Building CXX object CMakeFiles/mobilenetv2ssdlite.dir/mobilenetv2ssdlite.o
[  7%] Building CXX object CMakeFiles/mobilenetssd.dir/mobilenetssd.o
[ 14%] Building CXX object CMakeFiles/retinaface.dir/retinaface.o
[ 14%] Building CXX object CMakeFiles/simplepose.dir/simplepose.o
[ 21%] Linking CXX executable mobilenetssd
[ 21%] Linking CXX executable mobilenetv2ssdlite
[ 25%] Linking CXX executable simplepose
ld: library not found for -lncnn
ld: library not found for -lncnn
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mobilenetv2ssdlite] Error 1make[2]: 
*** [mobilenetssd] Error 1
make[1]: *** [CMakeFiles/mobilenetv2ssdlite.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/mobilenetssd.dir/all] Error 2
ld: library not found for -lncnn
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [simplepose] Error 1
make[1]: *** [CMakeFiles/simplepose.dir/all] Error 2

然后我又在<ncnn-root-dir>/src目录下进行编译，出现error: no member named 'from_pixels' in 'ncnn::Mat'
请问应该怎么解决呢

**Comment by nihui** [comment]
参考文档的步骤

https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-macosx

example 需要先 brew install opencv3

**Comment by DRosemei** [comment]
brew install opencv3太慢了，我是用源码安装opencv的，会有区别吗？

**Comment by DRosemei** [comment]
我给brew换源后，通过brew install opencv3安装好了opencv，仍然是上面的错误
