### ISSUE TITLE
.bin file load time

### ISSUE THREAD

**Issue by lsg945** [Tencent/ncnn#1911]
Hello, 
I have converted a darknet yolov4 model into .bin format using the darknet2ncnn and ncnnoptimize tools. The resulting file occupies 250MB on disk. In an Android project I have natively included the ncnn library and when loading the file this happens:

![imagen](https://user-images.githubusercontent.com/32260912/86520881-b4986e00-be49-11ea-8bf1-dbd87cfa4de3.png)

I have loaded the .bin file like this:

![imagen](https://user-images.githubusercontent.com/32260912/86520918-2a9cd500-be4a-11ea-9ee3-a5ffa5b1d50a.png)

How can I reduce the loading time of the .bin file?

Thank you in advance,
Best regards

**Comment by nihui** [comment]
The vanilla yolov4 is too heavy for deploying on mobile
I suggest using yolov4-tiny, see https://github.com/Tencent/ncnn/blob/master/examples/yolov4.cpp

**Comment by lsg945** [comment]
Hi, again. I have changed to yolov4-tiny, I can detect objects by executing it in darknet but when passing it with the darknet2ncnn and ncnnoptimize tools the model with ncnn does not detect anything on Android.

**Comment by nihui** [comment]
Some good news here. There are some android project of yolo detection cooked by the community !
You may take them as reference

https://github.com/WZTENG/YOLOv5_NCNN
https://github.com/dog-qiuqiu/Android_NCNN_yolov4-tiny
https://github.com/dog-qiuqiu/Android_MobileNetV2-YOLOV3-Nano-NCNN
