### ISSUE TITLE
compile dynamic error

### ISSUE THREAD

**Issue by cqray1990** [Tencent/ncnn#1915]
selu.cpp:(.text+0xec)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(hardswish.cpp.o)：在函数‘ncnn::HardSwish::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
hardswish.cpp:(.text+0xcf)：对‘GOMP_parallel’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(hardswish.cpp.o)：在函数‘ncnn::HardSwish::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
hardswish.cpp:(.text+0xfb)：对‘omp_get_num_threads’未定义的引用
hardswish.cpp:(.text+0x103)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(hardswish_x86.cpp.o)：在函数‘ncnn::HardSwish_x86::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
hardswish_x86.cpp:(.text+0x3f)：对‘GOMP_parallel’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(hardswish_x86.cpp.o)：在函数‘ncnn::HardSwish_x86::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
hardswish_x86.cpp:(.text+0x7b)：对‘omp_get_num_threads’未定义的引用
hardswish_x86.cpp:(.text+0x83)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(pixelshuffle.cpp.o)：在函数‘ncnn::PixelShuffle::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
pixelshuffle.cpp:(.text+0x35)：对‘omp_get_num_threads’未定义的引用
pixelshuffle.cpp:(.text+0x3c)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(pixelshuffle.cpp.o)：在函数‘ncnn::PixelShuffle::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const’中：
pixelshuffle.cpp:(.text+0x391)：对‘GOMP_parallel’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(mish.cpp.o)：在函数‘ncnn::Mish::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
mish.cpp:(.text+0x3a)：对‘GOMP_parallel’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(mish.cpp.o)：在函数‘ncnn::Mish::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
mish.cpp:(.text+0x75)：对‘omp_get_num_threads’未定义的引用
mish.cpp:(.text+0x7d)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(mish_x86.cpp.o)：在函数‘ncnn::Mish_x86::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
mish_x86.cpp:(.text+0x3a)：对‘GOMP_parallel’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(mish_x86.cpp.o)：在函数‘ncnn::Mish_x86::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
mish_x86.cpp:(.text+0x85)：对‘omp_get_num_threads’未定义的引用
mish_x86.cpp:(.text+0x8d)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(statisticspooling.cpp.o)：在函数‘ncnn::StatisticsPooling::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
statisticspooling.cpp:(.text+0x35)：对‘omp_get_num_threads’未定义的引用
statisticspooling.cpp:(.text+0x3d)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(statisticspooling.cpp.o)：在函数‘ncnn::StatisticsPooling::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.1]’中：
statisticspooling.cpp:(.text+0x28c)：对‘omp_get_num_threads’未定义的引用
statisticspooling.cpp:(.text+0x294)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(statisticspooling.cpp.o)：在函数‘ncnn::StatisticsPooling::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const’中：
statisticspooling.cpp:(.text+0x4d9)：对‘GOMP_parallel’未定义的引用
statisticspooling.cpp:(.text+0x4fd)：对‘GOMP_parallel’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(swish.cpp.o)：在函数‘ncnn::Swish::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
swish.cpp:(.text+0x3a)：对‘GOMP_parallel’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(swish.cpp.o)：在函数‘ncnn::Swish::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
swish.cpp:(.text+0x75)：对‘omp_get_num_threads’未定义的引用
swish.cpp:(.text+0x7d)：对‘omp_get_thread_num’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(swish_x86.cpp.o)：在函数‘ncnn::Swish_x86::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
swish_x86.cpp:(.text+0x3a)：对‘GOMP_parallel’未定义的引用
/home/lgx/myprj/chineseocr_lite/ncnn_project/myocr/ncnn/lib/libncnn.a(swish_x86.cpp.o)：在函数‘ncnn::Swish_x86::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
swish_x86.cpp:(.text+0x88)：对‘omp_get_num_threads’未定义的引用
swish_x86.cpp:(.text+0x90)：对‘omp_get_thread_num’未定义的引用

thank you so much

**Comment by b1xian** [comment]
@cqray1990 我也遇到了，怎么解决的呢

**Comment by nihui** [comment]
link libgomp or libomp

**Comment by b1xian** [comment]
> link libgomp or libomp

谢谢大佬
