### ISSUE TITLE
arm-himix100-linux-gcc 交叉编译出错

### ISSUE THREAD

**Issue by wjnxiang** [Tencent/ncnn#1917]
hisi3518ev300编译ncnn，
交叉编译链：arm-himix100-linux-gcc
`/ncnn/src/layer/arm/neon_mathfun.h: In function 'float32x4_t loadfp16(const void*)':
/ncnn/src/layer/arm/neon_mathfun.h:33:41: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
     return vcvt_f32_f16(vld1_f16((const __fp16*)ptr));
                                         ^~~~~~
/ncnn/src/layer/arm/neon_mathfun.h:33:35: error: expected primary-expression before 'const'
     return vcvt_f32_f16(vld1_f16((const __fp16*)ptr));
                                   ^~~~~
/ncnn/src/layer/arm/neon_mathfun.h:33:35: error: expected ')' before 'const'`

之前使用committed 6f2ef1932d717c45396f13a182dc347db74e9d1e 是可以编译过去的，
但是libncnn.a 比较大

**Comment by nihui** [comment]
正在修复 https://github.com/Tencent/ncnn/pull/1921

**Comment by nihui** [comment]
https://github.com/nihui/ncnn/tree/fix-arm-loadfp16
请试试看这个branch能不能编译

**Comment by wjnxiang** [comment]
还是不行，汇编不懂....
/ncnn/src/layer/arm/neon_mathfun.h:52:26: error: matching constraint references invalid operand number
         : "memory", "d0");

**Comment by nihui** [comment]
> 还是不行，汇编不懂....
> /ncnn/src/layer/arm/neon_mathfun.h:52:26: error: matching constraint references invalid operand number
> : "memory", "d0");

啊，这里有个地方写错了，现在改正了，更新下试试看

**Comment by wjnxiang** [comment]
可以啦 ，O(∩_∩)O谢谢
