### ISSUE TITLE
TF2.x to ncnn by mlir error:layer tf.ResizeNearestNeighbor not exists or registered

### ISSUE THREAD

**Issue by lovejing0306** [Tencent/ncnn#1929]
在使用tf2.x->mlir->ncnn转模型时，可以成功转换，没有报错。但在加载模型时候会报以下错误

```
layer tf.ResizeNearestNeighbor not exists or registered
Segmentation fault (core dumped)
```

请帮忙看一下，多谢了。

下面是我转换后的mlir文件
https://drive.google.com/file/d/11rjHP8Tasqm3YtFROV6L69YtEovch8mb/view?usp=sharing

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/b2b86fea165174b5a958510e4b4df73182d2d4f2 实现了转换

但是最后的 Reshape 还有点问题尚需解决

**Comment by lovejing0306** [comment]
> [b2b86fe](https://github.com/Tencent/ncnn/commit/b2b86fea165174b5a958510e4b4df73182d2d4f2) 实现了转换
> 
> 但是最后的 Reshape 还有点问题尚需解决

感谢大佬，那我把reshape操作删掉，应该就可以用了，我试试

**Comment by lovejing0306** [comment]
> [b2b86fe](https://github.com/Tencent/ncnn/commit/b2b86fea165174b5a958510e4b4df73182d2d4f2) 实现了转换
> 
> 但是最后的 Reshape 还有点问题尚需解决

大佬，我通过tf2.x->onnx->ncnn把tf2.x的模型转换到了ncnn上，通过测试转换成功了。我先把这个issue关闭了。

**Comment by nihui** [comment]
其实 Reshape 的问题，昨天也应该修好了。。。

**Comment by lovejing0306** [comment]
> 其实 Reshape 的问题，昨天也应该修好了。。。
我明天测试一把，毕竟多个方法多条出路。😁

**Comment by lovejing0306** [comment]
> 其实 Reshape 的问题，昨天也应该修好了。。。


大佬，再多问一句，这个修复的后的bug有合到master分之上吗？

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
