### ISSUE TITLE
发现一个可能的bug

### ISSUE THREAD

**Issue by bjmajic** [Tencent/ncnn#193]
convolution_arm.cpp 中，
`use_winograd3x3 = false;

    if (kernel_size == 3 && dilation == 1 && stride == 1)
    {
        int num_input = weight_data_size / 9 / num_output;
        // winograd is slow on small channel count
        if (num_input >= 16 && num_output >= 16)
            use_winograd3x3 = false;// TODO
    }
`
if 条件成功后，是不是应该把use_winograd3x3设置成true？

**Comment by nihui** [comment]
aarch64 尚未优化到位且未测试，所以暂时没有开启

**Comment by bjmajic** [comment]
好的，多谢解答

**Comment by chenhuizhou** [comment]
armv7是否优化完了，刚才用1920x1080的图片对比了一下，优化效果不是很明显？@nihui
