### ISSUE TITLE
采用pooling 0=1，1=4，得到的结果尺寸为：c = 1, h=1, w=通道数，进一步导致linux与安卓的结果对不上

### ISSUE THREAD

**Issue by lgcy** [Tencent/ncnn#1930]

**Comment by nihui** [comment]
pooling 0=1，1=4 表示 global pooling，ncnn 输出 c = 1, h=1, w=通道数 是正常的
请提供下 param 文件

**Comment by lgcy** [comment]
> pooling 0=1，1=4 表示 global pooling，ncnn 输出 c = 1, h=1, w=通道数 是正常的
> 请提供下 param 文件

但是在Android对输出的map进行卷积操作时，输出的map是异常的，比如pooling的结果为c =1, h=1, w=21，用1*1*42的卷积去卷，输出的结果为c = 42, h=1, w=42，在linux的输出为 c =1, h=1, w=42。
大佬，param文件我可以qq发给你吗

**Comment by nihui** [comment]
> > pooling 0=1，1=4 表示 global pooling，ncnn 输出 c = 1, h=1, w=通道数 是正常的
> > 请提供下 param 文件
> 
> 但是在Android对输出的map进行卷积操作时，输出的map是异常的，比如pooling的结果为c =1, h=1, w=21，用1×1×42的卷积去卷，输出的结果为c = 42, h=1, w=42，在linux的输出为 c =1, h=1, w=42。
> 大佬，param文件我可以qq发给你吗

可以加QQ群发我
