### ISSUE TITLE
Where floor and ceil methods are reflected in pooling layer ?

### ISSUE THREAD

**Issue by AIGirl10** [Tencent/ncnn#1933]
Can anyone please tell use where floor() and ceil() methods are reflected in the pooling layer, since I need to replace ceil() method with floor() method , since it was done in the caffemodel, need to do for NCNN model too. Please let us know.

**Comment by nihui** [comment]
```5=0``` full padding aka ceil
```5=1``` valid padding aka floor

**Comment by AIGirl10** [comment]
yes thanks, that solved my doubt. 

Closing this issue.
