### ISSUE TITLE
Convert MobileNetV2_05-sim.onnx to ncnn，出现：Unsupported reduction axes !

### ISSUE THREAD

**Issue by DRosemei** [Tencent/ncnn#1938]
将MobileNetV2，width=0.5 的onnx模型，首先经过onnx-simplify简化模型，然后使用onnx2ncnn转换ncnn模型，出现Unsupported reduction axes ! 但模型是能生成的，请问这样会有影响吗？

**Comment by nihui** [comment]
可以打开 param，把 Reduction 这层改为 Pooling 实现 global average pooling
```
Pooling                  globalavgpool                    1 1 input output 0=1 4=1
```

在 pytorch 中，global average pooling 可以用 adaptive pooling 实现，这样就能避免 reduction

**Comment by DRosemei** [comment]
Thx，因为之前在导出trt模型的时候需要把adaptive pooling改成global average pooling

**Comment by DRosemei** [comment]
顺便问下MobileNetV3 出现 Expand not supported yet!应该怎么解决呢？

**Comment by nihui** [comment]
可以试试看，直接把 param 的 Expand 替换为 Noop

**Comment by yuqiu1233** [comment]
您好，同样出现该问题
Unsupported reduction axes ! 
segment fault
通过查看onnx的op发现应该是ReduceSum导致该问题，请问应该如何解决呢？

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
