### ISSUE TITLE
which minimum gcc & g++ is required?

### ISSUE THREAD

**Issue by quocnhat** [Tencent/ncnn#1939]
When downgrade gcc & g++ to 4.8.5 on ubuntu 18.04, I got a lot of errors "undefined reference to..." when builing ncnn linux X86. Is it caused by gcc version? (It is fine with original gcc 7.5.0). thank you

**Comment by nihui** [comment]
```
export CC=gcc-4.8
export CXX=g++-4.8
cmake ..
```

**Comment by quocnhat** [comment]
Thank for your response, But it doesn't work. Here is a short snapshot:

[ 46%] Linking CXX static library libncnn.a
[ 46%] Built target ncnn
[ 46%] Linking CXX executable caffe2ncnn
CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o: In function `caffe::NetState::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const':
caffe.pb.cc:(.text+0x2038): undefined reference to `google::protobuf::internal::WireFormatLite::WriteString(int, std::string const&, google::protobuf::io::CodedOutputStream*)'
CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o: In function CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o:(.rodata._ZTVN5caffe14PReLUParameterE[_ZTVN5caffe14PReLUParameterE]+0x20): undefined reference to `google::protobuf::Message::GetTypeName() const'
CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o:(.rodata._ZTVN5caffe14PReLUParameterE[_ZTVN5caffe14PReLUParameterE]+0x58): undefined reference to `google::protobuf::Message::InitializationErrorString() const'
collect2: error: ld returned 1 exit status
tools/caffe/CMakeFiles/caffe2ncnn.dir/build.make:129: recipe for target 'tools/caffe/caffe2ncnn' failed
make[2]: *** [tools/caffe/caffe2ncnn] Error 1
CMakeFiles/Makefile2:859: recipe for target 'tools/caffe/CMakeFiles/caffe2ncnn.dir/all' failed
make[1]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Can you give me some advice? pls

**Comment by nihui** [comment]
resolve in https://github.com/Tencent/ncnn/issues/1423
