### ISSUE TITLE
darknet2ncnn.cpp中maxpool参数输出有些问题

### ISSUE THREAD

**Issue by ysc703** [Tencent/ncnn#1941]
https://github.com/Tencent/ncnn/blob/3ff40b0679aa5e069a821e45ceb02834ea44c145/tools/darknet/darknet2ncnn.cpp#L475
当该层输入的宽高不同时，s->out_w可能不等于s->out_h。
应该是:  s->out_w = (s->w + s->padding - s->size) / s->stride + 1;

**Comment by xiakj** [comment]
请问您是转的哪个模型，在ncnn上跑效果怎么样？

**Comment by nihui** [comment]
修好了
