### ISSUE TITLE
加入稀疏矩阵运算可否提高速度?

### ISSUE THREAD

**Issue by wenston2006** [Tencent/ncnn#195]
如题, 现在有些采用稀疏矩阵运算来提速的, ncnn是否有类似优化?

**Comment by HustCoderHu** [comment]
@wenston2006  稀疏矩阵提速的，可否举个例子

**Comment by zkfzle** [comment]
用稀疏矩阵的话，内存开销在手机平台会太大吧

**Comment by nihui** [comment]
稀疏矩阵运算对于内存访问不友好，不易优化，除非极度稀疏，否则无法提高速度
