### ISSUE TITLE
No vulkan device

### ISSUE THREAD

**Issue by lincolnhard** [Tencent/ncnn#1952]
執行
./benchncnn 4 8 0 0 0
顯示no vulkan device

但是參考了https://github.com/nihui/ncnn-android-mobilenetssd
編成apk檔案卻可以成功運行GPU

log顯示有抓到vulkan device

測試環境是Redmi note8 MIUI 11.05

請問有遇過這種問題嗎 謝謝

**Comment by nihui** [comment]
可能因为 android 10 对 adb shell 程序使用 vulkan 增加了限制

我后来写了个ncnn benchmark app
https://github.com/nihui/ncnn-android-benchmark

**Comment by lincolnhard** [comment]
了解了 謝謝
