### ISSUE TITLE
在x86平台打开AVX2后，编译失败

### ISSUE THREAD

**Issue by bin913** [Tencent/ncnn#1953]
按照build for VS2017.zh进行操作，在执行nmake报错，提示 error C2668: “ncnn::_mm_store_si128”: 对重载函数的调用不明确

**Comment by nihui** [comment]
是最新的 git 代码吗？

**Comment by nihui** [comment]
修好了

**Comment by bin913** [comment]
更新之后，重新编译下，好了没有问题了

**Comment by nihui** [comment]
> 更新之后，重新编译下，好了没有问题了

好的，感谢反馈~
