### ISSUE TITLE
problem when setting fork() =0

### ISSUE THREAD

**Issue by quocnhat** [Tencent/ncnn#1955]
Hi all, My retina model works fine. But when setting executable under fork() =0, it does not work with no bug. Does anyone know this? thank you.

**Comment by nihui** [comment]
Hi, please provide a small piece of code that could reproduce this problem

**Comment by quocnhat** [comment]
thank you for your attention. At this snapshot, parent process is waiting for the return status from child process. As I mentioned, the child process (retina face detection from your examples) executes with no bug and does not return anything. that's why the whole process is suspended. 
![image](https://user-images.githubusercontent.com/19263564/88246125-c8562800-ccc3-11ea-9a3d-ea550f47c648.png)

**Comment by quocnhat** [comment]
@nihui  without fork(), everything is doing well. Is there any limitation for the system when using fork()? I see that my program stops at extract function: ex.extract("face_rpn_cls_prob_reshape_stride32", score_blob);. No bug and do not return status for "wait" function in the parent.

**Comment by quocnhat** [comment]
solved: force the software run on a single thread.
