### ISSUE TITLE
最新的ncnn，使用bf16在arm上做推理，输出结果异常

### ISSUE THREAD

**Issue by jiyinghui39** [Tencent/ncnn#1962]
使用最新的ncnn分支。
我分别在Arm A53和A35上，使用opt.use_packing_layout = true;opt.use_bf16_storage = true;选项。
加载FP32的ultraFace模型。结果全部是错误的，还很异常，每次输出的结果还不一样。这个可能是什么问题呢@nihui

**Comment by jiyinghui39** [comment]
有遇到类似情况吗？期待解答。按照相同的方法，在x86上是推理是ok的。

**Comment by nihui** [comment]
已确认 bug

**Comment by jiyinghui39** [comment]
好的。感谢大神解答，修复了麻烦同步我们感谢。@nihui

**Comment by nihui** [comment]
应该修好了 ....

**Comment by jiyinghui39** [comment]
验证应该是可以了。接下来会进行性能评估。
赞修复速度
