### ISSUE TITLE
你好，我是通过onnx转ncnn，发现onnx输出的形状（预期）和param输出的形状不一致，且同一生成文件在不同时间输出的数值存在不一致

### ISSUE THREAD

**Issue by huihuixiaohuihui** [Tencent/ncnn#1964]
7767517
125 136
Input            input.1                  0 1 input.1
MemoryData       194                      0 1 194 0=37
Convolution      195                      1 1 input.1 195 0=32 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=288
BatchNorm        196                      1 1 195 196 0=32
ReLU             197                      1 1 196 197
Convolution      198                      1 1 197 198 0=64 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=18432
BatchNorm        199                      1 1 198 199 0=64
ReLU             200                      1 1 199 200
Pooling          201                      1 1 200 201 0=0 1=2 11=2 2=2 12=2 3=0 13=0 14=0 15=0 5=1
Split            splitncnn_0              1 2 201 201_splitncnn_0 201_splitncnn_1
Convolution      202                      1 1 201_splitncnn_1 202 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=73728
BatchNorm        203                      1 1 202 203 0=128
ReLU             204                      1 1 203 204
Convolution      205                      1 1 204 205 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=147456
BatchNorm        206                      1 1 205 206 0=128
Convolution      207                      1 1 201_splitncnn_0 207 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=8192
BatchNorm        208                      1 1 207 208 0=128
BinaryOp         209                      2 1 206 208 209 0=0
ReLU             210                      1 1 209 210
Convolution      211                      1 1 210 211 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=147456
BatchNorm        212                      1 1 211 212 0=128
ReLU             213                      1 1 212 213
Pooling          214                      1 1 213 214 0=0 1=2 11=2 2=2 12=2 3=0 13=0 14=0 15=0 5=1
Split            splitncnn_1              1 2 214 214_splitncnn_0 214_splitncnn_1
Convolution      215                      1 1 214_splitncnn_1 215 0=256 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=294912
BatchNorm        216                      1 1 215 216 0=256
ReLU             217                      1 1 216 217
Convolution      218                      1 1 217 218 0=256 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=589824
BatchNorm        219                      1 1 218 219 0=256
Convolution      220                      1 1 214_splitncnn_0 220 0=256 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=32768
BatchNorm        221                      1 1 220 221 0=256
BinaryOp         222                      2 1 219 221 222 0=0
ReLU             223                      1 1 222 223
Split            splitncnn_2              1 2 223 223_splitncnn_0 223_splitncnn_1
Convolution      224                      1 1 223_splitncnn_1 224 0=256 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=589824
BatchNorm        225                      1 1 224 225 0=256
ReLU             226                      1 1 225 226
Convolution      227                      1 1 226 227 0=256 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=589824
BatchNorm        228                      1 1 227 228 0=256
BinaryOp         229                      2 1 228 223_splitncnn_0 229 0=0
ReLU             230                      1 1 229 230
Convolution      231                      1 1 230 231 0=256 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=589824
BatchNorm        232                      1 1 231 232 0=256
ReLU             233                      1 1 232 233
Pooling          234                      1 1 233 234 0=0 1=2 11=2 2=1 12=2 3=1 13=0 14=1 15=0 5=1
Split            splitncnn_3              1 2 234 234_splitncnn_0 234_splitncnn_1
Convolution      235                      1 1 234_splitncnn_1 235 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=1179648
BatchNorm        236                      1 1 235 236 0=512
ReLU             237                      1 1 236 237
Convolution      238                      1 1 237 238 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        239                      1 1 238 239 0=512
Convolution      240                      1 1 234_splitncnn_0 240 0=512 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=131072
BatchNorm        241                      1 1 240 241 0=512
BinaryOp         242                      2 1 239 241 242 0=0
ReLU             243                      1 1 242 243
Split            splitncnn_4              1 2 243 243_splitncnn_0 243_splitncnn_1
Convolution      244                      1 1 243_splitncnn_1 244 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        245                      1 1 244 245 0=512
ReLU             246                      1 1 245 246
Convolution      247                      1 1 246 247 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        248                      1 1 247 248 0=512
BinaryOp         249                      2 1 248 243_splitncnn_0 249 0=0
ReLU             250                      1 1 249 250
Split            splitncnn_5              1 2 250 250_splitncnn_0 250_splitncnn_1
Convolution      251                      1 1 250_splitncnn_1 251 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        252                      1 1 251 252 0=512
ReLU             253                      1 1 252 253
Convolution      254                      1 1 253 254 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        255                      1 1 254 255 0=512
BinaryOp         256                      2 1 255 250_splitncnn_0 256 0=0
ReLU             257                      1 1 256 257
Split            splitncnn_6              1 2 257 257_splitncnn_0 257_splitncnn_1
Convolution      258                      1 1 257_splitncnn_1 258 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        259                      1 1 258 259 0=512
ReLU             260                      1 1 259 260
Convolution      261                      1 1 260 261 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        262                      1 1 261 262 0=512
BinaryOp         263                      2 1 262 257_splitncnn_0 263 0=0
ReLU             264                      1 1 263 264
Split            splitncnn_7              1 2 264 264_splitncnn_0 264_splitncnn_1
Convolution      265                      1 1 264_splitncnn_1 265 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        266                      1 1 265 266 0=512
ReLU             267                      1 1 266 267
Convolution      268                      1 1 267 268 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        269                      1 1 268 269 0=512
BinaryOp         270                      2 1 269 264_splitncnn_0 270 0=0
ReLU             271                      1 1 270 271
Convolution      272                      1 1 271 272 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        273                      1 1 272 273 0=512
ReLU             274                      1 1 273 274
Split            splitncnn_8              1 2 274 274_splitncnn_0 274_splitncnn_1
Convolution      275                      1 1 274_splitncnn_1 275 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        276                      1 1 275 276 0=512
ReLU             277                      1 1 276 277
Convolution      278                      1 1 277 278 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        279                      1 1 278 279 0=512
BinaryOp         280                      2 1 279 274_splitncnn_0 280 0=0
ReLU             281                      1 1 280 281
Split            splitncnn_9              1 2 281 281_splitncnn_0 281_splitncnn_1
Convolution      282                      1 1 281_splitncnn_1 282 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        283                      1 1 282 283 0=512
ReLU             284                      1 1 283 284
Convolution      285                      1 1 284 285 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        286                      1 1 285 286 0=512
BinaryOp         287                      2 1 286 281_splitncnn_0 287 0=0
ReLU             288                      1 1 287 288
Split            splitncnn_10             1 2 288 288_splitncnn_0 288_splitncnn_1
Convolution      289                      1 1 288_splitncnn_1 289 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        290                      1 1 289 290 0=512
ReLU             291                      1 1 290 291
Convolution      292                      1 1 291 292 0=512 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2359296
BatchNorm        293                      1 1 292 293 0=512
BinaryOp         294                      2 1 293 288_splitncnn_0 294 0=0
ReLU             295                      1 1 294 295
Convolution      296                      1 1 295 296 0=512 1=2 11=2 2=1 12=1 3=1 13=2 4=1 14=0 15=1 16=0 5=0 6=1048576
BatchNorm        297                      1 1 296 297 0=512
ReLU             298                      1 1 297 298
Convolution      299                      1 1 298 299 0=512 1=2 11=2 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=1048576
BatchNorm        300                      1 1 299 300 0=512
ReLU             301                      1 1 300 301
Permute          302                      1 1 301 302 0=4
Pooling          303                      1 1 302 303 0=1 1=1 11=1 2=1 12=1 5=1 6=0
Squeeze          304                      1 1 303 304 -23303=1,3
InnerProduct     306                      1 1 304 306 0=37 1=0 2=18944
BinaryOp         307                      2 1 306 194 307 0=0

**Comment by nihui** [comment]
```
Permute 302 1 1 301 302 0=4
Pooling 303 1 1 302 303 0=1 1=1 11=1 2=1 12=1 5=1 6=0
Squeeze 304 1 1 303 304 -23303=1,3
```
最后这几个op看起来有点问题
你的 onnx 是 pytorch 转过来的吗？globalpooling 用 adaptivepooling 实现

**Comment by huihuixiaohuihui** [comment]
是的 我是pth转过来的

**Comment by huihuixiaohuihui** [comment]
我的代码里确实用到了Adaptivepooling函数
self.AdaptiveAvgPool = nn.AdaptiveAvgPool2d((512, 1))
不知道你说的globalpooling 用adaptivepooling 是什么意思怎么修改？？

**Comment by zylo117** [comment]
我也遇到这种问题。才发现onnx并不支持adaptive avg/max pooling，即便你在pytorch用了adaptive pooling，转换到onnx也会被当成global pooling，丢失了adaptive的信息，所以用onnx2ncnn怎么样都不会转换成adaptive的了

这里有onnx全部ops，并没有adaptive pooling
https://github.com/onnx/onnx/blob/master/docs/Operators.md

虽然20210124版的这个pr说解决了这个问题，支持pytorch的adaptive转换，不过pytorch要先转换到onnx，但是到了onnx已经没有了adaptive的参数了，怎么转换成ncnn的adaptive呢？手工修改？

https://github.com/Tencent/ncnn/pull/2546

最要命的是，即便用global pooling，其实在onnxruntime（cpu、gpu）还是可以跑出正确结果的，ncnn的x86 cpu模式也可以跑，完全正常，但是用vulkan跑就nan（形状正常），或者int8后跑就形状异常（和这个issue一样的问题）。

@nihui 

所以有两个可能存在的问题，
1. ncnn并没有真正支持pytorch adaptive pooling
2. ncnn x86 cpu和vulkan、int8的实现并不一致

**Comment by nihui** [comment]
> 
> 
> 我也遇到这种问题。才发现onnx并不支持adaptive avg/max pooling，即便你在pytorch用了adaptive pooling，转换到onnx也会被当成global pooling，丢失了adaptive的信息，所以用onnx2ncnn怎么样都不会转换成adaptive的了
> 
> 这里有onnx全部ops，并没有adaptive pooling
> https://github.com/onnx/onnx/blob/master/docs/Operators.md
> 
> 虽然20210124版的这个pr说解决了这个问题，支持pytorch的adaptive转换，不过pytorch要先转换到onnx，但是到了onnx已经没有了adaptive的参数了，怎么转换成ncnn的adaptive呢？手工修改？
> 
> #2546
> 
> 最要命的是，即便用global pooling，其实在onnxruntime（cpu、gpu）还是可以跑出正确结果的，ncnn的x86 cpu模式也可以跑，完全正常，但是用vulkan跑就nan（形状正常），或者int8后跑就形状异常（和这个issue一样的问题）。
> 
> @nihui
> 
> 所以有两个可能存在的问题，
> 
>     1. ncnn并没有真正支持pytorch adaptive pooling
> 
>     2. ncnn x86 cpu和vulkan、int8的实现并不一致

1 据pr作者说，得用比较新版本的 pytorch 导出
2 有待确认，如果确实有问题一定会修好的 ~ （个人严重怀疑是有bug）

**Comment by zylo117** [comment]
```
torch                     1.7.1+cu110
torchvision               0.8.2+cu110
```
已经是最新的官方稳定版了，1.7.1。但是onnx都不支持adaptive，它又能把adaptive的信息放到哪里呢。

**Comment by zylo117** [comment]
我昨天遇到的这个问题，估计也是ncnn int8模式下global avg pooling 的实现和float32不同（从channel wise变成batch wise），经过这一层的形状都变了， 导致最终结果改变
https://github.com/Tencent/ncnn/issues/2623

**Comment by zylo117** [comment]
经过手工修改，把误以为是global avg pooling的层，改成adaptive avg pooling的层后，以及修改因此而连带误用的InnerProduct为Convolution，对应的参数的一些修改，结果和形状就都正常了。

但是这个操作需要知道那一层是真的adaptive，万一模型混用了global pooling，那修改起来就超费劲。
所以还是希望可以在做个monkey-patching，在pytorch导出onnx时，自动记录出onnx那一层本应是adaptive pooling，然后在onnx2ncnn中读取该信息，并转换成原本的样子。

或者说，既然ncnn在float32/16下执行正常，都可以猜到应有的形状（如果不是歪打正着的话），是不是可以把这个方法直接应用到int8预测中呢？

**Comment by zylo117** [comment]
全局替换global avg pooling为adaptive avg pooling，及其下一层的InnerProduct改为Convolution的python脚本
亲测可用
```
lines = open('model.param').readlines()

i = 0
for line_idx in range(len(lines)):
    if line_idx != i:
        continue

    if 'GlobalAveragePool' in lines[i]:
        lines[i] = lines[i].replace('GlobalAveragePool', 'AdaptiveAveragePool').replace('4=1', '7=1 8=1 5=1')
    if 'InnerProduct' in lines[i + 1]:
        lines[i + 1] = lines[i + 1].replace('InnerProduct', 'Convolution').replace('1=', '1=1 5=').replace('2=', '6=')
        i += 1

    i += 1
    if i > len(lines) - 2:
        break

open('model_fixed.param', 'w').writelines(lines)
```

**Comment by GuoxiaWang** [comment]
@huihuixiaohuihui @huihuixiaohuihui @nihui 

以下是我使用的方式，其他方式我确实没有去尝试。

1. pytroch 版本是 1.2.0
2. 使用 pytroch 导出模型的时候需要加上 operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK，例如下面的导出函数：
```
    torch.onnx.export(model, dummy_input, model_path, verbose=False, input_names=['data'],
            output_names=['scores'],
            operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
```
3. 在导出onnx模型时，输入的dummy_input一定不要让它整除您设置的 adaptive_pool 输出尺寸大小，例如 nn.AdaptiveAvgPool2d((512, 1))，dumpy_input 的尺寸不要整除 512，否则 pytroch 会自动帮你计算出 AvgPool2d 的 kernel 大小
4. ncnn版本需要在 2021年01月07日以后的版本，即支持 onnx2ncnn 的 AdaptiveAvgPool2d 转化以及推理。

另外，如果其他pytroch版本不支持 AdaptiveAvgPool2d 导出，那么可以像 @nihui 所说的，ncnn 是可以支持修改网络模型结构的，直接去修改对应 .param 文件中对应的的 Pooling 层，参数是 7=1, 8=`out_w`, 18=`out_h`

**Comment by zylo117** [comment]
> @huihuixiaohuihui @huihuixiaohuihui @nihui
> 
> 以下是我使用的方式，其他方式我确实没有去尝试。
> 
> 1. pytroch 版本是 1.2.0
> 2. 使用 pytroch 导出模型的时候需要加上 operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK，例如下面的导出函数：
> 
> ```
>     torch.onnx.export(model, dummy_input, model_path, verbose=False, input_names=['data'],
>             output_names=['scores'],
>             operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)
> ```
> 
> 1. 在导出onnx模型时，输入的dummy_input一定不要让它整除您设置的 adaptive_pool 输出尺寸大小，例如 nn.AdaptiveAvgPool2d((512, 1))，dumpy_input 的尺寸不要整除 512，否则 pytroch 会自动帮你计算出 AvgPool2d 的 kernel 大小
> 2. ncnn版本需要在 2021年01月07日以后的版本，即支持 onnx2ncnn 的 AdaptiveAvgPool2d 转化以及推理。
> 
> 另外，如果其他pytroch版本不支持 AdaptiveAvgPool2d 导出，那么可以像 @nihui 所说的，ncnn 是可以支持修改网络模型结构的，直接去修改对应 .param 文件中对应的的 Pooling 层，参数是 7=1, 8=`out_w`, 18=`out_h`

谢谢，明白了，主要是第二点，没有在readme和代码中看到啊，所以就踩坑

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
