### ISSUE TITLE
Build for ARM Cortex-A family with cross-compiling，在make的时候报错，报错信息如下，请教大佬该如何定位这个问题？

### ISSUE THREAD

**Issue by huanyuguo** [Tencent/ncnn#1966]
/data/arm_linux_gcc/gcc-arm-8.3/bin/../lib/gcc/aarch64-linux-gnu/8.3.0/../../../../aarch64-linux-gnu/bin/ld: /usr/local/lib/libopencv_highgui.so.3.4.10: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
examples/CMakeFiles/yolov3.dir/build.make:100: recipe for target 'examples/yolov3' failed
make[2]: *** [examples/yolov3] Error 1
CMakeFiles/Makefile2:228: recipe for target 'examples/CMakeFiles/yolov3.dir/all' failed
make[1]: *** [examples/CMakeFiles/yolov3.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zchrissirhcz** [comment]
Hi, @huanyuguo

It might be you are linking x86_64 version of opencv to your arm compilation process. Consider `/usr/local/lib/libopencv_highgui.so.3.4.10` should mostly like being an x86_64 linux file. You may manifest it via `file /usr/local/lib/libopencv_highgui.so.3.4.10` to see its file type.

ref: https://stackoverflow.com/questions/27967802/libstdc-so-error-adding-symbols-file-in-wrong-format

**Comment by zchrissirhcz** [comment]
Hi, @huanyuguo

It might be you are linking x86_64 version of opencv to your arm compilation process. Consider `/usr/local/lib/libopencv_highgui.so.3.4.10` should mostly like being an x86_64 linux file. You may manifest it via `file /usr/local/lib/libopencv_highgui.so.3.4.10` to see its file type.

If my guess is correct, then you should cross-compile opencv first, then linking that opencv in your current program.

ref: https://stackoverflow.com/questions/27967802/libstdc-so-error-adding-symbols-file-in-wrong-format

**Comment by huanyuguo** [comment]
First of all, thank you very much. Inspired by you, I uninstalled opencv from Linux this morning, then cross-compiled again, and the result was successful, so I wonder if it was caused by the installation of opencv in the Linux system

**Comment by fcyella** [comment]
it's definitely this file format issue.  You need make sure you have opencv in your toolchain or cross compile it first.

**Comment by nihui** [comment]
feel free to reopen issue for further communication :D
