### ISSUE TITLE
我这边有fp16格式推断的检测模型，相比于fp32也未衰减多少，很赞，但是推断时间上并未有丝毫减少，还多了一些，请问一般情况下ncnn在处理fp16模型的时间的效果情况，网上这方面材料较少，在代码中有需要设置什么flag参数，让推断代码知道调用是fp16模型吗？

### ISSUE THREAD

**Issue by 2017ZYS** [Tencent/ncnn#1967]

**Comment by nihui** [comment]
```
net.opt.use_fp16_packed = true;
net.opt.use_fp16_storage = true;
net.opt.use_fp16_arithmetic = true;
```

设置后，会检查硬件特性，自动在支持 fp16 storage/arithmetic 的情况下使用 fp16 推断
use_fp16_packed / use_fp16_storage 默认就是开启的
use_fp16_arithmetic 因为运算误差会更大些，需要手工开启

然后你没有说是跑 cpu 还是 gpu，也没有说是什么平台
arm cpu 只有 A55 / A75 / A76 / A77 架构支持 fp16_arithmetic，ncnn 的 fp16a 加速代码目前正在实现中....

**Comment by 2017ZYS** [comment]
清楚了，感谢nihui大佬
