### ISSUE TITLE
我怎么感觉linear的实现有问题我输入的数据1*26*512 weight为1*512*37 为啥输出的是37*1*1

### ISSUE THREAD

**Issue by huihuixiaohuihui** [Tencent/ncnn#1970]

**Comment by FlyingFishBird** [comment]
mark

**Comment by FlyingFishBird** [comment]
我也遇到了这个问题。不管我怎么调整输入的形状，输出都是固定的

**Comment by FlyingFishBird** [comment]
这是我的测试模型:
```python
import torch
import torch.nn as nn


class PianoTranscriber(nn.Module):
    def __init__(self):
        super(PianoTranscriber, self).__init__()

        self.dense = nn.Linear(in_features=128, out_features=256)

    def forward(self, x):
        return self.dense(x)


if __name__ == '__main__':
    x = torch.rand((6, 128))
    model = PianoTranscriber()
    data = model(x)
    print(data.shape, data)

    torch.onnx.export(model,
                      x,
                      "1.onnx",
                      verbose=True,
                      input_names=["data"],
                      output_names=["prob"])

```

输出形状应该是 6,256 
ncnn 对 线性正层的符号支持应该有缺少

**Comment by huihuixiaohuihui** [comment]
是的 这个linear功能 我是自己在ncnn实现了这个功能函数

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/pull/2607

**Comment by nihui** [comment]
最新版本ncnn已支持二维 gemm 的 innerproduct 计算

**Comment by xiaoMrzhang** [comment]
请问目前master分支已经修正了这个操作吗？我测试使用一层Linear层也会出现类似的问题，有时候还会出现segmentation fault。转换之前的onnx模型是没有问题的。

**Comment by nihui** [comment]
> 请问目前master分支已经修正了这个操作吗？我测试使用一层Linear层也会出现类似的问题，有时候还会出现segmentation fault。转换之前的onnx模型是没有问题的。

最新版本推荐使用 pnnx 转换模型

**Comment by xiaoMrzhang** [comment]
> 
> 最新版本推荐使用 pnnx 转换模型

好的，我尝试下pnnx，多谢

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
