### ISSUE TITLE
optimize问题

### ISSUE THREAD

**Issue by GUN-xing** [Tencent/ncnn#1978]
https://github.com/Tencent/ncnn/blob/master/docs/how-to-use-and-FAQ/use-ncnnoptimize-to-optimize-model.zh.md
![image](https://user-images.githubusercontent.com/34390030/88678651-46318d80-d121-11ea-8ce5-d0470af96dd1.png)

请教一下：
按照这个文档的说法，是在做optimize的时候可以根据硬件平台做特定的优化嘛？
如果是的话，在执行optimize的时候怎么指定硬件平台？还是说需要编译一个对应硬件平台上的tools？

**Comment by nihui** [comment]
这个文档已过时，不需要自动调优了

**Comment by GUN-xing** [comment]
意思是在PC上直接执行optimize就可以了对吧

**Comment by nihui** [comment]
是的

**Comment by GUN-xing** [comment]
好的，谢谢大佬
