### ISSUE TITLE
make -j 出现问题。。

### ISSUE THREAD

**Issue by IMYBo** [Tencent/ncnn#1980]
我准备将onnx模型导出为ncnn，安装ncnn时make -j,出现bug，protoc --version的版本号为libprotoc 3.6.0，不知道是啥问题，然后出现bug后tools里也有onnx2ncnn的文件，但是我使用时给我提示Segmentation fault (core dumped)，我现在不确定现在是我的模型问题还是onnx2ncnn的文件问题

/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/src/layer/x86/hardsigmoid_x86.cpp: In member function ‘virtual int ncnn::HardSigmoid_x86::forward_inplace(ncnn::Mat&, const ncnn::Option&) const’:
/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/src/layer/x86/hardsigmoid_x86.cpp:36:9: warning: unused variable ‘elempack’ [-Wunused-variable]
     int elempack = bottom_top_blob.elempack;
         ^
[ 64%] Building CXX object src/CMakeFiles/ncnn.dir/layer/hardswish.cpp.o
[ 64%] Building CXX object src/CMakeFiles/ncnn.dir/layer/selu.cpp.o
/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/build/src/layer/x86/cast_x86_avx2.cpp:28:5: error: ‘uint16_t’ does not name a type
     uint16_t m128i_u16[8];
     ^
/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/build/src/layer/x86/cast_x86_avx2.cpp:34:5: error: ‘uint32_t’ does not name a type
     uint32_t m256i_u32[8];
     ^
/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/build/src/layer/x86/cast_x86_avx2.cpp: In member function ‘virtual int ncnn::Cast_x86_avx2::forward(const ncnn::Mat&, ncnn::Mat&, const ncnn::Option&) const’:
/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/build/src/layer/x86/cast_x86_avx2.cpp:137:18: error: ‘union m256i’ has no member named ‘m256i_u32’
             mask.m256i_u32[i] = 0x80000000;
                  ^
/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/build/src/layer/x86/cast_x86_avx2.cpp:158:37: error: ‘union m128i’ has no member named ‘m128i_u16’
                 memcpy(outptr, fp16.m128i_u16, remain * sizeof(unsigned short));
                                     ^
/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/build/src/layer/x86/cast_x86_avx2.cpp:169:18: error: ‘union m256i’ has no member named ‘m256i_u32’
             mask.m256i_u32[i] = 0x80000000;
                  ^
/home/work_nfs2/lvshubo/workspace/tools/ncnn-master/build/src/layer/x86/cast_x86_avx2.cpp:189:29: error: ‘union m128i’ has no member named ‘m128i_u16’
                 memcpy(fp16.m128i_u16, ptr, remain * sizeof(unsigned short));
                             ^
src/CMakeFiles/ncnn.dir/build.make:3470: recipe for target 'src/CMakeFiles/ncnn.dir/layer/x86/cast_x86_avx2.cpp.o' failed
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/x86/cast_x86_avx2.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:118: recipe for target 'src/CMakeFiles/ncnn.dir/all' failed
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nihui** [comment]
这里修复了 https://github.com/Tencent/ncnn/commit/b80b84fda51c02bbf5b12030a0b66fea65fbb94e
可以参考修改下

**Comment by IMYBo** [comment]
> 这里修复了 [b80b84f](https://github.com/Tencent/ncnn/commit/b80b84fda51c02bbf5b12030a0b66fea65fbb94e)
> 可以参考修改下

哇，可以可以，make -j没问题了，不过我刚刚运行了一下onnx2ncnn，好像还是有问题，指令是:./onnx2ncnn ../../../test.onnx

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx

**Comment by IMYBo** [comment]
> https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx

多谢大佬，可能是我模型的问题了。。我运行这个demo没问题

**Comment by nihui** [comment]
如果是后处理部分，导出onnx的时候要去掉后处理

**Comment by IMYBo** [comment]
> 如果是后处理部分，导出onnx的时候要去掉后处理

好的~多谢多谢，我再检查一下，不知道是不是某些操作不支持的原因

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
