### ISSUE TITLE
NCNN多次运行，推理结果不一致

### ISSUE THREAD

**Issue by yizhaoyanbo** [Tencent/ncnn#1981]
问题描述：同样的ncnn模型以及同样的模型输入数据，多次运行代码，推理设置为只跑cpu，模型输出的tensor不一致。有时正确，有时错误，截图如下：
![image](https://user-images.githubusercontent.com/26928415/88799950-e4812a00-d1d9-11ea-895b-d48c2c527e9e.png)

开发环境：windows10 + vs2019

ncnn版本: 0616以及0727都测过，不论单线程和多线程，都能够稳定复现。

模型param文件如下：
[model.zip](https://github.com/Tencent/ncnn/files/4994812/model.zip)

忘大佬明察：）

**Comment by nihui** [comment]
这个模型的输入 shape 是什么

**Comment by yizhaoyanbo** [comment]
@nihui  输入shape是1x3x416x416

**Comment by yizhaoyanbo** [comment]
@nihui  发现这个是我的锅，预处理写的有问题，means没有初始化。。。。改完就好了，sorry， 打扰了打扰了。。
