### ISSUE TITLE
opencv not found,quantize tools won't be built,What should I do?Please help me,thank you 

### ISSUE THREAD

**Issue by NeekHua** [Tencent/ncnn#1982]
**Compile vision:**
cmake--3.15.4
protobuf--3.12.3
vulkan--1.1.114.0
vs2017 x64 Command prompt for native tools to compile。
----------------------------------------------------------------------------------------------------------------------------------------
**Problems:**
opencv not found,But I already add the Opencv path to the environment variable。That 
 is"D:\software\tool\opencv\opencv\build\x64\vc14\bin"
------------------------------------------------------------------------------------
**Compile result:**
-- The C compiler identification is MSVC 19.16.27041.0
-- The CXX compiler identification is MSVC 19.16.27041.0
-- Check for working C compiler: E:/vs_2017/vs_2017_ide/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: E:/vs_2017/vs_2017_ide/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: E:/vs_2017/vs_2017_ide/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: E:/vs_2017/vs_2017_ide/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target arch: x86
CMake Warning at CMakeLists.txt:116 (message):
  The submodules were not downloaded! NCNN_VULKAN_ONLINE_SPIRV will be turned
  off.

CMake Warning at CMakeLists.txt:117 (message):
  Please update submodules with "git submodule update --init" and try again.

-- Found glslangValidator: D:/software/tool/vulkan/1.1.114.0/Bin/glslangValidator.exe
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Found Vulkan: D:/software/tool/vulkan/1.1.114.0/Lib/vulkan-1.lib
CMake Warning at examples/CMakeLists.txt:38 (message):
  OpenCV not found, examples won't be built

-- Found Protobuf: D:/doc/github_program/protobuf/build_for_ncnn_by_vs2017/install/lib/libprotobuf.lib (found version "3.12.3")
CMake Warning at tools/quantize/CMakeLists.txt:18 (message):
  **OpenCV not found, quantize tools won't be built**

-- Configuring done
-- Generating done
-- Build files have been written to: D:/doc/github_program/ncnn/build_vs2017

------------------------------------------
Thank you watching...

**Comment by NeekHua** [comment]
This problems already solved。I add opencv_DIR into cmake command lines,follow is:
              -DOpenCV_DIR=D:/software/tool/opencv/opencv/build(your OpenCVConfig.cmake absolute path).

**Comment by zchrissirhcz** [comment]
@nihui  I think we can close this issue now.
