### ISSUE TITLE
用ncnn模型多次对同一张图片进行推理，结果偶尔出现不一致的情况

### ISSUE THREAD

**Issue by bestpower** [Tencent/ncnn#1983]
用pytorch训练出的人脸关键点检测模型，转换为ncnn模型后在安卓端上运行测试，多次对同一张人脸图片进行检测，打印推理结果对比发现有出现不一致的情况：
第1次检测人脸关键点信息数组值 = [0.117999755, 0.22517256, 0.09942238, 0.34804493, 0.08942526, 0.48181129, 0.10939247, 0.61601275, 0.16271731, 0.7285957, 0.26296714, 0.818509, 0.36935863, 0.87894803, 0.47998276, 0.92154783, 0.5815099, 0.9293533, 0.6465327, 0.90447617, 0.69728935, 0.8437892, 0.73554885, 0.770279, 0.7659493, 0.69126546, 0.80433613, 0.5884153, 0.82981277, 0.49755388, 0.8441034, 0.38798636, 0.8344257, 0.28880262, 0.26439282, 0.13426057, 0.3421433, 0.0985638, 0.4360252, 0.09717338, 0.52846223, 0.122183226, 0.60542476, 0.17367195, 0.6945219, 0.1829272, 0.73492396, 0.15684402, 0.7886958, 0.13666105, 0.8386022, 0.12589714, 0.868028, 0.15089607, 0.6541388, 0.27914852, 0.66188633, 0.34744903, 0.67078626, 0.41295987, 0.6824129, 0.47647405, 0.56835926, 0.5567903, 0.6083303, 0.566799, 0.65115213, 0.57179147, 0.68551534, 0.5702394, 0.71525764, 0.5566882, 0.36294115, 0.25142437, 0.42280287, 0.23027739, 0.48084095, 0.2358223, 0.521521, 0.28046975, 0.47384533, 0.28519788, 0.4127126, 0.28081426, 0.7034983, 0.29557934, 0.7623116, 0.25332263, 0.8059626, 0.25771233, 0.82906866, 0.28419507, 0.803387, 0.3082958, 0.7565547, 0.30479935, 0.47064233, 0.6909762, 0.5519225, 0.6614914, 0.61600924, 0.6391657, 0.64102733, 0.6507528, 0.672895, 0.63724416, 0.7060585, 0.6617698, 0.7206952, 0.6911722, 0.69722825, 0.74605423, 0.6633634, 0.7787216, 0.6296108, 0.78366524, 0.5964352, 0.7838399, 0.53780043, 0.76219183, 0.5000162, 0.6928813, 0.6090965, 0.6950959, 0.63610494, 0.6988079, 0.66559935, 0.69448674, 0.696934, 0.6923255, 0.66422015, 0.6966472, 0.6320412, 0.70301855, 0.60379905, 0.7047295]
第2次检测人脸关键点信息数组值 = [0.11782473, 0.22689092, 0.099114746, 0.35008162, 0.090027995, 0.48363566, 0.11134366, 0.61707914, 0.16457835, 0.7291046, 0.26395965, 0.8192736, 0.37055355, 0.8801438, 0.48114392, 0.92186564, 0.5824762, 0.9291182, 0.6460729, 0.90340775, 0.69607174, 0.8428923, 0.73395973, 0.7698689, 0.7648886, 0.69065183, 0.80410606, 0.5881075, 0.830592, 0.49722138, 0.8455799, 0.3881027, 0.83651775, 0.28879428, 0.26484984, 0.13588054, 0.34252405, 0.09961654, 0.43681017, 0.09779239, 0.5299234, 0.12291773, 0.6065026, 0.1748237, 0.696599, 0.1820408, 0.73758334, 0.15625958, 0.79146266, 0.13653752, 0.8408661, 0.12660164, 0.86891085, 0.15154752, 0.65490544, 0.27919132, 0.6623917, 0.3476472, 0.6710248, 0.413567, 0.6824272, 0.47720736, 0.56944734, 0.5566713, 0.6088518, 0.56679153, 0.65126646, 0.57180583, 0.6850051, 0.5704024, 0.7141701, 0.55724245, 0.36184475, 0.25202596, 0.4212555, 0.231122, 0.47926742, 0.23634793, 0.52032185, 0.28068346, 0.47279263, 0.28558585, 0.41173115, 0.2814797, 0.70514214, 0.29563108, 0.76339394, 0.25366402, 0.8067806, 0.25800523, 0.82971525, 0.28471807, 0.8045876, 0.30859, 0.7580974, 0.30504492, 0.4713342, 0.6911859, 0.55303866, 0.6616421, 0.61784494, 0.63927495, 0.6415322, 0.650664, 0.67350256, 0.63718104, 0.70684725, 0.6626025, 0.72063893, 0.6922819, 0.6971792, 0.7462692, 0.6631438, 0.7790431, 0.62931144, 0.7839823, 0.5971136, 0.78442603, 0.53805906, 0.7629449, 0.50050676, 0.69303256, 0.6103718, 0.6959215, 0.63610923, 0.69938684, 0.6657491, 0.6951828, 0.69688326, 0.6932688, 0.66395605, 0.69702137, 0.6317185, 0.7032861, 0.60477173, 0.70554787]
后将原图片改为bmp格式仍会出现该问题，经排查预测前的输入数据是一致的，用原pytorch模型进行多次推理对比结果也是一致的，请问是什么原因造成的，该如何解决？

**Comment by bestpower** [comment]
经排查发现在执行了jni层的ncnn数据转换代码后数据出现了差异情况：
ncnn::Mat ncnn_img = ncnn::Mat::from_pixels_resize(faceImageCharData, ncnn::Mat::PIXEL_RGBA2RGB, w, h, 112, 112);
后将输入数据faceImageCharData做CRC校验，发现都是一致的，将转换后的数据ncnn_img做CRC校验发现了差异：
10次测试输出的CRC校验值LOG：
2020-07-30 18:00:47.376 5345-5380/com.demo.face D/face_jni: CRC Value = -511748066
2020-07-30 18:00:47.898 5345-5380/com.demo.face D/face_jni: CRC Value = -1405686989
2020-07-30 18:00:48.430 5345-5380/com.demo.face D/face_jni: CRC Value = 263265961
2020-07-30 18:00:48.937 5345-5380/com.demo.face D/face_jni: CRC Value = 91259077
2020-07-30 18:00:49.442 5345-5380/com.demo.face D/face_jni: CRC Value = 263265961
2020-07-30 18:00:49.950 5345-5380/com.demo.face D/face_jni: CRC Value = 1271348725
2020-07-30 18:00:50.434 5345-5380/com.demo.face D/face_jni: CRC Value = 1271348725
2020-07-30 18:00:50.913 5345-5380/com.demo.face D/face_jni: CRC Value = 263265961
2020-07-30 18:00:51.402 5345-5380/com.demo.face D/face_jni: CRC Value = 263265961
2020-07-30 18:00:51.884 5345-5380/com.demo.face D/face_jni: CRC Value = 1271348725

**Comment by bestpower** [comment]
目前凡是用android api对同一张图片解析出来的bitmap/byte[]数据输入到ncnn::Mat::from_pixels_resize中后输出的数据很容易出现差异，请问ncnn::Mat::from_pixels_resize接口对输入的const unsigned char* pixels数据有什么特殊的要求吗，或者是什么类型的数据能够保证输出的一致性？

**Comment by nihui** [comment]
如果使用 112x112 resize 好的 bmp 图片测试，还会有这个问题吗？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/issues/1993
可能和这个有关

**Comment by nihui** [comment]
issue 1993 已经修复，应该就是这个 bug 引起的

**Comment by bestpower** [comment]
好的，我先试试

**Comment by bestpower** [comment]
更新编译替换ncnn库后可以了

**Comment by nihui** [comment]
感谢报告和测试！

**Comment by bestpower** [comment]
我这边人脸关键点检测和人脸特征检测模型在安卓端:10000次相同输入的压力测试时，出现了**偶发性**的推理结果不一致的情况，经测试分析**经ncnn库预处理后的Mat输入是一致的**，**经过模型推理出现了差异**，麻烦帮忙分析一下：
关键点推理核心代码：
```cpp
        ......
        //输入Bitmap转换
        ncnn::Mat ncnn_img = ncnn::Mat::from_android_bitmap_resize(env, obj_bitmap, ncnn::Mat::PIXEL_BGR2RGB, 112, 112);
        //归一化
        const float mean_vals[3] = {0.485f*255.f, 0.456f*255.f, 0.406f*255.f};
        const float norm_vals[3] = {1/0.229f/255.f, 1/0.224f/255.f, 1/0.225f/255.f};
        ncnn_img.substract_mean_normalize(mean_vals, norm_vals);
        ////人脸关键点检测
        ncnn::Extractor ex = LandmarkDetnet.create_extractor();
        ex.input(face68Landmark_opt_param_id::BLOB_data, ncnn_img);                         // input node
        ncnn::Mat out;//输出136维float数组
        int status = ex.extract(face68Landmark_opt_param_id::BLOB_landmark, out);     // output node
        ......
```
特征推理关键代码：
```cpp
        ......
        //输入Bitmap转换
        ncnn::Mat ncnn_img = ncnn::Mat::from_android_bitmap(env, obj_bitmap, ncnn::Mat::PIXEL_BGR2RGB);
        //人脸对齐
        ncnn::Mat det1 = mRecognize->preprocess(ncnn_img, 5Landmarks);
        //人脸特征提取
        ncnn::Extractor ex = Recognet.create_extractor();
        ex.input(faceFeature_opt_param_id::BLOB_data, det1 );                      // input node
        ncnn::Mat out;//输出128维float数组
        int status = ex.extract(faceFeature_opt_param_id::BLOB_fc1, out);     // output node
        ......
```
当前所用ncnn库版本为：**android ios macos linux windows webassembly 预编译库 20210525 f6c4952**
模型文件详见附件：
[models.zip](https://github.com/Tencent/ncnn/files/6936251/models.zip)
