### ISSUE TITLE
clang5.0 didn't support __builtin_cpu_init

### ISSUE THREAD

**Issue by wqvbjhc** [Tencent/ncnn#1984]
System information (version)
- Version =>20200722
- Operating System / Platform => ubuntu14.04
- Compiler =>clang 5.0.2

I get the error:
cpu.cpp:240:5: error: use of undeclared identifier '__builtin_cpu_init'

**Comment by nihui** [comment]
__builtin_cpu_init was added to clang since version 6.0
macro condition is needed for old clang
