### ISSUE TITLE
src/layer/convolution.cpp

### ISSUE THREAD

**Issue by banayoyo** [Tencent/ncnn#1988]
line 194: int gap = w * dilation_h - kernel_w * dilation_w;

请问为什么是w * dilation_h， 不是w * dilation_w？

**Comment by nihui** [comment]
gap 是计算向下 dilation_h，向右 dilation_w 的偏移

**Comment by banayoyo** [comment]
> gap 是计算向下 dilation_h，向右 dilation_w 的偏移

多谢
