### ISSUE TITLE
同一网络提取多层结果的快速方法

### ISSUE THREAD

**Issue by philp123** [Tencent/ncnn#1989]
采用retinaface的原始模型能够快速提取到人脸框
![Screenshot_2020-07-31_17-38-42](https://user-images.githubusercontent.com/49138243/89022523-c3911400-d354-11ea-8185-e6d2e69ec4c8.png)

但是后面为了得到人脸的关键5点，在后面又加入landmark输出层，具体方法如下：

![Screenshot_2020-07-31_17-38-57](https://user-images.githubusercontent.com/49138243/89022533-c7249b00-d354-11ea-8cbb-cf97ff8ee9a0.png)

但是加了landmark输出层后，在android上跑比原来慢了很多，请问下这里是不是做了三次网络推理计算，有没有什么方法可以加速,例如
ex.extract(layer1,out1,layer2,out2) 直接一次跑出结果

**Comment by nihui** [comment]
多次 extract 不会做多次推理

多次 extract 的调用顺序从上到下，比如截图里，先 extract landmark，再 extract class
