### ISSUE TITLE
resize_bilinear_c4函数的疑惑

### ISSUE THREAD

**Issue by leezivin** [Tencent/ncnn#1993]
[https://github.com/Tencent/ncnn/blob/master/src/mat_pixel_resize.cpp#L1025](url) 这里不是应该是 sy == prev_sy1 + 1 么？为什么是 sy == prev_sy1 + 4 。我看c1、c2、c3函数都是 sy == prev_sy1 + 1。请高手指点下

**Comment by nihui** [comment]
确实有问题，已修复，感谢反馈！
