### ISSUE TITLE
Android版本benchmark崩溃

### ISSUE THREAD

**Issue by sosopop** [Tencent/ncnn#1996]
[seesaw_feature_op.zip](https://github.com/Tencent/ncnn/files/5020381/seesaw_feature_op.zip)
使用安卓的benchmark测试这个模型崩溃，发现cmake使用-DANDROID_ABI='armeabi-v7a with NEON'会出现这个崩溃问题，-DANDROID_ABI='armeabi-v7a'是正常的
模型输入112x112

**Comment by ncnnnnn** [comment]
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
find_blob_index_by_name data failed
find_blob_index_by_name output failed
   seesaw_feature_op  min =    0.36  max =    1.44  avg =    0.64
          squeezenet  min =   56.01  max =   56.12  avg =   56.07

没有崩溃，但是模型好像不对？

**Comment by sosopop** [comment]
@ncnnnnn 输入层input0 输出层feature

**Comment by ncnnnnn** [comment]
是的。arm64也崩了。

float32x4_t _w = vld1q_f32(kptr);

怀疑是conv3x3s2_pack1to4_neon的问题··

**Comment by nihui** [comment]
输入 input0 的 shape 是怎样的？

**Comment by sosopop** [comment]
3,112,112

**Comment by nihui** [comment]
```
Crop                     575                      1 1 563_splitncnn_1 575 -23309=1,0 -23310=1,16 -23311=1,0
Crop                     587                      1 1 563_splitncnn_0 587 -23309=1,16 -23310=1,-1 -23311=1,0
```

已验证确实会crash，原因出在这里的第二个 Crop，-23310=1,-1 是不能表达剩余channel，要改成 -23310=1,-233
全局查找替换下就行了

也可以尝试用新版的 onnx2ncnn 重新转换下模型试试

**Comment by sosopop** [comment]
可以了
