### ISSUE TITLE
arm64, cross compile, protobuf 3.9.2,  build error

### ISSUE THREAD

**Issue by fcyella** [Tencent/ncnn#1998]
CMake error, 

```
CMake Warning at /opt/fsl-imx-internal-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.15/Modules/FindProtobuf.cmake:501 (message):
  Protobuf compiler version doesn't match library version 3.9.2
Call Stack (most recent call first):
  tools/caffe/CMakeLists.txt:2 (find_package)
```

I checked the cmake function, find_package,  I don't have a Protobuf_SRC_ROOT_FOLDER, but a prebuild binary in toolchain. 
```
 find_program(Protobuf_PROTOC_EXECUTABLE
     NAMES protoc
     DOC "The Google Protocol Buffers Compiler"
     PATHS
     ${Protobuf_SRC_ROOT_FOLDER}/vsprojects/${_PROTOBUF_ARCH_DIR}Release
     ${Protobuf_SRC_ROOT_FOLDER}/vsprojects/${_PROTOBUF_ARCH_DIR}Debug
 )
```

**Comment by zchrissirhcz** [comment]
@fcyella Hi, I guess you're cross-compiling for arm64 from x64 linux. If so, what you expected to build should be the ncnn static library, and you don't need to compile protobuf for arm64.

The protobuf is required for build caffe=>ncnn convertion tool, aiming to load `.caffemodel` and `.prototxt` files, and these files are actually protobuf binary and protobuf plain text files. Then, you will only need to compile ncnn with protobuf when you are on your host machine and convering a caffe model to ncnn.

Correct me if I'm wrong understanding you. Let me know if you're in a different situation. Thnaks!

**Comment by fcyella** [comment]
Thanks for your quick response. 
Yes, I am cross-compiling for arm64 from x64 Linux. 
I tried to disable ncnn tool in cmake (find this solution in other similar issues), 
may I ask, if the convert tool is disabled,  what's the impact?  only ncnn model can be used, right?

**Comment by zchrissirhcz** [comment]
@fcyella When you are deploying your network with ncnn, I think you can only feed ncnn format model. If the original network model format is caffemodel/mxnet/darknet/onnx, you have to convert them to ncnn format.

To convert them to that format, you have to build a target x64 ncnn library & convert tools. Hence, you have to build both x64 and arm64 ncnn.

**Comment by fcyella** [comment]
Got it. Thanks~
