### ISSUE TITLE
"error: use of undeclared identifier '__builtin_cpu_init'" on MacOS

### ISSUE THREAD

**Issue by lightsalt2011** [Tencent/ncnn#2002]
MacOS:10.11.6 (15G31)
ncnn: master, 076b509bb9af626f2076262e8d94230f5bb05ab1, Wed Aug 5 17:46:47 2020 +0800, 
clang version:
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

build error:

`
[ 87%] Built target ncnn-generate-spirv
[ 87%] Building CXX object src/CMakeFiles/ncnn.dir/cpu.cpp.o
/Users/lvfeng/trunk/ncnn/src/cpu.cpp:240:5: error: use of undeclared identifier '__builtin_cpu_init'; did you mean
      '__builtin_isfinite'?
    __builtin_cpu_init();
    ^~~~~~~~~~~~~~~~~~
    __builtin_isfinite
/Users/lvfeng/trunk/ncnn/src/cpu.cpp:240:5: note: '__builtin_isfinite' declared here
/Users/lvfeng/trunk/ncnn/src/cpu.cpp:240:24: error: too few arguments to function call, expected 1, have 0
    __builtin_cpu_init();
                       ^
2 errors generated.
make[2]: *** [src/CMakeFiles/ncnn.dir/cpu.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
make: *** [all] Error 2
`

is there someone can help me?

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/2000

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/418047661ca09b2ab7eb4e47e6810e5e15ce0484
