### ISSUE TITLE
onnx2ncnn出现segmantation fault（core dumped）

### ISSUE THREAD

**Issue by suntaiwu** [Tencent/ncnn#2004]
分割网络onnx转换成功，且验证了正确性，但在转换成ncnn时报段错误，并无什么特殊的op，仅有Gemm，ReduceMax，ReduceSum，Unsqueeze等

**Comment by suntaiwu** [comment]
[onnx.zip](https://github.com/Tencent/ncnn/files/5033152/onnx.zip)

**Comment by nihui** [comment]
试了下，没发生 segmantation fault，更新到最新的 onnx2ncnn 代码试试看
只是你这个模型最后有个 softmax 需要手工合并下 https://zhuanlan.zhihu.com/p/93017149
