### ISSUE TITLE
speed in x86 cpu is slower than mxnet 

### ISSUE THREAD

**Issue by hahahouomg** [Tencent/ncnn#2006]
platform:  x86, Windows
cpu: i7-6850k
gpu: GTX1080

1. using mxnet to do the inference on cpu(no mkldnn i think)  ~1.17ms/frame
![image](https://user-images.githubusercontent.com/18361777/89507692-70f5a300-d7ff-11ea-8717-58964a4c49ab.png)

convert mxnet to ncnn model and run ncnn optimize
2. using ncnn to do the inference(avx2, thread=1)    ~55ms/frame
![image](https://user-images.githubusercontent.com/18361777/89509442-e793a000-d801-11ea-961a-5928ac330895.png)
![image](https://user-images.githubusercontent.com/18361777/89509415-de0a3800-d801-11ea-9fdf-9b871081572b.png)

3.using ncnn to do the inference(avx2, thread=4)    ~28ms/frame
4.using ncnn to do the inference(vulkan=on, thread=4) ~19ms/frame
5.using ncnn to do the inference(vulkan=on, thread=1) ~2ms/frame

I have two questions here.

1. why the speed on mxnet is faster than ncnn optimize(both using cpu). I am not sure if my evaluation method is correct. But it seems if i directly using mxnet c++ api would be faster?(ignore the framework overhead)
2. why the vulkan on multiple thread(4) is slower than singer thread. I am not very understand how vulkan works. So it might be a stupid question.

Many many thanks for the awesome ncnn work.

**Comment by dexception** [comment]
Don't forget to measure cpu.

**Comment by nihui** [comment]
As far as I know, the mxnet inference speed measurement code may be wrong, because mxnet inference is asynchronous.
