### ISSUE TITLE
vkCreateInstance failed -9

### ISSUE THREAD

**Issue by Amanda-Barbara** [Tencent/ncnn#2011]
你好，nihui，在GPU模式下我跑benchmark的代码时，报出了vkCreateInstance failed -9这个错误，在网上没有找到解决方案，想请教一下这是什么原因导致的？谢谢，

**Comment by nihui** [comment]
通常是驱动没有装好的问题，比如安装nvidia驱动时，没有安装opengl文件，推荐重装驱动

**Comment by Amanda-Barbara** [comment]
@nihui 谢谢指点，应该是我没有安装opengl的原因导致的，可能我安装的centos7.2系统太旧了不支持，

**Comment by ByronGe** [comment]
你好,nihui,我在容器化部署的时候,也发生了vkCreateInstance failed -9这个错误,请问这个该怎么解决啊

**Comment by 501ZHY** [comment]
Hi, 我也遇到了同样的问题，请问如何解决的？
