### ISSUE TITLE
vulkun无法编译

### ISSUE THREAD

**Issue by CheungBH** [Tencent/ncnn#2012]
-- CMAKE_INSTALL_PREFIX = /home/xxx/Documents/ncnn/build/install
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Target arch: x86
CMake Warning at CMakeLists.txt:116 (message):
  The submodules were not downloaded! NCNN_VULKAN_ONLINE_SPIRV will be turned
  off.

CMake Warning at CMakeLists.txt:117 (message):
  Please update submodules with "git submodule update --init" and try again.

-- Found glslangValidator: GLSLANGVALIDATOR_EXECUTABLE-NOTFOUND
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CMake Error at src/CMakeLists.txt:175 (find_package):
  By not providing "FindVulkan.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Vulkan", but
  CMake did not find one.

  Could not find a package configuration file provided by "Vulkan" with any
  of the following names:

    VulkanConfig.cmake
    vulkan-config.cmake

  Add the installation prefix of "Vulkan" to CMAKE_PREFIX_PATH or set
  "Vulkan_DIR" to a directory containing one of the above files.  If "Vulkan"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/xxx/Documents/ncnn/build/CMakeFiles/CMakeOutput.log".

我在编译的时候除了这个问题，想问问可以怎么解决？是cmake版本问题还是缺了什么的原因？我是按照教程直接wget的vulkun，cmake版本是3.5.1

**Comment by nihui** [comment]
升级下cmake

**Comment by CheungBH** [comment]
> 升级下cmake
具体要升级到哪个版本呢？我升级了3.17.4还是不行

**Comment by nihui** [comment]
还有设置vulkan sdk的环境变量
具体参考下wiki的how to build文档
