### ISSUE TITLE
RGB packed to planar conversion code crashing on armv7

### ISSUE THREAD

**Issue by teamaltumview** [Tencent/ncnn#2013]
Hi:
I recently discovered that the color format conversion code causes bus error on armv7 platforms. I suspect it's an address alignment issue. Please take a look.
Error occurred at "ncnn/src/mat_pixel.cpp:119"
My ncnn repository is on master branch and points to e2557c16785e98349e50bcc1f4c21a9d5055c612
Thanks

**Comment by nihui** [comment]
Hi, how does your code use the ncnn api ?

The ```from_rgb``` function assumes that the output memory address is always 128bit aligned, which is true for the ncnn::Mat storage.

Always

**Comment by teamaltumview** [comment]
It turns out that it's an alignment issue in our code. We were feeding partially cropped images into the network and did not align the addresses. Thanks for checking though. Cheers.
