### ISSUE TITLE
广播乘有些情况没有支持，binaryop.cpp增加了一种情况，vulkan的实现该怎么修改

### ISSUE THREAD

**Issue by wangwencancn** [Tencent/ncnn#2015]
if (w1 != w || h1 != h || channels1 != channels)
			{
				// general broadcast
				c.create(std::max(w,w1), std::max(h,h1), std::max(channels, channels1), elemsize, opt.blob_allocator);
				if (c.empty())
				{
					return -100;
				}

				int maxC = std::max(channels, channels1);
				if (channels != maxC && channels != 1)
				{
					printf("error channel\n");
					return -100;
				}
				if (channels1 != maxC && channels1 != 1)
				{
					printf("error channel1\n");
					return -100;
				}
				int maxW = std::max(w,w1);
				if (w != maxW && w != 1)
				{
					printf("error w\n");
					return -100;
				}
				if (w1 != maxW && w1 != 1)
				{
					printf("error w1\n");
					return -100;
				}
				int maxH = std::max(h, h1);
				if (h != maxH && h != 1)
				{
					return -100;
					printf("error h\n");
				}
				if (h1 != maxH && h1 != 1)
				{
					printf("error h1\n");
					return -100;
				}

                                #pragma omp parallel for num_threads(opt.num_threads)
				for (int q = 0; q < maxC; q++)
				{
					const float* ptr;
					if (q < channels)
						ptr = a.channel(q);
					else
						ptr = a.channel(0);

					const float* ptr1;
					if (q < channels1)
						ptr1 = b.channel(q);
					else
						ptr1 = b.channel(0);

					float* outptr = c.channel(q);

					for (int i = 0; i < maxH; i++)
					{
						const float* ptr_h = ptr + w * i;
						if (i >= h) ptr_h = ptr;
						const float* ptr1_h = ptr1 + w1 * i;
						if (i >= h1) ptr1_h = ptr1;
						for (int j = 0; j < maxW; j++)
							outptr[i*w + j] = op(ptr_h[j<w?j:0], ptr1_h[j<w1?j:0]);
					}
				}
				return 0;
			}

**Comment by nihui** [comment]
是两个怎样的 shape 乘？

**Comment by wangwencancn** [comment]
a(32 1 1) b(32 14 14)
a(256 32 32) b(256 1 1)

**Comment by wangwencancn** [comment]
a(256 32 32) b(1 32 32)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/binaryop-broadcasting
应该就是 special type 1234 的情况

**Comment by wangwencancn** [comment]
这三种情况跟special type 1234 不同，也许需要将两个输入的位置换一下，用预编译的库，a(32 1 1) b(32 14 14) 出来的结果市（32  1  1）
另外两张情况一种程序会异常退出，一种结果是错误的。

**Comment by nihui** [comment]
a(32 1 1) b(32 14 14) 这是 chw 还是 whc 的表示顺序？
如果是 chw 的表示顺序，就是 special type 3

**Comment by wangwencancn** [comment]
whc顺序

**Comment by nihui** [comment]
> 
> 
> whc顺序

whc很奇怪，你这是什么模型结构？

se block / cbam block 都是不会出现这样的 broadcasting type

**Comment by wangwencancn** [comment]
a(256 32 32) b(256 1 1) a(256 32 32) b(1 32 32)，这两个是cbam
a(32 1 1) b(32 14 14)  这个是se

**Comment by wangwencancn** [comment]
转换工具在转onnx模型的时候，自动在前面加了Transpose

**Comment by nihui** [comment]
你这是 tf 模型吗？tf 转过来的 onnx 是不支持的，因为 onnx 中间商会额外添加很多诸如 transpose 胶水op，只有 pytorch 转来的 onnx 可以用 onnx2ncnn 转换到 ncnn 模型

tf 模型可以看下 tools/tensorflow/ readme，或者用 mlir 导出后 mlir2ncnn 转换

**Comment by wangwencancn** [comment]
谢谢，我用新方法试试。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4809

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/9022b7162a851f5deae0d2e6e5ee5e89a4813212

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
