### ISSUE TITLE
about Net::use_vulkan_compute and Extractor:: set_vulkan_compute confused concepts

### ISSUE THREAD

**Issue by Dongshengjiang** [Tencent/ncnn#2016]
Net::use_vulkan_compute and Extractor:: set_vulkan_compute 是否可以混动，谁的优先级更高，这里好像没有明确的说法，在你们官方的domo中也大量在Extractor设置light mode和线程数。请给出官方解释这两个概念的优先级及用法。

**Comment by nihui** [comment]
net.opt.use_vulkan_compute 如果为 false，Extractor 则不能 true
net.opt.use_vulkan_compute 如果为 true，Extractor 可以 true 或者 false，此时 Extractor 覆盖 net 设置


example 里的 extractor 线程数设置去掉了 https://github.com/Tencent/ncnn/commit/785b49aa87e9fdc1fc07b4000530a039da91cae7
