### ISSUE TITLE
yolov4-tiny ncnn+vulkan

### ISSUE THREAD

**Issue by OceanWong1991** [Tencent/ncnn#2018]
Hi @nihui , when I test yolov4-tiny on ncnn+vulkan, There were some error: vkQueueSubmit failed -4 error, Do you know what's wrong? Thx anyway.

**Comment by nihui** [comment]
Hi, what is your hardware, operating system, platform, driver ?
Try upgrading the graphics driver

https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan#i-got-errors-like-vkcreatecomputepipelines-failed--1000012000-or-random-stalls-or-crashes

**Comment by OceanWong1991** [comment]
@nihui Thx for your reply, I will try.

- hardware : mt2712, Mali-T880

- operating system: android 9.0
