### ISSUE TITLE
ncnn vulkan 在linux编译成功生成libncnn.a，在应用程序中调用中出错...

### ISSUE THREAD

**Issue by YangTao-AI** [Tencent/ncnn#2019]
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(pipelinecache.cpp.o)：在函数‘ncnn::PipelineCache::clear()’中：
pipelinecache.cpp:(.text+0x320)：对‘vkDestroyPipeline’未定义的引用
pipelinecache.cpp:(.text+0x33b)：对‘vkDestroyPipelineLayout’未定义的引用
pipelinecache.cpp:(.text+0x356)：对‘vkDestroyDescriptorSetLayout’未定义的引用
pipelinecache.cpp:(.text+0x370)：对‘vkDestroyShaderModule’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(pipelinecache.cpp.o)：在函数‘ncnn::PipelineCache::new_pipeline(VkShaderModule_T*, ncnn::ShaderInfo const&, std::vector<ncnn::vk_specialization_type, std::allocator<ncnn::vk_specialization_type> > const&, VkDescriptorSetLayout_T**, VkPipelineLayout_T**, VkPipeline_T**, VkDescriptorUpdateTemplateKHR_T**) const’中：
pipelinecache.cpp:(.text+0x666)：对‘vkDestroyPipeline’未定义的引用
pipelinecache.cpp:(.text+0x681)：对‘vkDestroyPipelineLayout’未定义的引用
pipelinecache.cpp:(.text+0x6a1)：对‘vkDestroyDescriptorSetLayout’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(pipelinecache.cpp.o)：在函数‘ncnn::PipelineCache::get_pipeline(unsigned int const*, unsigned long, std::vector<ncnn::vk_specialization_type, std::allocator<ncnn::vk_specialization_type> > const&, unsigned int, unsigned int, unsigned int, VkShaderModule_T**, VkDescriptorSetLayout_T**, VkPipelineLayout_T**, VkPipeline_T**, VkDescriptorUpdateTemplateKHR_T**, ncnn::ShaderInfo&) const’中：
pipelinecache.cpp:(.text+0xdd8)：对‘vkDestroyShaderModule’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(pipelinecache.cpp.o)：在函数‘ncnn::PipelineCache::get_pipeline(int, ncnn::Option const&, std::vector<ncnn::vk_specialization_type, std::allocator<ncnn::vk_specialization_type> > const&, unsigned int, unsigned int, unsigned int, VkShaderModule_T**, VkDescriptorSetLayout_T**, VkPipelineLayout_T**, VkPipeline_T**, VkDescriptorUpdateTemplateKHR_T**, ncnn::ShaderInfo&) const’中：
pipelinecache.cpp:(.text+0x1314)：对‘vkDestroyShaderModule’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkWeightStagingAllocator::fastFree(ncnn::VkBufferMemory*)’中：
allocator.cpp:(.text+0xbc)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0xd1)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0xe7)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkWeightAllocator::clear()’中：
allocator.cpp:(.text+0x146)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x15c)：对‘vkFreeMemory’未定义的引用
allocator.cpp:(.text+0x196)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x1d6)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x1ec)：对‘vkFreeMemory’未定义的引用
allocator.cpp:(.text+0x226)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x276)：对‘vkFreeMemory’未定义的引用
allocator.cpp:(.text+0x2d6)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkStagingAllocator::clear()’中：
allocator.cpp:(.text+0x3b5)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x3cb)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x3e2)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::invalidate(ncnn::VkBufferMemory*)’中：
allocator.cpp:(.text+0x5bc)：对‘vkInvalidateMappedMemoryRanges’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::flush(ncnn::VkBufferMemory*)’中：
allocator.cpp:(.text+0x6bc)：对‘vkFlushMappedMemoryRanges’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkWeightAllocator::fastFree(ncnn::VkImageMemory*)’中：
allocator.cpp:(.text+0x73e)：对‘vkDestroyImageView’未定义的引用
allocator.cpp:(.text+0x753)：对‘vkDestroyImage’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkBlobAllocator::clear()’中：
allocator.cpp:(.text+0x7ae)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x7c5)：对‘vkFreeMemory’未定义的引用
allocator.cpp:(.text+0x804)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x88f)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkStagingAllocator::~VkStagingAllocator()’中：
allocator.cpp:(.text+0x106d)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x1082)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x1098)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkStagingAllocator::~VkStagingAllocator()’中：
allocator.cpp:(.text+0x136d)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x1383)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x139a)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkStagingAllocator::fastMalloc(unsigned long)’中：
allocator.cpp:(.text+0x1535)：对‘vkCreateBuffer’未定义的引用
allocator.cpp:(.text+0x1561)：对‘vkGetBufferMemoryRequirements’未定义的引用
allocator.cpp:(.text+0x15b0)：对‘vkAllocateMemory’未定义的引用
allocator.cpp:(.text+0x15d7)：对‘vkBindBufferMemory’未定义的引用
allocator.cpp:(.text+0x15fb)：对‘vkMapMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkWeightStagingAllocator::fastMalloc(unsigned long)’中：
allocator.cpp:(.text+0x1787)：对‘vkCreateBuffer’未定义的引用
allocator.cpp:(.text+0x17b2)：对‘vkGetBufferMemoryRequirements’未定义的引用
allocator.cpp:(.text+0x1800)：对‘vkAllocateMemory’未定义的引用
allocator.cpp:(.text+0x1826)：对‘vkBindBufferMemory’未定义的引用
allocator.cpp:(.text+0x184a)：对‘vkMapMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkBlobAllocator::fastFree(ncnn::VkImageMemory*)’中：
allocator.cpp:(.text+0x1bb8)：对‘vkDestroyImageView’未定义的引用
allocator.cpp:(.text+0x1bce)：对‘vkDestroyImage’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::create_buffer(unsigned long, unsigned int)’中：
allocator.cpp:(.text+0x2081)：对‘vkCreateBuffer’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::allocate_memory(unsigned long, unsigned int)’中：
allocator.cpp:(.text+0x2140)：对‘vkAllocateMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::allocate_dedicated_memory(unsigned long, unsigned int, VkImage_T*, VkBuffer_T*)’中：
allocator.cpp:(.text+0x221c)：对‘vkAllocateMemory’未定义的引用

../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(pipelinecache.cpp.o)：在函数‘ncnn::PipelineCache::clear()’中：
pipelinecache.cpp:(.text+0x320)：对‘vkDestroyPipeline’未定义的引用
pipelinecache.cpp:(.text+0x33b)：对‘vkDestroyPipelineLayout’未定义的引用
pipelinecache.cpp:(.text+0x356)：对‘vkDestroyDescriptorSetLayout’未定义的引用
pipelinecache.cpp:(.text+0x370)：对‘vkDestroyShaderModule’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(pipelinecache.cpp.o)：在函数‘ncnn::PipelineCache::new_pipeline(VkShaderModule_T*, ncnn::ShaderInfo const&, std::vector<ncnn::vk_specialization_type, std::allocator<ncnn::vk_specialization_type> > const&, VkDescriptorSetLayout_T**, VkPipelineLayout_T**, VkPipeline_T**, VkDescriptorUpdateTemplateKHR_T**) const’中：
pipelinecache.cpp:(.text+0x666)：对‘vkDestroyPipeline’未定义的引用
pipelinecache.cpp:(.text+0x681)：对‘vkDestroyPipelineLayout’未定义的引用
pipelinecache.cpp:(.text+0x6a1)：对‘vkDestroyDescriptorSetLayout’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(pipelinecache.cpp.o)：在函数‘ncnn::PipelineCache::get_pipeline(unsigned int const*, unsigned long, std::vector<ncnn::vk_specialization_type, std::allocator<ncnn::vk_specialization_type> > const&, unsigned int, unsigned int, unsigned int, VkShaderModule_T**, VkDescriptorSetLayout_T**, VkPipelineLayout_T**, VkPipeline_T**, VkDescriptorUpdateTemplateKHR_T**, ncnn::ShaderInfo&) const’中：
pipelinecache.cpp:(.text+0xdd8)：对‘vkDestroyShaderModule’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(pipelinecache.cpp.o)：在函数‘ncnn::PipelineCache::get_pipeline(int, ncnn::Option const&, std::vector<ncnn::vk_specialization_type, std::allocator<ncnn::vk_specialization_type> > const&, unsigned int, unsigned int, unsigned int, VkShaderModule_T**, VkDescriptorSetLayout_T**, VkPipelineLayout_T**, VkPipeline_T**, VkDescriptorUpdateTemplateKHR_T**, ncnn::ShaderInfo&) const’中：
pipelinecache.cpp:(.text+0x1314)：对‘vkDestroyShaderModule’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkWeightStagingAllocator::fastFree(ncnn::VkBufferMemory*)’中：
allocator.cpp:(.text+0xbc)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0xd1)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0xe7)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkWeightAllocator::clear()’中：
allocator.cpp:(.text+0x146)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x15c)：对‘vkFreeMemory’未定义的引用
allocator.cpp:(.text+0x196)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x1d6)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x1ec)：对‘vkFreeMemory’未定义的引用
allocator.cpp:(.text+0x226)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x276)：对‘vkFreeMemory’未定义的引用
allocator.cpp:(.text+0x2d6)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkStagingAllocator::clear()’中：
allocator.cpp:(.text+0x3b5)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x3cb)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x3e2)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::invalidate(ncnn::VkBufferMemory*)’中：
allocator.cpp:(.text+0x5bc)：对‘vkInvalidateMappedMemoryRanges’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::flush(ncnn::VkBufferMemory*)’中：
allocator.cpp:(.text+0x6bc)：对‘vkFlushMappedMemoryRanges’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkWeightAllocator::fastFree(ncnn::VkImageMemory*)’中：
allocator.cpp:(.text+0x73e)：对‘vkDestroyImageView’未定义的引用
allocator.cpp:(.text+0x753)：对‘vkDestroyImage’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkBlobAllocator::clear()’中：
allocator.cpp:(.text+0x7ae)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x7c5)：对‘vkFreeMemory’未定义的引用
allocator.cpp:(.text+0x804)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x88f)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkStagingAllocator::~VkStagingAllocator()’中：
allocator.cpp:(.text+0x106d)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x1082)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x1098)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkStagingAllocator::~VkStagingAllocator()’中：
allocator.cpp:(.text+0x136d)：对‘vkUnmapMemory’未定义的引用
allocator.cpp:(.text+0x1383)：对‘vkDestroyBuffer’未定义的引用
allocator.cpp:(.text+0x139a)：对‘vkFreeMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkStagingAllocator::fastMalloc(unsigned long)’中：
allocator.cpp:(.text+0x1535)：对‘vkCreateBuffer’未定义的引用
allocator.cpp:(.text+0x1561)：对‘vkGetBufferMemoryRequirements’未定义的引用
allocator.cpp:(.text+0x15b0)：对‘vkAllocateMemory’未定义的引用
allocator.cpp:(.text+0x15d7)：对‘vkBindBufferMemory’未定义的引用
allocator.cpp:(.text+0x15fb)：对‘vkMapMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkWeightStagingAllocator::fastMalloc(unsigned long)’中：
allocator.cpp:(.text+0x1787)：对‘vkCreateBuffer’未定义的引用
allocator.cpp:(.text+0x17b2)：对‘vkGetBufferMemoryRequirements’未定义的引用
allocator.cpp:(.text+0x1800)：对‘vkAllocateMemory’未定义的引用
allocator.cpp:(.text+0x1826)：对‘vkBindBufferMemory’未定义的引用
allocator.cpp:(.text+0x184a)：对‘vkMapMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkBlobAllocator::fastFree(ncnn::VkImageMemory*)’中：
allocator.cpp:(.text+0x1bb8)：对‘vkDestroyImageView’未定义的引用
allocator.cpp:(.text+0x1bce)：对‘vkDestroyImage’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::create_buffer(unsigned long, unsigned int)’中：
allocator.cpp:(.text+0x2081)：对‘vkCreateBuffer’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::allocate_memory(unsigned long, unsigned int)’中：
allocator.cpp:(.text+0x2140)：对‘vkAllocateMemory’未定义的引用
../ncnn_vulkan_linux/build_vulkan/install/lib/libncnn.a(allocator.cpp.o)：在函数‘ncnn::VkAllocator::allocate_dedicated_memory(unsigned long, unsigned int, VkImage_T*, VkBuffer_T*)’中：
allocator.cpp:(.text+0x221c)：对‘vkAllocateMemory’未定义的引用

**请问如何解决？？？**

**Comment by nihui** [comment]
需要链接 libvulkan

**Comment by ByronGe** [comment]
你好,可以详细点吗?我也遇到了同样的问题 @nihui @YangTao-AI 
不胜感激

**Comment by nihui** [comment]
The latest master branch supports compiling gpu functions without installing vulkan-sdk. You can give it a try.
If it doesn’t work, feel free to reopen the issue and post your findings.
