### ISSUE TITLE
处理rgb顺序图像错误？

### ISSUE THREAD

**Issue by yileld** [Tencent/ncnn#2022]
原始模型是rgb顺序训练的。
opencv读取的原始bgr顺序的图片输入，ncnn和pytorch、onnx模型输出一致。
但改为rgb的输入后，pytorch和onnx的输出一致，但ncnn的不对。尝试了ncnn::Mat::PIXEL_BGR2RGB和cv::cvtColor结果相同。
另外，Mat::from_pixels里面type参数用PIXEL_RGB和PIXEL_BGR没区别吧，还是看输入pixels的通道顺序。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
