### ISSUE TITLE
arm64 linux下 有时候跑正确有时候跑不出结果的bug

### ISSUE THREAD

**Issue by Syencil** [Tencent/ncnn#2023]
测试环境是nvidia xavier开发板 单走cpu 无vulkan <br>
模型是torch版retinaface转onnx转ncnn x86和android上均正常 代码转到arm64上之后 就无法复现相同的结果
输出feature前10个特征值都试nan 但是同一个二进制文件跑起来有时候能获得正确结果 但是大部分时候都不行
还有一个问题就是arm64上运行速度接近1000ms了 android p40上也才40ms

**Comment by Syencil** [comment]
不稳定复现

**Comment by nihui** [comment]
首先，确认下 ex.input 的输入 mat 数据是否一样，shape 是否和模型所需要的一样，大部分情况都是因为输入数据不一样导致的

**Comment by Syencil** [comment]
这个都能确定是一样的 目前怀疑可能是资源占用导致输出不正确 代码出现问题的概率非常小 因为同一套在x86 android上均正确 但是到了nvidia开发板上就不对
不知道ncnn有没有针对系统资源这一块做判断 或者说对某一块资源占用是必须的

**Comment by nihui** [comment]
arm64上运行速度接近1000ms，这不正常
检查下是否编译的 arm 架构，开启了 neon

**Comment by nihui** [comment]
建议更新ncnn新版本再试试，如还有问题，可以reopen issue继续讨论

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
