### ISSUE TITLE
onnx2ncnn, 当我转换onnx模型为ncnn模型时，各种操作不支持，我该怎么手动修改或者怎么操作？

### ISSUE THREAD

**Issue by xinsuinizhuan** [Tencent/ncnn#2026]
https://github.com/ouyanghuiyu/chineseocr_lite/issues/236#issuecomment-675219267
chineseocr_lite的onnx分支中model下的crnn_lstm模型，我使用onnx2ncnn转换时各种操作不支持：
我这边使用ncnn的onnx2ncnn直接转换日志如下：
Shape not supported yet!
Gather not supported yet!
axis=0

Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
ConstantOfShape not supported yet!
value 4

Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Shape not supported yet!
Gather not supported yet!
axis=0

Shape not supported yet!
Gather not supported yet!
axis=0

Shape not supported yet!
Gather not supported yet!
axis=0

Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unknown data type 0
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unknown data type 0
Shape not supported yet!
Gather not supported yet!
axis=0

Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
ConstantOfShape not supported yet!
value 4

Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Shape not supported yet!
Gather not supported yet!
axis=0

Shape not supported yet!
Gather not supported yet!
axis=0

Shape not supported yet!
Gather not supported yet!
axis=0

Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unknown data type 0
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unknown data type 0

不知道怎么手动修改模型，请大神指教！非常感谢！

**Comment by nihui** [comment]
先使用 onnx-simplifier 消除这些不支持的胶水op
具体参考 
https://zhuanlan.zhihu.com/p/113338890

**Comment by xinsuinizhuan** [comment]
> 
> 
> 先使用 onnx-simplifier 消除这些不支持的胶水op
> 具体参考
> https://zhuanlan.zhihu.com/p/113338890

大神，我的onnx-simplifier处理过程如下：
    第一步
    安装pip install onnx-simplifier
    第二步：
    (base37) C:\WINDOWS\system32>python -m onnxsim I:\OCR\chineseocr_lite-onnx\models\crnn_lstm.onnx I:\OCR\chineseocr_lite-onnx\models\crnn_lstm_ex.onnx
    Simplifying...
    Traceback (most recent call last):
    File "E:\ProgramData\Anaconda3\envs\base37\lib\runpy.py", line 193, in run_module_as_main
    "main", mod_spec)
    File "E:\ProgramData\Anaconda3\envs\base37\lib\runpy.py", line 85, in run_code
    exec(code, run_globals)
    File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim_main.py", line 52, in
    main()
    File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim_main.py", line 40, in main
    args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
    File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 331, in simplify
    model, const_nodes, input_shapes=input_shapes)
    File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 172, in forward_for_node_outputs
    res = forward(model, input_shapes=input_shapes)
    File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 157, in forward
    inputs = generate_rand_input(model, input_shapes=input_shapes)
    File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 108, in generate_rand_input
    'please determine the input size manually by --input-shape xxx'.format(key))
    RuntimeError: The shape of input "input" has dynamic size, please determine the input size manually by --input-shape xxx

报错，不知道是哪儿有问题？需要加什么参数吗？

**Comment by xinsuinizhuan** [comment]
> 
> 
> 先使用 onnx-simplifier 消除这些不支持的胶水op
> 具体参考
> https://zhuanlan.zhihu.com/p/113338890

另外，我反复拜读过您的转换过程，前面就是大概验证那些层不支持，但是后面手动手工微调的时候，就云里雾里，不知道用什么工具，怎么就手动修改了。

**Comment by nihui** [comment]
> > 先使用 onnx-simplifier 消除这些不支持的胶水op
> > 具体参考
> > https://zhuanlan.zhihu.com/p/113338890
> 
> 大神，我的onnx-simplifier处理过程如下：
> 第一步
> 安装pip install onnx-simplifier
> 第二步：
> (base37) C:\WINDOWS\system32>python -m onnxsim I:\OCR\chineseocr_lite-onnx\models\crnn_lstm.onnx I:\OCR\chineseocr_lite-onnx\models\crnn_lstm_ex.onnx
> Simplifying...
> Traceback (most recent call last):
> File "E:\ProgramData\Anaconda3\envs\base37\lib\runpy.py", line 193, in run_module_as_main
> "main", mod_spec)
> File "E:\ProgramData\Anaconda3\envs\base37\lib\runpy.py", line 85, in run_code
> exec(code, run_globals)
> File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim_main.py", line 52, in
> main()
> File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim_main.py", line 40, in main
> args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
> File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 331, in simplify
> model, const_nodes, input_shapes=input_shapes)
> File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 172, in forward_for_node_outputs
> res = forward(model, input_shapes=input_shapes)
> File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 157, in forward
> inputs = generate_rand_input(model, input_shapes=input_shapes)
> File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 108, in generate_rand_input
> 'please determine the input size manually by --input-shape xxx'.format(key))
> RuntimeError: The shape of input "input" has dynamic size, please determine the input size manually by --input-shape xxx
> 
> 报错，不知道是哪儿有问题？需要加什么参数吗？

这个错误在 onnx-simplifier 上面，我之前转换的时候还没遇到过，可能是最新版不太一样，可以加QQ群交流

**Comment by xinsuinizhuan** [comment]
您说的是哪个QQ群，我在那个群里面，但是是不是这个问题，还得您帮忙看一下？

**Comment by xinsuinizhuan** [comment]
> 
> 
> > > 先使用 onnx-simplifier 消除这些不支持的胶水op
> > > 具体参考
> > > https://zhuanlan.zhihu.com/p/113338890
> > 
> > 
> > 大神，我的onnx-simplifier处理过程如下：
> > 第一步
> > 安装pip install onnx-simplifier
> > 第二步：
> > (base37) C:\WINDOWS\system32>python -m onnxsim I:\OCR\chineseocr_lite-onnx\models\crnn_lstm.onnx I:\OCR\chineseocr_lite-onnx\models\crnn_lstm_ex.onnx
> > Simplifying...
> > Traceback (most recent call last):
> > File "E:\ProgramData\Anaconda3\envs\base37\lib\runpy.py", line 193, in run_module_as_main
> > "main", mod_spec)
> > File "E:\ProgramData\Anaconda3\envs\base37\lib\runpy.py", line 85, in run_code
> > exec(code, run_globals)
> > File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim_main.py", line 52, in
> > main()
> > File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim_main.py", line 40, in main
> > args.input_model, check_n=args.check_n, perform_optimization=not args.skip_optimization, skip_fuse_bn=not args.enable_fuse_bn, input_shapes=input_shapes, skipped_optimizers=args.skip_optimizer, skip_shape_inference=args.skip_shape_inference)
> > File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 331, in simplify
> > model, const_nodes, input_shapes=input_shapes)
> > File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 172, in forward_for_node_outputs
> > res = forward(model, input_shapes=input_shapes)
> > File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 157, in forward
> > inputs = generate_rand_input(model, input_shapes=input_shapes)
> > File "E:\ProgramData\Anaconda3\envs\base37\lib\site-packages\onnxsim\onnx_simplifier.py", line 108, in generate_rand_input
> > 'please determine the input size manually by --input-shape xxx'.format(key))
> > RuntimeError: The shape of input "input" has dynamic size, please determine the input size manually by --input-shape xxx
> > 报错，不知道是哪儿有问题？需要加什么参数吗？
> 
> 这个错误在 onnx-simplifier 上面，我之前转换的时候还没遇到过，可能是最新版不太一样，可以加QQ群交流

@nihui大神，我使用Netron查看网络机构:
![图片](https://user-images.githubusercontent.com/40679769/90608555-5f67be80-e235-11ea-9c8d-470135aa979e.png)
使用onnx_simplify时，--input-shape 参数应该怎么写，上面使用时，没写--input-shape参数

**Comment by hhhhhhogan** [comment]
请问这个问题解决了吗？我也遇到这个错误了

**Comment by xinsuinizhuan** [comment]
输入尺寸没写，才会这样，写了输入尺寸就可以转换了。

**Comment by hhhhhhogan** [comment]
好的，谢谢你的回复，不过是要在哪里写输入尺寸呢？是pth-&gt;onnx那一步还是onnx-&gt;ncnn那一步？
我使用的命令分别是：
torch.onnx.export(model,
                  x,
                  onnx_file_name,
                  export_params=True,
                  opset_version=11,
                  do_constant_folding=True,
                  input_names=input_names, output_names=output_names,
                  dynamic_axes=None)


&nbsp;.\onnx2ncnn.exe&nbsp; yolov4_1_3_416_416_static.onnx yolo4.param yolo4.bin


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/ncnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午2:59
收件人:&nbsp;"Tencent/ncnn"<ncnn@noreply.github.com&gt;;
抄送:&nbsp;"张志辉"<675587543@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/ncnn] onnx2ncnn, 当我转换onnx模型为ncnn模型时，各种操作不支持，我该怎么手动修改或者怎么操作？ (#2026)





 
输入尺寸没写，才会这样，写了输入尺寸就可以转换了。

**Comment by hhhhhhogan** [comment]
> 输入尺寸没写，才会这样，写了输入尺寸就可以转换了。

好的，谢谢你的回复，不过是要在哪里写输入尺寸呢？是pth-&gt;onnx那一步还是onnx-&gt;ncnn那一步？
我使用的命令分别是：
torch.onnx.export(model,
                  x,
                  onnx_file_name,
                  export_params=True,
                  opset_version=11,
                  do_constant_folding=True,
                  input_names=input_names, output_names=output_names,
                  dynamic_axes=None)


&nbsp;.\onnx2ncnn.exe&nbsp; yolov4_1_3_416_416_static.onnx yolo4.param yolo4.bin

**Comment by zahidzqj** [comment]
`python -m onnxsim ***.onnx  ***-smi.onnx --input-shape 1,3,56,56`

**Comment by Phoenix865** [comment]
需要先将到处的onnx模型执行onnx-sim优化，得到优化过的模型后再执行转ncnn格式模型。
参考：https://github.com/HuPengsheet/use-ncnn/blob/main/notes/ncnn03-onnx%E8%BD%ACncnn%E6%A8%A1%E5%9E%8B%E8%B7%91yolov5-6.0.md

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
