### ISSUE TITLE
转换模型时出现问题："caffe.LayerParameter" has no field named "permute_param".

### ISSUE THREAD

**Issue by JefferyGong** [Tencent/ncnn#203]
想转换ssd-mobilenet模型，在做这一步时出错：
caffe 自带了工具可以把老版本的 caffe 网络和模型转换为新版
upgrade_net_proto_text [老prototxt] [新prototxt

ERROR_CAFFE_CAFFE_PARSING_ERROR: Caffe could not parse MobileNetSSD_deploy.prototxt: 1177:3 : Message type "caffe.LayerParameter" has no field named "permute_param".

求教！

**Comment by nihui** [comment]
用这里的caffe https://github.com/weiliu89/caffe/tree/ssd
