### ISSUE TITLE
量化后的模型很奇怪

### ISSUE THREAD

**Issue by wangzhao88** [Tencent/ncnn#2034]
您好，在转换以下开源模型时，发现转换前(float)和转换后(int8)的模型大小时一样的，模型地址：
https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/tree/master/caffe/model/Slim-320

我是严格按照caffe2ncnn -> ncnnoptimize -> ncnn2table -> ncnn2int8的步骤来对模型进行量化。
（其中ncnn2table是利用了widerface数据集的JPEGImages文件夹，能保证有较多的图片来生成.table文件）

demo中运行量化后的模型，在convolutionx86.cpp里面打印中间结果，发现use_int8_inference = false，感觉就像是量化后的模型依旧还是一个float模型，而不是一个分组量化int8模型。

请问，这个问题有没有什么好的解决办法呢？祝好。

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新
