### ISSUE TITLE
如何在自己的CMakeLists.txt中关闭layer

### ISSUE THREAD

**Issue by Jobernowl** [Tencent/ncnn#2036]
我这边是在自己的Android项目中直接把ncnn作为一个module加进去的（git submodule add https://github.com/Tencent/ncnn.git），现在想要去掉一些layer但是不知道如何写cmakelists，以下是我现在的cmakelists

cmake_minimum_required(VERSION 3.4.1)

SET(CMAKE_BUILD_TYPE "Release")

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -fopenmp")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fomit-frame-pointer -fstrict-aliasing -ffast-math")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fomit-frame-pointer -fstrict-aliasing -ffast-math")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fvisibility=hidden")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden -fvisibility-inlines-hidden")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions")

include_directories(.)

file(GLOB _SRC *.h *.cpp)

option(NCNN_OPENMP "openmp support" ON)
option(NCNN_STDIO "load model from external file" ON)
option(NCNN_STRING "plain and verbose string" ON)
option(NCNN_INSTALL_SDK "install ncnn library and headers" OFF)
option(NCNN_OPENCV "minimal opencv structure emulation" OFF)
option(NCNN_SIMPLESTL "minimal cpp stl structure emulation" OFF)
option(NCNN_THREADS "build with threads" ON)
option(NCNN_BENCHMARK "print benchmark information for every layer" OFF)
option(NCNN_PIXEL "convert and resize from/to image pixel" ON)
option(NCNN_PIXEL_ROTATE "rotate image pixel orientation" OFF)
option(NCNN_CMAKE_VERBOSE "print verbose cmake messages" OFF)
option(NCNN_VULKAN "vulkan compute support" OFF)
option(NCNN_VULKAN_ONLINE_SPIRV "online SPIR-V module compilation" OFF)
option(NCNN_SYSTEM_GLSLANG "use system glslang library" OFF)
option(NCNN_REQUANT "auto merge int8 quant and dequant" OFF)
option(NCNN_RUNTIME_CPU "runtime dispatch cpu routines" ON)
option(NCNN_DISABLE_PIC "disable position-independent code" OFF)
option(NCNN_BUILD_TESTS "build tests" OFF)
option(NCNN_COVERAGE "build for coverage" OFF)
option(NCNN_BUILD_BENCHMARK "build benchmark" OFF)

option(WITH_LAYER_AbsVal "build with layer AbsVal" OFF)
option(WITH_LAYER_ArgMax "build with layer ArgMax" OFF)
option(WITH_LAYER_BNLL "build with layer BNLL" OFF)
option(WITH_LAYER_Deconvolution "build with layer Deconvolution" OFF)
option(WITH_LAYER_Dropout "build with layer Dropout" OFF)
option(WITH_LAYER_Eltwise "build with layer Eltwise" OFF)
option(WITH_LAYER_Embed "build with layer Embed" OFF)
option(WITH_LAYER_Log "build with layer Log" OFF)
option(WITH_LAYER_LRN "build with layer LRN" OFF)
option(WITH_LAYER_MVN "build with layer MVN" OFF)
option(WITH_LAYER_Power "build with layer Power" OFF)
option(WITH_LAYER_PReLU "build with layer PReLU" OFF)
option(WITH_LAYER_Proposal "build with layer Proposal" OFF)
option(WITH_LAYER_Reduction "build with layer Reduction" OFF)
option(WITH_LAYER_ROIPooling "build with layer ROIPooling" OFF)
option(WITH_LAYER_Slice "build with layer Slice" OFF)
option(WITH_LAYER_Softmax "build with layer Softmax" OFF)
option(WITH_LAYER_SPP "build with layer SPP" OFF)
option(WITH_LAYER_Tile "build with layer Tile" OFF)
option(WITH_LAYER_RNN "build with layer RNN" OFF)
option(WITH_LAYER_LSTM "build with layer LSTM" OFF)
option(WITH_LAYER_Squeeze "build with layer Squeeze" OFF)
option(WITH_LAYER_ExpandDims "build with layer ExpandDims" OFF)
option(WITH_LAYER_Normalize "build with layer Normalize" OFF)
option(WITH_LAYER_PriorBox "build with layer PriorBox" OFF)
option(WITH_LAYER_DetectionOutput "build with layer DetectionOutput" OFF)
option(WITH_LAYER_DeconvolutionDepthWise "build with layer DeconvolutionDepthWise" OFF)
option(WITH_LAYER_InstanceNorm "build with layer InstanceNorm" OFF)
option(WITH_LAYER_Clip "build with layer Clip" OFF)
option(WITH_LAYER_Reorg "build with layer Reorg" OFF)
option(WITH_LAYER_YoloDetectionOutput "build with layer YoloDetectionOutput" OFF)
option(WITH_LAYER_Quantize "build with layer Quantize" OFF)
option(WITH_LAYER_Dequantize "build with layer Dequantize" OFF)
option(WITH_LAYER_PSROIPooling "build with layer PSROIPooling" OFF)
option(WITH_LAYER_ROIAlign "build with layer ROIAlign" OFF)
option(WITH_LAYER_Requantize "build with layer Requantize" OFF)
option(WITH_LAYER_HardSigmoid "build with layer HardSigmoid" OFF)
option(WITH_LAYER_PixelShuffle "build with layer PixelShuffle" OFF)
option(WITH_LAYER_StatisticsPooling "build with layer StatisticsPooling" OFF)

add_library(ncnn-jni SHARED ${_SRC})

add_subdirectory(ncnn)

target_link_libraries(ncnn-jni
        PRIVATE ncnn
        android
        jnigraphics
        log -static-openmp -fopenmp)

目前可以编译就是禁用layer没有生效

**Comment by nihui** [comment]
可以参考这个
https://github.com/nihui/waifu2x-ncnn-vulkan/blob/master/src/CMakeLists.txt

**Comment by Jobernowl** [comment]
> 
> 
> 可以参考这个
> https://github.com/nihui/waifu2x-ncnn-vulkan/blob/master/src/CMakeLists.txt

我看了    看起来和我的没什么区别

**Comment by Jobernowl** [comment]
> 
> 
> 可以参考这个
> https://github.com/nihui/waifu2x-ncnn-vulkan/blob/master/src/CMakeLists.txt

解决了   原来是我的option那里layer的名称不是纯小写造成的
