### ISSUE TITLE
Linux平台测试squeezenet，ex.set_num_threads（）打开的线程越多，速度越慢

### ISSUE THREAD

**Issue by fcheng-cv** [Tencent/ncnn#204]
Using 1 threads, Running time is 464.366 ms
Using 2 threads, Running time is 477.079 ms
Using 4 threads, Running time is 505.482 ms
Using 8 threads, Running time is 932.674 ms

**Comment by KangolHsu** [comment]
me too 。

**Comment by ujsyehao** [comment]
linux平台测试不稳定

**Comment by wangxm345566462** [comment]
me too
