### ISSUE TITLE
从onnx转换成ncnn后模型结构缺失

### ISSUE THREAD

**Issue by sabo-gu** [Tencent/ncnn#2045]
![image](https://user-images.githubusercontent.com/39322760/91413631-fe1b9d00-e87d-11ea-84b1-1b92b96d9802.png)
![image](https://user-images.githubusercontent.com/39322760/91413650-0542ab00-e87e-11ea-89e9-b222fcceb1d1.png)
从pytorch-onnx 再转成ncnn后，模型的结构缺失了一半，转换过程也没有报错，有什么办法解决这样的问题吗？

**Comment by nihui** [comment]
请提供下你的onnx文件

**Comment by sabo-gu** [comment]
> 请提供下你的onnx文件


[model.zip](https://github.com/Tencent/ncnn/files/5139564/model.zip)
谢谢，这是我的onnx文件

**Comment by nihui** [comment]
测试了下，没有发现这个问题，LeakyRelu_74 这里的结构也是正常的
更新 onnx-simplifier onnx2ncnn 试试看

**Comment by nihui** [comment]
如有问题可以reopen继续交流 ww

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
