### ISSUE TITLE
ncnn针对单通道图像输入的模型无法推理出正确结果

### ISSUE THREAD

**Issue by bestpower** [Tencent/ncnn#2046]
最近打算给同事讲一个简单网络训练出来的手写数字识别的模型在安卓端的调用
训练时的网络输入尺寸是[1,1,28,28]
训练数据是通过代码下载使用的：
![image](https://user-images.githubusercontent.com/16058611/91442581-a5abc600-e8a4-11ea-8699-140d0be3a3c6.png)
训练出来的模型经pth->onnx->sim-onnx->ncnn(*.param, *.bin)转换拷贝至安卓工程里调用
![image](https://user-images.githubusercontent.com/16058611/91442809-fde2c800-e8a4-11ea-8d69-6d578999e944.png)
但推理出的结果一直不对，正常应该是0~1之间的float型数组[1,10]，但是结果出现了很多大于1的数甚至是负数，麻烦帮忙分析下是什么原因？

**Comment by bestpower** [comment]
经过这几天自行训练模型转换模型对问题进行排查，发现是之前算法的同事给我模型时把输出数组中的数值范围告诉错了，其实并不局限于0~1
后修改安卓端模型调用代码如下：
![image](https://user-images.githubusercontent.com/16058611/91809159-4dd3dd00-ec5f-11ea-8212-544bc4540abe.png)
最后按取数组中最大值的角标为预测数字分类即可准确预测出结果

**Comment by anliyuan** [comment]
大佬这个问题是怎么解决的呢？

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
