### ISSUE TITLE
int8.bin 文件加载异常

### ISSUE THREAD

**Issue by liulai** [Tencent/ncnn#2047]
## Bug Report

![image](https://user-images.githubusercontent.com/12567867/91454035-10fc9480-e8b3-11ea-9a9d-cb6f43995ad2.png)

![image](https://user-images.githubusercontent.com/12567867/91454297-5f119800-e8b3-11ea-94ab-6630a5beea24.png)

ModelBin read quantization_value failed 644
layer load_model 57 failed

### System information

- OS Platform and Distribution: Windows 10

- ONNX version: 1.7.0

- VS 2019

1. pytorch文件转换为onnx正常，并且可以正常运行
2. onnx量化为int8，运行时报错
3. 下面是转换过程

>```
>F:\DATASET\MPI-Sintel-complete\onnx>D:\GIT\ncnn-build-vs2019-vulkan\tools\ncnnoptimize.exe reconet-sim.param reconet-sim.bin reconet-nobn-fp32.param reconet-nobn-fp32.bin 0
>Input layer input.1 without shape info, shape_inference aborted
>unsupported resize type 0
>unsupported resize type 0
>
>F:\DATASET\MPI-Sintel-complete\onnx>D:\GIT\ncnn-build-vs2019-vulkan\tools\quantize\ncnn2table.exe --param=reconet-nobn-fp32.param --bin=reconet-nobn-fp32.bin --images=F:\DATASET\MPI-Sintel-complete\training\clean\alley_1\ --output=reconet-nobn.table --mean=104,117,123 --norm=0.017,0.017,0.017 --size=224,224 --thread=2
>--- ncnn post training quantization tool --- 23:52:36 Apr 17 2020
>====> Quantize the parameters.
>====> Quantize the activation.
>    ====> step 1 : find the max value.
>    ====> step 2 : generate the histogram_interval.
>Conv_19              : max = 2.567000        interval = 0.001253
>Conv_41              : max = 8.940391        interval = 0.004365
>Conv_63              : max = 8.755829        interval = 0.004275
>Conv_66              : max = 11.001097       interval = 0.005372
>Conv_69              : max = 8.449386        interval = 0.004126
>Conv_72              : max = 13.503145       interval = 0.006593
>Conv_75              : max = 7.753081        interval = 0.003786
>Conv_78              : max = 13.806967       interval = 0.006742
>Conv_81              : max = 8.941078        interval = 0.004366
>Conv_84              : max = 17.687321       interval = 0.008636
>Conv_87              : max = 10.061552       interval = 0.004913
>Conv_90              : max = 21.526318       interval = 0.010511
>Conv_93              : max = 12.405465       interval = 0.006057
>Conv_144             : max = 30.248173       interval = 0.014770
>Conv_195             : max = 15.053385       interval = 0.007350
>Conv_217             : max = 14.197227       interval = 0.006932
>    ====> step 3 : generate the histogram.
>    ====> step 4 : using kld to find the best threshold value.
>Conv_19              bin : 2032     threshold : 2.547572        interval : 0.001253   scale : 49.851391
>Conv_41              bin : 1596     threshold : 6.969401        interval : 0.004365   scale : 18.222511
>Conv_63              bin : 1695     threshold : 7.248783        interval : 0.004275   scale : 17.520182
>Conv_66              bin : 1520     threshold : 8.167562        interval : 0.005372   scale : 15.549314
>Conv_69              bin : 1500     threshold : 6.190578        interval : 0.004126   scale : 20.515049
>Conv_72              bin : 1602     threshold : 10.565816       interval : 0.006593   scale : 12.019896
>Conv_75              bin : 1661     threshold : 6.289914        interval : 0.003786   scale : 20.191055
>Conv_78              bin : 1825     threshold : 12.306942       interval : 0.006742   scale : 10.319379
>Conv_81              bin : 1782     threshold : 7.781969        interval : 0.004366   scale : 16.319778
>Conv_84              bin : 1836     threshold : 15.860724       interval : 0.008636   scale : 8.007200
>Conv_87              bin : 1886     threshold : 9.268124        interval : 0.004913   scale : 13.702882
>Conv_90              bin : 1693     threshold : 17.800205       interval : 0.010511   scale : 7.134749
>Conv_93              bin : 1847     threshold : 11.190966       interval : 0.006057   scale : 11.348440
>Conv_144             bin : 1531     threshold : 22.619667       interval : 0.014770   scale : 5.614583
>Conv_195             bin : 1459     threshold : 10.727742       interval : 0.007350   scale : 11.838465
>Conv_217             bin : 1900     threshold : 13.174722       interval : 0.006932   scale : 9.639672
>====> Save the calibration table done.
>
>NCNN Int8 Calibration table create success, best wish for your INT8 inference has a low accuracy loss...\(^0^)/...233...
>
>F:\DATASET\MPI-Sintel-complete\onnx>
>F:\DATASET\MPI-Sintel-complete\onnx>ls
>just_reshape-sim.onnx  reconet-nobn-fp32.param  reconet-sim.onnx   reconet-sim2.onnx  reshape-smi.onnx                  just_reshape.onnx      reconet-nobn.table       reconet-sim.param  reconet.onnx       reshape.onnx
>reconet-nobn-fp32.bin  reconet-sim.bin          reconet-sim1.onnx  reconet.zip
>
>F:\DATASET\MPI-Sintel-complete\onnx>
>F:\DATASET\MPI-Sintel-complete\onnx>D:\GIT\ncnn-build-vs2019-vulkan\tools\quantize\ncnn2int8.exe reconet-nobn-fp32.param reconet-nobn-fp32.bin reconet-int8.param reconet-int8.bin reconet-nobn.table
>quantize_convolution Conv_19
>quantize_convolution Conv_41
>quantize_convolution Conv_63
>quantize_convolution Conv_66
>quantize_convolution Conv_69
>quantize_convolution Conv_72
>quantize_convolution Conv_75
>quantize_convolution Conv_78
>quantize_convolution Conv_81
>quantize_convolution Conv_84
>quantize_convolution Conv_87
>quantize_convolution Conv_90
>quantize_convolution Conv_93
>quantize_convolution Conv_144
>quantize_convolution Conv_195
>quantize_convolution Conv_217
>unsupported resize type 0
>unsupported resize type 0
>
>F:\DATASET\MPI-Sintel-complete\onnx>
>```

param和bin文件[onnx.zip](https://github.com/Tencent/ncnn/files/5136928/onnx.zip)

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
