### ISSUE TITLE
请问如何生成squeezenet可执行文件

### ISSUE THREAD

**Issue by 1415168782** [Tencent/ncnn#205]
按照官网介绍，在ncnn目录下：
mkdir build
cd build
cmake ..
make -j
make install
过程没有报错，生成了静态库build/src/libncnn.a，但没有生成可执行文件squeezenet，

网上的教程都在这一步生成了可执行文件，然后通过./squeezenet test.jpg测试了图片，请问
各位大佬，这个可执行文件是怎么生成的呢？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build
