### ISSUE TITLE
2个基于ncnn的sdk集成到一个app中，初始化第二个程序会崩溃

### ISSUE THREAD

**Issue by sysylcf** [Tencent/ncnn#2060]
2个基于ncnn的sdk集成到一个app中，运行任意一个都是正常的，在运行第二个就会程序崩溃，这种一般是什么问题？要怎么解决？

**Comment by zchrissirhcz** [comment]
这两个sdk所基于的ncnn版本一样吗？应当保持一模一样。

**Comment by nihui** [comment]
参考置顶 issue 
https://github.com/Tencent/ncnn/issues/976

**Comment by nihui** [comment]
如有问题可以reopen继续交流 ww

**Comment by sysylcf** [comment]
@nihui 
参考了 android/ndk#1028 的建议，
修改 ld flags
老的ndk上尝试
-Wl,-Bstatic -lomp -Wl,-Bdynamic
新的ndk这样
-fstatic-openmp
-------------------

**Comment by sysylcf** [comment]
@nihui 
参考了 android/ndk#1028 的建议，修改 ld flags
老的ndk(ndk 19)上尝试
-Wl,-Bstatic -lomp -Wl,-Bdynamic
新的ndk(ndk 21)这样
-fstatic-openmp
-------------------------
我是是修改 ncnn/src/CMakeLists.txt 中的 target_link_libraries 参数，还是会再在第二个动态库加载模型参数时报错
请问是不是我修改的位置不对？可以给一些详细修改的指导吗？

**Comment by zchrissirhcz** [comment]
这个魔法，不是在编ncnn库的时候 施展的
是在 链接A 和 B的时候，施展的，其中A和B：可以是ncnn本身（的不同版本），可以是链接了ncnn（不同版本）的动态库。

**Comment by sysylcf** [comment]
@zchrissirhcz  ncnn 使用的是同一个版本，目前是 基于ncnn 封装了不同功能的动态库，现在有需求把多个动态库集成到同一个应用中，我在生成动态库中也是加了如上的配置（CMAKE_SHARED_LINKER_FLAGS ），但是并没有解决，麻烦帮忙指导下，多谢

**Comment by renmystery** [comment]
> 
A和B是链接了ncnn(同一版本)的动态库，在链接A和B的时候，具体如何施展这个魔法呢？

**Comment by renmystery** [comment]
> 这个魔法，不是在编ncnn库的时候 施展的 是在 链接A 和 B的时候，施展的，其中A和B：可以是ncnn本身（的不同版本），可以是链接了ncnn（不同版本）的动态库。

 A和B是链接了ncnn(同一版本)的动态库，请问在链接A和B的时候，具体如何施展这个魔法呢？
