### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by Single430** [Tencent/ncnn#2061]
我在 **再编译example验证是否安装成功**时，修改了**ncnn-root-dir** 下的 **CmakeLists.txt**中的：

```
option(NCNN_OPENCV "minimal opencv structure emulation" ON)
```

然后
```
$ mkdir -p build
$ cd build
$ cmake ..
$ make -j4
```
都成功了，继续
```
$ cd 
$ cp examples/squeezenet_v1.1.param  build/examples
$ cp examples/squeezenet_v1.1.bin  build/examples
$ cd build/examples
# yourimage.jpg 自己的图片的路径
$ ./squeezenet yourimage.jpg 
```
这里报错了：
```
cv::imread /home/xxx/cat-dog.jpeg failed
段错误 (核心已转储)
```

版本信息：
```
opencv4.1.1
cmake 3.18.2
```
补充：
```
我有单独测试过opencv，cv::imread  都是可以成功的，所以这里不知道如何解决，希望可以得到帮助！
```

@zchrissirhcz  @et.al

**Comment by zchrissirhcz** [comment]
@Single430 问题可以复现

**Comment by nihui** [comment]
不要开 NCNN_OPENCV
除非你知道你在干什么
NCNN_OPENCV 不能读 jpg 图片

**Comment by Single430** [comment]
> 不要开 NCNN_OPENCV
> 除非你知道你在干什么
> NCNN_OPENCV 不能读 jpg 图片

不能读jpg图片？那为何官方的文档例子是 **yourimage.jpg**  请看后缀，应该是其它原因吧

**Comment by Single430** [comment]
> 不要开 NCNN_OPENCV
> 除非你知道你在干什么
> NCNN_OPENCV 不能读 jpg 图片

感谢，跟着教程是要使用opencv的话，要开NCNN_OPENCV
我将图片换成 其它格式 依旧有此问题

**Comment by nihui** [comment]
> > 不要开 NCNN_OPENCV
> > 除非你知道你在干什么
> > NCNN_OPENCV 不能读 jpg 图片
> 
> 感谢，跟着教程是要使用opencv的话，要开NCNN_OPENCV
> 我将图片换成 其它格式 依旧有此问题

是哪里的教程说要开？NCNN_OPENCV 不要开呀！

**Comment by Single430** [comment]
> > > 不要开 NCNN_OPENCV
> > > 除非你知道你在干什么
> > > NCNN_OPENCV 不能读 jpg 图片
> > 
> > 
> > 感谢，跟着教程是要使用opencv的话，要开NCNN_OPENCV
> > 我将图片换成 其它格式 依旧有此问题
> 
> 是哪里的教程说要开？NCNN_OPENCV 不要开呀！

[可能我们还是有差异，不适用，Linux下编译安装NCNN](https://yyingbiu.github.io/2019/08/21/linux-xia-bian-yi-an-zhuang-ncnn/)
感谢，我关了是可以的
