### ISSUE TITLE
onnx转ncnn不支持的操作，.param文件内容缺失。

### ISSUE THREAD

**Issue by tangohu17** [Tencent/ncnn#2065]
### 转换出现的错误
**(onnx) ➜  onnx git:(master) ./onnx2ncnn classification-sim.onnx classification-sim.param classification-sim.bin  
Einsum not supported yet!
   equation=imjk,injk->imn
Sign not supported yet!
[1]    8785 segmentation fault  ./onnx2ncnn classification-sim.onnx classification-sim.param **

###  训练模型里面对应的代码
**feature_matrix = (torch.einsum('imjk,injk->imn', (attentions, features)) / float(H * W)).view(B, -1)** 

### 模型
链接: https://pan.baidu.com/s/18lhbDYfMn1JVHm-FTNy2vw 提取码: dikq

**Comment by qqsuhao** [comment]
这个问题现在解决了吗？

**Comment by ken-zoukun** [comment]
> 这个问题现在解决了吗？

我也想请问，这个问题解决了吗～

**Comment by nihui** [comment]
einsum 已经支持了，可以用 pnnx 转换模型
https://github.com/Tencent/ncnn/commit/f9c1787de964cf87fa69f0475b9fdc25ac45b006

**Comment by ken-zoukun** [comment]
谢谢，邮件已收到

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by kenzoukun** [comment]
谢谢，邮件已收到
