### ISSUE TITLE
在arm上跑，推理时间很慢，芯片型号全志的r311

### ISSUE THREAD

**Issue by youbinqiao** [Tencent/ncnn#2073]
芯片参数：四核ARM Cortex-A7@1.8GHz，系统ubuntu16.04
模型使用的是mobilenetssd

当我将ex.set_num_threads(8);注释后，ncnn推理一帧图片的时间最快，大概780ms
当我手动调节ex.set_num_threads(n)的参数n的时候，推理时间都会变慢，具体参数和对应的推理时间(ms)如下：
1-->4300
2-->2150
3-->1550
4-->1200
5-->1000
6-->900
7-->840
8-->780
当n值调节到8的时候，与注释ex.set_num_threads(n)后的时间一致，是不是可以理解成如果以后把芯片换成单核，跑一帧图片需要4秒？
请问下，这个推理时间正常吗，哪里可以进行优化的？@nihui

**Comment by youbinqiao** [comment]
由于先前ncnn是在x86上编译后，我直接copy到arm环境下的，刚我将ncnn在arm的环境下重新编译了一遍，速度得到了提升，最快速度420ms一帧，在设置ex.set_num_threads(n)为1的时候，速度为1520ms，请问现在的检测速度算正常吗

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/tree/master/benchmark
这里有 A7 1.0G x2 的数据，可以参考

另外，可以试试 net.opt.use_bf16_storage = true; 打开bf16s加速
