### ISSUE TITLE
ncnn 下，SqueezeNet，MobileNet，ShuffleNet， Efficientnet 的速度对比

### ISSUE THREAD

**Issue by weilanShi** [Tencent/ncnn#2075]
大神你好，非常感谢你的贡献，请问下在制作examples 时，你有没有对比过现在一些开源的分类网络的精度与速度呢？如：SqueezeNet，MobileNet，ShuffleNet， Efficientnet

**Comment by Hgit007** [comment]
大神，同问网络的速度，目前有没有试过生成网络，如用于上采样，图像修复的网络的速度，谢谢。

**Comment by nihui** [comment]
benchmark 里面有耗时评测，可以参考
精度参考各个paper里的数据

**Comment by weilanShi** [comment]
> benchmark 里面有耗时评测，可以参考
> 

> benchmark 里面有耗时评测，可以参考
> 精度参考各个paper里的数据

感谢提醒，之前没有注意到
