### ISSUE TITLE
ncnn在windows平台编译不过

### ISSUE THREAD

**Issue by chenrenxue** [Tencent/ncnn#2077]
参照https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-windows-x64-using-visual-studio-community-2017，但编译失败。 protobuf 编译可以成功

E:\hawk-skys\ncnn\build-vs2019> cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=e:/hawk-skys/ncnn/build-vs2019/install -DProtobuf_INCLUDE_DIR=../../protobuf-3.4.0/build-vs2019/install/include -DProtobuf_LIBRARIES=../../protobuf-3.4.0/build-vs2019/install/lib/libprotobuf.lib -DProtobuf_PROTOC_EXECUTABLE=../../protobuf-3.4.0/build-vs2019/install/bin/protoc.exe ..
-- CMAKE_INSTALL_PREFIX = e:/hawk-skys/ncnn/build-vs2019/install
-- The C compiler identification is MSVC 19.28.29115.0
-- The CXX compiler identification is MSVC 19.28.29115.0
-- Check for working C compiler: D:/visualstudio/VC/Tools/MSVC/14.28.29115/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: D:/visualstudio/VC/Tools/MSVC/14.28.29115/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/visualstudio/VC/Tools/MSVC/14.28.29115/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: D:/visualstudio/VC/Tools/MSVC/14.28.29115/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
CMake Error at src/CMakeLists.txt:413 (if):
  if given arguments:

    "DEFINED" "ANDROID_NDK_MAJOR" "AND" "GREATER" "20"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "E:/hawk-skys/ncnn/build-vs2019/CMakeFiles/CMakeOutput.log".

**Comment by nihui** [comment]
更新到最新的代码

**Comment by nihui** [comment]
如果最新代码还有问题，请reopen继续交流

**Comment by chenrenxue** [comment]
谢谢，更新后就编译通过了！
