### ISSUE TITLE
cmake编译问题

### ISSUE THREAD

**Issue by Lee-AI-sco** [Tencent/ncnn#2079]
@nihui 
 第一次下载ncnn,安装步骤,在make -j4时出了问题.我的环境:ubuntu16.04, gcc-5.4,cmake-3.5.1
![15bb32d554aa38494010d39f3b8b5db](https://user-images.githubusercontent.com/49769622/92394020-5e9abc00-f153-11ea-80d4-f69105cb0f65.jpg)

我百度了原因,说是protoc的版本问题,但我还是想向你请教一下.

**Comment by nihui** [comment]
```
sudo apt-get update
sudo apt-get install libprotobuf-dev protobuf-compiler libopencv-dev
mkdir build
cd build
cmake ..
make
```

**Comment by Lee-AI-sco** [comment]
ok,好了,还好请教了你,不然准备装高版本的protobuf.

**Comment by Lee-AI-sco** [comment]
谢谢

**Comment by Lee-AI-sco** [comment]
@nihui 
我还有些问题想要了解一下
第一:我看了一个博客,发现很多的模型都是基于caffe的,是不是意味着我要装一个caffe框架.
第二:我对tensorflow比较熟悉,因此生成的是pb或者.h5文件,请问有没有将tensorflow生成的模型通过ncnn移植到android的相关资料.
