### ISSUE TITLE
关于模型转换的问题

### ISSUE THREAD

**Issue by Lee-AI-sco** [Tencent/ncnn#2081]
@nihui
我还有些问题想要了解一下
第一:我看了一个博客,发现很多的模型都是基于caffe转换的,是不是意味着我要装一个caffe框架.
第二:我对tensorflow比较熟悉,因此生成的是pb或者.h5文件,请问有没有将tensorflow生成的模型通过ncnn移植到android的相关资料.

**Comment by nihui** [comment]
1 转换模型不需要安装caffe，同理也不需要安装 mxnet darknet 等等
2 tensorflow 导出 mlir 用 mlir2ncnn 转换

**Comment by nihui** [comment]
最新的pnnx大幅改善 pytorch 模型转换过程和体验，推荐使用 pytorch 做模型训练和转换
