### ISSUE TITLE
ncnnoptimize工具转换后模型运行结果异常

### ISSUE THREAD

**Issue by blueskywwc** [Tencent/ncnn#2085]
你好，使用原param和bin模型进行预测结果没问题，经ncnnoptimize工具优化后预测结果异常，结果如下:
-91290.531250
-94587.554688
-100938.859375
-108871.523438
-117351.796875
-124278.796875
-131140.437500
-138433.546875
-146092.687500
-153510.625000

请问这是什么原因，怎么解决?谢谢

**Comment by qaz734913414** [comment]
我也遇到类似的问题，可能需要用最新生成的param和bin模型，经ncnnoptimize工具优化的模型进行比较。

**Comment by nihui** [comment]
请提供下优化前的 param bin

**Comment by blueskywwc** [comment]
重新github下载ncnn并编译后，问题解决，可能我之前的ncnn哪里没更新，用最新的就ok，谢谢
