### ISSUE TITLE
转换pytorch下训练好yolo的模型，出现错误：Softplus not supported yet!

### ISSUE THREAD

**Issue by hhhhhhogan** [Tencent/ncnn#2087]
将pytorch训练好的pth模型转成onnx后，再使用ncnn中的转换工具onnx2ncnn.exe报错。
![image](https://user-images.githubusercontent.com/40531744/92562227-2fe22a00-f2a8-11ea-89c5-c814a977bc18.png)
![image](https://user-images.githubusercontent.com/40531744/92562249-3bcdec00-f2a8-11ea-8936-350ed4824523.png)
ppytorch版本为1.6， onnx版本为1.6 操作系统为win10，使用onnxsim简化onnx后还是出现一样的错误。请问是什么原因呢？以及如何解决？
参考github原仓库：https://github.com/Tianxiaomo/pytorch-YOLOv4

**Comment by nihui** [comment]
Softplus 在最新版 ncnn 已经支持啦

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
