### ISSUE TITLE
关于ncnn实例分割

### ISSUE THREAD

**Issue by onexuan** [Tencent/ncnn#2088]
pytorch2onnx
const float scal2[] = {255,255,255};
out.substract_mean_normalize(0,scal2);
out.to_android_bitmap(env, bitmap, ncnn::Mat::PIXEL_RGB);
上面实现实例分割后，得到黑底红色实例

怎么得到透明底，原图实例，有例子吗？

**Comment by nihui** [comment]
参考yolact的做法
https://github.com/Tencent/ncnn/blob/master/examples/yolact.cpp#L431

**Comment by onexuan** [comment]
cv 不是很了解，有没有不用CV的
