### ISSUE TITLE
pixelshuffle_invert转ncnn集成到移动端推理奔溃

### ISSUE THREAD

**Issue by Zachary-ZCH** [Tencent/ncnn#2089]
def pixelshuffle_invert(x: torch.Tensor, factor_hw: Tuple[int, int]):
    pH = factor_hw[0]
    pW = factor_hw[1]
    y = x
    B, iC, iH, iW = y.shape
    oC, oH, oW = iC*(pH*pW), iH//pH, iW//pW
    y = y.reshape(B, iC, oH, pH, oW, pW)
    y = y.permute(0, 1, 3, 5, 2, 4)     # B, iC, pH, pW, oH, oW
    y = y.reshape(B, oC, oH, oW)
    return y
附上onnx
[best_simplified.zip](https://github.com/Tencent/ncnn/files/5193551/best_simplified.zip)

**Comment by nihui** [comment]
onnx 里面的是```0, 1, 3, 5, 4, 2```，这里有问题

**Comment by nihui** [comment]
改为 ```0, 1, 3, 5, 2, 4```再导出onnx就可以了
如果还有问题，可以reopen

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
