### ISSUE TITLE
pytorch->onnx->ncnn过程中，conv1d 在input w=3，1D卷积k=3,s=1,p=0,d=1的时候，net.load_model报错

### ISSUE THREAD

**Issue by perrywu1989** [Tencent/ncnn#2093]
pytorch代码

input = torch.randn(1,1024,3) # 1,1024,3
model = nn.Conv1d(1024, 1024, 3, stride=1, bias=False)
ourput = model(input) # 1,1024,1

模型转可以转成 onnx，并且验证成功，并且使用onnxsim简化，可以进一步生成ncnn的param和bin，但是应用的时候net.load_model("./*.bin")报错

**Comment by niuxiaozhang** [comment]
我也遇到相同的问题 感觉ncnn不支持nn.Conv1d 请问你最后怎么解决的@perrywu1989

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
