### ISSUE TITLE
同一模型，不同数据效果相差较大。

### ISSUE THREAD

**Issue by lhxy1991** [Tencent/ncnn#2094]
平台：Android 手机和imx8设备
对于imx8设备输入数据直接为BGR的格式，可正常识别；
对于android手机，输入数据为YV12的格式，通过opencv转化为BGR的格式输入，效果很差。
这是怎么回事？

**Comment by yileld** [comment]
你都说不同数据了，仔细看看具体预处理实现方式有啥区别，我光PIL和opencv的resize方式的不同准确率都能降40个点
