### ISSUE TITLE
Unsupported slice step !

### ISSUE THREAD

**Issue by algpower** [Tencent/ncnn#2100]
ncnn-master/build/tools/onnx# **./onnx2ncnn 1-sim.onnx 1-sim.param 1-sim.bin**
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !
Unsupported slice step !

**Comment by zzzz737** [comment]
你解决这个问题了吗？

**Comment by Liangdacai** [comment]
你这一看就是yolov5将输入slice的操作，别问我为啥知道。。。。。

**Comment by nihui** [comment]
参考 https://zhuanlan.zhihu.com/p/275989233

**Comment by MHGL** [comment]
https://github.com/DeepVAC/deepvac/issues/118

**Comment by MHGL** [comment]
https://github.com/DeepVAC/deepvac/issues/118

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
