### ISSUE TITLE
caffe2ncnn：生成的.param文件没有data层的信息

### ISSUE THREAD

**Issue by Eric-Zhang1990** [Tencent/ncnn#2103]
@nihui   你好， 我在用ncnn编译生成的caffe2ncnn工具转caffe模型至ncnn模型时， **生成的.param文件没有这两行**：
Input                    data                     0 1 data 0=300 1=300 2=3
Split                    splitncnn_0              1 7 data data_splitncnn_0 data_splitncnn_1 data_splitncnn_2 data_splitncnn_3 data_splitncnn_4 data_splitncnn_5 data_splitncnn_6
      这样也导致.param文件的第2行s数据”148 181“的splitncnn_blob_count数为148， 因为没有Input，所以少1层。
      我手动修改了148-->149，文件能正常加载。
看了下caffe2ncnn.cpp源代码，还是不太清楚为啥？ 麻烦有空解答一下， 谢谢！

**Comment by nihui** [comment]
看这里
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-alexnet.zh#%E8%BD%AC%E6%8D%A2ncnn%E7%BD%91%E7%BB%9C%E5%92%8C%E6%A8%A1%E5%9E%8B

**Comment by Eric-Zhang1990** [comment]
@nihui  好的， 谢谢

**Comment by ScorpionYH** [comment]
> @nihui 你好， 我在用ncnn编译生成的caffe2ncnn工具转caffe模型至ncnn模型时， **生成的.param文件没有这两行**：
> Input data 0 1 data 0=300 1=300 2=3
> Split splitncnn_0 1 7 data data_splitncnn_0 data_splitncnn_1 data_splitncnn_2 data_splitncnn_3 data_splitncnn_4 data_splitncnn_5 data_splitncnn_6
> 这样也导致.param文件的第2行s数据”148 181“的splitncnn_blob_count数为148， 因为没有Input，所以少1层。
> 我手动修改了148-->149，文件能正常加载。
> 看了下caffe2ncnn.cpp源代码，还是不太清楚为啥？ 麻烦有空解答一下， 谢谢！

大佬能否帮忙转一下模型，有偿
