### ISSUE TITLE
按指引编译出来的静态库体积远大于预编译库

### ISSUE THREAD

**Issue by PYNing** [Tencent/ncnn#2106]
@nihui  你好，
出于添加layer的需要，我按指引（https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android）自行编译安卓静态库，发现体积远大于预编译库（如armv8的不带GPU加速的库，预编译6.9M，自行编译58.2M）。除添加新层的必要改动，无其他更改。

比较发现.a文件，每个.o体积都变得很大（大10倍左右，详见附图）。请问怎样才能做到跟预编译库那样的大小？（例如，是不是少了某些优化选项？）

烦请指点，谢谢！如需补充文件分析请告知。

**编译环境**
ncnn代码版本：6f26f57d9ca5af4c25182452fd779fd497bf586a （8月22日）
系统：WSL1 Ubuntu 18.04
其余配置同指引

**附图**

![微信图片_20200912120216](https://user-images.githubusercontent.com/11667149/92986795-03205380-f4f0-11ea-8c4c-e6841c515012.png)

![微信图片_20200912120246](https://user-images.githubusercontent.com/11667149/92986807-10d5d900-f4f0-11ea-9998-50dc1a933031.png)

**自行编译的so库（打包压缩后10M左右）**
[libncnn.zip](https://github.com/Tencent/ncnn/files/5212177/libncnn.zip)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android

参考这段
(optional) drop debug compile flag to reduce binary size due to android-ndk issue

**Comment by PYNing** [comment]
> https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android
> 
> 参考这段
> (optional) drop debug compile flag to reduce binary size due to android-ndk issue

谢谢大佬的回复！已解决，上述库的体积降低至预编译库的大小。
抱歉是我漏看了。
