### ISSUE TITLE
yuv sp nv12 如何转到 rgb

### ISSUE THREAD

**Issue by Brightchu** [Tencent/ncnn#2111]
yuv420sp2rgb 只支持 nv21 到 rgb的 转换，在支持neon的移动端速度确实快的一笔。
求教，如何支持 nv12 到rgb的转换呢，或者 yuv420sp2rgb 中汇编的那一段如何调整来支持nv12，有大佬指导一下吗？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/da7989bda32a6b9cc2c35652b295712dc8f010ca

添加了 yuv420sp2rgb_nv12
