### ISSUE TITLE
请问可以实现（真）量化吗？

### ISSUE THREAD

**Issue by yileld** [Tencent/ncnn#2112]
由于bias的存在所以是伪量化，但如果不保存bias（同TensorRT的ppt所说那样）或bias也量化的话就可以实现（真）量化了吧。
那么转化成int8模型时有提供类似的选项吗？

**Comment by nihui** [comment]
有个 NCNN_REQUANTIZE 开关，会把 bias fuse 进 requantize

**Comment by yileld** [comment]
赞！是在哪里设置呀

**Comment by nihui** [comment]
最新版本默认使用端到端int8量化
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新
