### ISSUE TITLE
darknet2ncnn darknet模型(yolov4-tiny)能正常detect ，ncnn模型无法detect

### ISSUE THREAD

**Issue by eheroqiu** [Tencent/ncnn#2114]
darknet2ncnn 过程中无异常
ncnnoptimize 过程中无异常
请问该如何debug问题

**Comment by zchrissirhcz** [comment]
对于能够运行而结果不对的问题，你可以尝试考虑比对两个程序（一个能得到正确结果 一个结果不对的）

https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result

可以按照这里提到的常见易错点来排查

**Comment by eheroqiu** [comment]
> 对于能够运行而结果不对的问题，你可以尝试考虑比对两个程序（一个能得到正确结果 一个结果不对的）
> 
> https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result
> 
> 可以按照这里提到的常见易错点来排查

谢谢，已经定位好了
