### ISSUE TITLE
Normalize pytorch in Ncnn

### ISSUE THREAD

**Issue by Zrufy** [Tencent/ncnn#2119]
i convert pytorch model to ncnn but i have difference in result.
i think the problem is the values in mean and norm.
how take this value `transforms.Normalize([0.5], [0.5])` to ncnn?
@nihui

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#pre-process

**Comment by Zrufy** [comment]
@nihui i'm using the crnn from` https://github.com/ouyanghuiyu/chineseocr_lite` with your help i have converted to ncnn with lstm but now with the right mean and norm     
```
const float mean_vals_crnn[1] = { 127.5 };
    const float norm_vals_crnn[1] = { 1.0 / 127.5 };
```
i have different result.Any help?
Thanks in advance.
