### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hyaihjq** [Tencent/ncnn#2120]
[deeplabv3plus_mbv2-sim-opt.zip](https://github.com/Tencent/ncnn/files/5224833/deeplabv3plus_mbv2-sim-opt.zip)

**Comment by nihui** [comment]
If the input size is dynamic, you need to change Interp parameters to scale factor instead of hardcoded output shape

**Comment by hyaihjq** [comment]
> If the input size is dynamic, you need to change Interp parameters to scale factor instead of hardcoded output shape

i got, thanks nihui!!!
