### ISSUE TITLE
darknet转换为ncnn前后网络结构完全发生了变化

### ISSUE THREAD

**Issue by eheroqiu** [Tencent/ncnn#2124]
darknet
<img width="357" alt="image" src="https://user-images.githubusercontent.com/23409926/93299664-fec5a480-f827-11ea-9024-22b116750d16.png">
ncnn
<img width="345" alt="image" src="https://user-images.githubusercontent.com/23409926/93299781-346a8d80-f828-11ea-88bd-73ea6feb9083.png">
大佬帮忙看下是什么原因或者配置导致的？
param文件如下
[yolov4-tiny.zip](https://github.com/Tencent/ncnn/files/5230064/yolov4-tiny.zip)

**Comment by nihui** [comment]
这两张图结构其实是一样的，没有问题
netron显示的时候把darknet conv bn relu画在一个框里面了
