### ISSUE TITLE
binaryop转换，常量指数参数转换丢失

### ISSUE THREAD

**Issue by BlueWinters** [Tencent/ncnn#2127]
问题描述：torch.pow(x,2)在转换到ncnn模型的时候，常参数2转换丢失（param和bin文件均未保存常数2）

具体：
**torch代码**
```
import torch
import torch.nn as nn
class Pow(nn.Module):
    def forward(self, x):
        return torch.pow(x, 2)
```

转换结果
**pow.bin的大小为0字节**
**pow.param**
```
7767517
2 2
Input            x                        0 1 x
BinaryOp         y                        1 1 x y 0=6
```

**Comment by BlueWinters** [comment]
onnx文件
[pow-sim.zip](https://github.com/Tencent/ncnn/files/5236111/pow-sim.zip)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/2384fad8e07a21b731c34c08a67722606b289cf0
修好了

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
