### ISSUE TITLE
  nihui~~ 我在编译ncnn的时候遇到一个问题， 能帮我解决吗？

### ISSUE THREAD

**Issue by sxj731533730** [Tencent/ncnn#2129]
[ 60%] Built target ncnnoptimize
tools/caffe/CMakeFiles/caffe2ncnn.dir/build.make:80: *** target pattern contains no `%'.  Stop.
make[1]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/all] Error 2
make: *** [all] Error 2

**Comment by zchrissirhcz** [comment]
啊，是discord里提到的那个问题。我这里ubuntu16.04+opencv4.4+cmake3.18没有能复现。题主后来换了opencv2.4.9(apt的）可以编译通过。

**Comment by sxj731533730** [comment]
嗯，我已经解决了，哈哈。 sxj731533730 邮箱：sxj731533730@sina.com 签名由 网易邮箱大师 定制 在2020年09月18日 20:10，Zhuo Zhang 写道： 啊，是discord里提到的那个问题。我这里ubuntu16.04+opencv4.4+cmake3.18没有能复现。题主后来换了opencv2.4.9(apt的）可以编译通过。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
