### ISSUE TITLE
ncnn not support 1x3 and 1x5 convolution, any plan for this?

### ISSUE THREAD

**Issue by vsooda** [Tencent/ncnn#213]
I try to convert my TextBoxes trained with mxnet. I changed a lot for mxnet ssd model convert. but finally, I found ncnn not support 1x3, 1x5convolution!!

I want to know if @nihui have any plan for this? I would like to try to implement, but I am not familiar with arm.

**Comment by nihui** [comment]
so，you only need 1x3 and 1x5，but not 3x1 and 5x1 ？

**Comment by vsooda** [comment]
thank you. only need 1x3 and 1x5. 
height: 1
width: 3, 5

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/issues/1048
