### ISSUE TITLE
编译通过，使用不了GPU

### ISSUE THREAD

**Issue by mojiayuan** [Tencent/ncnn#2130]
![image](https://user-images.githubusercontent.com/54795004/93457160-44aa6780-f911-11ea-934b-c73eac364951.png)
这是哪里出问题的？

**Comment by nihui** [comment]
需要链接 libvulkan

**Comment by mojiayuan** [comment]
> 需要链接 libvulkan
没有找到 libvulkan，我重新又编译了一遍还是一样，是缺少下面箭头的某些模块吗
![image](https://user-images.githubusercontent.com/54795004/93542651-2fbeea00-f98c-11ea-9481-845911754c72.png)

**Comment by zchrissirhcz** [comment]
@mojiayuan 如你的截图中箭头所指出的，你需要下载glslang的代码。

如果你是用git clone方式下载的源码，则:
```
# 切换到ncnn的根目录，然后
git submodule update --init
```

如果你是手动下载的ncnn-master.zip，则打开 https://github.com/Tencent/ncnn 网页，点击 glslang 的链接，目前（2020-09-18 19:40:38）这个链接是 https://github.com/KhronosGroup/glslang/tree/d39b8afc47a1f700b5670463c0d1068878acee6f ，然后下载新链接中的代码压缩包，解压后的内容放到 ncnn/glslang 目录下。

**Comment by mojiayuan** [comment]
> @mojiayuan如你的截图中箭头所指出的，你需要下载glslang的代码。
> 
> 如果你是用git clone方式下载的源码，则：
> 
> ```
> # 切换到ncnn的根目录，然后
> git submodule update --init
> ```
> 
> 如果您是手动下载的ncnn-master.zip，则打开https://github.com/Tencent/ncnn网页，点击glslang的链接，目前（2020-09-18 19:40:38）这个链接是[https： //github.com/KhronosGroup/glslang/tree/d39b8afc47a1f700b5670463c0d1068878acee6f](https://github.com/KhronosGroup/glslang/tree/d39b8afc47a1f700b5670463c0d1068878acee6f)，然后下载新链接中的代码压缩包，解压后的内容放到ncnn / glslang目录下。

解决了，谢谢。

**Comment by zchrissirhcz** [comment]
@mojiayuan 请关闭此issue，蟹蟹~
