### ISSUE TITLE
单目标检测异常

### ISSUE THREAD

**Issue by eheroqiu** [Tencent/ncnn#2131]
请问什么行为会导致检测坐标出现  inf 这种错误啊？
（原始DARKNET模型没问题）
DETECT输出结果为：

1 = 1.00000 at 166.15 -inf 166.15 x inf
1 = 1.00000 at 83.08 -inf 83.08 x inf
1 = 1.00000 at 166.15 -inf 166.15 x inf
1 = 1.00000 at 498.46 -inf 498.46 x inf
1 = 1.00000 at 0.00 367.62 0.00 x 367.62
1 = 1.00000 at 664.62 245.08 664.62 x 245.08
1 = 1.00000 at 581.54 245.08 581.54 x 245.08
1 = 1.00000 at 913.85 -inf 913.85 x inf
1 = 1.00000 at 747.69 -inf 747.69 x inf
1 = 1.00000 at 498.46 -inf 498.46 x inf

// 归一化设置
const int target_size = 416;
const float mean_vals[3] = {0.0f, 0.0f, 0.0f};
const float norm_vals[3] = {1/255.f, 1/255.f, 1/255.f};

in.substract_mean_normalize(mean_vals, norm_vals);

**Comment by eheroqiu** [comment]
模型改用yolov3, yolov4 非tiny版本, ncnn是ok的

**Comment by zchrissirhcz** [comment]
@eheroqiu 出现inf的时候是你自己的模型吗？如果是自己的模型，可以考虑和原始模型（例如tf、pytorch）的推理结果逐一比对。

**Comment by eheroqiu** [comment]
> @eheroqiu 出现inf的时候是你自己的模型吗？如果是自己的模型，可以考虑和原始模型（例如tf、pytorch）的推理结果逐一比对。

问题已经定位了，谢谢。是模型精度的问题
