### ISSUE TITLE
宏“__ARM_FEATURE_FP16_VECTOR_ARITHMETIC”的定义位置

### ISSUE THREAD

**Issue by PYNing** [Tencent/ncnn#2133]
nihui你好，
我的算法目前跑在fp32下，暂时不需要fp16算子。
由于SDK需要尽可能控制体积，我希望不将fp16算子编译到静态库中。
但是我找不到宏“__ARM_FEATURE_FP16_VECTOR_ARITHMETIC”的定义位置，请问它在哪里 定义（或者在哪里修改它的值）？
谢谢！

**Comment by zchrissirhcz** [comment]
@PYNing 这是NDK里定义的，不是NCNN里定义的。怎么关闭，我也不知道，摸索一下

**Comment by zchrissirhcz** [comment]
@PYNing 这个宏定义是NDK的clang编译器内置的宏定义

要验证，可以这样做：
```
/home/zz/soft/android-ndk-r18b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target aarch64-linux-android -march=armv8.2a+fp16 -dM -E - </dev/null  | grep '__ARM_FEATURE_FP16_VECTOR_ARITHMETIC'
```

得到查找结果：
```
#define __ARM_FEATURE_FP16_VECTOR_ARITHMETIC 1
```

参考： https://github.com/android/ndk/issues/660

**Comment by nihui** [comment]
cmake选项 -DNCNN_ARM82=OFF

**Comment by PYNing** [comment]
谢谢两位大佬！
