### ISSUE TITLE
关于OpenMP的问题，编译报错

### ISSUE THREAD

**Issue by zzzz737** [Tencent/ncnn#2137]
CMake Error at /home/CLion-2020.2/clion-2020.2/bin/cmake/linux/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:261 (message):
  No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()
Call Stack (most recent call first):
  /home/CLion-2020.2/clion-2020.2/bin/cmake/linux/share/cmake-3.17/Modules/FindOpenMP.cmake:579 (find_package_handle_standard_args)
  CMakeLists.txt:7 (FIND_PACKAGE)
这是报错的问题！
下面是我的cmakelist：
cmake_minimum_required(VERSION 3.17)
find_package(OpenCV REQUIRED core highgui imgproc)
add_compile_options(-fopenmp)
include_directories(/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/include/ncnn)
link_directories(/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib)

FIND_PACKAGE( OpenMP REQUIRED)
if (OPENMP_FOUND)
    message("OPENMAP FOUND")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()

project(yolov5s)

set(CMAKE_CXX_STANDARD 14)

add_executable(yolov5s yolov5.cpp)

target_link_libraries(yolov5s ncnn ${OpenCV_LIBS})

求大佬解答一下啊！！！！

**Comment by zchrissirhcz** [comment]
Hi，如果你的ncnn代码是最新的，建议使用`find_package(ncnn)`

可以参考这里 https://github.com/zchrissirhcz/cmake_examples/tree/master/ncnn_example

**Comment by zchrissirhcz** [comment]
关于使用openmp，可以参考这里 https://github.com/zchrissirhcz/cmake_examples/blob/master/openmp_example/CMakeLists.txt

**Comment by zchrissirhcz** [comment]
有个疑问是，你的代码中需要使用openmp加速吗？加速得到的提升有多少？没记错的话，ncnn本身已经有openmp加速了。

**Comment by zzzz737** [comment]
> 有个疑问是，你的代码中需要使用openmp加速吗？加速得到的提升有多少？没记错的话，ncnn本身已经有openmp加速了。

你好，感谢能帮我解答疑惑！就是如果使用find_package(ncnn)，是否需要把find_package(openmp)那些全注释掉，我这样试了，cmake能编译通过，但是代码跑不过，有如下错误：
/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib/libncnn.a(swish_x86_avx2.cpp.o)：在函数‘ncnn::Swish_x86_avx2::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
swish_x86_avx2.cpp:(.text+0x43)：对‘GOMP_parallel’未定义的引用
swish_x86_avx2.cpp:(.text+0x68)：对‘GOMP_parallel’未定义的引用
/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib/libncnn.a(swish_x86_avx2.cpp.o)：在函数‘ncnn::Swish_x86_avx2::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.1]’中：
swish_x86_avx2.cpp:(.text+0xa4)：对‘omp_get_num_threads’未定义的引用
swish_x86_avx2.cpp:(.text+0xab)：对‘omp_get_thread_num’未定义的引用
/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib/libncnn.a(swish_x86_avx2.cpp.o)：在函数‘ncnn::Swish_x86_avx2::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
swish_x86_avx2.cpp:(.text+0x43e)：对‘omp_get_num_threads’未定义的引用
swish_x86_avx2.cpp:(.text+0x446)：对‘omp_get_thread_num’未定义的引用
/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib/libncnn.a(swish_x86_avx2.cpp.o)：在函数‘virtual thunk to ncnn::Swish_x86_avx2::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
swish_x86_avx2.cpp:(.text+0x633)：对‘GOMP_parallel’未定义的引用
swish_x86_avx2.cpp:(.text+0x658)：对‘GOMP_parallel’未定义的引用
/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib/libncnn.a(groupnorm.cpp.o)：在函数‘ncnn::GroupNorm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
groupnorm.cpp:(.text+0xe0)：对‘GOMP_parallel’未定义的引用
/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib/libncnn.a(groupnorm.cpp.o)：在函数‘ncnn::GroupNorm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
groupnorm.cpp:(.text+0x116)：对‘omp_get_num_threads’未定义的引用
groupnorm.cpp:(.text+0x11e)：对‘omp_get_thread_num’未定义的引用
/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib/libncnn.a(layernorm.cpp.o)：在函数‘ncnn::LayerNorm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]’中：
layernorm.cpp:(.text+0x66)：对‘omp_get_num_threads’未定义的引用
layernorm.cpp:(.text+0x6e)：对‘omp_get_thread_num’未定义的引用
/home/CLion-2020.2/clion-2020.2/ncnn-master/build/install/lib/libncnn.a(layernorm.cpp.o)：在函数‘ncnn::LayerNorm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const’中：
layernorm.cpp:(.text+0x6d3)：对‘GOMP_parallel’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/yolov5s.dir/build.make:110: recipe for target 'yolov5s' failed
make[3]: *** [yolov5s] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/yolov5s.dir/all' failed
make[2]: *** [CMakeFiles/yolov5s.dir/all] Error 2
CMakeFiles/Makefile2:102: recipe for target 'CMakeFiles/yolov5s.dir/rule' failed
make[1]: *** [CMakeFiles/yolov5s.dir/rule] Error 2
Makefile:138: recipe for target 'yolov5s' failed
make: *** [yolov5s] Error 2

**Comment by zzzz737** [comment]
> 有个疑问是，你的代码中需要使用openmp加速吗？加速得到的提升有多少？没记错的话，ncnn本身已经有openmp加速了。

如果使用你说的第二种方法，会出现我最开使说的那个错，上面这个错，我看就是openmp找不到！

**Comment by zzzz737** [comment]
> 有个疑问是，你的代码中需要使用openmp加速吗？加速得到的提升有多少？没记错的话，ncnn本身已经有openmp加速了。

我看ncnn的官方文档好像也说了自带有openmp，但是编译cmake就会报错，注释掉有关openmp的地方，cmake能编译通过，但是cpp文件运行报错，就是上面那个，显示的omp未定义，我不知道是我没装openmp还是说我的ncnn编译有问题，但是我用ncnn跑官方的demo又可以跑

**Comment by zchrissirhcz** [comment]
@zzzz737 需要你把编译ncnn时候的具体设定贴一下（cmake的各种选项），我猜你开了NCNN_AVX2，不知道有没有其他选项。我们需要先复现这个问题，才能帮你排查。

**Comment by zchrissirhcz** [comment]
>我看ncnn的官方文档好像也说了自带有openmp，但是编译cmake就会报错，注释掉有关openmp的地方，cmake能编译通过，但是cpp文件运行报错，就是上面那个，显示的omp未定义，我不知道是我没装openmp还是说我的ncnn编译有问题，但是我用ncnn跑官方的demo又可以跑

还请明确一下，这里提到的"编译cmake就会报错"指的是编译ncnn本身，还是编译你自己的yolov5s工程？

**Comment by zzzz737** [comment]
> > 我看ncnn的官方文档好像也说了自带有openmp，但是编译cmake就会报错，注释掉有关openmp的地方，cmake能编译通过，但是cpp文件运行报错，就是上面那个，显示的omp未定义，我不知道是我没装openmp还是说我的ncnn编译有问题，但是我用ncnn跑官方的demo又可以跑
> 
> 还请明确一下，这里提到的"编译cmake就会报错"指的是编译ncnn本身，还是编译你自己的yolov5s工程？

是编译我自己的yolov5s工程

**Comment by zchrissirhcz** [comment]
你的ncnn库的编译参数是怎样的呢？关闭了`NCNN_OPENMP`吗？

**Comment by zzzz737** [comment]
> > 我看ncnn的官方文档好像也说了自带有openmp，但是编译cmake就会报错，注释掉有关openmp的地方，cmake能编译通过，但是cpp文件运行报错，就是上面那个，显示的omp未定义，我不知道是我没装openmp还是说我的ncnn编译有问题，但是我用ncnn跑官方的demo又可以跑
> 
> 还请明确一下，这里提到的"编译cmake就会报错"指的是编译ncnn本身，还是编译你自己的yolov5s工程？

我编译ncnn是按照官方的方式编译的：
![图片](https://user-images.githubusercontent.com/69610913/93594329-38dda480-f9e8-11ea-8201-128122672db9.png)
然后这个squeezenet的demo时可以跑的

**Comment by zchrissirhcz** [comment]
@zzzz737 我还是没弄清楚你在yolov5.cpp中使用openmp的必要性。

不过我还是定位到了你贴出的报错的问题所在。

请在你的CMakeLists.txt的第二行添加一句：
```cmake
project(yolov5)
```
`yolov5`可以换成别的名字。

然后重新cmake即可。

**Comment by zzzz737** [comment]
> @zzzz737 我还是没弄清楚你在yolov5.cpp中使用openmp的必要性。
> 
> 不过我还是定位到了你贴出的报错的问题所在。
> 
> 请在你的CMakeLists.txt的第二行添加一句：
> 
> ```cmake
> project(yolov5)
> ```
> 
> `yolov5`可以换成别的名字。
> 
> 然后重新cmake即可。

非常感谢抽时间回答我的问题，openmp的问题解决了，非常感谢！

**Comment by zchrissirhcz** [comment]
@zzzz737 还请关闭此issue，谢谢~
