### ISSUE TITLE
onnx converter

### ISSUE THREAD

**Issue by nihui** [Tencent/ncnn#214]

**Comment by szad670401** [comment]
很重要😊

**Comment by nihui** [comment]
model support status
https://github.com/onnx/models

- [ ] alexnet
- [ ] googlenet
- [ ] caffenet
- [ ] rcnn_ilsvrc13
- [ ] densenet121
- [ ] emotion_ferplus
- [ ] inception_v1
- [ ] inception_v2
- [ ] mnist
- [ ] resnet50
- [ ] shufflenet
- [ ] squeezenet
- [ ] vgg16
- [ ] vgg19

**Comment by nihui** [comment]
onnx converter enabled
https://github.com/Tencent/ncnn/commit/addfcbafe0c292371fcabd6935dddba3130bfd56

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
