### ISSUE TITLE
新加入的groupnorm在onnx2ncnn转换中导致param出错

### ISSUE THREAD

**Issue by BlueWinters** [Tencent/ncnn#2142]
问题描述：groupnorm在onnx到ncnn的转换过程中，会导致layers数量的错误，具体如下：

定义pytorch的模型：
```
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.gn = nn.GroupNorm(2, 4)

    def forward(self, x):
        return self.gn(x)
```

依次运行导出onnx文件[onnx.zip](https://github.com/Tencent/ncnn/files/5258770/onnx.zip)

运行onnx2ncnn导出param和bin，param文件中layers数量为0
```
7767517
0 2
Input            x                        0 1 x
GroupNorm        y                        1 1 x y 0=2 1=4 2=1.000000e-05 3=1
```

**同时**，ncnnoptimizer也未更新groupnorm相关操作，具体：
手工修改上述layers（0-->2），然后运行ncnnoptimizer，导出gn-opt.bin的大小为0（参数被丢弃了QAQ）

**Comment by nihui** [comment]
修好了

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
