### ISSUE TITLE
大佬们，有测试过yolov5模型或者其他模型转ncnn精度会掉几个点吗？

### ISSUE THREAD

**Issue by zzzz737** [Tencent/ncnn#2147]

**Comment by DingYiWen** [comment]
大佬，你是怎么把yolov5转成ncnn的，连同头一起导出onnx再转ncnn的话，会报不支持slice\expand这些。大佬你是咋做的？

**Comment by zzzz737** [comment]
> 大佬，你是怎么把yolov5转成ncnn的，连同头一起导出onnx再转ncnn的话，会报不支持slice\expand这些。大佬你是咋做的？

刚好写完博客，运气好！https://blog.csdn.net/qq_33160678/article/details/108848264自己去看吧

**Comment by DingYiWen** [comment]
谢谢大佬，给大佬跪了

**Comment by nihui** [comment]
参考 https://zhuanlan.zhihu.com/p/275989233

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
