### ISSUE TITLE
各个版本问题（有的好使，有的不好使）

### ISSUE THREAD

**Issue by ReverseSystem001** [Tencent/ncnn#2153]
nihui大佬，有个问题想请教一下；我的配置是这样的
pytorch==1.5.0
onnx==1.6.0
onnxruntime==1.4.0
onnx-simplifier==0.2.9

用ncnn-20200413最后转换出的模型都好使，推理部分直接load_param等整个流程都ok；但是使用ncnn-20200727 跟
ncnn-20200916（mk文件ndk版本也改成了相应的版本），onnx->ncnn转换流程都没问题，但是inference使用ncnn->load_param（）加载模型时就直接崩了，好奇怪；有空麻烦回答下，是各个版本的问题吗？

**Comment by ReverseSystem001** [comment]
引入的ncnn include文件需要根据不同ndk版本进行相应替换，ncnn项目中build.sh可创建相应的include文件，刚开始没注意，，，

**Comment by kunyao2015** [comment]
你好，没明白你的版本替换的意思，我也是遇到ncnn->load_param加载就崩了的情况，用的最新的ncnn版本

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
