### ISSUE TITLE
救救孩子吧，ubuntu18，编译自己的工程，vulkan头文件找不到。。。

### ISSUE THREAD

**Issue by xiongzhu666** [Tencent/ncnn#2155]
给位大佬好，ncnn的sample编译都可以通过，测试都没问题，我在clion建立自己的工程的时候编译报错：

Scanning dependencies of target yolact
[ 50%] Building CXX object CMakeFiles/yolact.dir/main.cpp.o
In file included from /DATA/share/xiongzhu/thirdpart/ncnn/build/install/include/ncnn/mat.h:27:0,
                 from /DATA/share/xiongzhu/thirdpart/ncnn/build/install/include/ncnn/blob.h:18,
                 from /DATA/share/xiongzhu/thirdpart/ncnn/build/install/include/ncnn/net.h:18,
                 from /DATA/share/xiongzhu/CLionProjects/ncnn_pro/main.cpp:15:
/DATA/share/xiongzhu/thirdpart/ncnn/build/install/include/ncnn/allocator.h:30:10: fatal error: vulkan/vulkan.h: 没有那个文件或目录
 #include <vulkan/vulkan.h>

**Comment by nihui** [comment]
sudo apt-get install libvulkan-dev

**Comment by zchrissirhcz** [comment]
也可以是手动安装的vulkan，例如我是ubuntu16.04 用的是vulkan sdk 1.2.148
这种情况下我在`~/.bashrc`中的设定：
```bash
export VULKAN_SDK=/home/zz/soft/vulkansdk/1.2.148.0/x86_64
export PATH=$VULKAN_SDK/bin:$PATH
LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
```

**Comment by xiongzhu666** [comment]
> 也可以是手动安装的vulkan，例如我是ubuntu16.04 用的是vulkan sdk 1.2.148
> 这种情况下我在`~/.bashrc`中的设定：
> 
> ```shell
> export VULKAN_SDK=/home/zz/soft/vulkansdk/1.2.148.0/x86_64
> export PATH=$VULKAN_SDK/bin:$PATH
> LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
> ```

非常感谢社区大佬们迅速的反应，其实环境变量我已经设置过了，不过在自己的工程里没起作用（编译官方的例子可以），那我暂时先不用这个可选包吧。hui神的sudo默认安装指令确实可以解决问题，但是我又不太想这样。
再次谢谢二佬~！！哈哈

**Comment by baryluk** [comment]
Even better: `sudo apt install libvulkan-dev`
