### ISSUE TITLE
set_vulkan_compute failed

### ISSUE THREAD

**Issue by dengly** [Tencent/ncnn#2163]
运行使用GPU运算，报以下错误
```
set_vulkan_compute failed, network use_vulkan_compute disabled
```

从报错信息看是指网络禁止了vulkan，但不知是什么原因禁止
我是通过`ncnn::Extractor ex = net.create_extractor(); ex.set_vulkan_compute(true);`的方式设置的

版本是 android ios 预编译库 20200916 b766c8c  https://github.com/Tencent/ncnn/releases/download/20200916/ncnn-android-vulkan-lib.zip

**Comment by dengly** [comment]
如果修改为`net.opt.use_vulkan_compute = 1;`没有报以上错误，但是允许会闪退

**Comment by nihui** [comment]
开启方法参考 https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan

没有使用 gpu ？硬件是什么，系统版本？

android 可以参考这个例子 https://github.com/nihui/ncnn-android-squeezenet

**Comment by nihui** [comment]
某些手机在 adb shell 中使用vulkan会有问题，尝试用app调用
