### ISSUE TITLE
new ncnn with vulkan ,not support multple instance??  了?

### ISSUE THREAD

**Issue by bjthemost** [Tencent/ncnn#2167]
Hi , boss Hui

I use below code ,init Vulkan  in X86_64(ubuntu 18.04, with apt install libvulkan_dev,and rebuild ncnn )

But when multiple processes are running (the same program), it becomes very, very，very ， slow.

The old ncnn didn't have this problem(2019.07.xx)

why ? hui sir???

thank you...

best regards 

z
---------------

/* old
class GlobalGpuInstance
{
public:
    GlobalGpuInstance( ) {

        ncnn::create_gpu_instance();

    }
    ~GlobalGpuInstance() { ncnn::destroy_gpu_instance(); }
};

GlobalGpuInstance g_global_gpu_instance;
*/
void initVulk(int devID)
{

ncnn::create_gpu_instance();
    int gpu_device =0;
    int num_threads = 1;
    int powersave = 0;
    int isDisplay =1;
    int aDevId= 0; 
    gpu_device =devID;

#if NCNN_VULKAN 
 bool use_vulkan_compute = gpu_device != -1;   
 int cooling_down = 1;
  g_enable_cooling_down = cooling_down != 0;

    g_loop_count =4;// loop_count;

 if (use_vulkan_compute)
    {
	     g_warmup_loop_count = 10;

        g_vkdev = ncnn::get_gpu_device(gpu_device);
        g_blob_vkallocator =g_vkdev ->acquire_blob_allocator();// new ncnn::VkBlobAllocator(g_vkdev);//new ncnn::VkUnlockedBlobBufferAllocator(g_vkdev);
        g_staging_vkallocator =  g_vkdev ->acquire_staging_allocator();//new ncnn::VkStagingAllocator(g_vkdev);//new ncnn::VkUnlockedStagingBufferAllocator(g_vkdev);
    }
#endif
    ncnn::Option opt;
    opt.lightmode = true;
    opt.num_threads = 1;
    opt.blob_allocator = &g_blob_pool_allocator;
    opt.workspace_allocator = &g_workspace_pool_allocator;

#if NCNN_VULKAN
    //opt.vulkan_compute = g_use_vulkan_compute;
    opt.blob_vkallocator = g_blob_vkallocator;
    opt.workspace_vkallocator = g_blob_vkallocator;
    opt.staging_vkallocator = g_staging_vkallocator;
#endif // NCNN_VULKAN

    opt.use_winograd_convolution = true;
    opt.use_sgemm_convolution = true;
    opt.use_int8_inference = true;
    opt.use_vulkan_compute = use_vulkan_compute;
    opt.use_fp16_packed = true;
    opt.use_fp16_storage = true;
    opt.use_fp16_arithmetic = true;
    opt.use_int8_storage = true;
    opt.use_int8_arithmetic = true;
    opt.use_packing_layout = true;
    opt.use_shader_pack8 = false;
    opt.use_image_storage = false;

   // ncnn::set_default_option(opt);
    ncnn::set_cpu_powersave(powersave);
    ncnn::set_omp_dynamic(0);
    ncnn::set_omp_num_threads(num_threads);

#if NCNN_VULKAN
   // pnet.use_vulkan_compute = true;
//    rnet.use_vulkan_compute = true;
//    onet.use_vulkan_compute = true;
    std::cout << "use vulkan "<<std::endl;

    if (use_vulkan_compute)
    {
         pnet.opt=opt;//use_vulkan_compute = use_vulkan_compute;
        pnet.set_vulkan_device(g_vkdev);

        rnet.opt=opt;
        rnet.set_vulkan_device(g_vkdev);

        onet.opt=opt;
        onet.set_vulkan_device(g_vkdev);
    }
#endif // NCNN_VULKAN
#if NCNN_VULKAN
    g_blob_pool_allocator.clear();
    g_workspace_pool_allocator.clear();
    if (use_vulkan_compute)
    {
        g_blob_vkallocator->clear();
        g_staging_vkallocator->clear();
    }
#endif // NCNN_VULKAN

}

**Comment by nihui** [comment]
The latest master branch supports compiling gpu functions without installing vulkan-sdk. You can give it a try.
If it doesn’t work, feel free to reopen the issue and post your findings.
