### ISSUE TITLE
Is have example for WebAssembly? Can no find anywhere

### ISSUE THREAD

**Issue by paklau99988** [Tencent/ncnn#2173]
Is there online demo of ncnn web? 
Thanks you

**Comment by di-d6** [comment]
316901609

**Comment by paklau99988** [comment]
Is no understand reply

**Comment by waittim** [comment]
A web demo: https://github.com/nihui/ncnn-webassembly-yolov5
Action: https://github.com/Tencent/ncnn/actions/runs/370528198

**Comment by nihui** [comment]
https://github.com/nihui/ncnn-webassembly-yolov5
