### ISSUE TITLE
ncnn IOS 编译后体积过大，真机加模拟器的ncnn约17M

### ISSUE THREAD

**Issue by ZJune** [Tencent/ncnn#2181]
请教各位，按照https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-ios-on-macosx-with-xcode里面的操作编译ios的静态库，并设置了cmake 时-DENABLE_BITCODE=0，但是编译后真机加模拟器的ncnn约有17M，为什么预构建的ncnn只有13M（其实尺寸还是挺大），请问如何减小库体积？这样的体积放到app中肯定是太大了

**Comment by nihui** [comment]
因为架构太多了，13M 里面有 x86 x86-64 armv7 arm64 四个架构，你看看是不是还编译了其他架构，比如 arm64e ？

**Comment by ZJune** [comment]
> 因为架构太多了，13M 里面有 x86 x86-64 armv7 arm64 四个架构，你看看是不是还编译了其他架构，比如 arm64e ？

是的，armv7s和arm64e去掉后大概11M，再请问一下功能概述里面说的整体库体积小于 700K，并可轻松精简到小于 300K，这是怎么做到的呢？

**Comment by nihui** [comment]
根据模型所需要的层，把不需要的层全部去掉，只保留需要的架构，编译为so后的大小
静态库大小不代表最后二进制的大小

**Comment by ZJune** [comment]
> 根据模型所需要的层，把不需要的层全部去掉，只保留需要的架构，编译为so后的大小
> 静态库大小不代表最后二进制的大小
奥奥，了解了，感谢～
