### ISSUE TITLE
GPU device is recognized but crash occurs when using 

### ISSUE THREAD

**Issue by ghost** [Tencent/ncnn#2193]
Hello, 

I am using the LFFD model from here (https://github.com/SyGoing/LFFD-with-ncnn) which I successfully run on a CPU on a Windows 10 machine.

`cmake.exe -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - NMake Makefiles" . -B bin64 -DNCNN_VULKAN=ON -DNCNN_SYSTEM_GLSLANG=ON -DNCNN_BUILD_EXAMPLES=ON -DNCNN_BENCHMARK=ON -DNCNN_BUILD_TOOLS=ON  && cmake.exe --build bin64 
`
I verified that everything is OK and that Vulkan is fully supported and working on my platform.
During CMake:
`Found glslangValidator: C:/VulkanSDK/1.2.148.1/Bin/glslangValidator.exe`

During runtime:
```
int ins=ncnn::create_gpu_instance();
std::cout<<"GPU instance=?:" << ins<<std::endl;;
auto g= ncnn::get_gpu_device(0);
std::cout<<"GPU Device=?:" << g <<std::endl;;

[0 GeForce GTX 1080]  queueC=2[8]  queueT=1[2]  memU=10  memDL=7  memHV=8
[0 GeForce GTX 1080]  fp16p=1  fp16s=1  fp16a=0  int8s=1  int8a=1
GPU instance=?:0
GPU Device=?:000001B133A92D10
```

I then modified LFFD.cpp like so:
// enable vulkan compute feature before loading
```
    if (useGPU) {
        lffd.opt.use_vulkan_compute = true;
    }
	lffd.load_param(param_file_name.data());
	lffd.load_model(bin_file_name.data());
```
However, **this results in a crash**. Is there anything else  I have to do? 

I also tried 
`ex.set_vulkan_compute(true);` **with and WITHOUT** `lffd.opt.use_vulkan_compute = true;` but this does not work either. 

In addition, whenever I activate the model it prints debug messages to the console, can these be disabled? 

```
Convolution              conv1                             11.56ms    |    feature_map:  320 x 240     inch:    4    out
ch:   64     kernel: 3 x 3     stride: 2 x 2
ReLU                     relu_conv1                         0.56ms    |    feature_map:  159 x 119     inch:   64    out
ch:   64
Convolution              conv2                             35.94ms    |    feature_map:  159 x 119     inch:   64    out
```

The header fiel also includes: 
```
#include "cpu.h"
#include "net.h"
#if NCNN_VULKAN
#include "gpu.h"
#endif
#include "models/LFFD.h"
```

Thanks,

**Comment by nihui** [comment]
Try the latest ncnn release

**Comment by QuantScientist** [comment]
Thanks, I just did, none of the behavior I reported above changed. Still crashes. 
I even explicitly loaded the model into the GPU like so:

```
#if NCNN_VULKAN
    if (lffd.opt.use_vulkan_compute)
    {
        lffd.set_vulkan_device(device);
        lffd.opt.use_vulkan_compute = true;
    }
#endif // NCNN_VULKAN
```  
Also, regarding the debug messages, how do I disable them?

**Comment by QuantScientist** [comment]
Do I need to call   `ncnn::create_gpu_instance()` ( commented out below)?  
Crashes with or without this invocation. 


```
ncnn::Option VisionUtils::optGPU(bool use_vulkan_compute=false, int gpu_device=-1) {
    ncnn::Option opt;
    opt.lightmode = true;
    opt.num_threads = 4;
    opt.blob_allocator = &g_blob_pool_allocator;
    opt.workspace_allocator = &g_workspace_pool_allocator;
    opt.use_vulkan_compute=false;
    #if NCNN_VULKAN
    if (use_vulkan_compute && gpu_device >-1)
    {
        opt.use_vulkan_compute=true;
        //         ncnn::create_gpu_instance(); 
        g_vkdev = ncnn::get_gpu_device(gpu_device);
        g_blob_vkallocator = new ncnn::VkBlobAllocator(g_vkdev);
        g_staging_vkallocator = new ncnn::VkStagingAllocator(g_vkdev);
        opt.blob_vkallocator = g_blob_vkallocator;
        opt.workspace_vkallocator = g_blob_vkallocator;
        opt.staging_vkallocator = g_staging_vkallocator;
    }
    #endif // NCNN_VULKAN
    return opt;
}

```

**Comment by QuantScientist** [comment]
I found the problem after hours of debugging. Here is an initial result:
![ezgif-7-89b55a1b1021](https://user-images.githubusercontent.com/18743986/95690103-f93c5e00-0c1d-11eb-801d-ed8f9127521d.gif)
