### ISSUE TITLE
onnx2ncnn中MatMul转换出错

### ISSUE THREAD

**Issue by yh8899** [Tencent/ncnn#2194]
在转换Torch.MatMul算子时，出现错误，跟踪发现是ncnn把matmul全都转换为innerproduct，而Torch.MatMul转出的onnx是不带weights的，下面代码处出现错误
![image](https://user-images.githubusercontent.com/5336422/95729225-27b64980-0caf-11eb-866b-28719e45925c.png)
请问，对Torch.MatMul有没有什么好的解决办法？

**Comment by cruiceble** [comment]
同问

**Comment by cruiceble** [comment]
@yh8899 请问找到解决方法了嘛？

**Comment by yh8899** [comment]
> @yh8899 请问找到解决方法了嘛？

没有，ncnn里面不支持matmul这个算子。

**Comment by nihui** [comment]
最新的代码可以转换成 Gemm 了

**Comment by cruiceble** [comment]
@nihui 感谢nihui大佬；弱问红线处的dim是不是应该是transpose的weight而不是matmul的？

**Comment by yh8899** [comment]
@nihui 感谢大佬，没更新版本，赶紧更新玩一下。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
