### ISSUE TITLE
yolov5s的onnx转ncnn模型的问题

### ISSUE THREAD

**Issue by zxy464430447** [Tencent/ncnn#2226]
大佬您好，我这边在偿试使用yolov5的模型转ncnn的时候没有报错，但转出来的文件被截断了，不完整，请问这是什么原因呀？
onnx文件链接：
链接：https://pan.baidu.com/s/1OqqHihx0XFr86jsGeVyoSQ 
提取码：k426

**Comment by tinydustmr** [comment]
我也遇到了这个问题，我是在windows下编译的ncnn，后来我在linux下又编译了一个ncnn，然后同样的方法，竟然可以成功检测了。我也很想知道在windows下怎么解决。

**Comment by zxy464430447** [comment]
> 我也遇到了这个问题，我是在windows下编译的ncnn，后来我在linux下又编译了一个ncnn，然后同样的方法，竟然可以成功检测了。我也很想知道在windows下怎么解决。

那可不可以在linux下转换，然后放在windows做运行呢，有做过试验吗？

**Comment by tinydustmr** [comment]
> > 我也遇到了这个问题，我是在windows下编译的ncnn，后来我在linux下又编译了一个ncnn，然后同样的方法，竟然可以成功检测了。我也很想知道在windows下怎么解决。
> 
> 那可不可以在linux下转换，然后放在windows做运行呢，有做过试验吗？

那倒没有，直接扔android studio是可以的，所以我觉得windows也可以。

**Comment by zxy464430447** [comment]
> > > 我也遇到了这个问题，我是在windows下编译的ncnn，后来我在linux下又编译了一个ncnn，然后同样的方法，竟然可以成功检测了。我也很想知道在windows下怎么解决。
> > 
> > 
> > 那可不可以在linux下转换，然后放在windows做运行呢，有做过试验吗？
> 
> 那倒没有，直接扔android studio是可以的，所以我觉得windows也可以。

好的，多谢，有时间我试试

**Comment by EricHuiK** [comment]
同样的问题，我直接转换是报错的，直接放在Android(打开应用后会闪退)，我按照网上的方式，把slice操作改编了，不进行切片操作，这样的话可以转换但是检测出来的框是密密麻麻的的一堆，有人检测自己数据集成功的么

**Comment by nihui** [comment]
参考 https://zhuanlan.zhihu.com/p/275989233

**Comment by EricHuiK** [comment]
@nihui ,你好按照您说的方式，是可以转换的，但是下载按照你推荐的链接，Android项目中编译会报错：intermediates/cmake/debug/obj/arm64-v8a/libyolov5ncnn.so', missing and no known rule to make it?，翻遍提示下怎么解决嘛，谢谢！

**Comment by EricHuiK** [comment]
@nihui ，已解决，感谢！

**Comment by wszsp** [comment]
下载了nihui的demo试图直接studio运行，发现了上述同样的libyolov5ncnn.so问题，请问这个是什么原因

**Comment by 307509256** [comment]
metoo，用最新的https://github.com/ultralytics/yolov5我的param文件都被截断了，这样怎么改也不行啊

**Comment by 307509256** [comment]
我试用linux版本，是不会截断的，但是检查结果不准确，anchor很多且不是我要的类别

**Comment by 307509256** [comment]
anchor多的问题解决了，把reshape改成-1就行，但是检测的精度有问题，近景的图片都检测不到，小物体可以检测到，和nihui的模型差别很大

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
