### ISSUE TITLE
arm交叉编译出错

### ISSUE THREAD

**Issue by Wq-dd** [Tencent/ncnn#2233]
在交叉编译ncnn时出现这个错误。
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-linux-gnu.toolchain.cmake ..
make -j8
![2020-10-19 15-32-16屏幕截图](https://user-images.githubusercontent.com/62586707/96415128-a4ea3d00-1220-11eb-823b-c70fedd13083.png)

**Comment by nihui** [comment]
```cmake -DNCNN_ARM82=OFF ..```

**Comment by Wq-dd** [comment]
多谢，又出现了opencv的错误。
![01](https://user-images.githubusercontent.com/62586707/96417986-b2092b00-1224-11eb-9215-a26d2ff44010.png)

**Comment by nihui** [comment]
opencv 也需要先交叉编译出来才能用
或者 ```cmake -DNCNN_BUILD_EXAMPLES=OFF -DNCNN_BUILD_TOOLS=OFF ..``` 跳过

**Comment by Wq-dd** [comment]
搞定，多谢。
