### ISSUE TITLE
mac 编译ncnn 提示 library not found for -lEigen3::Eigen

### ISSUE THREAD

**Issue by li2508264** [Tencent/ncnn#2238]
在mac 编译ncnn的时候cmake提示`Target "ncnn2table" links to target "Eigen3::Eigen" but the target was not  found.`因此在tools/quantize/CMakeLists.txt加了find_package(Eigen3 3.3 REQUIRED NO_MODULE)，结果编译最后link的时候就提示not found for -lEigen3::Eigen。

我寻思Eigen3不是一个头文件库吗，为什么会有library not found呢？

**Comment by zchrissirhcz** [comment]
ncnn 的 量化工具 不依赖于 eigen。
你的 ncnn 源码，除了添加的`find_package(Eigen3 3.3 REQUIRED NO_MODULE)`，有别的修改吗

**Comment by li2508264** [comment]
没有修改，我也有点摸不着头脑，谢谢回复，我再各处试试吧
