### ISSUE TITLE
编译ncnn出错

### ISSUE THREAD

**Issue by reachzxsframe** [Tencent/ncnn#2239]
[ 97%] Running C++ protocol buffer compiler on onnx.proto
onnx.proto:451:5: Expected "required", "optional", or "repeated".
onnx.proto:451:17: Missing field number.
onnx.proto:479:3: Expected "required", "optional", or "repeated".
onnx.proto:479:15: Missing field number.
make[2]: *** [tools/onnx/onnx.pb.cc] Error 1
make[1]: *** [tools/onnx/CMakeFiles/onnx2ncnn.dir/all] Error 2
make: *** [all] Error 2

protobuf  版本： 3.12.4
opencv     版本： 2.4.5

**Comment by reachzxsframe** [comment]
protoc --version
libprotoc 2.5.0
升级protobuf

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
