### ISSUE TITLE
layer递归操作引发的问题

### ISSUE THREAD

**Issue by onepick** [Tencent/ncnn#224]
各层间的layer级联是递归操作，那每次调用exactor的时候，都会去递归一遍，这样会不会存在2个问题：

1.  跑大型网络模型的时候，对device的堆栈会形成一个极大的考验!
2.  每次都去压栈出栈，对于device性能较低而时间敏感的应用，还是有不小的影响

想问下，优图有没有考虑要将这部分替换为类似caffe的for的形式

**Comment by nihui** [comment]
大型网络不适合在手机部署，即使是非递归遍历
压栈出栈的消耗远远小于网络本身
递归遍历逻辑清晰，个人不会修改
不过，欢迎楼主贡献代码使用 for 实现
