### ISSUE TITLE
NCNN retinaface测试

### ISSUE THREAD

**Issue by yyqgood** [Tencent/ncnn#2240]
你好:
1. 我使用Pytorch_Retinaface: https://github.com/biubug6/Pytorch_Retinaface训练网络模型.
2. 使用以下命令:
       python -m onnxsim FaceDetector.onnx FaceDetector-sim.onnx
       ../build/tools/onnx/onnx2ncnn FaceDetector-sim.onnx FaceDetector.param FaceDetector.bin
转换成.param和.bin格式
3. 我想使用ncnn/examples/retinaface.cpp在本地测试转换的模型, 请问需要修改那些地方? 我执行会报以下错误:
find_blob_index_by_name data failed
Segmentation fault (core dumped)

**Comment by yyqgood** [comment]
我的 FaceDetector.param文件为:
7767517
185 201
Input            input0                   0 1 input0
Convolution      301                      1 1 input0 301 0=8 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=0 6=216
BatchNorm        302                      1 1 301 302 0=8
ReLU             303                      1 1 302 303 0=1.000000e-01
ConvolutionDepthWise 304                      1 1 303 304 0=8 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=72 7=8
BatchNorm        305                      1 1 304 305 0=8
ReLU             306                      1 1 305 306 0=1.000000e-01
Convolution      307                      1 1 306 307 0=16 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=128
BatchNorm        308                      1 1 307 308 0=16
ReLU             309                      1 1 308 309 0=1.000000e-01
ConvolutionDepthWise 310                      1 1 309 310 0=16 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=0 6=144 7=16
BatchNorm        311                      1 1 310 311 0=16
ReLU             312                      1 1 311 312 0=1.000000e-01
Convolution      313                      1 1 312 313 0=32 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=512
BatchNorm        314                      1 1 313 314 0=32
ReLU             315                      1 1 314 315 0=1.000000e-01
ConvolutionDepthWise 316                      1 1 315 316 0=32 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=288 7=32
BatchNorm        317                      1 1 316 317 0=32
ReLU             318                      1 1 317 318 0=1.000000e-01
Convolution      319                      1 1 318 319 0=32 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=1024
BatchNorm        320                      1 1 319 320 0=32
ReLU             321                      1 1 320 321 0=1.000000e-01
ConvolutionDepthWise 322                      1 1 321 322 0=32 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=0 6=288 7=32
BatchNorm        323                      1 1 322 323 0=32
ReLU             324                      1 1 323 324 0=1.000000e-01
Convolution      325                      1 1 324 325 0=64 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=2048
BatchNorm        326                      1 1 325 326 0=64
ReLU             327                      1 1 326 327 0=1.000000e-01
ConvolutionDepthWise 328                      1 1 327 328 0=64 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=576 7=64
BatchNorm        329                      1 1 328 329 0=64
ReLU             330                      1 1 329 330 0=1.000000e-01
Convolution      331                      1 1 330 331 0=64 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=4096
BatchNorm        332                      1 1 331 332 0=64
ReLU             333                      1 1 332 333 0=1.000000e-01
Split            splitncnn_0              1 2 333 333_splitncnn_0 333_splitncnn_1
ConvolutionDepthWise 334                      1 1 333_splitncnn_1 334 0=64 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=0 6=576 7=64
BatchNorm        335                      1 1 334 335 0=64
ReLU             336                      1 1 335 336 0=1.000000e-01
Convolution      337                      1 1 336 337 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=8192
BatchNorm        338                      1 1 337 338 0=128
ReLU             339                      1 1 338 339 0=1.000000e-01
ConvolutionDepthWise 340                      1 1 339 340 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=1152 7=128
BatchNorm        341                      1 1 340 341 0=128
ReLU             342                      1 1 341 342 0=1.000000e-01
Convolution      343                      1 1 342 343 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=16384
BatchNorm        344                      1 1 343 344 0=128
ReLU             345                      1 1 344 345 0=1.000000e-01
ConvolutionDepthWise 346                      1 1 345 346 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=1152 7=128
BatchNorm        347                      1 1 346 347 0=128
ReLU             348                      1 1 347 348 0=1.000000e-01
Convolution      349                      1 1 348 349 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=16384
BatchNorm        350                      1 1 349 350 0=128
ReLU             351                      1 1 350 351 0=1.000000e-01
ConvolutionDepthWise 352                      1 1 351 352 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=1152 7=128
BatchNorm        353                      1 1 352 353 0=128
ReLU             354                      1 1 353 354 0=1.000000e-01
Convolution      355                      1 1 354 355 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=16384
BatchNorm        356                      1 1 355 356 0=128
ReLU             357                      1 1 356 357 0=1.000000e-01
ConvolutionDepthWise 358                      1 1 357 358 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=1152 7=128
BatchNorm        359                      1 1 358 359 0=128
ReLU             360                      1 1 359 360 0=1.000000e-01
Convolution      361                      1 1 360 361 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=16384
BatchNorm        362                      1 1 361 362 0=128
ReLU             363                      1 1 362 363 0=1.000000e-01
ConvolutionDepthWise 364                      1 1 363 364 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=1152 7=128
BatchNorm        365                      1 1 364 365 0=128
ReLU             366                      1 1 365 366 0=1.000000e-01
Convolution      367                      1 1 366 367 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=16384
BatchNorm        368                      1 1 367 368 0=128
ReLU             369                      1 1 368 369 0=1.000000e-01
Split            splitncnn_1              1 2 369 369_splitncnn_0 369_splitncnn_1
ConvolutionDepthWise 370                      1 1 369_splitncnn_1 370 0=128 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=0 6=1152 7=128
BatchNorm        371                      1 1 370 371 0=128
ReLU             372                      1 1 371 372 0=1.000000e-01
Convolution      373                      1 1 372 373 0=256 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=32768
BatchNorm        374                      1 1 373 374 0=256
ReLU             375                      1 1 374 375 0=1.000000e-01
ConvolutionDepthWise 376                      1 1 375 376 0=256 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304 7=256
BatchNorm        377                      1 1 376 377 0=256
ReLU             378                      1 1 377 378 0=1.000000e-01
Convolution      379                      1 1 378 379 0=256 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=65536
BatchNorm        380                      1 1 379 380 0=256
ReLU             381                      1 1 380 381 0=1.000000e-01
Convolution      382                      1 1 333_splitncnn_0 382 0=64 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=4096
BatchNorm        383                      1 1 382 383 0=64
ReLU             384                      1 1 383 384 0=1.000000e-01
Convolution      385                      1 1 369_splitncnn_0 385 0=64 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=8192
BatchNorm        386                      1 1 385 386 0=64
ReLU             387                      1 1 386 387 0=1.000000e-01
Convolution      388                      1 1 381 388 0=64 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=0 6=16384
BatchNorm        389                      1 1 388 389 0=64
ReLU             390                      1 1 389 390 0=1.000000e-01
Split            splitncnn_2              1 3 390 390_splitncnn_0 390_splitncnn_1 390_splitncnn_2
Interp           407                      1 1 390_splitncnn_2 407 0=1 1=2.000000e+00 2=2.000000e+00
BinaryOp         408                      2 1 387 407 408 0=0
Convolution      409                      1 1 408 409 0=64 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=36864
BatchNorm        410                      1 1 409 410 0=64
ReLU             411                      1 1 410 411 0=1.000000e-01
Split            splitncnn_3              1 3 411 411_splitncnn_0 411_splitncnn_1 411_splitncnn_2
Interp           428                      1 1 411_splitncnn_2 428 0=1 1=2.000000e+00 2=2.000000e+00
BinaryOp         429                      2 1 384 428 429 0=0
Convolution      430                      1 1 429 430 0=64 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=36864
BatchNorm        431                      1 1 430 431 0=64
ReLU             432                      1 1 431 432 0=1.000000e-01
Split            splitncnn_4              1 2 432 432_splitncnn_0 432_splitncnn_1
Convolution      433                      1 1 432_splitncnn_1 433 0=32 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=18432
BatchNorm        434                      1 1 433 434 0=32
Convolution      435                      1 1 432_splitncnn_0 435 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=9216
BatchNorm        436                      1 1 435 436 0=16
ReLU             437                      1 1 436 437 0=1.000000e-01
Split            splitncnn_5              1 2 437 437_splitncnn_0 437_splitncnn_1
Convolution      438                      1 1 437_splitncnn_1 438 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        439                      1 1 438 439 0=16
Convolution      440                      1 1 437_splitncnn_0 440 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        441                      1 1 440 441 0=16
ReLU             442                      1 1 441 442 0=1.000000e-01
Convolution      443                      1 1 442 443 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        444                      1 1 443 444 0=16
Concat           445                      3 1 434 439 444 445 0=0
ReLU             446                      1 1 445 446
Split            splitncnn_6              1 3 446 446_splitncnn_0 446_splitncnn_1 446_splitncnn_2
Convolution      447                      1 1 411_splitncnn_1 447 0=32 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=18432
BatchNorm        448                      1 1 447 448 0=32
Convolution      449                      1 1 411_splitncnn_0 449 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=9216
BatchNorm        450                      1 1 449 450 0=16
ReLU             451                      1 1 450 451 0=1.000000e-01
Split            splitncnn_7              1 2 451 451_splitncnn_0 451_splitncnn_1
Convolution      452                      1 1 451_splitncnn_1 452 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        453                      1 1 452 453 0=16
Convolution      454                      1 1 451_splitncnn_0 454 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        455                      1 1 454 455 0=16
ReLU             456                      1 1 455 456 0=1.000000e-01
Convolution      457                      1 1 456 457 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        458                      1 1 457 458 0=16
Concat           459                      3 1 448 453 458 459 0=0
ReLU             460                      1 1 459 460
Split            splitncnn_8              1 3 460 460_splitncnn_0 460_splitncnn_1 460_splitncnn_2
Convolution      461                      1 1 390_splitncnn_1 461 0=32 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=18432
BatchNorm        462                      1 1 461 462 0=32
Convolution      463                      1 1 390_splitncnn_0 463 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=9216
BatchNorm        464                      1 1 463 464 0=16
ReLU             465                      1 1 464 465 0=1.000000e-01
Split            splitncnn_9              1 2 465 465_splitncnn_0 465_splitncnn_1
Convolution      466                      1 1 465_splitncnn_1 466 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        467                      1 1 466 467 0=16
Convolution      468                      1 1 465_splitncnn_0 468 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        469                      1 1 468 469 0=16
ReLU             470                      1 1 469 470 0=1.000000e-01
Convolution      471                      1 1 470 471 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=0 6=2304
BatchNorm        472                      1 1 471 472 0=16
Concat           473                      3 1 462 467 472 473 0=0
ReLU             474                      1 1 473 474
Split            splitncnn_10             1 3 474 474_splitncnn_0 474_splitncnn_1 474_splitncnn_2
Convolution      475                      1 1 446_splitncnn_2 475 0=8 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=512
Permute          476                      1 1 475 476 0=3
Reshape          486                      1 1 476 486 0=4 1=-1
Convolution      487                      1 1 460_splitncnn_2 487 0=8 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=512
Permute          488                      1 1 487 488 0=3
Reshape          498                      1 1 488 498 0=4 1=-1
Convolution      499                      1 1 474_splitncnn_2 499 0=8 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=512
Permute          500                      1 1 499 500 0=3
Reshape          510                      1 1 500 510 0=4 1=-1
Concat           output0                  3 1 486 498 510 output0 0=0
Convolution      512                      1 1 446_splitncnn_1 512 0=4 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=256
Permute          513                      1 1 512 513 0=3
Reshape          523                      1 1 513 523 0=2 1=-1
Convolution      524                      1 1 460_splitncnn_1 524 0=4 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=256
Permute          525                      1 1 524 525 0=3
Reshape          535                      1 1 525 535 0=2 1=-1
Convolution      536                      1 1 474_splitncnn_1 536 0=4 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=256
Permute          537                      1 1 536 537 0=3
Reshape          547                      1 1 537 547 0=2 1=-1
Concat           548                      3 1 523 535 547 548 0=0
Convolution      549                      1 1 446_splitncnn_0 549 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1280
Permute          550                      1 1 549 550 0=3
Reshape          560                      1 1 550 560 0=10 1=-1
Convolution      561                      1 1 460_splitncnn_0 561 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1280
Permute          562                      1 1 561 562 0=3
Reshape          572                      1 1 562 572 0=10 1=-1
Convolution      573                      1 1 474_splitncnn_0 573 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1280
Permute          574                      1 1 573 574 0=3
Reshape          584                      1 1 574 584 0=10 1=-1
Concat           585                      3 1 560 572 584 585 0=0
Softmax          586                      1 1 548 586 0=1 1=1

**Comment by zchrissirhcz** [comment]
You may just search "find_blob_index_by_name data failed" in this issue and find several questions with solutions.

**Comment by yyqgood** [comment]
@zchrissirhcz 我在这个地方: https://github.com/biubug6/Face-Detector-1MB-with-landmark/tree/master/Face_Detector_ncnn找到了解决方法

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by gordinmitya** [comment]
@nihui looks like after converting with pnnx the model is frozen with example input shape and is not able to change output shape at runtime

the face.param from [Face_Detector_ncnn](https://github.com/biubug6/Face-Detector-1MB-with-landmark/tree/master/Face_Detector_ncnn) is converted with old onnx2ncnn - and can handle variable input size -> output shape changes accordingly
however after I exported with pnnx - model always output the same shape regardless of input Mat
[fork with pnnx export](https://github.com/gordinmitya/Face-Detector-1MB-with-landmark/blob/master/convert_to_onnx.py#L110)

my guess this is fault of torch.jit.trace
