### ISSUE TITLE
File out libncnn.a so large

### ISSUE THREAD

**Issue by ngocdu12a1** [Tencent/ncnn#2245]
I've built libncnn for android on my own. But the file output is much larger (about 63M for arm64-v8a) than Tencent's library. I used the script which was provided by tencent (build.sh). I didn't know what was wrong. Can anyone explain that to me?
![ncnn](https://user-images.githubusercontent.com/42245190/96952242-9188eb80-1518-11eb-939c-60f91b78e692.png)

**Comment by nihui** [comment]
https://github.com/android/ndk/issues/243
```
# open $ANDROID_NDK/build/cmake/android.toolchain.cmake with your editor
# delete "-g"
list(APPEND ANDROID_COMPILER_FLAGS
  -g
  -DANDROID
```
