### ISSUE TITLE
单线程测试的问题

### ISSUE THREAD

**Issue by WenguoLi** [Tencent/ncnn#225]
设置线程个数为1, 即 ex.set_num_threads(1)，测试squeezenet例子耗时743.04ms

不设置线程个数 即 //ex.set_num_threads(4)，测试squeezenet例子耗时411.04ms

这两种方式测试的耗时不一样，到底那个才是准确的单线程测试耗时？

**Comment by nihui** [comment]
ex.set_num_threads(1) 是单线程
不设置是根据系统环境自动设置
