### ISSUE TITLE
tools\caffe\CMakeFiles\caffe2ncnn.dir\build.make(64) : fatal error U1033: 语法错误: 意外的“::”

### ISSUE THREAD

**Issue by tszhang20** [Tencent/ncnn#2256]
Windows10+VS2019下编译ncnn，出现如下错误，谢谢解答：
`yolact.cpp
G:\Tencent-ncnn\ncnn\src\mat.h(1342): warning C4267: “return”: 从“size_t”转换到“int”，可能丢失数据
G:\Tencent-ncnn\ncnn\examples\yolact.cpp(80): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
G:\Tencent-ncnn\ncnn\examples\yolact.cpp(87): warning C4267: “初始化”: 从“size_t”转换到“int”，可能丢失数据
G:\Tencent-ncnn\ncnn\examples\yolact.cpp(87): warning C4267: “初始化”: 从“size_t”转换到“const int”，可能丢失数据
G:\Tencent-ncnn\ncnn\examples\yolact.cpp(137): warning C4305: “初始化”: 从“double”到“const float”截断
G:\Tencent-ncnn\ncnn\examples\yolact.cpp(480): warning C4244: “初始化”: 从“const _Tp”转换到“int”，可能丢失数据
        with
        [
            _Tp=float
        ]
G:\Tencent-ncnn\ncnn\examples\yolact.cpp(481): warning C4244: “初始化”: 从“_Tp”转换到“int”，可能丢失数据
        with
        [
            _Tp=float
        ]
G:\Tencent-ncnn\ncnn\examples\yolact.cpp(475): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
[ 93%] Linking CXX executable yolact.exe
[ 93%] Built target yolact
Scanning dependencies of target ncnnoptimize
[ 93%] Building CXX object tools/CMakeFiles/ncnnoptimize.dir/ncnnoptimize.cpp.obj
ncnnoptimize.cpp
G:\Tencent-ncnn\ncnn\src\mat.h(1342): warning C4267: “return”: 从“size_t”转换到“int”，可能丢失数据
[ 93%] Linking CXX executable ncnnoptimize.exe
[ 93%] Built target ncnnoptimize
Scanning dependencies of target ncnn2mem
[ 93%] Building CXX object tools/CMakeFiles/ncnn2mem.dir/ncnn2mem.cpp.obj
ncnn2mem.cpp
G:\Tencent-ncnn\ncnn\src\mat.h(1342): warning C4267: “return”: 从“size_t”转换到“int”，可能丢失数据
[ 94%] Linking CXX executable ncnn2mem.exe
[ 94%] Built target ncnn2mem
tools\caffe\CMakeFiles\caffe2ncnn.dir\build.make(64) : fatal error U1033: 语法错误: 意外的“::”
Stop.
NMAKE : fatal error U1077: “"e:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"e:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.`

**Comment by cccober** [comment]
how to fix it?

**Comment by tszhang20** [comment]
> how to fix it?

I'm sorry, I forgot how to solve it, and I tried it again later and every went well. Follow this tutorial to install the corresponding version should be successful. https://blog.csdn.net/Skies_/article/details/109318667
