### ISSUE TITLE
windows下编译ncnn失败，是不支持opencv4吗

### ISSUE THREAD

**Issue by Bruno-bai** [Tencent/ncnn#2257]
![屏幕截图 2020-10-27 183337](https://user-images.githubusercontent.com/20271020/97290059-0181d380-1883-11eb-8363-744b31755d8d.jpg)
D:\ncnn\build_vs2019>nmake

Microsoft (R) 程序维护实用工具 14.27.29112.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

[  0%] Built target ncnn-generate-spirv
[ 81%] Built target ncnn
[ 81%] Built target benchncnn
[ 82%] Linking CXX executable yolov4.exe
LINK: command "D:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\yolov4.dir\objects1.rsp /out:yolov4.exe /implib:yolov4.lib /pdb:D:\ncnn\build_vs2019\examples\yolov4.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console ..\src\ncnn.lib D:\opencv\build\x64\mingw\lib\libopencv_highgui430.dll.a D:\opencv\build\x64\mingw\lib\libopencv_videoio430.dll.a D:\opencv\build\x64\mingw\lib\libopencv_imgcodecs430.dll.a D:\opencv\build\x64\mingw\lib\libopencv_imgproc430.dll.a D:\opencv\build\x64\mingw\lib\libopencv_core430.dll.a kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:yolov4.exe.manifest" failed (exit code 1120) with the following output:
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z)，函数 "public: __cdecl cv::Mat::~Mat(void)" (??1Mat@cv@@QEAA@XZ) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::copyTo(class cv::_OutputArray const &)const " (?copyTo@Mat@cv@@QEBAXAEBV_OutputArray@2@@Z)，函 数 "public: class cv::Mat __cdecl cv::Mat::clone(void)const " (?clone@Mat@cv@@QEBA?AV12@XZ) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::deallocate(void)" (?deallocate@Mat@cv@@QEAAXXZ)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "class cv::Mat __cdecl cv::imread(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?imread@cv@@YA?AVMat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z)，函数 main 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl cv::VideoCapture::VideoCapture(void)" (??0VideoCapture@cv@@QEAA@XZ)，函数 main 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: virtual __cdecl cv::VideoCapture::~VideoCapture(void)" (??1VideoCapture@cv@@UEAA@XZ)，函数 main 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: virtual bool __cdecl cv::VideoCapture::open(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?open@VideoCapture@cv@@UEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z)，函数 main 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: virtual bool __cdecl cv::VideoCapture::isOpened(void)const " (?isOpened@VideoCapture@cv@@UEBA_NXZ)，函数 main 中引用 了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "int __cdecl cv::waitKey(int)" (?waitKey@cv@@YAHH@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::imshow(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::_InputArray const &)" (?imshow@cv@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV_InputArray@1@@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::rectangle(class cv::_InputOutputArray const &,class cv::Rect_<int>,class cv::Scalar_<double> const &,int,int,int)" (?rectangle@cv@@YAXAEBV_InputOutputArray@1@V?$Rect_@H@1@AEBV?$Scalar_@N@1@HHH@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::putText(class cv::_InputOutputArray const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::Point_<int>,int,double,class cv::Scalar_<double>,int,int,bool)" (?putText@cv@@YAXAEBV_InputOutputArray@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$Point_@H@1@HNV?$Scalar_@N@1@HH_N@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "class cv::Size_<int> __cdecl cv::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,double,int,int *)" (?getTextSize@cv@@YA?AV?$Size_@H@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HNHPEAH@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.exe : fatal error LNK1120: 13 个无法解析的外部命令
NMAKE : fatal error U1077: “D:\CMake\bin\cmake.exe”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"d:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"d:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.

D:\ncnn\build_vs2019>

**Comment by Bruno-bai** [comment]
![屏幕截图 2020-10-27 183337](https://user-images.githubusercontent.com/20271020/97290114-16f6fd80-1883-11eb-8229-22b2cbdfa79d.jpg)

**Comment by Bruno-bai** [comment]
D:\ncnn\build_vs2019>nmake

Microsoft (R) 程序维护实用工具 14.27.29112.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

[  0%] Built target ncnn-generate-spirv
[ 81%] Built target ncnn
[ 81%] Built target benchncnn
[ 82%] Linking CXX executable yolov4.exe
LINK: command "D:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\yolov4.dir\objects1.rsp /out:yolov4.exe /implib:yolov4.lib /pdb:D:\ncnn\build_vs2019\examples\yolov4.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console ..\src\ncnn.lib D:\opencv\build\x64\mingw\lib\libopencv_highgui430.dll.a D:\opencv\build\x64\mingw\lib\libopencv_videoio430.dll.a D:\opencv\build\x64\mingw\lib\libopencv_imgcodecs430.dll.a D:\opencv\build\x64\mingw\lib\libopencv_imgproc430.dll.a D:\opencv\build\x64\mingw\lib\libopencv_core430.dll.a kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:yolov4.exe.manifest" failed (exit code 1120) with the following output:
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::fastFree(void *)" (?fastFree@cv@@YAXPEAX@Z)，函数 "public: __cdecl cv::Mat::~Mat(void)" (??1Mat@cv@@QEAA@XZ) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::copyTo(class cv::_OutputArray const &)const " (?copyTo@Mat@cv@@QEBAXAEBV_OutputArray@2@@Z)，函 数 "public: class cv::Mat __cdecl cv::Mat::clone(void)const " (?clone@Mat@cv@@QEBA?AV12@XZ) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl cv::Mat::deallocate(void)" (?deallocate@Mat@cv@@QEAAXXZ)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "class cv::Mat __cdecl cv::imread(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?imread@cv@@YA?AVMat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z)，函数 main 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl cv::VideoCapture::VideoCapture(void)" (??0VideoCapture@cv@@QEAA@XZ)，函数 main 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: virtual __cdecl cv::VideoCapture::~VideoCapture(void)" (??1VideoCapture@cv@@UEAA@XZ)，函数 main 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: virtual bool __cdecl cv::VideoCapture::open(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?open@VideoCapture@cv@@UEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z)，函数 main 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "public: virtual bool __cdecl cv::VideoCapture::isOpened(void)const " (?isOpened@VideoCapture@cv@@UEBA_NXZ)，函数 main 中引用 了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "int __cdecl cv::waitKey(int)" (?waitKey@cv@@YAHH@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::imshow(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::_InputArray const &)" (?imshow@cv@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV_InputArray@1@@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::rectangle(class cv::_InputOutputArray const &,class cv::Rect_<int>,class cv::Scalar_<double> const &,int,int,int)" (?rectangle@cv@@YAXAEBV_InputOutputArray@1@V?$Rect_@H@1@AEBV?$Scalar_@N@1@HHH@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "void __cdecl cv::putText(class cv::_InputOutputArray const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class cv::Point_<int>,int,double,class cv::Scalar_<double>,int,int,bool)" (?putText@cv@@YAXAEBV_InputOutputArray@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$Point_@H@1@HNV?$Scalar_@N@1@HH_N@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.cpp.obj : error LNK2019: 无法解析的外部符号 "class cv::Size_<int> __cdecl cv::getTextSize(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,double,int,int *)" (?getTextSize@cv@@YA?AV?$Size_@H@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HNHPEAH@Z)，函数 "int __cdecl draw_objects(class cv::Mat const &,class std::vector<struct Object,class std::allocator<struct Object> > const &,int)" (?draw_objects@@YAHAEBVMat@cv@@AEBV?$vector@UObject@@V?$allocator@UObject@@@std@@@std@@H@Z) 中引用了该符号
yolov4.exe : fatal error LNK1120: 13 个无法解析的外部命令
NMAKE : fatal error U1077: “D:\CMake\bin\cmake.exe”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"d:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"d:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.

D:\ncnn\build_vs2019>

**Comment by zchrissirhcz** [comment]
OpenCV用的是 自行编译的 mingw 版本？

**Comment by Bruno-bai** [comment]
> OpenCV用的是 自行编译的 mingw 版本？

用的mingw的

**Comment by Bruno-bai** [comment]
> OpenCV用的是 自行编译的 mingw 版本？

用的mingw的

**Comment by zchrissirhcz** [comment]
@Bruno-bai Hi, 可以考虑排除是否是mingw版opencv的问题。可以在opencv官网下载opencv最新版的windows预编译包，里面提供了vc15也就是vs2017的版本，然后搭配ncnn使用。

**Comment by sxj731533730** [comment]
我想问个问题 
  我的opencv 是mingw 编译的 是可以使用的 ，其次 我想使用mingw 编译libncnn.a
我操作步骤是这样的
cd protobuf-3.4.0\protobuf-3.4.0
F:\protobuf-3.4.0\protobuf-3.4.0\buildMinGW>cmake -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF ../cmake
F:\protobuf-3.4.0\protobuf-3.4.0\buildMinGW>mingw32-make
F:\protobuf-3.4.0\protobuf-3.4.0\buildMinGW>mingw32-make install

F:\>cd ncnn

F:\ncnn>mkdir build

F:\ncnn>cd build

F:\ncnn\build>cmake -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DProtobuf_INCLUDE_DIR=F:/protobuf-3.4.0/protobuf-3.4.0/buildMinGW/install/include -DProtobuf_LIBRARIES=F:/protobuf-3.4.0/protobuf-3.4.0/buildMinGW/install/lib/libprotobuf.a -D Protobuf_PROTOC_EXECUTABLE=F:/protobuf-3.4.0/protobuf-3.4.0/buildMinGW/install/bin/protoc.exe -D NCNN_VULKAN=OFF -DNCNN_AVX2=OFF ..
F:\ncnn\build>mingw32-make install 

我的cmakelist.txt文件为：
cmake_minimum_required(VERSION 3.17)
project(untitled4)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
# Where to find CMake modules and OpenCV
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -o3")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -o3")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp ")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp ")

set(OpenCV_DIR "D:\\Opencv440\\buildMinGW")#改为mingw-bulid的位置
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")
find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
# add libs you need


include_directories(${CMAKE_SOURCE_DIR}/include)

#导入ncnn
add_library(libncnn STATIC IMPORTED)
set_target_properties(libncnn PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/lib/libncnn.a)
add_executable(untitled4 main.cpp)

target_link_libraries(untitled4 ${OpenCV_LIBS} libncnn)


但是生成的libncnn.a和include 生成成功 但是 仍然 无法使用
====================[ Build | untitled4 | Debug ]===============================
"D:\Program Files (x86)\CLion 2020.2\bin\cmake\win\bin\cmake.exe" --build F:\untitled4\cmake-build-debug --target untitled4 -- -j 9
[ 50%] Linking CXX executable untitled4.exe
CMakeFiles\untitled4.dir/objects.a(main.cpp.obj): In function `demo(cv::Mat&, ncnn::Net&, int, int)':
F:/untitled4/main.cpp:297: undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int, ncnn::Allocator*)'
F:/untitled4/main.cpp:304: undefined reference to `ncnn::Option::Option()'
F:/untitled4/main.cpp:304: undefined reference to `ncnn::copy_make_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int, int, float, ncnn::Option const&)'
F:/untitled4/main.cpp:313: undefined reference to `ncnn::Mat::substract_mean_normalize(float const*, float const*)'
F:/untitled4/main.cpp:315: undefined reference to `ncnn::Net::create_extractor() const'
F:/untitled4/main.cpp:318: undefined reference to `ncnn::Extractor::input(char const*, ncnn::Mat const&)'
F:/untitled4/main.cpp:327: undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&, int)'
F:/untitled4/main.cpp:346: undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&, int)'
F:/untitled4/main.cpp:365: undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&, int)'
F:/untitled4/main.cpp:315: undefined reference to `ncnn::Extractor::~Extractor()'
F:/untitled4/main.cpp:315: undefined reference to `ncnn::Extractor::~Extractor()'
CMakeFiles\untitled4.dir/objects.a(main.cpp.obj): In function `test_cam()':

**Comment by sxj731533730** [comment]
已经解决

**Comment by nihui** [comment]
如有问题，可以reopen或者新开issue讨论...

**Comment by sxj731533730** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        收到 up 主  我解决了 在window10 下 使用mingw编译
        cd protobuf-3.4.0\protobuf-3.4.0F:\protobuf-3.4.0\protobuf-3.4.0\buildMinGW>cmake -G"MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF ../cmakeF:\protobuf-3.4.0\protobuf-3.4.0\buildMinGW>mingw32-makeF:\protobuf-3.4.0\protobuf-3.4.0\buildMinGW>mingw32-make install
    
        
            
        
    ----------------------------------------------------------------------------------------------------F:\>cd ncnn F:\ncnn>mkdir build F:\ncnn>cd build F:\ncnn\build>cmake -G"MinGW Makefiles" -DOpenCV_DIR=“D:\Opencv440\buildMinGW\install” -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DProtobuf_INCLUDE_DIR=F:/protobuf-3.4.0/protobuf-3.4.0/buildMinGW/install/include -DProtobuf_LIBRARIES=F:/protobuf-3.4.0/protobuf-3.4.0/buildMinGW/install/lib/libprotobuf.a -D Protobuf_PROTOC_EXECUTABLE=F:/protobuf-3.4.0/protobuf-3.4.0/buildMinGW/install/bin/protoc.exe -D NCNN_VULKAN=OFF -DNCNN_AVX2=OFF -DNCNN_SSE2=OFF ..F:\ncnn\build>mingw32-make install 谢谢 up主
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                sxj731533730
                            
                    
                        
                            
                                    sxj731533730@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年1月6日 23:48，nihui<notifications@github.com> 写道： 




如有问题，可以reopen或者新开issue讨论...



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
