### ISSUE TITLE
運行在 Sony Xa1 ultra 發生錯誤 Fatal signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by Aaron930** [Tencent/ncnn#2259]
目前只有在  Sony Xa1 ultra 這隻手機會發生這個問題，使用的.a 是從 https://github.com/Tencent/ncnn/releases 下載的

錯誤結果
<img width="1874" alt="Screen Shot 2020-10-27 at 9 31 54 PM" src="https://user-images.githubusercontent.com/24618929/97309295-ca202080-189c-11eb-8cd9-71a4ab283b46.png">

build gradle
<img width="1336" alt="Screen Shot 2020-10-27 at 9 40 54 PM" src="https://user-images.githubusercontent.com/24618929/97309550-22572280-189d-11eb-8b3e-995edb68d622.png">

NDK version
19c

cmakefile
<img width="925" alt="Screen Shot 2020-10-27 at 9 45 00 PM" src="https://user-images.githubusercontent.com/24618929/97310107-d3f65380-189d-11eb-9bf1-ad5e6a41eddf.png">
<img width="843" alt="Screen Shot 2020-10-27 at 9 45 15 PM" src="https://user-images.githubusercontent.com/24618929/97310126-d789da80-189d-11eb-85b9-71952befaa84.png">
<img width="859" alt="Screen Shot 2020-10-27 at 9 45 24 PM" src="https://user-images.githubusercontent.com/24618929/97310141-db1d6180-189d-11eb-9b87-b1482c56c04c.png">

**Comment by nihui** [comment]
参考 https://github.com/Tencent/ncnn/issues/976

**Comment by Aaron930** [comment]
修改的方式是這樣嗎？還是會報錯，更換了ndk 21d 使用`-fstatic-openmp`，情況也是一樣
<img width="1398" alt="Screen Shot 2020-10-28 at 9 02 41 AM" src="https://user-images.githubusercontent.com/24618929/97378058-64638100-18fc-11eb-8141-eec0d17398b4.png">

**Comment by nihui** [comment]
这是cmake的参考写法，https://github.com/nihui/ncnn-android-benchmark/blob/master/app/src/main/jni/CMakeLists.txt

gradle的linker flags参考 https://stackoverflow.com/questions/46085046/how-to-pass-linker-flags-to-cmake-in-android-studio-via-gradle

**Comment by sa1225** [comment]
请问解决了吗？
