### ISSUE TITLE
INT4量化推理

### ISSUE THREAD

**Issue by sroot0** [Tencent/ncnn#2270]
你好，现在有一个训练完成的INT4量化模型（levels=16)，文件格式是onnx，请问可以在ncnn框架中实现一次正向推理吗？

**Comment by BUG1989** [comment]
@sroot0 
好吧，居然有人在训练 Int4 的量化模型了，你们都是勇士！
BTW， 首先麻烦您再详细说明下你当前的技术状态

1. onnx已经支持 int4 量化模型的存储格式了吗？
2. 对称量化还是非对称量化，per-channel 还是 per-tensor？
3. 能否导出量化 weight 和 activation 所用的量化因子 scale？

请认真回答每一个问题，我看看能不能教你魔改下 ncnn int8 的源码，让你“实现一次正向推理”……

**Comment by sroot0** [comment]
> @ sroot0好吧
> ，居然有人在训练Int4的量化模型了，你们都是勇士！
> BTW，首先麻烦您再详细说明下你当前的技术状态
> 
> 1. onnx已经支持int4量化模型的存储格式了吗？
> 2. 对称量化还是非对称量化，每个通道还是每个张量？
> 3. 能否产生量化重量和激活所用的量化因子的规模？
> 
> 请认真回答每个一个问题，我看看能不能教你魔改下ncnn int8的源码，让你“实现一次正向推理”……
1、onnx已经支持int4量化模型的存储格式了，下面是打开的模型部分结构图，这个完成主要是基于nncf
   
![Uploading image.png…]()


2、我目前量化的IN4模型是非对称量化和每张量，但是如果需要的话可以更改设置
3、第3个问题，我没有尝试去导出scale，在量化这部分我了解的东西还是太少了，做INT4相关的量化也是由于ASIC的需求需要研究一下可行性

**Comment by BUG1989** [comment]
@sroot0 加我QQ（就是这个QQ邮箱的QQ）私聊吧，有点复杂了

**Comment by declanwucv** [comment]
> @sroot0 加我QQ（就是这个QQ邮箱的QQ）私聊吧，有点复杂了

大佬魔改成功了吗？

**Comment by 37ETs** [comment]
大佬是用什么工具量化到int4的？
