### ISSUE TITLE
"Expand not supported yet! " error when performing onnx2ncnn on model that consists of CBAM module

### ISSUE THREAD

**Issue by maxmx911** [Tencent/ncnn#2276]
My model consists of CBAM module, the code implementation of the CBAM module is from [here](https://github.com/Jongchan/attention-module/blob/master/MODELS/cbam.py). 

I've managed to export my model to onnx (had to cast `x.size(2)` and` x.size(3)` in `ChannelGate` forward to int) and ran onnx-simplifier (with `-skip_shape_inference` argument set to `True`, default is `False`) on the exported model. 

However, when I try to perform onnx2ncnn on the simplified model, I'm getting the error "**Expand not supported yet!**". 

Has anyone tried to perform onnx2ncnn with CBAM module successfully before? Or is there any advice regarding this issue?

Thank you in advance!!

**Comment by nihui** [comment]
open param with your editor, replace "Expand" with "Noop"

**Comment by maxmx911** [comment]
@nihui 
Thanks! Worked like a charm! 

Just so I understand this correctly, the reason for setting `Expand` to `Noop` is due to Ncnn `BinaryOp` accepts tensor with different shape, hence, this makes the `Expand` node useless. Yes?

**Comment by nihui** [comment]
> @nihui
> Thanks! Worked like a charm!
> 
> Just so I understand this correctly, the reason for setting `Expand` to `Noop` is due to Ncnn `BinaryOp` accepts tensor with different shape, hence, this makes the `Expand` node useless. Yes?

Yes
And the BinaryOp broadcasting rules are here
https://github.com/Tencent/ncnn/wiki/binaryop-broadcasting
