### ISSUE TITLE
Fatal signal 7 (SIGBUS), code 1, when use normed float data

### ISSUE THREAD

**Issue by Pinnh** [Tencent/ncnn#228]
mean file is not supported currently yet? so I use follow code to reconstruct input in order to test norm , when feed the reconstruct matrix to ncnn I get fatal signal 7 error,but when use the default norm method substract_mean_normalize evething is right .

Is there anything wrong with norm method?
Can you provide the sample method of mean file?

thanks for help~

ncnn::Mat sample_norm(ncnn::Mat& in){
	unsigned char data_in[10000];
	float data_out[10000];
	in.to_pixels(data_in,ncnn::Mat::PIXEL_GRAY);
	for(int i=0;i<100;i++){
		for(int j=0;j<100;j++){
			data_out[i*100+j]=((float)data_in[i*100+j])/255.0f;
		}
	}
	ncnn::Mat out(100,100,1,data_out);
	return out;
}

**Comment by nihui** [comment]
data_out pointer is not aligned by 128bit that caused the SIGBUS
you can apply operations ncnn::Mat internal data directly
```
ncnn::Mat in;
float* data = in;
// modify data will also modify the Mat in
```

**Comment by Pinnh** [comment]
Yes,It need pointer align, I solved this issue , thanks a lot~
