### ISSUE TITLE
ncnnoptimize after darknet2ncnn -> inconsistent content in layer 

### ISSUE THREAD

**Issue by linukc** [Tencent/ncnn#2281]
Yolo model work with darknet test, but if i try to run ncnnoptimize after darknet2ncnn i see error layer load_param failed: load_model error at layer 258, parameter file has inconsistent content (twice). I also cant load not optimized model with ncnn (same error). How i can detect this inconsistent content?
File with model config. I am following guide from https://github.com/dog-qiuqiu/Yolo-Fastest
[net.zip](https://github.com/Tencent/ncnn/files/5484475/net.zip)

**Comment by nihui** [comment]
reproduced

**Comment by nihui** [comment]
Your original darknet model file has invalid layer

yolo-fastest.cfg line 889
convolution filter 128 with group 96 is invalid setting, changing filter to 96 shall work
```
[convolutional]
filters=128
size=5
groups=96
stride=1
pad=1
batch_normalize=1
activation=leaky
```

**Comment by linukc** [comment]
@nihui , thanks a lot, i'll try. Share the secret: how you defined this layer 258 in the .cfg? Somehow programmatically or using tools identical to the netron app?
