### ISSUE TITLE
ncnn编译问题

### ISSUE THREAD

**Issue by Lee-Marry** [Tencent/ncnn#2282]
@nihui 
在CSDN找到的一个mobilenet-ssd在Android运行的例子，大概是18年的，运行环境为ubuntu16,在AS上写好代码后编译，出现以下错误，应（bu）该（zhi）是（dao）我这边ncnn编译的问题，

Build command failed.
Error while executing process /home/zhihuan/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/zhihuan/code/NCNN1/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target ncnn_jni}
[1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libncnn_jni.so
FAILED: : && /home/zhihuan/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=armv7-none-linux-androideabi21 --gcc-toolchain=/home/zhihuan/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/home/zhihuan/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -std=c++11 -fopenmp -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libncnn_jni.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libncnn_jni.so CMakeFiles/ncnn_jni.dir/src/main/cpp/ncnn_jni.cpp.o  ../../../../src/main/jniLibs/armeabi-v7a/libncnn.a -ljnigraphics /home/zhihuan/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/21/liblog.so -latomic -lm && :
/home/zhihuan/ncnn-master/src/net.cpp:719: error: undefined reference to 'AAssetManager_open'
/home/zhihuan/ncnn-master/src/net.cpp:727: error: undefined reference to 'AAsset_close'
/home/zhihuan/ncnn-master/src/net.cpp:740: error: undefined reference to 'AAssetManager_open'
/home/zhihuan/ncnn-master/src/net.cpp:748: error: undefined reference to 'AAsset_close'
/home/zhihuan/ncnn-master/src/net.cpp:760: error: undefined reference to 'AAssetManager_open'
/home/zhihuan/ncnn-master/src/net.cpp:768: error: undefined reference to 'AAsset_close'
/home/zhihuan/ncnn-master/src/datareader.cpp:97: error: undefined reference to 'AAsset_seek'
/home/zhihuan/ncnn-master/src/datareader.cpp:98: error: undefined reference to 'AAsset_getBuffer'
/home/zhihuan/ncnn-master/src/datareader.cpp:116: error: undefined reference to 'AAsset_seek'
/home/zhihuan/ncnn-master/src/datareader.cpp:124: error: undefined reference to 'AAsset_read'
**_/home/zhihuan/code/NCNN1/app/src/main/cpp/ncnn_jni.cpp:63: error: undefined reference to 'ncnn::set_default_option(ncnn::Option const&)'_**
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by nihui** [comment]
参考 https://github.com/nihui/ncnn-android-mobilenetssd
