### ISSUE TITLE
mxnet2ncnn, model conversion is successful, but loading model is fail

### ISSUE THREAD

**Issue by simon5u** [Tencent/ncnn#2287]
Hi, I am using the latest ncnn to convert the model from mxnet to ncnn, model conversion is successful, but there is a segmentation fault error when loading the model. I attached the mxnet json and ncnn param for your reference. Please advise. Thanks.

[models.zip](https://github.com/Tencent/ncnn/files/5492530/models.zip)

**Comment by nihui** [comment]
Your mxnet model contains multiple ReLU node with identical "name_relu0" name.
Change the name so that each node has its unique name, and try again

**Comment by simon5u** [comment]
@nihui Thanks for the comment, it works! Cheers!
