### ISSUE TITLE
why is the number parameter 'c' of weight_data always 1?!

### ISSUE THREAD

**Issue by onepick** [Tencent/ncnn#229]
the variable 'c' means channels , but it is always 1, caffe2cnn didn't set it?

**Comment by nihui** [comment]
please provide more information about your problem.
eg. source file and code line

**Comment by onepick** [comment]
in convolution layer, the channel 'c' value of Mat weight_data(src/layer/convolution.h 49 line ) is always 1, when ssd-mobilenet runing

**Comment by nihui** [comment]
Mat weight_data is used as a plain vector, holding the weight data regardless of the layout.

**Comment by onepick** [comment]
oh, but did you notice that we could apply high proformace Matrix Mult to deal with the 1x1 convolution layer in mobileNet?

**Comment by nihui** [comment]
the dim of weight_data is the num_output, num_input, kernel_h, kernel_w，which are the parameters of convolution layer, or can be deduced from them.

**Comment by onepick** [comment]
thank you to your quick response, I noticed that,   I wana  pre-process weight_data in the function load_model(), so I issue this question. If you  can set the channels info when loading weight_data, it is perfect. I think lots of people also need it to improve the proformace.

**Comment by nihui** [comment]
yes, these parameters are always setted in load_model, since load_param is always called before it
