### ISSUE TITLE
请教一下怎么编译为VS工程

### ISSUE THREAD

**Issue by baiyecha** [Tencent/ncnn#23]
我在windows下如何利用VS进行源码学习？怎么编译？

**Comment by guozhongluo** [comment]
参考[](https://github.com/Tencent/ncnn/issues/12)

**Comment by guozhongluo** [comment]
参考[https://github.com/Tencent/ncnn/issues/12](url)

**Comment by guozhongluo** [comment]
这里有个vs2015的ncnn例子，可以直接运行
[](https://github.com/guozhongluo/ncnn-vs2015-examples-demo)

**Comment by AirFishWang** [comment]
请教一下在windows环境中该如何用Cmake编译出ncnn的vs工程，该如何配置？

**Comment by AirFishWang** [comment]
@guozhongluo 请教一下在windows环境中该如何用Cmake编译出ncnn的vs工程，该如何配置？

**Comment by nihui** [comment]
可参考wiki

https://github.com/Tencent/ncnn/wiki/cmake-VS2017-%E7%BC%96%E8%AF%91
