### ISSUE TITLE
windwos10下的vs2017的编译问题

### ISSUE THREAD

**Issue by byh1990** [Tencent/ncnn#2304]
windwos10下的vs2017的编译时遇到如下问题
错误如下：
CMake Error at CMakeLists.txt:148 (message):
The submodules were not downloaded! Please update submodules with "git
submodule update --init" and try again.
执行下面语句
git submodule update --init后，没有出现任何提示
继续执行ncnn的编译命令，依然是上面的错误，请问如何解决？谢谢官方的回复

**Comment by zchrissirhcz** [comment]
执行`git submodule update --init`成功的前提是，ncnn是通过git clone方式获取的（而不是.zip/.tar.gz压缩包下载的），并且是在ncnn根目录或子目录里执行的（而不能是外面的目录），并且不能是特别特别老的ncnn（早期没有glslang子模块）

**Comment by byh1990** [comment]
windows10利用vs2017的x64本机工具命令提示，git clone https://github.com/Tencent/ncnn.git 命令后，发现glslang文件夹下没有任何文件，是怎么回事？谢谢

**Comment by nihui** [comment]
推荐下载 github release 页面中的预编译包，或者 full-source.zip 编译
