### ISSUE TITLE
Normalize层不支持pack吗？

### ISSUE THREAD

**Issue by kobevaliant** [Tencent/ncnn#2308]
https://github.com/Tencent/ncnn/blob/7836a143ec69bc1fbd0397751af8f3bc4c1aa53e/src/layer/normalize.cpp#L48

我看到这里并没有考虑Mat的elempack情况，arm平台也没有定制的实现，有什么方法可以让它支持pack吗？还是我需要在这个操作之前手动转换布局？

**Comment by nihui** [comment]
不支持 packing 也是可以用的，会自动转换
