### ISSUE TITLE
InnerProduct目前版本只处理一行数据，将来是否计划改为输出1*height*num_output

### ISSUE THREAD

**Issue by Ma-Dan** [Tencent/ncnn#2318]
目前需要在外部调用的时候，手动分出原本输入到InnerProduct的每一行数据，然后将结果拼接起来。
InnerProduct的行为如果修改为 1 * height * width 输入， weight形状是[num_output, width]，输出为 [1, height, num_output]
这样外部调用就可以直接一次计算完成了。
这个修改会影响到一个operator的行为，所以咨询下是否计划这么做？虽然从计算上是增加一层循环，但是工作量还是非常大而且需要对每个平台的优化版本都进行这个修改。

**Comment by nihui** [comment]
现在有gemm，优化下就好了

**Comment by Ma-Dan** [comment]
gemm的计算是期望的过程，参与计算的是输入的2或3个矩阵，bias存放在bottom_blobs[2]里面(如果需要的话)。后续是考虑将gemm改为类似onnx的gemm那样含有weight和bias，还是将weight和bias作为constant层输入到gemm计算呢？

**Comment by nihui** [comment]
最新版本ncnn中，InnerProduct已支持二维输入的 gemm 计算
