### ISSUE TITLE
如何编译为MT，默认为MD，求救，困扰好几天了

### ISSUE THREAD

**Issue by Bruno-bai** [Tencent/ncnn#2324]
Windows下，编译release， 属性》c/c++》代码生成》运行库》多线程/MT
然后报错：
![mt](https://user-images.githubusercontent.com/20271020/99477817-3d91eb00-298e-11eb-8dac-2b65613615d4.jpg)

看样子，编译ncnn库时，默认是MD，然后与我现在的工程MT不匹配，然后在编译的时候，修改ncnn项目的cmakelists， 加上了这几行：

set(CMAKE_CXX_FLAGS_RELEASE "/MT")
set(CMAKE_CXX_FLAGS "/MT")
set(CMAKE_C_FLAGS_RELEASE "/MT")
set(CMAKE_C_FLAGS "/MT")

但是，还是不行，编译ncnn的时候，一直提示
![md](https://user-images.githubusercontent.com/20271020/99477944-8053c300-298e-11eb-8f25-19703cb8b5e0.jpg)
然后，编译我的项目时，还是提示MD，MT冲突，求问编译ncnn时，怎么改成MT呢？

**Comment by youzainn** [comment]
cmake 3.15 以上，开启NCNN_BUILD_WITH_STATIC_CRT即可

**Comment by Bruno-bai** [comment]
> cmake 3.15 以上，开启NCNN_BUILD_WITH_STATIC_CRT即可

确实可行，不过上面的编译protobuf的命令里面要设置为ON🤭
