### ISSUE TITLE
Support for the itself Python binding

### ISSUE THREAD

**Issue by rose-jinyang** [Tencent/ncnn#2329]
Hello
How are you?
Thanks for contributing this project.
I am going to use NCNN in Python.
Of course, https://github.com/caishanli/pyncnn supports this but it does not support the latest NCNN.
MNN supports Python binding in itself source.
I hope that u will support yourself Python binding to NCNN at the same time when NCNN is upgraded.
Thanks

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/pull/2383
