### ISSUE TITLE
onnx2ncnn: Unsupported squeeze axes 

### ISSUE THREAD

**Issue by leochan2009** [Tencent/ncnn#2331]
Hi,
When i try to convert the onnx model to ncnn using the following command,
../ncnn-build/tools/onnx/onnx2ncnn  test_complete2-sim.onnx test.param test.bin
this error happened:
Unsupported squeeze axes !
The ncnn model was generated anyhow. but it seems wrong.
here is the onnx model. in the last layer, there is a squeeze operator at axes=0.
![image](https://user-images.githubusercontent.com/10211992/99728499-84afd700-2a87-11eb-89b3-8995efa57271.png)

here is the generated ncnn model:
![image](https://user-images.githubusercontent.com/10211992/99728826-07d12d00-2a88-11eb-8d2e-65e65d9fd514.png)
the squeeze is disconnected from the lstm
Any suggestion? 
Thanks for the help in advance

Best,
Chen

**Comment by Ca0L** [comment]
See if this helps.
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#simplify-onnx-model

**Comment by leochan2009** [comment]
Hi,

thanks for the reply. The model is already simplified using the tool.
also the tool only simplifies Shape, Gather and Unsqueeze. not the squeeze operator.

**Comment by Ca0L** [comment]
Can you provide your test.param file?

**Comment by leochan2009** [comment]
Hi, 
the onnx and the converted bin and param files are attached. Thanks

[test.zip](https://github.com/Tencent/ncnn/files/5580791/test.zip)

**Comment by Ca0L** [comment]
![image](https://user-images.githubusercontent.com/21077373/99949711-73800680-2db6-11eb-8577-0afaae44cc1a.png)
If I am not mistaken, the input shape `[N, 30, 250, 250, 3]` means `[batch_size, seq_len, H, W, C]`?
ncnn only supports batch size == 1, dim `seq_len` in this case is not supported neither, see https://github.com/Tencent/ncnn/issues/1197

**Comment by leochan2009** [comment]
HI,

Thanks for the prompt reply. To fix the batch size issue, i can set the N =1 in the model.  However, you mentioned seq_len is not supported either? So LSTM with image input is basically not supported by NCNN?

**Comment by leochan2009** [comment]
the model in the attached file has batch_size=1 now. 
[test_batch_size_1.zip](https://github.com/Tencent/ncnn/files/5587023/test_batch_size_1.zip)
I think the issue is that in the onnx2ncnn tool, somehow certain squeeze axes is not supported:
https://github.com/Tencent/ncnn/blob/fb59eeb4c240fcffc49355751fd4384211b0e861/tools/onnx/onnx2ncnn.cpp#L3681

**Comment by Ca0L** [comment]
> HI,
> 
> Thanks for the prompt reply. To fix the batch size issue, i can set the N =1 in the model. However, you mentioned seq_len is not supported either? So LSTM with image input is basically not supported by NCNN?

I think the problem is not LSTM, but conv. ncnn's convolution only accepts one image at a time. https://github.com/Tencent/ncnn/blob/master/docs/developer-guide/operators.md#convolution

**Comment by leochan2009** [comment]
I see, thanks for the kind support!

**Comment by bibekyess** [comment]
Hi @leochan2009! I am also facing the similar error. Can I know how you resolved your issue?
![Screenshot 2024-01-18 at 8 06 29 PM](https://github.com/Tencent/ncnn/assets/86763456/81ed71ef-5988-40e3-9d58-6aeac8640fa0)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
