### ISSUE TITLE
Android下添加ncnnvulkan与opencv3.3.0出现的问题

### ISSUE THREAD

**Issue by if-time** [Tencent/ncnn#2332]
1、Android下ncnn测试成功；
2、链接ncnn后opencv的imwriter()提示undefined，但是在只链接opencv的情况下是可以正常使用的；
3、我通过fssst做追踪，是通过传递Bitmap到JNI然后转换成Mat使用，在未链接ncnn的时候，可以正常使用，链接ncnn后，报OOM
`cv::error(): OpenCV Error: Insufficient memory (Failed to allocate 16078104 bytes) in void* cv::OutOfMemoryError(size_t), file E:\downProject\build-opencv-for-android-master\opencv\sources\modules\core\src\alloc.cpp, line 55
cv::error(): OpenCV Error: Assertion failed (u != 0) in void cv::Mat::create(int, const int*, int), file E:\downProject\build-opencv-for-android-master\opencv\sources\modules\core\src\matrix.cpp, line 436`

**Comment by nihui** [comment]
可以试试 https://github.com/nihui/opencv-mobile
这是个精简版 opencv，比较适合资源受限的平台
如有问题，可reopen issue继续交流
