### ISSUE TITLE
Question ： How to read and understand .param file ?

### ISSUE THREAD

**Issue by wwdok** [Tencent/ncnn#2339]
Hi, as we know, .param can be opened by Netron to visualize the network structure, but i find i can open .param with VSCode too, below is an example: 
![image](https://user-images.githubusercontent.com/43233772/99870051-f95f4e80-2c0a-11eb-9d78-b644651d5edb.png)
I am curious about what each column means, if you could add a wiki documentation about this, that would be very nice , thanks !

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure

**Comment by wwdok** [comment]
Great, it has been already there ！
