### ISSUE TITLE
example request: could you provide an example of feature extraction

### ISSUE THREAD

**Issue by coollofty** [Tencent/ncnn#2340]
I have this requirement in the project. For example, I need to directly use the features of VGG for other calculations, and ncnn has a good underlying optimization, so I hope that ncnn can have an example that does not train or derive the model but only solves the features extraction, thank you :)

**Comment by paklau99988** [comment]
Is found same here: 
https://github.com/QuantScientist/ncnnRay/blob/main/src/models/resnet50.cpp

**Comment by coollofty** [comment]
> Is found same here:
> https://github.com/QuantScientist/ncnnRay/blob/main/src/models/resnet50.cpp

Thanks ^_^
