### ISSUE TITLE
ModelBin read index_array failed 2642

### ISSUE THREAD

**Issue by siweimaodou** [Tencent/ncnn#2352]
使用最新的ncnn, 将nanodet pytorch模型转onnx->sim->ncnn->opt  执行ncnnoptimize出现如下错误。
ModelBin read index_array failed 2642
layer load_model 22 failed
Segmentation fault

不执行ncnnoptimize时，使用demo_ncnn加载模型，检测结果中，score很多为1，检测结果不对。

**Comment by siweimaodou** [comment]
可以关了，好像是我模型用错了

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
