### ISSUE TITLE
不同版本的NCNN的输出结果有差别？

### ISSUE THREAD

**Issue by whattheweather** [Tencent/ncnn#2356]
输入：
同一张图片

模型：
同一个onnx文件

模型转换：
同一个onnx2ncnn

输出：
old -0.264222 -0.331496 -0.144931 0.474687 
new -0.245483 -0.273926 -0.151733 0.556152

其中old使用的是2020.2.23的提交编译的结果，new使用的是2020.11.26的提交编译的结果。数值是在小图上的结果的差异，放大回原图就会相差很多

**Comment by whattheweather** [comment]
将CMakeLists.txt中的option(NCNN_ARM82 "optimize aarch64 platform with armv8.2" ON)改为option(NCNN_ARM82 "optimize aarch64 platform with armv8.2" OFF)即可

**Comment by nihui** [comment]
```
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
```
关闭fp16存储和运算

**Comment by whattheweather** [comment]
> ```
> net.opt.use_fp16_storage = false;
> net.opt.use_fp16_arithmetic = false;
> ```
> 
> 关闭fp16存储和运算

有效，谢谢！
