### ISSUE TITLE
ncnn 在window10的自带linux20.04内核上编译 存在问题。。。

### ISSUE THREAD

**Issue by sxj731533730** [Tencent/ncnn#2364]
ake[1]: *** [CMakeFiles/Makefile2:378: examples/CMakeFiles/yolact.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
examples/CMakeFiles/retinaface.dir/build.make:83: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:405: examples/CMakeFiles/retinaface.dir/all] Error 2
examples/CMakeFiles/simplepose.dir/build.make:83: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:432: examples/CMakeFiles/simplepose.dir/all] Error 2
examples/CMakeFiles/squeezenet.dir/build.make:83: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:459: examples/CMakeFiles/squeezenet.dir/all] Error 2
examples/CMakeFiles/mobilenetssd.dir/build.make:83: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:486: examples/CMakeFiles/mobilenetssd.dir/all] Error 2
examples/CMakeFiles/peleenetssd_seg.dir/build.make:83: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:513: examples/CMakeFiles/peleenetssd_seg.dir/all] Error 2

我发现一个问题，当我使用window10 的linux 内核编译ncnn 就会出现这个问题 ，但是在ubuntu系统 就没有问题。。谁能解释一下吗？

**Comment by zchrissirhcz** [comment]
Tested on Ubuntu 20.04.1 LTS on Window WSL2.

gcc/g++ version: 9.3.0

opencv version: `sudo apt installed libopencv-dev`, 4.2.0

Compile commands:
```
mkdir -p ~/work && cd work
git clone https://github.com/tencent/ncnn
cd ncnn && mkdir build && cd build
cmake .. && make -j2
```

Build output:
```
...

Scanning dependencies of target ncnnoptimize
[ 97%] Building CXX object tools/CMakeFiles/ncnnoptimize.dir/ncnnoptimize.cpp.o
[ 97%] Built target mobilenetv2ssdlite
Scanning dependencies of target ncnn2mem
[ 97%] Building CXX object tools/CMakeFiles/ncnn2mem.dir/ncnn2mem.cpp.o
[ 97%] Built target squeezenetssd
Scanning dependencies of target ncnn2int8
[ 98%] Linking CXX executable shufflenetv2
[ 99%] Building CXX object tools/quantize/CMakeFiles/ncnn2int8.dir/ncnn2int8.cpp.o
[100%] Linking CXX executable ncnn2mem
[100%] Built target shufflenetv2
Scanning dependencies of target ncnn2table
[100%] Building CXX object tools/quantize/CMakeFiles/ncnn2table.dir/ncnn2table.cpp.o
[100%] Built target ncnn2mem
[100%] Linking CXX executable ncnn2int8
[100%] Built target ncnn2int8
[100%] Linking CXX executable ncnnoptimize
[100%] Built target ncnnoptimize
[100%] Linking CXX executable ncnn2table
[100%] Built target ncnn2table
```


@sxj731533730 如果有指定cmake参数，或别的版本的gcc/g++/clang、opencv等，可以贴一下。我这里用默认的版本编译，没有问题。
