### ISSUE TITLE
GlobalPool输出数据shape不正确

### ISSUE THREAD

**Issue by runrunrun1994** [Tencent/ncnn#2369]
在使用ncnn的过程中，发现经过GlobalPool输出数据shape不正确，比如输入格式为whc, shape为(30,30,160)的数据，经过GlobalPool之后输出shape应该为(1,1,160)，而ncnn中输出的shape为(160,1,1)。问题来源于[top_blob.create(channels, elemsize, opt.blob_allocator);](https://github.com/Tencent/ncnn/blob/master/src/layer/pooling.cpp#L60)，需要使用`top_blob = top_blob.reshape(1, 1, channels, opt.blob_allocator);`将top_blob的shape由（160,1,1）转换为（1,1,160）输出shape才正确。

**Comment by nihui** [comment]
ncnn中的 global pooling 输出一维就是这样设计的，对于后面的 innerproduct 或者 binaryop 效率更高

**Comment by runrunrun1994** [comment]
那需要维持 global pooling三维shape的模型可能出现结果不对情况，最近我在转deeplabv3+模型的时候就发现，经过 global pooling之后的结果不正确，后来用两种方法解决了。1.修改.param文件，将global pooling替换成kernel size等于feature map大小的pooling；或者2.使用上面说的将top_blob reshape一下。up有没有考虑兼容一下这种情况？
![ASSP](https://user-images.githubusercontent.com/58387777/100560207-1ae9c580-32f0-11eb-9d6a-08dca68c4a97.png)

**Comment by nihui** [comment]
请提供下 onnx 文件，可以做成兼容的

**Comment by runrunrun1994** [comment]
算法使用来用人像分割的，onnx下载路径：https://share.weiyun.com/rCwditHt，其中deeplab_mobilenetv2_0.5_sim_modify.param是我修改过后的.param文件，测试用图。谢谢up!
![timg](https://user-images.githubusercontent.com/58387777/100563810-4d002500-32fa-11eb-95d4-8f881df91807.jpg)

**Comment by runrunrun1994** [comment]
算法是用来做人像分割的，onnx下载地址：[https://share.weiyun.com/rCwditHt](https://share.weiyun.com/rCwditHt)，其中deeplab_mobilenetv2_0.5_sim_modify.param是修改过后的.param文件。谢谢up！测试图如下：
![timg](https://user-images.githubusercontent.com/58387777/100564068-e3cce180-32fa-11eb-85fa-169e644233d2.jpg)

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/3fcd44cf995777c37678a6ce1ecd8ea865d3b15a
改善 Interp 层兼容性

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
