### ISSUE TITLE
Expand not supported yet!

### ISSUE THREAD

**Issue by CheungBH** [Tencent/ncnn#2370]
Hello. I was transforming a model including SE module to ncnn, and a warning occur: 

**Expand not supported yet!**

Despite error, the target model ".param" and ".bin" are still exported. 
I wonder whether it is normal, or models containing SE modules are not supported?

**Comment by nihui** [comment]
hi, please provide your onnx file and I will fix it asap  :D

**Comment by CheungBH** [comment]
https://drive.google.com/file/d/1O9nPvwkgDvIRi5EeBdOA_BD4vDTuLfAr/view?usp=sharing
Here's the model. The model is a little big, and I have to transmit it by Google drive

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/a260a19619c4006071f6ad94504cee45219209dc

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
