### ISSUE TITLE
onnx2ncnn处理模型后，Gemm与前后层连接断开

### ISSUE THREAD

**Issue by cruiceble** [Tencent/ncnn#2371]
![image](https://user-images.githubusercontent.com/6071188/100563027-5ab4ab00-32f8-11eb-8040-9a467e907053.png)
此处的Gemm对应的onnx中的算子是matmul
![image](https://user-images.githubusercontent.com/6071188/100563201-cdbe2180-32f8-11eb-8675-381c1ed8d460.png)
但是转换后Gemm与上下断开
![image](https://user-images.githubusercontent.com/6071188/100563286-04943780-32f9-11eb-91ce-a317fcaf4ace.png)

**Comment by nihui** [comment]
你的onnx是pytorch转换来的吗？

**Comment by cruiceble** [comment]
是的~

**Comment by cruiceble** [comment]
![image](https://user-images.githubusercontent.com/6071188/100565690-1d075080-32ff-11eb-8b78-d55a7a75087c.png)
理论上应该是这样？

**Comment by nihui** [comment]
请提供下 onnx 文件

**Comment by cruiceble** [comment]
链接：https://pan.baidu.com/s/1aeDmQA-Z1T7n9RikZmzeYA 
提取码：31pi

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/14ba69803452b7626a473e668c699c034b5081b0

**Comment by cruiceble** [comment]
感谢up大大~

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
