### ISSUE TITLE
confusion about `unary_op_abs`

### ISSUE THREAD

**Issue by zchrissirhcz** [Tencent/ncnn#2372]
functor定义：
```C++
struct unary_op_abs
{
    float operator()(const float& x) const
    {
        return abs(x);
    }
};
```

std::abs原型：
```c++
int       abs( int n );
```

`unary_op_abs`的目的是截断为int类型吗？

**Comment by nihui** [comment]
https://en.cppreference.com/w/cpp/numeric/math/fabs

**Comment by zchrissirhcz** [comment]
`unaryop_arm.cpp`用了`#include <math.h>`，里面对abs函数的声明，和`<cmath>`不太一样。

**Comment by zchrissirhcz** [comment]
https://github.com/Tencent/ncnn/blob/master/.github/workflows/android-armv8-gpu.yml

ci上 android-armv8-gpu 用的ndk-r16b。这样的话确实是有编译警告的，类似：

```
 warning: using integer absolute value function 'abs' when argument is of floating point type [-Wabsolute-value]
        return abs(x);

note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
```

**Comment by zchrissirhcz** [comment]
ndk-r16b有warning，ndk-r17b没有warning，我觉得ci上改成r17b，或者 `#include <math.h>`改`#include <cmath>`

**Comment by nihui** [comment]
或者来个 pr，改成 fabs()

**Comment by zchrissirhcz** [comment]
好的，整一个PR。

**Comment by nihui** [comment]
谢谢！
