### ISSUE TITLE
param is too old, please regenerate (faster-rcnn 运行失败)

### ISSUE THREAD

**Issue by Arthur-Shi** [Tencent/ncnn#238]
按照注释下载文件,然后重命名.    faster_rcnn_test.pt改成ZF_faster_rcnn_final.proto 还有一个改成bin文件.
 // original pretrained model from https://github.com/rbgirshick/py-faster-rcnn
    // py-faster-rcnn/models/pascal_voc/ZF/faster_rcnn_alt_opt/faster_rcnn_test.pt
    // https://dl.dropboxusercontent.com/s/o6ii098bu51d139/faster_rcnn_models.tgz?dl=0
    // ZF_faster_rcnn_final.caffemodel
    fasterrcnn.load_param("ZF_faster_rcnn_final.proto");
    fasterrcnn.load_model("ZF_faster_rcnn_final.bin");

但是运行依旧失败
param is too old, please regenerate
find_blob_index_by_name data failed
find_blob_index_by_name im_info failed
find_blob_index_by_name conv5 failed
find_blob_index_by_name rois failed

我该怎么做尼?

**Comment by nihui** [comment]
参考 wiki 上的使用指南，用 caffe2ncnn 工具转换模型后加载

**Comment by Arthur-Shi** [comment]
万分感谢!

**Comment by jjjjohnson** [comment]
@nihui 大神 我用了 最近的caffe2ncnn工具转换在ios上后依然报错
param is too old, please regenerate
o(╥﹏╥)o
这个caffe的模型太老了吗？
https://github.com/ElegantGod/ncnn/tree/master/mtcnn

**Comment by weilanShi** [comment]
> 参考 wiki 上的使用指南，用 caffe2ncnn 工具转换模型后加载

我在将fasterrcnn的zf模型用caffe2ncnn转换后，生成param和bin文件，在pc上测试fasterrcnn时，报如下错误：find_blob_index_by_name im_info failed 段错误 (核心已转储)，请问fasterrcnn的test.prototxt文件的开头输入部分按照下面这样改，正确吗？


layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param {shape {dim: 1 dim: 3 dim: 224 dim: 224  } } }


layer {
  name: "im_info"
  type: "Input"
  top: "data"
  input_param {shape { dim: 1 dim: 3 } } }
