### ISSUE TITLE
[Feature Request] AVX2 dispatch

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#2380]
Right now, as a user of the library, I either build the library with avx2 support or without (by setting the `NCNN_AVX2` cmake flag). If I try to run avx2 library on a cpu that doesn't support these instructions, it crashes. 

It would be great to have avx2 dispatch, meaning that ncnn is always built with AND without avx2 support, but it only uses avx2 instructions when the CPU supports them, similar to what OpenCV has done with their CPU dispatch: https://github.com/opencv/opencv/wiki/CPU-optimizations-build-options

**Comment by nihui** [comment]
Runtime dispatching is already there.
build ncnn library with -DNCNN_RUNTIME_CPU=ON

**Comment by cyrusbehr** [comment]
Awesome, would I also need to set the `NCNN_AVX2` flag? Or is setting `-DNCNN_RUNTIME_CPU=ON` all I need to do (and it will choose avx2 when available)?

**Comment by nihui** [comment]
> Awesome, would I also need to set the `NCNN_AVX2` flag as well? Or is setting `-DNCNN_RUNTIME_CPU=ON` all I need to do (and it will choose avx2 when available)?

both cmake options are enabled by default, actually you don't need to specify anything and it will work
