### ISSUE TITLE
安装ncnn时候报错，‘__m128 activation_ps(__m128, int, const ncnn::Mat&)’ conflicts with a previous declaration

### ISSUE THREAD

**Issue by woshifzh** [Tencent/ncnn#2388]
我的系统是centos7, 前置依赖已经按照说明安装了，
编译报错信息如下：

[ 51%] Building CXX object src/CMakeFiles/ncnn.dir/layer/x86/convolution_x86_avx2.cpp.o
In file included from /home/luban/ncnn/src/layer.h:19:0,
                 from /home/luban/ncnn/src/layer/convolution.h:18,
                 from /home/luban/ncnn/build/src/layer/x86/convolution_x86_avx2.h:18,
                 from /home/luban/ncnn/build/src/layer/x86/convolution_x86_avx2.cpp:15:
**/home/luban/ncnn/src/modelbin.h:51:7: 错误：‘__m128 activation_ps(__m128, int, const ncnn::Mat&)’ conflicts with a previous declaration
 class ModelBinFromMatArray : public ModelBin**
       ^
In file included from /home/luban/ncnn/build/src/layer/x86/convolution_x86_avx2.cpp:24:0:
/home/luban/ncnn/src/layer/x86/avx_activation.h:59:22: 附注：previous declaration ‘__m256 activation_ps(__m256, int, const ncnn::Mat&)’
 static inline __m256 activation_ps(__m256 _v, int activation_type, const ncnn::Mat& activation_params)
                      ^
In file included from /home/luban/ncnn/build/src/layer/x86/convolution_x86_avx2.cpp:19:0:
/home/luban/ncnn/src/layer/x86/sse_activation.h:59:22: 附注：-fabi-version=6 (or =0) avoids this error with a change in mangling
 static inline __m128 activation_ps(__m128 _v, int activation_type, const ncnn::Mat& activation_params)
                      ^
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/x86/convolution_x86_avx2.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] 错误 2
make: *** [all] 错误 2

没有搜到类似错误信息，请问应该怎么处理？

**Comment by lingyi-learning** [comment]
请问解决了吗？我也遇到了

**Comment by woshifzh** [comment]
> 请问解决了吗？我也遇到了

没解决。但是我按指引在mac上安装是成功的。现在不确定是啥问题。

**Comment by nihui** [comment]
已复现

**Comment by nihui** [comment]
更新下代码，已修复
