### ISSUE TITLE
shadowed variables

### ISSUE THREAD

**Issue by zchrissirhcz** [Tencent/ncnn#2390]
Hi NiHui

When compile ncnn library for x86 Linux, with strict compilation option checking, it fails with:
```
/home/zz/work/ncnn/src/mat.h:955:34: error: declaration shadows a field of 'ncnn::Mat' [-Werror,-Wshadow]
inline Mat Mat::clone(Allocator* allocator) const
                                 ^
/home/zz/work/ncnn/src/mat.h:277:16: note: previous declaration is here
    Allocator* allocator;
               ^
1 error generated.
```

It's valid to use shadowed variables, but I think it may cause conflict, or make people confusing. Change variable names, which avoid variable shadowing, I recommend.

**Comment by zchrissirhcz** [comment]
Thus I created an PR
https://github.com/Tencent/ncnn/pull/2391

**Comment by nihui** [comment]
merged

Thanks !
