### ISSUE TITLE
example里的Yolov5.cpp 可以在Ubuntu服务器上使用GPU运行吗？

### ISSUE THREAD

**Issue by yao-zheng-yi** [Tencent/ncnn#2397]
我在example的yolov5.cpp里设置了
`yolov5.opt.use_vulkan_compute = true;
ncnn::Extractor ex = yolov5.create_extractor();
 ex.set_vulkan_compute(true);`
但是在运行时，显示 set_vulkan_compute failed, network use_vulkan_compute disabled. 并且使用nvidia-smi查看GPU使用情况，没有发现程序在占用GPU运行。
请问该如何设置呢？

**Comment by nihui** [comment]
set ```net.opt.use_vulkan_compute = true;``` before loading param and model

**Comment by yao-zheng-yi** [comment]
没有再显示 set_vulkan_compute failed, network use_vulkan_compute disabled.
但是使用nvidia-smi查看GPU使用情况，还是没有发现程序在占用GPU运行，请问这是什么原因？ @nihui

**Comment by yao-zheng-yi** [comment]
> set `net.opt.use_vulkan_compute = true;` before loading param and model

我尝试加入代码
if (ncnn::get_gpu_count() != 0) {
    	yolov5.opt.use_vulkan_compute = true;
    	printf("use_vulkan\n");
}
但是并没有输出use_vulkan，找不到GPU，请问这该如何修改？

**Comment by nihui** [comment]
可能是显卡驱动没有安装好，vulkan sdk 里的 vulkaninfo 工具可以查看信息
重装下显卡驱动，要把 opengl 等功能也装上

**Comment by nihui** [comment]
如有问题，请reopen继续交流
