### ISSUE TITLE
在转yolo5.pt---onnx---ncnn遇到的问题

### ISSUE THREAD

**Issue by sxj731533730** [Tencent/ncnn#2398]
参考https://github.com/ultralytics/yolov5/issues/251这个转了 onnx 格式 ，下一步转ncnn 出现问题
注（使用的模型为yolov5l.pt）

./onnx2ncnn ../../../../yolov5/models/yolov5l.onnx ./../../../yolov5/models/yolov5l-smi.param ../../../../yolov5/models/yolov5l-smi.bin
Segmentation fault (core dumped)

**Comment by lengxia** [comment]
you solved？
i have got same

**Comment by troymaple** [comment]
same problem too

**Comment by nihui** [comment]
update the latest onnx2ncnn code
or export onnx file with opset_version=11

**Comment by sxj731533730** [comment]
OK copy it xiaojin sui 邮箱：sxj731533730@gmail.com 签名由 网易邮箱大师 定制 在2021年01月08日 17:17，nihui 写道： update the latest onnx2ncnn code or export onnx file with opset_version=11 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
