### ISSUE TITLE
extractor can't be used as single instance

### ISSUE THREAD

**Issue by Pinnh** [Tencent/ncnn#242]
when I modified the source code of Extractor's constructor to public in order to make extractor single instance, but I got wrong result when  invoke extractor greater than 2 times.

is there any way to resolve it? thanks.

**Comment by nihui** [comment]
you shall always create a new Extractor instance for each inference by design.
It is sufficient to create a single shared Net instance for reusing network model graph in most usecases.

**Comment by Pinnh** [comment]
OK thanks for your reply any way.
