### ISSUE TITLE
ShufflenetV2模型pytorch-->onnx-->ncnn结果精度丢失严重

### ISSUE THREAD

**Issue by Z-Xiong** [Tencent/ncnn#2424]
使用pytorch的shufflenetV2预训练模型训练了一个二分类模型，经测试pytorch模型输出与onnx、onnx-sim的模型输出基本相同，在ncnn上精度丢失严重。
pytorch使用PIL读入图片，使用默认归一化方法：
```
transform = tfs.Compose([
    tfs.Resize([224,224]),
    tfs.ToTensor(),
    tfs.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225])
])
```
ncnn使用归一化参数：
```
const float INPUT_MEAN[3] = {0.485f*255.f, 0.456f*255.f, 0.406f*255.f};
const float INPUT_STD[3] = {1/0.229f/255.f, 1/0.224f/255.f, 1/0.225f/255.f};
ncnn::Mat in = ncnn::Mat::from_pixels_resize(input_image.data, ncnn::Mat::PIXEL_BGR2RGB, input_image.cols, input_image.rows, 224, 224);
in.substract_mean_normalize(INPUT_MEAN, INPUT_STD);
```
[模型文件链接：](https://github.com/Z-Xiong/model)，包含原始pytorch模型，onnx模型，onnx-sim模型以及ncnn模型

**Comment by nihui** [comment]
使用预先resize好的 224x224 的 bmp 格式图片试试看

https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result

**Comment by Z-Xiong** [comment]
> 
> 
> 使用预先resize好的 224x224 的 bmp 格式图片试试看
> 
> https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result

谢谢up的及时回答，我又仔细调试了下，发现是我在输入nccn前做了这样的操作：
`bgr.convertTo(bgr,CV_32FC3);`
导致精度下降严重。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
