### ISSUE TITLE
nanodet无法识别任何东西

### ISSUE THREAD

**Issue by timaker** [Tencent/ncnn#2428]
测试了nanodet例子，用了很多图片测试，包含yolo提供的图像，都检测不出人，狗，车之类的

**Comment by nihui** [comment]
ncnn example 中的 nanodet 例子是动态size输入的，原始 nanodet_m.param 需要修改才能用，也可以用这里的模型
https://github.com/nihui/ncnn-assets/tree/master/models

**Comment by mojiayuan** [comment]
@nihui 我看了您v5如何修改动态输入，但我改了nanodet中的param,只能在nanodet原作者的ncnn代码运行，在example/yolov5.cpp的代码运行会出现一堆密密麻麻的框，请问下是如何修改param作为动态输入

**Comment by nihui** [comment]
你可以看看 ncnn-assets 里的 param 和原始 nanodet param 的区别，主要区别在 Interp 改为按 scale 缩放

**Comment by mojiayuan** [comment]
> 你可以看看 ncnn-assets 里的 param 和原始 nanodet param 的区别，主要区别在 Interp 改为按 scale 缩放

我看了 ncnn-assets 里的 param和原始 nanodet param，共修改了4处Interp ， param和原始 nanodet param第一处到第四处Interp的参数：  0=2 3=20 4=20，0=2 3=40 4=40，0=2 3=20 4=20，0=2 3=10 4=10，而ncnn-assets 里的 param里Interp是：0=2 1=2.0 2=2.0，0=2 1=2.0 2=2.0，0=2 1=0.5 2=0.5，0=2 1=0.5 2=0.5，为什么这前两个是按scale2.0来进行缩放w,h的,后两个是按scale0.5？

**Comment by liuwei3612** [comment]
@nihui 您好，自己的训练的模型也只要改Interp吗？

**Comment by liuwei3612** [comment]
@nihui 您好，请问怎样才能转换成和ncnn-assets里面的一样呢？

**Comment by mojiayuan** [comment]
> @nihui 您好，请问怎样才能转换成和ncnn-assets里面的一样呢？

我的改了param第一处到第四处Interp的参数： 0=2 3=20 4=20，0=2 3=40 4=40，0=2 3=20 4=20，0=2 3=10 4=10，改为0=2 1=2.0 2=2.0，0=2 1=2.0 2=2.0，0=2 1=0.5 2=0.5，0=2 1=0.5 2=0.5就可以了
