### ISSUE TITLE
iOS 集成ncnn bitcode的framework，上传到app store报错

### ISSUE THREAD

**Issue by zhfwch** [Tencent/ncnn#2432]
报错详细信息：
> ITMS-90562: Invalid Bundle - The app cannot be processed because options not allowed to be embedded in bitcode are detected in the submission. It is likely that you are not building the app with the toolchain provided in Xcode. Rebuild your entire app with the latest GM Xcode and submit the app again.

依照网上解决方案[bitcode ITMS-90562: Invalid Bundle](https://easeapi.com/blog/blog/104-invalid-bundle.html)无效。暂时用非bitcode打包上传到app store。

烦请后续版本解决一下。谢谢！

**Comment by nihui** [comment]
尝试最新的release，是用xcode编译的
