### ISSUE TITLE
Does ncnn support NXP series chips?

### ISSUE THREAD

**Issue by yufeilongyuan** [Tencent/ncnn#2434]
Hello, does ncnn support **NXP** series chips? If yes, are there any relevant cases? If not, can you provide an idea? What I can think of now is that **NXP** series chips are also based on **ARM**. Can the source code be embedded into my code and then compiled. thank you.

**Comment by nihui** [comment]
ncnn should compile and work out of box on any ARM chips

**Comment by yufeilongyuan** [comment]
OK, which one should I use to cross compile tool chains? For NXP series chips.

**Comment by nihui** [comment]
Normally, you shall get the toolchain from your vendor

**Comment by yufeilongyuan** [comment]
OK，I seem to know what to do. Thank you for your reply.
