### ISSUE TITLE
ncnn可以支持SOLOV2吗

### ISSUE THREAD

**Issue by junqiCao** [Tencent/ncnn#2441]
@nihui，前段时间研究了一些ncnn调用yolact模型，但是发现yolact模型有检测泄露，能不能搞一下ncnn调用SOLOV2?

**Comment by junqiCao** [comment]
@nihui, 最近有没有开发这个需求的打算呢？

**Comment by junqiCao** [comment]
@nihui, 最近有开发ncnn调用SOLOV2的想法吗？

**Comment by nihui** [comment]
https://github.com/aim-uofa/AdelaiDet/tree/master/onnx

**Comment by chingi071** [comment]
@nihui 請問這是指 SOLOV2 可以轉換為 .bin, .param 的意思嗎? 另外我想請問一下是否有 SOLOV2 inference 的 cpp 檔呢? 非常謝謝您。

**Comment by nihui** [comment]
https://github.com/DayBreak-u/SOLOV2_ncnn

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
