### ISSUE TITLE
多版本caffe转ncnn模型不兼容问题

### ISSUE THREAD

**Issue by qyxqyx** [Tencent/ncnn#245]
请问一下，我这里有两个版本的ncnn，一个是前几天clone的，另一个可能是三四个月前的版本，现在的问题是：
    之前用caffe训好的mtcnn在老版本ncnn上是调通了的，现在我用新版caffe2ncnn，并把之前caffe版的mtcnn模型移到新版ncnn上时，mtcnn的输出是错的，我应该怎么解决呢。
麻烦楼主解答一下，谢谢！

**Comment by nihui** [comment]
最新的ncnn，innerproduct输出是连续的了
所以以前 float prob = out.channel(j)[0] 的写法可能要改成 float prob = out[j]
mtcnn里的 rnet onet
