### ISSUE TITLE
NCNN运行 LSTM模型跑forward维度不对

### ISSUE THREAD

**Issue by zhangting9756** [Tencent/ncnn#2451]
输入为
float x[5*8]=
    {
    	{2836.8036,2847.3198,2848.9965,2831.9281,-9.7437,-0.3423,198149343.0,227934395.7},
    	{2846.2217,2838.2072,2861.9241,2820.1455,9.4181,0.332,207546019.0,239234260.6},
    	{2852.3512,2835.584,2855.3756,2829.6271,6.1295,0.2154,206792804.0,233798996.6},
    	{2915.4311,2871.9641,2917.1508,2871.9641,63.0799,2.2115,260196050.0,307416215.1},
    	{2921.398,2916.3168,2926.3588,2909.1277,5.9669,0.2047,256108049.0,294402745.9}

	};
    ncnn::Mat m(8,5,(void*)x,sizeof(float),0);
batch size为1，onnx模型见附件

**经过第一层LSTM之后，输出的blob维度dims=2，w=64，h=5与预期不符**
进行第一层计算的时候调用的是ncnn-master/build-andriod-aarch64/src/layer/arm/lstm_arm_arm82.cpp 中的forward函数

在第二层进行permute运算时（调用permute.cpp中的forward），**由于输入第二层的维度dims=2，w=64，h=5但是获取到的order_type为2导致直接返回0**，输出的维度都为0，导致出错

麻烦帮忙解决下，谢谢！
![onnx模型架构](https://user-images.githubusercontent.com/45795850/102091498-ddda1300-3e59-11eb-92df-cb3e7a400b61.jpg)
![onnx模型参数](https://user-images.githubusercontent.com/45795850/102091517-e3cff400-3e59-11eb-8932-618d8784a00d.jpg)

**Comment by Ca0L** [comment]
如果是双向，ncnn 的 LSTM 会把两个方向的输出拼接到一起，所以 w 才会等于 64，可以把第一个 LSTM 后面的 permute 和 reshape 都删了，在你的 onnx 里这两个操作本来也是把两个方向的输出拼到一起。

**Comment by nihui** [comment]
楼上说的对
另外，最新的onnx2ncnn转换器会自动删除不需要的 permute reshape

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
