### ISSUE TITLE
Is ncnn support nn.embedding in pytorch?

### ISSUE THREAD

**Issue by Songyima** [Tencent/ncnn#2457]
I have converted my pytorch model to onnx and simplified it by onnx-simplifier. However, there still a GATHER op which refers to nn.embedding in pytorch. Hence, I failed to run onnx2ncnn.

In fact, my model is used in an NLP task, I wonder if ncnn doesn't support NLP well.

**Comment by Songyima** [comment]
[dwcnn.zip](https://github.com/Tencent/ncnn/files/5700495/dwcnn.zip)
This is my onnx file converted from pytorch

**Comment by jxt1234** [comment]
Use mnn you can get correct result: https://github.com/alibaba/MNN

**Comment by nihui** [comment]
embedding is supported via pnnx, see https://github.com/Tencent/ncnn/tree/master/tools/pnnx

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
