### ISSUE TITLE
find_blob_index_by_name 3108 failed

### ISSUE THREAD

**Issue by cavalleria** [Tencent/ncnn#2469]
这个模型跑ncnn报错这个错是啥原因啊
`find_blob_index_by_name 3108 failed
find_blob_index_by_name 3109 failed
find_blob_index_by_name 3110 failed
find_blob_index_by_name 3111 failed
find_blob_index_by_name 3112 failed
find_blob_index_by_name 3113 failed
find_blob_index_by_name 3114 failed
find_blob_index_by_name 3115 failed
find_blob_index_by_name 3116 failed
find_blob_index_by_name 3117 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed
find_blob_index_by_name output1 failed
find_blob_index_by_name output2 failed
find_blob_index_by_name output3 failed`
[模型文件](https://drive.google.com/file/d/1jsJ-LuF18wGJzb9ZmzzxPCA_xd8K22mY/view?usp=sharing)

**Comment by nihui** [comment]
用 netron 打开 param，找到 blob name

**Comment by cavalleria** [comment]
我看了netron中blob_name，如图所画的这部分是id从3108到3117，看起来没啥问题呀
<img width="760" alt="截图" src="https://user-images.githubusercontent.com/13869178/102442661-e56b0900-405f-11eb-85b7-fdac79763bad.png">

**Comment by nihui** [comment]
是不是 load_param load_model 文件路径写错了？

**Comment by cavalleria** [comment]
确认应该不是的，这个文件跑ncnnoptimize和benchncnn都报这个错

**Comment by TomatoBoy90** [comment]
使用ncnn2mem转化成xxx.id.h和xxx.mem.h就可以解决

**Comment by liguoyu666** [comment]
> 使用ncnn2mem转化成xxx.id.h和xxx.mem.h就可以解决

你好，请问转换后，输入输出该怎么写啊　https://github.com/Tencent/ncnn/issues/2967
