### ISSUE TITLE
Eltwise layer change topblob dims if bottom dims != 3

### ISSUE THREAD

**Issue by harhar539** [Tencent/ncnn#2473]
![image](https://user-images.githubusercontent.com/37204312/102453384-14d94000-4077-11eb-8bf6-882dcf624119.png)
like part of the model struct above,  
POOLING: input (7,7,576,(dims ==3)) -->pooling(global ave pooling)-->output(576,1,1 (**dims == 1**)) 
Eltwise: input A(576,1,1 (dims == 1))  input B(576,1,1(dims == 1))-->eltwise(PROD)---->output(72,1,8 (**dims == 3**))
![image](https://user-images.githubusercontent.com/37204312/102454296-c167f180-4078-11eb-95a1-ea6ffdfbd209.png)
Because forward func of eltwise create output blob with dims == 3.
The change of shape of output blob from eltwise layer will cause error in the following layers forwarding.
This model will not cause error in caffe, since caffe **does not change output dims** in **global pooling layer**

**Comment by nihui** [comment]
Thanks for your issue report !
