### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by xidianzhuxi** [Tencent/ncnn#2476]
on my jetsonNano，when i finishded install NCNN and run the fllow command to test:
`../build/examples/squeezenet ../images/256-ncnn.png`
and i will get the next output:
![image](https://user-images.githubusercontent.com/40211659/102587510-ea56b800-4146-11eb-804c-cf897bcbb852.png)
run another test command ,after i got a correct result will also raise a error:
![image](https://user-images.githubusercontent.com/40211659/102587694-41f52380-4147-11eb-8c10-3e7aea8b5177.png)
what is the problem?

**Comment by ghimiredhikura** [comment]
I also got the same error 
@nihui, can you please give some suggestions?

**Comment by Eleanor456** [comment]
also got the same error， what can I do to solve this problem?

**Comment by uniartisan** [comment]
also got the same error.
my hardware is NVIDIA Jeston Nano, 4GB ubuntu 18.04
```
../build/examples/squeezenet ../images/256-ncnn.png
[0 NVIDIA Tegra X1 (nvgpu)]  queueC=0[16]  queueG=0[16]  queueT=0[16]
[0 NVIDIA Tegra X1 (nvgpu)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA Tegra X1 (nvgpu)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA Tegra X1 (nvgpu)]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
532 = 0.165161
920 = 0.095581
716 = 0.060242
Segmentation fault (core dumped)
```
I have followed the guide to install ncnn on Jeston.

**Comment by an99990** [comment]
anyone got the solution ?

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5234

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/ded0b78bb2926d3fd116c94d988c8e3d836d191a
