### ISSUE TITLE
同样一张图片，同样的模型，在pc(ubuntu系统)和Android检测结果有差异

### ISSUE THREAD

**Issue by liuwei3612** [Tencent/ncnn#2477]
@nihui 您好，我这边同样一张图片，同样的模型，在pc(ubuntu系统)和Android检测结果有差异，请问这个问题该朝哪个方向分析呢？

**Comment by nihui** [comment]
看看这个文档 https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result
