### ISSUE TITLE
Confusion about CMAKE_TOOLCHAIN_FILE annd CMAKE_TOOLCHAIN_FILE_NAME

### ISSUE THREAD

**Issue by zchrissirhcz** [Tencent/ncnn#2480]
In the root directory of ncnn, the first 7 lines of CMakeLists.txt sometimes make people confuse.

People may ask, what is the purpose of:
```
find_file(CMAKE_TOOLCHAIN_FILE ${CMAKE_TOOLCHAIN_FILE_NAME} PATHS ${CMAKE_SOURCE_DIR} NO_DEFAULT_PATH)
```

Well, I think the comment tells us: **it conert the relative path to absolute path, of the toolchain file.** （toolchain.cmake文件如果是相对路径传入，则转为绝对路径）

Let's just add `message` to print value of `CMAKE_TOOLCHAINN_FILE`, before and after existing code regions, and get:

```cmake
message(STATUS "--- before headlines, CMAKE_TOOLCHAIN_FILE is: ${CMAKE_TOOLCHAIN_FILE}")
if(CMAKE_TOOLCHAIN_FILE)
    set(LIBRARY_OUTPUT_PATH_ROOT ${CMAKE_BINARY_DIR} CACHE PATH "root for library output, set this to change where android libs are compiled to")
    # get absolute path, but get_filename_component ABSOLUTE only refer with source dir, so find_file here :(
    get_filename_component(CMAKE_TOOLCHAIN_FILE_NAME ${CMAKE_TOOLCHAIN_FILE} NAME)
    find_file(CMAKE_TOOLCHAIN_FILE ${CMAKE_TOOLCHAIN_FILE_NAME} PATHS ${CMAKE_SOURCE_DIR} NO_DEFAULT_PATH)
    message(STATUS "CMAKE_TOOLCHAIN_FILE = ${CMAKE_TOOLCHAIN_FILE}")
endif()
message(STATUS "--- after headlines, CMAKE_TOOLCHAIN_FILE is: ${CMAKE_TOOLCHAIN_FILE}")
```

Then, when passing `-DCMAKE_TOOLCHAIN_FILE=../../../../soft/android-ndk-r21b/build/cmake/android.toolchain.cmake`, the output will be like this:

```
-- --- before headlines, CMAKE_TOOLCHAIN_FILE is: ../../../../soft/android-ndk-r21b/build/cmake/android.toolchain.cmake
-- CMAKE_TOOLCHAIN_FILE = /Users/chris/soft/android-ndk-r21b/build/cmake/android.toolchain.cmake
-- --- after headlines, CMAKE_TOOLCHAIN_FILE is: /Users/chris/soft/android-ndk-r21b/build/cmake/android.toolchain.cmake
```

**Comment by zchrissirhcz** [comment]
@OFShare

**Comment by OFShare** [comment]
Yes, you're right, it converts the relative path to absolute path of the toolchain file. 

But cmake's `find_file` is a little bit of strange, it always converts the relative path to absolute path although it doesn't find the file in `PATHS` specified by `find_file`. Below is an example.

```cmake
if(CMAKE_TOOLCHAIN_FILE)
    message(STATUS "CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
    find_file(CMAKE_TOOLCHAIN_FILE "builddd.sh" PATHS ${CMAKE_CURRENT_SOURCE_DIR} 
              REQUIRED NO_DEFAULT_PATH NO_PACKAGE_ROOT_PATH NO_CMAKE_PATH)
    message(STATUS "CMAKE_TOOLCHAIN_FILE after = ${CMAKE_TOOLCHAIN_FILE}")
    return()
```

```shell
pwd     #/Users/acui/Proj/ncnn/build
# invoke like this, just an example `CMAKE_TOOLCHAIN_FILE` doesn't exist.
cmake -DCMAKE_TOOLCHAIN_FILE="../../../android.toolchain.cmakeeee" ..
```
output: 
-- CMAKE_CURRENT_SOURCE_DIR: /Users/acui/Proj/ncnn
-- CMAKE_TOOLCHAIN_FILE after = /Users/acui/android.toolchain.cmakeeee

---
as you noticed, there is no `builddd.sh` file in `PATHS ${CMAKE_CURRENT_SOURCE_DIR}` specified by `find_file` command. So my summary is: `find_file` always converts the relative path to absolute path no matter found or not found it. That behavior makes me confused, maybe somebody else as well. 
@zchrissirhcz
