### ISSUE TITLE
onnx2ncnn转换模型后，输出nan，发现试gemm有问题

### ISSUE THREAD

**Issue by banbishan** [Tencent/ncnn#2487]
![image](https://user-images.githubusercontent.com/13417277/102848221-45422500-444f-11eb-92c8-fe6bd4e09dfd.png)
这里的两个memorydata都是256\*1，就是权重和偏置，而reshape的输出试1\*1152，所以导致了后面输出都为nan。这个应该试转换有问题吗？下面试onnx模型：
[convnet.zip](https://github.com/Tencent/ncnn/files/5727759/convnet.zip)

模型试从pb转换来的。
使用onnxruntime推理结果试正确的。

**Comment by nihui** [comment]
修好了，更新下最新的代码

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
