### ISSUE TITLE
整合两个ncnn项目时出现错误

### ISSUE THREAD

**Issue by 851610272** [Tencent/ncnn#2491]
error: undefined reference to 'ncnn::Mat::from_android_bitmap(_JNIEnv*, _jobject*, int, ncnn::Allocator*)'这个问题有没有大佬知道咋个处理的

**Comment by nihui** [comment]
link libjnigraphics.so

**Comment by 851610272** [comment]
> 链接libjnigraphics.so

请问具体操作是怎样的呢？
