### ISSUE TITLE
Compile source code and example in linux

### ISSUE THREAD

**Issue by BiranLi** [Tencent/ncnn#25]
## Compile source code
Request a protobuf library. Please install it before you compile source code.
```bash
cd $root
mkdir build && cd build
cmake ..
make -j
make install
```
It will install include files and libncnn.a in `$root/build/install`.

## Compile example
I don't know how to build it with cmake, I write a Makefile to build it as follow.
```Makefile
g++ -otest -I$root/build/install/include -lopencv_core -lopencv_highgui -lopencv_imgproc -fopenmp -pthread test.cpp $root/build/install/lib/libncnn.a 
```

**Comment by Pratyeka** [comment]
Compile source code has succeed;
but Compile example failed.   
   g++: error: openmp: 没有那个文件或目录
   g++: error: thread: 没有那个文件或目录
   g++: error: test.cpp: 没有那个文件或目录
Please help me！！！ thank u

**Comment by BiranLi** [comment]
@Pratyeka  Have you installed openmp? For thread, maybe use -lpthread instead. And test.cpp is the source code file.

**Comment by walegahaha** [comment]
Compile source code has succeed but compile example failed(we can't find test.cpp). 
so what's your test.cpp?
How can I convert the caffe-cnn to ncnn-cnn and apply them in the phone?
Thanks!

**Comment by Vandermode** [comment]
@BiranLi  Hi, After I compile the ncnn source file, I write a makefile as follows:
```sh
NCNN = /home/vac/Desktop/ncnn

OPENCV = /home/vac/opencv/opencv-3.2.0

INCPATH = 		-I${NCNN}/build/install/include \
				-I${OPENCV}/modules/objdetect/include \
                -I${OPENCV}/modules/highgui/include \
                -I${OPENCV}/modules/imgproc/include \
                -I${OPENCV}/modules/core/include \
                -I${OPENCV}/modules/imgcodecs/include \
                -I${OPENCV}/modules/videoio/include

LIBS = -lopencv_core -lopencv_highgui -lopencv_imgproc  \
		-fopenmp -pthread

LIBPATH = -L${OPENCV}/build/lib

%:%.cpp
	$(CXX) $(INCPATH) $(LIBPATH) $^ ${NCNN}/build/install/lib/libncnn.a $(LIBS) -o $@
```
Then I type `make squeezenet```, 
however, I got a error:
```
g++ -I/home/vac/Desktop/ncnn/build/install/include -I/home/vac/opencv/opencv-3.2.0/modules/objdetect/include -I/home/vac/opencv/opencv-3.2.0/modules/highgui/include -I/home/vac/opencv/opencv-3.2.0/modules/imgproc/include -I/home/vac/opencv/opencv-3.2.0/modules/core/include -I/home/vac/opencv/opencv-3.2.0/modules/imgcodecs/include -I/home/vac/opencv/opencv-3.2.0/modules/videoio/include -L/home/vac/opencv/opencv-3.2.0/build/lib squeezenet.cpp /home/vac/Desktop/ncnn/build/install/lib/libncnn.a -lopencv_core -lopencv_highgui -lopencv_imgproc -fopenmp -pthread -o squeezenet
/tmp/ccIJ8RWP.o: In function `main':
squeezenet.cpp:(.text+0x507): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
makefile:19: recipe for target 'squeezenet' failed
make: *** [squeezenet] Error 1
```
It seems a ld problem, but I can pretty sure nothing wrong with my opencv address. 
Any suggestion? Thank u very much.

**Comment by wangzhe258369** [comment]
依赖的protobuf：
sudo apt-get install protobuf-compiler
sudo apt-get install libprotobuf-dev

**Comment by BiranLi** [comment]
@Vandermode Try to modify your opencv to version 2 . My working opencv's version is 2.4.13.

**Comment by ruyiweicas** [comment]
@Vandermode this is probably because imread was moved to opencv_imgcodecs. Try to add -lopencv_imgcodecs to linker flags
