### ISSUE TITLE
How to get all multi outputs at once?

### ISSUE THREAD

**Issue by rivergold** [Tencent/ncnn#2504]
For example, my model has an `FPN` module, and the model has multi outputs, how to get all multi outputs at once?

Use `ex.extract` multi times to get outputs one by one will cause the total run time to increase. 

Ref #234, the latest API doesn't have the function to get `vector<ncnn::Mat>`.
Is there any solution?

```C++
ncnn::Mat map0, map1, map2
ncnn::Extractor ex = net.create_extractor();

ex.set_num_threads(4);
ex.set_light_mode(false);

ex.input("x", x);
ex.extract("map0", map0);
// ex.extract("map0", map0); 
// ex.extract("map0", map0);
}
```
Only run get map0 time is `0.014 ms`, get all maps time is `0.043` which is 3 times longer than getting map0. And run get map0 N times is also N times longer than getting map0.

Is this problem is caused by `for loop` in  `forward` of PyTorch `nn.module` ?

**Comment by Suvi-dha** [comment]
Hi @rivergold can you share your solution?
