### ISSUE TITLE
onnx转ncnn后模型大小为0

### ISSUE THREAD

**Issue by zizizihua** [Tencent/ncnn#2505]
![onnx2ncnn](https://user-images.githubusercontent.com/51010057/103148486-16071d00-479b-11eb-91b3-28374381a189.png)
感谢大佬们的工作，我按https://zhuanlan.zhihu.com/p/275989233 中的步骤转换yolovs.pt，导出onnx以及onnxsim都执行成功，执行onnx2ncnn进行转换，得到模型大小为0. 不知道是什么原因导致转换失败？
环境：win10，onnx1.7.0

**Comment by zizizihua** [comment]
![onnx2ncnn2](https://user-images.githubusercontent.com/51010057/103148613-9a0dd480-479c-11eb-88c0-87e691876033.png)
执行转换命令没有报错信息

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/releases/tag/20201218
试试这里的 onnx2ncnn.exe

**Comment by savhascelik** [comment]
I'm getting the same error what's the solution

**Comment by zizizihua** [comment]
> https://github.com/Tencent/ncnn/releases/tag/20201218
> 试试这里的 onnx2ncnn.exe

我尝试了上面链接中的vs2017和vs2019版本，以及从源码编译，都不行哦，都是同样的结果。
另外我发现yolov5导出onnx的opset_version是12，如果设置为9，onnxsim会报错；但用mobilenet，opset_version为9导出后可以转为ncnn，但是推理异常，用ncnnoptimize优化后模型被截断了，param只包含原来的一部分。
有什么建议吗？

**Comment by savhascelik** [comment]
@zizizihua I've been dealing with this problem for two days. I think it is not possible to use a yolov5 model we have trained with ncnn with android.

**Comment by nihui** [comment]
> > https://github.com/Tencent/ncnn/releases/tag/20201218
> > 试试这里的 onnx2ncnn.exe
> 
> 我尝试了上面链接中的vs2017和vs2019版本，以及从源码编译，都不行哦，都是同样的结果。
> 另外我发现yolov5导出onnx的opset_version是12，如果设置为9，onnxsim会报错；但用mobilenet，opset_version为9导出后可以转为ncnn，但是推理异常，用ncnnoptimize优化后模型被截断了，param只包含原来的一部分。
> 有什么建议吗？

请提供下 onnx 文件以便复现问题

**Comment by zizizihua** [comment]
链接：https://pan.baidu.com/s/1OLI9kSZOGlv137arXmRVVw 
提取码：mdko

**Comment by zizizihua** [comment]
> @zizizihua I've been dealing with this problem for two days. I think it is not possible to use a yolov5 model we have trained with ncnn with android.

Thanks. I want to try more and hope to have good luck.

**Comment by nihui** [comment]
> 链接：https://pan.baidu.com/s/1OLI9kSZOGlv137arXmRVVw
> 提取码：mdko

已复现

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/19636723322bda5e31c2ad4e17f9ca946551aaed

**Comment by zizizihua** [comment]
成功了！！！

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
