### ISSUE TITLE
0 kb **.param and 0 kb ***.bin files

### ISSUE THREAD

**Issue by savhascelik** [Tencent/ncnn#2507]
Hello, after applying onnxsim to . pt file, **. bin and **. param files with onnx2ncnn come out as 0 kb have sizes. Does anyone know why

**Comment by nihui** [comment]
> Hello, after applying onnxsim to . pt file, **. bin and **. param files with onnx2ncnn come out as 0 kb have sizes. Does anyone know why

hi, please provide your onnx file after applying onnxsim

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/19636723322bda5e31c2ad4e17f9ca946551aaed

**Comment by nihui** [comment]
a workaround is to use onnx opset_version=11 when exporting

**Comment by savhascelik** [comment]
you are awesome . thanks for your effort 👍

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
