### ISSUE TITLE
在转换模型文件的过程中，为什么参数会发生变化？

### ISSUE THREAD

**Issue by yanJiang0216** [Tencent/ncnn#2508]
我是用pytorch生成的onnx模型，onnx模型经过onnxsim简化之后，再用onnx2ncnn转成.param文件，再用ncnnoptimize对.param进行优化之后, 然后用netron工具打开onnx模型文件和.param文件发现最后一层全连接层的w和b的值不一样，这是什么问题？有人遇到过没？

**Comment by nihui** [comment]
请提供下 onnxsim 简化后的 onnx 文件
通常可能是 conv-bn 或者 fc-bn 融合导致的参数变化

**Comment by yanJiang0216** [comment]
> 请提供下 onnxsim 简化后的 onnx 文件
> 通常可能是 conv-bn 或者 fc-bn 融合导致的参数变化

我们公司不能随便上传文件，上传文件需要申请，实在不好意思！
我的网络结构里没有卷积层，我的网络结构是两层lstm，然后再加一层全连接，那假如就是您说的这个fc-bn融合导致的参数变化的这种情况的话，我应该怎么处理？

**Comment by yanJiang0216** [comment]
> 请提供下 onnxsim 简化后的 onnx 文件
> 通常可能是 conv-bn 或者 fc-bn 融合导致的参数变化

你好，我再问一下，这跟pytorch有没有关系？用其他深度学习框架会有类似的问题吗？

**Comment by tpoisonooo** [comment]
提供不了文件，咋给你定位问题呢。
“上传文件需要申请，实在不好意思！” 潜台词是“这事儿不重要”。

无趣的灵魂...

**Comment by yanJiang0216** [comment]
> 提供不了文件，咋给你定位问题呢。
> “上传文件需要申请，实在不好意思！” 潜台词是“这事儿不重要”。
> 
> 无趣的灵魂...

我错了，大佬，我现在就去申请，谢谢大佬

**Comment by yanJiang0216** [comment]
转换过程中的所有文件已上传

**Comment by yanJiang0216** [comment]
test

**Comment by yanJiang0216** [comment]
test again

**Comment by yanJiang0216** [comment]
[onnx_ncnn.zip](https://github.com/Tencent/ncnn/files/5785388/onnx_ncnn.zip)
我将pytorch转出来的onnx模型，以及后面每一步转换生成的模型的上传上来了，请大神帮忙定位一下问题

**Comment by yanJiang0216** [comment]
@nihui @tpoisonooo 
在公司提这个申请真的很不容易，请大佬一定要帮我定位一下这个问题

**Comment by nihui** [comment]
你用最新的 onnx2ncnn 工具试试看
模型看起来没什么问题

**Comment by yanJiang0216** [comment]
> 你用最新的 onnx2ncnn 工具试试看
> 模型看起来没什么问题
好的，我试一下

**Comment by yanJiang0216** [comment]
@nihui 
用最新版的onnx2ncnn工具，ncnnoptimize工具处理后的文件，全连接层的参数为什么都看不到了，而且模型结构也有点变化
[new_onnx_ncnn.zip](https://github.com/Tencent/ncnn/files/5786300/new_onnx_ncnn.zip)

**Comment by yanJiang0216** [comment]
@tpoisonooo @nihui 
关于转换过程中的问题，我再整体描述一下，又截了一部分图，原文件在上一条评论中已经上传过了，希望有助于大神解答我的问题：
首先pytorch生成的onnx模型我已经检验过了，推理出来的结果和pkl模型推理出来的结果是一样的。
1.没有经过ncnnoptimize工具优化的param中的全连接层的w和b是看不到的，经过ncnnnoptimize工具优化之后又可以看到了，但是，经过ncnnnoptimize工具优化的param中的全连接层的w和b和onnx中的是不一样的，这是为什么？
3.不管经不经过ncnnoptimize工具优化的param中的lstm层的参数都是看不到的，这个有原因吗？
[ncnn转换截图.zip](https://github.com/Tencent/ncnn/files/5792140/ncnn.zip)

**Comment by nihui** [comment]
netron 工具似乎不支持显示 lstm 的权重，把 lstm 权重当成 innerproduct 显示出来了

**Comment by yanJiang0216** [comment]
> netron 工具似乎不支持显示 lstm 的权重，把 lstm 权重当成 innerproduct 显示出来了
1. netron 工具不支持显示 lstm 的权重，这个可以理解 ，但是它把yem层的参数显示在全连接层，我对照了一下好像也不一样，看不到lstm层的参数，不知道它的参数有没有变化
2. 我现在想到的一个方案是将onnx模型中全连接层参数直接复制粘贴到ncnn代码中，去计算全连接层，现在正在写代码测试中

**Comment by nihui** [comment]
netron 那边我已经发 pr 在修改，等 netron 发新版本就可以看 lstm 权重啦

**Comment by yanJiang0216** [comment]
> netron 那边我已经发 pr 在修改，等 netron 发新版本就可以看 lstm 权重啦

好的，谢谢大佬，最好再看一下，为什么全连接层的参数会发生变化？非常非常感谢

**Comment by nihui** [comment]
新版本的netron已经发布了，试试看

**Comment by yanJiang0216** [comment]
> 新版本的netron已经发布了，试试看

好的，谢谢

**Comment by yanJiang0216** [comment]
问题都解决了，感谢@nihui大佬

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
