### ISSUE TITLE
nanodet推理时间问题

### ISSUE THREAD

**Issue by guoxinzhan** [Tencent/ncnn#2509]
环境：Ubuntu18.04 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz， ncnn without vulkan
模型1：nanodet，backbone shufflenetV2 0.5x，input size 320*192，单帧推理时间为89.40ms；
模型2：nanodet，backbone shufflenetV2 1.0x，input size 320*320，单帧推理时间为14.53ms；
opt设置代码：    ex.set_light_mode(false); ex.set_num_threads(4);
模型文件：链接：https://pan.baidu.com/s/1BiqFJ7W8X-u3rn0b3YwSRg ，提取码：ndet 
后缀为s为模型1，m为模型2

**Comment by nihui** [comment]
和这里是一样的问题 https://github.com/Tencent/ncnn/issues/2510

**Comment by nihui** [comment]
修好了～
