### ISSUE TITLE
yolov5-onnx2ncnn，精度下降问题

### ISSUE THREAD

**Issue by zht123** [Tencent/ncnn#2518]
按照up主知乎的操作，但是在测试识别的时候发现识别精度下降，左边为up提供的param，右边为我自己转换的param。
![1RIX~LACOCG6XG0WDTG}0E2](https://user-images.githubusercontent.com/32835472/103256497-77600380-49c8-11eb-8089-04d23a336405.png)
![9DJGDXIG7U}{I9JVOBUT(@9](https://user-images.githubusercontent.com/32835472/103256503-7af38a80-49c8-11eb-9411-13882731e89a.png)

**Comment by zht123** [comment]
[yolov5s-opt.zip](https://github.com/Tencent/ncnn/files/5749518/yolov5s-opt.zip)
yolov5官方提供的最新权重文件转换的param

**Comment by lengxia** [comment]
请问你的各个环境是怎样的呢？我的一直没转换成功

**Comment by zht123** [comment]
> 请问你的各个环境是怎样的呢？我的一直没转换成功

win10，vs2019编译的ncnn

**Comment by zht123** [comment]
已解决，param里的blob名字变了，对应examples中yolov5的cpp文件也要修改，具体如图，修改后精度正常，原因是后面两层输出的参数读取错误（和up提供的参数blob不一样），只用了一层输出的结果，因此精度下降，差别很大。
![%3GKX8O(6~E%K03PB9F{T 7](https://user-images.githubusercontent.com/32835472/103388548-8966b100-4b44-11eb-9a90-5150d18b0aaa.jpg)
![)Z)Z}S(@QBOZJ2_1L5PQQB6](https://user-images.githubusercontent.com/32835472/103388550-8a97de00-4b44-11eb-961f-c6ee05d80f65.jpg)

**Comment by nihui** [comment]
恭喜啦！

**Comment by APeiZou** [comment]
@zht123 ，您好请问一下运用onnx2ncnn转换yolov5的模型出现open failed yolov5-sim.onnx
read_proto_from_binary failed这种错误怎么解决呢？
