### ISSUE TITLE
where is allocator?

### ISSUE THREAD

**Issue by CrazistDriver** [Tencent/ncnn#2520]
why the declare is Mat Mat::from_pixels(const unsigned char* pixels, int type, int w, int h, Allocator* allocator) but in the main function is ncnn::Mat inmat = ncnn::Mat::from_pixels(frame.data, ncnn::Mat::PIXEL_BGR2RGB, frame.cols, frame.rows); where is allocator? how it works?

**Comment by nihui** [comment]
It is the default parameter zero. That means it will use malloc()/free() for allocating memory.
