### ISSUE TITLE
float32计算比int8计算底层做了哪些优化

### ISSUE THREAD

**Issue by MonicaChen426** [Tencent/ncnn#2531]
很多模型测试下来都是量化成int8后运行速度比量化前更慢，代码中int8推理也都做了NEON和汇编优化，为何int8仍然比float32慢，float32计算比int8计算底层做了哪些优化？

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
20210507版本大幅优化int8推理速度并重写了量化工具，建议更新
