### ISSUE TITLE
What version of ndk is recommended when building for Android

### ISSUE THREAD

**Issue by OFShare** [Tencent/ncnn#2533]
When building for android, on this ncnn version(`git checkout 20201218`)

**NDK16**, notice vulkan is on.
```cmake
cmake -DCMAKE_TOOLCHAIN_FILE="$androidNdk16/build/cmake/android.toolchain.cmake" \
                                   -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON \
                                    -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
```

An error occurred (glslang is a third-party library)
---

[ 60%] Building CXX object glslang/glslang/CMakeFiles/glslang.dir/MachineIndependent/linkValidate.cpp.o
/Users/acui/Proj/ncnn/glslang/glslang/MachineIndependent/ParseHelper.cpp:5389:77: **error: no member named 'log2' in namespace 'std';** did you mean simply 'log2'?
            publicType.qualifier.layoutBufferReferenceAlign = (unsigned int)std::log2(value);
                                                                            ^~~~~~~~~
                                                                            log2
/Users/acui/Library/Android/sdk/ndk/android-ndk-r16b/sysroot/usr/include/math.h:168:8: note: 'log2' declared here
double log2(double __x) __INTRODUCED_IN(18);
       ^
[ 60%] Building CXX object glslang/glslang/CMakeFiles/glslang.dir/MachineIndependent/parseConst.cpp.o
[ 60%] Building CXX object glslang/glslang/CMakeFiles/glslang.dir/MachineIndependent/reflection.cpp.o
1 error generated.
make[2]: *** [glslang/glslang/CMakeFiles/glslang.dir/MachineIndependent/ParseHelper.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

---

So I switched to **ndk21** because I noticed this [how-to-build-for-android](https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android), then everything is ok. The following is the corresponding command.

```cmake
cmake -DCMAKE_TOOLCHAIN_FILE="$androidNdk21/build/cmake/android.toolchain.cmake" \
                                          -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON \
                                          -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..
```

![image](https://user-images.githubusercontent.com/49650602/103399341-a10d5c00-4b7b-11eb-8129-f964d4745475.png)

---

So I did more experiments and the conclusions are:

- ndk16, armeabi-v7a + vulkan=ON     **failed**, only failed one
- ndk16, arm64-v8a + vulkan=ON       **passed**

- ndk16, armeabi-v7a + vulkan=OFF   **passed**
- ndk16, arm64-v8a  + vulkan=OFF   **passed**

---

- ndk21, armeabi-v7a + vulkan=ON     **passed**
- ndk21, arm64-v8a + vulkan=ON       **passed**

- ndk21, armeabi-v7a + vulkan=OFF   **passed**
- ndk21, arm64-v8a  + vulkan=OFF   **passed**

Others:

vulkan sdk is: `wget "https://sdk.lunarg.com/sdk/download/1.2.154.0/linux/vulkansdk-linux-x86_64-1.2.154.0.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.2.154.0.tar.gz"`

Why we build for android but downloaded Vulkan SDK is vulkansdk-linux-x86_64(notice x86_64), probably because our compiler for compiling Vulkan code is in this x86_64 SDK. We just need to follow the rules.

---

These conclusions may help you, peace.

**Comment by nihui** [comment]
apply glslang upstream fix if you need to build with ndk-r16b

https://github.com/KhronosGroup/glslang/commit/5c202faffbb826fdec87caa3496b2b6726b3cc07

**Comment by OFShare** [comment]
This solution works, and the test passed. Now both ndk-r16b and ndk-r21b have passed.

`vim ncnn/glslang/glslang/MachineIndependent/ParseHelper.cpp`

```cpp
5389  publicType.qualifier.layoutBufferReferenceAlign = (unsigned int)(std::log(value) / std::log(2.0));                                                         
5390  // publicType.qualifier.layoutBufferReferenceAlign = (unsigned int)std::log2(value);
```
