### ISSUE TITLE
when calling cmake, Visual Studio is not able to compile a simple test program.

### ISSUE THREAD

**Issue by zchrissirhcz** [Tencent/ncnn#2549]
有群友提问。记录如下。

例如编译protobuf（或编译ncnn）时，执行：
```
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF ../cmake
```
报错：
![image](https://user-images.githubusercontent.com/3831847/103510645-98c95f80-4ea0-11eb-82c7-8d6e44161dd2.png)

关键报错是：
> RC Pass 1: command "rc /fo CMakeFiles\cmTC_0b573.dir/manifest.res CMakeFiles\cmTC_0B573.dir/manifest.rc" failed (exit code 0) with the following output:
> 系统找不到指定的文件。NMAKE : fatal error U1077:  "F:\CMake\bin\cmake.exe" : 返回代码"0xffffffff"
> Stop.
> NMAKE : fatal error U1077: "F:\VS2017\VC\Tools\MSVC\14.16.27023\bin\HostX64\nmake.exe" : 返回代码 "0x2"
> Stop.

**Comment by zchrissirhcz** [comment]
最初，猜测是 `rc` 命名没找到。正常情况下，进入 2017 x64 native prompt，是会自动设定然后找到 rc 命令的。例如：

![2`GACU8$A$( )@3`~RCFDRR](https://user-images.githubusercontent.com/3831847/103511092-55bbbc00-4ea1-11eb-8945-72478b53d983.png)

考虑手动添加 rc 的路径

>添加的C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64路径

然后清理cmake输出，重新执行cmake，遇到报错：

![image](https://user-images.githubusercontent.com/3831847/103511153-6bc97c80-4ea1-11eb-84f7-0bc796e05d4f.png)

其中关键报错：
> LINK : fatal error LNK1104: 无法打开文件"kernel32.lib"
> NMAKE : fatal error U1077： "F:\Cmake\bin\cmake.exe" " 返回代码 "0xffffffff"
>Stop.
>NMAKE : fatal error U1077: "F:\VS2017\VC\Tools\MSVC\14.16.27023\bin\HostX64\nmake.exe" : 返回代码 "0x2"
>Stop.

**Comment by zchrissirhcz** [comment]
这里基本判定是，还需要手动添加 lib 目录。（但为何要手动添加？猜测是因为系统装了多个版本的Windows SDK导致的).

**Comment by zchrissirhcz** [comment]
这里的解决思路，个人认为有两种：
1.改generator： 不用NMake Makefile，用Msbuild，也就是：
```
-G"Visual Studio 15 2017 Win64"
```
替代
```
-G"NMake Makefiles"
```

2. 卸掉不正确版本的 Windows SDK，卸掉VS2017，然后重装VS2017. (可以参考 https://www.cnblogs.com/zjutzz/p/13425916.html)

**Comment by ashing-zhang** [comment]
我已收到
