### ISSUE TITLE
copy_make_border()变量问题

### ISSUE THREAD

**Issue by Ergou-Liu** [Tencent/ncnn#2551]
copy_make_border()在mat.cpp中的定义为copy_make_border(const Mat& src, Mat& dst, int top, int bottom, int left, int right, int type, float v, const Option& opt)，但是在spp.cpp中使用的时候函数为：copy_make_border(bottom_blob, bottom_blob_bordered, pad_h, pad_h, pad_w, pad_w, BORDER_CONSTANT, 0.f, opt.workspace_allocator, opt.num_threads);函数定义时最后一个参数为const Option& opt，但是使用的时候函数多了一个参数而且类型也对不上。我搜了下这个函数仅有一处，不知道这样写是C++的特殊语法吗？

**Comment by nihui** [comment]
这里的代码是旧的，需要更新，spp默认没有编译的，所以ci上没有报错……
