### ISSUE TITLE
膨胀卷积计算错误

### ISSUE THREAD

**Issue by upperblacksmith** [Tencent/ncnn#2555]
pytorch模型上256*256与512*512输入大小均可成功推理，转到ncnn框架下512*512推理成功且无精度损失，但是在256*256输入大小时，在网络中间经过某个膨胀卷积计算时发生错误，膨胀卷积输入正确，经膨胀卷积计算后结果为空，无法获取结果

**Comment by maxfy1992** [comment]
- 最好有个param可以复现错误，维度不对可以只构造个param；如果是计算不对，bin最好也上传下；
- 另外可以试试关闭加速用native c的跑下试试

**Comment by upperblacksmith** [comment]
@maxfy1992 
如图圈出来的地方是无法计算的部分，将膨胀率改为16可以正常得到结果，膨胀率为18结果为空，手动算了一下，膨胀率为18的时候，膨胀卷积的输入和输出大小的特征图大小都没问题，大佬可以试下，压缩文件时param和bin文件
![111](https://user-images.githubusercontent.com/34127965/104894954-431ca900-59b0-11eb-860a-10d03a19d0e1.PNG)

[256.zip](https://github.com/Tencent/ncnn/files/5829003/256.zip)

**Comment by maxfy1992** [comment]
hello，我用256.zip中的模型文件测试了输入input维度  c(3)h(480)w(480) ps 因为没有给输入尺寸），得到535节点维度c(256)h(30)w(30)，且有数据不为空，你用最新版本测试一下

```
ncnn version
commit af7d8184aa260a385328166a8e0c5c720fd1b9bb (HEAD -> master, origin/master, origin/HEAD)
Author: nihui <shuizhuyuanluo@126.com>
Date:   Sun Jan 17 14:33:26 2021 +0800

    handle image allocation failure properly

ex.input("input", in);
 c(3)h(480)w(480)
ex.extract("535", out);
c(256)h(30)w(30)
```

**Comment by upperblacksmith** [comment]
谢谢，那我编译个新版本试一下，我之前的输入是512*512的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/ncnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午3:55
收件人:&nbsp;"Tencent/ncnn"<ncnn@noreply.github.com&gt;;
抄送:&nbsp;"Mr.W"<755976168@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/ncnn] 膨胀卷积计算错误 (#2555)





 
hello，我用256.zip中的模型文件测试了输入input维度  c(3)h(480)w(480) ps 因为没有给输入尺寸），得到535节点维度c(256)h(30)w(30)，且有数据不为空，你用最新版本测试一下
 ncnn version commit af7d8184aa260a385328166a8e0c5c720fd1b9bb (HEAD -&gt; master, origin/master, origin/HEAD) Author: nihui <shuizhuyuanluo@126.com&gt; Date:   Sun Jan 17 14:33:26 2021 +0800     handle image allocation failure properly ex.input("input", in);  c(3)h(480)w(480) ex.extract("535", out); c(256)h(30)w(30)

**Comment by upperblacksmith** [comment]
不好意思，说错了，输入大小是256*256的时候没有输出




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/ncnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午3:55
收件人:&nbsp;"Tencent/ncnn"<ncnn@noreply.github.com&gt;;
抄送:&nbsp;"Mr.W"<755976168@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/ncnn] 膨胀卷积计算错误 (#2555)





 
hello，我用256.zip中的模型文件测试了输入input维度  c(3)h(480)w(480) ps 因为没有给输入尺寸），得到535节点维度c(256)h(30)w(30)，且有数据不为空，你用最新版本测试一下
 ncnn version commit af7d8184aa260a385328166a8e0c5c720fd1b9bb (HEAD -&gt; master, origin/master, origin/HEAD) Author: nihui <shuizhuyuanluo@126.com&gt; Date:   Sun Jan 17 14:33:26 2021 +0800     handle image allocation failure properly ex.input("input", in);  c(3)h(480)w(480) ex.extract("535", out); c(256)h(30)w(30)

**Comment by maxfy1992** [comment]
hello，我用附件中的模型做了如下测试：
- 输入维度 输出维度 c(3)h(256)w(256)   c(256)h(16)w(16)，且输出都有正常的额数据
- 输入维度 输出维度 c(3)h(512)w(512)   c(256)h(32)w(32)，且输出都有正常的额数据


```
ncnn version
commit af7d8184aa260a385328166a8e0c5c720fd1b9bb (HEAD -> master, origin/master, origin/HEAD)
Author: nihui <shuizhuyuanluo@126.com>
Date:   Sun Jan 17 14:33:26 2021 +0800

    handle image allocation failure properly

// test code
ex.input("input", in);
ex.extract("535", out);
```

**Comment by upperblacksmith** [comment]
@maxfy1992 这就有点意思了，我编译个新版本的ncnn试下，可能是我用的ncnn有点历史了

**Comment by maxfy1992** [comment]
忘了问，你跑的平台了，我测试的是armv8

**Comment by upperblacksmith** [comment]
win10上做的测试，还没做移植


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/ncnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午4:07
收件人:&nbsp;"Tencent/ncnn"<ncnn@noreply.github.com&gt;;
抄送:&nbsp;"Mr.W"<755976168@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/ncnn] 膨胀卷积计算错误 (#2555)





 
忘了问，你跑的平台了，我测试的是armv8

**Comment by maxfy1992** [comment]
跑的是x86还是vulkan？

**Comment by upperblacksmith** [comment]
x86




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/ncnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午4:10
收件人:&nbsp;"Tencent/ncnn"<ncnn@noreply.github.com&gt;;
抄送:&nbsp;"Mr.W"<755976168@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/ncnn] 膨胀卷积计算错误 (#2555)





 
跑的是x86还是vulkan？

**Comment by maxfy1992** [comment]
可以跑下native c版本，如果native c没问题x86有问题，就是bug了

**Comment by nihui** [comment]
那么使用最新版本解决问题了吗？

**Comment by maxfy1992** [comment]
在macOS上测试x86版本上也没问题，win10没试过

**Comment by upperblacksmith** [comment]
@nihui @maxfy1992 编译了个新版本的试了下，可以推理了，stranger!!!!!

**Comment by upperblacksmith** [comment]
最近又发现个玄学问题，代码完全一致的情况下，win10,x86和x64跑出来的结果不一致,这正常吗

**Comment by upperblacksmith** [comment]
还是个很简单的mobilenetv2分类网络，我想确定下是不是我老版本的ncnn有问题
[mobilenetv2.zip](https://github.com/Tencent/ncnn/files/5854679/mobilenetv2.zip)

**Comment by zchrissirhcz** [comment]
@upperblacksmith 通常考虑用最新版 ncnn 再试一下，有可能已经修复过计算问题。可以考虑从 git commit 记录里头搜索。

**Comment by nihui** [comment]
我记忆中确实有修复过 dilated conv 的计算错误问题，总之更新最新版本应该就可以啦
