### ISSUE TITLE
make 编译遇到error: unknown value ‘armv8.2-a+fp16’ for -march

### ISSUE THREAD

**Issue by Hjy20255** [Tencent/ncnn#2557]
在armv8 平台源码编译ncnn   gcc7.5  make 时遇到错误 
求大神帮忙解决！

**Comment by nihui** [comment]
-DNCNN_ARM82=OFF

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/ce9ae96bde967a84341911834b96530d9568f6f9

**Comment by wxue1201** [comment]
> 在armv8平台源码编译ncnn gcc7.5 make时遇到错误 求大神帮忙解决！

请问最后解决了吗？

**Comment by wxue1201** [comment]
> 

请问，最后解决了吗？

**Comment by wxue1201** [comment]
> 在armv8平台源码编译ncnn gcc7.5 make时遇到错误 求大神帮忙解决！

请问，最后解决了吗？

**Comment by wxue1201** [comment]
> -DNCNN_ARM82=关闭
请问这个在哪里修改？
May I ask where to modify this？

**Comment by nihui** [comment]
最新版代码会自动检测编译器功能了

**Comment by wxue1201** [comment]
> 最新版代码会自动检测编译器功能了

好的，谢谢
