### ISSUE TITLE
cross-compilation

### ISSUE THREAD

**Issue by 2684160504** [Tencent/ncnn#2559]
Hello, what should I pay attention to when cross-compiling on my own board? Hope you can give some experience and opinions.
![Screenshot from 2021-01-05 17-34-26](https://user-images.githubusercontent.com/44891815/103648811-6569fc00-4f98-11eb-94a7-59560eadb8d2.png)

**Comment by zchrissirhcz** [comment]
You may print out the value of `CMAKE_SYSTEM_PROCESSOR` in `CMakeLists.txt`, around line 120~140. It seems that cmake options `NCNN_SSE2` and `NCNN_AVX2` is setting to `ON` while your board does not support sse and avx.

```
message(FATAL_ERROR "CMAKE_SYSTEM_PROCESSOR : ${CMAKE_SYSTEM_PROCESSOR}")
```

Or, if you are sure that your board support sse and avx, then we may refer to modifying flags to support your board.

**Comment by 2684160504** [comment]
> You may print out the value of `CMAKE_SYSTEM_PROCESSOR` in `CMakeLists.txt`, around line 120~140. It seems that cmake options `NCNN_SSE2` and `NCNN_AVX2` is setting to `ON` while your board does not support sse and avx.
> 
> ```
> message(FATAL_ERROR "CMAKE_SYSTEM_PROCESSOR : ${CMAKE_SYSTEM_PROCESSOR}")
> ```
> 
> Or, if you are sure that your board support sse and avx, then we may refer to modifying flags to support your board.

Hello teacher, thank you for your reply
1. In ncnn, the result of cmake directly after source your own cross-compilation tool is Target arch: x86, but my board is arm. Is this a problem?
2.I am newer，how to print out the value of `CMAKE_SYSTEM_PROCESSOR` in `CMakeLists.txt`?
3. Can you recommend several successful compilation cases for me to learn from?
Thank you again for your help, and hope to receive your guidance and suggestions.

**Comment by zchrissirhcz** [comment]
In cmake syntax, `message` command serves as `print`. You may learn how to use `message` according to cmake manual.
Actually, just put this line:
```
message(FATAL_ERROR "CMAKE_SYSTEM_PROCESSOR : ${CMAKE_SYSTEM_PROCESSOR}")
```

in CMakeLists.txt after line 140 with the latest ncnn commit.

**Comment by 2684160504** [comment]
> In cmake syntax, `message` command serves as `print`. You may learn how to use `message` according to cmake manual.
> Actually, just put this line:
> 
> ```
> message(FATAL_ERROR "CMAKE_SYSTEM_PROCESSOR : ${CMAKE_SYSTEM_PROCESSOR}")
> ```
> 
> in CMakeLists.txt after line 140 with the latest ncnn commit.
![Screenshot from 2021-01-07 20-59-41](https://user-images.githubusercontent.com/44891815/103895418-5d8e9100-512b-11eb-8327-690d91e838b7.png)
CMAKE_SYSTEM_PROCESSOR : x86_64

**Comment by zchrissirhcz** [comment]
@2684160504 I guess you didn't passing the cmake toolchain file, or you were using wrong cmake toolchain file.

I've tested with android arm platform for cross compilation. If not specify cmake toolchain file, will also get:
```
CMAKE_SYSTEM_PROCESSOR : x86_64
```

And if specify cmake toolchain file, will get:
```
CMAKE_SYSTEM_PROCESSOR : armv7-a
```

**How to specify cmake toolchain file when calling cmake?**  `-DCMAKE_TOOLCHAIN_FILE=/path/to/cmake/toolchain/file`, e.g.:
```
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabi.toolchain.cmake ..
```

You may refer to ncnn's official wiki page for more examples/details:  https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-arm-cortex-a-family-with-cross-compiling

**Comment by 2684160504** [comment]
> @2684160504 I guess you didn't passing the cmake toolchain file, or you were using wrong cmake toolchain file.
> 
> I've tested with android arm platform for cross compilation. If not specify cmake toolchain file, will also get:
> 
> ```
> CMAKE_SYSTEM_PROCESSOR : x86_64
> ```
> 
> And if specify cmake toolchain file, will get:
> 
> ```
> CMAKE_SYSTEM_PROCESSOR : armv7-a
> ```
> 
> **How to specify cmake toolchain file when calling cmake?** `-DCMAKE_TOOLCHAIN_FILE=/path/to/cmake/toolchain/file`, e.g.:
> 
> ```
> cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabi.toolchain.cmake ..
> ```
> 
> You may refer to ncnn's official wiki page for more examples/details: https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-arm-cortex-a-family-with-cross-compiling

Hello teacher, thank you for your patient answer.

I installed fsl-imx-fb-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-vfp-neon-toolchain-3.14.52-1.1.0.sh compiler, how can I find the corresponding cmake toolchain or I can directly  use cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabi.toolchain.cmake ..?
When compiling .cpp using the makefile, an error occurs as shown in the figure：
![Screenshot from 2021-01-08 15-15-52](https://user-images.githubusercontent.com/44891815/103986043-076e2c00-51c5-11eb-9c46-c9adb5f39d93.png)

**Comment by zchrissirhcz** [comment]
Just find that cmake toolchain file globally inside your toolchain directory. If there isn't such a file, write you own one.

P.S. I really don't know fsl-imx-fb-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-vfp-neon-toolchain-3.14.52-1.1.0.sh.  You may try your mentioned one but I don't guarantee.

**Comment by 2684160504** [comment]
> Just find that cmake toolchain file globally inside your toolchain directory. If there isn't such a file, write you own one.
> 
> P.S. I really don't know fsl-imx-fb-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-vfp-neon-toolchain-3.14.52-1.1.0.sh. You may try your mentioned one but I don't guarantee.

Ok，thank you teacher

**Comment by 2684160504** [comment]
> 
> 
> Just find that cmake toolchain file globally inside your toolchain directory. If there isn't such a file, write you own one.
> 
> P.S. I really don't know fsl-imx-fb-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-vfp-neon-toolchain-3.14.52-1.1.0.sh. You may try your mentioned one but I don't guarantee.

![Screenshot from 2021-01-14 21-36-40](https://user-images.githubusercontent.com/44891815/104599789-2ed86380-56b3-11eb-8651-edae11fc7c72.png)
Hello teacher, I have tried the method I thought of and it has not been solved yet. The link is the compiler, and the document is the installation tutorial I summarized. I hope you have time to try this compiler, thank you very much.
链接：https://pan.baidu.com/s/1jvxyK3dCOH-CDbV37EU-Vw 
提取码：i0ar 
复制这段内容后打开百度网盘手机App，操作更方便哦
[天双编译器.docx](https://github.com/Tencent/ncnn/files/5814806/default.docx)

**Comment by zchrissirhcz** [comment]
Ok, will try it tomorrow

**Comment by zchrissirhcz** [comment]
@2684160504 Hi, I am able to compile and link, generating libncnn.a and benchmark executable file, but I don't have a board to test.

Let me just put my method here, and give reponse whether it can be use or not.

## step1  Install poky toolchain
```bash
bash ./fsl-imx-fb-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-vfp-neon-toolchain-3.14.52-1.1.0.sh
```
Note that I've changed the installation directory, specifying it to `/home/zz/soft/fsl-imx-fb/3.14.52-1.1.0` instead of the default `/opt/fsl-imx-fb/3.14.52-1.1.0`. I think both are OK.

Then put the directory that contains the compiler `arm-poky-linux-gnueabi-gcc` to PATH, for me it is modifying `~/.zshrc`(or `~/.bashrc` if you are using bash) by appending this:
```bash
POKY_COMPILER_DIR=/home/zz/soft/fsl-imx-fb/3.14.52-1.1.0/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
export PATH=$PATH:$POKY_COMPILER_DIR
```
Then re-open shell, or open a new shell.

## Create poky.toolchain.cmake file
I create `poky.toolchain.cmake` in `ncnn/toolchains` directory.
```bash
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(POKY_SDK_DIR "/home/zz/soft/fsl-imx-fb/3.14.52-1.1.0")
set(SDKTARGETSYSROOT "${POKY_SDK_DIR}/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi")

set(CMAKE_C_COMPILER "arm-poky-linux-gnueabi-gcc")
set(CMAKE_CXX_COMPILER "arm-poky-linux-gnueabi-g++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_C_FLAGS "-march=armv7-a -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=${SDKTARGETSYSROOT}")
set(CMAKE_CXX_FLAGS "-march=armv7-a -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=${SDKTARGETSYSROOT}")

# cache flags
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" CACHE STRING "c flags")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "c++ flags")
```

## Compile ncnn
```bash
cd ~/work/ncnn
mkdir build
cd build
```

Then create `poky.sh` with content:
```bash
#!/bin/bash

TOOLCHAIN=../../toolchains/poky.toolchain.cmake

BUILD_DIR=poky
mkdir -p $BUILD_DIR
cd $BUILD_DIR

cmake -G Ninja \
    -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN \
    -DCMAKE_BUILD_TYPE=Release \
    ../..

cmake --build .
cd ..
```

After several seconds, you will get:
- ncnn/build/poky/src/libncnn.a
- ncnn/build/poky/benchmark/benchncnn

Then please copy all files under `ncnn/benchmark` to your board, copy `ncnn/build/poky/benchmark/benchncnn` to you board, then run benchmark.

**Comment by 2684160504** [comment]
> @2684160504 Hi, I am able to compile and link, generating libncnn.a and benchmark executable file, but I don't have a board to test.
> 
> Let me just put my method here, and give reponse whether it can be use or not.
> ## step1 Install poky toolchain
> 
> ```shell
> bash ./fsl-imx-fb-glibc-x86_64-meta-toolchain-qt5-cortexa9hf-vfp-neon-toolchain-3.14.52-1.1.0.sh
> ```
> 
> Note that I've changed the installation directory, specifying it to `/home/zz/soft/fsl-imx-fb/3.14.52-1.1.0` instead of the default `/opt/fsl-imx-fb/3.14.52-1.1.0`. I think both are OK.
> 
> Then put the directory that contains the compiler `arm-poky-linux-gnueabi-gcc` to PATH, for me it is modifying `~/.zshrc`(or `~/.bashrc` if you are using bash) by appending this:
> 
> ```shell
> POKY_COMPILER_DIR=/home/zz/soft/fsl-imx-fb/3.14.52-1.1.0/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi
> export PATH=$PATH:$POKY_COMPILER_DIR
> ```
> 
> Then re-open shell, or open a new shell.
> ## Create poky.toolchain.cmake file
> 
> I create `poky.toolchain.cmake` in `ncnn/toolchains` directory.
> 
> ```shell
> set(CMAKE_SYSTEM_NAME Linux)
> set(CMAKE_SYSTEM_PROCESSOR arm)
> set(POKY_SDK_DIR "/home/zz/soft/fsl-imx-fb/3.14.52-1.1.0")
> set(SDKTARGETSYSROOT "${POKY_SDK_DIR}/sysroots/cortexa9hf-vfp-neon-poky-linux-gnueabi")
> 
> set(CMAKE_C_COMPILER "arm-poky-linux-gnueabi-gcc")
> set(CMAKE_CXX_COMPILER "arm-poky-linux-gnueabi-g++")
> 
> set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
> set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
> set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
> 
> set(CMAKE_C_FLAGS "-march=armv7-a -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=${SDKTARGETSYSROOT}")
> set(CMAKE_CXX_FLAGS "-march=armv7-a -mfloat-abi=hard -mfpu=neon -mtune=cortex-a9 --sysroot=${SDKTARGETSYSROOT}")
> 
> # cache flags
> set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" CACHE STRING "c flags")
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "c++ flags")
> ```
> 
> ## Compile ncnn
> 
> ```shell
> cd ~/work/ncnn
> mkdir build
> cd build
> ```
> 
> Then create `poky.sh` with content:
> 
> ```shell
> #!/bin/bash
> 
> TOOLCHAIN=../../toolchains/poky.toolchain.cmake
> 
> BUILD_DIR=poky
> mkdir -p $BUILD_DIR
> cd $BUILD_DIR
> 
> cmake -G Ninja \
>     -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN \
>     -DCMAKE_BUILD_TYPE=Release \
>     ../..
> 
> cmake --build .
> cd ..
> ```
> 
> After several seconds, you will get:
> 
>     * ncnn/build/poky/src/libncnn.a
> 
>     * ncnn/build/poky/benchmark/benchncnn
> 
> 
> Then please copy all files under `ncnn/benchmark` to your board, copy `ncnn/build/poky/benchmark/benchncnn` to you board, then run benchmark.

Hello teacher, thank you for your help.openmp=off. Compile successfully according to the steps you wrote. And it was too slow to test a frame of 1.6s on the IMX6 board. Can you give some suggestions for speeding up?

**Comment by zchrissirhcz** [comment]
@2684160504  Hi, I don't konw much about hardware... I think you may try compile with `-DNCNN_SIMPLEOMP=ON` when calling cmake. (Not tested, not sure). If this fails, you may ask hardware dalaos in QQ groups.

**Comment by 2684160504** [comment]
> @2684160504 Hi, I don't konw much about hardware... I think you may try compile with `-DNCNN_SIMPLEOMP=ON` when calling cmake. (Not tested, not sure). If this fails, you may ask hardware dalaos in QQ groups.
OK， teacher, thank you very much！

**Comment by zchrissirhcz** [comment]
@2684160504  Hi, can we close this issue since not active talking in recent week?

**Comment by 2684160504** [comment]
> @2684160504 Hi, can we close this issue since not active talking in recent week?
Sure,teacher
