### ISSUE TITLE
ncnn在安卓上支持mobileNet吗？

### ISSUE THREAD

**Issue by h3clikejava** [Tencent/ncnn#257]
我有一个MobileNet模型，在ios上用12月份的ncnn加载正常可以使用，但是在安卓上输出一直是空。不知道是哪里出了问题，C++用的是一套代码。不知道是不是因为模型我用的是XXX.param而不是XXX.param.bin?

**Comment by nihui** [comment]
如果是照着 squeezencnn 那个 sample 改的话，要用 XXX.param.bin

**Comment by h3clikejava** [comment]
@nihui 好了，感谢！
