### ISSUE TITLE
官方yolov5在安卓上运行demo build出错

### ISSUE THREAD

**Issue by wszsp** [Tencent/ncnn#2573]
https://github.com/nihui/ncnn-android-yolov5上下载的demo，配置了
![1610071149(1)](https://user-images.githubusercontent.com/48707845/103965736-5dc57580-5199-11eb-9940-c1462387e16f.jpg)
，这是报错信息* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process F:\android\Sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C C:\Users\zsp\Downloads\ncnn-android-yolov5-master222\ncnn-android-yolov5-master\app\.cxx\cmake\debug\arm64-v8a yolov5ncnn}
  ninja: Entering directory `C:\Users\zsp\Downloads\ncnn-android-yolov5-master222\ncnn-android-yolov5-master\app\.cxx\cmake\debug\arm64-v8a'
  [1/1] Linking CXX shared library C:\Users\zsp\Downloads\ncnn-android-yolov5-master222\ncnn-android-yolov5-master\app\build\intermediates\cmake\debug\obj\arm64-v8a\libyolov5ncnn.so
  FAILED: C:/Users/zsp/Downloads/ncnn-android-yolov5-master222/ncnn-android-yolov5-master/app/build/intermediates/cmake/debug/obj/arm64-v8a/libyolov5ncnn.so 
  cmd.exe /C "cd . && F:\android\Sdk\ndk\20.0.5594570\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android24 --gcc-toolchain=F:/android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=F:/android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -shared -Wl,-soname,libyolov5ncnn.so -o C:\Users\zsp\Downloads\ncnn-android-yolov5-master222\ncnn-android-yolov5-master\app\build\intermediates\cmake\debug\obj\arm64-v8a\libyolov5ncnn.so CMakeFiles/yolov5ncnn.dir/yolov5ncnn_jni.cpp.o  C:/Users/zsp/Downloads/ncnn-android-yolov5-master222/ncnn-android-yolov5-master/app/src/main/jni/ncnn-20201218-android-vulkan/arm64-v8a/lib/libncnn.a -ljnigraphics -fopenmp -static-openmp F:/android/Sdk/ndk/20.0.5594570/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/24/libvulkan.so C:/Users/zsp/Downloads/ncnn-android-yolov5-master222/ncnn-android-yolov5-master/app/src/main/jni/ncnn-20201218-android-vulkan/arm64-v8a/lib/libSPIRV.a C:/Users/zsp/Downloads/ncnn-android-yolov5-master222/ncnn-android-yolov5-master/app/src/main/jni/ncnn-20201218-android-vulkan/arm64-v8a/lib/libglslang.a C:/Users/zsp/Downloads/ncnn-android-yolov5-master222/ncnn-android-yolov5-master/app/src/main/jni/ncnn-20201218-android-vulkan/arm64-v8a/lib/libOGLCompiler.a C:/Users/zsp/Downloads/ncnn-android-yolov5-master222/ncnn-android-yolov5-master/app/src/main/jni/ncnn-20201218-android-vulkan/arm64-v8a/lib/libOSDependent.a -pthread -landroid -llog -latomic -lm && cd ."
  clang++: error: unknown argument: '-static-openmp'
  ninja: build stopped: subcommand failed.

**Comment by nihui** [comment]
ndk 版本太低了？

**Comment by wszsp** [comment]
> ndk版本太低了？

自己又构建了一次ncnn就好了，配置了ndk版本，jni下重新ndk-build解决了

**Comment by gttiankai** [comment]
我这边出现同样的问题，应该是 ndk 版本比较低，从 19 调整到 21 之后就可以了。

**Comment by lightningsoon** [comment]
> > ndk版本太低了？
> 
> 自己又构建了一次ncnn就好了，配置了ndk版本，jni下重新ndk-build解决了

请问具体如何操作，用什么命令构建呢？
