### ISSUE TITLE
commit 3ffb502bc6eb2f6c17d43c82af1b2c81142a4b9b (reuse if the same shape) breaks SSD examples

### ISSUE THREAD

**Issue by simon-rob** [Tencent/ncnn#258]
The "reuse if same shape" code commit has broken the ssdmobilenet/ssdsqueezenet examples, the bounding boxes returned are now incorrect. If the code is removed then correct bounding boxes are returned.

I have tried using memset to ensure the mat is cleared, but the problem still persists. (Is this code just highlighting an issue memory corruption problem  in detectionout or priorbox layers?)

if (dims == 1 && w == _w && elemsize == _elemsize) {
      memset(data, 0, total() * elemsize);
      return;
}

I am running on ubuntu 16.04 LTS.

Cheers,

Simon

**Comment by nihui** [comment]
confirmed
