### ISSUE TITLE
cmakelists.txt 打开openmp出现问题 undefined reference to `__kmpc_for_static_init_4'等一堆错误，使用官网编译好的ncnn 和自己编译的都出现一样的问题。

### ISSUE THREAD

**Issue by victorlea** [Tencent/ncnn#2585]
问题：
  ../../../../src/main/cpp/include/ncnn-vulkan/arm64-v8a/lib/libncnn.a(softplus.cpp.o): In function `.omp_outlined.':
  /home/cpp/install/ncnn/ncnn/src/layer/softplus.cpp:35: undefined reference to `__kmpc_global_thread_num'
  ../../../../src/main/cpp/include/ncnn-vulkan/arm64-v8a/lib/libncnn.a(softplus.cpp.o): In function `.omp_outlined._debug__':
  /home/cpp/install/ncnn/ncnn/src/layer/softplus.cpp:35: undefined reference to `__kmpc_for_static_init_4'
  /home/cpp/install/ncnn/ncnn/src/layer/softplus.cpp:34: undefined reference to `__kmpc_for_static_fini'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

在cmakelists.txt中添加了这些内容。
find_package(OpenMP,REQUIRED)
if(OPENMP_FOUND)
    message("OPENMP FOUND")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
endif()

**Comment by nihui** [comment]
https://github.com/nihui/ncnn-android-yolov5/blob/master/app/src/main/jni/CMakeLists.txt
参考这里的 cmake 写法

另外，ndk 版本用 r21d

**Comment by victorlea** [comment]
谢谢，已经解决。
