### ISSUE TITLE
如何生成输入尺寸固定的 param 文件

### ISSUE THREAD

**Issue by Sanster** [Tencent/ncnn#2586]
- 问题1：固定网络的输入尺寸是否能提高网络推理速度？
- 问题2：如果能的话，如何生成带有尺寸信息的 param 文件？[benchmark](https://github.com/Tencent/ncnn/blob/master/benchmark) 中的 param 文件都是有输入尺寸的，请问这个尺寸是生成的，还是手动修改的？以下截图是我的 ONNX 模型的前两层，可以看到尺寸是固定的，使用 `onnx2ncnn` 转换后，param 文件没有尺寸信息

ONNX 模型的网络结果：
![image](https://user-images.githubusercontent.com/3998421/104157416-10116d00-5426-11eb-8999-f48e7ed552ab.png)

onnx2ncnn 转换后 param 前两层，没有尺寸信息：

![image](https://user-images.githubusercontent.com/3998421/104157440-1b649880-5426-11eb-955a-b5887ba87b53.png)

**Comment by nihui** [comment]
```问题1：固定网络的输入尺寸是否能提高网络推理速度？```
如果使用gpu推理，理论上会提高速度，具体看显卡驱动对于shape信息是否充分利用和优化，实际效果不一定变快，但不会变慢
cpu推理，几乎不影响速度

```问题2：如果能的话，如何生成带有尺寸信息的 param 文件？benchmark 中的 param 文件都是有输入尺寸的，请问这个尺寸是生成的，还是手动修改的？以下截图是我的 ONNX 模型的前两层，可以看到尺寸是固定的，使用 onnx2ncnn 转换后，param 文件没有尺寸信息```
修改 param Input 层，最后加上输入 blob 的 shape 信息，0=w 1=h 2=c，比如 0=224 1=224 2=3，保存
然后用 ncnnoptimize 过一遍模型就能得到有固定 shape 信息的 ncnn 模型啦

**Comment by Sanster** [comment]
thanks!

**Comment by Daipuwei** [comment]
> `问题1：固定网络的输入尺寸是否能提高网络推理速度？` 如果使用gpu推理，理论上会提高速度，具体看显卡驱动对于shape信息是否充分利用和优化，实际效果不一定变快，但不会变慢 cpu推理，几乎不影响速度
> 
> `问题2：如果能的话，如何生成带有尺寸信息的 param 文件？benchmark 中的 param 文件都是有输入尺寸的，请问这个尺寸是生成的，还是手动修改的？以下截图是我的 ONNX 模型的前两层，可以看到尺寸是固定的，使用 onnx2ncnn 转换后，param 文件没有尺寸信息` 修改 param Input 层，最后加上输入 blob 的 shape 信息，0=w 1=h 2=c，比如 0=224 1=224 2=3，保存 然后用 ncnnoptimize 过一遍模型就能得到有固定 shape 信息的 ncnn 模型啦

yolov5按这个思路处理，然后跑ncnnoptimize没办法生成文件，怎么处理哈
![Uploading 20240713-224126.jpg…]()

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
