### ISSUE TITLE
cpu上结果正常，使用vulkan后结果不正确

### ISSUE THREAD

**Issue by imliupu** [Tencent/ncnn#2588]
模型是一个分割模型，在cpu上可以正常运行，得到正确的分割结果，但是使用vulkan后结果却完全不正确了，出来的结果貌似是全为0。

param和bin文件：
[mobile.zip](https://github.com/Tencent/ncnn/files/5795465/mobile.zip)

测试图片（随便找一个有人的图像测试即可）：
![1](https://user-images.githubusercontent.com/46157714/104178428-43afbf80-5445-11eb-8a8b-ff0830dfcc6f.jpg)

使用方式：
......
ncnn::Net seg_net;
//注释掉 则可得到正确的结果
seg_net.opt.use_vulkan_compute = true;
//seg_net.opt.use_fp16_arithmetic = false;
//seg_net.opt.use_fp16_packed = false;
//seg_net.opt.use_fp16_storage = false;
seg_net.load_param("mobile1.param");
seg_net.load_model("mobile.bin");

cv::Mat frame;
frame = cv::imread("1.jpg");
cv::resize(frame, frame, cv::Size(640, 480));
cv::imshow("a", frame);
cv::waitKey(1);

int t1 = clock();
int w = frame.cols;
int h = frame.rows;
ncnn::Mat in = ncnn::Mat::from_pixels_resize(frame.data, ncnn::Mat::PIXEL_BGR, \
	frame.cols, frame.rows, 192, 192);
const float mean_vals[3] = { 127.5f, 127.5f, 127.5f };
const float norm_vals[3] = { 1 / 127.5f, 1 / 127.5f, 1 / 127.5f };
in.substract_mean_normalize(mean_vals, norm_vals);

ncnn::Extractor ex = seg_net.create_extractor();
ex.set_num_threads(1);
ex.input("image", in);
ncnn::Mat out1, out2;
//ex.extract("bilinear_interp_13.tmp_0", out1);
ex.extract("softmax_0.tmp_0", out2);
int t2 = clock();
int t = t2 - t1;

std::vector<cv::Mat> a(out2.c);
for (int p = 1; p < out2.c; p++)
{
	a[p] = cv::Mat(out2.h, out2.w, CV_32FC1);
	memcpy((uchar*)a[p].data, out2.channel(p), out2.w * out2.h * sizeof(float));
}

cv::normalize(a[1], a[1], 0, 255, cv::NORM_MINMAX, CV_8U);

cv::imshow("aa", a[1]);
cv::waitKey(0);

**Comment by imliupu** [comment]
随便找一个有人的图像测试即可

**Comment by nihui** [comment]
测试并没有发现 gpu 有问题，是最新的代码跑的

**Comment by imliupu** [comment]
> 测试并没有发现 gpu 有问题，是最新的代码跑的

请问你那边gpu的结果是和cpu的一致的吗？我的版本不是最新的，但是也是11月份的版本，会不会是版本导致的呀？

**Comment by nihui** [comment]
更新最新的ncnn代码，可以解决问题

**Comment by imliupu** [comment]
十分感谢！发自我的华为手机-------- 原始邮件 --------主题：Re: [Tencent/ncnn] cpu上结果正常，使用vulkan后结果不正确 (#2588)发件人：nihui 收件人：Tencent/ncnn 抄送：imliupu ,Author 

更新最新的ncnn代码，可以解决问题



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Tencent/ncnn/issues/2588#issuecomment-758353019",

"url": "https://github.com/Tencent/ncnn/issues/2588#issuecomment-758353019",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
