### ISSUE TITLE
"load_mocel" may have wrong chracter?

### ISSUE THREAD

**Issue by DXY123** [Tencent/ncnn#2594]
url：[ncnn load model · Tencent/ncnn Wiki](https://github.com/Tencent/ncnn/wiki/ncnn-load-model)

"the comprehensive model loading api table"
【custom IO reader】row
【alexnet.bin】column
load_mocel(const DataReader&) -> load_model

**Comment by nihui** [comment]
hi would you please create a pull request to fix the type ?

https://github.com/Tencent/ncnn/blob/master/docs/how-to-use-and-FAQ/ncnn-load-model.md

**Comment by zchrissirhcz** [comment]
Since this issue is not active, I've created an PR to fix this issue. https://github.com/Tencent/ncnn/pull/2625

**Comment by nihui** [comment]
fixed
