### ISSUE TITLE
使用c++caffe训练的人脸标点模型，经过转换后使用ncnn进行还原问题

### ISSUE THREAD

**Issue by yungs2017** [Tencent/ncnn#260]
使用ncnn进行还原的时候出现完全不对的情况，反复检查了代码，不存在逻辑错误问题，裁剪图片数据也没有问题。请问是否在转换caffe模型的时候需要注意什么？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result
看下faq

**Comment by nihui** [comment]
如果还有问题，可以 reopen issue 继续讨论
