### ISSUE TITLE
onnx转ncnn, param文件内容错误

### ISSUE THREAD

**Issue by fosaken** [Tencent/ncnn#2608]
&emsp;&emsp;在转换MobileNetV3 onnx模型到ncnn时, 生成的param文件中显示个别BinaryOp有两个输入, (其中一个输入并不存在, 如: ‘309_splitncnn_28’), 但事实上应该只有一个输入.

&emsp;&emsp;转换环境如下:
Ubuntu 16.04
- python=3.8.5
- torch=1.7.1
- ncnn=20101208

&emsp;&emsp;文件见附件: param文件为onnnx2ncnn结果, -op.param为ncnnoptimize结果
[file.zip](https://github.com/Tencent/ncnn/files/5833328/file.zip)

**Comment by nihui** [comment]
更新到最新的 onnx2ncnn.cpp 正常啦

**Comment by fosaken** [comment]
> 更新到最新的 onnx2ncnn.cpp 正常啦

ok, 问题解决了！！！  どうも

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
