### ISSUE TITLE
Denormals Are Zeros 

### ISSUE THREAD

**Issue by aliushn** [Tencent/ncnn#2610]
在用ncnn进行推理过程中，发现一个问题：CPU inference is very slow for some model checkpoints
https://github.com/apache/incubator-mxnet/issues/19218
mxnet相关研究人员有种建议是通过设置DAZ 的方式提高速度，ncnn能否有一个这种设置，做到类似下面这种

generating code for Intel set FZ (Flush to Zero) and DAZ (Denormals Are Zero) flags to avoid slow denormals

https://github.com/grame-cncm/faust/commit/cf9bb4cf46d35a81281d39b549d7c05734bc8453

**Comment by nihui** [comment]
good suggestion !

**Comment by nihui** [comment]
最新版本已支持自动 flush denormals to zero
