### ISSUE TITLE
ncnn VS2019 protobuf-3.4.0编译出现错误error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”

### ISSUE THREAD

**Issue by zhangts20** [Tencent/ncnn#2616]
`
libprotobuf.lib(coded_stream.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(message_lite.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(zero_copy_stream_impl_lite.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(zero_copy_stream_impl.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(text_format.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(io_win32.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(common.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(arena.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(once.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(repeated_field.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(wire_format_lite.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(generated_message_util.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(unknown_field_set.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(descriptor.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(message.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(generated_message_reflection.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(reflection_ops.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(wire_format.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(zero_copy_stream.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(stringprintf.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(any.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(strtod.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(tokenizer.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(dynamic_message.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(strutil.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(status.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(int128.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(atomicops_internals_x86_msvc.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(structurally_valid.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(extension_set.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(stringpiece.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(descriptor.pb.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(descriptor_database.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(substitute.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(map_field.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
libprotobuf.lib(extension_set_heavy.cc.obj) : error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MT_StaticRelease”不匹配值“MD_DynamicRelease”(caffe2ncnn.cpp.obj 中)
`
请问一下这个该怎么解决呢？

**Comment by nihui** [comment]
```
cmake -DNCNN_BUILD_WITH_STATIC_CRT=ON ..
```

**Comment by CP-Jiang** [comment]
在vs中的项目属性，设置c/c++ --> 代码生成-->运行库改为和库一致的值即可，库的值为：多线程 (/MT)

**Comment by YCG1** [comment]
> 在vs中的属性，设置c/c++ --> 代码生成--> 运行库改为和库一致的项目可以解决，库是：多线程(/MT)

改了还是会出现这个问题
