### ISSUE TITLE
src/gpu.cpp中glslang的头文件包含问题

### ISSUE THREAD

**Issue by Yangxiu123321** [Tencent/ncnn#2622]
OS: Arch Linux 
glslang：最新版本
配置命令：
> cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=ON -DNCNN_SYSTEM_GLSLANG=ON -DGLSLANG_TARGET_DIR=/usr/lib/cmake -DNCNN_BUILD_EXAMPLES=ON ..

/home/mod/code/DL/Tencent/ncnn_comment/src/gpu.cpp:24:10: 致命错误：glslang/glslang/Public/ShaderLang.h：没有那个文件或目录
   24 | #include "glslang/glslang/Public/ShaderLang.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
编译中断。

修改为：glslang/Public/ShaderLang.h后正常

**Comment by zchrissirhcz** [comment]
`src/CMakeLists.txt`:
```cmake
target_include_directories(ncnn PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/../>)
```

看起来是把 ncnn 工程根目录作为头文件搜索目录的，如果 glslang 是通过 submodule 方式拉取的，那么 gpu.cpp 里的用法是没有问题的

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/c16cac26780ed00ba8951a6deeac7c6806d99343
