### ISSUE TITLE
slice 层出错 ret为100

### ISSUE THREAD

**Issue by mxmxlwlw** [Tencent/ncnn#263]
你好:
       在innerprodect层后mat为w-512, 然后输入到slice层中就出错了.
       在caffe中innerproduct对应512的应该是c而不是w, 是不是哪里有问题?

**Comment by mxmxlwlw** [comment]
而且还有个奇怪的问题, 运行net.cpp到前面的innerproduct层以后经常会跳出 就是在if (ret != 0)这一句就直接跳出了

**Comment by mxmxlwlw** [comment]
有人吗... 在线等着那, 让我过个好年- -

**Comment by nihui** [comment]
主页上有qq群，可以加下

**Comment by mxmxlwlw** [comment]
哈哈哈, 我在公司里面, 被封锁了, 手机加吧

**Comment by YQZ1990** [comment]
arm上是正常的，x86的有问题

**Comment by mxmxlwlw** [comment]
不正常的, 我用的就是arm. 我最后换了个更小的网络, 所以没解决也无所谓了. 可以过个好年了, 么么哒
