### ISSUE TITLE
GPU mode output Nan error on 2080Ti ,CPU mode output right.

### ISSUE THREAD

**Issue by joe807191330** [Tencent/ncnn#2636]
![P(YPN7`WP4~X9B6K_%H%Y8T](https://user-images.githubusercontent.com/29222158/105970055-e746d400-60c3-11eb-828c-8064af137c21.png)

[efficientdet_ncnn.zip](https://github.com/Tencent/ncnn/files/5878965/efficientdet_ncnn.zip)

**Comment by nihui** [comment]
cannot reproduce
try upgrading your graphics driver, or disable some of the fp16 features

```
ncnn::Net net;
net.opt.use_fp16_packed = false;
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
net.opt.use_int8_storage = false;
net.opt.use_int8_arithmetic = false;
```

**Comment by joe807191330** [comment]
> cannot reproduce
> try upgrading your graphics driver, or disable some of the fp16 features
> 
> ```
> ncnn::Net net;
> net.opt.use_fp16_packed = false;
> net.opt.use_fp16_storage = false;
> net.opt.use_fp16_arithmetic = false;
> net.opt.use_int8_storage = false;
> net.opt.use_int8_arithmetic = false;
> ```

it worked,thanks!
