### ISSUE TITLE
Mxnet模型使用mxnet2ncnn的时候遇到问题

### ISSUE THREAD

**Issue by Ackesnal** [Tencent/ncnn#264]
在进行模型转换的时候报错：

~/ncnn/build/tools/mxnet$ ./mxnet2ncnn model-mobilenet-20180202-symbol.json model-mobilenet-20180202-0159.params 
_minus_scalar not supported yet!
#scalar=127.5
_mul_scalar not supported yet!
#scalar=0.0078125
BlockGrad not supported yet!
L2Normalization not supported yet!
#mode=instance
_mul_scalar not supported yet!
#scalar=64.0
L2Normalization not supported yet!
#mode=instance
one_hot not supported yet!
#depth=85164
#off_value=0.0
#on_value=1.0
pick not supported yet!
#axis=1
_div_scalar not supported yet!
#scalar=64.0
_minus_scalar not supported yet!
#scalar=-0.87758256189
_mul_scalar not supported yet!
#scalar=0.87758256189
_rminus_scalar not supported yet!
#scalar=1.0
sqrt not supported yet!
_mul_scalar not supported yet!
#scalar=0.479425538604
elemwise_sub not supported yet!
_mul_scalar not supported yet!
#scalar=64.0
_minus_scalar not supported yet!
#scalar=15.3416172353
where not supported yet!
elemwise_sub not supported yet!
expand_dims not supported yet!
#axis=1
broadcast_mul not supported yet!

有很多mxnet模型里的操作似乎ncnn不支持。但是如果把这些操作去掉，改用in.substract_mean_normalize(mean_vals, norm_vals)等函数处理，那在mxnet2ncnn转换模型的时候又会提示Segmentation fault (core dumped) 「可能是因为模型文件和参数文件是一一对应的，无法只修改模型文件。但是参数是经过训练已经封装好了的，也不能修改。」

想请教一下大神这时候可以怎么办？

还有find_blob_index_by_name  xxxx  failed这个问题该如何解决？我在xxxx中填的和模型里的名字应该已经一样了，但还是说找不到，可能是什么引起？

**Comment by pribadihcr** [comment]
+1

**Comment by Jancy1072** [comment]
+1

**Comment by Jancy1072** [comment]
ncnn工具有一直在更新，所以重新下载编译能解决

**Comment by datafarmers** [comment]
_minus_scalar not supported yet!
# scalar=127.5
_mul_scalar not supported yet!
# scalar=0.0078125
BlockGrad not supported yet!
BlockGrad not supported yet!
slice_axis not supported yet!
# axis=0
# begin=0
# end=20
slice_axis not supported yet!
# axis=0
# begin=20
# end=40
slice_axis not supported yet!
# axis=0
# begin=40
# end=60
_plus_scalar not supported yet!
# scalar=0.3
MakeLoss not supported yet!

我也遇到类似的问题

**Comment by TonyTangYu** [comment]
@Ackesnal  请问你解决了吗？
