### ISSUE TITLE
打开vulkan编译iOS时出现链接错误

### ISSUE THREAD

**Issue by devandong** [Tencent/ncnn#2653]
按照文档[build-for-ios-on-macosx-with-xcode](https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-ios-on-macosx-with-xcode)，下载vulkan sdk，cmake命令如下：
`
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=OS64 -DVulkan_INCLUDE_DIR=/path/to/vulkansdk-macos-1.1.114.0/MoltenVK/include -DVulkan_LIBRARY=/path/to/vulkansdk-macos-1.1.114.0/MoltenVK/iOS/dynamic/libMoltenVK.dylib -DNCNN_VULKAN=ON ..
make -j8
`
链接时出现错误：

```
ld: warning: ignoring file /Users/devandong/tools/vulkansdk-macos-1.1.114.0/MoltenVK/iOS/dynamic/libMoltenVK.dylib, building for iOS-arm64e but attempting to link with file built for iOS-arm64
Undefined symbols for architecture arm64e:
  "_vkAllocateCommandBuffers", referenced from:
      ncnn::VkComputePrivate::init() in libncnn.a(command.cpp.o)
      ncnn::VkTransferPrivate::init() in libncnn.a(command.cpp.o)
     ......
```
似乎是vulkan sdk仅包含arm64的编译代码，而设置OS64时，ncnn为arm64和arm64e进行编译，针对arm64e链接时找不到vulkan库的符号

**Comment by nihui** [comment]
cmake参数
```
-DIOS_ARCH="arm64"
```

**Comment by devandong** [comment]
> cmake参数
> 
> ```
> -DIOS_ARCH="arm64"
> ```

OK了
