### ISSUE TITLE
RepVGG-A0 NCNN耗时

### ISSUE THREAD

**Issue by cavalleria** [Tencent/ncnn#2663]
输入大小是112x112，分类输出改成了42类，在高通835上耗时如下
```
./benchncnn 4 1 0 -1 0 
RepVGG-A0_sim-opt  min =   56.03  max =   58.55  avg =   57.28
efficientnetb0-opt  min =   35.23  max =   35.82  avg =   35.42
mobilenetv2-opt  min =   18.28  max =   19.48  avg =   18.90
efficientnet-lite0-opt  min =   22.96  max =   24.18  avg =   23.74
```
RepVGG-A0_sim-opt模型下载地址(链接: https://pan.baidu.com/s/147hqdESKikVfftl8Tjp4MA 提取码: 9tsr)

**Comment by nihui** [comment]
[RepVGG-A0_sim-opt.param.txt](https://github.com/Tencent/ncnn/files/5926805/RepVGG-A0_sim-opt.param.txt)

**Comment by nihui** [comment]
optimization https://github.com/Tencent/ncnn/pull/2664

**Comment by cavalleria** [comment]
`RepVGG-A0_sim-opt  min =   44.58  max =   45.95  avg =   45.18`
