### ISSUE TITLE
请问可以用from_pixels_resize把ncnn::Mat直接给resize成另一个ncnn::Mat吗？

### ISSUE THREAD

**Issue by zylo117** [Tencent/ncnn#2667]
你好，我在使用from_pixels_resize把ncnn::Mat（BGR）给resize成另一个ncnn::Mat（BGR）后，出现了像素排列错位的情况，感觉是读取顺序问题。而按照文档先用`ncnn::Mat 3 channel -> cv::Mat CV_8UC3 + keep RGB/BGR order`把ncnn::Mat转换成opencv mat后，再使用from_pixels_resize，就可以正常转换，但是这个应该会先生成一个cv mat，就比较浪费内存。

我有另一个地方使用from_pixels_resize对RGB的ncnn::Mat进行resize，结果是正常的，用BGR排列就不正常了。
这个是我生成BGR Mat的方法

    ncnn::Mat bgr = ncnn::Mat::from_android_bitmap(env, bitmap, ncnn::Mat::PIXEL_RGB2BGR);

所以请问可以用from_pixels_resize把BGR的ncnn::Mat直接给resize成另一个ncnn::Mat吗？这样我也不用引入opencv了。

**Comment by zylo117** [comment]
是要求ncnn::Mat连续吗？试过用clone和reshape，都不行

**Comment by nihui** [comment]
```void resize_bilinear(const Mat& src, Mat& dst, int w, int h, const Option& opt = Option());```

**Comment by zylo117** [comment]
> `void resize_bilinear(const Mat& src, Mat& dst, int w, int h, const Option& opt = Option());`

谢谢大佬，解决了，非常感谢！
