### ISSUE TITLE
onnx转ncnn时出现protobuf版本不匹配

### ISSUE THREAD

**Issue by XingBin111** [Tencent/ncnn#2671]
用onnx2ncnn转yolo_v5.onnx时报错, 请问如何解决:
`$ onnx2ncnn yolov5s-sim.onnx yolov5s.param yolov5s.bin`
`[libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 3.12.3 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.13.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/xingb001/github_projects/ncnn/build/tools/onnx/onnx.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.12.3 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.13.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/home/xingb001/github_projects/ncnn/build/tools/onnx/onnx.pb.cc".)
Aborted (core dumped)`

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
