### ISSUE TITLE
Support 1D convolution?

### ISSUE THREAD

**Issue by KeepGoing2019HaHa** [Tencent/ncnn#2676]
Hi, does ncnn support 1d convolution? I observe that **onnx2ncnn** will automatically convert 1d convolution to 2d convolution, but the **elemsize** will also change, from 4-->12, which will cause error if we want to concat two array.

> EXC_BAD_ACCESS (code=1, address=0x13c2b5000)

A workaroud would be convert 1d conv to 2d conv first, and then call **onnx2ncnn**. 
Are there more elegant solutions?

**Comment by nihui** [comment]
1d convolution is supported if you use pnnx to convert your pytorch model to ncnn
try onnx2torch and then pnnx, if you only have onnx file around

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
