### ISSUE TITLE
retinaface landmark result on Android is not correct after upgrade NCNN to latest version

### ISSUE THREAD

**Issue by laihaotao** [Tencent/ncnn#2678]
After upgrade to version "1.0.20210124", the retinface model give the following result on Android (OnePlus8, android 10), as you can see the landmarks are not aligned properly:

![image (4)](https://user-images.githubusercontent.com/12627863/107672623-1da75600-6c63-11eb-9be9-70ce1934a36c.png)

The previous version (not sure which one exactly, no version number found inside `platform.h`, but this one doesn't have function `ncnn::Mat::from_pixels_roi_resize` yet) will give the following result without changing any code, just replacing the `include/ncnn` and `libncnn.a`.

![image](https://user-images.githubusercontent.com/12627863/107673586-251b2f00-6c64-11eb-8a58-a4bf0e4bee79.png)

But both versions work fine on Linux, seems something wrong with the Android build ? @nihui any idea what maybe the problem ?

Thanks

**Comment by laihaotao** [comment]
I verified that `20200727` tagged version was the latest that gave the proper landmark position

**Comment by laihaotao** [comment]
after compare the release log, disable fp16 fixed the issue lol

**Comment by netdur** [comment]
> fp16

how did you disable fp16?

**Comment by laihaotao** [comment]
> > fp16
> 
> how did you disable fp16?

check the `option` property of the `net` object.
