### ISSUE TITLE
onnx转ncnn后binaryop(乘)结点出现问题

### ISSUE THREAD

**Issue by zhangziwenHIT** [Tencent/ncnn#2684]
参考nihui大神的文章指导，我将一个mobilenet及部分后处理从pytorch转换成ncnn，固定模型输入，两个推理结果，一个恒定且错误，另一个数值一直在变（可能因为memorydata的存在？）。我自己尝试将模型打断点，最终定位在了两个矩阵相乘操作。
转换步骤如下：
1.opset版本设置成11，pytorch>>onnx；
2.使用onnxsim简化模型，去除胶水op；
3.使用网页    https://convertmodel.com/    转换模型，勾选onnx 和 ncnn optimizer选项；
其中出问题的部分模型结构如下，两个binaryop节点有问题：
![image](https://user-images.githubusercontent.com/69712084/108442571-3d0d3700-7292-11eb-8715-9d81589fa3aa.png)
对应的onnx模型部分：
![image](https://user-images.githubusercontent.com/69712084/108442671-64fc9a80-7292-11eb-91ce-6c51d616583f.png)
感谢！！

**Comment by nihui** [comment]
这个 Mul 是4维数据，不支持的
还是建议把后处理都去掉后导出模型，后处理外部自己实现下

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
