### ISSUE TITLE
Compilation Failed on Ubuntu 

### ISSUE THREAD

**Issue by AlanLu0808** [Tencent/ncnn#2685]
按照教程在Ubuntu16.04上编译最新的项目，在执行
`cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=ON -DNCNN_SYSTEM_GLSLANG=ON -DNCNN_BUILD_EXAMPLES=ON ..
build$ make -j$(nproc)`
时，报错。请问这可能是哪里出了问题呢？

![截图20210219092156](https://user-images.githubusercontent.com/17940005/108444196-1a305200-7295-11eb-8a78-b88275c5e2a6.png)

**Comment by AlanLu0808** [comment]
还有，请问有预编译好的python版ncnn可以提供吗？我直接pip install ncnn，提示找不到这个包。
`ERROR: Could not find a version that satisfies the requirement ncnn
ERROR: No matching distribution found for ncnn`

谢谢！: )

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/releases 这里有编译好的 ubuntu 16.04 包

**Comment by AlanLu0808** [comment]
> https://github.com/Tencent/ncnn/releases 这里有编译好的 ubuntu 16.04 包

感谢回复！我之前运行了这个包没问题。其实我主要想使用python接口，但是直接pip install ncnn 找不到，所以才重新编译这个项目。

请问有预编译好的python包提供吗？感谢！

**Comment by nihui** [comment]
现在已经可以 pip install ncnn 啦
