### ISSUE TITLE
用onnx2ncnn转换yolov5的模型出现这个问题请问有解决的吗？

### ISSUE THREAD

**Issue by APeiZou** [Tencent/ncnn#2695]
open failed yolov5-sim.onnx
read_proto_from_binary failed

**Comment by nihui** [comment]
似乎是 onnx 文件损坏
onnx 文件在 netron 中可以打开吗？

**Comment by 307509256** [comment]
你的文件名写错了

**Comment by NoMoreBeauty** [comment]
> open failed yolov5-sim.onnx read_proto_from_binary failed

我也遇到了 请问解决了吗

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
