### ISSUE TITLE
FP32 times reported using  v20200916 very fast. Are these really FP16 results?

### ISSUE THREAD

**Issue by DeleOgunjumelo** [Tencent/ncnn#2703]
Hello, 

I am having very fast inference times when i run the benchmark tests with the latest release v20210124. I have managed to track the release which brought this improvement to v20200916.  Please see some of my results below: 

Platform : Snapdragon  855 HDK
CPU Config:  Big big cores: A76 [ 4 cores - 1.61GHz ]
OS: Android 10

benchncnn  binary input parameters:  -
loop_count = 10
num_threads = 4
powersave = 2
gpu_device = -1
cooling_down = 0

Neural network inference performance results from Tencent NCNN release  v20200916

            squeezenet  min =    5.73  max =    6.17  avg =    5.91     
               mobilenet  min =    8.21  max =    9.76  avg =    8.76     
               shufflenet  min =    5.62  max =   19.88  avg =    7.32
               googlenet  min =   23.90  max =   36.39  avg =   25.72
                   alexnet  min =   21.09  max =   23.23  avg =   21.72
                    vgg16   min =   74.81  max =  154.05  avg =  123.63
                 resnet50  min =   40.58  max =   41.71  avg =   40.94
         mobilenet_ssd  min =   21.01  max =   22.52  avg =   21.64
  
   
Neural network inference performance results from from Tencent NCNN release  v20200727

          squeezenet  min =   10.33  max =   10.84  avg =   10.60
             mobilenet  min =   14.65  max =   15.51  avg =   15.05
             shufflenet  min =    8.46  max =   14.45  avg =   10.25
             googlenet  min =   34.52  max =   46.34  avg =   36.05
                 alexnet  min =   36.16  max =   36.96  avg =   36.45
                   vgg16  min =  159.91  max =  173.76  avg =  162.00
               resnet50  min =   79.16  max =   90.89  avg =   80.65
       mobilenet_ssd  min =   31.89  max =   44.66  avg =   33.95

**********************************************************************************

Please could you help in answering the following questions?

   -  Are the current test results from v20200916 from FP32 or FP16 results?

   -  Is there a way to enable or disable  FP32/FP16 with Tencent NCNN?
   
  -  There is a flag in the benchncnn application '"use_fp16_arithmetic = true flag".  Is this flag for enabling FP16 test run? or is there a better way to enable or disable FP16/FP32 runs.

**Comment by nihui** [comment]
The fp16 inference will be enabled on supported platforms automatically in recent releases.

You can disable fp16 inference via these option switches.
```
net.opt.use_fp16_packed = false;
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
```

**Comment by DeleOgunjumelo** [comment]
Thank you for the quick response. 

Also, would using the following flags -DNCNN_ARM82=OFF during compilation disable fp16 inference. This is due to its effect on the "__ARM_FEATURE_FP16_VECTOR_ARITHMETIC"  flag.

**Comment by nihui** [comment]
yeah, you can disable all the armv8.2 optimization code via -DNCNN_ARM82=OFF completely.
It makes sense if you are sure that your target platform does not support armv8.2, and it will produce smaller binary size.

**Comment by DeleOgunjumelo** [comment]
Thank you for your help
