### ISSUE TITLE
ncnn python proper teardown issue in Windows 10 (with Vulkan)

### ISSUE THREAD

**Issue by pinczakko** [Tencent/ncnn#2717]
I tested ncnn python _benchmark.py_ and the example files (_yolov4.py_, etc.) in Windows 10 with Vulkan enabled. It worked just fine until all the routines completed, but the program wouldn't exit gracefully until several minutes afterward, i.e. it kinds of "hang/stopped", before finally exiting. _benchmark.py_ requires less time to exit gracefully than the examples. I have tried using Ctrl+z, Ctrl+d to forcefully stop the python script, but it didn't work. 
![Screenshot (175)](https://user-images.githubusercontent.com/11014633/109460060-9f381a00-7a92-11eb-90b9-e8f0e19ff2f8.png)
The screenshot above shows the cursor stays for several minutes like that until the example python script finished itself.

I suspect, this issue is related to the teardown code/deinitialization of ncnn when vulkan is activated. 
This issue doesn't exist when only the CPU is used for inference. 
I read in _benchmark.py_ that the extractor need to be released manually when using Vulkan as ncnn backend. How exactly that needs to be done? A more thorough explanation than the one in _benchmark.py_ would be helpful.

**Comment by caishanli** [comment]
what about other samples, like yolov2.py yolov3.py yolov5.py?

**Comment by caishanli** [comment]
fixed in pr2726
