### ISSUE TITLE
ncnn的deconvolution层的结果和caffe的deconv层的结果偏差较大

### ISSUE THREAD

**Issue by jiajing76** [Tencent/ncnn#272]
![out_ca](https://user-images.githubusercontent.com/31911275/36535238-f41e1d16-1803-11e8-8f97-7990a5dca806.jpg)
![out](https://user-images.githubusercontent.com/31911275/36535239-f455975a-1803-11e8-8b68-10a73cd125f5.jpg)
两个结果对比，见图片。

**Comment by nihui** [comment]
请提供下输入的 size，以及 deconvolution 的参数

**Comment by jiajing76** [comment]
Deconvolution    deconvolution0                   1 1 activation20 deconvolution0 0=32 1=4 11=4 3=2 13=2 5=0 6=16384
输入为图像原图，712x474

**Comment by jiajing76** [comment]
相应caffe的是：
layer {
  name: "deconvolution0"
  type: "Deconvolution"
  bottom: "batchnorm26_scale"
  top: "deconvolution0"
  convolution_param {
    num_output: 32
    bias_term: false
    pad: 0
    kernel_size: 4
    stride: 2
  }
}

**Comment by jiajing76** [comment]
原来是batchnorm的问题，close吧
