### ISSUE TITLE
Build for iOS with Xcode

### ISSUE THREAD

**Issue by kernel-Peanut** [Tencent/ncnn#2721]
nihui大佬，我Xcode的版本是12.3
运行`cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DIOS_PLATFORM=OS64 ..`后，会报这样的错：

`-- CMAKE_TOOLCHAIN_FILE = /Users/zhongyuxiang/Documents/ncnn-20210124/toolchains/ios.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /Users/zhongyuxiang/Documents/ncnn-20210124/build-ios/install
-- NCNN_VERSION_STRING = 1.0.21.03.02
CMake Error at /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/Platform/Darwin-Initialize.cmake:234 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/Platform/Darwin-Initialize.cmake:278 (_apple_resolve_multi_arch_sysroots)
  /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:43 (project)

-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Check for working C compiler: /Users/zhongyuxiang/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CMake Error at /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/Platform/Darwin-Initialize.cmake:234 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/Platform/Darwin-Initialize.cmake:278 (_apple_resolve_multi_arch_sysroots)
  /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  /Users/zhongyuxiang/Documents/ncnn-20210124/build-ios/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)

CMake Error at /usr/local/Cellar/cmake/3.17.3/share/cmake/Modules/CMakeTestCCompiler.cmake:44 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:43 (project)
`

请问怎么解决，求助！

**Comment by DaChengTechnology** [comment]
你可以试试

```
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DIOS_PLATFORM=OS64 -DENABLE_BITCODE=0 -DENABLE_ARC=0 -DENABLE_VISIBILITY=0 -DIOS_ARCH="arm64"  -DNCNN_BUILD_BENCHMARK=OFF ..
```

**Comment by kernel-Peanut** [comment]
> 你可以试试
> 
> ```
> cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DIOS_PLATFORM=OS64 -DENABLE_BITCODE=0 -DENABLE_ARC=0 -DENABLE_VISIBILITY=0 -DIOS_ARCH="arm64"  -DNCNN_BUILD_BENCHMARK=OFF ..
> ```
> 
> 或者参考release CI

感谢回复！但运行后还是报同样的错
`string sub-command REPLACE requires at least four arguments.`
release CI是什么，可以share一个链接吗

**Comment by DaChengTechnology** [comment]
> > 你可以试试
> > ```
> > cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DIOS_PLATFORM=OS64 -DENABLE_BITCODE=0 -DENABLE_ARC=0 -DENABLE_VISIBILITY=0 -DIOS_ARCH="arm64"  -DNCNN_BUILD_BENCHMARK=OFF ..
> > ```
> > 
> > 
> > 或者参考release CI
> 
> 感谢回复！但运行后还是报同样的错
> `string sub-command REPLACE requires at least four arguments.`
> release CI是什么，可以share一个链接吗

抱歉 最近没关注这个

你加个
```
-DNCNN_VULKAN=OFF
```

**Comment by kernel-Peanut** [comment]
> > > 你可以试试
> > > ```
> > > cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DIOS_PLATFORM=OS64 -DENABLE_BITCODE=0 -DENABLE_ARC=0 -DENABLE_VISIBILITY=0 -DIOS_ARCH="arm64"  -DNCNN_BUILD_BENCHMARK=OFF ..
> > > ```
> > > 
> > > 
> > > 或者参考release CI
> > 
> > 
> > 感谢回复！但运行后还是报同样的错
> > `string sub-command REPLACE requires at least four arguments.`
> > release CI是什么，可以share一个链接吗
> 
> 抱歉 最近没关注这个
> 
> 你加个
> 
> ```
> -DNCNN_VULKAN=OFF
> ```
感谢！
