### ISSUE TITLE
Mobilenet V2 Optimization

### ISSUE THREAD

**Issue by CrazyAlan** [Tencent/ncnn#273]
Any plan to optimize for Mobilenet V2? When converting from caffe (https://github.com/shicai/MobileNet-Caffe), Mobilenet V2 is even slower than V1, which is in contrast to the original paper (https://arxiv.org/abs/1801.04381)

**Comment by sanallen** [comment]
@CrazyAlan I tested Mobilenet V2 on caffe2，there is also a slower running speed vs V1. I plan to test Mobilenet V2 on Tensorflow-lite

**Comment by nihui** [comment]
mobilenet v2 benchmark added https://github.com/Tencent/ncnn/commit/0d26710f3d729ad4fc207c605e06eb280adbd78b

qcom410 A53 1.2Gx4, single thread benchmark result with ncnn master source
```
loop_count = 4
num_threads = 1
powersave = 0
       mobilenet  min =  549.83  max =  566.07  avg =  558.28
    mobilenet_v2  min =  490.50  max =  494.69  avg =  492.25
```

**Comment by nihui** [comment]
well, mobilenet v2 is a little slower than v1 in multithread benchmark.
I guess that there's more multithreading overhead, but it needs more investigating

```
loop_count = 8
num_threads = 4
powersave = 0
       mobilenet  min =  194.55  max =  277.11  avg =  212.46
    mobilenet_v2  min =  207.02  max =  217.91  avg =  215.16
```

**Comment by CrazyAlan** [comment]
@sanallen yes, they mentioned their experiments is under TF lite, it would be awesome if you could reproduce their result. Please keep us informed.

**Comment by daquexian** [comment]
Just for your information,

```
sailfish:/data/local/tmp/ncnn $ ./benchncnn 8 4 0
loop_count = 8
num_threads = 4
powersave = 0
       mobilenet  min =  124.03  max =  163.20  avg =  137.62
    mobilenet_v2  min =   72.58  max =  164.37  avg =  114.46
```
