### ISSUE TITLE
set_num_threads not working for Retinaface example.

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#2739]
For some reason, the `ncnn::Extractor::set_num_threads` is not working for the [Retinaface](https://github.com/Tencent/ncnn/blob/master/examples/retinaface.cpp) sample code. 
I have tested with other inference code (arcface resnet 100 inference) and it works fine as expected for those models.

This is how to replicate the issue. 
Clone the git repo, then on [this](https://github.com/Tencent/ncnn/blob/2d31868389f7e8fb37cac73a072beefa8cfaeaa0/examples/retinaface.cpp#L259) line I add: 
`ex.set_num_threads(1);`

At the bottom of the app, I change [this](https://github.com/Tencent/ncnn/blob/2d31868389f7e8fb37cac73a072beefa8cfaeaa0/examples/retinaface.cpp#L425) to:
```
    while(true){
        detect_retinaface(m, faceobjects);    
    }
``` 
so that I can monitor CPU usage while it runs. 

Next, I compile the SDK and build the examples. 
When I run the sample app, running the command `top` show's that the CPU usage is ~500% (Dual Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz - 20 cores total).

![image](https://user-images.githubusercontent.com/17056751/110402953-23f5db80-8031-11eb-9564-10878b953dff.png)

As mentioned, with other more basic inference examples, setting `ex.set_num_threads(1)` limits CPU usage to 100%.

**Comment by zchrissirhcz** [comment]
Hi, there is a wiki page about openmp

https://github.com/Tencent/ncnn/wiki

Hope this can be helpful.

**Comment by cyrusbehr** [comment]
Hi @zchrissirhcz 
I search the page you linked and wasn't able to find anything about OpenMP.

**Comment by zchrissirhcz** [comment]
https://github.com/Tencent/ncnn/wiki/openmp-best-practice

**Comment by cyrusbehr** [comment]
Thank you, though it still doesn't actually explain the bug mention in the issue. 
Why is the `set_num_threads` function not working for the retinaface example, whereas it works fine for other inference examples?

**Comment by ncnnnnn** [comment]
```
int main(int argc, char** argv)
{
    while(true)
    {
        ncnn::Net mobilenet;
        mobilenet.opt.use_packing_layout=true;
        mobilenet.opt.num_threads=1;
        mobilenet.load_param("mobilenet_ssd_voc_ncnn.param");
        mobilenet.load_model("mobilenet_ssd_voc_ncnn.bin");
        mobilenet.clear();
    }
}
```
opt.use_packing_layout=true; -->   384.1  1.1   0:15.82 mobilenetssd
opt.use_packing_layout=false;->   100.0  0.9   0:16.43 mobilenetssd

**Comment by cyrusbehr** [comment]
After more investigation, it looks like my issue is a result of a call to `resize_bilinear(img, resizedImg, imgWidth*scaleFactor, imgHeight*scaleFactor);` in my retinaface implementation. This function uses many threads for resizing. ncnn is otherwise performing as expected, I'll therefore be closing this issue.
