### ISSUE TITLE
自己训练的caffe模型转ncnn模型，在windows下可以正确预测和识别，android下预测失败

### ISSUE THREAD

**Issue by juventi** [Tencent/ncnn#274]
相同版本ncnn，自己训练的LeNet模型，识别mnist数字，在windows下可以正确识别；
参考squeezencnn-AS的方法，在android下导入模型正常，但是ex.extract() 后的out.c 和 out.cstep都是0..求问可能的原因

**Comment by nihui** [comment]
ex.extract() 出来的 Mat 压平，参考 https://github.com/Tencent/ncnn/wiki/how-to-use-ncnn-with-alexnet
```
ncnn::Mat out_flatterned = out.reshape(out.w * out.h * out.c);
std::vector<float> scores;
scores.resize(out_flatterned.w);
for (int j=0; j<out_flatterned.w; j++)
{
    scores[j] = out_flatterned[j];
}
```

**Comment by juventi** [comment]
额 可以了。。这个问题是ncnn::Net不小心又初始化一遍导致的。。全局变量中有个Net。。结果自己的函数中又生声明了一个。。
后面又遇到一个识别结果不一样的问题，是不同的Opencv Mat转ncnn::Mat导致的；
如果传入Opencv RGB Mat，直接用ncnn::Mat::from_pixels_resize 转灰度图ncnn::Mat::PIXEL_GRAY，结果不对；
如果用Opencv转灰度后 传入Gray Mat，再用ncnn::Mat::PIXEL_GRAY，结果才对。。
已经OK了。。多谢大神

**Comment by Pinnh** [comment]
I meet the same issue, ncnn::Mat::from_pixels_resize will make wrong result ,when use OpenCV resize to instead ,everything is OK. what I used Ncnn is early version(2017/12) .

**Comment by ysduxx34** [comment]
I meet the same issue ， ncnn::Mat in = ncnn::Mat::from_pixels_resize(raw_img.data, ncnn::Mat::PIXEL_BGR2GRAY, raw_img.cols, raw_img.rows, input_size, input_size);Net result is wrong.
