### ISSUE TITLE
There is an error when kernel_w!=kernel_h in convolution op

### ISSUE THREAD

**Issue by hust-cxl** [Tencent/ncnn#2742]
1、My input is a wav sequence, length (1,16384), convolution kernel_w=15, kernel_h=1 , using pytorch to train the model.
2、Change .pt model to onnx, and optimize onnx to onnx-sim using onnxsimplify.
3、Use onnx2ncnn to change onnx-sim model to .param and .bin.
Error occured:
My .param file did not set convolutin param kernel_h, 1=15(means  kernel_w=15, as the picture depicted), while 11 was not set.
![image](https://user-images.githubusercontent.com/30313363/110764282-d1652b00-828d-11eb-9e67-eb36b8536923.png)
So kernel_h was defaulted to set kernel_h=kernel_w, and when computing maxk in convolution_arm.cpp,  maxk=kernel_w*kernel_h, there will be segmentation fault error.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
