### ISSUE TITLE
innerproduct implementation seems not surpport the axis 0 of  input blob axis?

### ISSUE THREAD

**Issue by wl3b10s** [Tencent/ncnn#275]
the loop of the innerproduct only go throug input blob of channel, width and height.

am i right?

if the num of input blob has information, i have to add a out for loop myself.

thanks.

**Comment by nihui** [comment]
yes, ncnn only supports three dims blob
you have to loop the N-dim manully if the model produce N-dim result intermediately

**Comment by nihui** [comment]
the rationale of no supporting the N-dim is that the batch size is usually one in inference process.

**Comment by wl3b10s** [comment]
very thanks~~~
