### ISSUE TITLE
咨询一下利用咱们ncnn进行手写识别的时候，耗电会比其它深度学习库耗电很高

### ISSUE THREAD

**Issue by van68** [Tencent/ncnn#2755]
利用最原始的cnn模型在手机端基于ncnn进行推理，耗电会很高，这个是正常的吗？
谢谢。

**Comment by nihui** [comment]
可以设置以下参数降低CPU占用
```
net.opt.num_threads = ncnn::get_big_cpu_count();
net.opt.openmp_blocktime = 0;
```

**Comment by van68** [comment]
net.opt.num_threads = ncnn::get_big_cpu_count();
目前已经按照这个设置了。

**Comment by van68** [comment]
net.opt.num_threads = ncnn::get_cpu_count();
是按照这个设置，应该是老版本。

**Comment by nihui** [comment]
你可以更新下ncnn的新版本，性能优化后，耗时变短，耗电也会减少

**Comment by van68** [comment]
多谢。

**Comment by TriLoo** [comment]
有没有办法根据模型的计算量预估耗电量呢？谢谢

**Comment by van-68** [comment]
> 可以更新下ncnn的新版本，性能优化后，耗时变短，耗电也会减少

多谢回复
ncnn的版本从去年2月份的升级到目前最新的了。内部测试功耗基本没啥变化（变化不大）
请问，版本升级以后，相关调用是否需要调整，或者添加调用的优化函数呢，谢谢。
