### ISSUE TITLE
Tesla M40和K80的显卡，nvnn gpu版本没法调用gpu?

### ISSUE THREAD

**Issue by xinsuinizhuan** [Tencent/ncnn#2766]
哪位大神遇到过，ncnn gpu版本，在专业显卡上跑，已经切换了WDDM模式，还是不行，在nvidia-smi下根本看不到进程，求大神帮忙？

**Comment by ncnnnnn** [comment]
benchncnn能列出显卡吗？

**Comment by xinsuinizhuan** [comment]
可以了。更换为WDDM模式，刚开始不行，后面突然可以了。但是，还有个问题，就是我们使用ncnn通过yulkan调用GPU，cpu占用率很高，cpu可以达到50%多，很奇怪。gpu反而只能达到32%。怎么回事，您遇到过没？

**Comment by nihui** [comment]
可能是因为模型中有部分op还不支持vulkan加速，导致回退到cpu上执行
建议更新ncnn版本，包含更多cpu/gpu优化支持，以及设置 net.opt.num_threads = 1 降低cpu使用
