### ISSUE TITLE
onnx2ncnn error Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by chuan298** [Tencent/ncnn#2769]
Hi @nihui, I am using newest ncnn and I get error Segmentation fault when using pytorch -> onnx -> ncnn model. Can you help me? Thank you.

This is my code:
`ncnn::Net net;
 net.load_param("resnet18-opt.param");
 net.load_model("/resnet18-opt.bin");
 ncnn::Mat in;
 ncnn::Mat out;
 ncnn::Extractor ex = net.create_extractor();
 ex.input("input.1", in);
 ex.extract("199", out);`

And this is my file .param:

> 7767517
49 57
Input                    input.1                  0 1 input.1
Convolution              Conv_0                   1 1 input.1 125 0=64 1=7 3=2 4=3 5=1 6=9408 9=1
Pooling                  MaxPool_3                1 1 125 126 1=3 2=2 3=1 5=1
Split                    splitncnn_0              1 2 126 126_splitncnn_0 126_splitncnn_1
Convolution              Conv_4                   1 1 126_splitncnn_1 129 0=64 1=3 4=1 5=1 6=36864 9=1
Convolution              Conv_7                   1 1 129 130 0=64 1=3 4=1 5=1 6=36864
BinaryOp                 Add_9                    2 1 130 126_splitncnn_0 132
ReLU                     Relu_10                  1 1 132 133
Split                    splitncnn_1              1 2 133 133_splitncnn_0 133_splitncnn_1
Convolution              Conv_11                  1 1 133_splitncnn_1 136 0=64 1=3 4=1 5=1 6=36864 9=1
Convolution              Conv_14                  1 1 136 137 0=64 1=3 4=1 5=1 6=36864
BinaryOp                 Add_16                   2 1 137 133_splitncnn_0 139
ReLU                     Relu_17                  1 1 139 140
Split                    splitncnn_2              1 2 140 140_splitncnn_0 140_splitncnn_1
Convolution              Conv_18                  1 1 140_splitncnn_1 143 0=128 1=3 3=2 4=1 5=1 6=73728 9=1
Convolution              Conv_21                  1 1 143 144 0=128 1=3 4=1 5=1 6=147456
Convolution              Conv_23                  1 1 140_splitncnn_0 146 0=128 1=1 3=2 5=1 6=8192
BinaryOp                 Add_25                   2 1 144 146 148
ReLU                     Relu_26                  1 1 148 149
Split                    splitncnn_3              1 2 149 149_splitncnn_0 149_splitncnn_1
Convolution              Conv_27                  1 1 149_splitncnn_1 152 0=128 1=3 4=1 5=1 6=147456 9=1
Convolution              Conv_30                  1 1 152 153 0=128 1=3 4=1 5=1 6=147456
BinaryOp                 Add_32                   2 1 153 149_splitncnn_0 155
ReLU                     Relu_33                  1 1 155 156
Split                    splitncnn_4              1 2 156 156_splitncnn_0 156_splitncnn_1
Convolution              Conv_34                  1 1 156_splitncnn_1 159 0=256 1=3 3=2 4=1 5=1 6=294912 9=1
Convolution              Conv_37                  1 1 159 160 0=256 1=3 4=1 5=1 6=589824
Convolution              Conv_39                  1 1 156_splitncnn_0 162 0=256 1=1 3=2 5=1 6=32768
BinaryOp                 Add_41                   2 1 160 162 164
ReLU                     Relu_42                  1 1 164 165
Split                    splitncnn_5              1 2 165 165_splitncnn_0 165_splitncnn_1
Convolution              Conv_43                  1 1 165_splitncnn_1 168 0=256 1=3 4=1 5=1 6=589824 9=1
Convolution              Conv_46                  1 1 168 169 0=256 1=3 4=1 5=1 6=589824
BinaryOp                 Add_48                   2 1 169 165_splitncnn_0 171
ReLU                     Relu_49                  1 1 171 172
Split                    splitncnn_6              1 2 172 172_splitncnn_0 172_splitncnn_1
Convolution              Conv_50                  1 1 172_splitncnn_1 175 0=512 1=3 3=2 4=1 5=1 6=1179648 9=1
Convolution              Conv_53                  1 1 175 176 0=512 1=3 4=1 5=1 6=2359296
Convolution              Conv_55                  1 1 172_splitncnn_0 178 0=512 1=1 3=2 5=1 6=131072
BinaryOp                 Add_57                   2 1 176 178 180
ReLU                     Relu_58                  1 1 180 181
Split                    splitncnn_7              1 2 181 181_splitncnn_0 181_splitncnn_1
Convolution              Conv_59                  1 1 181_splitncnn_1 184 0=512 1=3 4=1 5=1 6=2359296 9=1
Convolution              Conv_62                  1 1 184 185 0=512 1=3 4=1 5=1 6=2359296
BinaryOp                 Add_64                   2 1 185 181_splitncnn_0 187
ReLU                     Relu_65                  1 1 187 188
Pooling                  AveragePool_67           1 1 188 190 0=1 1=7 5=1
Reshape                  Reshape_73               1 1 190 198 0=-1
InnerProduct             Gemm_74                  1 1 198 199 0=2 1=1 2=1024

**Comment by chuan298** [comment]
I fixed it

**Comment by HungVS** [comment]
@chuan298 I've faced the same problem with Yolov5. Could you share your solution? 
I really appreciate any help you can provide.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
