### ISSUE TITLE
onnx转ncnn后推理结果不正确

### ISSUE THREAD

**Issue by sosopop** [Tencent/ncnn#2777]
[model.zip](https://github.com/Tencent/ncnn/files/6176994/model.zip)
用onnxruntime测试onnx模型的推理结果，和转换为ncnn的模型的推理结果完全不一样，模型输入3x112x112，归一化到-1~1
onnx结果：-0.5896841287612915,0.4294816553592682,0.3200630247592926,-0.4226250648498535,-0.6429726481437683
ncnn结果：-2.98415e+15,-5.7725e+15,-3.38238e+15,1.99497e+15

**Comment by sosopop** [comment]
自己搞错了

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
