### ISSUE TITLE
动态库编译后，yolact程序运行结束后异常退出，请问怎样才能正常退出程序

### ISSUE THREAD

**Issue by yingunjun** [Tencent/ncnn#2779]
现象：
yolact程序运行结束后，程序无法正常退出

![图片](https://user-images.githubusercontent.com/50563443/111938708-878a0980-8b05-11eb-81f3-e63866dd007a.png)

使用ncnn版本：release 20210124版

编译方式如下：
cmake -G"Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:/ncnn -DProtobuf_INCLUDE_DIR=D:/protobuf/include -DProtobuf_LIBRARIES=D:/protobuf/lib/libprotobuf.lib -DProtobuf_PROTOC_EXECUTABLE=D:/protobuf/bin/protoc.exe -DNCNN_VULKAN=ON -DNCNN_SHARED_LIB=ON ../code -DOpenCV_DIR=D:/opencv/build/x64/vc15/bin 

然后用virtual studio 2019 编译

跑example 中yolact 的例子，程序运行完成后退出异常。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#crash-when-freeing-a-ncnn-dynamic-librarydllso-built-with-openmp

**Comment by yingunjun** [comment]
> 
> 
> https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#crash-when-freeing-a-ncnn-dynamic-librarydllso-built-with-openmp

感谢大神回复，不过我这边加了环境变量后退出异常仍然存在，是vulkan的原因不，如下堆栈错误信息：
![图片](https://user-images.githubusercontent.com/50563443/112101691-0a809200-8be2-11eb-885d-a5f980a29ac8.png)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5234

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/ded0b78bb2926d3fd116c94d988c8e3d836d191a
