### ISSUE TITLE
宽和高不一样大的caffe 网络转换

### ISSUE THREAD

**Issue by sunjunlishi** [Tencent/ncnn#278]
对一个同样的 caffe网络结构，一个是 64*64 输入 一个是 40*30（高*宽）的输入的转换，64*64的输出很稳定；但是40*30的输入很不稳定？？？？
![1](https://user-images.githubusercontent.com/11845664/36769551-e2d28b2a-1c7f-11e8-9351-07f78c893dad.png)
![2](https://user-images.githubusercontent.com/11845664/36769553-e398fc92-1c7f-11e8-86ef-211a96953384.png)
![3](https://user-images.githubusercontent.com/11845664/36769555-e40a8bd2-1c7f-11e8-84c9-0ad95612a4c0.png)
![4](https://user-images.githubusercontent.com/11845664/36769557-e4a858bc-1c7f-11e8-85e2-cc5da59c5a26.png)

**Comment by sunjunlishi** [comment]
个人感觉某一层，对于宽和高不一致，有些地方没有处理好。

**Comment by sunjunlishi** [comment]
还有宽高不一样，为3通道，结果稍微稳定；甚者单通道的话，输出结果很不稳定。所以个人感觉一定是代码对于宽高和通道的数据组织那的问题。

**Comment by lucaslu1987** [comment]
似乎是winograde优化在宽高不想等的时候还有bug

**Comment by nihui** [comment]
请提供下是哪个 layer 开始输出不一样，以及这个 layer 的参数和输入图尺寸

**Comment by nihui** [comment]
关闭issue，如有反馈请重新打开
