### ISSUE TITLE
macOS下编译的Android armv7有23.1MB，求指点~

### ISSUE THREAD

**Issue by xiaoxiaocainiao** [Tencent/ncnn#2786]
按照步骤编译的，参数一点不改。https://github.com/Tencent/ncnn/releases 下载的只有3.8MB。

macOS 11.2.3
ndk: 22.0.7026061

$ cd <ncnn-root-dir>
$ mkdir -p build-android-armv7
$ cd build-android-armv7

$ cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON \
    -DANDROID_PLATFORM=android-14 ..
make -j$(nproc)
$ make install

**Comment by leeys888** [comment]
When I try to build with apple clang on mac, the library size seems to be bigger than when I build with gcc on linux.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/build-for-android.zh#%E5%87%86%E5%A4%87-android-toolchain-%E6%96%87%E4%BB%B6

注意删除ndk的 -g 参数
