### ISSUE TITLE
onnx2ncnn error

### ISSUE THREAD

**Issue by cqray1990** [Tencent/ncnn#2788]
[tools_onnx.zip](https://github.com/Tencent/ncnn/files/6212664/tools_onnx.zip)

**Comment by nihui** [comment]
你更新下 onnx-simplifier，以及 onnx2ncnn 转换 clip 没有考虑缺少 max 的情况，现在修好了
另外，建议用 torch.nn.Hardsigmoid 实现 hardsigmoid，效率更好点

**Comment by cqray1990** [comment]
@nihui 我的onnx-simplifier 是最新的０.3.3,是onnx2ncnn的问题？，我的ｃｌｉｐ缺少ｍａｘ是什么情况？
  x = (self.slope * x) + self.offset
x = torch.clamp(-x,-1)
  x = torch.clamp(-x,0)　是这个错误？这个有什么错误？

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
