### ISSUE TITLE
cv_core

### ISSUE THREAD

**Issue by YIFanH** [Tencent/ncnn#2795]
HI, I want to kown Is there an image processing module in ncnn，like gaussion filter、boxfiter or median filters，thanks for your replay

**Comment by nihui** [comment]
Hi
The opencv library is the most suitable
If you need a smaller opencv binary, go https://github.com/nihui/opencv-mobile

**Comment by YIFanH** [comment]
thanks for youe replay, the sdk package is not contain opencv library ，so I need code it with neon
