### ISSUE TITLE
Where to find original mxnet Retinaface mnet.25-opt model?

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#2798]
Where can I find the original mxnet Retinaface mobilenet model.
In the Retinaface code [here](https://github.com/Tencent/ncnn/blob/61cd9da55b1838a3509268bf858c76824caf63d7/examples/retinaface.cpp#L243-L246), it mentions that the model comes from [this](https://github.com/deepinsight/insightface/issues/669#issue-442669691) issue.

However, the model in that issue is 1.68 Mb in size, whereas the ncnn model [here](https://github.com/nihui/ncnn-assets/blob/e591f441b1f6d951852bb55e5b89feef2bb8eea1/models/mnet.25-opt.bin) is 834Kb in size - they are not the same model!

**Comment by ncnnnnn** [comment]
mxnet != ncnn

**Comment by cyrusbehr** [comment]
@ncnnnnn this is not a helpful answer. I know mxnet is not ncnn. 

If you look at the code I linked, you will see that the comments say that the model was obtained from the insightface repo and converted from mxnet to ncnn, so I’m asking where the original mxnet model is (which was converted to ncnn).

**Comment by cyrusbehr** [comment]
I think @nihui might know where the model is from. Did you train it yourself? Or did you convert one of the mxnet pre-trained models to ncnn? And if you did convert a mxnet model to ncnn, where can I find that original model?

**Comment by nihui** [comment]
The ncnn model is optimized as fp16 storage, via ncnnoptimize utility. so it is almost half the size of the original mxnet model.

**Comment by cyrusbehr** [comment]
ok that makes sense, thanks.
