### ISSUE TITLE
image dimension too large resulting in forward_layer image allocation failed, fallback to cpu

### ISSUE THREAD

**Issue by chuan298** [Tencent/ncnn#2799]
Hi @nihui, i am using ncnn with vulkan, Nvidia Tesla K80, cuda 10.1 in ubuntu 18.04 and it runs normally but with ubuntu 20.04 I get an error:

`image_ dimension too large 16 2405 16 > 2048`

`forward_layer 7 2_41 image allocation failed, fallback to cpu`

This is my .param file: 
`7767517
83 91
Input                  data                 0 1 data 0=416 1=416 2=3
Convolution            0_25                 1 1 data 0_25 0=32 1=3 2=1 3=2 4=1 5=0 6=864
BatchNorm              0_25_bn              1 1 0_25 0_25_bn 0=32 1=.00001
ReLU                   0_25_bn_leaky        1 1 0_25_bn 0_25_bn_leaky 0=0.1
Convolution            1_33                 1 1 0_25_bn_leaky 1_33 0=64 1=3 2=1 3=2 4=1 5=0 6=18432
BatchNorm              1_33_bn              1 1 1_33 1_33_bn 0=64 1=.00001
ReLU                   1_33_bn_leaky        1 1 1_33_bn 1_33_bn_leaky 0=0.1
Convolution            2_41                 1 1 1_33_bn_leaky 2_41 0=64 1=3 2=1 3=1 4=1 5=0 6=36864
BatchNorm              2_41_bn              1 1 2_41 2_41_bn 0=64 1=.00001
ReLU                   2_41_bn_leaky        1 1 2_41_bn 2_41_bn_leaky 0=0.1
Split                  2_41_bn_leaky_split  1 2 2_41_bn_leaky 2_41_bn_leaky_split_0 2_41_bn_leaky_split_1
Crop                   3_49                 1 1 2_41_bn_leaky_split_0 3_49 2=32 3=104 4=104 5=32
Convolution            4_54                 1 1 3_49 4_54 0=32 1=3 2=1 3=1 4=1 5=0 6=9216
BatchNorm              4_54_bn              1 1 4_54 4_54_bn 0=32 1=.00001
ReLU                   4_54_bn_leaky        1 1 4_54_bn 4_54_bn_leaky 0=0.1
Split                  4_54_bn_leaky_split  1 2 4_54_bn_leaky 4_54_bn_leaky_split_0 4_54_bn_leaky_split_1
Convolution            5_62                 1 1 4_54_bn_leaky_split_0 5_62 0=32 1=3 2=1 3=1 4=1 5=0 6=9216
BatchNorm              5_62_bn              1 1 5_62 5_62_bn 0=32 1=.00001
ReLU                   5_62_bn_leaky        1 1 5_62_bn 5_62_bn_leaky 0=0.1
Concat                 6_70                 2 1 5_62_bn_leaky 4_54_bn_leaky_split_1 6_70
Convolution            7_73                 1 1 6_70 7_73 0=64 1=1 2=1 3=1 4=0 5=0 6=4096
BatchNorm              7_73_bn              1 1 7_73 7_73_bn 0=64 1=.00001
ReLU                   7_73_bn_leaky        1 1 7_73_bn 7_73_bn_leaky 0=0.1
Concat                 8_81                 2 1 2_41_bn_leaky_split_1 7_73_bn_leaky 8_81
Pooling                9_84                 1 1 8_81 9_84 0=0 1=2 2=2 5=1 3=0 13=0 14=0 15=0
Convolution            10_88                1 1 9_84 10_88 0=128 1=3 2=1 3=1 4=1 5=0 6=147456
BatchNorm              10_88_bn             1 1 10_88 10_88_bn 0=128 1=.00001
ReLU                   10_88_bn_leaky       1 1 10_88_bn 10_88_bn_leaky 0=0.1
Split                  10_88_bn_leaky_split 1 2 10_88_bn_leaky 10_88_bn_leaky_split_0 10_88_bn_leaky_split_1
Crop                   11_96                1 1 10_88_bn_leaky_split_0 11_96 2=64 3=52 4=52 5=64
Convolution            12_101               1 1 11_96 12_101 0=64 1=3 2=1 3=1 4=1 5=0 6=36864
BatchNorm              12_101_bn            1 1 12_101 12_101_bn 0=64 1=.00001
ReLU                   12_101_bn_leaky      1 1 12_101_bn 12_101_bn_leaky 0=0.1
Split                  12_101_bn_leaky_split 1 2 12_101_bn_leaky 12_101_bn_leaky_split_0 12_101_bn_leaky_split_1
Convolution            13_109               1 1 12_101_bn_leaky_split_0 13_109 0=64 1=3 2=1 3=1 4=1 5=0 6=36864
BatchNorm              13_109_bn            1 1 13_109 13_109_bn 0=64 1=.00001
ReLU                   13_109_bn_leaky      1 1 13_109_bn 13_109_bn_leaky 0=0.1
Concat                 14_117               2 1 13_109_bn_leaky 12_101_bn_leaky_split_1 14_117
Convolution            15_120               1 1 14_117 15_120 0=128 1=1 2=1 3=1 4=0 5=0 6=16384
BatchNorm              15_120_bn            1 1 15_120 15_120_bn 0=128 1=.00001
ReLU                   15_120_bn_leaky      1 1 15_120_bn 15_120_bn_leaky 0=0.1
Concat                 16_128               2 1 10_88_bn_leaky_split_1 15_120_bn_leaky 16_128
Pooling                17_131               1 1 16_128 17_131 0=0 1=2 2=2 5=1 3=0 13=0 14=0 15=0
Convolution            18_135               1 1 17_131 18_135 0=256 1=3 2=1 3=1 4=1 5=0 6=589824
BatchNorm              18_135_bn            1 1 18_135 18_135_bn 0=256 1=.00001
ReLU                   18_135_bn_leaky      1 1 18_135_bn 18_135_bn_leaky 0=0.1
Split                  18_135_bn_leaky_split 1 2 18_135_bn_leaky 18_135_bn_leaky_split_0 18_135_bn_leaky_split_1
Crop                   19_143               1 1 18_135_bn_leaky_split_0 19_143 2=128 3=26 4=26 5=128
Convolution            20_148               1 1 19_143 20_148 0=128 1=3 2=1 3=1 4=1 5=0 6=147456
BatchNorm              20_148_bn            1 1 20_148 20_148_bn 0=128 1=.00001
ReLU                   20_148_bn_leaky      1 1 20_148_bn 20_148_bn_leaky 0=0.1
Split                  20_148_bn_leaky_split 1 2 20_148_bn_leaky 20_148_bn_leaky_split_0 20_148_bn_leaky_split_1
Convolution            21_156               1 1 20_148_bn_leaky_split_0 21_156 0=128 1=3 2=1 3=1 4=1 5=0 6=147456
BatchNorm              21_156_bn            1 1 21_156 21_156_bn 0=128 1=.00001
ReLU                   21_156_bn_leaky      1 1 21_156_bn 21_156_bn_leaky 0=0.1
Concat                 22_164               2 1 21_156_bn_leaky 20_148_bn_leaky_split_1 22_164
Convolution            23_167               1 1 22_164 23_167 0=256 1=1 2=1 3=1 4=0 5=0 6=65536
BatchNorm              23_167_bn            1 1 23_167 23_167_bn 0=256 1=.00001
ReLU                   23_167_bn_leaky      1 1 23_167_bn 23_167_bn_leaky 0=0.1
Split                  23_167_bn_leaky_split 1 2 23_167_bn_leaky 23_167_bn_leaky_split_0 23_167_bn_leaky_split_1
Concat                 24_175               2 1 18_135_bn_leaky_split_1 23_167_bn_leaky_split_0 24_175
Pooling                25_178               1 1 24_175 25_178 0=0 1=2 2=2 5=1 3=0 13=0 14=0 15=0
Convolution            26_182               1 1 25_178 26_182 0=512 1=3 2=1 3=1 4=1 5=0 6=2359296
BatchNorm              26_182_bn            1 1 26_182 26_182_bn 0=512 1=.00001
ReLU                   26_182_bn_leaky      1 1 26_182_bn 26_182_bn_leaky 0=0.1
Convolution            27_192               1 1 26_182_bn_leaky 27_192 0=256 1=1 2=1 3=1 4=0 5=0 6=131072
BatchNorm              27_192_bn            1 1 27_192 27_192_bn 0=256 1=.00001
ReLU                   27_192_bn_leaky      1 1 27_192_bn 27_192_bn_leaky 0=0.1
Split                  27_192_bn_leaky_split 1 2 27_192_bn_leaky 27_192_bn_leaky_split_0 27_192_bn_leaky_split_1
Convolution            28_200               1 1 27_192_bn_leaky_split_0 28_200 0=512 1=3 2=1 3=1 4=1 5=0 6=1179648
BatchNorm              28_200_bn            1 1 28_200 28_200_bn 0=512 1=.00001
ReLU                   28_200_bn_leaky      1 1 28_200_bn 28_200_bn_leaky 0=0.1
Convolution            29_208               1 1 28_200_bn_leaky 29_208 0=18 1=1 2=1 3=1 4=0 5=1 6=9216
Convolution            32_237               1 1 27_192_bn_leaky_split_1 32_237 0=128 1=1 2=1 3=1 4=0 5=0 6=32768
BatchNorm              32_237_bn            1 1 32_237 32_237_bn 0=128 1=.00001
ReLU                   32_237_bn_leaky      1 1 32_237_bn 32_237_bn_leaky 0=0.1
Interp                 33_245               1 1 32_237_bn_leaky 33_245 0=1 1=2.f 2=2.f
Concat                 34_248               2 1 33_245 23_167_bn_leaky_split_1 34_248
Convolution            35_251               1 1 34_248 35_251 0=256 1=3 2=1 3=1 4=1 5=0 6=884736
BatchNorm              35_251_bn            1 1 35_251 35_251_bn 0=256 1=.00001
ReLU                   35_251_bn_leaky      1 1 35_251_bn 35_251_bn_leaky 0=0.1
Convolution            36_259               1 1 35_251_bn_leaky 36_259 0=18 1=1 2=1 3=1 4=0 5=1 6=4608
Yolov3DetectionOutput  detection_out        2 1 29_208 36_259 output 0=1 1=3 2=0.250000 -23304=12,10.000000,14.000000,23.000000,27.000000,37.000000,58.000000,81.000000,82.000000,135.000000,169.000000,344.000000,319.000000 -23305=6,3.000000,4.000000,5.000000,1.000000,2.000000,3.000000 -23306=2,33.599998,16.799999`

This is my .bin file:

[model.zip](https://github.com/Tencent/ncnn/files/6233302/model.zip)

**Comment by huuson235** [comment]
I have the same problem.

**Comment by chuan298** [comment]
Thank you @nihui
