### ISSUE TITLE
ARM Linux 上如何编出带有neon支持的库

### ISSUE THREAD

**Issue by wonderzy** [Tencent/ncnn#28]
我在linux上make出来的静态库，默认是x86的,conv层也是conv_x86， 请问我需要怎样才能在Linux上编出带neon支持的库？

**Comment by nihui** [comment]
cmake 里头暂时只对 android 和 ios 开了 neon，要自己改下那边的判断。。

**Comment by wonderzy** [comment]
请问需要在哪边改？

**Comment by nihui** [comment]
src/CMakeLists.txt 37行这里，加上对应的 system 和 arch 条件
ugly 一点就直接 TRUE 应该也可以 ...

**Comment by wonderzy** [comment]
万分感谢

**Comment by ctgushiwei** [comment]
@wonderzy   请问比编译出来带neon支持的库了吗？怎么解决的，我在src/CMakeLists.txt 37行这里，加上对应的 system 和 arch 条件一样没有效果

**Comment by wonderzy** [comment]
那你就用ugly一点的写法咯 @ctgushiwei
