### ISSUE TITLE
请教NEON优化

### ISSUE THREAD

**Issue by yoershine** [Tencent/ncnn#280]
在卷积计算中，为什么针对AARCH64使用NEON 的C指令实现，而非AARCH64使用Inline Assembler 来实现呢？请大神给解释下原因。

**Comment by bigbigzxl** [comment]
这个项目工作量还是很巨的，各个部分得一步一步来实现的吧，话说最近这部分有补全来着！

**Comment by nihui** [comment]
aarch64 目前也采用 inline asm 实现了
