### ISSUE TITLE
Xavier使用ncnn报出关于glslang的一些问题

### ISSUE THREAD

**Issue by XHuaSheng** [Tencent/ncnn#2808]
ncnn在Xavier上编译通过后，在调用ncnn库的工程编译时出现如下的问题，这个需要怎们解决下
![图片](https://user-images.githubusercontent.com/29329700/113268123-a3fa2300-9309-11eb-8104-6dce99fadc32.png)

**Comment by NEO-237** [comment]
我在尝试使用vulkan加速时，也遇到了这个问题，请问最终是如何解决的呢？
