### ISSUE TITLE
Yolo examples fail on Raspberry Pi 4

### ISSUE THREAD

**Issue by Qengineering** [Tencent/ncnn#2812]
The NanoDet, YoloV2 and YoloV3 examples fail on a Raspberry Pi 4 - aarch64. 
Loading the model.bin seems to be the problem. 
BTW, YoloV4 and YoloV5 works just fine.

Raspberry Pi 4 - 64-bit OS - 1950 MHz - 8 GB RAM.

```
# build 64-bit ncnn
$ cmake -DNCNN_BUILD_EXAMPLES=ON -DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-linux-gnu.toolchain.cmake ..
$ make -j4
$ make install
```
Please see screen dump below
![image](https://user-images.githubusercontent.com/44409029/113474359-dd4ca300-946f-11eb-904a-7f35767e1e9a.png)

**Comment by notplus** [comment]
Maybe you can copy model files (bin/param) to the examples folder to solve it? You can download the model files from [models](https://github.com/nihui/ncnn-assets/tree/master/models).

**Comment by Qengineering** [comment]
All required models (bin and param) are already in the example folder. Only, you don't see them in the screen dump, because I've downloaded them later and copied thereafter. From the same repo as you suggested. BTW, all examples work fine on a Jetson Nano.

**Comment by nihui** [comment]
I think it is the compiler fault that generating LSE instructions, which are not supported by raspberry pi 4.
Here is a quick and dirty workaround

open src/allocator.h and jump to line 103, you will see a large code block related to atomic builtin implementation.
delete all of them and use the naive one
```
static inline int NCNN_XADD(int* addr, int delta)
{
    int tmp = *addr;
    *addr += delta;
    return tmp;
}
```

**Comment by Qengineering** [comment]
Thanks @nihui! works like charm!

**Comment by nihui** [comment]
@Qengineering 

I am trying to work out a better fix.
Could you please paste the gdb backtrace info when illegal instruction error happens ? 
A debug build may be more helpful.

**Comment by Qengineering** [comment]
@nihui 

With pleasure.
I'm not sure how to use gdb backtrace on a RPi 64-OS, but here are ValGrind and a screen dump.

valgrind --version
valgrind-3.14.0
valgrind  --tool=cachegrind "/home/pi/software/YoloV2/bin/Debug/YoloV2" parking.jpg
==13550== Cachegrind, a cache and branch-prediction profiler
==13550== Copyright (C) 2002-2017, and GNU GPL'd, by Nicholas Nethercote et al.
==13550== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==13550== Command: /home/pi/software/YoloV2/bin/Debug/YoloV2 parking.jpg
==13550== 
--13550-- Warning: Cannot auto-detect cache config, using defaults.
--13550--          Run with -v to see.
==13550== brk segment overflow in thread #1: can't grow to 0x4ae5000
==13550== (see section Limitations in user manual)
==13550== NOTE: further instances of this message will not be shown
ARM64 front end: load_store
disInstr(arm64): unhandled instruction 0xB8E10001
disInstr(arm64): 1011'1000 1110'0001 0000'0000 0000'0001
==13550== valgrind: Unrecognised instruction at address 0x2992fc.
==13550==    at 0x2992FC: ncnn::Mat::reshape(int, int, ncnn::Allocator*) const (in /home/pi/software/YoloV2/bin/Debug/YoloV2)
==13550==    by 0x41246F: ncnn::ConvolutionDepthWise_arm::create_pipeline(ncnn::Option const&) (in /home/pi/software/YoloV2/bin/Debug/YoloV2)
==13550==    by 0x144B57: ncnn::Net::load_model(ncnn::DataReader const&) (in /home/pi/software/YoloV2/bin/Debug/YoloV2)
==13550==    by 0x144E3B: ncnn::Net::load_model(char const*) (in /home/pi/software/YoloV2/bin/Debug/YoloV2)
==13550==    by 0x12F9EB: main (yolov2.cpp:140)
==13550== Your program just tried to execute an instruction that Valgrind
==13550== did not recognise.  There are two possible reasons for this.
==13550== 1. Your program has a bug and erroneously jumped to a non-code
==13550==    location.  If you are running Memcheck and you just saw a
==13550==    warning about a bad jump, it's probably your program's fault.
==13550== 2. The instruction is legitimate but Valgrind doesn't handle it,
==13550==    i.e. it's Valgrind's fault.  If you think this is the case or
==13550==    you are not sure, please let us know and we'll try to fix it.
==13550== Either way, Valgrind will now raise a SIGILL signal which will
==13550== probably kill your program.

![2021-04-06-144705_1024x768_scrot](https://user-images.githubusercontent.com/44409029/113714101-57875c80-96e8-11eb-8833-a57f08f92a11.png)

**Comment by nihui** [comment]
And another cleaner workaround may be disabling armv8.2 optimized kernel completely via ```cmake -DNCNN_ARM82=OFF ..```

**Comment by nihui** [comment]
shall be fixed by https://github.com/Tencent/ncnn/pull/2819

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/d7cbc055f339529d54c43379e742db3dd0cd521e

**Comment by Qengineering** [comment]
Thank you so much!
