### ISSUE TITLE
NCNN在iOS端的部署问题

### ISSUE THREAD

**Issue by TonyTangYu** [Tencent/ncnn#282]
我尝试https://github.com/Tencent/ncnn/wiki/how-to-build   这个网页中的build for iOS，在建立交叉编译环境（https://github.com/tpoechtrager/cctools-port）的时候，安装Apple’s TAPI library中命令 [INSTALLPREFIX=/home/user/cctools] ./build.sh，请问 [INSTALLPREFIX=/home/user/cctools] 这个是什么意思呢？
另外，在执行命令./install.sh的时候出现了cp: the -R and -r options may not be specified together这样的问题，不知道怎么解决。

**Comment by wangshouye** [comment]
+1

**Comment by BookOfStopHere** [comment]
@TonyTangYu  refer to https://github.com/tpoechtrager/apple-libtapi/issues/5

**Comment by fangzhiming** [comment]
INSTALLPREFIX=你自己新建一个文件夹（记得运行该命令的时候，把 [ ] 去掉）

**Comment by PowerOwner** [comment]
@TonyTangYu 
您那边解决了cp: the -R and -r options may not be specified together这个错误吗？

**Comment by PowerOwner** [comment]
@BookOfStopHere 
请教一下，如何删除 -r 选项，能否提供一下具体的操作方式；

**Comment by wangshouye** [comment]
> @BookOfStopHere
> Ask me how to delete the - R option, can you provide a specific way of operation

给我发一个你的邮箱

**Comment by PowerOwner** [comment]
> > @BookOfStopHere
> > Ask me how to delete the - R option, can you provide a specific way of operation
> 
> 给我发一个你的邮箱

@wangshouye 
cheers0724@hotmail.com 谢谢！

**Comment by nihui** [comment]
release 页面有编译好的 ios framework 可用，推荐直接下载使用
