### ISSUE TITLE
x86 SSE Fallback mechanism

### ISSUE THREAD

**Issue by Timen** [Tencent/ncnn#2824]
@nihui I saw that there is a code path selection mechanism in the android code which selects certain code paths during runtime based on which functions the SOC does and doesn't support. I was just wondering if such a similar setup could work for the x86 code where if a CPU supports AVX it would select AVX based code paths, but if a CPU doesn't support AVX it would automatically fallback on SSE. I guess the difficulty is managing automatic compiler optimisations, but it might be possible to compile only files that use AVX intrinsics with AVX enabled, and for everything else only use the SSE optimisations. Or am I overlooking something here?

**Comment by nihui** [comment]
As long as the NCNN_RUNTIME_CPU cmake option enabled, which is the default case, most source files will be compiled with SSE2 as the baseline arch, while a shadowed AVX2 one will be generated for all sources under layer/x86 folder. These shadowed AVX2 source will then compiled with AVX2 arch. CPU capability will be checked on runtime, and a corresponding layer instance for the cpu arch is created.

https://github.com/Tencent/ncnn/blob/68468dccbd842c716345c7d44fc7d634fe901c8a/src/layer.cpp#L250

**Comment by Timen** [comment]
I did not find that small piece of code, but that is really cool 👍 Thanks for clearing that up!
