### ISSUE TITLE
如何不编译int8算子？

### ISSUE THREAD

**Issue by PYNing** [Tencent/ncnn#2828]
@nihui 大大好，因为项目模型精度的限制，暂时只使用FP32算子。
为了使编译出来的so更小，请问如何能够不编译int8算子（例如有没有现成的编译选项，或者只能手删改代码了 ）？
谢谢大大~

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/2839

**Comment by nihui** [comment]
merged
