### ISSUE TITLE
binaryop.cpp:  there is an error in binary_op when a.dims == 2 && b.dims == 1

### ISSUE THREAD

**Issue by hust-cxl** [Tencent/ncnn#2837]
![image](https://user-images.githubusercontent.com/30313363/114383698-6eceba00-9bc0-11eb-8237-fa08e68c0052.png)

As the picture depicted,  in binary_op function, there is a logical error

const float b0 = b[y] should be replaced by const float b0 = b[x], and it should be placed in the loop of x

**Comment by nihui** [comment]
The code is correct according to ncnn broadcasting rule, which is opposite to numpy broadcasting.
https://github.com/Tencent/ncnn/wiki/binaryop-broadcasting
see type 12
