### ISSUE TITLE
ncnn是否支持非对称量化

### ISSUE THREAD

**Issue by retonym** [Tencent/ncnn#2854]
感觉非对称量化在数据正负不均衡的时候精度会更高。 
从 quantize layer上看 https://github.com/Tencent/ncnn/blob/master/src/layer/quantize.cpp， 目前ncnn是不是只支持对称量化？

**Comment by nihui** [comment]
是的，只支持对称量化
量化的目的是为了速度更快，对称量化在 cpu kernel 实现上比非对称量化更高效些
ncnn 是支持  per-channel 量化的，精度会更好些

以及，最初提倡非对称量化的 tensorflow 也因为推理效率，转向对称量化了（
