### ISSUE TITLE
shufflefacenet convert fails

### ISSUE THREAD

**Issue by jeonginseo** [Tencent/ncnn#2855]
Hi, I implemented shufflefacenet with mxnet and tried to convert ncnn.
(the model based on : https://github.com/osmr/imgclsmob/blob/master/gluon/gluoncv2/models/shufflenetv2.py)

Then I ran the mxnet2ncnn, it finished without error, but its result was weird.
The connections between some layers were broken(I used Netron to check model).
What can I do for this?

Thanks in advance.

source : https://www.dropbox.com/s/afuf44jkffc1muu/shufflenet.7z?dl=0
conversion result : https://www.dropbox.com/s/pt9axh19g3n12ab/shufflenet_ncnn.7z?dl=0

**Comment by nihui** [comment]
Hi, Thanks for your report

The cause of this problem is that the model json file contains multiple op nodes with same name, eg shufflenetv2_backbone0_stage1_shuffleunit_p0_prelu0_fwd

I've figured out a workaround in mxnet2ncnn.
