### ISSUE TITLE
PC端vulkan版ncnn加载模型耗时很长

### ISSUE THREAD

**Issue by lsy0816** [Tencent/ncnn#2856]
你好，我这边尝试在windows上用vulkan版ncnn加载yolov5x模型，加载模型的时间长达十几秒，占了90%，请问有什么办法可以解决吗

**Comment by lexuszhi1990** [comment]
我这边自行编译windows的vulkan ncnn版本，加载和运行都很正常。 感觉先从 模型大小  显卡配置来做排查

**Comment by nihui** [comment]
最新的ncnn对加载过程有优化，可以更新下再试试，如有问题，可reopen issue继续交流
