### ISSUE TITLE
卷积核权重查看

### ISSUE THREAD

**Issue by jolt2017** [Tencent/ncnn#2861]
nihui 大佬 你好，请问我把模型load到 ncnn 里了，怎么查看net中 指定卷积权重能？）

**Comment by nihui** [comment]
把 ncnn 的模型 param bin 两个文件一起拖入 netron 工具中，右侧点开可以查看卷积的权重数值

**Comment by jolt2017** [comment]
> 把 ncnn 的模型 param bin 两个文件一起拖入 netron 工具中，右侧点开可以查看卷积的权重数值

谢谢，很好用，配合 ncnn 里面的 extractor 简直了。

**Comment by WX-yh** [comment]
请问量化为int8之后的权重怎么查看呢？
