### ISSUE TITLE
A question about Yolact make_prior() 

### ISSUE THREAD

**Issue by mathmax12** [Tencent/ncnn#2875]
@nihui 
Thanks for the great work.
I followed the instruction in https://zhuanlan.zhihu.com/p/128974102 to convert an onnx model by removed the post-processing.
I got a question about the `make_prior()`  in the class `PredictionModule()`
In the orginal python code we can see the  make_prior() is not in the `"self.detect(pred_outs, self)"`
https://github.com/dbolya/yolact/blob/master/yolact.py#L453

So that means the `make_prior() ` should be already included in the onnx when converting the model to onnx by removing the `"self.detect(pred_outs, self)"` . But in the yolact.cpp why we still need to make the priors after the output of the model?
https://github.com/Tencent/ncnn/blob/master/examples/yolact.cpp#L158

Thanks.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
