### ISSUE TITLE
faster rcnn generates wrong results on GPU, but correct results on Jetson Xavier

### ISSUE THREAD

**Issue by minhdo3000** [Tencent/ncnn#2882]
Hi everyone,
I ran a faster rcnn example from ncnn library. It works correctly on CPU but generates wrong results on Jetson Xavier (it generates a lot of bounding boxes of person with confidence socres is 5.8%). Other examples from ncnn work fine on Jetson Xavier's GPU. Only faster rcnn happened this issues.  Do you know what is the reason?

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
fp16 precision is not enough to keep lrn vulkan correct.
fixed by forcing fp32 in lrn vulkan.
Thanks for your report !
