### ISSUE TITLE
最新版的ncnn examples/retinaface 关键点不对

### ISSUE THREAD

**Issue by sonixixi** [Tencent/ncnn#2885]
最新版的ncnn, 在arm-android上跑 examples/retinaface 关键点不对，x86平台跑出来是对的，20191113的版本跑出来是对的,

**Comment by nihui** [comment]
> 最新版的ncnn, 在arm-android上跑 examples/retinaface 关键点不对，x86平台跑出来是对的，20191113的版本跑出来是对的,

最新版本默认开启了 fp16 运算加速

load_param 前设置开关可以禁用
```
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
```

**Comment by sonixixi** [comment]
👌

**Comment by nihui** [comment]
这个commit修复了一处fp16计算的bug，可能有帮助 https://github.com/Tencent/ncnn/commit/7a1e015d7213028b6ead7f6529e85bfd11cb6d06

**Comment by sonixixi** [comment]
试了一下 landmark好了

**Comment by sonixixi** [comment]
> > 最新版的ncnn, 在arm-android上跑 examples/retinaface 关键点不对，x86平台跑出来是对的，20191113的版本跑出来是对的,
> 
> 最新版本默认开启了 fp16 运算加速
> 
> load_param 前设置开关可以禁用
> ```
> net.opt.use_fp16_storage = false;
> net.opt.use_fp16_arithmetic = false;
> ```

最新版把fp16加速关了跑fp32 在arm android跑比20191113版本fp32的速度 慢了好多

**Comment by nihui** [comment]
> > > 最新版的ncnn, 在arm-android上跑 examples/retinaface 关键点不对，x86平台跑出来是对的，20191113的版本跑出来是对的,
> > 
> > 
> > 最新版本默认开启了 fp16 运算加速
> > load_param 前设置开关可以禁用
> > ```
> > net.opt.use_fp16_storage = false;
> > net.opt.use_fp16_arithmetic = false;
> > ```
> 
> 最新版把fp16加速关了跑fp32 在arm android跑比20191113版本fp32的速度 慢了好多

retinaface的耗时还包括后处理部分，图片中人脸数不同，整体耗时也会不同
关于模型推理，我刚拿20191113和最新的master代码，fp32测试耗时并没有差很多

|qcom855单线程fp32|20191113|master|
|---|---|---|
|大核|35.19|34.05|
|小核|189.46|184.14|
