### ISSUE TITLE
lstm int8前向

### ISSUE THREAD

**Issue by as754770178** [Tencent/ncnn#2889]
参考教程`https://github.com/Tencent/ncnn/wiki/quantized-int8-inference` 将 lstm模型转为int8，但Debug模式下，代码运行和非量化没有区别。
lstm在windows下，没有实现量化前向？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5435

**Comment by nihui** [comment]
implemented in https://github.com/Tencent/ncnn/commit/08b7d99a75ad70fdc5c1d9e5debc675fce5e83a9
