### ISSUE TITLE
caffe2ncnn出错，protobuf相关

### ISSUE THREAD

**Issue by maydaying** [Tencent/ncnn#29]
caffe2ncnn转换example里的squeezenet是没问题的，但刚尝试转换一个 [face verification的caffe模型](https://github.com/AlfredXiangWu/face_verification_experiment) ，就出现下面的错误
<img width="563" alt="0a88eb84-cf10-4174-83d7-dc1ad2a54037" src="https://user-images.githubusercontent.com/5717913/28567933-a7017850-7166-11e7-8f6f-bab6403123ec.png">

**Comment by nihui** [comment]
upgrade_net_proto_text [老prototxt] [新prototxt]
upgrade_net_proto_binary [老caffemodel] [新caffemodel]
升级下看看？
lightcnn 这个model我曾经转过，是可以用的

**Comment by maydaying** [comment]
lightcnn的A和B模型转换后是可以用的。但C模型是新模型，在用caffe2ncnn的时候它出现了截图上的错误，proto文件到‘fc2’层没问题，bin文件只有21.9M（原C模型124.6M)

**Comment by walegahaha** [comment]
make完了之后怎么转换example里的squeezenet？
谢谢

**Comment by maydaying** [comment]
请参考作者写的指南：https://github.com/Tencent/ncnn/wiki/ncnn-组件使用指北-alexnet

**Comment by nihui** [comment]
#68  看这里
