### ISSUE TITLE
使用 ncnn2mem 载入方式，提示数组越界

### ISSUE THREAD

**Issue by GarrickLin** [Tencent/ncnn#290]
使用 `ncnn2mem` 生成文件 `det1.mem.h`, `det1.id.h`, `det1.param.bin` 
代码中直接载入内存数组
```
#include "det1.mem.h"
#include "det1.id.h"
_pnet.load_param(det1_param_bin);
_pnet.load_model(det1_bin);
```
提取时直接通过 `id` 提取
```
ext.extract(det1_param_id::BLOB_prob1, prob);
ext.extract(det1_param_id::BLOB_conv4_2, conv42);
```
报错
```
Expression: vector subscript out of range，数组越界
并且生成的 det1.param.bin 文件全程没有用上
```
感觉用法上应该哪里不对，求指点！
（ 使用find blob by name的话也会报错找不到，所以用了find by id ）

**Comment by GarrickLin** [comment]
抱歉我的错，我忘记把输入的地方也改过来了
```
ext.input(data_idx, in);
```

**Comment by WIll-Xu35** [comment]
@GarrickLin 您好，我也在尝试使用加密的param.bin文件来跑inference。但是我对c++不是很熟悉，wiki里也没有找到使用param.bin的详细的教程，能否请教一下使用param.bin和使用普通的param在inference上有什么区别？具体的代码上有什么区别呢？谢谢
