### ISSUE TITLE
load_model的时候出现异常 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突

### ISSUE THREAD

**Issue by wangyu09** [Tencent/ncnn#2904]
使用load_param时没有问题，但load_model的时候，出现了这个异常
`0x00007FF7771FA9B5 处(位于 NCNN.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突。`
我的环境是 wondows10 + vs 2017。请问是什么原因呢

**Comment by HwanWoongLee** [comment]
@wangyu09  did you solved this problem?
