### ISSUE TITLE
make -j4这步报错google/protobuf/inlined_string_field.h: 没有那个文件或目录

### ISSUE THREAD

**Issue by liguoyu666** [Tencent/ncnn#2908]
从码云上下载的最新版本的ncnn，protoc安装的是github上的，版本为libprotoc 3.15.5，编译ncnn在`make -j4`时报错如下，查看issues发现2018年也有报这个错的，不过看回答，lihui大佬已经更新解决了，但现在又遇到了同样的问题。

(base) lgy@lgy:~/tools/ncnn/build$ make -j4
[  1%] Built target mxnet2ncnn
[  1%] Built target ncnnmerge
[  1%] Built target ncnn-generate-spirv
[  1%] Building CXX object tools/caffe/CMakeFiles/caffe2ncnn.dir/caffe2ncnn.cpp.o
[  1%] Building CXX object tools/caffe/CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o
In file included from /home/lgy/tools/ncnn/tools/caffe/caffe2ncnn.cpp:19:0:
/home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers. Please
  ^
/home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
[  2%] Building CXX object tools/onnx/CMakeFiles/onnx2ncnn.dir/onnx2ncnn.cpp.o
[  3%] Built target darknet2ncnn
In file included from /home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.cc:4:0:
/home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers. Please
  ^
/home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /home/lgy/tools/ncnn/tools/onnx/onnx2ncnn.cpp:15:0:
/home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers. Please
  ^
/home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /home/lgy/tools/ncnn/tools/caffe/caffe2ncnn.cpp:19:0:
/home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.h:28:50: fatal error: google/protobuf/inlined_string_field.h: 没有那个文件或目录
compilation terminated.
tools/caffe/CMakeFiles/caffe2ncnn.dir/build.make:70: recipe for target 'tools/caffe/CMakeFiles/caffe2ncnn.dir/caffe2ncnn.cpp.o' failed
make[2]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/caffe2ncnn.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
In file included from /home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.cc:4:0:
/home/lgy/tools/ncnn/build/tools/caffe/caffe.pb.h:28:50: fatal error: google/protobuf/inlined_string_field.h: 没有那个文件或目录
compilation terminated.
tools/caffe/CMakeFiles/caffe2ncnn.dir/build.make:94: recipe for target 'tools/caffe/CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o' failed
[ 96%] Built target ncnn
make[2]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o] Error 1
CMakeFiles/Makefile2:393: recipe for target 'tools/caffe/CMakeFiles/caffe2ncnn.dir/all' failed
make[1]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 96%] Building CXX object tools/onnx/CMakeFiles/onnx2ncnn.dir/onnx.pb.cc.o
In file included from /home/lgy/tools/ncnn/tools/onnx/onnx2ncnn.cpp:15:0:
/home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.h:28:50: fatal error: google/protobuf/inlined_string_field.h: 没有那个文件或目录
compilation terminated.
tools/onnx/CMakeFiles/onnx2ncnn.dir/build.make:70: recipe for target 'tools/onnx/CMakeFiles/onnx2ncnn.dir/onnx2ncnn.cpp.o' failed
make[2]: *** [tools/onnx/CMakeFiles/onnx2ncnn.dir/onnx2ncnn.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
In file included from /home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.cc:4:0:
/home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers. Please
  ^
/home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.cc:4:0:
/home/lgy/tools/ncnn/build/tools/onnx/onnx.pb.h:28:50: fatal error: google/protobuf/inlined_string_field.h: 没有那个文件或目录
compilation terminated.
tools/onnx/CMakeFiles/onnx2ncnn.dir/build.make:94: recipe for target 'tools/onnx/CMakeFiles/onnx2ncnn.dir/onnx.pb.cc.o' failed
make[2]: *** [tools/onnx/CMakeFiles/onnx2ncnn.dir/onnx.pb.cc.o] Error 1
CMakeFiles/Makefile2:503: recipe for target 'tools/onnx/CMakeFiles/onnx2ncnn.dir/all' failed
make[1]: *** [tools/onnx/CMakeFiles/onnx2ncnn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
