### ISSUE TITLE
libvulkan.so error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by guoqiang0148666** [Tencent/ncnn#2910]
Hi, Thanks for your excellent works~!

I compile ncnn with vulkan on my NVIDIA jetson nano, the vulkan version is 1.1.114.0 (My jetpack 4.1), l follow this command to build ncnn
```
cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=ON -DNCNN_SYSTEM_GLSLANG=ON -DNCNN_BUILD_EXAMPLES=ON -DCMAKE_PREFIX_PATH=/home/zpy/guo-temp/protobuf/ -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake ..
```
Unfortunately, i meet a linking error in 95% building process
```
[ 95%] Linking CXX executable benchncnn
/home/zpy/guo-temp/1.2.176.1/x86_64/lib/libvulkan.so: error adding symbols: File in wrong format
```

I am a fresher in ncnn, anyone could help me and any suggesstion will be welcomed.

Thanks

**Comment by ThomsonW** [comment]
I met the same problem, and the problem was solved by running cmake and make commands with sudo privilege. you can try it on your own env.

**Comment by YandongJi** [comment]
I'm having this problem too and running with sudo did not solve the problem...

**Comment by nihui** [comment]
The latest master branch supports compiling gpu functions without installing vulkan-sdk. You can give it a try.
If it doesn’t work, feel free to reopen the issue and post your findings.
