### ISSUE TITLE
20210507 版本int8在cortexA53 上的效果问题

### ISSUE THREAD

**Issue by LinkenMu** [Tencent/ncnn#2912]
编译使用aarch64-linux-gnu toolchain   -DNCNN_OPENMP=OFF
用benchmark 在xilinx的开发板上测试，param文件使用的是benchmark 下的param文件。结果如下
./benchncnn 10 1 0 -1
syscall error -1
loop_count = 10
num_threads = 1
powersave = 0
gpu_device = -1
cooling_down = 1
            resnet50  min = 1083.73  max = 1091.52  avg = 1087.53
       resnet50_int8  min =  944.09  max =  946.70  avg =  945.03
      squeezenet_ssd  min =  315.19  max =  317.97  avg =  316.50
 squeezenet_ssd_int8  min =  298.50  max =  298.93  avg =  298.71
       mobilenet_ssd  min =  467.89  max =  468.15  avg =  468.02
  mobilenet_ssd_int8  min =  409.38  max =  409.97  avg =  409.76

发现int8跟硬浮点的时间没有拉开差距，请问是操作问题还是什么情况？

**Comment by nihui** [comment]
建议更新最新ncnn再测试看看，有更多int8优化
如有问题，可reopen issue继续交流
