### ISSUE TITLE
0507 版本，INT8 推断报错，fault addr 

### ISSUE THREAD

**Issue by edvardHua** [Tencent/ncnn#2916]
Demo 地址：https://github.com/edvardHua/NNBenchmark

报错的截图如下：

<img width="1514" alt="Screen Shot 2021-05-16 at 8 41 57 PM" src="https://user-images.githubusercontent.com/4105217/118398092-b2b65280-b689-11eb-89b3-f61e4339b766.png">

环境如下：
测试设备：魅族 16th
Flyme 版本：8.20.6.30
安卓版本：8.1.0
ndk: 21
sdk: 30, (min > 24)
platform: MacOS 10.15.6
NCNN: 0507

**Comment by nihui** [comment]
adb shell 里跑 benchncnn 有问题吗？

**Comment by edvardHua** [comment]
好像也运行不了，不过是 benchncnn 直接报错了。

具体的如下图所示：

![Screen Shot 2021-05-17 at 10 30 03 AM](https://user-images.githubusercontent.com/4105217/118425048-ef6e6200-b6fa-11eb-9b0e-22bbe0e4c983.png)

**Comment by nihui** [comment]
已确认

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/afc02d57f90b67ee31e99d1ac4398623baa96cff
qcom845 这个 cpu 支持 fp16 fma 但不支持 int8 dotprod 指令，因此 int8 速度应该会慢于 fp16

**Comment by nihui** [comment]
最新的 git master 代码已修复

**Comment by edvardHua** [comment]
Nihui 大佬强💪

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: nihui ***@***.***>
发送时间: Thursday, May 20, 2021 3:07:33 PM
收件人: Tencent/ncnn ***@***.***>
抄送: edvardHua ***@***.***>; Author ***@***.***>
主题: Re: [Tencent/ncnn] 0507 版本，INT8 推断报错，fault addr (#2916)


Closed #2916<https://github.com/Tencent/ncnn/issues/2916>.
