### ISSUE TITLE
Run-Time Check Failure in reduction.cpp

### ISSUE THREAD

**Issue by paleomoon** [Tencent/ncnn#2921]
Hi, I'm trying to convert a model to ncnn, the original Pytorch code is [here](https://github.com/sailyung/human-pose-estimation), I use the following code to export lpn.onnx:

```
input_name = ['image']
output_name = ['heatmap']
torch.onnx.export(model, input,'lpn.onnx', input_names=input_name, output_names=output_name, verbose=True,opset_version=11)
```
onnx-simplifier :

```
python -m onnxsim lpn.onnx lpn-sim.onnx
```
convert to ncnn:
```
onnx2ncnn.exe lpn-sim.onnx lpn-sim.param lpn-sim.bin
```
ncnnoptimize:
```
ncnnoptimize.exe lpn-sim.param lpn-sim.bin lpn-opt.param lpn-opt.bin
```
all the above steps looks normal.

when run the inference code in vs2017, an exception raised in reduction.cpp: 

![ex](https://user-images.githubusercontent.com/17964314/118463837-cbc70e00-b732-11eb-9d48-35afbc710dcc.png)

I found this occours after ReduceMean_14 op:

```
ex.input("image", in);
ex.extract("536", out); //error
```
```
Reduction                ReduceMean_14            1 1 534_splitncnn_1 536 0=3 1=0 -23303=3,-3,-2,-1 4=1
```

can you help me? thanks!

ncnn 20210507

pytorch 1.5.1

onnx 1.9.0 

onnx-simplifier 0.3.5

onnxoptimizer 0.2.6

onnxruntime 1.7.0

[ncnn-pose.zip](https://github.com/Tencent/ncnn/files/6492749/ncnn-pose.zip)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
