### ISSUE TITLE
同一个模型，多线程并行运行，如何进行？Nvidia显卡  centos7

### ISSUE THREAD

**Issue by sdnusqy-art** [Tencent/ncnn#2926]
同一个模型，多线程并行运行，如何进行？ Nvidia显卡  centos7
我用std::thread多线程并行进行推理， 尝试了两种方案，
1. 初始化一个Net实例
2. 初始化线程个数相同的Net实例
当std::thread个数大于1时这两种方式均会崩溃，为1时正常 。
支持多线程并行吗，如果支持应该如何使用

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/vulkan-notes#batch-inference

单卡：初始化一个Net实例，多线程各自创建 Extractor 使用
多卡：初始化卡数Net实例，每个卡上多线程各自创建 Extractor 使用，可以 M x N 并行

**Comment by sdnusqy-art** [comment]
> https://github.com/Tencent/ncnn/wiki/vulkan-notes#batch-inference
> 
> 单卡：初始化一个Net实例，多线程各自创建 Extractor 使用
> 多卡：初始化卡数Net实例，每个卡上多线程各自创建 Extractor 使用，可以 M x N 并行

我是单卡， 使用方式如下：(在benchmark的基础上修改的)， benchmark接口中的net初始化删除
for (int i = 0; i < num_threadss;i++){
	threads.emplace_back([&, i](){

       benchmark(net,ncnn::Mat(227, 227, 3));
        });
}

for (auto& t : threads) {
    if (t.joinable()) t.join();
  }

会出现以下错误：
*** Error in `../build/benchmark/benchncnn': double free or corruption (fasttop): 0x00007f680010ffc0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7f6819f3e329]
../build/benchmark/benchncnn[0x40aec0]
../build/benchmark/benchncnn[0x41d424]
../build/benchmark/benchncnn[0x48e750]
../build/benchmark/benchncnn[0x4249ce]
../build/benchmark/benchncnn[0x427eea]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427fd3]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x427e76]
../build/benchmark/benchncnn[0x42871d]
../build/benchmark/benchncnn[0x42e604]
../build/benchmark/benchncnn(_Z9benchmarkRN4ncnn3NetERKNS_3MatE+0x239)[0x408eb9]
../build/benchmark/benchncnn[0x40911c]
/lib64/libstdc++.so.6(+0xbf420)[0x7f681a862420]
/lib64/libpthread.so.0(+0x7ea5)[0x7f681bc1bea5]
/lib64/libc.so.6(clone+0x6d)[0x7f6819fbb9fd]

**Comment by sdnusqy-art** [comment]
> https://github.com/Tencent/ncnn/wiki/vulkan-notes#batch-inference
> 
> 单卡：初始化一个Net实例，多线程各自创建 Extractor 使用
> 多卡：初始化卡数Net实例，每个卡上多线程各自创建 Extractor 使用，可以 M x N 并行

单纯根据 https://github.com/Tencent/ncnn/wiki/vulkan-notes#batch-inference的操作， 
for (int i=0; i<1000; i++)
{
    ncnn::Extractor ex = net1.create_extractor();
    ex.input("data", inputs[i]);
    ex.extract("prob", outputs[i]);
}

这个难道不还是串行吗？
