### ISSUE TITLE
检测不使用GPU

### ISSUE THREAD

**Issue by wbq330** [Tencent/ncnn#2927]
windows10 
nvidia geforce rtx 3090
安装了vulkan1.2.170版本
编译运行都不报错，但是检测发现仅在cpu上运行，不使用gpu

**Comment by Mouna96** [comment]
@wbq330  Are you able to modify this ? I am having the same issue and I want to speed up the process.

**Comment by nihui** [comment]
最新的 master 分支可以自动检测gpu了，更新试试，如有问题可 reopen issue 继续交流
