### ISSUE TITLE
关于v8内联 v7内嵌汇编的实现方式

### ISSUE THREAD

**Issue by wl3b10s** [Tencent/ncnn#293]
使用neon情况下，v8采用内联neon函数而v7采用内嵌汇编的实现方式。

为什么v7不采用内联的形式实现?是v7的编译效果比较差么？

**Comment by nihui** [comment]
aarch64 assembly added in https://github.com/Tencent/ncnn/commit/6ea09ebf2c4cc05460a99dea53a6260f5843c19a
