### ISSUE TITLE
ncnn::yuv420sp2rgb

### ISSUE THREAD

**Issue by 271983592** [Tencent/ncnn#2930]
函数ncnn::yuv420sp2rgb再ncnn::Mat::PIXEL_RGB2BGR   与opencv中的COLOR_YUV2BGR_NV21生成图像数据貌似有明显不同。对模型的推理效果影响很大，请问这是由于函数实现的方法不同造成的吗？好像转化的公式应该是一样的。。。

**Comment by 271983592** [comment]
对不起，是我处理逻辑有问题。

**Comment by aovoc** [comment]
您好，最后结果一样么，我遇到了同样的问题
