### ISSUE TITLE
Arm Linux int8 推理结果与x86 Linux int8结果不一致

### ISSUE THREAD

**Issue by TianpengBu** [Tencent/ncnn#2936]
### 背景描述：
我们基于nanodet自建了检测模型，backbone依旧是shufflenetV2，在x86 Linux上完整走了模型转化，int8量化以及量化推理等流程。但是当我们把int8模型部署在arm Linux上的时候，int8的推理结果错误。

### 问题排查：
我们的思路是想要逐层对比两个平台int8模式下的结果输出。
**部分模型的.param:** 
```
7767517
147 170
Input                    input.1                  0 1 input.1
Convolution              Conv_0                   1 1 input.1 424 0=24 1=3 3=2 4=1 5=1 6=648 8=2 9=2 -23310=1,1.000000e-01
Pooling                  MaxPool_3                1 1 424 425 1=3 2=2 3=1 5=1
Split                    splitncnn_0              1 2 425 425_splitncnn_0 425_splitncnn_1
ConvolutionDepthWise     Conv_4                   1 1 425_splitncnn_1 427 0=24 1=3 3=2 4=1 5=1 6=216 7=24 8=101
Convolution              Conv_6                   1 1 427 430 0=24 1=1 5=1 6=576 8=2 9=2 -23310=1,1.000000e-01
Convolution              Conv_9                   1 1 425_splitncnn_0 433 0=24 1=1 5=1 6=576 8=102 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_12                  1 1 433 435 0=24 1=3 3=2 4=1 5=1 6=216 7=24 8=101
Convolution              Conv_14                  1 1 435 438 0=24 1=1 5=1 6=576 8=2 9=2 -23310=1,1.000000e-01
Concat                   Concat_17                2 1 430 438 439
```
**这段param对应的网络连接图为：**
![image](https://user-images.githubusercontent.com/37365950/119095869-68e0ba00-ba45-11eb-8659-18af09005816.png)
上图中的BN和LeakyRelu已经被fuse到conv中，因此没有画出。

我们对网络输送了一张320x320的图片，然后利用int8推理，并且渲染了上面参数重的424，425，425_splitncnn_0，425_splitncnn_1，427，430，433，435，438，439的feature map。我们发现在427与433之前，两个平台上输出的feature map是相同的，但是在433与427（包括）之后，两个平台的feature开始不同。

附上几个feature map的对比图：看起来是内存哪里出了问题，还没具体定位。
![image](https://user-images.githubusercontent.com/37365950/119115235-861f8380-ba59-11eb-8c90-8ed619c5e7fd.png)

**另外的尝试**
我们修改了前几层的连接，不做split，在第一个conv后，继续跟两个conv，我们发现，param如下：
```
7767517
149 172
Input                    input.1                  0 1 input.1
Convolution              Conv_0                   1 1 input.1 436 0=16 1=3 3=2 4=1 5=1 6=432 8=2 9=2 -23310=1,1.000000e-01
Pooling                  MaxPool_3                1 1 436 437 1=3 2=2 3=1 5=1
Convolution              Conv_4                   1 1 437 440 0=16 1=3 4=1 5=1 6=2304 8=102 9=2 -23310=1,1.000000e-01
Convolution              Conv_7                   1 1 440 443 0=16 1=3 4=1 5=1 6=2304 8=102 9=2 -23310=1,1.000000e-01
Split                    splitncnn_0              1 2 443 443_splitncnn_0 443_splitncnn_1
ConvolutionDepthWise     Conv_10                  1 1 443_splitncnn_1 444 0=16 1=3 3=2 4=1 5=1 6=144 7=16 8=101
Convolution              Conv_12                  1 1 444 448 0=12 1=1 5=1 6=192 8=2 9=2 -23310=1,1.000000e-01
Convolution              Conv_15                  1 1 443_splitncnn_0 451 0=12 1=1 5=1 6=192 8=102 9=2 -23310=1,1.000000e-01
ConvolutionDepthWise     Conv_18                  1 1 451 452 0=12 1=3 3=2 4=1 5=1 6=108 7=12 8=101
Convolution              Conv_20                  1 1 452 456 0=12 1=1 5=1 6=144 8=2 9=2 -23310=1,1.000000e-01
Concat                   Concat_23                2 1 448 456 457
```

我们发现两个平台在经过split层之前的三个卷积输出的feature依旧相同，split后有了问题。

希望大佬解答一下！！跪谢～

**Comment by zhangmytf** [comment]
same question+1

**Comment by damonzhou** [comment]
补充一下：425_splitncnn_0和425_splitncnn_1两个feature map的内容都是正确的，只是经过427和433两个卷积后，输出结果就不一致了。

**Comment by nihui** [comment]
fixed by https://github.com/Tencent/ncnn/commit/9b5cb959b9305d380b190ffc68329a4bbeb2cd86
extract 在获取 int8 blob 时没有正确的转换为 fp32

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/f6c49523d2359ee598a8ba1793a8e958b52c20ca 修复两处 convolutiondepthwise int8 arm 计算错误

**Comment by TianpengBu** [comment]
> [f6c4952](https://github.com/Tencent/ncnn/commit/f6c49523d2359ee598a8ba1793a8e958b52c20ca) 修复两处 convolutiondepthwise int8 arm 计算错误

 
 @nihui 首先感谢hui酱的答复。这个新版本我打算一会试一试，然后给出反馈。过去两天我们也在不断地排查问题，希望我们排查的过程和结果对完善框架有一丢丢贡献。

以下的问题排查过程依然基于20210507的版本。
排查的过程如下：

我们首先通过对比经过split后armv7上的卷积和x86上的卷积输出的feature map，即上图的433和427，我们发现，可能是内存的原因导致了armv7上输出的feature有了问题（不知道这样的怀疑是不是正确的）。


由于packing直接和内存操作相关，随即我们关掉了neon，发现卷积等操作不再使用packing，但是我们发现split层依然在packing，因此把425_split层的support_packing也关掉了，发现433(conv)和427（depthwise conv）的输出正常了，同时armv7还是没有正确的预测结果，但是这个感觉代表我们的方向对了。


最后，在demo中，把option里面的use_packing_layout设置成了false，armv7便可以正确输出结果了，再打开neon后，只要是`use_packing_layout=false`，我们的结果便可以正常输出。

但是我们其实只是从表象上输出了结果，具体很细（框架和硬件层面）的原因我们还是一知半解，希望大佬能给出一点解答。会是我们硬件对use_packing_layout的支持有问题吗？还是其他原因导致了这个问题。感谢！

去试最新版本了！溜了溜了

**Comment by TianpengBu** [comment]
> [f6c4952](https://github.com/Tencent/ncnn/commit/f6c49523d2359ee598a8ba1793a8e958b52c20ca) 修复两处 convolutiondepthwise int8 arm 计算错误

**This update really fixes the ISSUE!!!**

大佬，我又来更新啦。
首先贴结果，这次模型可以正确预测结果了：
![A829B8A5-70E6-4691-B99A-E6F2C21678C6](https://user-images.githubusercontent.com/37365950/119595935-eb37f800-be10-11eb-9a44-d6fdcd50716f.png)
![A829B8A5-70E6-4691-B99A-E6F2C21678C6](https://user-images.githubusercontent.com/37365950/119596034-14588880-be11-11eb-8774-5a5aafc1153d.png)

结果符合这次的commit，现在做pack的depthwise卷积不会搞坏内存了。


另外，之前427的feature是很奇怪的，[上图](https://user-images.githubusercontent.com/37365950/119115235-861f8380-ba59-11eb-8c90-8ed619c5e7fd.png)，原因是两个卷积连在一起，第一个卷积输出是requantize的结果，因此visualize的时候不是我们熟知的feature map的样子，在大佬的上次commit [9b5cb95](https://github.com/Tencent/ncnn/commit/9b5cb959b9305d380b190ffc68329a4bbeb2cd86)后，extract中间的feature时候，框架会把feature变成了fp32，armv7输出如下：

![426](https://user-images.githubusercontent.com/37365950/119595361-05250b00-be10-11eb-8190-265f43618ff1.jpg)
经过对比，与x86输出一致。

最后，原谅我一波彩虹屁：NiHui，yyds！

**Comment by damonzhou** [comment]
> [f6c4952](https://github.com/Tencent/ncnn/commit/f6c49523d2359ee598a8ba1793a8e958b52c20ca) 修复两处 convolutiondepthwise int8 arm 计算错误

多谢大佬
