### ISSUE TITLE
视频检测，初始化一个实例Net, 每帧图像都要单独创建 ncnn::Extractor ex = net.create_extractor();

### ISSUE THREAD

**Issue by zhcv** [Tencent/ncnn#2938]

**Comment by nihui** [comment]
是的，没有问题，尝试更新最新ncnn版本，或者使用gpu加速

**Comment by hwddean** [comment]
> 是的，没有问题，尝试更新最新ncnn版本，或者使用gpu加速

是针对每个不同的输入都要实例化一下Extractor吗？不能实例化一次，多次调用input，传入不同参数？

**Comment by nihui** [comment]
> > 是的，没有问题，尝试更新最新ncnn版本，或者使用gpu加速
> 
> 是针对每个不同的输入都要实例化一下Extractor吗？不能实例化一次，多次调用input，传入不同参数？

Net 实例化一次就可以了，实例化 Extractor 不耗时。

**Comment by hwddean** [comment]
但是我只实例化一次，每次input不同的参数，但是输出都是一样的，而且特征提取没有耗时。

发自我的iPhone
