### ISSUE TITLE
建议将代码中的 AAsset 功能做成编译开关

### ISSUE THREAD

**Issue by niinorz** [Tencent/ncnn#2940]
如题，现在代码中控制是否使用 AAsset 是通过 
#if __ANDROID_API__ >= 9  来控制
而 __ANDROID_API__ 这个宏的相关、耦合性太强
建议增加一个单独的宏开关来进行控制

**Comment by nihui** [comment]
```-DNCNN_PLATFORM_API=OFF```  可以禁用一切平台相关的api调用

**Comment by niinorz** [comment]
> `-DNCNN_PLATFORM_API=OFF` 可以禁用一切平台相关的api调用

谢谢，是我之前用的版本比较老了，还没有这个开关
