### ISSUE TITLE
VS2015下编译出错"InterlockedIncrement”: 找不到标识符"

### ISSUE THREAD

**Issue by sunbinbin1991** [Tencent/ncnn#295]
之前在VS2015下编译都是正常,(0129的release版本),最近两次编译新的代码时经常出现如下的错误,有人出现过类似的问题么?

> C3861	“_InterlockedIncrement”: 找不到标识符	ncnn

我的版本信息如下:
![2prqu xlazb 8 8z y s 6](https://user-images.githubusercontent.com/15342883/37405362-72138a82-27cf-11e8-870a-0aadb79a3879.png)

**Comment by HeiSir2014** [comment]
#283

**Comment by sunbinbin1991** [comment]
问题已解决,多谢@HeiSir2014

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/3977d32eb9de01a427e24e4ba0f99a53a32979c1

**Comment by zjzh** [comment]
@sunbinbin1991  I encounterd the same problem.How do you solve the problem?
Thank you!

**Comment by sunbinbin1991** [comment]
You can use the lasted version of ncnn, new version has no such problem. Also your could reference #283 ,change order of some header files.
