### ISSUE TITLE
retinaface int8模型在arm平台无人脸检测结果

### ISSUE THREAD

**Issue by mingx9527** [Tencent/ncnn#2952]
@nihui 您好！本人在终端部署模型遇到问题，请教！问题如下：
1）RK3288（A17 CPU）部署retinaface mobile版本模型；32f模型表现正常， 2线程60ms左右
2）int8模型量化过程正常
3）PC（i7-10700k）上，能正常输出人脸框（虽然速度比32f慢4倍，这可能是CPU不支持int8所致）
4）3288上，int8模型能跑起来，速度也从60ms将到33ms左右，但没有人脸框输出？？？ （ncnn已经更最新；retinaface代码也没有问题）

**Comment by nihui** [comment]
请提供下量化后的 param bin 模型文件

**Comment by mingx9527** [comment]
回复得好快 感谢！ 
模型链接：链接: https://pan.baidu.com/s/1GUEpvduJYnQpbP_2k2-8rg  密码: 2a8i
--来自百度网盘超级会员V4的分享
