### ISSUE TITLE
armv7上int8模型elempack8 速度比fp16 elempack4慢？？

### ISSUE THREAD

**Issue by damonzhou** [Tencent/ncnn#2958]
![image](https://user-images.githubusercontent.com/5668779/119930086-5c161600-bfb1-11eb-8629-c393adaf4cd1.png)
最近测试模型发现armv7 CPU上，int8耗时(280ms)反而比fp16(210ms)慢很多，benchmark每层layer发现如上图中，如果int8模型的elempack==8，速度比fp16就会慢。
NOTE：上图中左边是int8模型，右边是fp16模型。

进一步debug发现quantize_to_int8会修改elempack==8，
请问各位大佬：
1）是否可以指定elempack为4？
2）为何elempack==8反而比elempack==4慢呢？

**Comment by nihui** [comment]
最新版本ncnn已经修复，int8将会总是使用elempack8，提升性能，欢迎更新，如有问题，可reopen issue继续交流
