### ISSUE TITLE
Output is different depending on the devices.

### ISSUE THREAD

**Issue by andrew-yang0722** [Tencent/ncnn#2965]
The output value of the model is different depending on the device.
(Everything is the same but the device is different. same binary.)
Model is a kind of MobilenetV2.

What makes this problem?
Can Android version or processor make the different output?
Or NCNN inside make this difference?
Can you advice me what to look into

output of 3 devices
```
0.1889312 -0.2030006 0.4840440 -0.0620004 -0.1458000  # Galaxy S7 output
0.1953125 -0.2587891 0.5122070 -0.0869751 -0.1887207      # Galaxy S10  output
0.1953125 -0.2587891 0.5122070 -0.0869751 -0.1887207      # Galaxy note20  output

0.1889313 -0.2030008 0.4840437 -0.0619998 -0.1457993  # pytorch output
```

Galaxy S7:  Android 8, Exynos 8890 Octa (14 nm)
Galaxy S10: Android 11, Exynos9820
Galaxy note20: Android 11, Snapdragon 865 5G+ (7 nm+)

**Comment by nihui** [comment]
newer devices has fp16 arithmetic capability. fp16 will be used automatically for faster inference on supported devices.
You could disable fp16 via
```cpp
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
```

**Comment by docongminh** [comment]
@andrew-yang0722 i have same problem,

**Comment by andrew-yang0722** [comment]
with net.opt.use_fp16_storage = false; net.opt.use_fp16_arithmetic = false;
I got the same result as the S7(old phone).

```
0.1889312 -0.2030006 0.4840440 -0.0620004 -0.1458000 # Galaxy note20  output
```

I works well. 
Thank you. @nihui
