### ISSUE TITLE
find_blob_index_by_name报错经ncnn2mem转换后，加载模型和输入输出怎样修改

### ISSUE THREAD

**Issue by liguoyu666** [Tencent/ncnn#2967]
您好，我使用torchvison自带的resnet18模型转换为resnet18.param和resnet18.bin后，在运行时报`find_blob_index_by_name`。

个人尝试解决：
`./ncnn2mem resnet18.param resnet18.bin resent18.id.h resnet18.men.h`生成的resnet18.id.h打开为：

#ifndef NCNN_INCLUDE_GUARD_resent18_id_h
#define NCNN_INCLUDE_GUARD_resent18_id_h
namespace resnet18_param_id {
const int LAYER_input_1 = 0;
const int BLOB_input_1 = 0;
......
const int BLOB_190 = 64;
const int LAYER_Gemm_68 = 57;
const int BLOB_191 = 65;
} // namespace resnet18_param_id
#endif // NCNN_INCLUDE_GUARD_resent18_id_h

将复制squeezenet.cpp的resnet18.cpp进行修改

#include "net.h"
#include "resnet18.id.h"

#include <algorithm>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <stdio.h>
#include <vector>

static int detect_squeezenet(const cv::Mat& bgr, std::vector<float>& cls_scores)
{
    ncnn::Net squeezenet;

    squeezenet.opt.use_vulkan_compute = true;

    // the ncnn model https://github.com/nihui/ncnn-assets/tree/master/models
    squeezenet.load_param_bin("resnet18.param.bin");
    squeezenet.load_model("resnet18.bin");

    ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows, 227, 227);

    const float mean_vals[3] = {104.f, 117.f, 123.f};
    in.substract_mean_normalize(mean_vals, 0);

    ncnn::Extractor ex = squeezenet.create_extractor();

    ex.input("resnet18_param_id::BLOB_data", in);

    ncnn::Mat out;
    ex.extract("resnet18_param_id::BLOB_prob", out);

    cls_scores.resize(out.w);
    for (int j = 0; j < out.w; j++)
    {
        cls_scores[j] = out[j];
    }

    return 0;
}

还是报错
`find_blob_index_by_name resnet18_param_id::BLOB_data failed
Try
find_blob_index_by_name resnet18_param_id::BLOB_prob failed
Try
段错误
`

增加了 #include "resnet18.id.h"

问题一：加载模型修改
    **squeezenet.load_param_bin("resnet18.param.bin");**
    **squeezenet.load_model("resnet18.bin");**

问题二：输入输出修改
    **ex.input("resnet18_param_id::BLOB_data", in);**
    **ex.extract("resnet18_param_id::BLOB_prob", out);**

**Comment by liguoyu666** [comment]
我通过查找索引，能够正常跑通

`    squeezenet.load_param("resnet18.param");
    squeezenet.load_model("resnet18.bin");`

`    ex.input("input.1", in);

    ncnn::Mat out;
    ex.extract("191", out);`

但是，我想知道的是，我这若是加载二进制的 param.bin 和 bin，输入输出该如何修改？

**Comment by liguoyu666** [comment]
已解决，输入输出改为：

ex.input(resnet18_param_id::BLOB_input_1, in);
ex.extract(resnet18_param_id::BLOB_191, out);

之前在原文件上改，一直加了双引号。

**Comment by Xxxxi** [comment]
你好。我是iOS，也是遇到你这个问题，请问要怎么解决，我用的资源文件是.param 和 .bin
