### ISSUE TITLE
onnx2ncnn: ok, then ncnnoptimize: Segmentation fault 

### ISSUE THREAD

**Issue by Kerry678231** [Tencent/ncnn#2969]
cmd step:
![EZ%LB75V)HH{QH~JBJ811XB](https://user-images.githubusercontent.com/57534387/120273840-9ea55e80-c2e1-11eb-9ba1-0d45b267272a.png)

param file：
[yolact-s.param.zip](https://github.com/Tencent/ncnn/files/6573715/yolact-s.param.zip)

please tack a look , answer me this question.

**Comment by nihui** [comment]
fixed in onnx2ncnn

**Comment by Kerry678231** [comment]
ok，thanks，up
