### ISSUE TITLE
openmp crash

### ISSUE THREAD

**Issue by tfzhou** [Tencent/ncnn#297]
在android端，使用自带的example调用openmp没有问题。但是在自己封装的一个jni中使用openmp，程序会crash，即使jni只有一个最简单的for循环。

调用omp_get_thread_num()没有问题，其它调用会crash。猜想是不是因为在spawn threads的时候出问题。唯一觉得有关的就是set_cpu_powersave函数，但是并没有找到其被调用的地方。

@nihui 请问有没有什么地方可能导致这个问题

**Comment by nihui** [comment]
android ndk 版本是 r15c 或者更新版本？

**Comment by tfzhou** [comment]
r15c

**Comment by tfzhou** [comment]
我用r11c编译没有问题了，看来时ndk的问题
