### ISSUE TITLE
int8量化后速度比量化前慢了很多

### ISSUE THREAD

**Issue by lh-13** [Tencent/ncnn#2974]
各位，使用最新版本(大于20210507)的ncnn 推理yolov4-tiny模型，int8量化后速度比未量化的还要慢（如果把输入图像设的比较小，比如160*160，int8量化模型是比没有量化的快。如果输入图像为更大，像320*320或是416*416或是更大，则int8量化后的速度比未量化的要慢很多），目标平台为window10,工程使用vs2017。请知道的大神不吝赐教，哪里出了问题？模型量化这里吗？从github上(https://github.com/pengtougu/ncnn-yolov4-int8)找了一个现成的试了下，也是这个情况.......，在线等，谢谢了

**Comment by nihui** [comment]
ncnn新版本的int8优化主要针对arm平台，不是x86平台
建议用 android 手机跑跑看
以及，x86 可以开 gpu 加速推理

**Comment by lh-13** [comment]
@nihui ok thanks
