### ISSUE TITLE
quantization/ncnn2table params

### ISSUE THREAD

**Issue by txdat** [Tencent/ncnn#2975]
Thanks for your project. I have a question about ncnn2table's params `norm`, `mean`, `pixel` in quantization. `mean` and `norm` are values of `substract_mean_normalize`, but in [ncnn-yolov4-int8](https://github.com/pengtougu/ncnn-yolov4-int8), `mean=[104,117,123] norm=[0.017,0.017,0.017] shape=[224,224,3] pixel=BGR` while `const float mean_vals[3] = {0, 0, 0};const float norm_vals[3] = {1 / 255.f, 1 / 255.f, 1 / 255.f};` and `ncnn::Mat::PIXEL_BGR2RGB` in `ncnn::Mat::from_pixels` in [examples/yolov4](https://github.com/Tencent/ncnn/blob/master/examples/yolov4.cpp#L96). So what are correct values of `norm`, `mean` and `pixel` in `ncnn2table`? I tried params based on docs, but results were different (compared with pytorch/fp32 ncnn versions). My task is headpose prediction (regression). Thanks a lot!

**Comment by nihui** [comment]
mean norm and pixel parameters shall be the same as them in inference code
so in your example, mean=[0, 0, 0] norm=[0.00392156862745,0.00392156862745,0.00392156862745] pixel=RGB should be used

It is common that regression task is not practical for model quantization.

**Comment by txdat** [comment]
thank you, I will try it again.
