### ISSUE TITLE
安卓下，Extractor提取CRNN中第二个LSTM的输出时报错

### ISSUE THREAD

**Issue by chrischgx** [Tencent/ncnn#2976]
大概流程：
网络中有两个LSTM，第一个Extractor将归一化后的Mat传入param中的“input”，从“211”（第一个LSTM的输出）提取输出。然后手工实现InnerProduct。第二个Extractor将InnerProduct的结果传入“232”（第二个LSTM的输入），从“371”（第二个LSTM的输出）提取输出。
整个过程在VS中都是可以正常运行，且结果基本准确的。
在AS中，APP会闪退，同时AS中可以看到如下错误：
``` A/libc: Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7644634000 in tid 31801 (encent.crnnncnn), pid 31801 (encent.crnnncnn) ```
最终定位的问题处是：
``` crnn_ex2.extract("371", LSTM2out_371);  ```
将该句注销后（直接用InnerProduct结果进行fc2的步骤），报错消失，且APP不闪退。
因此想问下是不是我的处理有问题。
非常感谢！

用netron查看：
![image](https://user-images.githubusercontent.com/49402628/120461450-98d87780-c3cc-11eb-9635-9827e37b5667.png)

param：
![image](https://user-images.githubusercontent.com/49402628/120461634-bd345400-c3cc-11eb-9e9d-8d46f804b2b4.png)

JNI文件中对网络的处理：

```
    ncnn::Mat input = ncnn::Mat::from_android_bitmap_resize(env, bitmap, ncnn::Mat::PIXEL_RGB, input_width, input_height);

    normalization(input);

    ncnn::Extractor crnn_ex = crnn.create_extractor();

    crnn_ex.set_vulkan_compute(use_gpu);

    crnn_ex.input("input", input);

    // lstm 1
    ncnn::Mat LSTM1out_211;// ncnn::Mat blob162;
    crnn_ex.extract("211", LSTM1out_211); //crnn_ex.extract("234", blob162);

    // batch fc 1
    int nh = 512;
    int len_dic = 24;
    ncnn::Mat InnerProduct1_out(nh, LSTM1out_211.h);//ncnn::Mat blob182(256, blob162.h);

    for (int i = 0; i<LSTM1out_211.h; i++)
    {
        ncnn::Extractor crnn_ex_1 = crnn.create_extractor();
        crnn_ex_1.set_vulkan_compute(use_gpu);

        ncnn::Mat LSTM1out_211_i = LSTM1out_211.row_range(i, 1);
        crnn_ex_1.input("225", LSTM1out_211_i);  // 225 InnerProduct_in

        ncnn::Mat InnerProduct1_out_i;
        crnn_ex_1.extract("226", InnerProduct1_out_i);  // 226 InnerProduct_out

        memcpy(InnerProduct1_out.row(i), InnerProduct1_out_i, nh * sizeof(float));
    }

    // lstm 2
    ncnn::Mat LSTM2out_371;  // blob243
    ncnn::Extractor crnn_ex2 = crnn.create_extractor();
    crnn_ex2.set_vulkan_compute(use_gpu);

    crnn_ex2.input("232", InnerProduct1_out);  // 232 LSTM2in
    crnn_ex2.extract("371", LSTM2out_371);  // 371 LSTM2out
 
    // batch fc 2
    ...

```

**Comment by nihui** [comment]
The ncnn batch infrastructure feature, which relies on the pnnx tool, is implemented at https://github.com/Tencent/ncnn/commit/127b4146148844ccf67a5bdcb0385e925aa13fbb
