### ISSUE TITLE
android studio使用模拟器时如何上传图片至模拟器

### ISSUE THREAD

**Issue by liguoyu666** [Tencent/ncnn#2980]
算法在android studio和手机上都能正常运行，但是在android studio 上只能选择默认的那一张图片，我自己通过以下两种方式上传图片：1.通过Device File Explorer 在sdcard 用upload上传，该方式上传后能够在文件夹找到，但是相册和算法的选图还是只有默认的图片，2.通过拖图片到模拟器里，能够在sdcard的download里找到，模拟器的download里也能看到，但是相册和算法的选图还是只有默认的图片
重启模拟器没用，上传的图片重启后也没了
进入setting->storage，开启虚拟sd也没用

![2021-06-03 17-43-57屏幕截图](https://user-images.githubusercontent.com/47743761/120625283-1fa45780-c494-11eb-88f2-a9c23d326bf3.png)

![image](https://user-images.githubusercontent.com/47743761/120625849-a9542500-c494-11eb-98d8-955071c05c70.png)

![2021-06-03 17-43-30屏幕截图](https://user-images.githubusercontent.com/47743761/120625294-229f4800-c494-11eb-81c3-2be1d7971245.png)

**Comment by tpoisonooo** [comment]
这是纯  Android 业务开发问题了，跟 ncnn 没啥关系....帮您搜了一下   https://stackoverflow.com/questions/29588124/how-to-add-an-image-to-the-emulator-gallery-in-android-studio

google 关键词 android emulator upload image.

#2980  close

**Comment by liguoyu666** [comment]
> 这是纯 Android 业务开发问题了，跟 ncnn 没啥关系....帮您搜了一下 https://stackoverflow.com/questions/29588124/how-to-add-an-image-to-the-emulator-gallery-in-android-studio
> 
> google 关键词 android emulator upload image.
> 
> #2980 close

谢谢！

**Comment by liguoyu666** [comment]
> 这是纯 Android 业务开发问题了，跟 ncnn 没啥关系....帮您搜了一下 https://stackoverflow.com/questions/29588124/how-to-add-an-image-to-the-emulator-gallery-in-android-studio
> 
> google 关键词 android emulator upload image.
> 
> #2980 close

谢谢！
