### ISSUE TITLE
Yolov5s转onnx转ncnn后修改focus及Reshape的gird值后example的yolov5例子仍然返回密密麻麻的检测框

### ISSUE THREAD

**Issue by MasonSuWei** [Tencent/ncnn#2990]
大家好！

使用yolov5 tag v3.2的yolov5s.pt模型进行模型转换
https://github.com/ultralytics/yolov5/releases/download/v3.1/yolov5s.pt

按照以下文章进行操作
https://zhuanlan.zhihu.com/p/275989233
并将reshape的gird值改为-1和针对最后两层输出层按照生成的param修改了层名称，最后运行得到的检测框仍然密密麻麻。
不知道是什么原因导致了问题？
以下是我转换出来的yolov5ss-sim.onnx
https://pan.baidu.com/s/1P-C56W17s_1C616Uk2EJ5A
提取码
7q94

我使用以下ncnn版本
commit 71bc617a05f073d8b623dcc95e88eb5e1eb16aa5
Author: nihui <shuizhuyuanluo@126.com>
Date:   Sat May 29 21:43:29 2021 +0800

    better ncnn2table multithreading, print parsed parameters, print progress
以下为我生成的yolov5s-opt.param和yolov5-opt.bin
https://pan.baidu.com/s/1oBQ50s4PvVRYrtvgZH2uFQ
提取码
cbsw

提前感谢提供相关帮忙！

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
