### ISSUE TITLE
如何编译caffe2ncnn工具

### ISSUE THREAD

**Issue by LiMilo84** [Tencent/ncnn#30]
我在ubuntu上编译caffe2ncnn.cpp的时候一直编译不成功，头文件都已经添加了。请问还有什么需要特别注意的地方吗？

**Comment by nihui** [comment]
错误是什么呢

**Comment by LiMilo84** [comment]
打印的错误信息：
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.

应该是生成caffe.pb.h的PROTOBUF版本问题吧？

**Comment by nihui** [comment]
系统里有两个 protobuf ?
把 protobuf 卸载重装下，然后删除 build 重新编译

**Comment by ruyiweicas** [comment]
ruyiwei@ruyiwei:~/code/ncnn/tools/build$ make 
[ 66%] Built target caffe2ncnn
[ 83%] Linking CXX executable ncnn2mem
/usr/bin/ld: cannot find -lncnn
collect2: error: ld returned 1 exit status
CMakeFiles/ncnn2mem.dir/build.make:94: recipe for target 'ncnn2mem' failed
make[2]: *** [ncnn2mem] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/ncnn2mem.dir/all' failed
make[1]: *** [CMakeFiles/ncnn2mem.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
ruyiwei@ruyiwei:~/code/ncnn/tools/build$ upgrade_net_proto_text
upgrade_net_proto_text: command not found

**Comment by ruyiweicas** [comment]
ruyiwei@ruyiwei:/code/ncnn/tools/build$ make
[ 66%] Built target caffe2ncnn
[ 83%] Linking CXX executable ncnn2mem
/usr/bin/ld: cannot find -lncnn
collect2: error: ld returned 1 exit status
CMakeFiles/ncnn2mem.dir/build.make:94: recipe for target 'ncnn2mem' failed
make[2]: *** [ncnn2mem] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/ncnn2mem.dir/all' failed
make[1]: *** [CMakeFiles/ncnn2mem.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
ruyiwei@ruyiwei:/code/ncnn/tools/build$ upgrade_net_proto_text
upgrade_net_proto_text: command not found

**## 这是什么错误呢？修改platform.h.in 为platform.h 里面三行换为#define XXX true**

**Comment by akbarxie** [comment]
遇到同样的问题，求解？

**Comment by nihui** [comment]
用顶层的 CMakeLists.txt 编译....
编译完在 ncnn/build/tools 里头有

**Comment by LiMilo84** [comment]
@nihui
现在报出一大堆这样的错误
caffe2ncnn.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEESbIT_T0_T1_ERKS6_S8_[std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)]+0x15): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
caffe2ncnn.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEESbIT_T0_T1_ERKS6_S8_[std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)]+0x27): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
caffe2ncnn.cpp:(.text._ZStplIcSt11char_traitsIcESaIcEESbIT_T0_T1_ERKS6_S8_[std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)]+0x36): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/tmp/ccAH9QUS.o: In function `std::_Rb_tree_iterator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >::operator++(int)':
caffe2ncnn.cpp:(.text._ZNSt17_Rb_tree_iteratorISt4pairIKSsiEEppEi[std::_Rb_tree_iterator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >::operator++(int)]+0x19): undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base*)'
/tmp/ccAH9QUS.o: In function `std::_Rb_tree_iterator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >::operator++()':
caffe2ncnn.cpp:(.text._ZNSt17_Rb_tree_iteratorISt4pairIKSsiEEppEv[std::_Rb_tree_iterator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> >::operator++()]+0xf): undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base*)'
/tmp/ccAH9QUS.o: In function `bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)':
caffe2ncnn.cpp:(.text._ZSteqIcSt11char_traitsIcESaIcEEbRKSbIT_T0_T1_EPKS3_[bool std::operator==<char, std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)]+0x14): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
/tmp/ccAH9QUS.o: In function `google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler>(int) const':
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobProtoEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler>(int) const]+0x3c): undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobProtoEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler>(int) const]+0x54): undefined reference to `google::protobuf::internal::LogMessage::operator<<(char const*)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobProtoEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler>(int) const]+0x63): undefined reference to `google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobProtoEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler>(int) const]+0x72): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobProtoEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobProto>::TypeHandler>(int) const]+0xa1): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
/tmp/ccAH9QUS.o: In function `google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler>(int) const':
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldISsE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler>(int) const]+0x3c): undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldISsE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler>(int) const]+0x54): undefined reference to `google::protobuf::internal::LogMessage::operator<<(char const*)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldISsE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler>(int) const]+0x63): undefined reference to `google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldISsE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler>(int) const]+0x72): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldISsE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::TypeHandler>(int) const]+0xa1): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
/tmp/ccAH9QUS.o: In function `google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler>(int) const':
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobShapeEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler>(int) const]+0x3c): undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobShapeEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler>(int) const]+0x54): undefined reference to `google::protobuf::internal::LogMessage::operator<<(char const*)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobShapeEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler>(int) const]+0x63): undefined reference to `google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobShapeEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler>(int) const]+0x72): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe9BlobShapeEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::BlobShape>::TypeHandler>(int) const]+0xa1): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
/tmp/ccAH9QUS.o: In function `google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler>(int) const':
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe14LayerParameterEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler>(int) const]+0x3c): undefined reference to `google::protobuf::internal::LogMessage::LogMessage(google::protobuf::LogLevel, char const*, int)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe14LayerParameterEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler>(int) const]+0x54): undefined reference to `google::protobuf::internal::LogMessage::operator<<(char const*)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe14LayerParameterEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler>(int) const]+0x63): undefined reference to `google::protobuf::internal::LogFinisher::operator=(google::protobuf::internal::LogMessage&)'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe14LayerParameterEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler>(int) const]+0x72): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
caffe2ncnn.cpp:(.text._ZNK6google8protobuf8internal20RepeatedPtrFieldBase3GetINS0_16RepeatedPtrFieldIN5caffe14LayerParameterEE11TypeHandlerEEERKNT_4TypeEi[google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler::Type const& google::protobuf::internal::RepeatedPtrFieldBase::Get<google::protobuf::RepeatedPtrField<caffe::LayerParameter>::TypeHandler>(int) const]+0xa1): undefined reference to `google::protobuf::internal::LogMessage::~LogMessage()'
/tmp/ccAH9QUS.o: In function `float* std::vector<float, std::allocator<float> >::_M_allocate_and_copy<float*>(unsigned int, float*, float*)':
caffe2ncnn.cpp:(.text._ZNSt6vectorIfSaIfEE20_M_allocate_and_copyIPfEES3_jT_S4_[float* std::vector<float, std::allocator<float> >::_M_allocate_and_copy<float*>(unsigned int, float*, float*)]+0x50): undefined reference to `__cxa_end_catch'
caffe2ncnn.cpp:(.text._ZNSt6vectorIfSaIfEE20_M_allocate_and_copyIPfEES3_jT_S4_[float* std::vector<float, std::allocator<float> >::_M_allocate_and_copy<float*>(unsigned int, float*, float*)]+0x62): undefined reference to `__cxa_begin_catch'

**Comment by ruyiweicas** [comment]
@nihui 谢谢，问题解决了，我随后会出一个更详细的版本，多谢，而且，我并不是大叔啊楼上

**Comment by akbarxie** [comment]
@nihui 谢谢，nice。没事我就调戏大叔。

**Comment by ruyiweicas** [comment]
@akbarxie 我真的不是大叔

**Comment by akbarxie** [comment]
我知道的，大叔

**Comment by ruyiweicas** [comment]
http://blog.csdn.net/best_coder/article/details/76201275
这个是写的感觉比较详细的安装教程，可以参照的看看

**Comment by duangenquan** [comment]
感谢您的安装教程。
我编译后，没有upgrade_net_proto_text和upgrade_net_proto_binary。
请问如何您是如何编译的？
谢谢！
