### ISSUE TITLE
torch.nn.Unfold not supported yet?

### ISSUE THREAD

**Issue by Xelawk** [Tencent/ncnn#3013]
In my code, torch.nn.Unfold is used to extract image patches
I have tried to convert my pytorch model to onnx then onnxsim it, and it successed
But it stll failed when I try to convert it to ncnn. The error has happen as below:
```
Gather not supported yet!
  # axis=2
Gather not supported yet!
  # axis=4
Unsupported reduction axes !
Gather not supported yet!
  # axis=1
Gather not supported yet!
  # axis=2
Gather not supported yet!
  # axis=4
Gather not supported yet!
  # axis=2
Gather not supported yet!
  # axis=4
Unsupported split axis !
Gather not supported yet!
  # axis=2
Gather not supported yet!
  # axis=4
Unsupported split axis !
Unsupported split axis !
Gather not supported yet!
  # axis=0
Unsupported reduction axes !
Segmentation fault (core dumped)
```

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
