### ISSUE TITLE
ncnn 是否支持nn.Conv1d？

### ISSUE THREAD

**Issue by fkh12345** [Tencent/ncnn#3016]
请问NCNN可以支持一维卷积吗? 
使用onnx2ncnn可以将conv1d的model转化为param和bin 
但是在运行ncnn加载model net.load_model("./*.bin")时会报错

**Comment by tpoisonooo** [comment]
一般提一个问题，至少需要

* 提供 log 之类报错信息，读你问题的人可以快速定位大致方向
* 提供一下 .param 和  .bin  之类的复现方法
* 提供版本信息，commit-id 或者 release 的哪个 tag

光知道出错了，不能知道哪里错了也没啥用啊。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/3035

**Comment by nihui** [comment]
已支持
