### ISSUE TITLE
BatchNorm Layer: it seems to be safer to add a epsilon to the standard deviation

### ISSUE THREAD

**Issue by cook** [Tencent/ncnn#303]
In the following codes cited from the file [src/layer/batchnorm](https://github.com/Tencent/ncnn/blob/6ea09ebf2c4cc05460a99dea53a6260f5843c19a/src/layer/batchnorm.cpp#L62), if the `sqrt_var` is zero, there will be a zero-division error. So I advice to add a epsilon to the standard deviation or add some protection codes.

        float sqrt_var = sqrt(var_data[i]);
        a_data[i] = bias_data[i] - slope_data[i] * mean_data[i] / sqrt_var;
        b_data[i] = slope_data[i] / sqrt_var;

(虽然可能性不大, 但加上去毕竟更安全些)

**Comment by nihui** [comment]
epsilon value is handled in model converter that is pre-added to variance

**Comment by cook** [comment]
Why there is not a parameter for epsilon in the layer BatchNorm like in the layers such as InstanceNorm and MVN, I've found `eps` parameter in these layers. Is it inconsistency?

**Comment by nihui** [comment]
It is for some historical reason, and it is fine to add eps parameter with default value of zero for consistency.
welcome to open pull request  : )
