### ISSUE TITLE
segmentation fault when converting mobilenetssd .prototxt and .caffemodel to .param and .bin files

### ISSUE THREAD

**Issue by hygxy** [Tencent/ncnn#3043]
## error log | 日志或报错信息 | ログ
```
Segmentation fault (core dumped)


gdb caffe2ncnn
GNU gdb (Ubuntu 8.2-0ubuntu1~16.04.1) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from caffe2ncnn...(no debugging symbols found)...done.
(gdb) set args ~/Desktop/deploy_new.prototxt ~/Desktop/MobileNetSSD_deploy_new.caffemodel ~/Desktop/mobilenet_ssd_voc_ncnn.param ~/Desktop/mobilenet_ssd_voc_ncnn.bin
(gdb) r
Starting program: /home/hy/ncnn/build/tools/caffe/caffe2ncnn ~/Desktop/deploy_new.prototxt ~/Desktop/MobileNetSSD_deploy_new.caffemodel ~/Desktop/mobilenet_ssd_voc_ncnn.param ~/Desktop/mobilenet_ssd_voc_ncnn.bin
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00000000004468c9 in main ()
```
## model | 模型 | モデル
1.MobileNetSSD

## how to reproduce | 复现步骤 | 再現方法
1. Download Mobilenet-SSD from this [repo](https://github.com/chuanqi305/MobileNet-SSD), "deploy.prototxt" and "MobileNetSSD_deploy.caffemodel"
2. Use [caffe-ssd](https://github.com/weiliu89/caffe/tree/ssd) to update deploy.prototxt and .caffemodel file,  ``/path-to-caffe-ssd/upgrade_net_proto_text ~/Desktop/deploy.prototxt ~/Desktop/deploy_new.prototxt`` 
``/path-to-caffe-ssd/upgrade_net_proto_binary ~/Desktop/MobileNetSSD_deploy.caffemodel ~/Desktop/MobileNetSSD_deploy_new.caffemodel`` 
log info -> ``I0630 13:21:47.318075 19181 upgrade_proto.cpp:77] Attempting to upgrade batch norm layers using deprecated params: /home/hy/Desktop/deploy.prototxt
I0630 13:21:47.320994 19181 upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
``
``E0630 13:23:09.927997 19196 upgrade_net_proto_binary.cpp:43] File already in latest proto format: /home/hy/Desktop/MobileNetSSD_deploy.caffemodel
I0630 13:23:10.164958 19196 upgrade_net_proto_binary.cpp:48] Wrote upgraded NetParameter binary proto to /home/hy/Desktop/MobileNetSSD_deploy_new.caffemodel``

3. ``/path-to-ncnn/caffe2ncnn ~/Desktop/deploy_new.prototxt ~/Desktop/MobileNetSSD_deploy_new.caffemodel ~/Desktop/mobilenet_ssd_voc_ncnn.param ~/Desktop/mobilenet_ssd_voc_ncnn.bin``

**Comment by nihui** [comment]
Your prototxt and caffemodel files are not on-pair
Try https://github.com/chuanqi305/MobileNet-SSD/blob/master/voc/MobileNetSSD_deploy.prototxt
