### ISSUE TITLE
模型加载后，退出程序总会报错

### ISSUE THREAD

**Issue by Tomhouxin** [Tencent/ncnn#3058]
## error log | 日志或报错信息 | ログ

![52](https://user-images.githubusercontent.com/23637856/124859373-6977e480-dfe2-11eb-9950-7a2f930e21a8.png)

## context | 编译/运行环境 | バックグラウンド
Windows vs2019
vulkan1.2
ncnn最新的vs2019版本
RTX3060，驱动版本为461.72
原demo：[nanodet](https://github.com/RangiLyu/nanodet)

## how to reproduce | 复现步骤 | 再現方法
1.使用vs2019打开nanodet，运行
2.关闭软件的时候报内存错误

## more | 其他 | その他
1.已验证使用cpu是没毛病的，所以猜测可能是vulkan的问题嘛
2.发现vulkan最新版本支持显卡驱动版本为458.36，但此版本与我的显卡不兼容
3.应该有人会说为啥不用TRT。。。。

**Comment by deepage** [comment]
1.你可以尝试运行benchncnn看看vulkan是否正常。
2.或者你可以尝试下[ncnn/examples/nanodet](https://github.com/Tencent/ncnn/blob/master/examples/nanodet.cpp)

**Comment by liushuan** [comment]
我也遇到了相同的错误@Tomhouxin 你的解决了吗？

**Comment by HwanWoongLee** [comment]
@liushuan did you solved this problem?

**Comment by Yoh-Z** [comment]
nihui: main 函数退出前，调用下 ncnn::destroy_gpu_instance() 试试

**Comment by Tomhouxin** [comment]
@Yoh-Z 曾经试过你这种，但是依旧存在

**Comment by Yoh-Z** [comment]
@Tomhouxin 我的报错信息和你完全一样，在main的return 0;之前调用ncnn::destroy_gpu_instance()解决了问题。

**Comment by Tomhouxin** [comment]
@Yoh-Z 因为我是封装的dll，所以我是在析构函数里加的这句话，应该性质是一样的吧

**Comment by Yoh-Z** [comment]
@Tomhouxin 如果后面没有再调用ncnn的代码就没问题。我也封装了dll，这样也能解决问题。

**Comment by Tomhouxin** [comment]
@Yoh-Z 除此之外，我还有个问题，我在30系列的显卡上好像调用不到GPU

**Comment by Yoh-Z** [comment]
@Tomhouxin emmm，我这里一直是用的20系的显卡，不知道30系的情况。不过按理来说30系显卡运行vulkan也没问题。可以加进ncnn卷卷群艾特nihui试试~

**Comment by Tomhouxin** [comment]
没有，最后还是用的TRT



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月7日(星期二) 下午5:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/ncnn] 模型加载后，退出程序总会报错 (#3058)





 
@Tomhouxin 我也有这个问题，在3060显卡上调用不到GPU，请问你已经解决这个问题了吗

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5234

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/ded0b78bb2926d3fd116c94d988c8e3d836d191a

**Comment by www591rmb** [comment]
我也遇到这样的问题,已经解决.
在销毁前  调用 ncnn::destroy_gpu_instance()
