### ISSUE TITLE
concat 输出结果错误

### ISSUE THREAD

**Issue by niuxiaozhang** [Tencent/ncnn#3059]
## how to reproduce | 复现步骤 | 再現方法
1.测试代码
int main()
{
    int feaNum = 5;
    int oneNum = 3;
    float kpts[1 * 2 * feaNum] = {0};
    float score[1 * 1 * feaNum] = {0};

    for (int i = 0; i<2 * oneNum; i++)
    {

        kpts[i] = 10;
    }
    for (int i = 0; i<1 * oneNum; i++)
    {
        score[i] = 100;
    }
    
    ncnn::Net m_Net;

    std::string param_path = "./testMLP.param";
    std::string bin_path = "./testMLP.bin";

    int ret1 = m_Net.load_param(param_path.c_str());
    int ret2 = m_Net.load_model(bin_path.c_str());

    ncnn::Mat inKpts = ncnn::Mat(1, feaNum, 2, kpts);
    ncnn::Mat inScore = ncnn::Mat(1, feaNum, 1, score);

    ncnn::Extractor ex = m_Net.create_extractor();
    ex.set_light_mode(false);
    ex.input("1", inKpts);
    ex.input("2", inScore);

   //128维特征值（未归一化）
    ncnn::Mat outFeat;
    ex.extract("20", outFeat);
    outFeat = outFeat.reshape(outFeat.w*outFeat.h, outFeat.c);

    for (int i = 0; i < outFeat.h; i++)
    {
		for(int j = 0; j < outFeat.w; j++)
		{
			std::cout << std::setiosflags(std::ios::fixed) << std::setiosflags(std::ios::right)
                    << std::setprecision(8) << outFeat[i*outFeat.w +j]  << " ";
		}
        std::cout << std::endl;
	}
    return 0;
}
[model.zip](https://github.com/Tencent/ncnn/files/6782186/model.zip)

2. ncnn上传到附件了 麻烦帮忙看一下
3.

**Comment by deepage** [comment]
你这个问题是由你自己操作失误造成的，具体错误如下：
1.你给数组赋值时，for的长度不对；
2.你没有考虑到Mat的channel之间有gap。
使用自己数据转到ncnn::Mat可以参考[自己数据转Mat](https://github.com/Tencent/ncnn/blob/master/docs/faq.md#%E5%A6%82%E4%BD%95%E8%BD%AC%E6%8D%A2-float-%E6%95%B0%E6%8D%AE%E4%B8%BA-ncnnmat)
另外，你自己做实验，其实可以直接
``` c++
// 自己数据转Mat
ncnn::Mat inKpts = ncnn::Mat(1*feaNum*2, kpts).reshape(1, feaNum, 2);
ncnn::Mat inScore = ncnn::Mat(1*feaNum*1, score).reshape(1, feaNum, 1);

// 直接构建Mat然后fill
ncnn::Mat inKpts = ncnn::Mat(1, feaNum, 2);
ncnn::Mat inScore = ncnn::Mat(1, feaNum, 1);
inKpts.fill(10.f);
inScore.fill(100.f);
```

**Comment by niuxiaozhang** [comment]
我打印看了一下 我的输入真有问题 现在解决了 非常感谢
