### ISSUE TITLE
更新ncnn版本后，模型输出结果不一致

### ISSUE THREAD

**Issue by niinorz** [Tencent/ncnn#3062]
如果出现跨平台输出不一致的情况，应该如何解决呢？

**Comment by deepage** [comment]
因为你没有提供任何有价值的信息，所以我只能靠盲猜建议了：
1.你可以检查下更新版本之前跨平台是否输出一致，如果之前版本一致，但是更新版本之后不一致，那么你可以贴一下之前版本commit信息以及可以复现的param文件；
2.跨平台输出不一致时，一般是由于输入数据处理方式不同导致的。你可以采用resize好的bmp图片进行测试，或者自己构建一个ncnn::Mat，保证输入一致时，检查输出是否不一致；
3.如果以上都做了，还是不一致，那么可以逐层取出输出数据进行比对，看具体是哪一层导致输出不一致。

**Comment by niinorz** [comment]
> 因为你没有提供任何有价值的信息，所以我只能靠盲猜建议了：
> 1.你可以检查下更新版本之前跨平台是否输出一致，如果之前版本一致，但是更新版本之后不一致，那么你可以贴一下之前版本commit信息以及可以复现的param文件；
> 2.跨平台输出不一致时，一般是由于输入数据处理方式不同导致的。你可以采用resize好的bmp图片进行测试，或者自己构建一个ncnn::Mat，保证输入一致时，检查输出是否不一致；
> 3.如果以上都做了，还是不一致，那么可以逐层取出输出数据进行比对，看具体是哪一层导致输出不一致。
嗯，思路差不多，现在验证代码就是对同一张bmp进行测试。正在对三个不同版本进行排查，20200515(705dd36a)，r20200916，r20210525，目前三个版本的PC（windows，wsl）的输出是一致的，但是已知的是arm上0515和pc的0515结果一致，但和0525的arm不同

**Comment by niinorz** [comment]
> > 因为你没有提供任何有价值的信息，所以我只能靠盲猜建议了：
> > 1.你可以检查下更新版本之前跨平台是否输出一致，如果之前版本一致，但是更新版本之后不一致，那么你可以贴一下之前版本commit信息以及可以复现的param文件；
> > 2.跨平台输出不一致时，一般是由于输入数据处理方式不同导致的。你可以采用resize好的bmp图片进行测试，或者自己构建一个ncnn::Mat，保证输入一致时，检查输出是否不一致；
> > 3.如果以上都做了，还是不一致，那么可以逐层取出输出数据进行比对，看具体是哪一层导致输出不一致。
> 
> 嗯，思路差不多，现在验证代码就是对同一张bmp进行测试。正在对三个不同版本进行排查，20200515([705dd36](https://github.com/Tencent/ncnn/commit/705dd36a3133e0ca3cbbbba1ccb3020064056e76))，r20200916，r20210525，目前三个版本的PC（windows，wsl）的输出是一致的，但是已知的是arm上0515和pc的0515结果一致，但和0525的arm不同

最大的可能还是 option 默认值的问题

**Comment by niinorz** [comment]
基本定位到是 use_fp16_arithmetic 这个参数引起的，在 20200916 之后的版本，这个选项需要设置为 false，在 aarch64 的机器上的结果才能和PC对的上，但是精度差异有点大，个别数值差异能到 0.08 左右

**Comment by niinorz** [comment]
参考 https://github.com/Tencent/ncnn/issues/2703

`  
  net.opt.use_fp16_packed = false;
  net.opt.use_fp16_storage = false;
  net.opt.use_fp16_arithmetic = false;
`
已经 -DNCNN_ARM82=OFF 后，结果一致了
