### ISSUE TITLE
Typo in method name

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#3073]
Just an FYI, there is a typo in this method name [here](https://github.com/Tencent/ncnn/blob/5049aaeabd3e36ad4131ad46da3ecd12c973eea6/src/mat.h#L281).

I think you meant "subtract" instead of "substract", so that would require changing `substract_mean_normalize` to `subtract_mean_normalize`.

**Comment by zchrissirhcz** [comment]
Yes, this is a known typo.

However, to keep API compatibility, this typo won't change.

Other many typos have been changed in my previous PRs.
