### ISSUE TITLE
pc x86电脑，cpu, onnxruntime，运行时间比ncnn快一倍,建议下一版本对x86优化。

### ISSUE THREAD

**Issue by xinsuinizhuan** [Tencent/ncnn#3099]
## detail | 详细描述 | 詳細な説明
windows10 vs2019 cpu
现在很多模型训练完后，均为onnx模型，直接使用onnxruntime 加载模型，速度比转换成ncnn模型后运行，速度快一倍。
比如：我使用chinise_lite的ocr模型，同样的onnxruntime运行时间为500ms，但是使用ncnn推理需要1130ms。
ncnn在pc x86端加载onnx模型上已经明显慢于onnxruntime，建议下一版本进行优化。

**Comment by jnulzl** [comment]
@xinsuinizhuan 那你PC端可以直接用onnxruntime

**Comment by m657438565** [comment]
对呀 直接用 onnxruntime   我也是X86   不管速度 快慢=。=  NCNN 是一种情怀  哈哈哈哈 一直在用ncnn

**Comment by xinsuinizhuan** [comment]
ncnn比较通用，手机端，pc端，维护一套代码即可

**Comment by nihui** [comment]
最新版本的ncnn，对 x86 优化了几波，性能快了很多！推荐更新试试
另外，pc 也很适合使用 vulkan，支持独显和集显

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
