### ISSUE TITLE
性能好像没有发挥出来

### ISSUE THREAD

**Issue by simonzeus** [Tencent/ncnn#31]
在RK3288上4核全开，squeezenet要220多ms，和tensorflow相比，不算有优势的。

**Comment by nihui** [comment]
参考这个
#28

**Comment by zhiminzhou** [comment]
我在在RK3288上4核全开，squeezenet要400ms左右，求问你的200ms是怎么编译的

**Comment by simonzeus** [comment]
你3288的主频是多少？我改到了1.6GHz

**Comment by Andrawzyf** [comment]
@simonzeus 可以请问一下怎么测试性能么？有没有例子参考下呀

**Comment by nihui** [comment]
最新代码已改善 arm linux 的编译支持并且速度有优化
