### ISSUE TITLE
Anyone knows the full name of ncnn?

### ISSUE THREAD

**Issue by Onemaeus97** [Tencent/ncnn#3104]
Hi, just curious to know what does ncnn stands for? A novel computing neural network? Thanks

**Comment by zchrissirhcz** [comment]
It may stands for many full name, each one is ok:
- new/next cnn
- naive cnn
- neon cnn (originally optimized for arm neon on smart phones)
- Nihui's cnn, where its the author's name

See wiki's Home page for reference https://github.com/Tencent/ncnn/wiki

```
Q ncnn名字的来历

A cnn就是卷积神经网络的缩写，开头的n算是一语n关。比如new/next(全新的实现)，naive(ncnn是naive实现)，neon(ncnn最初为手机优化)，up主名字(←_←)

```

**Comment by caishanli** [comment]
nihui's cute neural network
