### ISSUE TITLE
[aarch64] Error: invalid register list at operand 1

### ISSUE THREAD

**Issue by imkow** [Tencent/ncnn#312]
/tmp/ccmdPLf6.s: Assembler messages:
/tmp/ccmdPLf6.s:13895: Error: invalid register list at operand 1 -- `ld1 {v6.4s,v3.4s,v7.4s,v16.4s},[x20],#64'
/tmp/ccmdPLf6.s:13897: Error: invalid register list at operand 1 -- `ld1 {v17.4s,v4.4s,v18.4s,v19.4s},[x20],#64'
/tmp/ccmdPLf6.s:13899: Error: invalid register list at operand 1 -- `ld1 {v20.4s,v5.4s,v21.4s,v22.4s},[x20],#64'
/tmp/ccmdPLf6.s:13901: Error: invalid register list at operand 1 -- `ld1 {v23.4s,v2.4s,v24.4s,v25.4s},[x20],#64'
/tmp/ccmdPLf6.s:14471: Error: invalid register list at operand 1 -- `ld1 {v3.4s,v0.4s},[x20],#32'
src/CMakeFiles/ncnn.dir/build.make:518: recipe for target 'src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o' failed

GCC5.4 aarch64 on Linux

**Comment by imkow** [comment]
the same problem still exists. thx

**Comment by imkow** [comment]
@nihui the same problem still exists. thx

**Comment by nihui** [comment]
make sure you have updated to the latest code and played with clean build

**Comment by imkow** [comment]
@nihui pretty sure I'd pulled the latest code and built completely clean. Thx.

**Comment by imkow** [comment]
@nihui 换了个板子, 系统不同, 但也是ARM64, GCC 6.3 同样问题
/tmp/cc0u01PH.s: Assembler messages:
/tmp/cc0u01PH.s:12395: Error: invalid register list at operand 1 -- `ld1 {v6.4s,v3.4s,v7.4s,v16.4s},[x20],#64'
/tmp/cc0u01PH.s:12397: Error: invalid register list at operand 1 -- `ld1 {v17.4s,v4.4s,v18.4s,v19.4s},[x20],#64'
/tmp/cc0u01PH.s:12399: Error: invalid register list at operand 1 -- `ld1 {v20.4s,v5.4s,v21.4s,v22.4s},[x20],#64'
/tmp/cc0u01PH.s:12401: Error: invalid register list at operand 1 -- `ld1 {v23.4s,v2.4s,v24.4s,v25.4s},[x20],#64'
/tmp/cc0u01PH.s:12972: Error: invalid register list at operand 1 -- `ld1 {v3.4s,v0.4s},[x20],#32'
src/CMakeFiles/ncnn.dir/build.make:518: recipe for target 'src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o' failed
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o] Error 1

**Comment by nihui** [comment]
reopen untill new workaround lands
