### ISSUE TITLE
solov2模型onnx转换NCNN出现问题

### ISSUE THREAD

**Issue by Evoluange** [Tencent/ncnn#3131]
solov2训练完成转换成onnx模型之后，通过onnx2ncnn转换成ncnn模型过程中出现问题，有一些层不支持，这个有啥方法解决？
![20210802160041](https://user-images.githubusercontent.com/25747262/127829261-9f14f706-31e6-4f8b-8553-6fdbd77424aa.png)
错误出现在kernel_pred层，在conv和permute之间有equal+cast操作不支持
onnx模型和转换后ncnn的param文件如下：
[solov2.zip](https://github.com/Tencent/ncnn/files/6915520/solov2.zip)

**Comment by huazai-1994** [comment]
@Evoluange 我遇到了同样的问题，请问你是怎么解决的？

**Comment by Evoluange** [comment]
我这个版本比较老，你可以在高版本下进行

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
