### ISSUE TITLE
build ncnn for Allwinner D1  'vmnot_m_b4' was not declared in this scope

### ISSUE THREAD

**Issue by jie2311260561** [Tencent/ncnn#3132]
## error log | 日志或报错信息 | ログ
ncnn/src/layer/riscv/selu_riscv.cpp:47:32: error: 'vmnot_m_b4' was not declared in this scope; did you mean 'vmnor_mm_b4'?
   47 |             vbool4_t _higher = vmnot_m_b4(_lower, vl);
      |                                ^~~~~~~~~~
      |                                vmnor_mm_b4

## context | 编译/运行环境 | バックグラウンド
echo $RISCV_ROOT_PATH
/home/gaojies/Tools/riscv64-linux-x86_64-20210512

 cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/c906.toolchain.cmake -DCMAKE_BUILD_TYPE=relwithdebinfo -DNCNN_OPENMP=OFF -DNCNN_THREADS=OFF -DNCNN_RUNTIME_CPU=OFF -DNCNN_RVV=ON -DNCNN_SIMPLEOCV=ON -DNCNN_BUILD_EXAMPLES=ON ..

之前编译通过，听闻 RISCV又有优化进展，同步后重新编译   就报错了

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/da7b64b83359588106b7e822c0bf7f775ea520db
