### ISSUE TITLE
量化后模型加载出现“ModelBin read index_array failed”

### ISSUE THREAD

**Issue by Z-Xiong** [Tencent/ncnn#3135]
## error log | 日志或报错信息 | ログ
```
ModelBin read index_array failed 13248
layer load_model 86 failed
Segmentation fault
```

## model | 模型 | モデル
https://gitee.com/Shawn-Xiong/model

模型量化前加载没有问题，请问会是哪里出问题了呢?

**Comment by nihui** [comment]
尝试使用最新的 ncnn 版本和对应版本的量化工具

**Comment by Z-Xiong** [comment]
> 尝试使用最新的 ncnn 版本和对应版本的量化工具

谢谢up，原因是转换模型的工具和量化工具的ncnn版本和推理时用的ncnn版本不一致，我重新使用比较新的ncnn的库就可以了
