### ISSUE TITLE
load model from memory makes a copy

### ISSUE THREAD

**Issue by mtamburrano** [Tencent/ncnn#3139]
## detail

Hi,
I switched from using the loading from filepath to loading from memory and I'm noticing that the usage of the memory is doubled.
From [here](https://github.com/Tencent/ncnn/blob/169614f73244a332c03102f998f288f48a80d85d/src/net.h#L101) it looks like that the memory is only referenced but it looks like it is not the case. Inspecting the code deeply I found [this line](https://github.com/Tencent/ncnn/blob/8cc8cd716a432fa1c579e0ee4f88ebeb96336e39/src/modelbin.cpp#L138) where it seems that in fact the memory is copied when dealing with int8 weights (and it is my case, my model is 8 bit quantized).
Am I right? Is the referencing from quantized 8bit models not supported?
My workaround is to release the memory right after loading the model and seems working, but still the peak of the memory is double the size of the model for few seconds. Is there a better way to avoid this issue?

If I am correct and there is not a clean workaround, is planned to add support for memory referencing for 8bit models? Can you point me what is needed to be done to add this feature? I can try to help for a PR

**Comment by mtamburrano** [comment]
@nihui any suggestions? Just a confirmation that the memory can be externally released after loading the model it would be enough.

**Comment by nihui** [comment]
fixed
