### ISSUE TITLE
error: undefined reference to 'DeleteUniformMap(TUniformMap*)'

### ISSUE THREAD

**Issue by vvxt** [Tencent/ncnn#3152]
## detail | 详细描述 | 詳細な説明
android studio 4.2.2 vulkan NDK编译报错：D:/ncnn/glslang/glslang/MachineIndependent/ShaderLang.cpp:1396: error: undefined reference to 'DeleteUniformMap(TUniformMap*)'

源码是2021年8月6日git拉的代码，ncnn cpu和vulkan编译没有问题，在ndk CMakeLists.txt中基本设置如下：
include_directories(${CMAKE_SOURCE_DIR}/src/main/cpp/ncnn)
include_directories(${CMAKE_SOURCE_DIR}/src/main/cpp/glslang)

set(GenericCodeGen ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libGenericCodeGen.a)
add_library(GenericCodeGen STATIC IMPORTED)
set(glslang ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libglslang.a)
add_library(glslang STATIC IMPORTED)
set(MachineIndependent ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libMachineIndependent.a)
add_library(MachineIndependent STATIC IMPORTED)
set(OGLCompiler ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libOGLCompiler.a)
add_library(OGLCompiler STATIC IMPORTED)
set(OSDependent ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libOSDependent.a)
add_library(OSDependent STATIC IMPORTED)
set(SPIRV ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libSPIRV.a)
add_library(SPIRV STATIC IMPORTED)
set_target_properties(GenericCodeGen PROPERTIES IMPORTED_LOCATION ${GenericCodeGen})
set_target_properties(glslang PROPERTIES IMPORTED_LOCATION ${glslang})
set_target_properties(MachineIndependent PROPERTIES IMPORTED_LOCATION ${MachineIndependent})
set_target_properties(OGLCompiler PROPERTIES IMPORTED_LOCATION ${OGLCompiler})
set_target_properties(OSDependent PROPERTIES IMPORTED_LOCATION ${OSDependent})
set_target_properties(SPIRV PROPERTIES IMPORTED_LOCATION ${SPIRV})
set(ncnn ${CMAKE_SOURCE_DIR}/src/main/jniLibs/${ANDROID_ABI}/libncnn.a)
add_library(ncnn STATIC IMPORTED )
set_target_properties(ncnn PROPERTIES IMPORTED_LOCATION ${ncnn})

...

add_library( omp SHARED IMPORTED)
set_target_properties( omp PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/libs/${ANDROID_ABI}/libomp.so )

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DANDROID_PLATFORM=android-24")

target_include_directories(channel_vis PRIVATE
        ${CMAKE_SOURCE_DIR}/src/main/cpp/ncnn
        ${CMAKE_SOURCE_DIR}/src/main/cpp/glslang
        )

target_link_libraries( channel_vis ${OpenCV_LIBS}
        ncnn omp
        glslang GenericCodeGen MachineIndependent SPIRV OGLCompiler OSDependent
        vulkan
        jnigraphics
        android avutil-55 swresample-2 avcodec-57 avfilter-6 swscale-4 avdevice-57 avformat-57
        ${log-lib}
        )

然后报如下错误：
[3/3] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libchannel_vis.so
FAILED: ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libchannel_vis.so 
cmd.exe /C "cd . && C:\Users\vvxt\AppData\Local\Android\Sdk\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi24 --gcc-toolchain=C:/Users/vvxt/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Users/vvxt/AppData/Local/Android/Sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -DANDROID_PLATFORM=android-24 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libchannel_vis.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libchannel_vis.so @CMakeFiles/channel_vis.rsp  && cd ."
D:/ncnn/glslang/glslang/MachineIndependent/ShaderLang.cpp:1359: error: undefined reference to 'ConstructCompiler(EShLanguage, int)'
D:/ncnn/glslang/glslang/MachineIndependent/ShaderLang.cpp:1369: error: undefined reference to 'ConstructLinker(EShExecutable, int)'
D:/ncnn/glslang/glslang/MachineIndependent/ShaderLang.cpp:1379: error: undefined reference to 'ConstructUniformMap()'
D:/ncnn/glslang/glslang/MachineIndependent/ShaderLang.cpp:1392: error: undefined reference to 'DeleteCompiler(TCompiler*)'
D:/ncnn/glslang/glslang/MachineIndependent/ShaderLang.cpp:1394: error: undefined reference to 'DeleteLinker(TShHandleBase*)'
D:/ncnn/glslang/glslang/MachineIndependent/ShaderLang.cpp:1396: error: undefined reference to 'DeleteUniformMap(TUniformMap*)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by vvxt** [comment]
追加：如果把前一部分链接删掉，然后改为如下：
set(ncnn_DIR D:/ncnn/build-android-armv7-vulkan/install/lib/cmake/ncnn)
find_package(ncnn REQUIRED)

则运行后报如果下错误：
E/vulkan: invalid vkGetInstanceProcAddr(VK_NULL_HANDLE, "vkEnumerateInstanceVersion") call

**Comment by chingi071** [comment]
@vvxt 請問你這個問題解決了嗎? 我也遇到相同問題，請問你是怎麼解決的呢?
我的設置在這邊: https://github.com/Tencent/ncnn/issues/3247
謝謝您。
