### ISSUE TITLE
关于ncnn静态库的openmp编译、链接选项属性不相同的疑问

### ISSUE THREAD

**Issue by zchrissirhcz** [Tencent/ncnn#3174]
## 问题描述
分别在 Android 和 PC 平台编译带 openmp 的 ncnn 静态库， 然后 benchncnn.cpp 改造为如下内容：
```c++
#include <stdio.h>
#include <omp.h>

int main(int argc, char** argv)
{
    omp_set_dynamic(0);
    #pragma omp parallel
    {
        fprintf(stderr, ">>> hello\n");
    }

    return 0;
}
```
预期结果是输出多行 `>>> hello`， 实际结果是， PC 输出多行， Android 平台只输出单行。

## 尝试排查

- 编译阶段， cmake开启 -DNCNN_OPENMP， 并且不开启 -DNCNN_SIMPLEOMP

- src/CMakeLists.txt 中， ndk>20 时，对openmp 的编译选项是PRIVATE， 链接选项是PUBLIC属性：

```cmake
            target_compile_options(ncnn PRIVATE -fopenmp)
            target_link_libraries(ncnn PUBLIC -fopenmp -static-openmp)
```
- ncnn这一静态库目标的**编译选项**中，-fopenmp 是 **PRIVATE** 属性；
- ncnn这一惊天库目标的**链接**选项中，-fopenmp -static-openmp 是 **PUBLIC** 属性

- 而其他情况下（老的NDK、PC+高版本CMake、低版本CMake）时，PUBLIC/PRIVATE也不统一

https://github.com/Tencent/ncnn/blob/ec561736a5ca4f3853c2b48319efb2bb77b82889/src/CMakeLists.txt#L221-L228

```cmake
        if(NCNN_SIMPLEOMP)
            ...
        elseif(ANDROID_NDK_MAJOR AND (ANDROID_NDK_MAJOR GREATER 20))
            target_compile_options(ncnn PRIVATE -fopenmp)
            target_link_libraries(ncnn PUBLIC -fopenmp -static-openmp)
        elseif(OpenMP_CXX_FOUND)
            target_link_libraries(ncnn PUBLIC OpenMP::OpenMP_CXX)
        else()
            target_link_libraries(ncnn PRIVATE "${OpenMP_CXX_FLAGS}")
        endif()
```

也就是说， Android NDK >= 21 之外的各种情况下， 编译链接openmp时也存在 PUBLIC 和 PRIVATE 的差异。

## 具体讨论

这个 PRIVATE 或 PUBLIC 属性， 对 ncnn 静态库本身没有影响； 影响的是依赖了 ncnn 静态库的动态库或可执行目标：在用户自行魔改的 benchncnn.cpp 中， 又或者用户是移植了 ncnn 里 OpenMP 的 cmake 写法，用户原本只有两种期待结果：
- 我包含了 omp.h, 调用了 `omp_set_dynamic( )` 等 API， 它应该编译通过，链接也通过，然后运行时候确实是多线程行为
- 包含了omp.h, 调用了  `omp_set_dynamic( )` 等 API， 它应该编译时就报错，及早发现问题

而上述例子中在 android 平台，发生的是第三种情况：
- 包含了 omp.h, 调用了  `omp_set_dynamic( )` 等 API， 编译不报错，链接也不报错， 但是运行的时候没有多线程行为。

个人的看法是，统一弄成 PUBLIC 属性。不过不清楚部分情况设为 PRIVATE 是否有其他考虑？

**Comment by nihui** [comment]
因为 ncnn 本身没有给外部暴露 openmp 的调用，即 h 中没有 openmp 的调用代码，所以用 private 减少污染..

**Comment by zchrissirhcz** [comment]
我大概理解一下， ncnn 的 cmake 尽可能清真，我觉得可以都弄成 PRIVATE

> 静态库 link flag 需要 public

这里我不是很理解。 我觉得是因为 android ndk > 20 ， 需要链接静态的 openmp 库， 而 cmake 的 FindOpenMP.cmake 只能找到动态库，所以写法上，从 target_link_libraries(ncnn PRIVATE OpenMP::OpenMP_CXX) 换成了分别指定编译和链接选项。而 OpenMP::OpenMP_CXX 看起来是会自动设定编译和链接选项。

新一次 commit 是通过存储原有的 find_library 的查找后缀、 显式指定为.a ， 然后find_package(OpenMP) ， 再恢复原来的查找后缀。这样能够在 android ndk > 20 情况下找到 libopenmp.a ， 复用了`OpenMP::OpenMP_CXX`.
