### ISSUE TITLE
Does NCNN support 3D convolution now?

### ISSUE THREAD

**Issue by j71200** [Tencent/ncnn#3180]
## error log | 日志或报错信息 | ログ
I know NCNN did not support 3D convolution in 2019. (https://github.com/Tencent/ncnn/issues/889)
But I still wanna give it a try.
At first, I have a PyTorch 3D convolution model.
PyTorch model -> ONNX model is fine
ONNX model -> simplified ONNX model is fine
simplified ONNX model -> NCNN model is fine (The model convertor did not show any error message like not support 3D convolution)
However, when I call
`ncnn::Extractor ex = resnet3d.create_extractor();`
an exception "Integer division by zero" popped out.

_**I wonder that is the exception due to NCNN does not support 3D convolution.**_
_**If NCNN does not support 3D convolution, will NCNN support 3D convolution in the near feature?**_

Thanks

## model | 模型 | モデル
1. https://github.com/kenshohara/3D-ResNets-PyTorch/blob/master/models/resnet.py

## how to reproduce | 复现步骤 | 再現方法
1.  Use PyTorch 1.7.1 to convert PyTorch model to ONNX
2. Use onnx-simplifier(0.3.4) to simplify ONNX model
3. Use onnx2ncnn tool from NCNN(20200916) to convert ONNX to NCNN
4. The code is shown below

ncnn::Net resnet3d;
resnet3d.load_param("resnet3Dmodel.param");
resnet3d.load_model("resnet3Dmodel.bin");

ncnn::Mat in = ncnn::Mat::from_pixels_resize(image.data, ncnn::Mat::PIXEL_BGR, image.cols, image.rows, image.cols, image.rows);
const float mean_vals[3] = { 0, 0, 0 };
const float norm_vals[3] = { 1.0 / 255, 1.0 / 255, 1.0 / 255 };
in.substract_mean_normalize(mean_vals, norm_vals);

ncnn::Mat out;
ncnn::Extractor ex = resnet3d.create_extractor();
ex.input("input", in);
ex.extract("output", out);

**Comment by nihui** [comment]
3d convolution is supported out of the box if you use pnnx tool to convert your fancy conv3d model to ncnn
https://github.com/pnnx/pnnc

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
