### ISSUE TITLE
模型每一次层channel数量问题

### ISSUE THREAD

**Issue by geoffzhang** [Tencent/ncnn#3190]
## detail | 详细描述 | 詳細な説明
你好，我想问一下，通道数降低，前传速度反而变慢怎么回事；
下面cfg0是原始的通道数，cfg1是剪枝后的通道数， 使用cfg1的速度比cfg0的速度更慢98.27ms vs 92.13ms。
输入为1080x1080, 四线程
cfg0 = [8, 8, 16, 16, 32, 32, 32, 32, 64, 64, 64, 64, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 128, 256, 256, 256]
cfg1 = [5, 5, 10, 10, 20, 20, 23, 23, 43, 43, 48, 48, 90, 90, 69, 69, 51, 51, 40, 40, 33, 33, 63, 63, 159, 159, 195]；

请问，通道数是需要向某一个数对齐吗？

**Comment by nihui** [comment]
通道数尽可能是 4 倍数，8 倍数更好

**Comment by geoffzhang** [comment]
好的，谢谢，验证过了是这样的
