### ISSUE TITLE
Could the weight be used between different layers?

### ISSUE THREAD

**Issue by grimoire** [Tencent/ncnn#3191]
## detail
Hi
I am trying to convert the model with onnx2ncnn. It's cool, but the converted model is larger than I expected.
I found that weight of some layers might be write to `.bin` multiple times. for example:
```python
# multiple feature maps
feats = feat_extract()

results = []
for feat in feats:
     result += [head(feat)]

results = concate(results)
```

The model file grows large cause the weights of the head will be writing again and again.
Is there anything I can do to reuse the weight?
Or is it possible to write `.bin` with another format (such as key-value pair)?

**Comment by nihui** [comment]
export your model to two onnx files, one for feat_extract, another for head
convert two onnx files to two couples of ncnn model files
implement the loop in c++ and run inference for head part in loop body

```cpp
feat_net_ex.extract("feat_ouptut", feats);

for loop
    slice feat like feat = feats.channel_range(i, 1);
    head_net_ex.input(“feat", feat);
    head_net_ex.extract("head_output", result);
    add result
```

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
