### ISSUE TITLE
How to convert custom model with YOLOX_L weight to NCNN

### ISSUE THREAD

**Issue by RTae** [Tencent/ncnn#3196]
## detail | 详细描述 | 詳細な説明
Hi, Now I work with the YOLOX model, I train my custom model with yolox-l weight. After I finish my training I want to convert from ONNX to NCNN. From YOLOX repository's document, it show how to convert from yolox-s onnx to ncnn. What's about yolox-l, it's using the same parameter as yolox-s ?

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
