### ISSUE TITLE
请问ncnn2mem是做什么用的？squeezenet_v1.1.param是如何生成的

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/ncnn#32]
请问ncnn2mem是做什么用的？
另外我试了./caffe2ncnn squeezenet_v1.1.prototxt squeezenet_v1.1.caffemodel
只得到了ncnn.bin和ncnn.proto ， example里面的squeezenet_v1.1.param 是怎么转换得到的？

**Comment by nihui** [comment]
squeezenet_v1.1.param 就是 ncnn,proto
ncnn2mem 是把 bin 和 param 转换成二进制数组
https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet

**Comment by huanyingjun** [comment]
thanks

**Comment by xujialiang** [comment]
> squeezenet_v1.1.param 就是 ncnn,proto
> ncnn2mem 是把 bin 和 param 转换成二进制数组
> https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet

我转换时报错了，segmentation fault:11 这是为什么呀？
