### ISSUE TITLE
Model output with all dimensions are 0 - ncnn-20210720

### ISSUE THREAD

**Issue by vietanhdev** [Tencent/ncnn#3201]
## context | 编译/运行环境 | バックグラウンド

I have output with all 0 in out.w, out.h or out.c.

**Environment:** 

- Android app, ncnn-20210720-android-vulkan.
- The model is converted from onnx with ncnn 20210720.

## how to reproduce | 复现步骤 | 再現方法

1. Use this code to run the below model and check the output.

```
cv::Mat rgb = image.clone();
  ncnn::Mat in = ncnn::Mat::from_pixels_resize(
          rgb.data, ncnn::Mat::PIXEL_RGB, rgb.cols, rgb.rows, _input_width,
          _input_height);
  ncnn::Extractor ex = _model->create_extractor();
  ex.set_light_mode(true);
  ex.set_num_threads(4);
  ex.input("input_1", in);
  ncnn::Mat out;
  ex.extract(20, out); // Extract the last output
```
[model.zip](https://github.com/Tencent/ncnn/files/7081055/model.zip)

**Comment by vietanhdev** [comment]
Fixed by changing my code. Thank you.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
