### ISSUE TITLE
pth转ONNX转NCNN,替换nanodet -master里的模型，启动后无法识别

### ISSUE THREAD

**Issue by Newsir** [Tencent/ncnn#3204]
## error log | 日志或报错信息 | ログ
无报错
## model | 模型 | モデル
1. original model

## how to reproduce | 复现步骤 | 再現方法
1.训练好的.pth可以在pc上正常识别，利用nanodet自带的export导出成为onnx后简化，
2.再使用https://convertmodel.com/ 进行ncnn的转换
3.替换ncnn-android-nanodet-master项目中的某一个模型然后修改名称，打包安装后无法识别
如何解决呢

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by Edward-YS** [comment]
> ## error log | 日志或报错信息 | ログ
> 无报错
> 
> ## model | 模型 | モデル
> 1. original model
> 
> ## how to reproduce | 复现步骤 | 再現方法
> 1.训练好的.pth可以在pc上正常识别，利用nanodet自带的export导出成为onnx后简化， 2.再使用https://convertmodel.com/ 进行ncnn的转换 3.替换ncnn-android-nanodet-master项目中的某一个模型然后修改名称，打包安装后无法识别 如何解决呢
您好！
请问有重识别吗？

**Comment by Newsir** [comment]
检查blob的输出，老版本是模型文件里面的三个层参数要和代码里面对应上，新版本三个参数合成一个了，历史久远需要看到具体的模型内容才能给出回答

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Edward-YS ***@***.***&gt;
发送时间: 2024年11月14日 12:54
收件人: Tencent/ncnn ***@***.***&gt;
抄送: Newsir ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [Tencent/ncnn] pth转ONNX转NCNN,替换nanodet -master里的模型，启动后无法识别 (#3204)





  
error log | 日志或报错信息 | ログ
 
无报错
 
model | 模型 | モデル
  
original model
  
how to reproduce | 复现步骤 | 再現方法
 
1.训练好的.pth可以在pc上正常识别，利用nanodet自带的export导出成为onnx后简化， 2.再使用https://convertmodel.com/ 进行ncnn的转换 3.替换ncnn-android-nanodet-master项目中的某一个模型然后修改名称，打包安装后无法识别 如何解决呢
 您好！
 请问有重识别吗？
