### ISSUE TITLE
关于ncnn框架对多模型并行推理的支持

### ISSUE THREAD

**Issue by bestpower** [Tencent/ncnn#3209]
目前部署框架均支持同一模型的多线程推理，请问ncnn框架在安卓端是否支持不同模型的并行推理？
如果支持的话该如何实现，或者给一个示例代码？
比如设备是4核cpu，我想同时跑四个不同模型，且四个模型的推理流程均互不干扰，尽量最大限度的发挥每个cpu性能，该如何实现？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/issues/1623

这里有个例子，A模型跑4线程小核心，B模型跑1线程大核心

**Comment by bestpower** [comment]
我按这个思路写代码自测了一下，在8核的安卓设备上并行跑两个模型（每个模型设置4线程）跑出的结果和串行跑两个模型（每个模型设置8线程）的总耗时几乎是一样的，按理说应该和单独跑两个模型（4线程）中最大的耗时一致，结果也相差了1/3左右。

**Comment by nihui** [comment]
你得绑定大核心或者小核心，小核心4线程比大核心1线程慢也很正常

**Comment by bestpower** [comment]
针对有大小核心的设备测试耗时应该没什么问题，但是我们大部分产品是没有大小核心的，主要是4核或者8核的，通过ncnn::get_big_cpu_count()获取到的数值就是4或者8，而ncnn::get_little_cpu_count()获取到的数值为0，我把每个模型分配1或2个线程，并行跑4个模型，最后的总耗时比每个模型分配满线程串行跑最后的总耗时多出30%左右，我们做多线程主要是为了混合模型推理加速的，如果不能比混合模型串行更快，那做这个多线程就没什么意义了，貌似ncnn没有绑定具体单个核心的功能吧

**Comment by ujsyehao** [comment]
@bestpower 在ubuntu系统里可以将进程绑定到cpu大、小核心，写个配置文件就行

**Comment by ujsyehao** [comment]
@bestpower 或者
`const CpuSet& get_cpu_thread_affinity_mask(int powersave)
{
    setup_thread_affinity_masks();

    if (powersave == 0)
        return g_thread_affinity_mask_all;

    if (powersave == 1)
        return g_thread_affinity_mask_little;

    if (powersave == 2)
        return g_thread_affinity_mask_big;

    NCNN_LOGE("powersave %d not supported", powersave);

    // fallback to all cores anyway
    return g_thread_affinity_mask_all;
}`
改写下这个函数，绑定到具体某个cpu核心上

**Comment by bestpower** [comment]
> @bestpower 或者
> 
> ```
> const CpuSet& get_cpu_thread_affinity_mask(int powersave)
> {
>     setup_thread_affinity_masks();
> 
>     if (powersave == 0)
>         return g_thread_affinity_mask_all;
> 
>     if (powersave == 1)
>         return g_thread_affinity_mask_little;
> 
>     if (powersave == 2)
>         return g_thread_affinity_mask_big;
> 
>     NCNN_LOGE("powersave %d not supported", powersave);
> 
>     // fallback to all cores anyway
>     return g_thread_affinity_mask_all;
> }
> ```
> 
> 改写下这个函数，绑定到具体某个cpu核心上

感谢告知，我试试！
