### ISSUE TITLE
运行ncnn出现  out 出现-nan的情况

### ISSUE THREAD

**Issue by zhangchenchen-novauto** [Tencent/ncnn#3221]
## error log | 日志或报错信息 | ログ
![ncnn](https://user-images.githubusercontent.com/84957934/133070482-6122ce22-2bb7-41ed-b2a5-fe006abbce8b.png)

## context | 编译/运行环境 | バックグラウンド
ncnn 最新版,昨天刚git的，ubuntu x86直接变异valkun-off
## how to reproduce | 复现步骤 | 再現方法
1. tensorflow = 1.5.1  python=3.6 onnxrutime =1.8.1
2. 
[testonnx.py.txt](https://github.com/Tencent/ncnn/files/7153615/testonnx.py.txt)

2. 运行的结果 
3. 
![onnx](https://user-images.githubusercontent.com/84957934/133070849-b8a3071a-b65b-45be-aeb7-b303c3c38651.png)

3. onnx model 
4. 
[AnimeGANv2slim.onnx.txt](https://github.com/Tencent/ncnn/files/7153619/AnimeGANv2slim.onnx.txt)
ncnn model 
[AnimeGANv2.bin.txt](https://github.com/Tencent/ncnn/files/7153621/AnimeGANv2.bin.txt)
[AnimeGANv2.param.txt](https://github.com/Tencent/ncnn/files/7153623/AnimeGANv2.param.txt)

## more | 其他 | その他
ncnn main.cpp
[AnimeGANv2.cpp.txt](https://github.com/Tencent/ncnn/files/7153629/AnimeGANv2.cpp.txt)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
