### ISSUE TITLE
段错误

### ISSUE THREAD

**Issue by MR-520DAI** [Tencent/ncnn#3229]
我首先用Tensorflow训练了一个手写数字识别模型，然后将其转换为onnx模型，最后将onnx模型转换为ncnn模型。
参考example加载模型，并读入图像进行推理，最终能够获得正确的预测结果，但是推理完成后会出现段错误。请问是我的模型有问题吗？但为什么又能获得正确的预测结果呢？
具体代码：
#include<vector>
#include<iostream>
#include"ncnn/net.h"
#include <opencv2/opencv.hpp>

void GetRlt()
{
	cv::Mat img = cv::imread("../7.jpg", 0);
	ncnn::Mat in = ncnn::Mat::from_pixels_resize(img.data, ncnn::Mat::PIXEL_GRAY, img.cols, img.rows, 28, 28);
	ncnn::Mat out;
	
	ncnn::Net net;
	net.load_param("../minist-1.param");
	net.load_model("../minist-1.bin");
	
	ncnn::Extractor ex = net.create_extractor();

	ex.input("img", in);
	ex.extract("prob", out);
	
	//std::vector<int> classrlt;
	//classrlt.resize(out.w);
	
	for(int i = 0; i < out.w; i++)
	{
		//classrlt[i] = out[i];
		std::cout<<out[i]<<std::endl;
	}
	net.clear();
	std::cout<<"net clear!"<<std::endl;
}

int main()
{
	GetRlt();
	
	std::cout<<"11111"<<std::endl;
	
	return 0;
}

bugs：
![image](https://user-images.githubusercontent.com/43158292/133428276-c43c4d27-a695-4456-acf0-c37ff5f9f62d.png)

**Comment by zhangchenchen-novauto** [comment]
`PoolAllocator::~PoolAllocator()
{
    clear();

    if (!d->payouts.empty())
    {
        NCNN_LOGE("FATAL ERROR! pool allocator destroyed too early");
#if NCNN_STDIO
        std::list<std::pair<size_t, void*> >::iterator it = d->payouts.begin();
        for (; it != d->payouts.end(); ++it)
        {
            void* ptr = it->second;
            NCNN_LOGE("%p still in use", ptr);
        }
#endif
    }

    delete d;
}`

**Comment by nihui** [comment]
out 需要在 net 实例析构前先析构，如调用 out.clear()

**Comment by MR-520DAI** [comment]
我首先使用了out.clear()，但提示ncnn::Mat 没有该方法（编译阶段无法通过），然后我又使用了out.release()（能够编译通过），但仍然会报段错误
![image](https://user-images.githubusercontent.com/43158292/133870977-bca3b726-8e3c-4b5a-bbf1-ea7cac86e292.png)
![1](https://user-images.githubusercontent.com/43158292/133870983-a485b897-1108-41eb-80ec-64b1e78f4ae8.PNG)

**Comment by MR-520DAI** [comment]
感谢回复，我自己发现了问题，ncnn::Extractor ex = net.create_extractor();
是ex变量没有释放内存，我添加语句：ex.clear();程序能够正常工作！！！！

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
