### ISSUE TITLE
当前最新版本RISCV编译未通过

### ISSUE THREAD

**Issue by jiaomingjun** [Tencent/ncnn#3230]
我在Tag-20210720的版本成功编译了全志D1-RISCV的版本并使用benchmark进行了测试，但是git pull到最新的版本后，重新编译D1-RISCV时，在进行到 cmake --build . -j 4 这一步时，报了以下的错误导致编译失败：
/Workspace/ncnn/src/layer/riscv/softmax_riscv.cpp:227:22: error: 'vfredosum_vs_f32m8_f32m1' was not declared in this scope; did you mean 'vfredsum_vs_f32m8_f32m1'?
  227 |                 _s = vfredosum_vs_f32m8_f32m1(_s, _p, _s, vl);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~
      |                      vfredsum_vs_f32m8_f32m1
/Workspace/ncnn/src/layer/riscv/softmax_riscv.cpp:467:35: error: 'vfredmax_vs_f32m8_f32m1' was not declared in this scope; did you mean 'vfredsum_vs_f32m8_f32m1'?
  467 |                     _scalar_max = vfredmax_vs_f32m8_f32m1(_scalar_max, _p, _scalar_max, vl);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
      |                                   vfredsum_vs_f32m8_f32m1

**Comment by nihui** [comment]
修好啦

**Comment by jiaomingjun** [comment]
嗯嗯， 谢谢~
