### ISSUE TITLE
自定义模型转换后，中间推理结果不对，图像还有错位

### ISSUE THREAD

**Issue by Albert666** [Tencent/ncnn#3232]
## detail | 详细描述 | 詳細な説明
自己用pytorch定义了一个端对端网络，转成onnx后推理正常，然后转成ncnn，结果总是不对，查看中间层，核onnx做对比，发现第一层卷积后就有问题，图像错位了？这是什么原因，有哪位大神知道。
![image](https://user-images.githubusercontent.com/13348817/133871248-7a7dd826-d146-4fd2-b999-97bbb70c55b3.png)

**Comment by Albert666** [comment]
原图大概是这种样子：
![image](https://user-images.githubusercontent.com/13348817/133872012-88478099-c94a-4e29-b8a0-97b5e56ee302.png)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
