### ISSUE TITLE
Question: NCNN inference time on Android between Release and Debug Android Apk build.

### ISSUE THREAD

**Issue by make-j64** [Tencent/ncnn#3241]
## detail | 详细描述 | 詳細な説明
I made a comparison between release 
build with a signature key and debug build apk, the inference time when release 
build is always about 30% slower than debug build. What is the reason for this difference?
Thanks.

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/ac3d32aa0dcbd5cbe0ce7ce768a8b7fe2d7b69a1
