### ISSUE TITLE
模型量化int8后，时间增加。

### ISSUE THREAD

**Issue by qinggangwu** [Tencent/ncnn#3244]
## expectation | 诉求 | 期待する
1. 没有量化之前模型推理速度240ms
2. int8量化后速度500ms

## model | 模型 | モデル
1.mobilenet.param.txt    没有量化的模型
2. mobilenet-int8.param.txt  量化后模型

## detail | 详细描述 | 詳細な説
[mobilenet.param.txt](https://github.com/Tencent/ncnn/files/7208611/mobilenet.param.txt)
[mobilenet-int8.param.txt](https://github.com/Tencent/ncnn/files/7208613/mobilenet-int8.param.txt)
明

**Comment by tpoisonooo** [comment]
## benchmark

测试环境： 鲲鹏 armv8

int8 模型有个 layer 比较慢

Convolution              Conv_291                          32.21ms    |     [200, 150,  11 *8] -> [200, 150,  32 *1]         kernel: 3 x 3     stride: 1 x 1
Convolution              Conv_314                          62.25ms    |     [400, 300,   6 *8] -> [400, 300,  24 *1]         kernel: 3 x 3     stride: 1 x 1
Convolution              Conv_337                         317.86ms    |     [800, 600,  27 *1] -> [800, 600,   2 *8]         kernel: 3 x 3     stride: 1 x 1


对比原始版本
Convolution              Conv_291                          12.63ms    |     [200, 150,  11 *8] -> [200, 150,   4 *8]         kernel: 3 x 3     stride: 1 x 1
...
Convolution              Conv_314                          31.56ms    |     [400, 300,   6 *8] -> [400, 300,   3 *8]         kernel: 3 x 3     stride: 1 x 1
...
Convolution              Conv_337                          94.01ms    |     [800, 600,  27 *1] -> [800, 600,   2 *8]         kernel: 3 x 3     stride: 1 x 1



可以看到 int8 版本对 wxh 比较小的情况不友好。

## 短期改法
网络结构调一下，把小的 hw conv 改掉，尾巴加 fc ?

## 长期改法
找人优化这种 kernel

## 建议
学会 benchmark 基本用法。

**Comment by tpoisonooo** [comment]
cc @nihui

**Comment by qinggangwu** [comment]
thanks

**Comment by nihui** [comment]
推荐更新ncnn版本，对int8有更好的优化～～
