### ISSUE TITLE
NCNN自带仿射变换使用问题

### ISSUE THREAD

**Issue by wzyforgit** [Tencent/ncnn#3253]
## detail | 详细描述 | 詳細な説明

代码如下，我目前是在做Qt和ncnn的联动，目前可以确认代码中的 src 变量能通过最下方的代码正确从 ncnn::Mat 还原为 QImage 并显示出来，但是中间这段从wiki那边搬运的人脸5点对齐代码却始终无法生效，我现在可以确认detectObj.keyPoints中的值就是对应的原图所在坐标，但转出来的图，也就是result变量，始终是一团黑，还有一道蓝色的横线和一坨红色的点（这个可能和我的输出图有关吧）

请各位大佬麻烦看一下是哪里姿势没对 =。=

    QImage stdImg = srcImg.convertToFormat(QImage::Format_RGB888);

    ncnn::Mat src = ncnn::Mat::from_pixels(stdImg.bits(), ncnn::Mat::PIXEL_RGB, stdImg.width(), stdImg.height());

    // 计算变换矩阵 并且求逆变换
    int type = 0;       // 0->区域外填充为v[0],v[1],v[2], -233->区域外不处理
    float tm[6];
    float tm_inv[6];
    // 人脸区域在原图上的坐标
    float point_src[10] = {
        static_cast<float>(detectObj.keyPoints[0]), static_cast<float>(detectObj.keyPoints[1]),
        static_cast<float>(detectObj.keyPoints[2]), static_cast<float>(detectObj.keyPoints[3]),
        static_cast<float>(detectObj.keyPoints[4]), static_cast<float>(detectObj.keyPoints[5]),
        static_cast<float>(detectObj.keyPoints[6]), static_cast<float>(detectObj.keyPoints[7]),
        static_cast<float>(detectObj.keyPoints[8]), static_cast<float>(detectObj.keyPoints[9]),
    };

    float point_dst[10] = { // +8 是因为我们处理112*112的图
        30.2946f + 8.0f, 51.6963f,
        65.5318f + 8.0f, 51.5014f,
        48.0252f + 8.0f, 71.7366f,
        33.5493f + 8.0f, 92.3655f,
        62.7299f + 8.0f, 92.2041f,
    };

    ncnn::get_affine_transform(point_src, point_dst, 5, tm);
    ncnn::invert_affine_transform(tm, tm_inv);

    ncnn::Mat dst(112, 112, 3);
    ncnn::warpaffine_bilinear_c3(static_cast<const unsigned char *>(src.data), src.w, src.h,
                                 static_cast<unsigned char *>(dst.data), dst.w, dst.h,
                                 tm_inv, type);

    QImage result(dst.w, dst.h, QImage::Format_RGB888);
    dst.to_pixels(result.bits(), ncnn::Mat::PIXEL_RGB);

**Comment by wzyforgit** [comment]
然后我那个srcImg是一张1920*1080的原始大图，不是人脸检测系统检测出来的小图，detectObj.keyPoints也是目标人脸上5点在这张原始大图中的坐标

**Comment by wzyforgit** [comment]
好吧，冷静了两天，在 https://github.com/Libero-zz/PiVA/blob/709758848563dee7a555b46cc1fd134a8b2910a1/src/cropface.cpp 找到了一份更好的例子，已测试通过，结贴

目前我的代码修改为下面这样：

    //人脸区域在原图上的坐标
    float point_src[10] = {
        static_cast<float>(detectObj.keyPoints[0]), static_cast<float>(detectObj.keyPoints[1]),
        static_cast<float>(detectObj.keyPoints[2]), static_cast<float>(detectObj.keyPoints[3]),
        static_cast<float>(detectObj.keyPoints[4]), static_cast<float>(detectObj.keyPoints[5]),
        static_cast<float>(detectObj.keyPoints[6]), static_cast<float>(detectObj.keyPoints[7]),
        static_cast<float>(detectObj.keyPoints[8]), static_cast<float>(detectObj.keyPoints[9]),
    };

    float point_dst[10] = { // +8 是因为我们处理112*112的图，不加则是 112*96
        30.2946f + 8.0f, 51.6963f,
        65.5318f + 8.0f, 51.5014f,
        48.0252f + 8.0f, 71.7366f,
        33.5493f + 8.0f, 92.3655f,
        62.7299f + 8.0f, 92.2041f,
    };

    //计算变换矩阵
    float tm_inv[6];
    ncnn::get_affine_transform(point_dst, point_src, 5, tm_inv);

    //规范图片格式
    auto stdImg = srcImg.convertToFormat(QImage::Format_RGB888);

    //计算结果存放位置
    QImage resultImg(112, 112, QImage::Format_RGB888);

    //执行变换，结果会直接刷入resultImg
    ncnn::warpaffine_bilinear_c3(stdImg.bits(), stdImg.width(), stdImg.height(),
                                 resultImg.bits(), resultImg.width(), resultImg.height(),
                                 tm_inv);

**Comment by 191086** [comment]
我也出现了类似的问题，待转换的图片是cv::Mat，也不知道应该怎么做了

**Comment by wzyforgit** [comment]
> 我也出现了类似的问题，待转换的图片是cv::Mat，也不知道应该怎么做了

你记住ncnn::Mat如果不指定内存分配器就不会主动分配内存，然后没了

**Comment by Ryuk17** [comment]
请教下这里+8是干什么呢？
