### ISSUE TITLE
Some phones do not support Neon - can ncnn work on them?

### ISSUE THREAD

**Issue by fzyzcjy** [Tencent/ncnn#3256]
## detail | 详细描述 | 詳細な説明

Hi thanks for this lib! As we know, some phones do not support neon. https://developer.android.com/ndk/guides/cpu-arm-neon says:

> Not all ARMv7-based Android devices support Neon

And neon optimizations are mentioned in the readme. So I wonder whether ncnn can work on those devices?

I do see the use of `__ARM_NEON` macro. But imho it is at compile time, not at runtime.

**Comment by nihui** [comment]
neon is required for running android 6.0, thus all devices you could have today must support arm neon.
ncnn can work on these ancient devices without neon. However, it is not a good idea to deploy any AI applications on them, that will be too slow.

**Comment by fzyzcjy** [comment]
@nihui 

> neon is required for running android 6.0

I do not know that before. Thank you very much!
