### ISSUE TITLE
on ARM64 arm/convolution_3x3.h:1281:14: error: more than 30 operands in ‘asm’ 

### ISSUE THREAD

**Issue by XunChangqing** [Tencent/ncnn#326]
ncnn/src/layer/arm/convolution_3x3.h:1281:14: error: more than 30 operands in ‘asm’
aarch64-buildroot-linux-uclibc-c++.br_real (Buildroot 2018.02) 6.4.0

**Comment by imkow** [comment]
update to latest code #309

**Comment by XunChangqing** [comment]
I tried again, and it still can not work.
My repo version d7e31987fadc54aa4244f7055d54402c99daabdf.
convolution_3x3.h:1281 lines:
  1249                 : "=r"(ktm2),   // %0
  1250                   "=r"(k00),    // %1
  1251                   "=r"(k01),    // %2
  1252                   "=r"(k02),    // %3
  1253                   "=r"(k03),    // %4
  1254                   "=r"(k10),    // %5
  1255                   "=r"(k11),    // %6
  1256                   "=r"(k12),    // %7
  1257                   "=r"(k13),    // %8
  1258                   "=r"(k20),    // %9
  1259                   "=r"(k21),    // %10
  1260                   "=r"(k22),    // %11
  1261                   "=r"(k23),    // %12
  1262                   "=r"(k30),    // %13
  1263                   "=r"(k31),    // %14
  1264                   "=r"(k32),    // %15
  1265                   "=r"(k33)     // %16
  1266                 : "0"(ktm2),
  1267                   "1"(k00),
  1268                   "2"(k01),
  1269                   "3"(k02),
  1270                   "4"(k03),
  1271                   "5"(k10),
  1272                   "6"(k11),
  1273                   "7"(k12),
  1274                   "8"(k13),
  1275                   "9"(k20),
  1276                   "10"(k21),
  1277                   "11"(k22),
  1278                   "12"(k23),
  1279                   "13"(k30),
  1280                   "14"(k31),
  1281                   "15"(k32),
  1282                   "16"(k33)
  1283                 : "cc", "memory", "v0", "v1", "v2", "v3"

Maybe my tool chain is different?
I build my tool chain by buildroot.

**Comment by XunChangqing** [comment]
I have tried gcc 5.5 and 4.9, still cannot work.
aarch64-buildroot-linux-uclibc-g++.br_real (Buildroot 2018.02) 4.9.4

**Comment by XunChangqing** [comment]
Finnally, I used a 32bit compiler, it worked...

**Comment by nihui** [comment]
You just need to pull the latest code from git master branch, and you will catch the wonderful ;)

**Comment by nihui** [comment]
Since the latest code resolved this issue, close it.

**Comment by xiaofengren** [comment]
I'm still met this issue on my armv8 platform, I'm using gcc-7.3. I checked gcc user manual and it mentioned that "The total number of input + output + goto operands is limited to 30.". 
https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html

In file included from /root/ncnn/src/layer/arm/convolution_arm.cpp:27:0:
/root/ncnn/src/layer/arm/convolution_1x1_int8.h: In function '_ZN4ncnnL19conv1x1s1_int8_neonERKNS_3MatERS0_S2_RKNS_6OptionE._omp_fn.8':
/root/ncnn/src/layer/arm/convolution_1x1_int8.h:1967:14: error: more than 30 operands in 'asm'
             );
              ^
/root/ncnn/src/layer/arm/convolution_1x1_int8.h:1414:14: error: more than 30 operands in 'asm'
             );
              ^
/root/ncnn/src/layer/arm/convolution_1x1_int8.h:850:14: error: more than 30 operands in 'asm'
             );
              ^
src/CMakeFiles/ncnn.dir/build.make:542: recipe for target 'src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o' failed
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/ncnn.dir/all' failed
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
