### ISSUE TITLE
Does somebody user ncnn in flutter ? 

### ISSUE THREAD

**Issue by RTae** [Tencent/ncnn#3270]
## detail | 详细描述 | 詳細な説明
now I develop app in flutter, but I only see android example. So i warp ncnn android  in flutter, but it's does work
Can someone help me or any guideline ?

**Comment by felithium** [comment]
@RTae

I am a little late but you could look into this flutter plugin: https://pub.dev/packages/ncnn_yolox_flutter

It was just released a day ago and I already found a bug in the demo app but it still looks promising.

**Comment by RTae** [comment]
@leeflix Wow, thank you a lot for sharing information
