### ISSUE TITLE
find_blob_index_by_name failed!!!!!!

### ISSUE THREAD

**Issue by Ijustakid** [Tencent/ncnn#3277]
## detail | 详细描述 | 詳細な説明

gaze-pfld onnx 转 ncnn, 得到param和bin, 通过netron看到input和output name 为 'images'和'output' / '468'
![Screenshot from 2021-10-11 17-03-04](https://user-images.githubusercontent.com/25544580/136763534-3f7c4919-5970-4a72-8057-2c61c0b84fc8.png)
但是
    ex.input("images", in);
    ncnn::Mat landmark, gaze;
    ex.extract("output", landmark);
    ex.extract("468", gaze);

得到
W/ncnn: find_blob_index_by_name 469 failed
W/ncnn: Try
W/ncnn: find_blob_index_by_name output failed
W/ncnn: Try
W/ncnn: find_blob_index_by_name 468 failed
W/ncnn: Try

bin/param:
[gaze-pfld.zip](https://github.com/Tencent/ncnn/files/7321099/gaze-pfld.zip)

我也用ncnn2mem转换为id.h, 得到:
namespace gaze_pfld_param_id {
const int LAYER_images = 0;
const int BLOB_images = 0;
...
const int BLOB_output = 113;
...
const int BLOB_468 = 125;
} // namespace gaze_pfld_param_id

尝试使用:
    ex.input("BLOB_images", in);
    ncnn::Mat landmark, gaze;
    ex.extract("BLOB_output", landmark);
    ex.extract("BLOB_468", gaze);

得到同样的结果:
W/ncnn: find_blob_index_by_name BLOB_images failed
W/ncnn: Try
W/ncnn: find_blob_index_by_name BLOB_output failed
W/ncnn: Try
W/ncnn: find_blob_index_by_name BLOB_468 failed
W/ncnn: Try

@nihui 大神帮忙看下这个问题, 一直都找不到input和output node

**Comment by zeng215217** [comment]
find_blob_index_by_name images failed
Try
find_blob_index_by_name output failed
Try
，所以这个·怎么解决啊

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by zengjie617789** [comment]
你看看你读取model和params的函数用的是什么，其实它参数可能根本没有读取成功，如果使用的load_param_bin只能使用index来获取结果
