### ISSUE TITLE
安卓ncnn mobilefacenet ex.extract，null pointer dereference

### ISSUE THREAD

**Issue by Zhaohuii-Wang** [Tencent/ncnn#3282]
## detail | 详细描述 | 詳細な説明
一个玩ncnn的小白遇到的问题，希望能够得到大佬们的帮助！
在学习ncnn的时候，想在nihui大佬的scrfd实现上人脸识别的后续功能，对齐等功能实现的应该没有问题，但是到了过mobilefacenet的时候在ex.extract处程序直接崩溃，查看log显示
![image](https://user-images.githubusercontent.com/73983855/137235209-af64a652-1276-42b9-b35c-966e83897c52.png)
但似乎找不到这个空指针是哪里来的┭┮﹏┭┮

也查阅了大佬们之前的issue，检查了图像的输入是3通道112x112大小没有错
c++代码：
![image](https://user-images.githubusercontent.com/73983855/137235739-3200f4b0-8b23-4eca-8e13-faeda6271057.png)
LOGD输出：
![image](https://user-images.githubusercontent.com/73983855/137235117-244b3bd1-d46b-4120-aa1b-782a7f79bdef.png)
param文件部分截图（网上找的现成的mobilefacenet，看了下应该是insightface放出来的那个mxnet版本转来的，自己转来的ncnn模型也是同样的问题）：
![image](https://user-images.githubusercontent.com/73983855/137235609-161b0012-fbce-4957-8ddc-fcaf742c3ff5.png)
![image](https://user-images.githubusercontent.com/73983855/137235644-0209ffad-ffc2-48d9-af37-7f9a3b5948c6.png)
先谢谢各位大佬了！希望能够得到解答！！感激不尽！！(～￣▽￣)～

**Comment by 785354408** [comment]
补充：过这个网络的时候，前面归一化的地方可以输出，到第一层卷积的时候就会出错
