### ISSUE TITLE
onnx2ncnn segmentation fault(core dumped)

### ISSUE THREAD

**Issue by chengqianma** [Tencent/ncnn#3288]
## error log | 日志或报错信息 | ログ
Segmentation fault (core dumped)
## context | 编译/运行环境 | バックグラウンド
Linux
## how to reproduce | 复现步骤 | 再現方法
1. ./onnx2ncnn ./test_sim.onnx ./test_sim.param ./test_sim.bin
2. model:[test_sim.onnx.zip](https://github.com/Tencent/ncnn/files/7352668/test_sim.onnx.zip)

**Comment by LamnouarMohamed** [comment]
Hi

I have same problem, do you have solve this issue or not yet

Thank you

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5622

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/f3cd4c2e917ad264f73c600af9e5c6801af08608
