### ISSUE TITLE
mac 上编译armeabi版本ncnn出错

### ISSUE THREAD

**Issue by bldu** [Tencent/ncnn#3295]
请问ncnn能够编译成armeabi的版本吗，项目需要。使用ndk版本是16

**编译命令:**
```
#! /bin/bash
ANDROID_NDK=~/Library/Android/sdk/ndk/16.1.4479499

rm -rf build-android-armeabi
mkdir -p build-android-armeabi
cd build-android-armeabi

cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI="armeabi" -DANDROID_ARM_NEON=ON \
    -DANDROID_PLATFORM=android-14 ../../ncnn


make -j4
make install
```

**报错:**
```
...
/var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-01882c.s: Assembler messages:
/var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-01882c.s:231: Error: selected processor does not support `vmrs r4,FPSCR' in Thumb mode
/var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-01882c.s:232: Error: cannot honor width suffix -- `bic r10,r4,#0x00c00000'
/var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-01882c.s:233: Error: selected processor does not support `vmsr FPSCR,r10' in Thumb mode
/var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-01882c.s:729: Error: selected processor does not support `vmsr FPSCR,r4' in Thumb mode
clang++: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/arm/quantize_arm.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
...
```

**Comment by bldu** [comment]
@nihui 大佬求助

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/4566ad529aa96886018d685482f19cf0b01054d6

**Comment by finch-yihe** [comment]
我下载最新的代码，按照上述方式，还是报错呀
![CleanShot 2023-11-07 at 15 03 01](https://github.com/Tencent/ncnn/assets/23740883/4209faea-0558-4141-81f6-1fdc154c13a7)

**Comment by finch-yihe** [comment]
> > cmake 添加参数 `-DANDROID_ARM_MODE=ON`
> 
> 感谢大佬回复。加了这个flag之后马上报错了，后面我查了一下，在 这里 [https://stackoverflow.com/a/41395408](url) 的回复里看到说要用 `-DANDROID_ARM_MODE=arm`。 然后我用了这个，转到了 arm mode， 但是还是报错
> 
> ```
> /var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-4ca1f5.s: Assembler messages:
> /var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-4ca1f5.s:221: Error: selected processor does not support `vmrs r4,FPSCR' in ARM mode
> /var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-4ca1f5.s:223: Error: selected processor does not support `vmsr FPSCR,r10' in ARM mode
> /var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-4ca1f5.s:717: Error: selected processor does not support `vmsr FPSCR,r4' in ARM mode
> clang++: error: assembler command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [src/CMakeFiles/ncnn.dir/layer/arm/quantize_arm.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> 2 warnings generated.
> make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
> make: *** [all] Error 2
> [  0%] Built target ncnn-generate-spirv
> Consolidate compiler generated dependencies of target ncnn
> [  0%] Building CXX object src/CMakeFiles/ncnn.dir/layer/arm/quantize_arm.cpp.o
> /Users/dbl/NewEra/Pkgs/ncnn_build/ncnn/src/layer/arm/quantize_arm.cpp:64:9: warning: unused variable 'elempack' [-Wunused-variable]
>     int elempack = bottom_blob.elempack;
>         ^
> /Users/dbl/NewEra/Pkgs/ncnn_build/ncnn/src/layer/arm/quantize_arm.cpp:1565:9: warning: unused variable 'elempack' [-Wunused-variable]
>     int elempack = bottom_blob.elempack;
>         ^
> 2 warnings generated.
> /var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-b0f7b3.s: Assembler messages:
> /var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-b0f7b3.s:221: Error: selected processor does not support `vmrs r4,FPSCR' in ARM mode
> /var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-b0f7b3.s:223: Error: selected processor does not support `vmsr FPSCR,r10' in ARM mode
> /var/folders/pm/q382cz2n3_dfq9c8bv2w2g8m0000gn/T/quantize_arm-b0f7b3.s:717: Error: selected processor does not support `vmsr FPSCR,r4' in ARM mode
> clang++: error: assembler command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [src/CMakeFiles/ncnn.dir/layer/arm/quantize_arm.cpp.o] Error 1
> make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
> make: *** [all] Error 2
> ```

哥们 你这个问题解决了吗 我也遇到了@-@

**Comment by finch-yihe** [comment]
@nihui 大佬 能帮忙看一下吗 我是用最新的代码 还是出现这个问题呢
