### ISSUE TITLE
 CMAKE_SYSTEM_NAME is 'Android' but 'NVIDIA Nsight Tegra Visual Studio  Edition' is not installed.

### ISSUE THREAD

**Issue by hexujun** [Tencent/ncnn#33]
在win8.1上编译 android 版本，出现此错误，我都安装了NVIDIA Nsight Tegra Visual Studio  Edition ，依然出错，如何破

**Comment by lijiayan2015** [comment]
@hexujun 我是win7的,也出现这个问题了,你的弄好了吗?怎么弄的?可否留个联系方式,感激感激........

**Comment by nihui** [comment]
参考 http://blog.csdn.net/minstyrain/article/details/78278893
