### ISSUE TITLE
模型int8量化后，armeabi-v7a和arm64-v8a结果不一致

### ISSUE THREAD

**Issue by ljdang** [Tencent/ncnn#3303]
## expectation | 诉求 | 期待する
在armeabi-v7a和arm64-v8a上结果一致

## model | 模型 | モデル
[model.zip](https://github.com/Tencent/ncnn/files/7414862/model.zip)

## detail | 详细描述 | 詳細な説明
ncnn版本：20210720
模型为mobilenetv2，之前激活函数是relu6，量化后结果正常，但是int8在armeabi-v7a上速度慢了很多，猜测可能是Clip导致的；
将激活函数替换成relu后，int8模型在arm64-v8a上结果正常，但是在armeabi-v7a上结果错误。

**Comment by nihui** [comment]
尝试用最新的 ncnn 和量化工具实验，修复了 x86 armv7 round 的差异
