### ISSUE TITLE
inf values in .table file after running ncnn2table

### ISSUE THREAD

**Issue by Daveorr** [Tencent/ncnn#3321]
Hello all,

I'm having an issue when generating my `.table` file with `ncnn2table` that will cause my int8 quantized model to not work.

I run the script with the following parameters:

`./ncnn2table my_model.param my model.bin imagelist_1000.txt  out.table mean=[104,117,123] norm=[1,1,1] shape=[112,112,3] pixel=RGB thread=8 method=aciq`

while most of  the values in the `.table` seems to be reasonable in the last 4 layers I got weird values as:

`stage4_unit2_conv1 3526864704793905861754880.000000 `
`stage4_unit2_conv2 inf` 
`stage4_unit3_conv1 2886406144460884753252352.000000 `
`stage4_unit3_conv2 inf`

I already successfully quantized my model for other frameworks like tflite without having any performance regression but I cannot solve this problem in ncnn.

Anyone can help?? T_T

PS: I already tried the solutions reported here by @nihui and @BUG1989  https://github.com/Tencent/ncnn/issues/1412
But so far I could not succeed

**Comment by jaehoon00** [comment]
@Daveorr 
Hi, did you solve the issue?
Currently I'm having it, too.
