### ISSUE TITLE
支持语音识别，TTS，NLP的模型转换应用吗

### ISSUE THREAD

**Issue by guijuzhejiang** [Tencent/ncnn#3324]
如题，想部署一个语音聊天的Android应用，请问NCNN对ASR，NLP，TTS模型的支持如何？有没有大佬实现过？

**Comment by QuinnCoder** [comment]
大佬有找到对应的解决方案吗，有一些思路提供吗

**Comment by jie2311260561** [comment]
同蹲大佬的方案

**Comment by magicse** [comment]
some example
https://github.com/Tencent/ncnn/discussions/4810

**Comment by kqdlx3** [comment]
> 大佬有找到对应的解决方案吗，有一些思路提供吗

不，这里并没有，这里不支持tts和nlp，只有语音识别

**Comment by csukuangfj** [comment]
是的，我们[提供的](https://github.com/k2-fsa/sherpa-ncnn)就是实时语音识别

目前为止，你找不到第二个支持 ncnn 的开源实时语音识别。你应该没有其他选择

**Comment by guijuzhejiang** [comment]
忘了这还有个issue，我们后来做了个网页版的实时英语口语对话系统，没有用NCNN
