### ISSUE TITLE
请问ncnn for raspberry pi 3b , 怎么编译？

### ISSUE THREAD

**Issue by Pillar1989** [Tencent/ncnn#333]
如题

**Comment by Pillar1989** [comment]
#28

**Comment by Pillar1989** [comment]
使用 89ef9d779dcc3fa0eee195ecc76552806b5be0d6 测试了一下。
```
respeaker@v2:~/ncnn/build/benchmark$  ./benchncnn 8 4 0
loop_count = 8
num_threads = 4
powersave = 0
      squeezenet  min =  300.97  max =  302.80  avg =  301.89
       mobilenet  min =  489.53  max =  627.75  avg =  515.26
    mobilenet_v2  min =  430.57  max =  474.48  avg =  438.63
      shufflenet  min =  172.46  max =  184.58  avg =  174.88
       googlenet  min =  900.90  max =  917.64  avg =  909.99
        resnet18  min = 1033.58  max = 1055.32  avg = 1045.79
         alexnet  min =  665.61  max =  732.15  avg =  696.10
           vgg16  min = 7845.35  max = 8337.21  avg = 8047.88
  squeezenet-ssd  min =  468.08  max =  476.50  avg =  470.12
   mobilenet-ssd  min =  505.71  max =  521.30  avg =  511.93

```

**Comment by lincolnhard** [comment]
同樣都是ARM A53 1.2 GHz quad-core 為什麼Snapdragon 410上速度可以這麼快

**Comment by zacario-li** [comment]
为什么，我树莓派上的性能，看起来，花费的时间是你这个结果的4倍？天哪，我这个哪里出问题了？

**Comment by JoeyZhu** [comment]
min max avg单位是毫秒吗？

**Comment by zhaoforever** [comment]
> 使用 [89ef9d7](https://github.com/Tencent/ncnn/commit/89ef9d779dcc3fa0eee195ecc76552806b5be0d6) 测试了一下。
> 
> ```
> respeaker@v2:~/ncnn/build/benchmark$  ./benchncnn 8 4 0
> loop_count = 8
> num_threads = 4
> powersave = 0
>       squeezenet  min =  300.97  max =  302.80  avg =  301.89
>        mobilenet  min =  489.53  max =  627.75  avg =  515.26
>     mobilenet_v2  min =  430.57  max =  474.48  avg =  438.63
>       shufflenet  min =  172.46  max =  184.58  avg =  174.88
>        googlenet  min =  900.90  max =  917.64  avg =  909.99
>         resnet18  min = 1033.58  max = 1055.32  avg = 1045.79
>          alexnet  min =  665.61  max =  732.15  avg =  696.10
>            vgg16  min = 7845.35  max = 8337.21  avg = 8047.88
>   squeezenet-ssd  min =  468.08  max =  476.50  avg =  470.12
>    mobilenet-ssd  min =  505.71  max =  521.30  avg =  511.93
> ```

试了一下3B+

root@raspberrypi:/home/pi/ncnn/build/benchmark# ./benchncnn 8 4 0
loop_count = 8
num_threads = 4
powersave = 0
      squeezenet  min =  103.89  max =  104.15  avg =  104.02
       mobilenet  min =  189.70  max =  191.48  avg =  190.49
    mobilenet_v2  min =  200.17  max =  201.02  avg =  200.49
      shufflenet  min =   72.47  max =   72.65  avg =   72.52
       googlenet  min =  337.07  max =  338.15  avg =  337.52
        resnet18  min =  510.73  max =  518.89  avg =  514.81
         alexnet  min =  422.94  max =  423.15  avg =  423.03
           vgg16  min = 2459.17  max = 2487.06  avg = 2474.63
  squeezenet-ssd  min =  341.95  max =  353.17  avg =  349.39
   mobilenet-ssd  min =  335.72  max =  349.97  avg =  346.59
  mobilenet-yolo  min =  866.91  max =  870.52  avg =  868.21

**Comment by nihui** [comment]
wiki how to build updated for Raspberry Pi 3 compilation
