### ISSUE TITLE
经pnnx转换的模型,再经ncnnoptimize ,模型加载报错

### ISSUE THREAD

**Issue by JiaoPaner** [Tencent/ncnn#3335]
## error log | 日志或报错信息 | ログ
`layer load_model 1 embed_0 failed`
## model | 模型 | モデル
pnnx模型:
链接: https://pan.baidu.com/s/1IiamJ_Z1Ap8FwxmdVVLmWw 提取码: 4i21

## how to reproduce | 复现步骤 | 再現方法
1. 使用pnnx成功转换一个带embedding层的lstm模型,推理结果正确
2. 利用ncnnoptimize转模型为fp16
3. 加载模型报错如下:
`layer load_model 1 embed_0 failed`

如何解决ncnnoptimize优化模型时的embed问题?

**Comment by nihui** [comment]
已修复，更新 ncnn 源码编译新的 ncnnoptimize 工具，谢谢反馈
