### ISSUE TITLE
onnx2ncnn problem

### ISSUE THREAD

**Issue by lavender-ling** [Tencent/ncnn#3336]
## error log | 日志或报错信息 | ログ

ArgMax not supported yet!
  # axis=1
  # keepdims=0
## model | 模型 | モデル
1. original model
[model.zip](https://github.com/Tencent/ncnn/files/7518769/model.zip)

## how to reproduce | 复现步骤 | 再現方法
1.python -m onnxsim model_v2.onnx model_v2_sim.onnx
2./path/to/ncnn/build/tools/onnx/onnx2ncnn model_v2_sim.onnx model_v2_sim.param model_v2_sim.bin

**Comment by Digital2Slave** [comment]
> ## error log | 日志或报错信息 | ログ
> ArgMax not supported yet!
> 
> # axis=1
> # keepdims=0
> ## model | 模型 | モデル
> 1. original model
>    [model.zip](https://github.com/Tencent/ncnn/files/7518769/model.zip)
> 
> ## how to reproduce | 复现步骤 | 再現方法
> 1.python -m onnxsim model_v2.onnx model_v2_sim.onnx 2./path/to/ncnn/build/tools/onnx/onnx2ncnn model_v2_sim.onnx model_v2_sim.param model_v2_sim.bin

Same issue. How to fix it? @lavender-ling 
Thanks a lot in advance.

**Comment by REFRAING** [comment]
anybody handle it ?

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
