### ISSUE TITLE
faq里面的链接失效

### ISSUE THREAD

**Issue by FreedoomG** [Tencent/ncnn#3346]
大佬好！
[如何去掉后处理，再导出 onnx？](https://github.com/Tencent/ncnn/blob/a539f16c13295ceb638036893fbe2960c99725e3/docs/faq.md)
这里的“转模型问题”里面“如何去掉后处理，再导出 onnx？”的链接过去木有内容哦

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/pull/3347
Thanks for your report !

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
