### ISSUE TITLE
android 上面出现crash的有出现过的没有？

### ISSUE THREAD

**Issue by fly-jelly** [Tencent/ncnn#335]
--------- beginning of crash
04-07 22:52:47.491 3261-3401/com.deepcam.test A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xfffffffffffff8 in tid 3401 (pool-1-thread-1)
04-07 22:52:47.491 3261-3399/com.deepcam.test A/libc: Fatal signal 11 (SIGSEGV) in tid 3399 (pool-1-thread-1)
04-07 22:52:47.491 3261-3399/com.deepcam.test I/libc: Another thread contacted debuggerd first; not contacting debuggerd.
04-07 22:52:47.492 3261-3398/com.deepcam.test A/libc: Fatal signal 11 (SIGSEGV) in tid 3398 (pool-1-thread-1)

**Comment by SankQin** [comment]
同样的问题 ，有人来解决么

**Comment by nihui** [comment]
信息太少了。。
