### ISSUE TITLE
int8比float32更慢，有时还慢得多？（是否意味着应当把int8模型运行前转为float32）

### ISSUE THREAD

**Issue by fzyzcjy** [Tencent/ncnn#3350]
## error log | 日志或报错信息 | ログ

观察官方benchmark： https://github.com/Tencent/ncnn/blob/master/benchmark/README.md 

发现经常int8比原版float32运行更慢，有时还慢得多。例如：

```
           mobilenet  min =   85.06  max =   86.67  avg =   86.01
      mobilenet_int8  min =  163.69  max =  185.67  avg =  168.48
```

```
           mobilenet  min =  143.11  max =  146.50  avg =  145.38
      mobilenet_int8  min =  202.25  max =  203.32  avg =  203.02
```

```
           mobilenet  min =   11.61  max =   12.14  avg =   11.87
      mobilenet_int8  min =   23.73  max =   24.24  avg =   23.96
```

```
           mobilenet  min =   34.09  max =   36.88  avg =   35.93
      mobilenet_int8  min =   52.62  max =   61.70  avg =   55.38
```

那么，是否应当把int8强制转换为float32模型，然后再进行运算？谢谢

## context | 编译/运行环境 | バックグラウンド

N/A

## how to reproduce | 复现步骤 | 再現方法

N/A

## more | 其他 | その他

N/A

**Comment by nihui** [comment]
benchmark 的 readme 数据有些比较老，没有用最新 int8 优化的ncnn跑
ncnn int8 推理目前只在 arm cpu 做了深入的优化
建议用自己的设备跑跑看，也欢迎提交相关 benchmark 数据的更新

**Comment by fzyzcjy** [comment]
@nihui 感谢
