### ISSUE TITLE
Simple op caused inconsistent results (FP32) between ncnn and pytorch/onnx

### ISSUE THREAD

**Issue by andgitchang** [Tencent/ncnn#3351]
## error log | 日志或报错信息 | ログ
N/A

## model | 模型 | モデル
1. [nanodet original model](https://github.com/RangiLyu/nanodet/blob/main/demo_ncnn/README.md)

## how to reproduce | 复现步骤 | 再現方法
1. Input a pre-processed image to the very first Convolution layer of ncnn/pytorch.
2. Get numerically inconsistent output between ncnn/pytorch, e.g. at Mat[N,C,H,W] hex: 0x3f2ca2c**c** (ncnn) & 0x3f2ca2c**d** (pytorch).
3. Thoroughly checked the pre-processed image, weight/bias between the platform are the same, up to single-precision float32.

Since I'm new to debugging numerical consistency across ML platforms, I not sure is it a bug (implementation of padding), or just an accumulation rounding error for two platforms' floating-point arithmetic?

**Comment by nihui** [comment]
I think this is the float arithmetic rounding difference.
You may find that the results on different platforms and hardware will be slightly different with ncnn.

eg:
x86-AVX ```a += b * c``` results two rounding
x86-FMA ```a += b * c``` results one rounding
armv7-neon is not fully complaint with IEEE-754 standard
```a * b * c``` may be different with ```a * (b * c)``` and we usually reorder arithmetic for better efficiency

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
