### ISSUE TITLE
"整体库体积小于 700K，并可轻松精简到小于 300K"，但实测最新版libncnn.so压缩后仍然有1.3MB？

### ISSUE THREAD

**Issue by fzyzcjy** [Tencent/ncnn#3353]
## error log | 日志或报错信息 | ログ

N/A

## context | 编译/运行环境 | バックグラウンド
N/A

## how to reproduce | 复现步骤 | 再現方法

去 https://github.com/Tencent/ncnn/releases/tag/20210720 下载 https://github.com/Tencent/ncnn/releases/download/20210720/ncnn-20210720-android-shared.zip 。以armeabi-v7a为例，libncnn.so 3.6MB、压缩后1.3MB，远大于readme所述700K。

## more | 其他 | その他
N/A

**Comment by zchrissirhcz** [comment]
“整体库体积小于 700K，并可轻松精简到小于 300K” 这句话的 git commit 记录是在3年前：
> dbf2052 
> 3 years ago   (March 20th, 2019 3:50pm) 

可以尝试切到历史版本，手动编译，预计大小比较接近。

P.S. 库大小通常来说一个bonus而不是必选项，可以删掉不需要的layer后再编译。

**Comment by fzyzcjy** [comment]
@zchrissirhcz 谢谢。本来以为readme一般是最新的
