### ISSUE TITLE
调用ncnnoptimize 或者自己加载param和bin的时候报Floating Point Exception(core dumped)

### ISSUE THREAD

**Issue by HongxiaoMa** [Tencent/ncnn#3375]

**Comment by nihui** [comment]
请提供下出错的 param 文件

**Comment by HongxiaoMa** [comment]
> 请提供下出错的 param 文件

7767517
63 63
Input            x                        0 1 x
Convolution      Conv_22                  1 1 x 311 0=1 5=1 6=3
ReLU             Relu_23                  1 1 311 220
Convolution      Conv_24                  1 1 220 314 0=3 5=1 6=3
ReLU             Relu_25                  1 1 314 223
Permute          Transpose_26             1 1 223 224 0=2
Reshape          Reshape_28               1 1 224 226 0=120 1=80 2=3
ConvolutionDepthWise Conv_29                  1 1 226 317 0=3 1=5 11=5 2=1 12=1 3=1 13=1 4=2 14=2 15=2 16=2 5=1 6=75 7=3
ReLU             Relu_30                  1 1 317 229
Convolution      Conv_31                  1 1 229 320 0=8 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=24
ReLU             Relu_32                  1 1 320 232
ConvolutionDepthWise Conv_33                  1 1 232 323 0=8 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=72 7=8
ReLU             Relu_34                  1 1 323 235
Convolution      Conv_35                  1 1 235 326 0=8 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=64
ReLU             Relu_36                  1 1 326 238
Pooling          MaxPool_37               1 1 238 239 0=0 1=2 11=2 2=2 12=2 3=0 13=0 14=0 15=0 5=1
ConvolutionDepthWise Conv_38                  1 1 239 329 0=8 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=72 7=8
ReLU             Relu_39                  1 1 329 242
Convolution      Conv_40                  1 1 242 332 0=16 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=128
ReLU             Relu_41                  1 1 332 245
ConvolutionDepthWise Conv_42                  1 1 245 335 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=144 7=16
ReLU             Relu_43                  1 1 335 248
Convolution      Conv_44                  1 1 248 338 0=16 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=256
ReLU             Relu_45                  1 1 338 251
Pooling          MaxPool_46               1 1 251 252 0=0 1=2 11=2 2=2 12=2 3=0 13=0 14=0 15=0 5=1
ConvolutionDepthWise Conv_47                  1 1 252 341 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=144 7=16
ReLU             Relu_48                  1 1 341 255
Convolution      Conv_49                  1 1 255 344 0=32 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=512
ReLU             Relu_50                  1 1 344 258
ConvolutionDepthWise Conv_51                  1 1 258 347 0=32 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=288 7=32
ReLU             Relu_52                  1 1 347 261
Convolution      Conv_53                  1 1 261 350 0=32 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1024
ReLU             Relu_54                  1 1 350 264
Pooling          MaxPool_55               1 1 264 265 0=0 1=3 11=2 2=3 12=2 3=0 13=0 14=0 15=0 5=1
ConvolutionDepthWise Conv_56                  1 1 265 353 0=32 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=288 7=32
ReLU             Relu_57                  1 1 353 268
Convolution      Conv_58                  1 1 268 356 0=64 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=2048
ReLU             Relu_59                  1 1 356 271
ConvolutionDepthWise Conv_60                  1 1 271 359 0=64 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=576 7=64
ReLU             Relu_61                  1 1 359 274
Convolution      Conv_62                  1 1 274 362 0=64 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=4096
ReLU             Relu_63                  1 1 362 277
Pooling          MaxPool_64               1 1 277 278 0=0 1=2 11=2 2=2 12=2 3=0 13=0 14=0 15=0 5=1
ConvolutionDepthWise Conv_65                  1 1 278 365 0=64 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=576 7=64
ReLU             Relu_66                  1 1 365 281
Convolution      Conv_67                  1 1 281 368 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=8192
ReLU             Relu_68                  1 1 368 284
ConvolutionDepthWise Conv_69                  1 1 284 371 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=1152 7=128
ReLU             Relu_70                  1 1 371 287
Convolution      Conv_71                  1 1 287 374 0=128 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=16384
ReLU             Relu_72                  1 1 374 290
Pooling          MaxPool_73               1 1 290 291 0=0 1=2 11=2 2=2 12=2 3=0 13=0 14=0 15=0 5=1
ConvolutionDepthWise Conv_74                  1 1 291 377 0=128 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=1152 7=128
ReLU             Relu_75                  1 1 377 294
Convolution      Conv_76                  1 1 294 380 0=256 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=32768
ReLU             Relu_77                  1 1 380 297
ConvolutionDepthWise Conv_78                  1 1 297 383 0=256 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=2304 7=256
ReLU             Relu_79                  1 1 383 300
Convolution      Conv_80                  1 1 300 386 0=256 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=65536
ReLU             Relu_81                  1 1 386 303
Reshape          Reshape_84               1 1 303 308 0=-1
InnerProduct     Gemm_85                  1 1 308 309 0=512 1=1 2=524288
InnerProduct     Gemm_86                  1 1 309 y 0=256 1=1 2=131072

**Comment by HongxiaoMa** [comment]
是在读取bin文件的时候报错的

**Comment by nihui** [comment]
看param文件，似乎是 tf 转过来的？
开头的 Permute Reshape 改 Noop 试试？

**Comment by HongxiaoMa** [comment]
把 Permute Reshape 删掉，并修改参数成如下，但是还是不行，和之前报一样的错误

 7767517
61 61
Input            x                        0 1 x
Convolution      Conv_22                  1 1 x 311 0=1 5=1 6=3
ReLU             Relu_23                  1 1 311 220
Convolution      Conv_24                  1 1 220 314 0=3 5=1 6=3
ReLU             Relu_25                  1 1 314 226
ConvolutionDepthWise Conv_29                  1 1 226 317 0=3 1=5 11=5 2=1 12=1 3=1 13=1 4=2 14=2 15=2 16=2 5=1 6=75 7=3
ReLU             Relu_30                  1 1 317 229
Convolution      Conv_31                  1 1 229 320 0=8 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=24
ReLU             Relu_32                  1 1 320 232
ConvolutionDepthWise Conv_33                  1 1 232 323 0=8 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=72 7=8
ReLU             Relu_34                  1 1 323 235

**Comment by HongxiaoMa** [comment]
我这个是从onnx转过来的模型

**Comment by nihui** [comment]
> 我这个是从onnx转过来的模型

是 tf -> onnx -> ncnn ？

**Comment by HongxiaoMa** [comment]
pytorch->onnx>ncnn

**Comment by nihui** [comment]
前两层卷积参数不正确
可以尝试用 pnnx 转换模型

**Comment by HongxiaoMa** [comment]
我这个是conv3d的卷积，ncnn支持吗，我单独生成只包含一个conv3d卷积的model，发现也会出现这个问题，然后改为conv2d的就可以

**Comment by HongxiaoMa** [comment]
也就是说我的输入是一个5维的输入

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by csukuangfj** [comment]
可以看看 #6322
