### ISSUE TITLE
Undefined symbol _ZTIN4ncnn5LayerE

### ISSUE THREAD

**Issue by noelex** [Tencent/ncnn#3383]
I'm trying to get my Android app running with ncnn. I have a C++ library with ncnn and OpenCV statically linked and this library is consumed by the frontend application. Everything compiles fine but when the app tries to load my library, it says
```
**Java.Lang.UnsatisfiedLinkError:** 'dlopen failed: cannot locate symbol "_ZTIN4ncnn5LayerE" referenced by "/data/app/com.my.app-nQB-tePGUwqGLV34jVKD1A==/lib/arm64/libmylibrary.so"...'
```

So I checked the symbols in libmylibrary.so with `readelf -Ws libmylibrary.so | grep ncnn`. All other symbols looks fine except this _ZTIN4ncnn5LayerE:
```
   256: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZTIN4ncnn5LayerE
 68965: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZTIN4ncnn5LayerE
```

I then checked symbols exported by libncnn.so and it doesn't export _ZTIN4ncnn5LayerE. 

I also tried using latest prebuilt static and shared binaries, with or without Vulkan, building ncnn from source, but none of them solves the issue.

Thoughts?

**Comment by nihui** [comment]
the prebuilt packages are compiled without c++ RTTI and exceptions.
If you link the library with rtti enabled, you will get undefined symbol error for ```typeinfo for ncnn::Layer``` etc.
try building ncnn from source with ```cmake -DNCNN_DISABLE_RTTI=OFF``` if you need these features

**Comment by zchrissirhcz** [comment]
To verify this issue, consider using `c++filt` command, which will do the demangle operation, mapping the symbol back to the C/C++ code:
```bash
(base) zz@localhost% c++filt _ZTIN4ncnn5LayerE
typeinfo for ncnn::Layer
```
Note this `typoinfo` related to rtti, as nihui said.
@noelex

**Comment by noelex** [comment]
Yes, I managed to work around this by switching RTTI off on my side. Thanks for the direction.
