### ISSUE TITLE
warpaffine_bilinear_c3人脸5点对齐方法调用

### ISSUE THREAD

**Issue by philp123** [Tencent/ncnn#3384]
在尝试ncnn-20211122版人脸对齐算法warpaffine_bilinear_c3遇到问题，麻烦哪位大牛能解答下么
原始图片如下：
![resizedImage](https://user-images.githubusercontent.com/49138243/143674548-43c0bd63-f98e-45a9-9a07-821538fe4181.jpg)

ncnn::Mat in = ncnn::Mat::from_pixels(img.data, ncnn::Mat::PIXEL_RGB, img.cols, img.rows);

在采用mtcnn获取图片人脸5关键点坐标后，按照faq.md上的说明定义了坐标：
    float point_dst[10] = { // +8 是因为我们处理112*112的图
        30.2946f + 8.0f, 51.6963f,
        65.5318f + 8.0f, 51.5014f,
        48.0252f + 8.0f, 71.7366f,
        33.5493f + 8.0f, 92.3655f,
        62.7299f + 8.0f, 92.2041f,
    };
 
    float point_src[10] = {     //mtcnn得到的人脸关键点在原图的位置
         562.0416,513.0859,
         751.38574,475.80707,
         652.1753,613.9405,
         596.121,681.59717,
         800.2197,641.05023,
    };

然后对比了下opencv和ncnn::get_affine_transform结果，差异不大：
    float tm_inv_ncnn[6];
    ncnn::get_affine_transform(point_src, point_dst, 5, tm_inv_ncnn);
得到的结果:     
tm_inv_ncnn = {   
        0.183683,-0.0401351,-43.977,
        0.0401351,0.183683,-62.5765
};

    float tm_inv_opencv[6] = {
        0.1966497495617472, -0.04298613553276823, -59.04788074890674,
        0.04298613553276819, 0.1966497495617473, -72.06162403846859,
    };

此参数在调用opencv warpAffine得到正常的人脸，但是在调用ncnn::warpaffine_bilinear_c3方法后，所有结果都为0，调用方法如下：

int resizeWidth = 112;
int resizeHeight = 112;
ncnn::Mat out(resizeWidth, resizeHeight, in.c);

int type = 0;       // 0->区域外填充为v[0],v[1],v[2], -233->区域外不处理
ncnn::warpaffine_bilinear_c3(in, in.w, in.h, out, out.w, out.h, tm_inv_ncnn, type);

查看后发现，进入warpaffine_bilinear_c3函数后，

![Screenshot from 2021-11-27 16-54-09](https://user-images.githubusercontent.com/49138243/143674949-5d43a045-018b-4174-a429-d111bf41f4c8.png)

发现每次代码都走到了    sxy_inout = 2;  （854行）

不知道是不是输入有错误，另外也麻烦大神能否解答下faq.md上面point_src的含义，
![Screenshot from 2021-11-27 16-58-24](https://user-images.githubusercontent.com/49138243/143675037-bc6075ce-066b-40fa-8daf-6f5a2d18cdeb.png)

这里面定义的pIveImageU8C3->u32Width在代码里面没搜到，不知道是指的yuv还是什么

**Comment by wzyforgit** [comment]
https://github.com/Tencent/ncnn/issues/3253
可以参考我之前提的issure（虽然还是自己解决的
另外这个仿射变化似乎对图片尺寸有要求，我拿去辅助清洗LFW数据集的时候，那个256*256的图输入进去执行仿射变换会直接崩掉，要resize到一个比较大的尺寸才行，比如512*512

**Comment by philp123** [comment]
> #3253 可以参考我之前提的issure（虽然还是自己解决的 另外这个仿射变换似乎对图片尺寸有要求，我拿去辅助清洗LFW数据集的时候，那个256 * 256的图输入进去执行仿射变换会直接崩掉，要resize到一个比较大的尺寸才行，比如512 * 512

按照您提供的方案，确实可以正常原图，但是还有个问题，因为我想把这部分用于ncnn::Mat，也就是输入ncnn::Mat，输出也是ncnn::Mat，但是这样输入会出现下面这样的图
![Screenshot from 2021-12-06 18-09-55](https://user-images.githubusercontent.com/49138243/144827577-8c185462-06c2-47fc-910f-50fc455001cc.png)

float point_dst[10] = {
        30.2946f + 8.0f, 51.6963f,
	    65.5318f + 8.0f, 51.5014f,
        48.0252f + 8.0f, 71.7366f,
        33.5493f + 8.0f, 92.3655f,
        62.7299f + 8.0f, 92.2041f,
    };

    std::vector<Face> dets;
    cv::Mat im = cv::imread("Helen/testing/2996372177_1.jpg", 1);
    dets.clear();
    facedetectionnet.detect(im, dets);

    ncnn::Mat in_im = ncnn::Mat::from_pixels(im.data, ncnn::Mat::PIXEL_BGR, im.cols, im.rows);
    visualize("in_im", in_im);      //参考官方visualize代码，可以正常显示灰度图

    for (int i = 0; i < dets.size(); ++i) {
        // cv::Mat cropped_face(112, 112, CV_8UC3);
        ncnn::Mat cropped_face(112, 112, 3);
        float tm_inv[6];

        float point_src[10] = {
            dets[i].landmarks.left_eye.x, dets[i].landmarks.left_eye.y,
            dets[i].landmarks.right_eye.x, dets[i].landmarks.right_eye.y,
            dets[i].landmarks.nose_tip.x, dets[i].landmarks.nose_tip.y,
            dets[i].landmarks.mouth_left.x, dets[i].landmarks.mouth_left.y,
            dets[i].landmarks.mouth_right.x, dets[i].landmarks.mouth_right.y,
        };

        ncnn::get_affine_transform(point_dst, point_src, 5, tm_inv);
        ncnn::warpaffine_bilinear_c3((unsigned char*)in_im.data, in_im.h, in_im.w,
                                        (unsigned char*)cropped_face.data, cropped_face.h, cropped_face.w,
                                        tm_inv);
        
        cv::Mat cropped_face_mat(cropped_face.h, cropped_face.w, CV_8UC3);
        cropped_face.to_pixels(cropped_face_mat.data, ncnn::Mat::PIXEL_BGR2RGB);

        cv::imshow("win", cropped_face_mat);
        cv::waitKey(0);
    }

**Comment by wzyforgit** [comment]
> > #3253 可以参考我之前提的issure（虽然还是自己解决的 另外这个仿射变换似乎对图片尺寸有要求，我拿去辅助清洗LFW数据集的时候，那个256 * 256的图输入进去执行仿射变换会直接崩掉，要resize到一个比较大的尺寸才行，比如512 * 512
> 
> 按照您提供的方案，确实可以正常原图，但是还有个问题，因为我想把这部分用于ncnn::Mat，也就是输入ncnn::Mat，输出也是ncnn::Mat，但是这样输入会出现下面这样的图 ![Screenshot from 2021-12-06 18-09-55](https://user-images.githubusercontent.com/49138243/144827577-8c185462-06c2-47fc-910f-50fc455001cc.png)
> 
> ```
> std::vector<Face> dets;
> cv::Mat im = cv::imread("Helen/testing/2996372177_1.jpg", 1);
> dets.clear();
> facedetectionnet.detect(im, dets);
> 
> ncnn::Mat in_im = ncnn::Mat::from_pixels(im.data, ncnn::Mat::PIXEL_BGR, im.cols, im.rows);
> visualize("in_im", in_im);      //参考官方visualize代码，可以正常显示灰度图
> 
> float point_dst[10] = {
>     30.2946f + 8.0f, 51.6963f,
>     65.5318f + 8.0f, 51.5014f,
>     48.0252f + 8.0f, 71.7366f,
>     33.5493f + 8.0f, 92.3655f,
>     62.7299f + 8.0f, 92.2041f,
> };
> 
> for (int i = 0; i < dets.size(); ++i) {
>     // cv::Mat cropped_face(112, 112, CV_8UC3);
>     ncnn::Mat cropped_face(112, 112, 3);
>     float tm_inv[6];
> 
>     float point_src[10] = {
>         dets[i].landmarks.left_eye.x, dets[i].landmarks.left_eye.y,
>         dets[i].landmarks.right_eye.x, dets[i].landmarks.right_eye.y,
>         dets[i].landmarks.nose_tip.x, dets[i].landmarks.nose_tip.y,
>         dets[i].landmarks.mouth_left.x, dets[i].landmarks.mouth_left.y,
>         dets[i].landmarks.mouth_right.x, dets[i].landmarks.mouth_right.y,
>     };
> 
>     ncnn::get_affine_transform(point_dst, point_src, 5, tm_inv);
>     ncnn::warpaffine_bilinear_c3((unsigned char*)in_im.data, in_im.h, in_im.w,
>                                     (unsigned char*)cropped_face.data, cropped_face.h, cropped_face.w,
>                                     tm_inv);
>     
>     cv::Mat cropped_face_mat(cropped_face.h, cropped_face.w, CV_8UC3);
>     cropped_face.to_pixels(cropped_face_mat.data, ncnn::Mat::PIXEL_BGR2RGB);
> 
>     cv::imshow("win", cropped_face_mat);
>     cv::waitKey(0);
> }
> ```

ncnn::Mat cropped_face(112, 112, 3);
注意一下这句代码，它实际上是没有分配内存的，这就是导致后面图片花掉的原因
要让它分配内存，要么传一个内存分配器进去，要么让它指向你自己在外面分配的内存块
我上面给你示例就是我让它指向了QImage分配的内存块

**Comment by philp123** [comment]
> > > #3253 可以参考我之前提的issure（虽然还是自己解决的 另外这个仿射变换似乎对图片尺寸有要求，我拿去辅助清洗LFW数据集的时候，那个256 * 256的图输入进去执行仿射变换会直接崩掉，要resize到一个比较大的尺寸才行，比如512 * 512
> > 
> > 
> > 按照您提供的方案，确实可以正常原图，但是还有个问题，因为我想把这部分用于ncnn::Mat，也就是输入ncnn::Mat，输出也是ncnn::Mat，但是这样输入会出现下面这样的图 ![Screenshot from 2021-12-06 18-09-55](https://user-images.githubusercontent.com/49138243/144827577-8c185462-06c2-47fc-910f-50fc455001cc.png)
> > ```
> > std::vector<Face> dets;
> > cv::Mat im = cv::imread("Helen/testing/2996372177_1.jpg", 1);
> > dets.clear();
> > facedetectionnet.detect(im, dets);
> > 
> > ncnn::Mat in_im = ncnn::Mat::from_pixels(im.data, ncnn::Mat::PIXEL_BGR, im.cols, im.rows);
> > visualize("in_im", in_im);      //参考官方visualize代码，可以正常显示灰度图
> > 
> > float point_dst[10] = {
> >     30.2946f + 8.0f, 51.6963f,
> >     65.5318f + 8.0f, 51.5014f,
> >     48.0252f + 8.0f, 71.7366f,
> >     33.5493f + 8.0f, 92.3655f,
> >     62.7299f + 8.0f, 92.2041f,
> > };
> > 
> > for (int i = 0; i < dets.size(); ++i) {
> >     // cv::Mat cropped_face(112, 112, CV_8UC3);
> >     ncnn::Mat cropped_face(112, 112, 3);
> >     float tm_inv[6];
> > 
> >     float point_src[10] = {
> >         dets[i].landmarks.left_eye.x, dets[i].landmarks.left_eye.y,
> >         dets[i].landmarks.right_eye.x, dets[i].landmarks.right_eye.y,
> >         dets[i].landmarks.nose_tip.x, dets[i].landmarks.nose_tip.y,
> >         dets[i].landmarks.mouth_left.x, dets[i].landmarks.mouth_left.y,
> >         dets[i].landmarks.mouth_right.x, dets[i].landmarks.mouth_right.y,
> >     };
> > 
> >     ncnn::get_affine_transform(point_dst, point_src, 5, tm_inv);
> >     ncnn::warpaffine_bilinear_c3((unsigned char*)in_im.data, in_im.h, in_im.w,
> >                                     (unsigned char*)cropped_face.data, cropped_face.h, cropped_face.w,
> >                                     tm_inv);
> >     
> >     cv::Mat cropped_face_mat(cropped_face.h, cropped_face.w, CV_8UC3);
> >     cropped_face.to_pixels(cropped_face_mat.data, ncnn::Mat::PIXEL_BGR2RGB);
> > 
> >     cv::imshow("win", cropped_face_mat);
> >     cv::waitKey(0);
> > }
> > ```
> 
> ncnn::Mat cropped_face(112, 112, 3); 注意一下这句代码，它实际上是没有分配内存的，这就是导致后面图片花掉的原因 要让它分配内存，要么传一个内存分配器进去，要么让它指向你自己在外面分配的内存块 我上面给你示例就是我让它指向了QImage分配的内存块

我明白您的意思，但是在实现过程中，还是有问题
    const char* imagepath = "2996372177_1.jpg";
    cv::Mat m = cv::imread(imagepath, 1);
    float tm_inv[6] = {12.1176348f, -0.306975275f, 939.240601f, 0.306975275f, 12.1176348f, 199.664124f};
    ncnn::Mat in = ncnn::Mat::from_pixels(m.data, ncnn::Mat::PIXEL_BGR2RGB, m.cols, m.rows);

    ncnn::Mat cropped_face_ncnn;
    cropped_face_ncnn.create(112, 112, 3);

    ncnn::warpaffine_bilinear_c3((unsigned char*)in.data, in.w, in.h,
                                        (unsigned char*)cropped_face_ncnn.data, cropped_face_ncnn.w, cropped_face_ncnn.h, 
                                        tm_inv);

    cv::Mat output(cropped_face_ncnn.h, cropped_face_ncnn.w, CV_8UC3);
    cropped_face_ncnn.to_pixels(output.data, ncnn::Mat::PIXEL_BGR2RGB);
    cv::imshow("win", output);
    cv::waitKey(0);
![Screenshot from 2021-12-08 11-33-42](https://user-images.githubusercontent.com/49138243/145143647-0a374205-2b04-45f3-9821-e74293382aa6.png)

**Comment by wzyforgit** [comment]
大哥 or 大姐，你得跟代码进去看看啊，ncnn是开源的。。。
他们的设计原则就是，你不给内存分配器，里面就不会给你分配内存，所以你会看到ncnn的示例都是先用opencv的cv::Mat申请一块内存，然后用ncnn::Mat去指向它
而你最后发的这坨代码非常明显没有给cropped_face_ncnn传入内存分配器，也没有主动指向某个已分配的内存块

**Comment by philp123** [comment]
> 大哥 or 大姐，你得跟代码进去看看啊，ncnn是开源的。。。 他们的设计原则就是，你不给内存分配器，里面就不会给你分配内存，所以你会看到ncnn的示例都是先用opencv的cv::Mat申请一块内存，然后用ncnn::Mat去指向它 而你最后发的这坨代码非常明显没有给cropped_face_ncnn传入内存分配器，也没有主动指向某个已分配的内存块

是的，已经查到问题，但是即使分配内存后，由于warpaffine_bilinear_c3代码的实现，此方法只能用于uchar格式，不适合ncnn::Mat，因为ncnn::Mat不存在uchar数据格式
