### ISSUE TITLE
使用ncnn推理时error

### ISSUE THREAD

**Issue by FengMu1995** [Tencent/ncnn#3390]
编译运行环境都是linux
然后在推理自己的代码时出现
[New LWP 17798]
[New LWP 17800]
[New LWP 17802]
[New LWP 17801]
[New LWP 17803]
[New LWP 17799]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./matting-infer'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562614d73a39 in ncnn::NetPrivate::forward_layer(int, std::vector<ncnn::Mat, std::allocator<ncnn::Mat> >&, ncnn::Option const&) const ()
[Current thread is 1 (Thread 0x7f979a75cc00 (LWP 17798))]

**Comment by zchrissirhcz** [comment]
考虑断点调试。VSCode +  C++插件，或者 gdb 命令行。

**Comment by FengMu1995** [comment]
这个就是用gdb调试出来的结果，因为链接的是库，没办法深层找了

**Comment by zchrissirhcz** [comment]
> 这个就是用gdb调试出来的结果，因为链接的是库，没办法深层找了
问题一分为二。

第一，真的没法深层调试了吗？你有设置过断点吗？设置断点后，什么条件下才能调试进去有了解过吗？ncnn 是开源代码，不是闭源库，你可以进行各种尝试探索。

第二，你确实觉得尽力了，没法调试进去，那怎样寻求帮助呢？别人不知道你跑的是什么程序。你随便丢一个报错，别人是猜不到你跑的具体程序是什么的。

**Comment by FengMu1995** [comment]
好的，我通过源码进行断电调试

**Comment by FengMu1995** [comment]
因为是ubuntu系统，只能一个个include，在编译ncnn的时候出现 c_api.cpp:47:12: error: ‘NCNN_VERSION_STRING’ was not declared in this scope return NCNN_VERSION_STRING;，不明白是缺了什么东西吗

**Comment by zchrissirhcz** [comment]
>因为是ubuntu系统，只能一个个include
如果你指的是，把 ncnn 的头文件，一个一个 include 进来。那应该是你的设置方式不够高效。

>error: ‘NCNN_VERSION_STRING’ was not declared in this scope return NCNN_VERSION_STRING;
这就类似于成语“断章取义”描述的情况，你用 ncnn 的方式不太恰当，出现了非预期的编译错误。

应当用 cmake 构建你的工程， 并且用 find_package(ncnn) 的方式引入 ncnn 库。https://github.com/Tencent/ncnn/wiki/use-ncnn-with-own-project
或者直接在 ncnn 工程里改 example / benchmark 工程。

**Comment by FengMu1995** [comment]
上面那位,我目前用了很多种框架了,没有一个论坛的开发者像你一样指责别人不去深层调试, 我都和你说了那个就是adb调试的结果.目前证明就是你们的ncnn库错误日志打印出来的东西并不明确才导致我们用户不知道问题出在哪里.我之前就解决了这个问题,但是我依然想说一句,如果你们这样做产品,就觉得开源库不需要对用户负责,那做出来的东西几年以后一定没人用.

**Comment by zchrissirhcz** [comment]
@FengMu1995 ncnn 是腾讯的开源项目；我不是腾讯的，我是和你一样的 ncnn 用户；你觉得 ncnn 不好调试，使用起来各种问题，我在你之前也有这样那样的“抱怨”，我所做的是给 ncnn 的 wiki 补充文档，修改 ncnn 里的  CMake 写的不好、不对的地方。

>如果你们这样做产品,就觉得开源库不需要对用户负责,那做出来的东西几年以后一定没人用.
我在 issue 里回复问题，完全是自发的，按个人觉得最有效的帮助提问者解决问题的方式回复的。如果你觉得没有帮助，那也 OK， 毕竟 ncnn 不是我写的， 我也不需要对 ncnn 负责。但你说 “不需要对用户负责”， 我只能说一个事实： ncnn 只有 @nihui 一个人开发，维持了5年，其他的代码贡献都是“用户自愿的”，我们并没有从中捞到什么好处； 你可以在项目主页里看到 QQ 群信息， 在QQ群里提问并得到回复的人有很多。

>没有一个论坛的开发者像你一样指责别人不去深层调试,
我就是这个风格，改不了了，你不喜欢可以忽略。

**Comment by godka** [comment]
无条件支持zz大佬

**Comment by FengMu1995** [comment]
风格就是解决不了问题在别人的问题下面说了一些没用的话, 然后带来了一些水货一起.
你上面提的东西根本就没有理解我的问题,提出了一个错误的方法.
笑，用cmake find_package ”加载源码“

**Comment by 791136190** [comment]
> 无条件支持zz大佬

无敌

**Comment by FeiGeChuanShu** [comment]
matting没啥后处理要做，大概率是转出来的模型有问题？如果能发模型就附上模型，不行那就瞎搞即可

**Comment by LJoson** [comment]
发生甚么事了

**Comment by Yoh-Z** [comment]
试试预编译库呢，实在不行带上源码debug

**Comment by FengMu1995** [comment]
确实是无条件支持, 这些匿名的水军有啥资格,自己都知道自己是无条件的idiot

**Comment by scarsty** [comment]
没有匿名

**Comment by FengMu1995** [comment]
> 没有匿名
你本身就是个没有名气的trash,当然不需要匿名了

**Comment by FengMu1995** [comment]
> @FengMu1995 ncnn 是腾讯的开源项目；我不是腾讯的，我是和你一样的 ncnn 用户；你觉得 ncnn 不好调试，使用起来各种问题，我在你之前也有这样那样的“抱怨”，我所做的是给 ncnn 的 wiki 补充文档，修改 ncnn 里的 CMake 写的不好、不对的地方。
> 
> > 如果你们这样做产品,就觉得开源库不需要对用户负责,那做出来的东西几年以后一定没人用.
> > 我在 issue 里回复问题，完全是自发的，按个人觉得最有效的帮助提问者解决问题的方式回复的。如果你觉得没有帮助，那也 OK， 毕竟 ncnn 不是我写的， 我也不需要对 ncnn 负责。但你说 “不需要对用户负责”， 我只能说一个事实： ncnn 只有 @nihui 一个人开发，维持了5年，其他的代码贡献都是“用户自愿的”，我们并没有从中捞到什么好处； 你可以在项目主页里看到 QQ 群信息， 在QQ群里提问并得到回复的人有很多。
> 
> > 没有一个论坛的开发者像你一样指责别人不去深层调试,
> 
> 我就是这个风格，改不了了，你不喜欢可以忽略。
谁也没说你为ncnncontribute的事情,讨论的就是这个问题,那全都是你自己把这里当成炫耀的舞台了,是可以不看啊,那也要你这只烦人的苍蝇不写啊,开源本身就是和优秀的人交流问题, 谁也没逼你写一些没用的东西.而且你知呼那些写的东西有用吗,连算法内容都没有,就会炫一些开发小技能.你看下你这些水军contribute的都是些啥呀,真的low.

**Comment by scarsty** [comment]
I am low

**Comment by godka** [comment]
I am low 2

**Comment by FengMu1995** [comment]
> I am low

知道low就行了,说给别人听干什么

**Comment by FengMu1995** [comment]
> I am low 2

why should others be told you are low?

**Comment by scarsty** [comment]
god on high

**Comment by FengMu1995** [comment]
> god on high
跟你说话就是浪费时间,886.

**Comment by scarsty** [comment]
hear my pray

**Comment by godka** [comment]
> > I am low 2
> 
> why should others be told you are low?

cuz I can bro.

**Comment by godka** [comment]
> hear my pray

in my need

**Comment by scarsty** [comment]
> > hear my pray
> 
> 
> 
> in my need

you have always been there

**Comment by FengMu1995** [comment]
> > > I am low 2
> > 
> > 
> > why should others be told you are low?
> 
> cuz I can bro.

God can't understand your words, low bro.886

**Comment by godka** [comment]
> > > > I am low 2
> > > 
> > > 
> > > why should others be told you are low?
> > 
> > 
> > cuz I can bro.
> 
> God can't understand your words, low bro.886

好嘞老哥明年见

**Comment by FengMu1995** [comment]
> > > > > I am low 2
> > > > 
> > > > 
> > > > why should others be told you are low?
> > > 
> > > 
> > > cuz I can bro.
> > 
> > 
> > God can't understand your words, low bro.886
> 
> 好嘞老哥明年见

哇塞，没想到有人回复我了诶。老哥，之前没看到！！！

**Comment by scarsty** [comment]
he is young
