### ISSUE TITLE
does ncnn support caffemodel loading?

### ISSUE THREAD

**Issue by VivienFu** [Tencent/ncnn#34]
as the example, model loading using:
	squeezenet.load_param("squeezenet_v1.1.param");
	squeezenet.load_model("squeezenet_v1.1.bin");

does ncnn support caffemodel loading? how to load caffemodel?

**Comment by humf** [comment]
@VivienFu See The Wiki
![12bc61ca-1a07-477a-9ca7-e3d5164e66ee](https://user-images.githubusercontent.com/4101464/28604857-762359e8-7200-11e7-9130-6ee9dd95b98f.png)

**Comment by VivienFu** [comment]
@humf  got it, thx!
