### ISSUE TITLE
pnnx: bug when input dtype is torch.uint8

### ISSUE THREAD

**Issue by pfeatherstone** [Tencent/ncnn#3409]
https://github.com/pnnx/pnnx/issues/3

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/3419

**Comment by nihui** [comment]
resolved in https://github.com/Tencent/ncnn/commit/db1fed6e115c409ca1ae5b26c8faf849e2ee1c6d

pass cmdline arg ```inputshape=[1,3,224,224]u8```
