### ISSUE TITLE
Extractor seems not support one input with muti-branch ouput

### ISSUE THREAD

**Issue by Pinnh** [Tencent/ncnn#343]
Extractor::extract(int blob_index, Mat& feat) seems not support one input with muti-branch ouput, the cnn architecture is looks like 
![x](https://user-images.githubusercontent.com/11919692/38490778-9bbae874-3c1c-11e8-8e84-9327a6ac3bf8.png)
can I extract both conv5-1 and conv5-2 output which means only run extract(method) once?
thanks.

**Comment by nihui** [comment]
the common practice

```
ncnn::Mat conv51;
ex.extract("conv5-1", conv51);

ncnn::Mat conv52;
ex.extract("conv5-2", conv52);
```

there's some smart logic behind each extract method
the first call will do inference from the graph beginning to conv5-1, but keep the intermediate prelu4 blob (in both light mode and non-light mode)
the second call will do inference from prelu4 to conv5-2
no repeated calculation in your graph at all  :)

**Comment by Pinnh** [comment]
excellent solution!
