### ISSUE TITLE
Failed when building without Vulkan on Intel CPU with GPU

### ISSUE THREAD

**Issue by rose-jinyang** [Tencent/ncnn#3431]
Hello
How are you?
Thanks for contributing to this project.
I tried to use the pre-built library(ncnn-20211208-windows-vs2017.zip) on Windows 10 & vs2017 but failed.

![image](https://user-images.githubusercontent.com/47862419/146531434-5e828078-fcb6-4d52-9b91-fd9c0fa41435.png)

My PC does NOT have a GPU so I did NOT install Vulkan.
How should I fix this issue?
Thanks

**Comment by wangyaxin1998** [comment]
这个问题您解决了吗

**Comment by nihui** [comment]
The latest master branch supports compiling gpu functions without installing vulkan-sdk. You can give it a try.
If it doesn’t work, feel free to reopen the issue and post your findings.
