### ISSUE TITLE
ncnn前向推理与pytorch与OnnxRumtime不一致- 初步定位为BinaryOp-Sub问题，辛苦大大看下

### ISSUE THREAD

**Issue by zhanglaplace** [Tencent/ncnn#3432]
## context | 编译/运行环境 | バックグラウンド
ncnn版本为最新release的，tag20211208，系统环境为Ubuntu，编译选项去掉vlkun； 

## 模型转化
- pth -> onnx
- onnx-> onnx sim
- onnx sim -> ncnn param 、bin

## 错误地方debug。
- 根据网络图分析效果不一致的节点。3502，为一个sub减法操作，输入来自于两个变量
  - 3450_splitncnn_0 [128 * 64 * 64] 和 3488 [1 * 1 * 1 ] (通过torch.mean([1,2,3],keepdim得到）
   打印出3450_splitncnn_0的前十个元素 float* ptr_out = out.channel(0); for i .. 0~10: printf(ptr_out[i])
   0.813766,0.813985,0.814184,0.814465,0.818144,0.818616,0.825198,0.824326,0.831073,0.828986,
   打印出3488的单个元素-0.25458； 理论减法的结果应该都是1.06左右，但是输出为
   1.06835,0.29488,0.28823,0.281915,0.285424,0.285124,0.308409,0.315561,0.354813,0.371676, 仅仅第一个一致。不符合预期

![image](https://user-images.githubusercontent.com/12178974/146567426-4332b1ab-b184-4a4a-97b3-d810644a84ac.png)

## pytorch对应输出
![image](https://user-images.githubusercontent.com/12178974/146567363-72af9c55-248d-4ee4-9106-13ba738328d2.png)

## 附件为onnx模型、和转化的param和bin文件
[model.zip](https://github.com/Tencent/ncnn/files/7736094/model.zip)

**Comment by zhanglaplace** [comment]
定位到问题； pytorch如果mean操作为123维度，在ncnn修改all_reduce，keepdim=0即可。如果mean为23维度，不修改。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
