### ISSUE TITLE
pnnx2ncnn

### ISSUE THREAD

**Issue by lavender-ling** [Tencent/ncnn#3435]
## error log | 日志或报错信息 | ログ
pnnxparam = model.pnnx.param
pnnxbin = model.pnnx.bin
pnnxpy = model_pnnx.py
ncnnparam = model.ncnn.param
ncnnbin = model.ncnn.bin
ncnnpy = model_ncnn.py
optlevel = 2
device = cpu
inputshape = [1,3,320,640]f32
inputshape2 =
customop =
moduleop =
############# pass_level0
inline module = lib.models.bisenetv2.BGALayer
inline module = lib.models.bisenetv2.CEBlock
inline module = lib.models.bisenetv2.ConvBNReLU
inline module = lib.models.bisenetv2.DetailBranch
inline module = lib.models.bisenetv2.GELayerS1
inline module = lib.models.bisenetv2.GELayerS2
inline module = lib.models.bisenetv2.SegmentBranch
inline module = lib.models.bisenetv2.SegmentHead
inline module = lib.models.bisenetv2.StemBlock
inline module = torch.nn.modules.linear.Identity
############# pass_level1
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value
############# pass_ncnn
Segmentation fault
## model | 模型 | モデル
1. original model
[model.zip](https://github.com/Tencent/ncnn/files/7742313/model.zip)

## how to reproduce | 复现步骤 | 再現方法
1../pnnx model.pt  inputshape=[1,3,320,640]

**Comment by nihui** [comment]
fixed
