### ISSUE TITLE
安卓工程使用的为202009版本ncnn库，想试下int8模型，采用最新的ncnn库，andriod studio报错如下

### ISSUE THREAD

**Issue by lavender-ling** [Tencent/ncnn#3438]
## detail | 详细描述 | 詳細な説明
![123899877-9e5cb980-d99a-11eb-92b4-2a960bda1fc1](https://user-images.githubusercontent.com/56438742/146906328-c249f9a9-c1f9-4220-816c-491f410ae0da.png)

**Comment by nihui** [comment]
参考这里的 cmake 配置
https://github.com/nihui/ncnn-android-yolov5/blob/master/app/src/main/jni/CMakeLists.txt

**Comment by lavender-ling** [comment]
谢谢，解决问题。
