### ISSUE TITLE
ncnn在xcode上找不到net.h

### ISSUE THREAD

**Issue by stereomatchingkiss** [Tencent/ncnn#3440]
os : ios 14
xcode : 13
macOS: 12
ncnn : ncnn-20211208-ios
opencv : opencv-4.5.4-ios-framework

我想用ncnn编译一个ios的static lib供unity调用，可是无论怎么做，编译的时候都会投诉不能够找到header file。

我首先用xcode创建一个新的project，选择static lib,然后加入很简单的source codes.

[img_00](https://i.stack.imgur.com/FXNHQ.png)

example.hpp

```
extern "C"{

#include <net.h> //XCode cannot find this file

int summation();

}
```

example.cpp

```
extern "C"{

int summation()
{
    return 1001;
}

}

```

接着加入framework，设置编译平台为ios

[img_01](https://i.stack.imgur.com/9RjUk.png)

然后选择编译类型为release

[img_02](https://i.stack.imgur.com/2ga2Z.png)

选择编译，然后程序报错，找不到<net.h>
我尝试过去掉<net.h>，.a档是可以build出来的，但是加入ncnn的header后会找不到header，很奇怪，不知道是哪里设定不对。

这是我第一次接触ios的project，很多地方不太清楚该怎么做，网路上能找到的资料也不多，写得比较详尽的不是资料太旧，就是告诉我要如何用cmake编译opencv，至于如何用c++链接其他c++的framework，build一个static lib出来，就找不到什么资料了，感觉是我找的方向不对。

感谢大家能耐着性子看完，谢谢

**Comment by wzyforgit** [comment]
没用过xcode。。。不过看这个代码，用extern "C"把#include <net.h>包起来可能有些问题，因为这个头文件里有一大堆的C++ class

**Comment by stereomatchingkiss** [comment]
> 没用过xcode。。。不过看这个代码，用extern "C"把#include <net.h>包起来可能有些问题，因为这个头文件里有一大堆的C++ class

Ah, 有道理哦，我居然犯了这么白痴的错误，而且还没发现，蠢到家了，真想给自己几巴掌，谢谢提点

**Comment by stereomatchingkiss** [comment]
最近再试了一次，把header file移出extern "C" 外面，还是不行，头大，找不到啥教学，这种东西通常不难，但是没有tutorials的话可以摸很久

**Comment by stereomatchingkiss** [comment]
成功的编译了，不过用的是cmake大法generate的make file，XCode这方面的教学资料不多，很难找，找到的都是旧资料，要不是ios上，用c++写static lib的人不多，就是会这么做的人都是老手，绝得没有分享经验的价值，导致资料稀少。

简化过的CMakeLists.txt

```
cmake_minimum_required(VERSION 3.5)

project(puzzle_pieces_plugin LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)

if(APPLE)
    add_definitions(-DTHIS_IS_IOS) #ncnn的header files，ios的framework，位置跟windows和android的不一样
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER) #这行很重要，可以是BOTH或NEVER（根据情况选择），不这么写的话，cmake会找不到custom framework的位置
    set(3RDLIBS_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../3rdLibs)

	#我知道的其他平台清一色都能靠find_package解决问题，只有ios比较特别，必须用find_library，详细的文档请自己查询
	#NAMES取framework的前缀就好，例如opencv2.framework，NAMES就是opencv2，以此类推
    find_library(OPENCV_IOS_LIBRARY NAMES opencv2 PATHS ${3RDLIBS_PATH}/opencv/ NO_DEFAULT_PATH)
    find_library(OPENMP_IOS_LIBRARY NAMES openmp PATHS ${3RDLIBS_PATH}/ncnn/ NO_DEFAULT_PATH)
    find_library(NCNN_IOS_LIBRARY NAMES ncnn PATHS ${3RDLIBS_PATH}/ncnn/ NO_DEFAULT_PATH)
endif()

ADD_LIBRARY(${PROJECT_NAME} STATIC example.hpp example.cpp)

#include path的部分跟其他os一样
target_include_directories(${PROJECT_NAME} PRIVATE ${3RDLIBS_PATH}/boost/boost_1_76_0)
target_include_directories(${PROJECT_NAME} PRIVATE ${3RDLIBS_PATH}/fmt/include)

if(APPLE)
    target_link_libraries(${PROJECT_NAME} ${OPENCV_IOS_LIBRARY} ${NCNN_IOS_LIBRARY} ${OPENMP_IOS_LIBRARY})
endif()


```

这个.a档是编译出来了，但不知道能不能执行，毕竟我手上没有任何ios的设备，只能等另外一个团队测试了

**Comment by stereomatchingkiss** [comment]
另外一个team测试后的结果是ok的，这个方法确实可以编译出ios的plugin.希望这一帖能帮到其他人

**Comment by Linkersem** [comment]
小白求问，我把rvm封装成了dll导入到了unity中，但是官方示例里面的rvm函数会一直加载模型和模型参数，我想把这一部分摘出来，rvm函数load需要net的对象，这个情况应该怎么处理呀

**Comment by nihui** [comment]
> 小白求问，我把rvm封装成了dll导入到了unity中，但是官方示例里面的rvm函数会一直加载模型和模型参数，我想把这一部分摘出来，rvm函数load需要net的对象，这个情况应该怎么处理呀

rvm example updated
https://github.com/Tencent/ncnn/blob/master/examples/rvm.cpp
https://github.com/nihui/ncnn-android-rvm

rvm ncnn deploy guide(zh)
https://zhuanlan.zhihu.com/p/1900989328831783411
