### ISSUE TITLE
使用的是最新的pnnx，只生成了*.pnnx.bin 和 *.pnnx.param 没有生成 *.ncnn.bin和*.ncnn.param文件

### ISSUE THREAD

**Issue by cyinen** [Tencent/ncnn#3442]
## error log | 日志或报错信息 | ログ
 pnnx.exe .\net_final.pt inputshape=[1,3,224,224],[1,3,224,224],[1,3,224,224],[1,3,224,224],[1],[1]
pnnxparam = .\net_final.pnnx.param
pnnxbin = .\net_final.pnnx.bin
pnnxpy = .\net_final_pnnx.py
ncnnparam = .\net_final.ncnn.param
ncnnbin = .\net_final.ncnn.bin
ncnnpy = .\net_final_ncnn.py
optlevel = 2
device = cpu
inputshape = [1,3,224,224],[1,3,224,224],[1,3,224,224],[1,3,224,224],[1],[1]
inputshape2 =
customop =
moduleop =
############# pass_level1
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value
## context | 编译/运行环境 | バックグラウンド
最新的pnnx
生成的文件
-a---          2021/12/23    13:32      103017586 debug.bin
-a---          2021/12/23    13:32          42354 debug.param
-a---          2021/12/23    13:33      103017586 debug2.bin
-a---          2021/12/23    13:33          31305 debug2.param
-a---          2021/12/23    13:33          42358 net_final_pnnx.py
-a---          2021/12/23    13:33      103017586 net_final.pnnx.bin
-a---          2021/12/23    13:33          31017 net_final.pnnx.param

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/05321904998dec92eaf0edf3060836478ee60b34
