### ISSUE TITLE
Question about extract() with Slice layer -- all Out w h c  are Zero

### ISSUE THREAD

**Issue by AnshanTJU** [Tencent/ncnn#345]
Hi,  
I use the NCNN library to extract the blob using:
ex.extract(pose_0408_param_id::BLOB_Mconv7_stage2,out);
However, the out W H C are all 0. The net  prototxt is like following:
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 1 dim: 4 dim: 368 dim: 368 } } 
}
layer {
  name: "image"
  type: "Slice"
  bottom: "data"
  top: "image"
  top: "center_map"
  slice_param {
    slice_point: 3
    axis: 1
  }
}
layer {
  name: "pool_center_lower"
  type: "Pooling"
  bottom: "center_map"
  top: "pool_center_lower"
  pooling_param {
    pool: AVE 
    kernel_size: 9
    stride: 8
  }
}
I tried to extract BLOB_pool_center_lower, But also get 0. The BLOB_data is right.
Does there any error with Slice layer?

**Comment by northeastsquare** [comment]
@AnshanTJU Have you solve it, I also met this. Could you share your final solution?
