### ISSUE TITLE
Android sample更换网络应用编译成功，但是闪退

### ISSUE THREAD

**Issue by TonyTangYu** [Tencent/ncnn#346]
在跑https://github.com/dangbo/ncnn-mobile 的As工程时，想把squeezenet换成mobilenet，我把相应文件都转化为ncnn需要的文件，即把squeezenetv1.1.param.bin和squeezenetv1.1.bin更换为mobilenet.param.bin和mobilenet.bin之后（参考是：https://blog.csdn.net/computerme/article/details/77876633 ），AS工程可以编译成功，但是上机跑闪退。请问还需要其他文件支持吗？有一步生成的mobilenet.id.h怎么使用呢？

**Comment by TonyTangYu** [comment]
@zkfzle 已经放到相应目录了

**Comment by nihui** [comment]
不要用 ncnn-mobile 那个工程，用这里的 https://github.com/Tencent/ncnn/tree/master/examples/squeezencnn
