### ISSUE TITLE
使用yoloV5 官方提供的 'yolov5n.onnx',转换ncnn时报错

### ISSUE THREAD

**Issue by superbayes** [Tencent/ncnn#3468]
## model | 模型 | モデル
1. [original model](https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5n.onnx)

## how to reproduce | 复现步骤 | 再現方法
1.[下载yoloV5官方的模型yolov5n.onnx](https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5n.onnx)
2.转换时遇到问题
![yoloV5Issues](https://user-images.githubusercontent.com/56495942/147730131-ef7e9d53-b4bb-46da-8a09-a041a7b656b5.PNG)

**Comment by superbayes** [comment]
报错日志
[yolov5issue.txt](https://github.com/Tencent/ncnn/files/7791897/yolov5issue.txt)

**Comment by cmdbug** [comment]
https://zhuanlan.zhihu.com/p/275989233
https://zhuanlan.zhihu.com/p/428911425

**Comment by superbayes** [comment]
@cmdbug 
万分感谢,按照教程,问题已解决

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
