### ISSUE TITLE
module 'ncnn' has no attribute 'get_gpu_device'

### ISSUE THREAD

**Issue by styler00dollar** [Tencent/ncnn#3471]
## error log | 日志或报错信息 | ログ

```
module 'ncnn' has no attribute 'get_gpu_device'
```

## how to reproduce | 复现步骤 | 再現方法
- `pip install ncnn` or `pip3 install git+https://github.com/Tencent/ncnn.git`

```
import ncnn
vkdev = ncnn.get_gpu_device(0)
```

It is used in the test files, but it does not exist.
https://github.com/Tencent/ncnn/blob/014387dfae999fe71fba559de790bd5a0a78973c/python/tests/benchmark.py#L126
https://github.com/Tencent/ncnn/blob/13d12da245e515031d35455a68701b254870a760/python/tests/test_vulkan_allocator.py#L24

**Comment by nihui** [comment]
Hi, the latest pyncnn gains vulkan support !
pip install -U ncnn
