### ISSUE TITLE
ncnn with Python API does not run on GPU despite using use_vulkan_compute=True

### ISSUE THREAD

**Issue by styler00dollar** [Tencent/ncnn#3472]
## context | 编译/运行环境 | バックグラウンド

I tested ncnn on a NVidia (1070ti) and a AMD (rx470) pc, both dont run this code on GPU, despite using `net.opt.use_vulkan_compute = True` like [here](https://github.com/Tencent/ncnn/blob/master/docs/how-to-use-and-FAQ/FAQ-ncnn-vulkan.md) is said.

![Unbenannt](https://user-images.githubusercontent.com/51405565/147850065-30e193ac-563b-4fb1-bef7-677346caef18.PNG)

ncnn model created with [this architecture](https://github.com/xinntao/Real-ESRGAN/blob/master/realesrgan/archs/srvgg_arch.py).

Running the C++ binary from [xinntao/Real-ESRGAN-ncnn-vulkan](https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan) works at high speed and high GPU usage, so this should not be related to the architecture or param/bin.

## how to reproduce | 复现步骤 | 再現方法
- I tried compiling myself and using `pip install ncnn`

```python
import ncnn
import cv2
import numpy as np
from tqdm import tqdm
net = ncnn.Net()
net.opt.use_vulkan_compute = True
net.load_param("test.param")
net.load_model("test.bin")
net.opt.use_vulkan_compute = True

for f in tqdm(range(1000)):
    ex = net.create_extractor()
    img = np.random.rand(720,1280,3)
    mat_in = ncnn.Mat.from_pixels(
                img,
                ncnn.Mat.PixelType.PIXEL_BGR,
                img.shape[1],
                img.shape[0]
            )
    ex.input("data", mat_in)
    ret, mat_out = ex.extract("output")
```
[test_model.zip](https://github.com/Tencent/ncnn/files/7797631/test_model.zip)

**Comment by joeyballentine** [comment]
Has there been any update on this? I'd like to support ncnn in my code but lacking gpu support is a deal breaker

**Comment by joeyballentine** [comment]
@nihui Looking at the attributes of what's actually included in the ncnn python from pip, I think the problem might be that it was not compiled with vulkan/gpu enabled. None of the GPU related attributes comes up when I check them.

So the one from pypi/pip is equivalent to installing CPU-only pytorch, I think.

**Comment by joeyballentine** [comment]
@nihui I figured this out. setup.py is missing this flag: `"-DNCNN_VULKAN=ON",`. Without it, it does not compile the python wheel with vulkan enabled. Confirmed working with just this one line added on linux.

**Comment by styler00dollar** [comment]
Recompiling with this parameter and turning vulkan on results in `nan`.
```
[0 NVIDIA GeForce GTX 1070 Ti]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1070 Ti]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1070 Ti]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1070 Ti]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
  0%|                                                     | 0/1 [00:00<?, ?it/s]
[[[nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  ...
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]
  [nan nan nan ... nan nan nan]]
  ...
```
Running it with `net.opt.use_vulkan_compute = False` seems to work fine.
```
[[[358.4389   340.10107  335.1232   ... 443.12463  349.5282   365.92096 ]
  [312.67572  287.42047  319.8791   ... 416.70142  375.17178  358.19812 ]
  [321.82782  312.0708   334.771    ... 489.53616  385.58862  441.08942 ]
  ...
```

**Comment by nihui** [comment]
Hi the latest pyncnn includes vulkan support !
pip install -U ncnn
