### ISSUE TITLE
pnnx转换带有roi_align的层报错

### ISSUE THREAD

**Issue by simochen** [Tencent/ncnn#3477]
## error log | 日志或报错信息 | ログ
pnnxparam =lolm_nano_head.pnnx.param
pnnxbin = lolm_nano_head.pnnx.bin
pnnxpy = lolm_nano_head_pnnx.py
ncnnparam = lolm_nano_head.ncnn.param
ncnnbin = lolm_nano_head.ncnn.bin
ncnnpy = lolm_nano_head_ncnn.py
optlevel = 2
device = cpu
inputshape = [1,64,52,52]f32
inputshape2 = [16,5]f32
customop = 
moduleop = 
libc++abi.dylib: terminating with uncaught exception of type torch::jit::ErrorReport: 
Unknown builtin op: torchvision::roi_align.
Could not find any similar ops to torchvision::roi_align. This op may not exist or may not be currently supported in TorchScript.
:
/root/anaconda3/lib/python3.9/site-packages/torchvision/ops/roi_align.py(56): roi_align
/root/anaconda3/lib/python3.9/site-packages/torchvision/ops/roi_align.py(79): forward
/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py(1102): _call_impl
/root/YOLOX/yolox/models/identify_head.py(164): _forward
/root/YOLOX/yolox/models/identify_head.py(192): forward
/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py(1090): _slow_forward
/root/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py(1102): _call_impl
/root/anaconda3/lib/python3.9/site-packages/torch/jit/_trace.py(958): trace_module
/root/anaconda3/lib/python3.9/site-packages/torch/jit/_trace.py(741): trace
/root/YOLOX/tools/export_torchscript.py(116): export_head
/root/anaconda3/lib/python3.9/site-packages/loguru/_logger.py(1220): catch_wrapper
/root/YOLOX/tools/export_torchscript.py(127): <module>
Serialized   File "code/__torch__/torchvision/ops/roi_align.py", line 9
    bbox: Tensor,
    argument_2: Tensor) -> Tensor:
    input = ops.torchvision.roi_align(argument_2, bbox, 0.125, 3, 3, -1, True)
            ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return input

Abort trap: 6

## model | 模型 | モデル
1. original model
[lolm_nano_head.pt.zip](https://github.com/Tencent/ncnn/files/7806231/lolm_nano_head.pt.zip)

## how to reproduce | 复现步骤 | 再現方法
1. ./pnnx ./lolm_nano_head.pt inputshape=[1,64,52,52] inputshape2=[16,5]

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/3478

**Comment by nihui** [comment]
编译时需要支持 torchvision 才能转换

**Comment by simochen** [comment]
> 编译时需要支持 torchvision 才能转换

请问这部分有参考文档吗

**Comment by nihui** [comment]
https://github.com/pnnx/pnnx 上的预编译包已经加上了 torchvision 支持
具体编译步骤可以参考 ci 脚本
https://github.com/pnnx/pnnx/blob/847e782018d4d73c6f39502e969174fb17b88a95/.github/workflows/release.yml#L50

**Comment by simochen** [comment]
感谢！
