### ISSUE TITLE
为何Mat在写入图片后数据预测不一样

### ISSUE THREAD

**Issue by wangha43** [Tencent/ncnn#349]
在解码一段视频流获得的Mat后,使用ncnn获得的概率不一样,但是Mat数据是一样的
`Mat rectMat = temp(v[i]);`
`fc->detect_facialnet(rectMat);`
`imwrite("/home/wxc/Pictures/test.png",rectMat);`
`Mat cv_test = imread("/home/wxc/Pictures/test.png");`
`fc->detect_facialnet(cv_test);`
一个是解码出来的,一个保存后再读取的,经查看打印出来的数据都一样.
其中detect_facialnet是使用ncnn去计算概率,使用的都是ncnn::mat::pixel_bgr2gray 
请问哪里不一样呢,搞的头大了没找出原因

**Comment by nihui** [comment]
Mat::from_pixels assumes the pixel buffer continous
so, try cloning
```
Mat rectMat = temp(v[i]).clone();
```

**Comment by wangha43** [comment]
Done,You are right.
Gracias!
