### ISSUE TITLE
pnnx 模块转换出现指针越界

### ISSUE THREAD

**Issue by zhu-zhaofei** [Tencent/ncnn#3492]
## error log | 日志或报错信息 | ログ

编译pnnx 没问题，但转化模型时发现出现指针越界。经过调试发现在 ncnn/tools/pnnx/src/pass_ncnn/chain_multi_output.cpp 的99行 
op0->outputs.clear();而101行Operand* op0_out = op0->outputs[0]，op0_out 必定越界。chain_multi_output.cpp需要修改。

![image](https://user-images.githubusercontent.com/30277854/148891898-5447229e-6c95-4389-a50c-ed7e851d234a.png)

https://github.com/Tencent/ncnn/pull/3262#issuecomment-1009631300

@nihui @xiaooquanwu

**Comment by nihui** [comment]
感谢反馈！
