### ISSUE TITLE
pnnx转换yolov5模型pnnx模型文件中池化层层名相同

### ISSUE THREAD

**Issue by deepage** [Tencent/ncnn#3493]
## error log | 日志或报错信息 | ログ
![image](https://user-images.githubusercontent.com/21257239/148924463-b4b2bd74-bdd4-4518-a9cf-30be1f053c4b.png)
池化层的层面都是model.11.m
## model | 模型 | モデル
1. yolov5s6模型

## how to reproduce | 复现步骤 | 再現方法
1.编译pnnx
2../pnnx yolov5s.pt inputshape=[1,3,640,640] inputshape2=[1,3,320,320]

**Comment by nihui** [comment]
感谢反馈！
