### ISSUE TITLE
question about source code

### ISSUE THREAD

**Issue by liupengkd** [Tencent/ncnn#350]
in convolution.cpp
"const int kernel_extent_w = dilation_w * (kernel_w - 1) + 1;
const int kernel_extent_h = dilation_h * (kernel_h - 1) + 1;"
dilation_w 和 kernel_extent_w变量指代的是什么意思？
“ else if (pad_w == -233 && pad_h == -233)
    {
        int wpad = kernel_extent_w + (w - 1) / stride_w * stride_w - w;
        int hpad = kernel_extent_h + (h - 1) / stride_h * stride_h - h;”
这段代码的含义是什么？

**Comment by liupengkd** [comment]
作为初学者，我对卷积参数的理解 
w1=(w0+2*pad-kernel_size)/stride+1;
 h1=(h0+2*pad-kernel_size)/stride+1;

**Comment by nihui** [comment]
may get your answer about dilated convolution in google :)
