### ISSUE TITLE
编译 32 位程序，加载模型的时候会崩掉，64 位正常，请问可能是什么问题？

### ISSUE THREAD

**Issue by demonstan** [Tencent/ncnn#3501]
## error log | 日志或报错信息 | ログ
32位程序加载 iresnet 50/100 模型的时候 (load_model) 程序崩掉

## context | 编译/运行环境 | バックグラウンド
Windows10 64 位系统，vs2019 编译 32 位程序

## how to reproduce | 复现步骤 | 再現方法
1. 将 insightface ir50 / ir100 模型从 pth 转为 onnx
2. 用 onnxsim 将 onnx 模型简化
3. 用 onnx2ncnn 工具将 onnx 模型转为 ncnn 模型
4. 用 vs2019 编译 32 位程序，程序执行到 load_model 的时候崩掉

## more | 其他 | その他
编译 64 位程序则没问题
32 位程序加载 mobilefacenet 也没问题，是因为模型太大了？

**Comment by nihui** [comment]
模型太大了，32位程序能用的内存并不多。。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
