### ISSUE TITLE
up 我遇到一个小问题，onnx2ncnn&pnnx转模型失败的问题，想请您协助一下~

### ISSUE THREAD

**Issue by sxj731533730** [Tencent/ncnn#3502]
## error log | 日志或报错信息 | ログ
模型和错误我放在百度云盘里

微云:https://share.weiyun.com/GOvndoUU
## model | 模型 | モデル
1. 原始模型 model-87.pth

## how to reproduce | 复现步骤 | 再現方法
1.我转onnx可以成功，使用onnx2ncnn转模型，也失败                    model-87.onnx 简化之后的模型是model-87_sim.onnx
2.我使用了traced_script_module 去转了一下模型，为了使用pnnx转化模型，也失败       model-87_jc.pt

**Comment by sxj731533730** [comment]
暂且关闭，up修改了一个版本pr3521

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
