### ISSUE TITLE
vulkan不开启，语义分割掩码会选择性错误

### ISSUE THREAD

**Issue by hwddean** [Tencent/ncnn#3507]
vulkan不开启时，语义分割获取的掩码会出现矩形黑块遮挡，显示mask错误，而且错误图片不固定，随机选择，不知道为什么，请教一下？？

**Comment by 1615070057** [comment]
> vulkan不开启时，语义分割获取的掩码会出现矩形黑块遮挡，显示mask错误，而且错误图片不固定，随机选择，不知道为什么，请教一下？？

大佬，我也遇到了这个问题，请问你是怎么解决的，能指点下吗
