### ISSUE TITLE
"__get_cpuid_count" not declared in cpu.cpp

### ISSUE THREAD

**Issue by harhar539** [Tencent/ncnn#3510]
## error log | 日志或报错信息 | ログ
[ 37%] Building CXX object src/CMakeFiles/ncnn.dir/cpu.cpp.o
/home/hjx/workspace/ncnn-test/ncnn/src/cpu.cpp: In function ‘void ncnn::x86_cpuid_sublevel(int, int, unsigned int*)’:
/home/hjx/workspace/ncnn-test/ncnn/src/cpu.cpp:464:70: error: ‘__get_cpuid_count’ was not declared in this scope
     __get_cpuid_count(level, sublevel, out, out + 1, out + 2, out + 3);
                                                                      ^
make[2]: *** [src/CMakeFiles/ncnn.dir/build.make:688: src/CMakeFiles/ncnn.dir/cpu.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:92: src/CMakeFiles/ncnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
## context | 编译/运行环境 | バックグラウンド
UBUNTU 20.04 
-- NCNN_VERSION_STRING = 1.0.20220117
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
## how to reproduce | 复现步骤 | 再現方法
1. mkdir build
2. cd build
3. cmake  -DNCNN_VULKAN=OFF ..
4. make -j8
## more | 其他 | その他
**I've checked cpuid.h of gcc 5.4.0，“__get_cpuid_count” is not found.**

**Comment by nihui** [comment]
最新代码里修好了，如有问题请 reopen
