### ISSUE TITLE
计算方差数值溢出

### ISSUE THREAD

**Issue by zhanglaplace** [Tencent/ncnn#3519]
## detail | 详细描述 | 詳細な説明
- pytorch模型中有个计算tensor方差的操作
```shell;
input shape : 32 * 64 * 64
in_var  = torch.std(input, dim=[2, 3], keepdim=True) ** 2
ln_var =  torch.std(input, dim=[1, 2, 3], keepdim=True) ** 2
```
- 转换为NCNN后的结构
    -  两条支路，一个求E(x^2),当数值较大时，累加和很大，在安卓的部分机型>=63356后显示inf，数值溢出了
![image](https://user-images.githubusercontent.com/12178974/150292464-4e9af655-e1b8-41ad-8d17-f1b88f071919.png)

![image](https://user-images.githubusercontent.com/12178974/150292608-109b0ad0-4d52-48b9-9d78-a920fc572300.png)

请教下有什么方法可以规避这个问题吗？

**Comment by nihui** [comment]
fp16 无法表示 > 65535 这样的大数，设置 ```opt.use_fp16_storage = false;``` 改用 fp32 运算应该ok，但效率会下降

**Comment by tpoisonooo** [comment]
或者“既要...也要...”手动调一下 param/实现，只有 reduction/出问题的 layer 计算过程用 fp32。 别的保持 fp16。

**Comment by dingqunfei** [comment]
可不可以用BF16呀

**Comment by zhanglaplace** [comment]
好的，我先试试，我现在尝试把param修改下，转化为 vars = sum((x-mean)^2/ (n-1)),这样子可能可以规避这个问题

**Comment by nihui** [comment]
我觉得，pnnx 可以支持下 torch.std，这样转到 ncnn 依然是一个op，不会像onnx拆开来，这样ncnn实现个 fp32 累加器的 var 实现就好了

**Comment by zhanglaplace** [comment]
> 

嗯， 可以的，目前确实一个std(var)会在ncnn有十多个binaryOp的出现。 目前通过去掉fp16暂时规避了这个问题。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
