### ISSUE TITLE
Question about Android memory usage

### ISSUE THREAD

**Issue by zkfzle** [Tencent/ncnn#352]
I wrote a command-line program for Android armv8, and it does nothing but init model and parms. 
The loaded model is converted from Caffe-ssd, and its file size is about 19MB. After model loaded, I found its PSS memory size is over 130MB. Is it reasonable?

**Comment by zkfzle** [comment]
#include <stdio.h>
#ifdef _WIN32
#include <windows.h> // Sleep()
#else
#include <unistd.h> // sleep()
#endif

#include "net.h"
void ztjc_init(ncnn::Net& net)
{
    net.load_param_bin("model.param.bin");
    net.load_model("model.bin"); // about 19MB
    printf("load model finished!\n");
}

int main(int argc, char** argv)
{
    ncnn::Net net;

    ztjc_init(net);

    getchar();
    
    return 0;
}

**Comment by zkfzle** [comment]
@nihui 大神求助

**Comment by zkfzle** [comment]
我们定位发现，内存的异常上涨是卷积算子的在卷积算子的winograd3x3加速带来的。
在卷子算子的arm实现里(Convolution_arm.cpp)，对于3x3卷积核，当输入和输出的个数都大于等于16个的时候，会开启winograd3x3的neon加速，会申请额外的空间。对于我们的模型（linux上内存占用30MB），会带来100MB左右的额外内存上涨。
在arm上新增的3倍内存基本上封死了模型上Android商用的可能了。这是否是个问题？

**Comment by nihui** [comment]
@zkfzle 不用winograd速度会慢，还有就是3倍内存其实还好，im2col + sgemm 内存占用更多...

**Comment by zkfzle** [comment]
update:
重新测试了一下，在Kirin 970上关闭winograd3x3加速，编译成release，计算速度与打开winograd相差不大。速度变慢其实是CMakeList里没有打开-fPIC、-Ofast、-ffast-math造成的。
