### ISSUE TITLE
ios release package ncnn.framework  crash

### ISSUE THREAD

**Issue by Richard-zhang-iOS** [Tencent/ncnn#356]
在调用新版的 ncnn.framework（20180314）中 调用 ncnn::Mat::from_pixels_resize 方法传入数据后会引发crash，而旧版的ncnn.framwork（20170724） 没有这个问题，我查看源码也没发现有什么不同，初步确定的打包过程中导致的差异，能帮忙修正下吗？

**Comment by suntaiwu** [comment]
求问这个问题怎么解决的啊，遇到了同样的问题
