### ISSUE TITLE
win10下 wsl2 编译 用于hi3995av100（himix100.toolchain.cmake）

### ISSUE THREAD

**Issue by zrl4836** [Tencent/ncnn#3564]
## detail | 详细描述 | 詳細な説明
[ 69%] Building CXX object src/CMakeFiles/ncnn.dir/layer/arm/binaryop_arm_arm82.cpp.o
[ 69%] Building CXX object src/CMakeFiles/ncnn.dir/layer/unaryop.cpp.o
/tmp/ccp5ihYA.s: Assembler messages:
/tmp/ccp5ihYA.s:5491: Error: register number out of range 0 to 15 at operand 3 -- `fmla v1.4h,v0.4h,v21.h[0]'
src/CMakeFiles/ncnn.dir/build.make:2918: recipe for target 'src/CMakeFiles/ncnn.dir/layer/arm/rnn_arm_arm82.cpp.o' failed
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/arm/rnn_arm_arm82.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:86: recipe for target 'src/CMakeFiles/ncnn.dir/all' failed
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nihui** [comment]
看起来是编译器版本太低
尝试 ```cmake -DNCNN_ARM82=OFF ..```

**Comment by zrl4836** [comment]
> 看起来是编译器版本太低 尝试 `cmake -DNCNN_ARM82=OFF ..`
加上  -DNCNN_ARM82=OFF  或者 换了高版本的编译器  都通过了，谢谢。
请问，你是如何看出 是我的编译器版本太低导致？不好意思，我懂的太少了。
