### ISSUE TITLE
Slowdown in performance when running parallel inference.

### ISSUE THREAD

**Issue by cyrusbehr** [Tencent/ncnn#3570]
I am trying to run inference in parallel on my 16 thread CPU in order to increase throughput, with each application thread having it's own `ncnn::Extractor`. I restrict each `ncnn::Extractor` to use only 4 threads for inference.

When I use only a single application thread to run inference (remember, each `ncnn::Extractor` still uses 4 threads), then I am able to process 100 inference requests in 7554ms.

When I now use 3 application threads to run inference in parallel (each `ncnn::Extractor` still uses 4 threads, so 12 threads used total), then I am able to process 300 images in 15820ms. Running `htop` confirms that I am indeed utilizing %1200 CPU. 

![image](https://user-images.githubusercontent.com/17056751/154775362-09266368-c37c-4408-8f70-941c7b4b1790.png)

Why the slowdown? 

I'd expect the total inference time to remain the same since we have tripled the number of images that we sample, but also tripled the concurrency (and we are not exceeding the number of machine threads so there should be minimal time slicing).

**Comment by cyrusbehr** [comment]
Looks like someone else had the [same issue](https://github.com/Tencent/ncnn/issues/869#issue-425688430) but it was never resolved.

**Comment by cyrusbehr** [comment]
@nihui any updates on this issue, it seems pretty important.

**Comment by cyrusbehr** [comment]
This issue has yet to be solved, but I am no longer using ncnn, so I shall therefore close this ticket.

**Comment by NayamAmarshe** [comment]
Any ideas why this is happening?

**Comment by TGS963** [comment]
We have been facing the same issue. Any insight on this as to why this might be happening???
