### ISSUE TITLE
双层LSTM问题

### ISSUE THREAD

**Issue by wzyforgit** [Tencent/ncnn#3571]
## detail | 详细描述 | 詳細な説明
RT，最近遇到个双层LSTM的模型，然后下面交错得跟蜘蛛网一样。。。有大佬知道怎么搞嘛？
网上能搜到的教程都是针对单层LSTM的 orz

ONNX模型，已经过onnxsim处理：
![截图_选择区域_20220220113912](https://user-images.githubusercontent.com/15171004/154827575-afff8150-83b5-42ee-9735-b7eeab3ffe45.png)

转出来的NCNN模型，惨不忍睹：
![截图_选择区域_20220220114003](https://user-images.githubusercontent.com/15171004/154827584-35c2773f-75ed-4df8-98db-02a03450dd5d.png)

**Comment by wzyforgit** [comment]
代码里面也没啥骚操作，就是一个简单的 nn.LSTM(层数=2，方向=双向) 这样

**Comment by nihui** [comment]
试试用 pnnx 转换，支持 n 层LSTM，不会有onnx那么多胶水op

**Comment by wzyforgit** [comment]
> 试试用 pnnx 转换，支持 n 层LSTM，不会有onnx那么多胶水op

非常感谢推荐，捣鼓了三个小时终于成功了～
（虽然精度差了点不过还在可接受范围内，希望隔壁搞算法的别再出这种阴间玩意儿了orz

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
