### ISSUE TITLE
insightface models

### ISSUE THREAD

**Issue by sunnyregion** [Tencent/ncnn#3574]
## detail | 详细描述 | 詳細な説明
谁能给一个靠谱的insightface gender-age的mxnet的原始模型，目前的onnx转换以后不正确

要是能够给一个靠谱的源码就更好了。

我原来的mxnet程序运算的结果很准。

换成ncnn 各种不准

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
