### ISSUE TITLE
在VS2017项目中使用ncnn，编译时出现LNK2001	无法解析的外部符号 "bool __cdecl glslang::InitializeProcess(void)"

### ISSUE THREAD

**Issue by HQLii** [Tencent/ncnn#3576]
## detail | 详细描述 | 詳細な説明
确认包含目录和附加依赖项都设置无误了
![image](https://user-images.githubusercontent.com/34810301/155473649-3fc8d813-52f1-4219-8337-766b81c8f260.png)

**Comment by ncnnnnn** [comment]
建议下载编译好的，用find pack

**Comment by zchrissirhcz** [comment]
既然要手动链接各种依赖库，就应该知晓正确的链接顺序。

![图片](https://user-images.githubusercontent.com/3831847/158217075-4dd47ca5-8d28-4953-8733-138712ec49d2.png)

https://github.com/Tencent/ncnn/wiki/use-ncnn-with-own-project

**Comment by sdnusqy-art** [comment]
> ## detail | 详细描述 | 詳細な説明
> 确认包含目录和附加依赖项都设置无误了 ![image](https://user-images.githubusercontent.com/34810301/155473649-3fc8d813-52f1-4219-8337-766b81c8f260.png)

遇到了同样问题， 请问解决了吗？

**Comment by sdnusqy-art** [comment]
> > ## detail | 详细描述 | 詳細な説明
> > 确认包含目录和附加依赖项都设置无误了 ![image](https://user-images.githubusercontent.com/34810301/155473649-3fc8d813-52f1-4219-8337-766b81c8f260.png)
> 
> 遇到了同样问题， 请问解

解决了， 是依赖项顺序问题， 如下正常

![image](https://user-images.githubusercontent.com/73977336/159401751-84b1fc02-de8d-462b-a001-ea3f94dbefb9.png)
