### ISSUE TITLE
Using NCNN in linux server - without GPU

### ISSUE THREAD

**Issue by UMUTBAYGUT** [Tencent/ncnn#3578]
## detail | 详细描述 | 詳細な説明

Hello everybody , 

I wonder that , is it good thing using ncnn on the linux server without GPU ?
Need I install vulkan on linux , when I use the ncnn  (without GPU)?

**Comment by nihui** [comment]
You can build cpu-only ncnn library on your server. It would be fine

**Comment by UMUTBAYGUT** [comment]
@nihui  thanks for reply.
I looked the wiki pages but I can not see anything about cpu-only build. 

-DNCNN_RUNTIME_CPU=ON
-DCMAKE_BUILD_TYPE=Release 
-DNCNN_VULKAN=OFF
Are those parameters are enough for build cpu-only?
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux

**Comment by nihui** [comment]
> @nihui thanks for reply. I looked the wiki pages but I can not see anything about cpu-only build.
> 
> -DNCNN_RUNTIME_CPU=ON -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=OFF Are those parameters are enough for build cpu-only? https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux

yeah, that's it.

**Comment by UMUTBAYGUT** [comment]
> > @nihui thanks for reply. I looked the wiki pages but I can not see anything about cpu-only build.
> > -DNCNN_RUNTIME_CPU=ON -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=OFF Are those parameters are enough for build cpu-only? https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux
> 
> yeah, that's it.

@nihui 
`cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=OFF -DNCNN_RUNTIME_CPU=ON  -DNCNN_SHARED_LIB=ON ..`

`make -j$(nproc)`

I used these command and created so files. but I saw the layer/x86 folder with same dir . 
I wonder that did build for the x86 architecture ? My computer is x64  .

so file size is about 7.8 mb. 

Is everyting  okay ?

**Comment by nihui** [comment]
> > > @nihui thanks for reply. I looked the wiki pages but I can not see anything about cpu-only build.
> > > -DNCNN_RUNTIME_CPU=ON -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=OFF Are those parameters are enough for build cpu-only? https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux
> > 
> > 
> > yeah, that's it.
> 
> @nihui `cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=OFF -DNCNN_RUNTIME_CPU=ON -DNCNN_SHARED_LIB=ON ..`
> 
> `make -j$(nproc)`
> 
> I used these command and created so files. but I saw the layer/x86 folder with same dir . I wonder that did build for the x86 architecture ? My computer is x64 .
> 
> so file size is about 7.8 mb.
> 
> Is everyting okay ?

yeah

**Comment by UMUTBAYGUT** [comment]
Is it possible build x64 ? And is there any difference (performance) between the two(for x64  and x86)?

**Comment by UMUTBAYGUT** [comment]
I need include net.h to my source code. 
But net.h depends to blob.h depends to mat.h depends to allocator.h . 
In the allocator.h there is  :

#if NCNN_VULKAN
#include <vulkan/vulkan.h>
#endif // NCNN_VULKAN

And in this step , I got a error.

/ncnn/include/ncnn/allocator.h:28:10: fatal error: vulkan/vulkan.h: No such file or directory
   28 | #include <vulkan/vulkan.h>
   
I build ncnn with    :

cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=OFF -DNCNN_RUNTIME_CPU=ON -DNCNN_SHARED_LIB=ON ..

**Comment by nihui** [comment]
make install
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-own-project

**Comment by UMUTBAYGUT** [comment]
> https://github.com/Tencent/ncnn/wiki/use-ncnn-with-own-project

I already using ncnn in my CMakeLists.txt as your gave link .
```

find_library(ncnn NAMES libncnn.so PATHS ${CMAKE_CURRENT_SOURCE_DIR}/ncnn/lib)

set (DIR ${CMAKE_CURRENT_SOURCE_DIR}/ncnn/)	

include_directories(
        ${DIR}/include   
        base
        "."
    )
    
    target_link_libraries(Engine  ${ncnn} 
    )
```

Note that , I did not install vulkan sdk . Need I install vulkan SDK ? I build ncnn without Vulkan SDK.

**Comment by UMUTBAYGUT** [comment]
@nihui 
When I downloaded this : https://github.com/Tencent/ncnn/releases/download/20220216/ncnn-20220216-ubuntu-2004-shared.zip and using the libncnn.so , there is no problem . But I think this is build for the vulkan . Because of this , When I run my project , I got a message like this 

`[0 llvmpipe (LLVM 12.0.0, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  bugsbn1=0  bugbilz=155  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/0
[0 llvmpipe (LLVM 12.0.0, 256 bits)]  subgroup=8  basic=1  vote=1  ballot=1  shuffle=0
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
`

but still project works. 

when I downloaded the source code https://github.com/Tencent/ncnn/archive/refs/tags/20220216.zip  and create a build folder then run this command : 

`cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=OFF -DNCNN_RUNTIME_CPU=ON -DNCNN_SHARED_LIB=ON ..` 

`make -j$(nproc)`

After this command , I used the new libncnn.so files in my project , and I got a error. 
Error Message is : Segmentation fault (core dumped)

When I look with gdb , Output is : 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff46e34ee in ncnn::Net::load_param(ncnn::DataReader const&) ()
from /home/umutbaygut/product/cppProject/ncnn/lib/libncnn.so.1

**Comment by nihui** [comment]
The latest master branch supports compiling gpu functions without installing vulkan-sdk. You can give it a try.
If it doesn’t work, feel free to reopen the issue and post your findings.
