### ISSUE TITLE
batchnorm issues

### ISSUE THREAD

**Issue by liupengkd** [Tencent/ncnn#358]
在batchnorm里的参数mean_data和var_data为什么不是根据输入数据算出来的而是模型读取的，对数据的高斯化不应该是要数据本来的均值和方差吗？

**Comment by harhar539** [comment]
The runtime statistics are used in the training phase, while the accumulated values saved are used in the testing phase.

**Comment by liupengkd** [comment]
@harhar539 这样和测试时使用测试数据自身的均值和方差会不会对结果产生大的影响

**Comment by nihui** [comment]
do you mean instancenorm ...

**Comment by liupengkd** [comment]
@nihui yes

**Comment by nihui** [comment]
batchnorm inference 时候就是这样做的
https://arxiv.org/abs/1502.03167
