### ISSUE TITLE
mac 编译ncnn问题

### ISSUE THREAD

**Issue by haddis3** [Tencent/ncnn#3585]
## detail | 详细描述 | 詳細な説明
macos 版本13.15 protobuf 是通过brew安装的，编译命令是：
`cmake -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" 
    -DNCNN_VULKAN=OFF -DNCNN_BUILD_EXAMPLES=ON ..`
最主要的错误是：
![QQ图片20220301100305](https://user-images.githubusercontent.com/21120947/156090952-95c79a43-5820-4f05-a422-4b5073d08eb6.png)

**Comment by wzyforgit** [comment]
就是编不了ARM64架构的呗，装个交叉编译器把Protobuf也重新编了？
实际上这里有个误区，如果不需要模型转换工具，就没有必要装Protobuf；而如果需要模型转换工具，那么工具实际上也只需要编一个架构的就够用了；如果要一口气编译多平台的转换工具，那就多装几个架构的Protobuf
