### ISSUE TITLE
预测结果不稳定，偶见异常输出nan

### ISSUE THREAD

**Issue by HuYue233** [Tencent/ncnn#3601]
二分类图像分割问题，同一张测试图片，有时候可以正确预测，有时候部分区域无法正确预测，输出结果为nan。
模型使用deeplabv3+,https://github.com/bubbliiiing/deeplabv3-plus-pytorch
python代码进行预测无异常，pytorch to onnx to ncnn 后，VS2019以及安卓发生异常

正常时的结果：
![image](https://user-images.githubusercontent.com/92309842/157186030-87833841-a4d1-4a8c-b44a-f2725745c4db.png)
![Screenshot_20220308_152652_com tencent deeplabv3p](https://user-images.githubusercontent.com/92309842/157188260-79eb3215-8989-4c1c-8ee1-ba8b543c59a3.jpg)

异常时的结果：
![image](https://user-images.githubusercontent.com/92309842/157186256-4f540398-dbc2-48d6-9ed0-3df7f4055423.png)![Screenshot_20220308_152803_com tencent deeplabv3p](https://user-images.githubusercontent.com/92309842/157187974-7b54b4e6-5f2b-405a-9d38-7c4b0ebb7ad4.jpg)

**Comment by nihui** [comment]
是最新版本的 ncnn 吗？

**Comment by HuYue233** [comment]
> 是最新版本的 ncnn 吗？

应该是的吧[20220216](https://github.com/Tencent/ncnn/releases/tag/20220216)

**Comment by HuYue233** [comment]
> 是最新版本的 ncnn 吗？

大佬，目前我这个是什么原因呢？有什么解决方案吗？

**Comment by nihui** [comment]
请提供下模型的 param 文件，以便复现问题

**Comment by HuYue233** [comment]
> 请提供下模型的 param 文件，以便复现问题
[param_and_bin.zip](https://github.com/Tencent/ncnn/files/8213002/param_and_bin.zip)

**Comment by HuYue233** [comment]
工程已上传至https://github.com/HuYue233/deeplabv3plus_ncnn.git
帮忙看一下是什么原因

**Comment by HuYue233** [comment]
@nihui 你好，我还是使用了之前同样的deeplabv3plus模型，但是从二分类问题改成了三分类问题。但是现在ncnn的预测结果与pytorch的预测结果完全不同，之前出现的nan异常输出结果也时有发生，请问我这个是因为模型转换出了问题吗？
[model.zip](https://github.com/Tencent/ncnn/files/8308844/model.zip)



![结果对比](https://user-images.githubusercontent.com/92309842/159113985-f025d011-3ed5-45bb-8964-7c1ffc942a82.png)
左一：NCNN
中间：原图
右一：pytorch

**Comment by HuYue233** [comment]
> @nihui 你好，我还是使用了之前同样的deeplabv3plus模型，但是从二分类问题改成了三分类问题。但是现在ncnn的预测结果与pytorch的预测结果完全不同，之前出现的nan异常输出结果也时有发生，请问我这个是因为模型转换出了问题吗？ [model.zip](https://github.com/Tencent/ncnn/files/8308844/model.zip)
> 
> ![结果对比](https://user-images.githubusercontent.com/92309842/159113985-f025d011-3ed5-45bb-8964-7c1ffc942a82.png) 左一：NCNN 中间：原图 右一：pytorch

好吧，还是归一化的问题。。。。代码检查不到位

**Comment by nihui** [comment]
后续如有其他问题，可以reopen继续交流

**Comment by 121649982** [comment]
你好，你的问题解决了吗？我也有这个问题，有时输出nan,有时部分区域无法预测

**Comment by 121649982** [comment]
![1](https://user-images.githubusercontent.com/5317102/186042462-35a28dc2-d839-4818-9157-dc57c043d931.jpg)

**Comment by zhahoi** [comment]
我的天，我也遇到了这个问题，使用模型使用deeplabv3+,https://github.com/bubbliiiing/deeplabv3-plus-pytorch用来做数字仪表识别，结果时常正确时常缺失，一直以为是我自己的后处理部分有问题，看来大家都遇到这种问题，真的不知道怎么解决，困扰我好几个星期了。 @HuYue233 请问你之后怎么解决的。

**Comment by HuYue233** [comment]
> 我的天，我也遇到了这个问题，使用模型使用deeplabv3+,[https://github.com/bubbliiiing/deeplabv3-plus-pytorch用来做数字仪表识别，结果时常正确时常缺失，一直以为是我自己的后处理部分有问题，看来大家都遇到这种问题，真的不知道怎么解决，困扰我好几个星期了。](https://github.com/bubbliiiing/deeplabv3-plus-pytorch%E7%94%A8%E6%9D%A5%E5%81%9A%E6%95%B0%E5%AD%97%E4%BB%AA%E8%A1%A8%E8%AF%86%E5%88%AB%EF%BC%8C%E7%BB%93%E6%9E%9C%E6%97%B6%E5%B8%B8%E6%AD%A3%E7%A1%AE%E6%97%B6%E5%B8%B8%E7%BC%BA%E5%A4%B1%EF%BC%8C%E4%B8%80%E7%9B%B4%E4%BB%A5%E4%B8%BA%E6%98%AF%E6%88%91%E8%87%AA%E5%B7%B1%E7%9A%84%E5%90%8E%E5%A4%84%E7%90%86%E9%83%A8%E5%88%86%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%8C%E7%9C%8B%E6%9D%A5%E5%A4%A7%E5%AE%B6%E9%83%BD%E9%81%87%E5%88%B0%E8%BF%99%E7%A7%8D%E9%97%AE%E9%A2%98%EF%BC%8C%E7%9C%9F%E7%9A%84%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%9B%B0%E6%89%B0%E6%88%91%E5%A5%BD%E5%87%A0%E4%B8%AA%E6%98%9F%E6%9C%9F%E4%BA%86%E3%80%82) @HuYue233 请问你之后怎么解决的。

我觉得你可以先检查一下ncnn是不是最新版，然后检查归一化操作是否和训练的时候相同。下图中是ncnn的代码，需要将mean_vals, norm_vals配置正确。此外还可以看看是不是只有GPU才会出现这种情况。
![image](https://github.com/Tencent/ncnn/assets/92309842/1ecc2a56-057e-4247-b6b5-53301fc0350e)

**Comment by zhahoi** [comment]
> > 我的天，我也遇到了这个问题，使用模型使用deeplabv3+,[https://github.com/bubbliiiing/deeplabv3-plus-pytorch用来做数字仪表识别，结果时常正确时常缺失，一直以为是我自己的后处理部分有问题，看来大家都遇到这种问题，真的不知道怎么解决，困扰我好几个星期了。](https://github.com/bubbliiiing/deeplabv3-plus-pytorch%E7%94%A8%E6%9D%A5%E5%81%9A%E6%95%B0%E5%AD%97%E4%BB%AA%E8%A1%A8%E8%AF%86%E5%88%AB%EF%BC%8C%E7%BB%93%E6%9E%9C%E6%97%B6%E5%B8%B8%E6%AD%A3%E7%A1%AE%E6%97%B6%E5%B8%B8%E7%BC%BA%E5%A4%B1%EF%BC%8C%E4%B8%80%E7%9B%B4%E4%BB%A5%E4%B8%BA%E6%98%AF%E6%88%91%E8%87%AA%E5%B7%B1%E7%9A%84%E5%90%8E%E5%A4%84%E7%90%86%E9%83%A8%E5%88%86%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%8C%E7%9C%8B%E6%9D%A5%E5%A4%A7%E5%AE%B6%E9%83%BD%E9%81%87%E5%88%B0%E8%BF%99%E7%A7%8D%E9%97%AE%E9%A2%98%EF%BC%8C%E7%9C%9F%E7%9A%84%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%8C%E5%9B%B0%E6%89%B0%E6%88%91%E5%A5%BD%E5%87%A0%E4%B8%AA%E6%98%9F%E6%9C%9F%E4%BA%86%E3%80%82) @HuYue233 请问你之后怎么解决的。
> 
> 我觉得你可以先检查一下ncnn是不是最新版，然后检查归一化操作是否和训练的时候相同。下图中是ncnn的代码，需要将mean_vals, norm_vals配置正确。此外还可以看看是不是只有GPU才会出现这种情况。 ![image](https://private-user-images.githubusercontent.com/92309842/344885147-1ecc2a56-057e-4247-b6b5-53301fc0350e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTgzNzYsIm5iZiI6MTcxOTg5ODA3NiwicGF0aCI6Ii85MjMwOTg0Mi8zNDQ4ODUxNDctMWVjYzJhNTYtMDU3ZS00MjQ3LWI2YjUtNTMzMDFmYzAzNTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA1Mjc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYjg4YjE2MTQ1ZDM0MWI1NzMxOGNkNTI2MWY3OWMyYjk0MTUxMGNhMjYyODc4MjU1NWViNGQ0NWJjMDQ2YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXRCN_FOB30i7g4TNvhUi997ml8ptwt0VzhJAzfmJ_8)

老哥，我看了bubbliiiing的python预处理代码，只对其进行了1/255.0的归一化操作，我在改c++代码的时候也是按照这样处理的。同时我的环境没有gpu，我不太确信是否是不使用GPU导致的。今天我换了该博主写的Unet代码，转换成ncnn时候，没有出现任何问题了。

老实讲，这个DeepLabV3Plus转ncnn的处理折腾了我快大半个月，搜到你的issues时才发现并不是个例，我不太清楚到底是哪个地方没做对，还是转换成ncnn后支持不好。换模型解决的问题，咱就不折腾了。

最后感谢你的回复。祝好。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
