### ISSUE TITLE
deepin20.4 build failed

### ISSUE THREAD

**Issue by xukefang** [Tencent/ncnn#3608]
在deepin编译ncnn时，遇到问题

cmake info:
cmake -DCMAKE_BUILD_TYPE=Release -DNCNN_VULKAN=ON -DNCNN_SYSTEM_GLSLANG=ON -DNCNN_BUILD_EXAMPLES=ON ..

output:
-- NCNN_VERSION_STRING = 1.0.20220310
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX - Success
-- Performing Test NCNN_COMPILER_SUPPORT_X86_FMA
-- Performing Test NCNN_COMPILER_SUPPORT_X86_FMA - Success
-- Performing Test NCNN_COMPILER_SUPPORT_X86_XOP
-- Performing Test NCNN_COMPILER_SUPPORT_X86_XOP - Success
-- Performing Test NCNN_COMPILER_SUPPORT_X86_F16C
-- Performing Test NCNN_COMPILER_SUPPORT_X86_F16C - Success
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX2
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX2 - Success
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX512
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX512 - Success
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX_VNNI
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX_VNNI - Failed
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX512_VNNI
-- Performing Test NCNN_COMPILER_SUPPORT_X86_AVX512_VNNI - Success
CMake Warning at CMakeLists.txt:287 (message):
  The compiler does not support avx vnni extension.  NCNN_AVXVNNI will be
  OFF.

-- Target arch: x86
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- OpenCV library: /usr
--     version: 3.2.0
--     libraries: opencv_core;opencv_highgui;opencv_imgproc;opencv_imgcodecs;opencv_videoio
--     include path: /usr/include;/usr/include/opencv
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-pthread (found version "3.6.1") 
-- Configuring done
-- Generating done

build err:
/tmp/ccoLh6AD.s:10900: 错误：unsupported instruction `vmovdqu'
make[2]: *** [src/CMakeFiles/ncnn.dir/build.make:2075：src/CMakeFiles/ncnn.dir/layer/x86/innerproduct_x86_avx512.cpp.o] 错误 1
/tmp/cc47TXf8.s: Assembler messages:
/tmp/cc47TXf8.s:12614: 错误：unsupported instruction `vmovdqu'
/tmp/cc47TXf8.s:13231: 错误：unsupported instruction `vmovdqu'
make[2]: *** [src/CMakeFiles/ncnn.dir/build.make:4155：src/CMakeFiles/ncnn.dir/layer/x86/requantize_x86_avx512.cpp.o] 错误 1
/tmp/ccGWXG4j.s: Assembler messages:
/tmp/ccGWXG4j.s:6364: 错误：unsupported instruction `vmovdqu'
make[2]: *** [src/CMakeFiles/ncnn.dir/build.make:1620：src/CMakeFiles/ncnn.dir/layer/x86/convolution_x86_avx512vnni.cpp.o] 错误 1
/tmp/ccG7oNRs.s: Assembler messages:

有什么办法可以解决这个问题吗？

**Comment by wzyforgit** [comment]
这个是因为Deepin自带的gcc版本太低了，8.3.0，导致不支持这个AVX指令
我自己是直接在cmake里面把那段代码全删了，反正我自己这边的项目不缺那个速度

**Comment by wzyforgit** [comment]
刚刚用deepin V20基于的debian 10也复现出来了，都是gcc 8.3.0
然后切到debian 11，gcc是10.2.1，就直接编过了

**Comment by wzyforgit** [comment]
老哥 or 老姐，可以试一下这个提交 #3671 
我刚刚在DeepinV20上编过了，gcc8.3.0
