### ISSUE TITLE
qq群满了，还有新的码

### ISSUE THREAD

**Issue by Dandelion111** [Tencent/ncnn#3609]

**Comment by cmdbug** [comment]
没有喽

**Comment by Yoh-Z** [comment]
@Dandelion111 @cmdbug ncnn群下面的MLIR群就是二群，入群暗号也有

**Comment by cmdbug** [comment]
技术交流QQ群：637093648(超多大佬) 答案：卷卷卷卷卷
Pocky群（MLIR YES!）: 677104663(超多大佬) 答案：multi-level intermediate representation
Telegram Group https://t.me/ncnnyes
Discord Channel https://discord.gg/YRsxgmF

**Comment by ncnnnnn** [comment]
pr个大群已满，请加二群
