### ISSUE TITLE
ubuntu上编译android_armv7报错

### ISSUE THREAD

**Issue by junxigauss** [Tencent/ncnn#361]
ubuntu上在ncnn root下运行如下命令
export ANDROID_NDK=/home/junxi/Project/ncnn/android-ndk-r16b
mkdir -p build-android-armv7
pushd build-android-armv7
cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-14 ..
make
make install
popd

提示
-- Configuring done
-- Generating done
-- Build files have been written to: /home/junxi/Project/ncnn

但实际上这个路径里面没有任何东西，请问是什么情况

**Comment by nihui** [comment]
build-android-armv7 目录里有东西
