### ISSUE TITLE
net.load_param_bin("/ncnn/test/openpose.param.bin"); signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by zark19890929** [Tencent/ncnn#362]
用的ncnn的工具把模型转出来了bin数据，然后代码编译，但是运行的时候，出现了这种错误，很是奇怪呀，求助各路大神。

**Comment by zark19890929** [comment]
好吧，自己来回答一下，主要是：
要用.param和.bin文件，不要用.parma.bin文件，.param.bin文件生成的时候才只有10K左右.load会出现这样的错误.

**Comment by sosopop** [comment]
你的openpose加载起来，跑的怎么样

**Comment by xiakj** [comment]
@sosopop 是呀，搞的咋样了，最近我也想把Openpose搞ncnn上来

**Comment by sosopop** [comment]
@xiakj 大概一秒两帧吧

**Comment by weilanShi** [comment]
> 用的ncnn的工具把模型转出来了bin数据，然后代码编译，但是运行的时候，出现了这种错误，很是奇怪呀，求助各路大神。

ncnn  下怎么加载 openpose 的两个输出啊，可以交流下嘛

**Comment by sosopop** [comment]
参考github上opencv的demo
