### ISSUE TITLE
ncnn::Mat::from_pixels_resize读取图片问题

### ISSUE THREAD

**Issue by iChiaGuo** [Tencent/ncnn#363]
UIImage* image = [UIImage imageNamed:@"test.jpg"];
    // get rgba pixels from image
    int w = image.size.width;
    int h = image.size.height;
    fprintf(stderr, "%d x %d\n", w, h);
    unsigned char* rgba = new unsigned char[w*h*4];
    {
        CGColorSpaceRef colorSpace = CGImageGetColorSpace(image.CGImage);
        CGContextRef contextRef = CGBitmapContextCreate(rgba, w, h, 8, w*4,
                                                        colorSpace,
                                                        kCGImageAlphaNoneSkipLast | kCGBitmapByteOrderDefault);
        
        CGContextDrawImage(contextRef, CGRectMake(0, 0, w, h), image.CGImage);
        CGContextRelease(contextRef);
    }
    
    //NSString *paramPath = [[NSBundle mainBundle] pathForResource:@"squeezenet_v1.1" ofType:@"param"];
    //NSString *binPath = [[NSBundle mainBundle] pathForResource:@"squeezenet_v1.1" ofType:@"bin"];
    NSString *paramPath = [[NSBundle mainBundle] pathForResource:@"demo" ofType:@"param"];
    NSString *binPath = [[NSBundle mainBundle] pathForResource:@"demo" ofType:@"bin"];
    // init net
    ncnn::Net net;
    {
        int r0 = net.load_param([paramPath UTF8String]);
        int r1 = net.load_model([binPath UTF8String]);
        fprintf(stderr, "net load %d %d\n", r0, r1);
    }
    
    std::vector<std::string> labels;
    NSString *labelPath = [[NSBundle mainBundle] pathForResource:@"synset_words" ofType:@"txt"];
    load_labels([labelPath UTF8String], labels);
    // run forward
    ncnn::Mat out;
    {
        ncnn::Extractor ex = net.create_extractor();
        ex.set_light_mode(true);
        ex.set_num_threads(2);
        
        ncnn::Mat in = ncnn::Mat::from_pixels_resize(rgba, ncnn::Mat::PIXEL_RGBA2RGB, w, h, 300, 300);
        const float mean_vals[3] = {104.f, 117.f, 123.f};
        const float norm_vals[3] = {1.0/127.5,1.0/127.5,1.0/127.5};
        in.substract_mean_normalize(mean_vals, norm_vals);
        
        ex.input("data", in);
        ex.extract("detection_out", out);
    }
![problem](https://user-images.githubusercontent.com/13581022/39083705-5a12047e-459b-11e8-91fe-09b98cd48b33.png
如图c的值为300了。大神帮忙解答一下 @nihui

**Comment by nihui** [comment]
ncnn库更新了，ncnn的头文件没更新？

**Comment by iChiaGuo** [comment]
确实
