### ISSUE TITLE
ncnn交叉编译出来的一直是x86

### ISSUE THREAD

**Issue by Dandelion111** [Tencent/ncnn#3631]
![image](https://user-images.githubusercontent.com/48303408/158721230-b67dce0c-948d-4441-8248-5d1ae1d85fe7.png)
请问各位大佬，我在x86上编译arm平台库，为啥我编译出来的一直是x86的呢，下面是我设置的环境
![image](https://user-images.githubusercontent.com/48303408/158721503-b3351ef0-e03e-4c59-b41e-1dc7ef8ac19f.png)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-arm-cortex-a-family-with-cross-compiling
