### ISSUE TITLE
ubuntu上编译报错求助

### ISSUE THREAD

**Issue by daixumo** [Tencent/ncnn#3633]
在ubuntu上编译时报错：
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/x86/unaryop_x86_avx.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/x86/unaryop_x86_fma.cpp.o] 错误 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by wzyforgit** [comment]
Ubuntu版本号没有，gcc版本号没有，ncnn commit ID 也没有
兄弟你是来搞笑的嘛？
