### ISSUE TITLE
Interp的dynamic_target_size如何使用？

### ISSUE THREAD

**Issue by 408550969** [Tencent/ncnn#3641]
Interp的时候我想让它的输出等于其他某一层的size（不是固定值，也不是固定的scale），我看interp.h中有dynamic_target_size这个参数，请问这个可以用吗，如何使用？

**Comment by nihui** [comment]
可以，Interp 接受第二个输入blob作为目标size

**Comment by 408550969** [comment]
我改成如下后会报错:
Interp           Upsample_66              2 1 390 387 403 0=1 5=1 6=0
387是我想要的目标size
