### ISSUE TITLE
请问为什么调用多次extract会出现访问冲突？

### ISSUE THREAD

**Issue by xiatutu** [Tencent/ncnn#3653]
bug：引发的异常: 0xC0000005: 读取位置 0x0000000000000000 时发生访问冲突

代码：
ncnn::Extractor ex = net.create_extractor();
ex.set_light_mode(true);
ncnn::Mat out;
ncnn::Mat fg_out;
ex.extract("res", out); 
ex.extract("fg_output", fg_out);

单次调用extract就可以正常运行，如：
ncnn::Mat out;
ex.extract("res", out); 
或者：
ncnn::Mat fg_out;
ex.extract("fg_output", fg_out);
求解答，谢谢 @nihui

**Comment by babyta** [comment]
你好，轻微一下这个问题是怎么解决的，我遇到了类似的问题，检测+识别任务，cpu版本没问题，vulkan版本这个地方报冲突错误

**Comment by babyta** [comment]
你好，请问一下这个问题是怎么解决的，我遇到了类似的问题，检测+识别任务，cpu版本没问题，vulkan版本这个地方报内存冲突错误

**Comment by ZiyueWangUoB** [comment]
@babyta 我自己从source build了一次，就没有这个问题了

**Comment by babyta** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
