### ISSUE TITLE
VisionFive的RVV编译问题

### ISSUE THREAD

**Issue by Janeqingss** [Tencent/ncnn#3660]
我在VisionFive上编译ncnn，在cmake时发现报错如下：
-- Performing Test NCNN_COMPILER_SUPPORT_RVV
-- Performing Test NCNN_COMPILER_SUPPORT_RVV - Failed
-- Performing Test NCNN_COMPILER_SUPPORT_RVV_FP16
-- Performing Test NCNN_COMPILER_SUPPORT_RVV_FP16 - Failed
CMake Warning at CMakeLists.txt:202 (message):
  The compiler does not support risc-v v extension.  NCNN_RVV will be OFF.

**Comment by Janeqingss** [comment]
我用的是Lubuntu镜像

**Comment by nihui** [comment]
这个信息没有问题
visionfive 本身不支持 rvv

**Comment by Janeqingss** [comment]
好的，谢谢您


| |
yunmuqun
|
|
***@***.***
|
在2022年4月6日 ***@***.***> 写道：

这个信息没有问题
visionfive 本身不支持 rvv
