### ISSUE TITLE
arm 32位与64位运行时间差异很大

### ISSUE THREAD

**Issue by niinorz** [Tencent/ncnn#3663]
环境: 高通的Trustzone QSEE,骁龙675平台,单核
同一个模型跑100次推理的平均时间
32位: 打开 sgemm 选项 100 ms,关闭 120ms
64位: 打开 sgemm 选项 785 ms,关闭 805ms

虽然675的主核是A76架构,但是给TZ用的大概率都是A55的小核.

不知道是否有优化方向

_Originally posted by @niinorz in https://github.com/Tencent/ncnn/issues/826#issuecomment-1085503248_

**Comment by niinorz** [comment]
由于编译环境不同,不能使用cmake,但是neon肯定是打开了的

**Comment by nihui** [comment]
64位慢那么多？
贴一下编译参数？

**Comment by niinorz** [comment]
`
"/home/algo/projects/qsee5.0/LLVM/4.0.11/bin/clang++" -cc1 -triple aarch64--linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name convolution.cpp -static-define -mrelocation-model pic -pic-level 2 -mthread-model posix -mllvm -enable-lsr-nested=true -fmath-errno -fno-signed-zeros -freciprocal-math -fno-trapping-math -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu cortex-a53 -target-feature +neon -target-feature +crc -target-feature +crypto -target-feature +strict-align -target-abi aapcs -mllvm -enable-quic -mllvm -enable-undefined-shift-warning -mllvm -inline-threshold-multicaller-size=0 -v -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -ffunction-sections -fdata-sections -coverage-notes-file /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/bsp/trustzone/qsapps/smplap64/build/QAOAANAA/A53_64/libs/ncnn_src_20220216/layer/convolution.gcno -nostdsysteminc -nobuiltininc -resource-dir /home/algo/projects/qsee5.0/LLVM/4.0.11/lib/clang/4.0.11 -D BUILD_LICENSE_ENVIRONMENT=NON_GPL_ENVIRONMENT -D NON_GPL_ENVIRONMENT=1 -D GPL_ENVIRONMENT=2 -D "CUST_H=\"custqaoaanaaa.h\"" -D "BUILD_TARGET=\"QAOAANAAA\"" -D "BUILD_VER=\"40000000\"" -D "BUILD_ASIC=\"7150\"" -D __ARM_NEON -D BUILD_QSEE -D __ARM_NEON -D NDEBUG -D BUILD_LICENSE_ENVIRONMENT=NON_GPL_ENVIRONMENT -D NON_GPL_ENVIRONMENT=1 -D GPL_ENVIRONMENT=2 -D "CUST_H=\"custqaoaanaaa.h\"" -D "BUILD_TARGET=\"QAOAANAAA\"" -D "BUILD_VER=\"40000000\"" -D "BUILD_ASIC=\"7150\"" -D USE_GNU_LD -D BUILD_QSEE -D __ARM_NEON -D NDEBUG -D ALGO_VERSION=libalgo_ver2.04_22_04_01 -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/sampleapp/build -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/build/cust -I . -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/ncnn_src_20220216 -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/ncnn_src_20220216/layer -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/ncnn_src_20220216/layer/arm -I /home/algo/projects/qsee5.0/LLVM/4.0.11/aarch64-none-elf/libc/include -I /home/algo/projects/qsee5.0/LLVM/4.0.11/aarch64-none-elf/include/c++/v1 -I /home/algo/projects/qsee5.0/LLVM/4.0.11/lib/clang/4.0.11/include -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/core/api/services -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/api/securemsm/trustzone/qsee -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsee/services/inc -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/core/api/kernel/libstd/stringl -I /inc -I /inc/gp -I /inc/qsee -I /inc/idl -I /inc/idl/private -I /inc/private -I /inc/util -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/core/api/kernel/libstd -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/api/securemsm/trustzone/gp -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/api/securemsm/trustzone/qsee -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/api/securemsm/util -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsee/include -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsee/mink/include -I /home/algo/projects/qsee5.0/LLVM/4.0.11/aarch64-none-elf/libc/include -Os -Wno-tautological-constant-out-of-range-compare -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-uninitialized -Wno-sign-compare -w -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /home/tz503/build/ms -ferror-limit 19 -fmessage-length 0 -fvisibility-inlines-hidden -fallow-half-arguments-and-returns -fno-rtti -fno-signed-char -fno-use-cxa-atexit -finline-hint-functions -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-slp -o /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/bsp/trustzone/qsapps/smplap64/build/QAOAANAA/A53_64/libs/ncnn_src_20220216/layer/convolution.o -x c++ /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/ncnn_src_20220216/layer/convolution.cpp
`
我用的platform.h 前面的宏定义如下：
`
#define NCNN_STDIO 0
#define NCNN_STRING 0
#define NCNN_SIMPLEOCV 0
#define NCNN_SIMPLEOMP 0
#define NCNN_SIMPLESTL 0
#define NCNN_THREADS 0
#define NCNN_BENCHMARK 0
#define NCNN_C_API 0
#define NCNN_PLATFORM_API 0
#define NCNN_PIXEL 1
#define NCNN_PIXEL_ROTATE 1
#define NCNN_PIXEL_AFFINE 1
#define NCNN_PIXEL_DRAWING 1
#define NCNN_VULKAN 0
#define NCNN_RUNTIME_CPU 0
#define NCNN_AVX 0
#define NCNN_XOP 0
#define NCNN_FMA 0
#define NCNN_AVX2 0
#define NCNN_AVXVNNI 0
#define NCNN_AVX512 0
#define NCNN_AVX512VNNI 0
#define NCNN_ARM82 1
#define NCNN_ARM82DOT 1
#define NCNN_MSA 0
#define NCNN_MMI 0
#define NCNN_RVV 0
#define NCNN_INT8 1
#define NCNN_BF16 1
#define NCNN_FORCE_INLINE 1

#define NCNN_VERSION_STRING "1.0.20220307"
...
`

**Comment by niinorz** [comment]
> 64位慢那么多？ 贴一下编译参数？

"/home/algo/projects/qsee5.0/LLVM/4.0.11/bin/clang++" -cc1 -triple aarch64--linux-gnu -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name convolution.cpp -static-define -mrelocation-model pic -pic-level 2 -mthread-model posix -mllvm -enable-lsr-nested=true -fmath-errno -fno-signed-zeros -freciprocal-math -fno-trapping-math -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu cortex-a53 -target-feature +neon -target-feature +crc -target-feature +crypto -target-feature +strict-align -target-abi aapcs -mllvm -enable-quic -mllvm -enable-undefined-shift-warning -mllvm -inline-threshold-multicaller-size=0 -v -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -ffunction-sections -fdata-sections -coverage-notes-file /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/bsp/trustzone/qsapps/smplap64/build/QAOAANAA/A53_64/libs/ncnn_src_20220216/layer/convolution.gcno -nostdsysteminc -nobuiltininc -resource-dir /home/algo/projects/qsee5.0/LLVM/4.0.11/lib/clang/4.0.11 -D BUILD_LICENSE_ENVIRONMENT=NON_GPL_ENVIRONMENT -D NON_GPL_ENVIRONMENT=1 -D GPL_ENVIRONMENT=2 -D "CUST_H=\"custqaoaanaaa.h\"" -D "BUILD_TARGET=\"QAOAANAAA\"" -D "BUILD_VER=\"40000000\"" -D "BUILD_ASIC=\"7150\"" -D __ARM_NEON -D BUILD_QSEE -D __ARM_NEON -D NDEBUG -D BUILD_LICENSE_ENVIRONMENT=NON_GPL_ENVIRONMENT -D NON_GPL_ENVIRONMENT=1 -D GPL_ENVIRONMENT=2 -D "CUST_H=\"custqaoaanaaa.h\"" -D "BUILD_TARGET=\"QAOAANAAA\"" -D "BUILD_VER=\"40000000\"" -D "BUILD_ASIC=\"7150\"" -D USE_GNU_LD -D BUILD_QSEE -D __ARM_NEON -D NDEBUG -D ALGO_VERSION=libalgo_ver2.04_22_04_01 -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/sampleapp/build -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/build/cust -I . -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/ncnn_src_20220216 -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/ncnn_src_20220216/layer -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/ncnn_src_20220216/layer/arm -I /home/algo/projects/qsee5.0/LLVM/4.0.11/aarch64-none-elf/libc/include -I /home/algo/projects/qsee5.0/LLVM/4.0.11/aarch64-none-elf/include/c++/v1 -I /home/algo/projects/qsee5.0/LLVM/4.0.11/lib/clang/4.0.11/include -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/core/api/services -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/api/securemsm/trustzone/qsee -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsee/services/inc -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/core/api/kernel/libstd/stringl -I /inc -I /inc/gp -I /inc/qsee -I /inc/idl -I /inc/idl/private -I /inc/private -I /inc/util -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/core/api/kernel/libstd -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/api/securemsm/trustzone/gp -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/api/securemsm/trustzone/qsee -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/api/securemsm/util -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsee/include -I /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsee/mink/include -I /home/algo/projects/qsee5.0/LLVM/4.0.11/aarch64-none-elf/libc/include -Os -Wno-tautological-constant-out-of-range-compare -Werror -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-uninitialized -Wno-sign-compare -w -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /home/tz503/build/ms -ferror-limit 19 -fmessage-length 0 -fvisibility-inlines-hidden -fallow-half-arguments-and-returns -fno-rtti -fno-signed-char -fno-use-cxa-atexit -finline-hint-functions -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-slp -o /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/bsp/trustzone/qsapps/smplap64/build/QAOAANAA/A53_64/libs/ncnn_src_20220216/layer/convolution.o -x c++ /home/algo/projects/qsee5.0/TZ.XF.5.0.3/trustzone_images/ssg/securemsm/trustzone/qsapps/libs/ncnn_src_20220216/layer/convolution.cpp
我用的platform.h 前面的宏定义如下：
`
#define NCNN_STDIO 0
#define NCNN_STRING 0
#define NCNN_SIMPLEOCV 0
#define NCNN_SIMPLEOMP 0
#define NCNN_SIMPLESTL 0
#define NCNN_THREADS 0
#define NCNN_BENCHMARK 0
#define NCNN_C_API 0
#define NCNN_PLATFORM_API 0
#define NCNN_PIXEL 1
#define NCNN_PIXEL_ROTATE 1
#define NCNN_PIXEL_AFFINE 1
#define NCNN_PIXEL_DRAWING 1
#define NCNN_VULKAN 0
#define NCNN_RUNTIME_CPU 0
#define NCNN_AVX 0
#define NCNN_XOP 0
#define NCNN_FMA 0
#define NCNN_AVX2 0
#define NCNN_AVXVNNI 0
#define NCNN_AVX512 0
#define NCNN_AVX512VNNI 0
#define NCNN_ARM82 1
#define NCNN_ARM82DOT 1
#define NCNN_MSA 0
#define NCNN_MMI 0
#define NCNN_RVV 0
#define NCNN_INT8 1
#define NCNN_BF16 1
#define NCNN_FORCE_INLINE 1

#define NCNN_VERSION_STRING "1.0.20220307"
...
`

**Comment by niinorz** [comment]
> 我尝试调整了一下 option use_bf16_storage 改为 true 可以将64位的速度提升一倍左右 但是同时 32位 的速度会慢一倍左右

但是这样结果似乎不对了

**Comment by niinorz** [comment]
convolution_1x1.h
conv1x1s1_neon 函数中
#ifdef __clang__ 这段代码的效率比 #else 中的代码效率低了50%左右
全是汇编，不敢乱改

**Comment by niinorz** [comment]
大概率与cache 命中相关，先close了

**Comment by niinorz** [comment]
我这边在 benchmark 里增加了一些日志和统计信息，分别在 sdm675 和 sdm865 的 qsee 环境下运行
sdm675结果：
sdm865结果：


Layer 6 是 Convolution，Layer 42 是 ConvolutionDepthWise
可以看到Layer 6 有很大提升，但是 Layer 42 的提升很少
使用的是同样的二进制文件（TA）和模型，能不能帮忙给点优化方向或者知识点的方向？



在 2022-04-01 16:00:20，"nihui" ***@***.***> 写道：

64位慢那么多？
贴一下编译参数？

**Comment by fanyongkang87** [comment]
@niinorz 能请教一下如果在QSEE 环境中编译 NCNN吗？
