### ISSUE TITLE
pytorch GRU模块转成ncnn后输出与原来不一致

### ISSUE THREAD

**Issue by hotelll** [Tencent/ncnn#3665]
## how to reproduce | 复现步骤 | 再現方法
1. 固定种子，pytorch创建一个简单的GRU模型，并且导出为onnx
```python
import torch
from torch import nn
torch.manual_seed(1)
class GRU_l1(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(GRU_l1, self).__init__()
        self.gru = nn.GRU(input_size, hidden_size)

    def forward(self, x_0, h_0):
        x_0, h_0 = self.gru(x_0, h_0)

        return x_0, h_0


model = GRU_l1(464, 512).eval()
x_0 = torch.zeros((1, 60, 464))
h_0 = torch.zeros((1, 60, 512))


torch.onnx.export(model,
                  (x_0, h_0),
                  "test.onnx",
                  export_params=True,
                  opset_version=10,
                  do_constant_folding=True,
                  input_names=["input.x", "input.h"],
                  output_names=["output.x", "output.h"])
```
2. 将该onnx转为ncnn
3. 用C++进行推断
```c++
ncnn::Net net;
net.load_param("files/test_gru.param");
net.load_model("files/test_gru.bin");
ncnn::Extractor ex = net.create_extractor();

// 置为全零矩阵
ncnn::Mat x(464, 60, 1);
ncnn::Mat h_0(512, 60, 1);


ex.input("input.x", x);
ex.input("input.h", h_0);

ncnn::Mat x_out;
ncnn::Mat h_out;
ex.extract("output.h", h_out);
ex.extract("output.x", x_out);
```
4. 比较 pytorch的GRU输出和C++下ncnn的GRU输出，结果不一样。而且每次在输出的某个固定位置开始就不一样了
这是pytorch输出
![image](https://user-images.githubusercontent.com/45009029/161248288-2c9628e0-51ab-499e-88b9-96eb8a5573d3.png)
这是ncnn输出
![image](https://user-images.githubusercontent.com/45009029/161247495-a4f7d881-fa79-4beb-afa0-8a7c01ef0e53.png)
可以看到，好像ncnn的输出，第一维是对的（也就是out[:, 0, :]是对的），后面就错了

**Comment by nihui** [comment]
试试用 pnnx 转换模型
https://github.com/Tencent/ncnn/tree/master/tools/pnnx

**Comment by hotelll** [comment]
> 试试用 pnnx 转换模型 https://github.com/Tencent/ncnn/tree/master/tools/pnnx

你好，我用pnnx试了，结果还是有错误，输出和原来一样

**Comment by nihui** [comment]
> > 试试用 pnnx 转换模型 https://github.com/Tencent/ncnn/tree/master/tools/pnnx
> 
> 你好，我用pnnx试了，结果还是有错误，输出和原来一样

看了下代码，原因是 ncnn 不支持 batch 维度，所以输入的 x h 只能是两维，seqlen 支持动态大小，这里是1

```cpp
ncnn::Mat x(464, 1);
ncnn::Mat h_0(512, 1);
```

**Comment by hotelll** [comment]
> > > 试试用 pnnx 转换模型 https://github.com/Tencent/ncnn/tree/master/tools/pnnx
> > 
> > 
> > 你好，我用pnnx试了，结果还是有错误，输出和原来一样
> 
> 看了下代码，原因是 ncnn 不支持 batch 维度，所以输入的 x h 只能是两维，seqlen 支持动态大小，这里是1
> 
> ```c++
> ncnn::Mat x(464, 1);
> ncnn::Mat h_0(512, 1);
> ```

原来如此，问题解决了，感谢！

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
