### ISSUE TITLE
Ubuntu上编译错误 /tmp/ccPSdrbU.s:6389: 错误： unsupported instruction `vmovdqu'

### ISSUE THREAD

**Issue by zhuheixin** [Tencent/ncnn#3669]
/tmp/ccPSdrbU.s: Assembler messages:
/tmp/ccPSdrbU.s:6389: 错误： unsupported instruction `vmovdqu'
make[2]: *** [src/CMakeFiles/ncnn.dir/build.make:1664：src/CMakeFiles/ncnn.dir/layer/x86/convolution_x86_avx512vnni.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
/tmp/ccNlepHJ.s: Assembler messages:
/tmp/ccNlepHJ.s:16164: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:16165: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:16167: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:16168: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:16171: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:16173: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:64045: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:70596: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:70599: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:70614: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:70621: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:82806: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:82807: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:82809: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:82810: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:82813: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:82815: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:90538: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:90541: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:90542: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:90545: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:90546: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:90550: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:94777: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:94779: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:94780: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:94781: 错误： unsupported instruction `vmovdqu'
/tmp/ccNlepHJ.s:94784: 错误： unsupported instruction `vmovdqu'
make[2]: *** [src/CMakeFiles/ncnn.dir/build.make:1622：src/CMakeFiles/ncnn.dir/layer/x86/convolution_x86_avx512.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:580：src/CMakeFiles/ncnn.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2
==========================================================
Ubuntu22.04编译错误
cmake指令：cmake -DCMAKE_BUILD_TYPE=Release  -DNCNN_VULKAN=ON -DNCNN_BUILD_EXAMPLES=ON ..
GUN版本：8.5.0
CPU：Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz

**Comment by nihui** [comment]
请测试下这个 pr 是否能解决问题
https://github.com/Tencent/ncnn/pull/3671

**Comment by wzyforgit** [comment]
> 请测试下这个 pr 是否能解决问题 #3671

我这边Deepin V20没问题了，gcc是8.3.0
