### ISSUE TITLE
安卓端跑相同模型，ncnn大版本更新导致推理结果错误

### ISSUE THREAD

**Issue by bestpower** [Tencent/ncnn#3681]
## 日志或报错信息

20211122（**错误部分推理输出结果日志**）：
```txt
crnn input size w = 271 h = 32
crnn out size = w(6625) h(68) c(1)
crnn_output_data_info print start
object[0][0][0] = 0.719948 
object[0][3312][0] = 0.000005 
object[0][6624][0] = 0.006919 
object[34][0][0] = 0.710995 
object[34][3312][0] = 0.000003 
object[34][6624][0] = 0.061837 
object[67][0][0] = 0.962402 
object[67][3312][0] = 0.000001 
object[67][6624][0] = 0.005614 
CRTextStr()
```

20210720（**正确部分推理输出结果日志**）:
```txt
crnn input size w = 271 h = 32
crnn out size = w(6625) h(68) c(1)
crnn_output_data_info print start
object[0][0][0] = 0.992786 
object[0][3312][0] = 0.000000 
object[0][6624][0] = 0.000029 
object[34][0][0] = 0.997965 
object[34][3312][0] = 0.000000 
object[34][6624][0] = 0.000639 
object[67][0][0] = 0.985671 
object[67][3312][0] = 0.000000 
object[67][6624][0] = 0.001203
CRTextStr(532101198906010015)
```

## 编译/运行环境

模型转换：
模型转换流：paddlepaddle->onnx->ncnn
模型转换环境：ubuntu18.04/python3.6.9/onnx==1.9.0/ncnn:be402bbf4d7b92ec92d1c11890832d123f31b037

测试应用：
错误输出ncnn-android版本：https://github.com/Tencent/ncnn/releases/tag/20211122
正确输出ncnn-android版本：https://github.com/Tencent/ncnn/releases/tag/20210720
编译环境：windows 10/android studio 2020.3.1/ndk21.1.6352462/cmake 3.10.2.4988404
编译配置参数：minSdkVersion 21/cppFlags "-DANDROID_ARM_NEON=ON -mfpu=neon"
运行环境：android 8.1/spreadtrum sc9832e/4 xARM Cortex-A53@1400MHz
测试素材：1x3x32x271尺寸图片/18个字符词条（详见附件
![271x32](https://user-images.githubusercontent.com/16058611/161952674-cf31117f-4fb6-4cf8-9b99-ef277562e011.png)
）

## 复现步骤
1.分别以ncnn-20211122和ncnn-20210720作为推理库对同一模型（详见附件
[model.zip](https://github.com/Tencent/ncnn/files/8426267/model.zip)
）编写推理app测试代码
2.jni部分关键代码如下：
```cpp
    //推理输入尺寸变换
    float scale = (float) dstHeight / (float) src.rows;
    int dstWidth = int((float) src.cols * scale);
    cv::Mat srcResize;
    cv::resize(src, srcResize, cv::Size(dstWidth, dstHeight));
    //推理输入对象构造
    ncnn::Mat input = ncnn::Mat::from_pixels(srcResize.data, ncnn::Mat::PIXEL_BGR2RGB, srcResize.cols, srcResize.rows);
    input.substract_mean_normalize(meanValues, normValues);
    //推理输出
    ncnn::Mat out;
    ncnn::Extractor extractor = net->create_extractor();
    extractor.input("x", input);
    extractor.extract("save_infer_model/scale_0.tmp_1", out);
    //打印推理输出
    LOGI("crnn out size = w(%d) h(%d) c(%d)", out.w, out.h, out.c);
    pretty_print(out, "crnn_output_data_info");
```
日志打印关键代码（只打印开头/中间/结尾部分）
```cpp
    LOGD("%s print start", objectName);
    for (int q=0; q<m.c; q++)
    {
        const float *ptr = m.channel(q);
        for (int y=0; y<m.h; y++)
        {
            for (int x=0; x<m.w; x++)
            {
                if((x==0 || x==m.w/2 || x==m.w-1) && (y==0 || y==m.h/2 || y==m.h-1)) {
                    LOGD("object[%d][%d][%d] = %f ", y, x, q, ptr[x]);
                }
            }
            ptr += m.w;
        }
    }
    LOGD("%s print end", objectName);
```
3.分别将以上不同版本编译出的测试应用在同一机器上运行测试，观察对应日志输出

## 其他
备注：测试模型为动态输入模型（1 x 3 x 32 x -1）/动态输出（1 x -1 x 6625）

目前的问题（现象）：相同输入、相同推理模型、相同推理代码，不同版本ncnn预编译库，推理结果存在明显差异，20210720版本推理输出经后处理结果（与实际情况一致）正确，20211122版本推理输出经后处理结果（为空）错误

确认是ncnn库在**20210720到20211122两个大版本之间更新出来的问题**，麻烦帮忙分析一下，盼复，不胜感激！

**Comment by bestpower** [comment]
另外使用最近的两个版本：
https://github.com/Tencent/ncnn/releases/tag/20211208
https://github.com/Tencent/ncnn/releases/tag/20220216
也是存在同样问题的

**Comment by nihui** [comment]
```
Squeeze          Squeeze_0                1 1 pool2d_9.tmp_0 squeeze_0.tmp_0 -23303=1,2
```

改成 

```
Squeeze          Squeeze_0                1 1 pool2d_9.tmp_0 squeeze_0.tmp_0 -23303=1,1
```

**Comment by bestpower** [comment]
> squeeze层有个不兼容的改变，之前 axis 是 nchw，没有去掉 n，最新的把 n 忽略了 用新版本工具重新转模型，或者
> 
> ```
> Squeeze          Squeeze_0                1 1 pool2d_9.tmp_0 squeeze_0.tmp_0 -23303=1,2
> ```
> 
> 改成
> 
> ```
> Squeeze          Squeeze_0                1 1 pool2d_9.tmp_0 squeeze_0.tmp_0 -23303=1,1
> ```

按这个方法修改模型在新版本ncnn库上可以推理出正确结果了，非常感谢！

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
