### ISSUE TITLE
RK3288 如何将多个模型绑定不同核心

### ISSUE THREAD

**Issue by SeaRecluse** [Tencent/ncnn#3683]
在设备上打印了下只有4个小核心，使用set_cpu_powersave功能只能设置全核/小核/大核，那请问如果将多个模型与不同的小核进行绑定呢？

**Comment by cmdbug** [comment]
- ## 大小核绑定
   ncnn::set_cpu_powersave(int)绑定大核或小核
   注意windows系统不支持绑核。
   ncnn支持不同的模型运行在不同的核心。假设硬件平台有2个大核，4个小核，你想把netA运行在大核，netB运行在小核。
   可以通过std::thread or pthread创建两个线程，运行如下代码：
   0:全部
   1:小核
   2:大核
```
   void thread_1()
   {
      ncnn::set_cpu_powersave(2); // bind to big cores
      netA.opt.num_threads = 2;
   }

   void thread_2()
   {
      ncnn::set_cpu_powersave(1); // bind to little cores
      netB.opt.num_threads = 4;
   }
```

可以大小核绑定，其它不懂qaq

**Comment by wzyforgit** [comment]
> * ## 大小核绑定
>   ncnn::set_cpu_powersave(int)绑定大核或小核
>   注意windows系统不支持绑核。
>   ncnn支持不同的模型运行在不同的核心。假设硬件平台有2个大核，4个小核，你想把netA运行在大核，netB运行在小核。
>   可以通过std::thread or pthread创建两个线程，运行如下代码：
>   0:全部
>   1:小核
>   2:大核
> 
> ```
>    void thread_1()
>    {
>       ncnn::set_cpu_powersave(2); // bind to big cores
>       netA.opt.num_threads = 2;
>    }
> 
>    void thread_2()
>    {
>       ncnn::set_cpu_powersave(1); // bind to little cores
>       netB.opt.num_threads = 4;
>    }
> ```
> 
> 可以大小核绑定，其它不懂qaq

感觉可以在此基础上先全部设置绑定小核，然后每个模型都少开点线程，最终总数等于小核的数量即可
但是就怕最后系统没调度的过来，冲突了（按理来说应该不会出现吧
