### ISSUE TITLE
MacOS X86 with Vulkan SDK 1.3.204.0 'tanh' shader compiler issue

### ISSUE THREAD

**Issue by DickyQi** [Tencent/ncnn#3698]
## error log | 日志或报错信息 | ログ
program_source:398:16: error: no matching function for call to 'tanh'
        v10 *= precise::tanh(log(exp(v10) + half4(half(1.0))));
               ^~~~~~~~~~~~~
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/lib/clang/31001.523/include/metal/metal_math:1724:18: note: candidate function not viable: no known conversion from 'metal::half4' (aka 'half4') to 'float' for 1st argument
METAL_FUNC float tanh(float x)
                 ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/lib/clang/31001.523/include/metal/metal_math:1968:19: note: candidate function not viable: no known conversion from 'metal::half4' (aka 'half4') to 'metal::float2' (aka 'float2') for 1st argument
METAL_FUNC float2 tanh(float2 x)
                  ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/lib/clang/31001.523/include/metal/metal_math:2212:19: note: candidate function not viable: no known conversion from 'metal::half4' (aka 'half4') to 'metal::float3' (aka 'float3') for 1st argument
METAL_FUNC float3 tanh(float3 x)
                  ^
/System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/31001/Libraries/lib/clang/31001.523/include/metal/metal_math:2456:19: note: candidate function not viable: no known conversion from 'metal::half4' (aka 'half4') to 'metal::float4' (aka 'float4') for 1st argument
METAL_FUNC float4 tanh(float4 x)

## context | 编译/运行环境 | バックグラウンド
MacOS 12.3.1 + Clang13 + vscode + VulkanSDK 1.3.204.0(1.2.198.1 also)
GPU 0: AMD Radeon Pro 5500M 8 GB
GPU 1: Intel(R) UHD Graphics 630

## how to reproduce | 复现步骤 | 再現方法
1. clone ncnn
2. open with vscode, enable NCNN_VULKAN, build
3. run benchncnn 0 16 0 0
4. runtime compile issue like log show(lots of same issue) 
## more | 其他 | その他
VulkanSDK 1.2.189.0 is working fine, but my project request newest Vulkan SDK

**Comment by nihui** [comment]
reproduced on macos arm

**Comment by nihui** [comment]
spirv-cross compiles tanh as precise float4 version since https://github.com/KhronosGroup/SPIRV-Cross/commit/40141ffddfe6a00fba0cce7e1b5f3759b8d520b8
have to workaround tanh/atan2 for half type ...

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/3711

**Comment by nihui** [comment]
fixed
