### ISSUE TITLE
ncnn2mem编译出错

### ISSUE THREAD

**Issue by noiplcx** [Tencent/ncnn#37]
/tools/../src/layer.h:22:22: fatal error: platform.h: 没有那个文件或目录
报的这个错
我想问下具体的编译流程

**Comment by nihui** [comment]
cmake的方式，这个文件是 cmake 过程中产生的
#25

**Comment by noiplcx** [comment]
还是不懂唉 我在主目录下cmake编译成功了 platform.h也产生了
但是现在我想编译 ncnn2mem和 caffe2ncnn
cd tools
mkdir build && cd build
cmake ..
make
我这样编译是可行么 报错platform.h找不到

**Comment by nihui** [comment]
主目录 build 成功，build/tools 里就有了

**Comment by noiplcx** [comment]
重新编译成功了 万分感谢
