### ISSUE TITLE
ubuntu build error 直接编译报错

### ISSUE THREAD

**Issue by varbegin** [Tencent/ncnn#370]
$ mkdir -p build
$ cd build
$ cmake ..
$ make -j4
[  1%] Building CXX object src/CMakeFiles/ncnn.dir/blob.cpp.o
[  2%] Building CXX object src/CMakeFiles/ncnn.dir/cpu.cpp.o
[  4%] Building CXX object src/CMakeFiles/ncnn.dir/layer.cpp.o
[  5%] Building CXX object src/CMakeFiles/ncnn.dir/mat.cpp.o
[  7%] Building CXX object src/CMakeFiles/ncnn.dir/mat_pixel.cpp.o
[  8%] Building CXX object src/CMakeFiles/ncnn.dir/modelbin.cpp.o
[ 10%] Building CXX object src/CMakeFiles/ncnn.dir/net.cpp.o
/....../ncnn-master/src/net.cpp: In member function ‘int ncnn::Net::load_param(FI
LE*)’:/....../ncnn-master/src/net.cpp:102:29: warning: ignoring return value of ‘int fs
canf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]     fscanf(fp, "%d", &magic);
                             ^
percentage and warnings......
......
Linking CXX executable mxnet2ncnn
[ 95%] Built target mxnet2ncnn
[ 97%] Running C++ protocol buffer compiler on onnx.proto
onnx.proto:383:5: Expected "required", "optional", or "repeated".
onnx.proto:383:17: Missing field number.
onnx.proto:402:3: Expected "required", "optional", or "repeated".
onnx.proto:402:15: Missing field number.
make[2]: *** [tools/onnx/onnx.pb.cc] Error 1
make[1]: *** [tools/onnx/CMakeFiles/onnx2ncnn.dir/all] Error 2
make: *** [all] Error 2

What's the matter and how to fix it?
怎么解决？

**Comment by nihui** [comment]
upgrade protobuf to 2.6.1 or higher
or you can disable onnx2ncnn tool by commenting it out in tools/CMakeLists.txt

**Comment by varbegin** [comment]
Thanks, nihui. I disabled onnx2ncnn tool and than it worked. 
Thank you.

**Comment by Note-Liu** [comment]
> Thanks, nihui. I disabled onnx2ncnn tool and than it worked.
> Thank you.

how did you do?

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
