### ISSUE TITLE
ncnn模型在第40个blob崩溃

### ISSUE THREAD

**Issue by yuan9778** [Tencent/ncnn#3703]
主要代码如下：
```
ncnn::Mat in = ncnn::Mat(229, 101, (void*)data_torch);
ex.input("input", in);
ncnn::Mat middleOut;
int middle_status = ex.extract("output", middleOut);
```
在android studio使用虚拟机Pixel 2 API 30运行时会闪退，查看logcat发现错误信息为：
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x31713174 in tid 29843 (mo.xxx), pid 29843 (mo.xxx)

后来逐个blob跑，发现：
`int middle_status = ex.extract(39, middleOut);` or 
`int middle_status = ex.extract("onnx::Add_411", middleOut);` 
可以正常运行，
但是：
`int middle_status = ex.extract(40, middleOut);` or 
`int middle_status = ex.extract("onnx::Sigmoid_412", middleOut);` 
就会闪退。

对应到param文件里是这一行出问题：
`BinaryOp  Add_68   2 1 note_model.reg_onset_model.fc.bias onnx::Add_411 onnx::Sigmoid_412 0=0`

求大佬帮忙看看，多谢！

param文件见附件
[param.txt](https://github.com/Tencent/ncnn/files/8488184/param.txt)

**Comment by yuan9778** [comment]
发现用ncnn-20220216-android-vulkan的库就不会崩溃，之前用的是ncnn-20220216-android

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4809

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/9022b7162a851f5deae0d2e6e5ee5e89a4813212

feel free to reopen issue if the error still persists

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
