### ISSUE TITLE
Fail to cross compile NCNN for Raspberry Pi (ARM Linux)

### ISSUE THREAD

**Issue by Graeme29** [Tencent/ncnn#3704]
## error log | 日志或报错信息 | ログ
```
In file included from ~/CrossCompil/ncnn/src/layer/arm/convolution_arm.cpp:33:
~/CrossCompil/ncnn/src/layer/arm/convolution_1x1.h: In function ‘_ZN4ncnnL14conv1x1s1_neonERKNS_3MatERS0_S2_S2_RKNS_6OptionE._omp_fn.0’:
~/CrossCompil/ncnn/src/layer/arm/convolution_1x1.h:908:104: error: ‘asm’ operand has impossible constraints
  908 |                     : "cc", "memory", "q6", "q7", "q8", "q9", "q10", "q11", "q12", "q13", "q14", "q15");
      |   
```

## context | 编译/运行环境 | バックグラウンド
On my Ubuntu computer, I want to cross compile NCNN for Raspberry Pi using CMake and the toolchain : /ncnn/toolchains/arm-linux-gnueabihf.toolchain.cmake
But it fails.

## how to reproduce | 复现步骤 | 再現方法
1. I'm following these steps : https://medium.com/trueface-ai/trueface-tutorials-how-to-cross-compile-popular-computer-vision-c-frameworks-for-raspberry-pi-4-afcbe2dcc302
2. I've downloaded NCNN, and I've updated my cross compiler.
3. I'm using these options to cross compile : 
> cmake -D NCNN_VULKAN=OFF -D CMAKE_BUILD_TYPE=Release -D NCNN_DISABLE_RTTI=OFF -D NCNN_ARM82DOT=OFF -D CMAKE_TOOLCHAIN_FILE=../ncnn/toolchains/arm-linux-gnueabihf.toolchain.cmake ../ncnn

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/715a248aabc5fd1ff4749c5ca1469989ab554957
