### ISSUE TITLE
qq群满员啦 咋搞啊

### ISSUE THREAD

**Issue by ljl86092297** [Tencent/ncnn#3716]

**Comment by cmdbug** [comment]
加Pocky群，算是2群:
技术交流QQ群：637093648(超多大佬) 答案：卷卷卷卷卷
Pocky群（MLIR YES!）: 677104663(超多大佬) 答案：multi-level intermediate representation
Telegram Group https://t.me/ncnnyes
Discord Channel https://discord.gg/YRsxgmF
