### ISSUE TITLE
yolov5模型未扫到目标时速度很快，一扫到目标马上变慢

### ISSUE THREAD

**Issue by caoailin** [Tencent/ncnn#3719]
## detail | 详细描述 | 詳細な説明
手机：K40,天玑1200
模型:   yolov5s，自训练
release模式 未扫到目标时帧率在12左右，一扫到目标马上变成4帧左右。

相同代码使用 
https://github.com/cmdbug/YOLOv5_NCNN/tree/master/android_YOLOV5_NCNN
的例子和里面的ncnn库，debug模式并不会存在这种情况，但release模式较慢

**Comment by caoailin** [comment]
应该是OMP 问题，注释掉OMP排序方法 就正常了。

**Comment by MoonSheepJx** [comment]
> 

您好，您的问题跟我很类似，我们在pytorch上训练了一个yolov5模型，转到onnx后转成ncnn下，但是检测速度很慢，一般是0.25-0.3秒一张图片，而转换之前的原模型检测速度基本上为0.01s左右，希望您能给些指点，麻烦了！

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
