### ISSUE TITLE
请问关于arm指令PLD的问题

### ISSUE THREAD

**Issue by Arthur77Wang** [Tencent/ncnn#372]
请问nihui大神，注意到在arm/conv3x3的代码里汇编部分多次用到PLD预取命令，请问其中的第二个入参到底是内存地址的偏移量还是预读的长度呢？如果只是偏移量，那么每次PLD就读取一个cache块吗？这条指令是怎么发挥作用，用在什么时间节点呢？

**Comment by nihui** [comment]
文档上写的是偏移量，不过个人经验是写预读长度，然后直接写在 load 前面...
```
pld [r0, #256]
vld1.f32 {d0-d3}, [r0]!
```
