### ISSUE TITLE
int8模型效果异常

### ISSUE THREAD

**Issue by 408550969** [Tencent/ncnn#3720]
你好，我把retinaface转换int8后，预测结果全为0，fp16无此问题
我用的widerface val数据集生成的table，生成table的指令如下
ncnn2table mobile_pretrain-fp16.param mobile_pretrain-fp16.bin imagelist.txt mobilenet.table mean=[104,117,123] norm=[0,0,0] shape=[320,320,3] pixel=BGR thread=8 method=kl
我看到在生成table的时候，Conv_0如下：
Conv_0                                   : max = 0.000000         threshold = 0.000000         scale = inf

scale为inf，这个值是否异常？

**Comment by nihui** [comment]
norm 参数有问题
预处理```x = (x - mean) * norm```

**Comment by 408550969** [comment]
谢谢，我改成全1后，没有inf了，但是还是所有图都检测不到人脸，这有可能是什么导致的？
这些是转换时的参数
Conv_0                                   : max = 151.000000       threshold = 117.120850       scale = 1.084350
Conv_2                                   : max = 3.940551         threshold = 0.262639         scale = 483.553009
Conv_4                                   : max = 8.518839         threshold = 2.131789         scale = 59.574364
Conv_6                                   : max = 9.688678         threshold = 1.289143         scale = 98.515060
Conv_8                                   : max = 6.418069         threshold = 0.750551         scale = 169.209122
Conv_10                                  : max = 5.579101         threshold = 0.622473         scale = 204.024933
Conv_12                                  : max = 8.099633         threshold = 1.164718         scale = 109.039291
Conv_14                                  : max = 6.763477         threshold = 0.840481         scale = 151.103973
Conv_16                                  : max = 3.425431         threshold = 1.208435         scale = 105.094643
Conv_18                                  : max = 2.003026         threshold = 0.626435         scale = 202.734650
Conv_20                                  : max = 2.683761         threshold = 1.007066         scale = 126.108940
Conv_22                                  : max = 1.887072         threshold = 0.724698         scale = 175.245331
Conv_24                                  : max = 2.923278         threshold = 1.064113         scale = 119.348213
Conv_26                                  : max = 1.370350         threshold = 0.672796         scale = 188.764389
Conv_28                                  : max = 3.061398         threshold = 0.972382         scale = 130.607056
Conv_30                                  : max = 1.196027         threshold = 0.620497         scale = 204.674561
Conv_32                                  : max = 2.147865         threshold = 0.928679         scale = 136.753418
Conv_34                                  : max = 1.052471         threshold = 0.649315         scale = 195.590668
Conv_36                                  : max = 1.925781         threshold = 1.110051         scale = 114.409164
Conv_38                                  : max = 1.169545         threshold = 0.550223         scale = 230.815430
Conv_40                                  : max = 2.488311         threshold = 0.989614         scale = 128.332886
Conv_42                                  : max = 1.630295         threshold = 0.691363         scale = 183.695114
Conv_44                                  : max = 2.788483         threshold = 1.192049         scale = 106.539223
Conv_46                                  : max = 1.251948         threshold = 0.843292         scale = 150.600250
Conv_48                                  : max = 4.029271         threshold = 1.254229         scale = 101.257462
Conv_50                                  : max = 0.925709         threshold = 0.798018         scale = 159.144379
Conv_52                                  : max = 2.641269         threshold = 1.393502         scale = 91.137306
Conv_54                                  : max = 1.887072         threshold = 0.724698         scale = 175.245331
Conv_56                                  : max = 1.251948         threshold = 0.843292         scale = 150.600250
Conv_58                                  : max = 9.039436         threshold = 7.730748         scale = 16.427906
Conv_68                                  : max = 4.163334         threshold = 3.202800         scale = 39.652809
Conv_78                                  : max = 4.862158         threshold = 2.104640         scale = 60.342861
Conv_80                                  : max = 4.094047         threshold = 1.894096         scale = 67.050446
Conv_81                                  : max = 4.094047         threshold = 1.894096         scale = 67.050446
Conv_83                                  : max = 3.397416         threshold = 2.069471         scale = 61.368343
Conv_84                                  : max = 3.397416         threshold = 2.069471         scale = 61.368343
Conv_86                                  : max = 2.958460         threshold = 1.854093         scale = 68.497093
Conv_89                                  : max = 2.448371         threshold = 2.175201         scale = 58.385418
Conv_90                                  : max = 2.448371         threshold = 2.175201         scale = 58.385418
Conv_92                                  : max = 2.788339         threshold = 2.311136         scale = 54.951344
Conv_93                                  : max = 2.788339         threshold = 2.311136         scale = 54.951344
Conv_95                                  : max = 2.489964         threshold = 2.184190         scale = 58.145138
Conv_98                                  : max = 2.770248         threshold = 1.999908         scale = 63.502922
Conv_99                                  : max = 2.770248         threshold = 1.999908         scale = 63.502922
Conv_101                                 : max = 1.763274         threshold = 1.712046         scale = 74.180252
Conv_102                                 : max = 1.763274         threshold = 1.712046         scale = 74.180252
Conv_104                                 : max = 1.679719         threshold = 1.493949         scale = 85.009590
Conv_107                                 : max = 5.681487         threshold = 3.699347         scale = 34.330383
Conv_115                                 : max = 5.018888         threshold = 4.346191         scale = 29.220989
Conv_123                                 : max = 3.956382         threshold = 3.945757         scale = 32.186474
Conv_127                                 : max = 5.681487         threshold = 3.699347         scale = 34.330383
Conv_135                                 : max = 5.018888         threshold = 4.346191         scale = 29.220989
Conv_143                                 : max = 3.956382         threshold = 3.945757         scale = 32.186474
Conv_147                                 : max = 5.681487         threshold = 3.699347         scale = 34.330383
Conv_155                                 : max = 5.018888         threshold = 4.346191         scale = 29.220989
Conv_163                                 : max = 3.956382         threshold = 3.945757         scale = 32.186474

**Comment by 408550969** [comment]
问题已解决。
int8模型效果异常是由三个因素导致的：
1、忘记修改阈值了，我的阈值设的0.7，测widerface得修改到0.02
2、我用的是去年的版本，更换到最新版本
3、ncnn量化教程里说是先要Optimize model，我发现加了Optimize会导致精度降低，不加反而高
总结：
我自己训练的fp32模型在widerface上的精度是
Easy   Val AP: 0.7652491643678062
Medium Val AP: 0.6576925711356209
Hard   Val AP: 0.3779476540527418
使用最新版ncnn，按照教程操作，精度是：
Easy   Val AP: 0.32014071859789944
Medium Val AP: 0.2283141129822412
Hard   Val AP: 0.11761710460179704
不使用Optimize model，精度是：
Easy   Val AP: 0.732122524893242
Medium Val AP: 0.6207044717295072
Hard   Val AP: 0.344834306222365

也尝试过混合精度推理，精度有稍许提高（0.1%）

**Comment by nihui** [comment]
恭喜你啦！

**Comment by 408550969** [comment]
谢谢！

**Comment by 408550969** [comment]
我在生成table的时候，发现每次生成的值都不一样。
特别是kl方法，值可以相差几十。导致最后的精度范围可以从0-74%浮动，这是0和74的table的值：
ac:0 | ac:0.74
Conv_0 1.084350 | Conv_0 0.991932
Conv_2 483.553009 | Conv_2 42.297329
Conv_4 63.506542 | Conv_4 57.079967
Conv_6 90.540833 | Conv_6 53.423595
Conv_8 169.209076 | Conv_8 36.493088
Conv_10 204.386963 | Conv_10 47.791733
Conv_12 113.209915 | Conv_12 41.195724
Conv_14 161.240982 | Conv_14 36.364990
Conv_16 94.971008 | Conv_16 39.634438
Conv_18 201.944916 | Conv_18 80.104340
Conv_20 126.599464 | Conv_20 57.569851
Conv_22 174.924042 | Conv_22 72.752975
Conv_24 119.353035 | Conv_24 42.111164
Conv_26 135.689743 | Conv_26 90.182953
Conv_28 93.061485 | Conv_28 59.463768
Conv_30 169.564590 | Conv_30 115.520103
Conv_32 96.832932 | Conv_32 63.605793
Conv_34 195.590759 | Conv_34 141.661743
Conv_36 114.409180 | Conv_36 99.933441
Conv_38 218.565720 | Conv_38 140.887299
Conv_40 129.285355 | Conv_40 71.131134
Conv_42 183.695190 | Conv_42 141.122757
Conv_44 104.455368 | Conv_44 96.174324
Conv_46 150.600250 | Conv_46 133.560287
Conv_48 101.120941 | Conv_48 85.440895
Conv_50 159.012573 | Conv_50 133.016006
Conv_52 91.137260 | Conv_52 122.251778
Conv_54 174.924042 | Conv_54 72.752975
Conv_56 150.600250 | Conv_56 133.560287
Conv_58 16.431799 | Conv_58 16.733620
Conv_78 39.652824 | Conv_78 42.981098
Conv_98 50.922359 | Conv_98 34.258045
Conv_100 67.050407 | Conv_100 47.216843
Conv_101 67.050407 | Conv_101 47.216843
Conv_103 56.354061 | Conv_103 45.340237
Conv_104 56.354061 | Conv_104 45.340237
Conv_106 52.253170 | Conv_106 50.396076
Conv_109 69.364784 | Conv_109 54.914532
Conv_110 69.364784 | Conv_110 54.914532
Conv_112 48.294014 | Conv_112 44.257877
Conv_113 48.294014 | Conv_113 44.257877
Conv_115 62.176476 | Conv_115 56.743526
Conv_118 63.502953 | Conv_118 63.203716
Conv_119 63.502953 | Conv_119 63.203716
Conv_121 89.787750 | Conv_121 72.674721
Conv_122 89.787750 | Conv_122 72.674721
Conv_124 84.975197 | Conv_124 76.335114
Conv_127 34.356152 | Conv_127 30.591095
Conv_135 34.226139 | Conv_135 34.363766
Conv_143 34.491764 | Conv_143 31.169909
Conv_152 34.356152 | Conv_152 30.591095
Conv_160 34.226139 | Conv_160 34.363766
Conv_168 34.491764 | Conv_168 31.169909
Conv_177 34.356152 | Conv_177 30.591095
Conv_185 34.226139 | Conv_185 34.363766
Conv_193 34.491764 | Conv_193 31.169909
acqi的好一点，差别不是很大，从结果来看也是，精度差别在0.1%
ac:0.745 | ac:0.746
Conv_0 0.997262 | Conv_0 0.997262
Conv_2 37.596451 | Conv_2 37.596451
Conv_4 16.621355 | Conv_4 16.307442
Conv_6 15.718475 | Conv_6 15.718475
Conv_8 22.419685 | Conv_8 22.419685
Conv_10 26.554586 | Conv_10 26.428234
Conv_12 18.291039 | Conv_12 18.291039
Conv_14 21.904531 | Conv_14 21.904531
Conv_16 38.257729 | Conv_16 35.855003
Conv_18 74.173248 | Conv_18 70.982658
Conv_20 53.615463 | Conv_20 50.632309
Conv_22 74.480110 | Conv_22 77.659554
Conv_24 38.020172 | Conv_24 35.458679
Conv_26 87.679993 | Conv_26 83.156769
Conv_28 42.557518 | Conv_28 42.424484
Conv_30 116.637390 | Conv_30 116.637390
Conv_32 56.509636 | Conv_32 56.174667
Conv_34 132.546677 | Conv_34 132.546677
Conv_36 72.438950 | Conv_36 72.438950
Conv_38 119.278381 | Conv_38 119.278381
Conv_40 56.062778 | Conv_40 56.062778
Conv_42 85.568291 | Conv_42 85.568291
Conv_44 51.797871 | Conv_44 50.304642
Conv_46 111.427574 | Conv_46 111.427574
Conv_48 37.041962 | Conv_48 34.626793
Conv_50 145.800964 | Conv_50 135.904663
Conv_52 51.100105 | Conv_52 51.100105
Conv_54 74.480110 | Conv_54 77.659554
Conv_56 111.427574 | Conv_56 111.427574
Conv_58 14.931147 | Conv_58 14.931147
Conv_78 32.418552 | Conv_78 32.418552
Conv_98 29.594086 | Conv_98 29.594086
Conv_100 35.146412 | Conv_100 35.146412
Conv_101 35.146412 | Conv_101 35.146412
Conv_103 39.727016 | Conv_103 39.727016
Conv_104 39.727016 | Conv_104 39.727016
Conv_106 45.621418 | Conv_106 45.621418
Conv_109 54.627995 | Conv_109 55.124287
Conv_110 54.627995 | Conv_110 55.124287
Conv_112 44.978104 | Conv_112 42.194027
Conv_113 44.978104 | Conv_113 42.194027
Conv_115 59.299751 | Conv_115 54.203350
Conv_118 45.271866 | Conv_118 45.271866
Conv_119 45.271866 | Conv_119 45.271866
Conv_121 65.258499 | Conv_121 65.258499
Conv_122 65.258499 | Conv_122 65.258499
Conv_124 67.839317 | Conv_124 67.198212
Conv_127 23.882915 | Conv_127 25.326319
Conv_135 41.246384 | Conv_135 36.848682
Conv_143 29.023970 | Conv_143 24.466185
Conv_152 23.882915 | Conv_152 25.326319
Conv_160 41.246384 | Conv_160 36.848682
Conv_168 29.023970 | Conv_168 24.466185
Conv_177 23.882915 | Conv_177 25.326319
Conv_185 41.246384 | Conv_185 36.848682
Conv_193 29.023970 | Conv_193 24.466185

我想问的是：
1、同样的数据集，为什么每次生成的table值会不一样？
2、为什么kl的波动会这么大？
