### ISSUE TITLE
如何在cpu.h上设定大小核以加速模型的运行速度?另外是一些有关num_threads的设定、lightmode

### ISSUE THREAD

**Issue by LRY89757** [Tencent/ncnn#3732]
## expectation | 诉求 | 期待する
1. speed : YOLOX-Tiny ，10FPS左右
## model | 模型 | モデル
1. model.param and model.bin
模型为fp16类型, 大小约为10MB
## detail | 详细描述 | 詳細な説明
目前摄像头实时条件下使用骁龙888约为10FPS，我们想要将速度进一步提升，最好可以完全跑满GPU，目前仅仅只能跑大约60%-70%（GPU占用）

非常感谢热心人的帮助！

**Comment by LRY89757** [comment]
@nihui @BUG1989

**Comment by LRY89757** [comment]
> @nihui @BUG1989
我们的项目目前速度一直得不到提升，我目前不知道ncnn如何才能最大程度上利用到手机的GPU, 所以请教各位大佬👀，拜托了🙏

**Comment by LRY89757** [comment]
```c++    
    ncnn::Option opt;  // 盲猜这个是ncnn中的一个配置文件，至于详细的也不是非常清楚
    opt.lightmode = true;
    opt.num_threads = 8;
    opt.blob_allocator = &g_blob_pool_allocator;
    opt.workspace_allocator = &g_workspace_pool_allocator;
    opt.use_packing_layout = true;

    // use vulkan compute
    if (ncnn::get_gpu_count() != 0)
        opt.use_vulkan_compute = true;
```
这是我目前的配置设定

**Comment by nihui** [comment]
```
#include "cpu.h"

opt.num_threads = ncnn::get_big_cpu_count();
ncnn::set_cpu_powersave(2);
```

**Comment by LRY89757** [comment]
> ```
> #include "cpu.h"
> 
> opt.num_threads = ncnn::get_big_cpu_count();
> ncnn::set_cpu_powersave(2);
> ```

opt.num_threads=ncnn::get_big_cpu_count();和ncnn::set_omp_num_threads(ncnn::get_big_cpu_count());这个命令是不是一样呢？
