### ISSUE TITLE
关于在windows上模型耗时的一些疑问

### ISSUE THREAD

**Issue by cn-bao** [Tencent/ncnn#3734]
## detail | 详细描述 | 詳細な説明
新手刚用ncnn，在windows平台上编译，遇到几个问题，麻烦答疑下，谢谢！
1. 编译了纯cpu版本和vulkan版本，读取摄像头画面跑的scrfd模型，cpu版本总体比vulkan版本的执行速度要快，这个可能是什么情况导致的？编译vulkan的时候怎么看是用的核显还是独显？
2. fp16比fp32慢，这个正常吗？

**Comment by wzyforgit** [comment]
vulkan慢的可能原因：
1.显卡驱动问题，显卡本身问题
2.模型本身不适合使用GPU
3.CPU非常先进而GPU非常拉垮（参考我司的i7-10700k搭配HD8570）

fp16的问题不是很懂，蹲一个大佬来解答

**Comment by wzyforgit** [comment]
然后看用哪张显卡的话，它那个NCNN初始化vulkan的时候会在命令行打印当前的显卡情况，上面有0123的编号，你根据编号在代码里面设置就行了

**Comment by cn-bao** [comment]
@wzyforgit  谢谢解答，我的cpu是 i7 10700k， GPU是专业显卡p2200，vulkan版本的核显和p2200都没编译的纯CPU版本快。

**Comment by nihui** [comment]
scrfd模型小，跑大模型gpu快了
