### ISSUE TITLE
no member named 'set_cpu_powersave' in namespace 'ncnn'

### ISSUE THREAD

**Issue by hadwinn** [Tencent/ncnn#3746]
## detail | 详细描述 | 詳細な説明
小白提问

已经复现代码：https://github.com/nihui/ncnn-android-squeezenet

想在代码中加入设置ARM big.LITTLE。

> 设置ARM big.LITTLE，这个是ARM提出的多核处理器的结构配置。这个配置规范中将比较耗电、但运算能力强的处理器核心组成“big集群”，将低耗电、运算能力弱的处理器核心组成“LITTLE集群”，并将它们结合在一起，这些处理器核心共享存储器区块，并能够在不同的CPU集群之间在线实时分派、切换负载。
> 
> 这个参数可以这么设定：
> 
> // 0, 1, 2
> powersave = 0
> ncnn::set_cpu_powersave(powersave);

报错no member named 'set_cpu_powersave' in namespace 'ncnn'。请问如何解决？

**Comment by nihui** [comment]
```#include "cpu.h"```

**Comment by hadwinn** [comment]
感谢！问题已解决。

**Comment by hadwinn** [comment]
![image](https://user-images.githubusercontent.com/73227570/165947684-20c4a56f-d209-488f-939f-6f67dada7219.png)

在您的帮助下，set_cpu_powersave调用成功。
目前的情况是，麒麟970 8核cpu，从图上看，调用set_cpu_powersave后，cpu仍有600%的空闲。
这是正常情况吗？如果想跑满cpu要如何设置？

**Comment by nihui** [comment]
squeezenet 模型小很快就跑完了，top 无法反映真实情况

**Comment by hadwinn** [comment]
好的，谢谢解答。
