### ISSUE TITLE
pnnx转ncnn效果异常

### ISSUE THREAD

**Issue by 408550969** [Tencent/ncnn#3748]
我使用pnnx转换retinaface模型，预测类别置信度全部为0，包括背景类别也为0.
pytorch模型pt已验证过是正常的。该模型使用onnx转换后的模型也可以使用。
pnnx也尝试过几个版本，但是结果均为异常。
这是最新版本的转换时print的参数：
pnnxparam = mobilenet.pnnx.param
pnnxbin = mobilenet.pnnx.bin
pnnxpy = mobilenet_pnnx.py
ncnnparam = mobilenet.ncnn.param
ncnnbin = mobilenet.ncnn.bin
ncnnpy = mobilenet_ncnn.py
optlevel = 2
device = cpu
inputshape = [1,3,224,224]f32
inputshape2 =
customop =
moduleop =
############# pass_level0
inline module = models.net.FPN
inline module = models.net.SSH
inline module = models.retinaface.BboxHead
inline module = models.retinaface.ClassHead
inline module = models.retinaface.LandmarkHead
inline module = torchvision.models._utils.IntermediateLayerGetter
inline module = models.net.FPN
inline module = models.net.SSH
inline module = models.retinaface.BboxHead
inline module = models.retinaface.ClassHead
inline module = models.retinaface.LandmarkHead
inline module = torchvision.models._utils.IntermediateLayerGetter
131  132  133  140  141  142  143  144  145  152  153  154  155  156  157  164  165  166  167  168  169  176  177  178  179  180  181  188  189  190  191  192  193  206  207  208  209  210  211  218  219  220  221  222  223  230  231  232  233  234  235  242  243  244  245  246  247  254  255  256  257  258  259  266  267  268  269  270  271  280  281  282  283  284  285  292  293  294  295  296  297  41  42  43  311  312  313  317  318  319  323  324  325  327  330  up3.1  input.5  338  339  340  342  345  up2.1  input0.1  353  354  355  49  50  51  52  53  365  366  370  371  372  375  376  380  381  382  385  386  input.7  389  398  399  403  404  405  408  409  413  414  415  418  419  input.9  422  431  432  436  437  438  441  442  446  447  448  451  452  input.1  455  463  465  out.2  468  471  479  481  out.4  484  487  495  497  out.6  500  503  77  510  512  out.8  515  518  525  527  out.10  530  533  540  542  out.12  545  548  input.3  556  558  out.14  561  564  572  574  out.16  577  580  588  590  out.1  593  596  101  106
----------------

############# pass_level1
no attribute value
no attribute value
no attribute value
no attribute value
no attribute value

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by 408550969** [comment]
好的。这是2年前的问题了，我都忘了，应该解决了
