### ISSUE TITLE
build fail on mips64el platform when cmake with NCNN_PYTHON=ON

### ISSUE THREAD

**Issue by zhangqiang-316** [Tencent/ncnn#3772]
## error log | 日志或报错信息 | ログ
[ 99%] Building CXX object python/CMakeFiles/pyncnn.dir/src/main.cpp.o
In file included from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/pytypes.h:12:0,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/cast.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/attr.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/pybind11.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/src/main.cpp:16:
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/common.h: In function ‘void pybind11::pybind11_fail(const char*)’:
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/common.h:838:104: error: exception handling disabled, use -fexceptions to enable
 [[noreturn]] PYBIND11_NOINLINE void pybind11_fail(const char *reason) { throw std::runtime_error(reason); }
                                                                                                        ^
In file included from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/cast.h:13:0,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/attr.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/pybind11.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/src/main.cpp:16:
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/pytypes.h: In function ‘bool pybind11::isinstance(pybind11::handle)’:
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/pytypes.h:448:78: error: cannot use typeid with -fno-rtti
 bool isinstance(handle obj) { return detail::isinstance_generic(obj, typeid(T)); }
                                                                              ^
In file included from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/cast.h:15:0,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/attr.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/pybind11.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/src/main.cpp:16:
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/descr.h: In static member function ‘static constexpr std::array<const std::type_info*, (sizeof... (Ts) + 1)> pybind11::detail::descr<N, Ts>::types()’:
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/descr.h:40:28: error: cannot use typeid with -fno-rtti
         return {{&typeid(Ts)..., nullptr}};
                            ^
In file included from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:15:0,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/cast.h:16,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/attr.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/pybind11.h:13,
                 from /home/loongson/workspace/code/ncnn/ncnn/python/src/main.cpp:16:
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h: In function ‘void pybind11::detail::translate_exception(std::__exception_ptr::exception_ptr)’:
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:286:48: error: ‘e’ was not declared in this scope
     } catch (error_already_set &e)           { e.restore();                                    return;
                                                ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:287:48: error: ‘e’ was not declared in this scope
     } catch (const builtin_exception &e)     { e.set_error();                                  return;
                                                ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:288:85: error: ‘e’ was not declared in this scope
     } catch (const std::bad_alloc &e)        { PyErr_SetString(PyExc_MemoryError,   e.what()); return;
                                                                                     ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:289:85: error: ‘e’ was not declared in this scope
     } catch (const std::domain_error &e)     { PyErr_SetString(PyExc_ValueError,    e.what()); return;
                                                                                     ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:290:85: error: ‘e’ was not declared in this scope
     } catch (const std::invalid_argument &e) { PyErr_SetString(PyExc_ValueError,    e.what()); return;
                                                                                     ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:291:85: error: ‘e’ was not declared in this scope
     } catch (const std::length_error &e)     { PyErr_SetString(PyExc_ValueError,    e.what()); return;
                                                                                     ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:292:85: error: ‘e’ was not declared in this scope
     } catch (const std::out_of_range &e)     { PyErr_SetString(PyExc_IndexError,    e.what()); return;
                                                                                     ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:293:85: error: ‘e’ was not declared in this scope
     } catch (const std::range_error &e)      { PyErr_SetString(PyExc_ValueError,    e.what()); return;
                                                                                     ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:294:85: error: ‘e’ was not declared in this scope
     } catch (const std::overflow_error &e)   { PyErr_SetString(PyExc_OverflowError, e.what()); return;
                                                                                     ^
/home/loongson/workspace/code/ncnn/ncnn/python/pybind11/include/pybind11/detail/internals.h:295:85: error: ‘e’ was not declared in this scope

## context | 编译/运行环境 | バックグラウンド
loongson 2K1000 or 3A4000 platform （mips64el）
## how to reproduce | 复现步骤 | 再現方法
1.cmake -DNCNN_DISABLE_RTTI=ON -DNCNN_DISABLE_EXCEPTION=ON -DNCNN_RUNTIME_CPU=OFF -DNCNN_MSA=ON -DNCNN_MMI=ON -DNCNN_SIMPLEOCV=ON -DNCNN_PYTHON=ON ..

2.cmake --build . -j 2

**Comment by nihui** [comment]
```cmake -DNCNN_RUNTIME_CPU=OFF -DNCNN_MSA=ON -DNCNN_MMI=ON -DNCNN_SIMPLEOCV=ON -DNCNN_PYTHON=ON ..```

试试这个参数编译

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/6647396667426405cee4da8da79f723148f60dd5
