### ISSUE TITLE
BinaryOp的计算结果跟手工计算的不一致

### ISSUE THREAD

**Issue by wwdok** [Tencent/ncnn#3788]
Sorry for the English reader, i will use Chinese to describe my question, if you have anything that don't understand well, please tell me.
这是原始onnx模型：
[subgraph1.zip](https://github.com/Tencent/ncnn/files/8692289/subgraph1.zip)
我使用`onnx2ncnn subgraph1.onnx` 转换得到了以下ncnn模型
[ncnn.zip](https://github.com/Tencent/ncnn/files/8692297/ncnn.zip)
但我发现转换过来的ncnn模型与原onnx模型的输出结果不一致，于是我开始查找原因，我使用以下代码来输出算子的计算结果：
```cpp
    const char* imagepath = "face.png";
    cv::Mat img = cv::imread(imagepath, 1);
    if (img.empty())
    {
        fprintf(stderr, "cv::imread %s failed.", imagepath);
        return ;
    }
    const int target_size = 192;
    int img_w = img.cols;
    int img_h = img.rows;
    ncnn::Mat in = ncnn::Mat::from_pixels_resize(img.data, ncnn::Mat::PIXEL_BGR2RGB, img_w, img_h, target_size, target_size);
    const float mean_vals[3] = {0.f, 0.f, 0.f};
    const float norm_vals[3] = {1.0f / 255.0f, 1.0f / 255.0f, 1.0f / 255.0f};
    in.substract_mean_normalize(mean_vals, norm_vals);
    ncnn::Net net;
    net.load_param("ncnn.param");
    net.load_model("ncnn.bin");
    ncnn::Extractor ex = net.create_extractor();
    ex.input("input_1", in);
    ncnn::Mat out;
    ex.extract("p_re_lu/Alpha_dequantize_prelu/add:0", out);

    int out_width = out.w;
    int out_height = out.h;
    int out_channels = out.c;
    printf("output whc shape:(%d, %d, %d) \n", out_width, out_height, out_channels);

    const float* ptr = out.channel(0);
    for (int y=0; y<out.h; y++)
    {
        for (int x=0; x<out.w; x++)
        {
            printf("%f ", ptr[x]);
        }
        ptr += out.w;
    }
```
这是测试图片：
![face](https://user-images.githubusercontent.com/43233772/168412030-935300aa-cf06-49b6-8000-76faee45f035.png)
我从模型的最开始部分找起，第一个卷积的计算结果是正确的，然后发现下面的两个BinaryOp的计算结果都不正确：
![image](https://user-images.githubusercontent.com/43233772/168412168-c85e3c37-5c8f-4279-832a-09175f30916f.png)
其实卷积下面的这些算子做的事情就是PRELU，特征图通道数为16，所以有16个slope斜率，储存在MemoryData里。

上面的代码我只打印了输出的第一个通道，以下是打印出来的部分结果（前16个数值）：

下图是计算图中下边的BinaryOp的验证过程，它是一个**加**法操作，可以看到，如果输入是正数，相加的结果符合逻辑，但如果输入是负数（如图红框所示），相加的结果就很莫名其妙：
![image](https://user-images.githubusercontent.com/43233772/168412417-ded64032-5457-485f-91fe-4a9cd4be3fa0.png)

下图是计算图中上边的BinaryOp的验证过程，它是一个**乘**法操作，因为这里有经过了permute操作，原来是c=16，现在是w=16，所以p_re_lu/Alpha_dequantize_prelu/Relu_1:0输出的16个数值应该是一个数值对应MemoryData里的一个斜率，但计算结果也不符合逻辑：
![image](https://user-images.githubusercontent.com/43233772/168412764-58fe9f3b-4dd3-457c-ac8c-aede03578825.png)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4809

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/9022b7162a851f5deae0d2e6e5ee5e89a4813212

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
