### ISSUE TITLE
0509版本ncnn使用vulkan占用更多内存

### ISSUE THREAD

**Issue by SeaRecluse** [Tencent/ncnn#3793]
对比220420release版本,在rk3288上测试，resnet18加速效果非常明显，速度大概快了1.8倍。但内存占用情况有所增多？
本地测试，开启vuvlkan下，应用加载scrfd0.5g/shufflenet/SSD/resnet18-fp16等四个模型，在0420版本下占用内存约1.1个g，但在0509版本中占用内存会超过1.2g?导致本地测试内存过载。
在0509版本中如果只关闭resnet18-fp16的vulkan选项，可以顺利加载。

本地测试从内存使用来看是这样的
|    | 0420  |0509  |
|  ----  | ----  |----  |
| 开启vulkan  | 加载成功 | **加载失败** |
| 纯CPU  | 加载成功 | 加载成功 |

**Comment by nihui** [comment]
emmm 可能得等下个版本

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/3865

**Comment by nihui** [comment]
最新代码已经大幅优化内存占用，推荐更新
