### ISSUE TITLE
龙芯3A4000下非fp32性能劣化问题

### ISSUE THREAD

**Issue by wzyforgit** [Tencent/ncnn#3795]
## detail | 详细描述 | 詳細な説明

由于3A4000基于的MIPS64R2指令集中并不存在fp16相关的操作指令，内部仅有针对fp32和fp64相关的指令，这导致触发了fp16相关运算的操作都会存在一定的劣化（比如向显卡喂fp16的数据）

另外由于优秀的fp32优化，导致int8量化下的数据存在一定的劣化（有点小尴尬，3A4000是有int8的SIMD指令的）：
（4核全开，使用MSA128指令集）
squeezenet  min =   18.21  max =   19.97  avg =   18.54
squeezenet_int8  min =   21.11  max =   36.58  avg =   24.60
mobilenet_ssd  min =   58.61  max =   63.20  avg =   62.63
mobilenet_ssd_int8  min =   72.35  max =  161.46  avg =  98.97

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/3797 优化了 fp32-fp16 转换效率

**Comment by wzyforgit** [comment]
> #3797 优化了 fp32-fp16 转换效率

这个在3A4000+HD8570+开启MSA128的配置下提速不明显，benchmark里面最多提升0.1~0.2ms的速度，搭配的是最新的代码
感觉是8570拖后腿了？

**Comment by nihui** [comment]
那就没办法了 :(

**Comment by wzyforgit** [comment]
> 那就没办法了 :(

还是很感谢UP啦～
那 int8 的还弄嘛？

**Comment by nihui** [comment]
已实现 https://github.com/Tencent/ncnn/commit/d4ee0853a557429384a9629e55eb23b7b5cf5ebe
