### ISSUE TITLE
app problem

### ISSUE THREAD

**Issue by eeric** [Tencent/ncnn#38]
error as following:
undefined reference to 'ncnn:Net::load_param(unsigned char const*)'
undefined reference to 'ncnn:Net::load_model(unsigned char const*)'
undefined reference to 'ncnn:Net::from_pixels(unsigned char const*,int,int,int)'
........
undefined reference to 'ncnn:Net::Net()'
undefined reference to 'ncnn:Net::~Net()'
error:linker command failed with exit code 1 (use -v to see invocation)

**Comment by noiplcx** [comment]
刚刚我也遇到这个错误了 
#   $ export ANDROID_NDK=/absolute/path/to/the/android-ndk
#   $ mkdir build && cd build
#   $ cmake -DCMAKE_TOOLCHAIN_FILE=path/to/the/android.toolchain.cmake ..
#   $ make -j8
#   $ make install
亲测可用

**Comment by eeric** [comment]
@noiplcx，你是在linux下生成libncnn.a，又在linux下编译jni的吗？

**Comment by eeric** [comment]
@noiplcx，试过了，会提示2个错误，后来按官网cmake打包android-sdk配置环境，成功生成libsqueezencnn.so，地址：https://github.com/Tencent/ncnn/wiki/cmake-打包-android-sdk，
之后也能运行app，但要注意assets文件夹在android studio工程中的位置。

**Comment by blackcat-tech** [comment]
@eeric 能分享个 .so文件用吗？

**Comment by dangbo** [comment]
https://github.com/dangbo/ncnn-mobile use ncnn in Android and iOS

**Comment by jj8401** [comment]
@eeric 我按照cmake打包android-sdk的说明，最后结果如下，并没有生成.so 文件，请教下是什么问题
➜  build-android git:(master) ✗ make install
[100%] Built target ncnn
Install the project...
-- Install configuration: "release"
-- Installing: /Users/yangguangdejianjian/code/ncnn/build-android/install/lib/libncnn.a
-- Installing: /Users/yangguangdejianjian/code/ncnn/build-android/install/include/blob.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build-android/install/include/cpu.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build-android/install/include/layer.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build-android/install/include/mat.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build-android/install/include/net.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build-android/install/include/opencv.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build-android/install/include/platform.h
➜  build-android git:(master) ✗ make package
make: *** No rule to make target `package'.  Stop.
➜  build-android git:(master) ✗

**Comment by eeric** [comment]
@jj8401 
按照https://github.com/Tencent/ncnn/wiki/cmake-打包-android-sdk，把这句-DANDROID_NATIVE_API_LEVEL=android-8，改成高版本的，比如android-18等，
另外，这句make package不需要，在obj文件夹或者lib文件夹内应该有的

**Comment by jj8401** [comment]
@eeric 我已经改过了 生成的.so文件有1.5m大小，相比官方参考的那个app里的.so文件270kb，想问下您生成的士多大，有没有影响

**Comment by eeric** [comment]
@jj8401，我的1.23M，这个大小与你的编译工具有关吧

**Comment by jj8401** [comment]
@eeric 非常感谢

**Comment by enduringstack** [comment]
@eeric   你的NDK版本和CMAKE版本能说下吗

**Comment by eeric** [comment]
@enduringstack 
android-ndk-r13b以上版本就可以了
cmake 3.22
