### ISSUE TITLE
Install Raspberry Pi Bullseye 32-bit fails

### ISSUE THREAD

**Issue by Qengineering** [Tencent/ncnn#3807]
### error log | 日志或报错信息 | ログ

When installing ncnn from scratch on a Raspberry Pi 4, it fails on Bullseye 32-bit OS. **Not** on Buster 32-bit nor on Bullseye 64-bit. 
```
/usr/bin/ld: ../src/libncnn.a(cpu.cpp.o): undefined reference to symbol 'dlopen@@GLIBC_2.4'
/usr/bin/ld: /usr/lib/gcc/arm-linux-gnueabihf/10/../../../arm-linux-gnueabihf/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
All the builds have libdl.so included with the -ldl flag as can be seen below.
Just because the installation works fine on Buster 32 and Bullseye 64, I haven't a clue where to look.

### context | 编译/运行环境 | バックグラウンド

Raspberry Pi 4 - 4 GB

### how to reproduce | 复现步骤 | 再現方法
In case of a 32 bit OS
```
$ git clone --depth=1 https://github.com/Tencent/ncnn.git
# install ncnn
$ cd ncnn
$ mkdir build
$ cd build
# build 32-bit ncnn
$ cmake -D PI3=ON \
-D NCNN_DISABLE_RTTI=OFF \
-D NCNN_BUILD_TOOLS=ON \
-D CMAKE_EXE_LINKER_FLAGS=-ldl \
-D CMAKE_TOOLCHAIN_FILE=../toolchains/pi3.toolchain.cmake ..
$ make -j4
```
With a 64-OS
```
$ git clone --depth=1 https://github.com/Tencent/ncnn.git
# install ncnn
$ cd ncnn
$ mkdir build
$ cd build
# build 64-bit ncnn
$ cmake -D NCNN_DISABLE_RTTI=OFF -D NCNN_BUILD_TOOLS=ON \
-D CMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-linux-gnu.toolchain.cmake ..
$ make -j4
```
### more | 其他 | その他
![image](https://user-images.githubusercontent.com/44409029/169021526-b9e3e6e5-af22-4b63-9661-11917a7fa5c3.png)

**Comment by nihui** [comment]
try building without ```-D CMAKE_TOOLCHAIN_FILE``` option
```cmake ..``` shall work

**Comment by Qengineering** [comment]
It works fine. Thanks!

**Comment by nihui** [comment]
pi3.toolchain.cmake updated with less error flags since https://github.com/Tencent/ncnn/commit/f79073c182971808bcd4d94d3fd90e01b7beb2db

**Comment by Qengineering** [comment]
Many thanks!
