### ISSUE TITLE
系统明明显示支持avx512 vnni，编译却显示不支持

### ISSUE THREAD

**Issue by jia0511** [Tencent/ncnn#3810]
## context | 编
![error](https://user-images.githubusercontent.com/24822418/169438695-c8232c4e-5219-40d8-a8ac-e8de495b0c73.png)
译/运行环境 | バックグラウンド
![cpuinfo](https://user-images.githubusercontent.com/24822418/169438724-9c6f4b60-ab10-46c3-a64f-a535ff2032d8.png)

## how to reproduce | 复现步骤 | 再現方法
1.下载最新版本ncnn
2.按照https://zhuanlan.zhihu.com/p/394762128安装必要包
3.运行出错

**Comment by nihui** [comment]
编译器版本太旧了？

**Comment by jia0511** [comment]
@nihui 
 要求支持的最低版本是多少？

**Comment by nihui** [comment]
gcc/g++ >= 9.1
