### ISSUE TITLE
Low computation speed on WASM without SIMD

### ISSUE THREAD

**Issue by qwertypower** [Tencent/ncnn#3812]
## detail | 详细描述 | 詳細な説明
Are you planning add XNNPACK or optimized backend for basic WASM library? I have tested mediapipe face_landmark model with simd and without. The result is very, very different.

WASM SIMD: blazeface time ~45ms.
WASM no SIMD: blazeface time ~180-200ms.

WASM SIMD: landmark time 8-10ms.
WASM no SIMD: landmark time ~55ms.

I think what convolution layers is not good optimized in plain C++. I have not tested timings for individual layers.

Builded with emscripten 3.1.10 with -O3

P.S. Yes, this optimizations only needed for Safari.

**Comment by nihui** [comment]
ncnn has wasm simd optimization, which brings significantly improvement in practical applications

Here is an example of ncnn wasm, compatible with various browsers
https://github.com/nihui/ncnn-webassembly-yolov5
