### ISSUE TITLE
Build errors on Fedora 36

### ISSUE THREAD

**Issue by Markon101** [Tencent/ncnn#3825]
## error log | 日志或报错信息 | ログ
make[2]: *** No rule to make target '/usr/lib/gcc/x86_64-redhat-linux/11/libgomp.so', needed by 'waifu2x-ncnn-vulkan'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:275: CMakeFiles/waifu2x-ncnn-vulkan.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

## context | 编译/运行环境 | バックグラウンド
Compiling in Fedora Linux version 36 fully updated.

## how to reproduce | 复现步骤 | 再現方法
1. Compile in Fedora Linux 36

**Comment by nihui** [comment]
remove build directory and rebuild

**Comment by Markon101** [comment]
> remove build directory and rebuild

Thank you for the quick reply! It is working now!
