### ISSUE TITLE
编译ncnn-20220420失败

### ISSUE THREAD

**Issue by onexuan** [Tencent/ncnn#3829]
环境

`
mac sierra 10.12.6
`

失败日志

/Users/hehe/Downloads/ncnn-20220420/src/layer/absval.cpp:25:65: warning: 
      unused parameter 'opt' [-Wunused-parameter]
int AbsVal::forward_inplace(Mat& bottom_top_blob, const Option& opt) const
                                                                ^
1 warning generated.
[ 46%] Building CXX object src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_fma.cpp.o
/Users/hehe/Downloads/ncnn-20220420/src/layer/batchnorm.cpp:72:68: warning: 
      unused parameter 'opt' [-Wunused-parameter]
int BatchNorm::forward_inplace(Mat& bottom_top_blob, const Option& opt) const
                                                                   ^
1 warning generated.
[ 47%] Building CXX object src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_avx.cpp.o
[ 47%] Building CXX object src/CMakeFiles/ncnn.dir/layer/bias.cpp.o
In file included from /Users/hehe/Downloads/ncnn-20220420/build/src/layer/x86/batchnorm_x86_avx512.cpp:23:
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:431:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpg = _mm512_shuffle_ps(_tmp0, _tmp2, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:432:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmph = _mm512_shuffle_ps(_tmp0, _tmp2, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:433:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpi = _mm512_shuffle_ps(_tmp1, _tmp3, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:434:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpj = _mm512_shuffle_ps(_tmp1, _tmp3, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:435:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpk = _mm512_shuffle_ps(_tmp4, _tmp6, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:436:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpl = _mm512_shuffle_ps(_tmp4, _tmp6, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:437:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpm = _mm512_shuffle_ps(_tmp5, _tmp7, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:438:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpn = _mm512_shuffle_ps(_tmp5, _tmp7, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:439:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpo = _mm512_shuffle_ps(_tmp8, _tmpa, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:440:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpp = _mm512_shuffle_ps(_tmp8, _tmpa, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:441:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpq = _mm512_shuffle_ps(_tmp9, _tmpb, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:442:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpr = _mm512_shuffle_ps(_tmp9, _tmpb, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:443:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmps = _mm512_shuffle_ps(_tmpc, _tmpe, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:444:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpt = _mm512_shuffle_ps(_tmpc, _tmpe, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:445:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpu = _mm512_shuffle_ps(_tmpd, _tmpf, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:446:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpv = _mm512_shuffle_ps(_tmpd, _tmpf, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:448:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp0 = _mm512_shuffle_f32x4(_tmpg, _tmpk, _MM_SHUFFLE(2, 0, 2, 0));
            ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:449:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp1 = _mm512_shuffle_f32x4(_tmpo, _tmps, _MM_SHUFFLE(2, 0, 2, 0));
            ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:450:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp2 = _mm512_shuffle_f32x4(_tmph, _tmpl, _MM_SHUFFLE(2, 0, 2, 0));
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_avx512.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/hehe/Downloads/ncnn-20220420/src/layer/bias.cpp:41:63: warning: 
      unused parameter 'opt' [-Wunused-parameter]
int Bias::forward_inplace(Mat& bottom_top_blob, const Option& opt) const
                                                              ^
1 warning generated.
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 47%] Linking CXX executable onnx2ncnn
[ 47%] Built target onnx2ncnn
[ 48%] Linking CXX executable caffe2ncnn
[ 48%] Built target caffe2ncnn
make: *** [all] Error 2

**Comment by DaChengTechnology** [comment]
建议关掉avx512

**Comment by DaChengTechnology** [comment]
可以参考 https://github.com/Tencent/ncnn/pull/3800/commits/557a5dfbb59f3b49d2f48fd0ee39a24a02f04227

**Comment by onexuan** [comment]
@DaChengTechnology 还是不行

**Comment by DaChengTechnology** [comment]
> @DaChengTechnology 还是不行

日志呢 或者加我QQ 给你teamviewer解决一下 QQ412200533

**Comment by DaChengTechnology** [comment]
@onexuan

**Comment by onexuan** [comment]
删除build.sh 文件的一些编译，只留
##### MacOS
mkdir -p build-mac
pushd build-mac
cmake   -DNCNN_OPENMP=OFF \
        -DNCNN_BENCHMARK=ON \
        ..
make -j8
make install
popd

CMakeLists.txt 增加
if(APPLE)
            set(NCNN_COMPILER_SUPPORT_X86_AVX512 OFF)
            set(NCNN_COMPILER_SUPPORT_X86_AVX512_VNNI OFF)
endif()

sh build.sh 编译


 46%] Building CXX object src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86.cpp.o
[ 46%] Building CXX object src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_avx512.cpp.o
/Users/hehe/Downloads/ncnn-20220420/src/layer/absval.cpp:25:65: warning: 
      unused parameter 'opt' [-Wunused-parameter]
int AbsVal::forward_inplace(Mat& bottom_top_blob, const Option& opt) const
                                                                ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/batchnorm.cpp:72:68: warning: 
      unused parameter 'opt' [-Wunused-parameter]
int BatchNorm::forward_inplace(Mat& bottom_top_blob, const Option& opt) const
                                                                   ^
1 warning generated.
[ 46%] Building CXX object src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_fma.cpp.o
1 warning generated.
[ 47%] Building CXX object src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_avx.cpp.o
[ 47%] Building CXX object src/CMakeFiles/ncnn.dir/layer/bias.cpp.o
In file included from /Users/hehe/Downloads/ncnn-20220420/build-mac/src/layer/x86/batchnorm_x86_avx512.cpp:23:
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:431:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpg = _mm512_shuffle_ps(_tmp0, _tmp2, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:432:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmph = _mm512_shuffle_ps(_tmp0, _tmp2, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:433:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpi = _mm512_shuffle_ps(_tmp1, _tmp3, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:434:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpj = _mm512_shuffle_ps(_tmp1, _tmp3, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:435:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpk = _mm512_shuffle_ps(_tmp4, _tmp6, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:436:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpl = _mm512_shuffle_ps(_tmp4, _tmp6, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:437:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpm = _mm512_shuffle_ps(_tmp5, _tmp7, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:438:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpn = _mm512_shuffle_ps(_tmp5, _tmp7, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:439:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpo = _mm512_shuffle_ps(_tmp8, _tmpa, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:440:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpp = _mm512_shuffle_ps(_tmp8, _tmpa, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:441:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpq = _mm512_shuffle_ps(_tmp9, _tmpb, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:442:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpr = _mm512_shuffle_ps(_tmp9, _tmpb, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:443:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmps = _mm512_shuffle_ps(_tmpc, _tmpe, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:444:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpt = _mm512_shuffle_ps(_tmpc, _tmpe, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:445:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpu = _mm512_shuffle_ps(_tmpd, _tmpf, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:446:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpv = _mm512_shuffle_ps(_tmpd, _tmpf, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:448:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp0 = _mm512_shuffle_f32x4(_tmpg, _tmpk, _MM_SHUFFLE(2, 0, 2, 0));
            ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:449:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp1 = _mm512_shuffle_f32x4(_tmpo, _tmps, _MM_SHUFFLE(2, 0, 2, 0));
            ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:450:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp2 = _mm512_shuffle_f32x4(_tmph, _tmpl, _MM_SHUFFLE(2, 0, 2, 0));
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
/Users/hehe/Downloads/ncnn-20220420/src/layer/bias.cpp:41:63: warning: 
      unused parameter 'opt' [-Wunused-parameter]
int Bias::forward_inplace(Mat& bottom_top_blob, const Option& opt) const
                                                              ^
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_avx512.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 47%] Linking CXX executable onnx2ncnn
[ 47%] Built target onnx2ncnn
[ 48%] Linking CXX executable caffe2ncnn
[ 48%] Built target caffe2ncnn
make: *** [all] Error 2
[  0%] Built target ncnn-generate-spirv
[  0%] Building CXX object src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_avx512.cpp.o
In file included from /Users/hehe/Downloads/ncnn-20220420/build-mac/src/layer/x86/batchnorm_x86_avx512.cpp:23:
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:431:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpg = _mm512_shuffle_ps(_tmp0, _tmp2, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:432:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmph = _mm512_shuffle_ps(_tmp0, _tmp2, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:433:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpi = _mm512_shuffle_ps(_tmp1, _tmp3, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:434:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpj = _mm512_shuffle_ps(_tmp1, _tmp3, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:435:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpk = _mm512_shuffle_ps(_tmp4, _tmp6, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:436:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpl = _mm512_shuffle_ps(_tmp4, _tmp6, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:437:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpm = _mm512_shuffle_ps(_tmp5, _tmp7, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:438:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpn = _mm512_shuffle_ps(_tmp5, _tmp7, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:439:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpo = _mm512_shuffle_ps(_tmp8, _tmpa, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:440:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpp = _mm512_shuffle_ps(_tmp8, _tmpa, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:441:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpq = _mm512_shuffle_ps(_tmp9, _tmpb, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:442:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpr = _mm512_shuffle_ps(_tmp9, _tmpb, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:443:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmps = _mm512_shuffle_ps(_tmpc, _tmpe, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:444:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpt = _mm512_shuffle_ps(_tmpc, _tmpe, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:445:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpu = _mm512_shuffle_ps(_tmpd, _tmpf, _MM_SHUFFLE(1, 0, 1, 0));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:446:20: error: 
      use of undeclared identifier '_mm512_shuffle_ps'
    __m512 _tmpv = _mm512_shuffle_ps(_tmpd, _tmpf, _MM_SHUFFLE(3, 2, 3, 2));
                   ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:448:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp0 = _mm512_shuffle_f32x4(_tmpg, _tmpk, _MM_SHUFFLE(2, 0, 2, 0));
            ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:449:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp1 = _mm512_shuffle_f32x4(_tmpo, _tmps, _MM_SHUFFLE(2, 0, 2, 0));
            ^
/Users/hehe/Downloads/ncnn-20220420/src/layer/x86/x86_usability.h:450:13: error: 
      use of undeclared identifier '_mm512_shuffle_f32x4'
    _tmp2 = _mm512_shuffle_f32x4(_tmph, _tmpl, _MM_SHUFFLE(2, 0, 2, 0));
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/x86/batchnorm_x86_avx512.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
make: *** [all] Error 2

**Comment by DaChengTechnology** [comment]
直接 
```
brew install libomp
cmake ..
```

**Comment by onexuan** [comment]
一样，error batchnorm_x86_avx512

**Comment by nihui** [comment]
更新xcode版本
或者 ```cmake -DNCNN_AVX512=OFF ..``` 禁用avx512
