### ISSUE TITLE
NCNN different output for PC and Android?

### ISSUE THREAD

**Issue by furiouslee** [Tencent/ncnn#383]
I loaded my parameters and model weights in the form of unsigned character array made using the ncnn2mem. However, they provide different outputs in PC and Android. 

Previously I couldn't load the unsigned character array because it was not aligned properly. 
Can this be a problem in declaring ncnn::Net or ncnn::Extractor or ncnn::Mat classes?  
Should I be adding `__attribute__((aligned(4)))` everywhere?

**Comment by nihui** [comment]
please try the latest code.
feel free to reopen this if the output is still different.
