### ISSUE TITLE
Deconv1d参数读取错误

### ISSUE THREAD

**Issue by YoungJay0612** [Tencent/ncnn#3833]
## error log | 日志或报错信息 | ログ
[执行ncnn工程时，读取deconv1d的网络参数，内存访问越界]
![error](https://user-images.githubusercontent.com/20794414/169976086-55b615f7-fabc-44c1-802b-7a1f4155917e.jpg)

## model | 模型 | モデル
1. original model
en_conv = nn.Conv1d(1, 24, 256, 128)
de_conv = nn.ConvTranspose1d(24, 1, 256, 128)
ncnn可调用模型：
[model.zip](https://github.com/Tencent/ncnn/files/8760474/model.zip)

## how to reproduce | 复现步骤 | 再現方法
1.测试两层网络结构，conv1d和deconv1d
2.如果kernel_size = 256, stride = 128，则报错，如果kernel_size = 8, stride=4则正常运行
3.好像和kernel大小有关，小的kernel可以运行，256，512就会报错

**Comment by nihui** [comment]
试试用 pnnx 转换模型，应该没有问题
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/tree/master/tools/pnnx#usage

**Comment by YoungJay0612** [comment]
谢谢大神。还有个问题咨询一下，ncnn的测试demo都是一次性处理。像我现在处理音频流分帧的话，能只进行一次create_extrator，然后循环进行处理吗？

**Comment by YoungJay0612** [comment]
> 多个 create_extrator比较好

多个是什么意思？
如果是每次处理一帧都需要重新进行create_extrator，会不会影响LSTM或者卷积网络的计算？有没有办法只生成一个create_extrator，然后循环处理？

**Comment by DaChengTechnology** [comment]
> > 多个 create_extrator比较好
> 
> 多个是什么意思？ 如果是每次处理一帧都需要重新进行create_extrator，会不会影响LSTM或者卷积网络的计算？有没有办法只生成一个create_extrator，然后循环处理？

可以做pipeline

**Comment by YoungJay0612** [comment]
> > > 多个 create_extrator比较好
> > 
> > 
> > 多个是什么意思？ 如果是每次处理一帧都需要重新进行create_extrator，会不会影响LSTM或者卷积网络的计算？有没有办法只生成一个create_extrator，然后循环处理？
> 
> 可以做pipeline

不好意思，能具体一些吗？不是很理解

**Comment by YoungJay0612** [comment]
@nihui 大神有时间可以解答一下这个疑惑吗？

> 谢谢大神。还有个问题咨询一下，ncnn的测试demo都是一次性处理。像我现在处理音频流分帧的话，能只进行一次create_extrator，然后循环进行处理吗？

**Comment by nihui** [comment]
> @nihui 大神有时间可以解答一下这个疑惑吗？
> 
> > 谢谢大神。还有个问题咨询一下，ncnn的测试demo都是一次性处理。像我现在处理音频流分帧的话，能只进行一次create_extrator，然后循环进行处理吗？

输入不同，就应该改使用新的 extractor

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
