### ISSUE TITLE
ncnn innerproduct layer top_blob create issue

### ISSUE THREAD

**Issue by hongtao12310** [Tencent/ncnn#384]
I am working on mtcnn ncnn project. I have transpose all the kernel weights manually according to wiki page: https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result

but I found there may be something wrong in the innerproduct layer. the num_output should not be the mat width but the mat channel ?

and we should create the top_blob by top_blob.create(1, 1, num_output, element_size) ?

did i miss something ?

int InnerProduct::forward(const Mat& bottom_blob, Mat& top_blob) const
{
    int w = bottom_blob.w;
    int h = bottom_blob.h;
    int channels = bottom_blob.c;
    int size = w * h;

    **top_blob.create(num_output);**

**Comment by nihui** [comment]
innerproduct produce blob of dimension 1, which is as [w] in ncnn Mat

you may refer one mtcnn implementation https://github.com/moli232777144/mtcnn_ncnn

**Comment by hongtao12310** [comment]
the [w] top blob mat is
    dims = 1;
    w = _w;
    h = 1;
    c = 1;

    cstep = w;

也就是说 top blob的num_outputs 给了width 。 难道不是channels 吗？

**Comment by nihui** [comment]
1维数据在ncnn Mat里总是存放在w上，这点和caffe不同，物理意义一致即可
