### ISSUE TITLE
layer F.grid_sample not exists or registered

### ISSUE THREAD

**Issue by zhang0557kui** [Tencent/ncnn#3841]
问题描述：
我将pytorch模型转换成libtorch，然后通过pnnx来转换出ncnn模型，使用的都是最新代码编译的，python班ncnn库也更新到了最新版，转换过程没报什么错误，转换完成后使用转换输出的model_ncnn.py来测试model.ncnn.bin和model.ncnn.param报错如下：
layer F.grid_sample not exists or registered

libtorch模型在这里: 
链接：https://pan.baidu.com/s/19BtXVgpjkh76L1cQ29noeQ?pwd=4as0 
提取码：4as0

**Comment by nihui** [comment]
F.grid_sample 现已支持 pnnx 到 ncnn 的转换
