### ISSUE TITLE
 基于shufflenetV2的106点检测输出不正确

### ISSUE THREAD

**Issue by nihilityworld** [Tencent/ncnn#3864]
## detail | 详细描述 | 詳細な説明
没有报错信息
模型后输出不正确

## model | 模型 | モデル
1. 基于shufflenetV2的106点检测，使用onnx2ncnn转换，尝试了pnnx，结果全不正确
2. 输出的y全部为0,x部分为0
3. 可以确认转换前的模型没有问题
4. 原模型无法上传

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result
注意RGB/BGR，注意预处理系数

**Comment by FeiGeChuanShu** [comment]
在保证输入数据一致的前提下，可以一次打印pytorch/onnx和ncnn每一层的输出看看哪里出了问题

**Comment by nihilityworld** [comment]
输入全0数据，对比pytorch/onnx和ncnn每一层的输出，出问题的地方在pooling（左边是pytorch，右边是ncnn）
![1656500402(1)](https://user-images.githubusercontent.com/11676992/176421064-ee85b4f1-0d2e-45ec-82ca-714790b20bc7.png)
pooling 类型是average，bottom是488x14x14，kernel是14x14，无padding，

**Comment by nihilityworld** [comment]
找到问题了，输出的cstep是4

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
