### ISSUE TITLE
IOS测试model时遇到在iphone6s运行工程OK但是在iPhone 11 Pro上运行结果就出错

### ISSUE THREAD

**Issue by lmq5294249** [Tencent/ncnn#3887]
项目地址
链接: https://pan.baidu.com/s/1imYQcX5RzbVjLU6y6d3IVQ 提取码: g886 

在手机iPhone 6s 上面运行结果输出是没问题的，
但是在手机iPhone 11 pro上面运行后，框选目标就出错，框框位置不对，然后检查代码得知输出的数据都是Nan
部分代码如下
    ncnn::Extractor ex = net.create_extractor();
    ex.set_num_threads(2);

    ncnn::Mat ncnn_in1 = ncnn::Mat::from_pixels(x_crop.data, ncnn::Mat::PIXEL_RGB, x_crop.cols, x_crop.rows);
    ncnn_in1.substract_mean_normalize(mean_vals1, norm_vals1);

    ex.input("input", ncnn_in1);
    ex.input("temp", zf_);

    ncnn::Mat cls, reg;
    ex.extract("cls", cls);
    ex.extract("reg", reg);

    float* cls_data = (float*)cls.data;
    cls_score.clear();
    for (int i = 0; i < 16 * 16; i++)
    {
        cls_score.push_back(sigmoid(cls_data[i]));
    }

    std::vector<float> pred_x1(16*16,0), pred_y1(16 * 16, 0), pred_x2(16 * 16, 0), pred_y2(16 * 16, 0);

    float* reg_data1 = reg.channel(0);
    float* reg_data2 = reg.channel(1);
    float* reg_data3 = reg.channel(2);
    float* reg_data4 = reg.channel(3);

输出的结果都是Nan
这就有点懵圈，都是64架构的两个机子，iphone 11 pro输出结果异常？？？？？？？？？？

**Comment by nihui** [comment]
是最新的 20220420 版本吗？

临时的workaround
```cpp
// net.load_param 前添加
net.opt.use_fp16_storage = false;
net.opt.use_fp16_arithmetic = false;
```

**Comment by lmq5294249** [comment]
应该不是最新版，最近没去更新NCNN库都是用旧的库。

**Comment by lmq5294249** [comment]
刚刚去更新了最新的NCNN库，确实没有这个问题。
而且推理运行速度上也提升了一大截快了6~8ms
