### ISSUE TITLE
尝试使用ncnnoptimize优化模型时，报错Floating point exception

### ISSUE THREAD

**Issue by crossover10** [Tencent/ncnn#3897]
## error log | 日志或报错信息 | ログ
user@ubuntu:~/ncnn-2022/build/tools# ./ncnnoptimize ./onnx/best_530.param ./onnx/best_530.bin best_530.param best_530.bin 65536
fuse_convolution_activation Conv_0 Relu_1
fuse_convolution_activation Conv_2 Relu_3
fuse_convolution_activation Conv_4 Relu_5
fuse_convolution_activation Conv_9 Relu_10
fuse_convolution_activation Conv_15 Relu_16
fuse_convolution_activation Conv_21 Relu_22
fuse_convolution_activation Conv_26 Relu_27
fuse_convolution_activation Conv_31 Relu_32
fuse_convolution_activation Conv_37 Relu_38
fuse_convolution_activation Conv_43 Relu_44
fuse_convolution_activation Conv_57 Relu_58
fuse_convolution_activation Conv_68 Relu_69
fuse_convolutiondepthwise_activation Conv_6 Relu_7
fuse_convolutiondepthwise_activation Conv_11 Relu_12
fuse_convolutiondepthwise_activation Conv_17 Relu_18
fuse_convolutiondepthwise_activation Conv_23 Relu_24
fuse_convolutiondepthwise_activation Conv_28 Relu_29
fuse_convolutiondepthwise_activation Conv_33 Relu_34
fuse_convolutiondepthwise_activation Conv_39 Relu_40
fuse_convolutiondepthwise_activation Conv_45 Relu_46
fuse_innerproduct_activation Gemm_78 Sigmoid_79
Floating point exception

## model | 模型 | モデル
1. original model
[model.zip](https://github.com/Tencent/ncnn/files/8860427/model.zip)

## how to reproduce | 复现步骤 | 再現方法
1./ncnnoptimize ./onnx/best_530.param ./onnx/best_530.bin best_530.param best_530.bin 65536

使用旧版本的ncnn能够正常转换：
![K{W2CZE)G14 W$25JI}7~B9](https://user-images.githubusercontent.com/40681438/172587117-f52218f9-bceb-4dfb-ba32-11cbb05165ad.jpg)

报错的版本是：
![PZBOH JLROSXIJ T2STM8XA](https://user-images.githubusercontent.com/40681438/172587255-d81340fb-196b-44cc-a706-c9e4f921157d.jpg)

模型是用torch 1.7训练出来的，GLIBC=2.23

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by csukuangfj** [comment]
可以看看 #6322  建议用 gdb 或者 lldb, 得到 backtrace, 看是哪一行挂掉的.
