### ISSUE TITLE
caffe LCNN ， Slice 、Eltwise层extract 返回-100

### ISSUE THREAD

**Issue by PipeBlack** [Tencent/ncnn#391]
Android平台下
layer {
  name: "fc1"
  type: "InnerProduct"
  bottom: "pool4"
  top: "fc1"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 512
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0.1
    }
  }
}
layer {
  name: "slice_fc1"
  type: "Slice"
  bottom: "fc1"
  top: "slice_fc1_1"
  top: "slice_fc1_2"
  slice_param {
    slice_dim: 1
  }
}
layer {
  name: "eltwise_fc1"
  type: "Eltwise"
  bottom: "slice_fc1_1"
  bottom: "slice_fc1_2"
  top: "eltwise_fc1"
  eltwise_param {
    operation: MAX
  }
}
**这是网络的最后三层**

.id.h以下
namespace __LCNN_param_id 
{
const int LAYER_fc1 = 32;
const int BLOB_fc1 = 41;
const int LAYER_slice_fc1 = 33;
const int BLOB_slice_fc1_1 = 42;
const int BLOB_slice_fc1_2 = 43;
const int LAYER_eltwise_fc1 = 34;
const int BLOB_eltwise_fc1 = 44;
}

ex.extract(__LCNN_param_id::BLOB_eltwise_fc1, out) 
ex.extract(__LCNN_param_id::BLOB_slice_fc1_1, out) 
ex.extract(__LCNN_param_id::BLOB_slice_fc1_2, out) 
结果都为：out.dims=0，ex.extract()返回值为-100

ex.extract(__LCNN_param_id::BLOB_fc1, out) 
结果为：out.dims=1,out.w=512,ex.extract()返回值为0

prototxt中还有其他的Slice Eltwise,并没有影响BLOB_fc1

**Comment by nihui** [comment]
使用最新的 caffe2ncnn 转换的吗？
把转换后的 param 文件，有问题的 slice 前后几行贴下

**Comment by PipeBlack** [comment]
2018/5/4下载编译，使用vs2015编译
param文件如下
[https://github.com/PipeBlack/PipeBlack.github.io/blob/master/tmp/LCNN.param](url)
上面贴的部分prototxt是网络的最后三层，输出有问题的是最后两层

在pc端使用.param、.bin
ex.extract("eltwise_fc1", out);
	cls_scores.resize(out.w);
	for (int j = 0; j<out.w; j++)
	{
		cls_scores[j] = out[j];
	}
	fprintf(stderr,"%d\n",cls_scores.size());//**此处打印256**

**Comment by nihui** [comment]
确认 eltwise on vector and image 有问题

**Comment by Dawson-huang** [comment]
我同样遇到类似的问题，我已经尝试过用今天最新的caffe2ncnn转换过模型，但是在ncnn代码上模型加载进来就是一个空的网络，什么都没有，我的caffe模型也已经转换到新版caffe了

**Comment by Dawson-huang** [comment]
我的问题已解决，主要是我个人原因操作失误，ncnn代码没问题，sorry

**Comment by nihui** [comment]
@PipeBlack https://github.com/PipeBlack/PipeBlack.github.io/blob/master/tmp/LCNN.param
我用这个文件跑测试并没有出现 -100 的问题...
```
    ncnn::Extractor ex = net.create_extractor();

    ncnn::Mat in(128, 128, 1);
    in.fill(2);

    ex.input("data", in);

    ncnn::Mat out;
    int ret = ex.extract("eltwise_fc1", out);
    fprintf(stderr, "ret = %d\n", ret);

    for (int j=0; j<out.w; j++)
    {
        fprintf(stderr, "%f\n", out[j]);
    }
```

**Comment by PipeBlack** [comment]
@nihui 问题出现在Android平台下

在pc端使用.param、.bin，结果正常
ex.input("data", in);
ncnn::Mat out;
ex.extract("eltwise_fc1", out);
cls_scores.resize(out.w);
for (int j = 0; j<out.w; j++)
{
cls_scores[j] = out[j];
}
fprintf(stderr,"%d\n",cls_scores.size());//**此处打印256**

**Comment by PipeBlack** [comment]
@nihui 
cmake 打包Android sdk生成libncnn.a,取代从releases中下载的libnann.a可以解决

make package这一句显示
make: *** No rule to make target 'package'. Stop.
issue#38说make package这句不需要,是吗？

**Comment by nihui** [comment]
make package 不需要
