### ISSUE TITLE
用20220525的pnnx导出convnext的模型后，推理结果为0，打印每一层，发现在某一个split操作后，输出为-nan

### ISSUE THREAD

**Issue by crossover10** [Tencent/ncnn#3910]
## error log | 日志或报错信息 | ログ
https://github.com/facebookresearch/ConvNeXt.git 模型有修改过，剪了通道，把gelu换成sigmod
## model | 模型 | モデル
1. original model
7767517
142 166
Input                    in0                      0 1 in0
Convolution              conv_7                   1 1 in0 1 0=32 1=4 11=4 12=1 13=4 14=0 2=1 3=4 4=0 5=1 6=1536
Split                    splitncnn_0              1 3 1 2 3 4
Reduction                mean_31                  1 1 4 5 0=3 1=0 -23303=1,0 4=1 5=1
Split                    splitncnn_1              1 2 5 6 7
BinaryOp                 sub_0                    2 1 2 6 8 0=1
BinaryOp                 pow_1                    1 1 8 9 0=6 1=1 2=2.000000e+00
MemoryData               pnnx_fold_96             0 1 10 0=1 1=1 2=32
MemoryData               pnnx_fold_100            0 1 11 0=1 1=1 2=32
Reduction                mean_32                  1 1 9 12 0=3 1=0 -23303=1,0 4=1 5=1
BinaryOp                 add_2                    1 1 12 13 0=0 1=1 2=1.000000e-06
UnaryOp                  sqrt_3                   1 1 13 14 0=5
BinaryOp                 sub_4                    2 1 3 7 15 0=1
BinaryOp                 div_5                    2 1 15 14 16 0=3
BinaryOp                 mul_6                    2 1 10 16 17 0=2
BinaryOp                 add_7                    2 1 17 11 18 0=0
Split                    splitncnn_2              1 2 18 19 20
MemoryData               stages.0.0               0 1 21 0=32
ConvolutionDepthWise     convdw_52                1 1 20 22 0=32 1=7 11=7 12=1 13=1 14=3 2=1 3=1 4=3 5=1 6=1568 7=32
Permute                  permute_40               1 1 22 23 0=3
LayerNorm                ln_0                     1 1 23 24 0=32 1=1.000000e-06 2=1
InnerProduct             linear_12                1 1 24 25 0=128 1=1 2=4096
Split                    splitncnn_3              1 2 25 26 27
Sigmoid                  sigmoid_25               1 1 27 28
BinaryOp                 mul_8                    2 1 26 28 29 0=2
InnerProduct             linear_13                1 1 29 30 0=32 1=1 2=4096
BinaryOp                 mul_9                    2 1 21 30 31 0=2
Permute                  permute_41               1 1 31 32 0=4
BinaryOp                 add_10                   2 1 19 32 33 0=0
Split                    splitncnn_4              1 3 33 34 35 36
Reduction                mean_33                  1 1 36 37 0=3 1=0 -23303=1,0 4=1 5=1
Split                    splitncnn_5              1 2 37 38 39
BinaryOp                 sub_11                   2 1 34 38 40 0=1
BinaryOp                 pow_12                   1 1 40 41 0=6 1=1 2=2.000000e+00
MemoryData               pnnx_fold_156            0 1 42 0=1 1=1 2=32
MemoryData               pnnx_fold_160            0 1 43 0=1 1=1 2=32
Reduction                mean_34                  1 1 41 44 0=3 1=0 -23303=1,0 4=1 5=1
BinaryOp                 add_13                   1 1 44 45 0=0 1=1 2=1.000000e-06
UnaryOp                  sqrt_14                  1 1 45 46 0=5
BinaryOp                 sub_15                   2 1 35 39 47 0=1
BinaryOp                 div_16                   2 1 47 46 48 0=3
BinaryOp                 mul_17                   2 1 42 48 49 0=2
BinaryOp                 add_18                   2 1 49 43 50 0=0
MemoryData               stages.1.0               0 1 51 0=64
Convolution              conv_8                   1 1 50 52 0=64 1=2 11=2 12=1 13=2 14=0 2=1 3=2 4=0 5=1 6=8192
Split                    splitncnn_6              1 2 52 53 54
ConvolutionDepthWise     convdw_53                1 1 54 55 0=64 1=7 11=7 12=1 13=1 14=3 2=1 3=1 4=3 5=1 6=3136 7=64
Permute                  permute_42               1 1 55 56 0=3
LayerNorm                ln_1                     1 1 56 57 0=64 1=1.000000e-06 2=1
InnerProduct             linear_14                1 1 57 58 0=256 1=1 2=16384
Split                    splitncnn_7              1 2 58 59 60
Sigmoid                  sigmoid_26               1 1 60 61
BinaryOp                 mul_19                   2 1 59 61 62 0=2
InnerProduct             linear_15                1 1 62 63 0=64 1=1 2=16384
BinaryOp                 mul_20                   2 1 51 63 64 0=2
Permute                  permute_43               1 1 64 65 0=4
BinaryOp                 add_21                   2 1 53 65 66 0=0
Split                    splitncnn_8              1 3 66 67 68 69
Reduction                mean_35                  1 1 69 70 0=3 1=0 -23303=1,0 4=1 5=1
Split                    splitncnn_9              1 2 70 71 72
BinaryOp                 sub_22                   2 1 67 71 73 0=1
BinaryOp                 pow_23                   1 1 73 74 0=6 1=1 2=2.000000e+00
MemoryData               pnnx_fold_217            0 1 75 0=1 1=1 2=64
MemoryData               pnnx_fold_221            0 1 76 0=1 1=1 2=64
Reduction                mean_36                  1 1 74 77 0=3 1=0 -23303=1,0 4=1 5=1
BinaryOp                 add_24                   1 1 77 78 0=0 1=1 2=1.000000e-06
UnaryOp                  sqrt_25                  1 1 78 79 0=5
BinaryOp                 sub_26                   2 1 68 72 80 0=1
BinaryOp                 div_27                   2 1 80 79 81 0=3
BinaryOp                 mul_28                   2 1 75 81 82 0=2
BinaryOp                 add_29                   2 1 82 76 83 0=0
MemoryData               stages.2.0               0 1 84 0=128
Convolution              conv_9                   1 1 83 85 0=128 1=2 11=2 12=1 13=2 14=0 2=1 3=2 4=0 5=1 6=32768
Split                    splitncnn_10             1 2 85 86 87
ConvolutionDepthWise     convdw_54                1 1 87 88 0=128 1=7 11=7 12=1 13=1 14=3 2=1 3=1 4=3 5=1 6=6272 7=128
Permute                  permute_44               1 1 88 89 0=3
LayerNorm                ln_2                     1 1 89 90 0=128 1=1.000000e-06 2=1
InnerProduct             linear_16                1 1 90 91 0=512 1=1 2=65536
Split                    splitncnn_11             1 2 91 92 93
Sigmoid                  sigmoid_27               1 1 93 94
BinaryOp                 mul_30                   2 1 92 94 95 0=2
InnerProduct             linear_17                1 1 95 96 0=128 1=1 2=65536
BinaryOp                 mul_31                   2 1 84 96 97 0=2
Permute                  permute_45               1 1 97 98 0=4
BinaryOp                 add_32                   2 1 86 98 99 0=0
Split                    splitncnn_12             1 2 99 100 101
MemoryData               stages.2.1               0 1 102 0=128
ConvolutionDepthWise     convdw_55                1 1 101 103 0=128 1=7 11=7 12=1 13=1 14=3 2=1 3=1 4=3 5=1 6=6272 7=128
Permute                  permute_46               1 1 103 104 0=3
LayerNorm                ln_3                     1 1 104 105 0=128 1=1.000000e-06 2=1
InnerProduct             linear_18                1 1 105 106 0=512 1=1 2=65536
Split                    splitncnn_13             1 2 106 107 108
Sigmoid                  sigmoid_28               1 1 108 109
BinaryOp                 mul_33                   2 1 107 109 110 0=2
InnerProduct             linear_19                1 1 110 111 0=128 1=1 2=65536
BinaryOp                 mul_34                   2 1 102 111 112 0=2
Permute                  permute_47               1 1 112 113 0=4
BinaryOp                 add_35                   2 1 100 113 114 0=0
Split                    splitncnn_14             1 2 114 115 116
MemoryData               stages.2.2               0 1 117 0=128
ConvolutionDepthWise     convdw_56                1 1 116 118 0=128 1=7 11=7 12=1 13=1 14=3 2=1 3=1 4=3 5=1 6=6272 7=128
Permute                  permute_48               1 1 118 119 0=3
LayerNorm                ln_4                     1 1 119 120 0=128 1=1.000000e-06 2=1
InnerProduct             linear_20                1 1 120 121 0=512 1=1 2=65536
Split                    splitncnn_15             1 2 121 122 123
Sigmoid                  sigmoid_29               1 1 123 124
BinaryOp                 mul_36                   2 1 122 124 125 0=2
InnerProduct             linear_21                1 1 125 126 0=128 1=1 2=65536
BinaryOp                 mul_37                   2 1 117 126 127 0=2
Permute                  permute_49               1 1 127 128 0=4
BinaryOp                 add_38                   2 1 115 128 129 0=0
Split                    splitncnn_16             1 3 129 130 131 132
Reduction                mean_37                  1 1 132 133 0=3 1=0 -23303=1,0 4=1 5=1
Split                    splitncnn_17             1 2 133 134 135
BinaryOp                 sub_39                   2 1 130 134 136 0=1
BinaryOp                 pow_40                   1 1 136 137 0=6 1=1 2=2.000000e+00
MemoryData               pnnx_fold_340            0 1 138 0=1 1=1 2=128
MemoryData               pnnx_fold_344            0 1 139 0=1 1=1 2=128
Reduction                mean_38                  1 1 137 140 0=3 1=0 -23303=1,0 4=1 5=1
BinaryOp                 add_41                   1 1 140 141 0=0 1=1 2=1.000000e-06
UnaryOp                  sqrt_42                  1 1 141 142 0=5
BinaryOp                 sub_43                   2 1 131 135 143 0=1
BinaryOp                 div_44                   2 1 143 142 144 0=3
BinaryOp                 mul_45                   2 1 138 144 145 0=2
BinaryOp                 add_46                   2 1 145 139 146 0=0
MemoryData               stages.3.0               0 1 147 0=256
Convolution              conv_10                  1 1 146 148 0=256 1=2 11=2 12=1 13=2 14=0 2=1 3=2 4=0 5=1 6=131072
Split                    splitncnn_18             1 2 148 149 150
ConvolutionDepthWise     convdw_57                1 1 150 151 0=256 1=7 11=7 12=1 13=1 14=3 2=1 3=1 4=3 5=1 6=12544 7=256
Permute                  permute_50               1 1 151 152 0=3
LayerNorm                ln_5                     1 1 152 153 0=256 1=1.000000e-06 2=1
InnerProduct             linear_22                1 1 153 154 0=1024 1=1 2=262144
Split                    splitncnn_19             1 2 154 155 156
Sigmoid                  sigmoid_30               1 1 156 157
BinaryOp                 mul_47                   2 1 155 157 158 0=2
InnerProduct             linear_23                1 1 158 159 0=256 1=1 2=262144
BinaryOp                 mul_48                   2 1 147 159 160 0=2
Permute                  permute_51               1 1 160 161 0=4
BinaryOp                 add_49                   2 1 149 161 162 0=0
Reduction                mean_39                  1 1 162 163 0=3 1=0 -23303=2,-2,-1 4=0 5=1
LayerNorm                ln_11                    1 1 163 164 0=256 1=1.000000e-06 2=1
InnerProduct             fcsigmoid_0              1 1 164 out0 0=8 1=1 2=2048 9=4

## how to reproduce | 复现步骤 | 再現方法
1.前处理：
    cv::Mat img = cv::imread("/root/Point/ncnn_signal/img/aomianjing.jpg");
    int w = img.cols;
    int h = img.rows;
    cv::cvtColor(img, img, CV_BGR2RGB);
    // subtract 128, norm to -1 ~ 1
    ncnn::Mat in = ncnn::Mat::from_pixels_resize(img.data, ncnn::Mat::PIXEL_RGB, w, h, 192, 192);
    float norm[3] = {1 / 255.f, 1 / 255.f, 1 / 255.f};
    float mean[3] = {0, 0, 0};
    in.substract_mean_normalize(mean, norm);
2.确认了图片输入和前处理是没有问题的，用其它模型能跑出正确结果
3. sub_4  div_5  mul_6 层的输出为inf（不知道是否正常），splitncnn_2层的输出就是-nan，最终输出是全为0

**Comment by nihui** [comment]
nn.Linear 转换为 ncnn InnerProduct 没有正确处理 3-dim 输入的情况

**Comment by crossover10** [comment]
是的，convnext的block实现基本模块的方式有两种，分别是7*7卷积 + Permute + LN + Permute + 1*1卷积 + GELU + 1*1卷积
norm_layer(dim)或者7*7卷积 + Permute + LN + Linear + GELU + Linear + Permute

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/bc8e939c85e4dd7d1af38592a38b69b68b5900f9 修复了转换问题
pnnx 自动在 Linear 前后添加 reshape，并加上了 convnext 模型的单元测试
