### ISSUE TITLE
inner product输出纬度问题 

### ISSUE THREAD

**Issue by chongt123** [Tencent/ncnn#3934]
## detail | 详细描述 | 詳細な説明
您好 我现在有一个输入 是1x4x52 输入到inner product中 它的输出是应该是 1x4x80 但是 我得到的是80个元素 这是什么原因呢 onnx那边没有问题

**Comment by nihui** [comment]
ncnn 不需要 batch 维度，输入 4x52 便会输出 4x80

**Comment by chongt123** [comment]
哦哦 感谢

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
