### ISSUE TITLE
多线程环境下启用OpenMP导致内存泄漏

### ISSUE THREAD

**Issue by Elvisass** [Tencent/ncnn#3938]
## error log | 日志或报错信息 | ログ
无日志。
多线程同时反复加载/卸载模型后，进程占用的内存不断增加（top指令中的VIRT与RES），一段时间后最终触发OOM。
使用ASan无法追踪到泄漏点，使用Valgrind测试会导致崩溃（可能与OpenMP有关）。
编译选项中关闭`NCNN_OPENMP`后，症状消失，内存波动稳定。

## context | 编译/运行环境 | バックグラウンド
编译&运行环境：Ubuntu 18.04 x86_64，内存16GB，GPU GTX1080Ti*2。
编译版本：[tag 20220420(commit 7600270)](https://github.com/Tencent/ncnn/tree/7600270430863ea0ce85fa0d65892151a734b382)
编译配置：`cmake -DNCNN_VULKAN=ON -DENABLE_HLSL=ON -DENABLE_OPT=ON -DENABLE_SPVREMAPPER=ON -DNCNN_BUILD_EXAMPLES=OFF -DNCNN_SHARED_LIB=ON ../ncnn_src`

## how to reproduce | 复现步骤 | 再現方法
测试关键代码示例：
``` Cpp
size_t load_file(const char* path, unsigned char** data);

void test()
{
    unsigned char *param, *bin;
    size_t param_size = load_file("./model.param", &param);
    size_t bin_size = load_file("./model.bin", &bin);
    
    ncnn::Net* net = new ncnn::Net();
    net->opt.lightmode = true;
    net->opt.use_fp16_arithmetic = true;
    net->opt.use_vulkan_compute = true;
    _net->load_param(ncnn::DataReaderFromMemory(param));
    _net->load_model(ncnn::DataReaderFromMemory(bin));

    sleep(0);

    delete net;
    free(bin);
    free(param);
}

int main()
{
    for(int loop = 0; loop < 10000; ++loop)
    {
        printf("Test loop #%d...\n", loop);
        std::vector<std::thread> ths;
        for(int tc = 0; tc < 5; ++tc)
        {
            ths.push_back(std::thread(&test));
        }
        for(auto& t : ths)
        {
            t.join();
        }
    }
    ncnn::destroy_gpu_instance();
    return 0;
}
```

## more | 其他 | その他
- 关闭OpenMP的想法是通过`__free_hook`得到的，它的内存操作存在大量`::free(NULL)`的调用，不确定是否为指针数据错误。
- 测试过程中发现，在`ncnn::Net::load_model(const DataReader&)`中，如果不执行`Layer::create_pipeline()` (Line 1866 in src/net.cpp) 以及其后的代码，则内存问题消失；但在`create_pipeline`函数中未找到omp相关代码，现象原因不明。

**Comment by wzyforgit** [comment]
这个测试牛逼了，插个眼

**Comment by nihui** [comment]
openmp代码应该没有问题，这是大部分openmp实现行为，包括libgomp libomp
每次创建 user thread，比如 std::thread，都会新开辟一个线程池，这个线程池在 user thread 结束后不会销毁，以便后面可能再次需要时，不用再创建一遍
你的代码实际创建了 50000 个 user thread

ncnn自带的simpleomp没有遵循openmp标准行为，于是总是复用同一个线程池，因此不会发生创建许多线程池的问题

**Comment by Elvisass** [comment]
> ncnn自带的simpleomp没有遵循openmp标准行为，于是总是复用同一个线程池，因此不会发生创建许多线程池的问题

开启simpleomp后依然会有这样的问题，omp实现用gomp/libomp也一样，查代码也看不出什么问题……

最后发现换个编译器能避免这个问题，原先使用的是Ubuntu18.04配套的gcc7，换成gcc11或者clang就没有出现了。
检查编译环境应该没什么污染，但总不能是编译器bug吧……先顶着用，不折腾了
