### ISSUE TITLE
 Build for Android -build aarch64 library的问题

### ISSUE THREAD

**Issue by Andrawzyf** [Tencent/ncnn#394]
当我编译build aarch64 library，执行cmake遇到如下问题：

zyn@ubuntu:~/NCNN/ncnn/build-android-aarch64$ echo $NDK_HOME
/home/zyn/android-ndk-r13b
zyn@ubuntu:~/NCNN/ncnn/build-android-aarch64$ cmake -DCMAKE_TOOLCHAIN_FILE=$NDK_HOME/build/cmake/android.toolchain.cmake \ -DANDROID_ABI="arm64-v8a" \ -DANDROID_PLATFORM=android-24 ..
-- CMAKE_TOOLCHAIN_FILE = /home/zyn/android-ndk-r13b/build/cmake/android.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /home/zyn/NCNN/ncnn/build-android-aarch64/install
-- Android: Selected GCC toolchain 'arm-linux-androideabi-4.9'
-- Check for working C compiler: /home/zyn/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
-- Check for working C compiler: /home/zyn/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -- broken
CMake Error at /usr/local/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
  The C compiler
  "/home/zyn/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /home/zyn/NCNN/ncnn/build-android-aarch64/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_fa591/fast"

  /usr/bin/make -f CMakeFiles/cmTC_fa591.dir/build.make
  CMakeFiles/cmTC_fa591.dir/build

  make[1]: Entering directory
  `/home/zyn/NCNN/ncnn/build-android-aarch64/CMakeFiles/CMakeTmp'

  Building C object CMakeFiles/cmTC_fa591.dir/testCCompiler.c.o

  
  /home/zyn/android-ndk-r13b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
  -target armv7-none-linux-androideabi
  --sysroot=/home/zyn/android-ndk-r13b/platforms/android-24/arch-arm -isystem
  /home/zyn/android-ndk-r13b/platforms/android-24/arch-arm/usr/include
  -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong
  -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16
  -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat
  -Werror=format-security -O0 -fno-limit-debug-info -fPIE -o
  CMakeFiles/cmTC_fa591.dir/testCCompiler.c.o -c
  /home/zyn/NCNN/ncnn/build-android-aarch64/CMakeFiles/CMakeTmp/testCCompiler.c

  arm-linux-androideabi-gcc: error: armv7-none-linux-androideabi: No such
  file or directory

  arm-linux-androideabi-gcc: error: unrecognized command line option
  '-target'

  arm-linux-androideabi-gcc: error: unrecognized command line option
  '-fno-integrated-as'

  arm-linux-androideabi-gcc: error: unrecognized command line option
  '-fno-limit-debug-info'

  make[1]: *** [CMakeFiles/cmTC_fa591.dir/testCCompiler.c.o] Error 1

  make[1]: Leaving directory
  `/home/zyn/NCNN/ncnn/build-android-aarch64/CMakeFiles/CMakeTmp'

  make: *** [cmTC_fa591/fast] Error 2

**Comment by nihui** [comment]
you may try updating android ndk r15c or newer

**Comment by Andrawzyf** [comment]
@nihui just now i updated to android-ndk r16b,still faied

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-android
