### ISSUE TITLE
c_api接口是否可以添加以下获取输入输出name或者index的接口

### ISSUE THREAD

**Issue by kingsoft-wps** [Tencent/ncnn#3942]
## detail | 详细描述 | 詳細な説明
看到net.h中有获取输入输出的name及index接口
 // get input/output indexes/names
    const std::vector<int>& input_indexes() const;
    const std::vector<int>& output_indexes() const;
#if NCNN_STRING
    const std::vector<const char*>& input_names() const;
    const std::vector<const char*>& output_names() const;
#endif
但是c_api.h中没有，对外使用感觉不是很合理，可否在c_api.h中添加一下该功能的标准c接口

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4534

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/833f6ed8e47da51584b77e29ca6075148aa2f107
已添加
