### ISSUE TITLE
可以直接修改parm文件参数，从而改变网络结构么？

### ISSUE THREAD

**Issue by Andrawzyf** [Tencent/ncnn#395]
ncnn的文件开头是几个数字，比如VGG16是：
7767517
40 40
然后是
Input            data             0 1 data 0=3 1=224 2=224
Convolution      conv1_1          1 1 data conv1_1 0=64 1=3 2=1 3=1 4=1 5=1 6=1728
接着后面各种网络描述，那么现在可以直接吧后面的删除或者改变么？比如就保留
7767517
40 40
Input            data             0 1 data 0=3 1=224 2=224
Convolution      conv1_1          1 1 data conv1_1 0=64 1=3 2=1 3=1 4=1 5=1 6=1728 那么它是不是就是一层卷积网络，然后就可以直接用？

**Comment by gfjiangly** [comment]
可以吗

**Comment by nihui** [comment]
可以参考这个修改 https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure
