### ISSUE TITLE
[Question] Battery optimization Android

### ISSUE THREAD

**Issue by ankandrew** [Tencent/ncnn#3958]
Are there any general tips to maintain a lower batter consumption for Android devices? It seems `use_vulkan_compute` uses more battery than we just using CPU inference, is that true? Lowering threads 4 ->1 can also decrease battery usage? Any other advice?

**Comment by wzyforgit** [comment]
"use_vulkan_compute" will try to use GPU, this will of course cause use more battery.
If your device's CPU is ARM architecture, you can try to bind your thread on little core.
Use "ncnn::set_cpu_powersave(1);" to do this

**Comment by ankandrew** [comment]
> "use_vulkan_compute" will try to use GPU, this will of course cause use more battery. If your device's CPU is ARM architecture, you can try to bind your thread on little core. Use "ncnn::set_cpu_powersave(1);" to do this

@wzyforgit I have an intense battery consumption in Android (ARM arch) and changing to use `ncnn::set_cpu_powersave(1)` didn't save my battery. I currently have 2 models that are loaded in memory and using:

```
Model 1:
- num_threads 4
- fp32 used
- vulkan disabled
Model2 :
- num_threads 4
- fp32 used
- vulkan disabled
```

What would you do in this case to save some battery in terms of model configuration?

**Comment by nihui** [comment]
opt.openmp_blocktime = 0

**Comment by ankandrew** [comment]
@nihui that didn't seem to help :(. I forgot to mention I'm running inference every 300 ms constantly. Any ideas?
