### ISSUE TITLE
extract 最后的fc blob出来的Mat是empty的

### ISSUE THREAD

**Issue by frankieGitHub** [Tencent/ncnn#396]
Hi ，
  我使用的是caffe模型转为ncnn的模型，使用example里的squeezencnn，可以正常加载模型。
在运行时，也正常输入in Mat，可是extract最后的FC层的top blob确是空的，如果往前面几层是有数据的，请问，这种问题应该如何排查，谢谢。

**Comment by PipeBlack** [comment]
什么平台下的（Android ios 或pc），能把你喂数据到提取数据那几句代码发一下吗？

**Comment by frankieGitHub** [comment]
@PipeBlack

**Comment by PipeBlack** [comment]
@frankieGitHub 
ex.extract(net_param_id::BLOB_fc5, out);
这个函数是有返回值的，你打出来看一下是多少？
你是用caffe2ncnn、ncnn2mem自己转的吗？编译的vs版本是哪一个？
issue#391是我提的问题，不知道是不是同样的原因造成的

**Comment by frankieGitHub** [comment]
@PipeBlack 
返回值-100

**Comment by frankieGitHub** [comment]
@PipeBlack 看样子现象是一样的

**Comment by PipeBlack** [comment]
@frankieGitHub 
没。。我以不同的方式得到Mat in喂进网络，还有ex.extract(）返回0，但out.w也为0的情况。出问题的原因在慢慢找
我更换了另一个网络，这次没有问题。

**Comment by PipeBlack** [comment]
@frankieGitHub 参考这个 https://github.com/Tencent/ncnn/wiki/cmake-打包-android-sdk
生成libncnn.a,取代从releases中下载的可以解决
make package这一句显示
make: *** No rule to make target 'package'.  Stop.
issue#38说make package这句不需要
