### ISSUE TITLE
在代码中如何查看版本号？

### ISSUE THREAD

**Issue by geoffzhang** [Tencent/ncnn#3961]
## detail | 详细描述 | 詳細な説明
您好，请问在代码中如何查看版本号？

**Comment by zchrissirhcz** [comment]
1. C++ 接口
```c++
#include "platform.h"
#include <stdio.h>

int main()
{
    printf("ncnn version: %s\n", NCNN_VERSION_STRING);
    return 0;
}
```

2. C 接口
```c
#include "c_api.h"
#include <stdio.h>

int main()
{
    printf("ncnn version: %s\n", ncnn_version());
}
```

**Comment by zchrissirhcz** [comment]
3. CMake 方式
在编译 ncnn 时， 根目录的 CMakeLists.txt 自动打印了当前版本：
```cmake
message(STATUS "NCNN_VERSION_STRING = ${NCNN_VERSION_STRING}")
```

4. pyncnn (ncnn Python库）
适用于已经执行了 `python -m pip install -U pip && pip install ncnn`情况
```python
import ncnn
print(ncnn.__version__)
```
>'1.0.20220420'

5. 通过ncnn安装路径
适用于从 ncnn 的 github prebuilt（预编译包）下载后解压、并保持目录名称的情况。
例如我解压到 /home/zz/artifacts/ncnn/ncnn-20220420-android ， 那么它的版本是 20220420

6. git 源码方式
查看当前 git commit 信息，以及对应的 git tag 信息。
ncnn 使用 年月日 格式的版本号，而不是“1.2.3”这样的数字版本号。

**Comment by geoffzhang** [comment]
> 1. C++ 接口
> 
> ```c++
> #include "platform.h"
> #include <stdio.h>
> 
> int main()
> {
>     printf("ncnn version: %s\n", NCNN_VERSION_STRING);
>     return 0;
> }
> ```
> 
> 2. C 接口
> 
> ```c
> #include "c_api.h"
> #include <stdio.h>
> 
> int main()
> {
>     printf("ncnn version: %s\n", ncnn_version());
> }
> ```
好的，谢谢
