### ISSUE TITLE
peleeNet caffe模型转ncnn后推理错误

### ISSUE THREAD

**Issue by ppl21847** [Tencent/ncnn#3963]
##同样的peleeNet onnx转ncnn后推理结果没问题，caffe转onnx后推理结果错误

## Centos7.6 CPU
![image](https://user-images.githubusercontent.com/34120042/176089491-122ce591-4ed2-41cc-be5b-384899c6668c.png)
输出经过SoftMax后再Concat，通过对比tensorRT  SoftMax已经不对了，Concat前后也不一致。

**Comment by ppl21847** [comment]
![image](https://user-images.githubusercontent.com/34120042/176091507-a04c00f9-9f68-4223-af01-be7555d3790b.png)
![image](https://user-images.githubusercontent.com/34120042/176091650-9bb453a0-3f88-450e-adb0-731d4771dbcf.png)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
