### ISSUE TITLE
自己做均值方差预处理后的cv::mat 图片,转成 ncnn::Mat 后,预测结果与 caffe差很多

### ISSUE THREAD

**Issue by Orangels** [Tencent/ncnn#397]
图片预处理需要短边 resize 到256,然后 center crop 到224, 然后均值方差
用 ncnn 处理的时候,短边 resize 到256后调用
 `ncnn::Mat in = ncnn::Mat::from_pixels_resize(bgr.data,ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows, 224, 224);`
`const float mean_vals[3] = {103.52f, 116.28f, 123.675f};`
`const float norm_vals[3] = {1/57.38f,1/57.12f,1/58.40f};`
 `in.substract_mean_normalize(mean_vals, norm_vals);`
这样跑 500 个测试,测试top_1 比 caffe 低了10%
之后自己实现均值方差预处理.只调用
`ncnn::Mat in = ncnn::Mat::from_pixels(bgr.data, ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows);`
`ncnn::Extractor ex = mobileNet.create_extractor();`
结果更差, 预处理和 caffe 的预处理都一样
请问问题大概出现在什么地方?

**Comment by jnulzl** [comment]
@Orangels “PIXEL_BGR”是否应该是“PIXEL_RGB”;

**Comment by lovehuanhuan** [comment]
or PIXEL_BGR_TO_RGB

**Comment by hanfanggithub** [comment]
crop 要加clone from_pixels 需要连续buffer ，RGB还是BGR 要看你原模型是哪种输入

**Comment by nihui** [comment]
可以参考faq，检查下
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result

如果还有问题，可以 reopen issue 继续讨论
