### ISSUE TITLE
x86平台下，int8量化后，modnet模型速度无明显变化

### ISSUE THREAD

**Issue by huaixia30** [Tencent/ncnn#3998]
## expectation | 诉求 | 期待する
1. 量化前，模型推理时间40~50ms；量化后，模型推理时间50~60ms；
2. 调试推理代码，发现convolution::create_pipeline()中 if (opt.use_int8_inference && weight_data.elemsize == (size_t)4u && int8_scale_term)始终无法满足；
3. 请问 看到nihui说过ncnn的优化是针对arm平台的，不支持x86平台，具体是哪一块不支持？x86底层加速指令没写吗？

**Comment by nihui** [comment]
最新的ncnn对x86平台也做了几波优化，推荐更新再试试，如有问题，可reopen issue继续交流
