### ISSUE TITLE
ios 平台下 wiki 步骤 make报错，如何解决，问题如下图

### ISSUE THREAD

**Issue by ZanderDev** [Tencent/ncnn#4]
![2017-07-24 2 23 35](https://user-images.githubusercontent.com/2055370/28510607-f58c5eb8-707b-11e7-8971-4643a46b5bd4.png)

**Comment by Librazy** [comment]
请问cmake生成过程中有什么异常输出麽？提供了所有cmake依赖了吗？

**Comment by chenkun2015** [comment]
添加好了么？

**Comment by Librazy** [comment]
我自己没有ios工具链，不过在wiki有一个相关的 https://github.com/Tencent/ncnn/wiki/ios-%E4%BD%BF%E7%94%A8-openmp

**Comment by nihui** [comment]
ios 的工程是我是在 fedora linux 上交叉编译的那种
主要是 mac os 上面的工具链不支持 openmp，所以后来没试过了
恩，大概会放个编译好的 framework ...

**Comment by shiquanwang** [comment]
up主在一台Mac上安装了Fedora并且使用各种手段完成了对iOS的交叉编译支持，棒棒哒

**Comment by nihui** [comment]
预编译好的库放在 releases 那边了，应该能直接用
https://github.com/Tencent/ncnn/releases
