### ISSUE TITLE
如何编译examples/squeezenet.cpp

### ISSUE THREAD

**Issue by junedgar** [Tencent/ncnn#40]
现在mac直接跑squeezenet.cpp这个demo
1、cmake .  然后make，出现下面错误，手动在src下添加"platform.h"后出现（2）的错误
![image](https://user-images.githubusercontent.com/17995658/28618869-8dbe0fca-7238-11e7-95a3-fb8378fb209e.png)
2、新出现错误
![image](https://user-images.githubusercontent.com/17995658/28618917-c09e1b06-7238-11e7-9d2f-2fd4e222c38c.png)
3、在CMakeLists.txt 添加include_directories(${OpenCV_INCLUDE_DIRS})后又出现新的错误：
![image](https://user-images.githubusercontent.com/17995658/28618993-13a1bc18-7239-11e7-872d-80f5f6c681a7.png)
4、指定libncnn.a绝对路径后又出现新的错误
![image](https://user-images.githubusercontent.com/17995658/28619081-5a7a5a32-7239-11e7-9776-2912ca1bbdd0.png)

第二条错误跟第四条的错误是一样的，又回来了/(ㄒoㄒ)/~~
菜鸟，望各位大神指点……

**Comment by nihui** [comment]
顶层的 CMakeLists.txt 把最后的 # add_subdirectory(examples) 取消注释
然后直接用顶层的 CMakeLists.txt 编译 ...

**Comment by junedgar** [comment]
@nihui 直接用顶层编译出现的错误是这个
![image](https://user-images.githubusercontent.com/17995658/28628736-100544b6-7258-11e7-8c92-26c17bcbb041.png)

**Comment by junedgar** [comment]
已经解决了，我同时装了opencv2,opencv3本来想着平时可以随意切换没问题，结果检测的时候老是检测到3.2版本去了
