### ISSUE TITLE
基于GRU的模型在安卓arm64设备上20220701版本输出错误，x64设备或者20220420版本无问题

### ISSUE THREAD

**Issue by XFY9326** [Tencent/ncnn#4007]
## error log | 日志或报错信息 | ログ
![image](https://user-images.githubusercontent.com/14016892/177881946-c05ed68f-80a9-4da3-8c0b-bcd2524a0fd5.png)  
两个输入到GRU，两个输出分别为InnerProduct的输出和GRU的另一个输出  
InnerProduct的输出的出现错误的nan

## context | 编译/运行环境 | バックグラウンド
Windows 11  
AndroidStudio 2021.2.1 Patch 1  
Android SDK 32  
Android NDK 24.0.8215888  
CMake 3.18.1  
JDK 11  

安卓arm64设备: 骁龙888 骁龙865  

pnnx为20220701版本  
模型转换：pytorch->torchscript->pnnx->ncnn->ncnn fp16

## how to reproduce | 复现步骤 | 再現方法
1. 下载附件，用AS启动并下载配置ncnn-20220420-android-vulkan-shared.zip和ncnn-20220701-android-vulkan-shared.zip
2. 运行AS项目，在安卓arm64设备就可以看到20220701版本logcat输出的nan，20220420版本不会
3. 在安卓x64虚拟机可以看到20220701版本和20220420版本输出正常

如果只有GRU层，我测试下来就没有这个问题  
如果用onnx2ncnn导出上面这个模型，这个问题依然存在  

## more | 其他 | その他
打印的Mat与AS项目文件如下
[error_report.zip](https://github.com/Tencent/ncnn/files/9067659/error_report.zip)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4008
