### ISSUE TITLE
申请为docs/developer-guide/完善提出PR

### ISSUE THREAD

**Issue by DC-Zhou** [Tencent/ncnn#4012]
## detail | 详细描述 | 詳細な説明
[ncnn](https://github.com/Tencent/ncnn)/[docs](https://github.com/Tencent/ncnn/tree/master/docs)/developer-guide/
目前直接可以更新的：
1. 编写sse 和 avx 加速算子，类似：how-to-write-a-sse-optimized-op-kernel.md & how-to-write-a-avx-optimized-op-kernel.md；
2. 更新 [how-to-write-a-neon-optimized-op-kernel.md](https://github.com/Tencent/ncnn/blob/master/docs/developer-guide/how-to-write-a-neon-optimized-op-kernel.md)
以上预计一周左右能够完毕，如确认需要更新我就开始动手做；
如果这种申请格式不正确，也可以通过联系 开源摘星计划那边提出issue 的任务委托，我来申请

**Comment by nihui** [comment]
欢迎贡献！feel free！
