### ISSUE TITLE
ncnn切换vulkan计算时闪退

### ISSUE THREAD

**Issue by XJTUWYD** [Tencent/ncnn#4024]
## error log | 日志或报错信息 | ログ
`2022-07-12 10:51:30.907 5593-5593/com.lenovo.nn_project A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc0 in tid 5593 (novo.nn_project), pid 5593 (novo.nn_project)`
在切换了vulkan之后在图计算出现闪退崩溃的现象,cpu下可以正常运行出结果.
配置代码如下:
![2022-07-12_11-02](https://user-images.githubusercontent.com/30773960/178399471-1d0aa20a-833a-4ade-88b1-cd47a06191b9.png)
运行时opt参数如下:
![2022-07-12_10-57](https://user-images.githubusercontent.com/30773960/178399256-5ed6b994-622f-486d-86a0-69ec92bd0ace.png)

## context | 编译/运行环境 | バックグラウンド
ndk 21.1.6352462 安卓12  ncnn-20220701-android-vulkan

**Comment by nihui** [comment]
opt 应当在 load_param 前设置

**Comment by XJTUWYD** [comment]
感谢小姐姐,成功解决了我的问题,谢谢

**Comment by XJTUWYD** [comment]
> opt 应当在 load_param 前设置

感谢小姐姐,成功解决了我的问题,谢谢
