### ISSUE TITLE
vs2017 Debug  编译错误

### ISSUE THREAD

**Issue by 121786404** [Tencent/ncnn#403]
call "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

cd protobuf-3.4.0
rm -rf build-vs2017-debug
mkdir build-vs2017-debug
cd build-vs2017-debug
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%cd%/install -Dprotobuf_BUILD_TESTS=OFF -Dprotobuf_MSVC_STATIC_RUNTIME=OFF ../cmake
nmake
nmake install
cd ../..

cd ncnn
rm -rf build-vs2017-debug
mkdir build-vs2017-debug
cd build-vs2017-debug
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%cd%/install -DProtobuf_INCLUDE_DIR=E:/Code/ncnn/protobuf-3.4.0/build-vs2017-debug/install/include -DProtobuf_LIBRARIES=E:/Code/ncnn/protobuf-3.4.0/build-vs2017-debug/install/lib/libprotobuf.lib -DProtobuf_PROTOC_EXECUTABLE=E:/Code/ncnn/protobuf-3.4.0/build-vs2017-debug/install/bin/protoc.exe ..
nmake
nmake install

tool 中的 caffe  onnx 链接会错误

**Comment by yinghuang** [comment]
debug模式下，protobuf生成的是libprotobufd.lib，所以要把libprotobuf.lib改为libprotobufd.lib
