### ISSUE TITLE
编译ncnn出错 。

### ISSUE THREAD

**Issue by Andrawzyf** [Tencent/ncnn#404]
cmake完后，执行make指令，出错，错误如下：
[  1%] Running C++ protocol buffer compiler on onnx.proto
onnx.proto:383:5: Expected "required", "optional", or "repeated".
onnx.proto:383:17: Missing field number.
onnx.proto:402:3: Expected "required", "optional", or "repeated".
onnx.proto:402:15: Missing field number.
make[2]: *** [tools/onnx/onnx.pb.cc] Error 1
[  2%] Running C++ protocol buffer compiler on caffe.proto
make[1]: *** [tools/onnx/CMakeFiles/onnx2ncnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target mxnet2ncnn

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/issues/370
duplicated

**Comment by Andrawzyf** [comment]
@nihui 是这样的，感谢~~~~~~~~~~~~
