### ISSUE TITLE
量化某个模型出错：malloc_consolidate(): invalid chunk size

### ISSUE THREAD

**Issue by liamsun2019** [Tencent/ncnn#4069]
## error log
mean = [0.000000,0.000000,0.000000]
norm = [1.000000,1.000000,1.000000]
shape = [3,256,256]
pixel = RGB
thread = 16
method = kl
---------------------------------------
count the absmax 0.00% [ 0 / 8831 ]
malloc_consolidate(): invalid chunk size
Aborted (core dumped)

## context 
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

## how to reproduce
1. build ncnn tools
2. utilize ncnn2table to generage quantization table
./ncnn2table  test.opt.param test.opt.bin imagelist.txt test.table mean=[0.0,0.0,0.0] norm=[1.0,1.0,1.0] shape=[3,256,256] pixel=RGB method=kl

## more
test.opt.param and test.opt.bin themselves work normally for ncnn. They are in fp32 representation. Pls refer to the attachment.

[test.zip](https://github.com/Tencent/ncnn/files/9163670/test.zip)

**Comment by liamsun2019** [comment]
做了实验，看起来shape要指定为 [256,256,3]，也就是HWC的形式。这里有个疑问，我的原始模型是onnx， input shape是CHW，那么转成ncnn内部格式后，是否意味着输入就变成HWC了？

**Comment by liamsun2019** [comment]
使用ncnn2table以及ncnn2int8后，生成量化后的Param和bin档，但是加载后运行，会报告：
find_blob_index_by_name input.1 failed
Try
find_blob_index_by_name 758 failed
Try

用netron观察，看起来输入输出节点名字并没有变化，但是weight的类型，却是个问号，预期应该是int8才对。

刚开始用Ncnn的量化功能，还请指点，Thanks.
![weight](https://user-images.githubusercontent.com/51946663/180346671-96b53848-6111-490a-8fbf-b5cfb53cf73e.jpg)

**Comment by nihui** [comment]
是不是32位编译的？32位程序很可能内存不够

**Comment by liamsun2019** [comment]
执行arch
 arch 
x86_64

确认是64bit。试验发现input shape设定为HWC就没有问题，设定为CHW就会发生malloc_consolidate(): invalid chunk size错误。所以我才问是不是转成Ncnn内部格式后，输入一定要设定为HWC(虽然我的onnx模型input shape是CHW)。如果是的话，那么就是我的使用问题了。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
使用上可以参考这个文档
shape is the blob shape of your model, [w,h] or [w,h,c]

**Comment by liamsun2019** [comment]
好的，多谢指点
