### ISSUE TITLE
mips 3A3000 不能加载 模型，报1560错误

### ISSUE THREAD

**Issue by znsoftm** [Tencent/ncnn#4072]
## context | 编译/运行环境 | バックグラウンド
mips 龙芯3a3000    Linux e14a76645b8f 3.10.0-514.26.2.ns7.030.mips64el

gcc version 7.3.1 20180303 (Red Hat 7.3.1-6) (GCC)

## how to reproduce | 复现步骤 | 再現方法
1.  直接加载附件的两个文件
2. load_param 报错 1560
3.  load_model 报错  483908

## more | 其他 | その他
[srcdet-v3.zip](https://github.com/Tencent/ncnn/files/9165757/srcdet-v3.zip)

**Comment by nihui** [comment]
暂时没有3A3000设备，在x86 linux下测试没有问题，可以尝试更新最新的ncnn代码
贴一下完整的stderr输出信息

```cpp
int main()
{
    ncnn::Net net;

    net.load_param("srcdet-v3.param");
    net.load_model("srcdet-v3.bin");

    ncnn::Extractor ex = net.create_extractor();

    ncnn::Mat in0(120);
    in0.fill(0.f);

    ex.input("in0", in0);

    ncnn::Mat out0;
    ex.extract("out0", out0);

    fprintf(stderr, "out0 %d %d %d %d\n", out0.w, out0.h, out0.d, out0.c);

    pretty_print(out0);

    return 0;
}
```

**Comment by znsoftm** [comment]
经过测试，是上面提到的api返回状态码不对，但是行为是对的，可以工作。
	int nRet = 0;
	nRet =m_net.load_param(srcdet_v3_param_bin);
	if (nRet)
	{
		printf("load error during load_param: %d\n", nRet);
	}
	else
		printf("load ok during load_param: %d\n", nRet);

	nRet = m_net.load_model(srcdet_v3_bin);
	if (nRet)
	{
		printf("load error during load_model: %d\n", nRet);
	}
	else
		printf("load ok during load_model: %d\n", nRet);

**Comment by znsoftm** [comment]
我把把上面的模型用ncnn2mem转成数组后用上面的api加载，它的返回状态不是0. 这是我理解有误，本来就是这样？还是只是返回值 有问题？

**Comment by znsoftm** [comment]
在其它平台上，它是真切返回0表示正确的。

load_param return  1560
load_model return 483908

**Comment by znsoftm** [comment]
结案了。没有bug, 返回的是模型数据占用的字节数。
