### ISSUE TITLE
ncnn 内存池是否会引起 数据错位？

### ISSUE THREAD

**Issue by LamHoCN** [Tencent/ncnn#408]
作者您好～
近期在使用ncnn depth_wise conv时，发现在top_data feature map size比较小的时候，与pytorch 比对出现了错位的情况。
输入 60 * 10 * 10      group = 60,kernel_size = 3,stride = 2,pad = 1
输出 60 * 5 * 5

<img width="590" alt="2018-05-17 12 51 32" src="https://user-images.githubusercontent.com/19267253/40131432-8ea03c3a-596c-11e8-8a33-af45d03783bf.png">
<img width="595" alt="2018-05-17 12 51 46" src="https://user-images.githubusercontent.com/19267253/40131440-93d34e36-596c-11e8-8da8-98422bf54f36.png">
<img width="677" alt="2018-05-17 12 51 55" src="https://user-images.githubusercontent.com/19267253/40131442-97077bfe-596c-11e8-9f0e-e079aa7ccb4e.png">

错位在 每个feature map 结尾处 有三个数字多余
当feature map 比较大的时候 则没有此问题
求解答

**Comment by nihui** [comment]
5x5的mat，25不是4倍数，每个channel后面会补3个数确保内存对齐

所以，没有问题

**Comment by LamHoCN** [comment]
感谢nihui 提醒～ 问题已经解决
