### ISSUE TITLE
VS 2015编译环境不通过LNK2001问题

### ISSUE THREAD

**Issue by cocolinCN** [Tencent/ncnn#4098]
## detail | 详细描述 | 詳細な説明

测试工程（未添加opencv330，单独测试编译的opencv330也没有问题）
windwos+Release+x64+ncnn+vulkan1.3.216.0+protobuf340
![image](https://user-images.githubusercontent.com/56459363/181505655-2679547f-1a86-4b52-94dd-c19519bb050b.png)
![image](https://user-images.githubusercontent.com/56459363/181506537-0efd46e1-f09c-4483-84ec-725f2f62fae6.png)
![image](https://user-images.githubusercontent.com/56459363/181506652-410227a7-ff8c-4344-9ecd-7915bab6379d.png)
![image](https://user-images.githubusercontent.com/56459363/181507904-58f7ccbf-d55e-4b64-a126-186793cc6844.png)
![image](https://user-images.githubusercontent.com/56459363/181508055-fda7c81d-733d-47e0-b127-89ec195946f6.png)
![image](https://user-images.githubusercontent.com/56459363/181508175-e10f8190-c361-4880-af91-66feb54c27a0.png)
![image](https://user-images.githubusercontent.com/56459363/181508383-8d2b19f4-59a5-4227-a00d-2598a66fd91c.png)
![image](https://user-images.githubusercontent.com/56459363/181509480-4b699529-e6c3-4e7c-9fb7-425084ba2d3f.png)
![image](https://user-images.githubusercontent.com/56459363/181509646-eadb6d97-021a-4bb2-a76e-2482468cdf10.png)

第三方库均编译成功（编译只改了VULKAN=ON），新建工程使用ncnn库，链接的时候不成功

nihui大佬，好像有点找不到是哪里链接的问题了，救救我

**Comment by cocolinCN** [comment]
rtx已删，只能github问了，求救，救救我救救我

**Comment by cocolinCN** [comment]
rtx已删，只能github问了，求救，救救我救救我

**Comment by nihui** [comment]
参考 https://github.com/Tencent/ncnn/wiki/use-ncnn-with-own-project

**Comment by cocolinCN** [comment]
> 参考 https://github.com/Tencent/ncnn/wiki/use-ncnn-with-own-project

CMake的工程编译还没试，有用VS编译链接的wiki吗？

**Comment by cocolinCN** [comment]
> 参考 https://github.com/Tencent/ncnn/wiki/use-ncnn-with-own-project

已经成功了，谢谢 nihui大佬 T.T 下次飞过去求个签名
