### ISSUE TITLE
apk打包时 ncnn.so 文件有点大

### ISSUE THREAD

**Issue by yyccR** [Tencent/ncnn#4099]
## detail | 详细描述 | 詳細な説明

大佬好，如下图，在我将ncnn模型部署到Android后，ncnn模型在打包编译后产生的 .so 文件有点大，请问有什么build参数可以减小这个 .so 文件的体积吗？ 为了减小相应体积我已经把您之前开源的 [ncnn-android-nanodet](https://github.com/nihui/ncnn-android-nanodet) 里面设计OpenCV相关操作替换为Java原生相关，并同时去掉了opencv-mobile依赖库，只留下了ncnn库。
 
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/14156500/181667842-07b58d3a-7f2f-4f10-bd6d-266959d0c6f2.png">

**Comment by wzyforgit** [comment]
编的时候CMake可以设置成Minimum Size Release
然后我记得哪里有个文档，是教怎么进一步裁剪ncnn的，你再多翻翻

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/build-minimal-library

**Comment by yyccR** [comment]
好的，感谢 @nihui @wzyforgit 
build的时候 release 已经minifyEnabled，我再看文档。
