### ISSUE TITLE
wsl环境对于优化intel intrinsic是否能体现真实的性能数据

### ISSUE THREAD

**Issue by ZhMi** [Tencent/ncnn#4103]
windows wsl方式安装的linux环境，wsl环境对于优化intel intrinsic是否能体现真实的性能数据

**Comment by ysh329** [comment]
https://stackoverflow.com/questions/54718527/can-i-use-simd-intrinsics-for-software-that-runs-on-cloud

**Comment by wzyforgit** [comment]
建议买块移动SSD硬盘，直接装实体的Linux，省心很多
