### ISSUE TITLE
termux make with NCNN_PYTHON=ON failed

### ISSUE THREAD

**Issue by chairwa** [Tencent/ncnn#4104]
## error log | 日志或报错信息 | ログ
[ 99%] Building CXX object python/CMakeFiles/pyncnn.dir/src/main.cpp.o
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:13:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pytypes.h:448:70: error: use of typeid requires -frtti
bool isinstance(handle obj) { return detail::isinstance_generic(obj, typeid(T)); }
                                                                     ^
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:15:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:40:19: error: use of typeid requires -frtti
        return {{&typeid(Ts)..., nullptr}};
                  ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:39:76: error: no return statement in constexpr function
    static constexpr std::array<const std::type_info *, sizeof...(Ts) + 1> types() {
                                                                           ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:100:29: error: no matching function for call to '_'
    return _("{") + descr + _("}");
                            ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:57:24: note: candidate template ignored: substitution failure [with N = 2]
constexpr descr<N - 1> _(char const(&text)[N]) { return descr<N - 1>(text); }
                       ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:85:51: note: candidate function template not viable: requires 0 arguments, but 1 was provided
template <typename Type> constexpr descr<1, Type> _() { return {'%'}; }
                                                  ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:81:16: note: candidate function template not viable: requires 0 arguments, but 1 was provided
auto constexpr _() -> remove_cv_t<decltype(int_to_str<Size / 10, Size % 10>::digits)> {
               ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:78:31: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, T2> _(const T1 &, const T2 &d) { return d; }
                              ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:76:30: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, T1> _(const T1 &d, const T2 &) { return d; }
                             ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:71:42: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, descr<N2 - 1>> _(char const(&)[N1], char const(&text2)[N2]) {
                                         ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:67:41: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, descr<N1 - 1>> _(char const(&text1)[N1], char const(&)[N2]) {
                                        ^
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:16:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/typeid.h:50:22: error: use of typeid requires -frtti
    std::string name(typeid(T).name());
                     ^
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:16:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:886:23: error: use of typeid requires -frtti
        type = src ? &typeid(*src) : nullptr;
                      ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:902:43: error: use of typeid requires -frtti
    type_caster_base() : type_caster_base(typeid(type)) { }
                                          ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:919:27: error: use of typeid requires -frtti
        auto &cast_type = typeid(itype);
                          ^
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:241:5: error: constexpr variable 'name' must be initialized by a constant expression
    PYBIND11_TYPE_CASTER(T, _("None"));
    ^                       ~~~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:93:27: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                          ^      ~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:241:5: error: constexpr variable 'name' must be initialized by a constant expression
    PYBIND11_TYPE_CASTER(T, _("None"));
    ^                       ~~~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:93:27: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                          ^      ~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:244:51: note: in instantiation of template class 'pybind11::detail::void_caster<pybind11::detail::void_type>' requested here
template <> class type_caster<void_type> : public void_caster<void_type> {};
                                                  ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:284:27: error: constexpr variable 'name' must be initialized by a constant expression
    static constexpr auto name = _("capsule");
                          ^      ~~~~~~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:241:5: error: constexpr variable 'name' must be initialized by a constant expression
    PYBIND11_TYPE_CASTER(T, _("None"));
    ^                       ~~~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:93:27: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                          ^      ~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:289:56: note: in instantiation of template class 'pybind11::detail::void_caster<std::nullptr_t>' requested here
template <> class type_caster<std::nullptr_t> : public void_caster<std::nullptr_t> { };
                                                       ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:335:32: error: no matching function for call to '_'
    PYBIND11_TYPE_CASTER(bool, _("bool"));
                               ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:93:34: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                                 ^~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:57:24: note: candidate template ignored: substitution failure [with N = 5]
constexpr descr<N - 1> _(char const(&text)[N]) { return descr<N - 1>(text); }
                       ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:85:51: note: candidate function template not viable: requires 0 arguments, but 1 was provided
template <typename Type> constexpr descr<1, Type> _() { return {'%'}; }
                                                  ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:81:16: note: candidate function template not viable: requires 0 arguments, but 1 was provided
auto constexpr _() -> remove_cv_t<decltype(int_to_str<Size / 10, Size % 10>::digits)> {
               ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:67:41: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, descr<N1 - 1>> _(char const(&text1)[N1], char const(&)[N2]) {
                                        ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:71:42: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, descr<N2 - 1>> _(char const(&)[N1], char const(&text2)[N2]) {
                                         ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:76:30: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, T1> _(const T1 &d, const T2 &) { return d; }
                             ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:78:31: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, T2> _(const T1 &, const T2 &d) { return d; }
                              ^
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:425:5: error: constexpr variable 'name' must be initialized by a constant expression
    PYBIND11_TYPE_CASTER(StringType, _(PYBIND11_STRING_NAME));
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:93:27: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                          ^      ~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:562:34: error: no matching function for call to '_'
    static constexpr auto name = _(PYBIND11_STRING_NAME);
                                 ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:57:24: note: candidate template ignored: substitution failure [with N = 4]
constexpr descr<N - 1> _(char const(&text)[N]) { return descr<N - 1>(text); }
                       ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:85:51: note: candidate function template not viable: requires 0 arguments, but 1 was provided
template <typename Type> constexpr descr<1, Type> _() { return {'%'}; }
                                                  ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:81:16: note: candidate function template not viable: requires 0 arguments, but 1 was provided
auto constexpr _() -> remove_cv_t<decltype(int_to_str<Size / 10, Size % 10>::digits)> {
               ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:67:41: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, descr<N1 - 1>> _(char const(&text1)[N1], char const(&)[N2]) {
                                        ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:71:42: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, descr<N2 - 1>> _(char const(&)[N1], char const(&text2)[N2]) {
                                         ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:76:30: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, T1> _(const T1 &d, const T2 &) { return d; }
                             ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:78:31: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, T2> _(const T1 &, const T2 &d) { return d; }
                              ^
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:599:83: error: no matching function for call to '_'
    static constexpr auto name = _("Tuple[") + concat(make_caster<Ts>::name...) + _("]");
                                                                                  ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:57:24: note: candidate template ignored: substitution failure [with N = 2]
constexpr descr<N - 1> _(char const(&text)[N]) { return descr<N - 1>(text); }
                       ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:85:51: note: candidate function template not viable: requires 0 arguments, but 1 was provided
template <typename Type> constexpr descr<1, Type> _() { return {'%'}; }
                                                  ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:81:16: note: candidate function template not viable: requires 0 arguments, but 1 was provided
auto constexpr _() -> remove_cv_t<decltype(int_to_str<Size / 10, Size % 10>::digits)> {
               ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:67:41: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, descr<N1 - 1>> _(char const(&text1)[N1], char const(&)[N2]) {
                                        ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:71:42: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, descr<N2 - 1>> _(char const(&)[N1], char const(&text2)[N2]) {
                                         ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:76:30: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, T1> _(const T1 &d, const T2 &) { return d; }
                             ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:78:31: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, T2> _(const T1 &, const T2 &d) { return d; }
                              ^
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:785:68: error: constexpr variable 'name' must be initialized by a constant expression
template <> struct handle_type_name<bytes> { static constexpr auto name = _(PYBIND11_BYTES_NAME); };
                                                                   ^      ~~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:786:74: error: no matching function for call to '_'
template <> struct handle_type_name<int_> { static constexpr auto name = _("int"); };
                                                                         ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:57:24: note: candidate template ignored: substitution failure [with N = 4]
constexpr descr<N - 1> _(char const(&text)[N]) { return descr<N - 1>(text); }
                       ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:85:51: note: candidate function template not viable: requires 0 arguments, but 1 was provided
template <typename Type> constexpr descr<1, Type> _() { return {'%'}; }
                                                  ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:81:16: note: candidate function template not viable: requires 0 arguments, but 1 was provided
auto constexpr _() -> remove_cv_t<decltype(int_to_str<Size / 10, Size % 10>::digits)> {
               ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:67:41: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, descr<N1 - 1>> _(char const(&text1)[N1], char const(&)[N2]) {
                                        ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:71:42: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, descr<N2 - 1>> _(char const(&)[N1], char const(&text2)[N2]) {
                                         ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:76:30: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, T1> _(const T1 &d, const T2 &) { return d; }
                             ^
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/detail/descr.h:78:31: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, T2> _(const T1 &, const T2 &d) { return d; }
                              ^
In file included from /data/data/com.termux/files/home/ncnn/python/src/main.cpp:16:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/attr.h:13:
/data/data/com.termux/files/home/ncnn/python/pybind11/include/pybind11/cast.h:787:71: error: constexpr variable 'name' must be initialized by a constant expression
template <> struct handle_type_name<iterable> { static constexpr auto name = _("Iterable"); };
                                                                      ^      ~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [python/CMakeFiles/pyncnn.dir/build.make:76: python/CMakeFiles/pyncnn.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:890: python/CMakeFiles/pyncnn.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

## how to reproduce | 复现步骤 | 再現方法
1. cmake -DNCNN_BUILD_EXAMPLES=ON -DNCNN_PLATFORM_API=OFF -DNCNN_SIMPLEOCV=ON -DNCNN_PYTHON=ON ..
2. make

**Comment by tpoisonooo** [comment]
what is your  g++ or clang version ?

**Comment by chairwa** [comment]
> 

g++ -v
clang version 14.0.6

When add -DNCNN_DISABLE_RTTI=OFF, make OK; but "pip install ." NG.

cmake -DNCNN_DISABLE_RTTI=OFF -DNCNN_BUILD_EXAMPLES=ON -DNCNN_PLATFORM_API=OFF -DNCNN_SIMPLEOCV=ON -DNCNN_PYTHON=ON ..

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/6647396667426405cee4da8da79f723148f60dd5

**Comment by wsora** [comment]
用20230517分支的代码还是遇到这个问题，怎么解决？
