### ISSUE TITLE
模型结构layer-param key参数定义含义问题

### ISSUE THREAD

**Issue by ZhMi** [Tencent/ncnn#4110]
https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure

在模型结构介绍的这个wiki里

请问， 这两处的高亮的意思是什么，

感谢~~ Thanks♪(･ω･)ﾉ

![EZ~ PI3A45@D2C7K ~$OE7B](https://user-images.githubusercontent.com/13502691/182527508-eef104ee-0a0b-44e5-9951-987fe81b74f3.png)

【1】integer or float key : index 0 ~ 19，这个是表示key对应的value为整数或者浮点数时，key的编号范围是0~19？但是看文档里，有的key的编号是20,21，20,21请问代表啥呢
![~1$S USRLI(65`RKD 4X$PK](https://user-images.githubusercontent.com/13502691/182527580-00760eba-967f-4769-aa32-21147dff923c.png)

【2】integer array or float array key : -23300 minus index 0 ~ 19
这句话的意思是，当参数是一个整数数组格式或者 浮点数数组格式， key的序列号为 -23300 减去 key为整数或者浮点数单个数字对应的key的编号？

**Comment by miemie2013** [comment]
（1）现在好像支持是0~31了。你看的应该是转置卷积Deconvolution的介绍吧？你可以看src/layer/deconvolution.cpp里load_param()函数的源码，数字对应特定的参数，20、21就是对应转置卷积的output_w、output_h参数呀。
（2）当属性的类型是Mat类型时（转置卷积的activation_params就是Mat类型）时，用-233xx表示这个属性，代码里activation_params对应数字10，所以用-23310表示activation_params这个属性。第一个数字表示数组长度，后面才是数组元素，用逗号隔开，比如 -23310=1,-5.580000e+01  表示activation_params是一个长度是1的数组且a[0]=-5.580000e+01

**Comment by ZhMi** [comment]
清晰明了，感谢，Thanks♪(･ω･)ﾉ ~ @miemie2013

**Comment by ZhMi** [comment]
> （1）现在好像支持是0~31了。你看的应该是转置卷积Deconvolution的介绍吧？你可以看src/layer/deconvolution.cpp里load_param()函数的源码，数字对应特定的参数，20、21就是对应转置卷积的output_w、output_h参数呀。 （2）当属性的类型是Mat类型时（转置卷积的activation_params就是Mat类型）时，用-233xx表示这个属性，代码里activation_params对应数字10，所以用-23310表示activation_params这个属性。第一个数字表示数组长度，后面才是数组元素，用逗号隔开，比如 -23310=1,-5.580000e+01 表示activation_params是一个长度是1的数组且a[0]=-5.580000e+01

清晰明了，感谢，Thanks♪(･ω･)ﾉ ~ @miemie2013
