### ISSUE TITLE
Tip: The proper way to use NCNN with vulkan acceleration in python

### ISSUE THREAD

**Issue by TabuaTambalam** [Tencent/ncnn#4113]
## detail | 详细描述 | 詳細な説明

Basically a conclusion from here: https://github.com/TabuaTambalam/DalleWebms/issues/1
I made this cuz I can't find any doc about using NCNN with vulkan in python, and I'm not 100% sure I did it right.
Also python-ncnn with vulkan on still cause output error in my case, as the link above described.

First, on google colab linux, `pip install ncnn` can't do vulkan accel, you have to use `pip install ncnn-vulkan`, or build linux-x64-gpu-clang-python.yml yourself.
In the case of `pip install ncnn-vulkan`, you can `mv /usr/local/lib/python3.7/dist-packages/ncnn_vulkan/*.so /usr/local/lib/python3.7/dist-packages/ncnn/`
if you don't want to write extra `from ncnn_vulkan import ncnn` codes, `/usr/local/lib/python3.7/dist-packages/` is your python lib installation path.

Now make a class(?) like this:
```py
class ExtractorGPU(object):
  def __enter__(self):
    self.ex = net.create_extractor()
    self.ex.set_blob_vkallocator(blob_vkallocator)
    self.ex.set_workspace_vkallocator(blob_vkallocator)
    self.ex.set_staging_vkallocator(staging_vkallocator)
    return self.ex

  def __exit__(self, exc_type, exc_val, exc_tb):
    blob_vkallocator.clear()
    staging_vkallocator.clear()
    del self.ex
```

The init code will be:

```py
UseVulkan=False #@param {type:'boolean'}

net = ncnn.Net()
net.opt.use_vulkan_compute = UseVulkan

if UseVulkan:
  vkdev = ncnn.get_gpu_device(ncnn.get_default_gpu_index())
  blob_vkallocator = ncnn.VkBlobAllocator(vkdev)
  staging_vkallocator = ncnn.VkStagingAllocator(vkdev)
  NCNNex = ExtractorGPU
else:
  NCNNex=net.create_extractor

net.opt.use_fp16_packed = ...etc
net.load_param...
```

blob_vkallocator, staging_vkallocator, NCNNex are all global vars. It can be done in a jupyter notebook, not sure about in py scripts.

To use it, just replace net.create_extractor() with NCNNex(), like this:
```py
def showp2(seq):
  with NCNNex() as ex:
    ex.input('in0', ncnn.Mat(seq.astype(np.uint32)).clone())
    hrr, out0 = ex.extract('out0')
  del ex
  uz=Image.fromarray(np.array(out0).astype(np.uint8))
  uz.save('/content/sample_data/000.png')
  return uz
```

I think ncnn python side codes should be updated for a easier cpu/gpu switching.

**Comment by joeyballentine** [comment]
Would you mind if I used this in the ncnn-vulkan readme? I like this a lot more than what I have there

**Comment by TabuaTambalam** [comment]
> Would you mind if I used this in the ncnn-vulkan readme? I like this a lot more than what I have there

Feel free, should be adjusted for py modules tho. (python can't make global vars inside module as I remember)
Also `del self.ex` might be `self.ex.clear()`.

**Comment by nihui** [comment]
Hi, the latest pyncnn gains vulkan support !
pip install -U ncnn
