### ISSUE TITLE
tensorflow2ncnn cannot convert batch_normalization layer

### ISSUE THREAD

**Issue by jjjjohnson** [Tencent/ncnn#413]
Hello @nihui 大神,
我发现如果加上`batch_normalization`层，用转换工具tensorflow2ncnn转换模型不会报错，但是前向使用时输出是`nan`, 如果去掉`batch_normalization`，则输出正常。请问是否现在还没有支持tensorflow `batch_normalization`的转换？
以是有`batch_normalization`的ncnn.proto 文件：
![screen shot 2018-05-21 at 5 25 08 pm](https://user-images.githubusercontent.com/20569095/40300537-16828f56-5d1c-11e8-8fd5-0a2d80d7bc7b.png)
万分感激！
Junjie

**Comment by nihui** [comment]
generally, it is hard to convert tensorflow model to others. you'd better try caffe pytorch or mxnet ...
see #5
