### ISSUE TITLE
android not support vulkan int8 ?

### ISSUE THREAD

**Issue by dachengai** [Tencent/ncnn#4130]
## 模型 
nanodet-plus-m  320x320   int8

## 参数&日志

参数：

    this->Net->opt.lightmode = true;
    this->Net->opt.num_threads = num_threads;
    this->Net->opt.blob_allocator = g_blob_pool_allocator;
    this->Net->opt.workspace_allocator = g_workspace_pool_allocator;
#if NCNN_VULKAN
    this->Net->opt.blob_vkallocator = g_blob_vkallocator;
    this->Net->opt.workspace_vkallocator = g_blob_vkallocator;
    this->Net->opt.staging_vkallocator = g_staging_vkallocator;
    
#endif // NCNN_VULKAN
    
    this->Net->opt.use_int8_inference = true;
    this->Net->opt.use_int8_arithmetic = true;
    this->Net->opt.use_winograd_convolution = true;
    this->Net->opt.use_sgemm_convolution = true;
    this->Net->opt.use_fp16_packed = true;
    this->Net->opt.use_fp16_storage = true;
    this->Net->opt.use_fp16_arithmetic = true;
    this->Net->opt.use_int8_packed = true;
    this->Net->opt.use_int8_storage = true;
    this->Net->opt.use_int8_arithmetic = true;
    this->Net->opt.use_packing_layout = true;
    this->Net->opt.use_shader_pack8 = false;
    this->Net->opt.use_image_storage = false;

日志：

set_vulkan_compute failed, network use_vulkan_compute disabled
1,time:129316.00,detect 2 objects:
set_vulkan_compute failed, network use_vulkan_compute disabled
2,time:114806.00,detect 2 objects:

**Comment by tpoisonooo** [comment]
Yes ncnn vulkan not support int8 yet.  try  vulkan fp16  or  arm int8.

**Comment by dachengai** [comment]
> Yes ncnn vulkan not support int8 yet. try vulkan fp16 or arm int8.

thanks

**Comment by liuqinglong110** [comment]
> Yes ncnn vulkan not support int8 yet. try vulkan fp16 or arm int8.

Hi, I also encountered the same problem. What should I do according to the method you said?
