### ISSUE TITLE
android 10.0版本之前都无法使用GPU

### ISSUE THREAD

**Issue by yuan9778** [Tencent/ncnn#4135]
在android studio使用模拟器实测，用的 [The squeezencnn example](https://github.com/Tencent/ncnn/tree/master/examples/squeezencnn)，测试了API 24 到API 30，使用ncnn-20220216-android-vulkan，gpu_count通过ncnn::get_gpu_count()获得，结果如下：

```
Android 	API	gpu_count
7	        24	    0
7.1.1	        25	    0
8	        26	    0
8.1	        27	    0
9	        28	    0
10	        29	    1
11	        30	    1
```
我在[FAQ ncnn vulkan](https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-vulkan)看到的是Vulkan最低支持API-24，是我什么地方配置的不对吗？请大佬指教。

**Comment by nihui** [comment]
模拟器不支持不代表手机不支持，android 7 发布后的手机基本都支持 vulkan
