### ISSUE TITLE
hisiv500.toolchain.cmake交叉编译出错

### ISSUE THREAD

**Issue by ElegantGod** [Tencent/ncnn#4147]
## error log | 日志或报错信息 | ログ
/home/Hisi/ncnn/src/layer/arm/innerproduct_fp16s.h: In function ‘void ncnn::innerproduct_pack4_fp16s_neon(const ncnn::Mat&, ncnn::Mat&, const ncnn::Mat&, const ncnn::Mat&, int, const ncnn::Mat&, const ncnn::Option&)’:
/home/Hisi/ncnn/src/layer/arm/innerproduct_fp16s.h:256:83: error: ‘vreinterpret_f16_u16’ was not declared in this scope
             float32x4_t _w0 = vcvt_f32_f16(vreinterpret_f16_u16(vget_low_u16(_w01)));

## how to reproduce | 复现步骤 | 再現方法
1.cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/hisiv500.toolchain.cmake ..
2.看了下arm_neon.h里面没有vreinterpret_f16_u16这个函数，所以就报错了

**Comment by Oliverwang** [comment]
关闭ncnn_vfpv4 选项之后，编译也会报错，位置不一样了，错误如下：
![4H6B( VB JR5$F(_2`ONYYV](https://user-images.githubusercontent.com/747345/194734321-d407db19-7569-461e-ba52-070b8f154577.png)

**Comment by nihui** [comment]
fixed

**Comment by live106** [comment]
^
/home/guanchao/wangyn/ai/ncnn/src/layer/arm/innerproduct_gemm_fp16s.h:436:52: error: 'float16x4_t' was not declared in this scope
                     float32x4_t _w = vcvt_f32_f16((float16x4_t)(vld1_u16(kptr)));
                                                    ^~~~~~~~~~~
/home/guanchao/wangyn/ai/ncnn/src/layer/arm/innerproduct_gemm_fp16s.h:436:80: error: 'vcvt_f32_f16' was not declared in this scope
                     float32x4_t _w = vcvt_f32_f16((float16x4_t)(vld1_u16(kptr)));

**Comment by hongson23** [comment]
I have the same issue 
/home/sonhh/repos/ncnn_nnie/ncnn/src/layer/arm/innerproduct_gemm_fp16s.h:436:52: error: 'float16x4_t' was not declared in this scope
                     float32x4_t _w = vcvt_f32_f16((float16x4_t)(vld1_u16(kptr)));
@nihui pls take a look, thanks

**Comment by hongson23** [comment]
hi
I just checked-out to 20211208 tag and ncnn can build successfully with himix200 toolchains
thanks
