### ISSUE TITLE
怎样获取blob的维度信息

### ISSUE THREAD

**Issue by ligonzheng** [Tencent/ncnn#416]
您好：
    blob的定义里面没有维度的相关信息，我如何获取某一个blob的ncwh相关的信息呢？
   祝好

**Comment by ligonzheng** [comment]
除了输入层的维度信息是在导入模型的时候就知道的，后面的blob的维度是不是都是在extract的过程中推算的？

**Comment by ligonzheng** [comment]
dims代表的是batch吗？
为什么说输入层的blob也是前向计算的呢？我实验了下，直接extract("data",in),然后查看in的维度，发现程序出错。而且代码里面的Input层的forward是直接返回1的，并没有reshape的操作。

**Comment by nihui** [comment]
dims 是维数，可能是 1 2 3
