### ISSUE TITLE
Android编译失败(ncnn-20220729)

### ISSUE THREAD

**Issue by Hi-Jingzhi** [Tencent/ncnn#4161]
## detail | 详细描述 | 詳細な説明
开发工具：
Android Studio: 4.1.3
Gradle model version: 4.10.1
开发环境：
Android SDK Build-Tools : 27.0.3
NDK (side by side): 20.0.5594570
CMake: 3.10.2.4988404 和 3.6.4111459
NCNN: 20201218

问题背景：
自己开发的app在vivo T1 pro (android 12)进行使用时，app闪退。app中使用的都是一些简单卷积网络。在其他手机上，不会复现闪退。考虑到app使用的ncnn发布时间早于andorid12发布时间。想试图通过更新ncnn去解决闪退问题。

问题描述：
当尝试使用最新的ncnn(ncnn-20220729-android.zip) 到Android项目中，遇到报错：
` ../../../../../3rdparty_lib/ncnn/x86/lib/libncnn.a -landroid ../../../../../3rdparty_lib/curl/x86/lib/libcurl.a ../../../../../3rdparty_lib/json11/x86/lib/libjson11.a -lz -latomic -lm && :
  ../../../../../3rdparty_lib/ncnn/x86/lib/libncnn.a(cpu.cpp.o):cpu.cpp:function ncnn::get_elf_hwcap(unsigned int): error: undefined reference to 'getauxval'
  ../../../../../3rdparty_lib/ncnn/x86/lib/libncnn.a(cpu.cpp.o):cpu.cpp:function sprintf(char*, char const* pass_object_size1, ...): error: undefined reference to '__vsprintf_chk'
  ../../../../../3rdparty_lib/ncnn/x86/lib/libncnn.a(datareader.cpp.o):datareader.cpp:function sprintf(char*, char const* pass_object_size1, ...): error: undefined reference to '__vsprintf_chk'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)`

额外的问题：
<ncnn与android12的兼容性>

烦请各位大佬指点！

**Comment by lsfx216** [comment]
顶一下！

我也遇到这个问题，我测试的版本是ncnn-20220729-android-vulkan，
换了ndk 24，也不行，放弃了，大佬没回，难道是个例：
ncnn-20220729/arm64-v8a/lib/libncnn.a(gpu.cpp.o):gpu.cpp:(.text._ZN4ncnn19VulkanDevicePrivateD2Ev[_ZN4ncnn19VulkanDevicePrivateD2Ev]+0xc8): more undefined references to `__aarch64_ldadd4_acq_rel' follow
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

**Comment by maziyi234** [comment]
> 顶一下！
> 
> 我也遇到过这个问题，我测试的版本是ncnn-20220729-android-vulkan， 换了ndk 24，也不行，放弃了，大佬没回，困难是个例： ncnn-20220729/arm64-v8a/lib/ libncnn.a(gpu.cpp.o):gpu.cpp:(.text._ZN4ncnn19VulkanDevicePrivateD2Ev[_ZN4ncnn19VulkanDevicePrivateD2Ev]+0xc8):更多未定义的引用`__aarch64_ldadd4_acq_rel'跟随 clang++:错误:链接器命令失败，退出代码1(使用-v)查看调用） 忍者：构建停止：子命令失败。

老哥 这个问题你怎么解决的呢

**Comment by nihui** [comment]
__aarch64_ldadd4_acq_rel 链接错误在最新版本 20221128 修复了

**Comment by Deeperfinder** [comment]
顶一下 我也遇到了这个问题

/ncnn-20221128-android/armeabi-v7a/lib/libncnn.a(cpu.cpp.o):cpu.cpp:function ncnn::get_elf_hwcap(unsigned int): error: undefined reference to 'getauxval'
../ncnn-20221128-android/armeabi-v7a/lib/libncnn.a(cpu.cpp.o):cpu.cpp:function sprintf(char*, char const* pass_object_size1, ...): error: undefined reference to '__vsprintf_chk'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nihui** [comment]
set android api version to 24
