### ISSUE TITLE
simpleocv中Mat具有类型转换的ptr方法

### ISSUE THREAD

**Issue by liangshuisanqian** [Tencent/ncnn#4169]
## context | 编译/运行环境 | バックグラウンド
当前master分支，commit `9af349c`

在测试`ncnn/examples/yolact.cpp`的时候，使用了自带的`simpleocv`，发现程序运行错误，使用`OpenCV`的时候正常。经过简单定位，应该是`simpleocv.h`中，Mat类的两个模版`ptr`方法的问题：

![image](https://user-images.githubusercontent.com/35721963/185868396-8739bf75-9421-4bbd-90a0-16c52258ebd8.png)

根据`yolact.cpp`中的调用方式以及`OpenCV`的实现来看，应该是要先相加再转换吧?

```c++
return (_Tp*)(data + y * cols * c);
```

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5241

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/d30af29ee2540eb80d878ff7df6841a7379713cd

感谢报告～
