### ISSUE TITLE
GEMM算子ncnn实现，貌似计算公式有误

### ISSUE THREAD

**Issue by RichardYang88** [Tencent/ncnn#4172]
GEMM广义矩阵的定义公式为 y = α*AB + β*C； 但是在ncnn源码写法应该是 y =  α * (AB + β*C) =  α*AB + α*β*C；

我想请问，是ncnn故意这样改为在C矩阵前冗余乘以α，还是代码写错了。对我们使用的开发工作非常重要，期待答复！

参考链接：https://github.com/Tencent/ncnn/blob/master/src/layer/gemm.cpp

**Comment by nihui** [comment]
代码确实是 y = alpha * (AB + beta * C)
文档中已经改正

**Comment by RichardYang88** [comment]
我看修改后的代码还是 y = alpha * (beta * C + AB)呢，跟之前是一样的，好像要 y = (beta * C + alpha *AB)才合适

**Comment by nihui** [comment]
是的，就是 y = alpha * (beta * C + AB)
如果你一定要 y = (beta * C + alpha *AB)，可以 beta 先除掉 alpha，就一样了...
