### ISSUE TITLE
python编译错误

### ISSUE THREAD

**Issue by ncnnnnn** [Tencent/ncnn#4176]
## error log | 日志或报错信息 | ログ
ncnn\python\src\pybind11_allocator.h(43,9): error C2440: “return”: 无法从“void”转换为“void *” [
## context | 编译/运行环境 | バックグラウンド
vs2022

## how to reproduce | 复现步骤 | 再現方法
1.vs2022
2.cmake -DNCNN_PYTHON=ON ..
3.cmake --build .

**Comment by nihui** [comment]
could be resolved by a local typedef for all pointer type
ref https://github.com/pybind/pybind11/issues/824

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4359

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/6647396667426405cee4da8da79f723148f60dd5
