### ISSUE TITLE
input层的宽 高 通道与输入blob的宽 高 通道不一致

### ISSUE THREAD

**Issue by ligonzheng** [Tencent/ncnn#418]
您好，
    我在运行squeezenet的时候，发现param文件的第一行后面写的是0=3 1=227 2=227,这应该代表的是输入blob的维度是通道、宽、高，且在输入Mat的尺寸设置上也是按这样设置的，然而在代码的Input.cpp文件里的load_param函数里面，发现输入层的维度设置是宽、高、通道（lnput::load_param函数），感觉输入层的宽高跟输入blob的宽高不一致，特此请教！
  祝好！

**Comment by nihui** [comment]
param文件有问题，应该是 0=227 1=227 2=3，不过这个问题不影响结果

**Comment by ligonzheng** [comment]
不影响的原因是因为Input层虽然有w h c的成员变量，但是它们应该并没有被真正用到，是这样吗？

**Comment by nihui** [comment]
是的
