### ISSUE TITLE
android中集成到app后速度比native程序慢且不稳定

### ISSUE THREAD

**Issue by wayen820** [Tencent/ncnn#419]
我写了一个简单的mtcnn测试程序，编译通过然后adb push 到android手机上，通过adb shell执行，结果是对的，打印时间，发现速度稳定在23ms左右，但是我添加jni接口，封装成为so后，给app调用，发现速度变慢了，四五十ms，并且不稳定。我已经查找并排除了其他因素，时间测得都是网络推断函数的时间，图像大小都是一样的。这究竟是什么原因呢？  @nihui

**Comment by ligonzheng** [comment]
是不是优化的等级不一致了？

**Comment by GuohongWu** [comment]
android后台如果开了其他进程，占用了某些核的部分cpu，会影响ncnn开多线程并行速度（以及稳定性）。类似于木桶原理，最差的CPU决定速度。

**Comment by InsightDev** [comment]
我也遇到类似的问题，也是Java调用JNI，for循环每一次计算时间大概是6、7毫秒，当我在每次计算之后加入一个sleep操作（sleep是在计算的时间之外），网络计算时间变成30多毫秒。另外其他人也有类似的问题。

**Comment by kobe2000** [comment]
我也遇到了这个问题，而且差距很夸张，50ms vs 5000ms，还没找打原因

**Comment by unaplugin** [comment]
走jni接口的是不是会受到android内核机制的调度？我记得这个挺复杂的

**Comment by look-recognize** [comment]
同问

**Comment by nihui** [comment]
app运行本身也会使用cpu资源，所以会比 benchncnn 慢

建议：
多线程设置不要用全部cpu，保守设置为 cpu_count / 2
使用 ncnn::set_cpu_powersave(2) 接口绑定大核心，减少调度切换
