### ISSUE TITLE
请问有和nnpack比较过速度吗？

### ISSUE THREAD

**Issue by hiyijian** [Tencent/ncnn#42]
看介绍说能胜过所有同类开源库，所以。。。有和nnpack pk的数据吗？

**Comment by nihui** [comment]
android 上面，nnpack只有少数条件下超过openblas，所以就不比了 :P 
https://github.com/Maratyszcza/NNPACK/issues/39
https://github.com/Maratyszcza/NNPACK/issues/46

**Comment by hiyijian** [comment]
所以nnpack的优势在于3x3 stride==1的卷积，那么ncnn在这种设置下性能如何呀

**Comment by nihui** [comment]
caffe-nnpack 好久不更新，nnpack 整合起来很麻烦
既然都是开源项目，不如自己测试下...
up主还要写代码，没什么时间做这个实验

**Comment by hiyijian** [comment]
好的。只是问问有没有做过，没有的话，我自测一下，谢谢

**Comment by knsong** [comment]
@hiyijian 你测过了吗？结果怎样？
