### ISSUE TITLE
The benchmark shows more lower speed in int8 than float. It cann't satisfy our expection

### ISSUE THREAD

**Issue by aqsc** [Tencent/ncnn#4206]
## expectation 
https://github.com/Tencent/ncnn/tree/master/benchmark
From the benchmark website, it shows the inference in int8 quantization cannot be faster than float32 in arm platform and other platforms.
It doesn't satisfy our expection.

**Comment by wzyforgit** [comment]
Because float32 is so well optimized than int8

**Comment by nihui** [comment]
The data in the benchmark readme is likely out of date
The new version optimizes the inference performance of int8
Welcome to update and test again. If there are any problems, please reopen the issue.
