### ISSUE TITLE
vkCreateDevice failed  VK_ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by sdnusqy-art** [Tencent/ncnn#4208]
## error log | 日志或报错信息 | ログ
vkCreateDevice failed  VK_ERROR_INITIALIZATION_FAILED

## context | 编译/运行环境 | バックグラウンド
centos7  ncnn-20210507    8 RTX3080显卡
显卡驱动  515.65.01

## how to reproduce | 复现步骤 | 再現方法
1.  修改benchncnn.cpp   8个Net对象，一个显卡对应一个
2. 前五个vkCreateDevice 没有问题， 第六个 报VK_ERROR_INITIALIZATION_FAILED
3.

**Comment by wzyforgit** [comment]
这个建议你自己先写一个直接基于vulkan库的demo试一下，看能不能正确识别八个卡
ncnn的下面其实也是直接调的vulkan库

**Comment by nihui** [comment]
The latest master branch supports compiling gpu functions without installing vulkan-sdk. You can give it a try.
If it doesn't work, feel free to reopen the issue and post your findings.
