### ISSUE TITLE
安霸cv22平台编译报错

### ISSUE THREAD

**Issue by Oliverwang** [Tencent/ncnn#4222]
-- Performing Test NCNN_COMPILER_SUPPORT_ARM_VFPV4
-- Performing Test NCNN_COMPILER_SUPPORT_ARM_VFPV4 - Failed
-- Performing Test NCNN_COMPILER_SUPPORT_ARM_VFPV4_FP16
-- Performing Test NCNN_COMPILER_SUPPORT_ARM_VFPV4_FP16 - Failed
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_FP16
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_FP16 - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_DOTPROD
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_DOTPROD - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_FP16FML
-- Performing Test NCNN_COMPILER_SUPPORT_ARM82_FP16FML - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM84_BF16
-- Performing Test NCNN_COMPILER_SUPPORT_ARM84_BF16 - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM84_I8MM
-- Performing Test NCNN_COMPILER_SUPPORT_ARM84_I8MM - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVE
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVE - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVE2
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVE2 - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVEBF16
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVEBF16 - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVEI8MM
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVEI8MM - Success
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVEF32MM
-- Performing Test NCNN_COMPILER_SUPPORT_ARM86_SVEF32MM - Success
CMake Warning at CMakeLists.txt:198 (message):
  The compiler does not support arm vfpv4.  NCNN_VFPV4 will be OFF.

-- Target arch: arm
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/project/ncnn-20220729/build_cv22

编译错误信息如下：
In file included from /home/project/ncnn-20220729/src/layer/arm/cast_arm_bf16.cpp:20:
/home/project/ncnn-20220729/src/layer/arm/cast_bf16.h: In function 'void ncnn::cast_bf16_to_fp32_neon(const ncnn::Mat&, ncnn::Mat&, const ncnn::Option&)':
/home/project/ncnn-20220729/src/layer/arm/cast_bf16.h:217:50: error: 'vget_low_bf16' was not declared in this scope; did you mean 'vget_low_f16'?
  217 |             float32x4_t _p0_fp32 = vcvt_f32_bf16(vget_low_bf16(_p_bf16));
      |                                                  ^~~~~~~~~~~~~
      |                                                  vget_low_f16
/home/project/ncnn-20220729/src/layer/arm/cast_bf16.h:217:36: error: 'vcvt_f32_bf16' was not declared in this scope; did you mean 'vcvt_f32_f16'?
  217 |             float32x4_t _p0_fp32 = vcvt_f32_bf16(vget_low_bf16(_p_bf16));
      |                                    ^~~~~~~~~~~~~
      |                                    vcvt_f32_f16
/home/project/ncnn-20220729/src/layer/arm/cast_bf16.h:218:50: error: 'vget_high_bf16' was not declared in this scope; did you mean 'vget_high_f16'?
  218 |             float32x4_t _p1_fp32 = vcvt_f32_bf16(vget_high_bf16(_p_bf16));
      |                                                  ^~~~~~~~~~~~~~
      |                                                  vget_high_f16
/home/project/ncnn-20220729/src/layer/arm/cast_bf16.h:233:35: error: 'vcvt_f32_bf16' was not declared in this scope; did you mean 'vcvt_f32_f16'?
  233 |             float32x4_t _p_fp32 = vcvt_f32_bf16(_p_bf16);
      |                                   ^~~~~~~~~~~~~
      |                                   vcvt_f32_f16
/home/project/ncnn-20220729/src/layer/arm/cast_bf16.h:246:25: error: 'vcvtah_f32_bf16' was not declared in this scope; did you mean 'vcvtah_u32_f16'?
  246 |             *outptr++ = vcvtah_f32_bf16(*ptr++);
      |                         ^~~~~~~~~~~~~~~
      |                         vcvtah_u32_f16
src/CMakeFiles/ncnn.dir/build.make:3614: recipe for target 'src/CMakeFiles/ncnn.dir/layer/arm/cast_arm_bf16.cpp.o' failed
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/arm/cast_arm_bf16.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'src/CMakeFiles/ncnn.dir/all' failed
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nihui** [comment]
临时的workaround
```cmake -DNCNN_ARM84BF16=OFF ..```

**Comment by Oliverwang** [comment]
> 临时的workaround `cmake -DNCNN_ARM84BF16=OFF ..`
感谢大佬，问题已解决

**Comment by nihui** [comment]
fixed
