### ISSUE TITLE
使用pnnx 怎么导出  torch.atan ，torch.sign ，torch.cos  和 torch.sin？

### ISSUE THREAD

**Issue by zuowanbushiwo** [Tencent/ncnn#4230]
模型代码里面用到了这些算子， 使用pnnx 导出 的pnnx.py 文件中转换成了  aten.atan，aten.sign，aten.cos 和 aten.sin 运行报错
运行ncnn.py 也会报错。
<img width="583" alt="image" src="https://user-images.githubusercontent.com/3354428/193183958-6c719cdb-9942-4fcc-932f-b8c15008bd9f.png">

运行ncnn.py 报错：
layer aten::atan not exists or registered

**Comment by wzyforgit** [comment]
实在不行自己实现一下加进运行库？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4251

**Comment by nihui** [comment]
已实现数学函数算子转换
