### ISSUE TITLE
Jetson Nano使用CPU推理成功检测人脸，但使用Vulkan加速推理却无法检测人脸

### ISSUE THREAD

**Issue by mawj111** [Tencent/ncnn#4231]
按照官方说明，在Jetson Nano上对NCNN进行编译，将编译后的install文件拷贝到自己的人脸检测工程文件中。未开启vulkan时，可以正常检测人脸，但开启Vulkan加速后，即net.opt.use_vulkan_compute=1，通过jtop可以观察到显卡有相关进程，且检测的速率确实得到改善，但是无法检测出人脸，即无法标记出人脸框。已经查看相关的issue，已使用最新的NCNN，但仍然有这个错误，恳请各位大神帮助！

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/vulkan-notes#control-storage-and-arithmetic-precision
try disabling fp16 inference

**Comment by mawj111** [comment]
@nihui Thank you for your quick response. 
By disabling fp16 and int8 inference, the net is still unable to detect the face. After inspection, it is found that the reason is that the size of the input image is inconsistent with the input size required by the net. After the modification, the net uses the GPU through Vulkan, which successfully accelerates the inference. 
Thanks again from the bottom of my heart.
