### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by Iron-iii** [Tencent/ncnn#4239]
## error log | 日志或报错信息 | ログ
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/caffe/caffe2ncnn] Error 1
make[1]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/all] Error 2
## how to reproduce | 复现步骤 | 再現方法
1.Build for MacOS出错
2.小白求救-_-!!!
3.

**Comment by wzyforgit** [comment]
链接库的架构选错了吧，苹果机现在有x86和arm两种架构，自己在机器上重新编一下？

**Comment by wzyforgit** [comment]
而且看你报错是报在caffe2ncnn上的，可能是protobuf的问题？重编一下这个库，或者把工具编译给关掉

**Comment by Iron-iii** [comment]
> 链接库的架构选错了吧，苹果机现在有x86和arm两种架构，自己在机器上重新编一下？
感谢感谢，解决了
