### ISSUE TITLE
Pooling layer: global_pooling error

### ISSUE THREAD

**Issue by mychina75** [Tencent/ncnn#426]
Hi, @nihui 
thank you for your great work.

I found a bug in pooling.cpp.
If we use global_pooling param in prototxt file, will cause "Segmentation fault (core dumped)" error. 

in line 58.
top_blob.create(channels);  ===>>> top_blob.create(1,1,channels);

Regards~

**Comment by nihui** [comment]
what is the bottom blob shape and pooling layer parameter ?

**Comment by nihui** [comment]
close, feel free to re-open issue and provide more info

**Comment by jianbaba** [comment]
@nihui hi,使用global_pooling能训练也能跑通，但是caffemodel和ncnn结果完全不同。前一层是输出为3x4x512（w，h，c）的卷积层，池化输出为1x1x512。请问是为什么

**Comment by jianbaba** [comment]
我发现采用caffe的话，前一个卷积层输出是3x4x512，之后无论接pool还是conv，输出全是1x1x512。而采用ncnn，之后无论接pool还是conv，输出全是512x1x1。很奇怪

**Comment by jianbaba** [comment]
我发现采用caffe的话，前一个卷积层输出是3x4x512，之后无论接pool还是conv，输出全是1x1x512。而采用ncnn，之后无论接pool还是conv，输出全是512x1x1。很奇怪
@nihui

**Comment by nihui** [comment]
> 我发现采用caffe的话，前一个卷积层输出是3x4x512，之后无论接pool还是conv，输出全是1x1x512。而采用ncnn，之后无论接pool还是conv，输出全是512x1x1。很奇怪
> @nihui

输出的数值应该是正常的，shape不一样是框架的差异，ncnn对于1维数据，只会放在 w 维度上

**Comment by jianbaba** [comment]
但是数值也完全不一样，后面接fc的话数值一样，但是接pool或者flanten就不一样了，很奇怪



---Original---

**Comment by jianbaba** [comment]
您好，经过试验，我猜测可能是模型结构原因。请问ncnn是不是不支持caffe的分组卷积？我用普通卷积层没问题，换成分组卷积层就不可以了！

> > 我发现采用caffe的话，前一个卷积层输出是3x4x512，之后无论接pool还是conv，输出全是1x1x512。而采用ncnn，之后无论接pool还是conv，输出全是512x1x1。很奇怪
> > @nihui
> 
> 输出的数值应该是正常的，shape不一样是框架的差异，ncnn对于1维数据，只会放在 w 维度上

您好，经过试验，我猜测可能是模型结构原因。请问ncnn是不是不支持caffe的分组卷积？我用普通卷积层没问题，换成分组卷积层就不可以了！

**Comment by nihui** [comment]
caffe分组卷积是支持的
如果发现结果值不对，extract 中间blob核对，看是哪个layer导致的

**Comment by jianbaba** [comment]
> caffe分组卷积是支持的
> 如果发现结果值不对，extract 中间blob核对，看是哪个layer导致的

我做了几组实验：
普通卷积+fc，fc层输出正确，中间层也正确
普通卷积+pool，pool层输出不正确
分组卷积+fc，fc层输出不正确
分组卷积+pool，pool层输出不正确，中间层也不正确（第一个卷积层后的relu层的输出就不正确了,但是每个元素的对应的输出很相近）
最更人头疼的是caffemodel只有74%，而转化为ncnn后的准确率居然有96%。很费解
