### ISSUE TITLE
基于yolox模型，NetPrivate::forward_layer中递归导致栈空间耗尽

### ISSUE THREAD

**Issue by xudahong** [Tencent/ncnn#4269]
## detail | 详细描述 | 詳細な説明

使用开发板部署NCNN，执行下述代码时发生栈空间耗尽问题
~~~
        ncnn::Mat out;
        // ex.extract("output", out);
        ex.extract(yolox_param_id::BLOB_output, out);
~~~

## 问题定位

通过排查，定位到在net.cpp文件中int NetPrivate::forward_layer(int layer_index, std::vector<Mat>& blob_mats, const Option& opt) const函数中存在递归写法
~~~
    if (layer->one_blob_only)
    {
        // load bottom blob
        int bottom_blob_index = layer->bottoms[0];

        if (blob_mats[bottom_blob_index].dims == 0)
        {
            int ret = forward_layer(blobs[bottom_blob_index].producer, blob_mats, opt);
            if (ret != 0)
                return ret;
        }
    }
~~~

**请问有方法可以避免使用递归的方式实现吗**

**Comment by nihui** [comment]
递归写法不会导致栈溢出，yolox 递归深度最多只有几十个
更可能是你的开发板可用内存不足以跑 yolox
可以先试试跑 benchncnn

**Comment by xudahong** [comment]
> 递归写法不会导致栈溢出，yolox 递归深度最多只有几十个 更可能是你的开发板可用内存不足以跑 yolox 可以先试试跑 benchncnn

我这边确认了，确实是栈空间不足，原因是我这边申请的任务栈空间太小导致的，后续增大栈空间就没有这个问题了。squeezenet可以运行的起来的话，yolox应该也可以吧？这两者的内存占用会有很大的差异吗？

**Comment by wzyforgit** [comment]
如果硬要避免递归的话，就只能做成栈的方式了，就是递归化栈，用ADT栈实现
