### ISSUE TITLE
使用ncnn的simpleocv如何保存图像为视频？

### ISSUE THREAD

**Issue by tcexeexe** [Tencent/ncnn#4276]
项目需要将摄像头采集到的图像在本地保存为视频，想问下在不安装opencv的情况下，simpleocv是否有对应的函数？

**Comment by wzyforgit** [comment]
我记得up的opencv都是把这些乱七八糟东西裁干净了的，只保留核心的图像处理功能，以确保没有额外依赖
原版opencv视频方面能力是基于ffmpeg或者gstreamer的，你开启相关功能后它会去调这俩的库，后续发布也会强依赖这俩的其中之一

**Comment by tcexeexe** [comment]
> 我记得up的opencv都是把这些乱七八糟东西裁干净了的，只保留核心的图像处理功能，以确保没有额外依赖 原版opencv视频方面能力是基于ffmpeg或者gstreamer的，你开启相关功能后它会去调这俩的库，后续发布也会强依赖这俩的其中之一


就等于说simpleocv是不能保存视频的对吧

**Comment by wzyforgit** [comment]
> > 我记得up的opencv都是把这些乱七八糟东西裁干净了的，只保留核心的图像处理功能，以确保没有额外依赖 原版opencv视频方面能力是基于ffmpeg或者gstreamer的，你开启相关功能后它会去调这俩的库，后续发布也会强依赖这俩的其中之一
> 
> 就等于说simpleocv是不能保存视频的对吧

是这样的，以此来保证整个项目没有强依赖那些奇奇怪怪的库

**Comment by wzyforgit** [comment]
我建议你参考一下up的opencv-mobile项目，里面有教怎么裁剪opencv，如果有需要的话，可以打开视频相关的功能

**Comment by tcexeexe** [comment]
> 我建议你参考一下up的opencv-mobile项目，里面有教怎么裁剪opencv，如果有需要的话，可以打开视频相关的功能

好的，感谢
