### ISSUE TITLE
报错:param is too old, please regenerate

### ISSUE THREAD

**Issue by lyp0413** [Tencent/ncnn#428]
tensorflow2ncnn转出的模型，运行时遇到这个问题，希望有大神解答

**Comment by nihui** [comment]
generally, it is hard to convert tensorflow model to others. you'd better try caffe pytorch or mxnet ...
see #5

**Comment by suzaku** [comment]
I came across the same issue when loading files generated by `caffe2ncnn`.

The `prototxt` and `caffemodel` files were already upgraded using `upgrade_net_proto_text` and `upgrade_net_proto_binary`, but still `ncnn` complained that the `param is too old`.

**Comment by lyp0413** [comment]
@suzaku How did you load your model data to your code?

**Comment by suzaku** [comment]
@lyp0413 

As documented in the wiki:

```c++
ncnn::Net net;
net.load_param("alexnet.param");
net.load_model("alexnet.bin");
```
With the parameters replaced with my own files.

**Comment by lyp0413** [comment]
@suzaku 
check the first line in your .param.
Your model was not converted well,if it is not 7767517.

**Comment by dzyjjpy** [comment]
file:///home/lucky/workspace/ncnn-master/build/examples/demo.param
file:///home/lucky/workspace/ncnn-master/build/examples/demo.bin
@suzaku @lyp0413
So did you solve the issue? 
I use upgrade_ command to get the new prototxt and caffemodel: 
$ ./upgrade_net_proto_text deploy.prototxt new_deploy.prototxt   #  .ptototxt file 
$ ./upgrade_net_proto_binary bvlc_alexnet.caffemodel new_bvlc_alexnet.caffemodel   #  
    
Also, I checked the first line in new.param, it starts with 7767517, like 
7767517
24 24
Input            data  ...

but still had the errors:
    param is too old, please regenerate
    段错误 (核心已转储)
