### ISSUE TITLE
能实现类似caffe的blob reshape功能？

### ISSUE THREAD

**Issue by maydaying** [Tencent/ncnn#43]
对于input层的height和width可变的情况，或者说像图像金字塔那样，输入层的尺寸是有多个的情况，用ncnn该怎么做比较好？

**Comment by nihui** [comment]
类似于 fcn 的网络，直接用就可以了，input 大小变化，出来的 output 也会自动变化。input 层的 c h w 实际不会强制检查

**Comment by jasminezz** [comment]
@maydaying 有解决问题吗？
