### ISSUE TITLE
can "ncnn" be used to run YOLO7 on AMD GPU?

### ISSUE THREAD

**Issue by rajhlinux** [Tencent/ncnn#4301]
Hello, can ncnn be used so that we can run YOLO7 for AMD GPU on Linux?

Thanks.

**Comment by nihui** [comment]
yeah, with vulkan api

**Comment by rajhlinux** [comment]
Thank you for your response, are there any guide I can follow for installation?

Thanks.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build
