### ISSUE TITLE
开发板移植yolov5n模型触发data abort异常

### ISSUE THREAD

**Issue by xudahong** [Tencent/ncnn#4307]
## detail | 详细描述 | 詳細な説明

使用开发板搭建基于yolov5n模型的ncnn应用，在运行时触发data abort问题。触发异常时，寄存器信息整理如下：

![image](https://user-images.githubusercontent.com/65880422/198171844-1b147e67-d101-4d6b-a495-afe06a0df9a5.png)

<br>

## 问题排查

目前排查触发问题的节点位于yolov5.cpp文件中的ex.extract(exp6_imgsz320_train_simply_param_id::BLOB_output, out);语句
![image](https://user-images.githubusercontent.com/65880422/198173881-884915a4-8e6d-4245-967c-ca919cbb2af2.png)

进一步分析问题触发节点，在ncnn库中查找触发问题的对应信息。使用汇编文件对栈指针进行分析，获得触发问题的指针节点如下图所示。
![image](https://user-images.githubusercontent.com/65880422/198174353-a184e8cb-5134-4190-932b-91fb163383ca.png)

上图中的指令节点对应的代码区域为
![image](https://user-images.githubusercontent.com/65880422/198174585-881355c7-1fec-40c8-ad23-6ecd503cab73.png)

<br>

## 问题总结

根据上述问题排查信息，问题触发的大致脉络为，程序执行ex.extract时，使用递归方式对每一层网络进行forward实现，在运行convolution_arm的farward实现时，程序访问了空指针，触发了data abort异常。

<br>

## 问题触发原因的可能性探究

当前我们已经在开发板上实现了squeezenet模型与yolox_nano模型的ncnn应用搭建，均可正常运行。搭建yolox_nano模型时，实际也遇到了类似的问题，但该问题最终通过将use_packing_layout置为false，关闭优化方面的内存占用解决了data abort问题。yolov5n模型的问题看起来与yolox_nano模型的问题相近，**怀疑是否是由于内存空间不足导致的问题？**（当然，我们也在yolov5n模型上将use_packing_layout置为false了）(ಥ_ಥ) 

@nihui 麻烦大佬帮我们看下这个问题，谢谢！！ヾ(＠゜▽゜@)ノ

**Comment by xudahong** [comment]
关于内存空间不足的问题，我们也看了下触发问题节点时，堆栈的使用情况。
其中，堆空间还有约7M的空间未被使用，其中最大的连续堆空间大小约为5.6M左右。
（5M的空间应该够空间的申请使用吧[・_・?]）

栈空间预分配了50KB的大小，触发时仅占用了约5KB的空间。

**Comment by xudahong** [comment]
By the way，在使用yolov5n模型时，我们通过将use_packing_layout置为false，以及将、use_bf16_storage置为true的方式，尽量减少了模型对内存的空间占用。

**Comment by nihui** [comment]
还有两个降速降内存的开关
use_sgemm_convolution = false;
use_winograd_convolution = false;

**Comment by xudahong** [comment]
> 还有两个降速降内存的开关 use_sgemm_convolution = false; use_winograd_convolution = false;

关掉后，ncnn应用可以正常运行起来了。ヾ(ﾟ∀ﾟゞ)

大佬yyds!!!!

**Comment by nihui** [comment]
> > 还有两个降速降内存的开关 use_sgemm_convolution = false; use_winograd_convolution = false;
> 
> 关掉后，ncnn应用可以正常运行起来了。ヾ(ﾟ∀ﾟゞ)
> 
> 大佬yyds!!!!

你的开发板内存可真够少的。。。

**Comment by jasonlamsz** [comment]
> > > 还有两个降速降内存的开关 use_sgemm_convolution = false; use_winograd_convolution = false;
> > 
> > 
> > 关掉后，ncnn应用可以正常运行起来了。ヾ(ﾟ∀ﾟゞ)
> > 大佬yyds!!!!
> 
> 你的开发板内存可真够少的。。。

Hello @nihui , 请问下如何该模型在ncnn应用需要消耗多大的内存（堆空间）？

**Comment by xudahong** [comment]
> 

我们开发板内存总共才64M,其中46M空间是给堆空间使用的|ू･ω･` )

**Comment by xudahong** [comment]
> > > > 还有两个降速降内存的开关 use_sgemm_convolution = false; use_winograd_convolution = false;
> > > 
> > > 
> > > 关掉后，ncnn应用可以正常运行起来了。ヾ(ﾟ∀ﾟゞ)
> > > 大佬yyds!!!!
> > 
> > 
> > 你的开发板内存可真够少的。。。
> 
> Hello @nihui , 请问下如何确认该模型在ncnn应用需要消耗多大的内存（堆空间）？

我们这边是通过获取堆空间的最大使用量来确认的，你们应该也可以这么干

**Comment by xudahong** [comment]
另外问下，我们在虚拟机上测试ncnn应用的RAM占用空间约为40M(40280KB)，但在虚拟机上ncnn占用的堆空间大约是10MB。

这个差距有些大，请问这是正常的吗？（ubuntu环境与arm环境运行流程不同导致？瞎猜）

![image](https://user-images.githubusercontent.com/65880422/198234824-a68a58c0-a986-4d41-a3bd-499e5dd6d567.png)


@nihui
