### ISSUE TITLE
yolov5 6.2 extract "output" crashed: bottom_blob_ref.refcount was nullptr.

### ISSUE THREAD

**Issue by Mactarvish** [Tencent/ncnn#4309]
## error log | 日志或报错信息 | ログ
```
发生异常: W32/0xC0000005
Unhandled exception thrown: read access violation.
bottom_blob_ref.refcount was nullptr.
```
![image](https://user-images.githubusercontent.com/13399458/198237724-16e54f69-544f-4ebb-aa3e-5c7e2c07d372.png)

## model | 模型 | モデル
1. original model
https://github.com/ultralytics/yolov5/releases/download/v6.2/yolov5s.pt

## how to reproduce | 复现步骤 | 再現方法
1. `git clone https://github.com/ultralytics/yolov5`
2. `python detect.py`  (in order to download the .pt below)
3. `python export.py --weights yolov5s.pt --include onnx  --img 640 --simplify`
4. `D:\ncnn\debug_build\install\bin\onnx2ncnn.exe   C:\Users\jerry\Desktop\yolov5s.onnx C:\Users\jerry\Desktop\yolov5s_6.0.param C:\Users\jerry\Desktop\yolov5s_6.0.bin`
5. execute the original yolov5 example

这里我编译了debug版本的ncnn以便调试源代码，可以看到在执行extract函数时，`bottom_blob` 为空
使用nihui提供的bin和param可以正常运行而没有出现该问题

**Comment by nihui** [comment]
export.py 需要 --train 参数
参考 https://zhuanlan.zhihu.com/p/471357671

**Comment by Mactarvish** [comment]
@nihui 
感谢，加上train并重新指定extract的层之后可以跑通了，但是结果不对，满图都是框而且置信度非常高，是还需要修改什么地方吗？

**Comment by xudahong** [comment]
> @nihui 感谢，加上train并重新指定extract的层之后可以跑通了，但是结果不对，满图都是框而且置信度非常高，是还需要修改什么地方吗？

我也遇到同样的问题，我这边的解决方式是去修改param文件，将param文件中的reshape的0=xxx,改为0=-1

![image](https://user-images.githubusercontent.com/65880422/198424217-24197210-9286-4952-bbb2-68a43f86f52c.png)

**Comment by Mactarvish** [comment]
> 

感谢！可以了！

**Comment by Mactarvish** [comment]
@xudahong 

感谢！可以了！

**Comment by xudahong** [comment]
> @xudahong
> 
> 感谢！可以了！

感谢nihui大佬吧，都是参考他的文章改的。(￣ω￣;)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by Paraniod1** [comment]
> > @nihui 感谢，加上train并重新指定extract的层之后可以跑通了，但是结果不对，满图都是框而且置信度非常高，是还需要修改什么地方吗？
> 
> 我也遇到同样的问题，我这边的解决方式是去修改param文件，将param文件中的reshape的0=xxx,改为0=-1
> 
> ![image](https://user-images.githubusercontent.com/65880422/198424217-24197210-9286-4952-bbb2-68a43f86f52c.png)

yolov5 6.2版本改了-1还是没有，效果太差了
