### ISSUE TITLE
groupnorm在c++上调用出错

### ISSUE THREAD

**Issue by MrCary** [Tencent/ncnn#4310]
## error log | 日志或报错信息 | ログ
![image](https://user-images.githubusercontent.com/28701781/198344090-25e3cbd0-beee-4b92-83a3-004fe2be77c1.png)

## context | 编译/运行环境 | バックグラウンド
window10
torchversion: '1.12.1+cu116'
pnnx：20221020-windows
ncnn：22.10.25更新的最新版

## how to reproduce | 复现步骤 | 再現方法
1.pytorch代码生成pt：相关代码在以下链接
![image](https://user-images.githubusercontent.com/28701781/198343105-cc575dcf-c146-448e-9809-637dbecbb158.png)
2.pnnx转ncnn：
pnnx wav2vec3.pt inputshape=[1,1,400]
3.c++调用报错：
![image](https://user-images.githubusercontent.com/28701781/198344052-1696da0d-40e1-4b6b-9b39-eeb81620dc38.png)

## more | 其他 | その他
经过实验，nn.groupnorm当输入的是二维（b, c, h,w）时，转成ncnn后，调用不会报错，而当nn.groupnorm当输入的是(b,c,h)时，转成ncnn后，调用就会出错。

相关param及bin链接，及相关代码
链接: https://pan.baidu.com/s/1cw6kYo3SqRiP4M77j5kIhg?pwd=1111 提取码: 1111

**Comment by nihui** [comment]
已确认

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4312

**Comment by nihui** [comment]
groupnorm 已支持 1d/3d/4d 输入
pnnx 默认会自动去除末尾的 transpose 操作，issue 中的模型其他算子结果正常
感谢反馈！
