### ISSUE TITLE
pnnx转换出错

### ISSUE THREAD

**Issue by MrCary** [Tencent/ncnn#4313]
## error log | 日志或报错信息 | ログ
使用pnnx转换时，crop操作消失
## model | 模型 | モデル
1. original model
环境;
window10
pnnx：20221020
## how to reproduce | 复现步骤 | 再現方法
1.导出pt模型
![image](https://user-images.githubusercontent.com/28701781/198821198-95e77f53-a207-4d53-980c-2845cae06762.png)

2.通过pnnx转换成onnx
pnnx wav2vec4.pt

3.通过netron查看模型结构
![image](https://user-images.githubusercontent.com/28701781/198821214-40e0baeb-bf6b-42b0-979d-1883e6f2e829.png)
相关模型文件及pytorch代码
[pnnx_wrong.zip](https://github.com/Tencent/ncnn/files/9893248/pnnx_wrong.zip)

**Comment by nihui** [comment]
已确认

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
