### ISSUE TITLE
开发板上使用yolov5n模型的NCNN应用无法检测出结果

### ISSUE THREAD

**Issue by xudahong** [Tencent/ncnn#4319]
## detail | 详细描述 | 詳細な説明

使用开发板运行yolov5n模型的NCNN应用，传入数据为BMP图像数据，from_pixels_resize设置type参数为ncnn::Mat::PIXEL_GRAY，程序无法得出任何检测结果。在虚拟机上使用相同的图片数据以及type参数，可以识别到目标。

之前测试NCNN应用传入BGR图像数据，from_pixels_resize设置type参数为ncnn::Mat::PIXEL_BGR，可正常得出检测结果。

<br>

## 问题排查

进行对比测试，在开发板的NCNN应用中传入BMP图像数据，from_pixels_resize设置type参数为ncnn::Mat::PIXEL_GRAY2BGR，此时NCNN应用可以得出和虚拟机相同的检测结果。

看起来不会是因为开发板运行的问题导致，应该是由于NCNN应用使用的type参数不同导致的问题？

## 补充信息

使用的模型是我们自己训练出来的模型，resize大小为320。运行是设置了use_sgemm_convolution为false。

@nihui 求大佬帮忙看下此问题●|￣|＿

**Comment by wzyforgit** [comment]
你保存一下开发板送入NCNN内部前的矩阵啊，和你在虚拟机里捣鼓的对比一下
然后你也没说你是啥开发板

**Comment by xudahong** [comment]
> 你保存一下开发板送入NCNN内部前的矩阵啊，和你在虚拟机里捣鼓的对比一下 然后你也没说你是啥开发板

我用的开发板是SigmaStar SSC9211的开发板。

传入的图像数据已和虚拟机上传入的图像数据对比过了，是完全一致的。

**Comment by xudahong** [comment]
开发板上的yolov5_ncnn应用程序文件如下所示

[yolov5.zip](https://github.com/Tencent/ncnn/files/9915534/yolov5.zip)

**Comment by yc66542260** [comment]
这个问题有解决吗？
