### ISSUE TITLE
ubuntu中使用ndk-build编译so出现错误

### ISSUE THREAD

**Issue by dingruoxiu** [Tencent/ncnn#432]
Android NDK: WARNING: APP_PLATFORM android-26 is higher than android:minSdkVersion 1 in /home/siasun/Downloads/squeezencnn-AS/app/src/main/AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-26. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
[armeabi-v7a] Compile++ thumb: squeezencnn <= squeezencnn_jni.cpp
/home/siasun/Downloads/squeezencnn-AS/app/src/main/jni/squeezencnn_jni.cpp: In function '_jstring* Java_com_tencent_squeezencnn_SqueezeNcnn_Detect(JNIEnv*, jobject, jobject)':
/home/siasun/Downloads/squeezencnn-AS/app/src/main/jni/squeezencnn_jni.cpp:149:65: warning: pointer of type 'void *' used in arithmetic [-Wpointer-arith]
             const float* prob = (float*)(out.data + out.cstep * j);
                                                                 ^
[armeabi-v7a] SharedLibrary  : libsqueezencnn.so
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:164: error: undefined reference to '__kmpc_fork_call'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:33: error: undefined reference to '__kmpc_for_static_init_4'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:32: error: undefined reference to '__kmpc_for_static_fini'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:99: error: undefined reference to '__kmpc_for_static_init_4'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:98: error: undefined reference to '__kmpc_for_static_fini'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:165: error: undefined reference to '__kmpc_for_static_init_4'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:164: error: undefined reference to '__kmpc_for_static_fini'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:529: error: undefined reference to '__kmpc_fork_call'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:530: error: undefined reference to '__kmpc_for_static_init_4'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:529: error: undefined reference to '__kmpc_for_static_fini'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:594: error: undefined reference to '__kmpc_fork_call'
/home/siasun/dingruoxiu/ncnn-master/src/mat.cpp:849: error: undefined reference to '__kmpc_fork_call'
/home/siasun/dingruoxiu/ncnn-master/src/layer/convolutiondepthwise.cpp:180: error: undefined reference to '__kmpc_for_static_init_8'
collect2: error: ld returned 1 exit status
make: *** [/home/siasun/Downloads/squeezencnn-AS/app/src/main/obj/local/armeabi-v7a/libsqueezencnn.so] Error 1有人遇到这种问题吗？

**Comment by nihui** [comment]
参考 https://github.com/Tencent/ncnn/issues/292
