### ISSUE TITLE
YOLOV5在特定尺寸下第三层输出异常

### ISSUE THREAD

**Issue by 408550969** [Tencent/ncnn#4320]
在480*288，或者480*352下（目前能确定这两个分辨率会异常）yolov5或者yolov5-face的模型在ncnn下第三层的输出异常，同样尺寸在pytorch下无异常。
因为pt转onnx时，resize会变成固定的上采样2倍，已经保证图片为32的倍数，且pytorch和ncnn一致性验证通过。
在更高分辨率比如640*384下无异常。貌似是在低分辨率下Height除以32为奇数时会存在这个问题
ncnn版本为最新的0722版本

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
