### ISSUE TITLE
how import a pytorch model in ncnn? any examples? thanks

### ISSUE THREAD

**Issue by utc1205** [Tencent/ncnn#433]

**Comment by nihui** [comment]
you may try https://github.com/starimeL/PytorchConverter for pytorch-0.2
or though onnx model for new versions

**Comment by utc1205** [comment]
thanks for your reply, a model trained by pytorch-0.3 can be loaded by pytorch-0.2 ? or I still need train a new model by pytorch-0.2 ?

**Comment by nihui** [comment]
you have to try it yourself ~

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
