### ISSUE TITLE
头部姿态估计模型FSANet部署问题

### ISSUE THREAD

**Issue by mawj111** [Tencent/ncnn#4345]
使用Pytorch->onnx->ncnn步骤对FSANet进行模型转换并进行ncnn部署推理，结果一直报错"段错误（核心已转储）"。
检查onnx模型后，发现其中存在div、pow、mul等node，是否ncnn不支持这些node的op？我需要自定义相应的ncnn layer吗？
相应的模型文件如下，麻烦各位大佬帮忙解答一下，感谢！
[model.zip](https://github.com/Tencent/ncnn/files/9993941/model.zip)

**Comment by mawj111** [comment]
input = [1, 3, 64, 64]
mean = [127.5, 127.5, 127.5]
norm = [1/128.f, 1/128.f, 1/128.f]

**Comment by nihui** [comment]
尝试使用 pnnx 转换 pytorch 模型到 ncnn
https://github.com/pnnx/pnnx

**Comment by mawj111** [comment]
@nihui 非常感谢您的快速回复，今天刚开始尝试使用最新的windows版本的pnnx.exe转换工具，在转换如retinaface等简单的模型时，转换成功并且成功使用ncnn部署。但在使用pnnx转换FSANet模型时遇到如下图一些问题。
![ORC38V63_(O$Z~84R{Z_~9I](https://user-images.githubusercontent.com/65847115/201462385-d9e4afa9-ef42-47d4-b288-59f84bb2fae2.png)
![P25FNQ``PL~K3)_TNGF9$7V](https://user-images.githubusercontent.com/65847115/201462388-b067d3e0-299d-4338-b3f9-63e35de39e7c.png)

**Comment by mawj111** [comment]
使用的pt文件如下
[FSANet_Conv.zip](https://github.com/Tencent/ncnn/files/9994414/FSANet_Conv.zip)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4346

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
