### ISSUE TITLE
optional pixel rotate api

### ISSUE THREAD

**Issue by nihui** [Tencent/ncnn#435]

**Comment by pribadihcr** [comment]
+1

**Comment by nihilityworld** [comment]
??when this api can be used?

**Comment by soham24** [comment]
+1

**Comment by chosungmann** [comment]
+100

**Comment by soham24** [comment]
@nihui

**Comment by soham24** [comment]
On lighter note

**Comment by soham24** [comment]
+1
any update on this?
As you have mentioned you have this code on your local branch? 
Can you share it?

**Comment by nihui** [comment]
will be added in the next coming release

**Comment by nihui** [comment]
pixel rotate api added in https://github.com/Tencent/ncnn/commit/1009b539aad42a0c0ac62143af61ae21fb8b1ee1
