### ISSUE TITLE
windows 是否不支持kmp_set_blocktime(time_ms)这个方法？

### ISSUE THREAD

**Issue by anliyuan** [Tencent/ncnn#4355]
windows 是否不支持kmp_set_blocktime(time_ms)这个方法？

**Comment by nihui** [comment]
msvc的omp不支持

**Comment by anliyuan** [comment]
> msvc的omp不支持 clang的libomp有

谢谢大佬

**Comment by anliyuan** [comment]
> msvc的omp不支持 clang的libomp有

大佬 windows是否能设置线程的睡眠时间呢？
