### ISSUE TITLE
bad result with onnx converted model

### ISSUE THREAD

**Issue by junedgar** [Tencent/ncnn#436]
I trained mobilenetv2 model which used the pytorch 0.4.  Then i converted the pythorch model to onnx model  followed the [guidance](https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html) . In the end, i used the onnx2ncnn tool to convert the onnx model, but the output matrix always None.

I also use the [PytorchConverter](https://github.com/starimeL/PytorchConverter) , but results didn't match which tested on python.

Can you show me some ncnn examples which use the model converted from pytorch?

Thank you @nihui

**Comment by junedgar** [comment]
I solved the problem by using PytorchConverter,  there is something wrong when I preprocessed the image.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
