### ISSUE TITLE
blob index is mismatched by caffe2ncnn and ncnn2mem 

### ISSUE THREAD

**Issue by bobby-chiu** [Tencent/ncnn#437]
hi, i converted caffe model by caffe2ncnn and got *.param and *bin model file with 178 blob counts, but when compiled *.param by ncnn2mem, it tried to write blob_index to blob_names with 178 and lead to Segmentation fault (core dumped at split layer), which exceeded the maximum blob_names size (with 178 count). I review the code but not found the cause. Any ideas?

**Comment by nihui** [comment]
please provide a minimal caffe prototxt that could reproduce your issue

**Comment by bobby-chiu** [comment]
I have fixed the problem. The error occurred when the train phase and test phase were configured in the same prototxt, as follows:
layer {
  name: "bn1"
  type: "BatchNorm"
  bottom: "conv1"
  top: "conv1"

  include {
    phase: TRAIN
  }
}
layer {
  name: "bn1"
  type: "BatchNorm"
  bottom: "conv1"
  top: "conv1"
  include {
    phase: TEST
  }
}

So maybe when converting model from caffe, caffe2ncnn could check the valid layer and ignore the invalid layer. Beacause the model file is available for caffe framework.
