### ISSUE TITLE
ncnn from pixel之后数据变为int ？

### ISSUE THREAD

**Issue by Stephenfang51** [Tencent/ncnn#4380]
## detail | 详细描述 | 詳細な説明

首先感谢ncnn
我有一个数据输入但不是图像， 而是一个二维的浮点数组 比如[32,63]这样的数据
cv mat格式下打印看是正常的，
执行转换之后
`ncnn::Mat::from_pixels(input_.data, ncnn::Mat::PIXEL_GRAY,input_.cols,  input_.rows)`

用wiki 提供的print方法看 全变为整型了
请问有什么方法解吗 
谢谢 !

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-opencv
参考 cv::Mat CV_32FC1 -> ncnn::Mat 1 channel

**Comment by Stephenfang51** [comment]
> https://github.com/Tencent/ncnn/wiki/use-ncnn-with-opencv 参考 cv::Mat CV_32FC1 -> ncnn::Mat 1 channel

Thanks you 1
