### ISSUE TITLE
20190320版本arm与x86推理结果不一致

### ISSUE THREAD

**Issue by ssr920121** [Tencent/ncnn#4382]
基于2019年3月20号的ncnn版本推理int8模型，发现x86运行出来的结果与arm neon运行结果不一致。输出的浮点结果无法bit true，但是大致差距在小数点，整数位没有明显区别。

请问这是符合预期的，还是属于bug？新版的ncnn是否能做到arm和x86 bit true？

**Comment by wzyforgit** [comment]
今夕是何年

**Comment by nihui** [comment]
新版ncnn有全面的单元测试，确保各个架构输出的结果一致
int8模型因为平台差异，round模式会导致结果有小数点后的细微区别，不能bit一致，这是符合预期的
