### ISSUE TITLE
benchncnn运行出现“fopen /proc/self/auxv failed“

### ISSUE THREAD

**Issue by cbldlpl** [Tencent/ncnn#4386]
工作平台：linux20.04
工具链：aarch64-linux-musl
目标平台：aarch64
在工作平台交叉编译之后移到目标平台，运行benchncnn，出现fopen /proc/self/auxv failed，
源码中在cpu.cpp的函数get_elf_hwcap_from_proc_self_auxv中，
想问几个问题
1.此函数获得获取的信息是什么，线程还是核的数量呢？或者其他？
2.发现系统中没有这个文件，是否有其他方法解决这个问题，获取相关信息？
3.出现了这行字仍能运行，会对运行的性能产生什么影响呢？
Look forward to your favourable reply！

**Comment by nihui** [comment]
1. /proc/self/auxv 获得当前 cpu 支持的指令集，比如 neon fp16 等
2. 如果目标平台已知，比如armv8.2，可以 ```-DNCNN_RUNTIME_CPU=OFF -DNCNN_ARM82=ON``` 编译，禁用运行时检测并强制开启armv8.2相关指令，这时候如果平台实际不支持armv8.2会illegal instruction
3. 将无法检测更新的扩展指令，不会受新指令集的加速
