### ISSUE TITLE
Android端切换前后置摄像头,导致ex.extract 执行时间不一致的问题

### ISSUE THREAD

**Issue by whr18756973961** [Tencent/ncnn#4390]
nihui你好, 我使用了demo  ncnn_android_mediapipe作为参考,来调试人脸识别相关的功能,我发现,landmark.cpp中的detect方法在打开前置摄像头时,人脸平均耗时在10ms以内,而切换到后置摄像头后,单人脸耗时在15-20,基本上增大了一倍.  而且同时我这边使用了一了一张相同的位图来识别,发现前后置的时间基本上也有一倍左右的差距.
同时我这边人landmark的人脸识别设置都是    
    ncnn::set_cpu_powersave(2);
    ncnn::set_omp_num_threads(2);
能帮忙排查下这种情况产生的原因吗?

**Comment by wzyforgit** [comment]
你最终传入神经网络的矩阵大小一样嘛？

**Comment by whr18756973961** [comment]
是的

**Comment by whr18756973961** [comment]
这个问题发现是face的set_omp_num_threads设置的过大了,目前调小了发现好多了

**Comment by whr18756973961** [comment]
已解决
