### ISSUE TITLE
caffe model convert error

### ISSUE THREAD

**Issue by hiwudery** [Tencent/ncnn#440]
./ssdmobilenet person.jpg
find_blob_index_by_name data_splitncnn_6 failed
find_blob_index_by_name data_splitncnn_5 failed
find_blob_index_by_name data_splitncnn_4 failed
find_blob_index_by_name data_splitncnn_3 failed
find_blob_index_by_name data_splitncnn_2 failed
find_blob_index_by_name data_splitncnn_1 failed
find_blob_index_by_name data_splitncnn_0 failed
Segmentation fault (core dumped)
------------------------------------------------------------
the following URL Link is the the caffe model.
https://drive.google.com/drive/folders/1GMflZxHrVr5mt6Y70PK6cGD2YURcSpOq?usp=sharing

**Comment by Ewenwan** [comment]
你好，这个问题解决了吗我的也是这种问题，分类网络没问题，squeezenet-ssd 和mobilenet-ssd检测网络出现这种错误

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error

**Comment by hiwudery** [comment]
Thanks nihui's hit. I fixed the problem.

The model generator of caffe-mobilenet-ssd generates old caffe model format, so we have to convert the training results of  caffe-mobilenet-ssd to new caffe model format.
the tools' names are "upgrade_net_proto_text" and "upgrade_net_proto_binary", you can find them in the caffe-ssd. 

----------------------------------------------------------------------------------------------------------------
[https://github.com/Tencent/ncnn/wiki/how-to-use-ncnn-with-alexnet](url)
convert to ncnn model

Convert old caffe prototxt and caffemodel to new ones using tools in caffe-ssd.
because the ncnn convert tool needs the new format

upgrade_net_proto_text  [old prototxt] [new prototxt]
upgrade_net_proto_binary [old caffemodel] [new caffemodel]

**Comment by xiaofengren** [comment]
I downloaded model from link (https://drive.google.com/drive/folders/1GMflZxHrVr5mt6Y70PK6cGD2YURcSpOq) and follow above suggestion to upgrade caffe prototxt and model.

When I upgrade caffe prototxt, I got following error:

root@Ubuntu:~/AI/ncnn/mobilessd# ~/AI/caffe/build/tools/upgrade_net_proto_text MobileNetSSD_deploy.prototxt MobileNetSSD_deploy_new.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:307] Error parsing text-format caffe.NetParameter: 1177:17: Message type "caffe.LayerParameter" has no field named "permute_param".
E0815 16:41:19.447813 29988 upgrade_net_proto_text.cpp:30] Failed to parse input text file as NetParameter: MobileNetSSD_deploy.prototxt

When I upgrade caffe model, it reminded me that caffe model is already latest one, like as following.  

root@Ubuntu:~/AI/ncnn/mobilessd# ~/AI/caffe/build/tools/upgrade_net_proto_binary MobileNetSSD_deploy.caffemodel MobileNetSSD_deploy_new.caffemodel
E0815 16:14:40.151506 29271 upgrade_net_proto_binary.cpp:43] File already in latest proto format: MobileNetSSD_deploy.caffemodel
I0815 16:14:40.192387 29271 upgrade_net_proto_binary.cpp:48] Wrote upgraded NetParameter binary proto to MobileNetSSD_deploy_new.caffemodel

Meanwhile, I also tried to use ncnn model and param downloaded from https://drive.google.com/drive/folders/1GMflZxHrVr5mt6Y70PK6cGD2YURcSpOq, it report same error as hiwudery mentioned in 1st post. 

it will be appreciated if anyone can share some suggestion.

**Comment by xiaofengren** [comment]
After downloaded new ncnn model from this link: https://drive.google.com/drive/folders/0ByaKLD9QaPtucWk0Y0dha1VVY0U . Now mobilenetssd can work.
