### ISSUE TITLE
Binaryop层内存越界

### ISSUE THREAD

**Issue by Elasine** [Tencent/ncnn#4408]
## error log | 日志或报错信息 | ログ
Segmentation fault.
0x000055555650332b in ncnn::binary_op_pack16<ncnn::BinaryOp_x86_avx512_functor::binary_op_add> (a=..., b=..., c=..., opt=...)
    at /**/ncnn/build/src/layer/x86/binaryop_x86_avx512.cpp:928
928                         std::cout << "outptr * :" << *outptr << std::endl;

## context | 编译/运行环境 | バックグラウンド
-- NCNN_VERSION_STRING = 1.0.20221209
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Target arch: x86

## how to reproduce | 复现步骤 | 再現方法
ncnn/src/layer/x86/binaryop_x86.cpp
 915              float* outptr = c;
   916
   917              std::cout << "c.w:" << c.w << ",c.h:" << c.h << ",c.dims:" << c.dims << std::endl;
   918
   919              for (int y = 0; y < h1; y++)
   920              {
   921                  __m512 _a0 = _mm512_loadu_ps(ptr);
   922                  for (int x = 0; x < w1; x++)
   923                  {
   924                      __m512 _p1 = _mm512_loadu_ps(ptr1);
   925                      __m512 _outp = op.func_pack16(_a0, _p1);
   926
   927                      std::cout << "outptr :" << *outptr << std::endl;
   928
   929                      _mm512_storeu_ps(outptr, _outp);
   930
   931                      ptr1 += 16;
   932                      outptr += 16;
   933                  }
   934
   935                  ptr += 16;
   936              }

(gdb) p w1
$3 = 1024

(gdb) p h1
$4 = 257

(gdb) p x
$47 = 115

(gdb) p y
$48 = 18

(gdb) p c.data
$49 = (void *) 0x55557b872340

(gdb) p outptr
$51 = (float *) 0x55557b994000

(gdb) p ((float*)c.data)[1023*256]
$13 = 1.79657185

(gdb) p &((float*)c.data)[1023*256]
$14 = (float *) 0x55557b971f40

   
hex(0x55557b872340+18*1024*16*4+115*16*4)
'0x55557b994000'

outptr 已经超过了 c.data 范围

for (int y = 0; y < h1; y++)
for (int x = 0; x < w1; x++)

两个 for 循环的 ++ 是否要改用 += 16

**Comment by Yoh-Z** [comment]
看下输入的a b两个tensor的whcd一样吗，ncnn貌似不支持广播机制，如果没有完全对齐，会有一个tensor越界

**Comment by Yoh-Z** [comment]
> > 看下输入的a b两个tensor的whcd一样吗，ncnn貌似不支持广播机制，如果没有完全对齐，会有一个tensor越界
> 
> 这里面说支持的 https://github.com/Tencent/ncnn/wiki/binaryop-broadcasting

嗯，那应该是有广播机制的。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/ab4cfbf5b05550f38f6aa562c1e583fa92d73da3

需要使用 pnnx 转换模型
