### ISSUE TITLE
NCNN 编译  是否支持 MT_StaticRelease 

### ISSUE THREAD

**Issue by z13228604287** [Tencent/ncnn#4409]
error LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MD_DynamicRelease”不匹配值“MT_StaticRelease”
| 因某些特殊需求，需要编译 MT 静态库 |
 NCNN 是否支持  如果支持  需要做哪些修改了？

**Comment by nihui** [comment]
```cmake -DNCNN_BUILD_WITH_STATIC_CRT=ON ..```

**Comment by z13228604287** [comment]
感谢 @nihui  女神提供的解决方案！
ncnn.lib 已生成
但出现如下错误：
`libprotobuf.lib(zero_copy_stream_impl.cc.obj) : error LNK2019: 无法解析的外部符号 __imp_strerror，函数 "public: virtual __cdecl google::protobuf::io::FileInputStream::CopyingFileInputStream::~CopyingFileInputStream(void)" (??1CopyingFileInputStream@FileInputStream@io@protobuf@google@@UEAA@XZ) 中引用了该符号
libprotobuf.lib(io_win32.cc.obj) : error LNK2019: 无法解析的外部符号 __imp__wchdir，函数 "int __cdecl google::protobuf::internal::win32::chdir(char const *)" (?chdir@win32@internal@protobuf@google@@YAHPEBD@Z) 中引用了该符号
libprotobuf.lib(io_win32.cc.obj) : error LNK2019: 无法解析的外部符号 __imp__wmkdir，函数 "int __cdecl google::protobuf::internal::win32::mkdir(char const *,int)" (?mkdir@win32@internal@protobuf@google@@YAHPEBDH@Z) 中引用了该符号
libprotobuf.lib(io_win32.cc.obj) : error LNK2019: 无法解析的外部符号 __imp__waccess，函数 "int __cdecl google::protobuf::internal::win32::access(char const *,int)" (?access@win32@internal@protobuf@google@@YAHPEBDH@Z) 中引用了该符号
libprotobuf.lib(io_win32.cc.obj) : error LNK2019: 无法解析的外部符号 __imp__dup，函数 "int __cdecl google::protobuf::internal::win32::dup(int)" (?dup@win32@internal@protobuf@google@@YAHH@Z) 中引用了该符号
libprotobuf.lib(io_win32.cc.obj) : error LNK2019: 无法解析的外部符号 __imp__dup2，函数 "int __cdecl google::protobuf::internal::win32::dup2(int,int)" (?dup2@win32@internal@protobuf@google@@YAHHH@Z) 中引用了该符号
libprotobuf.lib(io_win32.cc.obj) : error LNK2019: 无法解析的外部符号 __imp_close，函数 "int __cdecl google::protobuf::internal::win32::close(int)" (?close@win32@internal@protobuf@google@@YAHH@Z) 中引用了该符号
OLDNAMES.lib(close.obi) : error LNK2001: 无法解析的外部符号 __imp_close
libprotobuf.lib(io_win32.cc.obj) : error LNK2019: 无法解析的外部符号 __imp__wstat64i32，函数 "int __cdecl google::protobuf::internal::win32::stat(char const *,struct _stat64i32 *)" (?stat@win32@internal@protobuf@google@@YAHPEBDPEAU_stat64i32@@@Z) 中引用了该符号
libprotobuf.lib(strutil.cc.obj) : error LNK2019: 无法解析的外部符号 __imp__isnan，函数 "char * __cdecl google::protobuf::DoubleToBuffer(double,char *)" (?DoubleToBuffer@protobuf@google@@YAPEADNPEAD@Z) 中引用了该符号
caffe2ncnn.exe : fatal error LNK1120: 9 个无法解析的外部命令
NMAKE : fatal error U1077: “E:\OPENCV\cmake\bin\cmake.exe”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.`

**Comment by z13228604287** [comment]
谢谢已解决
