### ISSUE TITLE
onnx2ncnn wrong with "Slice not supported yet!"

### ISSUE THREAD

**Issue by junedgar** [Tencent/ncnn#441]
when will the tool support to transfer Slice layer?

**Comment by nihui** [comment]
TODO
Slice should be converted to ncnn Crop layer

**Comment by kealennieh** [comment]
Any new information about slice ? Thanks~

**Comment by nihui** [comment]
I added the starts, ends, axes attributes to crop, please test
https://github.com/Tencent/ncnn/commit/a6c60068e69c1458f1ad3c707a74239e2ccbdeff
