### ISSUE TITLE
load model from memory is wrong 

### ISSUE THREAD

**Issue by XiaXuehai** [Tencent/ncnn#4410]
load the model like this:
```
std::vector<char> bin_data;
std::ifstream fbin("model_name.bin", std::ios::binary);
f_bin >> std::noskipws;
std::copy(std::istream_iterator<char>(f_bin), std::istream_iterator<char>(), std::back_inserter(bin_data));
net.load_model((const unsigned char *) bin_data.data())
```
the output is  right on ncnn-20200423, but it is wrong on ncnn-20221128.

and the result is right if the net loaded like like this:
```
FILE * fp= fopen ("test.txt", "rb" );
fseek(fp , 0 , SEEK_END);
long lsize = ftell(fp);
rewind(fp);
char *buffer = (char*) malloc (sizeof(char)*lsize);
fread(buffer, 1, lsize, fp);
net.load_model((const unsigned char *) buffer)
```
what is the difference?

**Comment by nihui** [comment]
Either ```std::vector<char> bin_data;``` or ```char *buffer``` buffer must not freed until the net instance destroyed.
This api is usually used with static model memory generated from ncnn2mem tool
https://github.com/Tencent/ncnn/blob/c5640a16c3f5ff38384419a3ac9712c6c5720810/src/net.h#L103

**Comment by XiaXuehai** [comment]
but the buffer memory is not freed until the net instance destroyed.
and I print the net weight loaded by `vector<char>`. They are no different than which loaded by file name.
and if vector reserve a large size, got `segmentation fault`

**Comment by nihui** [comment]
and the pointer must be aligned
https://github.com/Tencent/ncnn/blob/c5640a16c3f5ff38384419a3ac9712c6c5720810/src/net.h#L105

**Comment by XiaXuehai** [comment]
They are all 8-byte(64-bit) aligned

**Comment by XiaXuehai** [comment]
THX
