### ISSUE TITLE
本机(host) 支持avx512,AVX2指令，编译只支持AVX2的库给其他老旧的电脑运行？

### ISSUE THREAD

**Issue by zuowanbushiwo** [Tencent/ncnn#4413]
## detail | 详细描述 | 詳細な説明
1. 本机是比较新 windows x86 的机器，编译器和cpu硬件都支持比较新的指定比如AVX512 相关的
2. 现在想在这台电脑上编译只支持AVX2 或者SSE 指定的库 给旧电脑使用
3. cmake -DNCNN_RUNTIME_CPU=OFF  -DNCNN_AVX2=ON  ..  这个编译选项好像还是会在编译时打开avx512 编译优化

**Comment by Yoh-Z** [comment]
cmake -DNCNN_AVX512=OFF .. //关闭avx512

**Comment by Yoh-Z** [comment]
不过一般运行期会检查cpuid选择指令集进行执行，新电脑编的库旧电脑应该也是可以用的。

**Comment by zuowanbushiwo** [comment]
@Yoh-Z  
你好，感谢回复。
看cmakelist 文件， 如果在本机运行，下面这些宏应该是打开的
 https://github.com/Tencent/ncnn/blob/master/CMakeLists.txt#L365
那么 是不是也会被打开
https://github.com/Tencent/ncnn/blob/master/CMakeLists.txt#L441
谢谢！

**Comment by Yoh-Z** [comment]
第一个链接下面是判断编译器是否支持这些宏，第二个链接是如果编译器支持之后就会打开。
但是实际上编译出来含有机器不支持的宏之后，ncnn cpu.cpp里有get_cpu_support_x86_avx之类的函数，检查你的cpuid，来判断你运行时最终会执行到哪些指令集。（即便编译出了avx512的库，机器没有avx512，也不会执行到）

**Comment by zuowanbushiwo** [comment]
> 不过一般运行期会检查cpuid选择指令集进行执行，新电脑编的库旧电脑应该也是可以用的。

意思是，由于主机是新电脑，编译的时候优化指令能全开(SSE,AVX,AVX2,AVX512)。在旧电脑上会选择支持的指令优化 ，比如AVX2。

**Comment by zuowanbushiwo** [comment]
> 第一个链接下面是判断编译器是否支持这些宏，第二个链接是如果编译器支持之后就会打开。 但是实际上编译出来含有机器不支持的宏之后，ncnn cpu.cpp里有get_cpu_support_x86_avx之类的函数，检查你的cpuid，来判断你运行时最终会执行到哪些指令集。（即便编译出了avx512的库，机器没有avx512，也不会执行到）

感谢，你的意思是 ncnn 编译的时候会把一个函数的多个实现都编译进库里面吗？比如一个conv 函数 会有sse，avx2，avx512 都编译进lib吗？ 运行的时候选择。

**Comment by zuowanbushiwo** [comment]
因为我看有些开源库是编译的时候选择。比如指定AVX2的就只编译AVX2的函数。

**Comment by Yoh-Z** [comment]
> > 第一个链接下面是判断编译器是否支持这些宏，第二个链接是如果编译器支持之后就会打开。 但是实际上编译出来含有机器不支持的宏之后，ncnn cpu.cpp里有get_cpu_support_x86_avx之类的函数，检查你的cpuid，来判断你运行时最终会执行到哪些指令集。（即便编译出了avx512的库，机器没有avx512，也不会执行到）
> 
> 感谢，你的意思是 ncnn 编译的时候会把一个函数的多个实现都编译进库里面吗？比如一个conv 函数 会有sse，avx2，avx512 都编译进lib吗？ 运行的时候选择。

是这样

**Comment by zuowanbushiwo** [comment]
好的，感谢！
