### ISSUE TITLE
WINDOWS 10X64   Vulkan  NCNN  交叉编译提示确少模块

### ISSUE THREAD

**Issue by z13228604287** [Tencent/ncnn#4417]
这里 VulKan 通过Vulkan Cube.exe 已测试没问题
在CMake 3.24.2 UI 勾选 NCNN_VULKAN  出现如下错误！

`CMAKE_INSTALL_PREFIX = C:/Users/hanyo/Desktop/ncnn-master/BUILD64/install
NCNN_VERSION_STRING = 1.0.20221215
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
CMake Warning at CMakeLists.txt:455 (message):
  The compiler does not support avx512 bf16 extension.  NCNN_AVX512BF16 will
  be OFF.

CMake Warning at CMakeLists.txt:462 (message):
  The compiler does not support avx512 fp16 extension.  NCNN_AVX512FP16 will
  be OFF.

**Target arch: x86
CMake Error at CMakeLists.txt:535 (message):
  The submodules were not downloaded! Please update submodules with "git
  submodule update --init" and try again.**

Configuring incomplete, errors occurred!
See also "C:/Users/hanyo/Desktop/ncnn-master/BUILD64/CMakeFiles/CMakeOutput.log".
See also "C:/Users/hanyo/Desktop/ncnn-master/BUILD64/CMakeFiles/CMakeError.log".`

根据提示  git submodule update--init  
fatal: not a git repository (or any of the parent directories): .git

想 在百度  Google 找到解决方法  然而并没发现

**Comment by Yoh-Z** [comment]
回到ncnn文件夹下git submodule update--init，不要在build文件夹下。（有依赖库需要拉下来）
需要等一会，如果失败了手动去git clone一下glslang复制到文件夹里

**Comment by z13228604287** [comment]
@Yoh-Z 
我已经 测试返回 ncnn 再次执行
git submodule update--init
然而
fatal: not a git repository (or any of the parent directories): .git

手动如何  做  是否能给个下载链接

**Comment by Yoh-Z** [comment]
那你的ncnn应该不是git clone下来的。
拉下来这个项目 https://github.com/KhronosGroup/glslang/tree/88fd417b0bb7d91755961c70e846d274c182f2b0
并把里面的所有项目拷贝到ncnn的glslang文件夹下。

**Comment by wzyforgit** [comment]
> @Yoh-Z 我已经 测试返回 ncnn 再次执行 git submodule update--init 然而 fatal: not a git repository (or any of the parent directories): .git
> 
> 手动如何 做 是否能给个下载链接

你猜一下github的git是个啥

**Comment by z13228604287** [comment]
@Yoh-Z  又出现新的问题  找不到  Vulkan     我已添加了环境变量
`CMAKE_INSTALL_PREFIX = C:/Users/hanyo/Desktop/ncnn-master/BUILD64/install
NCNN_VERSION_STRING = 1.0.20221215
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
CMake Warning at CMakeLists.txt:455 (message):
  The compiler does not support avx512 bf16 extension.  NCNN_AVX512BF16 will
  be OFF.


CMake Warning at CMakeLists.txt:462 (message):
  The compiler does not support avx512 fp16 extension.  NCNN_AVX512FP16 will
  be OFF.


Target arch: x86
Using Debug VC++ CRT: MT
Using Release VC++ CRT: MT
Using MinSizeRel VC++ CRT: MT
Using RelWithDebInfo VC++ CRT: MT
Using release VC++ CRT: MT
=== CMAKE_SYSTEM_NAME is: Windows
CMake Error at E:/OPENCV/cmake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Vulkan (missing: Vulkan_LIBRARY Vulkan_INCLUDE_DIR) (found
  version "")
Call Stack (most recent call first):
  E:/OPENCV/cmake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  E:/OPENCV/cmake/share/cmake-3.24/Modules/FindVulkan.cmake:518 (find_package_handle_standard_args)
  src/CMakeLists.txt:273 (find_package)


Configuring incomplete, errors occurred!
See also "C:/Users/hanyo/Desktop/ncnn-master/BUILD64/CMakeFiles/CMakeOutput.log".
See also "C:/Users/hanyo/Desktop/ncnn-master/BUILD64/CMakeFiles/CMakeError.log".`

**Comment by Yoh-Z** [comment]
cmd里输入vkcube试试，没东西出来就是环境变量还没配好

**Comment by z13228604287** [comment]
@Yoh-Z   运行了Vulkan Cube

**Comment by Yoh-Z** [comment]
cmake命令是什么
而且应该不需要opencv，只有demo需要用opencv，只需要打开NCNN_VULKAN就可以

**Comment by z13228604287** [comment]
但是我并没有设置 Opencv
#
![QQ图片20221215162542](https://user-images.githubusercontent.com/72919575/207809950-3d8b54cd-b99a-4a9d-9016-3f7f0b1239cf.png)
