### ISSUE TITLE
can ncnn provide the ReLU6 layer optimization 

### ISSUE THREAD

**Issue by itemhsu** [Tencent/ncnn#442]
ReLU6 is the foundation of mobilenet v2 and ssdlite.  I saw there is only ReLU neon optimization but not found ReLU6. Do you have any plan for supporting the ReLU6 in the future?

**Comment by hiwudery** [comment]
Because there is no NEON instruction available to implement ReLU6, you have to do it in "c++".
the following is the c++ code provide by the authors of NCNN.
[https://github.com/Tencent/ncnn/wiki/%E6%B7%BB%E5%8A%A0%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B1%82%E5%AE%9E%E7%8E%B0](url)

**Comment by nihui** [comment]
ReLU6 shall be converted to Clip in ncnn, with min=0 max=6
optimization will be coming later
