### ISSUE TITLE
关于neon加速问题

### ISSUE THREAD

**Issue by litingsjj** [Tencent/ncnn#443]
你好，我在测基于mobilenetV2的模型时，发现测试速度非常缓慢，测试一次基本需要5s，我看过关于neon加速的issues，在编译时也加了TRUE，但是速度还是很一样很慢，我不确定是不是已经进行neon加速了，请问这点应该如何确定？谢谢！

**Comment by hiwudery** [comment]
Add "printf" in the NEON code, then you can check if the NEON code is executed or not.

**Comment by nihui** [comment]
As the above comments mentions, you can add some log to ensure that it does run on the neon code path.
