### ISSUE TITLE
error This file was generated by a newer version of protoc which is  

### ISSUE THREAD

**Issue by double-vane** [Tencent/ncnn#444]
编译tensorflow2ncnn时候，遇到这个问题
protoc --version是3.5.1版本的

![qq 20180619165928](https://user-images.githubusercontent.com/20334378/41587601-29ef4174-73e2-11e8-8150-50cca470c08e.jpg)

**Comment by hiwudery** [comment]
Your protoc version is different from your  "libprotobuf-dev". 
step 1: remove the "libprotobuf-dev".
step 2: download the protoc 3.5.1 source code, compile and install it on your linux system.
the problem will be solved.

**Comment by nihui** [comment]
purge your system protobuf installation completely and reinstall protobuf library
