### ISSUE TITLE
yolov4使用VULKAN预测出现全屏预测框，yolov5、yolov7则根本没有使用GPU进行加速预测，请问是哪里出了问题呢

### ISSUE THREAD

**Issue by YFforever2022** [Tencent/ncnn#4445]
![1](https://user-images.githubusercontent.com/111646263/209949551-c1bdac89-128b-4788-80f8-3877aaf00212.png)
![2](https://user-images.githubusercontent.com/111646263/209949748-17729e17-9ba6-46c0-a1be-10cc570ebabc.png)
window10 + vs2019 + ncnn-20221128 + protobuf-3.11.2 + VulkanSDK1.3.231.1
如果使用最新版的VulkanSDK1.3.236.0，那么，如果yolov4将use_vulkan_compute设为true会启动异常，false则可以正常预测结果

**Comment by wzyforgit** [comment]
看着像没开非极大抑制，什么27.3%的框都糊上去了

**Comment by YFforever2022** [comment]
我似乎发现了问题所在
从这里下载测试模型[https://github.com/nihui/ncnn-assets/tree/master/models](url)
使用examples文件夹里的yolov3、yolov4、yolov5、yolov7进行测试
opt.use_vulkan_compute = true
结果只有yolov4出现了以上的满屏幕框的情况
我怀疑是不是模型有问题
于是自己从这里下载了模型自行转换[https://github.com/AlexeyAB/darknet/releases/](url)
命令为：darknet2ncnn yolov4-tiny.cfg yolov4-tiny.weights yolov4-tiny.param yolov4-tiny.bin 1
结果就是正常的了！
![a](https://user-images.githubusercontent.com/111646263/210160149-58a5929e-0ad1-4edc-9ac4-8835f82c4e4b.jpg)
