### ISSUE TITLE
May I ask how to generate the ncnn static library that supports VULKEN for windows x86

### ISSUE THREAD

**Issue by YFforever2022** [Tencent/ncnn#4449]

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/releases/tag/20221128
prebuild package contains x86 library supporting vulkan

refer build steps
https://github.com/Tencent/ncnn/blob/b07c5fc811042025b5f3529c9f9d1ee40e5032e3/.github/workflows/release.yml#L1301

**Comment by YFforever2022** [comment]
> https://github.com/Tencent/ncnn/releases/tag/20221128 prebuild package contains x86 library supporting vulkan
> 
> refer build steps
> 
> https://github.com/Tencent/ncnn/blob/b07c5fc811042025b5f3529c9f9d1ee40e5032e3/.github/workflows/release.yml#L1301

Thank you for your reply! Using the precompiled package and the ncnn.lib compiled by me for Multi-threaded compilation always prompts Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MT_StaticRelease'. I have been trying for 2 days and there is no progress. But with Multi-threaded DLL everything works fine

**Comment by nihui** [comment]
> > https://github.com/Tencent/ncnn/releases/tag/20221128 prebuild package contains x86 library supporting vulkan
> > refer build steps
> > https://github.com/Tencent/ncnn/blob/b07c5fc811042025b5f3529c9f9d1ee40e5032e3/.github/workflows/release.yml#L1301
> 
> Thank you for your reply! Using the precompiled package and the ncnn.lib compiled by me for Multi-threaded compilation always prompts Mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' does not match value 'MT_StaticRelease'. I have been trying for 2 days and there is no progress. But with Multi-threaded DLL everything works fine

yeah, dynamic crt is compiled by default.
build with `-DNCNN_BUILD_WITH_STATIC_CRT=ON` yourself if static crt is preferred
