### ISSUE TITLE
PytorchConverter channel mismatch

### ISSUE THREAD

**Issue by jjjjohnson** [Tencent/ncnn#445]
各位大神：
Pytorch 模型的 inputShape 是 [1, channel, height, width], 而OpenCV 读取的图片是[height, width，channel]. 请问是否需要人为转换channel 还是ncnn会自动帮我转换完成。 如果需要，在C++里面如何实现？

谢谢
Junjie

**Comment by hiwudery** [comment]
只需要将opencv读入的图片资料做转换[height, width，channel]-->[1, channel, height, width],就不需要人为转换pytorch channel.

**Comment by jjjjohnson** [comment]
测试了 只需将[height, width，channel]的 BGR 的图片传入即可不需要转换成[1, channel, height, width]
`ncnn::Mat in = ncnn::Mat::from_pixels(bgr.data, ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows);`

**Comment by lesleelichong** [comment]
pytorch模型的mobilenetv2+ssd如何转换成ncnn的？
