### ISSUE TITLE
image的char*强转uchar*传给from_pixels_resize会崩溃

### ISSUE THREAD

**Issue by YFforever2022** [Tencent/ncnn#4452]
`    char* img = new char[img_sjcd];
    img[img_sjcd] = '\0';
    memcpy(img, img_zz, img_sjcd);

    //std::vector<uchar> data;
    //for (int i = 0; i < img_sjcd; ++i) {
    //    data.push_back(img[i]);
    //}

    //cv::Mat pic = cv::imdecode(data, cv::IMREAD_UNCHANGED);

    ncnn::Mat in = ncnn::Mat::from_pixels_resize((uchar*)img, ncnn::Mat::PIXEL_RGB, img_w, img_h, target_w, target_h);`

如果使用OpenCV转换，再传入pic.data则一切正常，请问有什么方法可以直接将上述代码的img直接传给from_pixels_resize转换

**Comment by YFforever2022** [comment]
尝试使用fopen将img写出到文件，可正常显示图片jpg，假如char*可绕过OpenCV转换，那么运行耗时可大幅缩短

**Comment by YFforever2022** [comment]
尝试所有PIXEL类型都不行

**Comment by YFforever2022** [comment]
搜索整个ncnn源代码项目from_pixels_resize
来了mat_pixel.cpp第2541行，进去
跳到2557行
查看第2567行，进去
来到mat_pixel_resize.cpp第610行
可以看见参数一为const unsigned char* src
表示看不懂大佬的代码，厉害
第一次开始引用src的地方为710行
// hresize one row
            short* rows0_old = rows0;
            rows0 = rows1;
            rows1 = rows0_old;
            const unsigned char* S1 = src + srcstride * (sy + 1);

第二次引用src的地方为753行
// hresize two rows
            const unsigned char* S0 = src + srcstride * (sy);
            const unsigned char* S1 = src + srcstride * (sy + 1);

**Comment by YFforever2022** [comment]
明白我传入的是3通道的RGB图片，所以看到mat_pixel.cpp第2541行
return Mat::from_pixels_resize(pixels, type, w, h, w * 3, target_width, target_height, allocator);
第五个参数stride为宽度×3，有可能这个就是说的三通道
跳到函数处
依然看PIXEL_RGB分支，来到2564行
 if (type_from == PIXEL_RGB || type_from == PIXEL_BGR)
    {
        Mat dst(target_width, target_height, (size_t)3u, 3);
        resize_bilinear_c3(pixels, w, h, stride, dst, target_width, target_height, target_width * 3);

        return Mat::from_pixels(dst, type, target_width, target_height, allocator);
    }

我感觉是创建了一个dst空间
然后做了调整并把值写到了dst里
最后再使用dst做另一个调整
结果作为Mat::from_pixels的返回值返回传出

**Comment by YFforever2022** [comment]
到此还是不知道具体为何，看到mat_pixel.cpp第2559行
if (w == target_width && h == target_height)
        return Mat::from_pixels(pixels, type, w, h, stride, allocator);
看到这么个条件，可以直接返回，直接少了resize_bilinear_c3这一步的调整
那么我可以利用这个特性来传值，让它减少运行步骤，测试是否依然错误，来判断引发错误的地方

**Comment by YFforever2022** [comment]
使用ncnn::Mat in = ncnn::Mat::from_pixels_resize((uchar*)img, ncnn::Mat::PIXEL_RGB, 810, 1080, 810, 1080);
结果依然崩溃
说明只运行一步return Mat::from_pixels(pixels, type, w, h, stride, allocator);也错误，原因就是提供了不对应的参数
跟进去看一下这个函数在干吗
来到mat_pixel.cpp第2462行
看见判断，根据我提供的PIXEL_RGB，会跳转到第2523行
from_rgb(pixels, w, h, stride, m, allocator);
这里看见有个m，开头的地方有一句叫Mat m;
结尾是return m;
说明这里就是最终返回的Mat
跟进函数from_rgb，来到mat_pixel.cpp第27行

**Comment by YFforever2022** [comment]
可是我的char*只是一段二进制数据，并不是char数组，uchar*为什么是数组，涉及到基础类型概念，需要查阅一下理解一下先

**Comment by YFforever2022** [comment]
创建指针
    float* ptr0 = m.channel(0);
    float* ptr1 = m.channel(1);
    float* ptr2 = m.channel(2);
指向了Mat m
        for (; remain > 0; remain--)
        {
            *ptr0 = rgb[0];
            *ptr1 = rgb[1];
            *ptr2 = rgb[2];

            rgb += 3;
            ptr0++;
            ptr1++;
            ptr2++;
        }
通过循环来修改指针内容
实际上就是在修改Mat m的内容
最后返回
问题就在于传入的unsigned char* rgb
似乎有一种说法叫做 char* A ，当用A[0]表示时，实际上为指针A地址的偏移量
继续查阅相关资料，当了解完为什么有rgb[0]、rgb[1]、rgb[2]时，相信问题自然解决

**Comment by YFforever2022** [comment]
再来一下这部分代码怎么走的，因为还没到resize就会引发崩溃，先看前一部分像素转换
Mat Mat::from_pixels(const unsigned char* pixels, int type, int w, int h, Allocator* allocator)
{
    int type_from = type & PIXEL_FORMAT_MASK;

    if (type_from == PIXEL_RGB || type_from == PIXEL_BGR)
    {
        return Mat::from_pixels(pixels, type, w, h, w * 3, allocator);
    }
    else if (type_from == PIXEL_GRAY)
    {
        return Mat::from_pixels(pixels, type, w, h, w * 1, allocator);
    }
    else if (type_from == PIXEL_RGBA || type_from == PIXEL_BGRA)
    {
        return Mat::from_pixels(pixels, type, w, h, w * 4, allocator);
    }

    // unknown convert type
    NCNN_LOGE("unknown convert type %d", type);
    return Mat();
}

传的ncnn::Mat::PIXEL_BGR2RGB = 65538
PIXEL_FORMAT_MASK = 65535
int type_from = type & PIXEL_FORMAT_MASK;
所以type_from = 2
而PIXEL_BGR正好等于2，走第一个分支
if (type_from == PIXEL_RGB || type_from == PIXEL_BGR)
    {
        return Mat::from_pixels(pixels, type, w, h, w * 3, allocator);  //type = ncnn::Mat::PIXEL_BGR2RGB = 65538
    }

来到2462行，mat_pixel.cpp
PIXEL_CONVERT_MASK = -65536
传的ncnn::Mat::PIXEL_BGR2RGB = 65538
与运算结果0，为FALSE，所以走else部分

Mat Mat::from_pixels(const unsigned char* pixels, int type, int w, int h, int stride, Allocator* allocator)
{
    Mat m;

    if (type & PIXEL_CONVERT_MASK)
    {
        switch (type)
        {
        case PIXEL_RGB2BGR:
        case PIXEL_BGR2RGB:
            from_rgb2bgr(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_RGB2GRAY:
            from_rgb2gray(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_RGB2RGBA:
        case PIXEL_BGR2BGRA:
            from_rgb2rgba(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_BGR2GRAY:
            from_bgr2gray(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_BGR2RGBA:
        case PIXEL_RGB2BGRA:
            from_bgr2rgba(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_GRAY2RGB:
        case PIXEL_GRAY2BGR:
            from_gray2rgb(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_GRAY2RGBA:
        case PIXEL_GRAY2BGRA:
            from_gray2rgba(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_RGBA2RGB:
        case PIXEL_BGRA2BGR:
            from_rgba2rgb(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_RGBA2BGR:
        case PIXEL_BGRA2RGB:
            from_rgba2bgr(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_RGBA2GRAY:
            from_rgba2gray(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_RGBA2BGRA:
        case PIXEL_BGRA2RGBA:
            from_rgba2bgra(pixels, w, h, stride, m, allocator);
            break;
        case PIXEL_BGRA2GRAY:
            from_bgra2gray(pixels, w, h, stride, m, allocator);
            break;
        default:
            // unimplemented convert type
            NCNN_LOGE("unimplemented convert type %d", type);
            break;
        }
    }
    else
    {
        if (type == PIXEL_RGB || type == PIXEL_BGR)
            from_rgb(pixels, w, h, stride, m, allocator);

        if (type == PIXEL_GRAY)
            from_gray(pixels, w, h, stride, m, allocator);

        if (type == PIXEL_RGBA || type == PIXEL_BGRA)
            from_rgba(pixels, w, h, stride, m, allocator);
    }

    return m;
}

根据条件来看，没有一个分支符合，返回了个寂寞…
        PIXEL_RGB = 1,
        PIXEL_BGR = 2,
        PIXEL_GRAY = 3,
        PIXEL_RGBA = 4,
        PIXEL_BGRA = 5,

**Comment by YFforever2022** [comment]
修改传入type为ncnn::Mat::PIXEL_RGB = 1
结果1，依然走第一个分支
    if (type_from == PIXEL_RGB || type_from == PIXEL_BGR)
    {
        return Mat::from_pixels(pixels, type, w, h, w * 3, allocator);
    }

来到2462行，mat_pixel.cpp
传入type为ncnn::Mat::PIXEL_RGB = 1
PIXEL_CONVERT_MASK = -65536
与运算结果0，为FALSE，所以走else部分
PIXEL_RGB = 1,
PIXEL_BGR = 2,
PIXEL_GRAY = 3,
PIXEL_RGBA = 4,
PIXEL_BGRA = 5,
else
{
    if (type == PIXEL_RGB || type == PIXEL_BGR)
        from_rgb(pixels, w, h, stride, m, allocator);

    if (type == PIXEL_GRAY)
        from_gray(pixels, w, h, stride, m, allocator);

    if (type == PIXEL_RGBA || type == PIXEL_BGRA)
        from_rgba(pixels, w, h, stride, m, allocator);
}
走第一个分支
if (type == PIXEL_RGB || type == PIXEL_BGR)
        from_rgb(pixels, w, h, stride, m, allocator);
return m;

来到了27行
static int from_rgb(const unsigned char* rgb, int w, int h, int stride, Mat& m, Allocator* allocator)
{
    m.create(w, h, 3, 4u, allocator);
    if (m.empty())
        return -100;

    const int wgap = stride - w * 3;
    if (wgap == 0)
    {
        w = w * h;
        h = 1;
    }

    float* ptr0 = m.channel(0);
    float* ptr1 = m.channel(1);
    float* ptr2 = m.channel(2);

    for (int y = 0; y < h; y++)
    {
#if __ARM_NEON
        int nn = w >> 3;
        int remain = w - (nn << 3);
#else
        int remain = w;
#endif // __ARM_NEON

#if __ARM_NEON
#if __aarch64__
        for (; nn > 0; nn--)
        {
            uint8x8x3_t _rgb = vld3_u8(rgb);
            uint16x8_t _r16 = vmovl_u8(_rgb.val[0]);
            uint16x8_t _g16 = vmovl_u8(_rgb.val[1]);
            uint16x8_t _b16 = vmovl_u8(_rgb.val[2]);

            float32x4_t _rlow = vcvtq_f32_u32(vmovl_u16(vget_low_u16(_r16)));
            float32x4_t _rhigh = vcvtq_f32_u32(vmovl_u16(vget_high_u16(_r16)));
            float32x4_t _glow = vcvtq_f32_u32(vmovl_u16(vget_low_u16(_g16)));
            float32x4_t _ghigh = vcvtq_f32_u32(vmovl_u16(vget_high_u16(_g16)));
            float32x4_t _blow = vcvtq_f32_u32(vmovl_u16(vget_low_u16(_b16)));
            float32x4_t _bhigh = vcvtq_f32_u32(vmovl_u16(vget_high_u16(_b16)));

            vst1q_f32(ptr0, _rlow);
            vst1q_f32(ptr0 + 4, _rhigh);
            vst1q_f32(ptr1, _glow);
            vst1q_f32(ptr1 + 4, _ghigh);
            vst1q_f32(ptr2, _blow);
            vst1q_f32(ptr2 + 4, _bhigh);

            rgb += 3 * 8;
            ptr0 += 8;
            ptr1 += 8;
            ptr2 += 8;
        }
#else
        if (nn > 0)
        {
            asm volatile(
                "0:                             \n"
                "pld        [%1, #256]          \n"
                "vld3.u8    {d0-d2}, [%1]!      \n"
                "vmovl.u8   q8, d0              \n"
                "vmovl.u8   q9, d1              \n"
                "vmovl.u8   q10, d2             \n"
                "vmovl.u16  q0, d16             \n"
                "vmovl.u16  q1, d17             \n"
                "vmovl.u16  q2, d18             \n"
                "vmovl.u16  q3, d19             \n"
                "vmovl.u16  q8, d20             \n"
                "vmovl.u16  q9, d21             \n"
                "vcvt.f32.u32   q0, q0          \n"
                "vcvt.f32.u32   q1, q1          \n"
                "vcvt.f32.u32   q2, q2          \n"
                "vcvt.f32.u32   q3, q3          \n"
                "vcvt.f32.u32   q8, q8          \n"
                "subs       %0, #1              \n"
                "vst1.f32   {d0-d3}, [%2]!      \n"
                "vcvt.f32.u32   q9, q9          \n"
                "vst1.f32   {d4-d7}, [%3]!      \n"
                "vst1.f32   {d16-d19}, [%4]!    \n"
                "bne        0b                  \n"
                : "=r"(nn),   // %0
                "=r"(rgb),  // %1
                "=r"(ptr0), // %2
                "=r"(ptr1), // %3
                "=r"(ptr2)  // %4
                : "0"(nn),
                "1"(rgb),
                "2"(ptr0),
                "3"(ptr1),
                "4"(ptr2)
                : "cc", "memory", "q0", "q1", "q2", "q3", "q8", "q9", "q10");
        }
#endif // __aarch64__
#endif // __ARM_NEON
        for (; remain > 0; remain--)
        {
            *ptr0 = rgb[0];
            *ptr1 = rgb[1];
            *ptr2 = rgb[2];

            rgb += 3;
            ptr0++;
            ptr1++;
            ptr2++;
        }

        rgb += wgap;
    }

    return 0;
}

**Comment by YFforever2022** [comment]
再次看见从unsigned char数组里取内容填充到m里的通道，这里看见0、1、2，加上RGB，理解为三通道，没有成功只能说明我提供的rgb参数没有对应的排序方式，所以程序取不到要的东西，自然无法成功，暂时将问题锁定到没有内存对齐

**Comment by YFforever2022** [comment]
搜索了一下Mat中的data是什么，解释为：  
uchar类型的指针，指向Mat数据矩阵的首地址。也就是是data指针里的数据内容已经就是Mat格式了，所以必须将我的二进制数据转换为Mat才可以，所以此题无解

**Comment by nihui** [comment]
from_pixels 接受的是 RGB RGBA GRAY 这样的 pixel uchar，不是 jpg 编码的数据，jpg 必须先解码为 pixel 才能传入
