### ISSUE TITLE
模型的输入是二维[batch_size, dim]数据，但batch_size的值可变

### ISSUE THREAD

**Issue by fivenick** [Tencent/ncnn#4459]
## detail | 详细描述 | 詳細な説明

将pytorch的resnet模型到出为onnx，导出时需要指定一个输入，因为batch_size是可变的，所以我随便指定了一个维度的输入[100,81]。之后将该onnx模型转换成ncnn的模型，加载ncnn模型时，发现只能输入维度为[100,81]的数据，但100是batch_size的值，是可变值，每次输入不一定一样（我是做语音的，所以数据维度不固定），这个问题该怎么解决呢？谢谢~

**Comment by csukuangfj** [comment]
> ## detail | 详细描述 | 詳細な説明
> 
> 
> 
> 将pytorch的resnet模型到出为onnx，导出时需要指定一个输入，因为batch_size是可变的，所以我随便指定了一个维度的输入[100,81]。之后将该onnx模型转换成ncnn的模型，加载ncnn模型时，发现只能输入维度为[100,81]的数据，但100是batch_size的值，是可变值，每次输入不一定一样（我是做语音的，所以数据维度不固定），这个问题该怎么解决呢？谢谢~

好不容易碰到一个做语音的同行。

可以参考下

https://github.com/k2-fsa/sherpa-ncnn

用了ncnn做实时语音识别

**Comment by fivenick** [comment]
问题已经解决，onnx有可变输入参数维度模型，只要将pytorch转成灵活输入维度的onnx即可

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
