### ISSUE TITLE
how to use ncnn with multi-input and multi-output model

### ISSUE THREAD

**Issue by bobby-chiu** [Tencent/ncnn#446]
could you give some examples for multi-input/output model with ncnn?

**Comment by bobby-chiu** [comment]
hi, for this case, is there a general approach for different models to obtain the multi-input blob index and out ones when doing caffe2ncnn?

**Comment by bobby-chiu** [comment]
Any ideas ?

**Comment by bobby-chiu** [comment]
@nihui, did i make the issue clearly?

**Comment by nihui** [comment]
the model itself do not contains any blob info about inputs and outputs, so you have to provide them.
it is usually not real problem since you could parameterize these names instead of hardcode them.

**Comment by bobby-chiu** [comment]
@nihui, thank you for you reply. I have considered this for several days. One way maybe i can search all the layers of model network, and then extract the top/bottom layers if any one has no bottom or top layer connected. So as you given, what is your meaning of "parameterize these names" ? thanks.

**Comment by nihui** [comment]
for simple model as image classification, it is possible to search the leaf node and regard these nodes as input/output. while it is not always be the truth in real usecase, that you may encounter multiple leaves including some useless nodes.
