### ISSUE TITLE
请问一下关于Crop层的参数

### ISSUE THREAD

**Issue by XdpAreKid** [Tencent/ncnn#4467]
## detail | 详细描述 | 詳細な説明
请问我有这么一个crop层
Crop                     Slice_119                1 1 onnx::Slice_264_splitncnn_4 onnx::Slice_269 -23309=1,0 -23310=1,320 -23311=1,1
我想输入任意尺寸的话，这个参数应该怎么改呢？？参数里的那个320是我的默认输入尺寸640的一半，就是我想动态输入，然后每次都是int(w/2)

**Comment by nihui** [comment]
crop不适合这种动态的，可以用 slice 替代，设置 axis，两个输出，正好是切一半大小

**Comment by XdpAreKid** [comment]
感谢大大的解答，已经搞定了

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
