### ISSUE TITLE
ncnn::Net net --> global variable doesn't work local variable works

### ISSUE THREAD

**Issue by gedance** [Tencent/ncnn#4468]
## detail | 详细描述 | 詳細な説明

Hello,

I have C++ API using ncnn with yolox model that works fine in windows.
But Linux, it's behaving little weird.

There is a "Global variable on the top of class file ===>  ncnn::Net yoloxnet; 
(reason why using the global variable is that the yoloxnet variable is being used from several functions)

ISSUE=> yoloxnet can't not load model
               It returns the message "Floating point exception" when 'load_model' is called

However, when I do the exact same thing with Local variable (ncnn::Net yoloxnet inside a function), it loads the model fine.

I am totally lost, why this is happening on Linux only..

Can anyone help me figure out this issue?

Thank you!

**Comment by gedance** [comment]
This is very weird... someone might know why

Can anyone please try as following and see if you get the "Floating Point Exception"?

example code:  https://github.com/Tencent/ncnn/blob/master/examples/yolox.cpp
comment out line number 255  ===>     ncnn::Net yolox; (local variable)
                      to the top line 33 ===>     ncnn::Net yolox; (global variable)

if you get the same exception, do you have any idea why it's throwing the "Floating point exception"?

Thank you.

**Comment by Bocity** [comment]
I get the same exception，I dont know why

**Comment by Bocity** [comment]
hi, my solution is using local var, and shared by pointer

**Comment by hongson23** [comment]
hi, i have the same issue

**Comment by nihui** [comment]
shall be fixed with https://github.com/Tencent/ncnn/pull/4725

**Comment by nihui** [comment]
fell free to reopen issue if it still resists
