### ISSUE TITLE
转换不了slice 切片

### ISSUE THREAD

**Issue by ouleiwa** [Tencent/ncnn#4480]
## error log | 日志或报错信息 | ログ
代码中的6:9的切片无法转换。 还有就是Crop的参数，09，10，11和 对应的start,end,axis怎么对应上啊，为什么这三个参数的第一个都是1
## how to reproduce | 复现步骤 | 再現方法
1.class test_onnx(nn.Module):
    def __init__(self):
        super(test_onnx, self).__init__()

    def forward(self, x:torch.Tensor):
        x = x+1
        x = x[2,6:9,8]
        x = x + 1
        return x
2.ncnn_model = test_onnx()
   x = torch.ones([10, 10, 10])
   z = ncnn_model(x)
3.
7767517
6 6
Input            input1                   0 1 input1
BinaryOp         Add_1                    1 1 input1 onnx::Gather_2 0=0 1=1 2=1.000000e+00
Crop             Gather_3                 1 1 onnx::Gather_2 onnx::Slice_4 -23309=1,2 -23310=1,3 -23311=1,-1
Crop             Slice_8                  1 1 onnx::Slice_4 onnx::Gather_9 -23309=0 -23310=0
Crop             Gather_10                1 1 onnx::Gather_9 onnx::Add_11 -23309=1,8 -23310=1,9 -23311=1,0
BinaryOp         Add_12                   1 1 onnx::Add_11 output 0=0 1=1 2=1.000000e+00

**Comment by ouleiwa** [comment]
> 你试试 2-d 的 tensor?

也是一样的，切片都是不行。

**Comment by ouleiwa** [comment]
如果我把x = x[2,6:9,8]改成x = x[2,6,8]，导出的param的crop的参数11 axis是不是也有问题啊？为什么都是1，-1
class test_onnx(nn.Module):
    def __init__(self):
        super(test_onnx, self).__init__()

    def forward(self, x:torch.Tensor):
        x = x+1
        x = x[2,6,8]
        x = x + 1
        return x

param file
7767517
6 6
Input            input1                   0 1 input1
BinaryOp         Add_1                    1 1 input1 onnx::Gather_2 0=0 1=1 2=1.000000e+00
Crop             Gather_3                 1 1 onnx::Gather_2 onnx::Gather_4 -23309=1,2 -23310=1,3 -23311=1,-1
Crop             Gather_5                 1 1 onnx::Gather_4 onnx::Gather_6 -23309=1,6 -23310=1,7 -23311=1,-1
Crop             Gather_7                 1 1 onnx::Gather_6 onnx::Add_8 -23309=1,8 -23310=1,9 -23311=1,-1
BinaryOp         Add_9                    1 1 onnx::Add_8 output 0=0 1=1 2=1.000000e+00

**Comment by ouleiwa** [comment]
> > 如果我把x = x[2,6:9,8]改成x = x[2,6,8]
> 
> 你这个还是 3-d 的 tensor 呀

2-d的我也试过了，也是不行。

class test_onnx(nn.Module):
    def __init__(self):
        super(test_onnx, self).__init__()

    def forward(self, x:torch.Tensor):
        x = x+1
        x = x[2,6:8]
        x = x + 1
        return x

        ncnn_model = test_onnx()
        x = torch.ones([10, 10])
        z = ncnn_model(x)
        
7767517
5 5
Input            input1                   0 1 input1
BinaryOp         Add_1                    1 1 input1 onnx::Gather_2 0=0 1=1 2=1.000000e+00
Crop             Gather_3                 1 1 onnx::Gather_2 onnx::Slice_4 -23309=1,2 -23310=1,3 -23311=1,-1
Crop             Slice_8                  1 1 onnx::Slice_4 onnx::Add_9 -23309=0 -23310=0
BinaryOp         Add_10                   1 1 onnx::Add_9 output 0=0 1=1 2=1.000000e+00

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4522

**Comment by nihui** [comment]
implemented in https://github.com/Tencent/ncnn/commit/fc6ce4a641521bd70c0e51ace4b3a8e1a8190eca
配合pnnx模型转换

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by csukuangfj** [comment]
太棒啦！
