### ISSUE TITLE
How does the darknet version of yolov7 use ncnn for reasoning

### ISSUE THREAD

**Issue by YFforever2022** [Tencent/ncnn#4483]
### source
https://github.com/AlexeyAB/darknet/releases/tag/yolov4
https://github.com/AlexeyAB/darknet/releases/download/yolov4/yolov7-tiny.weights
https://github.com/AlexeyAB/darknet/releases/download/yolov4/yolov7-tiny.conv.87
https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov7-tiny.cfg
### result
Convert to bin model, then use yolov4.cpp for inference, the result is wrong

**Comment by sxj731533730** [comment]
请叙述具体错误原因，按照格式规范提问
