### ISSUE TITLE
Building on alpinelinux 

### ISSUE THREAD

**Issue by ridams** [Tencent/ncnn#4484]
how can one build ncnn on alpinelinux that uses musl libc; error _SC_LEVEL3_CACHE_SIZE was not declared in this scope

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4499

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/17197b3c4598004fb2cf9587826de183e6f51fdb
btw, alpinelinux ci added  :D
