### ISSUE TITLE
YOLOV7推理单类别模型，结果出错，很多置信度很高的误检

### ISSUE THREAD

**Issue by wyjj** [Tencent/ncnn#4490]
## detail | 详细描述 | 詳細な説明
yolov7_tiny训练了一个类别的模型，pt推理结果正常，转为ncnn推理时，结果有很多置信度很高（1或者0.99）的误检，这个怎么解决？

**Comment by sxj731533730** [comment]
参考　https://sxj731533730.blog.csdn.net/article/details/128330266?spm=1001.2014.3001.5502

**Comment by wyjj** [comment]
感谢！
