### ISSUE TITLE
关于低精度矩阵乘法的问题

### ISSUE THREAD

**Issue by ccJia** [Tencent/ncnn#45]
@nihui  你好，请问NCNN这种对于 FLOAT 数据进行量化的过程，是否有考虑过后续如果使用这种量化方式的参数进行矩阵乘法（Fix_Point）的溢出问题呢？

**Comment by nihui** [comment]
量化只是减小模型存储，实际运算是用 float

**Comment by ccJia** [comment]
OK，谢谢了，我以为会在这个基础上开发 类似于 INT8 的矩阵乘法。
