### ISSUE TITLE
RK3399上无法复现benchmark结果

### ISSUE THREAD

**Issue by meloncolie** [Tencent/ncnn#451]
@nihui 请问如何能复现RK3399的benchmark结果
1. 虽然是ubuntu16.04系统，但是已经参考[#28](https://github.com/Tencent/ncnn/issues/28)开启了neon优化，并且在确认了*_arm.cpp文件已经编译，#ifdef __ARM_NEON段代码会执行
2. 通过 ```shell sudo cpufreq-set -c [cpu-id] -g performance ```将所有cpu设置为performance模式（性能优先、频率最高）
但是我的benchmark结果如下
![image](https://user-images.githubusercontent.com/36785374/41812171-a0bde046-7750-11e8-823b-bd3b92ee1e99.png)
其中由于小核的瓶颈，导致6线程会明显慢于2线程；并且即使在2线程下依然比[README.md](https://github.com/Tencent/ncnn/blob/master/benchmark/README.md)中的benchmark结果慢，所以想请教两点问题：
1. 如何能够复现benchmark结果
2. 为何benchmark在6线程的情况下运行，而不是在2线程情况下

**Comment by zzuxzt** [comment]
你好，请问是如何在rk3399的ubuntu系统下开启neon加速的，#28没咋看明白，在src/CMakeLists.txt的37行已经有OR (UNIX AND ("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "armv7l"))
 OR (UNIX AND ("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "aarch64"))，应该就不需要添加了吧，然后直接cmake ..？这样做好像还是没有开启neon加速，benchmark里的squeeznet 平均180ms

**Comment by zzuxzt** [comment]
![screenshot from 2018-06-26 09-34-15](https://user-images.githubusercontent.com/19167549/41884050-1fad81ca-7924-11e8-92ad-5d52bdfc062d.png)
这是我RK3399 ubuntu系统，src/CMakeLists.txt的37行直接true之后的跑的，6线程还是慢了一倍，而2线程却和benchmark基本一样了，不知道什么原因？

**Comment by meloncolie** [comment]
@zzuxzt 你上传的图片好像挂掉了，我电脑看不到。另外请问你的cmake的时候还有加什么编译选项吗？还是直接cmake ..?

**Comment by zzuxzt** [comment]
我是在rk3399的ubuntu系统上进行编译的，并没有在PC端进行交叉编译，在rk3399上编译是直接cmake ..就好，不需要其他编译选项，再次附图
![screenshot from 2018-06-26 09-34-15](https://user-images.githubusercontent.com/19167549/41963624-9eadbaf6-7a2a-11e8-89d1-20602977cfc6.png)

**Comment by meloncolie** [comment]
找到原因了，之前用的是最新的tag编译的，发布时间是4.27，跟最新的master分支速度差距还是不小。
另外linux上arm编译的话src/cpu.cpp里面需要把gittid()重新实现下。

**Comment by lovehuanhuan** [comment]
// set affinity for thread
    pid_t pid = gettid();
这里？
3399上A72好像是后面两个核  前面四个是a53
这里怎么修改 ？

**Comment by lovehuanhuan** [comment]
这个函数 syscall(__NR_sched_setaffinity,  只在android下有效
这么说你的3399跑的是安卓系统

**Comment by meloncolie** [comment]
@lovehuanhuan 我是在ubuntu 16.04下面跑的。不过gettid()编译的时候说undefined，我就改成了#define gettid() syscall(SYS_gettid)

**Comment by bluelml** [comment]
@lovehuanhuan gettid()是在 “__ANDROID__”宏里面， 需要把这个宏打开。
"syscall(__NR_sched_setaffinity"  是Linux内核的，应该都可以用。 

但是我测试下来，6核时，还是比2核慢。不确定是不是小核拖慢了大核？ 如果在Android下面性能 6核>2核，那就是cpu.cpp有问题，对Linux支持不友好。

**Comment by meloncolie** [comment]
@bluelml 嗯，在linux上确实是6核比2核慢，因为6核时大小核都被开启运行openmp，小核就成了瓶颈。不知道android上到底是什么情况

**Comment by shuxiao9058** [comment]
有人测试过安卓下的情况吗？安卓下会不会好些？

**Comment by Victoth** [comment]
android系统也是同样的现象，6核比2核慢

**Comment by xiangdeyizhang** [comment]
@meloncolie  你好，请问你最后设置bianyi选项的呢？

**Comment by meloncolie** [comment]
@xiangdeyizhang 就是用的8 6 0

**Comment by nihui** [comment]
更新到最新 ncnn 代码会更快
rk3399有大小核区分，运行 benchncnn 时建议用 benchncnn 4 2 2 来绑定大核心测试
