### ISSUE TITLE
PNNX 如何支持多个input输入？

### ISSUE THREAD

**Issue by zcy618** [Tencent/ncnn#4510]
## detail | 详细描述 | 詳細な説明
我们现在有10个输入，我试图按照我对代码的理解，在PNNX的main.cpp中进行input的添加，但是发现更深层的代码也都需要进行相应的修改，比如在shape_inference.cpp中有诸如下面的判断：
for (size_t i = 0; i < sizes1.size(); i++)
              {
                  if (sizes1[i] == sizes2[i])
                      continue;

                  sizes1[i] = c10::ShapeSymbol::fromStaticSize(-1);
              }
那有更多输入的时候，这部分应该如何修改呢？
我们是刚开始接触PNNX，对代码的理解并不深，我们同时更担心这些修改是否会引入更多的问题？
所以我们是否会考虑更智能的方案在输入这块的一个自动判断？或者可以输入input的number，再输入相应的input shape，也是可以的，尽量减少PNNX代码内部的修改，对用户也更友好。
Thanks.

**Comment by nihui** [comment]
用逗号割开多个输入

```
./pnnx model.pt inputshape=[1,3,224,224],[1,1,224,224]
```

指定类型是这样
```
./pnnx model.pt inputshape=[1,3,224,224]f32,[1,1,224,224]f32
```
