### ISSUE TITLE
一个blob有多个consumer的情况该如何处理？

### ISSUE THREAD

**Issue by 111qqz** [Tencent/ncnn#4512]
## detail | 详细描述 | 詳細な説明
比如如下结构的网络
![image](https://user-images.githubusercontent.com/30498101/216814233-a2f5c40e-4058-4708-a9e7-14996e816b2d.png)

input blob "fp16/input_layer"会有两个分支，也就是两个consumer

我看到在[PR2493](https://github.com/Tencent/ncnn/pull/2493)中，将blob的consumer改为只支持一个了。

那么请问现在要怎么处理这种情况？

**Comment by csukuangfj** [comment]
你加个Split layer试试

**Comment by 111qqz** [comment]
在开头加了split layer,变成了如下:

```shell
7767517
9 10        
Input                    fp16/input_layer              0 1 fp16/input_layer -23330=4,1,150,1,1 0=150
Split                    fp16/split                    1 2 fp16/input_layer input1 input2

```

已经可以了，谢谢！
