### ISSUE TITLE
如何加速多个“输入相同，结构相同，权重不同”的模型的推理？

### ISSUE THREAD

**Issue by 111qqz** [Tencent/ncnn#4514]
## detail | 详细描述 | 詳細な説明
![image](https://user-images.githubusercontent.com/30498101/216865538-47ace3cc-e9f4-44fd-8e86-0625ff986afc.png)

如图，如果单个模型batch_size=1的情况下的推理速度为T, 那么顺序推理两个模型的时间基本是2*T
尝试过将这两个模型合并到一个(param,bin)，编译ncnn时设置了 -DNCNN_OPENMP=ON
然后设置了 ncnn::Extractor的 set_num_threads为2，代码如下:

```c++

 for (int i = 0; i < 1000; i++) {
    ncnn::Extractor ex = net.create_extractor();
    // this will overwrite global settings
    ex.set_num_threads(2);
    ex.input(input_name, in);
    ex.input(input_name2, in2);
    ex.extract(output_name, out);
    ex.extract(output_name2, out2);
    // ex.extract(output_name2,out);
  }
```

**期望是每个thread会分别去执行一个模型**, 得到的推理耗时小于2*T
但是实际测试发现，耗时仍然是2*T左右，没有明显变化

所以想请教一下:
1.  上述设置得到的仍然为2*T的耗时是否符合预期？
2. 有什么其他手段？
谢谢！

**Comment by csukuangfj** [comment]
你增加线程数量试试

**Comment by csukuangfj** [comment]
还有一个，因为这两个模型是是独立的，你可以自己创建两个线程，每个线程处理一个模型。

**Comment by nihui** [comment]
可以 ncnnmerge 合并成一个模型，然后 input input extract extract ...

**Comment by 111qqz** [comment]
> 你增加线程数量试试

线程尝试过2,4，推理性能和线程设置为1的时候基本没什么区别

**Comment by 111qqz** [comment]
> 可以 ncnnmerge 合并成一个模型，然后 input input extract extract ...

目前就是这样做的 ，使用了ncnnmerge将两个模型合并
然后input input extract extract
但是性能和串行inference两个模型基本是一致的

**Comment by 111qqz** [comment]
> 还有一个，因为这两个模型是是独立的，你可以自己创建两个线程，每个线程处理一个模型。

是的，这样肯定是OK的。不过也还是想探索下模型或者模型推理引擎的实现。

另外还想请教下，ncnnmerge的主要用途是为了方便模型的分发吗？ 预期是会有提速的吗？

**Comment by csukuangfj** [comment]
> > 还有一个，因为这两个模型是是独立的，你可以自己创建两个线程，每个线程处理一个模型。
> 
> 
> 
> 是的，这样肯定是OK的。不过也还是想探索下模型或者模型推理引擎的实现。
> 
> 
> 
> 另外还想请教下，ncnnmerge的主要用途是为了方便模型的分发吗？ 预期是会有提速的吗？
> 
> 

你两个模型是独立的，应该没有

**Comment by wzyforgit** [comment]
权重不同就意味着每一个卷积都得重新卷一遍

**Comment by 111qqz** [comment]
感觉大佬们的解答！

**Comment by nihui** [comment]
The ncnn batch infrastructure feature, which relies on the pnnx tool, is implemented at https://github.com/Tencent/ncnn/commit/127b4146148844ccf67a5bdcb0385e925aa13fbb
