### ISSUE TITLE
segmentation fault while extracting the output layer

### ISSUE THREAD

**Issue by xiang-wuu** [Tencent/ncnn#4515]
I have converted the [onnx](https://drive.google.com/file/d/1IGNFX0iKPXzH1u1IQbLeN6DNsYPOSWFZ/view?usp=sharing) model to the required ncnn format using [convertmodel.com](https://convertmodel.com/#input=onnx&output=ncnn) with the optimization flags, the [.param](https://drive.google.com/file/d/1NVJD81R6aNOtS5Snu_ajQha6IXYEQ2p6/view?usp=sharing) and [.bin](https://drive.google.com/file/d/1Y3HIPaNYEqIdLR8gvunRo65sGW9TlEbo/view?usp=sharing) files has generated without any errors. but as per the `.param` file the first layer is as below, 
```
Input                    0                        0 1 0
```
used with `0` as input blob(input layer) , as per below code,
```
cv::Mat img;
ncnn::Mat in = ncnn::Mat::from_pixels(img.data, ncnn::Mat::PIXEL_BGR, img.cols, img.rows);
ncnn::Extractor ex = net.create_extractor();
ex.set_light_mode(true);
ex.input("0", in);
```
while debugging(running) there is no issue while setting this as input blob, but when used `ex.extract` for inferencing it's causing segmentation fault,
```
ncnn::Mat out;
ex.extract("tf.identity", out);
```
as per the  last layer from `.param` file, which is as below,
```
Reshape  StatefulPartitionedCall/model/conv2d_62/Conv2D__262  1  1  StatefulPartitionedCall/model/conv2d_62/Conv2D:0  tf.identity 0=256 1=1 2=1
```
i selected `tf.identity` as output blob name which signifies to the final output layer, however the output tensor is going to be of shape `256, 1, 1` which appears to be correct for the above output layer, then what else is cause the segmentation fault? any help on this would be appreciated!

**Comment by csukuangfj** [comment]
建议用gdb 自己调试。nihui太忙了

**Comment by csukuangfj** [comment]
1.先编译一个debug 版
2.gdb 调试，碰到segfault 的时候，请把backtrace 贴出来

**Comment by sayyidan-i** [comment]
I have similar error with segmentation fault, can you explain how you solve your problem please?

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
