### ISSUE TITLE
benchncnn使用GPU作为device后，为什么不同的num_threads会有不同的性能？

### ISSUE THREAD

**Issue by yuxiao-ash** [Tencent/ncnn#4523]
## detail | 详细描述 | 詳細な説明
使用同一张GPU进行ncnn的benchmark测试时，cpu的线程数量不同会影响ncnn的模型推理耗时。

参与推理运算的不是同样的一张GPU吗，为什么cpu线程数量会影响到ncnn的模型推理耗时呢？

**Comment by nihui** [comment]
模型里有一些操作是在cpu上完成的，比如上传下载的fp16转换
还有可能是一些算子没有实现vulkan，会自动使用cpu进行计算，这里也会考虑多线程
