### ISSUE TITLE
双线性插值汇编代码疑问

### ISSUE THREAD

**Issue by fubuzhuirou1** [Tencent/ncnn#4531]
## detail | 详细描述 | 詳細な説明
mat_pixel_resize.cpp

三次右移
797行int16x4_t _rows0_sr4 = vshrn_n_s32(_rows0, 4);
888行"vsra.s32   q10, q0, #16    \n"
896行"vshrn.s32  d20, q10, #2    \n"

数字2
874行"mov        r4, #2          \n"

上述几行代码意思没太理解，能帮忙分析下吗？

**Comment by fubuzhuirou1** [comment]
@nihui 你好，打扰一下，可以帮忙看下这个疑问吗，非常感谢。

**Comment by nihui** [comment]
重写了下 https://github.com/Tencent/ncnn/pull/5200
文档参考 https://developer.arm.com/architectures/instruction-sets/intrinsics
