### ISSUE TITLE
在模型进行推理的时候出core

### ISSUE THREAD

**Issue by busishengui** [Tencent/ncnn#4545]
## error log | 日志或报错信息 | ログ
Segmentation fault
## context | 编译/运行环境 | バックグラウンド
Linux
## how to reproduce | 复现步骤 | 再現方法
我的代码：构建一个1x6000的矩阵
    ncnn::Mat input = ncnn::Mat(1, 6000);
    input.fill(1);
    sess.extract("input_x:0", input);

以下是core信息：
(gdb) f 0
#0  0x00007efcbfab2996 in ncnn::NetPrivate::forward_layer (this=0x1addd00, layer_index=0, blob_mats=..., opt=...) at /data/nfs_rt26/kailong/ncnn/src/net.cpp:179
179	        int bottom_blob_index = layer->bottoms[0];
永远都是这个错

**Comment by busishengui** [comment]
我通过调试程序发现：= layer->bottoms的shape永远都是0，这是为什么呢？这很明显不对啊

**Comment by nihui** [comment]
sess.extract 是不是应该 sess.input

**Comment by busishengui** [comment]
> sess.extract 是不是应该 sess.input

非常感谢！！
