### ISSUE TITLE
pip install . 缺少pybind11

### ISSUE THREAD

**Issue by Baiyuetribe** [Tencent/ncnn#4549]
## error log | 日志或报错信息 | ログ
在新机器上运行`pip install ncnn` 或者克隆项目后运行`pip install .`都会报错,如下：
```
      CMake Error at python/CMakeLists.txt:24 (add_subdirectory):
        The source directory
      
          /Users/baiyue/mino/cpp/ncnn20230220/python/pybind11
      
        does not contain a CMakeLists.txt file.
```      
    
## context | 编译/运行环境 | バックグラウンド
Apple Mac M2
## how to reproduce | 复现步骤 | 再現方法
解决办法，进入python目录后，需要手动`https://github.com/pybind/pybind11.git`后，再次安装就正常了。
按道理应该是自动克隆的，不清楚为什么失效了，望修复。

**Comment by csukuangfj** [comment]
出错的原因，是因为你没有看文档吧。

文档如下
https://github.com/Tencent/ncnn/tree/master/python

你少了下面两个命令
```
cd /pathto/ncnn
git submodule init && git submodule update
```

**Comment by Baiyuetribe** [comment]
即便这样，还是存在bug, 因为新机器`pip install ncnn`也会报上面的错误

**Comment by csukuangfj** [comment]
按照文档，会有问题么？
