### ISSUE TITLE
失败的经历，给后人以警示：我在训练时使用的max_size为550，但是在转化模型时的使用的max_size为512，导致模型转化失败，得到一个经验教训：做事情要认认真真。

### ISSUE THREAD

**Issue by 74284853** [Tencent/ncnn#4569]
失败的经历，给后人以警示：我在训练时使用的max_size为550，但是在转化模型时的使用的max_size为512，导致模型转化失败，得到一个经验教训：做事情要认认真真。

_Originally posted by @junqiCao in https://github.com/Tencent/ncnn/issues/2248#issuecomment-719147953_
yolact-ncnn部署按照知乎详细步骤完成模型模型，但却出现与上述问题相同的故障，无法预测正确的mask

**Comment by 74284853** [comment]
希望可以得到问题的解决方法

**Comment by 74284853** [comment]
问题一：torch.onnx._export(net, batch, "yolact.onnx", export_params=True, keep_initializers_as_inputs=True, opset_version=11)，设置opset_version=11时无法生存onnx文件。设置opset_version=9时生成onnx但是会有如下KetError=0的提示。
![image](https://user-images.githubusercontent.com/75053635/224867871-9b3df7b5-aed7-43a7-b2f0-ff7077bd37ee.png)

**Comment by 74284853** [comment]
问题二：使用opset_version=9所生成的onnx经过转换，优化得到的yolact-opt.param与yolact-opt.bin，执行example/yolact.cpp后无法正确生成mask渲染，其中根据nihui发布的知乎教程（https://zhuanlan.zhihu.com/p/128974102）中的0x6 手工微调模型进行了全面修改。结果如下图：
![Uploading image.png…]()

**Comment by 74284853** [comment]
![image](https://user-images.githubusercontent.com/75053635/224868867-19ec99e7-7be0-4ff3-9f9d-bb377739c92c.png)

**Comment by 74284853** [comment]
@nihui  Really hope to get your help.

**Comment by 74284853** [comment]
我是用这个网站的代码成功了，https://github.com/Ma-Dan/yolact/tree/onnx，在链接代码的基础上增加了opset_version=11，并执行‘python eval.py --trained_model=weights/yolact_darknet53_54_800000.pth --score_threshold=0.3 --top_k=100 --cuda=False --image=dog.jpg’

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
