### ISSUE TITLE
速度比mxnet慢许多

### ISSUE THREAD

**Issue by anguoyang** [Tencent/ncnn#457]
您好，我把mxnet的模型转换到ncnn以后，识别的结果是一致的。但速度比mxnet反而满了许多。
我试过mtcnn（caffe）转成ncnn以后做人脸检测，速度很快，效果也不错，但识别（mxnet）转成ncnn以后，识别速度比mxnet慢很多。

**Comment by anguoyang** [comment]
请问可能是什么原因？

**Comment by nihui** [comment]
ncnn对手机平台做了优化，对pc没有优化，pc上速度慢

**Comment by anguoyang** [comment]
多谢

**Comment by sunjunlishi** [comment]
@anguoyang 你是怎么调用的，我调用转换后的模型，结果一直一样

**Comment by anguoyang** [comment]
@sunjunlishi 好久了，记不太清楚怎么调用的。结果是一模一样的，速度不一样而已。

**Comment by sunjunlishi** [comment]
那个年龄性别的最新版本已经可以了

**Comment by anguoyang** [comment]
@sunjunlishi 哪个模型？

**Comment by sunjunlishi** [comment]
https://github.com/deepinsight/insightface/tree/master/gender-age

**Comment by zhanglaplace** [comment]
@sunjunlishi 请教下这个ncnn得模型转化后的提取的输出节点是什么
