### ISSUE TITLE
树莓派编译vulkan过程中，出现了gfxrecon-replay库的错误

### ISSUE THREAD

**Issue by Hao-Ke-Shui** [Tencent/ncnn#4571]
## detail | 详细描述 | 詳細な説明
![_ JMW}25RE~M955X C2_C(E](https://user-images.githubusercontent.com/101874724/224869100-7600e964-0457-4867-8c01-394d59f6797c.jpg)
![6}MB7C`TRF )H1Q6D6Y@AMI](https://user-images.githubusercontent.com/101874724/224869112-f4026989-5abd-4208-aef7-28eae6f97c3e.jpg)
请问如何解决？

**Comment by nihui** [comment]
参考网上的教程 https://qengineering.eu/install-vulkan-on-raspberry-pi.html
