### ISSUE TITLE
ncnn在ARMv7交叉编译后上板执行报错Arithmetic exception

### ISSUE THREAD

**Issue by shone666** [Tencent/ncnn#4574]
## error log | 日志或报错信息 | ログ
参考https://github.com/nihui/ncnn_on_esp32中的代码，用g++和arm-openwrt-linux-g++(musl)编译代码，在x86和R328/T113 ARMv7上运行
1）用mnist + ncnn在x86上运行，结果正常
![0b3f22e0fe325cc89a0f2c7691481d2](https://user-images.githubusercontent.com/50399513/225223114-b892b5e8-0f7d-4f35-be11-efaa87356710.jpg)
2）用mnist + ncnn 在T113/R328上运行异常
![69196dcfa14e5279733b332d5ccdb85](https://user-images.githubusercontent.com/50399513/225223309-c39bc08c-6de5-49ee-9369-d49a050b986b.jpg)
3）用mnist + tflite 在x86上运行正常
![1678861171713](https://user-images.githubusercontent.com/50399513/225223520-236f4b7d-81c3-47f0-9be6-538a6a79587b.png)
4）用mnist + tflite 在T113/R328上运行正常
![1678861288832](https://user-images.githubusercontent.com/50399513/225223796-d16b0283-3374-4958-9489-84d12ba893d3.png)
从上面的结果来看，tflite版本在x86和ARM-A7上运行都正常，但ncnn版本在ARM-A7上就报Arithmetic exception，free查看芯片上有39MB 内存剩余，而mnist+ncnn在x86上也只占用5.5MB内存，不存在板上内存泄露的问题

## context | 编译/运行环境 | バックグラウンド
1）x86 Linux (ubuntu22.04) g++11.3.0
2）ARMv7-32bit Cortex-A7 T113/R328 arm-openwrt-linux-muslgnueabi-g++ (OpenWrt/Linaro GCC 6.4-2017.11 2017-11) 6.4.1   

## how to reproduce | 复现步骤 | 再現方法
1.https://github.com/nihui/ncnn_on_esp32/main 中的代码抽出，注释掉esp和time相关的东西
2.关键步骤添加printf
3.x86和ARM换不同的编译工具编译运行测试

## more | 其他 | その他
1）ncnn的代码在全志D1s上运行不会出现上述Arithmetic exception问题，D1s是risc-v架构
2）不仅是mnist+ncnn在32bit ARMv7上报Arithmetic exception，用squeezenet也是一样，甚至benchncnn也一样
从上面的实验来看，可能是ncnn的某一些隐藏BUG，或是ncnn与ARMv7适配问题，请帮忙排查，谢谢！

**Comment by wzyforgit** [comment]
你把那个ARM相关的优化都关了再试试？

**Comment by shone666** [comment]
> 
#CXX_FLAGS = -march=armv7-a -mfloat-abi=hard -mfpu=neon -O3 -DNDEBUG -fPIE -fno-rtti
CXX_FLAGS =
我把Makefile里面CXX_FLAGS都去掉了编译main.cpp推到板子上依然Arithmetic exception

**Comment by wzyforgit** [comment]
一个比较暴力的办法：把NCNN的ARM优化代码全删了
也就是编译的时候你要注意输出日志，不能去编NCNN的ARM优化代码，只能编纯CPP代码

**Comment by shone666** [comment]
> 我把NCNN交叉编译的toolchanis/*.cmake文件里面的CXX_FLAGS也去掉了，改成了：
#SET ( CMAKE_CXX_FLAGS "-march=armv7-a -mfloat-abi=hard -mfpu=neon ${CMAKE_CXX_FLAGS}" )
SET ( CMAKE_CXX_FLAGS " ${CMAKE_CXX_FLAGS}" )
编译出来新的ARMv7 libncnn.a放到代码编译后上板运行，的确没有Arithmetic exception了，但是却报了Segmentation fault，但是这个程序在 x86上是运行没有问题的，也不存在内存问题
我将NCNN中toolchain/*.cmake 中 的编译选项改为：
SET ( CMAKE_CXX_FLAGS "-march=armv7-a ${CMAKE_CXX_FLAGS}" ) 然后编译上板运行又出现Arithmetic exception了

**Comment by wzyforgit** [comment]
> > 我把NCNN交叉编译的toolchanis/_.cmake文件里面的CXX_FLAGS也去掉了，改成了：
> > #SET ( CMAKE_CXX_FLAGS "-march=armv7-a -mfloat-abi=hard -mfpu=neon ${CMAKE_CXX_FLAGS}" )
> > SET ( CMAKE_CXX_FLAGS " ${CMAKE_CXX_FLAGS}" )
> > 编译出来新的ARMv7 libncnn.a放到代码编译后上板运行，的确没有Arithmetic exception了，但是却报了Segmentation fault，但是这个程序在 x86上是运行没有问题的，也不存在内存问题
> > 我将NCNN中toolchain/_.cmake 中 的编译选项改为：
> > SET ( CMAKE_CXX_FLAGS "-march=armv7-a ${CMAKE_CXX_FLAGS}" ) 然后编译上板运行又出现Arithmetic exception了

啊这～遇到我的知识盲区了

**Comment by niinorz** [comment]
-fno-exceptions 试试，不过很可能计算结果会出现 nan 或者 inf
跨平台的计算结果问题是比较麻烦

**Comment by shone666** [comment]
> -fno-exceptions 添加了这个交叉编译出libncnn.a 再链接生成可执行 adb push 到板子还是一样出现 Arithmetic exception。我甚至换成动态库编译出 libncnn.so 推进去板子也是一样的错误

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4610
这个pr应该修好了

**Comment by nihui** [comment]
fell free to reopen issue if it still resists
