### ISSUE TITLE
使用了新版本20230223得不出正确结果

### ISSUE THREAD

**Issue by lugof1988** [Tencent/ncnn#4576]
## error log | 日志或报错信息 | ログ
无报错，就是得出的结果和20230223之前的版本不一样
我使用的是https://github.com/FeiGeChuanShu/ncnn_nanodet_hand/tree/main/ncnn-yolox-hand 这个模型
目标检测方面都能正确得出结果，只是到了使用landmark,具体[hand_lite-op]这个模型(https://github.com/FeiGeChuanShu/ncnn_nanodet_hand/blob/main/ncnn-yolox-hand/app/src/main/assets/hand_lite-op.param)
会得到不正确结果，这个问题在其他版本下都是正常的。
编译运行的结果如图所示
## context | 编译/运行环境 | バックグラウンド
windows x86下使用Android Studio打包

## how to reproduce | 复现步骤 | 再現方法
1.下载最新ncnn版本
2.https://github.com/FeiGeChuanShu/ncnn_nanodet_hand/tree/main/ncnn-yolox-hand 配置里面修改为最新版本
3.运行部署到android手机上，得不到正确结果
4.将最新版本降级到20221128 版本下 能得到正确结果
[5.问题应该是出在layer里面,替换layer为旧的代码,发现能正确得出结果]

## more | 其他 | その他
![Screenshot_2023-03-14-22-35-18-582_com tencent nc](https://user-images.githubusercontent.com/111948138/225491912-b6d8dc52-bceb-4dfc-9325-01e0616f5e13.jpg)
![Screenshot_2023-03-14-22-35-24-663_com tencent nc](https://user-images.githubusercontent.com/111948138/225491918-27aace18-8562-4b5c-b523-6dd03df28044.jpg)

**Comment by lugof1988** [comment]
啊 佬们 第一次提交问题,不懂规矩，望佬们多多海涵。

**Comment by nihui** [comment]
load_param前设置
```
opt.use_winograd63_convolution=false;
```
是否能获得正常结果？

**Comment by lugof1988** [comment]
额 大佬好，我刚试了下还是不行，结果一样错的。

**Comment by nihui** [comment]
```
Squeeze                  model_1/model/global_average_pooling2d/Mean_Squeeze__310 1 1 model_1/model/global_average_pooling2d/Mean:0 model_1/model/global_average_pooling2d/Mean_Squeeze__310:0 -23300=2,2,3
```

`Squeeze` 修改为 `Noop` 试试

**Comment by lugof1988** [comment]
嗯嗯 大佬~改了 还是不行，额 这段时间忙其他的~现在才看到~ 我到时候也输出来看下是到哪一层出错~

**Comment by longit123** [comment]
我用`ncnn-20230223-windows-vs2017-shared` ，也有莫名其妙的问题，main函数执行完了一直卡那里几秒，然后`Process finished with exit code -1073740791 (0xC0000409)` 报错，结果现在看是正常的；

如果在main最后面加`ncnn::destroy_gpu_instance();`，就会报这类错误

```
FATAL ERROR! reclaim_blob_allocator get wild allocator 0000021F8DE8EA90
FATAL ERROR! reclaim_staging_allocator get wild allocator 0000021F8DE8EAF0
```

如果加`net.clear()`，就会报
```
FATAL ERROR! pool allocator destroyed too early
0000028F51A16080 still in use
```

但结果还是正常的，反正这个版本，main函数最后就会卡几秒，然后exit code有错，但结果还是正常的，让人有点不爽

**Comment by lugof1988** [comment]
额,不好意思最近太忙了，忙其他项目去了，今天才来回复， 按照楼上大佬修改得 得不出正确的结构?
另外我用blobs()[i]得出名称后 遍历输出值,如下图 左边是新版本的，右边是旧版本得出的结果(正确的)
![QQ截图20230406111937](https://user-images.githubusercontent.com/111948138/230264397-9b3ef26f-6105-4919-977e-7180d8379b37.png)

**Comment by lugof1988** [comment]
从数值上对比，前面一直是正确的?到了最后gemm后就开始歪了?(不知道我这么输出科不科学)

**Comment by WenJUST** [comment]
你的模型应该跟我的模型是一样的都是mediapipe转过来的，只是层名有点不一样，你按照我的改，注意输入输出层名改成你的，这样才能前后接上，才能得出正确的结构，gemm歪是因为你的输出还是有16个通道，Squeeze虽然压缩成1152*1了，但是后面做gemm时还是会出来16个。

**Comment by WenJUST** [comment]
> 你的模型应该跟我的模型是一样的都是mediapipe转过来的，只是层名有点不一样，你按照我的改，注意输入输出层名改成你的，这样才能前后接上，才能得出正确的结构，gemm歪是因为你的输出还是有16个通道，Squeeze虽然压缩成1152*1了，但是后面做gemm时还是会出来16个。

哦，我这是full的，op的那个，你自己看下，意思大概是这个意思。

**Comment by lugof1988** [comment]
恩恩 ,两个应该差不多,下午我试试 谢谢大佬指点~

**Comment by lugof1988** [comment]
哇 感谢两位大佬,晚上我回家看了下，经过楼上大佬指点 op我最终改为
Reshape                  model_1/model/global_average_pooling2d/Mean_Squeeze__310 1 1 model_1/model/global_average_pooling2d/Mean:0 model_1/model/global_average_pooling2d/Mean_Squeeze__310:0 0=672 1=1 11=1 2=1
最终数值略有偏差，但整体是一致的
![QQ截图20230406233205](https://user-images.githubusercontent.com/111948138/230427703-b756461c-4e57-404d-893a-73d48d705c85.png)
