### ISSUE TITLE
在支持AVX512F的CPU上运行Retinaface产生不正确结果

### ISSUE THREAD

**Issue by w8501** [Tencent/ncnn#4578]
## context | 编译/运行环境 | バックグラウンド
在win10 CPU  i5-8400 CPU 下编译 或者在虚拟机ubuntu16.04下编译
## how to reproduce | 复现步骤 | 再現方法
1.在**支持AVX512F的CPU**上 如：i7-1195G7和Xeon Platinum 8269CY以及Xeon Silver 4210R调用编译好的包含ncnn的动态库加载[retinaface](https://github.com/nihui/ncnn-assets/blob/master/models/mnet.25-opt.bin)
2.net.opt.use_packing_layout = true时支持AVX512F的CPU会得到错误的结果，而不支持AVX512F的CPU结果是正确的。
3.net.opt.use_packing_layout = flase时所有CPU的结果一致且正确。

**Comment by w8501** [comment]
debug发现是在第一个1x1的卷积处产生错误的结果

**Comment by Yoh-Z** [comment]
cmake的时候加一个-DNCNN_AVX512=OFF试试有没有问题

**Comment by w8501** [comment]
> 

已经定位出来了，在支持AVX512F的机器上我用的retinaface版本没合并bn层，然后在第一个1x1卷积后bn层的scale层的bottom_top_blob.elempack等于16，但是代码里没有对应实现，导致出现了错误的结果

**Comment by w8501** [comment]
已经定位出来是因为我使用的是没有合并bn的retinaface，然后在支持AVX512F的CPU上，第一个1x1卷积后的scale层的bottom_top_blob.elempack=16，但是代码里并没有对应的实现，导致出现了错误的结果

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4580

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/6987efd9509b33dac4be30deb0beb74f48d7db2b
