### ISSUE TITLE
pnnx support pytorch2.0

### ISSUE THREAD

**Issue by wm901115nwpu** [Tencent/ncnn#4581]
<img width="1465" alt="截屏2023-03-18 15 20 21" src="https://user-images.githubusercontent.com/13309349/226091345-fab91cca-2038-4379-aec7-f3d875d373d0.png">

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/693535afc17fb23e8c78eadeffa65e648b2c4a3e
