### ISSUE TITLE
使用ncnn自己实现的opencv.cpp问题

### ISSUE THREAD

**Issue by bigbao9494** [Tencent/ncnn#459]
通过在CMakeLists.txt中修改：
option(NCNN_OPENCV "minimal opencv structure emulation" ON)
来打开对opencv.cpp的编译
取消对opencv库的使用，再使用ncnn自己的cv::imread发现始终读取图片失败
调试进去发现是下面代码没有成功：
    int nscan = fscanf(fp, "%2s\n%d %d\n255\n", magic, &w, &h);
    if (nscan == 3 && magic[0] == 'P' && (magic[1] == '5' || magic[1] == '6'))

想请问一下这是什么原因？是只支持特殊图片格式？

**Comment by nihui** [comment]
首先，不推荐用这个 opencv.cpp，几乎没什么功能
这里头的 cv::imread 只能读写 ppm/pgm 格式
