### ISSUE TITLE
推理三个output该写多少？

### ISSUE THREAD

**Issue by jia0511** [Tencent/ncnn#4592]
报错如下
12 = 0.49901 at 679.01 719.00 65.99 x 0.00
43 = 0.49901 at 935.00 232.33 66.00 x 45.41
50 = 0.49901 at 423.01 719.00 65.98 x 0.00
4 = 0.49901 at 934.96 719.00 66.00 x 0.00
46 = 0.49901 at 422.99 719.00 66.00 x 0.00
14 = 0.49901 at 167.00 719.00 66.00 x 0.00
44 = 0.49901 at 420.79 1.97 65.99 x 60.04
12 = 0.49901 at 678.98 719.00 66.00 x 0.00
46 = 0.49900 at 423.00 457.00 65.99 x 45.99
44 = 0.49900 at 678.67 520.95 66.00 x 46.00
10 = 0.49900 at 423.00 436.58 66.00 x 34.16
12 = 0.49900 at 1191.00 461.38 66.00 x 37.21
50 = 0.49900 at 167.00 719.00 65.97 x 0.00
42 = 0.49899 at 935.25 489.00 63.88 x 46.00
4 = 0.49899 at 678.95 719.00 66.00 x 0.00
4 = 0.49899 at 679.56 0.00 64.26 x 23.00
6 = 0.49898 at 934.95 0.00 65.94 x 151.44
50 = 0.49898 at 935.00 414.42 65.99 x 35.14
4 = 0.49898 at 934.66 719.00 64.62 x 0.00
44 = 0.49897 at 934.89 485.47 65.99 x 178.08
4 = 0.49896 at 1190.86 719.00 63.81 x 0.00
4 = 0.49896 at 422.87 719.00 66.00 x 0.00
14 = 0.49896 at 423.00 136.23 66.00 x 46.00
51 = 0.49895 at 935.00 200.99 66.00 x 46.00
50 = 0.49895 at 935.00 719.00 66.00 x 0.00
13 = 0.49894 at 1191.00 201.00 66.00 x 46.00
11 = 0.49894 at 167.00 216.91 66.00 x 45.81
44 = 0.49894 at 678.91 719.00 65.99 x 0.00
14 = 0.49894 at 423.00 719.00 66.00 x 0.00
48 = 0.49893 at 1191.00 719.00 66.00 x 0.00
44 = 0.49893 at 422.93 719.00 66.00 x 0.00
12 = 0.49892 at 423.00 648.11 66.00 x 46.00
51 = 0.49892 at 166.92 719.00 65.99 x 0.00
12 = 0.49892 at 420.96 719.00 66.00 x 0.00
8 = 0.49892 at 167.00 719.00 66.00 x 0.00
3 = 0.49892 at 679.00 719.00 66.00 x 0.00
52 = 0.49892 at 935.00 719.00 65.99 x 0.00
13 = 0.49892 at 423.08 406.94 65.84 x 46.00
6 = 0.49891 at 1190.97 0.00 65.91 x 152.32
13 = 0.49890 at 422.90 719.00 65.99 x 0.00
10 = 0.49889 at 422.96 0.00 66.00 x 7.00
44 = 0.49889 at 422.16 520.99 66.00 x 45.99
52 = 0.49887 at 167.00 719.00 66.00 x 0.00
44 = 0.49885 at 934.87 719.00 65.99 x 0.00
51 = 0.49885 at 167.07 393.64 65.85 x 44.62
50 = 0.49884 at 935.00 719.00 66.00 x 0.00
50 = 0.49883 at 679.00 719.00 66.00 x 0.00
44 = 0.49882 at 1190.84 719.00 65.99 x 0.00
4 = 0.49882 at 166.93 719.00 66.00 x 0.00
50 = 0.49881 at 423.00 719.00 66.00 x 0.00
44 = 0.49880 at 165.14 10.49 65.97 x 43.02
10 = 0.49877 at 1191.00 0.00 65.98 x 126.93
10 = 0.49876 at 422.99 473.31 66.00 x 45.39
8 = 0.49876 at 423.00 719.00 66.00 x 0.00
49 = 0.49875 at 166.89 719.00 65.97 x 0.00
10 = 0.49874 at 935.00 275.93 66.00 x 183.04
40 = 0.49874 at 1190.97 719.00 65.98 x 0.00
52 = 0.49874 at 1191.00 719.00 66.00 x 0.00
12 = 0.49873 at 1191.00 719.00 66.00 x 0.00
4 = 0.49872 at 166.65 719.00 66.00 x 0.00
51 = 0.49870 at 934.99 719.00 65.99 x 0.00
13 = 0.49869 at 678.90 719.00 65.99 x 0.00
4 = 0.49867 at 936.52 0.00 62.07 x 23.00
44 = 0.49867 at 678.98 0.00 65.99 x 7.00
14 = 0.49865 at 679.00 136.07 66.00 x 46.00
76 = 0.49855 at 1191.04 312.41 65.91 x 175.16
44 = 0.49853 at 165.43 521.35 65.99 x 45.30
50 = 0.49844 at 172.84 719.00 54.32 x 0.00
52 = 0.49843 at 130.35 648.37 139.31 x 46.00
50 = 0.49834 at 1191.09 393.00 65.82 x 46.00
51 = 0.49826 at 1191.00 719.00 66.00 x 0.00
42 = 0.49823 at 934.99 0.00 65.98 x 7.00
13 = 0.49788 at 679.08 393.00 65.83 x 46.00
10 = 0.49774 at 165.73 0.00 65.47 x 3.89
44 = 0.49773 at 1188.84 0.00 65.89 x 39.00
52 = 0.49770 at 102.26 136.40 195.48 x 46.00
48 = 0.49768 at 166.33 478.47 65.61 x 35.02
8 = 0.49766 at 679.00 719.00 66.00 x 0.00
51 = 0.49765 at 950.84 648.04 66.00 x 46.00
42 = 0.49763 at 167.46 505.00 63.69 x 46.00
51 = 0.49761 at 934.96 136.10 66.00 x 46.00
14 = 0.49755 at 686.47 647.88 66.00 x 46.00
4 = 0.49754 at 919.00 719.00 66.00 x 0.00
12 = 0.49750 at 919.00 427.59 66.00 x 37.77
52 = 0.49748 at 663.00 443.18 66.00 x 40.78
12 = 0.49746 at 1175.00 426.71 66.00 x 39.05
52 = 0.49745 at 663.00 719.00 66.00 x 0.00
14 = 0.49745 at 151.00 437.12 66.00 x 49.38
8 = 0.49744 at 151.00 719.00 66.00 x 0.00
50 = 0.49741 at 919.00 719.00 66.00 x 0.00
52 = 0.49740 at 407.00 435.36 66.00 x 53.38
44 = 0.49740 at 405.32 13.30 66.00 x 37.40
52 = 0.49738 at 151.00 719.00 66.00 x 0.00
48 = 0.49737 at 1175.00 719.00 66.00 x 0.00
4 = 0.49731 at 918.98 719.00 66.00 x 0.00
14 = 0.49728 at 407.00 719.00 66.00 x 0.00
43 = 0.49727 at 919.00 719.00 66.00 x 0.00
50 = 0.49725 at 934.93 719.00 65.99 x 0.00
52 = 0.49723 at 1175.00 719.00 66.00 x 0.00
52 = 0.49721 at 919.00 719.00 66.00 x 0.00
42 = 0.49717 at 150.99 719.00 65.04 x 0.00
43 = 0.49717 at 663.00 232.86 66.00 x 45.92
76 = 0.49714 at 1190.93 719.00 65.99 x 0.00
42 = 0.49712 at 1175.33 489.00 64.53 x 46.00
10 = 0.49709 at 1175.00 22.96 65.99 x 79.35
4 = 0.49707 at 406.85 719.00 65.30 x 0.00
44 = 0.49704 at 919.00 535.74 65.99 x 99.58
4 = 0.49702 at 1189.11 505.00 65.95 x 45.99
42 = 0.49697 at 919.00 473.01 66.00 x 45.98
44 = 0.49697 at 1175.00 543.42 66.00 x 63.29
6 = 0.49695 at 167.00 57.71 66.00 x 40.84
6 = 0.49695 at 919.00 5.95 65.98 x 116.92
4 = 0.49694 at 662.42 719.00 65.71 x 0.00
51 = 0.49694 at 935.00 719.00 65.98 x 0.00
33 = 0.49691 at 694.01 719.00 66.00 x 0.00
5 = 0.49685 at 1175.00 248.93 66.00 x 45.99
4 = 0.49683 at 1174.68 719.00 65.99 x 0.00
8 = 0.49659 at 407.00 719.00 66.00 x 0.00
48 = 0.49649 at 166.79 719.00 65.64 x 0.00
43 = 0.49645 at 919.00 217.00 66.00 x 46.00
4 = 0.49639 at 1176.13 0.00 63.46 x 23.00
41 = 0.49627 at 935.00 719.00 66.00 x 0.00
12 = 0.49614 at 935.08 393.01 65.83 x 45.98
44 = 0.49606 at 406.98 719.00 65.98 x 0.00
4 = 0.49561 at 406.79 505.00 65.55 x 46.00
48 = 0.49529 at 1175.00 719.00 66.00 x 0.00
4 = 0.49520 at 662.45 505.00 65.80 x 46.00
8 = 0.49517 at 678.99 473.05 66.00 x 45.89
4 = 0.49515 at 918.02 505.00 65.91 x 46.00
44 = 0.49512 at 918.28 0.00 65.85 x 39.00
0 = 0.49498 at 684.49 719.00 54.97 x 0.00
5 = 0.49466 at 166.50 712.99 65.83 x 6.01
48 = 0.49463 at 1190.99 719.00 66.00 x 0.00
4 = 0.49427 at 151.77 0.00 64.23 x 39.00
44 = 0.49410 at 151.00 573.57 66.00 x 36.19
5 = 0.49374 at 1175.00 719.00 66.00 x 0.00
8 = 0.49350 at 663.00 719.00 66.00 x 0.00
51 = 0.49324 at 151.00 152.96 66.00 x 46.00
6 = 0.49277 at 407.00 60.58 66.00 x 36.46
4 = 0.49255 at 407.17 0.00 65.30 x 39.00
14 = 0.49251 at 413.47 278.65 53.05 x 174.59
44 = 0.49249 at 662.83 0.00 65.67 x 39.00
78 = 0.49217 at 919.03 352.47 65.93 x 95.02
44 = 0.49157 at 166.99 563.69 66.00 x 55.21
6 = 0.49129 at 412.54 719.00 54.92 x 0.00
0 = 0.49051 at 918.99 719.00 65.98 x 0.00
5 = 0.48964 at 1183.38 719.00 49.08 x 0.00
78 = 0.48913 at 935.08 328.62 65.83 x 142.67
6 = 0.48876 at 423.00 49.89 66.00 x 56.32
10 = 0.48797 at 663.08 719.00 65.84 x 0.00
51 = 0.48710 at 1175.00 648.78 66.00 x 46.00
53 = 0.48520 at 150.28 200.99 66.00 x 46.00
10 = 0.48488 at 151.00 719.00 66.00 x 0.00
13 = 0.48394 at 423.00 664.97 66.00 x 46.00
41 = 0.48354 at 1175.00 136.81 66.00 x 46.00
4 = 0.48271 at 897.34 719.00 139.90 x 0.00
10 = 0.48225 at 831.04 719.00 239.51 x 0.00
44 = 0.48099 at 174.24 719.00 51.16 x 0.00
78 = 0.48083 at 667.50 316.55 56.99 x 166.87
9 = 0.47997 at 428.15 681.00 51.30 x 38.00
50 = 0.47959 at 663.00 275.85 66.00 x 179.89
10 = 0.47862 at 919.00 719.00 66.00 x 0.00
47 = 0.47835 at 173.65 313.00 52.24 x 45.99
9 = 0.47815 at 662.48 719.00 101.05 x 0.00
46 = 0.47756 at 407.00 561.29 66.00 x 60.55
13 = 0.47664 at 937.95 184.99 59.02 x 46.00
5 = 0.47645 at 1174.38 185.00 65.98 x 46.00
51 = 0.47612 at 151.00 664.93 66.00 x 46.00
38 = 0.47567 at 1102.55 719.00 176.45 x 0.00
10 = 0.47323 at 166.99 719.00 66.00 x 0.00
10 = 0.47226 at 898.31 261.65 160.44 x 177.42
9 = 0.47187 at 433.85 719.00 49.03 x 0.00
5 = 0.47115 at 1179.21 697.00 57.18 x 22.00
13 = 0.46990 at 662.99 200.99 66.00 x 46.00
74 = 0.46354 at 1166.55 291.46 82.87 x 180.98
51 = 0.46275 at 167.00 719.00 66.00 x 0.00
43 = 0.46211 at 926.88 719.00 50.12 x 0.00
46 = 0.46048 at 423.00 536.62 66.00 x 108.98
46 = 0.45955 at 663.03 62.03 65.94 x 34.17
5 = 0.45758 at 662.99 719.00 66.00 x 0.00
7 = 0.45551 at 935.95 313.03 63.10 x 45.94
51 = 0.44993 at 407.00 153.00 66.00 x 46.00
44 = 0.44388 at 1202.10 719.00 49.08 x 0.00
9 = 0.44330 at 411.80 169.00 56.37 x 46.00
43 = 0.44321 at 407.11 264.99 65.79 x 46.00
8 = 0.44269 at 407.00 719.00 66.00 x 0.00
10 = 0.44213 at 592.71 277.94 251.19 x 146.63
5 = 0.44169 at 926.97 697.00 49.88 x 22.00
38 = 0.44131 at 156.00 719.00 55.96 x 0.00
49 = 0.44107 at 935.28 58.13 65.43 x 42.60
13 = 0.43978 at 422.40 200.97 66.00 x 46.00
48 = 0.43897 at 1176.20 314.11 60.70 x 43.77
47 = 0.43806 at 168.16 169.00 63.59 x 46.00
48 = 0.43734 at 610.62 719.00 201.59 x 0.00
48 = 0.43450 at 627.78 719.00 132.05 x 0.00
44 = 0.43156 at 1179.81 719.00 53.50 x 0.00
8 = 0.43022 at 423.00 719.00 65.99 x 0.00
9 = 0.42863 at 411.86 719.00 53.19 x 0.00
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
3 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
1 = 0.25000 at nan nan nan x nan
end!!!
我搞不清楚三个extract里面数字写多少，我找了网上很多介绍，有的是只有两个Permute，第三个output这个还好写，但是我用最新的ncnn库转换的模型Permute输出都是数字，我一个个试了一遍都不行，所以我全部写数字了，报了上面问题，我yolov5下载了v6.2版本代码，和v6.2版本的预训练模型，也都试过，还是有问题，对于这个三个输出你这里做了个concat后以output名字结尾，但是三个Permute不是写了8、16、32倍下采样吗，照这个写上去不就行了，我也试过你官方代码三个名字，直接段错误，为啥这个输出这么麻烦，不都合到一起输出了，不能只extract一个名字吗？
![2023-03-25 00-12-59屏幕截图](https://user-images.githubusercontent.com/24822418/227581505-9258a5ea-a2da-4388-8ddd-fed42386d6e7.png)
![2023-03-25 00-14-13屏幕截图](https://user-images.githubusercontent.com/24822418/227581683-352e770f-67e1-409e-93eb-46bc80fd7b91.png)
![2023-03-25 00-15-03屏幕截图](https://user-images.githubusercontent.com/24822418/227581880-e64e84de-9df6-4726-b407-a44a26aea9b6.png)

**Comment by jia0511** [comment]
我照你的流程YOLOv5 v6.2 export  onnx model method https://github.com/shaoshengsong/yolov5_62_export_ncnn也clone代码导出简化后的模型，目前输出名字也和你官方输出三个名字对齐，但是为什么结果还是不正常？
![2023-03-25 00-32-58屏幕截图](https://user-images.githubusercontent.com/24822418/227586032-574d1f31-be50-423c-a9d6-3a5362e124b4.png)
![2023-03-25 00-31-53屏幕截图](https://user-images.githubusercontent.com/24822418/227586069-023e8d46-a65b-4d57-a131-cfb7b8999473.png)
![2023-03-25 00-32-19屏幕截图](https://user-images.githubusercontent.com/24822418/227586089-d27469a4-a28d-4601-baf4-ee2c2d305c3c.png)

**Comment by jia0511** [comment]
![2023-03-25 00-41-25屏幕截图](https://user-images.githubusercontent.com/24822418/227587775-61f888b9-fb21-43fa-b3d7-cf92eb9d56d5.png)
我也用compare工具差分过你的模型和我从官方下载后v6.2pretrain模型，为我输出有问题，你提供地址模型输出没有问题，很奇怪。
![2023-03-25 00-44-08屏幕截图](https://user-images.githubusercontent.com/24822418/227588352-a3a2ef46-7a3b-4337-a73f-a6d48dd685f6.png)

**Comment by jia0511** [comment]
我上传了我的模型和你的模型，我的模型是基于你们提供地址下载v6.2预训练模型导出的onnx,再通过编译你们ncnn源码得到tools里onnx2ncnn工具生成的，测试过程中我的模型输出异常，你提供地址却是正常的，通过compare工具对比结构无差异
链接: https://pan.baidu.com/s/1pI5h27ZDdcD1tTd0QXduOA 提取码: 8s85

**Comment by tom2002965** [comment]
是跑yolov5嗎?
https://blog.csdn.net/flyfish1986/article/details/127669328
這邊有比較詳細的步驟

用工具轉出來的param，得修改三個地方喔!

**Comment by jia0511** [comment]
你好，按照你的地址，导出onnx-sim模型，且这三个地方已经是-1了，但是还是输出有问题！
![2023-03-25 13-07-38屏幕截图](https://user-images.githubusercontent.com/24822418/227697568-6894c09a-6326-4597-b5d6-13ea8c25db5c.png)
![2023-03-25 13-05-36屏幕截图](https://user-images.githubusercontent.com/24822418/227697575-31a7fda4-52f5-4edf-b6eb-192d1c172b5e.png)
![2023-03-25 13-08-53屏幕截图](https://user-images.githubusercontent.com/24822418/227697577-d6f9268f-62e2-4cd9-9be8-4bc4cffe37f3.png)

**Comment by jia0511** [comment]
解决了，解决办法是转到fp16后，修改reshape三处地方为-1，只能fp16在ubuntu系统下才能正常运行

**Comment by woodstream** [comment]
> 解决了，解决办法是转到fp16后，修改reshape三处地方为-1，只能fp16在ubuntu系统下才能正常运行

我是出现你第一张图，3个输出然后concat，参数填三个输出会报错。该怎么解决？重新转模型？

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
