### ISSUE TITLE
请问ncnn适用生成对抗网络吗

### ISSUE THREAD

**Issue by JWQZ** [Tencent/ncnn#4593]
## model | 模型 | モデル
1. original model

## how to reproduce | 复现步骤 | 再現方法
1.
2.
3.

**Comment by wzyforgit** [comment]
你就说你用的啥模型，里面有啥算子

**Comment by nihui** [comment]
GAN 是没问题的，这只是训练上和普通的不一样，部署的时候只会用 G 网络，和普通的CNN一样
