### ISSUE TITLE
MacOS newest Vulkan SDK test failed

### ISSUE THREAD

**Issue by DickyQi** [Tencent/ncnn#4600]
## context | 编译/运行环境 | バックグラウンド
MacOS 13.3 Vulkan SDK 1.3.243.0 clang 14.0.0 x86_64-apple-darwin22.3.0 GPU AMD Radeon Pro 5500M
## how to reproduce | 复现步骤 | 再現方法
1. Install newest Vulkan SDK(1.3.243.0)
2. build ncnn with test
3. ctest
93% tests passed, 8 tests failed out of 111

Total Test time (real) = 1335.30 sec

The following tests FAILED:
          6 - test_squeezenet (Failed)
         13 - test_binaryop (Failed)
         14 - test_binaryop_1 (Failed)
         15 - test_binaryop_2 (Failed)
         16 - test_binaryop_3 (Failed)
         37 - test_deconvolution (Failed)
         40 - test_deconvolutiondepthwise (Failed)
         87 - test_priorbox (Failed)
## more | 其他 | その他
CPU test is all passed
[LastTest.log](https://github.com/Tencent/ncnn/files/11144720/LastTest.log)

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
rollback glslang to 11.4.0 as workaround

**Comment by nihui** [comment]
bi-select caused by https://github.com/KhronosGroup/glslang/commit/230168d5d96d9f49393e2d5333fe1090aa9a336f

**Comment by nihui** [comment]
caused by persuade shader code

spec const float x = 0

main()
{
afpvec4 v = afpvec4(x);
}

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4714
