### ISSUE TITLE
Linking CXX executable squeezenet.exe 出错 error LINK 2019

### ISSUE THREAD

**Issue by fastslow** [Tencent/ncnn#4635]
protobuf-v22.3

编译日志
---
[ 89%] Linking CXX executable squeezenet.exe
LINK: command "D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\squeezenet.dir\objects1.rsp /out:squeezenet.exe /implib:squeezenet.lib /pdb:D:\Programs\ncnn\build\examples\squeezenet.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console ..\src\ncnn.lib D:\Programs\opencv\build\x64\mingw\lib\libopencv_highgui470.dll.a D:\Programs\opencv\build\x64\mingw\lib\libopencv_videoio470.dll.a D:\Programs\opencv\build\x64\mingw\lib\libopencv_imgcodecs470.dll.a D:\Programs\opencv\build\x64\mingw\lib\libopencv_imgproc470.dll.a D:\Programs\opencv\build\x64\mingw\lib\libopencv_core470.dll.a kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:squeezenet.exe.manifest" failed (exit code 1120) with the following output:
squeezenet.cpp.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl cv::Mat::~Mat(void)" (??1Mat@cv@@QEAA@XZ)，函数 main 中引用了该符号
squeezenet.cpp.obj : error LNK2019: 无法解析的外部符号 "public: bool __cdecl cv::Mat::empty(void)const " (?empty@Mat@cv@@QEBA_NXZ)，函数 main 中引用了该符号
squeezenet.cpp.obj : error LNK2019: 无法解析的外部符号 "class cv::Mat __cdecl cv::imread(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?imread@cv@@YA?AVMat@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z)，函数 main 中引用了该符号
squeezenet.exe : fatal error LNK1120: 3 个无法解析的外部命令
NMAKE : fatal error U1077: “"D:\Program Files\CMake\bin\cmake.exe"”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
---
进行的命令
git clone https://github.com/Tencent/ncnn.git
cd ncnn
git submodule update --init         # 编译未通过
mkdir build && cd build
cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DProtobuf_INCLUDE_DIR=<protobuf-root-dir>/build-2022/install/include -DProtobuf_LIBRARIES=<protobuf-root-dir>/build-2022/install/lib/libprotobuf.lib -DProtobuf_PROTOC_EXECUTABLE=<protobuf-root-dir>/build-2022/install/bin/protoc.exe -DNCNN_VULKAN=OFF ..

**Comment by Truejunjun** [comment]
Hi! Did you fix it? I have the same bug with you.

**Comment by nihui** [comment]
try the instruction here
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-windows-x64-using-visual-studio-community-2017
