### ISSUE TITLE
怎么判断我的arm板子是否支持int8加速啊？我yolov5转ncnn量化后，fp16和fp32相差不大，int8反而慢了一倍多，这是什么原因？

### ISSUE THREAD

**Issue by deeplearningers** [Tencent/ncnn#4637]
## expectation | 诉求 | 期待する
1. speed 
2. precision

## model | 模型 | モデル
1. model.param and model.bin

**Comment by nihui** [comment]
可以跑 benchncnn 看看 mobilenet
yolov5的swish层因为不能量化，所以慢
