### ISSUE TITLE
pnnx把torchsrcipt模型转为ncnn模型，用python调用问题

### ISSUE THREAD

**Issue by Esword618** [Tencent/ncnn#4640]
在yolo5.7.0版本下，用pnnx把torchsrcipt模型转为ncnn模型后，用 [ncnn的python的examples的yolov5.py文件](https://github.com/Tencent/ncnn/blob/master/python/examples/yolov5.py)调用会报错，用netron查看发现是模型的输出层被Concat了，也没有permute，接下来也尝试很久，但是都失败了，不知道该怎么做，可以提供一个yolov5.7.0的yolov5s.pt的模型通过pnnx操作做测试的案例吗？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/discussions/4541
