### ISSUE TITLE
请问一下，我用yolov8训练出来的模型，window下，NCNN怎么进行目标识别，感谢！

### ISSUE THREAD

**Issue by fengshangren** [Tencent/ncnn#4646]
我也是才学yolo几天，我训练出来了yolov8的.pt模型，现在我想在c++把训练出来的模型可以进行识别，但是现在我一头懵，请大佬讲一下识别流程，或者哪里有文档，谢谢了

**Comment by fengshangren** [comment]
我看例子里有个头文件是#include "opencv2/opencv.hpp"，是不是还要调用opencv

**Comment by fengshangren** [comment]
为了cv::imread这一个方法，还得多调用一个库啊，能不能只调用ncnn本身的方法就可以了

**Comment by tom2002965** [comment]
Build ncnn的時候把這個設置打開吧，就能用ncnn準備的simpleocv了!
這樣就不用多帶opencv library了

https://github.com/Tencent/ncnn/blob/master/CMakeLists.txt#L56

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
