### ISSUE TITLE
InnerProduct层导致模型的精度下降

### ISSUE THREAD

**Issue by gsx1378** [Tencent/ncnn#4666]
您好，我将onnx模型转换为ncnn模型之后，测试过程中发现ncnn网络结构中的InnerProduct层输出结果与onnx该层的输出结果存在较大精度损失，请问这是什么原因呢？
![image](https://user-images.githubusercontent.com/44281534/234222525-30c3c012-da25-4505-a5bc-d7a71177315a.png)
![2](https://user-images.githubusercontent.com/44281534/234222593-bf2e0168-3234-4cae-8b5c-5debdc0cbeb5.png)

**Comment by nihui** [comment]
可能是默认启用fp16引起的，关掉fp16试试
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#disable-fp16

**Comment by gsx1378** [comment]
> 可能是默认启用fp16引起的，关掉fp16试试 https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#disable-fp16

我尝试了关掉FP16,但是精度没有变化，损失和之前一样大。此外我按照您之前提到的方案查看ncnn权重(#2861)，出现了错误："Unknown weight type '1065060386' in 'xxx.bin' in 'xxx.bin'"，目前还未找到较好解决精度损失的方法。

**Comment by gsx1378** [comment]
1. 针对netron无法查看ncnn权重问题：使用netron官网的网页版可以查看，应该跟版本有关
2. 经过手动计算InnerProduct层的输入和权重是正确的
3. 尝试更换ncnn编译库，现在编译库版本是1.0.20221014(#define NCNN_VERSION_STRING "1.0.20220420"), 更换之后的编译库版本是1.0.20220420。更换之后InnerProduct层精度损失由10-3下降到10-6，模型最终输出损失由10-4降到10-5(少量图像测试)。
4. 最终精度损失原因不确定是ncnn版本问题，还是自己编译过程中存在问题。

**Comment by Mactarvish** [comment]
类似的问题，好像这个层带来的误差确实比其它层要大一些。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
