### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by itachi176** [Tencent/ncnn#4667]
## detail | 详细描述 | 詳細な説明
I have a issue. My model classifier mask. input (?,224,224,3) but when I inference model, it noticed "Segmentation fault (core dumped)
". is there any idea to fix this issue

**Comment by itachi176** [comment]
![mask_detector_sim param](https://user-images.githubusercontent.com/62019213/234494442-8e1c75aa-e2e7-417e-912f-c62f900b0030.png)

**Comment by wzyforgit** [comment]
Are you sure your input tensor have 224 channel ?
NCNN's tensor shape arrangement is NCHW, not NHWC, and the N must be 1

**Comment by itachi176** [comment]
> 

 net_input = ncnn::Mat::from_pixels_resize(bgr.data, ncnn::Mat::PIXEL_RGB,
                                                     img_width, img_height, w, h);
i change image to rgb for input

**Comment by nihui** [comment]
please provide the content of param file

**Comment by itachi176** [comment]
> please provide the content of param file

https://drive.google.com/drive/folders/1Pre4dD4Esz1dsG_niAg7kz8nLExsa2CP?usp=sharing 
link to onnx and param file.

**Comment by nihui** [comment]
> > please provide the content of param file
> 
> https://drive.google.com/drive/folders/1Pre4dD4Esz1dsG_niAg7kz8nLExsa2CP?usp=sharing link to onnx and param file.

try skipping the leading permute with
```
ex.input("model/Conv1/Conv2D__6:0", net_input);
```

**Comment by itachi176** [comment]
> > > please provide the content of param file
> > 
> > 
> > https://drive.google.com/drive/folders/1Pre4dD4Esz1dsG_niAg7kz8nLExsa2CP?usp=sharing link to onnx and param file.
> 
> try skipping the leading permute with
> 
> ```
> ex.input("model/Conv1/Conv2D__6:0", net_input);
> ```

it done! thank you so much ^^

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
