### ISSUE TITLE
sphereface转成ncnn后数据提取的问题

### ISSUE THREAD

**Issue by EngineeringBoy** [Tencent/ncnn#467]
rt，我把sphereface转换成ncnn后，同一张图像，提取出来的feature值跟matlab的feature不一样，有遇到相同问题的朋友吗？希望指教下，谢谢啦:)
附上我的代码
void sphereface::getfeature(ncnn::Mat& img_, std::vector<float>& feature) {
	img = img_;
	img.substract_mean_normalize(mean_vals, norm_vals);
	ncnn::Mat in;
	resize_bilinear(img_, in, 112, 96);
	ncnn::Extractor ex = SFnet.create_extractor();
    ex.set_light_mode(true);
    ex.input("data", in);
    ncnn::Mat feature_;
    ex.extract("fc5", feature_);
    float *p = feature_.data;
    for(int i=0;i<feature_.c;i++) {
    	feature.push_back(*p);
    	p += feature_.cstep;
    }
}

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result

**Comment by nihui** [comment]
如果还有问题，可以 reopen issue 继续讨论
