### ISSUE TITLE
a new data layout of binaryop add for some attention modules

### ISSUE THREAD

**Issue by FeiGeChuanShu** [Tencent/ncnn#4696]
## detail | 详细描述 | 詳細な説明

Hi nihui, Recently i have encountered a new data layout in my model.
It may appear in some attention modules that cannot be fused by pnnx at this stage.

A = [2,3,4,5]
B = [2,3,1,5]
C = [2,3,4,5]
C = A + B

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4809

**Comment by FeiGeChuanShu** [comment]
> #4809

Yes! You are my angel!

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/9022b7162a851f5deae0d2e6e5ee5e89a4813212
