### ISSUE TITLE
Inference on batch data

### ISSUE THREAD

**Issue by EdwardChou** [Tencent/ncnn#47]
请问对于NCWH的数据，N > 1的图片输入，ncnn::Extractor如何处理？ncnn::Mat能支持多图转换？

**Comment by nihui** [comment]
因为面向手机端只做 inference，所以不考虑 N > 1 的 batch data，cpu 也没这个能力做 N > 1
多张图片可以串行转换，或者用多线程

**Comment by EdwardChou** [comment]
明白了，谢谢

**Comment by twmht** [comment]
@nihui 

串行轉換是什麼？有任何範例嗎？

**Comment by nihui** [comment]
The ncnn batch infrastructure feature, which relies on the pnnx tool, is implemented at https://github.com/Tencent/ncnn/commit/127b4146148844ccf67a5bdcb0385e925aa13fbb
