### ISSUE TITLE
Is there any plan for supporting fixed point network

### ISSUE THREAD

**Issue by redglass1984** [Tencent/ncnn#470]
Hi, 

I have gone through the source code, seems ARM layers are all NEON **float operations**, as NEON would be faster with FP16 or INT8, do we have any plan to add kernels for supporting fixed point layers?

I also noticed that we can do caffe2ncnn model transform with 8bit or 16 bit quantization, but seems layers also not optimize for it.

Thanks!

**Comment by WenguoLi** [comment]
Waiting for  fixed point ......

**Comment by nihui** [comment]
quantized int8 inference implemented in git master
