### ISSUE TITLE
编译问题：ncnn 20230223在loongarch64架构编译失败

### ISSUE THREAD

**Issue by cugxchen** [Tencent/ncnn#4718]
## detail | 详细描述 | 詳細な説明
ncnn版本：20230223
芯片架构：loongarch64
编译器版本: gcc8.3.0
编译指令: cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/loongarch64-linux-gnu.toolchain.cmake -DCMAKE_BUILD_TYPE=Release .. && make -j4

错误日志：
[ 60%] Building CXX object src/CMakeFiles/ncnn.dir/layer/loongarch/slice_loongarch_lsx.cpp.o
[ 60%] Building CXX object src/CMakeFiles/ncnn.dir/layer/softmax.cpp.o
[ 60%] Building CXX object src/CMakeFiles/ncnn.dir/layer/loongarch/softmax_loongarch.cpp.o
/tmp/ccDesvfb.s: Assembler messages:
/tmp/ccDesvfb.s:1319: 致命错误：no match insn: vfcvtl.s.h.w     $vr0,$vr0
make[2]: *** [src/CMakeFiles/ncnn.dir/build.make:1123：src/CMakeFiles/ncnn.dir/layer/loongarch/innerproduct_loongarch_lsx.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/Makefile2:92：src/CMakeFiles/ncnn.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

**Comment by cugxchen** [comment]
编译器bug，升级编译器，或者删除ncnn源码中 
src/layer/loongarch/innerproduct_loongarch.cpp     
src/layer/loongarch/cast_loongarch.cpp
这两文件，再重新编译；删除后loongarch64就没了，优先考虑升级编译器版本

**Comment by wzyforgit** [comment]
那个就是龙芯gcc下面的汇编器bug，最新版本已经修复了，并且最新版本编出来的可以在老版本上正常运行

**Comment by cugxchen** [comment]
问题已解决，感谢答复

**Comment by wilway** [comment]
请问gcc升级到什么版本？貌似只能找到8.3.0版本

**Comment by wzyforgit** [comment]
> 请问gcc升级到什么版本？貌似只能找到8.3.0版本

8.3.0的最新版本，龙芯那边发布的时候后面会拖一个小的版本号尾巴
