### ISSUE TITLE
extract 最后的blob出来的Mat是empty的

### ISSUE THREAD

**Issue by AllanChen** [Tencent/ncnn#472]
平台：iOS
直接用相机的数据作为输入源来跑，最后出来的extract mat 是空。失败在睇53 层
ret code 为-100
查阅资料说是初始化mat 失败？？？ 没有说失败的原因。
尝试过以下方法：
1： 重新初始化
2：强制换成另外一个

结果：都不行。
`
    const float norm_vals[3] = {1.0f / 255.0f, 1.0f / 255.0f, 1.0f / 255.0f};
    const float mean_vals[3] = {103.95f, 116.779f, 123.68f};   
    in.substract_mean_normalize(mean_vals, &normal_val);

    ncnn::Extractor ex = squeezenet.create_extractor();
    ex.set_light_mode(true);
    ex.set_num_threads(1);

    ex.input(net_param_id::BLOB_data, in);
    ncnn::Mat out;
    ex.extract(net_param_id::BLOB_fc5, out);`

out 是空的，进去的数据是rgb，和要求的数据是一样格式

**Comment by AllanChen** [comment]
@PipeBlack

**Comment by PipeBlack** [comment]
你看一下53层之前有没有输出？
你同样的代码在pc端跑一下，输入的话就填充全1或什么的，看一下输出输不是空的

**Comment by zhangscth** [comment]
请问楼主解决了吗，遇到了相同的问题
