### ISSUE TITLE
from .param .bin convert .id.h .mem.h, the size is bigger, 4 times 

### ISSUE THREAD

**Issue by zhangyu13141** [Tencent/ncnn#4720]
## model | 模型 | モデル
1. original model

## how to reproduce | 复现步骤 | 再現方法
1.
2.
3.

**Comment by nihui** [comment]
This is normal because the text representation is much larger than the binary, but this does not affect the final compiled binary size

It is recommended to use this method only for small models

**Comment by zhangyu13141** [comment]
the .mem.h is bigger than the .bin,how to reduce?

**Comment by nihui** [comment]
> the .mem.h is bigger than the .bin,how to reduce?

There is no need to reduce it, because the compiled binary size is the same as the bin file and will not become larger. It's just that mem.h is big, distribution is not needed, that's not a problem.
