### ISSUE TITLE
新版本VS旧版本的结果变的很差

### ISSUE THREAD

**Issue by zys1994** [Tencent/ncnn#4724]
## detail | 详细描述 | 詳細な説明
、、、
    _mean_val[0] =104.f;
    _mean_val[1] =117.f;
    _mean_val[2] =123.f;
    _norm_vals[0] =1.f;
    _norm_vals[1] =1.f;
    _norm_vals[2] =1.f;
     ncnn::Mat in_=ncnn::Mat::from_pixels(imageData_re.data, ncnn::Mat::PIXEL_BGR, width, height);
    in_.substract_mean_normalize(_mean_val,_norm_vals);
    ncnn::Extractor ex = retinaface->create_extractor();
     ex.input("input0", in_);
     ex.extract(）；
、、、
是不是新版本对不做归一化的输入有另外的处理？

**Comment by wzyforgit** [comment]
你把新旧两个版本输入的mat都打印出来对比一下？另外还可以看下两边的代码啥的，ncnn是开源的

**Comment by zys1994** [comment]
2022.11和2023.2打印输入一致，输出不一致

**Comment by nihui** [comment]
试试最新的20230517
