### ISSUE TITLE
the release 20180704 is slower than 20180427

### ISSUE THREAD

**Issue by 593581244** [Tencent/ncnn#473]
the release 20180704 is slower than 20180427

**Comment by nihui** [comment]
please attach your benchncnn result of these two release

**Comment by 593581244** [comment]
I have done a contrastive test using a detection network build by myself , the release 20180704 was 38ms which was slower than 18ms tested using the release 20180427, thread num is 1.

**Comment by graph** [comment]
I have a precompiled version of ncnn and don't know what version it is, and have noticed on some devices the newer versions of ncnn is slower. On pixel there is no speed difference. On Galaxy S8 it is slower. I don't know where I got the precompiled version that is faster, but it's incomptable with the latest android NDK.

**Comment by nihui** [comment]
You can try the latest ncnn code, with opt.use_packing_layout enabled, it should run faster
