### ISSUE TITLE
Unable to use Layer.load_model() in Python for custom layers

### ISSUE THREAD

**Issue by csukuangfj** [Tencent/ncnn#4735]
Reproducible using the latest master.

# Description
When registering a custom layer from Python and overriding
```python
def load_model(self, mb):
   m = mb.load(w, type)
```
the returned `m` is an empty `Mat`.

The commit https://github.com/Tencent/ncnn/pull/4732/commits/52605938e08f9f5f353d96ca96306a713ed60b9e
fixes the following error:
```
RuntimeError: return_value_policy = copy, but type ncnn::modelbinfromdatareader is non-copyable!
```

I am not familiar with the internals of Pybind11. 

https://github.com/pybind/pybind11/issues/1123#issuecomment-335397291
provides an alternative fix for the above error.

Even though the commit https://github.com/Tencent/ncnn/pull/4732/commits/52605938e08f9f5f353d96ca96306a713ed60b9e 
also fixes the above error, but subclasses of `ModelBin` are not copyable or assignable.
https://github.com/Tencent/ncnn/blob/903ec7c2c9417e1ee11cb667d2198cc3607458ed/src/modelbin.h#L70-L72

I am not sure why pybind11 requires a reference argument to be copyable.

# Possible fixes
As suggested by https://github.com/pybind/pybind11/issues/1123#issuecomment-335397291, change the reference to a pointer fixes the issue.

I suggest that we add an overload for
https://github.com/Tencent/ncnn/blob/903ec7c2c9417e1ee11cb667d2198cc3607458ed/src/layer.h#L49

```cpp
 int load_model(const ModelBin* mb) { return load_model(*mb); }
```

Also, we need to change
https://github.com/Tencent/ncnn/blob/903ec7c2c9417e1ee11cb667d2198cc3607458ed/src/net.cpp#L1748
to
```
 int lret = layer->load_model(&mb); 
```

Similarly, we need to change the Python binding code

By the way, we can remove the file
https://github.com/Tencent/ncnn/blob/master/python/src/pybind11_modelbin.h
and also 
https://github.com/Tencent/ncnn/blob/903ec7c2c9417e1ee11cb667d2198cc3607458ed/python/src/main.cpp#L152-L157

We are not going to inherit `ModelBin` in Python and there is no need to define a new class PyModelBin.
Furthermore, there is no need to wrap subclasses of `ModelBin` to Python.

**Comment by nihui** [comment]
please test if the fix works

https://github.com/Tencent/ncnn/pull/4737
