### ISSUE TITLE
arm平台下使用最新的ncnn库， net.opt.num_threads  设置为1，cpu占用率400% 

### ISSUE THREAD

**Issue by SunwalkerHub** [Tencent/ncnn#4750]
arm平台下使用最新的ncnn库， net.opt.num_threads  设置为1（ <= 4 时 ），cpu占用率400% 
设置为8时正常， cpu占用率为700+%。

**Comment by nihui** [comment]
在load_param前设置opt
另外，尝试跑benchncnn看看是否正常

**Comment by SunwalkerHub** [comment]
> 在load_param前设置opt 另外，尝试跑benchncnn看看是否正常

是在load_param前设置的opt。 
----------------------------------------
   
现在定位到了部分问题， 是  OPENMP 引起的。  已找到办法可以绕过问题， 但还不知道原因，怎么彻底解决这个问题。

方法1： 在cpu.cpp,  set_cpu_thread_affinity()  里：  
把 int num_threads = thread_affinity_mask.num_enabled(); 改成定值，比如2。(通过thread_affinity_mask.num_enabled() 返回的 是4)。 
改为定值2，此时效果， 当 net.opt.num_threads设置为1时，cpu占用率为200%
设置为>=2时，  cpu占用率为正常

方法2： 不定义 _OPENMP 宏

**Comment by SunwalkerHub** [comment]
问题定位到一行， cpu.cpp,  set_cpu_thread_affinity()  里
```cpp
int num_threads = thread_affinity_mask.num_enabled();
    // set affinity for each thread
    set_omp_num_threads(num_threads);     //  this
```
这一行会导致，程序使用线程数最少为 thread_affinity_mask.num_enabled() 的返回值。    
在arm平台上，一般有多个大核。 如果 net.opt.num_threads 设置为1， 也还是会用多个线程。 
不知道这里设计是什么原因。

**Comment by nihui** [comment]
是不是因为有其他操作导致的？
比如 copy_make_border resize_bilinear 这些工具函数，后面有 opt 参数，默认是全部大核心数量

**Comment by SunwalkerHub** [comment]
> 

应该不是， 因为如果我 把  cpu.cpp, set_cpu_thread_affinity() 里修改为这样
```cpp
nt num_threads = thread_affinity_mask.num_enabled();
    // set affinity for each thread
    set_omp_num_threads(8);     //  patch
```

cpu  会跑800%。  我用的开发板是rk3588， 有4个大核 4个小核

**Comment by SunwalkerHub** [comment]
> 是不是因为有其他操作导致的？ 比如 copy_make_border resize_bilinear 这些工具函数，后面有 opt 参数，默认是全部大核心数量

应该不是， 因为如果我 把  cpu.cpp, set_cpu_thread_affinity() 里修改为这样
```cpp
int num_threads = thread_affinity_mask.num_enabled();
    // set affinity for each thread
    set_omp_num_threads(8);     //  patch
```

cpu  就会跑800%。  我用的开发板是rk3588， 有4个大核 4个小核

**Comment by ncnnnnn** [comment]
能不能麻烦试一下用NCNNOMP SIMPLEOMP看看结果怎么样？

**Comment by SunwalkerHub** [comment]
问题已找到。  是项目中别处引用的程序，使用了openmp指令，并没有明确指定使用的线程数，OpenMP会根据系统的处理器数量和其他因素自动确定使用的线程数。ncnn库本身不会导致这个问题。
