### ISSUE TITLE
binaryop 什么都没执行，直接 return

### ISSUE THREAD

**Issue by tpoisonooo** [Tencent/ncnn#4752]
## error log | 日志或报错信息 | ログ
现象是结果 NaN， 每次运行值不一样。
根源在 https://github.com/Tencent/ncnn/blob/07c2cac0913a4bb2cdcc4feb3fd4185cd699dd47/src/layer/binaryop.cpp#L554

## context | 编译/运行环境 | バックグラウンド

1. 代码用最新的 commit-id 07c2cac0913a4bb2cdcc4feb3fd4185cd699dd47
2. 机器是 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz，执行 avx512 kernel
3. g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

## how to reproduce | 复现步骤 | 再現方法
1. 下载这个压缩包解压，里面有 param/bin/测试图片和测试脚本  https://drive.google.com/file/d/1s84QlvwYx9ymUAmXSSgxDN17I0qHiDeM/view?usp=sharing
2. onnx 打开 param， 看 ExpandDims 和它后面的 BinaryOp
![图片](https://github.com/Tencent/ncnn/assets/7872421/26d7d22f-e71b-4164-b553-9b3e789aaa00)
3. 删掉  src/layer/x86，编译运行，排除 kernel 写错的可能，方便 debug。
4. gdb 先 break `expanddims.cpp:forward`，再 break  `binaryop.cpp:555`，打印输入
```bash
(gdb) p bottom_blobs[0]
$8 = {data = 0x7fffbd4de040, refcount = 0x7fffbd4e0240, elemsize = 4, elempack = 1, 
  allocator = 0x555555da8560, dims = 3, w = 128, h = 1, d = 1, c = 17, cstep = 128}
(gdb) p bottom_blobs[1]
$9 = {data = 0x7fffbd6c6040, refcount = 0x7fffbd6c6440, elemsize = 4, elempack = 1, 
  allocator = 0x555555da8560, dims = 3, w = 128, h = 2, d = 1, c = 1, cstep = 256}
```
6. 一行行 next，会发现 kernel 什么都没执行，return 0 了。 所以 top_blob 里是乱码
## more | 其他 | その他

torch 里想做这件事：
[1,17,1,128]  * [1,1,2,128]  -> [1,17,2,128]
torch 输入 base = [1,17,128]，所以 torch 写了  base.unsqueeze(2) * weight 

转到了 ncnn 里，
base.unsqueeze(2)  结果是 [w=128 h=1 d=1 c=17 dims=3]
base.unsqueeze(2) * weight 得到的是  [w=128 h=1 d=1 c=17 dims=3]， 预期的 h 应该是 2
导致后面不对。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4809

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/9022b7162a851f5deae0d2e6e5ee5e89a4813212
