### ISSUE TITLE
onnx模型转ncnn模型输出的shape不一样

### ISSUE THREAD

**Issue by liguiyuan** [Tencent/ncnn#4753]
大佬您好，我在onnx模型转ncnn模型时，onnx模型是经过onnxsim的，转换也没有出现错误提示。但是ncnn模型的输出尺寸和onnx的输出尺寸不一致。

如下图所示，右边的为onnx模型，分类模型softmax的输出为1x5，正常。左边的为转换之后的ncnn模型，模型的输出却为 out.c=1, out.h=8, out.w=5，请问这是什么原因呢

![选区_999(1549)](https://github.com/Tencent/ncnn/assets/25164335/8435e846-01d9-4d98-8533-056af23dcf0b)

![选区_999(1551)](https://github.com/Tencent/ncnn/assets/25164335/354e60c3-549a-4dc4-b803-4c6f8d27509e)

**Comment by liguiyuan** [comment]
经过排查发现是GlobalAveragePool层的问题，在我原始模型中用的是AdaptiveAvgPool2D，转换为onnx的时候貌似onnx不支持AdaptiveAvgPool2D，就自动变为了GlobalAveragePool（神奇的是我用onnx模型推理的结果也是正确的），进而导致ncnn输出的shape不对。请问一下有什么修改的方法吗？ 谢谢

**Comment by wzyforgit** [comment]
你原来是用啥训练的啊？如果是pytorch的话，可以用pnnx一步到位，免去onnx的问题

**Comment by liguiyuan** [comment]
> 

谢谢回复，我用的是paddle框架训练的，好像不能转为pnnx，我研究一下有没有别的解决办法。我之前的mobilenetv3 模型也有AdaptiveAvgPool2D，转为onnx后也是自动变为GlobalAveragePool，但是继续把onnx转ncnn没出现现在这个问题，好奇怪

**Comment by liguiyuan** [comment]
> 你原来是用啥训练的啊？如果是pytorch的话，可以用pnnx一步到位，免去onnx的问题

谢谢回复，我用的是paddle框架训练的，好像不能转为pnnx，我研究一下有没有别的解决办法。我之前的mobilenetv3 模型也有AdaptiveAvgPool2D，转为onnx后也是自动变为GlobalAveragePool，但是继续把onnx转ncnn没出现现在这个问题，好奇怪

**Comment by wzyforgit** [comment]
> > 你原来是用啥训练的啊？如果是pytorch的话，可以用pnnx一步到位，免去onnx的问题
> 
> 谢谢回复，我用的是paddle框架训练的，好像不能转为pnnx，我研究一下有没有别的解决办法。我之前的mobilenetv3 模型也有AdaptiveAvgPool2D，转为onnx后也是自动变为GlobalAveragePool，但是继续把onnx转ncnn没出现现在这个问题，好奇怪

唔。。。现在一些已有的成功案例（比如paddle ocr）是通过 paddle -> pytorch -> torchscipt -> pnnx -> ncnn 这样转换的，走ONNX路线确实会遇到很多奇怪的问题。。。

**Comment by liguiyuan** [comment]
大佬我再想请教一下，前面的没问题了，现在问题出现在最后面的FC层上，第一个图为onnx模型的gemm输出之后shape和推理结果都正常；第二个图是转换后的ncnn模型，正常来说FC层，转换为ncnn后层类型会变成InnerProduct，这里却变成了gemm，而且输出的shape也不正常，我查看了onnx2ncnn源码是由于transB == 0造成的，如果是transB == 1才会输出InnerProduct。reshape c层输出为(c,h,w顺序):1x1x200，然后经过gemm层正常的情况下，输出shape为：1x1x5的，这里却输出了：1x8x5。需要怎么修改param文件才能得到正确的结果。
[model.zip](https://github.com/Tencent/ncnn/files/11611272/model.zip)


![1685525167(1)](https://github.com/Tencent/ncnn/assets/25164335/258dd80c-18c0-4285-8059-27d3844fa06a)
![企业微信截图_16855263385386](https://github.com/Tencent/ncnn/assets/25164335/f864c5fb-5ae1-444b-9d3d-c1d9e9c41565)

**Comment by liguiyuan** [comment]
已经解决此问题，是onnx2ncnn代码造成，缺少考虑全连接层 transB = 0的判断。代码中Gemm矩阵乘法计算时，（alpha == 1.f && beta == 1.f && transA == 0 && transB == 1）为True时才会把它当做全连接层（FC层）执行InnerProduct操作，否则执行Gemm操作。而我的模型中的FC 层中 transB = 0，即 B矩阵不需要转置操作，在onnx2ncnn代码中就会跑Gemm的流程，导致计算出错。 
举例：
FC层的输入矩阵A维度为 [1, 200], B(weights) 为[200, 5] , C(bias) 为[5]，此时 transB = 0，即B矩阵不用转置，是可以直接计算 A * B + C 的，输出的矩阵维度为：[1, 5] 结果正确

当 transB = 1时，输出的结果是 A * B.T + C ，[1, 200] * [5, 200] + [5] 是无法计算的，导致输出的维度不对。

**Comment by hua1024** [comment]
你好，最后怎么解决的

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
