### ISSUE TITLE
存在多个GPU的情况下，如何指定使用某个GPU

### ISSUE THREAD

**Issue by tututu11** [Tencent/ncnn#4757]
## detail | 详细描述 | 詳細な説明
存在多个GPU的情况下，如何指定使用某个GPU。现在默认使用的都是GPU 0

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/vulkan-notes#select-gpu-device

**Comment by tututu11** [comment]
> https://github.com/Tencent/ncnn/wiki/vulkan-notes#select-gpu-device

多谢大佬，找到了
