### ISSUE TITLE
请问NCNN的归一化怎么处理？

### ISSUE THREAD

**Issue by ouxiand** [Tencent/ncnn#4762]
## detail | 详细描述 | 詳細な説明
请问NCNN的归一化怎么处理？
Python代码：
img = cv2.imread(p2)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (128, 256))
img = img.astype(np.float32)
img = (img / 255.0 - [0.485, 0.456, 0.406]) / [0.229, 0.224, 0.225]  # 图像归一化

# 转换输入数据为ONNX模型的输入格式
input_data = img.transpose((2, 0, 1)).reshape(1, 3, 256, 128)
input_data = input_data.astype(np.float32)

NCNN：
const float m_mean_value[3] = { 0.485, 0.456, 0.406};
const float m_norm_value[3] = { 0.229, 0.224, 0.225};
ncnn_img = ncnn::Mat::from_pixels_resize(rgb.data, ncnn::Mat::PIXEL_BGR2RGB, img_w,img_h, input_width, input_height);
ncnn_img.substract_mean_normalize(mean_vals, norm_vals);

结果不对，应该少了一个/255,  请问如何处理？求指导

**Comment by wzyforgit** [comment]
ncnn是(x - mean) * norm，你在草稿纸上推导一下啊

**Comment by ouxiand** [comment]
@wzyforgit   ncnn是(x - mean) * norm    ==>要改成   (x/255 - mean) * norm,   知道要怎么改不？

**Comment by wzyforgit** [comment]
> @wzyforgit ncnn是(x - mean) * norm ==>要改成 (x/255 - mean) * norm, 知道要怎么改不？

我觉得这最多是个初中数学问题。。。建议学完大学的高数、线性代数、概率论与数理统计课程后再来玩这些东西

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
