### ISSUE TITLE
调用ncnn2table 出现FATAL ERROR! unlocked pool allocator destroyed too early

### ISSUE THREAD

**Issue by reyuri** [Tencent/ncnn#4787]
模型为百度ppmattingv2_stdc1_human_512，对应的ncnn float模型 测试结果正常，但量化时，
调用ncnn2table时，出现出现FATAL ERROR! unlocked pool allocator destroyed too early，导致量化失败。
ncnn版本为ncnn-20230517，请问，出现这种错误的可能原因是什么呢？谢谢

**Comment by SEMLLYCAT** [comment]
您好，请问这个问题怎么解决的！
