### ISSUE TITLE
是否支持将transformers库的模型转换为ncnn

### ISSUE THREAD

**Issue by SchweitzerGAO** [Tencent/ncnn#4788]
## detail | 详细描述 | 詳細な説明
大佬们好，我最近在做huggingface transformers 模型在移动端推理，请问是否支持此类模型转换为ncnn呢？

**Comment by wzyforgit** [comment]
paddle ocr v3里面的transformer是可以的

**Comment by SchweitzerGAO** [comment]
好的，谢谢！

**Comment by nihui** [comment]
可以使用 pnnx 转换模型为 ncnn

**Comment by SchweitzerGAO** [comment]
> 可以使用 pnnx 转换模型为 ncnn

好的，谢谢！

**Comment by SchweitzerGAO** [comment]
> Hi! We have updated the great OCR sample project and Android project, welcome to refer to it
> 
> https://github.com/Tencent/ncnn/blob/master/examples/ppocrv5.cpp https://github.com/nihui/ncnn-android-ppocrv5

Thanks! will refer to this when in need
