### ISSUE TITLE
ncnn::get_gpu_info这个函数怎么使用，找不到任何例子

### ISSUE THREAD

**Issue by tututu11** [Tencent/ncnn#4789]
ncnn::get_gpu_info这个函数怎么使用，找不到任何例子，能有大佬可说明一下吗

**Comment by nihui** [comment]
获取gpu信息，主要有 vulkan 设备的属性和功能支持情况
https://github.com/Tencent/ncnn/blob/b8cf8cb73e7be5fc8be4b558d53efefd9b99b8a8/src/gpu.h#L94

**Comment by nihui** [comment]
如有其他问题，可以加qq群交流，群号见readme
