### ISSUE TITLE
ncnn+ vulkan slightly changes values

### ISSUE THREAD

**Issue by magicse** [Tencent/ncnn#4793]
This problem only with VULKAN enabled.
## how to reproduce | 复现步骤 | 再現方法
1. Create simple ncnn Test Mat with any shapes and fill it with values for example 142/255.0 = 0.556863 rounded value 0.5569
2. Create simple model with 2 layers
Input                    in0                      0 1 in0
Split                    splitncnn_0          1 2 in0 1 2 

3.  applly Mat to to model and extract Mat from split layer
ex.input("in0", Test);
ex.extract("1", out);
4. Check values from "out" and all values will be slightly changed. Instead get back 0.5569 we get 0.5566

**Comment by nihui** [comment]
It may help to disable fp16
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#disable-fp16

**Comment by magicse** [comment]
Yes you are right this is due fp16 prescision.
