### ISSUE TITLE
img2col计算卷积对比直接计算卷积是否会高效一点？

### ISSUE THREAD

**Issue by aitaoquanyi** [Tencent/ncnn#48]
作者你好：
        你的工作非常棒，但是在读你代码时，发现卷积计算方式为传统方式，你也提到直接计算卷积会节省内存，我想请教一下，如果按照img2col展开为矩阵乘法的方式是否会计算效率更高一些？谢谢！

**Comment by zsffq999** [comment]
哪个卷积类是基类，针对android的卷积派生类是用汇编写的

**Comment by ccJia** [comment]
@aitaoquanyi 在一些传统的模型里面IM2COL+GEMM的效果还不错( 非separate convolution的情景)，但是在新的 像 mobilenet这样的网络里面，IM2COL会占用掉大多数的时间，甚至大于GEMM的时间，感觉还是要根据实际的网络来定的。

**Comment by sunjunlishi** [comment]
是的img2col的话，速度会提高一倍多

**Comment by interqhq** [comment]
@ccJia 赞同你的观点，im2col也是要消耗时间的，要根据实际的特点来采用合适的方法

**Comment by nihui** [comment]
最新代码已有 im2col + gemm 的实现
