### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by zhenjiaguo** [Tencent/ncnn#4800]
我在运行 PNNX.exe 转换后的 yolov8n_pnnx.py 文件时，遇到一个错误：

## error log | 日志或报错信息 | ログ
```
E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jia\\AppData\\Local\\Temp\\tmp8ynogw65'

yolov8n_pnnx.py:282: PermissionError
```
## context | 编译/运行环境 | バックグラウンド
系统：windows11

## how to reproduce | 复现步骤 | 再現方法
1. 在 win11 系统上运行pnnx 转换生成后的 `*_pnnx.py` 文件

## more | 其他 | その他

经研究发现是该文件的 fd 没有正常关闭之前就被删除，所以程序报错了。`tempfile.mkstemp()`会返回 `(fd, name)`，在删除tmp文件之前应该使用 `os.close(fd)` 才不会报错。

而且我觉得有更好的写法，详见PR。

**Comment by nihui** [comment]
感谢反馈和修复！
