### ISSUE TITLE
BinaryOp not working correctly if one axis has dimension 1

### ISSUE THREAD

**Issue by serwansj** [Tencent/ncnn#4803]
I am exporting a PyTorch model to NCNN using PNNX. Following operation is then created in the `ncnn.param` file:

```
BinaryOp                mul_0                    2 1 51 42 52 0=2
```

The input 51 is an intermediate result from previous computations (shape `8 x 32 x 900 x 4`) while the input 42 is a `MemoryData` variable which was exported as follows:
```
MemoryData               pnnx_fold_318            0 1 42 0=4 1=900 11=1 2=8
```
The shape of this variable is consistent with the shape in PyTorch, namely `8 x 1 x 900 x 4`. During the multiplication operation the second axis should be broadcasted and then it should return the element-wise multiplication result.

However, I am experiencing the following issue and I am wondering whether it is a bug in the `BinaryOp` operation:
In the forward method of `BinaryOp` none of the if-statements is being triggered, i.e. the operation simply returns the input 51. After looking into it, it seems to me that it should trigger the following if-statement:
```cpp
if ((B.dims < A.dims) || (A.dims == 2 && B.w == 1 && B.h == A.h) || (A.dims == 3 && B.w == 1 && B.h == 1 && B.c == A.c) || (A.dims == 3 && B.w == 1 && B.h == A.h && B.c == A.c) || (A.dims == 4 && B.w == 1 && B.h == 1 && B.d == 1 && B.c == A.c) || (A.dims == 4 && B.w == 1 && B.h == 1 && B.d == A.d && B.c == A.c) || (A.dims == 4 && B.w == 1 && B.h == A.h && B.d == A.d && B.c == A.c))
    {
        return binary_op_broadcast_inner(A, B, top_blob, op_type_r, opt);
    }
```
It is not being triggered because the dims of both inputs are the same, namely 4, but I think the dim of the second input should instead be 3 because one axis is of size 1.

I went ahead and changed the exported MemoryData line in the `ncnn.param` file to:
```
MemoryData               pnnx_fold_318            0 1 42 0=4 1=900 2=8
```
In this case the tensor is loaded with `dim=3` and the correct shape. After this change the first couple of values in the result are correct, however, values towards the end are wrong. I assume this is because the dims are now 3 and the data is not being loaded correctly anymore.

Would appreciate any help with this and if you need me to clarify the problem more, please let me know.

**Comment by serwansj** [comment]
I was actually wrong in my initial post, it should trigger the following if-statement

```cpp
// broadcast B for outer axis
    if ((A.dims == 2 && B.w == A.w && B.h == 1) || (A.dims == 3 && B.w == A.w && B.h == 1 && B.c == 1) || (A.dims == 3 && B.w == A.w && B.h == A.h && B.c == 1) || (A.dims == 4 && B.w == A.w && B.h == 1 && B.d == 1 && B.c == 1) || (A.dims == 4 && B.w == A.w && B.h == A.h && B.d == 1 && B.c == 1) || (A.dims == 4 && B.w == A.w && B.h == A.h && B.d == A.d && B.c == 1))
    {
        return binary_op_broadcast_outer(A, B, top_blob, op_type_r, opt);
    }
```

I adjusted the code so it would trigger this part as well for
```
A.dims == 4 && B.w == A.w && B.h == A.h && B.d == A.d && B.d == 1
```
and it returns the correct result.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4809

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/9022b7162a851f5deae0d2e6e5ee5e89a4813212
