### ISSUE TITLE
卷积运算结果不稳定

### ISSUE THREAD

**Issue by kobe2000** [Tencent/ncnn#481]
Hi
我在使用ncnn的过程中发现多次循环执行网络结果不稳定，经过debug，定位到卷积Convolution操作输出出现变化

至少有一个Convolution配置如下：
输入尺寸为24x32x32(CHW)
输出尺寸为144x32x32
卷积核1x1
strides 1x1
padding 0

手动将输出的mat全置为0后，输出稳定

版本：20c0794b365cc70e3540bba6ee94b5a5600ecb8d
windows / NDK r17b
cmake -DCMAKE_TOOLCHAIN_FILE=d:/android-ndk-r17b/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-16 -G "NMake Makefiles" ..
with openmp

**Comment by kobe2000** [comment]
今天发现这个和openmp有关，当我设置OMP_NUM_THREADS=1的时候结果是稳定的，随着线程数增加，出现不稳定的概率会增大

**Comment by zhangyunming** [comment]
你好，请问你是在哪里设置的这个OMP_NUM_THREADS=1，我现在在跑模型的时候速度非常不稳定

**Comment by z13974509906** [comment]
@kobe2000 设置为1的时候结果也会出问题。。。有没有什么好的解决办法。

**Comment by nihui** [comment]
最新代码修复了诸多运算问题，建议更新最新代码，如有问题可以 reopen issue
