### ISSUE TITLE
Space to Depth not supported

### ISSUE THREAD

**Issue by SawantMyelin** [Tencent/ncnn#4814]
## error log | 日志或报错信息 | ログ
layer SpaceToDepth not exists or registered

## model | 模型 | モデル
1. original model
its a 4 layer model with space to depth and a depth to space in the end, but when i convert it , it says space do depth is not supported.
## how to reproduce | 复现步骤 | 再現方法
1.
2.
3.

**Comment by nihui** [comment]
use pytorch nn.PixelShuffle and nn.PixelUnshuffle module and convert model with pnnx
