### ISSUE TITLE
问一个简单的问题，ncnn的vulkan backend是打包到ncnn代码库里的，还是用手机自带的？

### ISSUE THREAD

**Issue by ldfandian** [Tencent/ncnn#4815]
rt

**Comment by wzyforgit** [comment]
你这说的是vulkan库还是GLSLang？
vulkan库用系统自带的，GLSLang用ncnn内部的

**Comment by ldfandian** [comment]
> 你这说的是vulkan库还是GLSLang？
> vulkan库用系统自带的，GLSLang用ncnn内部的

谢谢~

**Comment by nihui** [comment]
android系统自带 vulkan驱动
ios系统需要带上moltenvk编译链接
