### ISSUE TITLE
set_vulkan_compute 与 use_vulkan_compute

### ISSUE THREAD

**Issue by sunjian2015** [Tencent/ncnn#4825]
ex.set_vulkan_compute(use_gpu); 与 net.opt.use_vulkan_compute(use_gpu) 这两个有什么区别吗？必须都写上吗？

**Comment by nihui** [comment]
load_param前设置opt即可启用vulkan
ex 只作用于当前 ex，可以在启用vulkan的情况下临时禁用 gpu

**Comment by sunjian2015** [comment]
> load_param前设置opt即可启用vulkan ex 只作用于当前 ex，可以在启用vulkan的情况下临时禁用 gpu

明白了，感谢大佬回复😀
