### ISSUE TITLE
use_image_storage和use_tensor_storage打开后应该如何使用？

### ISSUE THREAD

**Issue by tumuyan** [Tencent/ncnn#4830]
## detail | 详细描述 | 詳細な説明
我在option.h中看到如下内容：
```
    // turn on for adreno
    bool use_image_storage;
    bool use_tensor_storage;
```
请问是给option设置这两个开关，就能够对骁龙设备自动优化嘛？还是需要做其他的操作？
与打开 use_fp16_storage 和 use_int8_storage相比，这2个开关能产生的优化效果相当明显还是几乎可以忽略？

**Comment by nihui** [comment]
image_storage 在老的 adreno 型号上能加快读数据效率，模型大还会爆image最大限制，默认是关掉的，老adreno可以尝试下
tensor_storage 是为2026年新vulkan扩展预留的开关，目前无作用

**Comment by tumuyan** [comment]
感谢说明
