### ISSUE TITLE
pnnx: torch traced 模型转ncnn 生成expand_as节点，无法加载

### ISSUE THREAD

**Issue by znsoftm** [Tencent/ncnn#4838]
生成 expand_as节点，无法加载。

inputshape =[1,3,320,32]

## how to reproduce | 复现步骤 | 再現方法
1.   pnnx   traced_language.pt inputshape=[1,3,320,32]
2.  打开 traced_language.ncnn.param 查看
3.

## more | 其他 | その他
[traced_language.zip](https://github.com/Tencent/ncnn/files/11946384/traced_language.zip)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4850

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/810bfbac6ed4dc8834b3c30d68ee408aae806e3f
