### ISSUE TITLE
Build aarch64 library faild when NCNN_PYTHON=ON

### ISSUE THREAD

**Issue by wsora** [Tencent/ncnn#4840]
## error log | 日志或报错信息 | ログ
[ 98%] Building CXX object python/CMakeFiles/pyncnn.dir/src/main.cpp.o
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/common.h:208:
In file included from /home/wgd/anaconda3/envs/mm2/include/python3.8/Python.h:44:
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:64:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:118:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:130:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:144:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:169:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:181:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:203:1: error: expected function body after function declarator
__THROW;
^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:14:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:40:19: error: use of typeid requires -frtti
        return {{&typeid(Ts)..., nullptr}};
                  ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:39:76: error: no return statement in constexpr function
    static constexpr std::array<const std::type_info *, sizeof...(Ts) + 1> types() {
                                                                           ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:154:38: error: no matching function for call to 'const_name'
    return const_name("{") + descr + const_name("}");
                                     ^~~~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:60:24: note: candidate template ignored: substitution failure [with N = 2]
constexpr descr<N - 1> const_name(char const (&text)[N]) {
                       ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:98:26: note: candidate function template not viable: requires 0 arguments, but 1 was provided
constexpr descr<1, Type> const_name() {
                         ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:93:16: note: candidate function template not viable: requires 0 arguments, but 1 was provided
auto constexpr const_name() -> remove_cv_t<decltype(int_to_str<Size / 10, Size % 10>::digits)> {
               ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:88:31: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, T2> const_name(const T1 &, const T2 &d) {
                              ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:84:30: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, T1> const_name(const T1 &d, const T2 &) {
                             ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:79:42: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, descr<N2 - 1>> const_name(char const (&)[N1], char const (&text2)[N2]) {
                                         ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:75:41: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, descr<N1 - 1>> const_name(char const (&text1)[N1], char const (&)[N2]) {
                                        ^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:15:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:12:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../pytypes.h:748:44: error: use of typeid requires -frtti
    return detail::isinstance_generic(obj, typeid(T));
                                           ^
[ 99%] Linking CXX executable benchncnn
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:15:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:15:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/internals.h:349:31: error: use of dynamic_cast requires -frtti
        if (const auto *nep = dynamic_cast<const std::nested_exception *>(std::addressof(e))) {
                              ^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:15:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:16:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/typeid.h:62:34: error: use of typeid requires -frtti
    return detail::clean_type_id(typeid(T).name());
                                 ^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:15:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:894:23: error: use of typeid requires -frtti
        type = src ? &typeid(*src) : nullptr;
                      ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:911:43: error: use of typeid requires -frtti
    type_caster_base() : type_caster_base(typeid(type)) {}
                                          ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:930:33: error: use of typeid requires -frtti
        const auto &cast_type = typeid(itype);
                                ^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:253:5: error: constexpr variable 'name' must be initialized by a constant expression
    PYBIND11_TYPE_CASTER(T, const_name("None"));
    ^                       ~~~~~~~~~~~~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:87:27: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                          ^      ~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:253:5: error: constexpr variable 'name' must be initialized by a constant expression
    PYBIND11_TYPE_CASTER(T, const_name("None"));
    ^                       ~~~~~~~~~~~~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:87:27: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                          ^      ~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:257:39: note: in instantiation of template class 'pybind11::detail::void_caster<pybind11::detail::void_type>' requested here
class type_caster<void_type> : public void_caster<void_type> {};
                                      ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:300:27: error: constexpr variable 'name' must be initialized by a constant expression
    static constexpr auto name = const_name("capsule");
                          ^      ~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
[ 99%] Built target benchncnn
20 errors generated.
make[2]: *** [python/CMakeFiles/pyncnn.dir/build.make:76：python/CMakeFiles/pyncnn.dir/src/main.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:502：python/CMakeFiles/pyncnn.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

## context | 编译/运行环境 | バックグラウンド
ubuntu20.04
ncnn 20230517
g++ 9.4.0
gcc 9.4.0

## how to reproduce | 复现步骤 | 再現方法
Follow the wiki "how to build, Build for Android, Build aarch64 library"
1. git clone https://github.com/Tencent/ncnn.git
2. cd ncnn
3. git checkout -b 20230517
4. git submodule update --init
5. export ANDROID_NDK=<your-ndk-root-path>
6. mkdir -p build-android-aarch64
7. cd build-android-aarch64
8. cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=False -DNCNN_PYTHON=ON ..
9. make -j4

then error occurred.

**Comment by wzyforgit** [comment]
Try to set your cmake option: NCNN_DISABLE_RTTI=OFF NCNN_DISABLE_EXCEPTION=OFF

**Comment by wsora** [comment]
> Try to set your cmake option: NCNN_DISABLE_RTTI=OFF NCNN_DISABLE_EXCEPTION=OFF
I try it, and got new error.

error log:
[ 98%] Built target ncnn
[ 98%] Building CXX object benchmark/CMakeFiles/benchncnn.dir/benchncnn.cpp.o
[ 98%] Building CXX object python/CMakeFiles/pyncnn.dir/src/main.cpp.o
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/common.h:208:
In file included from /home/wgd/anaconda3/envs/mm2/include/python3.8/Python.h:44:
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:64:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:118:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:130:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:144:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:169:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:181:1: error: expected function body after function declarator
__THROW;
^
/home/wgd/anaconda3/envs/mm2/include/python3.8/crypt.h:203:1: error: expected function body after function declarator
__THROW;
^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:14:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:40:19: error: use of typeid requires -frtti
        return {{&typeid(Ts)..., nullptr}};
                  ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:39:76: error: no return statement in constexpr function
    static constexpr std::array<const std::type_info *, sizeof...(Ts) + 1> types() {
                                                                           ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:154:38: error: no matching function for call to 'const_name'
    return const_name("{") + descr + const_name("}");
                                     ^~~~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:60:24: note: candidate template ignored: substitution failure [with N = 2]
constexpr descr<N - 1> const_name(char const (&text)[N]) {
                       ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:98:26: note: candidate function template not viable: requires 0 arguments, but 1 was provided
constexpr descr<1, Type> const_name() {
                         ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:93:16: note: candidate function template not viable: requires 0 arguments, but 1 was provided
auto constexpr const_name() -> remove_cv_t<decltype(int_to_str<Size / 10, Size % 10>::digits)> {
               ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:88:31: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, T2> const_name(const T1 &, const T2 &d) {
                              ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:84:30: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, T1> const_name(const T1 &d, const T2 &) {
                             ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:79:42: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<!B, descr<N2 - 1>> const_name(char const (&)[N1], char const (&text2)[N2]) {
                                         ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/descr.h:75:41: note: candidate function template not viable: requires 2 arguments, but 1 was provided
constexpr enable_if_t<B, descr<N1 - 1>> const_name(char const (&text1)[N1], char const (&)[N2]) {
                                        ^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:15:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:12:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../pytypes.h:748:44: error: use of typeid requires -frtti
    return detail::isinstance_generic(obj, typeid(T));
                                           ^
[ 99%] Linking CXX executable benchncnn
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:15:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:15:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/internals.h:349:31: error: use of dynamic_cast requires -frtti
        if (const auto *nep = dynamic_cast<const std::nested_exception *>(std::addressof(e))) {
                              ^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:15:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:16:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/typeid.h:62:34: error: use of typeid requires -frtti
    return detail::clean_type_id(typeid(T).name());
                                 ^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:15:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:894:23: error: use of typeid requires -frtti
        type = src ? &typeid(*src) : nullptr;
                      ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:911:43: error: use of typeid requires -frtti
    type_caster_base() : type_caster_base(typeid(type)) {}
                                          ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/type_caster_base.h:930:33: error: use of typeid requires -frtti
        const auto &cast_type = typeid(itype);
                                ^
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/src/main.cpp:16:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/pybind11.h:13:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/class.h:12:
In file included from /mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/detail/../attr.h:14:
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:253:5: error: constexpr variable 'name' must be initialized by a constant expression
    PYBIND11_TYPE_CASTER(T, const_name("None"));
    ^                       ~~~~~~~~~~~~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:87:27: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                          ^      ~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:253:5: error: constexpr variable 'name' must be initialized by a constant expression
    PYBIND11_TYPE_CASTER(T, const_name("None"));
    ^                       ~~~~~~~~~~~~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:87:27: note: expanded from macro 'PYBIND11_TYPE_CASTER'
    static constexpr auto name = py_name;                                                         \
                          ^      ~~~~~~~
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:257:39: note: in instantiation of template class 'pybind11::detail::void_caster<pybind11::detail::void_type>' requested here
class type_caster<void_type> : public void_caster<void_type> {};
                                      ^
/mnt/share/wgd/mmlab2.0/other/ncnn/python/pybind11/include/pybind11/cast.h:300:27: error: constexpr variable 'name' must be initialized by a constant expression
    static constexpr auto name = const_name("capsule");
                          ^      ~~~~~~~~~~~~~~~~~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
[ 99%] Built target benchncnn
20 errors generated.
make[2]: *** [python/CMakeFiles/pyncnn.dir/build.make:76：python/CMakeFiles/pyncnn.dir/src/main.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:502：python/CMakeFiles/pyncnn.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/6647396667426405cee4da8da79f723148f60dd5
