### ISSUE TITLE
关于项目中使用release的ncnn包时遇到的问题。

### ISSUE THREAD

**Issue by shihuai** [Tencent/ncnn#4844]
## detail | 详细描述 | 詳細な説明
小白问一个简单问题，以ncnn-20230517-macos-vulkan为例，在项目中使用这个release包时候，这个包里面是自带了vulkan，还是使用自己安装好的vulkan？

**Comment by wzyforgit** [comment]
肯定是用本地安装的，它里面只是说编的时候链接了vulkan库并激活了相关功能而已

**Comment by shihuai** [comment]
好的，了解，谢谢了！
