### ISSUE TITLE
ncnn-20230517-windows-vs2017-shared版本打开vulkan，在gemm操作之后输出结果对比20230223版本不一致

### ISSUE THREAD

**Issue by WenJUST** [Tencent/ncnn#4848]
## error log | 日志或报错信息 | ログ
ncnn-20230517-windows-vs2017-shared 和 ncnn-20230223-windows-vs2017-shared中的ncnn.dll ,加载rtmpose网络模型，打开vulkan,执行最后一个gemm操作时，输出特征图大小一致但是结果不一致，其中20230223结果是正确的。
![image](https://github.com/Tencent/ncnn/assets/38709966/78b5d961-590c-424f-9ca8-ebf37310853e)
![image](https://github.com/Tencent/ncnn/assets/38709966/eb9dd3d5-b9f1-4fa3-822e-d813b6b8b08f)
## context | 编译/运行环境 | バックグラウンド
win11 vs2017 Release-64/86
## how to reproduce | 复现步骤 | 再現方法
测试图片，测试源码，测试模型都在压缩包中
[gemm-vulkan-ERROR.zip](https://github.com/Tencent/ncnn/files/11999858/gemm-vulkan-ERROR.zip)

**Comment by kekxv** [comment]
测试一下是否是和这个一样的问题？ https://github.com/Tencent/ncnn/issues/4843 ？
影响提交为：

结果错误：https://github.com/Tencent/ncnn/commit/6987efd9509b33dac4be30deb0beb74f48d7db2b
结果正确：https://github.com/Tencent/ncnn/commit/693535afc17fb23e8c78eadeffa65e648b2c4a3e

**Comment by WenJUST** [comment]
我的应该就是 gemm_vulkan.cpp这里出的问题，我改了下第207行使我的这个模型最后一个gemm不进入”broadcast_type_C = 3;“就好了,因为本来就是正常的17x17 * 17x512的矩阵乘法不需要broadcast（不确定 ”broadcast_type_C = 3;“是不是要进行某种broadcast）
![image](https://github.com/Tencent/ncnn/assets/38709966/753bf653-ba0f-4575-aff7-0032b4b0ab4c)
