### ISSUE TITLE
W/ncnn: layer aten::max not exists or registered

### ISSUE THREAD

**Issue by lewis-v** [Tencent/ncnn#4858]
## error log | 日志或报错信息 | ログ
W/ncnn: layer aten::max not exists or registered

## model | 模型 | モデル
1. llama model

## how to reproduce | 复现步骤 | 再現方法
目前不支持aten::max？
<img width="927" alt="image" src="https://github.com/Tencent/ncnn/assets/31053777/ca12c104-3ece-415d-a054-bee5dd6edf80">

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4944

**Comment by nihui** [comment]
已更新，会转换到 binaryop max
