### ISSUE TITLE
does anyone successfully run mobilefacenet with ncnn on android armv7?

### ISSUE THREAD

**Issue by yc-huang** [Tencent/ncnn#486]
there's no errors when converting the mxnet model, but at runtime it will crash with SIGSEGV when get output from blob 171 or 170 (layer fc1 or pre_fc1); but if changed to get output of blob 169(layer conv_6dw7_7_batchnorm) it seems to work withot errors.

you might get the mxnet checkpoint from:
https://pan.baidu.com/s/1If28BkHde4fiuweJrbicVA

**Comment by simon-rob** [comment]
I haven't looked at the code... but I suspect it is a bug with the converter as pre_fc1 and fc1 share the same weights. I am not sure if the converter supports shared weights.

**Comment by yc-huang** [comment]
looks like any mxnet network contains FullyConnected layer might have similar issue. 
I tried with a simple lenet, which could reproduce this: you can't get output from any layer after the flatten layer...
[lenet_mnist.tar.gz](https://github.com/Tencent/ncnn/files/2229278/lenet_mnist.tar.gz)

Haven't tried similar network trained on other framework yet...
@nihui do you have any suggestion on this? Thanks...

**Comment by yc-huang** [comment]
This was caused by over-sized input. Mobilefacenet expect input size of 112x112x3, so crop input image to this size will work, otherwise it might encounter errors.
