### ISSUE TITLE
pnnx 报错 terminate called after throwing an instance of 'c10::Error'   what():  Expected Tensor but got None

### ISSUE THREAD

**Issue by jcyao** [Tencent/ncnn#4867]
############# pass_level1
terminate called after throwing an instance of 'c10::Error'
  what():  Expected Tensor but got None
Exception raised from reportToTensorTypeError at ../aten/src/ATen/core/ivalue.cpp:950 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f0ae6e63d77 in /data/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f0ae6e2dabb in /data/libtorch/lib/libc10.so)
frame #2: c10::IValue::reportToTensorTypeError() const + 0x58 (0x7f0acf786578 in /data/libtorch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0xe1703 (0x55fa79dde703 in ./pnnx)
frame #4: <unknown function> + 0x855ce (0x55fa79d825ce in ./pnnx)
frame #5: <unknown function> + 0x58a91 (0x55fa79d55a91 in ./pnnx)
frame #6: <unknown function> + 0x29d90 (0x7f0acd429d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #7: __libc_start_main + 0x80 (0x7f0acd429e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: <unknown function> + 0x65035 (0x55fa79d62035 in ./pnnx)

Aborted (core dumped)

## model | 模型 | モデル
1. original model
链接: https://pan.baidu.com/s/1xbXjLTDhx140yFuP4fshHA?pwd=yuuj

## how to reproduce | 复现步骤 | 再現方法
1.使用 torch.jit.trace 保存模型
2.运行 ./pnnx /data/rknn-toolkit2/examples/onnx/nmt_enzh_ez/nmt_enzh_dec.jit inputshape=[2,2]i64,[2,1]f32,[3,1,4,6,64]f32,[3,1,4,6,64]f32,[3,2,4,1,64]f32,[3,2,4,1,64]f32
3.

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
link to https://github.com/Tencent/ncnn/issues/4867

**Comment by nihui** [comment]
应该解决了，如有问题请reopen issue
