### ISSUE TITLE
pnnx导出的模型，推理结果不一致

### ISSUE THREAD

**Issue by wxqwinner** [Tencent/ncnn#4874]
## detail | 详细描述 | 詳細な説明
pnnx导出的模型，输入是random（默认测试case）时，jit、pnnx、ncnn推理结果一致。
输入是真实样本数据（附件内tensor1.pkl）时，jit、pnnx一致并且和原pytorch模型也一致，但是ncnn推理结果有误。

其中附件内kwsnet.pt是pytorch导出的jit模型；
kwsnet_pt.py是jit测试脚本；
result.txt是推理结果；
tensor1.pkl是真实样本数据；

复现步骤

1. pnnx导出模型
```bash
pnnx kwsnet.pt inputshape=[1,96,16,1]
```
2. 修改测试脚本，用真实样本数据测试
```python
  with open('tensor1.pkl', 'rb') as f:
      in0 = pickle.load(f)
```

[test.zip](https://github.com/Tencent/ncnn/files/12144263/test.zip)

**Comment by nihui** [comment]
转为连续数据，再给ncnn推理，结果就一致了
```python
    in0 = in0.contiguous()
```
