### ISSUE TITLE
Problem about int8 inference on xiaomi12

### ISSUE THREAD

**Issue by JiangShanCode** [Tencent/ncnn#4876]
## expectation | 诉求 | 期待する
1. speed 
![image](https://github.com/Tencent/ncnn/assets/53932468/b5fc42aa-abbe-49ef-9d86-1788b744c224)

## model | 模型 | モデル
1. model.param and model.bin
https://1drv.ms/u/s!AiRwaS4lla94i3m7kpoS1ziSl0St?e=LU2sRr

## detail | 详细描述 | 詳細な説明
1. When I try to infer on arm-gpu, fp32&fp16 can work on arm-gpu well. But it fallbacks to arm-cpu when performs int8. It seems the arm-gpu supports int8 according to the log.
2. When I try to infer on arm-cpu, int8 is slower than fp32&fp16.
3. The ncnn version is 20230517. QAQ

**Comment by JiangShanCode** [comment]
The ncnn version is 20230517. QAQ

**Comment by nihui** [comment]
vulkan inference does not support int8 model currently
try the latest version or even master branch if you really care speed  :D

**Comment by JiangShanCode** [comment]
谢谢 :D
