### ISSUE TITLE
升级NCNN导致Sherpa - encoder结果异常

### ISSUE THREAD

**Issue by Baiyuetribe** [Tencent/ncnn#4878]
## error log | 日志或报错信息 | ログ
2023.05-17版输出正常：
```log
encoder_out --> w:384,h:8,c:1
```
2023.07-master输出异常
```log
encoder_out --> w:384,h:384,c:1   // 此处h异常
```
## context | 编译/运行环境 | バックグラウンド
纯cpu推理，`windows amd64`和`mac m2`均可复现
## how to reproduce | 复现步骤 | 再現方法
在文件[https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/zipformer-model.cc](https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/zipformer-model.cc)第123行添加
`printf("encoder_out --> w:%d,h:%d,c:%d\n",encoder_out.w,encoder_out.h,encoder_out.c);`

**Comment by nihui** [comment]
confirmed
since https://github.com/Tencent/ncnn/commit/9022b7162a851f5deae0d2e6e5ee5e89a4813212

**Comment by nihui** [comment]
这里 https://github.com/k2-fsa/sherpa-ncnn/issues/252 提供了修改方法

**Comment by Baiyuetribe** [comment]
感谢nihui  😸 , 实测修改encoder后有效。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4930 兼容性回归！
