### ISSUE TITLE
Update到官网的最新版caffe，还是提示param is too old，不知道哪出问题了？

### ISSUE THREAD

**Issue by zengzhen92** [Tencent/ncnn#489]
使用的是其他caffe的版本训练的网络，然后下载最新官网的caffe，并使用里面的脚步Update，然后转换成.param和.bin文件，接下来调用脚本进行测试时它就报错param is too old，param文件中开始的数字为7767517
112 112       不知道哪里出问题了0.0

**Comment by Chanbluky** [comment]
你好，这个问题你解决了吗？ 我也遇到了类似的问题。。。。

**Comment by double-vane** [comment]
我也遇到了这个问题

**Comment by gozhhu** [comment]
make sure program can find the file, try full path first.
