### ISSUE TITLE
NCNN inference doesn't use GPU

### ISSUE THREAD

**Issue by jeck00119** [Tencent/ncnn#4893]
Hi! I'm on a nvidia jetson nano and want to use a ncnn model for inference but it doesn't use GPU(I use ultralytics for inference). How can I use the GPU for inference?Also I built the ncnn using setup.py(I added -DNCNN_VULKAN=ON to the cmake_args list from the setup.py)

**Comment by jeck00119** [comment]
It was from ultralytics.

**Comment by srinikethms** [comment]
@jeck00119 
Hi. 
Can I check whether you were able to run the ncnn model on GPU for jetson nano ?
If yes, can you please share on what you had done ?
Thanks
