### ISSUE TITLE
请问后续是否还会对性能做进一步提升不？比如采用Winograd算法等

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/ncnn#49]
RT

**Comment by nihui** [comment]
TODO

**Comment by nihui** [comment]
winograd (4x4,3x3) 方式的滑动窗口就地变换+点乘+变换，neon全寄存器手工优化，新增的加减法指令需要的时间大于 winograd 乘法减少的时间，比ncnn现有的实现慢了大概70%（也可能实力不够
更大的窗口理论上能减少更多的乘法，但是窗口太大了，寄存器不够，放在栈上读写就算了
不想再实验了，如果有好的实现思路可以再讨论下

**Comment by nihui** [comment]
winograd 6 4 https://github.com/Tencent/ncnn/commit/0385d8e8adcc475a27dbd4c5a83b4567e3d9fab7

**Comment by victorygogogo** [comment]
@nihui  winograd 6 4 算法，只使用了 G矩阵  怎么没有使用 A B矩阵呢？？
