### ISSUE TITLE
[question]想问下多channel的时候取值的问题

### ISSUE THREAD

**Issue by Tumb1eweed** [Tencent/ncnn#4901]
## detail | 详细描述 | 詳細な説明
比如我有个extract出来的output size是1,1,160，我发现直接用m[i]取出来的和m.channel(i)[0]取出来的不一样，channel这样取的值没问题，但前者的值不对，然后还会取出一些0（疑似paddle），reshape成160取出来的值也还是前面这种，是前面这样取不对吗…

**Comment by nihui** [comment]
channel 之间可能存在 padding，row之间则是连续的，应该用 m.channel(i).row(j)[k] 或者 m.channel(i)[j] 取值

**Comment by Tumb1eweed** [comment]
> 

多谢nihui大佬！
