### ISSUE TITLE
how to check the input image size is matched with model input layer?

### ISSUE THREAD

**Issue by bobby-chiu** [Tencent/ncnn#491]

**Comment by boyang24** [comment]
hi cause i saw your comment in ncnn project,and already fixed some problems,i have few questions here,i want you do me a favor,
1.now my project is age and gender recognize under mxnet,and i already change the paremeter to bin & param by mxnet2ncnn tool,
2.and i write a .cpp my self,

3.when i run the program in ubuntu,it ahs the problem like:find_blob_index_by_name prob failed
so i do not know the reason,please guide me to fix this,big thanks
4.i do not know if the mxnet2ncnn tool can change the parameter to the right format,but when i run the tool,it is no error,

**Comment by nihui** [comment]
ncnn do not check the size, as for some typical network (FCN), the input image size can be dynamic.
