### ISSUE TITLE
neon intrinsics算子速度慢很多

### ISSUE THREAD

**Issue by liuxufenfeiya** [Tencent/ncnn#4915]
都是ncnn源码，在aarch64 平台上，用neon intrinsics 的算子比直接编译的算子慢很多

**Comment by Superman0307** [comment]
对的，我也发现相同的问题。aarch64 O3编译器生成的NEON汇编比自己手写的intrinsics更加高效吗

**Comment by WadeThomas76** [comment]
up ,遇到相同的问题。效率差了好几十倍。另外，如果使用intrinsics的话，相比于opencv慢了7-8倍

**Comment by nihui** [comment]
请具体说明是哪个算子慢？
请补充信息后 reopen issue 继续交流
