### ISSUE TITLE
ndk-build编译mobilenet example出现错误,undefined reference to ncnn::Mat::from_pixels(unsigned char const*,int,int,int)

### ISSUE THREAD

**Issue by KaneHui** [Tencent/ncnn#492]
使用https://github.com/Tencent/ncnn/releases提供的预编译的ncnn-android-lib.zip里的libncnn.a编译我的mobilenet example没有问题（基于squeezenet example改写的），但是我想自己编译出libncnn.a文件，然后基于mobilenet example编译出so库，下面是我的步骤：

编译静态文件libncnn.a参考的是wiki上的命令：
$ cd  \<ncnn-root-dir\>
$ mkdir -p build-android-armv7
$ cd build-android-armv7
$ cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
    -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON \
    -DANDROID_PLATFORM=android-23..
$ make -j4
$ make install

这一步没有问题，在build-android-armv7/install下面生成了libncnn.a，我把这个libncnn.a拷贝到了ncnn-android-lib/armeabi-v7a下面，接下来我在ncnn/example目录下建了一个mobilenetncnn的目录，里面的jni设置和cpp代码参考的都是squeezenet：
 cd \<ncnn-root-dir\>\/example\/mobilenetcnn
ndk-build

然后就报错了：
undefined reference to ncnn::Mat::from_pixels(unsigned char const*,int,int,int)

**Comment by sunjunlishi** [comment]
应该是ndk版本的问题吧，最新的发布说是 ndkr15c

**Comment by zhangyanhbr** [comment]
我也遇到了同样的问题，请问，楼主解决了吗？

**Comment by sunjunlishi** [comment]
@zhangyanhbr 解决了。一定要和 发布版本的 ndk 一致。ndkr15c

**Comment by nihui** [comment]
自己编译的时候，armv7 aarch64 都编译出来一起用，android 工程注意下架构
