### ISSUE TITLE
新手问一下，2018版本的ncnn可以打印模型参数和中间结果看吗？

### ISSUE THREAD

**Issue by Sherlock-hh** [Tencent/ncnn#4932]
## detail | 详细描述 | 詳細な説明
模型:mobilenetssd
环境：工程是老版本20181228的库，最近测试发现同一个ncnn模型在电脑和手机（ios和安卓）仿真效果相差很大，手机上精度差，框抖误检测漏检都有，但是电脑就是一点问题都没有。
测试了作者提供的mobilenetssd_demo,使用的是20210525版本，在安卓上效果和电脑一致较好。
想问一下可以有什么办法在2018这个版本上打印模型参数和中间结果

看了2018版本没有fp16的相关参数选择，图片是bgr格式，mean_value和norm_value都确定一致。

**Comment by Baiyuetribe** [comment]
2023啦

**Comment by dentionY** [comment]
没试过，但https://blog.csdn.net/zqjackking/article/details/78219768这个提供了帮助，相关的.h文件依旧在src/layer/中可以找到。

**Comment by Sherlock-hh** [comment]
> https://blog.csdn.net/zqjackking/article/details/78219768

谢谢！我找到在extract(" 层名字",out)就可以看模型中间结果了，模型权重还是没办法看，看了一下源码，没有提供相关接口去看，都是protected，链接中提供的函数没有找到，估计权重是没法看了。
还想问一下，现在查看了有个模型在某一部手机上测试一直会出现一个位置差不多的大框，其他手机就不会，想问问您这边有建议吗

**Comment by Sherlock-hh** [comment]
> > https://blog.csdn.net/zqjackking/article/details/78219768
> 
> 谢谢！我找到在extract(" 层名字",out)就可以看模型中间结果了，模型权重还是没办法看，看了一下源码，没有提供相关接口去看，都是protected，链接中提供的函数没有找到，估计权重是没法看了。 还想问一下，现在查看了有个模型在某一部手机上测试一直会出现一个位置差不多的大框，其他手机就不会，想问问您这边有建议吗

已解决，是为了适配手机性能将模型输入变小了，所以导致结果错误，已改好
