### ISSUE TITLE
FastViT利用onnx2ncnn时出现错误。

### ISSUE THREAD

**Issue by yukaizhou** [Tencent/ncnn#4952]
## error log | 日志或报错信息 | ログ
<img width="761" alt="1692168079218" src="https://github.com/Tencent/ncnn/assets/38181468/1c85dc69-add8-4919-8834-ec00ca00e29c">

## model | 模型 | モデル
1. original model
[fastvit_t8.zip](https://github.com/Tencent/ncnn/files/12356390/fastvit_t8.zip)
## how to reproduce | 复现步骤 | 再現方法
1. build/tools/onnx/onnx2ncnn fastvit_t8.onnx fastvit_t8.param fastvit_t8.bin
   此时会出现不支持 Erf not supported yet!的提示，修改param文件。修改后如下提供 [fastvit_t8.param_modify.zip](https://github.com/Tencent/ncnn/files/12356403/fastvit_t8.param_modify.zip)
此时就会出现上述错误。

**Comment by Baiyuetribe** [comment]
建议使用pnnx转模型

**Comment by yukaizhou** [comment]
> 建议使用pnnx转模型

<img width="767" alt="1692175188621" src="https://github.com/Tencent/ncnn/assets/38181468/2cbce2b0-598d-4f04-80a2-b39a60275ef7">

好的，在尝试使用pnnx转换，但是在编译pnnx时出现了上图的错误。

**Comment by nihui** [comment]
https://github.com/pnnx/pnnx 这里直接下载pnnx工具

**Comment by yukaizhou** [comment]
> https://github.com/pnnx/pnnx 这里直接下载pnnx工具

后面编译成功了，并且可以正确转模型了。是因为虽然指定了libtorch的路径，但是还是会找系统的torch路径。后面在一个没有torch的路径里就可以源码编译了。谢谢。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
