### ISSUE TITLE
ncnn 20230816 linux build failure

### ISSUE THREAD

**Issue by chenrui333** [Tencent/ncnn#4953]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-11 -O3 -DNDEBUG -rdynamic CMakeFiles/caffe2ncnn.dir/caffe2ncnn.cpp.o CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o -o caffe2ncnn  -lprotobuf
  /usr/bin/ld: CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o: undefined reference to symbol '_ZN4absl12lts_2023012512log_internal21CheckOpMessageBuilder7ForVar2Ev'
  /usr/bin/ld: /home/linuxbrew/.linuxbrew/opt/abseil/lib/libabsl_log_internal_check_op.so.2301.0.0: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5877560299/job/15943734244
relates to Homebrew/homebrew-core#139679

---

For now, I just applied some ldflags patch to get it going.

**Comment by nihui** [comment]
hi, please test if this pr could fix it
https://github.com/Tencent/ncnn/pull/4955

**Comment by nihui** [comment]
resolved in https://github.com/Tencent/ncnn/commit/cd1c0d6eab505ce71a4cb1ed6b017609dbb80ffd

**Comment by felixonmars** [comment]
Confirmed that ncnn 20230816 with #4955 applied builds fine here on Arch against protobuf 24.2. Thanks!
