### ISSUE TITLE
rk toolchain make failed based latest ersion

### ISSUE THREAD

**Issue by xiongzhu666** [Tencent/ncnn#4954]
## error log | 日志或报错信息 | ログ
![screenshot-20230817-093933](https://github.com/Tencent/ncnn/assets/52955431/ebc75dce-fdf9-44af-9b5a-28804e239660)

## context | 编译/运行环境 | バックグラウンド
ubuntu20.04

toolchains: arm-rockchip830-linux-uclibcgnueabihf

rv1106.toolchain.cmake:
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(RV1106_ROOT_PATH "/home/xz/rk_workspace/arm-rockchip830-linux-uclibcgnueabihf")
set(CMAKE_C_COMPILER "${RV1106_ROOT_PATH}/bin/arm-rockchip830-linux-uclibcgnueabihf-gcc")
set(CMAKE_CXX_COMPILER "${RV1106_ROOT_PATH}/bin/arm-rockchip830-linux-uclibcgnueabihf-g++")
set(CMAKE_FIND_ROOT_PATH "${RV1106_ROOT_PATH}/arm-rockchip830-linux-uclibcgnueabihf")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_FLAGS "-march=armv7-a -mfloat-abi=hard -mfpu=neon")
set(CMAKE_CXX_FLAGS "-march=armv7-a -mfloat-abi=hard -mfpu=neon")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}" CACHE STRING "c flags")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}" CACHE STRING "c++ flags")

## how to reproduce | 复现步骤 | 再現方法
1. cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../toolchains/rv1106.toolchain.cmake -DNCNN_SIMPLEOCV=ON -DNCNN_BUILD_EXAMPLES=ON ..
2. make
3.

## more | 其他 | その他

**换成ncnn-20230223版本后编译顺利通过**

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/4963

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/c003281c537e6348745c2c845207e63d16145f5c
