### ISSUE TITLE
x86, int8推理速度比fp32还慢

### ISSUE THREAD

**Issue by happyday-lkj** [Tencent/ncnn#4956]
## expectation | 诉求 | 期待する
在ubuntu x86平台上，fp32模型推理232ms，转成int8以后，推理速度变成了270ms，在加载模型前已经设置 `net.opt.use_int8_inference = true;` 有遇到过这种情况吗

**Comment by JankinTian** [comment]
可以看一下推理的机器是否支持int8的推理，若是不支持，则会出现上述的情况

**Comment by swithmn1** [comment]
@JankinTian 怎么查看是否支持int8推理

**Comment by nihui** [comment]
最新的 ncnn 代码中对 x86 平台 int8 推理做了优化，可以更新试试
如有问题，可 reopen issue 继续交流
