### ISSUE TITLE
样例yolov4.cpp cpu与gpu推理结果不一致(yolov4-tiny)

### ISSUE THREAD

**Issue by Hideousmon** [Tencent/ncnn#4958]
## error log | 日志或报错信息 | ログ
1. 直接推理结果对比：
cpu:
![cpuresult](https://github.com/Tencent/ncnn/assets/43981919/1fc8c411-b3bb-4afa-bc28-b9e5ae6dc824)

gpu:
![gpuresult](https://github.com/Tencent/ncnn/assets/43981919/faa1092f-38bb-4c47-b8e2-9f2736ea4ad7)

2. 进一步探究了推理结果不一致问题发生的节点，通过将每一层输出结果进行打印对比，发现结果不一致发生在第二十三层（下图中蓝色选中的层）的输出中，且集中在后半部分的输出通道。
发生不一致的层：
![N(4N_ SVV)WPS}PXBPGED9L](https://github.com/Tencent/ncnn/assets/43981919/9a6d7e3c-6e40-4cf5-a12a-1d405b1fdbd1)

第二十三层输出cpu(左)与gpu(右)结果对比：
![UDAED{(3GI%_6O_X3QXC0Z](https://github.com/Tencent/ncnn/assets/43981919/f6c1cc30-0da2-4f43-ba1d-ed81183cf4c5)

## context | 编译/运行环境 | バックグラウンド
运行环境：
cpu: AMD 6800H，gpu: 3060 Laptop
编译/运行环境：
mingw64 windows
有关闭fp16：
yolov4->opt.use_winograd_convolution = true;
yolov4->opt.use_sgemm_convolution = true;
yolov4->opt.use_fp16_packed = false;
yolov4->opt.use_fp16_storage = false;
yolov4->opt.use_fp16_arithmetic = false;
yolov4->opt.use_packing_layout = true;
yolov4->opt.use_shader_pack8 = false;
yolov4->opt.use_image_storage = false;
权重文件来源：
the ncnn model https://drive.google.com/drive/folders/1YzILvh0SKQPS_lrb33dmGNq7aVTKPWS0?usp=sharing
## how to reproduce | 复现步骤 | 再現方法
在cpu与gpu上运行yolov4-tiny样例进行对比。

## more | 其他 | その他
除yolov4-tiny外，有对yolov4、fasterrcnn进行测试，没有发生结果不一致的问题。

**Comment by Hideousmon** [comment]
！将yolov4->opt.use_winograd_convolution = true;设置为false后，gpu结果正常：

**Comment by Hideousmon** [comment]
！将use_winograd_convolution设置为false后，gpu结果正常：
![gpuresult-wingograd_convolfalse](https://github.com/Tencent/ncnn/assets/43981919/db960c3e-66a9-48ac-b1e8-7fccbd73dde3)

**Comment by Hideousmon** [comment]
进一步试了下，仅在开启use_winograd43_convoluion时会出现不一致现象。

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
临时绕过方法：
修改 param，有问题的层末尾添加 31=64
```
Convolution              18_135                   1 1 17_131 18_135_bn_leaky -23330=4,3,26,26,256 0=256 1=3 4=1 5=1 6=589824 9=2 -23310=1,1.000000e-01 31=64
```

**Comment by Hideousmon** [comment]
> 临时绕过方法： 修改 param，有问题的层末尾添加 31=64
> 
> ```
> Convolution              18_135                   1 1 17_131 18_135_bn_leaky -23330=4,3,26,26,256 0=256 1=3 4=1 5=1 6=589824 9=2 -23310=1,1.000000e-01 31=64
> ```

好嘞 😄

**Comment by nihui** [comment]
pr修复 https://github.com/Tencent/ncnn/pull/4973

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/7c4969ed582fb0c7c00fa665fe1555cabb2d7b2d
感谢报告
