### ISSUE TITLE
slice not supported yet!!

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [Tencent/ncnn#498]
hello, when i transform pytorch ShuffleNetV2 to NCNN, a problem about slice raise, like title, can you tell me how to use a know operation to replace it? thank you very much!

**Comment by Casablancaaa** [comment]
@ZHANG-SHI-CHANG  hi, i met the same issue.  how did you modify it? please help...

**Comment by hanfanggithub** [comment]
> -_- i sovle it via modified some layers by hand ... but it can work ...
hi, i met the same issue, i modifier split to slice ,but can't work ,can you help me ?
