### ISSUE TITLE
不支持数外置的onnx模型转换

### ISSUE THREAD

**Issue by WillPen** [Tencent/ncnn#4994]
不支持数外置的onnx模型转换

onnx_model = xxxxx
onnx.save_model(onnx_model, "test.onnx", save_as_external_data=True, all_tensors_to_one_file=True, location="test.onnx.data", size_threshold=1024, convert_attribute=False)

比如生成一个test.onnx，外置参数文件：test.onnx.data

**Comment by nihui** [comment]
是的，不支持。
如果需要转换大模型，推荐使用 pnnx 工具直接从 pytorch 转换

**Comment by WillPen** [comment]
了解
