### ISSUE TITLE
采用自己的网络模型，计算出的结果与matlab运算出的相差较大

### ISSUE THREAD

**Issue by VivienFu** [Tencent/ncnn#50]
如题，您可不可以帮忙指点问题可能出在哪儿？

确认过ncnn每层网络输入输出size，简单看了几个FC的weight值，是正确的。

会不会下面的代码有问题？

int detect_faceIDnet(const cv::Mat& bgr, float *feat)
{
	ncnn::Mat in = ncnn::Mat::from_pixels(bgr.data, ncnn::Mat::PIXEL_BGR, bgr.cols, bgr.rows);
	in.substract_mean_normalize(mean_vals, 0);

	ncnn::Extractor ex = faceIDnet.create_extractor();
	ex.set_light_mode(true);
	ex.set_num_threads(4);
	ex.input("data", in);
	ncnn::Mat out;
	ex.extract("eltwise_fc1", out);
	for (int j = 0; j<FEAT_NUM; j++)
	{
		const float* prob = out.data + out.cstep * j;
		feat[j] = prob[0];
		//cout << feat[j] << " ";		
	}
	//cout << endl;
	return 0;
}

**Comment by nihui** [comment]
matlab 是 col-major 存储的，如果模型是 matlab 训练的，里头的 weight 要变换下。。

**Comment by VivienFu** [comment]
@nihui 答复神速啊，非常感谢！

我的模型不是用matlab训练的，就是caffe.exe跑得训练。后来发现是数据预处理不一致导致的。
太弱了，还没有好好理解ncnn。
处理方式记录在blog中了，http://blog.csdn.net/fuwenyan/article/details/76213015

**Comment by nihui** [comment]
const float mean_vals[3] = { 104.f, 117.f, 123.f };
const float norm_vals[3] = { 0.0078125f, 0.0078125f, 0.0078125f };
in.substract_mean_normalize(mean_vals, norm_vals);
这样应该也可以

**Comment by VivienFu** [comment]
@nihui  原来如此！！！谢大神！

**Comment by Tomhouxin** [comment]
@nihui ，如果mean_vals[3] = {104.f, 112.f, 121.f}呢，对应的norm_vals[3] 是怎么算的

**Comment by nihui** [comment]
> 
> 
> @nihui ，如果mean_vals[3] = {104.f, 112.f, 121.f}呢，对应的norm_vals[3] 是怎么算的

具体的 mean norm 要参考训练的设置
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#pre-process

**Comment by jolt2017** [comment]
> const float mean_vals[3] = { 127.5f, 127.5f, 127.5f };
> const float norm_vals[3] = { 0.0078125f, 0.0078125f, 0.0078125f };
> in.substract_mean_normalize(mean_vals, norm_vals);
> 这样应该也可以

您好，这里不是很理解，为啥均值和方差和pytorch 训练模型时使用的不一致？？？
