### ISSUE TITLE
Help,   What is the reason of my output is null?

### ISSUE THREAD

**Issue by wuyong139** [Tencent/ncnn#500]
My file *.param is:
7767517
19 21
Convolution      conv1            1 1 data conv1 0=20 1=4 2=1 3=1 4=0 5=1 6=320
ReLU             relu1            1 1 conv1 conv1_relu1
Pooling          pool1            1 1 conv1_relu1 pool1 0=0 1=2 2=2 3=0 4=0
Convolution      conv2            1 1 pool1 conv2 0=40 1=3 2=1 3=1 4=0 5=1 6=7200
ReLU             relu2            1 1 conv2 conv2_relu2
Pooling          pool2            1 1 conv2_relu2 pool2 0=0 1=2 2=2 3=0 4=0
Convolution      conv3            1 1 pool2 conv3 0=60 1=3 2=1 3=1 4=0 5=1 6=21600
ReLU             relu3            1 1 conv3 conv3_relu3
Pooling          pool3            1 1 conv3_relu3 pool3 0=0 1=2 2=2 3=0 4=0
Split            splitncnn_0      1 2 pool3 pool3_splitncnn_0 pool3_splitncnn_1
Convolution      conv4            1 1 pool3_splitncnn_1 conv4 0=80 1=2 2=1 3=1 4=0 5=1 6=19200
ReLU             relu4            1 1 conv4 conv4_relu4
Flatten          pool3_flat       1 1 pool3_splitncnn_0 pool3_flat
Flatten          conv4_flat       1 1 conv4_relu4 conv4_flat
Concat           concat           2 1 pool3_flat conv4_flat faker 0=0
InnerProduct     fc1              1 1 faker fc1 0=120 1=1 2=103200
ReLU             relu_fc1         1 1 fc1 fc1_relu_fc1
InnerProduct     fc2              1 1 fc1_relu_fc1 fc2 0=16 1=1 2=1920
ReLU             relu_fc2         1 1 fc2 fc2_relu_fc2

code: 
ncnn::Extractor ex = level1.create_extractor();
ex.set_light_mode(true);
ex.set_num_threads(num_threads);
ex.input("data",img);
ncnn::Mat level1_8point;
ex.extract("fc2_relu_fc2",level1_8point);
return level1_8point;

the result level1_8point.w == 0, level1_8point.h == 0, level1_8point.c ==0,

why?

**Comment by nihui** [comment]
incorrect img size ?

**Comment by lrain-CN** [comment]
我也遇到一样的问题，中间的某层结果开始输出的 w、h、c维度就变成0 ，caffe的结果是正确的。而且同时训练的其他模型没有问题，差别只是改了一个conv layer的 stride
