### ISSUE TITLE
torch.int64的常量数据使用pnnx转到ncnn，变成了float32，而且数据全是0

### ISSUE THREAD

**Issue by zhang0557kui** [Tencent/ncnn#5015]
torch.int64的常量数据使用pnnx转到ncnn，变成了float32，而且数据全是0

**Comment by zhang0557kui** [comment]
> torch.int64的常量数据使用pnnx转到ncnn，变成了float32，而且数据全是0

![1](https://github.com/Tencent/ncnn/assets/28557916/4bb7f14d-1c28-4640-a4ce-b5113eb175a6)
上图是torchscript
下图是ncnn
不知道是不是算子index_select不支持导致的memorydata的转换错误？
![2](https://github.com/Tencent/ncnn/assets/28557916/c781d245-3bdd-45fa-9761-9cd3a216fe5e)

**Comment by zhang0557kui** [comment]
以下是测试了一个简单地Mul算子，int64依然转的不对
![4](https://github.com/Tencent/ncnn/assets/28557916/0938cb6d-b8c5-40c5-8597-f5979457a43d)
![3](https://github.com/Tencent/ncnn/assets/28557916/442f3894-1269-4250-96af-e38c086d93bb)

**Comment by nihui** [comment]
请贴一下 pytorch module 的代码

**Comment by zhang0557kui** [comment]
> 
import torch
from torch import nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.index = torch.ones(1, 3, 128, 128, dtype=torch.int64)*2

    def forward(self, x):
        #return torch.index_select(x, 1, self.index)
        return torch.mul(x, self.index)

**Comment by zhang0557kui** [comment]
> 请贴一下 pytorch module 的代码

`import torch
from torch import nn


class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.index = torch.ones(1, 3, 128, 128, dtype=torch.int64)*2

    def forward(self, x):
        #return torch.index_select(x, 1, self.index)
        return torch.mul(x, self.index)`

**Comment by zhang0557kui** [comment]
> 请贴一下 pytorch module 的代码

import torch
from torch import nn


class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.index = torch.ones(1, 3, 128, 128, dtype=torch.int64)*2

    def forward(self, x):
        #return torch.index_select(x, 1, self.index)
        return torch.mul(x, self.index)

**Comment by zhang0557kui** [comment]
> 请贴一下 pytorch module 的代码

```
import torch
from torch import nn


class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.index = torch.ones(1, 3, 128, 128, dtype=torch.int64)*2

    def forward(self, x):
        #return torch.index_select(x, 1, self.index)
        return torch.mul(x, self.index)
```

**Comment by zhang0557kui** [comment]
> 请贴一下 pytorch module 的代码

```
import torch
from torch import nn


class MyModel1(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.index = torch.ones(1, 3, 128, 128, dtype=torch.int64)*2

    def forward(self, x):
        return torch.mul(x, self.index)

class MyModel2(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.index = torch.ones(2, dtype=torch.int64)

    def forward(self, x):
        return torch.index_select(x, 1, self.index)
```

**Comment by nihui** [comment]
问题根源是 ncnn memorydata 没有支持 int 数据
