### ISSUE TITLE
protobuf version

### ISSUE THREAD

**Issue by FSetragno** [Tencent/ncnn#502]
I am trying to execute make -j4 but I'm getting tons of errors with protobuf 3.6.0. What version should I use?

**Comment by hlcool** [comment]
protobuf 2.6.1is good for me

**Comment by SisterL** [comment]
Does it should be used by corresponding version of ncnn?

**Comment by nihui** [comment]
protobuf >= 2.6.1
you may need to add "-std=c++11" compile flags for building tools if you use the most recent protobuf
