### ISSUE TITLE
为啥ncnn编译之后 选择的是MT ，应用安装到其他电脑后 还是需要VC 运行库才能跑

### ISSUE THREAD

**Issue by sylarrrm** [Tencent/ncnn#5023]
## expectation | 诉求 | 期待する
1. speed 
2. precision

## model | 模型 | モデル
1. model.param and model.bin

## detail | 详细描述 | 詳細な説明
为啥ncnn编译之后 选择的是MT ，应用安装到其他电脑后 还是需要VC 运行库才能跑

**Comment by sylarrrm** [comment]
> `cmake -DNCNN_BUILD_WITH_STATIC_CRT=ON ..`

开启了这个 但是发现需要vcomp140 才可以运行

**Comment by nihui** [comment]
把vcomp140的dll一起带着发布就可以了
