### ISSUE TITLE
自定义算子异常

### ISSUE THREAD

**Issue by zhang0557kui** [Tencent/ncnn#5024]
测试代码：
[https://drive.google.com/file/d/1vAJGCRgNZM_xrE-wQn5kBzLwrmVwD1Tj/view?usp=drive_link](url)
环境:
windows 10
vs2022
ncnn-20230816-windows-vs2022-shared
model param为：
```
7767517
2 2
Input                    in0                      0 1 in0
MyReLU               myrelu_0             1 1 in0 out0
```
其中MyReLU的算子实现就是copy的ncnn的relu layer，没做改动
算子注册后DEFINE_LAYER_CREATOR(MyReLU)，load_param没问题，就是ex.extract("out0", out0)出现如下异常：
![捕获](https://github.com/Tencent/ncnn/assets/28557916/72eebba7-28de-483a-912c-4077d3cf3980)

请问是什么原因呢，param中MyReLU直接改成ReLU，不使用自定义算子，则没问题

**Comment by nihui** [comment]
你没有调用 load_model

**Comment by zhang0557kui** [comment]
> 

如果模型是这样的：
```
7767517
2 2
Input                    in0                    0 1 in0
ReLU                    relu_0                1 1 in0 out0
```
没有load_model，为什么没有问题呢

**Comment by nihui** [comment]
不load_model也是有问题，只不过你可能没发现...
总之，load_model是需要的
