### ISSUE TITLE
disable c++ stl

### ISSUE THREAD

**Issue by xiaozhi003** [Tencent/ncnn#5031]
不再依赖编译器提供的 stl 实现，使用 ncnn 自带的 simplestl，上层调用时也只能使用 simplestl 的功能。
通常需要配合编译参数-nodefaultlibs -fno-builtin -nostdinc++ -lc。

请问在精简ncnn库的时候，上述配合编译参数如何使用，在哪里设置？

**Comment by whyb** [comment]
> 不再依赖编译器提供的 stl 实现，使用 ncnn 自带的 simplestl，上层调用时也只能使用 simplestl 的功能。 通常需要配合编译参数-nodefaultlibs -fno-builtin -nostdinc++ -lc。
> 
> 请问在精简ncnn库的时候，上述配合编译参数如何使用，在哪里设置？

![圖片](https://github.com/Tencent/ncnn/assets/2672931/13b42898-0248-4bb8-98a1-62505007938c)
NCNN_SIMPLESTL

**Comment by xiaozhi003** [comment]
> > 不再依赖编译器提供的 stl 实现，使用 ncnn 自带的 simplestl，上层调用时也只能使用 simplestl 的功能。 通常需要配合编译参数-nodefaultlibs -fno-builtin -nostdinc++ -lc。
> > 请问在精简ncnn库的时候，上述配合编译参数如何使用，在哪里设置？
> 
> ![圖片](https://user-images.githubusercontent.com/2672931/268161534-13b42898-0248-4bb8-98a1-62505007938c.png) NCNN_SIMPLESTL

首先感谢回复，我是cmake编译android的.a库，下面是我的编译脚本，你上面发的那个界面在哪里呢，是怎么用的呢? 编译脚本里面如何修改呢？

```
cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" -DANDROID_STL=system \
    -DANDROID_ABI="armeabi-v7a" \
    -DANDROID_ARM_NEON=ON \
    -DNCNN_SIMPLESTL=ON \  # 使用 ncnn 自带的 simplestl
    -DNCNN_DISABLE_RTTI=ON -DNCNN_DISABLE_EXCEPTION=ON \
    -DNCNN_VULKAN=OFF \
    -DNCNN_BF16=OFF \
    -DNCNN_PIXEL_DRAWING=OFF \
    -DNCNN_PIXEL_ROTATE=OFF -DNCNN_PIXEL_AFFINE=OFF \
    -DNCNN_PIXEL=OFF \
    -DNCNN_OPENMP=OFF \
    -DNCNN_AVX2=OFF -DNCNN_ARM82=OFF \
    -DNCNN_RUNTIME_CPU=OFF \
    -DWITH_LAYER_absval=OFF -DWITH_LAYER_bnll=OFF \
    -DANDROID_PLATFORM=android-14 ..
```

**Comment by whyb** [comment]
> > > 不再依赖编译器提供的 stl 实现，使用 ncnn 自带的 simplestl，上层调用时也只能使用 simplestl 的功能。 通常需要配合编译参数-nodefaultlibs -fno-builtin -nostdinc++ -lc。
> > > 请问在精简ncnn库的时候，上述配合编译参数如何使用，在哪里设置？
> > 
> > 
> > ![圖片](https://user-images.githubusercontent.com/2672931/268161534-13b42898-0248-4bb8-98a1-62505007938c.png) NCNN_SIMPLESTL
> 
> 首先感谢回复，我是cmake编译android的.a库，下面是我的编译脚本，你上面发的那个界面在哪里呢，是怎么用的呢? 编译脚本里面如何修改呢？
> 
> ```
> cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" -DANDROID_STL=system \
>     -DANDROID_ABI="armeabi-v7a" \
>     -DANDROID_ARM_NEON=ON \
>     -DNCNN_SIMPLESTL=ON \  # 使用 ncnn 自带的 simplestl
>     -DNCNN_DISABLE_RTTI=ON -DNCNN_DISABLE_EXCEPTION=ON \
>     -DNCNN_VULKAN=OFF \
>     -DNCNN_BF16=OFF \
>     -DNCNN_PIXEL_DRAWING=OFF \
>     -DNCNN_PIXEL_ROTATE=OFF -DNCNN_PIXEL_AFFINE=OFF \
>     -DNCNN_PIXEL=OFF \
>     -DNCNN_OPENMP=OFF \
>     -DNCNN_AVX2=OFF -DNCNN_ARM82=OFF \
>     -DNCNN_RUNTIME_CPU=OFF \
>     -DWITH_LAYER_absval=OFF -DWITH_LAYER_bnll=OFF \
>     -DANDROID_PLATFORM=android-14 ..
> ```

抱歉我没有接触过Android的NDK，
我看到仓库的编译脚本 https://github.com/Tencent/ncnn/blob/master/.github/workflows/android-armv7-gpu.yml#L39 上面都是使用的NCNN_SIMPLESTL默认即-DNCNN_SIMPLESTL=OFF。
为什么要在Android上使用极致精简版的STL呢？担心二进制包体积不能很大的原因吗？

**Comment by xiaozhi003** [comment]
@whyb 是的业务要求极简，减少apk的大小，所以现在是想法设法让他小😊。所以不知道 @nihui `disable c++ stl` 这一项该如何正确使用，才能使库精简。

**Comment by Baiyuetribe** [comment]
@xiaozhi003  缩减方法wiki里写的很清楚，大概有16种办法，请多多阅读文档，少打扰nihi酱
https://github.com/Tencent/ncnn/wiki/build-minimal-library

**Comment by xiaozhi003** [comment]
> @xiaozhi003 缩减方法wiki里写的很清楚，大概有16种办法，请多多阅读文档，少打扰nihui酱
> https://github.com/Tencent/ncnn/wiki/build-minimal-library

16种方式已经都看过了并已经编译测试了，现在就是不明白`disable c++ stl`这一项怎么操作呢？还望大神不吝赐教。

**Comment by nihui** [comment]
> > > 不再依赖编译器提供的 stl 实现，使用 ncnn 自带的 simplestl，上层调用时也只能使用 simplestl 的功能。 通常需要配合编译参数-nodefaultlibs -fno-builtin -nostdinc++ -lc。
> > > 请问在精简ncnn库的时候，上述配合编译参数如何使用，在哪里设置？
> > 
> > 
> > ![圖片](https://user-images.githubusercontent.com/2672931/268161534-13b42898-0248-4bb8-98a1-62505007938c.png) NCNN_SIMPLESTL
> 
> 首先感谢回复，我是cmake编译android的.a库，下面是我的编译脚本，你上面发的那个界面在哪里呢，是怎么用的呢? 编译脚本里面如何修改呢？
> 
> ```
> cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" -DANDROID_STL=system \
>     -DANDROID_ABI="armeabi-v7a" \
>     -DANDROID_ARM_NEON=ON \
>     -DNCNN_SIMPLESTL=ON \  # 使用 ncnn 自带的 simplestl
>     -DNCNN_DISABLE_RTTI=ON -DNCNN_DISABLE_EXCEPTION=ON \
>     -DNCNN_VULKAN=OFF \
>     -DNCNN_BF16=OFF \
>     -DNCNN_PIXEL_DRAWING=OFF \
>     -DNCNN_PIXEL_ROTATE=OFF -DNCNN_PIXEL_AFFINE=OFF \
>     -DNCNN_PIXEL=OFF \
>     -DNCNN_OPENMP=OFF \
>     -DNCNN_AVX2=OFF -DNCNN_ARM82=OFF \
>     -DNCNN_RUNTIME_CPU=OFF \
>     -DWITH_LAYER_absval=OFF -DWITH_LAYER_bnll=OFF \
>     -DANDROID_PLATFORM=android-14 ..
> ```

你这不已经 simplestl 了么
