### ISSUE TITLE
onnx 转模型之后运行demo崩溃

### ISSUE THREAD

**Issue by Sherlock-hh** [Tencent/ncnn#5044]
## error log | 日志或报错信息 | ログ
出现在forward里。
`ex.extract("conv2d_50",out);`
`浮点数例外 (核心已转储)`

## context | 编译/运行环境 | バックグラウンド
[onnx模型下载](https://github.com/Sherlock-hh/bug_record/blob/main/model.onnx)
[ncnn的onnx模型配置](https://github.com/Sherlock-hh/bug_record/blob/main/ncnn.param)
[ncnn的onnx模型权重](https://github.com/Sherlock-hh/bug_record/blob/main/ncnn.bin)
ncnn 20230223

使用convertmodel.com和ncnn自带的onnx2ncnn转换完出来的模型都出现报错了
## how to reproduce | 复现步骤 | 再現方法
1.使用onnx2ncnn将模型转成.param和.bin 文件
2.运行代码
```
cv::Rect test_mbllen(cv::Mat& raw_img, float threshold)
{
#if NCNN_VULKAN
    mobilenet.opt.use_vulkan_compute = true;
#endif // NCNN_VULKAN

    cv::Rect ret(0, 0, 0, 0);
    std::vector<cv::Rect> object_rects;

    int img_h = raw_img.size().height;
    int img_w = raw_img.size().width;
    int input_size_w = 256;// = 300;
    int input_size_h = 256;// = 300;
    ncnn::Mat in = ncnn::Mat::from_pixels_resize(raw_img.data, ncnn::Mat::PIXEL_BGR, raw_img.cols, raw_img.rows, input_size_w, input_size_h);

    printf("in mat %f %f",in[0],in[1]);
    ncnn::Mat out;
    const float mean_vals[3] = {0.0f, 0.0f, 0.0f};
    const float norm_vals[3] = {1.0/255.0,1.0/255.0,1.0/255.0};

    in.substract_mean_normalize(mean_vals, norm_vals);
    std::string savenamein="./mbllenin"+std::to_string(frame_id)+".raw";
    FILE* fncnnin=fopen(savenamein.c_str(),"wb");
    fwrite(in.data,sizeof(float),in.h*in.c*in.w,fncnnin);
    fclose(fncnnin);
    ncnn::Extractor ex = mobilenet.create_extractor();
    //ex.set_light_mode(true);
    ex.set_num_threads(4);
    //ex.input("data", in);
    //ex.extract("detection_out",out);
    ex.input("input_1", in);
    printf("what input?");
    ex.extract("conv2d_50",out);
    printf("what output?");
    std::string savename="./mbllenout"+std::to_string(frame_id)+".raw";
    FILE* fncnn=fopen(savename.c_str(),"wb");
    fwrite(out.data,sizeof(float),in.h*in.c*in.w,fncnn);
    fclose(fncnn);
    
    printf("out mat %f %f",out[0],out[256*256]);
    printf("\nout size:%d,%d,%d\n", out.w, out.h, out.c);
}
```
3.然后崩溃报错

## more | 其他 | その他
1、想问一下想原始的onnx模型打开最后一层为`con2d_50`，但是转完ncnn模型之后是`permute`层，也没有了 `transpose层`，这是正常的吗
![image](https://github.com/Tencent/ncnn/assets/65853825/dde48c5e-44f9-4c6d-87e3-4b41353236d8)
![image](https://github.com/Tencent/ncnn/assets/65853825/6166ebdf-5143-4cb6-adf4-333c25ce5dd4)
2、我把所有层都打印出来之后发现最后一层blob.name为空，这个时候我写`ex.extract('blob_name',out)`中的`blob_name` 需要怎么写呢？
![image](https://github.com/Tencent/ncnn/assets/65853825/a551c8e1-b5a0-49fa-8410-67d6bf3fb404)

**Comment by Sherlock-hh** [comment]
windows下试着跑一下那个demo，没有崩溃但是返回的out全是NULL，实在不知道要从哪里找问题了OTZ

**Comment by w8501** [comment]
> windows下试着跑一下那个demo，没有崩溃但是返回的out全是NULL，实在不知道要从哪里找问题了OTZ

onnx模型前面怎么还有个premute把输入转成nchw的形式？
这个layer导致ncnn把本来nchw的输入转成了错误的shape，所以后面的层没结果了。
![image](https://github.com/Tencent/ncnn/assets/35365618/18a9a30f-f8eb-48bd-833b-a1acd2f0ac15)
把ncnn.param前面改一下，改成右边的形式
![image](https://github.com/Tencent/ncnn/assets/35365618/06199165-7a5e-4bd7-9eff-b22b1d53166a)
这个结果是你想要的吗？
![image](https://github.com/Tencent/ncnn/assets/35365618/d98856eb-42b2-42ab-9435-049877a3c0af)

**Comment by xll98** [comment]
> 震惊好神奇，真是改完之后是对的了，谢谢大佬指点！ 这个permute应该是从原始模型的这个transpose转过来的,我看了一眼demo里面竟然真的有一步是reshape， 啊哈哈哈哈感谢大佬回复，不然我就要加班更新ncnn库了啊哈哈哈还好不用更新啊哈哈哈哈啊哈哈哈不用加班了啊哈哈哈谢谢大佬 ![image](https://user-images.githubusercontent.com/65853825/270918741-66f8c597-8f95-40c6-9882-e7b9bd19c71c.png) ![image](https://user-images.githubusercontent.com/65853825/270923418-8fd588c5-e96a-46b9-84b9-65a49704645e.png)
> 
> > > windows下试着跑一下那个demo，没有崩溃但是返回的out全是NULL，实在不知道要从哪里找问题了OTZ
> > 
> > 
> > @Sherlock-hh onnx模型前面怎么还有个premute把输入转成nchw的形式？ 这个layer导致ncnn把本来nchw的输入转成了错误的shape，所以后面的层没结果了。 ![image](https://user-images.githubusercontent.com/35365618/270643507-18a9a30f-f8eb-48bd-833b-a1acd2f0ac15.png) 把ncnn.param前面改一下，改成右边的形式 ![image](https://user-images.githubusercontent.com/35365618/270644061-06199165-7a5e-4bd7-9eff-b22b1d53166a.png) 这个结果是你想要的吗？ ![image](https://user-images.githubusercontent.com/35365618/270644386-d98856eb-42b2-42ab-9435-049877a3c0af.png)

请问这个ncnn Mat可视化的插件是什么，感觉很好用

**Comment by xll98** [comment]
> > windows下试着跑一下那个demo，没有崩溃但是返回的out全是NULL，实在不知道要从哪里找问题了OTZ
> 
> @Sherlock-hh onnx模型前面怎么还有个premute把输入转成nchw的形式？ 这个layer导致ncnn把本来nchw的输入转成了错误的shape，所以后面的层没结果了。 ![image](https://user-images.githubusercontent.com/35365618/270643507-18a9a30f-f8eb-48bd-833b-a1acd2f0ac15.png) 把ncnn.param前面改一下，改成右边的形式 ![image](https://user-images.githubusercontent.com/35365618/270644061-06199165-7a5e-4bd7-9eff-b22b1d53166a.png) 这个结果是你想要的吗？ ![image](https://user-images.githubusercontent.com/35365618/270644386-d98856eb-42b2-42ab-9435-049877a3c0af.png)

请问这个ncnn Mat可视化的插件是什么，感觉很好用

**Comment by Sherlock-hh** [comment]
netron



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月13日(周五) 中午11:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/ncnn] onnx 转模型之后运行demo崩溃 (Issue #5044)




   
windows下试着跑一下那个demo，没有崩溃但是返回的out全是NULL，实在不知道要从哪里找问题了OTZ
  
@Sherlock-hh onnx模型前面怎么还有个premute把输入转成nchw的形式？ 这个layer导致ncnn把本来nchw的输入转成了错误的shape，所以后面的层没结果了。  把ncnn.param前面改一下，改成右边的形式  这个结果是你想要的吗？ 
  
请问这个ncnn Mat可视化的插件是什么，感觉很好用

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
