### ISSUE TITLE
undefined reference to `__expf_finite'

### ISSUE THREAD

**Issue by zchrissirhcz** [Tencent/ncnn#5051]
## error log | 日志或报错信息 | ログ

![image](https://github.com/Tencent/ncnn/assets/3831847/d367a362-e66f-4a2c-b20f-9ba0caa23ee5)

## how to reproduce | 复现步骤 | 再現方法
1. Compile ncnn (tag: 20230517) on Ubuntu 16.04 (Compiler: GCC 5.4.0). Keep original C/C++ flags
2. Link ncnn on Ubuntu 20.04 (Compiler: 9.4)

## more | 其他 | その他

- https://stackoverflow.com/questions/29607422/undefined-expf-finiteglibc-2-15-libm-so-error-adding-symbols-dso-missing

- https://github.com/cocos2d/cocos2d-x/issues/20471

- https://stackoverflow.com/questions/63261220/link-errors-with-ffast-math-ffinite-math-only-and-glibc-2-31

It seems like `-ffast-math` cause this link error.
@nihui I guess `-ffast-math` is mostly for ARM NEON, and Linux-x64 may not require that. If so, could we strict `-ffast-math` only for ARM NEON enabled compilation?

**Comment by zchrissirhcz** [comment]
![image](https://github.com/Tencent/ncnn/assets/3831847/443bf91e-63ce-4e43-b6eb-6ce0e8dca348)

**Comment by zchrissirhcz** [comment]
Bothe -Ofast and -ffast-math will enable -ffinite-math-only in GCC 5.4.0
```bash
gcc -c -Q -Ofast -ffast-math --help=optimizers | grep 'finite'
  -ffinite-math-only    

gcc -c -Q -ffast-math --help=optimizers | grep 'finite' 
  -ffinite-math-only                    [enabled]
```

**Comment by nihui** [comment]
You should use the same version of the compiler to compile and link

Disabling fast-math may result in performance loss
