### ISSUE TITLE
多输出模型如何读取输出节点

### ISSUE THREAD

**Issue by Haibit** [Tencent/ncnn#5053]
## detail | 详细描述 | 詳細な説明
模型是多个输出，但是在初始化后拿输出节点的时候（使用ncnn->output_names()接口），只能获取到节点23，请问怎么才能直接获取到所有的输出节点呢。
![image](https://github.com/Tencent/ncnn/assets/17947664/b3771c84-0c2e-4cd1-9e07-190685698722)

**Comment by Haibit** [comment]
目前多输入的节点名称是可以通过ncnn->input_names()接口直接获取到的

**Comment by Haibit** [comment]
ncnn->input_indexes()会有多个层数，ncnn->output_indexes()只有一个层数

**Comment by Haibit** [comment]
7767517
14 14
Input                    input.1                  0 1 input.1
Input                    onnx::Concat_1           0 1 onnx::Concat_1
Input                    onnx::Concat_2           0 1 onnx::Concat_2
Input                    onnx::Concat_3           0 1 onnx::Concat_3
MemoryData               linear.bias              0 1 linear.bias 0=128
Convolution              Conv_0                   1 1 input.1 onnx::Concat_14 0=4 1=3 3=2 13=1 5=1 6=36
Concat                   Concat_1                 2 1 onnx::Concat_1 onnx::Concat_14 input 0=1
Convolution              Conv_2                   1 1 input onnx::Concat_16 0=8 1=3 3=2 13=1 5=1 6=288
Concat                   Concat_3                 2 1 onnx::Concat_2 onnx::Concat_16 input.4 0=1
Convolution              Conv_4                   1 1 input.4 onnx::Concat_18 0=16 1=3 3=2 13=1 5=1 6=1152
Concat                   Concat_5                 2 1 onnx::Concat_3 onnx::Concat_18 input.8 0=1
Convolution              Conv_6                   1 1 input.8 onnx::MatMul_20 0=1 1=3 3=2 13=1 5=1 6=144
InnerProduct             MatMul_7                 1 1 onnx::MatMul_20 onnx::Add_22 0=128 2=896
BinaryOp                 Add_8                    2 1 linear.bias onnx::Add_22 23

**Comment by w8501** [comment]
请看wiki[[多个blob输入，多个blob输出，怎么做？](https://github.com/Tencent/ncnn/wiki/faq#%E5%A4%9A%E4%B8%AAblob%E8%BE%93%E5%85%A5%E5%A4%9A%E4%B8%AAblob%E8%BE%93%E5%87%BA%E6%80%8E%E4%B9%88%E5%81%9A)]

**Comment by Haibit** [comment]
> 请看wiki[[多个blob输入，多个blob输出，怎么做？](https://github.com/Tencent/ncnn/wiki/faq#%E5%A4%9A%E4%B8%AAblob%E8%BE%93%E5%85%A5%E5%A4%9A%E4%B8%AAblob%E8%BE%93%E5%87%BA%E6%80%8E%E4%B9%88%E5%81%9A)]

不是的，我想问的是，如何通过ncnn->output_names()接口获取你发的链接的里的"output1"，“output2”这两个节点名字，现在调用ncnn->input_names()是可以直接获取到“data1”,"data2"这两个节点名字的。

**Comment by Haibit** [comment]
> 7767517 14 14 Input input.1 0 1 input.1 Input onnx::Concat_1 0 1 onnx::Concat_1 Input onnx::Concat_2 0 1 onnx::Concat_2 Input onnx::Concat_3 0 1 onnx::Concat_3 MemoryData linear.bias 0 1 linear.bias 0=128 Convolution Conv_0 1 1 input.1 onnx::Concat_14 0=4 1=3 3=2 13=1 5=1 6=36 Concat Concat_1 2 1 onnx::Concat_1 onnx::Concat_14 input 0=1 Convolution Conv_2 1 1 input onnx::Concat_16 0=8 1=3 3=2 13=1 5=1 6=288 Concat Concat_3 2 1 onnx::Concat_2 onnx::Concat_16 input.4 0=1 Convolution Conv_4 1 1 input.4 onnx::Concat_18 0=16 1=3 3=2 13=1 5=1 6=1152 Concat Concat_5 2 1 onnx::Concat_3 onnx::Concat_18 input.8 0=1 Convolution Conv_6 1 1 input.8 onnx::MatMul_20 0=1 1=3 3=2 13=1 5=1 6=144 InnerProduct MatMul_7 1 1 onnx::MatMul_20 onnx::Add_22 0=128 2=896 BinaryOp Add_8 2 1 linear.bias onnx::Add_22 23

我在这里param里手动加上四个Output层不起作用

**Comment by Haibit** [comment]
Output                   onnx::Concat_14          1 0 onnx::Concat_14
Output                   onnx::Concat_16          1 0 onnx::Concat_16
Output                   onnx::Concat_18          1 0 onnx::Concat_18
Output                   onnx::Add_22             1 0 onnx::Add_22

结尾是这样加的

**Comment by w8501** [comment]
> > 7767517 14 14 Input input.1 0 1 input.1 Input onnx::Concat_1 0 1 onnx::Concat_1 Input onnx::Concat_2 0 1 onnx::Concat_2 Input onnx::Concat_3 0 1 onnx::Concat_3 MemoryData linear.bias 0 1 linear.bias 0=128 Convolution Conv_0 1 1 input.1 onnx::Concat_14 0=4 1=3 3=2 13=1 5=1 6=36 Concat Concat_1 2 1 onnx::Concat_1 onnx::Concat_14 input 0=1 Convolution Conv_2 1 1 input onnx::Concat_16 0=8 1=3 3=2 13=1 5=1 6=288 Concat Concat_3 2 1 onnx::Concat_2 onnx::Concat_16 input.4 0=1 Convolution Conv_4 1 1 input.4 onnx::Concat_18 0=16 1=3 3=2 13=1 5=1 6=1152 Concat Concat_5 2 1 onnx::Concat_3 onnx::Concat_18 input.8 0=1 Convolution Conv_6 1 1 input.8 onnx::MatMul_20 0=1 1=3 3=2 13=1 5=1 6=144 InnerProduct MatMul_7 1 1 onnx::MatMul_20 onnx::Add_22 0=128 2=896 BinaryOp Add_8 2 1 linear.bias onnx::Add_22 23
> 
> 我在这里param里手动加上四个Output层不起作用

ncnn 没有Output这个layer。使用转换工具转模型吧，不要手写。ncnn会判断如果这个blob没有consumer的话就认为他是输出。

**Comment by Haibit** [comment]
> > > 7767517 14 14 Input input.1 0 1 input.1 Input onnx::Concat_1 0 1 onnx::Concat_1 Input onnx::Concat_2 0 1 onnx::Concat_2 Input onnx::Concat_3 0 1 onnx::Concat_3 MemoryData linear.bias 0 1 linear.bias 0=128 Convolution Conv_0 1 1 input.1 onnx::Concat_14 0=4 1=3 3=2 13=1 5=1 6=36 Concat Concat_1 2 1 onnx::Concat_1 onnx::Concat_14 input 0=1 Convolution Conv_2 1 1 input onnx::Concat_16 0=8 1=3 3=2 13=1 5=1 6=288 Concat Concat_3 2 1 onnx::Concat_2 onnx::Concat_16 input.4 0=1 Convolution Conv_4 1 1 input.4 onnx::Concat_18 0=16 1=3 3=2 13=1 5=1 6=1152 Concat Concat_5 2 1 onnx::Concat_3 onnx::Concat_18 input.8 0=1 Convolution Conv_6 1 1 input.8 onnx::MatMul_20 0=1 1=3 3=2 13=1 5=1 6=144 InnerProduct MatMul_7 1 1 onnx::MatMul_20 onnx::Add_22 0=128 2=896 BinaryOp Add_8 2 1 linear.bias onnx::Add_22 23
> > 
> > 
> > 我在这里param里手动加上四个Output层不起作用
> 
> ncnn 没有Output这个layer。使用转换工具转模型吧，不要手写。ncnn会判断如果这个blob没有consumer的话就认为他是输出。

@w8501 这个param就是用网页版的转换工具得到的，没有多个输出层。所以尝试了一下手动写，但是会报错。

**Comment by Haibit** [comment]
也就是用网页版转换工具得到param，load模型之后使用ncnn->output_indexes()只有一个层数，只能得到一个输出节点。

**Comment by w8501** [comment]
> 也就是用网页版转换工具得到param，load模型之后使用ncnn->output_indexes()只有一个层数，只能得到一个输出节点。

那你可以根据你需要那层的output name去拿
比如在你这里是
`ex.extract("input.4", out_1);
ex.extract("input.8", out_2);
ex.extract("23", out_3);`

**Comment by Haibit** [comment]
> > 也就是用网页版转换工具得到param，load模型之后使用ncnn->output_indexes()只有一个层数，只能得到一个输出节点。
> 
> 那你可以根据你需要那层的output name去拿 比如在你这里是 `ex.extract("input.4", out_1); ex.extract("input.8", out_2); ex.extract("23", out_3);`

好的，那我理解其实就是转换工具的问题对吧，只能是手动去指定想要的输出层，即使onnx是多个输出的。Anyway，thanks.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
