### ISSUE TITLE
ncnn中一些类的封装关系

### ISSUE THREAD

**Issue by HuPengsheet** [Tencent/ncnn#5068]
## detail | 详细描述 | 詳細な説明
nihui，你好!
我最近在看ncnn的源码，发现了ncnn中把好多的类的一些属性和方法会额外在写一个ClassPrivate类里。比如Net里面有一个NetPrivate类，Net的构造函数里会把NetPrivate给new出来，这种设计是不是有一些特殊的好处，或者说这种编写方式有没有一种名字？

**Comment by nihui** [comment]
https://en.cppreference.com/w/cpp/language/pimpl

**Comment by HuPengsheet** [comment]
感谢回答！
