### ISSUE TITLE
Memory usage on 16bit calculation.

### ISSUE THREAD

**Issue by Alan-Turing-Ko** [Tencent/ncnn#507]
I've tested new 8, 16bit inference.
I expected memory usage will be half on 16bit inference than 32bit, but actual result went over my expectation.
On creating net, 11MB used for 32 bit model, but 16.5MB used for 16 bit model.
I turned off winograd, sgemm options for pure memory calculation.
Caffe model size is 12.2MB
What am I wrong?
Hope to any suggestions.

**Comment by liaocz** [comment]
I want to kown what platform for your testing?

**Comment by Alan-Turing-Ko** [comment]
Thanks for your reply.
I tested in ARM platform.
I use ncnn in android app.
And I measure in squeezenet example included in project.

        long initMem = Debug.getNativeHeapAllocatedSize();
        {
            InputStream assetsInputStream = getAssets().open("kkkkk.param.bin");
            int available = assetsInputStream.available();
            param = new byte[available];
            int byteCode = assetsInputStream.read(param);
            assetsInputStream.close();
        }
        {
            InputStream assetsInputStream = getAssets().open("kkkkk.bin");
            int available = assetsInputStream.available();
            bin = new byte[available];
            int byteCode = assetsInputStream.read(bin);
            assetsInputStream.close();
        }

        words = new byte[0];
        boolean binit = squeezencnn.Init(param, bin, words);
        long MemSize = Debug.getNativeHeapAllocatedSize() - initMem;

        Log.e("Net mem: ", String.valueOf(MemSize));

And one more question.
I convert my model into int8 using BUG1989/caffe-int8-convert-tools.
But when I inference I got all NaN values when pass conv layer.
What could be the problem?

**Comment by nihui** [comment]
ncnn now supports fp16 operations and takes up half the memory compared to fp32.
