### ISSUE TITLE
welcome to contribute: improve x86 compiler compatibility

### ISSUE THREAD

**Issue by nihui** [Tencent/ncnn#5072]
_mm256_set_m128 is only availble on gcc8+

https://github.com/Tencent/ncnn/blob/54a9a563e9913d3142782dac0e497f2be50075b5/src/layer/x86/shufflechannel_x86.cpp#L348C42-L348C42

**Comment by whyb** [comment]
```cpp
#if __GNUC__ > 7 || (__GNUC__ == 7 && (__GNUC_MINOR__ > 0 || (__GNUC_MINOR__ == 0 && __GNUC_PATCHLEVEL__ >= 0)))
// only availble on gcc8+
    __m256 _p1 = _mm256_set_m128(_mm_loadu_ps(ptr2), _mm_loadu_ps(ptr1));
#else
    __m256 _p1 = _mm256_loadu2_m128(ptr2, ptr1);
#endif
```
这样改？

**Comment by nihui** [comment]
> ```c++
> #if __GNUC__ > 7 || (__GNUC__ == 7 && (__GNUC_MINOR__ > 0 || (__GNUC_MINOR__ == 0 && __GNUC_PATCHLEVEL__ >= 0)))
> // only availble on gcc8+
>     __m256 _p1 = _mm256_set_m128(_mm_loadu_ps(ptr2), _mm_loadu_ps(ptr1));
> #else
>     __m256 _p1 = _mm256_loadu2_m128(ptr2, ptr1);
> #endif
> ```
> 
> 这样改？

用 insert 和 cast 实现两个 m128 合成一个 m256

**Comment by whyb** [comment]
> > ```c++
> > #if __GNUC__ > 7 || (__GNUC__ == 7 && (__GNUC_MINOR__ > 0 || (__GNUC_MINOR__ == 0 && __GNUC_PATCHLEVEL__ >= 0)))
> > // only availble on gcc8+
> >     __m256 _p1 = _mm256_set_m128(_mm_loadu_ps(ptr2), _mm_loadu_ps(ptr1));
> > #else
> >     __m256 _p1 = _mm256_loadu2_m128(ptr2, ptr1);
> > #endif
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样改？
> 
> 用 insert 和 cast 实现两个 m128 合成一个 m256

```cpp
#if __GNUC__ > 7 || (__GNUC__ == 7 && (__GNUC_MINOR__ > 0 || (__GNUC_MINOR__ == 0 && __GNUC_PATCHLEVEL__ >= 0)))
    // only availble on gcc8+
    __m256 _p1 = _mm256_set_m128(_mm_loadu_ps(ptr2), _mm_loadu_ps(ptr1));
#else
    __m256 _p1 = _mm256_castps128_ps256(_mm_loadu_ps(ptr1));
    _p1 = _mm256_insertf128_ps(_p1, _mm_loadu_ps(ptr2), 1);
#endif
```

这样？
