### ISSUE TITLE
请问python版ncnn怎么构造通道数大于4的mat？

### ISSUE THREAD

**Issue by tianyu06030020** [Tencent/ncnn#5080]
real_b = cv2.imread('real_b.jpg')
ncnn_real_b = ncnn.Mat.from_pixels(real_b, ncnn.Mat.PixelType.PIXEL_BGR2RGB, real_b.shape[0], real_b.shape[1])
ncnn_real_b.substract_mean_normalize(mean_list, normal_list)

mask_b = cv2.imread('mask_b.jpg')
ncnn_mask_b = ncnn.Mat.from_pixels(mask_b, ncnn.Mat.PixelType.PIXEL_BGR2RGB, mask_b.shape[0], mask_b.shape[1])
ncnn_mask_b.substract_mean_normalize(mean_list, normal_list)

cat_ncnn_mat = ncnn.Mat(160, 160, 1, 6)？

我想把两张图按通道concat成6通道的，就是把ncnn_real_b和ncnn_mask_b拼到一起，有什么办法吗？c++我是按通道memcpy的，python试了好像不行。

**Comment by nihui** [comment]
可以用 numpy 拼好，再转成 ncnn Mat

**Comment by tianyu06030020** [comment]
> 可以用 numpy 预处理，拼好，再转成 ncnn Mat
> 
> 或者在模型param开头添加一层Concat

好的，感谢！
