### ISSUE TITLE
MobileNetV3 转换后结果不正确。

### ISSUE THREAD

**Issue by znsoftm** [Tencent/ncnn#5086]
## error log | 日志或报错信息 | ログ
mobilenet v3  通过pnnx转换成ncnn后结果不正确。 所有模型，测试程序和测试数据在附件zip中。
## how to reproduce | 复现步骤 | 再現方法
1. 运行 convert_to_script.py 转成trace模型和onnx模型
2.  使用pnnx将trace模型转换为ncnn 模型
3. 运行test_ncnn.py 得到结果为3 (不正确，正确的结果是test_onnx.py 得到的0)

## more | 其他 | その他

[ori_lang_class.zip](https://github.com/Tencent/ncnn/files/12891105/ori_lang_class.zip)

**Comment by znsoftm** [comment]
这个其实就是paddleOCR的方向检测模型。

**Comment by znsoftm** [comment]
上一次提交的Issue在当时的sample上结果是对的，但是换一张图就不work.

**Comment by znsoftm** [comment]
经过测试发现输出结果与在pt->traced过程的数据有一定关系，是不是里面有分支，trace并不对，难道需要script转换的pt? 但是script pt用pnnx时会挂掉，无输出 模型。

**Comment by nihui** [comment]
把 test_onnx.py 的输入预处理，搬到 test_ncnn.py 里面，出来就一样了

```python
    img_src = cv2.imread(img_path)
    resized_image = img_src.transpose((2, 0, 1)) / 255

    resized_image -= 0.5
    resized_image /= 0.5
    padding_im = np.zeros((resized_image.shape[0], resized_image.shape[1], resized_image.shape[2]), dtype=np.float32)
    padding_im[:, :, : resized_image.shape[2]] = resized_image

    # ncnn does not need batch dimension
    # padding_im=padding_im[np.newaxis,:]

    mat_in = ncnn.Mat(padding_im)
```
