### ISSUE TITLE
有计划支持鸿蒙原生吗

### ISSUE THREAD

**Issue by harrywater** [Tencent/ncnn#5088]
## detail | 详细描述 | 詳細な説明
目前很多app已经在做鸿蒙原生兼容，对于一些AI SDK也会有述求需求鸿蒙原生兼容，ncnn库是否有计划推出？

**Comment by nihui** [comment]
ncnn是纯cpp库，天然兼容的  :D

**Comment by harrywater** [comment]
有人回答解惑吗

**Comment by nihui** [comment]
修复了ohos编译错误 https://github.com/Tencent/ncnn/commit/3eb2969db9fa083260ff966ed9b468902a5f7f51

编译方法
```shell
cmake -DCMAKE_TOOLCHAIN_FILE=hwsdk/hmscore/3.0.0_7/native/build/cmake/ohos.toolchain.cmake ..
make -j4
make install
```

但是ohos的工具链缺少很多功能，缺少openmp，缺少pthread，缺少vulkan，不支持armv8.4的指令集等等
目前建议用android版本，待后面ohos更新工具链后再考虑发布预编译包

**Comment by zcl912** [comment]
> 修复了ohos编译错误 [3eb2969](https://github.com/Tencent/ncnn/commit/3eb2969db9fa083260ff966ed9b468902a5f7f51)
> 
> 编译方法
> 
> ```shell
> cmake -DCMAKE_TOOLCHAIN_FILE=hwsdk/hmscore/3.0.0_7/native/build/cmake/ohos.toolchain.cmake ..
> make -j4
> make install
> ```
> 
> 但是ohos的工具链缺少很多功能，缺少openmp，缺少pthread，缺少vulkan，不支持armv8.4的指令集等等 目前建议用android版本，待后面ohos更新工具链后再考虑发布预编译包

大佬，如果在鸿蒙上部署，因为缺少一些功能，这个有没有比较啊，速度上的差异大概有多大，网络结构VGG形式的

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5474
