### ISSUE TITLE
File path bug '-' → '_'

### ISSUE THREAD

**Issue by yayoimizuha** [Tencent/ncnn#5089]
## error log | 日志或报错信息 | ログ
```
fopen /home/tomokazu/PycharmProjects/helloproject_ai/retinaface_resnet50.pnnx.param failed
fopen /home/tomokazu/PycharmProjects/helloproject_ai/retinaface_resnet50_pnnx.py failed
```
## context | 编译/运行环境 | バックグラウンド
I'm using pnnx cmdline-tool  convert to ncnn file from torchscript file.
I was encounted fopen error.
I saw logs carefully,I found file path was changed.
`helloproject-ai` -> `helloproject_ai`
## how to reproduce | 复现步骤 | 再現方法
1. ./pnnx /home/tomokazu/PycharmProjects/helloproject-ai/retinaface_resnet50.ts
2.
3.

## more | 其他 | その他
I can use Japanese and little English.

**Comment by whyb** [comment]
You can try adding `"` symbols to both ends of the full path string.

e.g. 
```
./pnnx "/home/tomokazu/PycharmProjects/helloproject-ai/retinaface_resnet50.ts"
```

**Comment by nihui** [comment]
confirmed bug

workaround: use a path without special characters

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5099

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/efcfe95a42ec5a08a1283818f3409992854cc0a6
