### ISSUE TITLE
pip install -U ncnn errors with M2

### ISSUE THREAD

**Issue by Baiyuetribe** [Tencent/ncnn#5090]
## error log | 日志或报错信息 | ログ
```log
'/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ncnn/ncnn.cpython-310-darwin.so' 
(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```
需要修复兼容性，临时办法：从源码进行安装

**Comment by Hideousmon** [comment]
#5020 有包含对这个问题的修复，可以使用(测试) [built wheels](https://github.com/Hideousmon/ncnn-gpu-pre-verification/tree/main/built-wheels) 里面的wheel.

**Comment by Baiyuetribe** [comment]
从现有的ci来看，是否[这里](https://github.com/Tencent/ncnn/blob/3f79c4ff103780d6e6def9224fe2dab2406b04e3/.github/workflows/release-python.yml#L53C10-L53C76)的  `- { os: macos-latest, arch: arm64,      build: 'cp*'            }`为apple arm64的action?

资料显示apple arm64的运行环境可以指定为`macos-latest-xlarge`.
附：https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by nihui** [comment]
fix merged
