### ISSUE TITLE
Android的squeezenet demo，测试速度160ms，和caffe持平，请问这正常吗？

### ISSUE THREAD

**Issue by BKZero** [Tencent/ncnn#51]
rt
up主你们测试的时候都是什么样的速度？看新智源采访说能提速2~4倍，然而自己跑出来的速度ncnn和caffe都是160ms。
是在编译过程中自己漏掉了什么编译选项吗？

**Comment by nihui** [comment]
不可能完全一样的，总有个快慢吧 ...

**Comment by BKZero** [comment]
基本差不多，不同图片和测试次数的时间也会有差别。刚才重新多测了几次
ncnn的时间基本在160ms左右，快的时候150ms，慢的到180ms
caffe demo的时间在160ms～190ms，如果比较平均的话大概ncnn能快10ms？

**Comment by nihui** [comment]
测试方法是怎样的？连续跑多次才能看出差距，demo 里选一张图跑一次，首次的速度是不可靠的

**Comment by BKZero** [comment]
你的意思要单张图片循环多次看平均？我是直接选图-跑-再选图-再跑。

**Comment by nihui** [comment]
嗯，是这样。选图，跑，选图，跑是看不出的，第一遍会受到很多干扰

**Comment by BKZero** [comment]
两张图，分别循环forward100次
第一张图caffe 133.44ms，ncnn139.82ms
第二张图caffe 138.55ms，ncnn140.20ms     TAT。。。。。

**Comment by BKZero** [comment]
在读native层代码，看是不是有什么多余因素。。刚刚的测试结果是去掉了native层log后得出的。

**Comment by BKZero** [comment]
试了下，即便循环内不打log，尽可能只保留forward操作，结果并没有特别大的改变。。。
也尝试过更改线程数，然并卵。。。

**Comment by nihui** [comment]
可能编译上有问题，试试看我这里预先编译好的 libncnn.a
https://github.com/Tencent/ncnn/releases

**Comment by BKZero** [comment]
并没有变化。。。或许squeezenet体现不出性能上的差异？也或许我仔细清掉再重来一遍再看看。。。

**Comment by blackcat-tech** [comment]
你好，Android demo，在eclipse中能正常运行吗？

遇到问题：Caused by: java.lang.UnsatisfiedLinkError: Couldn't load squeezencnn: findLibrary returned null

**Comment by BKZero** [comment]
android studio都出了这么多年了干嘛还用eclipse……这不是自己给自己找别扭么

**Comment by blackcat-tech** [comment]
@BKZero example是个eclipse项目吧？所以，就直接用它了。。。应该与开发工具没关系吧？

**Comment by BKZero** [comment]
安卓工程啊。既然是安卓工程肯定AS更方便。。。

**Comment by blackcat-tech** [comment]
@BKZero  工具先放一边，重点是如何在app中跑起来~ 哈哈  希望大神们能出个教程贴，新手对.a,.so文件编译生成，很陌生~

**Comment by minipeach** [comment]
iphone6s，caffe2 squeezenet 40ms

**Comment by Andrawzyf** [comment]
@BKZero 楼主可以请教你一下怎么测这个速度么

**Comment by Andrawzyf** [comment]
@minipeach 可以请教下怎么测试速度么

**Comment by zhushuhao** [comment]
使用官方so文件可以正常使用，但是使用我自己编译的so替换官方的so后，完全没有效果，什么都检测不出来，可能是哪里出了问题呢？

**Comment by nihui** [comment]
最新的demo可参考 https://github.com/nihui/ncnn-android-squeezenet
