### ISSUE TITLE
GirdSample算子不支持转换ncnn格式吗？

### ISSUE THREAD

**Issue by yuxiao-ash** [Tencent/ncnn#5101]
onnx2ncnn 转换模型时报错现象如下：
## error log | 日志或报错信息 | ログ
GridSample not supported yet!
  # align_corners=0
  # mode=bilinear
  # padding_mode=zeros

我看到src/layer目录下有gridsample.h和gridsample.cpp，目前onnx2ncnn是不支持GridSample这个算子的原因是什么呢？
我可以在自己本地通过做什么修改来成功转换吗？

**Comment by nihui** [comment]
使用 pnnx 转换 torch 模型，无痛支持的！如有问题，可reopen issue继续交流
