### ISSUE TITLE
layer F.scaled_dot_product_attention not exists or registered

### ISSUE THREAD

**Issue by is-sixfive** [Tencent/ncnn#5102]
## model | 模型 | モデル

1. original model
chilloutmix-NiPrunedFp16Fix.safetensors
## how to reproduce | 复现步骤 | 再現方法
1.先将模型chilloutmix-NiPrunedFp16Fix.safetensors转换为.pt
2.用pnnx转为ncnn，转换成功
3.采用ncnn推理报错：layer F.scaled_dot_product_attention not exists or registered

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5107

**Comment by nihui** [comment]
已修复，用最新的pnnx

**Comment by liuwuwuwu** [comment]
> 已修复，用最新的pnnx

刚试过不报错了，感谢哈

**Comment by is-sixfive** [comment]
> 已修复，用最新的pnnx
刚试过不报错了，感谢哈
