### ISSUE TITLE
NCNN推理结果和python不一致

### ISSUE THREAD

**Issue by hfwanguanghui** [Tencent/ncnn#5108]
## detail | 详细描述 | 詳細な説明
[model.zip](https://github.com/Tencent/ncnn/files/13184478/model.zip)
如上附件是我的模型，没有有什么特殊算子，使用python推理和ncnn推理得不到一样的结果。
pytorch：
def get_pt():
    model = torch.jit.load('model/test.pt')
    input_data1 = torch.ones([1,15,256,1])
    input_data2 = torch.zeros([1,1,96])
    out = model(input_data1, input_data2)
    print(out[0][:,:,0:10])
    print(out[1][:,:,0:10])

out：
tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.5833, 0.0000, 1.6946, 0.9135,
          0.0000, 0.0000]]], grad_fn=<SliceBackward0>)
tensor([[[ 0.0119,  0.0022, -0.0045,  0.0096,  0.0090,  0.0132, -0.0076,
           0.0158,  0.0114, -0.0087]]], grad_fn=<SliceBackward0>)
324 [[[0.        0.        0.        0.        0.5832769 0.        1.6946273

onnx：
def get_onnx():
    # 加载ONNX模型
    model_path = '/model/test.onnx'

    #model_path = 'Y:/adla-toolkit-binary-2.0.10.3/CNN_model.onnx'
    sess = ort.InferenceSession(model_path)

    # 准备输入数据
    input_names = [input.name for input in sess.get_inputs()]
    input_shapes = [input.shape for input in sess.get_inputs()]

    input_data1 = np.ones(input_shapes[0]).astype(np.float32)
    input_data2 = np.zeros(input_shapes[1]).astype(np.float32)

    # 进行推理
    output_names = [output.name for output in sess.get_outputs()]
    outputs = sess.run(output_names, {input_names[0]: input_data1, input_names[1]: input_data2})
    #outputs = sess.run(output_names, {input_names[0]: input_data1})

    # 打印输出结果
    for output, output_name in zip(outputs, output_names):
        print(output_name, output[:,:,0:10])
out：
324 [[[0.        0.        0.        0.        0.5832769 0.        1.6946273
   0.9134713 0.        0.       ]]]
224 [[[ 0.01191645  0.00223782 -0.00451431  0.00960346  0.00895633
    0.01319804 -0.00755622  0.01578778  0.01140068 -0.00871257]]]
如上，pytorch推理和onnx推理完全一致。

NCNN推理：

void test1(char *_param, char *bin_)
{
    ncnn::Net net;
   
    net.load_param(_param);
    net.load_model(bin_);
    std::cout<<"GO.."<<std::endl;
    //ex.set_num_threads(1);
    ncnn::Mat nnet_out;
    ncnn::Mat ncnn_hn_0;
    ncnn_hn_0.create(1,1,96);
    ncnn_hn_0.fill(0.0f);

    float* mag = new float[256*15];
    for (int j = 0; j < 2; j ++)
    {

        auto start = std::chrono::high_resolution_clock::now();
        for(int i = 0 ; i < 256*15 ; i++)
        {
            mag[i] = 1.0f;
        }

        ncnn::Extractor ex = net.create_extractor();
        ncnn::Mat ncnn_inFlt(256,15,1,mag);

        //std::cout<<"ncnn_inFlt=";
        float * f_ncnn_inFlt = (float *)ncnn_inFlt.data;
       /*for (size_t i = 0; i < 10; i++)
        {
            std::cout<<f_ncnn_inFlt[i]<<" ";
        }
        std::cout<<std::endl;*/

        float *f_ncnn_hn_0 = (float *)ncnn_hn_0.data;
        /*std::cout<<"before net h0=";
        for (size_t i = 0; i < 10; i++)
        {
            std::cout<<f_ncnn_hn_0[i]<<" ";
        }
        std::cout<<std::endl;*/

        ex.input("in0",ncnn_inFlt);
        //std::cout<<"---0-----\n";
        ex.input("in1",ncnn_hn_0);
        std::cout<<"---1-----\n";
 
      

   

        ex.extract("out0",nnet_out);
        
       //std::cout<<"---2-----\n";

        float *f_nnet_out = (float *)nnet_out.data;
        
        //std::cout<<std::endl;
        std::cout<<"net out i =" <<j<<std::endl;

        for (size_t i = 0; i < 20; i++)
        {
            std::cout<<f_nnet_out[i]<<" ";
        }
        std::cout<<std::endl;

        ncnn::Mat h0_out;
        ex.extract("out1",ncnn_hn_0);
        //std::cout<<"---3-----\n";
     

        float *f_ncnn_hn_1 = (float *)ncnn_hn_0.data;
        /*std::cout<<"after net h0=";
        for (size_t i = 0; i < 10; i++)
        {
            std::cout<<f_ncnn_hn_1[i]<<" ";
        }
        std::cout<<std::endl;*/

        auto end = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();
        std::cout << "s函数运行时间：" << duration << " 毫秒" << std::endl;

    }

}

PC Linux out:
AAAAAAAAAAAAAAGO..
---1-----
net out i =0
0 2.0077 0.135289 0.850866 0.464657 1.43884 1.77429 0.705607 0.00828147 0 0.87667 0 1.33143 0.981268 0 0 0 0 0.106536 0.324174 
s函数运行时间：3 毫秒
---1-----
net out i =1
0.271975 0.413422 0 0.0337885 0.23191 0 0 0 0.578095 0.36221 0.0871347 0 0 0 0.167736 0 0 0 0.514903 0 
s函数运行时间：3 毫秒

Arm Linux 开发板结果：
AAAAAAAAAAAAAAGO..
---1-----
net out i =0
1.07922 3.11123 0 1.28085 1.22089 0.299432 2.66096 0.761451 0.558493 0 0.82165 0 2.44196 0.0690197 1.66714 0 0 0 1.65503 0
s函数运行时间：18 毫秒
---1-----
net out i =1
0.139273 0.256149 0 0.122522 0.259072 0.0834974 0.0220155 0 0.360854 0.0810971 0.107429 0 0 0 0 0 0 0 0.183737 0
s函数运行时间：14 毫秒

运行pnnx方式如下：
 pnnx test_jit.pt fp16=0
pnnxparam = test_jit.pnnx.param
pnnxbin = test_jit.pnnx.bin
pnnxpy = test_jit_pnnx.py
pnnxonnx = test_jit.pnnx.onnx
ncnnparam = test_jit.ncnn.param
ncnnbin = test_jit.ncnn.bin
ncnnpy = test_jit_ncnn.py
fp16 = 0
optlevel = 2
device = cpu
inputshape = 
inputshape2 = 
customop = 
moduleop = 
############# pass_level0
inline module = models.model.connection
inline module = models.model.convtranspose2d
inline module = models.model.normal_conv2d
############# pass_level3
open failed
############# pass_level5
make_slice_expression input 20
make_slice_expression input 18
make_slice_expression input 16
make_slice_expression input 14
make_slice_expression input 12
make_slice_expression input 10
make_slice_expression input 8
############# pass_ncnn

所得 ncnn 结果在附件中
[ncnn_out.zip](https://github.com/Tencent/ncnn/files/13184601/ncnn_out.zip)

以上，
模型是两输入，两输出，一个输入shape是[1,15,256,1] 使用全 1 ，第二个输入是[1,1,96],使用全0.
第一个输出shape是[1,1,257] ,第二个输出shape是[1,1,96]
1.NCNN模型推理在Armv7开发版和x86_64 PC Liunx结果不一致。
2.NCNN推理模型和onnx ，torch.jit.save的pt文件 推理不一致。

希望大佬帮忙看一下，我已经调了很就都没有正确。也用了最新的rep，都不行。

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#disable-fp16
