### ISSUE TITLE
如何确认是否成功使用GPU？

### ISSUE THREAD

**Issue by 408550969** [Tencent/ncnn#5111]
## detail | 详细描述 | 詳細な説明
我在load param 之前 使用opt.use_vulkan_compute=true; 虽然能跑但是实际测下来和CPU没有区别。我用的库是ncnn-20230816-android-vulkan-shared 预编译库，CPU能预测出结果。
我用的安卓11，在系统里也搜到了vulkan的库，编译的时候也把vulkan.h路径包进去了。

**Comment by nihui** [comment]
加载的时候，stderr / adb logcat 会输出 gpu 信息

**Comment by 408550969** [comment]
logcat没有搜到stderr ，我测了一下use_vulkan_compute=true时 GPU使用率和CPU使用率和flase一样，应该是没有跑在GPU上。这是库的问题吗，我需要自己编译一个库吗？

**Comment by nihui** [comment]
logcat 搜索 ncnn

**Comment by 408550969** [comment]
ncnn  : no vulkan device。 这是没有找到vulkan 的库，还是这个设备不支持vulkan？我问了同事，他们说是支持的。

**Comment by nihui** [comment]
具体是什么设备呢

**Comment by 408550969** [comment]
8155

**Comment by 408550969** [comment]
确认了是设备支持vulkan，但是没有打开

**Comment by 408550969** [comment]
现在NCNN vulkan可以跑了，但是速度很慢，跑两个模型整个流程下来需要150多ms，而CPU是在60ms左右，MNN的GPU在60多ms。下面我搜ncnn输出的log，是否有需要改动的地方？
ncnn    : [0 Adreno (TM) 640]  queueC=0[3]  queueG=0[3]  queueT=0[3]
ncnn    : [0 Adreno (TM) 640]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=1
ncnn    : [0 Adreno (TM) 640]  fp16-p/s/a=1/0/0  int8-p/s/a=1/0/1
ncnn    : [0 Adreno (TM) 640]  subgroup=64  basic/vote/ballot/shuffle=1/1/0/1
ncnn    : [0 Adreno (TM) 640]  fp16-matrix-16_8_8/16_8_16/16_16_16=0/0/0

**Comment by 408550969** [comment]
我用的模式是yolov5和pipnet，param如下。在检测到人脸和landmark的情况下，vulkan的CPU使用率比非vulkan还高，GPU使用率是有提升的，说明是跑在GPU上。
7767517
161 183
Input            images                   0 1 images
Convolution      Conv_0                   1 1 images 114 0=16 1=6 11=6 2=1 12=1 3=2 13=2 4=2 14=2 15=2 16=2 5=1 6=1728
Swish            Mul_2                    1 1 114 116
Convolution      Conv_3                   1 1 116 117 0=24 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=3456
Swish            Mul_5                    1 1 117 119
Split            splitncnn_0              1 2 119 119_splitncnn_0 119_splitncnn_1
Convolution      Conv_6                   1 1 119_splitncnn_1 120 0=12 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=288
Swish            Mul_8                    1 1 120 122
Split            splitncnn_1              1 2 122 122_splitncnn_0 122_splitncnn_1
Convolution      Conv_9                   1 1 122_splitncnn_1 123 0=12 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=144
Swish            Mul_11                   1 1 123 125
Convolution      Conv_12                  1 1 125 126 0=12 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=1296
Swish            Mul_14                   1 1 126 128
BinaryOp         Add_15                   2 1 122_splitncnn_0 128 129 0=0
Convolution      Conv_16                  1 1 119_splitncnn_0 130 0=12 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=288
Swish            Mul_18                   1 1 130 132
Concat           Concat_19                2 1 129 132 133 0=0
Convolution      Conv_20                  1 1 133 134 0=24 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=576
Swish            Mul_22                   1 1 134 136
Convolution      Conv_23                  1 1 136 137 0=40 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=8640
Swish            Mul_25                   1 1 137 139
Split            splitncnn_2              1 2 139 139_splitncnn_0 139_splitncnn_1
Convolution      Conv_26                  1 1 139_splitncnn_1 140 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=800
Swish            Mul_28                   1 1 140 142
Split            splitncnn_3              1 2 142 142_splitncnn_0 142_splitncnn_1
Convolution      Conv_29                  1 1 142_splitncnn_1 143 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=400
Swish            Mul_31                   1 1 143 145
Convolution      Conv_32                  1 1 145 146 0=20 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=3600
Swish            Mul_34                   1 1 146 148
BinaryOp         Add_35                   2 1 142_splitncnn_0 148 149 0=0
Convolution      Conv_36                  1 1 139_splitncnn_0 150 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=800
Swish            Mul_38                   1 1 150 152
Concat           Concat_39                2 1 149 152 153 0=0
Convolution      Conv_40                  1 1 153 154 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1600
Swish            Mul_42                   1 1 154 156
Split            splitncnn_4              1 2 156 156_splitncnn_0 156_splitncnn_1
Convolution      Conv_43                  1 1 156_splitncnn_1 157 0=80 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=28800
Swish            Mul_45                   1 1 157 159
Split            splitncnn_5              1 2 159 159_splitncnn_0 159_splitncnn_1
Convolution      Conv_46                  1 1 159_splitncnn_1 160 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=3200
Swish            Mul_48                   1 1 160 162
Split            splitncnn_6              1 2 162 162_splitncnn_0 162_splitncnn_1
Convolution      Conv_49                  1 1 162_splitncnn_1 163 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1600
Swish            Mul_51                   1 1 163 165
Convolution      Conv_52                  1 1 165 166 0=40 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=14400
Swish            Mul_54                   1 1 166 168
BinaryOp         Add_55                   2 1 162_splitncnn_0 168 169 0=0
Split            splitncnn_7              1 2 169 169_splitncnn_0 169_splitncnn_1
Convolution      Conv_56                  1 1 169_splitncnn_1 170 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1600
Swish            Mul_58                   1 1 170 172
Convolution      Conv_59                  1 1 172 173 0=40 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=14400
Swish            Mul_61                   1 1 173 175
BinaryOp         Add_62                   2 1 169_splitncnn_0 175 176 0=0
Convolution      Conv_63                  1 1 159_splitncnn_0 177 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=3200
Swish            Mul_65                   1 1 177 179
Concat           Concat_66                2 1 176 179 180 0=0
Convolution      Conv_67                  1 1 180 181 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=6400
Swish            Mul_69                   1 1 181 183
Split            splitncnn_8              1 2 183 183_splitncnn_0 183_splitncnn_1
Convolution      Conv_70                  1 1 183_splitncnn_1 184 0=160 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=115200
Swish            Mul_72                   1 1 184 186
Split            splitncnn_9              1 2 186 186_splitncnn_0 186_splitncnn_1
Convolution      Conv_73                  1 1 186_splitncnn_1 187 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=12800
Swish            Mul_75                   1 1 187 189
Split            splitncnn_10             1 2 189 189_splitncnn_0 189_splitncnn_1
Convolution      Conv_76                  1 1 189_splitncnn_1 190 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=6400
Swish            Mul_78                   1 1 190 192
Convolution      Conv_79                  1 1 192 193 0=80 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=57600
Swish            Mul_81                   1 1 193 195
BinaryOp         Add_82                   2 1 189_splitncnn_0 195 196 0=0
Convolution      Conv_83                  1 1 186_splitncnn_0 197 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=12800
Swish            Mul_85                   1 1 197 199
Concat           Concat_86                2 1 196 199 200 0=0
Convolution      Conv_87                  1 1 200 201 0=160 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=25600
Swish            Mul_89                   1 1 201 203
Convolution      Conv_90                  1 1 203 204 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=12800
Swish            Mul_92                   1 1 204 206
Split            splitncnn_11             1 2 206 206_splitncnn_0 206_splitncnn_1
Pooling          MaxPool_93               1 1 206_splitncnn_1 207 0=0 1=5 11=5 2=1 12=1 3=2 13=2 14=2 15=2 5=1
Split            splitncnn_12             1 2 207 207_splitncnn_0 207_splitncnn_1
Pooling          MaxPool_94               1 1 207_splitncnn_1 208 0=0 1=5 11=5 2=1 12=1 3=2 13=2 14=2 15=2 5=1
Split            splitncnn_13             1 2 208 208_splitncnn_0 208_splitncnn_1
Pooling          MaxPool_95               1 1 208_splitncnn_1 209 0=0 1=5 11=5 2=1 12=1 3=2 13=2 14=2 15=2 5=1
Concat           Concat_96                4 1 206_splitncnn_0 207_splitncnn_0 208_splitncnn_0 209 210 0=0
Convolution      Conv_97                  1 1 210 211 0=160 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=51200
Swish            Mul_99                   1 1 211 213
Convolution      Conv_100                 1 1 213 214 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=12800
Swish            Mul_102                  1 1 214 216
Split            splitncnn_14             1 2 216 216_splitncnn_0 216_splitncnn_1
Interp           Resize_107               1 1 216_splitncnn_1 221 0=1 1=2.000000e+00 2=2.000000e+00 3=0 4=0 6=0
Concat           Concat_108               2 1 221 183_splitncnn_0 222 0=0
Split            splitncnn_15             1 2 222 222_splitncnn_0 222_splitncnn_1
Convolution      Conv_109                 1 1 222_splitncnn_1 223 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=6400
Swish            Mul_111                  1 1 223 225
Convolution      Conv_112                 1 1 225 226 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1600
Swish            Mul_114                  1 1 226 228
Convolution      Conv_115                 1 1 228 229 0=40 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=14400
Swish            Mul_117                  1 1 229 231
Convolution      Conv_118                 1 1 222_splitncnn_0 232 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=6400
Swish            Mul_120                  1 1 232 234
Concat           Concat_121               2 1 231 234 235 0=0
Convolution      Conv_122                 1 1 235 236 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=6400
Swish            Mul_124                  1 1 236 238
Convolution      Conv_125                 1 1 238 239 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=3200
Swish            Mul_127                  1 1 239 241
Split            splitncnn_16             1 2 241 241_splitncnn_0 241_splitncnn_1
Interp           Resize_132               1 1 241_splitncnn_1 246 0=1 1=2.000000e+00 2=2.000000e+00 3=0 4=0 6=0
Concat           Concat_133               2 1 246 156_splitncnn_0 247 0=0
Split            splitncnn_17             1 2 247 247_splitncnn_0 247_splitncnn_1
Convolution      Conv_134                 1 1 247_splitncnn_1 248 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1600
Swish            Mul_136                  1 1 248 250
Convolution      Conv_137                 1 1 250 251 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=400
Swish            Mul_139                  1 1 251 253
Convolution      Conv_140                 1 1 253 254 0=20 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=3600
Swish            Mul_142                  1 1 254 256
Convolution      Conv_143                 1 1 247_splitncnn_0 257 0=20 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1600
Swish            Mul_145                  1 1 257 259
Concat           Concat_146               2 1 256 259 260 0=0
Convolution      Conv_147                 1 1 260 261 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1600
Swish            Mul_149                  1 1 261 263
Split            splitncnn_18             1 2 263 263_splitncnn_0 263_splitncnn_1
Convolution      Conv_150                 1 1 263_splitncnn_1 264 0=40 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=14400
Swish            Mul_152                  1 1 264 266
Concat           Concat_153               2 1 266 241_splitncnn_0 267 0=0
Split            splitncnn_19             1 2 267 267_splitncnn_0 267_splitncnn_1
Convolution      Conv_154                 1 1 267_splitncnn_1 268 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=3200
Swish            Mul_156                  1 1 268 270
Convolution      Conv_157                 1 1 270 271 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1600
Swish            Mul_159                  1 1 271 273
Convolution      Conv_160                 1 1 273 274 0=40 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=14400
Swish            Mul_162                  1 1 274 276
Convolution      Conv_163                 1 1 267_splitncnn_0 277 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=3200
Swish            Mul_165                  1 1 277 279
Concat           Concat_166               2 1 276 279 280 0=0
Convolution      Conv_167                 1 1 280 281 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=6400
Swish            Mul_169                  1 1 281 283
Split            splitncnn_20             1 2 283 283_splitncnn_0 283_splitncnn_1
Convolution      Conv_170                 1 1 283_splitncnn_1 284 0=80 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=57600
Swish            Mul_172                  1 1 284 286
Concat           Concat_173               2 1 286 216_splitncnn_0 287 0=0
Split            splitncnn_21             1 2 287 287_splitncnn_0 287_splitncnn_1
Convolution      Conv_174                 1 1 287_splitncnn_1 288 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=12800
Swish            Mul_176                  1 1 288 290
Convolution      Conv_177                 1 1 290 291 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=6400
Swish            Mul_179                  1 1 291 293
Convolution      Conv_180                 1 1 293 294 0=80 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=57600
Swish            Mul_182                  1 1 294 296
Convolution      Conv_183                 1 1 287_splitncnn_0 297 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=12800
Swish            Mul_185                  1 1 297 299
Concat           Concat_186               2 1 296 299 300 0=0
Convolution      Conv_187                 1 1 300 301 0=160 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=25600
Swish            Mul_189                  1 1 301 303
Convolution      Conv_190                 1 1 263_splitncnn_0 304 0=18 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=720
Reshape          Reshape_202              1 1 304 316 0=-1 1=6 2=3
Permute          Transpose_203            1 1 316 output 0=1
Convolution      Conv_204                 1 1 283_splitncnn_0 318 0=18 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1440
Reshape          Reshape_216              1 1 318 330 0=-1 1=6 2=3
Permute          Transpose_217            1 1 330 331 0=1
Convolution      Conv_218                 1 1 303 332 0=18 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=2880
Reshape          Reshape_230              1 1 332 344 0=-1 1=6 2=3
Permute          Transpose_231            1 1 344 345 0=1


7767517
104 118
Input            input_1                  0 1 input_1
Convolution      Conv_0                   1 1 input_1 545 0=16 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=432
HardSwish        Mul_5                    1 1 545 295 0=1.666667e-01 1=5.000000e-01
Split            splitncnn_0              1 2 295 295_splitncnn_0 295_splitncnn_1
ConvolutionDepthWise Conv_6                   1 1 295_splitncnn_1 548 0=16 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=144 7=16
ReLU             Relu_7                   1 1 548 298
Convolution      Conv_8                   1 1 298 551 0=16 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=256
BinaryOp         Add_9                    2 1 295_splitncnn_0 551 301 0=0
Convolution      Conv_10                  1 1 301 554 0=64 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1024
ReLU             Relu_11                  1 1 554 304
ConvolutionDepthWise Conv_12                  1 1 304 557 0=64 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=576 7=64
ReLU             Relu_13                  1 1 557 307
Convolution      Conv_14                  1 1 307 560 0=24 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1536
Split            splitncnn_1              1 2 560 560_splitncnn_0 560_splitncnn_1
Convolution      Conv_15                  1 1 560_splitncnn_1 563 0=72 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1728
ReLU             Relu_16                  1 1 563 312
ConvolutionDepthWise Conv_17                  1 1 312 566 0=72 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=648 7=72
ReLU             Relu_18                  1 1 566 315
Convolution      Conv_19                  1 1 315 569 0=24 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1728
BinaryOp         Add_20                   2 1 560_splitncnn_0 569 318 0=0
Convolution      Conv_21                  1 1 318 572 0=72 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=1728
ReLU             Relu_22                  1 1 572 321
ConvolutionDepthWise Conv_23                  1 1 321 575 0=72 1=5 11=5 2=1 12=1 3=2 13=2 4=2 14=2 15=2 16=2 5=1 6=1800 7=72
ReLU             Relu_24                  1 1 575 324
Convolution      Conv_25                  1 1 324 578 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=2880
Split            splitncnn_2              1 2 578 578_splitncnn_0 578_splitncnn_1
Convolution      Conv_26                  1 1 578_splitncnn_1 581 0=120 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=4800
ReLU             Relu_27                  1 1 581 329
ConvolutionDepthWise Conv_28                  1 1 329 584 0=120 1=5 11=5 2=1 12=1 3=1 13=1 4=2 14=2 15=2 16=2 5=1 6=3000 7=120
ReLU             Relu_29                  1 1 584 332
Convolution      Conv_30                  1 1 332 587 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=4800
BinaryOp         Add_31                   2 1 578_splitncnn_0 587 335 0=0
Split            splitncnn_3              1 2 335 335_splitncnn_0 335_splitncnn_1
Convolution      Conv_32                  1 1 335_splitncnn_1 590 0=120 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=4800
ReLU             Relu_33                  1 1 590 338
ConvolutionDepthWise Conv_34                  1 1 338 593 0=120 1=5 11=5 2=1 12=1 3=1 13=1 4=2 14=2 15=2 16=2 5=1 6=3000 7=120
ReLU             Relu_35                  1 1 593 341
Convolution      Conv_36                  1 1 341 596 0=40 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=4800
BinaryOp         Add_37                   2 1 335_splitncnn_0 596 344 0=0
Convolution      Conv_38                  1 1 344 599 0=240 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=9600
HardSwish        Mul_43                   1 1 599 353 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_44                  1 1 353 602 0=240 1=3 11=3 2=1 12=1 3=2 13=2 4=1 14=1 15=1 16=1 5=1 6=2160 7=240
HardSwish        Mul_49                   1 1 602 362 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_50                  1 1 362 605 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=19200
Split            splitncnn_4              1 2 605 605_splitncnn_0 605_splitncnn_1
Convolution      Conv_51                  1 1 605_splitncnn_1 608 0=200 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=16000
HardSwish        Mul_56                   1 1 608 373 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_57                  1 1 373 611 0=200 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=1800 7=200
HardSwish        Mul_62                   1 1 611 382 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_63                  1 1 382 614 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=16000
BinaryOp         Add_64                   2 1 605_splitncnn_0 614 385 0=0
Split            splitncnn_5              1 2 385 385_splitncnn_0 385_splitncnn_1
Convolution      Conv_65                  1 1 385_splitncnn_1 617 0=184 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=14720
HardSwish        Mul_70                   1 1 617 394 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_71                  1 1 394 620 0=184 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=1656 7=184
HardSwish        Mul_76                   1 1 620 403 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_77                  1 1 403 623 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=14720
BinaryOp         Add_78                   2 1 385_splitncnn_0 623 406 0=0
Split            splitncnn_6              1 2 406 406_splitncnn_0 406_splitncnn_1
Convolution      Conv_79                  1 1 406_splitncnn_1 626 0=184 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=14720
HardSwish        Mul_84                   1 1 626 415 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_85                  1 1 415 629 0=184 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=1656 7=184
HardSwish        Mul_90                   1 1 629 424 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_91                  1 1 424 632 0=80 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=14720
BinaryOp         Add_92                   2 1 406_splitncnn_0 632 427 0=0
Convolution      Conv_93                  1 1 427 635 0=480 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=38400
HardSwish        Mul_98                   1 1 635 436 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_99                  1 1 436 638 0=480 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=4320 7=480
HardSwish        Mul_104                  1 1 638 445 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_105                 1 1 445 641 0=112 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=53760
Split            splitncnn_7              1 2 641 641_splitncnn_0 641_splitncnn_1
Convolution      Conv_106                 1 1 641_splitncnn_1 644 0=672 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=75264
HardSwish        Mul_111                  1 1 644 456 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_112                 1 1 456 647 0=672 1=3 11=3 2=1 12=1 3=1 13=1 4=1 14=1 15=1 16=1 5=1 6=6048 7=672
HardSwish        Mul_117                  1 1 647 465 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_118                 1 1 465 650 0=112 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=75264
BinaryOp         Add_119                  2 1 641_splitncnn_0 650 468 0=0
Convolution      Conv_120                 1 1 468 653 0=672 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=75264
HardSwish        Mul_125                  1 1 653 477 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_126                 1 1 477 656 0=672 1=5 11=5 2=1 12=1 3=2 13=2 4=2 14=2 15=2 16=2 5=1 6=16800 7=672
HardSwish        Mul_131                  1 1 656 486 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_132                 1 1 486 659 0=160 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=107520
Split            splitncnn_8              1 2 659 659_splitncnn_0 659_splitncnn_1
Convolution      Conv_133                 1 1 659_splitncnn_1 662 0=960 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=153600
HardSwish        Mul_138                  1 1 662 497 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_139                 1 1 497 665 0=960 1=5 11=5 2=1 12=1 3=1 13=1 4=2 14=2 15=2 16=2 5=1 6=24000 7=960
HardSwish        Mul_144                  1 1 665 506 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_145                 1 1 506 668 0=160 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=153600
BinaryOp         Add_146                  2 1 659_splitncnn_0 668 509 0=0
Split            splitncnn_9              1 2 509 509_splitncnn_0 509_splitncnn_1
Convolution      Conv_147                 1 1 509_splitncnn_1 671 0=960 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=153600
HardSwish        Mul_152                  1 1 671 518 0=1.666667e-01 1=5.000000e-01
ConvolutionDepthWise Conv_153                 1 1 518 674 0=960 1=5 11=5 2=1 12=1 3=1 13=1 4=2 14=2 15=2 16=2 5=1 6=24000 7=960
HardSwish        Mul_158                  1 1 674 527 0=1.666667e-01 1=5.000000e-01
Convolution      Conv_159                 1 1 527 677 0=160 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=153600
BinaryOp         Add_160                  2 1 509_splitncnn_0 677 530 0=0
Convolution      Conv_161                 1 1 530 680 0=960 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=153600
HardSwish        Mul_166                  1 1 680 539 0=1.666667e-01 1=5.000000e-01
Split            splitncnn_10             1 5 539 539_splitncnn_0 539_splitncnn_1 539_splitncnn_2 539_splitncnn_3 539_splitncnn_4
Convolution      Conv_167                 1 1 539_splitncnn_4 output_1 0=98 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=94080
Convolution      Conv_168                 1 1 539_splitncnn_3 541 0=98 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=94080
Convolution      Conv_169                 1 1 539_splitncnn_2 542 0=98 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=94080
Convolution      Conv_170                 1 1 539_splitncnn_1 543 0=980 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=940800
Convolution      Conv_171                 1 1 539_splitncnn_0 544 0=980 1=1 11=1 2=1 12=1 3=1 13=1 4=0 14=0 15=0 16=0 5=1 6=940800

**Comment by 408550969** [comment]
自问自答，参考 #5133
