### ISSUE TITLE
Can ncnn exported on Ubuntu be used on Windows?

### ISSUE THREAD

**Issue by seawater668** [Tencent/ncnn#5117]
## detail | 详细描述 | 詳細な説明

Because my models are all trained on Ubuntu, and configuring ncnn on Ubuntu is more convenient than Windows. The key is that Windows has to configure vs. a lot of memory.

**Comment by Baiyuetribe** [comment]
Yes, ncnn only needs to write the code once full platform available

**Comment by seawater668** [comment]
Do you mean that the NCNN I converted on ubuntu can also be used on windows?

**Comment by Baiyuetribe** [comment]
yeah

**Comment by nihui** [comment]
yes, the model file is the same across all platform
