### ISSUE TITLE
请问ncnn是否支持在推理之前预先分配内存空间，并且在推理过程中的中间变量全部复用该空间

### ISSUE THREAD

**Issue by Mactarvish** [Tencent/ncnn#5118]
## detail | 详细描述 | 詳細な説明
在嵌入式设备的JNI环境中，我们一般希望在构造对象时预先分配一块内存，然后在算法执行过程中所有的对象都在这块空间中操作，而不再在堆上申请和释放新的内存，从而减少内存碎片的产生以及避免由于JNI释放内存不及时可能引起的OOM问题。请问ncnn是否支持这样的操作？
我已知`ncnn::Mat`在构造的时候是支持直接通过指针引用现有内存的，但是在调用`ncnn::Extractor::extract`时，如何保证中间层的对象也在给定内存中分配？谢谢！

**Comment by nihui** [comment]
如果是静态shape输入，可以用自定义内存池实现

实现内存池，然后设置 opt.blob_allocator 与 opt.workspace_allocator

**Comment by Mactarvish** [comment]
> 如果是静态shape输入，可以用自定义内存池实现
> 
> 实现内存池，然后设置 opt.blob_allocator 与 opt.workspace_allocator

谢谢！原来ncnn天然地支持内存持有(๑•̀ㅂ•́)و✧
