### ISSUE TITLE
5d grid_sampe不支持

### ISSUE THREAD

**Issue by tianyu06030020** [Tencent/ncnn#5127]
你好，我用pnnx转换出了param/bin，但是有些警告：
![图片](https://github.com/Tencent/ncnn/assets/9124519/2decbd70-6f32-4380-ada3-ef775e1e9b54)

加载param/bin的时候提示grid_sample层不支持，看了下代码，目前支持4d的，我模型里用的5d的，有什么解决的办法吗？谢谢!

**Comment by tianyu06030020** [comment]
> 你好，我用pnnx转换出了param/bin，但是有些警告： ![图片](https://user-images.githubusercontent.com/9124519/279943772-2decbd70-6f32-4380-ada3-ef775e1e9b54.png)
> 
> 加载param/bin的时候提示grid_sample层不支持，看了下代码，目前支持4d的，我模型里用的5d的，有什么解决的办法吗？谢谢!

抱歉，好像是另一个问题：
![图片](https://github.com/Tencent/ncnn/assets/9124519/4bce6138-9c88-4cf3-a461-b9ec6af1226f)

我的模型如下：
[ncnn_model.zip](https://github.com/Tencent/ncnn/files/13237688/ncnn_model.zip)

**Comment by Yoh-Z** [comment]
能提供一个不带权重的torchscript模型吗

**Comment by tianyu06030020** [comment]
> 能提供一个随机权重的torchscript模型吗

@Yoh-Z  你好，我是用这个pt转换的

[random.zip](https://github.com/Tencent/ncnn/files/13240833/random.zip)

**Comment by tianyu06030020** [comment]
> > 能提供一个随机权重的torchscript模型吗
> 
> @Yoh-Z 你好，我是用这个pt转换的
> 
> [random.zip](https://github.com/Tencent/ncnn/files/13240833/random.zip)

@Yoh-Z 你好，我把取shape的地方写成固定值，shape不报错了，但报了另一个错误：
![图片](https://github.com/Tencent/ncnn/assets/9124519/8c630491-8bad-4cd0-86ab-acabcb2e7cc1)
pt/param/bin 如下：
[test.zip](https://github.com/Tencent/ncnn/files/13246031/test.zip)
转换命令如下：
![图片](https://github.com/Tencent/ncnn/assets/9124519/3476bfd4-ec01-4811-8426-423fa45e46a0)

**Comment by tianyu06030020** [comment]
> > > 能提供一个随机权重的torchscript模型吗
> > 
> > 
> > @Yoh-Z 你好，我是用这个pt转换的
> > [random.zip](https://github.com/Tencent/ncnn/files/13240833/random.zip)
> 
> @Yoh-Z 你好，我把取shape的地方写成固定值，shape不报错了，但报了另一个错误： ![图片](https://user-images.githubusercontent.com/9124519/280165723-8c630491-8bad-4cd0-86ab-acabcb2e7cc1.png) pt/param/bin 如下： [test.zip](https://github.com/Tencent/ncnn/files/13246031/test.zip) 转换命令如下： ![图片](https://user-images.githubusercontent.com/9124519/280166414-3476bfd4-ec01-4811-8426-423fa45e46a0.png)

--------------------------------------------------------------------------
之前使用的pnnx版本有点老了，ncnn目前支持5d和常用的数学算子了，用新的pnnx没有之前的问题了，但出现了新的问题：
![图片](https://github.com/Tencent/ncnn/assets/9124519/8bc5ab85-d89f-4f0b-8fcc-0add4c8d8a92)
模型里一个tensor是6维的，squeeze 报错

**Comment by Yoh-Z** [comment]
> > > > 能提供一个随机权重的torchscript模型吗
> > > 
> > > 
> > > @Yoh-Z 你好，我是用这个pt转换的
> > > [random.zip](https://github.com/Tencent/ncnn/files/13240833/random.zip)
> > 
> > 
> > @Yoh-Z 你好，我把取shape的地方写成固定值，shape不报错了，但报了另一个错误： ![图片](https://user-images.githubusercontent.com/9124519/280165723-8c630491-8bad-4cd0-86ab-acabcb2e7cc1.png) pt/param/bin 如下： [test.zip](https://github.com/Tencent/ncnn/files/13246031/test.zip) 转换命令如下： ![图片](https://user-images.githubusercontent.com/9124519/280166414-3476bfd4-ec01-4811-8426-423fa45e46a0.png)
> 
> 之前使用的pnnx版本有点老了，ncnn目前支持5d和常用的数学算子了，用新的pnnx没有之前的问题了，但出现了新的问题： ![图片](https://user-images.githubusercontent.com/9124519/280226579-8bc5ab85-d89f-4f0b-8fcc-0add4c8d8a92.png) 模型里一个tensor是6维的，squeeze 报错

六维就是不支持的，想办法看看那部分的处理能不能降低到五维做吧

**Comment by tianyu06030020** [comment]
> > > > > 能提供一个随机权重的torchscript模型吗
> > > > 
> > > > 
> > > > @Yoh-Z 你好，我是用这个pt转换的
> > > > [random.zip](https://github.com/Tencent/ncnn/files/13240833/random.zip)
> > > 
> > > 
> > > @Yoh-Z 你好，我把取shape的地方写成固定值，shape不报错了，但报了另一个错误： ![图片](https://user-images.githubusercontent.com/9124519/280165723-8c630491-8bad-4cd0-86ab-acabcb2e7cc1.png) pt/param/bin 如下： [test.zip](https://github.com/Tencent/ncnn/files/13246031/test.zip) 转换命令如下： ![图片](https://user-images.githubusercontent.com/9124519/280166414-3476bfd4-ec01-4811-8426-423fa45e46a0.png)
> > 
> > 
> > 之前使用的pnnx版本有点老了，ncnn目前支持5d和常用的数学算子了，用新的pnnx没有之前的问题了，但出现了新的问题： ![图片](https://user-images.githubusercontent.com/9124519/280226579-8bc5ab85-d89f-4f0b-8fcc-0add4c8d8a92.png) 模型里一个tensor是6维的，squeeze 报错
> 
> 六维就是不支持的，想办法看看那部分的处理能不能降低到五维做吧

@Yoh-Z ，你好，这个问题我解决了，有个新的问题，
![图片](https://github.com/Tencent/ncnn/assets/9124519/c69350b3-ef06-46a1-ae28-94cfc5dd7292)

我看生成的pnnx.py中permute维度没有交换，
![图片](https://github.com/Tencent/ncnn/assets/9124519/3c2107fd-3316-4ad5-95db-4389908f31ba)

注释掉以后转换没问题，ncnn测试的时候没有输出结果，也没有其他报错，
![图片](https://github.com/Tencent/ncnn/assets/9124519/5c1fa6aa-dee4-4270-bd14-7e097585c7fe)

pt文件如下：
[test.zip](https://github.com/Tencent/ncnn/files/13294526/test.zip)

**Comment by tianyu06030020** [comment]
解决了

**Comment by roachsinai** [comment]
@tianyu06030020 请教下你是怎么解决的呢？pnnx 转完之后跑 model_pnnx.py 和 onnx 的结果是相同的。但是，跑 model_ncnn.py 就 core dump 了？

**Comment by tianyu06030020** [comment]
> @tianyu06030020 请教下你是怎么解决的呢？pnnx 转完之后跑 model_pnnx.py 和 onnx 的结果是相同的。但是，跑 model_ncnn.py 就 core dump 了？
@roachsinai 有些忘记了，应该就是各种降维

**Comment by roachsinai** [comment]
好的，感谢！
