### ISSUE TITLE
conv1d inference nan issue

### ISSUE THREAD

**Issue by MuskTang** [Tencent/ncnn#5135]
## error log | 日志或报错信息 | ログ

我在嘗試inference一個只有conv1d layer的model, 發現他會隨機的跳出不同的inference結果如下

normal output
![截圖 2023-11-07 下午6 29 55](https://github.com/Tencent/ncnn/assets/116534967/062aa61c-0aef-44e6-a998-0fd2d2142d90)

overflow or wrong access (I guess) output
![截圖 2023-11-07 下午6 29 20](https://github.com/Tencent/ncnn/assets/116534967/726f3aa0-651c-4a01-b570-ec18698431ad)

## context | 编译/运行环境 | バックグラウンド
os: ubuntu 20.04
ncnn version: 1.0.20230407
torch version=1.13.1
onnx version=1.12.1

## how to reproduce | 复现步骤 | 再現方法
1. build a conv1d model and export
```
conv1d = nn.Conv1d(
                    80,
                    80,
                    11,
                    stride=1,
                    dilation=1,
                    padding=5,
                    bias=True,
                    groups=80,
                )


x = torch.randn(80, 64)
output = conv1d(x)

torch.onnx.export(conv1d, x, "conv1d.onnx", verbose=True, input_names=['input'], output_names=['output'])
```
3. onnx2ncnn and inference 
```
    float* data = new float[80 * 64];
    for (int i = 0; i < 80 * 64; i++) { data[i] = 1.0f; }
    printf("data: %f\n", data[0]);
    cv::Mat spec = cv::Mat(cv::Size(80, 64), CV_32FC(1), data);

    // Load NCNN model
    ncnn::Net net;

    int ret = net.load_param("conv1d.param");
    if (ret) std::cerr << "Failed to load model parameters" << std::endl;
    ret = net.load_model("conv1d.bin");
    if (ret) std::cerr << "Failed to load model weights" << std::endl;

    // tried, but no help
    // net.opt.use_fp16_storage = false;
    // net.opt.use_fp16_packed = false;
    // net.opt.use_fp16_arithmetic = false;

    // Inference
    ncnn::Extractor extractor = net.create_extractor();
    extractor.input("input", input);
    ncnn::Mat output;

    extractor.extract("output", output);

    // Flatten
    ncnn::Mat out_flatterned = output.reshape(output.w * output.h * output.c);
    printf("out_flatterned: %d, %d, %d\n", output.w, output.h, output.c);

    std::vector<float> scores;
    scores.resize(out_flatterned.w);
    for (int j = 0; j < out_flatterned.w; j++) {
        scores[j] = out_flatterned[j];
        printf("output [%d]: %f\n", j, scores[j]);
    }
```

## more | 其他 | その他

有發現一件事是當我conv1d的group參數設成1的時候似乎不會有這個問題，可是當我把group設成80的時候就會出現
請問我可以怎麼解決這個問題

**Comment by nihui** [comment]
onnx2ncnn 工具对 conv1d 转换有问题，可以用 pnnx 转换，兼容更多的算子
https://github.com/pnnx/pnnx

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
