### ISSUE TITLE
A question about the resize function of ncnn

### ISSUE THREAD

**Issue by XJTUWYD** [Tencent/ncnn#5140]
## detail | 详细描述 | 詳細な説明
 Is ncnn's bicubic resize strictly bit-true with respect to OpenCV's bicubic resize?

**Comment by nihui** [comment]
Usually not, opencv uses quantization technology to speed up operations, and ncnn also applies the same approach, but the quantization scale is different, and ncnn retains more effective digits. But in practice, this does not affect the results of the model.
