### ISSUE TITLE
MTCNN with int8 quantization gives wrong result

### ISSUE THREAD

**Issue by conanhujinming** [Tencent/ncnn#515]
I used this tool (https://github.com/BUG1989/caffe-int8-convert-tools) to do int8 quantization with MTCNN. The dataset I used was WIDER FACE (http://mmlab.ie.cuhk.edu.hk/projects/WIDERFace/). I only tired to quantize the first stage of MTCNN. However, no matter what parameter I chose, or chose the runtime way, or set some params in the table file to be 0,  the quantized first stage of MTCNN would always give an empty result. I used the latest NCNN version, and tried with Linux x86 and arm-linux, but none of these worked.

**Comment by conanhujinming** [comment]
Yeah, I find the answer in the ncnn faq. And this is because the model of MTCNN is trained with matlab caffe, so the model saved is column-major. However, ncnn asks for a row-major model.

**Comment by ivoxx** [comment]
> Yeah, I find the answer in the ncnn faq. And this is because the model of MTCNN is trained with matlab caffe, so the model saved is column-major. However, ncnn asks for a row-major model.

怎么解决的？
