### ISSUE TITLE
Gemm之后shape异常

### ISSUE THREAD

**Issue by Momenta-IPO** [Tencent/ncnn#5177]
我有一个onnx模型，其中有若干gemm算子，转换成ncnn推理的时候在第一个gemm算子就出现了错误，预期的输出是shape为1x16的矩阵（如下图）
![image](https://github.com/Tencent/ncnn/assets/141317307/0c77bcc4-faf2-4ec2-b9a2-350370d002e2)
但是在ncnn推理的时候这个gemm输出的shape是4x16的，我用的pyncnn，版本是20231027，可以帮看看这个问题吗，模型发你qq邮箱

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
