### ISSUE TITLE
VkImageMat获取AHardwareBuffer的值异常

### ISSUE THREAD

**Issue by 408550969** [Tencent/ncnn#5190]
## detail | 详细描述 | 詳細な説明
我在benchmark下使用AHardwareBuffer创建了一块内存，想让VkImageMat指向这块内存，ahb_im_allocator打印出来的值是正常的分别是320,160,647，但是两个vkimagemat的值打印出来都是异常的，其中from_android_hardware_buffer 的out0打印出来的值是全0。 而out1打印出来的值是320,1,1。
	AHardwareBuffer* buffer = nullptr;
	AHardwareBuffer_Desc desc = {
	.width = 320,
	.height = 260,
	.layers = 1,
	.format = AHARDWAREBUFFER_FORMAT_Y8Cb8Cr8_420,
	.usage = AHARDWAREBUFFER_USAGE_CPU_READ_OFTEN | AHARDWAREBUFFER_USAGE_CPU_WRITE_OFTEN | AHARDWAREBUFFER_USAGE_GPU_SAMPLED_IMAGE | AHARDWAREBUFFER_USAGE_GPU_FRAMEBUFFER,
	};
	int ret = AHardwareBuffer_allocate(&desc, &buffer);
	ncnn::VkAndroidHardwareBufferImageAllocator ahb_im_allocator(g_vkdev, buffer);
	fprintf(stderr, "ahb_im_allocator.w=%d,h=%d,%lu \n", ahb_im_allocator.width(), ahb_im_allocator.height(), ahb_im_allocator.external_format());
	ncnn::VkImageMat out0;
	out0.from_android_hardware_buffer(&ahb_im_allocator);
	fprintf(stderr, "out0.w=%d,h=%d,c=%d \n", out0.w, out0.h, out0.c);
	ncnn::VkImageMat out1(ahb_im_allocator.width(), ahb_im_allocator.height(), &ahb_im_allocator);
	fprintf(stderr, "out1.w=%d,h=%d,c=%d \n", out1.w, out1.h, out1.c);

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5237

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/6c261a8c04cb62b9ca429fdbf7b8df65f670b4f9
