### ISSUE TITLE
deform_conv2d not supported yet!

### ISSUE THREAD

**Issue by nypyp** [Tencent/ncnn#5192]
## model | 模型 | モデル
1. original model
yolov7-tiny

## how to reproduce | 复现步骤 | 再現方法
1. ./onnx2ncnn yolov7-tiny-sim.onnx报错
deform_conv2d not supported yet!
deform_conv2d not supported yet!
deform_conv2d not supported yet!
Shape not supported yet!
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unknown data type 0
Shape not supported yet!
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unknown data type 0
Shape not supported yet!
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unsupported unsqueeze axes !
Unknown data type 0
请问有什么办法解决可变形卷积算子不支持的问题吗，去掉可变形卷积的模型能成功部署，但是加上可变形卷积就不能

**Comment by nihui** [comment]
torchvision 的 deform conv2d 可以用 pnnx 工具直接转到 ncnn，不要使用 onnx 中转

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
