### ISSUE TITLE
int num_threads = thread_affinity_mask.num_enabled(); 等于0，是不是表示没有绑定核心

### ISSUE THREAD

**Issue by Gitxiaozhu-oss** [Tencent/ncnn#5196]
![image](https://github.com/Tencent/ncnn/assets/61084986/334183cd-c6ce-4fca-85f4-0ac183999e12)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/b7f70cfe4e4d990f3680ab37dbac29f69cf9b06a

已修复，感谢报告~
