### ISSUE TITLE
layer Identity not exists or registered

### ISSUE THREAD

**Issue by Cooo1der** [Tencent/ncnn#5197]
Thans for your excellent work! However when I run tum dataset, an error ocuurs:layer Identity not exists or registered
I have recompiled ncnn code, but it didn't work

**Comment by nihui** [comment]
hi, try converting your model via pnnx tool  https://github.com/pnnx/pnnx
nn.Identity is supported :D

**Comment by Cooo1der** [comment]
What a Pity... The rtdetr model currently supports only onnx exports

**Comment by nihui** [comment]
> What a Pity... The rtdetr model currently supports only onnx exports

You can try the onnx2torch project, convert to torch model, and then use pnnx
You can also try editing the ncnn param file directly and replace Identity with Noop

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
