### ISSUE TITLE
Unable to convert YOLOv8s models to NCNN format.

### ISSUE THREAD

**Issue by kmatsuyama0921** [Tencent/ncnn#5207]
## model | 模型 | モデル
1. load & convert model
    Yolov8s
## how to reproduce | 复现步骤 | 再現方法
1.`https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb#scrollTo=CYIjW4igCjqD`
2.run script  ➡　`!yolo export model=yolov8s.pt format=ncnn`
3.Download model.ncnn.param & model.ncnn.bin
4. Open param file on Newtron https://netron.app/
5. YOLOv8s model downloaded from the Internet.　➡　https://github.com/nihui/ncnn-assets/tree/master/models

## Check model architecture
The first image is a model downloaded from the Internet.
The second image is the model I converted myself.

The official NCNN model has three outputs, but the model I downloaded from the official YOLOv8 model and converted to NCNN format has only one output.
Is there a conversion error somewhere?
I would like to get some expert opinions.

![スクリーンショット 2023-12-07 161937](https://github.com/Tencent/ncnn/assets/130947905/b08cf561-3da9-483c-959a-b4271d7f8487)
![スクリーンショット 2023-12-07 162146](https://github.com/Tencent/ncnn/assets/130947905/5a006396-c4ae-412a-be01-40ac19941ce9)

**Comment by CloudsRL** [comment]
Have u finish? I faced the same trouble QAQ I wanna convert YOLOv8s models to NCNN format, in order to improve my SLAM program, but eachtime i trans it into NCNN format, my program call mistakes QAQ
if u did it, could u send me the files (.bin and .parame)? i really really want sb. to help me

**Comment by nihui** [comment]
yolov8 example https://github.com/Tencent/ncnn/pull/5506

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
