### ISSUE TITLE
使用 vulkan 退出异常

### ISSUE THREAD

**Issue by YuHe0108** [Tencent/ncnn#5210]
## detail | 详细描述 | 詳細な説明
c++ 使用 vulkan 作为后端进行模型推理，退出的时候会有异常出现，我用了以下方式，但是还是会有异常出现，请问如何解决。
![微信图片_20231208172936](https://github.com/Tencent/ncnn/assets/40628937/615c0007-0e35-43b5-afdb-d0ff0023ea6d)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5234

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/ded0b78bb2926d3fd116c94d988c8e3d836d191a
