### ISSUE TITLE
mac ncnn和android ncnn 的 from_pixels_resize方法后，差异较大

### ISSUE THREAD

**Issue by minushuang** [Tencent/ncnn#5218]
在mac上，使用opencv读取本地一张图im1，经过ncnn的from_pixels_resize后的值 im_ncnn_1。
在android上，使用opencv读取本地一张图im2，经过ncnn的from_pixels_resize后的值 im_ncnn_2。
发现pc和手机上，opencv读出来的im1和im2都是一样的，但经过from_pixels_resize后的 im_ncnn_1 和 im_ncnn_2则出现了差异。
想问下，移动端和pc端from_pixels_resize实现方法不一样吗？

**Comment by nihui** [comment]
用 bmp 图片试试？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5390

**Comment by minushuang** [comment]
和 #5263 问题重复，close了
