### ISSUE TITLE
rvm_512.param、rvm_512.bin文件下载连接失效了，可以再发一份吗？

### ISSUE THREAD

**Issue by 714273725** [Tencent/ncnn#5227]
在issue中发现有个2022年的链接，也失效了

**Comment by 714273725** [comment]
已从项目 ncnn_Android_RobustVideoMatting 中找到

**Comment by nihui** [comment]
rvm example updated
https://github.com/Tencent/ncnn/blob/master/examples/rvm.cpp
https://github.com/nihui/ncnn-android-rvm

rvm ncnn deploy guide(zh)
https://zhuanlan.zhihu.com/p/1900989328831783411
