### ISSUE TITLE
在QNX编译GPU版本

### ISSUE THREAD

**Issue by wenhyan** [Tencent/ncnn#5240]
## 想在QNX系统下编译支持GPU版本的NCNN，请问有成功编译的吗

**Comment by nihui** [comment]
最新 master 分支 git clone + 更新 submodule + cmake -DNCNN_VULKAN=ON

有什么编译问题请贴log

**Comment by wenhyan** [comment]
@nihui 谢谢，搞定了，驱动版本更新之后可以了
