### ISSUE TITLE
在QNX系统上使用yolov7tiny+ncnn，表现与Windows上不一样

### ISSUE THREAD

**Issue by SpiceGL** [Tencent/ncnn#5242]
我在QNX上编译了231027版的ncnn，编译时build_type设置为空。
在测试yolov7tiny网络时，opencv的Mat为(224, 224, 3)，而在使用from_pixels，type为BGR2RGB后，得到的ncnn Mat的尺寸变为(224, 224, 1)，而在Windows平台尺寸正常。
于是我new了一个[224x224x3]的float数组，手动将cv::Mat的像素归一化后填到数组上，再由此创建了一个尺寸为(224, 224, 3)的ncnn Mat。在QNX上推理时，则在extract时以-100的错误码退出，在Windows平台同样没有这个问题。
在这个过程中，测试代码是同一个，请问这是什么原因呢？

**Comment by nihui** [comment]
看看项目中是否存在老版本ncnn共用的问题，以及更新ncnn库时，头文件有没有一起更新

**Comment by SpiceGL** [comment]
> 看看项目中是否存在老版本ncnn共用的问题，以及更新ncnn库时，头文件有没有一起更新

感谢大佬！确实是因为我只更新了lib文件没有更新include导致的，

**Comment by nihui** [comment]
> > 看看项目中是否存在老版本ncnn共用的问题，以及更新ncnn库时，头文件有没有一起更新
> 
> 感谢大佬！确实是因为我只更新了lib文件没有更新include导致的，

好耶！
