### ISSUE TITLE
您好作者现在有很多需要动态序列化输入的模型算法，但是pnnx只支持torch.jit.trace吗固定的输入，有别的方法出路吗

### ISSUE THREAD

**Issue by fordeep3d** [Tencent/ncnn#5248]
## expectation | 诉求 | 期待する
1. speed 
2. precision

## model | 模型 | モデル
1. model.param and model.bin

**Comment by nihui** [comment]
trace 的模型支持动态长度序列输入的
你还可以在pnnx转换时指定 inputshape2 来指派动态的维
