### ISSUE TITLE
连续推理的速度貌似大于间断的推理 如何让ncnn始终处于连续推理的状态

### ISSUE THREAD

**Issue by misslng** [Tencent/ncnn#5250]
## detail | 详细描述 | 詳細な説明
使用的项目地址 https://github.com/JiweiMaster/PP-PicoDet-Android-Demo
如果不debug直接跑 nanodet可以跑到70fps+
然后我在as中打断点 一帧一帧的跑 大概要20ms完成一次推理
放开了跑只需要10ms左右,如何让ncnn能够持续在10ms这种状态嘞

**Comment by nihui** [comment]
cpu提升频率需要时间，所以连续运行会更快些
