### ISSUE TITLE
AddVectoredExceptionHandler and RemoveVectoredExceptionHandler cannot be used under uwp

### ISSUE THREAD

**Issue by jimwang118** [Tencent/ncnn#5256]
## error log | 日志或报错信息 | ログ
\src\cpu.cpp(205): error C3861: 'AddVectoredExceptionHandler': identifier not found
\src\cpu.cpp(212): error C3861: 'RemoveVectoredExceptionHandler': identifier not found
## context | 编译/运行环境 | バックグラウンド
windows
msvc
## how to reproduce | 复现步骤 | 再現方法
1.git clone https://github.com/jimwang118/vcpkg.git ncnn
2.git checkout upncnn
3.cd ncnn
4. ./bootstrap-vcpkg.bat
5. ./vcpkg install ncnn:x64-uwp

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5328
