### ISSUE TITLE
layer LayerNorm not exists or registered 

### ISSUE THREAD

**Issue by HarryGest** [Tencent/ncnn#5262]
## error log | 日志或报错信息 | ログ
layer LayerNorm not exists or registered

## context | 编译/运行环境 | バックグラウンド
arm64
sylixos操作系统

## how to reproduce | 复现步骤 | 再現方法
1. pytorch的bertjiont转化为ncnn模型
转化后的param参数如下（部分）：
Input                    in0                      0 1 in0
MemoryData               pnnx_fold_87             0 1 1 0=512 1=100
MemoryData               pnnx_fold_88             0 1 2 0=512 1=100
Embed                    embed_17                 1 1 in0 3 0=512 1=21128 2=0 3=10817536
BinaryOp                 add_0                    2 1 3 1 4 0=0
BinaryOp                 add_1                    2 1 4 2 5 0=0
MemoryData               attn_mask_0              0 1 6 0=100 1=100
LayerNorm                ln_18                    1 1 5 7 0=512 1=1.000000e-12 2=1
Split                    splitncnn_0              1 2 7 8 9
...
运行爆以下问题
layer LayerNorm not exists or registered

## more | 其他 | その他

是由于我的ncnn版本太低了么？

**Comment by nihui** [comment]
更新ncnn版本再试试？
编译ncnn的时候观察是否编译了 layernorm 相关的代码

**Comment by HarryGest** [comment]
感谢回复，是版本问题，新的版本支持了。
