### ISSUE TITLE
Android编译openMP未开启多核是什么原因。

### ISSUE THREAD

**Issue by Justin-bin** [Tencent/ncnn#528]
开启OMP
ncnn::set_omp_dynamic(1);
        ncnn::Option opt;
        opt.lightmode = true;
        opt.num_threads = 4;

        ncnn::set_default_option(opt);

        ncnn::set_omp_num_threads( 4 );

打印结果：
 LOGE("ncnn cpu num =  %d",ncnn::get_cpu_count());
 LOGE("ncnn cpu num omp =  %d",ncnn::get_omp_num_threads());
ncnn cpu num = 8;
ncnn cpu num omp =1 ;

想问一下为什么 num omp 为1 。

**Comment by nihui** [comment]
you can query the current num_threads setting via ncnn::get_default_option().num_threads
