### ISSUE TITLE
Problem after last update 

### ISSUE THREAD

**Issue by ilie321** [Tencent/ncnn#5282]
## detail | 详细描述 | 詳細な説明
Hello
As usual i got the android vulkan shared put it in my project same as last 3 4 updates and is not working anymore. Fails to create vk... - 8. Any idea? Thanks

**Comment by nihui** [comment]
hi, please provide your android phone model info

**Comment by nihui** [comment]
confirmed regression for adreno devices

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5287

**Comment by ilie321** [comment]
S20fe android 13

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/5329d32e74c31dfa250378ea180c40cb74e830ea

Thanks for your report !
