### ISSUE TITLE
Operator fusion Problem

### ISSUE THREAD

**Issue by Hua1211** [Tencent/ncnn#5296]
## error log | 日志或报错信息 | ログ
我是用YOLO訓練，轉成onnx之後轉成ncnn param後
發現第一個模塊的batchnorm沒有和conv 融合再一起，
想問為什麼?

## model | 模型 | モデル
1. original model
# create by pogg
# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [ 10,13, 16,30, 33,23 ]  # P3/8
  - [ 30,61, 62,45, 59,119 ]  # P4/16
  - [ 116,90, 156,198, 373,326 ]  # P5/32

# custom backbone
backbone:
   [ [ -1, 1, conv_bn_relu_maxpool, [ 32 ] ],    # 0-P2/4
    [ -1, 1, Shuffle_Block, [ 100, 2 ] ], # 1-P3/8
    [ -1, 3, Shuffle_Block, [ 100, 1 ] ], # 2
    [ -1, 1, Shuffle_Block, [ 200, 2 ] ], # 3-P4/16
    [ -1, 7, Shuffle_Block, [ 200, 1 ] ], # 4
    [ -1, 1, Shuffle_Block, [ 400, 2 ] ], # 5-P5/32
    [ -1, 1, Shuffle_Block, [ 400, 1 ] ], # 6
  ]
head:
  [ [ -1, 1, Conv, [ 96, 1, 1 ] ],
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, DWConvblock, [96, 3, 1] ],  # 10

    [ -1, 1, Conv, [ 96, 1, 1 ] ],
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
    [ -1, 1, DWConvblock, [96, 3, 1] ],  # 14 (P3/8-small)

    [-1, 1, DWConvblock, [96, 3, 2]],
    [ [ -1, 11 ], 1, ADD, [ 1 ] ],  # cat head P4
    [ -1, 1, DWConvblock, [96, 3, 1] ],  # 17 (P4/16-medium)

    [ -1, 1, DWConvblock, [ 96, 3, 2 ] ],
    [ [ -1, 7 ], 1, ADD, [ 1 ] ],  # cat head P5
    [ -1, 1, DWConvblock, [96, 3, 1] ],  # 20 (P5/32-large)

    [ [ 14, 17, 20 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
  ]

## how to reproduce | 复现步骤 | 再現方法
1. 用YOLO github 訓練即可
2. 我是用github中的eport.py轉出onnx 
python export.py --include onnx --train --simplify --weights [weight file] --img 320 
3.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
