### ISSUE TITLE
cannot extract Deconvolution converted from MXNET

### ISSUE THREAD

**Issue by husencd** [Tencent/ncnn#532]
Hello! I used mxnet2ncnn to convert model correctly (at least there is no error info). But when I do the inference, I found that I cannot extract Deconvolution layer (extracting the downsampling convolution layer is ok). Can u help me?

**Comment by nihui** [comment]
I tried the simple pose model, which contains deconvolution layer, and it works properly
https://gluon-cv.mxnet.io/build/examples_pose/demo_simple_pose.html
try updating the latest mxnet2ncnn code
