### ISSUE TITLE
rv1109(armv7)上，ncnn推理出现core dump，具体报错位置在：gemm_transB_packed_tile()

### ISSUE THREAD

**Issue by Xiaowei-coder** [Tencent/ncnn#5322]
### error log | 日志或报错信息 | ログ
**报错信息如下：**
![image](https://github.com/Tencent/ncnn/assets/65143911/2ffb0e0f-f9e9-4b9f-b89d-4766b79362e2)
**bt信息：**
![image](https://github.com/Tencent/ncnn/assets/65143911/df11da0e-6ca7-489c-b69a-fb178fbea0fe)

## context | 编译/运行环境 | バックグラウンド
编译环境：linux_x86
运行环境：rv1109(双核32位ARM Cortex-A7)
可用内存：789568 kB(rv1109)
编译ncnn版本：20240102

## how to reproduce | 复现步骤 | 再現方法
1. ./benchncnn 2 2 0 -1 1 param=./model.ncnn.param shape=[32,1,1,1],[2,96,1,1]
2. [model.ncnn.zip](https://github.com/Tencent/ncnn/files/14094040/model.ncnn.zip)

## more | 其他 | その他
1. rv1109(armv7)上，benchncnn可正常推理squeezenet模型
![image](https://github.com/Tencent/ncnn/assets/65143911/d44882d8-83b7-4fb7-8642-6035956afadd)
2. rv1109(armv7)上，benchncnn推理则会在gemm_transB_packed_tile()处报相同的错误，如下：
![image](https://github.com/Tencent/ncnn/assets/65143911/2cf2aca9-b3fc-4f69-89ec-5f1479b79ca3)
3. 在rv1109(armv7)上会报错；其他arm平台则能正常推理，如下：
![image](https://github.com/Tencent/ncnn/assets/65143911/d6785f0b-9bc3-47df-bc60-8f540efbd5d9)

```[tasklist]
### Tasks
```

**Comment by Xiaowei-coder** [comment]
### 补充说明
相同的代码与模型，交叉编译后，测试发现中间层参数不同，具体如下：
1. **在不带neon的arm平台上，可正常推理[view_75->gemm_0]：**
![image](https://github.com/Tencent/ncnn/assets/65143911/e47025be-1659-4c62-bf2d-5081186a2981)
2. **带neon的arm平台上，会在gemm_0处报错[view_75->gemm_0]：**
![image](https://github.com/Tencent/ncnn/assets/65143911/f5ac7a95-4d0a-474d-8cd4-3fa87b315a90)

**Comment by Xiaowei-coder** [comment]
### 补充说明
（1）不开启NEON，ncnn可正常推理；开启NEON后，ncnn推理会在在gemm做矩阵乘法的位置出错：
![LD}90D85 ZG6{ZD9Y24842E](https://github.com/Tencent/ncnn/assets/65143911/3e353350-221f-4569-9925-a4e4532635f7)
（2）去掉ncnn模型中报错的层gemm_0，仍会在下次调用gemm矩阵乘法函数处报错；

- gemm_0对应模型中的Linear层

（3）开启和不开启neon，AT_tile.w出现了2倍关系

**Comment by nihui** [comment]
confirmed and reproduced

workaround
```cpp
net.opt.use_fp16_storage = ncnn::cpu_support_arm_asimdhp();
```
before loading model

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5325

**Comment by Xiaowei-coder** [comment]
带上#5325 修改后，加载模型前无需设置net.opt.use_fp16_storage = ncnn::cpu_support_arm_asimdhp()，也能在我的armv7平台上推理，再次感谢nihui大佬。
![image](https://github.com/Tencent/ncnn/assets/65143911/c70f26f8-f158-40d7-915b-df5a8b467821)

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/984d6dd84497f044bff09d1f87e4f692f9bd909f
Thanks for your report
