### ISSUE TITLE
ncnn的不同平台的预编译版本的疑问

### ISSUE THREAD

**Issue by ANYMS-A** [Tencent/ncnn#5329]
## detail | 详细描述 | 詳細な説明
请问不同平台的预编译版本（Linux|Win|MacOS）指的是说我的host machine的platform，还是说最终ncnn模型运行的target platform？

如果我使用Win的预编译版本转化得到的ncnn模型，是否可以部署在Arm/Linux等平台上运行呢？

**Comment by nihui** [comment]
1. target platform
2. ncnn模型文件是通用的

**Comment by ANYMS-A** [comment]
好的，感谢解答。
