### ISSUE TITLE
recipe for target 'src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o' failed

### ISSUE THREAD

**Issue by ShaunWilson** [Tencent/ncnn#533]
src/CMakeFiles/ncnn.dir/build.make:542: recipe for target 'src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o' failed
make[2]: *** [src/CMakeFiles/ncnn.dir/layer/arm/convolution_arm.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/ncnn.dir/all' failed
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Hello, Excuse ,there is a  error in NCNN when NCNN is maked in RK3288 Linux

**Comment by nihui** [comment]
resolved by adding "-mfpu=neon" compiler option
