### ISSUE TITLE
Yolov8 convert issue

### ISSUE THREAD

**Issue by WillWarti** [Tencent/ncnn#5338]
Hi,
I would like to draw to your attention to the following convertors behaviour : I trained a Yolov8 nano version model from Ultralytics SDK, I have no problem when I convert it to ncnn format directly from this framework and deploy it in a C++ application : input is a 640x640 image and output is a 8400x7 matrix (3 classes only) as expected. But when I convert it firstly to ONNX from Ultralytics and then convert to NCNN format using NCNN convertor (20240201 version) or online convertor, I noticed that output size is wrong in C++ application (8400x38 matrix).
See attached both .param models.
Sincerely yours.

[yolov8_corrupted.param.txt](https://github.com/Tencent/ncnn/files/14308554/yolov8_corrupted.param.txt)
[yolov8_from_ultralytics.param.txt](https://github.com/Tencent/ncnn/files/14308555/yolov8_from_ultralytics.param.txt)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by nihui** [comment]
yolov8 example https://github.com/Tencent/ncnn/pull/5506

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
