### ISSUE TITLE
yolov8 的结果和预期不一致，只有macOS(M1)受影响

### ISSUE THREAD

**Issue by kekxv** [Tencent/ncnn#5340]
正确输出了结果，但是有偏差；关闭 fp16 之后结果正常

https://github.com/Tencent/ncnn/releases/tag/20230517 以及后续出现错误结果
https://github.com/Tencent/ncnn/releases/tag/20230223 结果正确

## how to reproduce | 复现步骤 | 再現方法
1. 使用 yolov8 导出的模型，或者用 https://github.com/kekxv/YOLOv8Tutorial/releases/tag/20240219 里面的测试

错误的结果：
<img width="695" alt="截屏2024-02-20 22 45 11" src="https://github.com/Tencent/ncnn/assets/15551108/fed155b8-8406-498a-ba80-1946f1e0bd3f">
正确的结果：
<img width="688" alt="截屏2024-02-20 22 44 52" src="https://github.com/Tencent/ncnn/assets/15551108/56437e8a-a61e-4d2f-be0e-9bcc3add546f">

**Comment by kekxv** [comment]
受影响开始的提交 ：
https://github.com/Tencent/ncnn/commit/010d6772d6c0f4528ab95c9f5bb238d1f235e985

像是 [softmax_arm.cpp](https://github.com/Tencent/ncnn/issues/5340#diff-eb3a52567fd153bcdc6cb31005ad0a69174568e0f19a97eeaaef5eb0415922a6) 部份

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5393

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
