### ISSUE TITLE
sigmastar平台 加载模型 bus error   

### ISSUE THREAD

**Issue by IwraI** [Tencent/ncnn#5343]
## detail | 详细描述 | 詳細な説明
编译器版本  gcc-sigmastar-9.1.0-2019.11-x86_64_arm-linux-gnueabihf
armA7
核心代码

	printf("load ncnn model\n");
	printf("param  %p\n",My_DeepFilterNet_howl_16k_ep42_ncnn_param_bin);
	printf("bin    %p\n",My_DeepFilterNet_howl_16k_ep42_ncnn_bin);
	printf("dfnet    %p\n",DFNET_handle->dfnet);
	int nRet = 0;
	nRet = ((DFNET_handle->dfnet))->load_param(ncnn_param_bin);
	printf("nRet %d\n", nRet);
	printf("load ncnn param done\n");

	nRet= ((DFNET_handle->dfnet))->load_model(ncnn_bin);
	printf("nRet %d\n", nRet);
	printf("load ncnn model done\n");

输出信息

	 /tmp # ./dfnet_ncnn_demo wav_test.wav wav_test_ncnn.wav 
	load ncnn model
	param  0x19da0c
	bin    0x148798
	dfnet    0x1dbf20
	nRet 4752
	load ncnn param done
	Bus error

相同的代码在windows平台运行正常，模型正确输出，麻烦看下大概是什么原因导致的

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/656b082284c8043c478e00feb98de0bec411d800
master分支上应该已经修好了，可以试试

**Comment by IwraI** [comment]
已验证
