### ISSUE TITLE
how to cite the ncnn in a paper？

### ISSUE THREAD

**Issue by lijuan-lll** [Tencent/ncnn#5349]
## detail | 详细描述 | 詳細な説明
hello，how to cite the ncnn in a paper？what‘s the citation format？

**Comment by nihui** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

![图片](https://github.com/Tencent/ncnn/assets/171016/411be877-3472-4e71-9f1c-ebb626a00a39)
