### ISSUE TITLE
caffe matlab版的mtcnn 转ncnn 能够成功检测与同样的代码 c++ 版的mtcnn 转ncnn 后检测不到人脸是怎么回事。

### ISSUE THREAD

**Issue by grainw** [Tencent/ncnn#535]
使用的是https://github.com/moli232777144/mtcnn_ncnn 这上面的程序，matlab版mtcnn 转ncnn 是项目自带的。c++版的是自己训练的。还了模型后检测不到东西。但是在caffe上能检测到。

**Comment by unaplugin** [comment]
我另外的工程中（和你的不一样）也遇到了检不到脸的问题，后面发现是```std::vector<Bbox> faces; mtcnn.detect(frame,faces);```中的这个```faces```只能定义一次，如果每个loop重复定义，或者每个loop做了```faces.resize(0);```这种操作，就会有检不到脸的时候。

**Comment by Xiangyu-CAS** [comment]
@grainw 刚解决了这个问题，这是conv和fc参数存储row-major和col-major不一致导致的，我们自己训练的MTCNN，做了weights转置后就可以正常工作了
