### ISSUE TITLE
graph is not ready

### ISSUE THREAD

**Issue by minushuang** [Tencent/ncnn#5355]
## detail | 详细描述 | 詳細な説明
paddleocr训练的模型导出推理模型，导出onnx后，导出ncnn，再onnxsim简化后，
py-ncnn加载模型在`net.load_model("filename.bin")`时，提示`graph is not ready`，然后就一直卡住。

### ncnn版本
1.0.20240102

### 模型
链接: https://pan.baidu.com/s/1WnX5zt_RvHnxGDbvVZV5FQ 提取码: nw49

**Comment by wzyforgit** [comment]
完整代码呢？是不是没加载param就在搞model了

**Comment by minushuang** [comment]
> 完整代码呢？是不是没加载param就在搞model了

确实，按照您的回复我讲load_param和load_model顺序对换之后就可以了。
原来如下，报错的
```
net.load_model("bin_model_path")
net.load_param("param_path")
```
改成如下，可以了
```
net.load_param("param_path")
net.load_model("bin_model_path")
```
之前一直没发现过这个问题，非常感谢。

还有个疑问，有些model，先load_model再load_param，确实是可以的，看了之前的推理代码，一直这样写的，却没报错，这是为啥呢？

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
