### ISSUE TITLE
在arm-linux平台利用交叉编译的libncnn.a库报相关方法没有定义

### ISSUE THREAD

**Issue by sglshanghai** [Tencent/ncnn#536]
In function `Detect::detect_object(cv::Mat)':
undefined reference to `ncnn::Net::Net()'；
undefined reference to `ncnn::Net::load_param(char const*)'
undefined reference to `ncnn::Net::load_model(char const*)'
undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int)'
undefined reference to `ncnn::Mat::substract_mean_normalize(float const*, float const*)'
undefined reference to `ncnn::Net::create_extractor() const'
undefined reference to `ncnn::Extractor::set_light_mode(bool)'
undefined reference to `ncnn::Extractor::input(char const*, ncnn::Mat const&)'
undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&)'
undefined reference to `ncnn::Net::~Net()'
undefined reference to `ncnn::Net::~Net()'

**Comment by leeburt** [comment]
请问你是怎么解决的这个问题，谢谢~

**Comment by Ryuk17** [comment]
> 请问你是怎么解决的这个问题，谢谢~

请问你解决了，谢谢~

**Comment by MoonSheepJx** [comment]
请问您解决了嘛

**Comment by ZX-lang** [comment]
> In function `Detect::detect_object(cv::Mat)': undefined reference to `ncnn::Net::Net()'； undefined reference to `ncnn::Net::load_param(char const*)' undefined reference to `ncnn::Net::load_model(char const*)' undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int)' undefined reference to `ncnn::Mat::substract_mean_normalize(float const*, float const*)' undefined reference to `ncnn::Net::create_extractor() const' undefined reference to `ncnn::Extractor::set_light_mode(bool)' undefined reference to `ncnn::Extractor::input(char const*, ncnn::Mat const&)' undefined reference to `ncnn::Extractor::extract(char const*, ncnn::Mat&)' undefined reference to `ncnn::Net::~Net()' undefined reference to `ncnn::Net::~Net()'

请问有解决这个问题吗
