### ISSUE TITLE
Wrong detection results for yolov7 on RISC-V with RVV 

### ISSUE THREAD

**Issue by vassilijnadarajah** [Tencent/ncnn#5360]
## error log | 日志或报错信息 | ログ
When peforming object detection with yolov7 and NCNN on RISC-V, I get different results depending on if i use NCNN with RVV support or without RVV support. I use the same source code but the NCNN library is compiled differently. The results are the same, when perfoming inference on x86, armv8 or RISC-V without RVV. Just when compiling with RVV, I get wrong results. 

#### Classification with NCNN on RISC-V with RVV
![failed_rvv_classification](https://github.com/Tencent/ncnn/assets/96822320/fe4dcb45-a2f3-492a-a1af-5bff4cd37bbb)

#### Classification with NCNN on RISC-V without RVV
![successful_classification](https://github.com/Tencent/ncnn/assets/96822320/46c97be9-2a20-434a-924a-939a5c8ab756)
 

## how to reproduce | 复现步骤 | 再現方法
I uploaded an [example project](https://github.com/vassilijnadarajah/ncnn-yolov7-risc-v.git) with instructions on how to compile with and without RVV support. For the compilation of the NCNN library i followed the steps in the [wiki](https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-allwinner-d1).

## more | 其他 | その他
Please let me know, if I need to supply more information. I would really appreciate any help with this. Thank you in advance! 谢谢!

**Comment by wzyforgit** [comment]
Please run ncnn unit test with RVV to see what goes wrong.

Run ncnn unit test:
cmake -DNCNN_BUILD_TESTS=ON (other parameters) ..
make
make test

**Comment by wzyforgit** [comment]
> Hi @wzyforgit! Thank you for taking the time to reply. I just ran all the unit tests and apart from one test, all of them have passed.
> 
> When running `test_reduction`, I get the error message `param is too old, please regenerate!` multiple times. I attached a screenshot.
> 
> Also for `test_squeezenet` I get `overwrite built-in layer type Convolution` and `overwrite built-in layer type 6` printed to the console. The test still passes though.
> 
> I'd be thankful for any other tips you may be able to give me.
> 
> ![param_too_old](https://private-user-images.githubusercontent.com/96822320/311183712-29bb3f1f-3513-4182-806c-3fdedaf83a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5NzEwMDUsIm5iZiI6MTcwOTk3MDcwNSwicGF0aCI6Ii85NjgyMjMyMC8zMTExODM3MTItMjliYjNmMWYtMzUxMy00MTgyLTgwNmMtM2ZkZWRhZjgzYTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA5VDA3NTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNTIxMTIxNjFiYmZkZTllMjNhNjUzZjFhMzM5NzE4NzcyODg0MTA0OTJlZDY2NGRmNTczYTYwZjU4MzQ0ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Kfdk2kpANPXIu_iELlP4y9kPb611sFr3TwahHw5qfM)

There is another way here: 
0. Keep use RVV param in cmake
1. Remove all RVV files in src/layer/riscv
2. Recover one RVV file in src/layer/riscv
3. Build ncnn and run your yolov7 application
4.1 If the detection results are wrong, the file you recovered last time have bug, remove it
4.2 If the detection results are all right, the file you recovered last time is right, keep it
4. Repeat steps 2 to 4 until you find all the problematic files
5. Remove all problematic files and rebuild ncnn into your application

I'm sorry that I'm not good at RVV and C906 core.
If your project is urgent, you can try this method to get maximum speed up and wait for the owner to fix the problems.

**Comment by nihui** [comment]
`param is too old, please regenerate!` warning fixed in https://github.com/Tencent/ncnn/pull/5397
I am now trying to reproduce the rvv issue

**Comment by nihui** [comment]
The bug has been confirmed and can be reproduced

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/pull/5398
Thanks for your report

**Comment by vassilijnadarajah** [comment]
Thank you so much @nihui! It works now :)
