### ISSUE TITLE
layer load_model LSTM failed

### ISSUE THREAD

**Issue by Haibit** [Tencent/ncnn#5378]
## error log | 日志或报错信息 | ログ
layer load_model 9 LSTM_7 failed

## context | 编译/运行环境 | バックグラウンド
ESP32 

cmake的编译选项： -mlongcalls -mtext-section-literals  -std=c++11  -DNCNN_STRING=1 -DNCNN_STDIO=1 -DNCNN_THREADS=0

## how to reproduce | 复现步骤 | 再現方法
model param is :

7767517
12 14
Input                    input.1                  0 1 input.1
Input                    onnx::LSTM_1             0 1 onnx::LSTM_1
Input                    onnx::LSTM_2             0 1 onnx::LSTM_2
MemoryData               linear.bias              0 1 linear.bias 0=32
Convolution              Conv_0                   1 1 input.1 onnx::Mul_12 0=32 1=1 5=1 6=32 9=1
BinaryOp                 Mul_3                    1 1 onnx::Mul_12 onnx::Transpose_14 0=2 1=1 2=4.000000e+00
Permute                  Transpose_4              1 1 onnx::Transpose_14 onnx::Reshape_17 0=2
Reshape                  Reshape_5                1 1 onnx::Reshape_17 input.4 0=-1 1=1
LSTM                     LSTM_7                   3 3 input.4 onnx::LSTM_1 onnx::LSTM_2 onnx::Unsqueeze_50 47 48 0=64 1=262144
ExpandDims               Unsqueeze_10             1 1 onnx::Unsqueeze_50 onnx::MatMul_51 -23300=1,0
InnerProduct             MatMul_11                1 1 onnx::MatMul_51 onnx::Add_53 0=32 2=2048
BinaryOp                 Add_12                   2 1 linear.bias onnx::Add_53 54

model bin is

[test.zip](https://github.com/Tencent/ncnn/files/14623047/test.zip)

转换的时候，采用优化选项得到的param也会有同样的报错。
但是linux上可以正常加载模型。

**Comment by Haibit** [comment]
debug定位到lstm.h中
weight_xc_data = mb.load(size, hidden_size * 4, num_directions, 0);
得到的weight_xc_data的data是0x0。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
