### ISSUE TITLE
pnnx 转 ncnn 得到的 reshape 算子没有参数

### ISSUE THREAD

**Issue by roachsinai** [Tencent/ncnn#5394]
## error log | 日志或报错信息 | ログ

<img width="686" alt="image" src="https://github.com/Tencent/ncnn/assets/9500049/79149cfc-e6b7-4612-855e-00bbc13fc64d">

如上图 `reshape_118` 算子没有参数，param 文件中也只到输入输出。执行 pnnx 生成的 `ncnn.py` 也是这个算子输出之前正常，之后 core dump。

`reshape_118` 下方的 reshape 算子是正常的

<img width="551" alt="image" src="https://github.com/Tencent/ncnn/assets/9500049/78ada2d7-540d-47c0-87b9-9e8e55bd274e">

`pnnx.py` 中这两个 reshape 算子对应的代码如下图：

<img width="654" alt="image" src="https://github.com/Tencent/ncnn/assets/9500049/ce518af6-31ee-4b3d-ab42-c125384c2aa5">

正常的 reshape 算子对应语句：`v_106.reshape(1, 256, 104, 80, 2)`，

异常 reshape 算子对应语句：`v_102.reshape(256, 1, 1, 2, 2)`

这个 `reshape_118` 算子的参数应该如何添加呢？谢谢。

```[tasklist]
### Tasks
```

**Comment by roachsinai** [comment]
`reshape_118` 算子输入的维度是 `256, 2, 2`，输出的维度应该是 `256, 1, 1, 2, 2`。

**Comment by nihui** [comment]
ncnn reshape 不支持5维及以上
如果reshape的shape batch=1，那么是可以的

**Comment by roachsinai** [comment]
好的，我想想有没有调整的办法。感谢。

**Comment by qingyang-jiandao** [comment]
reshape 肯定有问题的
