### ISSUE TITLE
怎么在hisi 3519上编译ncnn?

### ISSUE THREAD

**Issue by ctgushiwei** [Tencent/ncnn#54]
你好，请问怎么在hisi 3519上编译ncnn，是armv7架构，而且怎么样才能保证用到arm下面的neon和汇编？

**Comment by nihui** [comment]
#28

**Comment by ctgushiwei** [comment]
@nihui 我就用了Cmakelist生成makefile，并在src、Cmakelist.txt的37行增加了 OR (Linux AND ("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "armv7")),也没在生成的 layer_declaration.h 里头是
看到有 xxx_arm，应该石没有编译neon，请问是不是还有那个地方开关没有开启，生成makefile后就直接make了

**Comment by whtc123** [comment]
新建一个arm.toolchan.cmake.
SET(CMAKE_SYSTEM_NANE Android)
SET(CMAKE_SYSTEM_PROCESSOR "armv7-a")
SET(ANDROID_ARCH_NAME "arm")
SET(ANDROID true)
SET(CMAKE_C_COMPILER "arm-hisiv600-linux-gcc")
SET(CMAKE_CXX_COMPILER "arm-hisiv600-linux-g++")

然后mkdir build_arm ;cd build_arm;cmake ..;make

**Comment by whtc123** [comment]
海思3519我没有试过，3536试了，450ms。
深度学习和安防还是有点距离。

**Comment by ctgushiwei** [comment]
@whtc123 你这个450ms是跑的什么网络，另外你测试的是单线程还是多线程？

**Comment by whtc123** [comment]
@ctgushiwei  squeezenet 单线程

**Comment by BUG1989** [comment]
这时候，你需要Hi3559A，内置NPU，GoogleNet 10ms，VGG-SSD 89ms  ^0^

**Comment by ehancen** [comment]
@BUG1989 GoogleNet 10ms，VGG-SSD 89ms是在什么条件下测试得到的啊？图片分辨率多少啊？

**Comment by BUG1989** [comment]
@ehancen Hi3559A SDK中的例程
