### ISSUE TITLE
在Mac M3 芯片下编译ncnn 编译成功后 在优化的时候出现Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Elijah-Yi** [Tencent/ncnn#5401]
## error log | 日志或报错信息 | ログ
![image](https://github.com/Tencent/ncnn/assets/22116117/1d994cb8-af55-41bd-ac74-b83ffd80aa20)

## context | 编译/运行环境 | バックグラウンド
macos M3 系统本班 sonoma 14.4 ubuntu 22.04 均出现这个问题。使用版本：2023-10-27没有问题
## how to reproduce | 复现步骤 | 再現方法
编译命令：

cmake -DCMAKE_CXX_STANDARD=11 -DNCNN_OPENMP=OFF -DNCNN_BENCHMARK=ON ..

**Comment by nihui** [comment]
最新版本 20240410 已修复
