### ISSUE TITLE
MacOS下 new ncnn::Net() 崩溃

### ISSUE THREAD

**Issue by FyhSky** [Tencent/ncnn#5417]
## how to reproduce | 复现步骤 | 再現方法

Mtcnn::Mtcnn() :
	pnet_(new ncnn::Net()),
	rnet_(new ncnn::Net()),
	onet_(new ncnn::Net()),

1.* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001031e9314 libncnn.1.dylib`some_avxvnni() + 4
    frame #1: 0x00000001031e92e6 libncnn.1.dylib`detectisa(void (*)()) + 86
    frame #2: 0x00000001031e9116 libncnn.1.dylib`try_initialize_global_cpu_info() + 982
    frame #3: 0x00000001031e9779 libncnn.1.dylib`ncnn::get_physical_big_cpu_count() + 9
    frame #4: 0x0000000103285bd1 libncnn.1.dylib`ncnn::Option::Option() + 17
    frame #5: 0x000000010327e1b0 libncnn.1.dylib`ncnn::Net::Net() + 32
  * frame #6: 0x000000010001481b
2.
3.

**Comment by nihui** [comment]
shall be fixed in https://github.com/Tencent/ncnn/commit/87d71658480b821a4af8dcd6db03e14643eb84e5

**Comment by nihui** [comment]
更新最新版本 20240410 即可
