### ISSUE TITLE
ncnn 在android 上识别输出为0,并且模型载入也是0

### ISSUE THREAD

**Issue by LonglongaaaGo** [Tencent/ncnn#542]
@nihui   哈喽,nihui , 我不知道为什么我编译出来的libsqueezencnn.so  能够在 https://github.com/dangbo/ncnn-mobile 上跑通 ,但是模型就是无法载入,并且识别为0 ,没有报错.
一下是我编译的过程:
longlongaaago@longlongaaago-X550DP ~/WorkSpace/ncnn/build-anroid $ cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
>     -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON \
>     -DANDROID_PLATFORM=android-14 ..
-- CMAKE_TOOLCHAIN_FILE = /build/cmake/android.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /home/longlongaaago/WorkSpace/ncnn/build-anroid/install
...
-- Build files have been written to: /home/longlongaaago/WorkSpace/ncnn/build-anroid
longlongaaago@longlongaaago-X550DP ~/WorkSpace/ncnn/build-anroid $ make -j4
longlongaaago@longlongaaago-X550DP ~/WorkSpace/ncnn/build-anroid $ make install
[100%] Built target ncnn

然后我再使用案例里面的 squeezencnn_jni.cpp    squeezenet_v1.1.id.h
Application.mk    Android.mk  这四个文件,基本都没改过,只是改了对应的路径
![screenshot from 2018-08-25 16-03-38](https://user-images.githubusercontent.com/34880268/44616321-7d85c880-a880-11e8-9d6b-5773852659c5.png)
如图所示,只是这样而已
然后我输入
ndk-build   之后就产生了我自己编译的  libsqueezencnn.so  但是我的这个文件
大小不一样  我的为423.5kb
同时,我给案例项目squeezencnn-AS也编了一个libsqueezencnn.so , 然后这个项目也识别不了了....

项目结构,原材料全跟squeezencnn-AS 一样没变,只是变了一些路径而已

所以我想问一下大神@nihui  我该怎么办.,...

**Comment by LonglongaaaGo** [comment]
走过路过的大神也帮忙看看啊.卡了两个星期了,内心焦灼啊..

**Comment by nihui** [comment]
不要用 ncnn-mobile 那个工程，太旧了
用这里的 https://github.com/Tencent/ncnn/tree/master/examples/squeezencnn

**Comment by LonglongaaaGo** [comment]
@nihui 谢谢大神回复,我可能没说清楚,我的意思是,您的案例工程是本来可以跑通的,但是在替换我自己编译了这个libsqueezencnn.so 库之后就不行了,就是我这个编译不知道哪里出了问题.

**Comment by LonglongaaaGo** [comment]
@nihui   您的案例教程是可以识别的,但是用了我自己编译的库之后也只能识别为0 了

**Comment by LonglongaaaGo** [comment]
@nihui  aaa　成功啦！！！谢谢大神，确实是工程太旧的缘故！！！
