### ISSUE TITLE
ncnn-20240410使用-DNCNN_BF16=OFF编译报错

### ISSUE THREAD

**Issue by xiaozhi003** [Tencent/ncnn#5421]
## error log | 日志或报错信息 | ログ
使用`-DNCNN_BF16=OFF`参数编译Android和iOS库报错
<img width="570" alt="image" src="https://github.com/Tencent/ncnn/assets/4998101/ce1d5cc6-3002-4310-bc5a-094f3eae15db">

## context | 编译/运行环境 | バックグラウンド
MacBook，M1芯片，版本：14.4.1
NDK版本：25.1.8937393
Android平台和iOS平台

编译脚本
```
cmake -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK/build/cmake/android.toolchain.cmake" \
    -DANDROID_ABI="armeabi-v7a" \
    -DANDROID_ARM_NEON=ON \
    -DNCNN_DISABLE_RTTI=ON \
    -DNCNN_DISABLE_EXCEPTION=ON \
    -DNCNN_VULKAN=OFF \
    -DNCNN_BF16=OFF \
    -DNCNN_INT8=OFF \
    -DNCNN_OPENMP=OFF \
    -DANDROID_PLATFORM=android-19 ..
```

## how to reproduce | 复现步骤 | 再現方法
1. 使用最新版本ncnn-20240410，采用以往的编译脚本报错
2. 发现 **-DNCNN_BF16=OFF** 使用该参数导致编译报错，打开无问题
3.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5422

**Comment by xiaozhi003** [comment]
> #5422
> 
> 请测试下这个 pr 的修改

这个没问题了！

**Comment by nihui** [comment]
> > #5422
> > 请测试下这个 pr 的修改
> 
> 这个没问题了！

感谢报告！
