### ISSUE TITLE
rnn(lstm，gru)，解卷积的量化以及增加weight only的量化

### ISSUE THREAD

**Issue by hugauss** [Tencent/ncnn#5423]
希望能补充rnn相关的lstm，gru层的量化
另外也希望增加weight only量化的支持

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5435

**Comment by nihui** [comment]
implemented in https://github.com/Tencent/ncnn/commit/08b7d99a75ad70fdc5c1d9e5debc675fce5e83a9
