### ISSUE TITLE
iPhone创建ncnn::net崩溃

### ISSUE THREAD

**Issue by xiaozhi003** [Tencent/ncnn#5433]
## error log | 日志或报错信息 | ログ
```
已崩溃：com.o.FaceDetectQueue
EXC_BAD_INSTRUCTION 0x00000000d5380000

Crashed: com.o.FaceDetectQueue
0  iOS_Wallet          0x15050 ruapu_some_cpuid() + 6
1  iOS_Wallet          0x15108 ruapu_detect_isa(void (*)()) + 96
2  iOS_Wallet          0x15578 try_initialize_global_cpu_info() + 900
3  iOS_Wallet          0x1597c ncnn::get_physical_big_cpu_count() + 16
4  iOS_Wallet          0x2cb0c ncnn::Option::Option() + 28
5  iOS_Wallet          0x2a180 ncnn::Net::Net() + 40
6  iOS_Wallet          0x129f4 Face::Face() + 437 (face.cpp:437)
```
该问题必现

## context | 编译/运行环境 | バックグラウンド
使用ncnn-20240410
iPhone 12 mini，iOS 16.5.1

## how to reproduce | 复现步骤 | 再現方法
1. 创建ncnn::net就崩溃
2.
3.

## more | 其他 | その他
补充下，多款iPhone手机都是必现的
我看到issue #5417 是同样的问题，@nihui 说是20240410解决了这个问题，但是我这边就是用的这个版本才出的问题，旧版本没事

**Comment by nihui** [comment]
> ## error log | 日志或报错信息 | ログ
> ```
> 已崩溃：com.o.FaceDetectQueue
> EXC_BAD_INSTRUCTION 0x00000000d5380000
> 
> Crashed: com.o.FaceDetectQueue
> 0  iOS_Wallet          0x15050 ruapu_some_cpuid() + 6
> 1  iOS_Wallet          0x15108 ruapu_detect_isa(void (*)()) + 96
> 2  iOS_Wallet          0x15578 try_initialize_global_cpu_info() + 900
> 3  iOS_Wallet          0x1597c ncnn::get_physical_big_cpu_count() + 16
> 4  iOS_Wallet          0x2cb0c ncnn::Option::Option() + 28
> 5  iOS_Wallet          0x2a180 ncnn::Net::Net() + 40
> 6  iOS_Wallet          0x129f4 Face::Face() + 437 (face.cpp:437)
> ```
> 
> 该问题必现
> 
> ## context | 编译/运行环境 | バックグラウンド
> 使用ncnn-20240410 iPhone 12 mini，iOS 16.5.1
> 
> ## how to reproduce | 复现步骤 | 再現方法
> 1. 创建ncnn::net就崩溃
> 
> ## more | 其他 | その他
> 补充下，多款iPhone手机都是必现的 我看到issue #5417 是同样的问题，@nihui 说是20240410解决了这个问题，但是我这边就是用的这个版本才出的问题，旧版本没事

是调试启动才会出现，不调试ok吗？

**Comment by xiaozhi003** [comment]
> > ## error log | 日志或报错信息 | ログ
> > ```
> > 已崩溃：com.o.FaceDetectQueue
> > EXC_BAD_INSTRUCTION 0x00000000d5380000
> > 
> > Crashed: com.o.FaceDetectQueue
> > 0  iOS_Wallet          0x15050 ruapu_some_cpuid() + 6
> > 1  iOS_Wallet          0x15108 ruapu_detect_isa(void (*)()) + 96
> > 2  iOS_Wallet          0x15578 try_initialize_global_cpu_info() + 900
> > 3  iOS_Wallet          0x1597c ncnn::get_physical_big_cpu_count() + 16
> > 4  iOS_Wallet          0x2cb0c ncnn::Option::Option() + 28
> > 5  iOS_Wallet          0x2a180 ncnn::Net::Net() + 40
> > 6  iOS_Wallet          0x129f4 Face::Face() + 437 (face.cpp:437)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 该问题必现
> > ## context | 编译/运行环境 | バックグラウンド
> > 使用ncnn-20240410 iPhone 12 mini，iOS 16.5.1
> > ## how to reproduce | 复现步骤 | 再現方法
> > 
> > 1. 创建ncnn::net就崩溃
> > 
> > ## more | 其他 | その他
> > 补充下，多款iPhone手机都是必现的 我看到issue #5417 是同样的问题，@nihui 说是20240410解决了这个问题，但是我这边就是用的这个版本才出的问题，旧版本没事
> 
> 是调试启动才会出现，不调试ok吗？

是打的debug包，二维码安装出问题；在xcode中run到手机上反而没事

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5593

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/997c8926d706db5f9e4098aec8ed51c49ab9417c

感谢报告
