### ISSUE TITLE
yolov8n模型在鲲鹏ARM机器的检测结果和pytorch结果不一样

### ISSUE THREAD

**Issue by zhenjing** [Tencent/ncnn#5439]
pytorch代码，导出ncnn模型，推理测试。

from ultralytics import YOLO
from PIL import Image

model = YOLO('yolov8n.pt')
//# model.export(format='ncnn', half=False, imgsz=640)

source = './TestMe.jpg'
results = model.predict(source, save=True, save_txt=True)

model_ncnn = YOLO("yolov8n_ncnn_model", task="detect")
results = model_ncnn.predict(source, save=True, save_txt=True)

在python的推理结果ncnn和pytorch一致(细微差别)。

## context | 编译/运行环境 | バックグラウンド
[用C++实现ncnn模型推理，结果不同](![TestMe](https://github.com/Tencent/ncnn/assets/801574/50b2486a-84a5-48bc-83cf-57191a90e2ca))

正常结果：
box: {416.000000, 451.000000, 1304.000000, 893.000000}, class_idx: 20, score: 0.894148
box: {352.000000, 210.000000, 509.000000, 309.000000}, class_idx: 33, score: 0.735249
box: {0.000000, 0.000000, 337.000000, 128.000000}, class_idx: 33, score: 0.728028
box: {337.000000, 145.000000, 406.000000, 180.000000}, class_idx: 33, score: 0.652099
box: {861.000000, 373.000000, 936.000000, 463.000000}, class_idx: 14, score: 0.628122

错误结果：
box: {416.000000, 223.000000, 1305.000000, 894.000000}, class_idx: 20, score: 0.894531
**box: {448.000000, 441.000000, 1349.000000, 1109.000000}, class_idx: 20, score: 0.812500**
box: {352.000000, 211.000000, 525.000000, 310.000000}, class_idx: 33, score: 0.728516
box: {0.000000, 0.000000, 338.000000, 127.000000}, class_idx: 33, score: 0.727051
box: {337.000000, 145.000000, 405.000000, 180.000000}, class_idx: 33, score: 0.650879
box: {861.000000, 373.000000, 936.000000, 464.000000}, class_idx: 14, score: 0.636230

## how to reproduce | 复现步骤 | 再現方法
1.
2.
3.

**Comment by nihui** [comment]
用最新的 20240410 版本
pnnx 转换时使用 fp16=0
ncnn 禁用fp16 https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#disable-fp16
应该就能获得完全一致的结果了

**Comment by zhenjing** [comment]
用 ncnn-20240102，禁用fp16，检测结果和pytorch一致。
禁用fp16后，速度慢了50%。能否启用fp16，还能得到正确结果？

**Comment by zhenjing** [comment]
采用 https://github.com/Qengineering/YoloV8-ncnn-Raspberry-Pi-4 的模型，这个模型去掉了部分输出推理逻辑，在启动fp16时，检测结果是正确的。 对原始模型的输出是有某些算子不支持吗？

**Comment by nihui** [comment]
> 用 ncnn-20240102，禁用fp16，检测结果和pytorch一致。 禁用fp16后，速度慢了50%。能否启用fp16，还能得到正确结果？

用 20240410 版本啊

**Comment by nihui** [comment]
> 20240410 , 启用fp16，能得到正确结果，精度有偏差。
> 
> pytorch 检测结果（half=False，不启用fp16）： 原始模型： [class] [x_center] [y_center] [width] [height] [confidence] 20 0.578238 0.674553 0.595038 0.432779 0.900195 33 0.287819 0.258129 0.104904 0.100881 0.671818 33 0.113862 0.0640004 0.222977 0.128001 0.64798 33 0.248576 0.161419 0.0472315 0.0305715 0.539291 14 0.599585 0.415717 0.0515121 0.0925999 0.472335
> 
> ncnn模型： 20 0.578125 0.675 0.59375 0.433594 0.902344 33 0.1125 0.0645264 0.224219 0.129053 0.731445 33 0.287891 0.257812 0.104883 0.101074 0.689941 33 0.248437 0.161426 0.0470703 0.0304688 0.547363 14 0.6 0.416016 0.0527344 0.0919922 0.474854
> 
> C++检测结果： Kunpeng-920 启用fp16 20 = 0.89453 at 417.00 451.00 887.00 x 442.00 33 = 0.72852 at 352.00 211.00 157.00 x 99.00 33 = 0.72705 at 0.00 0.00 337.00 x 127.00 33 = 0.65088 at 337.00 145.00 68.00 x 35.00 14 = 0.63623 at 861.00 373.00 75.00 x 90.00
> 
> Kunpeng-920 不启用fp16 20 = 0.89414 at 416.00 451.00 888.00 x 442.00 33 = 0.73525 at 352.00 210.00 157.00 x 99.00 33 = 0.72803 at 0.00 0.00 337.00 x 128.00 33 = 0.65210 at 337.00 145.00 69.00 x 35.00 14 = 0.62812 at 861.00 373.00 75.00 x 90.00
> 
> Intel(R) Xeon(R) Gold 6240 不启用fp16 20 = 0.89415 at 416.00 451.00 888.00 x 442.00 33 = 0.73525 at 352.00 210.00 157.00 x 99.00 33 = 0.72803 at 0.00 0.00 337.00 x 128.00 33 = 0.65210 at 337.00 145.00 69.00 x 35.00 14 = 0.62812 at 861.00 373.00 75.00 x 90.00
> 
> C++不启用fp16的检测结果和pytorch不启用fp16推理ncnn模型的精度也存在偏差。 不启用fp16，鲲鹏和x64 检测结果完全一样。

这个误差就是 fp16 fp32 造成的，不影响实际使用效果

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
