### ISSUE TITLE
load_param是否将支持传读取param文件后的字符串

### ISSUE THREAD

**Issue by onexuan** [Tencent/ncnn#544]
想加密param文件，然后读取解密后传给load_param，是否将支持传字符串

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/ncnn-%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8C%97-alexnet
使用 param.bin

**Comment by onexuan** [comment]
这个知道，但用ncnn2mem生成后，模型从4M变到20M，所以不合要求

**Comment by nihui** [comment]
可以 XXX.param.bin + XXX.bin + XXX.id.h 配合使用，用 load_param_bin + load_model 文件加载

**Comment by onexuan** [comment]
OK，谢谢了

**Comment by SophieChang66** [comment]
@nihui 想模型加密，因为有自定义层，使用ncnn2mem后调用失败；试过将自定义层加入layer下，增加ncnn_add_layer（），ncnn library编译通过了，但新编译的库，无论load有自定义层的模型还是无自定义层的其他模型，遇到参数层就load失败，请问将自定义层内嵌入ncnn library，需要怎么修改
