### ISSUE TITLE
matmul与InnerProduct存在差异，将matmul当作InnerProduct是否不妥？

### ISSUE THREAD

**Issue by jimlee10** [Tencent/ncnn#545]
矩阵乘法matmul的两个输入可能都是变化的数据，全连接InnerProduct则是输入变化的数据和不变的参数。tensorflow2ncnn中将matmul当作InnerProduct，尝试存储参数，当matmul输入都是数据时，forward是否存在问题？是否应当分情况处理matmul的不同场景？

**Comment by diggerdu** [comment]
请问这个问题你是如何解决的
