### ISSUE TITLE
pnnx能正常转换模型，模型输出与onnx模型输出不一致

### ISSUE THREAD

**Issue by Oliverwang** [Tencent/ncnn#5451]
## error log | 日志或报错信息 | ログ
ncnn版本 ncnn-20240410
pnnx版本 pnnx-20240410-linux

运行python3 readout_query_pnnx.py 输出nan
![image](https://github.com/Tencent/ncnn/assets/747345/f10d6315-be67-45c8-8493-225f19c8d224)

## model | 模型 | モデル
1. original model

## how to reproduce | 复现步骤 | 再現方法
1. pnnx readout_query.pt  inputshape=[[1,64,24,24],[1,1,16,65]]
2.python3 readout_query_pnnx.py
3.

**Comment by Oliverwang** [comment]
模型见附件

**Comment by Oliverwang** [comment]
[Uploading readout_query.tar.gz…]()
模型见附件

**Comment by nihui** [comment]
```python
    net = torch.jit.load('readout_query.pt')
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 64, 24, 24, dtype=torch.float)
    v_1 = torch.rand(1, 1, 16, 65, dtype=torch.float)

    return net(v_0, v_1)
```

你提供的模型，这样随机输入，输出也是 nan

**Comment by Oliverwang** [comment]
@nihui 验证了 torch.manual_seed(0) 的时候输出就会是nan 把随机种子改成别的就不会输出nan

**Comment by Oliverwang** [comment]
[readout_query.tar.gz](https://github.com/Tencent/ncnn/files/15269999/readout_query.tar.gz)
![image](https://github.com/Tencent/ncnn/assets/747345/e9d687fa-e941-459b-8d03-4b2e151aec28)
pt模型与onnx模型  同样的输入  输出基本能对上      pnnx的就对不上

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
