### ISSUE TITLE
windows下用clang编译引起crash

### ISSUE THREAD

**Issue by maconel** [Tencent/ncnn#5468]
## error log | 日志或报错信息 | ログ
windows下用clang编译dll，调用load_param_bin时会引起crash。

## context | 编译/运行环境 | バックグラウンド
windows x86_64，clang，dll

## how to reproduce | 复现步骤 | 再現方法
1. windows下用clang编译dll
2. 调用load_param_bin

## more | 其他 | その他
希望能对windows+clang给予支持，谢谢。
[build.zip](https://github.com/Tencent/ncnn/files/15410891/build.zip)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5469

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/c4a007406d0382a3b1bec763402c7e6f2213023d

感谢报告
