### ISSUE TITLE
arm平台使用开启int8功能后，检测不到目标

### ISSUE THREAD

**Issue by ranson** [Tencent/ncnn#547]
arm平台使用开启int8功能后，检测不到目标。
我用的是mobilenetssd的网络，用x86编译的caffe2ncnn来做模型的转换。
同样的模型，我在arm平台上编译x86的layer的代码，来做对比实验，发现是可以检测到目标的。
另外，同样的caffe模型用https://github.com/BUG1989/ncnn.git的代码来试，int8功能是ok的。
请问谁有遇到过相关问题吗？求解...

**Comment by renfeier** [comment]
请问你是如何开启int8功能的呢

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/ef36d79b7eaa114797d968f262e410197f6ac3da

**Comment by ranson** [comment]
我合了ef36d79的修改还是没有解决我的问题，请问是否还有其它问题需要注意
