### ISSUE TITLE
鸿蒙平台开启vulkan编译ncnn

### ISSUE THREAD

**Issue by cugxchen** [Tencent/ncnn#5473]
## detail | 详细描述 | 詳細な説明
鸿蒙平台开启vulkan编译ncnn，链接报错

环境配置：
export PATH=/ohos-sdk/linux/native/sysroot/usr/include:/ohos-sdk/linux/native/sysroot/usr/lib/aarch64-linux-ohos:${PATH}
编译指令：
cmake -DOHOS_STL=c++_static -DOHOS_ARCH=arm64-v8a -DOHOS_PLATFORM=OHOS -DCMAKE_TOOLCHAIN_FILE=/ohos-sdk/linux/native/build/cmake/ohos.toolchain.cmake  -DNCNN_VULKAN=ON  -DNCNN_OPENMP=OFF -DCMAKE_BUILD_TYPE=Release  ..
make -j4

报错信息：
ld.lld: error: unable to find library -lOSDependent

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5474

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-harmonyos-with-cross-compiling
