### ISSUE TITLE
没有yolov8.cpp

### ISSUE THREAD

**Issue by WangShuai771216** [Tencent/ncnn#5487]
ncnn量化后的yolov8模型模型文件，example目录下没有推理代码yolov8.cpp

**Comment by cillayue** [comment]
wait for

**Comment by whyb** [comment]
I just submitted a pull request for yolov8 example https://github.com/Tencent/ncnn/pull/5506
I hope it can be helpful to you.

**Comment by Deephome** [comment]
> I just submitted a pull request for yolov8 example #5506 I hope it can be helpful to you.

Hi, I tested the yolov8.cpp example in your PR, but the results are unreasonable. Specifically, I got yolov8n.bin and yolov8n.param following your guide in yolov8.cpp, and your yolov8n example returns many detections with same confidence of 0.5. The result:
![image](https://github.com/Tencent/ncnn/assets/28822327/c0f26314-b960-4011-8982-3907f4163bd8)

**Comment by whyb** [comment]
> > I just submitted a pull request for yolov8 example #5506 I hope it can be helpful to you.
> 
> Hi, I tested the yolov8.cpp example in your PR, but the results are unreasonable. Specifically, I got yolov8n.bin and yolov8n.param following your guide in yolov8.cpp, and your yolov8n example returns many detections with same confidence of 0.5. The result: ![image](https://private-user-images.githubusercontent.com/28822327/341003192-c0f26314-b960-4011-8982-3907f4163bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODkxNDUsIm5iZiI6MTcxODc4ODg0NSwicGF0aCI6Ii8yODgyMjMyNy8zNDEwMDMxOTItYzBmMjYzMTQtYjk2MC00MDExLTg5ODItMzkwN2Y0MTYzYmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA5MjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjVhMWFkMzA5MWQyMmEwOTk3MWJkYmIxOWE5N2E1ZDJkYzI1OTQyODdiNDg1OTBkMTRmOGU1NDYxNDNjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b5Q8i2DUnMqX3lMWtJa9Ir4K_r8p6JPT5vitEP5J6oM)

我知道这个问题，这个原因不是因为我这边的原因，而是您导出的yolov8.ncnn.* 模型是仅固定支持[1,3,640,640]的模型，并不支持动态shape输入造成的。

这个错误的模型会导致输入进去的数据为了保持图像原比例缩放，并不符合模型要求的[1,3,640,640]，实际上有可能是[1,3,640,540]，所以模型内部会错位读取图像，对结果造成严重偏差。

只是要尝试效果的话，您可以直接把输入的图片用画图工具或者cv::resize() 修改成640x640的尺寸。

pnnx本身是支持动态shape输入的，您可以去参考  [https://github.com/pnnx/pnnx?tab=readme-ov-file#------detailed-options](https://github.com/pnnx/pnnx?tab=readme-ov-file#------detailed-options)

导出正确的支持动态shape输入的模型，期待您的好消息~🤣

**Comment by Deephome** [comment]
> > > I just submitted a pull request for yolov8 example #5506 I hope it can be helpful to you.
> > 
> > 
> > Hi, I tested the yolov8.cpp example in your PR, but the results are unreasonable. Specifically, I got yolov8n.bin and yolov8n.param following your guide in yolov8.cpp, and your yolov8n example returns many detections with same confidence of 0.5. The result: ![image](https://private-user-images.githubusercontent.com/28822327/341003192-c0f26314-b960-4011-8982-3907f4163bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODkxNDUsIm5iZiI6MTcxODc4ODg0NSwicGF0aCI6Ii8yODgyMjMyNy8zNDEwMDMxOTItYzBmMjYzMTQtYjk2MC00MDExLTg5ODItMzkwN2Y0MTYzYmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA5MjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjVhMWFkMzA5MWQyMmEwOTk3MWJkYmIxOWE5N2E1ZDJkYzI1OTQyODdiNDg1OTBkMTRmOGU1NDYxNDNjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b5Q8i2DUnMqX3lMWtJa9Ir4K_r8p6JPT5vitEP5J6oM)
> 
> 我知道这个问题，这个原因不是因为我这边的原因，而是您导出的yolov8.ncnn.* 模型是仅固定支持[1,3,640,640]的模型，并不支持动态shape输入造成的。
> 
> 这个错误的模型会导致输入进去的数据为了保持图像原比例缩放，并不符合模型要求的[1,3,640,640]，实际上有可能是[1,3,640,540]，所以模型内部会错位读取图像，对结果造成严重偏差。
> 
> 只是要尝试效果的话，您可以直接把输入的图片用画图工具或者cv::resize() 修改成640x640的尺寸。
> 
> pnnx本身是支持动态shape输入的，您可以去参考 https://github.com/pnnx/pnnx?tab=readme-ov-file#------detailed-options
> 
> 导出正确的支持动态shape输入的模型，期待您的好消息~🤣

Well, I find out that the problem originates from a bug in your [yolov8.cpp](https://github.com/whyb/ncnn/blob/8a28d71c3c6bc40420d213618b294e5d7b32fde9/examples/yolov8.cpp#L245)
the following lines:
```
    int wpad = (w + MAX_STRIDE - 1) / MAX_STRIDE * MAX_STRIDE - w;
    int hpad = (h + MAX_STRIDE - 1) / MAX_STRIDE * MAX_STRIDE - h;
```
should be modified as:
```
    int wpad = (target_size + MAX_STRIDE - 1) / MAX_STRIDE * MAX_STRIDE - w;
    int hpad = (target_size + MAX_STRIDE - 1) / MAX_STRIDE * MAX_STRIDE - h;
```

**Comment by nihui** [comment]
close for https://github.com/Tencent/ncnn/pull/5506

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
