### ISSUE TITLE
.Net support

### ISSUE THREAD

**Issue by kamlesh-shukla** [Tencent/ncnn#5494]
we need to load model on .net and use, how to do this. Actually we have trained model with celeba spoof and trying to use this with android which not giving result as expected, however same pytorch model giving result in python.
We just want to check what wrong with model during ncnn conversion.
If required, we can send model also.

Thanks 
Kamlesh

**Comment by nihui** [comment]
https://github.com/takuya-takeuchi/NcnnDotNet may help
