### ISSUE TITLE
yolov8Post-processing

### ISSUE THREAD

**Issue by zjkhahah** [Tencent/ncnn#5495]
I printed the loaded model, but it seems that many confidence levels corresponding to categories are 1. Is this normal? Or something went wrong?
The model uses official yolov8s

##############################
    ncnn::Extractor ex = yolo.create_extractor();
    ex.input("in0", in_pad);
    ncnn::Mat out;
    ncnn::Mat transpose_out;
    ex.extract("out0", out);
    transpose(out, transpose_out);

   for (int i = 0; i < transpose_out.h; i++) {
      for (int j = 0; j < transpose_out.w; j++) {
          printf("%f,", transpose_out[i *(4+ num_class) +j]);
        }
      printf("\n");
  }
    printf("width=%d,height=%d,channels=%d\n", transpose_out.w, transpose_out.h, transpose_out.c);
    return 0;
}
############################
This is the output

![1717913260509](https://github.com/Tencent/ncnn/assets/107382486/7725c522-c84c-4cac-a63e-4fd72167582b)
464.000000,736.000000,512.000000,736.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,1.000000,0.500000,0.500000,0.500000,0.500000,1.000000,0.500000,1.000000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.000000,0.500000,1.000000,0.500000,0.500000,0.500000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.000000,0.500000,1.000000,0.500000,0.000000,1.000000,
496.000000,688.000000,512.000000,832.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000,1.000000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,1.000000,0.000000,0.500000,0.000000,1.000000,0.500000,0.500000,0.500000,0.500000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.500000,1.000000,0.500000,0.000000,0.000000,
width=84,height=8400,channels=1

**Comment by whyb** [comment]
I just submitted a pull request for yolov8 example https://github.com/Tencent/ncnn/pull/5506
I hope it can be helpful to you.

**Comment by zjkhahah** [comment]
Thanks for the reply. I seem to have a problem running the code. 
<img width="1057" alt="fbe2c79f74a48a0d08244e51cf9aff0" src="https://github.com/Tencent/ncnn/assets/107382486/1cd9ab92-c025-4d2e-b2e3-02cc194fb570">

I tried to print the highest confidence level for the value of out, but the output did not seem to be correct. These confidence levels felt too high.Below is the result and code I printed

   ncnn::Mat out;
   ex.extract("out0", out);
  cv::Mat a(out.h, out.w, CV_32FC1);
  memcpy((uchar*)a.data, out.data, out.w * out.h * sizeof(float));
  for (int col = 0; col < a.cols; ++col) {
      float maxVal = std::numeric_limits<float>::lowest(); // 初始化为可能的最小浮点数
      for (int row = 4; row < 84; ++row) { // 从第 4 行到第 83 行（索引从 0 开始）
          float value = a.at<float>(row, col);
          if (value > maxVal) {
              maxVal = value; // 更新最大值
          }
      }
      std::cout << "Column " << col << " max value from row 4 to 84 is: " << maxVal << std::endl;
  }

<img width="544" alt="aed0ff9ba1dc19a003a991696c95244" src="https://github.com/Tencent/ncnn/assets/107382486/2a805d3f-86d1-4ad8-956f-8c6b50a2d2f4">

**Comment by whyb** [comment]
> Thanks for the reply. I seem to have a problem running the code. <img alt="fbe2c79f74a48a0d08244e51cf9aff0" width="1057" src="https://private-user-images.githubusercontent.com/107382486/339486029-1cd9ab92-c025-4d2e-b2e3-02cc194fb570.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzkyMjEsIm5iZiI6MTcxODMzODkyMSwicGF0aCI6Ii8xMDczODI0ODYvMzM5NDg2MDI5LTFjZDlhYjkyLWMwMjUtNGQyZS1iMmUzLTAyY2MxOTRmYjU3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwNDIyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzExZDczZjE1OGNmOTQ0YTk0ZTc2ZjE2NTYxMDRiZWRhNGZjYzA0NTQwZjc2Zjg4ZDM4MzllY2ZiYjllMTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hmMl7uGyxOOW9dt6UWSDSvEJgiMw9LZbdaANObjAKkU">
> 
> I tried to print the highest confidence level for the value of out, but the output did not seem to be correct. These confidence levels felt too high.Below is the result and code I printed
> 
> ncnn::Mat out; ex.extract("out0", out); cv::Mat a(out.h, out.w, CV_32FC1); memcpy((uchar*)a.data, out.data, out.w * out.h * sizeof(float)); for (int col = 0; col < a.cols; ++col) { float maxVal = std::numeric_limits::lowest(); // 初始化为可能的最小浮点数 for (int row = 4; row < 84; ++row) { // 从第 4 行到第 83 行（索引从 0 开始） float value = a.at(row, col); if (value > maxVal) { maxVal = value; // 更新最大值 } } std::cout << "Column " << col << " max value from row 4 to 84 is: " << maxVal << std::endl; }
> <img alt="aed0ff9ba1dc19a003a991696c95244" width="544" src="https://private-user-images.githubusercontent.com/107382486/339487508-2a805d3f-86d1-4ad8-956f-8c6b50a2d2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMzkyMjEsIm5iZiI6MTcxODMzODkyMSwicGF0aCI6Ii8xMDczODI0ODYvMzM5NDg3NTA4LTJhODA1ZDNmLTg2ZDEtNGFkOC05NTZmLThjNmI1MGEyZDJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQwNDIyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YWUzZGI3MTEzZjkwZTA0MTk3NzI4N2MzYjQ0YWZiMjAzN2M0YWNmYmViNDg3MzdjNWE2YTk5NDdmZmY3OTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1nO3y7jM73ZM_41nJUzkDXswnR4frbppu1CA7ywDwag">

我知道这个问题，这个原因不是因为我这边的原因，而是您导出的yolov8.ncnn.* 模型是仅固定支持[1,3,640,640]的模型，并不支持动态shape输入造成的。

这个错误的模型会导致输入进去的数据为了保持图像原比例缩放，并不符合模型要求的[1,3,640,640]，实际上有可能是[1,3,640,540]，所以模型内部会错位读取图像，对结果造成严重偏差。

pnnx本身是支持动态shape输入的，您可以去参考  [https://github.com/pnnx/pnnx?tab=readme-ov-file#------detailed-options](https://github.com/pnnx/pnnx?tab=readme-ov-file#------detailed-options)

导出正确的支持动态shape输入的模型，期待您的好消息~🤣

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
