### ISSUE TITLE
【咨询】关于caffe2ncnn的问题

### ISSUE THREAD

**Issue by xhappy** [Tencent/ncnn#550]
Hi，

非常感谢您的工作，对caffe2ncnn工具，有下列问题，求解答：

1. 已开源出来的caffe layers，caffe2ncnn都能将caffe模型转化成功，对么？

2. 对于https://github.com/senlinuc/caffe_ocr 这里面的开源layer，caffe2ncnn支持转化么？

**Comment by BUG1989** [comment]
1.都支持
2.自定义layer需要自己修改，请参考wiki中自定义layer的相关指南

**Comment by nihui** [comment]
LSTM 的层没有支持，其他大部分都可以
