### ISSUE TITLE
ncnn中Mat类设计的内存对齐问题

### ISSUE THREAD

**Issue by HuPengsheet** [Tencent/ncnn#5510]
ncnn中的Mat类，是在channel维度上对齐的，有一个c_step参数。
我在b站看过作者的讲解，说这个对齐主要考虑到ARMV7和openmp下的cache miss导致的性能原因。
想请问一下，这个cache miss是怎么理解，我想学习一下这个内存对齐对于性能的影响。

感谢！

**Comment by nihui** [comment]
armv7 对齐访问速度快
对齐还能避免 openmp false sharing
