### ISSUE TITLE
VkMat可以提取单通道数据吗？为什么Mat提供了channel()函数用于提取单通道，而VkMat没有呢？

### ISSUE THREAD

**Issue by Gao-JF** [Tencent/ncnn#5511]
## detail | 详细描述 | 詳細な説明
我想把RGB的VkMat转为只有R通道的VkMat。

但我发现VkMat没有类似Mat的channel(int c)函数用于提取单通道，那么VkMat如何提取单通道呢？还是说是因为VkMat无法提取单通道才没有channel函数呢？

请求路过的大佬帮忙解答一下（鞠躬）

**Comment by nihui** [comment]
因为 vulkan buffer 在资源绑定时有对齐限制...
直接在 shader 代码里提取单通道即可

**Comment by Gao-JF** [comment]
> 因为 vulkan buffer 在资源绑定时有对齐限制... 直接在 shader 代码里提取单通道即可

哦哦明白🫡，谢谢nihui大佬！
