### ISSUE TITLE
在mac build for android faild

### ISSUE THREAD

**Issue by wuhongsheng** [Tencent/ncnn#5568]
![image](https://github.com/Tencent/ncnn/assets/10295461/d82f2107-e479-49ad-8161-6192706ee931)

![image](https://github.com/Tencent/ncnn/assets/10295461/23c96ee4-d0e0-4c06-8cc0-c41a4c2ef6b0)

**Comment by nihui** [comment]
follow the build guide
https://github.com/Tencent/ncnn/wiki/how-to-build

you need to checkout all submodules, or you could download full source tarball at https://github.com/Tencent/ncnn/releases
