### ISSUE TITLE
Segmentation Fault when extracting output ncnn

### ISSUE THREAD

**Issue by TriCaoChanh** [Tencent/ncnn#5570]
I am using a ConvNeXt UNet model from the following repository: [ConvNeXtV2-Unet](https://github.com/HMS97/ConvNeXtV2-Unet). After converting the model to ONNX and then to NCNN for inference with C++, I encounter a segmentation fault.

I have tried using different versions of NCNN, but the issue persists. Some older versions of NCNN do not even support conversion to the NCNN format with throwing segmentation fault.

I would appreciate any assistance in resolving this issue.

Here is the .param file: [convnext.zip](https://github.com/user-attachments/files/16115357/convnext.zip)

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by TriCaoChanh** [comment]
Thank you for your great work! I have successfully converted my model to NCNN!

Initially, I attempted to convert the model from ONNX to NCNN, but encountered issues due to some operations (ReduceL2 layer) not being implemented in ONNX. I then decided to convert the model directly from PyTorch, and this method worked successfully!
