### ISSUE TITLE
人脸检测点位的模型无法在60pro上推理正确,在之前安卓上是正常的

### ISSUE THREAD

**Issue by lshgw14** [Tencent/ncnn#5577]
## context | 编译/运行环境 | バックグラウンド

1、在mate60pro上对比验证推理正确
2、目前通过两种方式进行排查：
      a.ncnn基础库在鸿蒙化后本身存在在鸿蒙内核个别测试用例不通过的情况，会显示具体的错误信息，根据错误日志定位到layer层（计算模块，其中包含ncnn的各类算法），但对于ncnn源码不是很了解，需要求助。
      b.通过demo打印日志排查出安卓和matepro对比获取值的不同，定位到使用底层ncnn库的具体接口，以及对应的layer层，需求助；
## how to reproduce | 复现步骤 | 再現方法
1.
2.
3.

**Comment by nihui** [comment]
get_thread_siblings 返回错误

**Comment by leizh007** [comment]
我本地测试，在mate60 pro鸿蒙next系统上，编译的时候需要关闭优化
```
export CXXFLAGS="-O0"
export CFLAGS="-O0"
```
并且开启使用vulkan，关闭fp16和bf16
```
net.opt.use_fp16_arithmetic = false;
net.opt.use_packing_layout = false;
net.opt.use_bf16_storage = false;
net.opt.use_vulkan_compute = true;
```
可以出来大体正确的结果，其他情况下，结果不对，而且耗时会特别高。

**Comment by MadHawkEye** [comment]
请问是怎么在鸿蒙next上实现ncnn的？可以分享一下教程或者工程源码吗？谢谢！

**Comment by leizh007** [comment]
> 请问是怎么在鸿蒙next上实现ncnn的？可以分享一下教程或者工程源码吗？谢谢！

你看readme里有编译鸿蒙上用的so啊，直接编译出来放到鸿蒙中用就好了

**Comment by MadHawkEye** [comment]
> 请问是怎么在鸿蒙next上实现ncnn的？可以分享一下教程或者工程源码吗？谢谢！

111

**Comment by MadHawkEye** [comment]
> > 请问是怎么在鸿蒙next上实现ncnn的？可以分享一下教程或者工程源码吗？谢谢！
> 
> 你看readme里有编译鸿蒙上用的so啊，直接编译出来放到鸿蒙中用就好了

我是按照这个方法做的交叉编译，-DOHOS_STL=c++_static 、-DOHOS_STL=c++_shared 都试了，但是编译出来的是.a静态库文件，不是.sc动态库文件，请问你是怎么编译的？请帮忙po个链接，谢谢！另外问一下你是在linux还是Windows下编译的呢？
![image](https://github.com/user-attachments/assets/8e2e032b-a09d-4e57-b301-6900c0bbad4b)

**Comment by leizh007** [comment]
> > > 请问是怎么在鸿蒙next上实现ncnn的？可以分享一下教程或者工程源码吗？谢谢！
> > 
> > 
> > 你看readme里有编译鸿蒙上用的so啊，直接编译出来放到鸿蒙中用就好了
> 
> 我是按照这个方法做的交叉编译，-DOHOS_STL=c++_static 、-DOHOS_STL=c++_shared 都试了，但是编译出来的是.a静态库文件，不是.sc动态库文件，请问你是怎么编译的？请帮忙po个链接，谢谢！另外问一下你是在linux还是Windows下编译的呢？ ![image](https://private-user-images.githubusercontent.com/144407150/356121392-8e2e032b-a09d-4e57-b301-6900c0bbad4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDgzMTAsIm5iZiI6MTcyMzEwODAxMCwicGF0aCI6Ii8xNDQ0MDcxNTAvMzU2MTIxMzkyLThlMmUwMzJiLWEwOWQtNGU1Ny1iMzAxLTY5MDBjMGJiYWQ0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwOTA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODU3Nzc5NDkyMGIzNmExMzNhODk2NjRmY2FmNDJkYjU4M2VjNjBiMjMwNzM5MmU5ZGZjYWFmYmQ5MDY3M2Q1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sAv2mBFSihE7AKJH_wKlw1so_ivEpJF8WuPM6eW59e0)

额。。。老铁，-DOHOS_STL=c++_static 、-DOHOS_STL=c++_shared你这个链接的是C++的静态库还是C++的动态库啊。。。



我在本地起了个docker，跑的ubuntu20的，用下面这个脚步跑的，路径改成你自己本地的路径

```
mkdir build && cd build

export CMAKE_FILE_PATH=/home/leizh007/ohos-sdk-windows_linux-public/ohos-sdk/linux/native/build-tools/cmake/bin/cmake
export CMAKE_TOOLCHAIN_FILE_PATH=/home/leizh007/ohos-sdk-windows_linux-public/ohos-sdk/linux/native/build/cmake/ohos.toolchain.cmake

export CXXFLAGS="-O0"
export CFLAGS="-O0"

${CMAKE_FILE_PATH} -DBUILD_SHARED_LIBS=ON \
    -DOHOS_STL=c++_shared \
    -DOHOS_ARCH=arm64-v8a \
    -DOHOS_PLATFORM=OHOS \
    -DNCNN_SHARED_LIB=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DNCNN_VULKAN=ON \
    -DNCNN_SIMPLEOMP=ON \
    -DNCNN_OPENMP=ON \
    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE_PATH} .. && make

DEST_DIR=/home/leizh007/ncnn_install
if [ -d ${DEST_DIR} ]; then
    rm -rf ${DEST_DIR}
fi

make install DESTDIR=${DEST_DIR}

````

**Comment by lexuszhi1990** [comment]
@leizh007 老铁，我这边把ncnn模型集成进去以后，在最新的IDE DevEco Studio NEXT Developer Beta3/5.0.3.600 上，debug模式下正常跑通了，然后切换到release模式下
![image](https://github.com/user-attachments/assets/45ad6dda-cd62-4a4e-9df9-2a8cdcf88518)
，模型推理失败了，表现为耗时几乎为0，不返回结果。
![image](https://github.com/user-attachments/assets/4800c778-bebe-4052-9cb1-b3a84a838089)

大佬有遇到这种情况吗？

**Comment by leizh007** [comment]
> @leizh007 老铁，我这边把ncnn模型集成进去以后，在最新的IDE DevEco Studio NEXT Developer Beta3/5.0.3.600 上，debug模式下正常跑通了，然后切换到release模式下 ![image](https://private-user-images.githubusercontent.com/548467/358554066-45ad6dda-cd62-4a4e-9df9-2a8cdcf88518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTExODAsIm5iZiI6MTcyMzgxMDg4MCwicGF0aCI6Ii81NDg0NjcvMzU4NTU0MDY2LTQ1YWQ2ZGRhLWNkNjItNGE0ZS05ZGY5LTJhOGNkY2Y4ODUxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMjIxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjc5NGUzYmIzMjBjNDc5NWZhN2MzNmZhZmFkNjRlMmI2MWUxNmNlZTk4NGNjNzI5ODFmNDM3YmRmNTkzZDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JvyCVr5dU8QZaUFVnBXBIqFuJuxc3ww7e-LEWYyuhl8) ，模型推理失败了，表现为耗时几乎为0，不返回结果。
> 
> 模式	耗时
> debug	9.760 ms
> release	0.029 ms
> 关掉代码混淆以后也是这样子，大佬有遇到这种情况吗？

是这样的。。。我这也是这种现象。。。

**Comment by lexuszhi1990** [comment]
> > @leizh007 老铁，我这边把ncnn模型集成进去以后，在最新的IDE DevEco Studio NEXT Developer Beta3/5.0.3.600 上，debug模式下正常跑通了，然后切换到release模式下 ![image](https://private-user-images.githubusercontent.com/548467/358554066-45ad6dda-cd62-4a4e-9df9-2a8cdcf88518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MTExODAsIm5iZiI6MTcyMzgxMDg4MCwicGF0aCI6Ii81NDg0NjcvMzU4NTU0MDY2LTQ1YWQ2ZGRhLWNkNjItNGE0ZS05ZGY5LTJhOGNkY2Y4ODUxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQxMjIxMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjc5NGUzYmIzMjBjNDc5NWZhN2MzNmZhZmFkNjRlMmI2MWUxNmNlZTk4NGNjNzI5ODFmNDM3YmRmNTkzZDI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JvyCVr5dU8QZaUFVnBXBIqFuJuxc3ww7e-LEWYyuhl8) ，模型推理失败了，表现为耗时几乎为0，不返回结果。
> > 模式	耗时
> > debug	9.760 ms
> > release	0.029 ms
> > 关掉代码混淆以后也是这样子，大佬有遇到这种情况吗？
> 
> 是这样的。。。我这也是这种现象。。。

那这可就尴尬了，老铁。。本来已经在写交付文档了...

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5740

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/8105c75120f4f3a996395f21323e0578d65664dc

感谢报告
