### ISSUE TITLE
pytorch导出成onnx再转ncnn出错

### ISSUE THREAD

**Issue by caohaitao** [Tencent/ncnn#558]
pytorch中的view操作，转成onnx后，再通过onnx2ncnn转模型，报 Shape not supported yet! Slice not supported yet!，需要怎么解决啊？

**Comment by lizhengwei1992** [comment]
@caohaitao 请教一下：怎么将onnx转换成ncnn？ 哪里有示例代码？

**Comment by caohaitao** [comment]
@lizhengwei1992 ncnn的工程里面tools目录下有onnx2ncnn

**Comment by JosephineRabbit** [comment]
hi～我也想把pytorch转成ncnn，请问这个问题解决了吗？

**Comment by zym1119** [comment]
为什么不直接用pytorch converter，把pytorch net转成ncnn

**Comment by Xiangyu-CAS** [comment]
在model文件中，不要做 out.size(0)这种操作，这个操作会引入 shape操作符

**Comment by nihui** [comment]
试试看 daquexian 的优化工具，可以把这些op去掉
https://github.com/daquexian/onnx-simplifier

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
