### ISSUE TITLE
CPU推理没问题GPU 推理报错

### ISSUE THREAD

**Issue by wuhongsheng** [Tencent/ncnn#5587]
Android vulkan
https://github.com/wuhongsheng/ncnn-android-lighttrack/blob/main/lighttrack/src/main/assets/lighttrack_update.param

**Comment by nihui** [comment]
请把报错信息提供下？

**Comment by wuhongsheng** [comment]
> 请把报错信息提供下？

![image](https://github.com/user-attachments/assets/e9dff241-f115-4810-825b-b45dfff4d2e9)

**Comment by wuhongsheng** [comment]
加了这行可以了，但是速度无提升
net_init.set_vulkan_device(0);
