### ISSUE TITLE
efficientvit onnx转换为ncnn后出现无参数的LayerNorm，推理时ex.extract()返回-100

### ISSUE THREAD

**Issue by heivens** [Tencent/ncnn#5590]
## model | 模型 | モデル
1. original model
onnx结构:
![image](https://github.com/user-attachments/assets/2b135c9d-8c71-413e-86a5-2eca56ecb839)
ncnnj结构:
![image](https://github.com/user-attachments/assets/c79447c9-bf4e-4d72-bce0-1c2b1cf7b26e)

看起来像是把onnx中MatMul之后到Div的结点转为了ncnn的LayerNorm，但是无参数

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx

**Comment by heivens** [comment]
感谢大佬
