### ISSUE TITLE
ios非调试中ruapu_init异常

### ISSUE THREAD

**Issue by mutemoon** [Tencent/ncnn#5591]
## error log | 日志或报错信息 | ログ
Thread 1: EXC_BAD_INSTRUCTION (code=1, subcode=0xd5380000)
ruapu_some_cpuid at ruapu.h:231

[`RUAPU_INSTCODE(cpuid, 0xd5380000) // mrs x0,midr_el1`
](https://github.com/nihui/ruapu/blob/8a048fb0253149efd66139cb1c8ea2ef2dc7daad/ruapu.h#L231)

## context | 编译/运行环境 | バックグラウンド
iphone 15pro
ios 18.0
xcode 15.4

## how to reproduce | 复现步骤 | 再現方法
测试工程：https://github.com/mutemoon/test-ruapu

## more | 其他 | その他
同样的问题：https://github.com/Tencent/ncnn/issues/5433#issue-2247251684

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5593

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/997c8926d706db5f9e4098aec8ed51c49ab9417c

感谢报告
