### ISSUE TITLE
安卓上ncnn开启Vulkan compute推理后，GPU没有被调用？

### ISSUE THREAD

**Issue by Rubint0x** [Tencent/ncnn#5594]
## error log | 日志或报错信息 | ログ

**开启vulkan compute代码**
```
 // net init
    ncnn::Option opt;
    opt.lightmode = true;
    if (ncnn::get_gpu_count() != 0){
        opt.use_vulkan_compute = true;
        net_init.set_vulkan_device(0);
        net_update.set_vulkan_device(0);
    }
    net_init.opt = opt;
    net_update.opt = opt;
```

## context | 编译/运行环境 | バックグラウンド
手机型号：**OPPO PEDM00**
GPU型号：**Adreno (TM) 650**
NCNN：**ncnn-20240410-android-vulkan**
## how to reproduce | 复现步骤 | 再現方法

**GPU下推理可以看到GPU推理与CPU推理下的GPU负载一致，GPU没有被调用**
![image](https://github.com/user-attachments/assets/205bd468-3b18-46c9-b575-630698f79056)

**在同样机型条件下运行作者的人脸识别项目可以看到GPU可以被调用（这个CPU是GPU运行速度的二倍是正常的吗= =）。**

![image](https://github.com/user-attachments/assets/54ab5117-cc26-4636-92b7-8d4fb9d9c2b2)

## more | 其他 | その他
提供的项目运行param
[param.zip](https://github.com/user-attachments/files/16278875/param.zip)

**Comment by wzyforgit** [comment]
CPU是GPU运行速度的二倍很正常

**Comment by Rubint0x** [comment]
<img width="441" alt="5" src="https://github.com/user-attachments/assets/9fe0f11a-f638-4a5d-89cf-631f37a5b146">

**我将设置GPU的代码放在loadparam前，现在GPU可以被调用但是只有17%，负载很低，请问有什么办法像作者一样调用率达到50+%，或者可以让我看到每层运行时间的方法吗。**
