### ISSUE TITLE
使用onnx2ncnn转换模型，部分权重变为-nan

### ISSUE THREAD

**Issue by sen-O** [Tencent/ncnn#5599]
### 使用onnx2ncnn转换模型，部分权重变为-nan，使用netron可视化源onnx模型权重如下：
![ncnn](https://github.com/user-attachments/assets/15cb0da2-8c21-44c7-9acb-94b0ed4050ff)
### 使用ncnn读取模型权重并打印结果如下：
![error](https://github.com/user-attachments/assets/17560b0b-fbc6-41d9-955e-408c534aa6c2)
### 同时转换输出的bin文件无法使用netron可视化
![bin'](https://github.com/user-attachments/assets/57838875-15d3-4789-8b5b-2d18693b80df)

## model | 模型 | モデル
1. original model
[https://github.com/opencv/opencv_zoo/blob/main/models/object_tracking_vittrack/object_tracking_vittrack_2023sep.onnx](url)
## how to reproduce | 复现步骤 | 再現方法
读取ncnn模型打印权重
![main](https://github.com/user-attachments/assets/af4c0d7f-1b6a-45d2-be9e-606459e0f377)

**Comment by wzyforgit** [comment]
用pnnx转

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
