### ISSUE TITLE
加上openmp程序就闪退是什么原因？

### ISSUE THREAD

**Issue by zjchuyp** [Tencent/ncnn#56]
编译可以通过，运行就闪退。安卓平台 。

**Comment by BKZero** [comment]
你是在哪儿加的？编译.a还是.so？
我这里倒是能用，然而感觉好像没加上，因为更改threads数量cpu占用和速度完全没有影响。

**Comment by caochunyuan** [comment]
我在.a中加的openmp,我的也没有加上,更改线程数速度没变

**Comment by BKZero** [comment]
我后来发现可能是小米资源管理的问题，换了其他手机之后更改线程数量速度有所改变。但是不管怎么样也调不出来作者宣称的速度。分别在中兴、华为、oppo上进行过测试。

**Comment by nihui** [comment]
要使用最新的 android ndk 编译
