### ISSUE TITLE
ncnn 跑自己训练的MobileNetv2-SSDLite模型没结果出来

### ISSUE THREAD

**Issue by NOON47** [Tencent/ncnn#560]
ncnn 跑自己训练的MobileNetv2-SSDLite模型没结果出来，同样的模型用OpenCV的接口是可以有结果的，请问是怎么回事，有没有相关的资料可参考，是模型转换的时候出了问题，还是还需要增加什么东西？

**Comment by ouyanghuiyu** [comment]
我也是这个问题呀，请问解决了吗

**Comment by hellocsi** [comment]
是什么模型转的？Caffe吗？有没有分析原始模型参数文件和ncnn.param中不同的地方？

**Comment by nihui** [comment]
example 里的 mobilenetv2_ssdlite 模型上传到这里了 https://github.com/nihui/ncnn-assets/tree/master/models
已使用ncnnoptimize优化模型和fp16存储
