### ISSUE TITLE
最近想在sm84xx的armv9-a上部署，如何支持armv9-a的sve，sme？

### ISSUE THREAD

**Issue by sumagic** [Tencent/ncnn#5602]
## detail | 详细描述 | 詳細な説明
如题

**Comment by sumagic** [comment]
另外，在android ndk上编译ncnn，怎么支持armv9a的sve呢

**Comment by nihui** [comment]
sve是根据编译器能力 **自动** 开启的，但是 sm84xx 并不支持 sve sme 指令集，所以并没有用。。
