### ISSUE TITLE
arm平台使用开启int8功能后，检测不到目标

### ISSUE THREAD

**Issue by ranson** [Tencent/ncnn#561]
接着#547问题，我合了ef36d79后，int8依旧不work.
请帮忙分析一下。

原问题如下：
arm平台使用开启int8功能后，检测不到目标。
我用的是mobilenetssd的网络，用x86编译的caffe2ncnn来做模型的转换。
同样的模型，我在arm平台上编译x86的layer的代码，来做对比实验，发现是可以检测到目标的。
另外，同样的caffe模型用https://github.com/BUG1989/ncnn.git的代码来试，int8功能是ok的。
请问谁有遇到过相关问题吗？求解...

**Comment by kalcohol** [comment]
int8 is under experimental for now. if u want to use int8 with ncnn, be carefull pls. all model u will use should be test in all conditions.
if your model work well with version of @BUG1989 , just fork and test, that is a good option.

**Comment by nihui** [comment]
try the latest code
feel free to reopen this issue if you still encounter the same problem ;)
