### ISSUE TITLE
使用最新版的pnnx，pytorch实现的一个模型里面用了一个全连接层nn.linear()，在ncnn会转换为F.linear，但是报错ncnn没有该层。

### ISSUE THREAD

**Issue by 2236133143** [Tencent/ncnn#5633]
## model | 模型 | モデル
1. original model

## how to reproduce | 复现步骤 | 再現方法
1.运行my_lstm.py
2.运行转换工具
3.运行ncnn_lstm.cpp
[test.zip](https://github.com/user-attachments/files/16635546/test.zip)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5634
