### ISSUE TITLE
GiHub actions for Android build is failing

### ISSUE THREAD

**Issue by csukuangfj** [Tencent/ncnn#5636]
Please see
https://github.com/Tencent/ncnn/actions/workflows/android.yml

<img width="1289" alt="Screenshot 2024-08-18 at 07 46 47" src="https://github.com/user-attachments/assets/ac459a00-11e8-4952-abd0-06d47379f110">

**Comment by nihui** [comment]
ref https://github.com/android/ndk/issues/2054

**Comment by csukuangfj** [comment]
Thanks!

**Comment by nihui** [comment]
fixed in upstream ndk r27b
