### ISSUE TITLE
新加的examples/yolov8.cpp未对c++98兼容

### ISSUE THREAD

**Issue by wxtshr001** [Tencent/ncnn#5637]
## error log | 日志或报错信息 | ログ
/home/wang/data/opensource/ncnn/examples/yolov8.cpp: In function ‘void parse_yolov8_detections(float*, float, int, int, int, int, int, std::vector<Object>&)’:
/home/wang/data/opensource/ncnn/examples/yolov8.cpp:178:14: error: ‘row_ptr’ does not name a type
         auto row_ptr = output.row(i).ptr<float>();
              ^
/home/wang/data/opensource/ncnn/examples/yolov8.cpp:179:14: error: ‘bboxes_ptr’ does not name a type
         auto bboxes_ptr = row_ptr;
              ^
/home/wang/data/opensource/ncnn/examples/yolov8.cpp:180:14: error: ‘scores_ptr’ does not name a type
         auto scores_ptr = row_ptr + 4;
              ^
/home/wang/data/opensource/ncnn/examples/yolov8.cpp:181:14: error: ‘max_s_ptr’ does not name a type
         auto max_s_ptr = std::max_element(scores_ptr, scores_ptr + num_labels);
              ^
/home/wang/data/opensource/ncnn/examples/yolov8.cpp:182:24: error: ‘max_s_ptr’ was not declared in this scope
         float score = *max_s_ptr;
                        ^
/home/wang/data/opensource/ncnn/examples/yolov8.cpp:185:24: error: ‘bboxes_ptr’ was not declared in this scope
             float x = *bboxes_ptr++;
                        ^
/home/wang/data/opensource/ncnn/examples/yolov8.cpp:201:40: error: ‘scores_ptr’ was not declared in this scope
             object.label = max_s_ptr - scores_ptr;
                                        ^
/home/wang/data/opensource/ncnn/examples/yolov8.cpp:204:24: error: ‘class std::vector<Object>’ has no member named ‘emplace_back’
             detections.emplace_back(object);
                        ^
examples/CMakeFiles/yolov8.dir/build.make:75: recipe for target 'examples/CMakeFiles/yolov8.dir/yolov8.cpp.o' failed
make[2]: *** [examples/CMakeFiles/yolov8.dir/yolov8.cpp.o] Error 1
CMakeFiles/Makefile2:377: recipe for target 'examples/CMakeFiles/yolov8.dir/all' failed
make[1]: *** [examples/CMakeFiles/yolov8.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

## context | 编译/运行环境 | バックグラウンド
opencv version: 2.4.13

## how to reproduce | 复现步骤 | 再現方法
cmake ..;make -j4

## more | 其他 | その他
examples里只有在OpenCV_VERSION_MAJOR > 3的时候才会启用c++11 standard
auto和emplace_back都是c++11才开始支持

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
