### ISSUE TITLE
HarmonyOS cpu.cpp get_thread_siblings 返回错误

### ISSUE THREAD

**Issue by WayneHalake** [Tencent/ncnn#5644]
HarmonyOS 中 cpu.cpp get_thread_siblings 返回错误

_Originally posted by @nihui in https://github.com/Tencent/ncnn/issues/5577#issuecomment-2228230505_

**Comment by WayneHalake** [comment]
HarmonyOS中无 /sys/devices/system/cpu/cpu%d/topology/thread_siblings 该文件，可通过修改为/sys/devices/system/cpu/cpu%d/topology/thread_siblings_list修复

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5740

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/8105c75120f4f3a996395f21323e0578d65664dc

感谢报告
