### ISSUE TITLE
faster rcnn测试耗时

### ISSUE THREAD

**Issue by lvpchen** [Tencent/ncnn#565]
在pc上，用ncnn跑faster rcnn训练的目标检测模型，结果正确，但耗时25-30秒，正常吗？

**Comment by sunsetmail** [comment]
我测试差不多，但提特征耗时330ms，提特征竟然比安卓慢了好多，QAQ，很疑惑~~

**Comment by nihui** [comment]
试试看设置多线程
faster-rcnn 是挺慢的，pc 上主要是验证结果的

**Comment by zhedasuiyuan** [comment]
> 试试看设置多线程
> faster-rcnn 是挺慢的，pc 上主要是验证结果的
谢谢@nihui。我能把一个caffe的faster rcnn model转换为ncnn的形式。但是在一些示例image上跟本来的caffe model准确率差蛮多的，比如有一些object就是没有detect到。请问有什么方法解决呢？因为model并没有变小，也没有压缩。我本来以为准确率应该是差不多的。谢谢！

**Comment by nihui** [comment]
有些超参，比如 score threshold，topk 等会影响最终检测的物体数量
模型本身应该和caffe是对上的

**Comment by zhedasuiyuan** [comment]
> 有些超参，比如 score threshold，topk 等会影响最终检测的物体数量
> 模型本身应该和caffe是对上的

@nihui 非常感谢您的回复。我之前已经确定我用的超参和他们用的一样。但是出来的detection还是很不一样。经过多次实验，我发现faster-rcnn.cpp 里的post-processing 和他们很不一样。他们有个例子在这里。https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/demo.ipynb

主要有两点不一样的地方。第一点，他们不会因为background的cls_score高，就把那个roi label为background。相反，他们不把background的cls_score和正常的class去比较。第二点，他们先对每个class的bbox做NMS，然后再计算cls_score最大的值和对应的label。我觉得这样比较make sense。而我们例子里先计算每个roi cls_score值最大的label，再做NMS。这样的问题是会在NMS之前丢掉一些object。他们的代码如下：

```
im = cv2.imread(im_file)
scores, boxes, attr_scores, rel_scores = im_detect(net, im)

# Keep the original boxes, don't worry about the regression bbox outputs
rois = net.blobs['rois'].data.copy()
# unscale back to raw image space
blobs, im_scales = _get_blobs(im, None)

cls_boxes = rois[:, 1:5] / im_scales[0]
cls_prob = net.blobs['cls_prob'].data
attr_prob = net.blobs['attr_prob'].data
pool5 = net.blobs['pool5_flat'].data

# Keep only the best detections
max_conf = np.zeros((rois.shape[0]))
for cls_ind in range(1,cls_prob.shape[1]):
    cls_scores = scores[:, cls_ind]
    dets = np.hstack((cls_boxes, cls_scores[:, np.newaxis])).astype(np.float32)
    keep = np.array(nms(dets, cfg.TEST.NMS))
    max_conf[keep] = np.where(cls_scores[keep] > max_conf[keep], cls_scores[keep], max_conf[keep])

```
谢谢！
