### ISSUE TITLE
yolov8的py示例未更新

### ISSUE THREAD

**Issue by cookielive** [Tencent/ncnn#5654]
## detail | 详细描述 | 詳細な説明
ncnn/python/ncnn/model_zoo/yolov8.py

还是需要三个输出的版本，现在转换的v8模型只有一个输出该如何处理，麻烦出一个py版本的示例

**Comment by whyb** [comment]
> ## detail | 详细描述 | 詳細な説明
> 
> ncnn/python/ncnn/model_zoo/yolov8.py
> 
> 还是需要三个输出的版本，现在转换的v8模型只有一个输出该如何处理，麻烦出一个py版本的示例

@cookielive  您可以参考这个c++示例里面开头从第18行到第45行中所提到的导出yolov8的ncnn模型的方法。
https://github.com/Tencent/ncnn/blob/master/examples/yolov8.cpp

**Comment by whale1st** [comment]
> ## detail | 详细描述 | 詳細な説明
> ncnn/python/ncnn/model_zoo/yolov8.py
> 
> 还是需要三个输出的版本，现在转换的v8模型只有一个输出该如何处理，麻烦出一个py版本的示例

可以参考: https://github.com/ultralytics/ultralytics/pull/7961/commits/a007668e1fa8d5d586e6daa3924d65cfb139b8ac#diff-9606bf4bd68abeeea710df3b6911239d05da8d8d0b776cd9ed3e91465c109cb6

**Comment by cookielive** [comment]
> > ## detail | 详细描述 | 詳細な説明
> > ncnn/python/ncnn/model_zoo/yolov8.py
> > 还是需要三个输出的版本，现在转换的v8模型只有一个输出该如何处理，麻烦出一个py版本的示例
> 
> @cookielive 您可以参考这个c++示例里面开头从第18行到第45行中所提到的导出yolov8的ncnn模型的方法。 https://github.com/Tencent/ncnn/blob/master/examples/yolov8.cpp

感谢回答，昨天参考此cpp结合gpt成功做了一版py，但实际推理和解析速度 不如yolov8直接使用pt推理的速度，暂时还是用pt了

**Comment by cookielive** [comment]
> > ## detail | 详细描述 | 詳細な説明
> > ncnn/python/ncnn/model_zoo/yolov8.py
> > 还是需要三个输出的版本，现在转换的v8模型只有一个输出该如何处理，麻烦出一个py版本的示例
> 
> 可以参考: https://github.com/ultralytics/ultralytics/tree/a007668e1fa8d5d586e6daa3924d65cfb139b8ac/examples/YOLOv8-NCNN-Python-Det-Pose-Cls-Seg-Obb

感谢，我也参考下

**Comment by nihui** [comment]
hi, yolov8 examples are updated with full support for detection, segmentation, classification, pose estimation and obb
https://github.com/Tencent/ncnn/tree/master/examples

android demo
https://github.com/nihui/ncnn-android-yolov8

detailed instruction (zh)
https://zhuanlan.zhihu.com/p/16030630352
