### ISSUE TITLE
模型的前后处理部分，可以通过ncnn::set_omp_num_threads(1);控制在单核上吗

### ISSUE THREAD

**Issue by qiu-pinggaizi** [Tencent/ncnn#5669]
在Android上用ncnn部署模型，ncnn::set_omp_num_threads(1);可以控制模型推理占用的cpu核数，但模型的前后处理不受限制，这是正常的吗@lihui

**Comment by qiu-pinggaizi** [comment]
ncnn::set_omp_num_threads(1);     opt.num_threads = 1; 有什么区别呢，为什么benchmark中需要都设置一下

**Comment by wzyforgit** [comment]
你把前后处理塞进模型了？

**Comment by qiu-pinggaizi** [comment]
没有，前后处理是单独处理，没放进模型里面

**Comment by wzyforgit** [comment]
那就跟ncnn无关了，自己设置去

**Comment by qiu-pinggaizi** [comment]
ok
