### ISSUE TITLE
Cortex-A510 android 64bit系统，运行benchncnn crash

### ISSUE THREAD

**Issue by runrunrun1994** [Tencent/ncnn#5697]
## error log | 日志或报错信息 | ログ
loop_count = 4
num_threads = 4
powersave = 2
gpu_device = -1
cooling_down = 1
          squeezenet  min =   51.32  max =  163.52  avg =   91.45
     squeezenet_int8  min =   72.46  max =  108.40  avg =   90.00
**Segmentation fault**

堆栈信息
512 total frames
09-05 17:43:59.238  3653  3653 F DEBUG   : backtrace:
09-05 17:43:59.238  3653  3653 F DEBUG   :       #00 pc 0000000000025784  /data/local/tmp/benchmark/benchncnn (ncnn::cpu_support_arm_asimdfhm()+0) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #01 pc 000000000013e18c  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+80) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #02 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #03 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #04 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #05 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #06 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #07 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #08 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #09 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #10 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #11 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #12 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #13 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #14 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #15 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.238  3653  3653 F DEBUG   :       #16 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)

...... 此处省略500条..............
09-05 17:43:59.257  3653  3653 F DEBUG   :       #509 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.257  3653  3653 F DEBUG   :       #510 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)
09-05 17:43:59.257  3653  3653 F DEBUG   :       #511 pc 000000000013e1a8  /data/local/tmp/benchmark/benchncnn (ncnn::innerproduct_transform_kernel_fp16s_neon_asimdfhm(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Option const&)+108) (BuildId: 6c7af00264dd6781620b2af0ac8a8ab5203d242e)

## context | 编译/运行环境 | バックグラウンド
CPU     : Cortex-A510
运行环境: android 64位系统
## how to reproduce | 复现步骤 | 再現方法
1.
2.
3.

**Comment by runrunrun1994** [comment]
使用的android-ndk-r21e 太老，nihui建议使用ndk 27，使用ndk27问题解决。
nihui,yyds!

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/5804
