### ISSUE TITLE
pnnx转onnx模型会有一个open failed

### ISSUE THREAD

**Issue by kazyun** [Tencent/ncnn#5699]
## error log | 日志或报错信息 | ログ
pnnxparam = ../scene_resnet18_0905.pnnx.param
pnnxbin = ../scene_resnet18_0905.pnnx.bin
pnnxpy = ../scene_resnet18_0905_pnnx.py
pnnxonnx = ../scene_resnet18_0905.pnnx.onnx
ncnnparam = ../scene_resnet18_0905.ncnn.param
ncnnbin = ../scene_resnet18_0905.ncnn.bin
ncnnpy = ../scene_resnet18_0905_ncnn.py
fp16 = 1
optlevel = 2
device = cpu
inputshape = [1,3,180,180]f32
inputshape2 =
customop =
moduleop =
############# pass_level0 onnx
inline_containers ...                 0.00ms
eliminate_noop ...                    0.06ms
fold_constants ...                    0.04ms
canonicalize ...                      0.09ms
shape_inference ...                 194.11ms
fold_constants_dynamic_shape ...      0.07ms
inline_if_graph ...                   0.01ms
fuse_constant_as_attribute ...        0.07ms
eliminate_noop_with_shape ...         0.03ms
┌───────────────────┬──────────┬──────────┐
│                   │ orig     │ opt      │
├───────────────────┼──────────┼──────────┤
│ node              │ 52       │ 52       │
│ initializer       │ 49       │ 48       │
│ functions         │ 0        │ 0        │
├───────────────────┼──────────┼──────────┤
│ nn module op      │ 0        │ 0        │
│ custom module op  │ 0        │ 0        │
│ aten op           │ 0        │ 0        │
│ prims op          │ 0        │ 0        │
│ onnx native op    │ 52       │ 52       │
├───────────────────┼──────────┼──────────┤
│ Add               │ 8        │ 8        │
│ Conv              │ 20       │ 20       │
│ Gemm              │ 4        │ 4        │
│ GlobalAveragePool │ 1        │ 1        │
│ MaxPool           │ 1        │ 1        │
│ Relu              │ 17       │ 17       │
│ Reshape           │ 1        │ 1        │
└───────────────────┴──────────┴──────────┘
############# pass_level3
open failed
## model | 模型 | モデル
1.  基于resnet18.onnx

## how to reproduce | 复现步骤 | 再現方法
1.
3.
4.

这个open failed对于生成的ncnn.param, ncnn.bin使用是否会有影响呢

**Comment by wangchu-chu** [comment]
> 无影响

哇塞谁懂相同报错一搜就出现大佬回答的救赎感😭

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/6492

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/6ebcb644c514a8d5e2a6a07a99099818b5ce7fdc
