### ISSUE TITLE
shufflnet v2+ssd 使用caffe2int8工具生成table 转化到int8后 performance下降特别多

### ISSUE THREAD

**Issue by DL-85** [Tencent/ncnn#571]
如题，mobilnet ssd转化到int8后performance下降很少，想知道可能是什么原因导致的？

**Comment by insmod-he** [comment]
小模型的冗余度很低,直接做8bit量化detection精度会急剧下降.

**Comment by DL-85** [comment]
之前已经完成了mobilenet+ssd的int8压缩 精度并没有损失很多，所以推测可能是转换table的时候出了问题，使用caffe2int8工具和ncnn转换之前是否需要将caffe的BN和Scale层合并到Conv层中？

**Comment by zyc4me** [comment]
@DL-85 hi，有两个问题想请教你一下，在线等。。
      1、你做的这个mobilenet+ssd 的int8 压缩 ，请问精度具体下降了多少呢？我在voc上做了测试，从68.6下降到了62.9，还是比较多的，你的是怎么衡量的呢？
      2、shufflenetv2 +ssd 你在voc上能训到多少的map呢？我训了很久，1x的shufflenetv2 ssdlite map在61就上不去了。

**Comment by BUG1989** [comment]
@zyc4me hi，你可以尝试混合精度，conv1 layer这一层采用Float32进行计算，mAP会有可见的提升。

**Comment by DL-85** [comment]
@1976277169 参见https://github.com/Tencent/ncnn/wiki/quantized-int8-inference#mixed-precision-inference 或者可以查看issue https://github.com/BUG1989/caffe-int8-convert-tools/issues/10

**Comment by 1976277169** [comment]
> @1976277169 参见[mixed-precision-inference](https://github.com/Tencent/ncnn/wiki/quantized-int8-inference#mixed-precision-inference) 或者可以查看issue [BUG1989/caffe-int8-convert-tools#10](https://github.com/BUG1989/caffe-int8-convert-tools/issues/10)

好滴，谢谢啦~

**Comment by kadebudongtan** [comment]
> @DL-85 hi，有两个问题想请教你一下，在线等。。
> 1、你做的这个mobilenet+ssd 的int8 压缩 ，请问精度具体下降了多少呢？我在voc上做了测试，从68.6下降到了62.9，还是比较多的，你的是怎么衡量的呢？
> 2、shufflenetv2 +ssd 你在voc上能训到多少的map呢？我训了很久，1x的shufflenetv2 ssdlite map在61就上不去了。

转为ncnn后如何测试mAP呢？

**Comment by DanyangYue** [comment]
@DL-85 你好想问一下mobilnet ssd int8量化有什么技巧吗，可以分享学习一下吗
