### ISSUE TITLE
Flatten not supported yet

### ISSUE THREAD

**Issue by tanjiarui** [Tencent/ncnn#573]
The document here https://github.com/Tencent/ncnn/wiki/operation-param-weight-table reveals that flatten op is part of this tool, but this op isn't implemented in the source onnx2ncnn. Truly hope someone can perfect this defect. @nihui

**Comment by tanjiarui** [comment]
Also, it's better to add Identity op.

**Comment by ForestWang** [comment]
got the same problem

**Comment by nihui** [comment]
flatten support added in https://github.com/Tencent/ncnn/commit/bbe044f3853fcd2fb81d9652aaa03723ae6232e4
