### ISSUE TITLE
pnnx 转换 gemm op的疑问

### ISSUE THREAD

**Issue by huoshuai-dot** [Tencent/ncnn#5731]
Q1:      https://github.com/Tencent/ncnn/blob/1c7af00499380dfe760e6131bea63db210bdab2e/tools/pnnx/src/pass_ncnn/nn_Linear.cpp#L58 op->params["10"] = captured_params.at("bias").b ? 4 : -1; 可以看到gemm的导出只考虑了constant_broadcast_type_C 为4的情况，那么如何理解constant_broadcast_type_C这个参数的意义呢？设置为4是否在模型转换上存在一定的局限性？ @nihui

**Comment by nihui** [comment]
broadcast_type_C 是 gemm bias 的广播方向，根据 C 的shape而定，nn.Linear 的 bias 只有这一种shape
-1 代表没有 bias
