### ISSUE TITLE
extract崩溃

### ISSUE THREAD

**Issue by wkt** [Tencent/ncnn#575]
从 https://github.com/lsy17096535/face-landmark/tree/master/model 下载caffemodel和prototxt
使用upgrade_net_proto_text转换prototext
再用caffe2ncnn转换获取face.param和face.bin
修改examples/squeezenet.cpp:
    squeezenet.load_param("face.param");
    squeezenet.load_model("face.bin");
和
    //根据 https://github.com/lsy17096535/face-landmark/blob/master/face_landmark.cpp
    ex.extract("Dense3", out);

然后编译运行，结果崩溃了，最后发现崩溃位置在
    ex.extract("Dense3", out);

**Comment by nihui** [comment]
检查输入图的尺寸和通道数
