### ISSUE TITLE
need yolo inference code 

### ISSUE THREAD

**Issue by xalteropsx** [Tencent/ncnn#5772]
after getting the out0 

what we do next ? how can we get xyxy cause the output is not readable format

**Comment by Baiyuetribe** [comment]
see: https://github.com/search?q=yolo%20ncnn&type=repositories
Over 200 cases.

**Comment by Baiyuetribe** [comment]
> @Baiyuetribe sorry for tagging how can we pass int arugment on pnxx
> 
> pnnx resnet18.pt inputshape=[1,3,224,224],[i want here any float here like threshold]

eg:`./pnnx resnet18.pt inputshape=[1,3,224,224]f32,[1,32]i64`
see more: https://github.com/pnnx/pnnx
