### ISSUE TITLE
windows端在Qt Creator中引入ncnn库，运行时报"platform.h"中的mutex错误

### ISSUE THREAD

**Issue by zhahoi** [Tencent/ncnn#5777]
## detail | 详细描述 | 詳細な説明
在Qt Creator中引入ncnn库，在编译的时候出现如下错误，我有在网络中搜寻没找到解决答案，因此想提问有没有解决方法。
![微信截图_20241115090509](https://github.com/user-attachments/assets/41f7d016-3d1f-41e6-901d-16a8a3f541ce)
![微信截图_20241115090534](https://github.com/user-attachments/assets/0c0a25c2-6700-4b93-8aa9-49d2c8b843be)

我使用自己编译的ncnn库在visual studio2019可以正常使用，但是在QT中却不行。此外，我也下载了ReadMe中相应的编译好的版本，依旧报错，希望有谁可以帮我解答一下。感谢。

**Comment by wzyforgit** [comment]
老哥是必须用.pro组织工程嘛？现在Qt官方都在推荐用cmake了，我这边用cmake是可以正常用的
看这个报错感觉是头文件没找全，你搜一下这几个函数在哪里

**Comment by zhahoi** [comment]
感谢，我研究一下

**Comment by zhahoi** [comment]
> 老哥是必须用.pro组织工程嘛？现在Qt官方都在推荐用cmake了，我这边用cmake是可以正常用的 看这个报错感觉是头文件没找全，你搜一下这几个函数在哪里

我尝试使用CMakeList.txt来编译程序，但是会报libprotobuf错误，请问能帮我给出一个mingw64 cmake编译ncnn的范例参考吗？

# 标注最低版本
cmake_minimum_required(VERSION 3.8.2)

# 设置项目名称
project(yolov8Seg)

# 设置C++标准 C++11
set(CMAKE_CXX_STANDARD 11)

# Find includes in the build directories
set(CMAKE_INCLUDE_CURRENT_DIR ON)

# Turn on automatic invocation of the MOC, UIC & RCC
# 自动把UI转换为C++代码
set(CMAKE_AUTOMOC ON)
# 自动生成元对象的C++代码
set(CMAKE_AUTOUIC ON)
# 自动生成资源文件
set(CMAKE_AUTORCC ON)

# Add a compiler flag
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")

# Make this a GUI application on Windows
if(WIN32)
  set(CMAKE_WIN32_EXECUTABLE ON)
endif()

# 设置QT5_DIR
set(Qt5_DIR C:/Qt/Qt5.14.2/5.14.2/mingw73_64/lib/cmake/Qt5)
# Find the QtWidgets library
find_package(Qt5 REQUIRED COMPONENTS Widgets)

# 查找opencv
set(OpenCV_DIR "C:/NCNN/opencv-3.4.10/opencv/build/x64/vc15/lib")
find_package(OpenCV REQUIRED)

# 查找 NCNN
set(NCNN_DIR "C:/NCNN/ncnn-20240820-full-source/build/install/lib/cmake/ncnn")   
find_package(NCNN REQUIRED)

set(PROTOBUF_DIR "C:/NCNN/protobuf-3.4.0/build-vs2019/install/cmake")
find_package(Protobuf REQUIRED CONFIG PATHS ${PROTOBUF_DIR} NO_DEFAULT_PATH)

# # 查找 NCNN
# set(NCNN_DIR "C:/NCNN/ncnn-20240820-full-source/build/install")   
# set(PROTOBUF_DIR "C:/NCNN/protobuf-3.4.0/build-vs2019/install/")

# # 配置 NCNN 库和包含路径
# include_directories(${NCNN_DIR}/include/ncnn ${PROTOBUF_DIR}/include)
# link_directories(${NCNN_DIR}/lib ${PROTOBUF_DIR}/lib)

# Tell CMake to create the yolov8Seg executable
add_executable(yolov8Seg main.cpp yolov8seg.cpp yolov8seg.ui)

# Add the Qt5 Widgets for linking
target_link_libraries(yolov8Seg Qt5::Widgets ${OpenCV_LIBS} ncnn libprotobuf)

![Uploading 微信截图_20241118123702.png…]()

**Comment by zhahoi** [comment]
> 老哥是必须用.pro组织工程嘛？现在Qt官方都在推荐用cmake了，我这边用cmake是可以正常用的 看这个报错感觉是头文件没找全，你搜一下这几个函数在哪里

![微信截图_20241118123702](https://github.com/user-attachments/assets/93ed9f47-1a19-4ded-b565-797d1331a416)
报错说找不到libprotobuf，应该是我的问题，不知道大大有没有好的修改建议。

**Comment by wzyforgit** [comment]
cmake里面把构建模型转换工具的部分设置为OFF就不会要求protobuf了，mingw构建ncnn我倒是没实践过，你可以去扒一下doc目录下的how to build文档，不过我本人推荐你在windows下构建项目还是用VC++那坨工具更好

**Comment by zhahoi** [comment]
> cmake里面把构建模型转换工具的部分设置为OFF就不会要求protobuf了，mingw构建ncnn我倒是没实践过，你可以去扒一下doc目录下的how to build文档，不过我本人推荐你在windows下构建项目还是用VC++那坨工具更好

感谢大大的回复，我去尝试一下。

**Comment by zhahoi** [comment]
改成vc++哪个编译器可以用了
