### ISSUE TITLE
怎么查看运行日志

### ISSUE THREAD

**Issue by wyb222333** [Tencent/ncnn#5785]
Android上怎么查看so的日志呢

**Comment by wyb222333** [comment]
@nihui 大佬有遇到这种状况吗

**Comment by 9479421** [comment]
我和你一模一样 方便交流吗？ qq9479421

**Comment by wyb222333** [comment]
> hat.torchscript inputshape=[1,3,320,640] 采用onnx在各种手机上推理结果一致。但是ncnn推理，同一份代码同一张图片测试不同的手机推理。小米14识别跟onnx一致，一加手机只能识别个别类，或者直接识别错误。
> 
> ## more | 其他 | その他
