### ISSUE TITLE
float16 溢出问题

### ISSUE THREAD

**Issue by qingyang-jiandao** [Tencent/ncnn#5799]
只要模型里面有数值超过65519，就当作inf处理，造成最后推理结果错误，麻烦解决一下这个bug

**Comment by nihui** [comment]
可以禁用整个模型的fp16推理
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#disable-fp16

也可以针对容易溢出的层单独禁用fp16推理
https://github.com/Tencent/ncnn/wiki/layer-feat-mask#disable-fp16-for-certain-layer-to-fix-overflow

**Comment by qingyang-jiandao** [comment]
好的，谢谢了
