### ISSUE TITLE
cmake ..时找不到protobuf？？？

### ISSUE THREAD

**Issue by clhne** [Tencent/ncnn#581]
protobuf为3.0版本，报错如下：
![ncnn_error](https://user-images.githubusercontent.com/11884005/45791173-1a3e5900-bcbb-11e8-88c9-b407d4438de6.jpg)

**Comment by yvanwy** [comment]
使用protoc --version能查看版本吗

**Comment by oscarriddle** [comment]
@nihui 我下载预编译的protobuf后也遇到这个问题，请问如何解决
include目录下是google目录，然后是protobuf目录，没看到头文件

**Comment by xingjinglu** [comment]
同样问题，试过多个版本都不行，最后，安装了protobuf 2.6.1，编译成功。
