### ISSUE TITLE
请问有没有copy_cut_border和resize_bilinear 功能结合的函数？

### ISSUE THREAD

**Issue by ygyin-ivy** [Tencent/ncnn#582]
比如下面一段代码
ncnn::Mat tempIm;
ncnn::copy_cut_border(img, tempIm, top, bottom, left, right);
ncnn::Mat in;
ncnn::resize_bilinear(tempIm, in, w, h);

tempIm 分配了一次内存，in也分配了一次内存
有没有函数可以跳过tempIm 的内存分配，直接从img 到in？

**Comment by nihui** [comment]
目前并没有 ~

**Comment by soham24** [comment]
can this be a feature request ?
