### ISSUE TITLE
NCNN with vulkan  not using the GPU

### ISSUE THREAD

**Issue by zengjie617789** [Tencent/ncnn#5829]
## detail | 详细描述 | 詳細な説明
成功安装和编译了ncnn， 以及编译的时候带上了VULKAN；
vulkaninfo显示正常；
在运行../build/benchmark/benchncnn 时， 结果正常输出，但无GPU使用；
环境： GPU A100； docker ubuntu22.04

请问下如何解决。

**Comment by wzyforgit** [comment]
benchncnn要改传入的参数才能调起显卡的，详情看benchmark文件夹下的README文件其它人是怎么调用的
比如这样：./benchncnn 128 1 0 0 0
右边数第二个参数就是要使用的GPU的编号，如果你只有一张卡的话，这个编号一般是0

**Comment by zengjie617789** [comment]
是的， 谢谢，我严格按照readme的操作步骤，但是仍然不行。
![image](https://github.com/user-attachments/assets/773b7aa3-9f86-493b-a012-6ff8392de0c8)
