### ISSUE TITLE
请问extract可以执行一次提取多层特征吗？

### ISSUE THREAD

**Issue by LingQiu** [Tencent/ncnn#583]
请问每次执行extract是否进行一次前向计算？可否执行一次extract同时提取多层的输出？如果需要多层输出的话执行多次extract会不会影响耗时？

**Comment by rediceli** [comment]
Ref:
```
...
ncnn::Extractor ex = MyNet.create_extractor();
ex.set_light_mode(true);
ex.input("data", in);
ncnn::Mat prob1;
ncnn::Mat conv4;
ex.extract("prob1", prob1);
ex.extract("conv4", conv4);
...
```

**Comment by LingQiu** [comment]
@rediceli 多谢回复，目前已对该结果进行了验证，了解了其过程。

**Comment by ysc703** [comment]
@LingQiu 请问您的结论是？
请问每次执行extract是否进行一次前向计算？如果需要多层输出的话执行多次extract会不会影响耗时？

**Comment by LingQiu** [comment]
@ysc703 结论是提取多层特征只进行一次前向传播，我提取了三个全连接层的结果，只在第一次执行extract的时候有耗时输出。

**Comment by NEU-Gou** [comment]
@ysc703 准确的说是之前extract算过的layer不会重复计算，如果后续的extract涉及到没有计算过的layer，还是会消耗一些时间来计算的

**Comment by LingQiu** [comment]
@NEU-Gou  您的意思是如果只是提取中间某层的结果，前向计算就会执行到当前层？

**Comment by nihui** [comment]
> @NEU-Gou 您的意思是如果只是提取中间某层的结果，前向计算就会执行到当前层？

是的，只会计算需要算的部分

**Comment by nihui** [comment]
> @NEU-Gou @nihui 确实如此，多谢多谢+1
> 还得请教一下：同一个Extractor，输入图像大小不变，我想循环处理N张不同的图像，有没有简单的方法？多谢^_^
> 如下面的这种形式，第二次调extract会直接给出第一次extract的结果，而不会真正forward一次：
> ncnn::Extractor t_ex = T_Net.create_extractor();
> for (int i = 0; i < N; i++)
> {
> t_ex.extract(...);
> }


```
for (int i = 0; i < N; i++)
{
ncnn::Extractor t_ex = T_Net.create_extractor();
t_ex.extract(...);
}
```
