### ISSUE TITLE
light cnn C模型，有谁能用caffe2ncnn转成功的吗？

### ISSUE THREAD

**Issue by eeric** [Tencent/ncnn#59]
如题所述
C 模型转换后的大小是20M，明显的缩小了不少，.param是空的，有谁转换成功请介绍下方法，谢谢！

**Comment by zsffq999** [comment]
我转成功了，有什么问题？

**Comment by eeric** [comment]
@zsffq999，请问怎么转的，能说说具体步骤吗？先谢谢了

**Comment by VivienFu** [comment]
@eeric 我转成功并且博客记录了过程，你可以去看看
http://blog.csdn.net/fuwenyan/article/details/76147204

**Comment by eeric** [comment]
@VivienFu，呵呵，答非所问

**Comment by nihui** [comment]
#68  看这里
