### ISSUE TITLE
benchmark中的shufflenet咨询

### ISSUE THREAD

**Issue by grainw** [Tencent/ncnn#590]
想问一下用benchmark测的shufflenet 是30ms左右，自己caffe训练的shufflenet 转成ncnn后是300ms，想知道benchmark中shufflenet的网络结构，是什么？

**Comment by bailvwangzi** [comment]
@grainw 你caffe的shufflenet flops是多少？

**Comment by nihui** [comment]
shufflenet 1.0 g3
