### ISSUE TITLE
pytorch RNN not supported yet

### ISSUE THREAD

**Issue by xuzhiyuan1528** [Tencent/ncnn#592]
Convert model with the latest version of `ncnn` with `pytorch==0.4.1` on Mac:

pytorch -> onnx -> ncnn

A simple RNN model,

```
rnn = nn.RNN(1, 2, 2)
input = torch.randn(5, 3, 1)
h0 = torch.randn(2, 3, 2)
output, hn = rnn(input, h0)
torch.onnx.export(rnn, input, 'rnn.onnx')
```

use onnx2ncnn tool:

`./onnx2ncnn rnn.onnx`

Errors:

```
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
ConstantFill not supported yet!
  # input_as_shape=1
RNN not supported yet!
  # activations 8
  # hidden_size=2
Squeeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
ConstantFill not supported yet!
  # input_as_shape=1
RNN not supported yet!
  # activations 8
  # hidden_size=2
Squeeze not supported yet!
  # axes 7
```

Anybody has tried to convert the pytorch RNN model before?

**Comment by SanjunLiu** [comment]
pytorch mobilenetv1-ssd: pytorch -> onnx -> ncnn
Unsqueeze not supported yet!                                                                        [110/1610]
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
