### ISSUE TITLE
cannot build shared library in ncnn default cmake envs.

### ISSUE THREAD

**Issue by kalcohol** [Tencent/ncnn#599]
"target platform does not support dynamic linking” was shown when cross-build ncnn on linux for arm.
it seems like same issue on stackoverflow: 
https://stackoverflow.com/questions/12264299/cmake-on-linux-target-platform-does-not-support-dynamic-linking/12266163

i add a line before order cmake build shared library, such as:
SET_PROPERTY(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS TRUE)

it was not a good solution, but just work well for now. please check and fix this issue when some one have time.
(i'm not good at cmake)

**Comment by nihui** [comment]
the ncnn ABI is not stable enough to be built as shared library.
so we provide static building only.

**Comment by MagnusBai** [comment]
> the ncnn ABI is not stable enough to be built as shared library.
> so we provide static building only.

unofficial old news of new year of 2021:

!()[https://i.imgur.com/AeqFnaM.png]

ncnn shared library is supported!
