### ISSUE TITLE
希望添加group convolution和depth-wise convolution

### ISSUE THREAD

**Issue by SunEve** [Tencent/ncnn#6]
RT，计算量很小的mobilenet和shufflenet都需要group convolution/depth-wise convolution操作，看api似乎对于group conv不支持，希望添加相应的支持并做优化。

**Comment by nihui** [comment]
TODO

**Comment by ccJia** [comment]
@nihui 你好，请问有什么好的区别于CAFFE的实现depthwise 的思路吗？？？

**Comment by tanguofu** [comment]
+1

**Comment by nihui** [comment]
添加 group convolution，还没优化，至少能跑了  qwq
https://github.com/Tencent/ncnn/commit/9f51c2132267edcdeefd0b1a4e67424b7b2b8096

**Comment by zl1994** [comment]
请问如果不支持depth-wise convolution layer，模型还能转化吗？

**Comment by nihui** [comment]
optimized path implemented for depth-wise convolution
