### ISSUE TITLE
example，是一个Android demo吗？

### ISSUE THREAD

**Issue by blackcat-tech** [Tencent/ncnn#60]
eclipse导入example/squeezencnn,不能正常运行吗？

Caused by: java.lang.UnsatisfiedLinkError: Couldn't load squeezencnn: findLibrary returned null

**Comment by eeric** [comment]
请看https://github.com/Tencent/ncnn/issues/38，eeric的回复

**Comment by eeric** [comment]
要使ncnn的样例squeeze在手机上正常运行，需解决了以下问题：
 （1）在linux环境下配置环境，编译生成了库文件libncnn.a；
 （2）在linux环境下编译jni生成了.so库文件；
 （3）调整了模型转换文件assets在安卓工程中的位置；

**Comment by blackcat-tech** [comment]
.so文件的生成，没搞过~ 好复杂的样纸。有生成的小伙们，可以共享一下吗

**Comment by lzx1413** [comment]
#11 直接用as打开，然后修改Android.mk中的ncnn安装路径就好了

**Comment by blackcat-tech** [comment]
@lzx1413  Caused by: java.lang.UnsatisfiedLinkError: Couldn't load squeezencnn: findLibrary returned null  错误与开发工具没关系的。example项目中，是没有.so文件的。。。

**Comment by dangbo** [comment]
@blackcat-tech https://github.com/dangbo/squeezencnn-AS 使用 Android Studio 直接运行

**Comment by lzx1413** [comment]
@blackcat-tech  这个.so是ndk编译的，用as直接编译就行

**Comment by blackcat-tech** [comment]
@dangbo 你的项目是已经编译好的.so，可以正常运行。O(∩_∩)O
