### ISSUE TITLE
vs2015 compling error

### ISSUE THREAD

**Issue by andyhx** [Tencent/ncnn#601]
hi,I am trying to complie the new version of nccn , I used the vs2015 and the vs2015 x64 native tools ,I followed the commands in wiki for vs2017 , the protobuff was builded successfully ,but when compling the nccn part , I met some errors ,the errors are the followings ；
`
[ 10%] Building CXX object src/CMakeFiles/ncnn.dir/net.cpp.obj
net.cpp
d:\ubuntu\project\ncnn_ms\ncnn\src\mat.h(287): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
d:\ubuntu\project\ncnn_ms\ncnn\src\mat.h(341): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(235): error C2059: syntax error: '{'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(235): error C2143: syntax error: missing ';' before '{'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(235): error C2059: syntax error: ')'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(245): error C2059: syntax error: '{'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(245): error C2143: syntax error: missing ';' before '{'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(245): error C2059: syntax error: ')'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(264): error C2059: syntax error: '{'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(264): error C2143: syntax error: missing ';' before '{'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(542): warning C4311: 'type cast': pointer truncation from 'const unsigned char *' to 'unsigned long'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(542): warning C4302: 'type cast': truncation from 'const unsigned char *' to 'unsigned long'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(649): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(660): warning C4311: 'type cast': pointer truncation from 'const unsigned char *' to 'unsigned long'
D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(754): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data
........................................................................................
NMAKE : fatal error U1077: 'C:\PROGRA2\MICROS1.0\VC\bin\amd64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
`
what's the problem?  thanks in advance！

**Comment by LeoaY** [comment]
同样的问题，在最新的版本。 以前的版本没有

F:\ncnn_m\ncnn\src\net.cpp(235) : error C2059: 语法错误:“{”
F:\ncnn_m\ncnn\src\net.cpp(235) : error C2143: 语法错误 : 缺少“;”(在“{”的前面)
F:\ncnn_m\ncnn\src\net.cpp(235) : error C2143: 语法错误 : 缺少“;”(在“)”的前面)
F:\ncnn_m\ncnn\src\net.cpp(245) : error C2059: 语法错误:“{”
F:\ncnn_m\ncnn\src\net.cpp(245) : error C2143: 语法错误 : 缺少“;”(在“{”的前面)
F:\ncnn_m\ncnn\src\net.cpp(245) : error C2143: 语法错误 : 缺少“;”(在“)”的前面)
F:\ncnn_m\ncnn\src\net.cpp(264) : error C2059: 语法错误:“{”
F:\ncnn_m\ncnn\src\net.cpp(264) : error C2143: 语法错误 : 缺少“;”(在“{”的前面)
F:\ncnn_m\ncnn\src\net.cpp(264) : error C2143: 语法错误 : 缺少“;”(在“)”的前面)
F:\ncnn_m\ncnn\src\net.cpp(291) : error C2059: 语法错误:“{”
F:\ncnn_m\ncnn\src\net.cpp(291) : error C2143: 语法错误 : 缺少“;”(在“{”的前面)
F:\ncnn_m\ncnn\src\net.cpp(291) : error C2143: 语法错误 : 缺少“;”(在“)”的前面)
F:\ncnn_m\ncnn\src\net.cpp(323) : error C2059: 语法错误:“{”
F:\ncnn_m\ncnn\src\net.cpp(323) : error C2143: 语法错误 : 缺少“;”(在“{”的前面)
F:\ncnn_m\ncnn\src\net.cpp(323) : error C2143: 语法错误 : 缺少“;”(在“)”的前面)

**Comment by LeoaY** [comment]
> hi,I am trying to complie the new version of nccn , I used the vs2015 and the vs2015 x64 native tools ,I followed the commands in wiki for vs2017 , the protobuff was builded successfully ,but when compling the nccn part , I met some errors ,the errors are the followings ；
> `[ 10%] Building CXX object src/CMakeFiles/ncnn.dir/net.cpp.obj net.cpp d:\ubuntu\project\ncnn_ms\ncnn\src\mat.h(287): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data d:\ubuntu\project\ncnn_ms\ncnn\src\mat.h(341): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(235): error C2059: syntax error: '{' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(235): error C2143: syntax error: missing ';' before '{' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(235): error C2059: syntax error: ')' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(245): error C2059: syntax error: '{' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(245): error C2143: syntax error: missing ';' before '{' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(245): error C2059: syntax error: ')' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(264): error C2059: syntax error: '{' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(264): error C2143: syntax error: missing ';' before '{' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(542): warning C4311: 'type cast': pointer truncation from 'const unsigned char *' to 'unsigned long' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(542): warning C4302: 'type cast': truncation from 'const unsigned char *' to 'unsigned long' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(649): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(660): warning C4311: 'type cast': pointer truncation from 'const unsigned char *' to 'unsigned long' D:\ubuntu\Project\ncnn_ms\ncnn\src\net.cpp(754): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data ........................................................................................ NMAKE : fatal error U1077: 'C:\PROGRA2\MICROS1.0\VC\bin\amd64\cl.exe' : return code '0x2' Stop. NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2' Stop. NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2' Stop.`
> what's the problem? thanks in advance！

I just build 20180704 code  here https://github.com/Tencent/ncnn/releases,  you can try it!

**Comment by andyhx** [comment]
@LeoaY  ，oldder version 20180427 that u referred works ，thanks so much！

**Comment by sirius-ai** [comment]
I annotation the line which use mem_sscanf，and unfold mem_sscanf such as below：

// nscan = mem_sscanf(mem, "%256s %256s %d %d", layer_type, layer_name, &bottom_count, &top_count);

{
    int _b=0;
    int _n = sscanf(mem, "%256s %256s %d %d" "%n", layer_type, layer_name, &bottom_count, &top_count, &_b);
    mem+=_b;
    nscan = _b>0?_n:0;
}

This fix the problems in my case.

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/4e68a29effbdf72c54f500274c22cf3036124331
try the latest code

**Comment by andyhx** [comment]
thanks！
