### ISSUE TITLE
7*7池化的一个问题？

### ISSUE THREAD

**Issue by BBuf** [Tencent/ncnn#604]
为什么我把网络的最后一个全连接层(前一层的大小为7*7*512)换成7*7平均池化并接，训练得到的结果在caffe预测没问题，在NCNN进行预测却得到错误的结果？并且尝试了4*4的平均池化发现结果正确。阅读了polling.cpp没有看出玄机，望解答，谢谢。

**Comment by BBuf** [comment]
7乘以7乘以512，然后是4乘4

**Comment by nihui** [comment]
7*7 应该是可以的，你看看是否有padding或者什么别的参数
另外，也可以使用 global pooling 参数替代
