### ISSUE TITLE
ncnn output on converted from tensorflow pb wrong result

### ISSUE THREAD

**Issue by dimitryn** [Tencent/ncnn#611]
Hi , 
I am testing several IE for the performance.
My tensorflow pb file contain 2 types of layers DepthWiseConv2D and Conv2D.
Tensorflow Lite , Mace XiaoMi , Arm nn sdk produce exactly same output.
Ncnn output completely different from all others.
Is look's like channels separated on output os need some kind of post-processing or pre-processing?
Thanks.

Uploaded source pb file and converted ncnn files
[IE_DATA.zip](https://github.com/Tencent/ncnn/files/2481834/IE_DATA.zip)

**Comment by dimitryn** [comment]
Hi @nihui , so it bug ? what that mean tensorflow do not like ncnn ?

**Comment by nihui** [comment]
duplicate of https://github.com/Tencent/ncnn/issues/5

**Comment by tejas35** [comment]
How would you convert from .pb to ncnn files ?

**Comment by dimitryn** [comment]
@tejas35 as I see tensorflow not supported any more
