### ISSUE TITLE
ex.extract("prob",out) error: thread 1:EXC_BAD_ACCESS(code=1,address=0x0)

### ISSUE THREAD

**Issue by fangzhiming** [Tencent/ncnn#613]
problem is shown as the title.
I load my param and bin files and return 0. it seems loading model successfully.
how to solve it!help!thanks!

**Comment by fangzhiming** [comment]
I found that something wrong when ex.extract the fc8 layer, update the 20180830 framework of ios.

**Comment by fangzhiming** [comment]
still crash the same problem after update the new ios framework(update 20180830).should I build the ios framework by myself?

**Comment by fangzhiming** [comment]
something wrong operation to my input data, ex.extract function is right!

**Comment by julianakent** [comment]
I have the same problem and input data is all zeros,  any suggestions?
