### ISSUE TITLE
OpenCL 1.2 support

### ISSUE THREAD

**Issue by xiaofengren** [Tencent/ncnn#615]
May I know whether NCNN opencl branch can support OpenCL 1.2? On my arm platform, it only find OpenCL 1.2 (Found OpenCL: /usr/lib/libOpenCL.so (found version "1.2") ). 

When I build ncnn with OpenCL, it will report a lot of library unmatched error, like as followings:

../src/libncnn.a(modelbin.cpp.o): In function ncnn::ModelBin::load(int, int, int, int) const': modelbin.cpp:(.text+0x1354): undefined reference to clReleaseMemObject'
modelbin.cpp:(.text+0x15dc): undefined reference to clReleaseMemObject' modelbin.cpp:(.text+0x172c): undefined reference to clReleaseMemObject'
modelbin.cpp:(.text+0x1748): undefined reference to clReleaseMemObject' modelbin.cpp:(.text+0x17c0): undefined reference to clCreateBuffer'
modelbin.cpp:(.text+0x1858): undefined reference to clReleaseMemObject' modelbin.cpp:(.text+0x18c8): undefined reference to clCreateBuffer'
../src/libncnn.a(paramdict.cpp.o): In function ncnn::ParamDict::set(int, ncnn::Mat const&)': paramdict.cpp:(.text+0x248): undefined reference to clReleaseMemObject'
../src/libncnn.a(paramdict.cpp.o): In function ncnn::ParamDict::clear()': paramdict.cpp:(.text+0x388): undefined reference to clReleaseMemObject'
paramdict.cpp:(.text+0x3ac): undefined reference to clReleaseMemObject' ../src/libncnn.a(paramdict.cpp.o): In function ncnn::ParamDict::load_param(_IO_FILE*)':
paramdict.cpp:(.text+0x778): undefined reference to clReleaseMemObject' paramdict.cpp:(.text+0x7e4): undefined reference to clCreateBuffer'
../src/libncnn.a(paramdict.cpp.o): In function ncnn::ParamDict::load_param_bin(_IO_FILE*)': paramdict.cpp:(.text+0xa98): undefined reference to clCreateBuffer'
paramdict.cpp:(.text+0xad4): undefined reference to clReleaseMemObject' ../src/libncnn.a(paramdict.cpp.o): In function ncnn::ParamDict::load_param(unsigned char const*&)':
paramdict.cpp:(.text+0xcb0): undefined reference to clCreateBuffer' paramdict.cpp:(.text+0xd04): undefined reference to clReleaseMemObject'

The GPU what I used is not Mali GPU, so can it be supported?

**Comment by xiaofengren** [comment]
After modify CMakeCache.txt file to implicitly add OpenCL library, it can build successfully. 

//Flags used by the linker during all build types.
CMAKE_EXE_LINKER_FLAGS:STRING= -lOpenCL

//Flags used by the linker during DEBUG builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING= -lOpenCL

//Flags used by the linker during MINSIZEREL builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during RELEASE builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING= -lOpenCL

//Flags used by the linker during RELWITHDEBINFO builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING= -lOpenCL

**Comment by nihui** [comment]
the opencl branch is deprecated, do not use it
for gpu inference, vulkan will be picked for future adoption

**Comment by xiaofengren** [comment]
Thank you so much for your clarification. Look forward vulkan support.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/6876
