### ISSUE TITLE
感觉很需要ncnn::Mat 的resize函数

### ISSUE THREAD

**Issue by ElegantGod** [Tencent/ncnn#62]
缺少ncnn::Mat resize()函数，发现很不方便，每次使用copy_cut_border()取roi后，还要转pixel形式后再做resize和substract_mean_normalize
不知道是不是我用的不对

**Comment by nihui** [comment]
在原图上取 roi，然后 Mat::from_pixels_resize

**Comment by ElegantGod** [comment]
我觉得这样会导致重复的做substract_mean_normalize(mean_vals, norm_vals)，比如做图像金字塔；还有个问题，float和uint8分别作resize，时间大概是几倍的关系呢

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/613028aa173bc113616fc0e2a9dbc6164c70fd29
后续会优化下，然后做个 resize layer
