### ISSUE TITLE
Error on aarch64 linux: more than 30 operands in 'asm'

### ISSUE THREAD

**Issue by teamAltumview** [Tencent/ncnn#626]
The following errors are due to the gcc compiler limit on inline assembly code. I am using gcc 6.3.0. I'm at commit e38c5a69a6b8d2db26b98a09fd1f5c07cc22de79. Please take a look. Thanks.

convolution_1x1_int8.h:849:14: error: more than 30 operands in 'asm'
convolution_1x1_int8.h:1413:14: error: more than 30 operands in 'asm'
convolution_1x1_int8.h:1966:14: error: more than 30 operands in 'asm'

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/971fe2f639255d04762ee26cb395e3ef64426cf0
