### ISSUE TITLE
after use mxnet2ncnn tool，run the forward progress，it throw the error like：find_blob_index_by_name prob failed Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by boyang24** [Tencent/ncnn#627]
@nihui hi，thanks the project you applied，now i have few question to ask，thanks
1.now i already switch the training parameter by mxnet2ncnn，then i program my mxnet.cpp,to run the age and gender recognize,the code is like : 
![image](https://user-images.githubusercontent.com/41313271/47598966-ed2a4800-d9d6-11e8-8691-0c56154d5483.png)
but it has the error:find_blob_index_by_name prob failed
Segmentation fault (core dumped)
the former parameter i used in mxnet to run is ok,big thanks for your help,waiting for your answer

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error

the most probably reason is that your model symbol has invalid node like duplicated names.
