### ISSUE TITLE
ncnn example compile

### ISSUE THREAD

**Issue by jmu201521121021** [Tencent/ncnn#63]
当编译ncnn/example时,出现一下错误,请问怎么解决?
[ 50%] Building CXX object CMakeFiles/squeezenet.dir/squeezenet.cpp.o
[100%] Linking CXX executable squeezenet
/usr/bin/ld: 找不到 -lncnn
collect2: error: ld returned 1 exit status
CMakeFiles/squeezenet.dir/build.make:101: recipe for target 'squeezenet' failed
make[2]: *** [squeezenet] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/squeezenet.dir/all' failed
make[1]: *** [CMakeFiles/squeezenet.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jjyycchh** [comment]
你的ncnn的src源码需要编译，
cmake完了你make install一下装到系统下
系统里面用ldconfig确认一下才能link这个ncnn的库。

**Comment by nihui** [comment]
顶层的 CMakeLists.txt 取消注释 add_subdirectory(examples)，然后用顶层的编译
