### ISSUE TITLE
3D卷积

### ISSUE THREAD

**Issue by nicehuster** [Tencent/ncnn#637]
ncnn什么时候能支持3D卷积相关的操作呀

**Comment by nihui** [comment]
3D卷积是哪里用到了.... 视频？

**Comment by emojilearning** [comment]
> 3D卷积是哪里用到了.... 视频？

视频分析（动作识别，检测）
三维视觉（点云分类，检测）
个人感觉后面应该会用的越来越多吧。

**Comment by muzi2045** [comment]
我寻思着pointpillars也没用到3D卷积啊

**Comment by emojilearning** [comment]
> 我寻思着pointpillars也没用到3D卷积啊

您要是读过那篇论文的话就应该知道它也提到了3d卷积在其它点云识别和检测工作中的使用。
更不要说动作识别里面3d卷积应用有多广泛。

**Comment by czqhubu** [comment]
3D卷积目前在行为检测方面还是用的较多的

**Comment by nihui** [comment]
3d卷积已实现，尚待优化

**Comment by superbayes** [comment]
> 3D 用途是哪里用到了.... 视频？

pointpollar,3D目标检测

![image](https://github.com/user-attachments/assets/fbf7cca2-3adc-4128-b4d7-cf248df4927e)
