### ISSUE TITLE
MacOS上build iOS遇到“is not able to compile a simple test program”

### ISSUE THREAD

**Issue by wangwenjing** [Tencent/ncnn#639]
![image](https://user-images.githubusercontent.com/6176821/47901238-566bf880-deba-11e8-8fe0-edb15cabe1e7.png)
MacOS上build iOS，按照github wiki流程，遇到如上问题，

**Comment by huangturen** [comment]
ncnn的编译流程简直就是渣渣啊

**Comment by nihui** [comment]
因为 ios 编译环境配置比较麻烦，需要 linux + cctools-port，推荐使用编译好的 framework
https://github.com/Tencent/ncnn/releases
