### ISSUE TITLE
ncnn Batch Norm实现与Caffe不一样？

### ISSUE THREAD

**Issue by wasd96040501** [Tencent/ncnn#64]
请问，ncnn的Batch Norm和Caffe的Batch Norm实现不一样吧？
经过测试对比，我们的网络通过ncnn的Batch Norm之后与Caffe的相比误差很大（差不多有e-1），最终我们的效果也不太好。
请问，针对Batch Norm有后续的更新计划吗？

**Comment by nihui** [comment]
用转换器转换batchnorm，应该是一样的才对

**Comment by wasd96040501** [comment]
@nihui 问题已经查明了，并不是batch norm的问题。而是convolution层的dilation有一点小错误。
`
int gap = w * dilation - kernel_extent;
`
这里有个小错误，应该改为
`
int gap = w * dilation - dilation * (kernel_size);
`
已经在3x3卷积dilation为4，16等测试过了，修改之后结果就正确了。
