### ISSUE TITLE
关于ncnn支持onnx问题

### ISSUE THREAD

**Issue by JSnobody** [Tencent/ncnn#643]
Hi，我发现ncnn并不能完全支持onnx，比如mnist lenet就不能完全支持，有的算子还没有实现。
这块内容，ncnn后续会更新吧？

**Comment by nihui** [comment]
由于onnx的opset升级造成的
https://github.com/Tencent/ncnn/commit/4c5d9ae425f0b47e88ddadfda5d7464fa94d5309 做了更新
