### ISSUE TITLE
Is your inference time stable?

### ISSUE THREAD

**Issue by zym1119** [Tencent/ncnn#644]
I tested on several networks include mobilenet, mobilenetv2, resnet18 etc.
I found the inference time is quite unstable even for the same image, sometimes can range from 120+ms to 80ms, is that normal?
Or something wrong happened?

the time is calculated in MainActivity.java as:
long start = System.currentTimeMillis();
float[] result = ncnn.Detect(input_bmp);
long end = System.currentTimeMillis();

**Comment by nihui** [comment]
try to warmup 10 times, and then benchmark

**Comment by lvpchen** [comment]
我在pc上测的时间比较稳定，在手机上测试的时间也波动很大，很不稳定。求解答 @zym1119 @nihui

**Comment by nihui** [comment]
see https://github.com/Tencent/ncnn/issues/668
