### ISSUE TITLE
ncnn是否可以支持relu6层？

### ISSUE THREAD

**Issue by yulong112** [Tencent/ncnn#647]
想用mobilenetv2-ssdlite，但是其中有relu6层，请问可以不可以在ncnn中支持该层？
I wanna use mobilenetv2-ssdlite, but a new layer called "relu6" is conluded. Can ncnn
support this layer?

**Comment by NEU-Gou** [comment]
If you use caffe2ncnn, relu6 layer will be transferred to clip layer

**Comment by yulong112** [comment]
> If you use caffe2ncnn, relu6 layer will be transferred to clip layer
@NEU-Gou  Thanks!  Does the transformation from relu6 layer to clip layer have any influence on accuracy?

**Comment by NEU-Gou** [comment]
It should not. Clip to [0,6] works exactly the same as relu6.

**Comment by nihui** [comment]
yes, we convert relu6 to clip(0,6), should work out of box
