### ISSUE TITLE
mobilenet-YOLOv3在VS2015上已经运行成功了 但在ARM上跑的时候报错

### ISSUE THREAD

**Issue by YiDing2333** [Tencent/ncnn#649]
同样的代码已经在VS2015上调通了，但在ARM A53 ubuntu系统上运行的时候报错
find_blob_index_by_name data failed
find_blob_index_by_name detection_out failed

**Comment by eric612** [comment]
看起來像是prototxt 轉換的問題，我目前沒有arm平台測試，你可以先試試這個
https://github.com/eric612/caffe-int8-convert-tools/tree/master/test/models

轉換後的名稱記得改為 yolo.param yolo.bin

**Comment by YiDing2333** [comment]
@eric612 已经解决了 因为之前编译的ncnn没有删掉 cmakelist写的也有点问题 就链接到了原来编译的libncnn.a上了

**Comment by dlml** [comment]
![default](https://user-images.githubusercontent.com/35597616/49198555-9c8b7d80-f3ce-11e8-9975-79c441031042.png)
@YiDing2333  你用vs的时候遇到这些error吗？

**Comment by YiDing2333** [comment]
@dlml 没遇到 我估计是ncnn框架没编译好 或者是工程环境配置有问题 你可以参考这个demo https://github.com/guozhongluo/ncnn-vs2015-examples-demo
