### ISSUE TITLE
用mxnet2ncnn工具转换模型时，出现某些层不支持的错误

### ISSUE THREAD

**Issue by MayLuo123** [Tencent/ncnn#652]
1 在将mxnet框架训练的模型转换成ncnn框架支持的模型时，出现某些层不支持，如_copy not supported yet,但成功生成.param和.bin,请问出现这个错误后，模型还可以正常使用吗？
2 尝试加载.param和.bin成功，但在进行如下前向预测时：
ex.input("data",in);
ex.extract("fc1",out)
出现如下错误:
find_blob_index_by_name  data  failed
find_blob_index_by_name  fc1  failed

请问遇到以上问题该如何解决？

**Comment by junqiangwu** [comment]
你需要自己实现  ncnn不支持的op运算，参考这里   https://github.com/Tencent/ncnn/wiki/how-to-implement-custom-layer-step-by-step

**Comment by MayLuo123** [comment]
已解决，多谢
