### ISSUE TITLE
Yolov3比mobilenet_ssd运行速度要慢

### ISSUE THREAD

**Issue by jackyfriend** [Tencent/ncnn#654]
您好，我在PC上运行yolov3和mobilenetssd这两个测试程序，发现yolov3比mobilenetssd要慢2-3倍左右，请问这是正常的吗？论文那里说yolov3要比ssd快的
我的PC配置是Ubuntu 16.04 LTS
CPU: i7-6700 3.40GHz x 8
GPU: GeForce GTX 960
yolov3跑0.15s 左右，mobilenetssd可以跑到0.07s.

还有，想请问下在rk3288这样的平台上做目标检测的话，选用yolo好还是ssd好呢？
烦请多多指教！谢谢大神！

**Comment by nihui** [comment]
backbone 网络不一样？
真要比的话用mobilenet-yolov3，标准yolov3肯定比mobilenetssd慢

**Comment by zyc4me** [comment]
为什么现在看来 mobilenet-yolo3 还是比mobilenet ssd 慢很多？

**Comment by Oldpan** [comment]
同样的疑问呀？benchmark中 yolov3-mobile确实比mobile-ssd慢

**Comment by nihui** [comment]
输入的图片尺寸不一样，ssd是300x300，yolo是416x416
