### ISSUE TITLE
the name should be remain

### ISSUE THREAD

**Issue by 00liujj** [Tencent/ncnn#655]
https://github.com/Tencent/ncnn/blob/201ebb8e447175ed6ea5f359f930dd1dc2ec0e11/src/layer/arm/clip_arm.cpp#L41

**Comment by nihui** [comment]
hi  could you please send a pull request for this trival fix ?

**Comment by 00liujj** [comment]
PR submitted.

**Comment by nihui** [comment]
PR merged, thank you !
