### ISSUE TITLE
question about bit littlle core optiomization

### ISSUE THREAD

**Issue by han-qiu** [Tencent/ncnn#658]
In the readme file, you mentioned multi-core parallel and ARM big.LITTLE cpu sheduling optimization.
It seems that the multi-core parallelism is implemented by OPENMP, but what about the bit.LITTLE cpu sheduling? Can you please kindly explain how it's implemented? Thank you in advance.

**Comment by nihui** [comment]
we set openmp thread affinity to the specified big or LITTLE cores
you may find implementation details in src/cpu.cpp
