### ISSUE TITLE
请问caffe中的xxx_mean.npy 该怎么处理？

### ISSUE THREAD

**Issue by huanyingjun** [Tencent/ncnn#66]
在例子中看到，
const float mean_vals[3] = {104.f, 117.f, 123.f};
in.substract_mean_normalize(mean_vals, 0);
对于caffe中的xxx_mean.npy 该怎么处理？
将数据读出来，放到一段float  的buffer中，然后调 substract_mean_normalize ？

**Comment by nihui** [comment]
mean blob 方式的 substract_mean_normalize 没有支持，需要自己实现减均值...
因为手机上对模型大小也挺苛刻的，通常建议用 mean value 代替 mean blob
