### ISSUE TITLE
目前的ncnn模型验证部分该如何做呢？

### ISSUE THREAD

**Issue by liaocz** [Tencent/ncnn#660]

**Comment by liaocz** [comment]
是否可以编译成x86平台的代码进行模型验证？

**Comment by liaocz** [comment]
caffe2ncnn后如何验证模型的正确性？

**Comment by nihui** [comment]
pc 上，extract blob 后自己打印出来，然后再把 caffe 对应的 blob 打印出来比较

**Comment by liaocz** [comment]
for(size_t i = 0; i < out.cstep; i++)
    std::cout << out[i] << std::endl;
这样输出最后的结果吗？

**Comment by liaocz** [comment]
for(size_t i = 0; i < out.cstep; i++)
    std::cout << out[i] << std::endl;
这样输出最后的结果吗？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki#print-mat-content
