### ISSUE TITLE
设置多线程没任何效果

### ISSUE THREAD

**Issue by zhangkom** [Tencent/ncnn#661]
在init的时候设置了2个线程，但是测试发现opt.num_threads这个值设置任何值都没有作用。

    ncnn::Option opt;
    opt.lightmode = true;
    opt.num_threads = 2;
    opt.blob_allocator = &g_blob_pool_allocator;
    opt.workspace_allocator = &g_workspace_pool_allocator;

    ncnn::set_default_option(opt);
    ncnn::set_omp_dynamic(0);
    ncnn::set_omp_num_threads(opt.num_threads);

**Comment by nihui** [comment]
你是不是 extractor 那里设置了 num threads ...

**Comment by zhangkom** [comment]
在load param的时候，你看下整个代码，设置的地方在Java_com_tencent_squeezencnn_SqueezeNcnn_Init里面。

#include <android/bitmap.h>
#include <android/log.h>

#include <jni.h>

#include <string>
#include <vector>

// ncnn
#include "net.h"
#include "cpu.h"
#include "squeezenet_v1.1.id.h"

#include <sys/time.h>
#include <unistd.h>

static struct timeval tv_begin;
static struct timeval tv_end;
static double elasped;
static double total_time = 0;
static int total_num = 0;
static void bench_start()
{
    gettimeofday(&tv_begin, NULL);
}

static void bench_end(const char* comment)
{
    gettimeofday(&tv_end, NULL);
    elasped = ((tv_end.tv_sec - tv_begin.tv_sec) * 1000000.0f + tv_end.tv_usec - tv_begin.tv_usec) / 1000.0f;
//     fprintf(stderr, "%.2fms   %s\n", elasped, comment);
    total_time += elasped;
    total_num ++;
    double avg = total_time/total_num;
    __android_log_print(ANDROID_LOG_DEBUG, "SqueezeNcnn", "%.2fms   %s,%.2fms,%d,%.2fms", elasped, comment, total_time, total_num, avg);
}

static ncnn::UnlockedPoolAllocator g_blob_pool_allocator;
static ncnn::PoolAllocator g_workspace_pool_allocator;

static ncnn::Mat squeezenet_param;
static ncnn::Mat squeezenet_bin;
static std::vector<std::string> squeezenet_words;
static ncnn::Net squeezenet;

static std::vector<std::string> split_string(const std::string& str, const std::string& delimiter)
{
    std::vector<std::string> strings;

    std::string::size_type pos = 0;
    std::string::size_type prev = 0;
    while ((pos = str.find(delimiter, prev)) != std::string::npos)
    {
        strings.push_back(str.substr(prev, pos - prev));
        prev = pos + 1;
    }

    // To get the last substring (or only, if delimiter is not found)
    strings.push_back(str.substr(prev));

    return strings;
}

extern "C" {

// public native boolean Init(byte[] param, byte[] bin, byte[] words);
JNIEXPORT jboolean JNICALL Java_com_tencent_squeezencnn_SqueezeNcnn_Init(JNIEnv* env, jobject thiz, jbyteArray param, jbyteArray bin, jbyteArray words)
{
    // init param
    {
        int len = env->GetArrayLength(param);
        squeezenet_param.create(len, (size_t)1u);
        env->GetByteArrayRegion(param, 0, len, (jbyte*)squeezenet_param);
        int ret = squeezenet.load_param((const unsigned char*)squeezenet_param);
        __android_log_print(ANDROID_LOG_DEBUG, "SqueezeNcnn", "load_param %d %d", ret, len);
    }

    // init bin
    {
        int len = env->GetArrayLength(bin);
        squeezenet_bin.create(len, (size_t)1u);
        env->GetByteArrayRegion(bin, 0, len, (jbyte*)squeezenet_bin);
        int ret = squeezenet.load_model((const unsigned char*)squeezenet_bin);
        __android_log_print(ANDROID_LOG_DEBUG, "SqueezeNcnn", "load_model %d %d", ret, len);
    }

    // init words
    {
        int len = env->GetArrayLength(words);
        std::string words_buffer;
        words_buffer.resize(len);
        env->GetByteArrayRegion(words, 0, len, (jbyte*)words_buffer.data());
        squeezenet_words = split_string(words_buffer, "\n");
    }

    ncnn::Option opt;
    opt.lightmode = true;
    opt.num_threads = 2;
    opt.blob_allocator = &g_blob_pool_allocator;
    opt.workspace_allocator = &g_workspace_pool_allocator;

    ncnn::set_default_option(opt);

    //ncnn::set_cpu_powersave(powersave);

    ncnn::set_omp_dynamic(0);
    ncnn::set_omp_num_threads(opt.num_threads);

    //fprintf(stderr, "loop_count = %d\n", g_loop_count);
    fprintf(stderr, "num_threads = %d\n", opt.num_threads);
    fprintf(stderr, "powersave = %d\n", ncnn::get_cpu_powersave());

    return JNI_TRUE;
}

// public native String Detect(Bitmap bitmap);
JNIEXPORT jstring JNICALL Java_com_tencent_squeezencnn_SqueezeNcnn_Detect(JNIEnv* env, jobject thiz, jobject bitmap)
{
    ncnn::Mat in;
    {
        AndroidBitmapInfo info;
        AndroidBitmap_getInfo(env, bitmap, &info);
        int width = info.width;
        int height = info.height;
        if (width != 227 || height != 227)
            return NULL;
        if (info.format != ANDROID_BITMAP_FORMAT_RGBA_8888)
            return NULL;

        void* indata;
        AndroidBitmap_lockPixels(env, bitmap, &indata);

        in = ncnn::Mat::from_pixels((const unsigned char*)indata, ncnn::Mat::PIXEL_RGBA2BGR, width, height);

        AndroidBitmap_unlockPixels(env, bitmap);
    }

    // squeezenet
    std::vector<float> cls_scores;
    {
        const float mean_vals[3] = {104.f, 117.f, 123.f};
        in.substract_mean_normalize(mean_vals, 0);

        ncnn::Extractor ex = squeezenet.create_extractor();

        ex.input(squeezenet_v1_1_param_id::BLOB_data, in);
        ncnn::Mat out;


        ex.extract(squeezenet_v1_1_param_id::BLOB_prob, out);
        cls_scores.resize(out.w);
        for (int j=0; j<out.w; j++)
        {
            cls_scores[j] = out[j];
        }
    }

    // return top class
    int top_class = 0;
    float max_score = 0.f;
    for (size_t i=0; i<cls_scores.size(); i++)
    {
        float s = cls_scores[i];

        if (s > max_score)
        {
            top_class = i;
            max_score = s;
        }
    }
    const std::string& word = squeezenet_words[top_class];
    char tmp[32];
    sprintf(tmp, "%.3f", max_score);
    std::string result_str = std::string(word.c_str() + 10) + " = " + tmp;

    // +10 to skip leading n03179701
    jstring result = env->NewStringUTF(result_str.c_str());

    return result;
}

}

**Comment by nihui** [comment]
这个代码是正确的，libncnn.a 没有编译 openmp ?

**Comment by zhangkom** [comment]
build ncnn的时候，openMP正常，也build成功了。
-- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1") 

但是在ncnn-mobile用ndk编译上面的代码的时候，说libncnn.a里面缺少openmp。
kom$ ndk-build 
[armeabi-v7a] SharedLibrary  : libsqueezencnn.so
/Users/kom/ncnn/src/mat.cpp:168: error: undefined reference to '__kmpc_fork_call'
/Users/kom/ncnn/src/mat.cpp:37: error: undefined reference to '__kmpc_for_static_init_4'
/Users/kom/ncnn/src/mat.cpp:36: error: undefined reference to '__kmpc_for_static_fini'
/Users/kom/ncnn/src/mat.cpp:103: error: undefined reference to '__kmpc_for_static_init_4'
/Users/kom/ncnn/src/mat.cpp:102: error: undefined reference to '__kmpc_for_static_fini'
/Users/kom/ncnn/src/mat.cpp:169: error: undefined reference to '__kmpc_for_static_init_4'
/Users/kom/ncnn/src/mat.cpp:168: error: undefined reference to '__kmpc_for_static_fini'
/Users/kom/ncnn/src/mat.cpp:410: error: undefined reference to '__kmpc_global_thread_num'
/Users/kom/ncnn/src/mat.cpp:438: error: undefined reference to '__kmpc_push_num_threads'
/Users/kom/ncnn/src/mat.cpp:438: error: undefined reference to '__kmpc_fork_call'
/Users/kom/ncnn/src/mat.cpp:439: error: undefined reference to '__kmpc_for_static_init_4'
/Users/kom/ncnn/src/mat.cpp:438: error: undefined reference to '__kmpc_for_static_fini'
/Users/kom/ncnn/src/mat.cpp:679: error: undefined reference to '__kmpc_global_thread_num'
/Users/kom/ncnn/src/mat.cpp:705: error: undefined reference to '__kmpc_push_num_threads'
/Users/kom/ncnn/src/mat.cpp:705: error: undefined reference to '__kmpc_fork_call'
/Users/kom/ncnn/src/layer/arm/absval_arm.cpp:26: error: undefined reference to '__kmpc_global_thread_num'
/Users/kom/ncnn/src/layer/arm/absval_arm.cpp:32: error: undefined reference to '__kmpc_push_num_threads'
/Users/kom/ncnn/src/layer/arm/absval_arm.cpp:32: error: undefined reference to '__kmpc_fork_call'
/Users/kom/ncnn/src/layer/arm/batchnorm_arm.cpp:26: error: undefined reference to '__kmpc_global_thread_num'
/Users/kom/ncnn/src/layer/arm/batchnorm_arm.cpp:41: error: undefined reference to '__kmpc_push_num_threads'
/Users/kom/ncnn/src/layer/convolutiondepthwise.cpp:347: error: undefined reference to '__kmpc_for_static_init_8'
/Users/kom/ncnn/src/layer/convolutiondepthwise.cpp:448: error: undefined reference to '__kmpc_for_static_init_8'


下面是使用的Android.mk
LOCAL_PATH := $(call my-dir)
ARCH_ABI:=armv7
NCNN_INSTALL_PATH := /Users/kom/ncnn/build-android-$(ARCH_ABI)/install
include $(CLEAR_VARS)
LOCAL_MODULE := ncnn
LOCAL_SRC_FILES := $(NCNN_INSTALL_PATH)/lib/libncnn.a
include $(PREBUILT_STATIC_LIBRARY)
$(warning $(LOCAL_INSTALL_PATH))
include $(CLEAR_VARS)

LOCAL_MODULE := squeezencnn
LOCAL_SRC_FILES := squeezencnn_jni.cpp
LOCAL_C_INCLUDES := $(NCNN_INSTALL_PATH)/include
LOCAL_STATIC_LIBRARIES := ncnn
LOCAL_CFLAGS := -O2 -fvisibility=hidden -fomit-frame-pointer -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math
LOCAL_CPPFLAGS := -O2 -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math
LOCAL_LDFLAGS += -Wl,--gc-sections

LOCAL_CFLAGS += -fopenmp
LOCAL_CPPFLAGS += -fopenmp
LOCAL_LDFLAGS += -fopenmp
LOCAL_LDLIBS := -lz -llog -ljnigraphics
include $(BUILD_SHARED_LIBRARY)

**Comment by nihui** [comment]
kmpc 错误是要link omp
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#undefined-reference-to-__kmpc_xyz_xyz

ncnn-mobile repo 的东西太旧了点，可以试试 ncnn repo 里的 example

**Comment by zhangkom** [comment]
注释掉这一行就可以了，不知道影不影响别的？
Application.mk

#NDK_TOOLCHAIN_VERSION := 4.9

**Comment by nihui** [comment]
这行要注释的
参考 ncnn/examples/squeezencnn/jni/Application.mk

**Comment by liujhjack** [comment]
添加了
LOCAL_CFLAGS += -fopenmp
LOCAL_CPPFLAGS += -fopenmp
LOCAL_LDFLAGS += -fopenmp  ，还是报如下错误，编译libncnn.a 怎么添加openmp ?
../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn::Mat::substract_mean_normalize(float const*, float const*): error: undefined reference to '__kmpc_fork_call'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined.: error: undefined reference to '__kmpc_for_static_init_4'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined.: error: undefined reference to '__kmpc_for_static_fini'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..1: error: undefined reference to '__kmpc_for_static_init_4'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..1: error: undefined reference to '__kmpc_for_static_fini'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..2: error: undefined reference to '__kmpc_for_static_init_4'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..2: error: undefined reference to '__kmpc_for_static_fini'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn::copy_cut_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int, ncnn::Allocator*, int): error: undefined reference to '__kmpc_global_thread_num'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn::copy_cut_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int, ncnn::Allocator*, int): error: undefined reference to '__kmpc_push_num_threads'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn::copy_cut_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int, ncnn::Allocator*, int): error: undefined reference to '__kmpc_fork_call'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..3: error: undefined reference to '__kmpc_for_static_init_4'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..3: error: undefined reference to '__kmpc_for_static_fini'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn::resize_bilinear(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Allocator*, int): error: undefined reference to '__kmpc_global_thread_num'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn::resize_bilinear(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Allocator*, int): error: undefined reference to '__kmpc_push_num_threads'
../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn::resize_bilinear(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Allocator*, int): error: undefined reference to '__kmpc_fork_call'
../lib//libncnn.a(absval_arm.cpp.o):absval_arm.cpp:function ncnn::AbsVal_arm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const: error: undefined reference to '__kmpc_global_thread_num'
../lib//libncnn.a(absval_arm.cpp.o):absval_arm.cpp:function ncnn::AbsVal_arm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const: error: undefined reference to '__kmpc_push_num_threads'
../lib//libncnn.a(absval_arm.cpp.o):absval_arm.cpp:function ncnn::AbsVal_arm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const: error: undefined reference to '__kmpc_fork_call'
../lib//libncnn.a(batchnorm_arm.cpp.o):batchnorm_arm.cpp:function ncnn::BatchNorm_arm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const: error: undefined reference to '__kmpc_global_thread_num'
../lib//libncnn.a(batchnorm_arm.cpp.o):batchnorm_arm.cpp:function ncnn::BatchNorm_arm::forward_inplace(ncnn::Mat&, ncnn::Option const&) const: error: undefined reference to '__kmpc_push_num_threads'
../lib//libncnn.a(convolutiondepthwise.cpp.o):convolutiondepthwise.cpp:function .omp_outlined..4: error: undefined reference to '__kmpc_for_static_init_8'
../lib//libncnn.a(convolutiondepthwise.cpp.o):convolutiondepthwise.cpp:function .omp_outlined..7: error: undefined reference to '__kmpc_for_static_init_8'
../lib//libncnn.a(convolutiondepthwise.cpp.o):convolutiondepthwise.cpp:function .omp_outlined..10: error: undefined reference to '__kmpc_for_static_init_8'
../lib//libncnn.a(deconvolutiondepthwise.cpp.o):deconvolutiondepthwise.cpp:function .omp_outlined..1: error: undefined reference to '__kmpc_for_static_init_8'

**Comment by liujhjack** [comment]
cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-24 ..
是有以下openmp的
-- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  

> 添加了
> LOCAL_CFLAGS + = -fopenmp 
> LOCAL_CPPFLAGS + = -fopenmp 
> LOCAL_LDFLAGS + = -fopenmp，还是报如下错误，编译libncnn.a怎么添加openmp？
> ../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn :: Mat :: substract_mean_normalize（float const *，float const *）：error：undefined reference to'__kmpc_fork_call' 
> ../ lib // libncnn.a（mat.cpp.o）：mat.cpp：function .omp_outlined。：error：undefined reference to'__kmpc_for_static_init_4' 
> ../ lib//libncnn.a(mat.cpp.o): mat。 cpp：function .omp_outlined。：error：未定义引用'__kmpc_for_static_fini' 
> ../lib // libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..1：错误：未定义引用'__kmpc_for_static_init_4 “
> ../lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..1：错误：未定义引用'__kmpc_for_static_fini' 
> ../lib// libncnn.a( mat.cpp。 o）：mat.cpp：function .omp_outlined..2：错误：未定义引用'__kmpc_for_static_init_4' 
> ../lib// libncnn.a( mat.cpp.o ):mat.cpp:function .omp_outlined..2：错误：未定义引用'__kmpc_for_static_fini' 
> ../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn :: copy_cut_border（ncnn :: Mat const＆，ncnn :: Mat＆，int，int， int，int，ncnn :: Allocator *，int）：error：未定义引用'__kmpc_global_thread_num' 
> ../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn :: copy_cut_border（ncnn： ：mat const＆，ncnn :: Mat＆，int，int，int，int，ncnn :: Allocator *，int）：error：undefined reference to'__kmpc_push_num_threads'
> ../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn :: copy_cut_border（ncnn :: Mat const＆，ncnn :: Mat＆，int，int，int，int，ncnn :: Allocator *，int）：错误：未定义引用'__kmpc_fork_call' 
> ../lib // libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..3：错误：未定义引用'__kmpc_for_static_init_4' 
> 。 ./lib//libncnn.a(mat.cpp.o):mat.cpp:function .omp_outlined..3：错误：未定义引用'__kmpc_for_static_fini' 
> ../lib// libncnn.a( mat.cpp.o ）：mat.cpp：function ncnn :: resize_bilinear（ncnn :: Mat const＆，ncnn :: Mat＆，int，int，ncnn :: Allocator *，int）：error：未定义引用'__kmpc_global_thread_num'
> ../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn :: resize_bilinear（ncnn :: Mat const＆，ncnn :: Mat＆，int，int，ncnn :: Allocator *，int） ：错误：未定义引用'__kmpc_push_num_threads' 
> ../lib//libncnn.a(mat.cpp.o):mat.cpp:function ncnn :: resize_bilinear（ncnn :: Mat const＆，ncnn :: Mat＆，int，int ，ncnn :: Allocator *，int）：错误：未定义引用'__kmpc_fork_call' 
> ../lib//libncnn.a(absval_arm.cpp.o):absval_arm.cpp:function ncnn :: AbsVal_arm :: forward_inplace（ncnn： ：Mat＆，ncnn :: Option const＆）const：error：undefined reference to'__kmpc_global_thread_num' 
> ../lib//libncnn.a(absval_arm.cpp.o):absval_arm.cpp:function ncnn :: AbsVal_arm :: forward_inplace（ncnn :: Mat＆，ncnn :: Option const＆）const：error：未定义引用'__kmpc_push_num_threads'
> ../lib//libncnn.a(absval_arm.cpp.o):absval_arm.cpp:function ncnn :: AbsVal_arm :: forward_inplace（ncnn :: Mat＆，ncnn :: Option const＆）const：error：undefined reference to'__kmpc_fork_call ' 
> ../lib//libncnn.a(batchnorm_arm.cpp.o):batchnorm_arm.cpp:function ncnn :: BatchNorm_arm :: forward_inplace（ncnn :: Mat＆，ncnn :: Option const＆）const：error：undefined reference to' __kmpc_global_thread_num' 
> ../lib//libncnn.a(batchnorm_arm.cpp.o):batchnorm_arm.cpp:function ncnn :: BatchNorm_arm :: forward_inplace（ncnn :: Mat＆，ncnn :: Option const＆）const：error：undefined reference to '__kmpc_push_num_threads' 
> ../lib // libncnn.a(convolutiondepthwise.cpp.o):convolutiondepthwise.cpp:function .omp_outlined..4：错误：未定义引用'__kmpc_for_static_init_8'
> ../lib//libncnn.a(convolutiondepthwise.cpp.o):convolutiondepthwise.cpp:function .omp_outlined..7：错误：未定义引用'__kmpc_for_static_init_8' 
> ../lib// libncnn.a( convolutiondepthwise.cpp。 o）：convolutiondepthwise.cpp：function .omp_outlined..10：error：undefined reference to'__kmpc_for_static_init_8' 
> ../lib // libncnn.a(deconvolutiondepthwise.cpp.o):deconvolutiondepthwise.cpp:function .omp_outlined..1：错误：对'__kmpc_for_static_init_8'的未定义引用

cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON -DANDROID_PLATFORM=android-24 ..
是有以下openmp的
-- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")
