### ISSUE TITLE
caffe2ncnn read_int8scale_table

### ISSUE THREAD

**Issue by lippman1125** [Tencent/ncnn#664]
caffe2ncnn 
read_int8scale_table can not correctly parse xxx.table .

The part of xxx.table as follow:

conv1/7x7_s3_param_0 115.8229307728101
inception_2a/3x3_reduce_param_0 127.11296596065004
inception_2a/3x3_param_0 156.20083876232303
inception_2a/5x5_reduce_param_0 115.41536851175779
inception_2a/5x5_param_0 89.52436692383993

I find a workaround, if i comment out  bold  sentences.
![read_int8](https://user-images.githubusercontent.com/27212106/48840007-5334a000-edc8-11e8-8368-262245739174.png)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/501cdf2adfe98c31c34be47a162072def61c49d7
更新下，试试看

**Comment by lippman1125** [comment]
> [501cdf2](https://github.com/Tencent/ncnn/commit/501cdf2adfe98c31c34be47a162072def61c49d7)
> 更新下，试试看

I just tried it, new commit may omit the last line of the xxxx.table.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/9b10729860341d71878c1dec640006d05f73abbb

try to fix the last line issue.

**Comment by lippman1125** [comment]
> [9b10729](https://github.com/Tencent/ncnn/commit/9b10729860341d71878c1dec640006d05f73abbb)
> 
> try to fix the last line issue.

In my case, it works.
