### ISSUE TITLE
如何在mac中安装ncnn 

### ISSUE THREAD

**Issue by jj8401** [Tencent/ncnn#67]
参考http://blog.csdn.net/best_coder/article/details/76201275中
在cmake ..中出现
-- CMAKE_INSTALL_PREFIX = /Users/yangguangdejianjian/code/ncnn/build/install
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
WITH_LAYER_absval = ON
WITH_LAYER_argmax = OFF
WITH_LAYER_batchnorm = ON
WITH_LAYER_bias = ON
WITH_LAYER_bnll = ON
WITH_LAYER_concat = ON
WITH_LAYER_convolution = ON
WITH_LAYER_crop = ON
WITH_LAYER_deconvolution = ON
WITH_LAYER_dropout = ON
WITH_LAYER_eltwise = ON
WITH_LAYER_elu = ON
WITH_LAYER_embed = OFF
WITH_LAYER_exp = ON
WITH_LAYER_flatten = ON
WITH_LAYER_innerproduct = ON
WITH_LAYER_input = ON
WITH_LAYER_log = ON
WITH_LAYER_lrn = ON
WITH_LAYER_memorydata = OFF
WITH_LAYER_mvn = ON
WITH_LAYER_pooling = ON
WITH_LAYER_power = ON
WITH_LAYER_prelu = ON
WITH_LAYER_proposal = OFF
WITH_LAYER_reduction = OFF
WITH_LAYER_relu = ON
WITH_LAYER_reshape = OFF
WITH_LAYER_roipooling = OFF
WITH_LAYER_scale = ON
WITH_LAYER_sigmoid = ON
WITH_LAYER_slice = ON
WITH_LAYER_softmax = ON
WITH_LAYER_split = ON
WITH_LAYER_spp = OFF
WITH_LAYER_tanh = ON
WITH_LAYER_threshold = ON
WITH_LAYER_tile = OFF
WITH_LAYER_rnn = OFF
WITH_LAYER_lstm = OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yangguangdejianjian/code/ncnn/build

请教如何解决

**Comment by iphone5solo** [comment]
@jj8401  在根目录下的` CMakeLists.txt`  文件中 关闭` openmp`  如下


option(NCNN_OPENMP "openmp support" OFF)

**Comment by jj8401** [comment]
感谢老铁

**Comment by BiranLi** [comment]
或者你考虑在机子上装个openmp呗

**Comment by AirFishWang** [comment]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 

使用gcc4.9.4时, 检测openmp成功了,为什么Could NOT find OpenMP?

**Comment by logic1988** [comment]
在mac上采用`brew install gcc --without-multilib`装了支持openmp的g++后, 采用`export CXX=g++-7 CC=gcc-7 &&  cmake ..`命令编译会提示成功找到openmp, 但会出现https://github.com/Tencent/ncnn/issues/91中一样的protobuf错误, 即使切换回非openmp版g++还会出错, 除非手动指定-DNCNN_OPENMP=OFF后才能成功编译.

**Comment by yang-chenyu104** [comment]
我的是编译make -j$(sysctl -n hw.ncpu)会出现头文件找不到  "___emutls_v._ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E", referenced from:
      google::protobuf::RepeatedField<long long>::GrowNoAnnotate(bool, int, int) in caffe.pb.cc.o
      google::protobuf::RepeatedField<float>::GrowNoAnnotate(bool, int, int) in caffe.pb.cc.o
      google::protobuf::RepeatedField<double>::GrowNoAnnotate(bool, int, int) in caffe.pb.cc.o
      google::protobuf::RepeatedField<int>::GrowNoAnnotate(bool, int, int) in caffe.pb.cc.o
      google::protobuf::RepeatedField<bool>::GrowNoAnnotate(bool, int, int) in caffe.pb.cc.o
      google::protobuf::RepeatedField<unsigned int>::GrowNoAnnotate(bool, int, int) in caffe.pb.cc.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe/caffe2ncnn] Error 1
make[1]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/all] Error 2
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
