### ISSUE TITLE
layer =64 not exists, layer index -1  not exists, custom  layer =64 not exists, custom   layer index -1  not exists,

### ISSUE THREAD

**Issue by dlml** [Tencent/ncnn#673]
能够正常从pytorch-onnx-ncnn,mxnet-ncnn

模型文件parm在load的时候报如下错误
![default](https://user-images.githubusercontent.com/35597616/49139186-161e5f80-f32c-11e8-97c6-c3698638ee52.png)

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/d9d7d6b6eae223598cb63e27335d5e6385d9750c

please try the latest code

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
