### ISSUE TITLE
ndk-build提示错误，但是还会在libs文件夹内生成.so文件。然后运行在android 上识别输出为0

### ISSUE THREAD

**Issue by IrisLimiao** [Tencent/ncnn#678]
@nihui 你好。我在windows上编译出build-android文件夹，里边包含install->include头文件以及lib中的libncnn.a文件。下一步在AS terminal中执行的ndk-build(或者在VS2017)都会提示如下
libncnn.a: error adding symb
ols: File in wrong format
collect2.exe: error: ld returned 1 exit status
![default](https://user-images.githubusercontent.com/44689073/49216225-8351f380-f405-11e8-858f-7a910436b5b2.png)

然后error了还能生成libs文件夹，其中有libsqueezencnn.so文件，编译可以通过，但是在手机上运行的识别输出为0.

我用的工程是https://github.com/Tencent/ncnn/tree/master/examples/squeezencnn这个。
请大家帮忙指导一下，谢谢！

**Comment by nihui** [comment]
你没有编译出 arm64-v8a 的 libncnn.a，所以生成 arm64-v8a so 失败了
