### ISSUE TITLE
slice与etlwise层转换不了

### ISSUE THREAD

**Issue by eeric** [Tencent/ncnn#68]
ncnn的caffe2ncnn命令无法转换这2种层

**Comment by nihui** [comment]
样例 prototxt 和 caffemodel 能提供下吗？

**Comment by eeric** [comment]
@nihui 
it was from that the light cnn C model
 https://github.com/AlfredXiangWu/face_verification_experiment

**Comment by nihui** [comment]
下载下来看了下，lightcnn C 的 prototxt 最后那个 fc2 在对应的 caffemodel 中没有找到，看了下 caffemodel 内容发现被改成了 fc2_ms
把 prototxt 里面的 fc2 改成 fc2_ms 就可以了

ps 对于这种提取特征的模型，建议拿到 eltwise_fc1 就可以了，后面的可以不用，才 20.9M  :)

**Comment by eeric** [comment]
@nihui，感谢，我试试

**Comment by wangkgege** [comment]
@eeric ，你的问题解决了吗？
@nihui ，你好，我的prototxt文件中也包含Slice层，在使用caffe2ncnn的时候没有报错。但在读取模型的时候报错。
layer {
  name: "slicer_data"
  type: "Slice"
  bottom: "data"
  top: "data241"
  top: "data242"
  top: "data243"
  top: "data244"
  top: "data245"
  slice_param {
    slice_point: 3
    slice_point: 6
    slice_point: 9
    slice_point: 12
    axis: 1
  }
}
错误信息：
layer data241 not exists
layer index -1 not exists
custom layer data241 not exists
custom layer index -1 not exists
我查看了caffemodel的层名字，确实没有layer data241。
请问这种情况，如何处理？

**Comment by nihui** [comment]
@wangkgege 转换后的 param 能贴下吗？

**Comment by wangkgege** [comment]
方便留个邮箱吗？我发给你。

**Comment by wangkgege** [comment]
不好意思，确实不方便把param贴在这里。这是我的邮箱1575929189@qq.com。麻烦你给我发封邮件，我回复给你param。

**Comment by nihui** [comment]
@wangkgege  https://github.com/kpzhang93/MTCNN_face_detection_alignment/blob/master/code/codes/MTCNNv2/model/det4.prototxt
类似这个？

**Comment by wangkgege** [comment]
@nihui ，对，跟这个类似。

**Comment by nihui** [comment]
转换器的 slice 确实有问题，已修改
https://github.com/Tencent/ncnn/commit/ced04ddb4a6a5bcc23ce25914184de200c006f86

**Comment by wangkgege** [comment]
@nihui  模型读取成功！ 大神威武！！

**Comment by eeric** [comment]
@nihui @wangkgege ,lightcnn C模型转换成功，但在etlwise_fc1提取的256维特征与caffe版的平均L1规则误差在实数1以内。
是不是按ced04dd修改，就可以纠正？

**Comment by moli232777144** [comment]
各位转换移植结果怎样？lightcnnA的模型，我测试通过了，识别率复现正常，但B和C模型结果就不对，粗略看了下，A与B主要模型结构的差异，A模型Eltwise 后接的Convolution层，B模型Eltwise 后接的是pooling层，数据预处理方面如下代码，复现过的朋友能说下您复现的结果如果吗。	
       `
	ncnn::Mat in = ncnn::Mat::from_pixels_resize(img.data, ncnn::Mat::PIXEL_GRAY,
		img.cols, img.rows, crop_size, crop_size);
        const float mean_vals[3] = { 0.0f, 0.0f, 0.0f };
	const float norm_vals[3] = { 0.003922f, 0.003922f, 0.003922f };
	in.substract_mean_normalize(mean_vals, norm_vals);`
