### ISSUE TITLE
What is resnet.table when convert caffe model to ncnn quantized int8 model?

### ISSUE THREAD

**Issue by MasonSuWei** [Tencent/ncnn#681]
Hi,
I have tried to quantize the mode(reading the follow link). But I don't know what resnet.table is and how I get this file.
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
./caffe2ncnn resnet.prototxt resnet.caffemodel resnet-int8.param resnet-int8.bin 256 resnet.table

Best regards

**Comment by nihui** [comment]
the table file is generated by https://github.com/BUG1989/caffe-int8-convert-tools
