### ISSUE TITLE
有关detectionoutput这个层，我想把同类抑制，改成非同类也抑制  该怎么做啊

### ISSUE THREAD

**Issue by liuzhenhui** [Tencent/ncnn#685]
ncnn 中 detectionoutput 这个层我看了貌似代码是写的是同类抑制的，我想改成非同类只要iou过大就抑制，请问有人改过吗 可以帮一下小忙吗～ 1061441313@qq.com

**Comment by nihui** [comment]
global sort inplace 后面再接个 nms 不就好了....

**Comment by liuzhenhui** [comment]
谢谢@nihui ～  我更改了一下在global sort inplace 后面又加了nms确实可行 ，问题解决，但是感觉这样是不是有点重复计算啊，会不会不太高效，过一会儿再优化一下看看 。十分感谢～
