### ISSUE TITLE
想直接build-android出来可执行example   但make时出错

### ISSUE THREAD

**Issue by xiaoyang151** [Tencent/ncnn#688]
修改后的cmakelist：
if(ANDROID)
    # disable shared library on android
    set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions -pie -fPIE") 
    set(OpenCV_DIR "/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/jni")
elseif(IOS)
    # disable shared library on xcode ios
    set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-rtti -fno-exceptions")
endif()

##############################################

add_subdirectory(examples)
add_subdirectory(benchmark)
add_subdirectory(src)
if(NOT ANDROID AND NOT IOS)
add_subdirectory(tools)
endif()
 ##############
make时报错：
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(system.cpp.o):system.cpp:function std::vector<void*, std::allocator<void*> >::_M_fill_insert(__gnu_cxx::__normal_iterator<void**, std::vector<void*, std::allocator<void*> > >, unsigned int, void* const&): error: undefined reference to 'std::__throw_length_error(char const*)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(system.cpp.o):system.cpp:function _GLOBAL__sub_I_system.cpp: error: undefined reference to 'std::ios_base::Init::Init()'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(system.cpp.o):system.cpp:function _GLOBAL__sub_I_system.cpp: error: undefined reference to 'std::ios_base::Init::~Init()'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf(): error: undefined reference to 'std::locale::~locale()'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf(): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf(): error: undefined reference to 'std::string::_Rep::_S_empty_rep_storage'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf(): error: undefined reference to 'vtable for std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
/home/local/SPREADTRUM/ziyang.duan/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::~basic_stringbuf(): error: undefined reference to 'vtable for std::basic_streambuf<char, std::char_traits<char> >'
/home/local/SPREADTRUM/ziyang.duan/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::string::assign(std::string const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::string::assign(std::string const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::string::_Rep::_M_dispose(std::allocator<char> const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::string::_Rep::_M_dispose(std::allocator<char> const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::string::_Rep::_M_dispose(std::allocator<char> const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::string::_Rep::_M_dispose(std::allocator<char> const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'
/home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(ocl.cpp.o):ocl.cpp:function std::vector<std::string, std::allocator<std::string> >::_M_insert_aux(__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, std::string const&): error: undefined reference to 'std::string::_Rep::_M_destroy(std::allocator<char> const&)'

**Comment by nihui** [comment]
android example 可以参考 examples/squeezencnn

**Comment by yu20103983** [comment]
我也出现了同样的问题， 请问你解决了吗
