### ISSUE TITLE
请问如何在Linux上编译源码?

### ISSUE THREAD

**Issue by Igamegum** [Tencent/ncnn#69]
我直接操作如下
`1. cd ncnn 
2. mkdir build && cd build
3. cmake ..
4. make
`

make 的时候报错如下
`[ 90%] Linking CXX executable ncnn2mem
[ 90%] Built target ncnn2mem
make[2]: *** No rule to make target '../tools/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'tools/caffe.pb.cc'.  Stop.
CMakeFiles/Makefile2:179: recipe for target 'tools/CMakeFiles/caffe2ncnn.dir/all' failed
make[1]: *** [tools/CMakeFiles/caffe2ncnn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by nihui** [comment]
需要先安装protobuf devel

**Comment by BiranLi** [comment]
少了protobuf-compiler

**Comment by Igamegum** [comment]
已解决，谢谢

**Comment by 522730312** [comment]
install opencv for building example 的时候遇到这么一个问题：ncnn/examples/fasterrcnn.cpp:3:33: fatal error: opencv2/core/core.hpp: 没有那个文件或目录

**Comment by creat2012** [comment]
> 已解决，谢谢

一样的问题， 请问是如何解决的？

**Comment by spaul13** [comment]
Did anyone (@522730312, @creat2012)  solve this issue? I am also getting the same problem of  opencv2/core/core.hpp file not found.

**Comment by yuzhengfa** [comment]
ubuntu@6f2da8572426:~/MyFiles/INT8/ncnn/build/examples$ ./squeezenet test.jpg
ModelBin read weight_data failed 0
layer load_model 22 failed
Segmentation fault (core dumped)
ubuntu@6f2da8572426:~/MyFiles/INT8/ncnn/build/examples$

**Comment by yuzhengfa** [comment]
make编译出现以下问题：
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Warning: File 'examples/CMakeFiles/peleenetssd_seg.dir/flags.make' has modification time 98 s in the future
[ 96%] Building CXX object examples/CMakeFiles/peleenetssd_seg.dir/peleenetssd_seg.cpp.o
/home/ubuntu/MyFiles/INT8/ncnn/examples/peleenetssd_seg.cpp: In function ‘void draw_objects(const cv::Mat&, const std::vector<Object>&, ncnn::Mat)’:
/home/ubuntu/MyFiles/INT8/ncnn/examples/peleenetssd_seg.cpp:97:53: error: in C++98 ‘color’ must be initialized by constructor, not by ‘{...}’
     std::vector<int> color = {128,255,128,244,35,232};
                                                     ^
/home/ubuntu/MyFiles/INT8/ncnn/examples/peleenetssd_seg.cpp:97:53: error: could not convert ‘{128, 255, 128, 244, 35, 232}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<int>’
/home/ubuntu/MyFiles/INT8/ncnn/examples/peleenetssd_seg.cpp:150:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if(color_index<color.size()) {
                               ^
examples/CMakeFiles/peleenetssd_seg.dir/build.make:62: recipe for target 'examples/CMakeFiles/peleenetssd_seg.dir/peleenetssd_seg.cpp.o' failed
make[2]: *** [examples/CMakeFiles/peleenetssd_seg.dir/peleenetssd_seg.cpp.o] Error 1
CMakeFiles/Makefile2:436: recipe for target 'examples/CMakeFiles/peleenetssd_seg.dir/all' failed
make[1]: *** [examples/CMakeFiles/peleenetssd_seg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mumuyanyan** [comment]
> 已解决，谢谢

你好，同样在问题，请问如何解决

**Comment by jianbaba** [comment]
> ubuntu@6f2da8572426:~/MyFiles/INT8/ncnn/build/examples$ ./squeezenet test.jpg ModelBin read weight_data failed 0 layer load_model 22 failed Segmentation fault (core dumped) ubuntu@6f2da8572426:~/MyFiles/INT8/ncnn/build/examples$

请问这个怎么解决的
