### ISSUE TITLE
cmake时有警告，有影响吗

### ISSUE THREAD

**Issue by xiaoyang151** [Tencent/ncnn#690]
build-android-armv7$ cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake     -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON     -DANDROID_PLATFORM=android-14  -DANDROID_STL_FORCE_FEATURES=OFF ..
-- CMAKE_TOOLCHAIN_FILE = /home/local/SPREADTRUM/ziyang.duan/android-ndk-r15c/build/cmake/android.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /home/local/SPREADTRUM/ziyang.duan/ncnn/build-android-armv7/install
CMake Warning (dev) at /home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/jni/abi-armeabi-v7a/OpenCVModules.cmake:205 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
Call Stack (most recent call first):
  /home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/jni/abi-armeabi-v7a/OpenCVConfig.cmake:125 (include)
  /home/local/SPREADTRUM/ziyang.duan/OpenCV-android-sdk/sdk/native/jni/OpenCVConfig.cmake:44 (include)
  examples/CMakeLists.txt:2 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

WITH_LAYER_absval = ON
WITH_LAYER_argmax = OFF
WITH_LAYER_batchnorm = ON
WITH_LAYER_bias = ON
WITH_LAYER_bnll = ON
WITH_LAYER_concat = ON
WITH_LAYER_convolution = ON
WITH_LAYER_crop = ON
WITH_LAYER_deconvolution = ON
WITH_LAYER_dropout = ON
WITH_LAYER_eltwise = ON
WITH_LAYER_elu = ON
WITH_LAYER_embed = ON
WITH_LAYER_exp = ON
WITH_LAYER_flatten = ON
WITH_LAYER_innerproduct = ON
WITH_LAYER_input = ON
WITH_LAYER_log = ON
WITH_LAYER_lrn = ON
WITH_LAYER_memorydata = ON
WITH_LAYER_mvn = ON
WITH_LAYER_pooling = ON
WITH_LAYER_power = ON
WITH_LAYER_prelu = ON
WITH_LAYER_proposal = ON
WITH_LAYER_reduction = ON
WITH_LAYER_relu = ON
WITH_LAYER_reshape = ON
WITH_LAYER_roipooling = ON
WITH_LAYER_scale = ON
WITH_LAYER_sigmoid = ON
WITH_LAYER_slice = ON
WITH_LAYER_softmax = ON
WITH_LAYER_split = ON
WITH_LAYER_spp = OFF
WITH_LAYER_tanh = ON
WITH_LAYER_threshold = ON
WITH_LAYER_tile = OFF
WITH_LAYER_rnn = OFF
WITH_LAYER_lstm = OFF
WITH_LAYER_binaryop = ON
WITH_LAYER_unaryop = ON
WITH_LAYER_convolutiondepthwise = ON
WITH_LAYER_padding = ON
WITH_LAYER_squeeze = ON
WITH_LAYER_expanddims = ON
WITH_LAYER_normalize = ON
WITH_LAYER_permute = ON
WITH_LAYER_priorbox = ON
WITH_LAYER_detectionoutput = ON
WITH_LAYER_interp = ON
WITH_LAYER_deconvolutiondepthwise = ON
WITH_LAYER_shufflechannel = ON
WITH_LAYER_instancenorm = ON
WITH_LAYER_clip = ON
WITH_LAYER_reorg = ON
WITH_LAYER_yolodetectionoutput = ON
WITH_LAYER_quantize = ON
WITH_LAYER_dequantize = ON
WITH_LAYER_yolov3detectionoutput = ON
-- Configuring done
-- Generating done

**Comment by nihui** [comment]
不影响，不要生成动态库
