### ISSUE TITLE
DepthwiseConvolution层的输出错误

### ISSUE THREAD

**Issue by lrain-CN** [Tencent/ncnn#692]
caffe转ncnn，ConvolutionDepthwise层输出维度为0,0,0 导致最终输出为nan。caffe的结果是正确的，这个问题有时候出现在把shuffleNetV2网络第一层Conv 的stride 2改为1 出现的，但是其他类似的网络输出是正确的 。

**Comment by kalcohol** [comment]
手动添加 7=group 你要的分组数，并且重新计算 6=? 可以临时解决这个问题。

**Comment by nihui** [comment]
shufflenetv2 works out of box
just uploaded an example here
https://github.com/Tencent/ncnn/blob/master/examples/shufflenetv2.cpp
you can refer this code

**Comment by lrain-CN** [comment]
> 
> 
> 手动添加 7=group 你要的分组数，并且重新计算 6=? 可以临时解决这个问题。

感谢回复，确实是参数转的时候产生错误了 手动修改可以解决~不知道是什么导致的
