### ISSUE TITLE
Regression with Mobilenet-SSD V2 Caffe-ssd model

### ISSUE THREAD

**Issue by ayounes-nviso** [Tencent/ncnn#694]
With the latest master, the bounding box are completely wrong, it was correct a few days ago with the same models and input images. For example:

previously: w=540.5, h=644.089, x=612.796, y=294.769
now: w=49.8276, h=54.9937, x=-11.3205, y=-16.5792

Here is the code I use to retrieve the results, is there something I need to change?

```
  ncnn::Mat out;
  res = ex.extract("detection_out", out);

  struct NcnnSsdResult {
    // ncnn does not give sampleIx
    // float sampleIx;
    float labelId;
    float confidence;
    float x1;
    float y1;
    float x2;
    float y2;
  };

  std::vector<DetectedFace> faces;
  for (int i = 0; i < out.h; i++) {
    auto box = reinterpret_cast<const NcnnSsdResult*>(out.row(i));
    // Top left corner
    float x1 = box->x1 * imageWidth;
    float y1 = box->y1 * imageHeight;
    // Bottom right corner
    float x2 = box->x2 * imageWidth;
    float y2 = box->y2 * imageHeight;

    DetectedFace face = {box->confidence, {x1, y1, x2 - x1, y2 - y1}};
    detectedFaces->push_back(face);
  }
```

**Comment by nihui** [comment]
regression in commit https://github.com/Tencent/ncnn/commit/65be036aa6562848449abe901dfcf4fdbbc4db77
should fixed in https://github.com/Tencent/ncnn/commit/adfbb9eb2512a320a755f5b3a0dbb560c3ad75db

**Comment by ayounes-nviso** [comment]
Thanks a lot!
