### ISSUE TITLE
android中set_omp_num_threads设置始终无效，不知道到底opemmp是否有生效啊？

### ISSUE THREAD

**Issue by bigbao9494** [Tencent/ncnn#698]
1、初始化代码如下，确定extractor中没有设置线程
    LOGD("ncnn default num_threads: %d,lightmode: %d,omp_dynamic: %d",ncnn::get_default_option().num_threads,
         ncnn::get_default_option().lightmode,ncnn::get_omp_dynamic());
    ncnn::set_omp_dynamic(1);
    ncnn::Option opt;
    opt.lightmode = false;
    //opt.num_threads = 4;
    ncnn::set_default_option(opt);
    ncnn::set_omp_num_threads( 4 );
    LOGD("ncnn default num_threads: %d,lightmode: %d,omp_dynamic: %d",ncnn::get_default_option().num_threads,
         ncnn::get_default_option().lightmode,ncnn::get_omp_dynamic());
    LOGD("ncnn cpu num = %d",ncnn::get_cpu_count());
    LOGD("ncnn cpu num omp = %d",ncnn::get_omp_num_threads());
	
	打印内容：get_omp_num_threads始终返回1
	ncnn default num_threads: 6,lightmode: 1,omp_dynamic: 0
	ncnn default num_threads: 6,lightmode: 0,omp_dynamic: 1
	ncnn cpu num = 6
	ncnn cpu num omp = 1

	确定OPENMP是编译到了的：
	因为在上面set_omp_dynamic(1)都是生效了的，如果没有编译的话根据源码cpu.cpp中
	get_omp_dynamic只会返回0，说明宏_OPENMP是有效的
	-- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
	-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
	-- Found OpenMP: TRUE (found version "3.1")  
	-- Configuring done
	-- Generating done

2、测试extractor中设置线程方式比上面初始化(不在extractor中设置线程数量)快，为什么会这样？

**Comment by nihui** [comment]
可以参考 benchmark/benchncnn.cpp 的做法和测试
