### ISSUE TITLE
关于mxnet的BatchNorm层和ncnn的BatchNorm计算方式的疑问？

### ISSUE THREAD

**Issue by dlml** [Tencent/ncnn#702]
mxnet的bn层前向的计算方式是利用上一层的输出计算得到每个channel的mean和var，然后利用参数文件里边读出来的gamma和beta，接着就可以用公式计算bn层的输出了，我这样算出来和利用mxnet的api的结果一致。但是ncnn里边的mean_data读取的是mxnet参数文件中的moving_mean, 对应的var_data读取的是mxnet参数文件中的moving_var, 至于beta和gamma值是对的，但最终输出和mxnet输出相差很大。同时验证了一下如果python用moving_mean和moving_var算的话和ncnn这层的结果一致！

**Comment by dlml** [comment]
layer = mx.symbol.BatchNorm(data=layer, name='batchnorm-%d' % i)
欢迎小伙伴们验证一下

**Comment by nihui** [comment]
你说的计算方式是训练过程的，ncnn的推断计算没有问题
