### ISSUE TITLE
Sigmoid layer

### ISSUE THREAD

**Issue by weiyichang** [Tencent/ncnn#704]
Hi
I see the sigmoid.cpp src/layer
but when I use onnx2ncnn.cpp or caffe2ncnn.cpp
It seems that they can not convert sigmoid layer ?
So I want to check whether ncnn support sigmoid layer?
Thanks!

**Comment by nihui** [comment]
caffe2ncnn support sigmoid out of box
onnx2ncnn sigmoid just added https://github.com/Tencent/ncnn/commit/fdb69378ac97219a189a9fcee9e5ef44ec41566c
