### ISSUE TITLE
Comparision benchmark?

### ISSUE THREAD

**Issue by mrgloom** [Tencent/ncnn#710]
Is any benchmark using `nccn` for mobile platform is available?
Something like http://cknowledge.org/dashboard/mlperf.mobilenets

Here is `ncnn` is in some tables, but I'm not sure how it's related to consumer mobile phones
https://github.com/ARM-software/ComputeLibrary/issues/599

**Comment by nihui** [comment]
you can find the benchmark tool and some result in ncnn/benchmark folder
https://github.com/Tencent/ncnn/tree/master/benchmark
