### ISSUE TITLE
循环去执行网络的时候不同的输入得到同样的输出

### ISSUE THREAD

**Issue by z13974509906** [Tencent/ncnn#718]
因为没有batchsize的维度，所以只能一张一张的执行，我的代码大概是这样：
```c++
ncnn::Net net;
net.load_param(xxx);
net.load_model(xxx);

ncnn::Extractor ex = net.create_extractor();
//数据获取，得到数据集dataset
for(int i=0;i<dataset.size();++i){
      ex.input("data", dataset[i]);
      ex.extract("prob", out);
}
```

这样每次得到的out都是一样的，我把代码改成以下形式就可以正确执行
```c++
ncnn::Net net;
net.load_param(xxx);
net.load_model(xxx);


//数据获取，得到数据集dataset
for(int i=0;i<dataset.size();++i){
    ncnn::Extractor ex = net.create_extractor();
    ex.input("data", dataset[i]);
    ex.extract("prob", out);
}
```
请问下这是正确的使用方法吗？ 是不是需要每次都重新生成Extractor？这样子感觉效率有点低，Extractor有类似clear的API吗？ 还有没有更优雅的跑batchsize的方式啊，求解答。。。万分感谢

**Comment by nihui** [comment]
每次创建新 Extractor
Extractor 几乎不耗时，不需要考虑这个地方复用

**Comment by jolt2017** [comment]
> 每次创建新 Extractor
> Extractor 几乎不耗时，不需要考虑这个地方复用

大佬，这个问题我找了 两天....

**Comment by CsVeryLoveXieWenLi** [comment]
> 每次创建新 Extractor Extractor 几乎不耗时，不需要考虑这个地方复用

原来如此么，那我就得到答案了。

**Comment by hjq052070** [comment]
> 每次创建新 Extractor Extractor 几乎不耗时，不需要考虑这个地方复用

大佬你好！请问ncnn推理的过程到底是哪一步呢？是ex.extract这一步吗？另外发现循环每次创建extractor时间好像还挺长的
