### ISSUE TITLE
android上用新的model问题

### ISSUE THREAD

**Issue by hilohg** [Tencent/ncnn#72]
我稍微修改了conv 以及conv arm的实现，改成depthwise conv 的， 只改了前向过程，其他的模型加载等等都是用的convolution的， 都没有改，然后在mac上模型加载以及运行都正常，但是，在andorid上跑时候，在
https://github.com/Tencent/ncnn/blob/master/examples/squeezencnn/src/com/tencent/squeezencnn/MainActivity.java#L128
时候就挂了， 我想问是什么问题导致的？

**Comment by nihui** [comment]
最新的android demo可以参考 https://github.com/nihui/ncnn-android-squeezenet
另外 depthwise conv 已经直接支持，无需修改了
