### ISSUE TITLE
InnerProduct 参数中axis: 2，forward的时候指针越界

### ISSUE THREAD

**Issue by ppl21847** [Tencent/ncnn#721]
layer {
  name: "fc_t2_"
  type: "InnerProduct"
  bottom: "fc_t1"
  top: "fc_t2"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  inner_product_param {
    num_output: 512
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
    axis: 2
  }
}
网络如上，forward的时候 指针越界，有没有遇到的呢

**Comment by nihui** [comment]
innerproduct 现已支持二维矩阵乘
