### ISSUE TITLE
自定义网络可以运算但是无法提取结果

### ISSUE THREAD

**Issue by sweed111** [Tencent/ncnn#724]
网络param
7767517
19 19
Input            data             0 1 data 0=64 1=64 2=3
Convolution      conv1            1 1 data conv1 0=32 1=3 2=1 3=1 4=1 5=1 6=270
PReLU            prelu1           1 1 conv1 conv1_prelu1 0=32
Pooling          pool1            1 1 conv1_prelu1 pool1 0=0 1=2 2=2 3=0 4=0
Convolution      conv2            1 1 pool1 conv2 0=64 1=3 2=1 3=1 4=1 5=1 6=1440
PReLU            prelu2           1 1 conv2 conv2_prelu2 0=64
Pooling          pool2            1 1 conv2_prelu2 pool2 0=0 1=2 2=2 3=0 4=0
Convolution      conv3            1 1 pool2 conv3 0=128 1=3 2=1 3=1 4=1 5=1 6=4608
PReLU            prelu3           1 1 conv3 conv3_prelu3 0=128
Pooling          pool3            1 1 conv3_prelu3 pool3 0=0 1=2 2=2 3=0 4=0
Convolution      conv4            1 1 pool3 conv4 0=256 1=3 2=1 3=1 4=1 5=1 6=294912
PReLU            prelu4           1 1 conv4 conv4_prelu4 0=256
Pooling          pool4            1 1 conv4_prelu4 pool4 0=0 1=2 2=2 3=0 4=0
Convolution      conv5            1 1 pool4 conv5 0=256 1=3 2=1 3=1 4=1 5=1 6=589824
PReLU            prelu5           1 1 conv5 conv5_prelu5 0=256
Pooling          pool5            1 1 conv5_prelu5 pool5 0=0 1=2 2=2 3=0 4=0
Convolution      conv6            1 1 pool5 conv6 0=1024 1=2 2=1 3=1 4=0 5=1 6=1048576
PReLU            prelu6           1 1 conv6 conv6_prelu6 0=1024
InnerProduct     conv7            1 1 conv6_prelu6 conv7 0=136 1=1 2=139264

读取载入模型应该都没报错
ex.extract("conv7", keyPoint);
读取输出的时候报错了，程序崩了

然后我从第一层开始读 排查
依次读了 conv1 pool1 都还能读到东西，c w h 也与期望的输出结构一致
读conv2 的时候直接程序崩了 conv2往后的层都没法读。。。这是什么原因呢？？

求帮助啊 感谢感谢

**Comment by sleepwalker2017** [comment]
gdb 跟进去看啊   这代码开源的  正好你也熟悉一下代码呗

**Comment by sweed111** [comment]
把caffe原模型看了下，是caffe的原因， 在caffe训练时 我第一层设置的输出是32 而实际训练出来的模型输出只有10 很奇怪 跟ncnn这边关联不大
