### ISSUE TITLE
ncnn请问一下支持int8哪些大小的卷积核？

### ISSUE THREAD

**Issue by xiangyu19** [Tencent/ncnn#728]
ncnn请问一下支持int8哪些大小的卷积核？我知道的有3x3和1x1，请问7x7，11x11支持么？因为从caffe转成ncnn的量化模型的时候，7x7和11x11这些都是没有被打开量化开关的，也就是没有8=1这个参数，请问一下是不是只支持3x3和1x1的量化优化啊？

**Comment by BUG1989** [comment]
@Vxychen 
目前7x7已经支持了，11x11的话，理论上是支持的，因为现在新增了 im2col + sgemm的int8实现，可以支持任意尺寸的kernel，但是需要修改下代码调用逻辑。目前支持以下kernel size

- conv1x1s1/s2
- conv3x3s1/s2
- conv5x5s1/s2
- conv7x7s1/s2

现在那个量化工具，只要是conv layer,dwconv layer都能量化了。

**Comment by Enshall** [comment]
Hi @BUG1989 毛毛虫大侠
我想请教下，我看ncnn2int8里面目前也支持fc的量化，而且方法与conv一致，请问是这样吗？fc层的量化带来的精度损失大吗？
非常感谢！

**Comment by nihui** [comment]
int8 任意卷积核都支持
https://zhuanlan.zhihu.com/p/370689914
20210507版本大幅优化int8推理速度，建议更新
