### ISSUE TITLE
How to use the tensorflow2ncnn to convert the tensorflow model?

### ISSUE THREAD

**Issue by ljdang** [Tencent/ncnn#73]
可以编译tensorflow2ncnn工具，但是用它来转换模型的时候貌似没有生成ncnn可用的模型？

**Comment by nihui** [comment]
正在实现中呢

**Comment by ljdang** [comment]
@nihui 明白了，多谢

**Comment by ddxu** [comment]
@nihui 感谢你的工作。我在VS2015中用你最近更新的tensorflow2ncnn.cpp试图转换一个我自己frozen之后tensorflow模型（.pb，模型由tf 1.0训练得到），但失败了。错误出现在下面代码的“int kernel_size_h = shape.dim(0).size()”这一行，提示越界。 调试可看到， “find_tensor_proto” 函数是返回true的，但是“tensor.tensor_shape()"得到的shape的维度为0，以至于在下一行出现越界错误。shape的dim size为0，是我的frozen model有问题吗？还是代码转换的一些bug呢？可以确保的是我的frozen model在python接口和c++接口下都是可以正常加载并使用的。期待您的指点~
`else if (node.op() == "Conv2D")
		{
			// weights
			tensorflow::TensorProto tensor;
		        find_tensor_proto(weights, node, tensor);

			const tensorflow::TensorShapeProto& shape = tensor.tensor_shape();


			int kernel_size_h = shape.dim(0).size();
			int kernel_size_w = shape.dim(1).size();
			int num_input = shape.dim(2).size();
			int num_output = shape.dim(3).size();
`

**Comment by nihui** [comment]
@ddxu  大概修好crash了...
https://github.com/Tencent/ncnn/commit/c9af14b70e0f5a5d399ee91619b3e78cae8e09d8
