### ISSUE TITLE
ncnn是不是对arm64-v8a的支持不太好？

### ISSUE THREAD

**Issue by dancingpipi** [Tencent/ncnn#730]
同样的模型，在armeabi-v7a的安卓机上能得到和PC上一样的结果，但是在arm64的机器上得到的结果与PC上有较大的误差，有人遇到过这样的问题吗？

**Comment by helloearth012** [comment]
@z13974509906  可以贴一下你的结果吗 或者 你已经找到加速的办法了吗？ 我的测试结果，arm64也比较慢，在查是不是arm64的原因。

**Comment by jliangqiu** [comment]
@z13974509906 请问解决了吗？我也遇到了这样的问题，在arm64-v8a使用mtcnn中的pnet可以出结果，rnet结果始终都是空的，而armeabi-v7a的安卓机上可以出来
