### ISSUE TITLE
fatal error: net.h: No such file or directory  #include "net.h"

### ISSUE THREAD

**Issue by DaojuCV2017** [Tencent/ncnn#731]
请问在树莓上编译时，找不到"net.h"头文件，怎么解决呢？谢谢！

**Comment by DaojuCV2017** [comment]
经过高人指点，在编译ncnn后，最后忘了make install这一步！如果还有问题，注意头文件路径就ok了，现已解决！

**Comment by KeepGoing2019HaHa** [comment]
@DaojuCV2017 求问下怎么添加头文件呢？我执行了make install，也把src/目录加到includ path，还是报错找不到net.h

**Comment by ZX-lang** [comment]
> @DaojuCV2017 求问下怎么添加头文件呢？我执行了make install，也把src/目录加到includ path，还是报错找不到net.h

老哥请问问题解决了吗

**Comment by YandongJi** [comment]
Maybe try this: "export ncnn_DIR=YOUR_NCNN_PATH/src/CMakeFiles/Export/lib/cmake/ncnn"
