### ISSUE TITLE
20181224版本，无法读入转换后的模型的问题。

### ISSUE THREAD

**Issue by ningxiner1001** [Tencent/ncnn#732]
template<typename T> bool readValue(T & val, FILE * fp)
{
    size_t res = fread(&val, sizeof(T), 1, fp);
    if (res != sizeof(T)) {
        fprintf(stderr, "issue with param file reading\n");
        return false;
    }
    return true;
}

int Net::load_param_bin(FILE* fp)
{
    int magic = 0;
    if (!readValue(magic, fp))
        return -1;
    if (magic != 7767517)
    {
        fprintf(stderr, "param is too old, please regenerate\n");
        return -1;
    }
...
}

上述代码中以下是否有问题，res=1，sizeof(T)=4，return false，导致模型无法读入，@nihui 求帮助。
   size_t res = fread(&val, sizeof(T), 1, fp);
    if (res != sizeof(T)) {
        fprintf(stderr, "issue with param file reading\n");
        return false;
    }

**Comment by nihui** [comment]
真是个 bug ...

**Comment by nihui** [comment]
已重新tag发布新版本 :)

**Comment by ningxiner1001** [comment]
谢谢大神，向大神学习！
