### ISSUE TITLE
mxnet2ncnn reduction层 缺少 'axis' 参数

### ISSUE THREAD

**Issue by zy3830zeng** [Tencent/ncnn#739]
mxnet2ncnn转换工具ln 1850:  fprintf(pp, " 0=%d", operation); 只提供了操作类型，
而reduction.cpp ln 35: dim = pd.get(1, 0); 需要的dim参数未开放。
对应json:
    {
      "op": "mean", 
      "name": "stage5_2_expandedconv20_cbam_mean0", 
      "attrs": {
        "axis": "1", 
        "keepdims": "True"
      }, 
      "inputs": [[423, 0, 0]]
    },

**Comment by zy3830zeng** [comment]
补充：'keepdims'参数也没有生效，reduction之后dims从3变为2了。

**Comment by z13974509906** [comment]
> 补充：'keepdims'参数也没有生效，reduction之后dims从3变为2了。

ncnn会把batchsize这维直接删除，比如原来是b*h*w*c，现在变成了h*w*c（ncnn::Mat的顺序是w*h*c）

**Comment by z13974509906** [comment]
![image](https://user-images.githubusercontent.com/20511825/50671603-d83ce700-100d-11e9-8d59-bcefc7cb0600.png)

你可以根据这个来手动修改网络参数dim

不过这个地方有个bug：
https://github.com/Tencent/ncnn/blob/b75516b9b179a97f0b0f470c986b2cfec8fa675f/src/layer/reduction.cpp#L138
当dim=2时，需要把这里的i修改为j

**Comment by zy3830zeng** [comment]
> 
> 
> > 补充：'keepdims'参数也没有生效，reduction之后dims从3变为2了。
> 
> ncnn会把batchsize这维直接删除，比如原来是b_h_w_c，现在变成了h_w_c（ncnn::Mat的顺序是w_h*c）

感谢答复！我在用concat拼接前两层（mean和max）时结果的dims不正常才发现的这个问题，希望能够增加维度保留的参数项！

**Comment by nihui** [comment]
> ![image](https://user-images.githubusercontent.com/20511825/50671603-d83ce700-100d-11e9-8d59-bcefc7cb0600.png)
> 
> 你可以根据这个来手动修改网络参数dim
> 
> 不过这个地方有个bug：
> 
> [ncnn/src/layer/reduction.cpp](https://github.com/Tencent/ncnn/blob/b75516b9b179a97f0b0f470c986b2cfec8fa675f/src/layer/reduction.cpp#L138)
> 
> Line 138 in [b75516b](/Tencent/ncnn/commit/b75516b9b179a97f0b0f470c986b2cfec8fa675f)
>  sum = op(sum, ptr[i]); 
> 
> 当dim=2时，需要把这里的i修改为j

fixed in https://github.com/Tencent/ncnn/commit/d9301c4f59fa3854db01d0536ebf9842be85404c

**Comment by nihui** [comment]
axis and keepdims attribute conversion implemented
