### ISSUE TITLE
Permute支持 “order0 != 0”的情况吗

### ISSUE THREAD

**Issue by ppl21847** [Tencent/ncnn#740]
caffe2ncnn的源码中，关于Permute层的转换中只有order0 == 0，的情况支持下面这种情况吗？
layer {
  name: "conv_t0_4_permute"
  type: "Permute"
  bottom: "conv_t0_4"
  top: "conv_t0_4_permute"
  permute_param {
    order: 3
    order: 0
    order: 2
    order: 1
  }
}

**Comment by z13974509906** [comment]
经过我的实验，是支持的

**Comment by nihui** [comment]
第一个 order 表示 N，ncnn 数据结构只有3维，不支持跨 N 的 permute
