### ISSUE TITLE
tensorflow tool

### ISSUE THREAD

**Issue by xhzzhang** [Tencent/ncnn#745]
在tools/CMakeLists.txt 添加tensorflow 的编译后，遇到下面的错误：

ersions.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
tools/tensorflow/CMakeFiles/tensorflow2ncnn.dir/build.make:134: recipe for target 'tools/tensorflow/versions.pb.cc' failed
make[2]: *** [tools/tensorflow/versions.pb.cc] Error 1
CMakeFiles/Makefile2:371: recipe for target 'tools/tensorflow/CMakeFiles/tensorflow2ncnn.dir/all' failed
make[1]: *** [tools/tensorflow/CMakeFiles/tensorflow2ncnn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[ 68%] Built target ncnn
[ 70%] Built target ncnn2mem
[ 73%] Built target caffe2ncnn
[ 75%] Built target mxnet2ncnn
[ 79%] Built target onnx2ncnn
[ 80%] Running C++ protocol buffer compiler on versions.proto
versions.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
tools/tensorflow/CMakeFiles/tensorflow2ncnn.dir/build.make:134: recipe for target 'tools/tensorflow/versions.pb.cc' failed
make[2]: *** [tools/tensorflow/versions.pb.cc] Error 1
CMakeFiles/Makefile2:371: recipe for target 'tools/tensorflow/CMakeFiles/tensorflow2ncnn.dir/all' failed
make[1]: *** [tools/tensorflow/CMakeFiles/tensorflow2ncnn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/issues/5
