### ISSUE TITLE
size_t issue in func. load_param_bin 

### ISSUE THREAD

**Issue by harhar539** [Tencent/ncnn#747]
In func. **load_param_bin** at net.cpp, readValue is used to get value of param as the follows:
`size_t layer_count = 0;
if (!readValue(layer_count, fp))
        return -1;`
**These codes doesn't get the correct lenth of param value**. Since in 64bit system, size_t means 8 bytes. But the params in param.bin are all dumped in 4 bytes format (int type) by ncnn2mem.
Thus in 64 bit platform, program will crash while loading param.bin.

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/a577d71c1215f708250ca5459e97c32b082f17f4
fix, first try

**Comment by harhar539** [comment]
Verified, many thx!
