### ISSUE TITLE
Android/IOS 内存问题

### ISSUE THREAD

**Issue by Justin-bin** [Tencent/ncnn#752]
初始化ncnn模型后，应用会持有大概70M内存，无法释放。（包括detele net ） 请问你们有碰到这种类似的情况吗？

**Comment by nihui** [comment]
是否有使用 allocator 内存池？

**Comment by Justin-bin** [comment]
目前没有使用到allocator

**Comment by Justin-bin** [comment]
目前也使用到 UnlockedPoolAllocator  和  PoolAllocator 
在Destroy 的时候也         g_blob_pool_alloctator.clear();    g_ws_pool_alllocator.clear();    但是70M内存并没有减少。释放不掉。

**Comment by nihui** [comment]
delete 内存池，操作系统可能会短暂保留
