### ISSUE TITLE
onnx：ncnn Upsample not supported yet!   # mode=nearest

### ISSUE THREAD

**Issue by dianxin556** [Tencent/ncnn#753]
I have an onnx model with Upsample layer, and got error like above. what can i do to solve it ? Thanks!

**Comment by 1976277169** [comment]
顶一下，防沉~~~

**Comment by gemfield** [comment]
Upsample op is popular in segmentation network.

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
