### ISSUE TITLE
Will it be faster using winograd for 3x3s1 than normal ?

### ISSUE THREAD

**Issue by XiaochaoGONG** [Tencent/ncnn#754]
Hi, how much faster using winograd for 3x3s1 with certain conditions e.g. channel >= 16, in_w <= 120, etc. than using normal convolution operations ? Suppose both are in the arm environment.

**Comment by nihui** [comment]
that is experiential condition, the sppedup ratio may vary between operating system and hardware. you'd better benchmarking that by yourself.
