### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7337800000 in tid 7052 (cedetectiondemo), pid 7052 (cedetectiondemo)

### ISSUE THREAD

**Issue by wuyajun0627** [Tencent/ncnn#758]
NCNN，你们好！我在使用PCN-ncnn进行人脸角度识别的时候，应用停止相应了，log如下。烦请帮忙指点一下！谢谢

Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7337800000 in tid 7052 (cedetectiondemo), pid 7052 (cedetectiondemo)
01-17 16:17:34.634  7331  7331 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-17 16:17:34.635  7331  7331 F DEBUG   : Build fingerprint: 'Hisense/HLTE215T/HSSDM429QC:8.1.0/OPM1.171019.026/L1574.6.01.01:user/release-keys'
01-17 16:17:34.635  7331  7331 F DEBUG   : Revision: '0'
01-17 16:17:34.635  7331  7331 F DEBUG   : ABI: 'arm64'
01-17 16:17:34.635  7331  7331 F DEBUG   : pid: 7052, tid: 7052, name: cedetectiondemo  >>> com.hmct.wuyajun.pcn_facedetectiondemo <<<
01-17 16:17:34.635  7331  7331 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7337800000
01-17 16:17:34.635  7331  7331 F DEBUG   :     x0   0000000000000000  x1   00000073377ffe80  x2   0000000000000048  x3   0000000000000040
01-17 16:17:34.635  7331  7331 F DEBUG   :     x4   0000007357d76dd0  x5   00000073377fff40  x6   000000734c6d8760  x7   000000734c6d881e
01-17 16:17:34.635  7331  7331 F DEBUG   :     x8   0000000000000017  x9   0000000000000009  x10  0000000000000048  x11  0000000000000018
01-17 16:17:34.635  7331  7331 F DEBUG   :     x12  0000000000000018  x13  0000007357d801d0  x14  0000000000000000  x15  00000000000000c0
01-17 16:17:34.635  7331  7331 F DEBUG   :     x16  000000000000000a  x17  0000000100000000  x18  000000000000008a  x19  0000000000000018
01-17 16:17:34.635  7331  7331 F DEBUG   :     x20  0000000100000000  x21  00000000000000ba  x22  000000734c6d8700  x23  00000000000000ba
01-17 16:17:34.635  7331  7331 F DEBUG   :     x24  00000000000000b2  x25  0000007357d8026c  x26  000000734c6d8760  x27  000000734c6d887c
01-17 16:17:34.635  7331  7331 F DEBUG   :     x28  0000007357d76e6c  x29  0000007ff25690f0  x30  000000733afc372c
01-17 16:17:34.635  7331  7331 F DEBUG   :     sp   0000007ff2569060  pc   000000733afc38b8  pstate 0000000020000000
01-17 16:17:34.640  7331  7331 F DEBUG   : 
01-17 16:17:34.640  7331  7331 F DEBUG   : backtrace:
01-17 16:17:34.640  7331  7331 F DEBUG   :     #00 pc 00000000000b38b8  /data/app/com.hmct.wuyajun.pcn_facedetectiondemo-wBVmNkUFr-uJaXzMZuBrng==/lib/arm64/libface_angle_detection.so
01-17 16:17:34.640  7331  7331 F DEBUG   :     #01 pc 00000000000b5c28  /data/app/com.hmct.wuyajun.pcn_facedetectiondemo-wBVmNkUFr-uJaXzMZuBrng==/lib/arm64/libface_angle_detection.so
01-17 16:17:34.640  7331  7331 F DEBUG   :     #02 pc 00000000000a3924  /data/app/com.hmct.wuyajun.pcn_facedetectiondemo-wBVmNkUFr-uJaXzMZuBrng==/lib/arm64/libface_angle_detection.so (Impl::Stage2(cv::Mat, cv::Mat, ncnn::Net&, float, int, std::vector<Window2, std::allocator, <Window2>>&)+1008)
01-17 16:17:34.640  7331  7331 F DEBUG   :     #03 pc 00000000000a1b34  /data/app/com.hmct.wuyajun.pcn_facedetectiondemo-wBVmNkUFr-uJaXzMZuBrng==/lib/arm64/libface_angle_detection.so (PCN::DetectFace(cv::Mat)+592)
01-17 16:17:34.640  7331  7331 F DEBUG   :     #04 pc 00000000000a70cc  /data/app/com.hmct.wuyajun.pcn_facedetectiondemo-wBVmNkUFr-uJaXzMZuBrng==/lib/arm64/libface_angle_detection.so (Java_com_example_facedetectionlibrary_FaceAngleDetectionUtils_faceAngleDetect+720)
01-17 16:17:34.640  7331  7331 F DEBUG   :     #05 pc 00000000000090e4  /data/app/com.hmct.wuyajun.pcn_facedetectiondemo-wBVmNkUFr-uJaXzMZuBrng==/oat/arm64/base.odex (offset 0x9000)
--------- beginning of system
01-17 16:18:02.416  7230  7230 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:997 android.content.ContextWrapper.sendBroadcast:442 com.tencent.mm.sdk.channel.MMessage.send:62 com.tencent.mm.sdk.channel.MMessage.send:1 com.tencent.mm.sdk.openapi.WXApiImplV10.registerApp:66 
01-17 16:18:02.417   835   924 I chatty  : uid=1000(system) ActivityManager expire 3 lines
01-17 16:18:02.428   835  2822 I chatty  : uid=1000(system) Binder:835_12 expire 273 lines
01-17 16:18:02.432   835  6807 I chatty  : uid=1000(system) Binder:835_1B expire 1 line
01-17 16:18:02.433   835  2855 I chatty  : uid=1000(system) Binder:835_16 expire 308 lines
01-17 16:18:02.448   835  2822 I chatty  : uid=1000(system) Binder:835_12 expire 28 lines

**Comment by wuyajun19900627** [comment]
01-16 16:54:33.496 14807 14807 F DEBUG : Build fingerprint: 'Hisense/HLTE510T/HSSDM636QC:8.1.0/OPM1.171019.026/L1511.6.01.02:user/release-keys'
01-16 16:54:33.496 14807 14807 F DEBUG : Revision: '0'
01-16 16:54:33.496 14807 14807 F DEBUG : ABI: 'arm64'
01-16 16:54:33.496 14807 14807 F DEBUG : pid: 10918, tid: 14789, name: ProcessingDualC >>> com.android.gallery3d <<<
01-16 16:54:33.496 14807 14807 F DEBUG : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x70b8400000
01-16 16:54:33.496 14807 14807 F DEBUG : x0 0000000000000000 x1 00000070b83ffe80 x2 0000000000000048 x3 0000000000000040
01-16 16:54:33.496 14807 14807 F DEBUG : x4 00000070bd0e4f50 x5 00000070b83fff40 x6 00000070bd03ed60 x7 00000070bd03ee1e
01-16 16:54:33.496 14807 14807 F DEBUG : x8 0000000000000017 x9 0000000000000009 x10 0000000000000048 x11 0000000000000018
01-16 16:54:33.496 14807 14807 F DEBUG : x12 0000000000000018 x13 00000070bcc72010 x14 0000000000000000 x15 00000000000000c0
01-16 16:54:33.496 14807 14807 F DEBUG : x16 000000000000000a x17 0000000100000000 x18 000000000000008a x19 0000000000000018
01-16 16:54:33.496 14807 14807 F DEBUG : x20 0000000100000000 x21 00000000000000ba x22 00000070bd03ed00 x23 00000000000000ba
01-16 16:54:33.496 14807 14807 F DEBUG : x24 00000000000000b2 x25 00000070bcc720ac x26 00000070bd03ed60 x27 00000070bd03ee7c
01-16 16:54:33.496 14807 14807 F DEBUG : x28 00000070bd0e4fec x29 00000070a6e0ea50 x30 00000070b8d2b264
01-16 16:54:33.496 14807 14807 F DEBUG : sp 00000070a6e0e9c0 pc 00000070b8d2b3f0 pstate 0000000020000000
01-16 16:54:33.507 14807 14807 F DEBUG : 
01-16 16:54:33.507 14807 14807 F DEBUG : backtrace:
01-16 16:54:33.508 14807 14807 F DEBUG : #00 pc 000000000009f3f0 /system/priv-app/Vision_Gallery/lib/arm64/libface_angle_detection.so (ncnn::resize_bilinear_c3(unsigned char const*, int, int, unsigned char*, int, int)+1112)
01-16 16:54:33.508 14807 14807 F DEBUG : #01 pc 00000000000a1760 /system/priv-app/Vision_Gallery/lib/arm64/libface_angle_detection.so (ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int)+184)
01-16 16:54:33.508 14807 14807 F DEBUG : #02 pc 000000000009592c /system/priv-app/Vision_Gallery/lib/arm64/libface_angle_detection.so (Impl::Stage2(cv::Mat, cv::Mat, ncnn::Net&, float, int, std::vector<Window2, std::allocator, <Window2>>&)+1312)
01-16 16:54:33.508 14807 14807 F DEBUG : #03 pc 000000000009269c /system/priv-app/Vision_Gallery/lib/arm64/libface_angle_detection.so (PCN::DetectFace(cv::Mat)+1584)
01-16 16:54:33.508 14807 14807 F DEBUG : #04 pc 0000000000099e34 /system/priv-app/Vision_Gallery/lib/arm64/libface_angle_detection.so (Java_com_example_facedetectionlibrary_FaceAngleDetectionUtils_faceAngleDetect+856)
01-16 16:54:33.508 14807 14807 F DEBUG : #05 pc 0000000000026614 /system/priv-app/Vision_Gallery/oat/arm64/Vision_Gallery.odex (offset 0x20000)

**Comment by wuyajun19900627** [comment]
@nihui 您好，能帮忙看一下这个问题吗，谢谢

**Comment by nihui** [comment]
看堆栈信息，似乎是因为你的抠图区域超出了图像边界...
具体你得找个重现问题的图调试下
