### ISSUE TITLE
android上测试ssd mobilenet输出结果总是为0

### ISSUE THREAD

**Issue by huangsiyuzhoujie** [Tencent/ncnn#760]
@nihui 你好，我按照https://github.com/chehongshu/ncnnforandroid_objectiondetection_Mobilenetssd 这个里面的自己做了一遍，然后在pc上使用未加密的文件测试的时候没有问题，然后我使用这个android工程，然后将里面的文件替换成自己生成的文件之后，识别结果就一直为0，不知道哪里出问题了，谢谢。

**Comment by bryanlinnan** [comment]
@huangsiyuzhoujie ，你好，我下问一下你有用过NCNN的模型转换工具把caffe版本的Mobilenet SSD转换成功后使用吗？我可以转换出ncnn的模型，但是使用就会报错，应该是模型转换问题，因为使用ncnnforandroid_objectiondetection_Mobilenetssd工程里提供的就可以正常使用

**Comment by huangsiyuzhoujie** [comment]
> @huangsiyuzhoujie ，你好，我下问一下你有用过NCNN的模型转换工具把caffe版本的Mobilenet SSD转换成功后使用吗？我可以转换出ncnn的模型，但是使用就会报错，应该是模型转换问题，因为使用ncnnforandroid_objectiondetection_Mobilenetssd工程里提供的就可以正常使用

转换成功了，一个.param文件一个.bin文件，然后在pc上测试没有问题

**Comment by bryanlinnan** [comment]
> > @huangsiyuzhoujie ，你好，我下问一下你有用过NCNN的模型转换工具把caffe版本的Mobilenet SSD转换成功后使用吗？我可以转换出ncnn的模型，但是使用就会报错，应该是模型转换问题，因为使用ncnnforandroid_objectiondetection_Mobilenetssd工程里提供的就可以正常使用
> 
> 转换成功了，一个.param文件一个.bin文件，然后在pc上测试没有问题

我这边转换的时候就不正常，会报Segmentation fault      (core dumped)，模型虽然能出来，但是不能用

**Comment by huangsiyuzhoujie** [comment]
> > > @huangsiyuzhoujie ，你好，我下问一下你有用过NCNN的模型转换工具把caffe版本的Mobilenet SSD转换成功后使用吗？我可以转换出ncnn的模型，但是使用就会报错，应该是模型转换问题，因为使用ncnnforandroid_objectiondetection_Mobilenetssd工程里提供的就可以正常使用
> > 
> > 
> > 转换成功了，一个.param文件一个.bin文件，然后在pc上测试没有问题
> 
> 我这边转换的时候就不正常，会报Segmentation fault (core dumped)，模型虽然能出来，但是不能用，不知道能不能分享一下你的mobilenetssd caffe模型，我试下是不是我的模型问题，[linnansuda@163.com](mailto:linnansuda@163.com)，谢谢

你是需要什么 ，转换成功之后的param 和bin文件吗？

**Comment by bryanlinnan** [comment]
我想要你的caffe mobilenetSSD模型，然后我这边试下能不能转换成功，另外我想问一下你转换过的模型跑出来的结果对吗？我这边用转换工具转出来的模型跑分类都不正确

**Comment by Roger8** [comment]
> > @huangsiyuzhoujie "> 转换成功了，一个.param文件一个.bin文件，然后在pc上测试没有问题"
在pc上测试的代码怎么引用ncnn库呢？请指教

**Comment by nihui** [comment]
我把 mobilenetssd 转换后的模型上传到这里 https://github.com/nihui/ncnn-assets/tree/master/models
已使用ncnnoptimize工具优化并用fp16存储

**Comment by 201677I0318** [comment]
您好，我也有同样的问题，请问您是怎么解决的？
