### ISSUE TITLE
mobilenet ssd 模型转换

### ISSUE THREAD

**Issue by bryanlinnan** [Tencent/ncnn#761]
我在使用mobilenet ssd caffe版本模型转换的时候，虽然可以转换出ncnn的模型，但是log信息里有
16169 Segmentation fault      (core dumped) ，而且测试程序加载模型的时候会报错，请问是ncnn版本问题吗？还是caffe版本的mobilenetssd有问题？

**Comment by liushuan** [comment]
depthwiseconvolution? 是不是在 ncnn 里面没有？

**Comment by liushuan** [comment]
@nihui

**Comment by nihui** [comment]
> depthwiseconvolution? 是不是在 ncnn 里面没有？

depthwiseconvolution是支持的
