### ISSUE TITLE
VS2017 build fails

### ISSUE THREAD

**Issue by Mut1nyJD** [Tencent/ncnn#762]
Problem seems to be building caffe2ncnn and onnx2ncnn because of the google protobuf. According to the instructions on the Wiki you'll get a link error right away because it still will build protobuf as static library if you use cmake-gui and change the options to set shared library on it passes that but then you get link failures later with Unresolved external symbol google::protobuf::io::CodedInputStream:default_recursion_limit and
Unresolved external symbol google:protobuff:internal::ExplicitlyConstructed<......

**Comment by kalcohol** [comment]
if u do not need share protobuf.dll to another app, static linked lib will be a good way to cut down size of app.

so static link is recommended.

**Comment by nihui** [comment]
building protobuf as static library shall solve the issue
