### ISSUE TITLE
Better not delete "-g" in android.toolchain.cmake when building android Release version.

### ISSUE THREAD

**Issue by GaussRieman** [Tencent/ncnn#766]
When building android static lib, we will find the lib is nearly 10m in size. This is just because the "-g" option is set by default in android.toolchain.cmake. Of course we can delete it to get a lib without debug signals through this way, but we'd better not revise the default file in case you may need this option in other projects organized by cmake.

The better way to solve get out this situation is to set the CMAKE_CXX_FLAGS but not to append it. We can copy the options in android.toolchain.cmake to ensure the consistency.

1. delete the "${CMAKE_CXX_FLAGS}"
2. copy from android.toolchain.cmake list(APPEND ANDROID_COMPILER_FLAGS ...

set(CMAKE_CXX_FLAGS "-ffunction-sections \
	                     -funwind-tables \
	                    -fstack-protector-strong\
                            -no-canonical-prefixes \
                            -fno-rtti \
                            -fno-exceptions \
                            -Ofast")

After this, we can get the lib we need.

**Comment by nihui** [comment]
move to upstream issue https://github.com/android-ndk/ndk/issues/243

**Comment by hidoudou** [comment]
just forget the "-g" option, just use CMAKE_BUILD_TYPE=Release if you write your own build script.
if you build your AAR component using gradlew script, plz use Release build variant. when you got the right ndk version that work with agp, everything will be ok after stripReleaseDebugSymbols task is done.

that's all.
