### ISSUE TITLE
rk3288 speed can not match the benchmarklist. And multi-thread seems not work.

### ISSUE THREAD

**Issue by ZGAI** [Tencent/ncnn#771]
Hi, I have tested ncnn on rk3288 just now, But It seems the speed is much slower than benchmark list. And, it seems cost save time when thread changes from 1 -> 4. My environment is rk3288 with ubuntu16.04, I compiled the ncnn on rk3288 directly without cross-compile. Does anyone has some idea? 
<img width="649" alt="2019-01-26 11 17 04" src="https://user-images.githubusercontent.com/46375507/51789235-af011800-21c1-11e9-8ebc-2dacc1883144.png">
<img width="613" alt="2019-01-26 11 11 58" src="https://user-images.githubusercontent.com/46375507/51789236-b0cadb80-21c1-11e9-99ca-5853aef43b54.png">

**Comment by nihui** [comment]
try updating cmake 3.9 above to compile the latest code
prefer using clang over gcc
