### ISSUE TITLE
NCNN iOS 识别出的物体最大外边框的坐标能不能获取到？

### ISSUE THREAD

**Issue by yaoliangjun** [Tencent/ncnn#775]
如下图的红框是Android识别出的物体最大外边框，想知道iOS有什么方法可以获取到红框的坐标？
![1](https://user-images.githubusercontent.com/7575968/51955374-abe68000-247e-11e9-9ca8-69662915700e.jpg)

**Comment by nihui** [comment]
mobilenet-ssd 模型会给出这个框的坐标，ios android 一样

**Comment by yaoliangjun** [comment]
具体接口代码能告知一下不？

**Comment by nihui** [comment]
输出的结果处理代码可以参考例子
https://github.com/Tencent/ncnn/blob/master/examples/mobilenetssd.cpp

**Comment by yaoliangjun** [comment]
![1550543877062](https://user-images.githubusercontent.com/7575968/52988221-54ae4c80-3439-11e9-9389-63030d958a21.jpg)


我参考了mobilenetssd.cpp的代码，在断点的地方报错了，请问这是什么原因导致的呀？

**Comment by nihui** [comment]
ios上不能 imshow，你可以把图片存成jpg看效果

**Comment by yaoliangjun** [comment]
![1550737070574](https://user-images.githubusercontent.com/7575968/53153864-4ce6d780-35f4-11e9-821e-be8064eacdd6.jpg)

img_w=1024, img_h=727
8 = 0.65231 at 3.92 2.83 1014.89 x 722.07
cat 65.2%

大神你好，如上图片识别出的物体边框基本上等于图片的最大边框了，而不是图片里面的狗的外边框，图片的宽高 = 1024x727，但是识别出来的边框坐标是：x=3.92 y=2.83 w=1014.89 h=722.07
如果是正确识别出狗的边框，坐标不应该是这个数据的呀？请问是什么原因导致的呢？
