### ISSUE TITLE
permute 能转换batch 维度吗

### ISSUE THREAD

**Issue by phybrain** [Tencent/ncnn#776]
permute.cpp 只有转换 cwh 维度

**Comment by nihui** [comment]
ncnn 没有 batch，不能

**Comment by swithmn1** [comment]
如果caffe模型里permute 3,0,2,1，交换batch，转到ncnn应该怎么处理呢？

**Comment by nihui** [comment]
The ncnn batch infrastructure feature, which relies on the pnnx tool, is implemented at https://github.com/Tencent/ncnn/commit/127b4146148844ccf67a5bdcb0385e925aa13fbb
