### ISSUE TITLE
ndk-build 编译so文件错误

### ISSUE THREAD

**Issue by xisi789** [Tencent/ncnn#779]
报错信息如下：
xs@xs-HP-Pavilion-Power-Laptop-15-cb0xx:~/ncnn/examples/squeezencnn/jni$ ndk-build
Android NDK: android-9 is unsupported. Using minimum supported version android-14.    
Android NDK: WARNING: APP_PLATFORM android-14 is higher than android:minSdkVersion 1 in /home/xs/ncnn/examples/squeezencnn/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-14. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: WARNING: APP_STL gnustl_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    
Android NDK: ERROR:/home/xs/ncnn/examples/squeezencnn/jni/Android.mk:ncnn: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /home/nihui/osd/ncnn/ncnn-android-lib/armeabi-v7a/libncnn.a exists  or that its path is correct   
/home/xs/Android/Sdk/ndk-bundle/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
xs@xs-HP-Pavilion-Power-Laptop-15-cb0xx:~/ncnn/examples/squeezencnn/jni$ ndk-build
Android NDK: android-9 is unsupported. Using minimum supported version android-14.    
Android NDK: WARNING: APP_PLATFORM android-14 is higher than android:minSdkVersion 1 in /home/xs/ncnn/examples/squeezencnn/AndroidManifest.xml. NDK binaries will *not* be compatible with devices older than android-14. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
Android NDK: WARNING: APP_STL gnustl_static is deprecated and will be removed in the next release. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    
Android NDK: WARNING: Deprecated NDK_TOOLCHAIN_VERSION value: 4.9. GCC is no longer supported and will be removed in the next release. See https://android.googlesource.com/platform/ndk/+/master/docs/ClangMigration.md.    
[armeabi-v7a] Compile++ thumb: squeezencnn <= squeezencnn_jni.cpp
[armeabi-v7a] SharedLibrary  : libsqueezencnn.so
/home/xs/ncnn/src/mat.cpp:0: error: undefined reference to '__kmpc_fork_call'
/home/xs/ncnn/src/mat.cpp:37: error: undefined reference to '__kmpc_for_static_init_4'
/home/xs/ncnn/src/mat.cpp:36: error: undefined reference to '__kmpc_for_static_fini'
/home/xs/ncnn/src/mat.cpp:103: error: undefined reference to '__kmpc_for_static_init_4'
/home/xs/ncnn/src/mat.cpp:102: error: undefined reference to '__kmpc_for_static_fini'
/home/xs/ncnn/src/mat.cpp:169: error: undefined reference to '__kmpc_for_static_init_4'
/home/xs/ncnn/src/mat.cpp:168: error: undefined reference to '__kmpc_for_static_fini'
/home/xs/ncnn/src/mat.cpp:410: error: undefined reference to '__kmpc_global_thread_num'
/home/xs/ncnn/src/mat.cpp:438: error: undefined reference to '__kmpc_push_num_threads'
/home/xs/ncnn/src/mat.cpp:438: error: undefined reference to '__kmpc_fork_call'
/home/xs/ncnn/src/mat.cpp:439: error: undefined reference to '__kmpc_for_static_init_4'
/home/xs/ncnn/src/mat.cpp:438: error: undefined reference to '__kmpc_for_static_fini'
/home/xs/ncnn/src/mat.cpp:679: error: undefined reference to '__kmpc_global_thread_num'
/home/xs/ncnn/src/mat.cpp:705: error: undefined reference to '__kmpc_push_num_threads'
/home/xs/ncnn/src/mat.cpp:705: error: undefined reference to '__kmpc_fork_call'
/home/xs/ncnn/src/layer/arm/absval_arm.cpp:26: error: undefined reference to '__kmpc_global_thread_num'
/home/xs/ncnn/src/layer/arm/absval_arm.cpp:32: error: undefined reference to '__kmpc_push_num_threads'
/home/xs/ncnn/src/layer/arm/absval_arm.cpp:32: error: undefined reference to '__kmpc_fork_call'
/home/xs/ncnn/src/layer/arm/batchnorm_arm.cpp:26: error: undefined reference to '__kmpc_global_thread_num'
/home/xs/ncnn/src/layer/arm/batchnorm_arm.cpp:41: error: undefined reference to '__kmpc_push_num_threads'
/home/xs/ncnn/src/layer/convolutiondepthwise.cpp:374: error: undefined reference to '__kmpc_for_static_init_8'
/home/xs/ncnn/src/layer/convolutiondepthwise.cpp:475: error: undefined reference to '__kmpc_for_static_init_8'
/home/xs/ncnn/src/layer/deconvolutiondepthwise.cpp:160: error: undefined reference to '__kmpc_for_static_init_8'
collect2: error: ld returned 1 exit status
make: *** [/home/xs/ncnn/examples/squeezencnn/obj/local/armeabi-v7a/libsqueezencnn.so] Error 1
不明白这个错误是如何产生的以及要怎样解决，请各位大佬赐教

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error

**Comment by xisi789** [comment]
非常感谢您的及时回复！
