### ISSUE TITLE
issue of quantized int8 inference 

### ISSUE THREAD

**Issue by SecretGuardian** [Tencent/ncnn#781]
Hi thanks for the great work!
I generated squeezenet-int8 by using the squeezenet_v1_1.table in quantized int8 and the squeezenet_v1.1.bin and .param files provided by NCNN.

The size of new squeezenet-int8 went down to 1.2Mb, also it did work and produced the similar results of test images.

However when I use benchmark to test the 2 models on Macbook Pro, the original squeezenet took 138ms while the int8 model took 174ms.

The results of int8 model are as below:
...
64 {fire3/expand3x3, 5.022, 0.027} 1
65 {fire2/expand3x3, 5.486, 0.030} 1
66 {fire4/expand3x3, 5.709, 0.031} 1
67 {fire5/expand3x3, 5.712, 0.031} 1
68 {fire6/expand3x3, 6.511, 0.035} 1
69 {fire9/expand3x3, 8.201, 0.044} 1
70 {fire8/expand3x3, 8.300, 0.045} 1
71 {pool1, 8.631, 0.046} 1
72 {conv1, 21.531, 0.116} 1
73 {conv10, 59.041, 0.318} 1
sum=185.699 ms
795 = 0.195848
655 = 0.105379
608 = 0.061154
Program ended with exit code: 0

I checked the time for each layer, the time difference might caused by conv10, which took 24ms and 59ms in the original model and int8 model, respectively.

Can you please share your int8 model or give some hints about why did this happen? Thanks!

**Comment by nihui** [comment]
ncnn is mainly optimized for mobile platform (arm), the x86 code path is not well optimized.
If you deploy your model on arm platform, it will probably run faster.
