### ISSUE TITLE
ShuffleNetV2 example cannot reach the targeted accuracy in ImageNet?

### ISSUE THREAD

**Issue by WeiyiLi** [Tencent/ncnn#790]
I tried the ShuffleNetV2 in the example. However the accuracy is on ImageNet validation dataset is only around 32%. 

The link https://github.com/miaow1988/ShuffleNet_V2_pytorch_caffe shows that shufflenetv2_0.5x can reach 58.93%.

How I can make it reach the better accuracy? Thank you.

UPDATE: In https://github.com/Tencent/ncnn/blob/master/examples/shufflenetv2.cpp#L32, I change `PIXEL_BGR` to `PIXEL_BGR2RGB`, the accuracy can reach about 50%. Better but not enough...

**Comment by kalcohol** [comment]
can u try the model in the first link? compare both results to find the diff?

**Comment by WeiyiLi** [comment]
@kalcohol That is the one I was trying...
