### ISSUE TITLE
caffe2ncnn yolov3 报错

### ISSUE THREAD

**Issue by cmusjtuliuyuan** [Tencent/ncnn#791]
按照example里面https://github.com/Tencent/ncnn/blob/master/examples/yolov3.cpp#L34 下载了yolov3的caffe模型后。用caffe2ncnn转换报错
错误如下：
caffe2ncnn.exe yolov3.prototxt yolov3.caffemodel yolov3.param yolov3.bin
[libprotobuf ERROR D:\protobuf-3.4.0\src\google\protobuf\text_format.cc:288] Error parsing text-format caffe.NetParameter: 3343:20: Message type "caffe.LayerParameter" has no field named "upsample_param".
read_proto_from_text failed

**Comment by eric612** [comment]
抱歉，我後來有替換過upsample layer，需要使用舊版的prototxt
https://github.com/eric612/MobileNet-YOLO/blob/811c0f96de3e55dcfcb29613387222222db97ed3/models/darknet_yolov3/yolov3.prototxt

**Comment by nihui** [comment]
需要把 caffe upsample 转换到 ncnn interp ...

**Comment by cmusjtuliuyuan** [comment]
> 抱歉，我後來有替換過upsample layer，需要使用舊版的prototxt
> https://github.com/eric612/MobileNet-YOLO/blob/811c0f96de3e55dcfcb29613387222222db97ed3/models/darknet_yolov3/yolov3.prototxt

换成了这个yolov3.propotxt之后，确实能跑yolov3.cpp这个例子了，但是跑出来的预测结果不对。（相同图片mobilenet_yolo能预测对）。
是使用如下的caffemodel吗？https://github.com/Tencent/ncnn/blob/b392b1dbfc3fea7fff098ee8ea9a1c30682110eb/examples/yolov3.cpp#L37

**Comment by cmusjtuliuyuan** [comment]
> > 抱歉，我後來有替換過upsample layer，需要使用舊版的prototxt
> > https://github.com/eric612/MobileNet-YOLO/blob/811c0f96de3e55dcfcb29613387222222db97ed3/models/darknet_yolov3/yolov3.prototxt
> 
> 换成了这个yolov3.propotxt之后，确实能跑yolov3.cpp这个例子了，但是跑出来的预测结果不对。（相同图片mobilenet_yolo能预测对）。
> 是使用如下的caffemodel吗？
> 
> [ncnn/examples/yolov3.cpp](https://github.com/Tencent/ncnn/blob/b392b1dbfc3fea7fff098ee8ea9a1c30682110eb/examples/yolov3.cpp#L37)
> 
> Line 37 in [b392b1d](/Tencent/ncnn/commit/b392b1dbfc3fea7fff098ee8ea9a1c30682110eb)
> 
>  // https://drive.google.com/file/d/12nLE6GtmwZxDiulwdEmB3Ovj5xx18Nnh/view

可以跑起来了，需要更改如下行：https://github.com/Tencent/ncnn/blob/master/examples/yolov3.cpp#L55

const float mean_vals[3] = {0.0f, 0.0f, 0.0f};

**Comment by nihui** [comment]
yolov3.cpp 更新了下，注释里链接的模型可以跑

**Comment by gwestner94** [comment]
Hi @nihui I am facing the same issue, after using @eric612 's darknet2caffe converter to convert the official yolov3 model (not mobilenet yolov3). If I understand this correctly there are 2 solutions:

- Update the caffe2ncnn parser to convert upsample layer into interp layer in ncnn

- Modify the prototxt file in caffe to exchange upsample layer with Deconvolution

@eric612 Is there a retrain of the yolov3 model in caffe necessary?
@nihui did I understand this correctly? 
谢谢你们！
