### ISSUE TITLE
Add New layer, but not added to NCNN layer after compiled

### ISSUE THREAD

**Issue by nejyeah** [Tencent/ncnn#792]
I have implement a new layer in NCNN refer to https://github.com/Tencent/ncnn/wiki/how-to-implement-custom-layer-step-by-step.

I have done "DEFINE_LAYER_CREATOR(PriorBoxS)" in cpp file.
After ncnn re-compiled, there is no `PriorBoxS` layer in  "build/src/ layer_registry.h or layer_type_enum.h"

Besides, after transfering model based on `caffe2ncnn`, and run my test based on ncnn, errors as follows
```
layer PriorBoxS not exists or registered
network graph not ready
find_blob_index_by_name data failed
find_blob_index_by_name detection_out failed
```

**Comment by nihui** [comment]
try regenerating cmake cache

**Comment by nejyeah** [comment]
Hi, I have removed the build dir and re-compile again, still not register the new layer.

**Comment by nejyeah** [comment]
Okay, I get it. It seems that I have to add "ncnn_add_layer(PriorBoxS)" in CmakeLists.txt.
Or manually register the new layer "squeezenet.register_custom_layer("PriorBoxS", ncnn::PriorBoxS_layer_creator); " in the forward test program.

**Comment by zhoujinhai** [comment]
@nejyeah 你好，请问一下，我测试模型的时候出现以下错误
```c++
$ ./yolov3 ../test.bmp 
layer DarknetActivation not exists or registered
```
按照您的建议，在yolov3.cpp中添加
```
yolov3.register_custom_layer("DarknetActivation", ncnn::DarknetActivation_layer_creator);
```
但是编译时报错，您有好的建议吗？
```c++
yolov3.cpp:47:55: error: ‘DarknetActivation_layer_creator’ is not a member of ‘ncnn’
```

**Comment by hejunmingstrogner** [comment]
我用darknet2ncnn 转的模型过来，用的yolov3.app 编译之后，运行报错：layer DarknetActivation not exists or registered，这什么问题呢，是模型转换不正确吗？

**Comment by AIGirl10** [comment]
@nihui 

I followed the same documentation to register a layer.
1. Created mylayer.cpp and mylayer.h files
2. Followed the [documentation](https://github.com/Tencent/ncnn/wiki/how-to-implement-custom-layer-step-by-step) and put the sources code inside .cpp and .h files.
3. Then added `ncnn_add_layer(Mylayer)` line in the CMakeLists.txt file in the last. Still it is not showing me `Mylayer` layer in  "build/src/ layer_registry.h or layer_type_enum.h".

Can you please help ?
