### ISSUE TITLE
进不了ncnn QQ群

### ISSUE THREAD

**Issue by murdockhou** [Tencent/ncnn#793]
输入 `卷卷卷卷卷` 提示答案错误.
另外, 该如何实现tensorflow conv2d_transpose卷积操作?求救各位大佬

**Comment by kalcohol** [comment]
the answer i don't know now.
but now the working flow which from tf to ncnn will not work for a long time.
most ncnn user include nihui him self do not use tf, and do not know how to build this tool. 

pr is welcome.
