### ISSUE TITLE
实测树莓派3b的benchmark时间过长

### ISSUE THREAD

**Issue by ljpadam** [Tencent/ncnn#795]
mobilenet和mobilenetssd在树莓派3b上运行时间较reamde中的时间分别多了30ms和80ms，但是其他网络的运行时间基本正常。编译步骤和运行方式完全和指南中的一致，请问可能是什么原因造成mobilenet的运行时间过长？

下面是在树莓派3b上运行benchmark后的结果，
pi@raspberrypi:~/code/ncnn2/ncnn/build/benchmark $ ./benchncnn 8 4 0
loop_count = 8
num_threads = 4
powersave = 0
gpu_device = -1
      squeezenet  min =  102.85  max =  114.07  avg =  105.64
       **mobilenet  min =  188.02  max =  196.52  avg =  189.66**
    mobilenet_v2  min =  199.89  max =  219.67  avg =  204.00
      shufflenet  min =   72.04  max =   81.76  avg =   73.70
         mnasnet  min =  132.11  max =  144.29  avg =  134.11
 proxylessnasnet  min =  162.51  max =  174.80  avg =  167.04
       googlenet  min =  332.20  max =  376.71  avg =  349.60
        resnet18  min =  501.01  max =  543.74  avg =  523.46
         alexnet  min =  414.20  max =  478.88  avg =  452.09
           vgg16  min = 2453.36  max = 2549.59  avg = 2501.66
  squeezenet-ssd  min =  340.02  max =  354.93  avg =  346.49
   **mobilenet-ssd  min =  344.44  max =  377.71  avg =  356.27**
  mobilenet-yolo  min =  901.09  max =  950.96  avg =  927.55
mobilenet-yolov3  min =  777.89  max =  806.25  avg =  790.33

下面是benchmark中readme给出的结果
pi@raspberrypi:~ $ ./benchncnn 8 4 0
loop_count = 8
num_threads = 4
powersave = 0
      squeezenet  min =  108.66  max =  109.24  avg =  108.96
       **mobilenet  min =  151.78  max =  152.92  avg =  152.31**
    mobilenet_v2  min =  193.14  max =  195.56  avg =  194.50
      shufflenet  min =   91.41  max =   92.19  avg =   91.75
       googlenet  min =  302.02  max =  304.08  avg =  303.24
        resnet18  min =  411.93  max =  423.14  avg =  416.54
         alexnet  min =  275.54  max =  276.50  avg =  276.13
           vgg16  min = 1845.36  max = 1925.95  avg = 1902.28
  squeezenet-ssd  min =  313.86  max =  317.35  avg =  315.28
   **mobilenet-ssd  min =  262.91  max =  264.92  avg =  263.85**
  mobilenet-yolo  min =  638.73  max =  641.27  avg =  639.87

**Comment by nihui** [comment]
benchmark readme 是64位系统上跑的，你的是32位系统？

**Comment by ljpadam** [comment]
感谢回复，我是在树莓派官方的32位系统上运行的，请问你用的64位系统是从哪里下载的呢？

**Comment by nihui** [comment]
这个你自己找下吧，比如 https://wiki.ubuntu.com/ARM/RaspberryPi#arm64 ...

**Comment by JoeyZhu** [comment]
> benchmark readme 是64位系统上跑的，你的是32位系统？

除了64位，使用别的编译器会更快吗？快多少？
