### ISSUE TITLE
Caffe int 8 quantization, performance drop

### ISSUE THREAD

**Issue by WIll-Xu35** [Tencent/ncnn#798]
Hi all, I was trying to use the caffe-int-8-quantization tool given in the tutorial to convert a pretrained caffe model. The quantization and caffe2ncnn process can both finish without a single error or warning. However, when I try to load the model and do a single inference to test the performance, it can load the param file but not the bin file. It will throw a Segmentation_fault(core dumped) error when the code try to load the bin file.

The command I used for quantization is:
`python caffe-int8-convert-tool-dev-weight.py --proto=model.prototxt --model=model.caffemodel --mean 127.5 127.5 127.5 --norm=0.0078215 --images=./image_dir --output=model.table --group=1 --gpu=1`

The command I used for caffe2ncnn is:
`./caffe2ncnn model.prototxt model.caffemodel model.param model.bin 256 model.table`

Any idea what may have caused this problem?

**Comment by BUG1989** [comment]
@WIll-Xu35 
The master branch use old int8 implement,if you want to try the new quantize tool,please use my repo.[https://github.com/BUG1989/ncnn/tree/ncnn-pr](https://github.com/BUG1989/ncnn/tree/ncnn-pr)

**Comment by WIll-Xu35** [comment]
@BUG1989 

Oh my, you are literally everywhere:)

Just kidding, thank you so much for your help, I'll give it a try.

**Comment by WIll-Xu35** [comment]
@BUG1989 

Hi, I tested on your ncnn-pr branch, generate param and bin using the original caffe model and the table file. The generated param and bin files are exactly the same as before (both have the same checksum) and still raises the same error.

**Comment by BUG1989** [comment]
@WIll-Xu35
Can you show me your generated param？

**Comment by WIll-Xu35** [comment]
@BUG1989 sorry about the late reply.

https://drive.google.com/open?id=1PjrIXgszTTe62yWsFPBLRiMGsroAHPkP

All the model files are included in the google drive link, caffemodel, prototxt, table, param, bin files.

Thank you so much for your help.

**Comment by BUG1989** [comment]
@WIll-Xu35 
I have fixed the bug,please update the latest codes and try it again
[pr #811](https://github.com/Tencent/ncnn/pull/811)

**Comment by WIll-Xu35** [comment]
@BUG1989 

Thank you so much! It works now.

**Comment by BUG1989** [comment]
@WIll-Xu35 
Can you share the accuracy drop when using int8 inference.This will help us continue to optimize.
Thanks a lots.

**Comment by WIll-Xu35** [comment]
@BUG1989 

No problem. Once I get the results, I'll let you know.

**Comment by WIll-Xu35** [comment]
@BUG1989 

Hi, I've got the test results. It's not looking good and almost unusable. I'm wondering if I did something wrong during the whole process, especially the preprocess of the input.

My caffe model takes 3x112x112 RGB image inputs. In python, I generate input use:
```
image = cv2.imread(image_path)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image = np.transpose(image, (2, 0, 1))
image = image.astype('float')
image -= 127.5
image *= 0.0078125
```

In the caffe-int8-convert-tool-dev-weight.py, the caffe transformer does the preprocess, but I'm not sure about the result of it. Especially those two lines:
```
transformer.set_transpose('data', (2, 0, 1))
transformer.set_channel swap('data', (2, 1, 0))
```
comments says they both convert rgb to bgr, but I think the first should serve as np.transpose. So does network_prepare() function do exactly as I want? This is the first part that may lead to the bad result.

The next thing is during inference using the quantized ncnn model, the code I use is:
```
cv::Mat image = cv::imread(image_path);
ncnn:Mat in = ncnn::Mat::from_pixels(image, ncnn::Mat::PIXEL_BGR2RGB, img_w, img_h);
const float mean_vals[3] = { 127.5f, 127.5f, 127.5f };
const float norm_vals[3] = { 0.0078125f, 0.0078125f, 0.0078125f };
in.substract_mean_normalize(mean_vals, norm_vals);
```

I didn't do transpose because I'm not sure how to do it in ncnn::Mat. Even if I didn't do transpose, the model can accept my input of 112x112x3, so it seems ncnn flatten the input before actually feed to the model?  Do you have any idea how to transpose ncnn:Mat? It is likely after transpose the result can be better.

**Comment by WIll-Xu35** [comment]
I've checked caffe transformer, set_transpose should be transpose HWC to CHW. The comment in the original caffe directory was wrong and it was corrected in Feb 2018.

So it might be better if line 268 in caffe-int8-convert-tool-dev-weight.py is changed to "Set the order of dimensions, e.g. to convert OpenCV's HxWxC images into CxHxW.", which is the original comment in caffe.

**Comment by WIll-Xu35** [comment]
@BUG1989 

Hi, I applied transpose to every input image using the function given on ncnn repo:

```
void transpose(const ncnn::Mat& in, ncnn::Mat& out)
{
    ncnn::Layer* op = ncnn::create_layer("Permute");

    // set param
    ncnn::ParamDict pd;
    pd.set(3, 0);// order_type, transform hwc to chw

    op->load_param(pd);

    // forward
    op->forward(in, out);

    delete op;
}
```

And I use this ncnn::Mat& out as the input to the model. However, the generated output is exactly the same as before. Not sure what is wrong with this function.

My network is a modified mobilefacenet with some res blocks. After quantization, the accuracy on my private dataset dropped from 99.7 to 96.2. The worst part is that false positive and false negative always exist at the same time (The original accuracy of 99.7 is acquired while there is no false positive).

According to the results from your git repo, smaller models like mobilenet (my model size is 25mb) has very little or none performance drop after quantization. So there must be something wrong during the quantization, image preprocessing or caffe-to-ncnn transition.

**Comment by WIll-Xu35** [comment]
Tested both quantized model and original model using the same inference code, original model performs well and quantized model performs bad. So the problem should be the quantized model itself. Closing this issue and opening a new issue at [https://github.com/BUG1989/caffe-int8-convert-tools/issues/36]
