### ISSUE TITLE
deconvolution实现方式

### ISSUE THREAD

**Issue by ujsyehao** [Tencent/ncnn#799]
查看nccn关于deconvolution实现方式，采用**Input pixel * filter = output window，不同output window重合的部分使用sum叠加处理.** 如图
而caffe中deconv的forward使用的是普通conv的backward，请问这两者等价吗？
![329](https://user-images.githubusercontent.com/17454232/53394951-a3c92400-39db-11e9-83e0-14b3b30b930a.png)

**Comment by nihui** [comment]
ncnn deconvolution 是公式上的 naive 做法，caffe 是 gemm + col2im，结果一样的

**Comment by ujsyehao** [comment]
@nihui 你好，关于deconvolution有3个方法(自己整理)：

- tensorflow中，transpose2d()先对输入进行pad，再进行convolution，最后进行crop
- ncnn中，使用input pixel * filter = window，再对重合部分进行sum，最后crop，**请问ncnn使用的方法就是上图中的方法吗？**
- caffe中，使用gemm+col2im，**请问这个如何理解？为何结果一样，可以提供一些资料参考吗？**

**Comment by ujsyehao** [comment]
ncnn不支持tensorflow的deconvolution层，**请问如何修复这个bug?**

**Comment by ujsyehao** [comment]
@nihui 可以给一些建议吗？

**Comment by nihui** [comment]
ncnn 是你所提的第二种方式
我不会tensorflow，建议换caffe试试

**Comment by ujsyehao** [comment]
@nihui 谢谢大佬，大佬那你明白caffe到底是怎么运算的吗
