### ISSUE TITLE
make package error

### ISSUE THREAD

**Issue by NHZlX** [Tencent/ncnn#8]
the 
$ make
$ make install 
is good

but there is error when runing make package
log is :
`make: *** No rule to make target `package'.  Stop.`

**Comment by nihui** [comment]
library and header files will be installed in build/install dir
not necessary to execute make package

**Comment by NHZlX** [comment]
the lib compiled on mac is about 200k smaller than cross compiled on android，that's why

**Comment by akbarxie** [comment]
add Execute permissions to build.sh,just run build.sh,can bulid the project
