### ISSUE TITLE
请问ncnn的mat类是否有在channel方向的max操作

### ISSUE THREAD

**Issue by lzqcode** [Tencent/ncnn#800]
请问ncnn的mat类是否有在channel方向的max操作，比如segmentation任务，在最后softmax后shape是w*h*c，怎么在c方向取max，变成w*h的seg_map啊

**Comment by nihui** [comment]
Reduction, operation=max, dim=-2

https://github.com/Tencent/ncnn/blob/24f423b0c6791464d32a9b566754db6399c34da6/src/layer/reduction.cpp#L73
