### ISSUE TITLE
layer BatchNorm not exists or registered

### ISSUE THREAD

**Issue by nila101** [Tencent/ncnn#803]
网络是resnet101
交叉编译后在arm端跑，提示下面的错误：
layer BatchNorm not exists or registered
network graph not ready
ncnn是最新git clone下来的
是编译的问题，还是运行环境的问题呢？
谢谢！

**Comment by nihui** [comment]
BatchNorm 是内置的层，你是不是改过 CMakeLists.txt

**Comment by nila101** [comment]
@nihui tks!
应该是交叉编译编译链的问题，目标是fedora，用了aarch64-linux-gnu-。
