### ISSUE TITLE
ncnn支持inception_resnet吗？加载模型一直是-1

### ISSUE THREAD

**Issue by mhsszm** [Tencent/ncnn#804]

**Comment by nihui** [comment]
应该是支持的
caffe模型提供下？

**Comment by mhsszm** [comment]
怎么把模型发给你呢？

**Comment by nihui** [comment]
发转出来的param文件

**Comment by mhsszm** [comment]
上传到百度文库了，链接：https://pan.baidu.com/s/1sp6PJGL_E8s_SUvJVm2dRg 
提取码：9eh2

**Comment by nihui** [comment]
> 
> 
> 上传到百度文库了，链接：https://pan.baidu.com/s/1sp6PJGL_E8s_SUvJVm2dRg
> 提取码：9eh2

发 param 文件，不是 bin ...

**Comment by mhsszm** [comment]
链接：https://pan.baidu.com/s/1nQI4Cs9m1Z5Iwk1WxqNJHw 
提取码：ird1

**Comment by nihui** [comment]
dummydata层需要自定义注册下
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#layer-xyz-not-exists-or-registered

**Comment by mhsszm** [comment]
只有dummydata这一层吧...

**Comment by nihui** [comment]
看下stderr输出的东西
