### ISSUE TITLE
rnn

### ISSUE THREAD

**Issue by caohaitao** [Tencent/ncnn#812]
请问怎么把rnn的onnx模型转换成ncnn的模型？ncnn现在是否支持rnn？有没有相关文档？谢谢

**Comment by nihui** [comment]
ncnn不支持rnn

**Comment by nihui** [comment]
最新ncnn已支持rnn

针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
