### ISSUE TITLE
make -j报错，尝试更改过protoc版本（2.5,3.0,3.6）均报错

### ISSUE THREAD

**Issue by dzyjjpy** [Tencent/ncnn#814]
CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o:(.data.rel.ro._ZTVN5caffe15FillerParameterE[_ZTVN5caffe15FillerParameterE]+0xb8)：对‘google::protobuf::Message::SpaceUsedLong() const’未定义的引用
CMakeFiles/caffe2ncnn.dir/caffe.pb.cc.o:(.data.rel.ro._ZTVN5caffe12NetParameterE[_ZTVN5caffe12NetParameterE]+0xb8): more undefined references to `google::protobuf::Message::SpaceUsedLong() const' follow
collect2: error: ld returned 1 exit status
make[2]: *** [tools/caffe/caffe2ncnn] 错误 1
make[1]: *** [tools/caffe/CMakeFiles/caffe2ncnn.dir/all] 错误 2
make: *** [all] 错误 

请问大神，应该怎么解决？

**Comment by nihui** [comment]
重启系统，重新编译安装 protobuf > 2.6.1，然后再重启系统

**Comment by dzyjjpy** [comment]
好的，我试一下编译安装，谢谢大神

**Comment by dzyjjpy** [comment]
重新编译安装搞定啦，protocbuf编译安装也是好多坑o(╯□╰)o 
Thanks
