### ISSUE TITLE
ncnn后面会支持onnx中的Unsqueeze 、Shape 、Gather吗？

### ISSUE THREAD

**Issue by 1976277169** [Tencent/ncnn#816]

**Comment by 1976277169** [comment]
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
Slice not supported yet!
  # axes 7
  # ends 7
  # starts 7
Slice not supported yet!
  # axes 7
  # ends 7
  # starts 7
Slice not supported yet!
  # axes 7
  # ends 7
  # starts 7
Slice not supported yet!
  # axes 7
  # ends 7
  # starts 7
Slice not supported yet!
  # axes 7
  # ends 7
  # starts 7
Slice not supported yet!
  # axes 7
  # ends 7
  # starts 7

**Comment by zhyj3038** [comment]
同样的问题，研究中。。。  应该是支持，可能名字不一样而已

**Comment by 1976277169** [comment]
听大大说，这些操作不是标准的op，这些东西等价于Reshape啥的操作，请问方便加个企鹅一起交流吗？

**Comment by 1976277169** [comment]
> 同样的问题，研究中。。。 应该是支持，可能名字不一样而已

听大大说，这些操作不是标准的op，这些东西等价于Reshape啥的操作，请问方便加个企鹅一起交流吗？

**Comment by Junan007** [comment]
同样的问题。

**Comment by nihui** [comment]
试试看 daquexian 的优化工具，可以把这些op去掉
https://github.com/daquexian/onnx-simplifier

**Comment by xylcbd** [comment]
+1

**Comment by borninfreedom** [comment]
> 试试看 daquexian 的优化工具，可以把这些op去掉 https://github.com/daquexian/onnx-simplifier

一直在使用，竟然没有看过这个仓库。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
