### ISSUE TITLE
BinaryOp在gpu上与cpu结果不一致

### ISSUE THREAD

**Issue by hux999** [Tencent/ncnn#817]
我将torchvision的resnet用onnx成功转化到ncnn(不包含fc曾)。但是残差连接中的BinaryOp用gpu跑的结果与cpu的不一致。验证后cpu的结果是没问题的。附件是对应的计算图文件。
[resnet.txt](https://github.com/Tencent/ncnn/files/2936104/resnet.txt)

**Comment by nihui** [comment]
confirmed

**Comment by hgj3804278** [comment]
我跑的网络也存在这个问题：用cpu运行网络结果是正确的，开启Vulkan的Gpu结果就不正确了，请问你的问题解决了吗？

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
