### ISSUE TITLE
jni里面的squeezenet_v1.1.id.h定义的变量是如何赋值的？

### ISSUE THREAD

**Issue by eeric** [Tencent/ncnn#82]
#ifndef NCNN_INCLUDE_GUARD_squeezenet_v1_1_id_h
#define NCNN_INCLUDE_GUARD_squeezenet_v1_1_id_h
namespace squeezenet_v1_1_param_id {
const int LAYER_data = 0;
const int BLOB_data = 0;
const int LAYER_conv1 = 1;
const int BLOB_conv1 = 1;
const int LAYER_relu_conv1 = 2;
const int BLOB_conv1_relu_conv1 = 2;
const int LAYER_pool1 = 3;
const int BLOB_pool1 = 3;
const int LAYER_fire2_squeeze1x1 = 4;
const int BLOB_fire2_squeeze1x1 = 4;
const int LAYER_fire2_relu_squeeze1x1 = 5;
const int BLOB_fire2_squeeze1x1_fire2_relu_squeeze1x1 = 5;
const int LAYER_splitncnn_0 = 6;
const int BLOB_fire2_squeeze1x1_fire2_relu_squeeze1x1_splitncnn_0 = 6;
const int BLOB_fire2_squeeze1x1_fire2_relu_squeeze1x1_splitncnn_1 = 7;
const int LAYER_fire2_expand1x1 = 7;
const int BLOB_fire2_expand1x1 = 8;
.......

这些变量如何命名和赋值的？

**Comment by nihui** [comment]
这个文件是通过 ncnn2mem 生成的

**Comment by eeric** [comment]
@nihui 感谢
