### ISSUE TITLE
Running efficiency gap on Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by YonghaoHe** [Tencent/ncnn#820]
I ran benchmark on Raspberry Pi 3 Model B+, and I get the following results:
![_20190307131241117](https://user-images.githubusercontent.com/28685653/53960239-b7356700-4120-11e9-829b-430125ddd068.jpg)
These results have a big gap compared to the offcial ones in ncnn/benchmark/README.md:
Raspberry Pi 3 Model B+ Broadcom BCM2837B0, Cortex-A53 (ARMv8) (1.4GHz x 4 )
loop_count = 8
num_threads = 4
powersave = 0
 squeezenet  min      =  108.66  max =  109.24  avg =  108.96
mobilenet  min         =  151.78  max =  152.92  avg =  152.31
mobilenet_v2  min    =  193.14  max =  195.56  avg =  194.50
shufflenet  min          =   91.41  max =   92.19  avg =   91.75
googlenet  min         =  302.02  max =  304.08  avg =  303.24
resnet18  min            =  411.93  max =  423.14  avg =  416.54
alexnet  min              =  275.54  max =  276.50  avg =  276.13
vgg16  min                = 1845.36  max = 1925.95  avg = 1902.28
squeezenet-ssd  min =  313.86  max =  317.35  avg =  315.28
mobilenet-ssd  min  =  262.91  max =  264.92  avg =  263.85
mobilenet-yolo  min =  638.73  max =  641.27  avg =  639.87

So, I wonder why this happened ? The detailed config is presented below:
system: ubuntu 18.04 64bit for raspberryPi (https://wiki.ubuntu.com/ARM/RaspberryPi,  ubuntu-18.04.2-preinstalled-server-arm64+raspi3.img.xz)
compile: cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-linux-gnu.toolchain.cmake ..  (I found cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/pi3.toolchain.cmake -DPI3=ON .. get compilation errors)

**Comment by BUG1989** [comment]
Please use clang compiler and try it again.

**Comment by YonghaoHe** [comment]
@BUG1989 I use clang 7.0 to recompile the code, and get the following results:
![_20190308090816---](https://user-images.githubusercontent.com/28685653/54019038-249ad380-41c5-11e9-8d50-5dff7f5560ea.jpg)
Indeed, the performance is better now. But there is still a gap. Moreover, the program prompted segmentation fault.

**Comment by nihui** [comment]
Please update to the latest ncnn code, and you will get a nice speed improvement with the new packing layout optimzation
