### ISSUE TITLE
make -j4报错，protobuf版本已更新为2.6.1

### ISSUE THREAD

**Issue by jiajiajun** [Tencent/ncnn#822]
求教各位大神，是否在make的时候遇到下面的问题？
/ncnn/src/mat.cpp:362:47: error: ‘Padding’ is not a member of ‘-LayerType’
     ncnn::Layer* padding = ncnn::create_layer(ncnn::LayerType::Padding);
                                               ^
/ncnn/src/mat.cpp: At global scope:
/ncnn/src/mat.cpp:718:47: error: ‘Packing’ is not a member of ‘-LayerType’
     ncnn::Layer* packing = ncnn::create_layer(ncnn::LayerType::Packing);
                                               ^
[ 20%] make[2]: *** [src/CMakeFiles/ncnn.dir/mat.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by nihui** [comment]
删除 build 目录，重新 mkdir build && cd build && cmake .. && make

**Comment by jiajiajun** [comment]
谢谢@nihui，已经尝试过，还是有这个问题

**Comment by jiajiajun** [comment]
换了个服务器，重装了cmake3.6.3，protobuf2.6.1，OpenCV2.4.11，重下了ncnn，mkdir build && cd build && cmake .. && make后，还是存在上面的问题，请问大神@nihui，还有可能是哪方面的问题呢？

**Comment by nihui** [comment]
ncnn代码被改过？重新 git clone 试试看

**Comment by jiajiajun** [comment]
@nihui没有呢，也都是最新下载的，都试了几遍的

**Comment by jiajiajun** [comment]
重新下了个最新的ncnn，make通过了，非常感谢@nihui
