### ISSUE TITLE
vulkan 对性能影响有多大？

### ISSUE THREAD

**Issue by helloearth012** [Tencent/ncnn#825]
安装的时候，vulkan是optional，所以暂时没有装。
假如安装vulkan后，一般情况下，性能有多大提升？

**Comment by nihui** [comment]
取决于显卡性能，pc上加速效果显著，比ncnn x86 cpu快10~20倍吧。。
手机上性能比 ncnn arm 慢

**Comment by tpoisonooo** [comment]
从17年5月就经常在看ncnn的更新，写了那么多汇编的 nihui 竟然是个姑娘？...
