### ISSUE TITLE
骁龙625 armv8a的结果似乎比armv7a+neon慢很多

### ISSUE THREAD

**Issue by helloearth012** [Tencent/ncnn#826]
一个开发人员的结果:https://github.com/Tencent/ncnn/issues/281
它使用的v7+neon  (2018 05/01)
loop_count = 10
num_threads = 8
powersave = 0
      squeezenet  min =   64.70  max =   67.36  avg =   65.85
       mobilenet  min =   90.11  max =  104.90  avg =   92.96
    mobilenet_v2  min =  114.83  max =  125.85  avg =  117.29
      shufflenet  min =   40.93  max =   42.20  avg =   41.38
       googlenet  min =  171.80  max =  181.18  avg =  175.35
        resnet18  min =  197.73  max =  203.97  avg =  199.43
         alexnet  min =  175.38  max =  192.03  avg =  178.28
           vgg16  min = 1617.39  max = 1696.84  avg = 1647.92
  squeezenet-ssd  min =  121.85  max =  131.11  avg =  124.26
   mobilenet-ssd  min =   96.02  max =  106.27  avg =   98.15

下面是我的结果（2019 3/11），使用armv8a，大概用了v7a的两倍时间。为什么会产生这个差异？
loop_count = 4
num_threads = 8
powersave = 0
gpu_device = -1
squeezenet            min =  135.19  max =  135.76  avg =  135.53
squeezenet-int8       min =  362.83  max =  363.69  avg =  363.20
mobilenet             min =  203.84  max =  205.01  avg =  204.20
mobilenet-int8        min =  569.93  max =  571.49  avg =  570.43
mobilenet_v2          min =  177.74  max =  178.43  avg =  178.12
shufflenet            min =   77.23  max =   77.57  avg =   77.40
mnasnet               min =  138.27  max =  138.47  avg =  138.37
proxylessnasnet       min =  162.99  max =  164.04  avg =  163.39
googlenet             min =  497.75  max =  501.03  avg =  499.51
googlenet-int8        min = 1091.38  max = 1092.88  avg = 1092.27
resnet18              min =  517.81  max =  518.88  avg =  518.30
resnet18-int8         min = 1138.52  max = 1139.91  avg = 1139.30
alexnet               min =  557.29  max =  559.75  avg =  558.41
vgg16                 min = 2549.05  max = 2554.16  avg = 2551.18
resnet50              min = 2139.37  max = 2149.42  avg = 2144.63
resnet50-int8         min = 2685.84  max = 2691.28  avg = 2688.74
squeezenet-ssd        min =  342.37  max =  352.80  avg =  347.55
squeezenet-ssd-int8   min =  929.92  max =  934.02  avg =  932.00
mobilenet-ssd         min =  378.07  max =  379.95  avg =  379.12
mobilenet-ssd-int8    min = 1086.97  max = 1089.69  avg = 1088.41
mobilenet-yolo        min =  953.24  max =  955.91  avg =  955.08
mobilenet-yolov3      min =  886.06  max =  891.43  avg =  888.58

**Comment by nihui** [comment]
检查下是否开启了 neon，用 clang 编译

**Comment by helloearth012** [comment]
> 检查下是否开启了 neon，用 clang 编译

@nihui 你好，
1. arm-v8a 是默认开启neon。
2. 我重新用arm-v7a, 骁龙625，-DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=ON 开启了neon，速度还是https://github.com/Tencent/ncnn/issues/281 的2倍时间，不知道除了用上面指令开启neon，是否还有其他指令。

**Comment by thtfpcuser** [comment]
在imx6q上运行benchmark非常慢，不过已经开启neon了。
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "Cortex-A9"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_align_preserved: 8-byte, except leaf SP
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_MPextension_use: Allowed
  Tag_Virtualization_use: TrustZone

root@imx6qsabresd:/home/ncnn/benchmark# ./benchncnn 
loop_count = 4
num_threads = 1
powersave = 0
gpu_device = -1
          squeezenet  min = 1473.06  max = 1474.05  avg = 1473.44

应该如何排查？

**Comment by thtfpcuser** [comment]
一个排查点：set( CMAKE_SYSTEM_NAME Linux )必须在toolchain文件里面写，否则CMAKE_SYSTEM_PROCESSOR的值是错的。

**Comment by MirrorYu** [comment]
v8a版本的ncnn，好像mobilenetv2推理结果异常

**Comment by niinorz** [comment]
相同的问题,不过我的环境是高通的Trustzone,骁龙675平台,单核,同一个模型跑100次推理的平均时间:
32位: 打开 sgemm 选项 100 ms,关闭 120ms
64位: 打开 sgemm 选项 785 ms,关闭 805ms

骁龙888(sdm865)环境下,由于不支持32位,64位要160ms

不知道是否有优化方向

**Comment by nihui** [comment]
更新ncnn版本获得性能提升哦！
