### ISSUE TITLE
转换模型失败

### ISSUE THREAD

**Issue by EEWenbinWu** [Tencent/ncnn#828]
[libprotobuf ERROR google/protobuf/message_lite.cc:123] Can't parse message of type "caffe.NetParameter" because it is missing required fields: layer[0].psroi_pooling_param.spatial_scale, layer[0].psroi_pooling_param.output_dim, layer[0].psroi_pooling_param.group_size
read_proto_from_binary failed

无奈换了太电脑，转出来的模型不正常，有大神见过这种情况吗，模型再caffe运行是正常的

**Comment by nihui** [comment]
caffe2ncnn 转换工具重新编译下

**Comment by wkt** [comment]
我转换openpose的[body_25b](https://github.com/CMU-Perceptual-Computing-Lab/openpose_train/tree/master/experimental_models#body_25b-model---option-1-maximum-accuracy-less-speed)模型时，也遇到了类似的错误提示，重新编译caffe2ncnn不管用啊
