### ISSUE TITLE
ncnn支持的输入数据格式？

### ISSUE THREAD

**Issue by wangkgege** [Tencent/ncnn#83]
看了源代码，好像目前只支持PIXEL_RGB2BGR，PIXEL_BGR2RGB，PIXEL_RGB2GRAY，PIXEL_BGR2GRAY，PIXEL_GRAY2RGB，PIXEL_RGBA2RGB，PIXEL_RGBA2BGR，PIXEL_RGBA2GRAY，PIXEL_RGB，PIXEL_BGR。
有必要支持自定义通道数的输入。比如，mtcnn的第四个网络，其通道数为15。见：https://github.com/kpzhang93/MTCNN_face_detection_alignment/blob/master/code/codes/MTCNNv2/model/det4.prototxt

**Comment by nihui** [comment]
from_pixels 只是方便从图像转换的接口
可以自己构造 15 通道 Mat

**Comment by wangkgege** [comment]
@nihui  谢谢，我接下来试一试。现在遇到其他问题了，同样的图片，caffe model的输出结果与ncnn model的结果不同。我在查找原因，可能是我对ncnn的数据输入没搞清楚。

**Comment by wangkgege** [comment]
@nihui 大神，能否以mtcnn为例，做一个例子，介绍一下ncnn model的数据输入？因为在caffe model的使用中，对input_layer做了reshape，然后对输入图片数据也做了转置。而在ncnn model的使用时，只能控制输入数据的格式。我尝试过若干种ncnn model的数据输入格式，都无法得到caffe model同样的结果。本人能力有限，希望大神赐教。

**Comment by wangkgege** [comment]
@nihui ，我做了三组实验，其中两组ncnn model输出结果的实验，不同点是数据预处理和输入方式。另一组使用caffe model得出的结果。对比了三组输出结果，发现均不一致，但我尚未找到原因。我把实验代码记录在博客：[caffe model和ncnn model输出结果不一致](http://blog.csdn.net/Chris__kk/article/details/76788285)，请您指教。

**Comment by nihui** [comment]
mtcnn 原始的caffemodel是colmajor的，直接转换的模型会被当成rowmajor算，结果肯定不对的
mtcnn可以参考这里的
https://github.com/ElegantGod/ncnn

**Comment by wangkgege** [comment]
@nihui ，我编译了这份代码（https://github.com/ElegantGod/ncnn），使用caffe2ncnn_mtcnn重新转换了pnet模型，然后使用ncnn进行相关预处理，并输入ncnn版pnet模型。但是caffe版pnet模型跑出来的结果与ncnn版pnet模型跑出的结果还是有差异。而且对输出结果prob1的索引方式不同，结果也不同。

下面以比较pnet模型中prob1的第二通道的数据为例，给出下面的对比结果。
caffe版pnet模型跑出来的prob1结果,记为prob1_c，59*48.
ncnn版pnet模型跑出来的prob1结果，记为prob1_n，59*48
索引方式1：
for (int k = 0; k < prob1.c; ++k){
        float* p = prob1.channel(k);
        for (int i=0; i < prob1.h; ++i){
            for (int j=0; j<prob1.w; ++j){
                cout << *p << ",";
                p++;
            }
            cout << endl;
        }
        cout << endl;
        cout << endl;
    }
caffe和ncnn结果对比：prob1_c > 0.6的数据点有19个，prob1_n > 0.6的数据点有16个。sum(prob1_c - prob1_n) = 4.114。

索引方式2：
for (int k = 0; k < prob1.c; ++k){
        for (int i=0; i < prob1.h; ++i){
            for (int j=0; j<prob1.w; ++j){
                cout << *(prob1.data + prob1.cstep*k + prob1.h*i + j) << ",";
            }
            cout << endl;
        }
        cout << endl;
        cout << endl;
    }
caffe和ncnn结果对比：prob1_c > 0.6的数据点有19个，prob1_n > 0.6的数据点有19个，但坐标不同。sum(prob1_c - prob1_n) = -0.8318。

全部实验代码：
#include <iostream>
#include <string>
#include <opencv2/opencv.hpp>
using std::string;
using std::cout;
using std::endl;
#include "net.h"

/*
ncnn版pnet模型的输出结果，其中数据预处理部分使用ncnn做
*/

int main(){
    int ws = 128;
    int hs = 106;
    string path_img = "/home/wangk/face.jpg";
    cv::Mat img_in = cv::imread(path_img, CV_LOAD_IMAGE_COLOR);
    ncnn::Mat in_ = ncnn::Mat::from_pixels(img_in.data, ncnn::Mat::PIXEL_BGR2RGB, img_in.cols, img_in.rows);
    ncnn::Mat in(ws, hs, 3);
    resize_image(in_, in);
    const float mean_vals[3] = { 127.5f, 127.5f, 127.5f };
    const float norm_vals[3] = { 0.0078125f, 0.0078125f, 0.0078125f };
    in.substract_mean_normalize(mean_vals, norm_vals);
    cout << "in.w: " << in.w << "\n" \
         << "in.h: " << in.h << "\n" \
         << "in.c: " << in.c << "\n" \
         << "in.cstep: " << in.cstep << "\n";
    ncnn::Net pnet;
    string path = "/home/wangk/tencent/ncnn_mtcnn";
    string path_param_str = path + "/mtcnn_c2_new/det1.param";
    string path_model_str = path + "/mtcnn_c2_new/det1.bin";
    const char* path_param = path_param_str.c_str();
    const char* path_model = path_model_str.c_str();
    pnet.load_param(path_param);
    pnet.load_model(path_model);

    ncnn::Extractor ex = pnet.create_extractor();
    ex.set_light_mode(true);
    ncnn::Mat conv4_2;
    ncnn::Mat prob1;

    ex.input("data",in);
    ex.extract("conv4-2", conv4_2);
    ex.extract("prob1", prob1);

    cout << "prob1.w: " << prob1.w << endl; 
    cout << "prob1.h: " << prob1.h << endl; 
    cout << "prob1.c: " << prob1.c << endl;
    cout << "prob1.cstep: " << prob1.cstep << endl;
    for (int k = 0; k < prob1.c; ++k){
        for (int i=0; i < prob1.h; ++i){
            for (int j=0; j<prob1.w; ++j){
                cout << *(prob1.data + prob1.cstep*k + prob1.h*i + j) << ",";
            }
            cout << endl;
        }
        cout << endl;
        cout << endl;
    }

    // for (int k = 0; k < prob1.c; ++k){
    //     float* p = prob1.channel(k);
    //     for (int i=0; i < prob1.h; ++i){
    //         for (int j=0; j<prob1.w; ++j){
    //             cout << *p << ",";
    //             p++;
    //         }
    //         cout << endl;
    //     }
    //     cout << endl;
    //     cout << endl;
    // }
    
    return 0;
}

**Comment by wangkgege** [comment]
@nihui 谢谢

**Comment by LittlePeng** [comment]
@nihui https://github.com/ElegantGod/ncnn
发现ncnn mtcnn和caffe model相比同样threshold情况下识别率要差不少，把resize_image改为cv::resize 也不管用，相同输入图片 Pnet的输出bbox少很多

**Comment by jj8401** [comment]
@wangkgege 你的博客中 img = (img - 127.5) * 0.0078125;这句代码不会报错么，我的报undefined reference to operator

**Comment by wangkgege** [comment]
@jj8401 使用opencv做的，运行没有出现问题。
