### ISSUE TITLE
发现benchmark里包含的int8性能怎么比原来的差呢

### ISSUE THREAD

**Issue by xiaofengren** [Tencent/ncnn#830]
我是ARMv8架构的平台上做的测试，怎么发现使用int8的性能测试结果比原来的没有int8的结果低呢？还需要在那里做配置吗？
下面的是在我的平台上跑出来的性能测试结果：
root@aad2441cbcdb5598851a5f655d0a70f7:~/ncnn/benchmark# ../build/benchmark/benchncnn 4 4
loop_count = 4
num_threads = 4
powersave = 0
gpu_device = -1
squeezenet            min =   23.34  max =   23.37  avg =   23.35
squeezenet-int8       min =   60.70  max =   60.93  avg =   60.82
mobilenet             min =   31.65  max =   31.90  avg =   31.74
mobilenet-int8        min =   67.30  max =   68.88  avg =   67.72
mobilenet_v2          min =   32.71  max =   33.06  avg =   32.90
shufflenet            min =   24.88  max =   26.74  avg =   25.44
mnasnet               min =   29.53  max =   29.84  avg =   29.64
proxylessnasnet       min =   35.48  max =   35.58  avg =   35.54
googlenet             min =   78.54  max =   80.31  avg =   79.07
googlenet-int8        min =  221.94  max =  240.36  avg =  232.89

我的"../CMakeLists.txt" 和编译相关的配置如下：

project(ncnn)

option(NCNN_OPENMP "openmp support" ON)
option(NCNN_STDIO "load model from external file" ON)
option(NCNN_STRING "plain and verbose string" ON)
option(NCNN_OPENCV "minimal opencv structure emulation" OFF)
option(NCNN_BENCHMARK "print benchmark information for every layer" OFF)
option(NCNN_PIXEL "convert and resize from/to image pixel" ON)
option(NCNN_PIXEL_ROTATE "rotate image pixel orientation" OFF)
option(NCNN_CMAKE_VERBOSE "print verbose cmake messages" OFF)
option(NCNN_VULKAN "vulkan compute support" OFF)
option(NCNN_REQUANT "auto merge int8 quant and dequant" ON)
option(NCNN_IM2COL_SGEMM "im2col sgemm support" ON)

我的toolchain版本是 gcc-7.3. 

root@aad2441cbcdb5598851a5f655d0a70f7:~/ncnn/benchmark# gcc --version
gcc (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by BUG1989** [comment]
ARMv8平台正在优化int8推理速度

**Comment by xiaofengren** [comment]
多谢，期待ARMv8平台的支持。
请问int8目前在那些平台上支持？

**Comment by BUG1989** [comment]
@xiaofengren 
ARMv8平台已经支持了，只是速度，看机器 (

**Comment by xiaofengren** [comment]
这么快就支持，非常感谢。
请问，您说的看机器是指具体的芯片吗？我用的NXP的16和Cortex-A72处理器。
我重新跑了一下benchmark，和上次的对比，int8的性能有比较大的提升，但是相比缺省的FP32，性能还是低除了resnet50。我是运行在Linux下面，不是Android。

rk/benchncnn 4 4d513f8e7adefbb0267145:/app/facedetect/src/ncnn/benchmark# ../build/benchmar
loop_count = 4
num_threads = 4
powersave = 0
gpu_device = -1
squeezenet            min =   21.82  max =   22.15  avg =   22.00
squeezenet-int8       min =   22.43  max =   23.13  avg =   22.66
mobilenet             min =   29.91  max =   44.67  avg =   34.03
mobilenet-int8        min =   38.53  max =   39.17  avg =   38.85
mobilenet_v2          min =   30.76  max =   32.37  avg =   31.43
shufflenet            min =   23.99  max =   24.06  avg =   24.02
mnasnet               min =   28.12  max =   28.91  avg =   28.37
proxylessnasnet       min =   34.59  max =   34.75  avg =   34.65
googlenet             min =   73.41  max =   76.97  avg =   75.14
googlenet-int8        min =   72.31  max =   83.70  avg =   76.48
resnet18              min =   65.78  max =   76.28  avg =   70.32
resnet18-int8         min =   70.29  max =   73.97  avg =   71.37
alexnet               min =   83.19  max =  103.99  avg =   88.52
vgg16                 min =  294.75  max =  307.59  avg =  299.38
resnet50              min =  201.36  max =  204.86  avg =  203.09
resnet50-int8         min =  156.02  max =  156.77  avg =  156.24
squeezenet-ssd        min =   54.97  max =   61.00  avg =   57.84
squeezenet-ssd-int8   min =   57.56  max =   57.75  avg =   57.63
mobilenet-ssd         min =   60.57  max =   69.49  avg =   63.64
mobilenet-ssd-int8    min =   66.72  max =   68.02  avg =   67.11
mobilenet-yolo        min =  134.19  max =  136.39  avg =  135.18
mobilenet-yolov3      min =  133.54  max =  135.63  avg =  134.62

**Comment by BUG1989** [comment]
持续优化中，mobilenet ssd单独跑demo应该int8会快一点点

**Comment by BUG1989** [comment]
@xiaofengren 
最近有更新了，int8都比fp32快一点点了。建议直接上自己使用的模型单独测试，使用benchncnn int8的速度偏慢，原因未知 : (

**Comment by xiaofengren** [comment]
感谢，我会按照您说的方法再试一下。
