### ISSUE TITLE
How to read Shape proto from Attr "value" in "Const" ops from Tensorflow frozen graph in Tensorflow2ncnn.cpp? 

### ISSUE THREAD

**Issue by WeiyiLi** [Tencent/ncnn#832]
I have one model with some const ops. These opts saved the shape information in protobuf in the attr "value". However, when I use tensorflow2ncnn.cpp to convert the frozen graph, these information are sometimes missing. 
I use `protoc --deocde` to read the frozen graph, I found the "tag" that relates this information is different. 
Below is the ops that the "shape" information CAN be read in tensorflow2ncnn.cpp because the tag in front of the values is "4". 
![image](https://user-images.githubusercontent.com/6508944/54383407-3b22ae00-464f-11e9-9efb-08727597ecb9.png)

Below is the ops that the "shape" information CANNOT be read into tensorflow2ncnn.cpp because the tag in front of the values is "7"
![image](https://user-images.githubusercontent.com/6508944/54383577-9bb1eb00-464f-11e9-82b0-2eff9464d5a7.png)

I searched the ncnn code and found https://github.com/Tencent/ncnn/blob/master/tools/tensorflow/attr_value.proto#L18
To my understanding, the values with tag "4" is _float_ and the values with tag "7" is _shape_. 
Therefore, how can I change the tensorflow2ncnn.cpp code and read this shape information out? Thank you!

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/issues/5
