### ISSUE TITLE
User Error 1001: argument to num_threads clause must be positive

### ISSUE THREAD

**Issue by yizhaoyanbo** [Tencent/ncnn#834]
我用工程里给的example，跑了下squeezenet的demo。debug下会打印这个log：

User Error 1001: argument to num_threads clause must be positive

但是结果是正确的：

323 = 0.997080
325 = 0.001358
619 = 0.000190

这是个什么鬼捏

**Comment by yizhaoyanbo** [comment]
ex.set_num_threads(N), OK

**Comment by 18022443868** [comment]
如何解决的？

**Comment by 18022443868** [comment]
解决了吗？这个问题？vs2015里面一跑就遇到这个，还打印了好几次

**Comment by 18022443868** [comment]
如何解决的？
