### ISSUE TITLE
caffe2ncnn层名为纯数字字符例如‘111’这样的，使用外置转int8的table会出错

### ISSUE THREAD

**Issue by RexGShan** [Tencent/ncnn#836]
int nscan = sscanf(key, "%f", &scale);
            if (nscan == 1)
            {
                scales.push_back(scale);
                continue;
            }
这段代码会因为获取到数字而无法正确执行

PS：该分支（0x000D4B38）转换文件读取同样异常，无法正确获取table的参数，代码如下：
                fwrite(weight_int8scale.data(), sizeof(float), weight_int8scale.size(), bp);
                fwrite(blob_int8scale.data(), sizeof(float), blob_int8scale.size(), bp);
调试读取模型时会走到像是在读
                fwrite(quantize_table.data(), sizeof(float), quantize_table.size(), bp);
                fwrite(quantize_index.data(), sizeof(unsigned char), quantize_index.size(), bp);
这两行的分支，导致模型读取失败

**Comment by RexGShan** [comment]
@nihui @BUG1989

**Comment by nihui** [comment]
暂时先别用纯数字的名字，table文件没有考虑这些...
