### ISSUE TITLE
vkCreateComputePipelines failed -1000012000

### ISSUE THREAD

**Issue by yizhaoyanbo** [Tencent/ncnn#837]
环境：windows10 + VS2015 +Nivida Geforce GTX750TI + VulkanSDK1.1.101.0

I have installed VulkanSDK  and added it to Cmake. the error occurs at following sentence：

squeezenet.cpp:

     squeezenet.load_model("squeezenet_v1.1.bin"); 

pipeline.cpp:

VkResult ret = vkCreateComputePipelines(vkdev->vkdevice(), 0, 1, &computePipelineCreateInfo, 0, &pipeline);
    if (ret != VK_SUCCESS)
    {
        fprintf(stderr, "vkCreateComputePipelines failed %d\n", ret);
        return -1;
    }`

**Comment by nihui** [comment]
更新下 nvidia 驱动试试看
https://www.nvidia.com/Download/index.aspx

**Comment by yizhaoyanbo** [comment]
@nihui it worked. thanks.
