### ISSUE TITLE
Bug in Slice layer?

### ISSUE THREAD

**Issue by iamhankai** [Tencent/ncnn#838]
How to use Slice layer? Some examples?

I tried "Slice conv1_slice 1 2 conv1_dw conv1_dw1 conv1_dw2 0=32 1=0", but met "段错误"

I print the slices varaible, its empty, is it bug?

**Comment by hanfanggithub** [comment]
> 0

hi , did you solve the slice problem ? i met the same issue.

**Comment by iamhankai** [comment]
Not yet. how about u?

**Comment by hanfanggithub** [comment]
> Not yet. how about u?

no ........ so i modified my model structure , my situation is i need to tranform shufflev2 model from pytorch to ncnn , i changed to mobilev2 and problem solved , if you want to use shufflev2 ,recomend pytorch > caffe >ncnn  , slice in onnx will meet a lot of problems

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/1b910efea52621e36813874334d18920c48ec6d4
slice op should be converted to ncnn crop properly now

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
