### ISSUE TITLE
squeezenet中使用新生成的.param 和.bin文件出错

### ISSUE THREAD

**Issue by 5059** [Tencent/ncnn#84]
Windows\VS 环境下使用caffe2ncnn转换得到.param和.bin文件，替换到squeezenet这个Demo中，运行失败。直接运行.exe出现 fopen xxx.param failed 和 fopen xxx.param failed 参考的博文http://blog.csdn.net/fuwenyan/article/details/76147204。 求解啊

**Comment by nihui** [comment]
这个只能是文件没找到啊，看下路径。
还有也可以访问主页上qq群
