### ISSUE TITLE
Build error without neon

### ISSUE THREAD

**Issue by michaelowenliu** [Tencent/ncnn#840]
Build ncnn with "-DANDROID_ARM_NEON=OFF" or not include "-DANDROID_ARM_NEON".

`cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_ARM_NEON=OFF -DANDROID_PLATFORM=android-14 ..`

`cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a" -DANDROID_PLATFORM=android-14 ..`

error log like:

/ncnn/src/layer/arm/convolution_arm.cpp:77:13: error: use
      of undeclared identifier
      'conv3x3s1_winograd23_transform_kernel_int8_neon'; did you mean
      'conv3x3s1_winograd64_transform_kernel_neon'?
            conv3x3s1_winograd23_transform_kernel_int8_neon(weight_data...
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            conv3x3s1_winograd64_transform_kernel_neon

**Comment by nihui** [comment]
arm neon instruction is critical for ncnn optimization. why do you want to build ncnn without arm neon ？

**Comment by BUG1989** [comment]
Please try the latest codes again : )
I think that i have fixed this error.

**Comment by michaelowenliu** [comment]
> arm neon instruction is critical for ncnn optimization. why do you want to build ncnn without arm neon ？

just try the option and see how.

**Comment by nihui** [comment]
update to the latest code and that shall solve this issue
