### ISSUE TITLE
cpu占用率很高

### ISSUE THREAD

**Issue by michaelowenliu** [Tencent/ncnn#845]
现在ncnn单线程跑起来，cpu占用率基本都飙到60%，怎么平衡速度和cpu占用率呢？用了sleep，在sleep的时候cpu占用率很低，但是只要ncnn detect一运行，立刻飙升。是ncnn去占用了所有的算力？

**Comment by nihui** [comment]
cnn推断本身是个纯计算过程，占用cpu是正常的，减小调用频率，使用更小的模型

硬要减慢速度的话，extract中间的blob，然后sleep，相当于把一个模型分成多个阶段跑，中间休息下。。

**Comment by michaelowenliu** [comment]
> cnn推断本身是个纯计算过程，占用cpu是正常的，减小调用频率，使用更小的模型
> 
> 硬要减慢速度的话，extract中间的blob，然后sleep，相当于把一个模型分成多个阶段跑，中间休息下。。

@nihui 试过减小调用频率和更小模型不会降低调用时时间内CPU占用率，一个模型分段跑怎么操作呢，这个听起来更可行一些，需要修改哪里呢，能稍微详细一点吗？谢谢。

**Comment by nihui** [comment]
```
ex.input("data", data);
ex.extract("conv1", conv1);
sleep(1);
ex.extract("conv2", conv2);
sleep(1);
ex.extract("conv3", conv3);
sleep(1);
ex.extract("conv4", conv4);
sleep(1);
.....
.....
.....
ex.extract("prob", prob);
```

**Comment by zbpjlc** [comment]
我在以前的版本上使用时占用的CPU不到10%，可是现在占用就如上大概50%-60%那样了，请问是做了什么改进，导致CPU使用率大幅上升了呢
