### ISSUE TITLE
slice层转换问题

### ISSUE THREAD

**Issue by eeric** [Tencent/ncnn#85]
@nihui @wangkgege ,lightcnn C模型转换成功，但在etlwise_fc1提取的256维特征与caffe版的平均L1规则误差在实数1以内。
是不是按ced04dd修改，就可以纠正？

另外，C模型转后的param的slice层参数出现负数，这个是不是有问题？如下所示：
Slice slice1 1 2 conv1 slice1_1 slice1_2 2 -233 -233
Eltwise etlwise1 2 1 slice1_1 slice1_2 eltwise1 2 0
Pooling pool1 1 1 eltwise1 pool1 0 2 2 0 0
Convolution conv2a 1 1 pool1 conv2a 96 1 1 1 0 1 4608
Slice slice2a 1 2 conv2a slice2a_1 slice2a_2 2 -233 -233
Eltwise etlwise2a 2 1 slice2a_1 slice2a_2 eltwise2a 2 0
...............

再问问，param里面的参数具体是什么含义？先谢谢啦！

**Comment by nihui** [comment]
-233 是个特殊标记，表示运行时断定，Slice 里的 -233 就是均匀切分

**Comment by nihui** [comment]
注意下输入图像通道 RGB / BGR 的区别

**Comment by eeric** [comment]
@nihui，感谢

**Comment by xiaomage11** [comment]
@eeric，您好，你的问题已经解决了吗，输出的特征跟caffe的一致了吗？
