### ISSUE TITLE
Extractor(const Net* net, int blob_count); candidate expects 2 arguments, 0 provided

### ISSUE THREAD

**Issue by patrick-ucr** [Tencent/ncnn#853]
Hi,

I am trying to build this Android demo app from https://github.com/xumengwei/DeepCache , which is built upon ncnn. I link static library in CMakeLists.txt and the library can be imported from cpp implementation. However, when extractor is being constructed like

static ncnn::Extractor ex;

compiler complains this
Extractor(const Net* net, int blob_count); candidate expects 2 arguments, 0 provided

Not sure if the constructor was wrong or the library linking was incorrect.

**Comment by nihui** [comment]
it seems that deepcache project is using a rather old version of ncnn library. you may ask the deepcache developer to update their code, or stick with its ncnn source bundled.
