### ISSUE TITLE
ReduceMean not supported yet!

### ISSUE THREAD

**Issue by hgj3804278** [Tencent/ncnn#856]
I tried to run from onnx model transform to ncnn model  
onnx2ncnn.exe mobilnetv2.onnx mobilnetv2.param mobilnetv2.bin

ReduceMean not supported yet!
  # axes 7
  # keepdims=0
ReduceMean not supported yet!
  # axes 7
  # keepdims=0

**Comment by hanfanggithub** [comment]
mean操作可以用avgpooling代替

**Comment by nihui** [comment]
ReduceMean added in https://github.com/Tencent/ncnn/commit/04b4b023249865ae01befe4170a873d5f2ec33f8

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
