### ISSUE TITLE
如何新增自定义层？

### ISSUE THREAD

**Issue by iphone5solo** [Tencent/ncnn#86]
由于需求用到[CTPN](
https://github.com/tianzhi0549/CTPN) ，CTPN有自定义的网络层，请问如何添加到ncnn中? 以便使用caffe2ncnn工具转化！

**Comment by cuihao19931030** [comment]
https://github.com/Tencent/ncnn/commit/dcbc117368fffd4d70b9876bb3a4cae31b97dd7e

**Comment by cuihao19931030** [comment]
这是nihui大神的大致参考
https://github.com/Tencent/ncnn/commit/dcbc117368fffd4d70b9876bb3a4cae31b97dd7e

**Comment by nihui** [comment]
wiki 上有一篇关于添加自定义层的方法

**Comment by yulinhuyang** [comment]
但是这样caffe2ncnn工具支持不了新层啊，会报错，还需要改其他的地方吗

**Comment by Aaron4Fun** [comment]
你好，请问你实现了转化了吗？我现在遇到相同的问题，但是用的是pytorch下的ctpn，因为有自定义的im2col层所以转换成onnx时会报 Couldn't export Python operator Im2Col的错误，不能生成对应的.bin和。param文件。在这种情况下请问有什么解决方案呢？还是说得把代码改写成caffe版本会好一点呢，谢谢。

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
