### ISSUE TITLE
pytorch导出成onnx再转ncnn出错怎么办

### ISSUE THREAD

**Issue by FiveCP** [Tencent/ncnn#860]
pytorch导出成onnx再转ncnn出现
Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!
  # axes 7
Unsqueeze not supported yet!
  # axes 7
请问怎么解决怎么解决

**Comment by nihui** [comment]
试试看 daquexian 的优化工具，可以把这些op去掉
https://github.com/daquexian/onnx-simplifier
