### ISSUE TITLE
安卓端与PC端结果不一致

### ISSUE THREAD

**Issue by briansst** [Tencent/ncnn#862]
PC端测试成功，输出结果正确。
移植到安卓端测试时，打印出的第一个卷积层的输出结果，已与PC端的不一致。预处理确定没有问题，随机打印出了一些值比较。 
请问下大佬们，会是什么问题？  第一次接触安卓，仿照例子里加密的方法进行读取的。 有可能是ncnn2mem 转出的模型有关吗？

**Comment by nihui** [comment]
用bmp格式的图片测试下看看

**Comment by briansst** [comment]
> 用bmp格式的图片测试下看看

谢谢大佬回复，pc android 同一张bmp，第一层conv layer的输出相差就很大了... ncnn::Mat in 随机打印出几个值，预处理是没有问题的... :(

**Comment by briansst** [comment]
换非加密的方式在android端测试，结果正确，可能与ncnn2mem的转出有关，my bad

**Comment by chenloveheimei** [comment]
> 换非加密的方式在android端测试，结果正确，可能与ncnn2mem的转出有关，my bad

你好,问下,你非加密的libncnn.a的库是哪个库呀,我这边也是这样值不对,用的是加密的那种.我看网上用的非加密的方式,
这是加密的写法:
ex.input(hand_param_id::BLOB_data, in);
    ncnn::Mat out;
    ex.extract(hand_param_id::BLOB_detection_out, out);
这是非加密的写法:
ex.input("data", in);
ncnn::Mat out;
ex.extract("detection_out",out);
但是我用非加密报错.
请教下,怎么做呢?
