### ISSUE TITLE
bilinear resize 逻辑

### ISSUE THREAD

**Issue by zealerww** [Tencent/ncnn#863]
https://github.com/Tencent/ncnn/blob/43737b378f38a147f3935b048e304c5b2ffa9930/src/mat.cpp#L525

resize_bilinear_image这个函数的逻辑是不是有点小问题
原逻辑
```
prev_sy1 = -1;
...
if (sy == prev_sy1)
{
...
}
else
{
...
}
...
prev_sy1 = sy + 1;
```

下面这种逻辑应该能更省时间
```
prev_sy = -2;
...
if (sy == prev_sy)
{
// do nothing.
}
else if (sy == prev_sy+1)
{
...
}
else
{
...
}
...
prev_sy = sy;
```

**Comment by ToBigboss** [comment]
prev_sy = -2;
...
if (sy == prev_sy)
{
// do nothing.
}不存在==-2的情况吧

**Comment by zealerww** [comment]
> prev_sy = -2;
> ...
> if (sy == prev_sy)
> {
> // do nothing.
> }不存在==-2的情况吧

第一次肯定都要计算rows0和rows1的数据

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
感谢~

**Comment by zealerww** [comment]
> 感谢~

互相学习，从你的代码里学到了很多。
