### ISSUE TITLE
Is there a way to find out the dimensions of the output layer?

### ISSUE THREAD

**Issue by NikolaMr** [Tencent/ncnn#864]
I want to find out the output layer's size. How am I supposed to do that?

**Comment by nihui** [comment]
you can get the blob shape with the Mat class member w h c

**Comment by NikolaMr** [comment]
That is true, but that means I have to know what the output layer name is. What if I don't know the name of the output layer?

How to get the output layer name?

**Comment by nihui** [comment]
the output blob name depends on model.
In practice, you could always change the blob name to a fixed name in param file by yourself, so that you can hardcoded this fixed name in your code.

**Comment by NikolaMr** [comment]
@nihui thank you for the practical advice.
