### ISSUE TITLE
Multithreading doesn't speed up performance using multiple mobilenet extractors on Raspberry Pi model b+.

### ISSUE THREAD

**Issue by mkar2210** [Tencent/ncnn#869]
Hello @nihui

I am trying to use different extractors loading different models and use multiple threads to extract independently. Running a single extractor takes around 400 ms. After multithreading two different extractors simultaneously, I expected around the same time(or +=100ms). But It becomes twice when I use 2 threads, thrice on 3 threads and goes on. I have posted the code that I tried. Can someone help ?

**Configuration:**
Raspberry pi model b+

**Note:**
 Different inputs, different models and different extractors. Are there still any dependency between the extractors/threadTasks?

**void threadTask( ncnn::Extractor ex, ncnn::Mat ins, ncnn::Mat class, ncnn::Mat loc)
{
	for (int j=0;j<6;j++)
	{
		ex.extract(clas_name,class);
		ex.extract(loc_name,loc);
	}
}

ncnn::Net mobilenet[2];
for (int i=0;i<2;i++)
{
    	mobilenet[i].register_custom_layer("aaa", aaa_layer);
    	mobilenet[i].load_param("mobilenet.param");
    	mobilenet[i].load_model("mobilenet.bin");
};

ncnn::Extractor ex[2] = {mobilenet[0].create_extractor(),mobilenet[1].create_extractor()};

ex[0].set_num_threads(2);
ex[1].set_num_threads(2);
ex[0].input("Placeholder", ins[0]);
ex[1].input("Placeholder", ins[1]);

for(int i=0; i<2; i++)
{
	tid[i] = std::thread(threadTask, ex[i], ins[i], classification[i], localization[i] );
}

for(int i = 0;i < 2; i++)
	if(tid[i].joinable())
		tid[i].join();**

**Comment by nihui** [comment]
Raspberry Pi model b+ is single-core sbc, so it is expected that multi-threading do not scale well on it
