### ISSUE TITLE
对齐problem

### ISSUE THREAD

**Issue by NHZlX** [Tencent/ncnn#87]
我看代码是16位对齐， 即对 N C H W 的data， 那data + (n * C + c) * H * W 的地址都是对齐的，但是对 data + ((n * C + c)*H + h) * W 的地址， 当h > 0不一定是对齐的把, 那么这块不会减少速度么

**Comment by nihui** [comment]
h>0 不一定对齐，会减少些速度，但是把h对齐会浪费很多额外的空间，所以就没这么做

**Comment by NHZlX** [comment]
ok, thanks
