### ISSUE TITLE
请问读取ncnn::Mat out应该用什么指针类型？

### ISSUE THREAD

**Issue by PK15946** [Tencent/ncnn#871]
你好，非常感谢ncnn！
我现在有一个图像生成模型，输出是浮点数(但不止[0, 1]， 可能是[0, 几百]那种), 因此，我写了这么一小段程序来读ncnn::Mat out
```
static void to_float(const ncnn::Mat &m, std::vector<float> &rgb)
{
    const float *ptr0 = m.channel(0);
    const float *ptr1 = m.channel(1);
    const float *ptr2 = m.channel(2);
    int size = m.w * m.h;
    for(int remain = size;remain>0;remain--)
    {
        rgb.push_back(*ptr0);
        rgb.push_back(*ptr1);
        rgb.push_back(*ptr2);
        ptr0++;
        ptr1++;
        ptr2++;
    }

}
```
但是读到的输出全是-nan(0x400000)
我了解到out.data 的类型是(void *)， 是我选的类型(float *)不对吗？
亦或是模型的问题
我的模型是相同的block堆积起来的, 很奇怪的一件事是当堆积两个block时，能读到正常的输出；再增加一个block， 就变成了上述的-nan(0x400000)。
所以，我现在不确定是模型的问题还是读数据的问题，你觉得这段代码有问题吗？非常感谢！

**Comment by nihui** [comment]
这段代码看起来没什么问题， -nan 要检查是哪个 layer 开始坏掉的

**Comment by kalcohol** [comment]
推荐 visual studio 上用 image watch 看一下中间层的输出，非常直观。
https://github.com/Tencent/ncnn/tree/master/tools/plugin

**Comment by PK15946** [comment]
非常感谢！ @kalcohol

**Comment by kalcohol** [comment]
@PK15946 注意这个插件在通道有 gap 时有 bug

**Comment by PK15946** [comment]
@kalcohol 嗯嗯，我会注意的，谢谢提醒！
