### ISSUE TITLE
量化对性能影响有多大？

### ISSUE THREAD

**Issue by yizhaoyanbo** [Tencent/ncnn#872]
本来想onnx2ncnn的时候做一个模型量化，但是发现目前onnx转ncnn还不支持模型8bit量化操作。所以想了解一下模型量化到8bit后，对性能影响有多大，理论上是比32bit要提高4倍的。
但是我看之前@nihui 在#21中说在内部处理的时候还是按照32bit读取，量化只是缩减模型尺寸。现在还是这样处理的吗。
求大佬们解答，另外：啥时候能支持下onnx2ncnn的量化操作捏。

**Comment by BUG1989** [comment]
由于现在主流ARM芯片指令集的特性，速度提升最多2倍左右(通常情况下x1.5倍)。最新架构才支持int8 dot指令，理论提升4倍(ncnn目前暂未支持)。

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
20210507版本大幅优化int8推理速度，建议更新
