### ISSUE TITLE
what does  ex.set_light_mode(true); do?

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#873]
I did not find any in-depth documentation for the same. So asking here. 
How does this affect operation speed.

**Comment by nihui** [comment]
in light mode, input blob memory will be released after layer forwarding, which saves memory usage

**Comment by soham24** [comment]
does this affects speed?

**Comment by nihui** [comment]
maybe somewhat speed gain if you use pooled allocator
depends on operating system and environment
