### ISSUE TITLE
树梅派3B＋ 运行mobilenetssd 检测结果 为0

### ISSUE THREAD

**Issue by smartwell** [Tencent/ncnn#875]
caffe模型在PC端运行没问题，但是在树梅派断运行有问题，经过检查在mbox_conf_reshape 1 1 mbox_conf mbox_conf_reshape 0=21 1=0 2=-233 3=0 这个位置出现问题，有没有运行成功的

**Comment by smartwell** [comment]
> _No description provided._

**Comment by nihui** [comment]
如果是最新的代码编译，param 文件要重新生成下

**Comment by smartwell** [comment]
> 如果是最新的代码编译，param 文件要重新生成下

我是前两天26号，拉的代码，按照提示安装成功了，刚刚又重新拉了2次，make 都没有成功，convolutiondepthwise_arm.cpp.o  failed，树梅派3B＋ 官方32位系统，真是哭笑不得

**Comment by nihui** [comment]
模型文件可以在这里下载了 https://github.com/nihui/ncnn-assets/tree/master/models
如有问题，可重新open issue讨论
