### ISSUE TITLE
caffe的transform_para{scale:0.0005} 没有转到ncnn的param里

### ISSUE THREAD

**Issue by helloearth012** [Tencent/ncnn#876]
@nihui 
在caffe.proto里面input
{ 
layer: "data"
type: "MemoryData"
top: "data"
top: "label"

caffe的transform_param{scale:0.0005} 
.....}

caffe2ncnn 转化完之后新的ncnn_caffe.param里面，没有体现出**transform_param** 这一项，也没有体现出**MemoryData这**一项，谢谢

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#pre-process

**Comment by helloearth012** [comment]
@nihui 
谢谢您的回复，从link中看到可以对input进行预处理
const float mean_vals[3] = { 103.94f, 116.78f, 123.68f };
const float norm_vals[3] = { 0.017f, 0.017f, 0.017f };
in.substract_mean_normalize(mean_vals, norm_vals);

因为我并没有使用mean，只是用了scale，那mean那一项，都写成0应该就可以了，对吗？
const float mean_vals[3] = { 0.0f, 0.0f, 0.0f };
const float norm_vals[3] = { 0.017f, 0.017f, 0.017f };
in.substract_mean_normalize(mean_vals, norm_vals);

**Comment by nihui** [comment]
```
in.substract_mean_normalize(0, norm_vals);
```
这样就可以
