### ISSUE TITLE
多线程不能加速mobilenet模型运行速度（树莓派b+）

### ISSUE THREAD

**Issue by zhijiewangLUNAID** [Tencent/ncnn#877]
我试图用多个线程来同时运行几个ncnn模型，每个线程独立load并执行一个不同的ncnn模型。所有模型的执行速度几乎相同,大概400ms运行一次。当我使用一个线程运行一个模型的时候确实显示大概花费了400ms. 但是当我使用两个线程独立运行两个模型的时候，却花费了大概800ms的时间，三个线程独立运行三个模型的时候大概1200ms的时间。但是我预计的是两个线程或三个线程应该大概还是花费和一个线程一个模型差不多的时间（400ms）或稍微多一点的时间（比如500-600ms). 哪位能帮我看一下吗？

环境：
Raspberry pi model b+

代码：
不同的输入，不同的模型，不同的extractors. 我的extractors或线程之间还有dependency吗?

**void threadTask( ncnn::Extractor ex, ncnn::Mat ins, ncnn::Mat class, ncnn::Mat loc)
{
for (int j=0;j<6;j++)
{
ex.extract(clas_name,class);
ex.extract(loc_name,loc);
}
}

ncnn::Net mobilenet[2];
for (int i=0;i<2;i++)
{
mobilenet[i].register_custom_layer("aaa", aaa_layer);
mobilenet[i].load_param("mobilenet.param");
mobilenet[i].load_model("mobilenet.bin");
};

ncnn::Extractor ex[2] = {mobilenet[0].create_extractor(),mobilenet[1].create_extractor()};

ex[0].set_num_threads(2);
ex[1].set_num_threads(2);
ex[0].input("Placeholder", ins[0]);
ex[1].input("Placeholder", ins[1]);

for(int i=0; i<2; i++)
{
tid[i] = std::thread(threadTask, ex[i], ins[i], classification[i], localization[i] );
}

for(int i = 0;i < 2; i++)
if(tid[i].joinable())
tid[i].join();**

**Comment by zhijiewangLUNAID** [comment]
追加。在我的代码例子里加载了同一个模型两次，像下面显示的。但是我确实测试过加载两个不同的模型。
for (int i=0;i<2;i++)
{
mobilenet[i].register_custom_layer("aaa", aaa_layer);
mobilenet[i].load_param("mobilenet.param");
mobilenet[i].load_model("mobilenet.bin");
};

**Comment by a-little-cat** [comment]
我在台式机上遇到了同样的现象,即多线程调用模型的前向计算,速度几乎没有提升.
ubuntu18.04 gcc7.4 cuda10.0,gtx1060,vulkan1.1.106.0

在追踪问题时,我发现2线程和8线程时的volatile gpu-util(gpu使用率)由40%提升到90%,但是显卡的功率都在40-50w左右.
我分析可能原因是,多线程通过vulkan调用显卡计算过程,没有享受到并行,依然使用串行.

具体位置在ncnn调用vulkan,vulkan调用硬件,还需要继续追.

**Comment by helloearth012** [comment]
@a-little-cat 
您刚讲了gpu的部分，那cpu的使用率是怎样的？几个cpu在运行？

**Comment by a-little-cat** [comment]
我的cpu是4核4线程的, 在单线程,2线程和8线程时候,cpu平均占用40%左右.
4核平均都在40%.

**Comment by ShanrenLi** [comment]
我也出现类似的问题，多个不同模型开启多个线程不会加快推理速度，而且还会提示“out of hardware queue 0 out of compute queue”的信息。

**Comment by nihui** [comment]
Raspberry Pi model b+ 是单核cpu，多线程不能加速是合理的
