### ISSUE TITLE
IOS中使用提供的预编译的库(android ios 预编译库 20190320 dbf2052),编译时报如下错误,该怎样解决? 新手,不懂IOS

### ISSUE THREAD

**Issue by jiashilei-1985** [Tencent/ncnn#878]
ld: '../ncnn.framework/ncnn(mat.cpp.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

工程禁用bitcode后,报如下错误
Undefined symbols for architecture arm64:
  "___kmpc_for_static_init_8", referenced from:
      _.omp_outlined..4 in ncnn(convolutiondepthwise.cpp.o)
      _.omp_outlined..7 in ncnn(convolutiondepthwise.cpp.o)
      _.omp_outlined..10 in ncnn(convolutiondepthwise.cpp.o)
      _.omp_outlined..1 in ncnn(deconvolutiondepthwise.cpp.o)
  "___kmpc_push_num_threads", referenced from:
      ncnn::copy_cut_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int, ncnn::Allocator*, int) in ncnn(mat.cpp.o)
      ncnn::resize_bilinear(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Allocator*, int) in ncnn(mat.cpp.o)
      ncnn::ELU::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(elu.cpp.o)
      ncnn::Exp::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(exp.cpp.o)
      ncnn::Log::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(log.cpp.o)
      ncnn::MVN::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const in ncnn(mvn.cpp.o)
      ncnn::BNLL::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(bnll.cpp.o)
      ...
  "___kmpc_global_thread_num", referenced from:
      ncnn::copy_cut_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int, ncnn::Allocator*, int) in ncnn(mat.cpp.o)
      ncnn::resize_bilinear(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Allocator*, int) in ncnn(mat.cpp.o)
      ncnn::ELU::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(elu.cpp.o)
      ncnn::Exp::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(exp.cpp.o)
      ncnn::Log::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(log.cpp.o)
      ncnn::MVN::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const in ncnn(mvn.cpp.o)
      ncnn::BNLL::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(bnll.cpp.o)
      ...
  "___kmpc_for_static_init_4", referenced from:
      _.omp_outlined. in ncnn(mat.cpp.o)
      _.omp_outlined..1 in ncnn(mat.cpp.o)
      _.omp_outlined..2 in ncnn(mat.cpp.o)
      _.omp_outlined..3 in ncnn(mat.cpp.o)
      _.omp_outlined..4 in ncnn(mat.cpp.o)
      _.omp_outlined. in ncnn(elu.cpp.o)
      _.omp_outlined. in ncnn(exp.cpp.o)
      ...
  "___kmpc_for_static_fini", referenced from:
      _.omp_outlined. in ncnn(mat.cpp.o)
      _.omp_outlined..1 in ncnn(mat.cpp.o)
      _.omp_outlined..2 in ncnn(mat.cpp.o)
      _.omp_outlined..3 in ncnn(mat.cpp.o)
      _.omp_outlined..4 in ncnn(mat.cpp.o)
      _.omp_outlined. in ncnn(elu.cpp.o)
      _.omp_outlined. in ncnn(exp.cpp.o)
      ...
  "___kmpc_fork_call", referenced from:
      ncnn::Mat::substract_mean_normalize(float const*, float const*) in ncnn(mat.cpp.o)
      ncnn::copy_cut_border(ncnn::Mat const&, ncnn::Mat&, int, int, int, int, ncnn::Allocator*, int) in ncnn(mat.cpp.o)
      ncnn::resize_bilinear(ncnn::Mat const&, ncnn::Mat&, int, int, ncnn::Allocator*, int) in ncnn(mat.cpp.o)
      ncnn::ELU::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(elu.cpp.o)
      ncnn::Exp::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(exp.cpp.o)
      ncnn::Log::forward_inplace(ncnn::Mat&, ncnn::Option const&) const in ncnn(log.cpp.o)
      ncnn::MVN::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const in ncnn(mvn.cpp.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by nihui** [comment]
openmp.framework 一起用
