### ISSUE TITLE
mobilenetv2 ssd lite run error

### ISSUE THREAD

**Issue by jinfagang** [Tencent/ncnn#882]
Converting mobilenetv2 ssdlite model for voc from here:  https://github.com/chuanqi305/MobileNetv2-SSDLite

it can runs on caffe and can successfully convert into nccn model, but run time error when using ncnn:
```
find_blob_index_by_name data_splitncnn_6 failed
find_blob_index_by_name data_splitncnn_6 failed
find_blob_index_by_name data_splitncnn_5 failed
find_blob_index_by_name data_splitncnn_4 failed
find_blob_index_by_name data_splitncnn_3 failed
find_blob_index_by_name data_splitncnn_2 failed
find_blob_index_by_name data_splitncnn_1 failed
find_blob_index_by_name data_splitncnn_0 failed
fopen ../models/ncnn/mb2_ssdlite_voc_voc.bin failed

```

Any idea?

**Comment by nihui** [comment]
upgrade your prototxt to new version, which has dedicated "Input" layer
https://github.com/Tencent/ncnn/wiki/how-to-use-ncnn-with-alexnet#convert-to-ncnn-model
