### ISSUE TITLE
骁龙625 使用1-8核运算，set_omp_num_threads()，试了1-8，运算时间没有变化

### ISSUE THREAD

**Issue by helloearth012** [Tencent/ncnn#883]
625是8个A53， Android， Neon开启，不分大小核，使用snap dragon profiler, 手机在运行我的程序之前, CPU 4, 5, 6, 7是在运行当中的。0， 1， 2， 3属于idle。

之后在我的程序中(caffe ->NCNN), set_omp_num_threads()，1-8都尝试了，运行时间没有变化。

看到其他人的运行结果，一般是set omp num threads为2的时候，运行速度有所提升。

@nihui NCNN是否有API指定在某个特定function内使用哪个核？还是需要用omp的API

**Comment by nihui** [comment]
可以参考下 benchmark/benchncnn.cpp 的写法
