### ISSUE TITLE
ncnn2mem find_blob_index_by_name failed

### ISSUE THREAD

**Issue by hackeritchy** [Tencent/ncnn#885]
keras模型转换到onnx之后，再使用onnx2ncnn转换没有报错，但是在工程中调用的时候出现大量find_blob_index_by_name failed报错。于是我将转换好的ncnn模型再使用ncnn2mem转换到.id.h
.mem.h文件，也出现find_blob_index_by_name_failed 问题， 无法正常使用。
请问有人知道如何解决嘛

**Comment by DZ9** [comment]
请问你是怎么解决的呀

**Comment by HLIG** [comment]
请问怎么解决的啊

**Comment by allanruin** [comment]
请问怎么解决的哟。

**Comment by wanglaotou** [comment]
请问怎么解决的啊

**Comment by znsoftm** [comment]
使用mem时，需要用id作为输入输出节点的名字，从xx.id.h中查看，比如以前是in,刚id为BLOB_in , 输出也类推

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
