### ISSUE TITLE
resize_bilinear出现Segmentation fault

### ISSUE THREAD

**Issue by lakehui** [Tencent/ncnn#886]
resize_bilinear(img, in, 192, 54);  
img的大小是240x480x3;
resize_bilinear报Segmentation fault。

**Comment by nihui** [comment]
thanks for your bug report !

**Comment by lakehui** [comment]
`static void resize_bilinear_image(const Mat& src, Mat& dst)
{
    int w = dst.w;
    int h = dst.w;`
看源码里面h的赋值好像有问题，看到下面resize_bicubic_image函数也是一样的问题。

**Comment by nihui** [comment]
已经修改了
