### ISSUE TITLE
hisiv500编译出错，scalar out of range for multiply instruction

### ISSUE THREAD

**Issue by lvyes1988** [Tencent/ncnn#887]
文件：ncnn/src/layer/arm/convolutiondepthwise_3x3_int8.h
函数：convdw3x3s2_int8_requant_neon

Error: scalar out of range for multiply instruction -- `vmull.s16 q7,d30,d8[0]'
Error: scalar out of range for multiply instruction -- `vmull.s16 q8,d31,d8[0]'
Error: scalar out of range for multiply instruction -- `vmull.s16 q9,d10,d8[1]'
Error: scalar out of range for multiply instruction -- `vmull.s16 q10,d11,d8[1]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q7,d12,d8[2]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q8,d13,d8[2]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q7,d30,d8[3]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q8,d31,d8[3]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q9,d10,d9[0]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q10,d11,d9[0]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q7,d12,d9[1]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q8,d13,d9[1]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q7,d30,d9[2]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q8,d31,d9[2]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q9,d10,d9[3]'
Error: scalar out of range for multiply instruction -- `vmlal.s16 q10,d11,d9[3]'

**Comment by kalcohol** [comment]
@lvyes1988 你是如何解决这个问题的？我没有在 v500 工具链上遇到这个问题，但在 arm-himix100 上遇到了

**Comment by cyf518** [comment]
@kalcohol
我也遇到了同样的问题，请问你解决了没有？

**Comment by nihui** [comment]
duplicate of https://github.com/Tencent/ncnn/issues/888
