### ISSUE TITLE
3D convolution support

### ISSUE THREAD

**Issue by WIll-Xu35** [Tencent/ncnn#889]
I'm trying to implement ECO (Efficient Convolutional Network for Online Video Understanding) on ncnn. Does ncnn support 3d conv layer?

If not, I'm trying to implement a workaround by combining some of the data dimensions and need to check if ncnn support it. For example, a layer of the ECO network has input size (3(batch size), 3(channel number), 12(time span), 224(image width), 224(image height)), is there any support for changing data blob of this size to (3*12, 3, 224, 224)?

**Comment by nihui** [comment]
ncnn do not support 3d conv. In fact, I think it is hard to implement 3d operators in ncnn because the Mat data storage only has three dims at most at the moment.

**Comment by WIll-Xu35** [comment]
@nihui Does ncnn support batch processing? If it does, I'm thinking to transform 5 dimension data to 4 dimension data to do 3D conv instead. Is there any way to transform data of size (3(batch size), 3(channel number), 12(time span), 224(image width), 224(image height)) to (36, 3, 224, 224), combining the batch size and time span channel?

**Comment by nihui** [comment]
batch processing is not supported
