### ISSUE TITLE
4核armv8处理器，开了多线程加速效果不明显，求解？

### ISSUE THREAD

**Issue by boundles** [Tencent/ncnn#89]
如题。

**Comment by BKZero** [comment]
同问

**Comment by Vandermode** [comment]
你把线程开大些会有一定加速，但是没有naive版本提升的明显。 这是因为arm版本neon内部实现的时候没有过多考虑openmp的优化，仅仅是简单的在外面包了一层#paragma omp parallel for 。属于正常现象。

**Comment by xindongzhang** [comment]
如果你用的电脑是mac，ndk编译的时候，find openmp可能会有点问题，你检查一下cmake的输出确认下；换个ubunut的电脑编译就好了。

**Comment by Justin-bin** [comment]
我是开加速没有效果，怎么破。。

**Comment by asas1235813** [comment]
我也是开加速没有效果....

**Comment by nihui** [comment]
建议先跑下 ncnn 的 benchncnn 程序看看

**Comment by nihui** [comment]
wiki how to build 更新了树莓派3和arm-linux交叉编译方法，可参考
