### ISSUE TITLE
ncnn为什么无法读取量化模型？

### ISSUE THREAD

**Issue by MayLuo123** [Tencent/ncnn#892]
我用caffe-int8-convert-tools和caffe2ncnn工具，转换caffe模型为8位ncnn模型。在用ncnn框架读取量化模型时出现如下错误:ModelBin read index_array  failed 0
                                         layer load_model 6 failed
请问谁遇到过类似的问题，可以帮我解答一下吗？谢谢！

**Comment by nihui** [comment]
如果是git上的版本，caffe-int8-convert-tools 和 ncnn 都要更新到最新的

**Comment by BUG1989** [comment]
请再确认下 caffe2ncnn是用最新代码生成的

**Comment by MayLuo123** [comment]
好的，谢谢

**Comment by MayLuo123** [comment]
再请教以下两个问题：
1为什么我用caffe2ncnn工具转换后的ncnn模型，即使在不量化的情况下性能也较之前变差很多？
2量化后的ncnn模型性能变得一塌糊涂，是否与用caffe-int8-convert-tools工具生成的table有关？该工具中校准图像的选择对结果的影响有多大？选择校准图像有什么原则？

**Comment by MayLuo123** [comment]
ncnn和工具已采用最新版本，模型可以正确读取，就是性能较差。

**Comment by BUG1989** [comment]
@MayLuo123 
如果方便，能否详细说明下你所使用的网络模型以及caffe2ncnn的参数

**Comment by MayLuo123** [comment]
采用网络模型是mtcnn
caffe2ncnn参数(未量化):caffe2ncnn pnet.prototxt pnet.caffemodel pnet.param pnet.bin
                                       caffe2ncnn rnet.prototxt rnet.caffemodel rnet.param rnet.bin
                                       caffe2ncnn onet.prototxt onet.caffemodel onet.param onet.bin
caffe2ncnn参数(量化):caffe2ncnn pnet.prototxt pnet.caffemodel pnet.param pnet.bin 256 pnet.table
                                   caffe2ncnn rnet.prototxt rnet.caffemodel rnet.param rnet.bin 256 rnet.table
                                   caffe2ncnn onet.prototxt onet.caffemodel onet.param onet.bin 256 onet.table

**Comment by hanson-young** [comment]
我也出现了一样的问题：
ModelBin read index_array failed 0
layer load_model 207 failed
我用的是https://github.com/honghuCode/mobileFacenet-ncnn/tree/feature/mobilefacenet-mxnet2caffe提供的mobilefacenet caffe 模型，并且也用了最新的ncnn和caffe-int8-convert-tools工具

**Comment by FanglaiPeng** [comment]
> 
> 
> 再请教以下两个问题：
> 1为什么我用caffe2ncnn工具转换后的ncnn模型，即使在不量化的情况下性能也较之前变差很多？
> 2量化后的ncnn模型性能变得一塌糊涂，是否与用caffe-int8-convert-tools工具生成的table有关？该工具中校准图像的选择对结果的影响有多大？选择校准图像有什么原则？

同问

**Comment by mshiyu** [comment]
同问，感觉网络在安卓端运行的时候，int8版本的速度比fp32的慢一些，是有哪些可以再配置的吗？

**Comment by zxDeepDiver** [comment]
> 我也出现了一样的问题：
> ModelBin read index_array failed 0
> layer load_model 207 failed
> 我用的是https://github.com/honghuCode/mobileFacenet-ncnn/tree/feature/mobilefacenet-mxnet2caffe 提供的mobilefacenet caffe 模型，并且也用了最新的ncnn和caffe-int8-convert-tools工具

我也报这个错，用的也是最新的

**Comment by Zrufy** [comment]
anyone have solve this issue?

**Comment by nihui** [comment]
量化工具要和ncnn版本配套
https://zhuanlan.zhihu.com/p/370689914
20210507版本大幅优化int8推理速度，建议更新
