### ISSUE TITLE
vulkan about

### ISSUE THREAD

**Issue by bjthemost** [Tencent/ncnn#893]
初始化的时候  这样了一下:
#if NCNN_VULKAN
  ncnn::create_gpu_instance();
#endif // NCNN_VULKAN
....
....
 #if NCNN_VULKAN
        p_net_.use_vulkan_compute =true;
        r_net_.use_vulkan_compute =true;
        o_net_.use_vulkan_compute =true;

    result_faces.resize(0);
     p_net_.load_param("/opt/myprojs/models/ncnn/12net.param");
     p_net_.load_model("/opt/myprojs/models/ncnn/12net.bin");
......
#endif

然后调用 类方法 ,为啥 速度读变慢了呢 比不用 vulkan 的时候满了大概10倍 左右, 

但是跑 benchncnn,却比单纯用cpu 快10呗左右. 

显卡 titan xp 12G , i7-6700k

ncnn是最新版本?

why ? 呢?

**Comment by bjthemost** [comment]
ncnn 和 vulkan 是最新版本 刚刚download..

**Comment by bjthemost** [comment]
重新跑了一下 ncnn自带的例子....
SEE,,,,,,,,,,,
------
root@zlcats-B250M-D3V:/opt/gits/ncnn/build/examples# ./squeezenet cat.jpg 
[0 TITAN Xp]  queueC=2  queueT=1  memU=4294967295  memDL=7  memHV=9
use vulkan 
 time : 372.491
281 = 0.227178
282 = 0.221583
278 = 0.162667
root@zlcats-B250M-D3V:/opt/gits/ncnn/build/examples# ./squeezenet cat.jpg 
[0 TITAN Xp]  queueC=2  queueT=1  memU=4294967295  memDL=7  memHV=9
use vulkan 
 time : 356.011
281 = 0.227178
282 = 0.221583
278 = 0.162667
root@zlcats-B250M-D3V:/opt/gits/ncnn/build/examples# ./squeezenet cat.jpg 
 time : 19.5188
281 = 0.227176
282 = 0.221582
278 = 0.162667
root@zlcats-B250M-D3V:/opt/gits/ncnn/build/examples# ./squeezenet cat.jpg 
 time : 18.8032
281 = 0.227176
282 = 0.221582
278 = 0.162667 

//#if NCNN_VULKAN
//    squeezenet.use_vulkan_compute = true;
//    std::cout << "use vulkan "<<std::endl;
//#endif // NCNN_VULKAN
........
.......
.......

//#if NCNN_VULKAN
//    ncnn::create_gpu_instance();
//#endif // NCNN_VULKAN

这种方式使用 vulkan 还有啥 开关吗? 

谢谢.

**Comment by nihui** [comment]
因为mtcnn模型太小了，你换个大点的模型会有加速

**Comment by nihui** [comment]
另外，看到你是 squeezenet 单独跑一张图片，gpu第一张图片速度会慢，后面连续跑就快了

**Comment by bjthemost** [comment]
@nihui , 好像不是 模型大小的缘故.

下面 分别是 带vulkan(2-3ms左右的)  和不带vulkan(30ms左右的)

Debugging starts
&"warning: GDB: Failed to set controlling terminal: \345\257\271\350\256\276\345\244\207\344\270\215\351\200\202\345\275\223\347\232\204 ioctl \346\223\215\344\275\234\n"
[0 TITAN Xp]  queueC=2  queueT=1  memU=4294967295  memDL=7  memHV=9
 time in func : 29.1941
 time in func : 30.7671
 time in func : 30.7979
 time in func : 30.7761
 time in func : 31.1079
 time in func : 30.595
 time in func : 30.5198
 time in func : 31.7891
 time in func : 30.5869
 time in func : 30.2722
 time in func : 30.2729
 time in func : 30.301
 time in func : 30.249
 time in func : 29.8691
 time in func : 30.0601
 time in func : 29.99
 time in func : 30.375
 time in func : 30.0261
 time in func : 30.1311
 time in func : 29.9309
 time in func : 36.8621
 time in func : 31.595
 time in func : 32.7542
 time in func : 32.448
 time in func : 31.7261
 time in func : 31.656
 time in func : 29.9639
 time in func : 30.2971
 time in func : 30.928
 time in func : 29.9111
 time in func : 31.8279
 time in func : 30.1379
 time in func : 29.9001
 time in func : 30.022
 time in func : 30.0149
 time in func : 29.885
 time in func : 30.114
 time in func : 30.77
 time in func : 29.751
 time in func : 30.0781
 time in func : 30.613
 time in func : 29.9229
 time in func : 30.04
 time in func : 29.803
 time in func : 29.8611
 time in func : 29.957
 time in func : 29.865
 time in func : 30.1091
 time in func : 29.874
 time in func : 29.9109
 time in func : 30.481
 time in func : 30.0869
 time in func : 30.114
 time in func : 31.3611
 time in func : 36.1809
 time in func : 30.7461
 time in func : 30.387
 time in func : 30.625
 time in func : 29.9629
 time in func : 29.936
 time in func : 30.0291
 time in func : 29.9219
 time in func : 33.395
 time in func : 30.1499
 time in func : 29.8789
 time in func : 30.6411
 time in func : 30.104
 time in func : 29.6812
 time in func : 29.8599
 time in func : 30.0029
 time in func : 30.3269
 time in func : 29.8679
 time in func : 29.8298
 time in func : 29.7119
 time in func : 29.6799
 time in func : 29.4971
 time in func : 30.2229
 time in func : 29.8
 time in func : 29.533
 time in func : 29.7542
 time in func : 29.542
 time in func : 30.363
 time in func : 29.9199
 time in func : 29.7229
 time in func : 29.6611
 time in func : 29.9138
 time in func : 31.249
 time in func : 36.8379
 time in func : 31.9211
 time in func : 31.928
 time in func : 30.571
 time in func : 29.8931
 time in func : 29.7881
 time in func : 29.72
 time in func : 29.6941
 time in func : 30.624
 time in func : 29.9512
 time in func : 29.5549
 time in func : 39.479
 time in func : 30.3909
530 = 1.000000
818 = 0.000000
111 = 0.000000
Debugging has finished

Debugging starts
&"warning: GDB: Failed to set controlling terminal: \345\257\271\350\256\276\345\244\207\344\270\215\351\200\202\345\275\223\347\232\204 ioctl \346\223\215\344\275\234\n"
[0 TITAN Xp]  queueC=2  queueT=1  memU=4294967295  memDL=7  memHV=9
use vulkan 
load model FILE * fp [net.cpp 643,vkdev :0x5555558d0000
 time in func : 15.2068
 time in func : 11.3411
 time in func : 10.6069
 time in func : 11.229
 time in func : 11.5891
 time in func : 12.333
 time in func : 12.5469
 time in func : 11.9949
 time in func : 10.6602
 time in func : 11.2551
 time in func : 11.7771
 time in func : 4.54907
 time in func : 10.5159
 time in func : 11.9302
 time in func : 14.2859
 time in func : 5.01782
 time in func : 2.91992
 time in func : 2.89111
 time in func : 2.87915
 time in func : 3.63794
 time in func : 2.88818
 time in func : 2.87109
 time in func : 2.85815
 time in func : 2.87305
 time in func : 3.63501
 time in func : 2.88013
 time in func : 2.86401
 time in func : 2.86792
 time in func : 3.00903
 time in func : 3.6062
 time in func : 2.87378
 time in func : 2.92896
 time in func : 2.70508
 time in func : 2.70508
 time in func : 3.38501
 time in func : 2.69995
 time in func : 2.7002
 time in func : 2.69897
 time in func : 2.7019
 time in func : 3.0271
 time in func : 2.83301
 time in func : 2.71899
 time in func : 2.69995
 time in func : 2.80396
 time in func : 2.91016
 time in func : 3.19897
 time in func : 2.71411
 time in func : 2.7019
 time in func : 2.70898
 time in func : 3.56714
 time in func : 2.74902
 time in func : 2.73901
 time in func : 3.15308
 time in func : 3.66797
 time in func : 2.72998
 time in func : 2.72607
 time in func : 2.69995
 time in func : 2.81885
 time in func : 3.4939
 time in func : 2.729
 time in func : 2.71484
 time in func : 2.69604
 time in func : 2.69287
 time in func : 3.48096
 time in func : 2.69897
 time in func : 2.70386
 time in func : 2.70898
 time in func : 2.71997
 time in func : 11.583
 time in func : 7.04492
 time in func : 11.3069
 time in func : 18.4731
 time in func : 8.58594
 time in func : 8.31787
 time in func : 8.99512
 time in func : 9.32593
 time in func : 9.34009
 time in func : 9.323
 time in func : 9.31787
 time in func : 9.31396
 time in func : 9.30713
 time in func : 7.33105
 time in func : 8.52002
 time in func : 7.66089
 time in func : 6.37109
 time in func : 5.82104
 time in func : 5.07202
 time in func : 7.74805
 time in func : 8.05298
 time in func : 8.61719
 time in func : 9.05786
 time in func : 9.48022
 time in func : 7.49902
 time in func : 7.49805
 time in func : 7.64185
 time in func : 5.83081
 time in func : 8.03491
 time in func : 7.94702
 time in func : 7.48706
 time in func : 7.87695
530 = 1.000000
818 = 0.000000
111 = 0.000000
Debugging has finished

需要做一堆堆的初始化工作,
