### ISSUE TITLE
May I need to custom layers in ncnn or replace  unsupported ops in pytorch? 

### ISSUE THREAD

**Issue by gfjiangly** [Tencent/ncnn#894]
I train a model using pytorch, than transfer to ncnn model file, but some ops are not supported.

**Comment by nihui** [comment]
try pytorch -> onnx -> ncnn path
you may also interest in https://github.com/daquexian/onnx-simplifier project for removing redundant operators.

**Comment by gfjiangly** [comment]
> try pytorch -> onnx -> ncnn path
> you may also interest in https://github.com/daquexian/onnx-simplifier project for removing redundant operators.

Can I edit ncnn.param file directly and remove redundant operators? Is the model weight in ncnn loaded according to the name in the param file?

**Comment by nihui** [comment]
If you change a layer which contains weight, like convolution etc, loading the original model file will probably fail
https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure

for the operator not supported but known unused, you can register noop to skip it
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#layer-xyz-not-exists-or-registered

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
