### ISSUE TITLE
about   vkEnumeratePhysicalDevices

### ISSUE THREAD

**Issue by bjthemost** [Tencent/ncnn#896]
多显卡 ,到这里 报错
[root@hhsvr objs]# ./thuAIFaceSDK 
vkEnumeratePhysicalDevices failed-1  -3 
---------
 uint32_t physicalDeviceCount = 0;
    ret = vkEnumeratePhysicalDevices(g_instance, &physicalDeviceCount, 0);
    if (ret != VK_SUCCESS)
    {
        fprintf(stderr, "vkEnumeratePhysicalDevices failed-1  %d\n", ret);
        return -1;
    }
--------------
显卡是这样的..
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.73       Driver Version: 410.73       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
| 32%   38C    P0    28W / 120W |      0MiB /  6078MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 00000000:02:00.0 Off |                  N/A |
| 26%   34C    P0    43W / 250W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P4            Off  | 00000000:83:00.0 Off |                  N/A |
| N/A   46C    P0    23W /  75W |      0MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 1070    Off  | 00000000:84:00.0 Off |                  N/A |
| 28%   40C    P0    35W / 151W |      0MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
单卡是没问题的. 是不是不同显卡类型的原因?
-------------------

**Comment by bjthemost** [comment]
不好意思 copy的字体比较 大..sorry 没有其他意思.

**Comment by nihui** [comment]
你试试看 vulkaninfo 工具是否能正常读出设备信息

**Comment by bjthemost** [comment]
okay 稍等
z

发自我的 iPhone

**Comment by bjthemost** [comment]
[root@hhsvr bin]# ./vulkaninfo 
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.101

/home/lunarg/sdk-build/Vulkan-Tools/vulkaninfo/vulkaninfo.c:5028: failed with VK_ERROR_INITIALIZATION_FAILED
-------
读不出来, 我貌似知道原因了. 这个是centos7.4, vulkan 是从ubuntu18.04 copy过来的 .rebuilding...

**Comment by bjthemost** [comment]
搞定了

发自我的 iPhone

**Comment by Shengxiaolin** [comment]
你好，遇到了类似的错误，centos编译vulkan ncnn通过，但是测试squeezenet时出现vkEnumeratePhysicalDevices failed -3的错误，vulkaninfo无法获取设备信息，请问是如何解决的呢？1080单卡 驱动版本435.27.01 vulkan版本1.1.92.1

**Comment by bjthemost** [comment]
在本机（有物理显卡）运行 不能在远端运行


发自我的iP6+1

**Comment by AIwzx** [comment]
大佬怎么解决的啊   我也是同样错误 Ubuntu18.04  2080TI显卡 驱动440.100 版本1.1.114

**Comment by AIwzx** [comment]
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
==========
VULKANINFO
==========

Vulkan Instance Version: 1.1.114

/root/sdk-build/1.1.114.0/source/Vulkan-Tools/vulkaninfo/vulkaninfo.c:5884: failed with VK_ERROR_INITIALIZATION_FAILED
