### ISSUE TITLE
arm_neon宏

### ISSUE THREAD

**Issue by zealerww** [Tencent/ncnn#898]
问个小问题，我看源文件都是通过__ARM_NEON来开启neon部分的代码，这个宏最初是在哪里定义的呢，我看$ANDROID_NDK/build/cmake/android.toolchain.cmake也没有定义。要自己编译时手动定义下吗？

**Comment by nihui** [comment]
这是编译器定义的，armv7 上 -mfpu=neon，aarch64 自动定义
