### ISSUE TITLE
pytorch->onnx->ncnn 推理失败，到中间某层后blob维度全为0

### ISSUE THREAD

**Issue by hanfanggithub** [Tencent/ncnn#899]
求助，有人遇到类似的情况吗

**Comment by GatzZ** [comment]
+1 我也遇到同样问题

**Comment by hanfanggithub** [comment]
> +1 我也遇到同样问题

我不知道你具体情况是什么样，我的原因是转shufflev2的时候onnx >ncnn slice层的问题 ， 如果要用shufflev2可以试一下 pytorch >caffe>ncnn

**Comment by GatzZ** [comment]
> > +1 我也遇到同样问题
> 
> 我不知道你具体情况是什么样，我的原因是转shufflev2的时候onnx >ncnn slice层的问题 ， 如果要用shufflev2可以试一下 pytorch >caffe>ncnn

我发现是onnxmltools转keras->onnx，onnx的结果不对。现在我用keras->coreml->onnx->ncnn就可以了

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
