### ISSUE TITLE
How to run the example project?

### ISSUE THREAD

**Issue by akbarxie** [Tencent/ncnn#9]
我使用的是android studio，不知道你的example project是基于什么平台开发的，怎样才能把它加入到android project中？

**Comment by nihui** [comment]
导入 ant 工程

**Comment by dodola** [comment]
[app-debug.apk.zip](https://github.com/Tencent/ncnn/files/1169575/app-debug.apk.zip)
给你个apk，先看看

**Comment by dangbo** [comment]
@dodola 安装失败

**Comment by lijian8454088** [comment]
@dodola 直接下载失败

**Comment by nihui** [comment]
首先编译好 ncnn，或者用 releases 里头编译好的 ncnn android lib
jni 目录里调整 Android.mk 里头的路径 NCNN_INSTALL_PATH，ndk-build
工程目录里 ant debug

**Comment by lybvinci** [comment]
最最开始，按照up主文档，编译.a文件。
然后用android studio 导入功能example，导入Eclipse工程类似项目的那个选项，等待生成完毕。在app目录下的build.gradle 安卓中括号里面配置如下：
sourceSets.main {
        jniLibs.srcDirs = ["src/main/libs"]
        jni.srcDirs=[]
    }
手动打开到jni目录，用命令行执行 ndk-build 没有问题，应该就编译安卓so到libs目录下。再run到设备上。

**Comment by telefire** [comment]
hi, 最新的Android SDK的tools里已经没有 ant了，所以 ant debug编译不了。。。
lybvinci的方法直到 ndk-build都是没有问题的， libs 文件会被编译到 ncnn/examples/squeezencnn 下，但是运行 Android Studio project会报错

```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.tencent.squeezencnn-2/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.squeezencnn-2/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libsqueezencnn.so"
```

把
```
sourceSets.main {
jniLibs.srcDirs = ["src/main/libs"]
jni.srcDirs=[]
}
```
改成
```
sourceSets.main {
jniLibs.srcDirs = ["libs"]
jni.srcDirs=[]
}
```
libsqueezencnn.so 还是找不到，不知道如何解决这个lib引用不到的问题。。。。

**Comment by akbarxie** [comment]
@lybvinci ，我按照你的方法试了一下，android studio生产了一个squeezencnn的项目，不过
![image](https://user-images.githubusercontent.com/17984011/28607209-5db40436-720d-11e7-90f2-1387f2ac8640.png)
Error:error: ld returned 1 exit status
在编译的时候还是有出现链接不成功的问题。不知道你有没有遇到，有什么解决方法

**Comment by akbarxie** [comment]
一行一行的检查之后，我找到了问题是这一行导致的
static ncnn::Net squeezenet;（squeezencnn_jni.cpp）
是这一行导致的

**Comment by ccnuxjg** [comment]
![image](https://user-images.githubusercontent.com/30468918/28621685-59263286-7244-11e7-987f-f6a7af722e83.png)

编译出错？是我的姿势出错了么？

**Comment by nihui** [comment]
libncnn.a 的架构和 app 的不一样，比如 libncnn.a 并没有编译 android x86 的版本

**Comment by ccnuxjg** [comment]
@nihui 去掉x86的版本就可以了，谢谢

**Comment by akbarxie** [comment]
我也说一下我的问题吧，用@lybvinci 的方法可以实现构造ncnn的例子。只需要在build.gradle(app)加上这么一句：
ndk {
            moduleName "ncnn"
            abiFilters  'armeabi-v7a'
        }
估计@ccnuxjg  也要加上这么一句就可以跑了

**Comment by dangbo** [comment]
https://github.com/dangbo/ncnn-mobile use ncnn in Android and iOS
