### ISSUE TITLE
armeabi-v7a_hard with NEON模式编译失败

### ISSUE THREAD

**Issue by VivienFu** [Tencent/ncnn#90]
-DANDROID_ABI="armeabi-v7a with NEON"这个模式下编译没有问题，可以正常生成并运行。

DANDROID_ABI="armeabi-v7a with NEON"，ndk是不是不支持hard模式armeabi-v7a-hard with NEON呀？我用这个编译，发现想要查找的ndk包含目录中没有armeabi-v7a-hard文件夹，只有armeabi-v7a文件夹 ，所以造成最终报错

**Comment by VivienFu** [comment]
问题解决了，我用的NDK版本是r15b, 从r14开始，ANDROID_ABI就不支持armeabi-v7a-hard了。
切换成r10e，正常编译生成和执行了。
本来想试试hardfp是不是能快一点儿，不过好像并没有，可能是因为数据是float*类型的？

armeabi-v7a with NEON，lightCNN 200次的平均值147ms
armeabi-v7a-hard with NEON， lightCNN 200次的平均值145ms

**Comment by nihui** [comment]
最耗时的代码都已经汇编实现了，编译参数的优化很有限

**Comment by sunjunlishi** [comment]
在哪个地方配置 armeabi-v7a with NEON
