### ISSUE TITLE
MXNET模型转化失败

### ISSUE THREAD

**Issue by yangchengtest** [Tencent/ncnn#900]
LinearRegressionOutput not supported yet!
# grad_scale=1
Custom not supported yet!
# op_type=negativemining

NCNN不支持MXNET LinearRegressionOutput和CUSTOM OP转化么？
谢谢。

**Comment by nihui** [comment]
训练用的 op 可以不转换
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-throw-error#layer-xyz-not-exists-or-registered

**Comment by jackdonghai** [comment]
@nihui   训练用的op可以不用转是指，直接在param中删除不用的几个op吗？
