### ISSUE TITLE
memalign error

### ISSUE THREAD

**Issue by Royzon** [Tencent/ncnn#901]
easley@ubuntu:~/work/ncnn-master/build-arm-linux-gnueabihf$ cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/arm-linux-gnueabihf.toolchain.cmake ..
-- CMAKE_TOOLCHAIN_FILE = /home/easley/work/ncnn-master/toolchains/arm-linux-gnueabihf.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /home/easley/work/ncnn-master/build-arm-linux-gnueabihf/install
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /home/easley/work/face_recognition/face/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /home/easley/work/face_recognition/face/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/easley/work/face_recognition/face/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /home/easley/work/face_recognition/face/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/easley/work/ncnn-master/build-arm-linux-gnueabihf
easley@ubuntu:~/work/ncnn-master/build-arm-linux-gnueabihf$ make
Scanning dependencies of target generate-spirv
[  0%] Built target generate-spirv
Scanning dependencies of target ncnn
[  1%] Building CXX object src/CMakeFiles/ncnn.dir/allocator.cpp.o
In file included from /home/easley/work/ncnn-master/src/allocator.cpp:15:
/home/easley/work/ncnn-master/src/allocator.h: In function ‘void* ncnn::fastMalloc(size_t)’:
/home/easley/work/ncnn-master/src/allocator.h:62:12: error: ‘memalign’ was not declared in this scope
     return memalign(MALLOC_ALIGN, size);
            ^~~~~~~~
/home/easley/work/ncnn-master/src/allocator.h:62:12: note: suggested alternative: ‘max_align_t’
     return memalign(MALLOC_ALIGN, size);
            ^~~~~~~~
            max_align_t
src/CMakeFiles/ncnn.dir/build.make:62: recipe for target 'src/CMakeFiles/ncnn.dir/allocator.cpp.o' failed
make[2]: *** [src/CMakeFiles/ncnn.dir/allocator.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'src/CMakeFiles/ncnn.dir/all' failed
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/de7071452d3f99cb1f053ce61c342dfef96fcc14
