### ISSUE TITLE
ncnn and vulkan ON android 7.1

### ISSUE THREAD

**Issue by bjthemost** [Tencent/ncnn#903]
哪位大师 能提供一下 可以在 android7.0 以上版本 run起来的最新 ncnn+vulkan的工程的例子, arm64-v8a.
请吃饭.

**Comment by jeremycheong** [comment]
rk3399 安卓7.1亲测不行，可能要让oem厂商支持……

**Comment by bjthemost** [comment]
> rk3399 安卓7.1亲测不行，可能要让oem厂商支持……

okay  谢谢

**Comment by nihui** [comment]
you can refer https://github.com/Tencent/ncnn/wiki/vulkan-conformance-test to see the current supported devices

**Comment by bjthemost** [comment]
okay thanks ，i m on my way ：）
z

发自我的 iPhone
