### ISSUE TITLE
ncnn 模型 在ubuntu下较慢

### ISSUE THREAD

**Issue by wangxm345566462** [Tencent/ncnn#905]
mtcnn(1280 * 720)  windwos 下 100 - 120ms    i7-7700HQ CPU @ 2.80GHz
mtcnn(1280 * 720)  ubuntu 下 300 - 350ms      i7-6800K CPU @ 3.40GHz

**Comment by nihui** [comment]
ncnn 在 pc cpu 上没有优化，慢是正常的
