### ISSUE TITLE
FPN-MBv2 Caffe

### ISSUE THREAD

**Issue by yyfyan** [Tencent/ncnn#909]
使用Caffe搭了个MBv2-FPN-SSD，使用了新的层做上采样（最近邻插值），而没有使用caffe中的DeConv，如何转换到ncnn.
有大神做过吗？

**Comment by zhouleidcc** [comment]
你用的是upsample层吗，如果是可以用deconv来替换

**Comment by yyfyan** [comment]
@zhouleidcc 
先用新的upsample训练好模型，然后把它改为DeConv，最后再转换为ncnn模型，是这样吗，，好像是的。。
