### ISSUE TITLE
mac 编译ncnn

### ISSUE THREAD

**Issue by jj8401** [Tencent/ncnn#91]
mac编译ncnn出现这个问题，是什么原因呢
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(opencv.cpp.o) has no symbols

[ 93%] Linking CXX static library libncnn.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(opencv.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libncnn.a(opencv.cpp.o) has no symbols
[ 93%] Built target ncnn
Scanning dependencies of target ncnn2mem
[ 95%] Building CXX object tools/CMakeFiles/ncnn2mem.dir/ncnn2mem.cpp.o
[ 97%] Linking CXX executable ncnn2mem
[ 97%] Built target ncnn2mem
[100%] Linking CXX executable caffe2ncnn
[100%] Built target caffe2ncnn
➜  build git:(master) ✗ make install
[ 86%] Built target ncnn
[ 95%] Built target caffe2ncnn
[100%] Built target ncnn2mem
Install the project...
-- Install configuration: "release"
-- Installing: /Users/yangguangdejianjian/code/ncnn/build/install/lib/libncnn.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/yangguangdejianjian/code/ncnn/build/install/lib/libncnn.a(opencv.cpp.o) has no symbols
-- Installing: /Users/yangguangdejianjian/code/ncnn/build/install/include/blob.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build/install/include/cpu.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build/install/include/layer.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build/install/include/mat.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build/install/include/net.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build/install/include/opencv.h
-- Installing: /Users/yangguangdejianjian/code/ncnn/build/install/include/platform.h

**Comment by logic1988** [comment]
cmake 命令中增加 -DNCNN_OPENMP=OFF 参数, 否则会出现上面错误, 即使mac上已经安装了openmp版本的gcc

**Comment by nihui** [comment]
has no symbols 表示 opencv.cpp 里没有编译代码，因为 NCNN_OPENCV 默认是禁用的，这是正常现象
