### ISSUE TITLE
winograd方法比sgemm方法慢很多

### ISSUE THREAD

**Issue by Isco-Chen** [Tencent/ncnn#910]
你好，我的平台是ARM A76，发现跑网络的时候ncnn根据网络结构默认使用的方法是use_winograd3x3，但是时间比较慢；后来我手动改成了use_sgemm1x1，性能提升了很多，两者大概是1:0.6的关系（use_winograd3x3 1000ms，use_sgemm1x1 600ms），请问下这个正常吗？而且我发现use_sgemm1x1虽然平均性能提升了，但是每次跑的时间波动很多，最低能到300多ms，最高超过了1000ms，这个是不是因为openmp开了多线程后不稳定导致的？我把线程数设为1，就稳定很多，基本上都在800ms上下（use_sgemm1x1）。

**Comment by BUG1989** [comment]
use_winograd3x3：针对conv3x3s1的计算；
use_sgemm1x1：针对conv1x1s1的计算。
两者互不干扰的，你是跑的什么网络模型呀？能否使用benchncnn做一下基础测试？

**Comment by Isco-Chen** [comment]
啊，是我错了。那如果我手动把use_winograd3x3设成false，是不是3x3kernel的卷积就是用gemm的方法计算了？

**Comment by BUG1989** [comment]
fp32的话，应该是调用的direct conv，int8会调用sgemm
