### ISSUE TITLE
How to convert shufflenetv2 to ncnn

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#912]
I see an example of shufflenet with pytorch implementation here. https://github.com/Tencent/ncnn/blob/master/examples/shufflenetv2.cpp

I want to convert my own customized shufflenetv2 model to ncnn from pytorch.
Which tool should I use to do the same?

**Comment by soham24** [comment]
@nihui

**Comment by soham24** [comment]
@tamworth @LittlePeng @nihui 
Any update?

**Comment by LittlePeng** [comment]
pytorch convert tool:
ncnn/tools/pytorch/readme.txt

But you need add ShuffleChannel layer support

**Comment by soham24** [comment]
@LittlePeng  thank you . 
can you provide any link/docs where I can get steps for adding custom layers

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/ad9e0a97255eeb179efa9969c2d481a1ab250549
shufflechannel is now supported
