### ISSUE TITLE
ndk版本与OMP启用

### ISSUE THREAD

**Issue by ysh329** [Tencent/ncnn#918]
发现一个问题，如果用ndk-r19c，默认就没有启用omp（编译时候会出很多warning，那个变量没有用到），但用了r18b就不会有这个问题。

- 环境：Ubuntu16.04 docker容器
- 编译版本：交叉编译 Android 版

**Comment by ysh329** [comment]
Add CPU benchmark of Qualcomm Snapdragon 835 by ysh329 · Pull Request #916 · Tencent/ncnn
https://github.com/Tencent/ncnn/pull/916

**Comment by nihui** [comment]
r19c is not tested yet. r18b is fine.
