### ISSUE TITLE
转换后的model size有限制吗

### ISSUE THREAD

**Issue by gneworld** [Tencent/ncnn#92]
使用caffe2ncnn 转换后的model 在5~6M的时候 可以在手机上正常work，但当model在13M的时候发现在load model的时候回crash，请问ncnn对手机端的model size有限制吗，谢谢

**Comment by gneworld** [comment]
D/SqueezeNcnn( 5440): load_param 440 440
D/SqueezeNcnn( 5440): model len: 13182824
--------- beginning of crash
F/libc    ( 5440): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x97a5075c in tid 5440 (ent.squeezencnn)
I/DEBUG   ( 4594): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 4594): Build fingerprint: 
I/DEBUG   ( 4594): Revision: '0'
I/DEBUG   ( 4594): ABI: 'arm'
I/DEBUG   ( 4594): pid: 5440, tid: 5440, name: ent.squeezencnn  >>> com.tencent.squeezencnn <<<
I/DEBUG   ( 4594): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x97a5075c
I/DEBUG   ( 4594):     r0 66f6e630  r1 bedbf934  r2 6a2108c8  r3 6705a82d
I/DEBUG   ( 4594):     r4 66f6e630  r5 97a5075c  r6 bedbf934  r7 97a5075c
I/DEBUG   ( 4594):     r8 bedbf9c8  r9 bedbf9c4  sl bedbf9d0  fp 41f07800
I/DEBUG   ( 4594):     ip 00000000  sp bedbf8f0  lr 01306b47  pc 6705a842  cpsr 000f0030
I/DEBUG   ( 4594): 
I/DEBUG   ( 4594): backtrace:
I/DEBUG   ( 4594):     #00 pc 0003a842  /data/app/com.tencent.squeezencnn-2/lib/arm/libsqueezencnn.so
I/DEBUG   ( 4594):     #01 pc 00023153  /data/app/com.tencent.squeezencnn-2/lib/arm/libsqueezencnn.so
I/DEBUG   ( 4594):     #02 pc 0001b72d  /data/app/com.tencent.squeezencnn-2/lib/arm/libsqueezencnn.so (Java_com_tencent_squeezencnn_SqueezeNcnn_Init+256)
I/DEBUG   ( 4594):     #03 pc 000a2991  /system/lib/libart.so (art_quick_generic_jni_trampoline+32)
I/DEBUG   ( 4594):     #04 pc 000013fc  /dev/ashmem/dalvik-alloc space (deleted)
I/DEBUG   ( 4594): 
I/DEBUG   ( 4594): Tombstone written to: /data/tombstones/tombstone_05

**Comment by eeric** [comment]
应该没有吧，估计是模型转换的问题

**Comment by nihui** [comment]
没有限制
