### ISSUE TITLE
MTCNN with latest ncnn produce wrong result

### ISSUE THREAD

**Issue by StartNowX** [Tencent/ncnn#922]
Run mtcnn(with latest ncnn) to detect the same image, but result is not same. No error in load param and model, and squeeze net in example is also OK. And run mtcnn with version 20181228 can produce the right result.

**Comment by XIANG24** [comment]
Run mtcnn(with lasted ncnn) to detect the same image, but result is not same. No error in load param and model, and squeeze net in example is also OK. And run mtcnn with version 20181228 can produce the right result.

**Comment by Pinnh** [comment]
I meet the same problem ,You may need to change code to get data when refine face by RNet or ONet 

change
score.channel(0)[0] score.channel(1)[0]  
to 
score.channel(0)[0] score.channel(0)[1]

**Comment by nihui** [comment]
Pay attention to the memory layout of the output blob
https://github.com/Tencent/ncnn/wiki/FAQ-ncnn-produce-wrong-result#blob-may-have-channel-gap

Feel free to reopen issue if the problem is still not resolved
