### ISSUE TITLE
vulkan performance is same as cpu

### ISSUE THREAD

**Issue by ysh329** [Tencent/ncnn#923]
- mix2，snpadragon 835
- gpu adreno 540

跑出vulkan benchmark的性能和cpu一样，如果是powersave=1，跑出来的就是小核的cpu性能，如果是powersave=2，那就是大核的cpu性能

**Comment by ysh329** [comment]
看错了_(:з」∠)_，没啥问题正在编译vulkan-armv8-android

**Comment by feirenlg** [comment]
利用powersave可以在终端指定大小核运行吗？

**Comment by ysh329** [comment]
@feirenlg 可以
