### ISSUE TITLE
为什么Extractor类没有自己的构造函数？

### ISSUE THREAD

**Issue by GaussRieman** [Tencent/ncnn#926]
出于跨框架的考虑，想对各个model做一层抽象。想在ncnn_model类中保存Net和Extractor，而不需要每次都新创建一个Extractor对象，但是目前Extractor不支持其他构造，只能通过Net的create_extractor()方法创建。

请问这个能否考虑修改呢？添加一个构造函数？

**Comment by GaussRieman** [comment]
@nihui

**Comment by nihui** [comment]
因为就是需要你每次创建新的 extractor
可以设置 allocator 避免重复申请和释放内存
