### ISSUE TITLE
如何配置fp16进行计算

### ISSUE THREAD

**Issue by Isco-Chen** [Tencent/ncnn#927]
你好，想问下我的模型参数默认都是fp32类型的，但是我计算时可以损失一些精度但速度要快点，我能不能有办法配置成fp16的数据类型进行计算，怎么配置？

**Comment by Isco-Chen** [comment]
看了下代码，ARM侧优化尤其是neon优化都是float32x4类型的向量进行的计算，是不是意味着没办法配置成fp16进行计算了？

**Comment by ivoxx** [comment]
2019.6.11版本的支持gpu的fp16了

gpu fp16 packed 优化，支持全部gpu
gpu fp16 storage 优化，支持绝大多数桌面gpu
gpu fp16 arithmetic 优化，默认关闭
gpu fp16p fp16s fp16a int8s in8a 控制开关

**Comment by nihui** [comment]
gpu 参考 https://github.com/Tencent/ncnn/wiki/vulkan-notes#control-storage-and-arithmetic-precision

**Comment by jiyinghui39** [comment]
@nihui 
借这个issue求问下，arm A35,A53平台是否支持cpu上fp16运算。如果可以的话如何实现？感谢

**Comment by nihui** [comment]
> @nihui
> 借这个issue求问下，arm A35,A53平台是否支持cpu上fp16运算。如果可以的话如何实现？感谢

fp16运算需要硬件支持 armv8.2
fp16存储都是可以的
另外bf16存储也都是支持的

**Comment by jiyinghui39** [comment]
fp16，bf16储存都如何参考实现？
这样我理解，如果在A35平台上，使用fp16的模型存储。
1.可以减少模型的体积为原来的一半。还可以减少推理过程中内存的占用吗？
2.可以提供加速效果吗。如果使用fp16存储，fp32做运算，我理解cpu的占用会比之前fp32运算多一点。因为有转换的开销。
麻烦指正我的理解对不对？感谢@nihui

**Comment by jiyinghui39** [comment]
@nihui 帮忙解答下，感谢

**Comment by nihui** [comment]
> fp16，bf16储存都如何参考实现？
> 这样我理解，如果在A35平台上，使用fp16的模型存储。
> 1.可以减少模型的体积为原来的一半。还可以减少推理过程中内存的占用吗？
> 2.可以提供加速效果吗。如果使用fp16存储，fp32做运算，我理解cpu的占用会比之前fp32运算多一点。因为有转换的开销。
> 麻烦指正我的理解对不对？感谢@nihui

1 可以
2 取决于硬件实现效率，A35 我没有试过，A53 上 fp16 转换开销过大，但 bf16 会加速

**Comment by jiyinghui39** [comment]
感谢回复。ncnn上bf16，转换的步骤应该是怎样的。
我在opt里面将
opt.use_packing_layout = true;
opt.use_bf16_storage = true;
设置后，去加载fp32的模型。输出异常。
请问，是需要将模型也通过ncnnOptimzer也转化为bf16的模型吗

**Comment by nihui** [comment]
> 感谢回复。ncnn上bf16，转换的步骤应该是怎样的。
> 我在opt里面将
> opt.use_packing_layout = true;
> opt.use_bf16_storage = true;
> 设置后，去加载fp32的模型。输出异常。
> 请问，是需要将模型也通过ncnnOptimzer也转化为bf16的模型吗

更新git最新的代码试试看，如果结果差很多，可以发issue

**Comment by jiyinghui39** [comment]
请问，是需要将模型也通过ncnnOptimzer也转化为bf16的模型吗。
这步需要操作吗@nihui

**Comment by jiyinghui39** [comment]
我分别在Arm A53和A35上，使用opt.use_packing_layout = true;opt.use_bf16_storage = true;。加载FP32的ultraFace模型。结果全部是错误的，还很异常。这个可能是什么问题呢@nihui

**Comment by yurensmile** [comment]
最后是怎么解决这个问题的？

**Comment by nihui** [comment]
最新版本已经实现cpu fp16存储和运算，默认自动开启，无需设置
