### ISSUE TITLE
alexnet转换成ncnn模型后运行不成功

### ISSUE THREAD

**Issue by ljdang** [Tencent/ncnn#93]
将alexnet转换成ncnn模型后，替换examples中的squeezenet模型，运行出现段错误，请问是还需要修改哪些值吗？

**Comment by jj8401** [comment]
@ljdang 你是哪里有问题，我是包initSqueezenetNcnn错误

**Comment by ljdang** [comment]
@jj8401 貌似是现在还不支持group的原因

**Comment by Howave** [comment]
我也出现同样的问题

**Comment by nihui** [comment]
添加 group convolution，还没优化，至少能跑了  qwq
https://github.com/Tencent/ncnn/commit/9f51c2132267edcdeefd0b1a4e67424b7b2b8096

**Comment by nihui** [comment]
alexnet 亲测可以转换使用了...
