### ISSUE TITLE
新定义层参数解析方式

### ISSUE THREAD

**Issue by LaVieEnRoseSMZ** [Tencent/ncnn#930]
不同层的特殊参数的含义不同，想知道，如果我们新定义的层增加一些参数，那么这些参数只需要在新定义的的cpp文件里的load_param里写new_param = pd.get(15, 0); 然后再param文件里写明15=对应的value是吗？

还是需要在对不同层的解析param的文件中去特殊定义（没有找到这种解析文件）

**Comment by nihui** [comment]
对的，就这样...
