### ISSUE TITLE
squeezenet_ssd跑GPU结果错误

### ISSUE THREAD

**Issue by kelvinou** [Tencent/ncnn#932]
squeezenet_ssd跑GPU结果错误，定位到Softmax-mbox_conf_softmax层结果与CPU结果不一致，再次麻烦nihui大佬解决一下！

**Comment by kelvinou** [comment]
@nihui

**Comment by nihui** [comment]
confirmed

**Comment by kelvinou** [comment]
squeezenet_ssd的输出结果是正常的，但是发现原版Caffe-SSD的官方模型在CPU上结果正确，而GPU的结果却不正确（没有结果输出），同样也是定位在Softmax-mbox_conf_softmax层的输出与CPU不一致

**Comment by nihui** [comment]
confirmed

**Comment by nihui** [comment]
> squeezenet_ssd的输出结果是正常的，但是发现原版Caffe-SSD的官方模型在CPU上结果正确，而GPU的结果却不正确（没有结果输出），同样也是定位在Softmax-mbox_conf_softmax层的输出与CPU不一致 @nihui

应该都修复了 ...
