### ISSUE TITLE
官网下载的bvlc_alexnet.caffemodel量化之后，得到的预测值都是nan

### ISSUE THREAD

**Issue by pele228** [Tencent/ncnn#933]
官网下载的bvlc_alexnet.caffemodel, 使用caffe-int8-convert-tool-dev-weight.py工具量化之后的.param和.bin文件做预测， 发现所有的结果都是nan. 请问是什么原因? caffe2ncnn是0320版本. 

cls_scores[710] = -nan(ind)
cls_scores[711] = -nan(ind)
cls_scores[712] = -nan(ind)
cls_scores[713] = -nan(ind)
cls_scores[714] = -nan(ind)
cls_scores[715] = -nan(ind)
cls_scores[716] = -nan(ind)
cls_scores[717] = -nan(ind)
cls_scores[718] = -nan(ind)
cls_scores[719] = -nan(ind)
cls_scores[720] = -nan(ind)
cls_scores[721] = -nan(ind)
cls_scores[722] = -nan(ind)
cls_scores[723] = -nan(ind)
cls_scores[724] = -nan(ind)
cls_scores[725] = -nan(ind)
cls_scores[726] = -nan(ind)
cls_scores[727] = -nan(ind)
cls_scores[728] = -nan(ind)
cls_scores[729] = -nan(ind)
cls_scores[730] = -nan(ind)
cls_scores[731] = -nan(ind)
cls_scores[732] = -nan(ind)
cls_scores[733] = -nan(ind)
cls_scores[734] = -nan(ind)
cls_scores[735] = -nan(ind)
cls_scores[736] = -nan(ind)
cls_scores[737] = -nan(ind)
cls_scores[738] = -nan(ind)
cls_scores[739] = -nan(ind)
cls_scores[740] = -nan(ind)
cls_scores[741] = -nan(ind)
cls_scores[742] = -nan(ind)
cls_scores[743] = -nan(ind)
cls_scores[744] = -nan(ind)
cls_scores[745] = -nan(ind)
cls_scores[746] = -nan(ind)
cls_scores[747] = -nan(ind)
cls_scores[748] = -nan(ind)
cls_scores[749] = -nan(ind)
cls_scores[750] = -nan(ind)
cls_scores[751] = -nan(ind)
cls_scores[752] = -nan(ind)
cls_scores[753] = -nan(ind)
cls_scores[754] = -nan(ind)
cls_scores[755] = -nan(ind)
cls_scores[756] = -nan(ind)
cls_scores[757] = -nan(ind)
cls_scores[758] = -nan(ind)
cls_scores[759] = -nan(ind)
cls_scores[760] = -nan(ind)
cls_scores[761] = -nan(ind)
cls_scores[762] = -nan(ind)
cls_scores[763] = -nan(ind)
cls_scores[764] = -nan(ind)
cls_scores[765] = -nan(ind)
cls_scores[766] = -nan(ind)
cls_scores[767] = -nan(ind)
cls_scores[768] = -nan(ind)
cls_scores[769] = -nan(ind)
cls_scores[770] = -nan(ind)
cls_scores[771] = -nan(ind)
cls_scores[772] = -nan(ind)
cls_scores[773] = -nan(ind)
cls_scores[774] = -nan(ind)
cls_scores[775] = -nan(ind)
cls_scores[776] = -nan(ind)
cls_scores[777] = -nan(ind)
cls_scores[778] = -nan(ind)
cls_scores[779] = -nan(ind)
cls_scores[780] = -nan(ind)
cls_scores[781] = -nan(ind)
cls_scores[782] = -nan(ind)
cls_scores[783] = -nan(ind)
cls_scores[784] = -nan(ind)
cls_scores[785] = -nan(ind)
cls_scores[786] = -nan(ind)
cls_scores[787] = -nan(ind)
cls_scores[788] = -nan(ind)
cls_scores[789] = -nan(ind)
cls_scores[790] = -nan(ind)
cls_scores[791] = -nan(ind)
cls_scores[792] = -nan(ind)
cls_scores[793] = -nan(ind)
cls_scores[794] = -nan(ind)
cls_scores[795] = -nan(ind)
cls_scores[796] = -nan(ind)
cls_scores[797] = -nan(ind)
cls_scores[798] = -nan(ind)
cls_scores[799] = -nan(ind)
cls_scores[800] = -nan(ind)
cls_scores[801] = -nan(ind)
cls_scores[802] = -nan(ind)
cls_scores[803] = -nan(ind)
cls_scores[804] = -nan(ind)
cls_scores[805] = -nan(ind)
cls_scores[806] = -nan(ind)
cls_scores[807] = -nan(ind)
cls_scores[808] = -nan(ind)
cls_scores[809] = -nan(ind)
cls_scores[810] = -nan(ind)
cls_scores[811] = -nan(ind)
cls_scores[812] = -nan(ind)
cls_scores[813] = -nan(ind)
cls_scores[814] = -nan(ind)
cls_scores[815] = -nan(ind)
cls_scores[816] = -nan(ind)
cls_scores[817] = -nan(ind)
cls_scores[818] = -nan(ind)
cls_scores[819] = -nan(ind)
cls_scores[820] = -nan(ind)
cls_scores[821] = -nan(ind)
cls_scores[822] = -nan(ind)
cls_scores[823] = -nan(ind)
cls_scores[824] = -nan(ind)
cls_scores[825] = -nan(ind)
cls_scores[826] = -nan(ind)
cls_scores[827] = -nan(ind)
cls_scores[828] = -nan(ind)
cls_scores[829] = -nan(ind)
cls_scores[830] = -nan(ind)
cls_scores[831] = -nan(ind)
cls_scores[832] = -nan(ind)
cls_scores[833] = -nan(ind)
cls_scores[834] = -nan(ind)
cls_scores[835] = -nan(ind)
cls_scores[836] = -nan(ind)
cls_scores[837] = -nan(ind)
cls_scores[838] = -nan(ind)
cls_scores[839] = -nan(ind)
cls_scores[840] = -nan(ind)
cls_scores[841] = -nan(ind)
cls_scores[842] = -nan(ind)
cls_scores[843] = -nan(ind)
cls_scores[844] = -nan(ind)
cls_scores[845] = -nan(ind)
cls_scores[846] = -nan(ind)
cls_scores[847] = -nan(ind)
cls_scores[848] = -nan(ind)
cls_scores[849] = -nan(ind)
cls_scores[850] = -nan(ind)
cls_scores[851] = -nan(ind)
cls_scores[852] = -nan(ind)
cls_scores[853] = -nan(ind)
cls_scores[854] = -nan(ind)
cls_scores[855] = -nan(ind)
cls_scores[856] = -nan(ind)
cls_scores[857] = -nan(ind)
cls_scores[858] = -nan(ind)
cls_scores[859] = -nan(ind)
cls_scores[860] = -nan(ind)
cls_scores[861] = -nan(ind)
cls_scores[862] = -nan(ind)
cls_scores[863] = -nan(ind)
cls_scores[864] = -nan(ind)
cls_scores[865] = -nan(ind)
cls_scores[866] = -nan(ind)
cls_scores[867] = -nan(ind)
cls_scores[868] = -nan(ind)
cls_scores[869] = -nan(ind)
cls_scores[870] = -nan(ind)
cls_scores[871] = -nan(ind)
cls_scores[872] = -nan(ind)
cls_scores[873] = -nan(ind)
cls_scores[874] = -nan(ind)
cls_scores[875] = -nan(ind)
cls_scores[876] = -nan(ind)
cls_scores[877] = -nan(ind)
cls_scores[878] = -nan(ind)
cls_scores[879] = -nan(ind)
cls_scores[880] = -nan(ind)
cls_scores[881] = -nan(ind)
cls_scores[882] = -nan(ind)
cls_scores[883] = -nan(ind)
cls_scores[884] = -nan(ind)
cls_scores[885] = -nan(ind)
cls_scores[886] = -nan(ind)
cls_scores[887] = -nan(ind)
cls_scores[888] = -nan(ind)
cls_scores[889] = -nan(ind)
cls_scores[890] = -nan(ind)
cls_scores[891] = -nan(ind)
cls_scores[892] = -nan(ind)
cls_scores[893] = -nan(ind)
cls_scores[894] = -nan(ind)
cls_scores[895] = -nan(ind)
cls_scores[896] = -nan(ind)
cls_scores[897] = -nan(ind)
cls_scores[898] = -nan(ind)
cls_scores[899] = -nan(ind)
cls_scores[900] = -nan(ind)
cls_scores[901] = -nan(ind)
cls_scores[902] = -nan(ind)
cls_scores[903] = -nan(ind)
cls_scores[904] = -nan(ind)
cls_scores[905] = -nan(ind)
cls_scores[906] = -nan(ind)
cls_scores[907] = -nan(ind)
cls_scores[908] = -nan(ind)
cls_scores[909] = -nan(ind)
cls_scores[910] = -nan(ind)
cls_scores[911] = -nan(ind)
cls_scores[912] = -nan(ind)
cls_scores[913] = -nan(ind)
cls_scores[914] = -nan(ind)
cls_scores[915] = -nan(ind)
cls_scores[916] = -nan(ind)
cls_scores[917] = -nan(ind)
cls_scores[918] = -nan(ind)
cls_scores[919] = -nan(ind)
cls_scores[920] = -nan(ind)
cls_scores[921] = -nan(ind)
cls_scores[922] = -nan(ind)
cls_scores[923] = -nan(ind)
cls_scores[924] = -nan(ind)
cls_scores[925] = -nan(ind)
cls_scores[926] = -nan(ind)
cls_scores[927] = -nan(ind)
cls_scores[928] = -nan(ind)
cls_scores[929] = -nan(ind)
cls_scores[930] = -nan(ind)
cls_scores[931] = -nan(ind)
cls_scores[932] = -nan(ind)
cls_scores[933] = -nan(ind)
cls_scores[934] = -nan(ind)
cls_scores[935] = -nan(ind)
cls_scores[936] = -nan(ind)
cls_scores[937] = -nan(ind)
cls_scores[938] = -nan(ind)
cls_scores[939] = -nan(ind)
cls_scores[940] = -nan(ind)
cls_scores[941] = -nan(ind)
cls_scores[942] = -nan(ind)
cls_scores[943] = -nan(ind)
cls_scores[944] = -nan(ind)
cls_scores[945] = -nan(ind)
cls_scores[946] = -nan(ind)
cls_scores[947] = -nan(ind)
cls_scores[948] = -nan(ind)
cls_scores[949] = -nan(ind)
cls_scores[950] = -nan(ind)
cls_scores[951] = -nan(ind)
cls_scores[952] = -nan(ind)
cls_scores[953] = -nan(ind)
cls_scores[954] = -nan(ind)
cls_scores[955] = -nan(ind)
cls_scores[956] = -nan(ind)
cls_scores[957] = -nan(ind)
cls_scores[958] = -nan(ind)
cls_scores[959] = -nan(ind)
cls_scores[960] = -nan(ind)
cls_scores[961] = -nan(ind)
cls_scores[962] = -nan(ind)
cls_scores[963] = -nan(ind)
cls_scores[964] = -nan(ind)
cls_scores[965] = -nan(ind)
cls_scores[966] = -nan(ind)
cls_scores[967] = -nan(ind)
cls_scores[968] = -nan(ind)
cls_scores[969] = -nan(ind)
cls_scores[970] = -nan(ind)
cls_scores[971] = -nan(ind)
cls_scores[972] = -nan(ind)
cls_scores[973] = -nan(ind)
cls_scores[974] = -nan(ind)
cls_scores[975] = -nan(ind)
cls_scores[976] = -nan(ind)
cls_scores[977] = -nan(ind)
cls_scores[978] = -nan(ind)
cls_scores[979] = -nan(ind)
cls_scores[980] = -nan(ind)
cls_scores[981] = -nan(ind)
cls_scores[982] = -nan(ind)
cls_scores[983] = -nan(ind)
cls_scores[984] = -nan(ind)
cls_scores[985] = -nan(ind)
cls_scores[986] = -nan(ind)
cls_scores[987] = -nan(ind)
cls_scores[988] = -nan(ind)
cls_scores[989] = -nan(ind)
cls_scores[990] = -nan(ind)
cls_scores[991] = -nan(ind)
cls_scores[992] = -nan(ind)
cls_scores[993] = -nan(ind)
cls_scores[994] = -nan(ind)
cls_scores[995] = -nan(ind)
cls_scores[996] = -nan(ind)
cls_scores[997] = -nan(ind)
cls_scores[998] = -nan(ind)
cls_scores[999] = -nan(ind)

**Comment by pele228** [comment]
如果不做量化， caffemodel直接转.param和.bin,  那么预测值都是正常的，和原始的caffemodel的分类结果比较接近.

**Comment by nihui** [comment]
https://zhuanlan.zhihu.com/p/370689914
20210507版本大幅优化int8推理速度，建议更新
