### ISSUE TITLE
mxnet-ssd

### ISSUE THREAD

**Issue by yyfyan** [Tencent/ncnn#934]
I used the ssd-mxnet:https://github.com/zhreshold/mxnet-ssd.
then I try use mxnet2ncnn tool to convert to ncnn model. But I meet the problem,how to sloved?
![Screenshot from 2019-04-22 09-38-17](https://user-images.githubusercontent.com/24808222/56478537-be52e180-64e2-11e9-9cfa-59bd54c389ed.png)

And can you provide some example to use the mxnet's ncnn model? Thank you.

**Comment by yyfyan** [comment]
@nihui

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/1dea9fe353d9a38b2a6e6a48a056a0f1ef45ed99

**Comment by nihui** [comment]
```
class Noop : public ncnn::Layer
{
};

DEFINE_LAYER_CREATOR(Noop)
```
```
    ncnn::Net net;

    net.register_custom_layer("_contrib_MultiBoxTarget", Noop_layer_creator);
    net.register_custom_layer("smooth_l1", Noop_layer_creator);
    net.register_custom_layer("MakeLoss", Noop_layer_creator);

    net.load_param("ssd_300.param");
    net.load_model("ssd_300.bin");
```

**Comment by nihui** [comment]
since mxnet2ncnn do not support binaryop with constant weight blob
you have to modify the param file like the following
```
BinaryOp         broadcast_mul0                   1 1 relu4_3_norm broadcast_mul0 0=2
```
```
BinaryOp         broadcast_mul0                   1 1 relu4_3_norm broadcast_mul0 0=2 1=1 2=20.0
```
