### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by albanjiang** [Tencent/ncnn#935]
tag:20190320 build error.

/src/mat.cpp: In function 'void ncnn::convert_packing(const ncnn::Mat&, ncnn::Mat&, int, ncnn::Allocator*, int)':
/src/mat.cpp:718:47: error: 'Packing' is not a member of 'ncnn::LayerType'
     ncnn::Layer* packing = ncnn::create_layer(ncnn::LayerType::Packing);
                                               ^
src/CMakeFiles/ncnn.dir/build.make:140: recipe for target 'src/CMakeFiles/ncnn.dir/mat.cpp.o' failed
make[2]: *** [src/CMakeFiles/ncnn.dir/mat.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'src/CMakeFiles/ncnn.dir/all' failed
make[1]: *** [src/CMakeFiles/ncnn.dir/all] Error 2
Makefile:129: recipe for target 'all' failed

**Comment by albanjiang** [comment]
build error on linux，Qualcomm 845

**Comment by albanjiang** [comment]
build same code ok with vs on win10.

**Comment by nihui** [comment]
try #include "layer_type.h"

**Comment by nihui** [comment]
feel free to reopen this issue if you still encounter the error
