### ISSUE TITLE
Mxnet ssd convert failed

### ISSUE THREAD

**Issue by tianylijun** [Tencent/ncnn#936]
tools/mxnet$ ./mxnet2ncnn ssd/ssd_512_mobilenet1.0_voc-symbol.json ssd/ssd_512_mobilenet1.0_voc-0000.params ssd/ssd.ncnnproto ssd/ssd.ncnnbin

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Model:
https://gluon-cv.mxnet.io/model_zoo/detection.html#id34

ssd_512_mobilenet1.0_voc

<img width="876" alt="屏幕快照 2019-04-23 下午5 38 07" src="https://user-images.githubusercontent.com/23356740/56570988-918bf080-65ee-11e9-938f-555e442483a9.png">

**Comment by nihui** [comment]
提供下 json 和 params 文件

**Comment by tianylijun** [comment]
https://pan.baidu.com/s/1yxg7RY_8aVa0b2tttlLpXg

**Comment by nihui** [comment]
不支持这个模型
mxnet ssd 可以用这个 repo https://github.com/zhreshold/mxnet-ssd
