### ISSUE TITLE
Does ncnn support CenterNet ?

### ISSUE THREAD

**Issue by hanfanggithub** [Tencent/ncnn#937]

**Comment by 18022443868** [comment]
目前来说，应该是不支持的，YOLOV3版本中的一些层都不支持，需要自己去添加层信息

**Comment by hanfanggithub** [comment]
> 目前来说，应该是不支持的，YOLOV3版本中的一些层都不支持，需要自己去添加层信息

yolov3可以，我已经转成功了

**Comment by 18022443868** [comment]
如何转的？
可以把工程打包发我一份吗？谢谢




| |
任云
|
|
邮箱：18022443868@163.com
|

签名由 网易邮箱大师 定制

On 06/13/2019 11:29, hanfanggithub wrote:

目前来说，应该是不支持的，YOLOV3版本中的一些层都不支持，需要自己去添加层信息

yolov3可以，我已经转成功了

**Comment by hanfanggithub** [comment]
> 如何转的？ 可以把工程打包发我一份吗？谢谢 | | 任云 | | 邮箱：18022443868@163.com | 签名由 网易邮箱大师 定制 On 06/13/2019 11:29, hanfanggithub wrote: 目前来说，应该是不支持的，YOLOV3版本中的一些层都不支持，需要自己去添加层信息 yolov3可以，我已经转成功了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

我还没有整理成完整工程，有些是自己手动修改的，你说的不支持的层是指yolo-layer里边的一些操作吗？yolo-layer我没有转，直接用ncnn的yolov3detectionoutput就可以，而且我原模型是pytorch的，通过onnx转的

**Comment by wlguan** [comment]
@hanfanggithub 请问在转换过程中有遇到squueze unsqueeze gather的问题吗　我使用了onnxsim还是没能消除掉这些op

**Comment by grainw** [comment]
@nihui 想问下关于可变形卷积什么时候能支持呢？

**Comment by nihui** [comment]
> 
> 
> @hanfanggithub 请问在转换过程中有遇到squueze unsqueeze gather的问题吗　我使用了onnxsim还是没能消除掉这些op

https://zhuanlan.zhihu.com/p/93017149

**Comment by nihui** [comment]
可以关注下...
https://github.com/ouyanghuiyu/centernet_mobilenetv2_ncnn

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
