### ISSUE TITLE
请问作者有计划支持keras转ncnn?

### ISSUE THREAD

**Issue by onexuan** [Tencent/ncnn#939]
请问作者有计划支持keras转ncnn?

**Comment by zhouleidcc** [comment]
其实这个可以先自己转。自己用api搭建net，然后将keras版本对应的net的权重导入用api搭建net中去就可以了。第一次做可能有点费劲，多转几次就熟练了

**Comment by onexuan** [comment]
@zhouleidcc  我也想，不会而以，所以希望直接支持，看到好多用keras了

**Comment by nihui** [comment]
我个人没有计划支持keras
有计划pytorch
