### ISSUE TITLE
 ncnn::Mat::from_pixels 导致段错误

### ISSUE THREAD

**Issue by wangsuyu** [Tencent/ncnn#941]
海思平台调用 ncnn::Mat::from_pixels出现段错误，复现代码如下
int main(int argc, char** argv) {
    for (int i = 0; i < 10000; i++)
        test_from_pixels();
    test_from_pixels();
    return 0;
}

void test_from_pixels()
{
    int w = 2000;
    int h = 2000;
    printf("w = %d, h = %d\n", w, h);
    unsigned char *rgb = (unsigned char *)malloc(w*h*3*sizeof(unsigned char));
    if(rgb == NULL)
    {
        printf("rgb malloc error");
        return;
    }
        ncnn::Mat ncnn_img = ncnn::Mat::from_pixels(rgb, ncnn::Mat::PIXEL_RGB2BGR, w, h);
    free(rgb);
}

w和h设置2000只要运行就复现了。

arm-hisiv300-linux-g++ -g -Wall mtcnn_testFromPixels.cpp -I/sdk/hisi/hi3521a/Hi3521A_SDK_V1.0.3.0/mpp/include/include_ncnn /sdk/hisi/hi3521a/Hi3521A_SDK_V1.0.3.0/mpp/lib/libncnn.a -std=c++11 -o mtcnn

**Comment by nihui** [comment]
move to https://github.com/Tencent/ncnn/issues/944
