### ISSUE TITLE
救救孩子吧linux build error

### ISSUE THREAD

**Issue by weishuoycbb** [Tencent/ncnn#945]
![image](https://user-images.githubusercontent.com/43461329/56720155-c7f37800-6774-11e9-9fde-0e669a063b53.png)

**Comment by weishuoycbb** [comment]
![image](https://user-images.githubusercontent.com/43461329/56720876-54526a80-6776-11e9-8624-3212d70605de.png)

**Comment by nihui** [comment]
升级cmake到最新版本试试

**Comment by weishuoycbb** [comment]
升级cmake之后，编译中出现了一些warning,有影响吗
![image](https://user-images.githubusercontent.com/43461329/56891911-9817dd80-6ab0-11e9-887f-79cc18e2367c.png)
![image](https://user-images.githubusercontent.com/43461329/56891915-a0701880-6ab0-11e9-9a86-2947277a12fd.png)
