### ISSUE TITLE
tensorflow convert 

### ISSUE THREAD

**Issue by starhiking** [Tencent/ncnn#946]
Hi,There!
I haven't found the `rate` key in tensorflow `Conv2D` node, why do you wirte like this? @nihui 
https://github.com/Tencent/ncnn/blob/59c476a6b5bcd8281bfb0ba11841171f676dca62/tools/tensorflow/tensorflow2ncnn.cpp#L729-L734

I am doing a tool convert tensorflow, so where does  the `rate` key exist in?

**Comment by nihui** [comment]
tensorflow is not supported yet
https://github.com/Tencent/ncnn/issues/5

**Comment by iqDF** [comment]
Hi @nihui has tensorflow been supported yet?
