### ISSUE TITLE
ncnn支持U-net吗？

### ISSUE THREAD

**Issue by haikuoyao** [Tencent/ncnn#947]
请问，有人转过U-net吗
ncnn支持U-net吗

**Comment by nihui** [comment]
应该是支持的，用 caffe / mxnet / onnx 模型转换下看看

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
