### ISSUE TITLE
a question of tensorflow

### ISSUE THREAD

**Issue by 5658www638** [Tencent/ncnn#952]
May I ask you a question?I used win10 to install the GPU version of TensorFlow successfully, and also ran for several days, suddenly these days do not work, there is "Fail to load the native Tensorflow runtime". CUDA and cuDNN certainly no problem because I managed to run the convolution neural network. You have no good solution, I have looked for a lot of information, can not work.

**Comment by nihui** [comment]
I haven't ever used tensorflow.
You may ask the tensorflow community for help.
