### ISSUE TITLE
请问ncnn和caffe2相比速度优势在什么地方呢

### ISSUE THREAD

**Issue by tao-githup** [Tencent/ncnn#96]

**Comment by tao-githup** [comment]
有人对比过ncnn和caffe2的速度吗

**Comment by cgoxopx** [comment]
不知道。我在arm上，caffe从来就没编译成功过

**Comment by lzx1413** [comment]
在自己的项目中似乎caffe2 加nnpack 和ncnn差不多快，但是squeeze确实是ncnn快，而且ncnn依赖少，包也小，支持android版本更低

**Comment by Soledad89** [comment]
@lzx1413 Why my compiled caffe2 with NNPack support is much slower than ncnn on the same android platform? My computer does not support PinYin input, sorry about that.

**Comment by tao-githup** [comment]
@lzx1413 caffe2你怎么加nnpack的，我也用了nnpack，但是打印出来，仍然是用的是eigen

**Comment by lzx1413** [comment]
Nnpack 对3x3卷积支持更好，不同网络结构效率不太一样吧

**Comment by minipeach** [comment]
caffe2在iphone 6s （iOS10）上运行无压力啊，Eigen速度也很快

**Comment by nihui** [comment]
ncnn目前在手机cpu上已做了多轮优化，速度更快
