### ISSUE TITLE
How to run the benchmark experiments on Android GPU

### ISSUE THREAD

**Issue by spaul13** [Tencent/ncnn#962]
I already compiled the benchmark with VULKAN SDK in order to get see how fast the GPU on Android can finish the benchmark but while running on the android through adb shell, No output is showing regarding the min, max and average latencies and also GPU usage on android is 0%. Can anyone please help me telling how to run the benchmark experiments on android GPU.

FYI, I am running the experiments on Pixel 2 which has a Adreno 540 qualcomm GPU

The output I am getting is (I am just running yolo and yolov3 benchmarks)
_./benchncnn 5000 4 0 0                               
[0 Adreno (TM) 540]  queueC=0  queueT=0  memU=2  memDL=2  memHV=2
[0 Adreno (TM) 540]  fp16s=0  fp16a=0  int8s=0  int8a=0
default num_threads = 8
loop_count = 5000
num_threads = 4
powersave = 0
gpu_device = 0
Only running YOLO and YOLOv3 model benchmark_

**Comment by nihui** [comment]
loop count 5000 is too large, try small value as 4 or 8

**Comment by spaul13** [comment]
I also tried loop count 4 and 8 but still giving the same output, means no output regarding the detection time or run time of the model and no GPU utilization. Is there anything else I have to enable or I am missing?

**Comment by GaussRieman** [comment]
maybe you should just wait for a longer time :D @spaul13

**Comment by zengjie617789** [comment]
I found i can use the gpu sources but the utilization rate is 0. Anyone meet the same problem?
