### ISSUE TITLE
pytorch converter

### ISSUE THREAD

**Issue by nihui** [Tencent/ncnn#964]
convert pytorch pt file to ncnn model

to be updated

**Comment by tomingliu** [comment]
我试了下这个tool，没能正确转出来，输出以下错误信息

pytorch2ncnn.exe
name = model_second
unhandled a8a0280
no submodules
node_count = 0

代码在VC下编译做了以下调整，请问下这个pt文件格式上有什么要求吗？

#pragma pack(push)
#pragma pack(1)

struct zip_local_file_header_t
{
    uint32_t signature;
    uint16_t version;
    uint16_t flag;
    uint16_t compression_method;
    uint16_t last_modify_time;
    uint16_t last_modify_data;
    uint32_t crc32;
    uint32_t compressed_size;
    uint32_t uncompressed_size;
    uint16_t filename_length;
    uint16_t extradata_length;
};

union zip_data_descriptor_t
{
    struct
    {
        uint32_t signature;
        uint32_t crc32;
        uint32_t compressed_size;
        uint32_t uncompressed_size;
    } ws;
    struct
    {
        uint32_t crc32;
        uint32_t compressed_size;
        uint32_t uncompressed_size;
    } os;
};

struct zip_central_directory_file_header_t
{
    uint32_t signature;
    uint16_t version_made_by;
    uint16_t version;
    uint16_t flag;
    uint16_t compression_method;
    uint16_t last_modify_time;
    uint16_t last_modify_data;
    uint32_t crc32;
    uint32_t compressed_size;
    uint32_t uncompressed_size;
    uint16_t filename_length;
    uint16_t extradata_length;
    uint16_t filecomment_length;
    uint16_t disk_number;
    uint16_t internal_file_attrs;
    uint32_t external_file_attrs;
    uint32_t relative_local_file_header_offset;
};

struct zip_end_of_central_directory_record_t
{
    uint32_t signature;
    uint16_t disk_number;
    uint16_t disk_starts;
    uint16_t disk_record_count;
    uint16_t total_record_count;
    uint32_t central_directory_size;
    uint32_t central_directory_offset;
    uint16_t comment_length;
};

struct zip64_end_of_central_directory_record_t
{
    uint32_t signature;
    uint64_t header_size;
    uint16_t version_made_by;
    uint16_t version;
    uint32_t disk_number;
    uint32_t disk_number_with_central_directory;
    uint64_t total_entry_number_on_disk;
    uint64_t total_entry_number;
    uint64_t central_directory_size;
    uint64_t central_directory_offset;
};

struct zip64_end_of_central_directory_locator_t
{
    uint32_t signature;
    uint32_t disk_number_with_central_directory;
    uint64_t end_central_directory_offset;
    uint32_t total_disk_number;
};

#pragma pack(pop)

**Comment by nihui** [comment]
discontinued as the pytorch model could be converted via onnx

https://github.com/Tencent/ncnn/wiki/practical-pytorch-to-onnx-to-ncnn

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
