### ISSUE TITLE
Tensorflow2ncnn tool is decently reliable now?

### ISSUE THREAD

**Issue by helloearth012** [Tencent/ncnn#967]
@nihui 
I converted my tensorflow pb to ncnn.proto and ncnn.bin. 
The first 3 lines of ncnn.proto are 
7767517
254 272
Input input 0 1 input 0=0 1=0 2=0

So I guess this input size hasn't been converted correctly?

**Comment by helloearth012** [comment]
FusedBatchNorm not supported yet !
Relu6 not supported yet !
FusedBatchNorm not supported yet !
StridedSlice not supported yet !
Pack not supported yet !

Just want to confirm that there operations are not supported yet?

**Comment by nihui** [comment]
tensorflow is not supported yet
https://github.com/Tencent/ncnn/issues/5
