### ISSUE TITLE
How to build the benchmarks for android with opencv support 

### ISSUE THREAD

**Issue by spaul13** [Tencent/ncnn#968]
I have modified the benchmark for Yolov3 so that it can run the model with an image something like this (inspired from https://github.com/Tencent/ncnn/blob/master/examples/yolov3.cpp)

_void mobilenet_yolov3_run(const ncnn::Net& net)
{
    ncnn::Extractor ex = net.create_extractor();

    //reading the image
    const char* imagepath = "/sdcard/bitmap_store/dog.jpg";
    const int target_size = 608;
    cv::Mat m = cv::imread(imagepath, 1);
    if (m.empty())
    {
        fprintf(stderr, "cv::imread %s failed\n", imagepath);
        return ;
    }
    
    int img_w = m.cols;
    int img_h = m.rows;
    //Resizing the image converting from cv::Mat to ncnn::Mat
    ncnn::Mat in = ncnn::Mat::from_pixels_resize(m.data, ncnn::Mat::PIXEL_BGR, m.cols, m.rows, target_size, target_size);

    //Normalization
    const float mean_vals[3] = {127.5f, 127.5f, 127.5f};
    const float norm_vals[3] = {0.007843f, 0.007843f, 0.007843f};
    in.substract_mean_normalize(mean_vals, norm_vals);	
    fprintf(stderr, "\n After Normalizing ");
    ex.input("data", in);
    fprintf(stderr, "\n input image = %d, %d, %d", in.w, in.h, in.c);
    ncnn::Mat out;
    ex.extract("detection_out", out);
    fprintf(stderr, "\n results = %d, %d, %d", out.w, out.h, out.c);
    for (int i=0; i<out.h; i++)
    {
        const float* values = out.row(i);
        fprintf(stderr, "\n the current label = %f and current prob of detection = %f", values[0], values[1]);
        fprintf(stderr, "\n the x label = %f and y label = %f", values[2] * img_w, values[3] * img_h);
        fprintf(stderr, "\n the width = %f and height = %f", values[4] * img_w - (values[2] * img_w), values[5] * img_h - (values[3] * img_h));	
    }
}_

But while compiling this (make -j4) the opencv giving me error saying

**_/home/sj/ncnn/benchmark/benchncnn.cpp:33:10: fatal error: 
      'opencv2/core/core.hpp' file not found
#include <opencv2/core/core.hpp>_**

Looking in the example directory I tried to change the CMakeLists.txt a little bit in order to add the opencv libraries 

**_find_package(OpenCV QUIET COMPONENTS core highgui imgproc imgcodecs)
if(NOT OpenCV_FOUND)
    find_package(OpenCV REQUIRED COMPONENTS core highgui imgproc)
endif()
set(NCNN_BENCHMARK_LINK_LIBRARIES ncnn ${OpenCV_LIBS})_**

but its showing the following error while running cmake

_**CMake Error at benchmark/CMakeLists.txt:3 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!**_

can anyone please tell me how to build this benchmark with opencv support for android?

**Comment by nihui** [comment]
examples are supposed to be build on host system
you may refer the android example project in readme file

**Comment by spaul13** [comment]
Hi @nihui, thanks for replying me back. Can u please tell me how to compile the benchmark for android with the opencv support I guess that will work for me.
