### ISSUE TITLE
Compiling ncnn/examples/yolov3.cpp and run object detection for linux platform

### ISSUE THREAD

**Issue by spaul13** [Tencent/ncnn#969]
Can anyone plz tell me how compile yolov2.cpp or yolov3.cpp under ncnn/examples to run the detection using yolov2/yolov3 model on ubuntu?

**Comment by nihui** [comment]
build instruction https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux-x86
howto https://github.com/Tencent/ncnn/wiki/how-to-use-ncnn-with-alexnet
model files could be found in yolov2/yolov3.cpp source file

**Comment by spaul13** [comment]
I tried the exact same way as mentioned in the https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux-x86

But having the following error can you @nihui, please tell me why I am getting this error
**_Error:_**
_/home/sj/ncnn/examples/peleenetssd_seg.cpp: In function ‘void draw_objects(const cv::Mat&, const std::vector<Object>&, ncnn::Mat)’:
/home/sj/ncnn/examples/peleenetssd_seg.cpp:97:53: error: in C++98 ‘color’ must be initialized by constructor, not by ‘{...}’
     std::vector<int> color = {128,255,128,244,35,232};
                                                     ^
/home/sj/ncnn/examples/peleenetssd_seg.cpp:97:53: error: could not convert ‘{128, 255, 128, 244, 35, 232}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<int>’_

**Comment by eric612** [comment]
@spaul13 

The error was from my code , can you try to replace 
```
std::vector color = {128,255,128,244,35,232}; 
```
to 
```
std::vector color;
color.push_back(128);
color.push_back(255);
color.push_back(128);
color.push_back(244);
color.push_back(35);
color.push_back(232);
```
