### ISSUE TITLE
Benchmark performance

### ISSUE THREAD

**Issue by spaul13** [Tencent/ncnn#970]
While running the yolov3 benchmark for 10 times on android, can I say the cpu utilization for running the model for 10 times in benchmark will be same if I run a batch of object detections with 10 frames??

**Comment by nihui** [comment]
batch inference is not supported in ncnn

**Comment by spaul13** [comment]
No, what I want to mean that I run the model 10 times using benchmark will it result in same CPU usage if used 10 images and run the model for 10 times to detect objects inside those images?
