### ISSUE TITLE
examples build error

### ISSUE THREAD

**Issue by spaul13** [Tencent/ncnn#971]
while building the ncnn for linux platform following https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-linux-x86 
I am getting the following error, 

**_/home/sj/ncnn/examples/peleenetssd_seg.cpp: In function ‘void draw_objects(const cv::Mat&, const std::vector<Object>&, ncnn::Mat)’:
/home/sj/ncnn/examples/peleenetssd_seg.cpp:97:53: error: in C++98 ‘color’ must be initialized by constructor, not by ‘{...}’
     std::vector<int> color = {128,255,128,244,35,232};
                                                     ^
/home/sj/ncnn/examples/peleenetssd_seg.cpp:97:53: error: could not convert ‘{128, 255, 128, 244, 35, 232}’ from ‘<brace-enclosed initializer list>’ to ‘std::vector<int>’_**

My gcc and g++ compiler version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

can anyone please tell me how to resolve this error?

**Comment by gzp0201** [comment]
把
std::vector<int> color = {128,255,128,244,35,232};
改成
std::vector<int> color;
color.push_back(128);
color.push_back(255);
color.push_back(128);
color.push_back(244);
color.push_back(35);
color.push_back(232);

**Comment by linxueya** [comment]
I had the same problem as you

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/838c5df839004236bbd350ffe93fabfc888dd7fc
