### ISSUE TITLE
新模型的分享

### ISSUE THREAD

**Issue by PKUEcho** [Tencent/ncnn#98]
大家有成功跑起来的除了squeezenet以外的模型如VGG，Inception，是不是可以考虑分享一下，push上去或者只是在issue里给个链接。非常感谢！

**Comment by telefire** [comment]
同问这个问题， 貌似 AlexNet也是最近刚刚调整了Group Convolution 才能跑。。

**Comment by nihui** [comment]
example模型我放在这里了 https://github.com/nihui/ncnn-assets/tree/master/models
