### ISSUE TITLE
ncnn+vulkan  benchmark on xiaomi-mix2s(sdm845+adreno630)-armv8

### ISSUE THREAD

**Issue by GaussRieman** [Tencent/ncnn#980]
polaris:/data/local/tmp $ ./benchncnn 4 8 0 -1                                                                                                                                                             
[0 Adreno (TM) 630]  queueC=0  queueT=0  memU=2  memDL=2  memHV=2
[0 Adreno (TM) 630]  fp16s=0  fp16a=0  int8s=0  int8a=0
loop_count = 4
num_threads = 8
powersave = 0
gpu_device = -1
          squeezenet  min =   21.29  max =   23.88  avg =   22.51
     squeezenet-int8  min =   19.84  max =   24.12  avg =   22.45
           mobilenet  min =   26.33  max =   30.23  avg =   28.12
      mobilenet-int8  min =   32.68  max =   34.84  avg =   33.66
        mobilenet_v2  min =   24.94  max =   26.65  avg =   25.58
          shufflenet  min =   15.59  max =   20.51  avg =   17.90
             mnasnet  min =   22.68  max =   25.07  avg =   23.54
     proxylessnasnet  min =   26.60  max =   29.16  avg =   27.61
           googlenet  min =   78.21  max =   80.24  avg =   79.11
      googlenet-int8  min =   74.48  max =   80.33  avg =   78.01
            resnet18  min =   69.21  max =   70.60  avg =   69.94
       resnet18-int8  min =   64.66  max =   69.81  avg =   67.01
             alexnet  min =  105.64  max =  111.90  avg =  108.49
               vgg16  min =  322.05  max =  335.43  avg =  326.09
            resnet50  min =  331.46  max =  350.55  avg =  338.39
       resnet50-int8  min =  150.48  max =  156.43  avg =  153.72
      squeezenet-ssd  min =   60.20  max =   64.76  avg =   62.96
 squeezenet-ssd-int8  min =   59.75  max =   63.49  avg =   61.29
       mobilenet-ssd  min =   56.82  max =   58.47  avg =   57.76
  mobilenet-ssd-int8  min =   66.83  max =   72.32  avg =   69.17
      mobilenet-yolo  min =  124.87  max =  127.09  avg =  126.10
    mobilenet-yolov3  min =  130.62  max =  132.28  avg =  131.36

polaris:/data/local/tmp $ ./benchncnn 4 4 2 -1                                                                                                                                                             
[0 Adreno (TM) 630]  queueC=0  queueT=0  memU=2  memDL=2  memHV=2
[0 Adreno (TM) 630]  fp16s=0  fp16a=0  int8s=0  int8a=0
loop_count = 4
num_threads = 4
powersave = 2
gpu_device = -1
          squeezenet  min =   16.60  max =   17.62  avg =   17.25
     squeezenet-int8  min =   12.54  max =   12.75  avg =   12.64
           mobilenet  min =   21.44  max =   21.55  avg =   21.50
      mobilenet-int8  min =   19.72  max =   19.91  avg =   19.81
        mobilenet_v2  min =   15.54  max =   15.61  avg =   15.57
          shufflenet  min =    9.51  max =    9.61  avg =    9.58
             mnasnet  min =   14.74  max =   15.01  avg =   14.85
     proxylessnasnet  min =   17.26  max =   17.46  avg =   17.37
           googlenet  min =   61.28  max =   62.05  avg =   61.65
      googlenet-int8  min =   49.91  max =   50.02  avg =   49.95
            resnet18  min =   59.36  max =   60.61  avg =   59.76
       resnet18-int8  min =   41.69  max =   42.03  avg =   41.80
             alexnet  min =   96.46  max =   96.86  avg =   96.68
               vgg16  min =  305.06  max =  306.28  avg =  305.97
            resnet50  min =  304.90  max =  308.08  avg =  306.77
       resnet50-int8  min =   97.94  max =   98.71  avg =   98.30
      squeezenet-ssd  min =   47.25  max =   50.42  avg =   48.46
 squeezenet-ssd-int8  min =   36.13  max =   37.17  avg =   36.51
       mobilenet-ssd  min =   45.76  max =   45.90  avg =   45.85
  mobilenet-ssd-int8  min =   39.57  max =   39.69  avg =   39.64
      mobilenet-yolo  min =  101.24  max =  101.93  avg =  101.48
    mobilenet-yolov3  min =  105.47  max =  105.78  avg =  105.65

polaris:/data/local/tmp $ ./benchncnn 4 4 2 0                                                                                                                                                              
[0 Adreno (TM) 630]  queueC=0  queueT=0  memU=2  memDL=2  memHV=2
[0 Adreno (TM) 630]  fp16s=0  fp16a=0  int8s=0  int8a=0
loop_count = 4
num_threads = 4
powersave = 2
gpu_device = 0
          squeezenet  min =  106.33  max =  108.36  avg =  107.70
           mobilenet  min =  166.99  max =  167.89  avg =  167.39
        mobilenet_v2  min =   77.64  max =  128.68  avg =   90.76
          shufflenet  min =   37.26  max =   37.75  avg =   37.41
             mnasnet  min =   81.79  max =   82.51  avg =   82.22
     proxylessnasnet  min =   85.97  max =   87.07  avg =   86.62
           googlenet  min =  375.65  max =  377.53  avg =  376.64
            resnet18  min =  451.76  max =  453.45  avg =  452.64
             alexnet  min =  499.08  max =  506.94  avg =  502.15
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
               vgg16  min =    1.24  max =    1.32  avg =    1.28
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
            resnet50  min =    2.56  max =    2.61  avg =    2.59
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
      squeezenet-ssd  min =    7.84  max =    9.26  avg =    8.23
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
       mobilenet-ssd  min =    4.76  max =    4.91  avg =    4.83
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
      mobilenet-yolo  min =    5.66  max =    6.17  avg =    5.97
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
vkQueueSubmit failed -4
vkWaitForFences failed 2
    mobilenet-yolov3  min =    3.94  max =    4.90  avg =    4.59

**Comment by nihui** [comment]
thank you !
vkQueueSubmit failed -4 error has been fixed in the latest code
