### ISSUE TITLE
TX2 compilation failed

### ISSUE THREAD

**Issue by veepersgit** [Tencent/ncnn#987]
I followed the 
https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-nvidia-jetson 
instructions, but with errors listed below:
nvidia@tegra-ubuntu:~/glslang/ncnn/build$ cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake -DNCNN_VULKAN=ON -DCMAKE_BUILD_TYPE=Release ..
-- CMAKE_TOOLCHAIN_FILE = /home/nvidia/glslang/ncnn/toolchains/jetson.toolchain.cmake
-- CMAKE_INSTALL_PREFIX = /home/nvidia/glslang/ncnn/build/install
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/aarch64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
CMake Error at CMakeLists.txt:45 (find_package):
  By not providing "FindVulkan.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Vulkan", but
  CMake did not find one.

  Could not find a package configuration file provided by "Vulkan" with any
  of the following names:

    VulkanConfig.cmake
    vulkan-config.cmake

  Add the installation prefix of "Vulkan" to CMAKE_PREFIX_PATH or set
  "Vulkan_DIR" to a directory containing one of the above files.  If "Vulkan"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/nvidia/glslang/ncnn/build/CMakeFiles/CMakeOutput.log".
Cannot figure out why. Thx.

**Comment by kalcohol** [comment]
tensorrt is better in TX2, highly recommended.

or u can see https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-nvidia-jetson for more vulkan in nVIDIA TX serials

**Comment by veepersgit** [comment]
@kalcohol Thank u for ur recommendation! I will track the tensorrt line, but the ncnn line is still a problem. Can u figure it out?

**Comment by kalcohol** [comment]
@veepersgit more detials in https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-nvidia-jetson

**Comment by veepersgit** [comment]
@kalcohol Sorry，I think u might not understand my question here. I followed the instructions of https://github.com/Tencent/ncnn/wiki/how-to-build#build-for-nvidia-jetson with each step checked, but got errors mentioned above.

**Comment by veepersgit** [comment]
Here's the command line:
cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/jetson.toolchain.cmake -DNCNN_VULKAN=ON -DCMAKE_BUILD_TYPE=Release ..

**Comment by nihui** [comment]
@veepersgit you need to upgrade cmake

**Comment by veepersgit** [comment]
It worked, thx.

**Comment by JensenHJS** [comment]
Hello，what is ncnn‘s advantage over tensorRT ？Will it be more faster？

**Comment by sunjunlishi** [comment]
@veepersgit it worked。到底哪个方法起作用。which method ok ？
