### ISSUE TITLE
onnx update

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#990]
the recent onnx update has enabled ceil mode=true mode for pooling layers. this will help in conversion of pytorch/caffe models to ncnn via onnx.
when will be support for shape, gather, Unsqueeze will be added in onnx2ncnn

Shape not supported yet!
Gather not supported yet!
  # axis=0
Unsqueeze not supported yet!

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/practical-pytorch-to-onnx-to-ncnn#simplify-onnx-model

**Comment by soham24** [comment]
Thank you. 
after converting model to ncnn from this method, I am able to load bin and param files.
but output is always returning -100

**Comment by hellocsi** [comment]
1. Have you checked you onnx model by onnxruntime?
2. Can you provide the onnx model for analysis?

**Comment by hellocsi** [comment]
> Thank you.
> after converting model to ncnn from this method, I am able to load bin and param files.
> but output is always returning -100

Hi! 
1. Have you checked you onnx model by onnxruntime?
2. Can you provide the onnx model for analysis?

**Comment by soham24** [comment]
@hellocsi I have not checked my model with onnxruntime.

Sure I can provide my model .
 It was shufflenetv2 with 50% width and modified the last layer for custom op. 
I have used  https://github.com/miaow1988/ShuffleNet_V2_pytorch_caffe .

**Comment by hellocsi** [comment]
Hi, the model in ShuffleNet_V2_pytorch_caffe is in PyTorch format, can you directly provide the onnx model? This will be easily to analysis. Also, the error log and the onnxruntime output are helpful for analysis. Thank you!

**Comment by zhanglaplace** [comment]
@nihui  @hellocsi 
"Unsqueeze not supported yet! " problem still appears after using onnxsim transformation origin onnx to onnx-sim model .
"Gather and Shape" problem  is fix

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/commit/ad9e0a97255eeb179efa9969c2d481a1ab250549
pytorch shufflechannel -> onnx -> ncnn is now supported

**Comment by nihui** [comment]
针对onnx模型转换的各种问题，推荐使用最新的pnnx工具转换到ncnn
In view of various problems in onnx model conversion, it is recommended to use the latest pnnx tool to convert your model to ncnn

```shell
pip install pnnx
pnnx model.onnx inputshape=[1,3,224,224]
```

详细参考文档
Detailed reference documentation
https://github.com/pnnx/pnnx
https://github.com/Tencent/ncnn/wiki/use-ncnn-with-pytorch-or-onnx#how-to-use-pnnx
