### ISSUE TITLE
Any way to convert onnx model to int8 

### ISSUE THREAD

**Issue by kealennieh** [Tencent/ncnn#991]
From the Wiki, I know caffe model can be converted to int8 model by using [caffe-int8-convert-tools](https://github.com/BUG1989/caffe-int8-convert-tools).

Is there any tool to convert onnx model to int8, which can be used in NCNN? 

Many thanks!

**Comment by nihui** [comment]
no, currently

a quantization tool directly applied on ncnn models is planned, but won't be ready in near future

**Comment by nihui** [comment]
see quantization tool
https://github.com/Tencent/ncnn/wiki/quantized-int8-inference
