### ISSUE TITLE
cafffe2ncnn channel and width missmatch 

### ISSUE THREAD

**Issue by soham24** [Tencent/ncnn#992]
when I am trying to convert model from caffe to ncnn.

the params file are generating with input layer as
 0 1 data 0=128 1=128 2=3

actually it should be like 
 0 1 data 0=3 1=128 2=128

I don't know why this is happening.

caffetxt is normal. 
layer {
  name: "data"
  type: "Input"
  top: "data"
  input_param { shape: { dim: 1 dim: 3 dim: 128 dim: 128 } }
}

**Comment by nihui** [comment]
input layer param use whc order
https://github.com/Tencent/ncnn/wiki/operation-param-weight-table

**Comment by soham24** [comment]
I am using mtcnn model in which 
input param has this order 
20 22
Input            data             0 1 data 0=3 1=48 2=48
