### ISSUE TITLE
不同显卡运行结果不一致

### ISSUE THREAD

**Issue by Lin427** [Tencent/ncnn#994]
在win10系统，显卡：TITAN X ，gpu和cpu运行结果一致，差异在0.001左右
在win10系统，显卡：1080 ，gpu和cpu运行结果不一致，差异在0.5左右
这是因为显卡问题导致的吗？如何克服这个问题？谢谢！

**Comment by veepersgit** [comment]
遇到同样的问题：所提取的特征值，1070显卡与CPU运行结果一致，嵌入式TX2与CPU运行结果不一致

**Comment by Lin427** [comment]
问题已解决。
解决方法：
在gpu.cp中，将686行gpu_info.support_fp16_storage= 更改为：gpu_info.support_fp16_storage = false;
将690行gpu_info.support_fp16_arithmetic =更改为：gpu_info.support_fp16_arithmetic = false;
通过改变这两个地方可以使GPU1080 和CPU的结果达到差异0.001左右。
