### ISSUE TITLE
ncnn convolution no padding result error

### ISSUE THREAD

**Issue by jackcc** [Tencent/ncnn#996]
ncnn-20190320 release版本
3x3的卷积，没有padding，stride为2,；
ncnn得到的结果与caffe得到的结果在边界处不一样，其他位置是一样；
已经验证过，如果加入padding，结果是一致的。

**Comment by nihui** [comment]
fixed in https://github.com/Tencent/ncnn/commit/c4b84262d99d11b2e62661268b862dcecf151634
