### ISSUE TITLE
Squeezenet_v1.1.bin weight buffer存放问题

### ISSUE THREAD

**Issue by Kikou1998** [Tencent/ncnn#998]
试图手动提取Squeezenet_v1.1.bin 里的weight，
然后根据.param文件提供的参数自己先算了下第一个convolution的weight buffer所占的大小
 = 1728 * 4 = 6912 bytes + flag = 6916 bytes 
     然后自己hex dump了一下 .bin文件，
发现第二个weight buffer(第二个0000 0000开始的位置)开始于第7172个byte之后，
请问中间的256个bytes是用来存放什么数据的？

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/wiki/param-and-model-file-structure
https://github.com/Tencent/ncnn/wiki/operation-param-weight-table
参考一下
