### ISSUE TITLE
nano 使用 vulkan 加载模型core dumped

### ISSUE THREAD

**Issue by stupidchenchen** [Tencent/ncnn#999]
up 主 
加载model PriorBox 类型的层 跑到 cmd.record_upload() 这里崩溃了
![image](https://user-images.githubusercontent.com/26602552/58071756-37bc1d80-7bd0-11e9-8617-4fc0bb8fd8c1.png)

**Comment by nihui** [comment]
aspect_ratios 为空？

**Comment by nihui** [comment]
请使用最新的代码测试下，如果还有问题可以 reopen issue 反馈
